### ISSUE TITLE
OpenWrt 编译：直连/代理/屏蔽列表失效

### ISSUE THREAD

**Issue by Neurotoxin0** [xiaorouji/openwrt-package#1452]
OpenWrt 编译：直连/代理/屏蔽列表失效

貌似连分流规则都不生效

**Comment by sy19890515** [comment]
我也是，之前反馈了，说清dns缓存，但是不知道怎么清……

**Comment by handsomeji** [comment]
如果你是因为使用了 第三方DNS 导致的无法使用 均无法解决
直连/代理/屏蔽列表是使用dnsmasq的，如果你使用其他DNS重定向了肯定是无法使用的.

**Comment by sy19890515** [comment]
> 如果你是因为使用了 第三方DNS 导致的无法使用 均无法解决
> 直连/代理/屏蔽列表是使用dnsmasq的，如果你使用其他DNS重定向了肯定是无法使用的.

第三方DNS指哪些？我是指定的8.8.8.8和8.8.4.4

**Comment by Neurotoxin0** [comment]
怪不得。。我ADG代替了dnsmasq

**Comment by sy19890515** [comment]
> 如果你是因为使用了 第三方DNS 导致的无法使用 均无法解决
> 直连/代理/屏蔽列表是使用dnsmasq的，如果你使用其他DNS重定向了肯定是无法使用的.

请问要怎么检查啊

**Comment by sy19890515** [comment]
我目前只在passwall的基本设置页里的DNS页里选择了“远程DNS”为8.8.8.8，wan口的dns服务器本来是勾的“使用对端通告的 DNS 服务器”，当时有这个问题，于是我改成了指定8.8.8.8，8.8.4.4，还是不行……

**Comment by handsomeji** [comment]
> 怪不得。。我ADG代替了dnsmasq

这种情况ADG上游可以设置127.0.0.1即可解决

**Comment by Neurotoxin0** [comment]
> > 怪不得。。我ADG代替了dnsmasq
> 
> 这种情况ADG上游可以设置127.0.0.1即可解决

问一下，是只要加入127.0.0.1就行了还是说上游只能有127.0.0.1
因为同时用了加入GFW到上游

**Comment by hrokilshi** [comment]
> 如果你是因为使用了 第三方DNS 导致的无法使用 均无法解决
> 直连/代理/屏蔽列表是使用dnsmasq的，如果你使用其他DNS重定向了肯定是无法使用的.

即使用dnsmasq也是不行，各种尝试都失败。

**Comment by yunxi993** [comment]
> 如果你是因为使用了 第三方DNS 导致的无法使用 均无法解决
> 直连/代理/屏蔽列表是使用dnsmasq的，如果你使用其他DNS重定向了肯定是无法使用的.

话说，自定义DNS(UDP)与通过UDP节点请求DNS是一个意思吗？都是通过UDP节点请求DNS

**Comment by handsomeji** [comment]
> > > 怪不得。。我ADG代替了dnsmasq
> > 
> > 
> > 这种情况ADG上游可以设置127.0.0.1即可解决
> 
> 问一下，是只要加入127.0.0.1就行了还是说上游只能有127.0.0.1
> 因为同时用了加入GFW到上游

方案1：dnsmasq继续用53端口，ADG非53端口选择重定向模式，ADG上游只填127.0.0.1
方案2：dnsmasq使用非53端口，ADG使用53端口，ADG上游只填写dnsmasq的服务
因为passwall必须依赖于dnsmasq作为ipset分流，也就是说，无论如何都必须经过dnsmasq。
`因为同时用了加入GFW到上游` 这个不要

**Comment by Neurotoxin0** [comment]
> > > > 怪不得。。我ADG代替了dnsmasq
> > > 
> > > 
> > > 这种情况ADG上游可以设置127.0.0.1即可解决
> > 
> > 
> > 问一下，是只要加入127.0.0.1就行了还是说上游只能有127.0.0.1
> > 因为同时用了加入GFW到上游
> 
> 方案1：dnsmasq继续用53端口，ADG非53端口选择重定向模式，ADG上游只填127.0.0.1
> 方案2：dnsmasq使用非53端口，ADG使用53端口，ADG上游只填写dnsmasq的服务
> 因为passwall必须依赖于dnsmasq作为ipset分流，也就是说，无论如何都必须经过dnsmasq。
> `因为同时用了加入GFW到上游` 这个不要

那能不能用 ADG作为dnsmasq上游，这样既用到了masq也用到了adg的DOH和分流=
