### ISSUE TITLE
求大佬给xray grpc加个multi选项

### ISSUE THREAD

**Issue by wizxy** [xiaorouji/openwrt-package#1457]
![QQ图片20210918112413](https://user-images.githubusercontent.com/75599967/133870972-182c5b2d-c9f1-4b5c-acf1-0651c7538a09.jpg)

听说multi模式速度快百分之20，性能更好，哈哈

**Comment by handsomeji** [comment]
有空再说

**Comment by zxlhhyccc** [comment]
> ![QQ图片20210918112413](https://user-images.githubusercontent.com/75599967/133870972-182c5b2d-c9f1-4b5c-acf1-0651c7538a09.jpg)
> 
> 听说muti模式速度快百分之20，性能更好，哈哈

你这个不是加上去了吗？直接提pr不就行了。。。。

**Comment by handsomeji** [comment]
最新源码已加入，请自行测试

**Comment by jh0072110** [comment]
手贱测试了一下，那个multi真的是…卡到没边了……
Update：第二次测试又变得挺快…玄学啊我C……

**Comment by handsomeji** [comment]
感觉主要还是看线路
close.
