### ISSUE TITLE
9月25日编译版本，自动订阅后，原来的负载均衡节点信息异常

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-package#1465]
![image](https://user-images.githubusercontent.com/34025388/134832309-cd56d706-023b-48a2-a870-cb261e4397a9.png)
![image](https://user-images.githubusercontent.com/34025388/134779388-fa52a47a-b344-4c87-a4ba-33d56431341c.png)
 如上图，原来是正常的并且负载均衡运行了，点击订阅后就变成了这样，并且负载均衡无法启动

**Comment by handsomeji** [comment]
重置重新配置

**Comment by WYC-2020** [comment]
@xiaorouji 我就是全新配置的，也是这样，我等下再试下吧，目前是只要开启负载均衡，然后更新订阅都会失效

**Comment by WYC-2020** [comment]
@xiaorouji 验证完毕，确实有我说的那个问题，全新配置先配置订阅节点，然后更新更新节点，然后再配置负载均衡，比如负载均衡增加两个节点，然后再去点击订阅节点更新一下节点 此时负载均衡的配置就会变成一堆乱码，此时再把乱码的在配置一边，在更新居然不乱码了，如果此时再到负载均衡中在增加几个节点在更新，新增加的都会乱码，必须按上面步骤在配置一遍这样就不会了，现在我是重复多次配置才没乱码了，大佬有时间看下吧，谢谢

**Comment by Davyliu021** [comment]
我也遇到同样问题！

**Comment by WYC-2020** [comment]
看以前好像就有人遇到这个问题，他说的是这样解决
![image](https://user-images.githubusercontent.com/34025388/134844586-cceab479-421d-4c7c-8990-89192173b5a8.png)
就是添加负载均衡的节点后，不要把他置顶一直放最后，说可以，没试过 有试过的可以去试试

**Comment by handsomeji** [comment]
大概找到原因是，只能说op官方的cfgid恶心，下个版本修正一下，其实不算BUG。

**Comment by WYC-2020** [comment]
@xiaorouji 大佬牛逼

**Comment by handsomeji** [comment]
@WYC-2020 试试4.36

**Comment by WYC-2020** [comment]
@xiaorouji 好的，还没更新等会中午试下

**Comment by WYC-2020** [comment]
@xiaorouji 测试了一下更新乱码问题解决了，不过我这里建议一下，如果更新订阅后，节点丢失了，可以自动选择已有的节点顶替，或者节点订阅没有节点还是维持原来的节点不动，这样最起码保证不会出现乱码，如果第二次更新没有上次的节点还是会乱码
