### ISSUE TITLE
群晖7.0无法正常使用docker跑passwall

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-package#1467]
群晖内核是4.4.180+
按照/etc/init.d/passwall启动脚本排查，
初步判断是/usr/share/passwall/iptables start里面有命令执行错误，导致无法正常加载防火墙规则，手动尝试目前发前ipset命令会报错。
命令：ipset -! create laniplist nethash maxelem 1048576
报错：ipset v7.6: Kernel error received: set type not supported

查询dns因为在NAT表的OUTPUT→PSW_OUTPUT，第一条规则就redirect到1041的监听端口了，所以DNS可以正常查询，但是其它所有规则pw均无法正常使用防火墙，导致google等tcp连接均无法访问。

同时使用N1的armbian的docker跑op+pw，一切正常，N1内核*5.3.0。

**Comment by badgv** [comment]
目前在群晖的docker版本的op启动后，使用ipset list命令，一个列表都没有，是空的。

**Comment by xiaorouji** [comment]
既然有能力排查，为什么不理解那段意思呢？

**Comment by badgv** [comment]
> 既然有能力排查，为什么不理解那段意思呢？

看样子是群晖的内核本身就不支持ipset的原因导致的问题了，来发贴主要是想看下有没有什么解决办法

**Comment by handsomeji** [comment]
docker特权模式开了吗？

**Comment by badgv** [comment]
> docker特权模式开了吗？

开了的，启动命令是docker run --name openwrt -d --privileged --restart unless-stopped --network opnet .....，用的macvlan网络
我试了下ipset create TEST hash:ip,可以建一个TEST的ipset list，但是上面那个命令就不行，是不是nethash这个type不支持的原因？

**Comment by badgv** [comment]
尝试把nethash改成hash:ip，部分nat规则能正确生成，路由自身能实现走代理，但是部分规则还是没有，估计是iptables模块不全导致的，放弃了...看样子群晖用docker跑op基本没戏

**Comment by xiaorouji** [comment]
虚拟机

**Comment by cndanili** [comment]
6.X尝试加载insmod /lib/modules/xt_comment.ko 以及相同目录下的xt_socket.ko后成功。

**Comment by badgv** [comment]
> 6.X尝试加载insmod /lib/modules/xt_comment.ko 以及相同目录下的xt_socket.ko后成功。

加载了ipset能用吗？

**Comment by merlinus2019** [comment]
看了这个帖子的思路后，我终于找到了大神的解决方案。
原来的确是群晖系统的内核被阉割了，下载内核补丁后，insmod加载补丁，
docker+openwrt+Passwall瞬间就全部正常了！
群晖玩docker有问题的，都去这里看看呀
https://github.com/sjtuross/syno-iptables

**Comment by merlinus2019** [comment]
> > 6.X尝试加载insmod /lib/modules/xt_comment.ko 以及相同目录下的xt_socket.ko后成功。
> 
> 加载了ipset能用吗？

加载了mod就完全可以用了，在dock里面一看就知道

**Comment by badgv** [comment]
> 看了这个帖子的思路后，我终于找到了大神的解决方案。 原来的确是群晖系统的内核被阉割了，下载内核补丁后，insmod加载补丁， docker+openwrt+Passwall瞬间就全部正常了！ 群晖玩docker有问题的，都去这里看看呀 https://github.com/sjtuross/syno-iptables

居然有现成的模块可以用，点个赞:)

**Comment by 0x5e** [comment]
s905l3a盒子，装了armbian + docker + openwrt跑passwall同样有问题，不知道要装哪个补丁，后来发现代理模式「GFW列表」不生效，改成「中国列表以外」就可以用了。。

**Comment by taxtigerno1** [comment]
> s905l3a盒子，装了armbian + docker + openwrt跑passwall同样有问题，不知道要装哪个补丁，后来发现代理模式「GFW列表」不生效，改成「中国列表以外」就可以用了。。

兄弟，我的模式是跟你一模一样，也是s905l3a盒子，然后安装了armbian+docker+openwrt，然后安装passwall v4.73-3，但是发现passwall不能科学上网，确信节点连接（使用过vless+vison+reality和hy2，这些节点在v2rayn正常使用没有问题）设置没有问题，因为那个连接我是在正常使用的v2rayn导出来的。我像你说的改为“中国列表以外”还是不行。请问后面你怎么解决。我使用s905l3a直接安装（不通过docker安装）v2raya工具代理上网却没有问题（但是这个v2raya这个工具不能代理hy2协议）。
