### ISSUE TITLE
【需求】订阅更新后按关键字筛选节点列表并创建负载均衡节点

### ISSUE THREAD

**Issue by Miroxyz** [xiaorouji/openwrt-package#1469]
有同一机场的多个订阅，但是每个订阅流量都比较少。想把不同订阅的同节点合并在一起，作为一个负载均衡节点。

例如A、B订阅均有以下节点：
Lv1HKxxx
Lv1USxxx

通过设置两个关键字`HK`和`US`，将A、B订阅的`HK`和`US`节点设置成两个负载均衡节点。

求大佬实现这样的功能。

**Comment by WYC-2020** [comment]
这玩意还是自己配置合理

**Comment by handsomeji** [comment]
动下手吧 不要太过于依赖

**Comment by Miroxyz** [comment]
暂时在`/usr/share/passwall/subscribe.lua`的`update_node`方法的`uci:commit(appname)`前黑科技了一段逻辑实现了：）
