### ISSUE TITLE
您好，coolsnowwolf/lede和Lienol/openwrt加入passwall有报错

### ISSUE THREAD

**Issue by 281677160** [xiaorouji/openwrt-package#1474]
您好，coolsnowwolf/lede和Lienol/openwrt的19.07源码加入passwall有报错
请问要怎么解决啊？
![QQ截图20211002095439](https://user-images.githubusercontent.com/66651997/135700322-bf8df0b3-29de-46e3-b3c1-4eaf0cee2f8f.png)

**Comment by microdockman** [comment]
> 您好，coolsnowwolf/lede和Lienol/openwrt的19.07源码加入passwall有报错 请问要怎么解决啊？ ![QQ截图20211002095439](https://user-images.githubusercontent.com/66651997/135700322-bf8df0b3-29de-46e3-b3c1-4eaf0cee2f8f.png)

如果源码文件夹根目录有staging_dir/host/bin/upx ,能编译出来，但是也会提示这个。

**Comment by 281677160** [comment]
哦，好的，感谢回复，我没测试能不能编译，我看到这个情况，我直接拉取仓库没修改这个之前的源码编译了，没报错，编译也没问题
![QQ截图20211002103522](https://user-images.githubusercontent.com/66651997/135709001-0ebefdcc-78a1-4e69-a53c-b70636ee33fe.png)

**Comment by imy7** [comment]
编译没有错误,但是make info里面仍然报错,估计是内核的问题吧!

**Comment by microdockman** [comment]
趁问题开，想请问老哥们又没有碰到一段时间需要重启wan口（因为国内网站访问不了，国外网站正常的情况。）以为是dns问题，改了passwall的几种过滤模式，其他不动（没有自定义dns,wan口dhcp获取链接的硬路由lan口，设置无改动，lan口无自定义dns无改动），一段时间问题照旧。存储没满35%，openwrt防火墙无改动，也不是windows问题，（用linux ping国内网站地址不通，重启wan口后恢复正常），版本是官方master （kernel 5.4.142） 加passwall（版本？8九月）。以前倒是没有碰到这些情况，硬件问题的话国外网站应该也会访问不了。。

**Comment by microdockman** [comment]
> 趁问题开，想请问老哥们又没有碰到一段时间需要重启wan口（因为国内网站访问不了，国外网站正常的情况。）以为是dns问题，改了passwall的几种过滤模式，其他不动（没有自定义dns,wan口dhcp获取链接的硬路由lan口，设置无改动，lan口无自定义dns无改动），一段时间问题照旧。存储没满35%，openwrt防火墙无改动，也不是windows问题，（用linux ping国内网站地址不通，重启wan口后恢复正常），版本是官方master （kernel 5.4.142） 加passwall（版本？8九月）。以前倒是没有碰到这些情况，硬件问题的话国外网站应该也会访问不了。。

wan口自定义了几个dns,暂时没需要重启wan口了，看来是设置不通

**Comment by handsomeji** [comment]
@dianlujitao

**Comment by moetayuko** [comment]
Warning应该不会有实质性负面影响

**Comment by xtwz** [comment]
我也遇到这个问题，
