### ISSUE TITLE
Github和Instagram测试连接会重复请求

### ISSUE THREAD

**Issue by costcopy** [xiaorouji/openwrt-package#1475]
dns设置为adguard home端口：127.0.0.1#xx 
测试Github和Instagram连接 特别慢 dns请求里发现Github连续请求了两次 Instagram请求了三次 很怀疑是不是重复请求导致测试连接的时间变长了

![A81CBFC9-80C0-460D-A48E-B3C0B202352F](https://user-images.githubusercontent.com/14955364/135702449-4f4186f6-b086-4249-b1ed-942896c91446.jpeg)

![20A24969-F6E1-4E74-9524-20737B109C86](https://user-images.githubusercontent.com/14955364/135702504-5829c629-b1b1-409a-acc5-811be06395e0.jpeg)

**Comment by handsomeji** [comment]
可能是 http重定向https了
