### ISSUE TITLE
UPX/HOST

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-package#1479]
![image](https://user-images.githubusercontent.com/59167936/135878081-f99c7c2a-6914-4188-aa1b-1191cb2522ae.png)

**Comment by yubanmeiqin9048** [comment]
同样的问题

**Comment by e703** [comment]
同样的问题，貌似不影响编译。

编译环境 UBUNTU 21.04 LTS 

[
![2021-10-06_17-04-46](https://user-images.githubusercontent.com/61598472/136174039-e5ef3543-29ac-4784-b78e-dc4a49b3818e.png)
](url)

**Comment by WYC-2020** [comment]
@yunxi993 严重洁癖的吧那个增加这个依赖的commit给撤销了
