### ISSUE TITLE
请问dns2socks是否是必要组件

### ISSUE THREAD

**Issue by hplee0120** [xiaorouji/openwrt-package#1480]
之前在编译中是提供可选的，现在已经无选项且默认选中编译进去了。请问是否是有改动默认变成必要组件了或者是Makefile中忘记添加选项了。

**Comment by skylanderno1** [comment]
是必要组件，dns过滤模式中有一个模式用到了dns2socks，默认的是pdnsd。

**Comment by hplee0120** [comment]
> 是必要组件，dns过滤模式中有一个模式用到了dns2socks，默认的是pdnsd。

那就不是必要组件吧，我之前一直没有勾选这个的，我一直用的xray的doh功能。现在没有那个选项了，默认也编译进去。

**Comment by handsomeji** [comment]
目前必要，给访问控制用。除非你不需要用到访问控制用不同的节点就不需要。

**Comment by hplee0120** [comment]
> 目前必要，给访问控制用。除非你不需要用到访问控制用不同的节点就不需要。

了解了。
