### ISSUE TITLE
只启动一个v2ray/xray实例

### ISSUE THREAD

**Issue by moetayuko** [xiaorouji/openwrt-package#1481]
目前TCP, UDP, dns分别会启动单独的v2ray/xray实例，在内存不大的硬路由上会影响性能甚至触发oom kill，但实际上一个v2ray/xray实例是可以同时完成上述任务的

**Comment by WYC-2020** [comment]
单独有单独的好处，稳定好，一个挂了不会影响另外一个

**Comment by moetayuko** [comment]
> 单独有单独的好处，稳定好，一个挂了不会影响另外一个

软路由当然不差这点，128M内存的硬路由就捉急了。v2ray程序本身不存在稳定性问题，但多个instance带来的oom kill反而产生了稳定性问题。

**Comment by WYC-2020** [comment]
只有128m，额太可怜了
