### ISSUE TITLE
新版本无法订阅节点

### ISSUE THREAD

**Issue by cheungws01** [xiaorouji/openwrt-package#1482]
X86，OpenWRT，上海电信，光猫桥接。
使用passwall 4.36-1版本无法订阅某个机场的订阅链接。
直接订阅和挂代理订阅都不行。
测试旧版本可以，其他机场订阅链接可以。

**Comment by tianiue** [comment]
4-32版可以
![屏幕截图 2021-10-06 181112](https://user-images.githubusercontent.com/61725402/136197634-b8c47190-7480-4f35-8c68-2bc61ebde086.png)
后面的版本都这样，今天编译的最新版未修复
![屏幕截图 2021-10-06 175514](https://user-images.githubusercontent.com/61725402/136197740-91af7c31-55be-41b3-9d89-f265febf7445.png)
主要是v2节点出现，ss正常

**Comment by cheungws01** [comment]
![image](https://user-images.githubusercontent.com/91939437/136223772-3c98767c-ae8b-407b-b325-453d51e18725.png)
我的某个机场不管是v2ray/ss都不行，别的机场就可以，或者退回到旧版本也没问题，就特别神奇

**Comment by handsomeji** [comment]
订阅链接不发我又如何测试复现呢？

**Comment by tianiue** [comment]
网络环境相同，固件相同，电脑安装就可以，软路订阅了就不显示出来，怎么可以抓取这块日志

**Comment by handsomeji** [comment]
估计你固件保留配置导致，与源码无关，close了

**Comment by tianiue** [comment]
> 估计你固件保留配置导致，与源码无关，close了

每次我都是重装的，重新设置，没有还原
