### ISSUE TITLE
一个Socks5的BUG，导致tcp无法启动

### ISSUE THREAD

**Issue by pidou122** [xiaorouji/openwrt-package#1484]
使用的是最新版的passwall，发现一个bug，socks5节点地址如果使用的是域名地址，那么tcp将无法正常启动。如果socks5节点地址使用的是ip地址，那么tcp是可以正常启动的。测试下来，目前发现这个bug，还请老大修复。

**Comment by handsomeji** [comment]
最新源码已优化。
