### ISSUE TITLE
最新版，订阅问题还是存在

### ISSUE THREAD

**Issue by tianiue** [xiaorouji/openwrt-package#1488]
![屏幕截图 2021-10-09 191701](https://user-images.githubusercontent.com/61725402/136655950-c44e42b3-f1cb-47e3-8562-181c58d75bde.png)
![屏幕截图 2021-10-09 191735](https://user-images.githubusercontent.com/61725402/136655955-2dfca5b0-9dd9-4af1-a8c4-4e80a02ecb39.png)
![屏幕截图 2021-10-09 191836](https://user-images.githubusercontent.com/61725402/136655961-895179cc-32bb-42d6-9f23-3e136b526c55.png)
希望能帮助找到问题，谢谢

**Comment by tianiue** [comment]
![屏幕截图 2021-10-09 195604](https://user-images.githubusercontent.com/61725402/136656919-0a453799-44cd-4939-a3c5-9c986c8ab0df.png)
![屏幕截图 2021-10-09 195544](https://user-images.githubusercontent.com/61725402/136656923-a25f9e16-3d09-4989-aa7e-4b7667cb65f8.png)
最新版，在5.4内核可以订阅，应该和5.10内核存在兼容性

**Comment by tianiue** [comment]
![屏幕截图 2021-10-10 003740](https://user-images.githubusercontent.com/61725402/136666969-39c87744-8b6e-4e2f-9f0e-85506bcd1417.png)
![屏幕截图 2021-10-10 003647](https://user-images.githubusercontent.com/61725402/136666978-b4e19fb7-fe0f-4084-a6a0-d86de58e932b.png)
4-38版，在内核5.10，还是不能订阅成功

**Comment by handsomeji** [comment]
你可以勾选 通过代理订阅 试试

**Comment by tianiue** [comment]
> 你可以勾选 通过代理订阅 试试
![QQ截图20211016165409](https://user-images.githubusercontent.com/61725402/137581242-f6621188-934a-41c4-a1bc-d65a426d3d88.png)
![QQ截图20211016165424](https://user-images.githubusercontent.com/61725402/137581245-d5f092aa-bbe6-46d1-a1f3-2cb0ad1b2cfb.png)
使用代理还是一样，在今天的5.10，还是出现订阅失败

**Comment by handsomeji** [comment]
固件问题

**Comment by handsomeji** [comment]
自己用curl看看吧
