### ISSUE TITLE
upx/host error

### ISSUE THREAD

**Issue by kokenot** [xiaorouji/openwrt-package#1491]
how to solve this? i'm using lede source

Collecting package info: done
WARNING: Makefile 'package/lean/openwrt-passwall/brook/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/hysteria/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/trojan-go/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/v2ray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/v2ray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/xray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/lean/openwrt-passwall/xray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist

**Comment by lxhao61** [comment]
一样报错，不影响成功编译。
此问题是 https://github.com/xiaorouji/openwrt-passwall/commit/68278f4448191c8d89a3dbb3b096257b02dfe8ae 引入的。

**Comment by kokenot** [comment]
tqvm. i just ignore the error.
