### ISSUE TITLE
Xray分流总节点总是重置默认分流

### ISSUE THREAD

**Issue by jinhill** [xiaorouji/openwrt-package#1492]
OpenWrt x64 21.02.0，luci-app-passwall_4.34
TCP节点Xray分流总节点设置默认分流走代理，路由器poweroff后断电，然后再上电启动默认分流被重置为直连。可以复现，但不是每次都出现这样的情况。/etc/config/passwall中default_node被修改。

**Comment by handsomeji** [comment]
用最新版再试，不保存配置

**Comment by jinhill** [comment]
@xiaorouji 我昨天新编译的v4.40,问题仍然存在，我检查了只有passwall的配置被重置了，其他的服务配置都是正常的。有点奇怪，我猜想passwall在停止服务时会写配置文件吗？

**Comment by ZqinKing** [comment]
> @xiaorouji 我昨天新编译的v4.40,问题仍然存在，我检查了只有passwall的配置被重置了，其他的服务配置都是正常的。有点奇怪，我猜想passwall在停止服务时会写配置文件吗？

可能是passwall的配置文件在/tmp目录下。部分硬路由的rom有限/tmp路径是ram开机的时候挂载上去的。关机了信息就没有了。

**Comment by jinhill** [comment]
@ZqinKing 感谢回复，我的是软路由硬盘空间足够，我检查了文件路径在/etc/config下， 这个目录下的其他配置都正常，就是passwall总是被重置，太诡异了。
