### ISSUE TITLE
Passwall 的“Xray 分流”，默认 AD 为“直连”，导致无法打开 Google 等网站

### ISSUE THREAD

**Issue by sky2016cn** [xiaorouji/openwrt-package#1494]
Passwall 的“Xray 分流”，默认 AD 为“直连”，导致无法打开 Google 等网站，建议把 AD 默认为“关闭”

**Comment by kang1ting** [comment]
> Passwall 的“Xray 分流”，默认 AD 为“直连”，导致无法打开 Google 等网站，建议把 AD 默认为“关闭”

同样的问题，怎么操作?

**Comment by sky2016cn** [comment]
设置分流的时候，把AD默认直连改为关闭，就可以了
