### ISSUE TITLE
brook的编译过程中upx压缩没有去掉

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-package#1495]
日志如下

/LEDE_IMG/openwrt-psw/staging_dir/target-x86_64_musl/usr/share/gocode/src does not exist, skipping symlinks

touch /LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.configured_714e0dfdd6e56a07ea297aadc7dec878
rm -f /LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.built
touch /LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/LEDE_IMG/openwrt-psw/tmp/go-build" GO_MOD_CACHE_DIR="/LEDE_IMG/openwrt-psw/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/txthinking/brook" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/txthinking/brook/cli/brook" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701" GO_BUILD_DIR="/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.go_work/build" GO_BUILD_BIN_DIR="/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/LEDE_IMG/openwrt-psw/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOARM="" GOMIPS="" GOMIPS64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701=brook-20210701 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701=brook-20210701 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -znow -zrelro" GOPATH="/LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.go_work/build" GOCACHE="/LEDE_IMG/openwrt-psw/tmp/go-build" GOMODCACHE="/LEDE_IMG/openwrt-psw/dl/go-mod-cache" GOENV=off /usr/bin/env bash /LEDE_IMG/openwrt-psw/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1634158545' -linkmode external -extldflags '-L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w  -buildid '1634158545' -linkmode external -extldflags '-L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE_IMG/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets

/LEDE_IMG/openwrt-psw/staging_dir/host/bin/upx --lzma --best /LEDE_IMG/openwrt-psw/build_dir/target-x86_64_musl/brook-20210701/.go_work/build/bin/brook
make[3]: Leaving directory '/LEDE_IMG/openwrt-psw/feeds/diy1/brook'
time: package/feeds/diy1/brook/compile#32.40#4.93#24.64
    ERROR: package/feeds/diy1/brook failed to build.
make[2]: Leaving directory '/LEDE_IMG/openwrt-psw'
make[1]: Leaving directory '/LEDE_IMG/openwrt-psw'

**Comment by handsomeji** [comment]
/usr/share/gocode/src does not exist, skipping symlinks

**Comment by eslamsesa** [comment]
home/eslam/Downloads/openwrt-21.02.0/staging_dir/host/bin/upx --lzma --best /home/eslam/Downloads/openwrt-21.02.0/build_dir/target-mips_24kc_musl/brook-20210701/.go_work/build/bin/linux_mips/brook
bash: /home/eslam/Downloads/openwrt-21.02.0/staging_dir/host/bin/upx: No such file or directory
make[3]: *** [Makefile:78: /home/eslam/Downloads/openwrt-21.02.0/build_dir/target-mips_24kc_musl/brook-20210701/.built] Error 127
make[3]: Leaving directory '/home/eslam/Downloads/openwrt-21.02.0/feeds/passwall/brook'
time: package/feeds/passwall/brook/compile#1.18#0.37#1.00
    ERROR: package/feeds/passwall/brook failed to build.
make[2]: *** [package/Makefile:114: package/feeds/passwall/brook/compile] Error 1
make[2]: Leaving directory '/home/eslam/Downloads/openwrt-21.02.0'
make[1]: *** [package/Makefile:108: /home/eslam/Downloads/openwrt-21.02.0/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/eslam/Downloads/openwrt-21.02.0'
make: *** [/home/eslam/Downloads/openwrt-21.02.0/include/toplevel.mk:230: world] Error 2
eslam@eslam-VirtualBox:~/Downloads/openwrt-21.02.0$
