### ISSUE TITLE
TCP&UDP 默认代理模式采用“防火墙表”无法翻墙

### ISSUE THREAD

**Issue by csco11298754** [xiaorouji/openwrt-package#1497]
防火墙域名列表(gfwlist)更新URL正常，测试过其它编译的固件可以正常使用，用这个固件TCP&UDP 默认代理模式采用“防火墙表”无法翻墙。

**Comment by jh0072110** [comment]
这个固件是哪个固件…

**Comment by csco11298754** [comment]
> 这个固件是哪个固件…

<html>
<body>


passwallOpenWrt by Lienol v2021.10.12 / LuCI 17.01 Lienol (git-28bc3c3)
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by WYC-2020** [comment]
固件原因那就换固件哈哈
