### ISSUE TITLE
socks节点配置问题

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#1503]
我目前碰到的问题，主节点部分和socks配置部分，如果在socks配置部分，选择“与TCP节点相同”以外的选项，则NatTypeTester测试走socks节点不通，TCP可能是正常链接状态。如图：
![image](https://user-images.githubusercontent.com/31793080/137613422-cbad23cf-57b3-4ef2-844f-90aba3ffd20f.png)
![image](https://user-images.githubusercontent.com/31793080/137608565-5b71d894-71c9-4ca8-ad06-26510c42a825.png)
![image](https://user-images.githubusercontent.com/31793080/137613337-683a7118-b35d-42fa-9196-d812dd7ca562.png)
![image](https://user-images.githubusercontent.com/31793080/137613347-0ee398e6-4b02-410a-a828-44d087c972c2.png)
![image](https://user-images.githubusercontent.com/31793080/137620450-e305f363-3ff9-42e9-8a65-6d1016017c3e.png)
望作者看看，能否复现，此功能比较实用，socks节点下挂各种游戏跑对应节点。

**Comment by handsomeji** [comment]
试试用ss-libev版看看？

**Comment by handsomeji** [comment]
NatTypeTester用最新版看看？

**Comment by SakuraFallingMad** [comment]
按您的要求重新调整下选项，结果依然是这样，socks udp不通，如图：
图一，走主节点：
![image](https://user-images.githubusercontent.com/31793080/138047642-f9581b3d-5a6f-4bf5-b4b8-62f03d028b20.png)
图二，走socks节点：
![image](https://user-images.githubusercontent.com/31793080/138048460-5c31755c-bc6f-4c44-bdb3-da23bea4378f.png)
望知悉。

**Comment by SakuraFallingMad** [comment]
ss-rust不影响测试结果，如图：
![image](https://user-images.githubusercontent.com/31793080/138048212-56414575-ea49-49e3-a8b5-0cd6f24cce22.png)
![image](https://user-images.githubusercontent.com/31793080/138049003-2bd8a372-0c26-4a46-8ec2-70022a651c0a.png)

**Comment by handsomeji** [comment]
我测试是正常的

**Comment by SakuraFallingMad** [comment]
好滴，我重新用最新的源码编译的固件再排错下

**Comment by SakuraFallingMad** [comment]
最新源码已测试游戏正常使用感谢！

**Comment by 631122919** [comment]
想请问socks功能的作用是什么 什么情况下需要用到

**Comment by moorish168** [comment]
> 最新源码已测试游戏正常使用感谢！

请问大神解决了吗，最近也遇到了这个问题怎么联系，有偿

**Comment by Wallemuse** [comment]
@SakuraFallingMad 下面这个Socks配置那里是不是不能添加用户名和密码的？如果想要添加如何实现，不知道楼主是否可解答，谢谢。
