### ISSUE TITLE
support mwan3?

### ISSUE THREAD

**Issue by malikshi** [xiaorouji/openwrt-package#1505]
is there any future update to support mwan3? v2rayA fix/support mwan3 by fixing transparent proxy mark from mwan3 there the [reference](https://github.com/v2rayA/v2rayA/commit/27feca769ee109a984468ea1aad5e56d9919c083)
also, i tried to load balancing feature from passwall some interfaces not shown up in the list.
![image](https://user-images.githubusercontent.com/9080737/137683056-98a7c863-424e-4327-bf12-2935e07250fb.png)
I used wwan(wlan0) as WAN.

**Comment by handsomeji** [comment]
The next version will be optimized, but I don't have a multi-wan environment and cannot be tested.

**Comment by malikshi** [comment]
> The next version will be optimized, but I don't have a multi-wan environment and cannot be tested.

Thank you.

**Comment by handsomeji** [comment]
You can try the latest source code now.

**Comment by malikshi** [comment]
ok, let me compile first

**Comment by malikshi** [comment]
@xiaorouji fixed and all interfaces showed up.
![image](https://user-images.githubusercontent.com/9080737/138054681-8d80a3b4-330d-4ac9-8391-55f300421a26.png)
so the thing to do about `mwan3 mark` in transparent proxy, Xray/v2ray shunt would work if users set up luci-app-mwan3/mwan3.
i usually use v2rayA since they fixed transparent proxy mark mwan3 and openclash(TUN ONLY) that work along luci-app-mwan3/mwan3
![image](https://user-images.githubusercontent.com/9080737/138055614-80775aba-19e4-431a-8277-ca695f9d1e6d.png)
gain more speed e.g 2 WAN can be set 1+1=2.  hope passwall support it too

**Comment by handsomeji** [comment]
I don't have multi wan, so I can't test and complete it.

**Comment by malikshi** [comment]
thank you for the response, I hope you're considering this in the future if you got two WAN/ISP.
