### ISSUE TITLE
多虚拟机桥接方式,新版本passwall相互干扰,无法隔离控制

### ISSUE THREAD

**Issue by hh3270** [xiaorouji/openwrt-package#1518]
问题点: 
             创建2个虚拟机,通过桥接方式共用同一网口,分别设置不同局域网ip,2个虚拟机同时开通新的passwall (OpenWrt R21.10.1), 相互都 
             不能科学上网.同时只能激活一台,无法同时设置两条线路.
             测试不带xray的旧版本passwall(OpenWrt R20.7.1),可以同时设置不同路线,各虚拟机相互隔离,不干扰.

不同点分析:
             1.通过netstat 对比端口变化,新版是xray的进程,旧版本是v2ray 
              2.passwall的日志不同.具体如下:
旧版本
22:31:17: 清空并关闭相关程序和缓存完成。
22:31:18: SOCKS_1节点：node_xxx，节点：xxx:443，监听端口：1081
22:31:18: TCP_1节点：node_xxx，节点：xxx:443，监听端口：1041
22:31:18: UDP_1节点：node_xxx，节点：xxx:443，监听端口：1051
22:31:18: DNS：pdnsd + 使用TCP节点解析DNS（8.8.4.4）...
22:31:18: dnsmasq：生成配置文件。
22:31:18: 开始加载防火墙规则...
22:31:19: 开始过滤所有IPV4节点到白名单
22:31:19: 过滤所有IPV4节点完成
22:31:21: TCP默认代理模式：大陆白名单
22:31:21: UDP默认代理模式：大陆白名单
22:31:21: 防火墙规则加载完成！
22:31:22: 运行完成！

新版本
20:46:19: 删除相关防火墙规则完成。
20:46:21: 清空并关闭相关程序和缓存完成。
20:46:21: TCP节点：[xxx:443，监听端口：1041
20:46:21: -proto tcp
20:46:21: UDP节点：[xxx:443，监听端口：1051
20:46:21: 过滤服务配置：准备接管域名解析...
20:46:21:   + [0]Pdnsd (127.0.0.1:7913)...
20:46:21:   | - [0]上游DNS：8.8.4.4:53
20:46:21:   - 域名解析：pdnsd + 使用(TCP节点)解析域名...
20:46:21:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
20:46:22:   - [0]节点列表中的域名(vpsiplist)：192.168.1.1
20:46:22:   - [0]域名白名单(whitelist)：192.168.1.1
20:46:22:   - [0]代理域名表(blacklist)：127.0.0.1#7913
20:46:24:   - [0]防火墙域名表(gfwlist)：127.0.0.1#7913
20:46:24: 开始加载防火墙规则...
20:46:26: 加入负载均衡的节点到ipset[vpsiplist]直连完成
20:46:26: 加入所有节点到ipset[vpsiplist]直连完成
20:46:27: 加载路由器自身 TCP 代理...
20:46:27:   - [0]将上游 DNS 服务器 8.8.4.4:53 加入到路由器自身代理的 TCP 转发链
20:46:27: 加载路由器自身 UDP 代理...
20:46:27:   - [127]不代理 UDP 端口：80,443
20:46:27: TCP默认代理：使用TCP节点[xxx] [中国列表以外](REDIRECT:1041)代理所有端口
20:46:27: UDP默认代理：使用UDP节点[xxx] [中国列表以外](TPROXY:1051)代理除80,443外的所有端口
20:46:27: 防火墙规则加载完成！
20:46:27: 重启 dnsmasq 服务
20:46:28: 运行完成！

请各位大佬分析分析什么原因.

**Comment by Aukansh** [comment]
你们的用途稀奇古怪的，你还是用旧版本吧！搞来搞去那么麻烦还虚拟机1 虚拟机2

**Comment by smallprogram** [comment]
需求太奇葩。建议自己折腾把

**Comment by badgv** [comment]
这个是混杂模式下OP的通病，OP会在混杂口收到所有的数据包，不是发给自己的也会乱反馈，也不知道是OP本身的问题还是XRAY工作逻辑导致的问题。
