### ISSUE TITLE
能不能把 `手动订阅`（手动更新全部订阅） 这个按钮恢复啊？

### ISSUE THREAD

**Issue by se7enmuting** [xiaorouji/openwrt-package#1522]
能不能把 `手动订阅`（手动更新全部订阅） 这个按钮恢复啊？
发现改UI了，取消了上面的`手动订阅`，每个订阅有各自独立的 `手动订阅`了。
但是：像我这种有5,6个订阅的，有时想一下全部手动更新下订阅，现在只能每个都要单独点一次，而且每次还要等他刷完才能点下一个，好慢吗。。。
想一下，既然保留了`删除所有点阅节点`，当我点了这个之后，再要再手动更新下所有订阅，那再一个个点不是很费事吗。。。

**Comment by WYC-2020** [comment]
其实完全可以吧外面的自动更新和手动更新全部保留，如果有人在里面配置了某一个订阅单独的更新就以他自己的为准，如果没有 那就全部按最外面那个更新为准，这样既可以兼容以前的也新增了私有定制，只是可能逻辑稍微复杂哈哈，有的折腾大佬了

**Comment by handsomeji** [comment]
最新源码恢复了
