### ISSUE TITLE
最新passwall和内核5.10

### ISSUE THREAD

**Issue by BOBINIUNIU** [xiaorouji/openwrt-package#1533]
昨天心血来潮想编译个新版本玩玩，重新git clone了Lienol大佬的代码和最新passwall，没想到大佬把5.4内核删掉了，于是只能编5.10了。不保留配置刷了新固件后发现passwall无法开启dns过滤，开启则国内外都无法上。
环境：极简编译，passwall只选了xray (1.5)，同样的编译配置文件在5.4内核和4.36-1下工作正常，不知道是不是5.10的锅

**Comment by handsomeji** [comment]
日志？

**Comment by tritu** [comment]
passwall has been working on kernel 5.10 and latest 5.14 for a while...

**Comment by BOBINIUNIU** [comment]
> 日志？

我还原了系统，稍后重新刷一下再附上日志。

**Comment by BOBINIUNIU** [comment]
问题在于dnsmasq启动失败，大佬请看下日志。

passwall 日志
2021-11-02 14:26:14: 删除相关防火墙规则完成。
2021-11-02 14:26:16: 清空并关闭相关程序和缓存完成。
2021-11-02 14:26:16: TCP节点：xxxxxxxxx:443，监听端口：1041
2021-11-02 14:26:16:   - 域名解析 DNS Over HTTPS...
2021-11-02 14:26:16: UDP节点没有选择或为空，不代理UDP。
2021-11-02 14:26:16: 过滤服务配置：准备接管域名解析...
2021-11-02 14:26:16:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2021-11-02 14:26:16:   - [0]节点列表中的域名(vpsiplist)：222.246.129.80,59.51.78.210
2021-11-02 14:26:16:   - [0]域名白名单(whitelist)：222.246.129.80,59.51.78.210
2021-11-02 14:26:16:   - [0]代理域名表(blacklist)：127.0.0.1#7913
2021-11-02 14:26:17:   - [0]防火墙域名表(gfwlist)：127.0.0.1#7913
2021-11-02 14:26:17: 开始加载防火墙规则...
2021-11-02 14:26:17: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2021-11-02 14:26:17: 加入所有节点到ipset[vpsiplist]直连完成
2021-11-02 14:26:17: 加载路由器自身 TCP 代理...
2021-11-02 14:26:17:   - 启用 TPROXY 模式
2021-11-02 14:26:17:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2021-11-02 14:26:17: TCP默认代理：使用TCP节点xxxxxxxxxxx [防火墙列表](TPROXY:1041)代理所有端口
2021-11-02 14:26:17: 防火墙规则加载完成！
2021-11-02 14:26:20: 重启 dnsmasq 服务
2021-11-02 14:26:20: 运行完成！
----------------------------------------------------------------------------------
系统日志
Tue Nov  2 14:26:01 2021 daemon.err uhttpd[2725]: netstat: showing only processes with your user ID
Tue Nov  2 14:26:02 2021 cron.err crond[11140]: crond (busybox 1.34.1) started, log level 5
Tue Nov  2 14:26:02 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Nov  2 14:26:02 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Nov  2 14:26:02 2021 daemon.err odhcpd[2543]: Failed to send to ff02::1%lan@br-lan (Permission denied)
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: started, version 2.86 cachesize 150
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: DNS service limited to local subnets
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for test
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for local
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using nameserver 222.246.129.80#53
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using nameserver 59.51.78.210#53
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for test
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for local
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Tue Nov  2 14:26:04 2021 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Tue Nov  2 14:26:04 2021 cron.err crond[11463]: crond (busybox 1.34.1) started, log level 5
Tue Nov  2 14:26:14 2021 cron.err crond[11756]: crond (busybox 1.34.1) started, log level 5
Tue Nov  2 14:26:14 2021 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Tue Nov  2 14:26:14 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Nov  2 14:26:14 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: started, version 2.86 cachesize 150
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: DNS service limited to local subnets
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for test
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for local
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using nameserver 222.246.129.80#53
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using nameserver 59.51.78.210#53
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for test
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for local
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Tue Nov  2 14:26:16 2021 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Tue Nov  2 14:26:17 2021 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Tue Nov  2 14:26:18 2021 daemon.err odhcpd[2543]: Failed to send to ff02::1%lan@br-lan (Permission denied)
Tue Nov  2 14:26:20 2021 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
Tue Nov  2 14:26:20 2021 daemon.crit dnsmasq[1]: FAILED to start up
Tue Nov  2 14:26:20 2021 cron.err crond[12865]: crond (busybox 1.34.1) started, log level 5
Tue Nov  2 14:26:25 2021 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
Tue Nov  2 14:26:25 2021 daemon.crit dnsmasq[1]: FAILED to start up
Tue Nov  2 14:26:30 2021 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
Tue Nov  2 14:26:30 2021 daemon.crit dnsmasq[1]: FAILED to start up
Tue Nov  2 14:26:34 2021 daemon.err odhcpd[2543]: Failed to send to ff02::1%lan@br-lan (Permission denied)
Tue Nov  2 14:26:35 2021 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
Tue Nov  2 14:26:35 2021 daemon.crit dnsmasq[1]: FAILED to start up
Tue Nov  2 14:26:40 2021 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
Tue Nov  2 14:26:40 2021 daemon.crit dnsmasq[1]: FAILED to start up

**Comment by tritu** [comment]
something related to your IPv6 setting? I bet you enable the IPv6 but never assigned by upstream router?

**Comment by handsomeji** [comment]
/var/etc/dnsmasq-passwall.d
检查一下有没有这个目录

**Comment by BOBINIUNIU** [comment]
> something related to your IPv6 setting? I bet you enable the IPv6 but never assigned by upstream router?

all the IP 6 options has been disabled.

**Comment by BOBINIUNIU** [comment]
> /var/etc/dnsmasq-passwall.d 检查一下有没有这个目录

有的，目录权限是0755

**Comment by BOBINIUNIU** [comment]
> something related to your IPv6 setting? I bet you enable the IPv6 but never assigned by upstream router?

The router connected to modem as pppoe and IP6 disabled on modem settings as well.
This error (daemon.err odhcpd[2543]: Failed to send to ff02::1%lan@br-lan (Permission denied)) disappeared after disabled IP6 in the DHCP option

**Comment by xiaorouji** [comment]
刚用Lienol的源码编译了5.10，测试是正常的。

**Comment by handsomeji** [comment]
应该是 `procd-ujail` 导致

**Comment by handsomeji** [comment]
用最新源码试下

**Comment by BOBINIUNIU** [comment]
> 用最新源码试下

感谢回复，我重新编译测试一下再反馈

**Comment by pangfeng161** [comment]
不是源码问题,5.4 5.10都试过一样

**Comment by BOBINIUNIU** [comment]
> 用最新源码试下

经测试，4.42-1修复了这个问题，谢谢。
