### ISSUE TITLE
能不能自动把所有节点加入到自动切换节点中？

### ISSUE THREAD

**Issue by vpei** [xiaorouji/openwrt-package#1534]
能不能自动把所有节点加入到自动切换节点中？

**Comment by handsomeji** [comment]
必要性？一般用也就几个稳定的节点吧？
而且，自动切换界面里面不是可以通过关键字添加到备用节点？

**Comment by vpei** [comment]
TCP 备用节点的列表
这个不是需要手动一个个的添加么？是不是在这个列表中的，当主节点不能使用时，才使用这个？不在这个列表中的节点，可能切换到？
使用付费的节点比较稳定，可以手动设置下就行。如果是免费的节点，稳定性不好，不自动切换，容易上着上着就断网了。

**Comment by nantayo** [comment]
当你开启这个功能,并且添加了非空的"TCP 备用节点的列表"之后才能用.
自动切换的逻辑是,每隔一定的时间检查主节点的连通性,如果不正常,就从备用节点列表里按顺序检测连通性,并切换到第一个正常的节点.
虽然但是,研究自动切换我个人认为不如用它旁边的负载均衡更好.

**Comment by showme2005** [comment]
> 必要性？一般用也就几个稳定的节点吧？ 而且，自动切换界面里面不是可以通过关键字添加到备用节点？

有些小机场 便宜的那种.每隔一段时间会换地址 ...单一节点太累了..启用haproxy的话会好一点.自动走最快的路线..如果可以自动添加.并且过滤IP一样的..那就太完美了..不需要 每次都要更新节点.然后重新配置harproxy.

**Comment by vpei** [comment]
> > 必要性？一般用也就几个稳定的节点吧？ 而且，自动切换界面里面不是可以通过关键字添加到备用节点？
> 
> 有些小机场 便宜的那种.每隔一段时间会换地址 ...单一节点太累了..启用haproxy的话会好一点.自动走最快的路线..如果可以自动添加.并且过滤IP一样的..那就太完美了..不需要 每次都要更新节点.然后重新配置harproxy.

用Clash吧，自己设置负载均衡，可以轮流使用有效节点，能把免费机场发挥到极致。

**Comment by truelv** [comment]
同样有这个需求，免费节点每天都要重新订阅的，每次订阅完又得去设置一堆操作，一个个的试过去太麻烦了

**Comment by vpei** [comment]
> 同样有这个需求，免费节点每天都要重新订阅的，每次订阅完又得去设置一堆操作，一个个的试过去太麻烦了

如果有软路由，可以用docker安装clash，多安装几个Clash容器，分别定阅不同的链接，分配不同的端口，再做一个负载均衡的Clash配置，把本地的几个SOCK5定阅都加上去，这样可以稳定的，快速的下载。特别是用电报软件或多线程软件下载时，速度提升比较明显。
