### ISSUE TITLE
请问有没有什么类似抓包的工具能分辨什么流量走了节点

### ISSUE THREAD

**Issue by sy19890515** [xiaorouji/openwrt-package#1538]
有些网站上的图片不翻墙也能加载，就是慢，开全局模式以后比较快，但把网站和图片域名都加到代理域名中再开gfw模式后，跟不翻墙一样慢

请问有没有什么类似抓包的工具可以让我看到哪些访问是走节点哪些访问没走节点的？我试过用tcpdump但似乎是所有访问都抓到了，无法判断到底有没有走节点

**Comment by handsomeji** [comment]
http代理
socks代理

**Comment by sy19890515** [comment]
> http代理 socks代理

这两个是在哪里看？
另外我发现虽然google.com能打开，但是google.ca（谷歌加拿大）和patents.google.com（谷歌专利）打不开，把这两个放到代理域名中后，一开始也打不开，狂刷新十几次以后可能就能打开了（有时候还是打不开，要再狂刷新）

**Comment by handsomeji** [comment]
透明代理环境下，dns是有缓存的。不会马上生效

**Comment by sy19890515** [comment]
> 透明代理环境下，dns是有缓存的。不会马上生效

原来如此……但有时候真的狂刷无数次都还是打不开，很难受，用PC开v2rayN连同一节点就没问题，每次出现这样的现象我都试过，不是节点的问题，于是就挺麻烦的……急着用的时候就只能继续在PC上翻墙……

**Comment by sy19890515** [comment]
> 透明代理环境下，dns是有缓存的。不会马上生效

另外还有个情况，我之前开了定时自动订阅，后来注意到日志里重启服务的记录好像比自动订阅的要多，然后我关掉了，之后观察了一下确实好像有时候明明我长时间没在电脑前的时候它也会重启服务，请问是怎么回事呢？

**Comment by sy19890515** [comment]
> > 透明代理环境下，dns是有缓存的。不会马上生效
> 
> 另外还有个情况，我之前开了定时自动订阅，后来注意到日志里重启服务的记录好像比自动订阅的要多，然后我关掉了，之后观察了一下确实好像有时候明明我长时间没在电脑前的时候它也会重启服务，请问是怎么回事呢？

啊我刚说完又发现这个现象了
我今天回家发现一个网站今天居然不开PC翻墙也能打开，速度也不慢，用了一会，然后外卖来了刚才去吃饭了，吃完饭以后我想起那个随机重启服务的问题，回复了一下，然后我就去看了下路由器的日志发现刚好在几分钟前重启过，再试了一下之前那个网站结果就发现打不开了
