### ISSUE TITLE
Socks 长时间链接后无网络

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-package#1539]
在主页Socks 主开关打开节点后，用qbittorrent链接该socks的端口下载种子，几小时后会出现无网络现象

节点是走的Xray VLESS协议，插件检测TCP UDP 都在运行中，开启缓存解析结果 未开启ChinaDNS-NG

重启passwall后正常联网。设备是R4S，上一次编译固件没出现此问题，具体应该是几个月前的版本

尝试用chrome+SwitchyOmega去链接那个socks端口，提示代理服务器异常，猜测可能BT下载连接数太大socks插件崩溃？

**Comment by handsomeji** [comment]
这样的话估计很大可能是socks进程挂了...
用不了的时候 socks状态是√还是×呢？

**Comment by zhucaidan** [comment]
> 这样的话估计很大可能是socks进程挂了... 用不了的时候 socks状态是√还是×呢？

对，忘了说上面显示正常，只有那个BT下载用的端口显示×

**Comment by handsomeji** [comment]
那就是进程挂了

**Comment by zhucaidan** [comment]
> 那就是进程挂了

那可怎么办啊，几个月前编译的哪个版本不管怎么弄都不会挂，但是那个版本很奇怪硬盘空间都被吃满了可能是日志爆了

**Comment by zhucaidan** [comment]
![image](https://user-images.githubusercontent.com/47970938/140437682-0d0a99e4-e3cd-481a-bbc0-1cb44ba2e308.png)
一觉起来就这样了😂

**Comment by handsomeji** [comment]
更新最新源码，启动守护进程。

**Comment by zhucaidan** [comment]
今天全新编译了一个lede固件+全新passwall源码试了下，一开始socks下载BT一切正常没断联5-6个小时，
然后突然无法上网，打开路由器后台发现很长时间无法进入然后提示：
Bad Gateway
The process did not produce any response

ping路由器是通的，断电重启后正常，猜测可能是socks进程守护导致内存爆了？设备是R4S旁路由只开了BBR和passwall
用的qBittorrent 同时下载大概15个任务，全局限制最高500连接数，每个任务下载50连接数，上传1个窗口
节点是xray的trojan然后，qBittorrent直接全部连接包括P2P也是走socks5总开关那里，路由器是旁路由模式。

![image](https://user-images.githubusercontent.com/47970938/155527745-eee90250-fa57-4aab-a8ab-9c6189c515c8.png)
