### ISSUE TITLE
openwrt-passwall  请教opkg包如何安装

### ISSUE THREAD

**Issue by l-yp** [xiaorouji/openwrt-package#1540]
i need qos 功能
谢谢
`root@passwallOpenWrt:~# opkg install luci-app-qos
Installing luci-app-qos (git-21.301.66621-6335d0f-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/luci/luci-app-qos_git-21.301.66621-6335d0f-1_all.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-qos:
 *      kernel (= 4.14.248-1-68143adfcb7fc62a239c4be112fe40de)
 * opkg_install_cmd: Cannot install package luci-app-qos.
root@passwallOpenWrt:~# opkg update
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/freifunk/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_freifunk
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/freifunk/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/passwall/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/passwall/Packages.gz

Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/telephony/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/passwall/Packages.gz, wget returned 8.
`

**Comment by Jin33334** [comment]
it would be great if there will be writen a detail discription how to install passwall on a openwrt.
It woould help many people and recude the issues.

In chinese is enough, we can use a translator.

**Comment by yaott2020-666** [comment]
这个插件依赖内核，内核版本不一致无法安装，就算可以安装，有可能工作异常，只能在固件编译时编译进去，不能单独安装，除非是固件编译后产生的ipk包，此时内核版本一致
