### ISSUE TITLE
使用lean 编译  passwall xray分流无法启动 

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#1541]
Xray 1.5.0 (Xray, Penetrates Everything.) OpenWrt (go1.17.2 linux/amd64)
A unified platform for anti-censorship.
2021/11/05 01:23:12 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall/TCP.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ads > infra/conf: failed to load geosite: CATEGORY-ADS > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /usr/share/xray/geosite.dat: no such file or directory

**Comment by ghost** [comment]
WARNING: Not overriding core package 'dns2socks'; use -f to force
WARNING: Not overriding core package 'ipt2socks'; use -f to force
WARNING: Not overriding core package 'microsocks'; use -f to force
WARNING: Not overriding core package 'pdnsd-alt'; use -f to force
 
使用 -f 之后 还是有问题

**Comment by ShanStone** [comment]
缺少geosite.dat，检查/usr/share/xray/下有没有geosite.dat和geoip.dat，没有请在规则管理里更新一次geoip和geosite
