### ISSUE TITLE
Passwall好像不能代理局域网IP?

### ISSUE THREAD

**Issue by smallprogram** [xiaorouji/openwrt-package#1542]
我在公网中架设了一个xray的服务器，
**公网IP 1.2.3.4，简单叫【S1】服务器**。
S1服务器具有双网口，**eht0为公网IP1.2.3.4，eth1为内网 192.168.1.2，他的网关是192.168.1.1的内网网关**。
还有一台同内网的**服务器【S2】，内网IP 192.168.1.3，网关192.168.1.1**

我在家里，使用Passwall，设置代理规则，如果请求IP为192.168.1.3，那么走S1上的xray代理。
设置方式尝试：
id|设置方式|具体|结果
-|-|-|-
1| Passwall添加代理名单IP|将192.168.1.3添加到代理IP列表中，代理方式全局代理|无效
2|Passwall添加Xray分流规则|在分流规则中添加新的规则并置顶，规则内容IP中设置192.168.1.3，主节点使用Xray分流，全局代理|无效
3|直接使用Xray.exe，在本地设置代理规则|编写XrayConfig，Inbound使用Sock代理，Windows配置为该代理，Outbound设置为公网1.2.3.4的代理服务器配置，route添加代理规则，如果访问IP匹配192.168.1.3则走代理Outbound，如果不匹配则直连|有效

检查了相关passwall生成的TCP_UDP.json的配置文件，也没有关于privateIP的代理规则，理论上应该没问题的。但是就是不生效。

**问题： Passwall好像无法代理内网IP?**

**Comment by handsomeji** [comment]
不能 iptables写死局域网IP直接return了

**Comment by smallprogram** [comment]
> 不能 iptables写死局域网IP直接return了

我去看看源码，研究怎么改一下，弄个开关啥的......感谢你的回复
