### ISSUE TITLE
最近总是检测不到组件

### ISSUE THREAD

**Issue by sundaqiang** [xiaorouji/openwrt-package#1545]
![321321](https://user-images.githubusercontent.com/34206512/140630302-fb525789-16b4-4c4f-bafb-267c7a402abd.png)

查看了代码，发现这里总是获取不到版本号，代码稍微删除后面的两个管道操作。
-version为啥会无效呢？
![123](https://user-images.githubusercontent.com/34206512/140630449-72e082d3-fa09-469a-b1b9-6d83d6927782.png)

但是我在命令行是能获取到的，手动截取部分代码运行也是能成功获取，为啥插件会获取不到呢？
![312321321](https://user-images.githubusercontent.com/34206512/140630459-360e18cd-7260-40be-8811-da8103a3ed98.png)

实际上刚重启路由器虽然获取不到版本号但是也能运行。
不过如果更改配置重启passwall后，是无法启动这几个服务的。

真是百思不得其解呀.....

**Comment by WYC-2020** [comment]
不断爆无法分配内存

**Comment by smallprogram** [comment]
把路由器自身TCP代理改为中国列表以外，然后再试试。

**Comment by handsomeji** [comment]
用了nginx代替uhttpd？

**Comment by sundaqiang** [comment]
> 用了nginx代替uhttpd？

是的，这会有影响吗？我自己做的插件也能检测到二进制文件的版本号。

**Comment by sundaqiang** [comment]
> 把路由器自身TCP代理改为中国列表以外，然后再试试。

我的设置一直都是中国列表外，他这个获取本地版本应该和网络没关系。其实我检测版本和下载最新版本的功能没啥问题。

**Comment by kiddin9** [comment]
sed -i '/limit-as/c\limit-as = 5000' /etc/uwsgi/vassals/luci-webui.ini
/etc/init.d/uwsgi restart

**Comment by sundaqiang** [comment]
> sed -i '/limit-as/c\limit-as = 5000' /etc/uwsgi/vassals/luci-webui.ini /etc/init.d/uwsgi restart

确实有效！这个是控制什么的限制？

**Comment by kiddin9** [comment]
> > sed -i '/limit-as/c\limit-as = 5000' /etc/uwsgi/vassals/luci-webui.ini /etc/init.d/uwsgi restart
> 
> 确实有效！这个是控制什么的限制？

https://github.com/fw876/helloworld/pull/630

**Comment by WYC-2020** [comment]
控制内存分配限制的，不是给你说了分配内存失败？居然没看我的回复

**Comment by sundaqiang** [comment]
> 控制内存分配限制的，不是给你说了分配内存失败？居然没看我的回复

真抱歉，我眼花了。。😂😂😂
