### ISSUE TITLE
VLESS+WS+TLS无法使用443以外的的端口

### ISSUE THREAD

**Issue by lvlinkeji** [xiaorouji/openwrt-package#1546]
在 passwall 上，VLESS+WS+TLS无法使用443以外的的端口。如果使用非443的端口，passwall 会一直连不上服务器。

同样，套上CDN后，passwall 使用 VLESS+WS+TLS 的配置时，无法使用443以外的端口，例如444端口。

备注：服务器的端口配置与客户端的端口配置是同步的，服务器使用的是x-ui。服务器使用VLESS+WS+TLS 加 444端口时，passwall连不上。

现在的问题是，在passwall上，使用 VLESS+WS+TLS的组合时，只能用443端口。若用其它端口则会连不上服务器。

passwall 版本：2021年11月8日编译的最新源码的版本。而且用以前旧的版本也不行。

**Comment by smallprogram** [comment]
把你的配置发上来我测一下。要是觉得不妥发邮箱也行。smallprogramzhusir@gmail.com

**Comment by lvlinkeji** [comment]
我验证了一下，这个是 xray 内核的问题，只要用 VLESS+WS+TLS 就只能用 443 端口。

**Comment by zhangbiwen** [comment]
同样的问题，443端口我们这里电信用不了
