### ISSUE TITLE
Openwrt 21.02.1 树莓派4官方SDK编译passwall出现trojan-plus/compile Error 

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#1548]
#!/bin/bash

#非root账号下载sdk
wget：.... 
# 添加包含 passwall 的 feed
echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default

# 因为部分软件包需要用到 upx，而官方 SDK 镜像中没有包含，所以自行安装
sudo apt-get update
sudo apt-get install upx -y
cp /usr/bin/upx staging_dir/host/bin
cp /usr/bin/upx-ucl staging_dir/host/bin

# 更新所有 feeds
./scripts/feeds update -a

# 这里因为 Xray 使用的 golang 版本较新而 SDK 中依赖的 golang 版本较旧，所以替换了旧的，用了 21.02 的 golang 配置
pushd feeds/packages/lang
rm -rf golang && svn co https://github.com/openwrt/packages/branches/openwrt-21.02/lang/golang
popd

./scripts/feeds install luci-app-passwall

make defconfig

# 编译
make package/luci-app-passwall/{clean,compile} -j4
# 生成 index 和签名
make package/index

但是目前在编译这一步出现问题了。
等一下提交错误代码。。大佬看一下我的步骤没有问题吧

**Comment by wazzx** [comment]
GO是1.17版本的

**Comment by wazzx** [comment]
我已经成功了。是SDK使用了的问题。大佬可以使用一下这个文件，方便大家使用

**Comment by azim0044** [comment]
Hi.. sorry for asking. I have compiled passwall using sdk for my rpi4 sdk openwrt v21.20.1.. but when I want to opkg install luci app passwall.. its give me an error.. like incompatible architecture. But others ipk can install only Luci app passwall.

**Comment by dukmonki** [comment]
请大雕们处理一下吧，这些代码能写进去吗？自己处理很麻烦。

**Comment by wazzx** [comment]
> Hi.. sorry for asking. I have compiled passwall using sdk for my rpi4 sdk openwrt v21.20.1.. but when I want to opkg install luci app passwall.. its give me an error.. like incompatible architecture. But others ipk can install only Luci app passwall.

im do not  problem.u can try again.

**Comment by wazzx** [comment]
问题已经解决
