### ISSUE TITLE
Passwall无法让Kodi走代理

### ISSUE THREAD

**Issue by sky2016cn** [xiaorouji/openwrt-package#1550]
Lean最新编译的固件，使用 Passwall，电视盒子上的 Kodi 无法正常使用，譬如搜刮器无法连接外网报错，字幕下载也完全无法使用。换 SSR Plus+ 就会一切正常！

**Comment by smallprogram** [comment]
找到kodi、搜刮器等访问的域名，加入代理列表中。
再不行把电视盒子全局代理了。
这种问题自己动手解决一下就行了。

**Comment by sky2016cn** [comment]
之前试过了，kodi.tv的域名不对，不知如何查找？全局又会让爱奇艺无法观看，小白求告知，谢谢啦
