### ISSUE TITLE
官方openwrt源码编译passwall，三个包编译失败

### ISSUE THREAD

**Issue by 13528943945** [xiaorouji/openwrt-package#1552]
基于官方openwrt源码，添加passwall到feed，勾选passwall并全选其INCLUDE项编译，如下三个包编译失败：V2ray，Brook，Hysteria。不选这三个包则编译成功。成功运行后，在passwall的组件更新界面，又可以通过手动安装V2ray及Brook。

**Comment by ShanStone** [comment]
官方没有upx，要么自己手动添加，要么make menuconfig里把upx压缩选项取消掉
可以参考 https://github.com/xiaorouji/openwrt-passwall/issues/1548

**Comment by 13528943945** [comment]
明白了，多谢！机场提供了ss&ssr&v2ray三种节点。因为xray兼容v2ray且比后者先进，所以仅仅勾选了xray，其余一律不选，试验完全可行！仅使用其v2ray节点就够了！




发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: ShanStone  ***@***.***>
 

 
 发送时间: 2021-11-11 17:18:23
 

 
 收件人: xiaorouji/openwrt-passwall  ***@***.***> 
 

 
 抄送: myfirstgit  ***@***.***>,Author  ***@***.***> 
 

 
 主题: Re: [xiaorouji/openwrt-passwall] 官方openwrt源码编译passwall，三个包编译失败 (Issue #1552)
 





 官方没有upx，要么自己手动添加，要么make menuconfig里把upx压缩选项取消掉

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
