### ISSUE TITLE
某一路pppoe断连会导致passwall反复重启

### ISSUE THREAD

**Issue by sjtuross** [xiaorouji/openwrt-package#1558]
当某一路pppoe暂时不可用时，passwall会反复重启，日志中没有错误信息，都是正常启动的日志，启动结束后过几秒，这些日志又会来一遍。删了这路pppoe就好了，希望告知如何避免passwall反复重启的方法。

**Comment by sjtuross** [comment]
查到原因了，断开的pppoe接口会反复尝试拨号，估计触发了firewall reload，然后以下这段include被反复执行。把reload改成0之后问题就解决了，而且应用network, firewall, mwan3等配置速度变得飞快，估计之前就是在不断地passwall reload

```
config include 'passwall'
	option type 'script'
	option path '/var/etc/passwall.include'
	option reload '1'
```

这个文件/var/etc/passwall.include的内容是以下这个函数写入的，来自iptables.sh，就是做passwall reload

```
gen_include() {
	flush_include
	cat <<-EOF >>$FWI
		echo "" > $LOG_FILE
		/etc/init.d/passwall reload
	EOF
	return 0
}
```

可能这个并非是最优解决方案，但对我来说，手工重启passwall优于靠firewall来触发自动重启

**Comment by mu910125** [comment]
遇到了相同的问题，
我是编译openwrt镜像，升级后，路由器始终无法连上。
排除了驱动和其他问题后，最后删除了该包，路由器能正常工作了。

**Comment by mu910125** [comment]
遇到了相同的问题，我是编译openwrt镜像。升级后，路由器始终无法连上。
现象是只要发生PPPOE相关操作，路由器就再也无法连接上。
排除了驱动和其他问题后，开始一个一个删包，最后删除了该包，路由器能正常工作了。

**Comment by 5632515** [comment]
> 查到原因了，断开的pppoe接口会反复尝试拨号，估计触发了firewall reload，然后以下这段include被反复执行。把reload改成0之后问题就解决了，而且应用network, firewall, mwan3等配置速度变得飞快，估计之前就是在不断地passwall reload
> 
> ```
> config include 'passwall'
> 	option type 'script'
> 	option path '/var/etc/passwall.include'
> 	option reload '1'
> ```
> 
> 这个文件/var/etc/passwall.include的内容是以下这个函数写入的，来自iptables.sh，就是做passwall reload
> 
> ```
> gen_include() {
> 	flush_include
> 	cat <<-EOF >>$FWI
> 		echo "" > $LOG_FILE
> 		/etc/init.d/passwall reload
> 	EOF
> 	return 0
> }
> ```
> 
> 可能这个并非是最优解决方案，但对我来说，手工重启passwall优于靠firewall来触发自动重启
求求大佬细说，是要修改哪里，我貌似也遇到这个问题，之前只能确定，是因为开始用mwan3，就会出这个问题，不知道您是怎么解决的……

**Comment by ghost** [comment]
太谢谢你了，ipv6每半小时会重置一次route路径，就会触发这个reload。每半小时断网一次真是烦死我。终于找到解决办法，谢谢你

**Comment by sjtuross** [comment]
不客气，补充一下，如果是自编译，可以修改L14和L24这2行reload为0，这样固件刷好默认就是0了。或者参考上面2个引用的commit

https://github.com/xiaorouji/openwrt-passwall/blob/cc7ba47760a77be9865401780340bd31a703a11f/luci-app-passwall/root/etc/uci-defaults/luci-passwall#L14-L24
