### ISSUE TITLE
希望访问控制能支持IPSET

### ISSUE THREAD

**Issue by sjtuross** [xiaorouji/openwrt-package#1559]
现在的访问控制只支持IP或MAC，希望加入ipset的支持，这样可以减少iptable规则的数量，还能动态调整ipset而不重启passwall

**Comment by smallprogram** [comment]
希望GitHub能够支持自动PR。这样既能减轻具有无私开源精神的开发者负担又能满足使用者需求。

**Comment by Aukansh** [comment]
需求越来越囊肿！ 越搞BUG越多

**Comment by WYC-2020** [comment]
还是先把现有的功能搞稳定再说，那个锁的问题一直都没解决

**Comment by sjtuross** [comment]
访问控制是passwall的一大特色，希望更好用，性能更好才提了这个，优先级或者做不做大佬决定哈

**Comment by handsomeji** [comment]
来源地址 ipset？

**Comment by sjtuross** [comment]
是的老大，来源ipset，比如针对某一批内网地址（192.168.1.10-192.168.1.59）指定策略，现在只能一个个IP加，然后就有相同数量的iptable规则生成

或者允许添加iprange，但估计生成的iptable规则数量不会少

**Comment by handsomeji** [comment]
最新源码 https://github.com/xiaorouji/openwrt-passwall/commit/a147f8ab7d15b54a1c21fbc80af133e3b698c841 已加入，请测试。

**Comment by sjtuross** [comment]
很久没编译了，周末补补课，测试一下

**Comment by haiibo** [comment]
不错不错我也试试新功能

**Comment by greennyreborn** [comment]
予取予求小肉机

**Comment by sjtuross** [comment]
@xiaorouji 编译了优化过之后的最新代码，测试了ipset和ip range跟全局代理、GFW列表、中国列表以外的各个组合，都正常&#128077;
