### ISSUE TITLE
过滤关键字模式建议增加保留列表和丢弃并存

### ISSUE THREAD

**Issue by nemo-ex** [xiaorouji/openwrt-package#1562]
如题，比如想保留香港节点，同时又想丢弃掉香港里面“游戏|测试”节点

**Comment by Aukansh** [comment]
那你直接命中过滤游戏这两个字或者测试两个字不行？非要整这些连自己都觉得困难分别不了的东西！

**Comment by ShanStone** [comment]
已添加，试一下最新源码呢

**Comment by martin-xj** [comment]
最新源码已经无法过滤，保留 丢弃四种方式都不起作用了。

**Comment by ShanStone** [comment]
> 最新源码已经无法过滤，保留 丢弃四种方式都不起作用了。

有可能是配置的问题，因为加了模式，所以相应订阅配置里可能就会变成“丢弃列表，但保留列表优先”模式了，需要自己改过来或者删掉原来的订阅配置，再重新配置一轮。默认是使用全局配置。
![image](https://user-images.githubusercontent.com/31815718/142622885-5d28b2c7-6256-4b47-a36a-e447763a549a.png)

**Comment by WYC-2020** [comment]
感觉越搞越复杂

**Comment by nemo-ex** [comment]
> > 最新源码已经无法过滤，保留 丢弃四种方式都不起作用了。
> 
> 有可能是配置的问题，因为加了模式，所以相应订阅配置里可能就会变成“丢弃列表，但保留列表优先”模式了，需要自己改过来或者删掉原来的订阅配置，再重新配置一轮。默认是使用全局配置。 ![image](https://user-images.githubusercontent.com/31815718/142622885-5d28b2c7-6256-4b47-a36a-e447763a549a.png)

666大神np
