### ISSUE TITLE
能否只使用【规则管理】里的【V2ray/Xray 分流规则】？现在各种规则选项有点乱

### ISSUE THREAD

**Issue by exlulu** [xiaorouji/openwrt-package#1569]
x86_64
固件版本 | OpenWrt R21.11.11 / LuCI Master (git-21.320.49600-21168d4)
内核版本 | 5.4.158
luci-app-passwall 4.43-2

清空了【直连/代理/局域网/hosts名单管理】里的全部内容
在【规则管理】-【V2ray/Xray 分流规则】里默认的规则全删除，只建立了【直连】和【代理】
在【直连】的域名添加
geosite:private
geosite:tld-cn
geosite:cn

在【代理】的域名添加
geosite:geolocation-!cn

【基本设置】-【主要】
【TCP节点】选【分流总节点】
【直连】选【直连】
【代理】选【添加好的节点】
【默认】选【添加好的节点】

如果在【基本设置】-【模式】
【TCP 默认代理模式】选【中国列表以外】
http://ip111.cn 【从国内测试】显示的是拨号的IP，其它均显示节点的IP
但是 https://apps.apple.com/us/app/qq/id444934666 不能打开，是否没有正确使用【分流总节点】？
【TCP 默认代理模式】选【全局代理】
则 https://apps.apple.com/us/app/qq/id444934666 能正常打开
但是 http://ip111.cn 【从国内测试】显示的是拨号的IP，其它均显示节点的IP，是否没有正确使用【全局代理】？

【基本设置】-【主要】
【TCP节点】选【分流总节点】
【直连】选【直连】
【代理】选【添加好的节点】
【默认】选【直连】（上面【V2ray/Xray 分流规则】配置的是白名单模式，所以这里选【直连】其实是不对的，只为测试）

如果在【基本设置】-【模式】
【TCP 默认代理模式】选【全局代理】
那么 http://ip111.cn 【从国内测试】和【从国外测试】显示的是拨号的IP，【从谷歌测试】显示的是节点IP，是否没有正确使用【全局代理】？相比上面【TCP 默认代理模式】选【中国列表以外】，却正确使用了【分流总节点】？因为 http://ip111.cn 【从国外测试】显示的是拨号的IP
但是 https://apps.apple.com/us/app/qq/id444934666 却能正常打开

如果【基本设置】-【主要】
【TCP节点】选【分流总节点】
无论【基本设置】-【模式】选什么，在【直连/代理/局域网/hosts名单管理】里添加什么都无效
那么【规则管理】-【V2ray/Xray 分流规则】、【直连/代理/局域网/hosts名单管理】、【基本设置】-【主要】-【TCP节点】的【分流总节点】和【基本设置】-【模式】之间的关系是如何的？优先级又是何如的？
能否独立分开【V2ray/Xray 分流规则】，只允许这个规则有效？
比如当使用【基本设置】-【主要】-【TCP节点】的【分流总节点】时，在【基本设置】-【模式】里添加一个【V2ray/Xray 分流规则】，【直连/代理/局域网/hosts名单管理】和【基本设置】-【模式】里的其它规则不生效，并在【基本设置】-【模式】只有【V2ray/Xray 分流规则】选项
当使用【基本设置】-【主要】-【TCP节点】的非【分流总节点】时，【基本设置】-【模式】不显示【V2ray/Xray 分流规则】并使其失效

**Comment by greennyreborn** [comment]
首先决定流量走向的第一步是passwall的代理设置，有不代理/GFW/中国列表以外/全局代理，这一步决定了是哪些该直连，哪些该走代理。
走代理的流量会去你设置的代理节点，然后你的代理节点是xray分流，所以上一部进入代理的流量会再根据你xray的分流规则进行分流，走你自己设置的"直连"/"代理"。

最后是直连/代理/局域网/hosts名单管理的设置，这个设置是passwall代理级别的设置，和xray的分流没有关系，如果在这里配置了直连的域名，会直接直连，根据进不到xray分流节点里面，所以你在xray的分流节点这个域名配置了走FQ节点也没用。

你的例子里passwall里设置了全局代理，只是让所有流量(实际上还要去掉直连/代理/局域网/hosts名单里配置了直连的域名) 进入xray分流而已，ip111.cn 国内测试显示你的拨号IP就很好理解了

**Comment by exlulu** [comment]
谢谢，明白了。
但是关于 直连/代理/局域网/hosts名单管理的设置 有点出入，我在模式选全局，xray分流 白名单规则（就是1L最上面写的规则）
【基本设置】-【主要】
【TCP节点】选【分流总节点】
【直连】选【直连】
【代理】选【添加好的节点】
【默认】选【添加好的节点】
然后打开speedtest.net，显示的是节点的IP，在 直连/代理/局域网/hosts名单管理 里面的直连添加了speedtest.net，打开speedtest.net也是显示节点的IP，要在xray分流规则 直连 的域名里添加speedtest.net或者domian:speedtest.net才会打开speedtest.net显示拨号的IP

所以要使用xray分流，模式必须选择全局。那流量要全部先经过代理，然后再到xray分流规则才分流，流量会浪费好多？如果是这样，我还是希望能把xray分流独立为一个模式，流量直接到xray分流

**Comment by yaott2020-666** [comment]
还不如只把局域网地址用passwall代理设置，其他通通交给xray分流去处理，直观很多

**Comment by greennyreborn** [comment]
> 谢谢，明白了。 但是关于 直连/代理/局域网/hosts名单管理的设置 有点出入，我在模式选全局，xray分流 白名单规则（就是1L最上面写的规则） 【基本设置】-【主要】 【TCP节点】选【分流总节点】 【直连】选【直连】 【代理】选【添加好的节点】 【默认】选【添加好的节点】 然后打开speedtest.net，显示的是节点的IP，在 直连/代理/局域网/hosts名单管理 里面的直连添加了speedtest.net，打开speedtest.net也是显示节点的IP，要在xray分流规则 直连 的域名里添加speedtest.net或者domian:speedtest.net才会打开speedtest.net显示拨号的IP
> 
> 所以要使用xray分流，模式必须选择全局。那流量要全部先经过代理，然后再到xray分流规则才分流，流量会浪费好多？如果是这样，我还是希望能把xray分流独立为一个模式，流量直接到xray分流

 按理说不应该，你可以看一下 ```/var/etc/passwall/TCP.log``` 这是xray 分流节点的日志，按理说，passwall上配置了直连的域名，在xray的日志上根本就不会出现。至少我自己测试下来是这样的

**Comment by exlulu** [comment]
> 按理说不应该，你可以看一下 `/var/etc/passwall/TCP.log` 这是xray 分流节点的日志，按理说，passwall上配置了直连的域名，在xray的日志上根本就不会出现。至少我自己测试下来是这样的

Xray 1.5.0 (Xray, Penetrates Everything.) OpenWrt (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2021/11/23 12:36:15 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP.json
2021/11/23 12:36:16 [Warning] core: Xray 1.5.0 started
2021/11/23 12:36:17 192.168.50.100:58682 accepted tcp:172.217.163.46:443 [Proxy]
2021/11/23 12:36:17 192.168.50.100:58683 accepted tcp:172.217.163.46:443 [Proxy]
2021/11/23 12:36:17 192.168.50.100:58684 accepted tcp:59.82.31.210:443 [blackhole]
2021/11/23 12:36:17 192.168.50.100:58685 accepted tcp:59.82.31.210:443 [blackhole]
2021/11/23 12:36:17 192.168.50.100:58686 accepted tcp:59.82.31.210:443 [blackhole]
2021/11/23 12:36:19 192.168.50.100:58690 accepted tcp:203.208.40.66:443 [direct]
2021/11/23 12:36:23 192.168.50.100:58694 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:23 192.168.50.100:58695 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:23 192.168.50.100:58696 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:26 192.168.50.100:58700 accepted tcp:52.139.250.253:443 [Proxy]
2021/11/23 12:36:28 192.168.50.100:58701 accepted tcp:172.217.160.78:443 [Proxy]
2021/11/23 12:36:28 192.168.50.178:37410 accepted tcp:119.147.70.219:443 [direct]
2021/11/23 12:36:28 192.168.50.178:40394 accepted tcp:119.147.39.226:443 [direct]
2021/11/23 12:36:28 192.168.50.100:58702 accepted tcp:108.160.169.181:443 [Proxy]
2021/11/23 12:36:28 192.168.50.100:58703 accepted tcp:108.160.169.181:443 [Proxy]
2021/11/23 12:36:29 192.168.50.100:58704 accepted tcp:108.160.169.181:443 [Proxy]
2021/11/23 12:36:29 192.168.50.100:58705 accepted tcp:108.160.169.181:443 [Proxy]
2021/11/23 12:36:29 192.168.50.100:58708 accepted tcp:142.251.42.238:443 [Proxy]
2021/11/23 12:36:29 192.168.50.100:58709 accepted tcp:142.251.43.10:443 [Proxy]
2021/11/23 12:36:29 192.168.50.100:58710 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:29 192.168.50.100:58711 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:29 192.168.50.100:58712 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:32 192.168.50.100:58714 accepted tcp:151.101.130.219:80 [default]
2021/11/23 12:36:32 192.168.50.100:58716 accepted tcp:151.101.74.219:443 [default]
2021/11/23 12:36:34 192.168.50.100:58718 accepted tcp:184.51.206.113:443 [default]
2021/11/23 12:36:34 192.168.50.100:58719 accepted tcp:151.101.74.219:443 [Proxy]
2021/11/23 12:36:35 192.168.50.100:58720 accepted tcp:104.77.73.201:443 [default]
2021/11/23 12:36:35 192.168.50.100:58722 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:35 192.168.50.100:58723 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:35 192.168.50.100:58724 accepted tcp:59.82.29.163:443 [blackhole]
2021/11/23 12:36:39 192.168.50.100:58738 accepted tcp:18.208.45.198:443 [default]
2021/11/23 12:36:40 192.168.50.100:58739 accepted tcp:18.208.45.198:443 [default]
2021/11/23 12:36:40 192.168.50.100:58740 accepted tcp:18.208.45.198:443 [default]

看不出什么

**Comment by exlulu** [comment]
Xray 1.5.0 (Xray, Penetrates Everything.) OpenWrt (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2021/11/23 12:39:33 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP.json
2021/11/23 12:39:33 [Warning] core: Xray 1.5.0 started
2021/11/23 12:39:33 192.168.50.100:58993 accepted tcp:140.82.114.26:443 [Proxy]
2021/11/23 12:39:33 192.168.50.178:42462 accepted tcp:101.36.166.16:443 [direct]
2021/11/23 12:39:34 192.168.50.100:58994 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:34 192.168.50.100:58995 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:34 192.168.50.100:58996 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:34 192.168.50.178:49198 accepted tcp:121.11.196.56:443 [direct]
2021/11/23 12:39:36 192.168.50.178:47982 accepted tcp:106.11.40.34:443 [direct]
2021/11/23 12:39:36 192.168.50.100:59000 accepted tcp:40.119.211.203:443 [Proxy]
2021/11/23 12:39:40 192.168.50.100:59003 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:40 192.168.50.100:59004 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:40 192.168.50.100:59005 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:40 192.168.50.178:40872 accepted tcp:119.147.39.226:443 [direct]
2021/11/23 12:39:40 192.168.50.178:37888 accepted tcp:119.147.70.219:443 [direct]
2021/11/23 12:39:42 192.168.50.100:59008 accepted tcp:142.251.42.238:443 [Proxy]
2021/11/23 12:39:42 192.168.50.100:59009 accepted tcp:106.75.184.70:443 [direct]
2021/11/23 12:39:43 192.168.50.179:56416 accepted tcp:113.96.209.106:80 [direct]
2021/11/23 12:39:43 192.168.50.179:56419 accepted tcp:113.96.202.101:80 [direct]
2021/11/23 12:39:43 192.168.50.100:59011 accepted tcp:151.101.230.219:443 [direct]
2021/11/23 12:39:43 192.168.50.100:59012 accepted tcp:172.217.24.10:443 [Proxy]
2021/11/23 12:39:44 192.168.50.100:59013 accepted tcp:151.101.110.219:443 [Proxy]
2021/11/23 12:39:44 192.168.50.100:59014 accepted tcp:151.101.110.219:443 [Proxy]
2021/11/23 12:39:44 192.168.50.100:59015 accepted tcp:184.51.206.96:443 [direct]
2021/11/23 12:39:45 192.168.50.100:59018 accepted tcp:151.101.110.219:443 [Proxy]
2021/11/23 12:39:46 192.168.50.100:59019 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:46 192.168.50.100:59020 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:46 192.168.50.100:59021 accepted tcp:59.82.29.248:443 [blackhole]
2021/11/23 12:39:46 192.168.50.100:59022 accepted tcp:104.121.218.39:443 [default]
2021/11/23 12:39:48 192.168.50.178:46050 accepted tcp:203.119.144.10:443 [direct]

用ping.chinaz.com查了www.speedtest.net解析的IP，是151.101.XXX.XXX
这个是添加在 V2ray/Xray 分流规则的 直连域名 里的，可以见到 151.101.230.219:443 [direct] 或者 [Proxy]，上面添加在 直连/代理/局域网/hosts名单 就显示 [default] 或者 [Proxy]

**Comment by exlulu** [comment]
> 还不如只把局域网地址用passwall代理设置，其他通通交给xray分流去处理，直观很多

我是希望不经过其他任何规则，只交给xray分流去处理就好

**Comment by smallprogram** [comment]
> > 还不如只把局域网地址用passwall代理设置，其他通通交给xray分流去处理，直观很多
> 
> 我是希望不经过其他任何规则，只交给xray分流去处理就好

你可以将黑白名单全部清空，并使用全局代理，然后再设置xray分流。这种方式也可以满足你的需求。
最好的方式是你去好好阅读源码，然后根据你自己的需求提交PR。而不是在这里提需求。这个项目不是商业项目，是开源项目，没有人有义务去实现任何人的需求，ISSUE说到底是提交bug的地方而不是提交需求的地方。谢谢。

**Comment by exlulu** [comment]
> 你可以将黑白名单全部清空，并使用全局代理，然后再设置xray分流。这种方式也可以满足你的需求。 最好的方式是你去好好阅读源码，然后根据你自己的需求提交PR。而不是在这里提需求。这个项目不是商业项目，是开源项目，没有人有义务去实现任何人的需求，ISSUE说到底是提交bug的地方而不是提交需求的地方。谢谢。

我现在就是这样设置，我就是说规则乱，有BUG，添加了直连没有直连，希望改进，我提出的改进是独立开xray分流规则，至于大佬要怎么处理或者不需处理那是大佬的事

**Comment by toniexly** [comment]
其实楼主说的有道理，我今天也发现这个分流设置有一点不足。按这个规则，如果passwall是国内白名单模式，那么分流里的ad黑洞对国内广告就没有过滤作用。

**Comment by cliia** [comment]
楼主说的确实有道理，passwall的规则太乱了，连个文档都找不到

**Comment by auflute** [comment]
我觉得v2ray/xray分流可以把系统的黑白名单替换掉，没必要分两遍。另外分流的直连和代理等可以分别设置不同的dns组，或者dns的解析在分流前全部托管给mosdns来分流，避免查dns的时候分流两遍

**Comment by auflute** [comment]
> 我觉得v2ray/xray分流可以把系统的黑白名单替换掉，没必要分两遍。另外分流的直连和代理等可以分别设置不同的dns组，或者dns的解析在分流前全部托管给mosdns来分流，避免查dns的时候分流两遍

我试了一下passwall 2，基本解决了我的问题。我写了一篇心得总结在这里 https://www.right.com.cn/forum/thread-8266242-1-1.html

**Comment by forrany** [comment]
> > 我觉得v2ray/xray分流可以把系统的黑白名单替换掉，没必要分两遍。另外分流的直连和代理等可以分别设置不同的dns组，或者dns的解析在分流前全部托管给mosdns来分流，避免查dns的时候分流两遍
> 
> 我试了一下passwall 2，基本解决了我的问题。我写了一篇心得总结在这里 https://www.right.com.cn/forum/thread-8266242-1-1.html

<img width="545" alt="image" src="https://user-images.githubusercontent.com/29779326/233783331-b4c4d16f-fbe8-4da8-93da-a7f435e25edc.png">

在github，引流到论坛去付费？ 这个操作有点不厚道了吧。
