### ISSUE TITLE
luci-app-passwall 的依赖包

### ISSUE THREAD

**Issue by osnosn** [xiaorouji/openwrt-package#1580]
在openwrt-21.02官方固件中，安装 luci-app-passwall，web管理界面会出错。
之后安装 luci-compat 包之后恢复正常。
而这个luci-compat包，默认是没有安装的。

希望把
luci-compat
dnsmasq-full
这两个包加入到依赖列表中。

**Comment by chaangliu** [comment]
hello @osnosn 请问你的luci-app-passwall是自己编译的吗？在这个仓库没有找到编译好的ipk

**Comment by osnosn** [comment]
@chaangliu  自己编译，看 #1557
