### ISSUE TITLE
点保存&应用后，无法启动PASSWALL，需要进行手动重启/etc/init.d/passwall restart

### ISSUE THREAD

**Issue by alivenp** [xiaorouji/openwrt-package#1584]
这个问题出现的时间有点长了，进入配置页面，哪怕没改任何东西，点“保存&应用”后，运行状态中的所有内容除了DNS外，全部是未运行状态，手动执行/etc/init.d/passwall restart 后，运行状态会恢复到运行中，但重启路由器后是正常的，上面显示的都是已运行，也可以正常上外网，尝试过恢复默认配置，也是一样的情况，不知道是我的特例还是有BUG

**Comment by sky2016cn** [comment]
你不说固件版本和passwall版本号，也没有系统日志是没用的

**Comment by alivenp** [comment]
固件都是我自己编译的，用的都是最新版的passwall 和 lean openwrt，之前的版本好的，最近一个月都这样，x86环境下

**Comment by smallprogram** [comment]
我昨天编译的，没有此问题。

**Comment by WROIATE** [comment]
看看是不是用了nginx

**Comment by alivenp** [comment]
> 看看是不是用了nginx

确实是用了nginx，请问有办法解决吗？

**Comment by WROIATE** [comment]
> > 看看是不是用了nginx
> 
> 确实是用了nginx，请问有办法解决吗？

https://github.com/fw876/helloworld/pull/630

**Comment by alivenp** [comment]
> > > 看看是不是用了nginx
> > 
> > 
> > 确实是用了nginx，请问有办法解决吗？
> 
> [fw876/helloworld#630](https://github.com/fw876/helloworld/pull/630)

非常感谢！！！
终于解决了
