### ISSUE TITLE
高级设置中找不到tcp节点数设置问题上报

### ISSUE THREAD

**Issue by lpflhh** [xiaorouji/openwrt-package#1585]
拉取lean openwrt固件源码，然后在feeds.conf.default文件中加入`src-git passwall https://github.com/xiaorouji/openwrt-passwall`启动编译，编译好的passwall在`高级设置`中没有`tcp节点数`设置，请问是取消了吗，以后只能用1条tcp线路？
[http://ene.dynu.net:90/2021/11/28/openwrt-passwall%e9%ab%98%e7%ba%a7%e8%ae%be%e7%bd%aebug/](url)

**Comment by yunxi993** [comment]
你说的是之前可以设置3个节点的功能吗？
如果是，这个早就取消了，你之前用的很早的版本吗?

**Comment by handsomeji** [comment]
访问控制里面直接可以选择节点，而且无限制。无需再用以前复杂的逻辑。

**Comment by lpflhh** [comment]
> 

请问那我该如何做精确分流呢？比如我有一批disney+域名，我正在使用的tcp主线路不能解锁disney+，我希望这些域名能够走另一条tcp线路，至少以前我是这样做的，现在我找了一下好像没有这种设置方式了？或者说有另一种替代方式？

**Comment by smallprogram** [comment]
xray分流
