### ISSUE TITLE
在节点列表里，能否增加【订阅备注（机场）】的名字？

### ISSUE THREAD

**Issue by sk163** [xiaorouji/openwrt-package#1588]
在节点列表里，能否增加【订阅备注（机场）】的名字？
现在有个选项可以显示订阅节点的url地址，如果机场一多，还是不太好分辨，能否增加一个选项，把这个【订阅备注（机场）】的名字显示出来呢？谢谢~

**Comment by yunxi993** [comment]
![image](https://user-images.githubusercontent.com/59167936/143911159-9a4ab555-6606-4cd1-a99c-f5a0c79040a0.png)
这玩意儿不是你的需求吗？

**Comment by sk163** [comment]
![image](https://user-images.githubusercontent.com/2271609/143978782-9c57bb12-87c1-46bc-b225-671466543c9a.png)

抱歉，是我没有表达清楚，是在选择节点的下拉框中，能否增加一个显示订阅备注（机场名字）的名字，这样的话，节点一多，看地址是不能知道这个链接是属于哪个机场的

**Comment by sk163** [comment]
暂时用这种方法显示机场名了，修改api.lua文件，get_full_node_remarks()方法,：

            if n.use_kcp and n.use_kcp == "1" then
                remarks = "%s-%s+%s：[%s] %s" % {n.group, type2, "Kcptun", n.remarks, n.address}
            else
                remarks = "%s-%s：[%s] %s:%s" % {n.group, type2, n.remarks, n.address, n.port}
            end

![image](https://user-images.githubusercontent.com/2271609/144257706-68a3d1b7-6c41-466e-a11b-f4b3477e07f1.png)
