### ISSUE TITLE
手机，电脑怎么设置才能通过passwall上网呢？

### ISSUE THREAD

**Issue by viponedream** [xiaorouji/openwrt-package#1591]
手机，电脑怎么设置才能通过passwall上网呢？

**Comment by smallprogram** [comment]
基本设置中，主要中开关打开，设置好自己的节点，保存设置
两种基本方案：
1. 基本设置中，TCP默认代理模式，按照自己的需求选择相应的代理模式，这种设置所有连入路由的设备均走代理
2. 基本设置中，TCP默认代理模式，设置为不代理，在访问控制中单独设置某些IP或者mac设备走那些代理模式。
