### ISSUE TITLE
Xray 时常劫走vpn接口的53

### ISSUE THREAD

**Issue by 0xffffharry** [xiaorouji/openwrt-package#1594]
RT，设置xray分流 模式为IPOnDemand  部署在旁路由 上面有vpnserver 单独划出接口给vpn分配ip之类的（10.8.0.1）lan地址为10.0.0.3

但是xray进程时常劫走10.8.0.1:53，使得dnsmasq无法正常工作，vpn连接后无法通过10.8.0.1:53查询dns导致断网

xray却从来没有劫持过lan上的地址

**Comment by 0xffffharry** [comment]
补充  代理模式为全局（全都是）并且关闭dns防污染

**Comment by handsomeji** [comment]
passwall本身并不会占用53端口，53端口都是dnsmasq用的。建议查一下占用进程的pid，然后看看是不是passwall所开启的进程。

**Comment by 0xffffharry** [comment]
xray 没有多开，应该就是 passwall 开启的进程。已经关闭 dnsmasq 改用 mosdns 直接解析，不再通过 dnsmasq 代理，目前正常，再看看
