### ISSUE TITLE
大佬  hysteria插件能否增加alpn选项

### ISSUE THREAD

**Issue by liaoweiliao521** [xiaorouji/openwrt-package#1597]

**Comment by emptysuns** [comment]
希望能支持，直接默认hysteria alpn裸奔，不太好

**Comment by 70599** [comment]
还有hysteria 0.9.1新增了`protocol`字段，可以配置`faketcp`模式，希望也能更新进去。
https://github.com/HyNetwork/hysteria#fake-tcp--tcp-masquerade

**Comment by handsomeji** [comment]
Try the latest version.

**Comment by 70599** [comment]
> Try the latest version.

Worked as expected 👍
