### ISSUE TITLE
IPv6透明代理的iptables规则，漏掉了代理udp流量的规则

### ISSUE THREAD

**Issue by MikeMiao** [xiaorouji/openwrt-package#1600]
系统：OpenWrt Ipv6-Mini-S2021.11.20 by Sirpdboy / LuCI Master (git-21.320.49600-21168d4)
passwall版本：4.43-2

故障现象：内网开启ipv6，并在高级菜单内启用了IPv6代理（Tproxy）之后，youtube视频加载速度变得十分缓慢

分析：排查后发现，该版本passwall在启用IPv6透明代理之后，即使udp代理模式选择“全局”或者“中国列表以外”，ip6tables内未自动添加udp的代理规则，造成udp直连，youtube等支持quic的视频网站，udp443端口未过代理，造成视频加载速度缓慢。

对比：尝试使用另一版本的固件：
OpenWrt R21.8.6 GDQ v9.1[2021] Compiled by eSir / LuCI Master (git-21.238.35254-83494a9)
附带passwall版本为较老的4.34-1，未发现此问题。

正常配置及ip6tables：
![image](https://user-images.githubusercontent.com/17871086/144716907-f7ca40a9-fb94-4b2c-84f5-6488b7df920d.png)
![image](https://user-images.githubusercontent.com/17871086/144716781-7b85d45e-a202-436b-8e26-d67b89aa1f82.png)

异常配置及ip6tables：
![image](https://user-images.githubusercontent.com/17871086/144716920-d4216eee-1a32-4714-9fd7-a6ebd30a67e7.png)
![image](https://user-images.githubusercontent.com/17871086/144716875-5d6c3185-db55-405f-ae07-5d37f0714e7b.png)

**Comment by smallprogram** [comment]
[For some reasons](https://github.com/xiaorouji/openwrt-passwall/commit/5134b7ffd205383dbd965e3fc1940eaef9f33642#diff-9bc143043a6600231878b10092f1d0e2c6a523f4d613c44041d267134ad71d85), the udp proxy of ipv6 is blocked
https://github.com/xiaorouji/openwrt-passwall/blob/5134b7ffd205383dbd965e3fc1940eaef9f33642/luci-app-passwall/root/usr/share/passwall/iptables.sh#L414-L418

**Comment by MikeMiao** [comment]
got it, thanks a lot.

**Comment by WROIATE** [comment]
How about xray? Seem them achieved Fullcone?

**Comment by LitCcc** [comment]
> How about xray? Seem them achieved Fullcone?

If you are using Xray, you can uncomment these rules in iptables.sh. It works fine for me.

**Comment by MikeMiao** [comment]
> How about xray? Seem them achieved Fullcone?

I tried Xray 1.4.5 and 1.5.0,it works well with ipv6 udp traffic and nat type is indeed fullcone .However just like @LitCcc said, you have to manually uncomment those lines in /usr/share/passwall/iptables.sh which reenable paswall  to automatically add ipv6 udp divert ruls in ip6tables.

@smallprogram I think it's a good idea to add an option at frontend and leave the choice to user whether to divert ipv6 udp traffic to proxy or not, passwall was designed to work with various of proxy programs, I believe some of them would work well with ipv6 udp traffic just like xray.

**Comment by smallprogram** [comment]
Maybe the next version will fulfill your needs, but not now. I have been too busy lately to contribute code

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/0c05475eacc4984cc3dcab227e4325e6c0c350a9
