### ISSUE TITLE
【PassWall】Router Localhost TCP Proxy Mode，为何没有【No Proxy】模式？

### ISSUE THREAD

**Issue by zglonfee** [xiaorouji/openwrt-package#1607]
## 描述

我看了下代码，Router Localhost TCP Proxy Mode下并没有增加value("disable", translate("No Proxy"))的选项，请问，是设计如此，还是丢了一行代码？

**Comment by ShanStone** [comment]
看了一下，应该是漏了

**Comment by badgv** [comment]
刚想来搜下，果然如此。。。
