### ISSUE TITLE
SSR UDP中继失败

### ISSUE THREAD

**Issue by htfcuddles** [xiaorouji/openwrt-package#1611]
## 描述bug
当启用Xray作分流，SSR作TCP节点，UDP选择与TCP节点相同时，UDP中继失败

## 复现步骤
1. TCP节点选择Xray分流
2. 默认节点选SSR Libev类型
3. UDP节点选择与TCP节点相同	

## 你想要实现的目的
期望UDP转发，但所有UDP通信失败，TCP成功。

## 日志信息
ps输出如下，注意到命令行参数中没有-u选项开启UDP：
`7406 root      5656 S    /tmp/etc/passwall/bin/ssr-local -c /tmp/etc/passwall/v2_tcp,udp_xxx_2082.json -v `
该json配置如下，注意到配置中亦没有开启UDP：
`{
  "method": "xxx",
  "local_port": 2082,
  "reuse_port": true,
  "server_port": 10211,
  "local_address": "0.0.0.0",
  "password": "xxx",
  "fast_open": false,
  "protocol": "auth_aes128_sha1",
  "obfs": "plain",
  "protocol_param": "xxx",
  "timeout": 60,
  "server": "x.x.x.x"
}
`
## 系统相关信息
passwall版本：4.43
ssr-libev版本：2.5.6

## 其他相关信息
https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L525 加入-u选项后问题解决
`		ln_start_bin "$(first_type ssr-local)" "ssr-local" $log_file -c "$config_file" -v -u
`

**Comment by SakuraFallingMad** [comment]
不仅ssr，其实udp转发好像都有问题。允许的话，都可以排查下。
https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L529
https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L533

**Comment by htfcuddles** [comment]
> 不仅ssr，其实udp转发好像都有问题。允许的话，都可以排查下。
> 
> https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L529
> 
> 
> https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L533

ss是没问题的，上面一行在生成的json文件里指定了mode=tcp_and_udp
https://github.com/xiaorouji/openwrt-passwall/blob/d11e50811fd97e3c49962013e3b9fb8272d65c9b/luci-app-passwall/root/usr/share/passwall/app.sh#L528

我比较好奇从历史记录看这个bug从项目诞生起就有了，没人发现么

**Comment by xiaorouji** [comment]
用ssr的人较少，所以应该没什么留意吧

**Comment by SakuraFallingMad** [comment]
ssr经常用的路过，不过拿来分流看片的，是不是成功的躲过了bug点。。。
