### ISSUE TITLE
Force Proxy website doesn't work

### ISSUE THREAD

**Issue by xenstar** [xiaorouji/openwrt-package#1627]
## 描述bug ## 复现步骤
Rule List Manage -> Proxy List 

I have added a few sites manually to always use the Proxy Bandwidth, but still, it uses the local (CN) bandwidth to open the website. These websites are not blocked in CN, but it loads very slowly. I have added in this format, xyzxyz.com. Should I add with www.zyzxyz.com.

How do I know it uses local bandwidth? Because that website can also show the IP, and it shows CN IP.

## 日志信息

![image](https://user-images.githubusercontent.com/55502651/145713673-ee1b0680-93c9-4138-99ba-bfac30624a68.png)

## 系统相关信息
 

4.34-1

Brave, Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

**Comment by smallprogram** [comment]
you need update your passwall to last version

**Comment by xenstar** [comment]
In the latest version, have you fixed this issue?

**Comment by smallprogram** [comment]
Please try and you will get the answer

**Comment by xenstar** [comment]
Hello 

I tried, but didn't get the answer.

![image](https://user-images.githubusercontent.com/55502651/146431130-8fc61302-d059-4a92-9a43-a3a296b7515e.png)

Still the issue is there. I have also installed the new firmware from https://github.com/SuLingGG/OpenWrt-Rpi

Now please guide me how to fix this issue.

**Comment by smallprogram** [comment]
Please tell me what your proxy URL is, I'll try it

**Comment by xenstar** [comment]
When I go to find the issue, now faced a new issue is TCP and UDP not starting, only DNS is running. 

![image](https://user-images.githubusercontent.com/55502651/146505930-b6d1e0ec-ec1d-41a9-84ba-81f53135ac82.png)

I switched to shadowsocksr temporarily.

The domain I am trying to use proxy, e.g is berrycast.com and berrycast.app.

**Comment by smallprogram** [comment]
> When I go to find the issue, now faced a new issue is TCP and UDP not starting, only DNS is running.
> 
> ![image](https://user-images.githubusercontent.com/55502651/146505930-b6d1e0ec-ec1d-41a9-84ba-81f53135ac82.png)
> 
> I switched to shadowsocksr temporarily.
> 
> The domain I am trying to use proxy, e.g is berrycast.com and berrycast.app.

I tried the URL you gave. After adding it to the proxy list, the problem you described did not appear. I checked the proxy log on the server and everything was normal.
I don't know if there is any problem with your OP firmware. In short, I did not have the problem described.
As for the problem that TCP and UDP are not running, please refer to #1615 
By the way, I use Xray vless xtls instead of ssr

**Comment by xenstar** [comment]
//I checked the proxy log on the server and everything was normal//

So when you added berrycast.com, and berrycast.app in here, you are sure in the log it shows that berrycast was routed through the proxy server right? 
![image](https://user-images.githubusercontent.com/55502651/146566025-3a007844-85c7-4902-8c50-5661b0952d7e.png)

What I am saying is, even though I add the domains here, still it uses the local bandwidth to load the site.

**Comment by smallprogram** [comment]
@xenstar
My friend, may I ask which country you are from and do you have any remote tools? If you believe me, I want to remote your computer to see what's going on.
If you believe me, please add my twitter:@smallprogram2, and then send me a private message.

**Comment by xenstar** [comment]
> @xenstar My friend, may I ask which country you are from and do you have any remote tools? If you believe me, I want to remote your computer to see what's going on. If you believe me, please add my twitter:@smallprogram2, and then send me a private message.

I don't have twitter, you can send me message on telegram my id is xenstar

**Comment by smallprogram** [comment]
> > @xenstar My friend, may I ask which country you are from and do you have any remote tools? If you believe me, I want to remote your computer to see what's going on. If you believe me, please add my twitter:@smallprogram2, and then send me a private message.
> 
> 
> 
> I don't have twitter, you can send me message on telegram my id is xenstar

Ok，please wait min.
