### ISSUE TITLE
Xray分流在透明代理下无法根据域名匹配

### ISSUE THREAD

**Issue by 0xffffharry** [xiaorouji/openwrt-package#1639]
## 描述bug
Xray在透明代理下无法根据域名匹配

## 复现步骤

Xray分流 使用 IPIfNotMatch
no_china---代理节点------geoip:!cn / geosite:geolocation-!cn
gfw---代理节点------geosite:gfw
默认节点---直连

透明代理即可复现
*gstatic.com 解析到上海电信(203.208.41.66)
由于域名匹配失效--直接匹配ip，发现是中国ip，选择直连

google mail 无法正常显示

## 你想要实现的目的

透明代理希望可以实现域名匹配

#### Socks5代理 ####
2021/12/17 09:48:13 tcp:10.0.2.102:51811 accepted tcp:www.gstatic.com:443 [direct]
2021/12/17 09:48:13 tcp:10.0.2.102:51810 accepted tcp:fonts.gstatic.com:443 [direct]
2021/12/17 09:48:13 tcp:10.0.2.102:51813 accepted tcp:ssl.gstatic.com:443 [direct]
2021/12/17 09:48:13 tcp:10.0.2.102:51814 accepted tcp:edge.microsoft.com:443 [default]
2021/12/17 09:48:15 tcp:10.0.2.102:51815 accepted tcp:fonts.gstatic.com:443 [direct]
##### 透明代理 #####
2021/12/17 09:48:28 10.8.0.100:49731 accepted udp:203.208.41.98:443 [direct]
2021/12/17 09:56:21 10.8.0.100:37658 accepted udp:203.208.41.98:443 [direct]
##################
## 系统相关信息

4.41-1

**Comment by tritu** [comment]
*gstatic.com is in chnlist
