### ISSUE TITLE
Xray分流总节点模式下导致谷歌账号登录会卡住

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#1641]
## 描述bug
采取Xray分流总节点模式,谷歌账号登录不了,主节点更换了Vless及VMess测试
不知道是否和内核有关,用了论坛上大部分固件和自编译固件
拉取
git clone https://github.com/coolsnowwolf/lede.git openwrt
src-git kenzo https://github.com/kenzok8/openwrt-packages
src-git passwall https://github.com/xiaorouji/openwrt-passwall

都有这问题,用了xiaorouji/openwrt-passwall x64 passwall 固件
出错概率小很多

## 复现步骤
重启固件,分流主节点选择xray节点(概率大)
重启电脑,清理浏览器,google.com,点登录,会卡在正在进行安全连接
主节点采用Vless节点不能登录的几率比主节点是Vmess节点的概率大

## 日志信息
2021/12/18 06:40:39 [Warning] [2886116705] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [3470882945] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [24554359] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [656937757] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [2859805457] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [3298677770] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [1015913974] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:39 [Warning] [333760063] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.xxx.xxx:13192/xxx.xxx): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:40:41 2xx.xxx.14.163:57165 accepted tcp:8.8.4.4:53 [default]
2021/12/18 06:40:41 2xx.xxx.14.163:25889 accepted tcp:8.8.4.4:53 [default]

================================================

2021/12/18 06:52:01 [Warning] [1359570007] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [34393251] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [2359534152] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [4142689231] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [299267159] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [4219613517] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [283526006] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [1812194173] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [402388997] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/12/18 06:52:01 [Warning] [1658532807] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: 

## 截图
主开关

TCP节点

Xray 分流：[分流总节点]
  修改  日志
* AD

关闭
* BT

直连
* YouTube

默认
  修改
* Netflix

Xray VMess：[香港 xxxx|Netflix]
  修改
* China

直连
* 默认

Xray VLESS：[xxxxxxx]
  修改

---------------------------------------------------------
过滤模式

pdnsd 通过TCP节点请求DNS
远程DNS

8.8.4.4 (Google DNS)
缓存解析结果 否

ChinaDNS-NG 否

## 系统相关信息

固件版本 | OpenWrt R21.12.1 / LuCI Master (git-21.335.48743-5f363d9)

luci-app-passwall | 4.43-2

Brave
版本 1.32.115 Chromium: 96.0.4664.93（正式版本） （64 位)

Firefox 95.0.1 (64 位)

**Comment by handsomeji** [comment]
透明代理用大陆白名单外，Xray分流的China规则关闭，试试

**Comment by ghost** [comment]
谢谢大佬,目前测试, 只能通过UDP节点请求dns, 后面4个节点, 分流模式可以登录谷歌,pdnsd不行.
我自己另外安装了一个虚拟机做dns服务器,地址是192.168.2.1, 是adguardhome和smartdns, 端口是53,7053, 为了测试是不是端口的问题,专门设置53端口, 经过测试,单节点模式,可以支持adguardhome和smartdns作为dns服务器,分流模式, 不支持. 这就奇怪了.

这后面4个可以
<img width="589" alt="2021-12-27_225841" src="https://user-images.githubusercontent.com/35391542/147484790-389a2315-2a1d-4a2d-94de-c7a7a3685410.png">

设置本地smartdns为dns之后的日志

<img width="675" alt="2021-12-27_230703" src="https://user-images.githubusercontent.com/35391542/147490950-f0f237cf-e693-4bb0-b8ba-3b4370177b09.png">


这个"
- 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 UDP 代理转发对该服务器 UDP/7053 端口的访问"
不知道是什么意思,我已经把192.168.0.0/16加入代理列表了,并且把192.168.0.0/16从局域网列表删除,
他没有强制转发是不是这里的问题.

**Comment by handsomeji** [comment]
使用外置DNS，你的外置DNS也必须是无污染，否则也是白搞。

**Comment by ghost** [comment]
局域网adguardhome DNS 服务器 192.168.2.1:5335, 今天用完全相同的配置在vps上面配置了一个dns, 用下面的配置测试, 分流模式谷歌可以正常登录, 说明应该和ip地址有关, 也可能是没有加载(猜测), 局域网adguard 上游只设置了一个8.8.8.8目前也不成功.

<img width="456" alt="2021-12-29_012539" src="https://user-images.githubusercontent.com/35391542/147591863-4dba9979-f2d4-4e1b-8a16-a5a4c8828873.png">

**Comment by smallprogram** [comment]
代理列表里加的应该是192.168.2.1，而不是192.168.0.0/16，并且局域网列表里删除192.168.0.0/16

**Comment by ghost** [comment]
谢谢大神,测试了一下不成功

**Comment by handsomeji** [comment]
> 代理列表里加的应该是192.168.2.1，而不是192.168.0.0/16，并且局域网列表里删除192.168.0.0/16

不是这个意思

**Comment by handsomeji** [comment]
在你未弄懂DNS之前，请用passwall内置DNS方案，使用第三方DNS无法给予解答。

**Comment by handsomeji** [comment]
不行就用Xray DoH  + EDNS 解决

**Comment by guhill** [comment]
> 在你未弄懂DNS之前，请用passwall内置DNS方案，使用第三方DNS无法给予解答。

大佬, 我用相同方案在vps上配置dns是分流是可以成功解析的, 只是更换了一下ip地址, 用dig和dog命令测试局域网DNS 192.168.2.1:5335是有效的, 局域网DNS上游只设置了8.8.8.8, 应该不是我dns的问题.

**Comment by ghost** [comment]
第三方DNS的上游只有8.8.8.8,并且只是更换了一下ip就正常工作了，这应该是ip判断逻辑的问题，不方便修复就算了，还是感谢你们的贡献。

**Comment by handsomeji** [comment]
可以试试不要用8.8.8.8，因为我以前就试过出现GooglePlay无法下载的问题，后来诊断发现是Google DNS给返回了一个国内IP导致，换其他DNS或者更换服务器IP或用Edns client subnet 都可以解决。

**Comment by ghost** [comment]
> 

不晓得, 原因不明,, 有时间再慢慢折腾吧! 谢谢.
