### ISSUE TITLE
自动切换 如果dns是xray会导致被终止不启动

### ISSUE THREAD

**Issue by tuzhis** [xiaorouji/openwrt-package#1643]
## 描述bug
自动切换时如果dns是xray会导致被终止不启动

## 复现步骤
当节点有问题的时候后台会执行/usr/share/passwall/test.sh 判断切换
需要切换时会执行/usr/share/passwall/app.sh node_switch TCP xxx 0 1
当用xtls作为dns的时候，配置的名称是/tmp/etc/passwall/TCP_UDP_SOCKS_xxx_DNS.json会被终止，然后再启动的时候不会添加xray的dns配置

## 你想要实现的目的
切换时也添加重启dns的逻辑

## 截图
<img width="565" alt="截屏2021-12-19 09 57 28" src="https://user-images.githubusercontent.com/8074454/146660911-130826e6-7327-43cd-947b-e4397db406e0.png">

## 系统相关信息
passwall版本：4.43-2

**Comment by handsomeji** [comment]
The next version will be fix it.

**Comment by handsomeji** [comment]
更新最新源码
