### ISSUE TITLE
分流不接管不处理直连流量

### ISSUE THREAD

**Issue by sjtuross** [xiaorouji/openwrt-package#1650]
## 你的功能请求是否与问题有关？ 请描述。

Xray分流处理会把直连流量重新从本机发出，数据包的源IP变成本机IP，导致mwan3基于源IP的策略失效，直连流量总是走默认路由，而不是走指定的wan出口。

## 描述你考虑过的替代方案

很久以前的passwall支持启动3个节点，然后可以在访问控制中指定客户端比如Apple TV走Netflix节点，如下图。这种方式纯粹对代理流量进行分流，而不接管不处理直连流量，这样可以配合mwan3进行后续策略路由。

## 附加上下文

![image](https://user-images.githubusercontent.com/940110/146948427-aaaaeda2-7fc0-4047-ae14-b6d751a11657.png)

**Comment by greennyreborn** [comment]
这个功能现在也有啊，你访问控制里点修改进去看看

**Comment by sjtuross** [comment]
这功能隐藏得好深啊，可以正常使用，而且直连流量可以被mwan3的规则正确处理。

不过有个小问题，那里面的DNS选项貌似不完整？至少能不能有个默认的选项，就是默认用主界面的配置呢？

![image](https://user-images.githubusercontent.com/940110/147113775-5c412dd4-b4aa-401c-a9d5-dde386a7eae4.png)

这是主界面DNS配置，可以用自定义外加ChinaDNS

![image](https://user-images.githubusercontent.com/940110/147113861-aa97a17f-89c6-401f-909d-4d46c09028b6.png)

**Comment by handsomeji** [comment]
不支持自定义DNS
