### ISSUE TITLE
AdguardTeam工具dnsproxy

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#1654]
项目地址：https://github.com/AdguardTeam/dnsproxy
功能看起来很齐全，go编写大小也有保证
感觉可以用在passwall中，供参考

**Comment by Beginner-Go** [comment]
PDNS貌似更小？

**Comment by WROIATE** [comment]
> PDNS貌似更小？

和c写得比大小还是比不过，不过功能应该比pdnsd齐全，我看着东西功能甚至带了fast dns、dot or doh、转nat64的功能，而大小只有3M+

**Comment by WROIATE** [comment]
> PDNS貌似更小？

和c写得比大小还是比不过，不过功能应该比pdnsd齐全，我看着东西功能甚至带了fast dns、dot or doh、转nat64的功能，而大小只有3M+

**Comment by handsomeji** [comment]
不想再加任何DNS，可以自己外置。
