### ISSUE TITLE
节点启用了，但是TCP显示未运行.

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-package#1655]
节点启用了，使用也是正常的，但是TCP显示未运行.
![image](https://user-images.githubusercontent.com/59167936/147332488-a987a736-bf67-41ab-9dd6-69a529143fdf.png)
passwall 4.44-1

**Comment by pangfeng161** [comment]
自编译如果加入v2ray和xray一起就会导致出现tcp未运行,把v2ray去掉只编译xray就没这问题,反复测试过,可能还有其他解决方法

**Comment by smallprogram** [comment]
参考 #1615

**Comment by yunxi993** [comment]
> 自编译如果加入v2ray和xray一起就会导致出现tcp未运行,把v2ray去掉只编译xray就没这问题,反复测试过,可能还有其他解决方法

好的，我试试，谢谢！

**Comment by yunxi993** [comment]
> 自编译如果加入v2ray和xray一起就会导致出现tcp未运行,把v2ray去掉只编译xray就没这问题,反复测试过,可能还有其他解决方法

突然发现是v2ray的版本居然是1.5.1（变成xray的版本号了）
我重新把v2ray的版本更新成4.44.0就正常了.
