### ISSUE TITLE
Xray分流使用一会，TCP UDP不运行！

### ISSUE THREAD

**Issue by binhe-cpu** [xiaorouji/openwrt-package#1658]
设置分流保存&应后正常使用，过一会TCP UDP停止运行，再点保存&应用又正常，请问是什么原因？

**Comment by SakuraFallingMad** [comment]
打开日志，看错误， 更新geodata

**Comment by binhe-cpu** [comment]
![Screenshot_20211225_151349_com android chrome](https://user-images.githubusercontent.com/61576528/147379705-78cc9db2-4512-45d0-8d69-062ccf0f40ae.jpg)
都更新完成了

**Comment by binhe-cpu** [comment]
日志也没发现有错误

**Comment by smallprogram** [comment]
x86平台实测xray分流3小时，没有遇到该问题。硬件3865u,8G

**Comment by 70599** [comment]
同样无法复现

**Comment by binhe-cpu** [comment]
设置好后，重启op正常了，已经10个小时没出问题了
