### ISSUE TITLE
luci: change geodata 还是默认"/usr/share/xray/"

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#1660]
## 系统相![Snipaste_2021-12-26_06-33-22](https://user-images.githubusercontent.com/60512548/147394786-2cf8596f-8aed-4c17-a20b-a26ffde3a930.png)

luci: change geodata path
main (#1649)
按照道理应该是    
o.default = "/usr/share/v2ray/"
但是我这边是自己编译的最新的ipk升级以后情况还是
"/usr/share/xray/"
已经清空缓存重新加载。
还有如果这个是bug可以直接在luci改掉吗！

**Comment by tritu** [comment]
check /etc/config/passwall

**Comment by wazzx** [comment]
> check /etc/config/passwall

```
config global_rules
	option chnlist_update '1'
	option chnroute_update '1'
	option chnroute6_update '1'
	option gfwlist_update '1'
	list gfwlist_url 'https://cdn.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt'
	list chnroute_url 'https://ispip.clang.cn/all_cn.txt'
	list chnroute6_url 'https://ispip.clang.cn/all_cn_ipv6.txt'
	list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf'
	list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/apple.china.conf'
	list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/google.china.conf'
	option v2ray_location_asset '/usr/share/xray/'
	option auto_update '1'
```

**Comment by wazzx** [comment]
![Snipaste_2021-12-26_08-57-14](https://user-images.githubusercontent.com/60512548/147396307-92879340-87a5-4bb1-8e78-46aa8f7bf087.png)
目前已经手动更改了，不知道情况会怎么样。开始默认"/usr/share/xray/"
时不时的断网。
现在更改一下看一下情况

**Comment by tritu** [comment]
opkg upgrade won’t overwrite ur previous config

**Comment by wazzx** [comment]
![Snipaste_2021-12-26_10-51-40](https://user-images.githubusercontent.com/60512548/147397710-7f9cb099-c3f9-40e9-9b7d-36b1ec6026c3.png)
google检查不能联用但是，YouTube能正常访问

**Comment by wazzx** [comment]
> opkg upgrade won’t overwrite ur previous config

ok so I change it in luci to /usr/share/v2ray/ is ok

**Comment by smallprogram** [comment]
@Beginner-Go need fix

**Comment by handsomeji** [comment]
不要保留配置升级啊，或者升级后在passwall里面恢复配置

**Comment by wazzx** [comment]
> 不要保留配置升级啊，或者升级后在passwall里面恢复配置

我这边是稳定版的固件，只编译passwall相关的ipk，然后上传升级。所以应该没有保留配置升级这个选项，我这边升级以后在passwall里面恢复配置了的:
`恢复默认配置方法，地址栏输入例：http://192.168.1.1/cgi-bin/luci/admin/services/passwall/reset_config`
但是还是一样的
