### ISSUE TITLE
负载均衡无法在UI中关闭

### ISSUE THREAD

**Issue by drunkbear999** [xiaorouji/openwrt-package#1663]
## 描述bug
<负载均衡无法在UI中关闭：也不知道是否算Bug，自4.43开始发现在Passwall的负载均衡菜单下，“开启负载均衡
”的选项不工作了。。。不过也不影响使用的，汇报一下而已，谢谢>

**Comment by smallprogram** [comment]
经过测试不存在该问题，建议使用最新源码编译并不保留配置升级
