### ISSUE TITLE
增加xray/v2ray的shadowsocks的加密模式

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#1666]
## 你的功能请求是否与问题有关？ 请描述。
现在使用的ss+ws+tls不支持chacha20-ietf-poly1305

## 描述你想要的解决方案 
ss支持更多的加密模式

## 附加上下文
passwall xray/v2ray ss支持的加密模式就是图片中的效果

![Desktop_2021_12_28_12_09_35_8841](https://user-images.githubusercontent.com/72486732/147527419-95ab9390-facb-4842-9904-c965ba2dbdc7.jpg)

**Comment by handsomeji** [comment]
选 chacha20-poly1305 一样效果的
你可以看xray的源码
不过xchacha20以后会加上去

**Comment by ghost** [comment]
好的
