### ISSUE TITLE
可否为gRPC增加`initial_windows_size`选项

### ISSUE THREAD

**Issue by 70599** [xiaorouji/openwrt-package#1669]
## 你的功能请求是否与问题有关？ 请描述。

Xray 1.5.2的grpc 传输模式增加了`initial_windows_size`选项，可以解决被 Cloudflare 切断连接的问题
https://github.com/XTLS/Xray-core/releases/tag/v1.5.2

## 描述你想要的解决方案 

可否考虑在节点配置页面为gRPC增加`initial_windows_size`选项

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/c4c9fb254dcb4b5e475a682194db0a5b2919f036
