### ISSUE TITLE
依赖包ip6tables-save v1.8.7 (legacy): Cannot initialize: Table does not exist (openwrt21.02.1稳定版)

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#1673]
Installing xray-example (1.4.5-1) to root...
Installing xray-geodata (1.4.5-1) to root...
Configuring xray-core.
Configuring xray-example.
Configuring xray-geodata.
Configuring luci-app-passwall.
ip6tables-save v1.8.7 (legacy): Cannot initialize: Table does not exist (do you                                                                                                                                      need to insmod?)
Configuring luci-i18n-passwall-zh-cn.

## 系统相关信息
最新版4.45

**Comment by smallprogram** [comment]
这说的多明确，`Cannot initialize: Table does not exist (do you need to insmod?)`，明显你用的固件没有包含ip6tables。
这不是passwall插件的问题

**Comment by lialosiu** [comment]
<del>OpenWrt 21.02.2 也出现了这个错误，请问有解决方案吗？</del>

找到原因了，缺了 `kmod-ipt-nat6` 这个包，opkg装上就好了
