### ISSUE TITLE
编译进原版openwrt代码的若干问题

### ISSUE THREAD

**Issue by wuhaoc** [xiaorouji/openwrt-package#1675]
整体编译进最新版固件在最后一步报错，显示dnsmasq-full冲突。若取消原版dnsmasq可以编译成功，但刷入路由器wan口会无法联网。显示没有驱动。
若不整体编译单独编译软件，安装完全部依赖并且删除dnsmasq和配置文件 安装full版后，软件可以正常安装，但无法启动。上面的tcp uhd dns等都是未启动状态。
路由器型号为r3p  cpu mtk7621
只是有限 目前无解。
另编译到l大的lede固件一切正常。

**Comment by handsomeji** [comment]
官方默认就是dnsmasq，但是缺少好多功能，passwall需要用到full完整版。
建议使用国内openwrt分支，都是国人习惯，已经默认调好的。
