### ISSUE TITLE
组件更新把v2ray-core给删掉并且还无法更新回来

### ISSUE THREAD

**Issue by sy19890515** [xiaorouji/openwrt-package#1687]
## 描述bug
今天想着更新一下组件版本，结果v2ray一开始说更新成功，但是刷新完版本号变成了“无”，现在连不上v2ray节点了，然后再更新还是那样，一直说成功（前面也能正常下载、解压）但是刷新完版本号还是无

## 复现步骤
1. 组件更新
2. 点击v2ray版本后的“手动更新”按钮
3. 点击后先会检查当前最新版本号，之后按钮会变成“点击更新”，后面还有最新的版本号5.0.1
4. 点击“点击更新”按钮
5. 之后按钮会变成“下载中”-“解压中”-“移动中”，最后提示更新成功

## 你想要实现的目的
现在完全用不了v2ray节点了，ssr节点还能用，希望恢复

## 截图
![Snipaste_2022-01-03_17-32-09](https://user-images.githubusercontent.com/9069998/147916255-86d6d18a-554e-4927-8e6c-929c975995ad.png)
![Snipaste_2022-01-03_17-36-20](https://user-images.githubusercontent.com/9069998/147916533-00945a81-49ff-4dc0-9276-52bcb8c543e6.png)

## 系统相关信息
4.34-
96.0.4664.110

**Comment by Beginner-Go** [comment]
https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6

**Comment by HackYe** [comment]
一样的问题

**Comment by shuangleo** [comment]
那应该怎么办呢？

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/1689

**Comment by head2021** [comment]
v5版本应该还没有获得passwall支持，直接下载4.44版本的v2ray copy到usr/bin 覆盖即可。

**Comment by lanyucomputer** [comment]
看来都是这样的问题，找到这里来了

**Comment by ghost** [comment]
手动切换类型可以正常使用节点，
方法，进入passwall、选择节点列表、在点击单个V2节点旁边的修改按钮，修改类型为Xray，方可正常使用。
但是无法做到批量修改，因为使用的是机场，节点不止一个，要机场主改不可能，除非是自建。
希望后续更新，支持Xray代替V2ray的选项，这样就不用手动一个一个改了。

**Comment by HackYe** [comment]
建议直接把V2ray的程序路径替换为Xray的程序路径这样可以不用一个一个的修改节点
