### ISSUE TITLE
组件更新 V2ray 版本手动更新，更新成功之后，所有v2ray节点均无法正常访问外网

### ISSUE THREAD

**Issue by djt-dev** [xiaorouji/openwrt-package#1689]
## 描述bug

手动更新  V2ray 版本之后，V2ray 版本【 无 】，然后无法正常访问google,
两天之前手动更新还是正常的，今早也是正常使用，点击更新v2ray组件就不行了
## 复现步骤

1.组件更新

2.点击v2ray版本后的“手动更新”按钮

3.点击后先会检查当前最新版本号，之后按钮会变成“点击更新”，后面还有最新的版本号5.0.1
点击“点击更新”按钮，更新成功之后  版本变成 无

4.passwalll 其他功能都正常 ，唯独所有的v2ray节点无法访问外网

## 你想要实现的目的

希望点击更新，能更新出正确的版本，V2ray 本版那 不再是  [无] 而是有版本号
而且希望所有的 v2ray 节点可以正常访问 外网

## 截图

![2022-01-04_09-13](https://user-images.githubusercontent.com/82853739/147996988-cac92504-1ba1-475f-91f3-070dec29adbf.png)
![2022-01-04_09-14](https://user-images.githubusercontent.com/82853739/147996995-14fed495-ff41-4689-be94-069050955cdd.png)
![2022-01-04_09-14_1](https://user-images.githubusercontent.com/82853739/147997000-2f9b1aff-c3aa-416d-84b8-e9f3e4d89a41.png)

**Comment by handsomeji** [comment]
当v2ray没有发布正式版时，暂不支持v2ray 5.0

**Comment by aiastia** [comment]
https://github.com/v2fly/v2ray-core/releases
