### ISSUE TITLE
服务器端有没有守护功能？

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-package#1695]
RT，在服务器端起的HTTP代理经常会莫名挂掉，后台XRAY进程消失，不会自动重启，能否加个守护，挂了自动启动呢

**Comment by smallprogram** [comment]
高级设置里有进程守护

**Comment by badgv** [comment]
> 高级设置里有进程守护

守护功能没有守护“服务器端功能”，请问你这边测试过没有，你可以在“服务器端”起一个XRAY服务端，然后去终端直接kill该服务器端的XRAY进程，然后直接去进程序观察，会不会自动重启“服务器端”

高级功能那个守护应该是守护的“客户端”吧

**Comment by smallprogram** [comment]
> 进程守护



> > 高级设置里有进程守护
> 
> 守护功能没有守护“服务器端功能”，请问你这边测试过没有，你可以在“服务器端”起一个XRAY服务端，然后去终端直接kill该服务器端的XRAY进程，然后直接去进程序观察，会不会自动重启“服务器端”
> 
> 高级功能那个守护应该是守护的“客户端”吧

嗯嗯，看了看源码 monitor.sh，确实只是客户端。
