### ISSUE TITLE
使用dns2socks就无法访问IPV6网站，如果是PDNSD就正常。

### ISSUE THREAD

**Issue by lovelyOK** [xiaorouji/openwrt-package#1696]
## 描述bug
使用PDNSD可以（通过VPS的IPV6地址）正常访问IPV6网站，只是打开网页有点慢，所以我切换到dns2socks模式，这时IPV6网站就都打不开了，譬如IPV6.GOOGLE.COM

**Comment by handsomeji** [comment]
用nslookup 看看是否能解析到ipv6地址，另外我测试了一下dns2socks是可以解析到ipv6的。
