### ISSUE TITLE
今天打包的版本Brook不能更新，提示客户端不适合

### ISSUE THREAD

**Issue by tianiue** [xiaorouji/openwrt-package#1697]
lean源码 内核5.10.89,5.15.12，今天打包的，都是提示同样问题
![QQ截图20220108121303](https://user-images.githubusercontent.com/61725402/148631089-debe5fa1-0d1a-49bd-822c-5ebdf0381cff.png)

**Comment by smallprogram** [comment]
我看了下代码，你编译的时候是不是没选择Brook啊？如果没选建议编译的时候选择上。然后获取更新就没问题了。
rouji大佬写的get_brook_version函数在当前没有Brook的时候会返回空值，导致提示The client file is not suitable for current device.
你先尝试勾选brook编译。

**Comment by handsomeji** [comment]
不是，应该是上次优化的时候，忘记chmod权限了

**Comment by smallprogram** [comment]
> 不是，应该是上次优化的时候，忘记chmod权限了

好吧。那问题应该就是get_bin_version_cache这个函数了。回头我得学学lua如何debug了。

**Comment by handsomeji** [comment]
Fix.
