### ISSUE TITLE
使用自建V2ray节点上网，可以正常代理上网；但是局域网内所有电脑无法访问自建节点本身

### ISSUE THREAD

**Issue by chanfried** [xiaorouji/openwrt-package#1700]
## 描述bug
使用自建V2ray节点上网，可以正常代理上网；但是局域网内所有电脑无法访问自建节点本身。

使用自建节点的域名无法访问或者PING通，但是使用IP地址是正常访问及PING。

![Untitled-1](https://user-images.githubusercontent.com/1514920/148678259-ce907422-0392-43d1-aef8-e565f6c7d6d2.png)
![Untitled-2](https://user-images.githubusercontent.com/1514920/148678262-1962e18c-914c-4f82-9cdc-9c7c337e4554.png)
![Untitled-3](https://user-images.githubusercontent.com/1514920/148678298-536dfb4b-5cd9-4cf1-9c5f-96e0c31e26ee.png)
![Untitled-4](https://user-images.githubusercontent.com/1514920/148678437-a84fdd43-6f0f-4238-bb70-26575fd0c5fa.png)

执行 “DNS”下的 “ClEARIPSET"后可以暂时解决该问题，但是运行一段时间后，又出现自建节点域名无法访问。

**Comment by handsomeji** [comment]
`cat /var/dnsmasq.d/passwall/10-vpsiplist_host.conf`
`nslookup 节点域名`

**Comment by chanfried** [comment]
![Untitled](https://user-images.githubusercontent.com/1514920/148863880-2e82a626-62f6-4a5b-a421-3ede5517e0ba.png)
昨天上午刚使用了最新版本的代码版本，昨天是正常的。今天早上问题复现。
@xiaorouji

**Comment by chanfried** [comment]
![Untitled](https://user-images.githubusercontent.com/1514920/148867673-e131d403-8033-418c-bdd4-3258e00f4d86.png)
从软路由后的Win7系统，运行nslookup的输出。其中240e:3a1:ec5... 是我软路由拨号WAN的IPV6

**Comment by chanfried** [comment]
![Untitled](https://user-images.githubusercontent.com/1514920/149093536-8e85b3ba-6a27-4edf-8a72-aa7e7049c897.png)
![Untitled1](https://user-images.githubusercontent.com/1514920/149094145-3b7a9b79-4f0d-4093-9653-7b8af060ac4e.png)

dnsmasq添加日志后，今天问题复现，nslookup VPS域名，直连域名，代理域名 dnsmasq日志。

**Comment by chanfried** [comment]
其中的 61.147.37.1 应该是电信运营商的DNS IP

**Comment by chanfried** [comment]
继续排查

less /tmp/dnsmasq.d/passwall/11-direct_host.conf

![image](https://user-images.githubusercontent.com/1514920/149162011-3a2881a4-901f-4097-aa08-91f1bd3b9720.png)

发现问题了了，DNS端口使用的是5053,5054。

 netstat -ltuen | grep 53
![image](https://user-images.githubusercontent.com/1514920/149162521-7e7634fe-1513-481f-8e27-849f4448ff47.png)

netstat -ltuen | grep 53
![image](https://user-images.githubusercontent.com/1514920/149162597-cbf7fa78-9fcd-432e-942d-bc54860e7ebe.png)

也就是说，我这边DNS端口是53，但是这里的配置文件用的是5053/5054；所以导致 10-vpsiplist_host.conf 和 11-direct_host.conf 内的域名全部无法解析。

执行passwall 中的 RESETIPSET
![image](https://user-images.githubusercontent.com/1514920/149163101-8a9f8caf-4ab3-4bf8-a70f-2511f211cb0b.png)

再次查看这两个配置文件
less 11-direct_host.conf
![image](https://user-images.githubusercontent.com/1514920/149163290-918c676a-63e7-487b-9300-f397400fef06.png)

此时DNS的端口是正确的，DNS解析正常

但是运行一段时间后10-vpsiplist_host.conf 和 11-direct_host.conf 的DNS端口再次修改了5053/5054，麻烦大佬们分析一下是谁修改了这2个文件，并重新启动了dnsmasql

**Comment by handsomeji** [comment]
估计是 https-dns-proxy
请找到并关闭

**Comment by chanfried** [comment]
![image](https://user-images.githubusercontent.com/1514920/149177769-ed4f0e9d-3c44-48ba-a56d-010d8390d0c2.png)
奇怪了，我这边没有安装该包。

**Comment by handsomeji** [comment]
恢复passwall配置重新配置试下

**Comment by chanfried** [comment]
> 恢复passwall配置重新配置试下

恢复后端口正常了，今天发现又复现了
less less 11-direct_host.conf
![image](https://user-images.githubusercontent.com/1514920/149248974-0e344bae-2772-4b81-b33f-7f37915d8e80.png)
其中 61.147.37.1 和 218.2.135.1 是电信运营商的DNS地址。
如果手动将61.147.37.1 和 218.2.135.1 修改为127.0.0.1后,
/etc/init.d/dnsmasq restart
域名解析正常。
但是一段时间后，11-direct_host.conf中的DNS地址又恢复到了61.147.37.1 和 218.2.135.1，

**Comment by chanfried** [comment]
继续。。。
发现一个奇怪的现象，只要passwall启动，使用114域名服务器，无法解析到域名
![image](https://user-images.githubusercontent.com/1514920/149254250-97b13903-2238-45e9-9459-7d1d57e55193.png)

passwall停止后，正常。
![image](https://user-images.githubusercontent.com/1514920/149254327-97d6ac65-21b2-431b-9d96-0d40bda63720.png)

**Comment by handsomeji** [comment]
换固件

**Comment by pypykim** [comment]
> 换固件

我用的官方固件23.05

**Comment by pypykim** [comment]
> 继续排查
> 
> less /tmp/dnsmasq.d/passwall/11-direct_host.conf
> 
> ![image](https://user-images.githubusercontent.com/1514920/149162011-3a2881a4-901f-4097-aa08-91f1bd3b9720.png)
> 
> 发现问题了了，DNS端口使用的是5053,5054。
> 
> netstat -ltuen | grep 53 ![image](https://user-images.githubusercontent.com/1514920/149162521-7e7634fe-1513-481f-8e27-849f4448ff47.png)
> 
> netstat -ltuen | grep 53 ![image](https://user-images.githubusercontent.com/1514920/149162597-cbf7fa78-9fcd-432e-942d-bc54860e7ebe.png)
> 
> 也就是说，我这边DNS端口是53，但是这里的配置文件用的是5053/5054；所以导致 10-vpsiplist_host.conf 和 11-direct_host.conf 内的域名全部无法解析。
> 
> 执行passwall 中的 RESETIPSET ![image](https://user-images.githubusercontent.com/1514920/149163101-8a9f8caf-4ab3-4bf8-a70f-2511f211cb0b.png)
> 
> 再次查看这两个配置文件 less 11-direct_host.conf ![image](https://user-images.githubusercontent.com/1514920/149163290-918c676a-63e7-487b-9300-f397400fef06.png)
> 
> 此时DNS的端口是正确的，DNS解析正常
> 
> 但是运行一段时间后10-vpsiplist_host.conf 和 11-direct_host.conf 的DNS端口再次修改了5053/5054，麻烦大佬们分析一下是谁修改了这2个文件，并重新启动了dnsmasql

同样的问题， 然后网路就挂了

**Comment by pypykim** [comment]
> 继续排查
> 
> less /tmp/dnsmasq.d/passwall/11-direct_host.conf
> 
> ![image](https://user-images.githubusercontent.com/1514920/149162011-3a2881a4-901f-4097-aa08-91f1bd3b9720.png)
> 
> 发现问题了了，DNS端口使用的是5053,5054。
> 
> netstat -ltuen | grep 53 ![image](https://user-images.githubusercontent.com/1514920/149162521-7e7634fe-1513-481f-8e27-849f4448ff47.png)
> 
> netstat -ltuen | grep 53 ![image](https://user-images.githubusercontent.com/1514920/149162597-cbf7fa78-9fcd-432e-942d-bc54860e7ebe.png)
> 
> 也就是说，我这边DNS端口是53，但是这里的配置文件用的是5053/5054；所以导致 10-vpsiplist_host.conf 和 11-direct_host.conf 内的域名全部无法解析。
> 
> 执行passwall 中的 RESETIPSET ![image](https://user-images.githubusercontent.com/1514920/149163101-8a9f8caf-4ab3-4bf8-a70f-2511f211cb0b.png)
> 
> 再次查看这两个配置文件 less 11-direct_host.conf ![image](https://user-images.githubusercontent.com/1514920/149163290-918c676a-63e7-487b-9300-f397400fef06.png)
> 
> 此时DNS的端口是正确的，DNS解析正常
> 
> 但是运行一段时间后10-vpsiplist_host.conf 和 11-direct_host.conf 的DNS端口再次修改了5053/5054，麻烦大佬们分析一下是谁修改了这2个文件，并重新启动了dnsmasql

安装https-dns-proxy， 转发到这里吧 @ @
