### ISSUE TITLE
01.10最新源码显示运行正常但无法解析DNS

### ISSUE THREAD

**Issue by nantayo** [xiaorouji/openwrt-package#1702]
## 描述bug
拉取最新源码编译的passwall插件，使用与稍老一些的4.44版完全一致的设置。菜单中显示正常工作，但无法打开外网，观察浏览器提示为找不到IP地址，应该是DNS没有正确解析。

## 你想要实现的目的
希望插件正常解析DNS

## 日志信息
从网口上线开始的系统日志如下：
Mon Jan 10 14:32:31 2022 daemon.notice netifd: Network device 'eth0' link is up
Mon Jan 10 14:32:31 2022 daemon.notice netifd: Interface 'lan' has link connectivity
Mon Jan 10 14:32:31 2022 kern.info kernel: [   29.912026] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
Mon Jan 10 14:32:31 2022 kern.info kernel: [   29.912059] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S60dnsforwarder: dnsforwarder running pid is
Mon Jan 10 14:32:40 2022 user.notice The: pid of dnsforwarder is /var/run/dnsforwarder/dns.pid
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Found user 'nobody' (UID 65534) and group 'nogroup' (GID 65534).
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Successfully dropped root privileges.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: avahi-daemon 0.8 starting up.
Mon Jan 10 14:32:40 2022 daemon.warn avahi-daemon[1791]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: No service file found in /etc/avahi/services.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::a099:63ff:fecb:7abc.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: New relevant interface eth0.IPv6 for mDNS.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.3.101.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: New relevant interface eth0.IPv4 for mDNS.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: New relevant interface lo.IPv6 for mDNS.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: New relevant interface lo.IPv4 for mDNS.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Network interface enumeration completed.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Registering new address record for fe80::a099:63ff:fecb:7abc on eth0.*.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Registering new address record for 192.168.3.101 on eth0.IPv4.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Registering new address record for ::1 on lo.*.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Registering new address record for 127.0.0.1 on lo.IPv4.
Mon Jan 10 14:32:40 2022 daemon.info avahi-daemon[1791]: Registering HINFO record with values 'AARCH64'/'LINUX'.
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S95done: irq name:eth0, irq:29, affinity: 8
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S95done: irq name:xhci-hcd:usb1, irq:48, affinity: 4
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S95done: Set the rps cpu mask of eth0 to 0x3
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S96led: setting up led n1:white:status
Mon Jan 10 14:32:40 2022 daemon.notice procd: /etc/rc.d/S99dnsfilter: 2022-01-10 14:32:40 [Download Subscribe Rules...]
Mon Jan 10 14:32:41 2022 daemon.info avahi-daemon[1791]: Server startup complete. Host name is OpenWrt.local. Local service cookie is 2691132002.
Mon Jan 10 14:43:37 2022 daemon.err wsdd2: samba36/4 or ksmbd is not running, can't start wsdd2!
Mon Jan 10 14:43:45 2022 daemon.notice procd: /etc/rc.d/S99zzz_passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 771: ip6tables: not found
Mon Jan 10 14:43:46 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon Jan 10 14:43:46 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon Jan 10 14:43:46 2022 daemon.info procd: - init complete -
Mon Jan 10 14:43:49 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon Jan 10 14:43:49 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon Jan 10 14:43:57 2022 daemon.info procd: Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

## 截图
![1](https://user-images.githubusercontent.com/77558823/148727368-319740d4-ed38-4d0b-b3a3-3cbef56699a4.png)
![异常](https://user-images.githubusercontent.com/77558823/148727386-a0bbeaac-d252-4da6-920a-ced21618ad2b.png)

## 系统相关信息
插件版本共使用过4.44，4.45，4.46。并且同样使用着Xray1.5.2，以及Haproxy4.11。
openwrt内核同为5.10.90，架构为arm64-v8a，机型为斐讯N1。

## 其他相关信息
我在三个版本的passwall中使用完全一致的设置，备份+恢复配置文件以及手动重新设置均尝试过。三个版本显示同样的正常工作，然而4.44可以正常访问外网，4.45，4.46均无法解析DNS。

**Comment by nantayo** [comment]
请问2022年1月以来的更新是否更改了某些重要的默认选项？以及我还需要在哪里进一步查询哪些debug信息？

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/bebd9b0b47bec9cd6ea805ef04ec4dd6b1351dfa

**Comment by nantayo** [comment]
> [bebd9b0](https://github.com/xiaorouji/openwrt-passwall/commit/bebd9b0b47bec9cd6ea805ef04ec4dd6b1351dfa)

谢谢回复，不过能否指点一下应该怎样修改配置文件？尝试订阅之后在config里删除所有节点的alterId，仍然不行

**Comment by handsomeji** [comment]
`⚠️ VMESS AEAD 将在 2022 年 1 月 1 日强制启用 请注意更新服务端 移除 alterId 参数`
最好的方案就是让机场升级
实在没办法就fork此源码，然后 `git revert bebd9b0b47bec9cd6ea805ef04ec4dd6b1351dfa`
