### ISSUE TITLE
DNS功能能否考虑下添加mosdns的支持？

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-package#1707]
[mosdns](https://github.com/IrineSistiana/mosdns)
[mosdns wiki](https://github.com/IrineSistiana/mosdns/wiki)

![image](https://user-images.githubusercontent.com/45598380/148865744-ea94df25-aa07-4f1c-8c12-f865f446a160.png)
对IPV6的处理，有这种更高级的模式，优先反馈IPV4，并不是简单粗爆的直接过滤IPV6查询，不会过滤纯IPV6的查询:)

**Comment by hplee0120** [comment]
https://github.com/QiuSimons/openwrt-mos
建议自己套娃 ，没必要集成

**Comment by badgv** [comment]
> https://github.com/QiuSimons/openwrt-mos 建议自己套娃 ，没必要集成

好的，这个问题可以关了

**Comment by jliveusa** [comment]
套娃遇到问题，op重启会出现mosdns与passwall的启动顺序问题，passwall虽然启动，但无法连通Google等外网，重启passwall方可解决
