### ISSUE TITLE
PPPoE 拨号情况下，wan 口重连会导致 passwall 无法工作

### ISSUE THREAD

**Issue by sbwml** [xiaorouji/openwrt-package#1719]
## 描述bug
PPPoE 拨号情况下，wan 口重连会导致 passwall 无法工作。
正常情况下运营商每隔几天会变更一次IP地址，wan口会重新连接，passwall 将无法访问国外所有IP或网站，国内站点则正常。

## 复现步骤
1、停止 ```WAN``` 接口
2、重启 ```WAN``` 接口，问题复现

## 日志信息
/cgi-bin/luci/admin/services/passwall/get_redir_log?proto=tcp 日志

2022/01/15 09:52:24 [Info] [2779250791] app/dispatcher: sniffed domain: www.google.com
2022/01/15 09:52:24 [Info] [2779250791] app/dispatcher: taking detour [default] for [tcp:www.google.com:443]
2022/01/15 09:52:24 [Info] [2779250791] common/mux: dispatching request to tcp:172.217.31.228:443
2022/01/15 09:52:24 10.0.0.228:62193 accepted tcp:172.217.31.228:443 [default]
2022/01/15 09:52:27 [Info] transport/internet/websocket: creating connection to tcp:appnode.cooluc.com:443
2022/01/15 09:52:27 [Debug] transport/internet: dialing to tcp:appnode.cooluc.com:443
2022/01/15 09:52:27 [Debug] [2022615812] proxy/dokodemo: processing connection from: 172.29.147.158:41912
2022/01/15 09:52:27 [Info] [2022615812] proxy/dokodemo: received request for 172.29.147.158:41912
2022/01/15 09:52:27 [Debug] [2009336735] proxy/dokodemo: processing connection from: 172.29.147.158:48830
2022/01/15 09:52:27 [Info] [2009336735] proxy/dokodemo: received request for 172.29.147.158:48830
2022/01/15 09:52:27 [Info] [2009336735] app/dispatcher: taking detour [default] for [tcp:9.9.9.9:853]
2022/01/15 09:52:27 172.29.147.158:48830 accepted tcp:9.9.9.9:853 [default]
2022/01/15 09:52:27 [Info] [2009336735] common/mux: dispatching request to tcp:9.9.9.9:853
2022/01/15 09:52:27 172.29.147.158:41912 accepted tcp:8.8.4.4:853 [default]
2022/01/15 09:52:27 [Info] [2022615812] app/dispatcher: taking detour [default] for [tcp:8.8.4.4:853]
2022/01/15 09:52:27 [Info] [2022615812] common/mux: dispatching request to tcp:8.8.4.4:853
2022/01/15 09:52:27 [Debug] [2349909870] proxy/dokodemo: processing connection from: 10.0.0.228:62194
2022/01/15 09:52:27 [Info] [2349909870] proxy/dokodemo: received request for 10.0.0.228:62194
2022/01/15 09:52:27 [Info] [2349909870] app/dispatcher: taking detour [Telegram] for [tcp:91.108.56.183:443]
2022/01/15 09:52:27 [Info] [2349909870] common/mux: dispatching request to tcp:91.108.56.183:443
2022/01/15 09:52:27 10.0.0.228:62194 accepted tcp:91.108.56.183:443 [Telegram]
2022/01/15 09:52:27 [Debug] [91411756] proxy/dokodemo: processing connection from: 10.0.0.228:62195
2022/01/15 09:52:27 [Info] [91411756] proxy/dokodemo: received request for 10.0.0.228:62195
2022/01/15 09:52:27 [Info] [91411756] app/dispatcher: sniffed domain: 91.108.56.183
2022/01/15 09:52:27 [Info] [91411756] app/dispatcher: taking detour [Telegram] for [tcp:91.108.56.183:80]
2022/01/15 09:52:27 [Info] [91411756] common/mux: dispatching request to tcp:91.108.56.183:80
2022/01/15 09:52:27 10.0.0.228:62195 accepted tcp:91.108.56.183:80 [Telegram]
2022/01/15 09:52:27 [Debug] [2619187603] proxy/dokodemo: processing connection from: 172.29.147.158:62985
2022/01/15 09:52:27 [Info] [2619187603] proxy/dokodemo: received request for 172.29.147.158:62985
2022/01/15 09:52:27 [Info] [2619187603] app/dispatcher: taking detour [default] for [tcp:1.1.1.1:53]
2022/01/15 09:52:27 [Info] [2619187603] common/mux: dispatching request to tcp:1.1.1.1:53
2022/01/15 09:52:27 172.29.147.158:62985 accepted tcp:1.1.1.1:53 [default]

## 截图
![](https://user-images.githubusercontent.com/16485166/149617697-dbb4fb42-1687-4ec7-9ffc-edcc6e4d4b53.png)

## 系统相关信息
passwall版本：4.47

**Comment by smallprogram** [comment]
**经过测试，无法复现该问题，请确认你是否搞了些什么DNS的特殊设置，或者特殊的代理模式，再或者使用了特殊的OP固件。**


![dfd](https://user-images.githubusercontent.com/6050360/149622686-95ccca26-9e96-4475-89a9-e90f0ba6a86f.gif)

**Comment by sbwml** [comment]
> 

是我自己的问题，dnsmasq 使用了自定义解析文件导致
