### ISSUE TITLE
希望保留“DNS 过滤模式”中的“不过滤”选项

### ISSUE THREAD

**Issue by rabbitrogi** [xiaorouji/openwrt-package#1725]
如题

虽然可以使用“通过UDP节点请求DNS”，然后选本机原来的DNS，并且关闭Chinadns-ng来替代，但是仍然不如“不过滤”更加清楚。

**Comment by adwzlad** [comment]
支持。如题设置，通过代理节点上网全部网站都没法过滤广告

**Comment by adwzlad** [comment]
不知道是不是没法指定DNS端口导致

**Comment by LevineWoo** [comment]
请问不过滤的话是不是由路由wan的DNS来判断呢？
