### ISSUE TITLE
希望增强下Xray的DNS设置

### ISSUE THREAD

**Issue by EsuRt** [xiaorouji/openwrt-package#1730]
## 你的功能请求是否与问题有关？ 请描述。

在关闭ChinaDNS-NG的情况下，设置Xray的DNS为`https://1.1.1.1/dns-query`，通过DNS泄露测试网站(`https://browserleaks.com/dns`)测试，发现存在DNS泄露，测试所得的DNS服务器均为国内服务器。关闭ChinaDNS-NG的原因是因为黑白名单并不完善，且貌似不支持DOH，由于v2ray的DNS比较完善，一直用的是v2ray的方案，在PC上已经能够在国内外DNS分流的前提下避免DNS泄露。

## 描述你想要的解决方案 

在Xray的DNS下增设解析直连域名的DNS服务器和被代理域名的DNS解析服务器，DOH可直接使用IP形式，比如`https://1.1.1.1/dns-query` ，而非`https://cloudflare-dns.com/dns-query`，避免再次解析cloudflare-dns.com。同时，DNS增加skipFallback和disableFallback的设置，启用后，能够避免国外域名因某些原因无法通过国外DNS解析时，转而使用DNS列表中的国内服务器解析，从而再次造成泄露。
参考：
https://www.v2fly.org/config/dns.html#dns-%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B
https://xtls.github.io/Xray-docs-next/config/dns.html#dns-%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B
目前版本后台生成的配置文件中DNS虽然只有`https://1.1.1.1/dns-query`，但仍出现了泄露，原因不明。

## 描述你考虑过的替代方案

暂时没有想到替代方案

## 附加上下文

![Snipaste_2022-01-21_22-08-46](https://user-images.githubusercontent.com/15177069/150545283-ded93e9b-1840-4b87-bf77-ebb9fa285e07.jpg)
![Snipaste_2022-01-21_22-13-10](https://user-images.githubusercontent.com/15177069/150545314-e33e17bb-30fb-4941-8316-e713924922c4.jpg)

**Comment by Pacio** [comment]
其他的过滤模式也有这些问题？

**Comment by EsuRt** [comment]
> 其他的过滤模式也有这些问题？

几种过滤模式测试出来都有dns泄露的问题，因为主要用DOH，所以重点放在了Xray

**Comment by xcyll** [comment]
https://browserleaks.com/dns这个网站测试时有如下提示
This test attempts to resolve 100 randomly generated domain names asynchronously, 50 with A record (IPv4-only) and 50 with both A and AAAA records (IPv4+IPv6).
这100个域名当中 maybe...（***域名不在封锁列表，故本地的dns参与了解析） 所以显示了china mobile
个人理解 不一定对

**Comment by EsuRt** [comment]
> [https://browserleaks.com/dns这个网站测试时有如下提示](https://browserleaks.com/dns%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E6%B5%8B%E8%AF%95%E6%97%B6%E6%9C%89%E5%A6%82%E4%B8%8B%E6%8F%90%E7%A4%BA) This test attempts to resolve 100 randomly generated domain names asynchronously, 50 with A record (IPv4-only) and 50 with both A and AAAA records (IPv4+IPv6). 这100个域名当中 maybe...（***域名不在封锁列表，故本地的dns参与了解析） 所以显示了china mobile 个人理解

测试的域名确实不在列表之内，passwall可能默认不在列表之内的使用国内dns，但生成的配置文件中却只有`https://1.1.1.1/dns-query`，按照v2ray的处理逻辑，应该全部走cloudflare的dns，不应该出现国内dns，所以不知道是哪种情况。

**Comment by xcyll** [comment]
passwall基于dnsmasq 不在封锁的列表 是走本地dns解析

**Comment by EsuRt** [comment]
应该是这样，那有没有其他可以实现国内外分流且支持doh的方案？

**Comment by xcyll** [comment]
你试试这个
https://whoer.net/zh/dns-leak-test
且把whoer.net加入代理列表 应该可以看到只显示cloudflare的dns

**Comment by xcyll** [comment]
mosdns

**Comment by EsuRt** [comment]
我把域名加入后测试过，这样是行的。不过实际使用时，域名太多了，全部加入太麻烦了，就想默认使用国外dns，直连的就用国内dns。我待会试试mosdns，谢谢。

**Comment by EsuRt** [comment]
mosdns测试了下，结果显示的仍有国内的地址，但不全是，不知道是不是配置错了？dnsmasq设置了转发到127.0.0.1#5335。
```
log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - _single_flight
        - main_sequence
      server:
        - protocol:        udp
          addr:            '127.0.0.1:5335'
        - protocol:        tcp
          addr:            '127.0.0.1:5335'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _end
        - if:
            - query_is_local_domain
          exec:
            - forward_local
            - _end
        - if:
            - query_is_non_local_domain
            - '!_query_is_common'
          exec:
            - _prefer_ipv4
            - forward_remote
            - _end
        - primary:
            - _prefer_ipv4
            - forward_remote
          fast_fallback:   150
          always_standby:  true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:  
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          idle_timeout:    8
          max_conns:       1
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '175.24.219.66:443'
          idle_timeout:    59
          max_conns:       1  


  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'https://cloudflare-dns.com/dns-query'
          dial_addr:       '1.1.1.1:443'
          idle_timeout:    60
          max_conns:       1
        - addr:            'https://dns.google/dns-query'
          dial_addr:       '8.8.8.8:443'
          idle_timeout:    9
          max_conns:       1

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./serverlist.txt'
```

**Comment by xcyll** [comment]
嗯 好像漏了未知域名的分流

**Comment by xcyll** [comment]
配置有遗漏之处
primary下一行
未知域名的分流 具体解析流程方案 没有

**Comment by xcyll** [comment]
你前面配置的是已知的本地域名 & 已知的非本地域名解析方案

**Comment by EsuRt** [comment]
官方的配置文件中也是这样写的，把dnsmap中的忽略解析文件勾选后，使用passwall的pdnsd过滤，并指定127.0.0.1:5335后，测试下来没有泄露。不过临时关闭就麻烦了，需要重置dnsmap的设置，下次启用还要重新设置，暂时先过渡下吧，谢谢。
![1](https://user-images.githubusercontent.com/15177069/150635362-95448f72-0303-493d-8224-bdac7d3d75ad.jpg)

**Comment by xcyll** [comment]
嗯嗯
 # 剩下的未知域名用 IP 分流。详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - forward_local     # 本地服务器为主。
            - if:
                - '!response_has_local_ip'  # 过滤掉非本地的 IP。
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
   官方针对未知域名首先是以本地服务器为主 你的配置中此处好像漏了

**Comment by EsuRt** [comment]
确实，我的配置文件有问题，我再改下。

**Comment by Pacio** [comment]
cmd输入ping whoami.akamai.net -n 1查看返回结果是否含有本地ip,如果没有任何本地ip，一般就可以了
另外说一下这个东西只是一种心理安慰，对于专业的那些部门来说，想找到你的真实ip其实只是花费时间多少而已

**Comment by EsuRt** [comment]
嗯，现在没问题了，其实就是图个心理安慰。

**Comment by handsomeji** [comment]
你的需求可能是想 默认走国外DNS，chnlist+chnroute走国内DNS吧。

**Comment by EsuRt** [comment]
> 你的需求可能是想 默认走国外DNS，chnlist+chnroute走国内DNS吧。

大佬猜的没错，我默认都是走国外DNS，已有的国内域名就走国内DNS，特殊的通过自定义设置实现。

**Comment by mhycy** [comment]
问题不在 xray 的配置上
在 passwall在底层的实现上，无论是否使用 xray 进行分流
DNS 的解析都是依赖于 `规则列表` 与 xray 配置下的 `domain:xxxx` 配置进行策略（*不支持 geosite*）

这时候产生的问题有 2
1、xray 的分流规则严格意义上并不完全起效，除非 xray 只有基于 geoip 的配置
      因为 xray 本身没法基于域名产生`域名<-->IP` 绑定清单 劫持并策略 tproxy 过来的请求（tproxy 不带域名）
2、DNS 解析会被污染，因为生成 dnsmasq 配置文件的时候，只有`规则列表`，`gfwlist`，xray 下的`domain: xxxx`这类设置可由境外服务解析

另 xray 本身的 DNS 查询也存在 bug
xray 的 dns 请求并不会发送到境外服务器进行查询，因为 dns 项目缺少 proxySettings 设置

综上，修复办法如下（解决境外访问问题）
1、dnsmasq 使用 xray 作为默认 dns 服务器
2、（不建议）可选分流，解析 xray 配置 为 direct 条目下的 geosite 信息，并加入清单使用国内服务器进行解析
（这个操作会导致 xray 的按优先级策略失效，并不建议使用）
3、（建议）可选分流的另一个操作是，单独增加规则，把 chndns 相关的 geosite 条目写入到 xray 的 dns 配置项，利用 xray 内部的 dns 进行基于 geosite 的 dns 策略

**Comment by Pacio** [comment]
👍👍👍👍👍👍👍👍
前段时间用pw确实各种莫名其妙，希望作者从底层逻辑上解决一下

**Comment by Pacio** [comment]
> 问题不在 xray 的配置上 在 passwall在底层的实现上，无论是否使用 xray 进行分流 DNS 的解析都是依赖于 `规则列表` 与 xray 配置下的 `domain:xxxx` 配置进行策略（_不支持 geosite_）
> 
> 这时候产生的问题有 2 1、xray 的分流规则严格意义上并不完全起效，除非 xray 只有基于 geoip 的配置 因为 xray 本身没法基于域名产生`域名<-->IP` 绑定清单 劫持并策略 tproxy 过来的请求（tproxy 不带域名） 2、DNS 解析会被污染，因为生成 dnsmasq 配置文件的时候，只有`规则列表`，`gfwlist`，xray 下的`domain: xxxx`这类设置可由境外服务解析
> 
> 另 xray 本身的 DNS 查询也存在 bug xray 的 dns 请求并不会发送到境外服务器进行查询，因为 dns 项目缺少 proxySettings 设置
> 
> 综上，修复办法如下（解决境外访问问题） 1、dnsmasq 使用 xray 作为默认 dns 服务器 2、（不建议）可选分流，解析 xray 配置 为 direct 条目下的 geosite 信息，并加入清单使用国内服务器进行解析 （这个操作会导致 xray 的按优先级策略失效，并不建议使用） 3、（建议）可选分流的另一个操作是，单独增加规则，把 chndns 相关的 geosite 条目写入到 xray 的 dns 配置项，利用 xray 内部的 dns 进行基于 geosite 的 dns 策略

👍👍👍👍👍👍👍👍
前段时间用pw确实各种莫名其妙，希望作者从底层逻辑上解决一下
