### ISSUE TITLE
passwall  lede版本里面更新组建更新v2ray后版本变成无

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#1735]
lede版本默认带的v2ray内核是4.44，到组件更新里点击更新显示有5.03版本，点击更新成功后，版本变成了无，实际到/usr/bin里查询还是4.44

![image](https://user-images.githubusercontent.com/20067401/150620538-4111e74a-f023-43fc-9ddb-bcdedcfff878.png)

**Comment by smallprogram** [comment]
恢复默认配置

**Comment by lanyucomputer** [comment]
不要更新，一更新就是这样的
