### ISSUE TITLE
劫持ICMP (PING)功能无效

### ISSUE THREAD

**Issue by Diffused7245** [xiaorouji/openwrt-package#1739]
## 描述bug

劫持ICMP (PING)功能对IPv6无效
## 复现步骤

打开高级设置，劫持ICMP，GFW列表模式，仅对v4生效。

## 你想要实现的目的

IPv6 Ping也被成功劫持，小于1ms

## 截图

![image](https://user-images.githubusercontent.com/76898556/150677283-f24f9bfb-a00f-4dcb-ab1a-63e6854399d5.png)
![20220123_200237](https://user-images.githubusercontent.com/76898556/150677439-5110627c-79c4-4d9f-850b-c558c075f4cb.jpg)

## 系统相关信息

Passwall 4.48

**Comment by smallprogram** [comment]
没有IPv6的网络，没办法测试。。。。

**Comment by tritu** [comment]
Have you enabled IPv6 proxy?

**Comment by Diffused7245** [comment]
> Have you enabled IPv6 proxy?

Yes, my server is support IPv6 too, and proxy looks normal.
ICMPing is failed, but TCPing can success.
![image](https://user-images.githubusercontent.com/76898556/150704882-837f6697-8ced-45cf-a355-72ff4f64bc21.png)

![image](https://user-images.githubusercontent.com/76898556/150704691-f17b8158-3b82-4ae3-9725-937738f9a21d.png)
![image](https://user-images.githubusercontent.com/76898556/150704790-fcca0a8f-676b-436a-96b0-6d801f6a308e.png)

**Comment by handsomeji** [comment]
@ShanStone 已在最新源码加入，请更新测试。

**Comment by ShanStone** [comment]
Native IPv6下测试PING正常，需要编译ip6tables-mod-nat
![image](https://user-images.githubusercontent.com/31815718/152793142-080a0530-dde4-45a5-955f-2f1205a02d2d.png)

**Comment by Diffused7245** [comment]
v6解决了，v4又出现个新的bug，TCPING现在正常了，icmp v4又没了😂
路由器两个劫持都开了
![image](https://user-images.githubusercontent.com/76898556/153582646-ea664425-c4ef-4379-943c-61d075c994d2.png)
我以为是ip的问题，换了一楼一开始那个142的，也ping不通，tcping可以。
![image](https://user-images.githubusercontent.com/76898556/153583562-42d2adcc-e215-4c78-9c8e-2ad1249fa66d.png)
而且路由器本身没问题，电脑不通了，全局代理也是这样

**Comment by ShanStone** [comment]
> v6解决了，v4又出现个新的bug，TCPING现在正常了，icmp v4又没了😂
> 路由器两个劫持都开了
> ![image](https://user-images.githubusercontent.com/76898556/153582646-ea664425-c4ef-4379-943c-61d075c994d2.png)
> 我以为是ip的问题，换了一楼一开始那个142的，也ping不通，tcping可以。
> ![image](https://user-images.githubusercontent.com/76898556/153583562-42d2adcc-e215-4c78-9c8e-2ad1249fa66d.png)
> 而且路由器本身没问题，电脑不通了，全局代理也是这样
> 

是不是没开启劫持前进行ping的测试了，如果是可能是连接没释放，尝试清除dns缓存，关掉命令行后等待几分钟再尝试ping
或者有多余设备也可以尝试ping一下

**Comment by handsomeji** [comment]
![image](https://user-images.githubusercontent.com/60100640/153637266-bb453bf4-05b5-4710-9fff-d16b641dd12a.png)

**Comment by Diffused7245** [comment]
貌似还是不成功，目前只有路由器本身可以ping成功，下面的手机电脑都不行。
这次更新后，v6的tcping也不通了……或许我得清理干净文件重0开始新编译一遍再看看？
我用的是原版Openwrt固件，顺便再试试Lienol的那个，记得那个就没问题，但是其它功能不对（比如uhttpd的证书没用），我就刷了原版。

**Comment by Diffused7245** [comment]
又试了试，相同情况下，Lienol固件没问题，但是原版Openwrt就出现上述问题，我用的是原版，昨天晚上编译了新版本，并且重置设置再试，Tcping正常了，icmp v4只有路由器本身能通，下面的设备（电脑手机）都不行，v6的话则一切正常。

**Comment by handsomeji** [comment]
用最新源码试下

**Comment by Diffused7245** [comment]
欧克了，此贴终结。
三星手机国行ROM是靠谷歌主域名能否ping通来判断是否限制谷歌服务自启动的，能响应的话，推送服务收消息就正常了，感谢大佬！（不过谷歌的FCM就没被墙，是三星自己搞的这个限制）
看来这两个固件有区别的地方多了哇。
![image](https://user-images.githubusercontent.com/76898556/156546304-480d6f2f-091c-4014-b3a5-5cc1ea7e0db5.png)

![image](https://user-images.githubusercontent.com/76898556/156545870-afad9eca-04b8-46fa-bf96-7ebcd4860bb2.png)
