### ISSUE TITLE
旁路由模式连接测试一直检测中

### ISSUE THREAD

**Issue by xiaoxintang** [xiaorouji/openwrt-package#1740]
## 描述bug

r4s，lan口旁路由模式。谷歌、github、Instagram连接检测无效，一直在检测中。

百度检测，节点检测，包括ip111.cn都能有预期效果。

手机wifi设置路由器dns为软路由。可以正常科学上网
## 复现步骤

1. 目前只试过r4s的旁路由模式
2. 设置好一切，直接点击测试就可以复现
3. 试过骷髅头编译的固件。试过自己编译的lede，都是一样的效果

## 你想要实现的目的

想要在旁路由模式能够正常测试谷歌，github等
## 日志信息

无错误日志，不知道在哪看
## 截图
![image](https://user-images.githubusercontent.com/24927686/150770795-45a2d3b3-8554-46da-9edd-a5791d3668fe.png)
![image](https://user-images.githubusercontent.com/24927686/150770948-1eb26f4f-1d3c-408f-8a1d-95fa2b44d334.png)

## 系统相关信息

passwall[这里](https://github.com/kenzok8/small-package)的软件包集合。本仓库单独添加src-git也是一样

**Comment by xiaoxintang** [comment]
@smallprogram 大佬看下需要提供什么信息

**Comment by smallprogram** [comment]
@xiaoxintang 看看路由自身代理模式是什么，要不试试[我编译的固件](https://github.com/smallprogram/OpenWrtAction/tags)？我也做过旁路，没遇到过这种情况。

**Comment by xiaorouji** [comment]
发个日志都那么难吗，无论有无错误都要发上来啊

**Comment by badgv** [comment]
目测这玩意儿多半不是BUG，我主路由mikrotik，也是旁路OP，采用主路由策略路由的旁路方式，这测试一点问题没有，我觉得还是先贴个网络环境拓普上来看下

**Comment by xiaoxintang** [comment]
> 目测这玩意儿多半不是BUG，我主路由mikrotik，也是旁路OP，采用主路由策略路由的旁路方式，这测试一点问题没有，我觉得还是先贴个网络环境拓普上来看下
![IMG_20220129_095344](https://user-images.githubusercontent.com/24927686/151642879-0cca29c3-c308-43c9-9fff-1e9ce14cb2f5.jpg)

**Comment by xiaoxintang** [comment]
> @xiaoxintang 看看路由自身代理模式是什么，要不试试[我编译的固件](https://github.com/smallprogram/OpenWrtAction/tags)？我也做过旁路，没遇到过这种情况。

路由自身tcp,udp分别都是与tcp、udp默认代理模式相同（默认的，没有改），固件年后回去试一下，现在在老家

**Comment by xiaoxintang** [comment]
> 发个日志都那么难吗，无论有无错误都要发上来啊

![image](https://user-images.githubusercontent.com/24927686/151645904-0d3a6d95-fd8c-4cde-b6a0-8e53f56c5e70.png)

**Comment by xiaoxintang** [comment]
感觉可能是我的节点的问题，试了一下r4s直接拨号，第一次也无法测试，需要关闭再次开启才可以

**Comment by 2984397010** [comment]
我这里问题和他一样，是因为 /tmp/etc/passwall/UDP.json 和 cat /tmp/etc/passwall/TCP.json 里面订阅的节点少了settings->vnext->users->alterId定义，我参考客户端的配置，加上这个属性改为1就好了
![image](https://user-images.githubusercontent.com/15757022/152638364-dfca87c4-c10b-4d48-adb6-ba2091cb87ae.png)

**Comment by solarflows** [comment]
你是直接代理电脑的流量还是用的switchyomega代理浏览器的流量，如果是后者的话，问题很简单switchyomega匹配域名的时候接管了用来测试连通性的流量，把这个流量交给socks5代理跑外面去了，我之前也有这个问题，设置管理页面的流量全部直连就可以了。
