### ISSUE TITLE
v2ray无法使用，请帮忙看看是哪里出了问题，谢谢！

### ISSUE THREAD

**Issue by aweigz** [xiaorouji/openwrt-package#1745]
官方源码21.02编译（也试过Lienol的openwrt），luci中passwall默认配置，V2RAY版本4.44.0，能成功编译，SSR正常，但是V2RAY无法使用，V2RAY可以正常订阅，Info日志显示如下信息：

V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) OpenWrt (go1.17.6 linux/arm)
A unified platform for anti-censorship.
2022/01/27 14:14:28 [Info] main/jsonem: Reading config: /tmp/etc/passwall/TCP.json
2022/01/27 14:14:28 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1041
2022/01/27 14:14:28 [Warning] V2Ray 4.44.0 started
2022/01/27 14:14:34 [Info] [1534091975] proxy/dokodemo: received request for 14.145.36.203:16078
2022/01/27 14:14:34 [Info] [1534091975] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:34 14.145.36.203:16078 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:34 [Info] [1534091975] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:34 [Info] [2219685342] proxy/dokodemo: received request for 14.145.36.203:24634
2022/01/27 14:14:34 [Info] [2219685342] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:34 14.145.36.203:24634 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:34 [Info] [2219685342] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:34 [Info] [1534091975] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:34 [Info] [2219685342] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:35 [Info] [2219685342] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2022/01/27 14:14:35 [Info] [2219685342] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2022/01/27 14:14:35 [Info] [2523311026] proxy/dokodemo: received request for 14.145.36.203:26245
2022/01/27 14:14:35 [Info] [1534091975] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2022/01/27 14:14:35 [Info] [1534091975] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2022/01/27 14:14:35 [Info] [2523311026] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:35 [Info] [2523311026] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:35 14.145.36.203:26245 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:35 [Info] [2523311026] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:35 [Info] [635129028] proxy/dokodemo: received request for 14.145.36.203:62839
2022/01/27 14:14:35 [Info] [635129028] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:35 14.145.36.203:62839 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:35 [Info] [635129028] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:35 [Info] [635129028] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:35 [Info] [2523311026] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2022/01/27 14:14:35 [Info] [2523311026] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2022/01/27 14:14:36 [Info] [635129028] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2022/01/27 14:14:36 [Info] [635129028] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2022/01/27 14:14:36 [Info] [3049368959] proxy/dokodemo: received request for 14.145.36.203:48102
2022/01/27 14:14:36 [Info] [3049368959] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:36 [Info] [3049368959] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:36 14.145.36.203:48102 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:36 [Info] [3049368959] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:36 [Info] [3049368959] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
2022/01/27 14:14:36 [Info] [3049368959] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2022/01/27 14:14:37 [Info] [396292818] proxy/dokodemo: received request for 14.145.36.203:27440
2022/01/27 14:14:37 [Info] [396292818] app/dispatcher: default route for tcp:1.1.1.1:53
2022/01/27 14:14:37 [Info] [396292818] transport/internet/tcp: dialing TCP to tcp:br-cn-east-cu1.node-fnf.xyz:25082
2022/01/27 14:14:37 14.145.36.203:27440 accepted tcp:1.1.1.1:53 [213913592b834ed0b1b284f55a350ade]
2022/01/27 14:14:37 [Info] [396292818] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:53 via tcp:br-cn-east-cu1.node-fnf.xyz:25082

请问是哪里出了问题？该怎么解决，谢谢！

**Comment by smallprogram** [comment]
去翻翻之前的issue。
