### ISSUE TITLE
做旁路路由时导入SSR信息不全2

### ISSUE THREAD

**Issue by lucktu** [xiaorouji/openwrt-package#1749]
## 描述bug(必填)
使用“导入分享URL”导入信息时，缺少“加密”、“协议”、“混淆”等选项

## 复现步骤(必填)
“节点列表”--“新增”--“导入分享URL”，导入一个SSR的信息，例如下面这样的：
ssr://MTAuMzAuMTAuMjExOjE3MDUwOmF1dGhfYWVzMTI4X21kNTphZXMtMTI4LWN0cjp0bHMx ... ....
然后发现缺少“加密”、“协议”、“混淆”等选项，同时，有时“导出分享URL”也没有反应。

## 你想要实现的目的(必填)
希望导入全面，无需手动填入

## 日志信息(必填！)
此时是没有日志的

## 截图
![001](https://user-images.githubusercontent.com/30952545/151689229-5859a4c2-3976-4810-8131-31c0f8dc77b6.PNG)

## 系统相关信息(必填)
我在ubuntu18（64位）下使用docker版openwrt，这个openwrt时作为旁路路由使用的，安装了这里的 luci-app-passwall 插件（https://github.com/MoetaYuko/openwrt-passwall-build），在 openwrt_19 和 21 里面都不正常，在 openwrt_18 里面正常。测试了这些插件，都是一样的：luci-app-passwall_4.36_all.ipk / luci-app-passwall_4.48_all.ipk（最新）。

## 其他相关信息
最初反馈在这里，那边建议到上游来反馈
https://github.com/MoetaYuko/openwrt-passwall-build/issues/6

**Comment by handsomeji** [comment]
luci不同，一些html元素不同导致。
建议使用旧版luci。
导入链接可直接在 节点列表 - 通过链接添加节点 导入

**Comment by lucktu** [comment]
> luci不同，一些html元素不同导致。 建议使用旧版luci。 导入链接可直接在 节点列表 - 通过链接添加节点 导入

好失望，其实我也说了，这个luci兼容旧版，不兼容新版。暂时用ssr去了
