### ISSUE TITLE
GFW 抽风产生奇怪的问题（UDP/QUIC 协议）

### ISSUE THREAD

**Issue by yk271** [xiaorouji/openwrt-package#1752]
## 描述bug(必填)
这几天发现，Google 搜索 reCAPTCHA 验证页面显示的 IP 地址为本地 IP（即国内 IP），导致无法正常进行人机验证。
经过排查，发现 Google 搜索的 IP 地址未被 GFW 阻断，UDP 可直连。
部分 YouTube 域名的 IP 也可以直连，但由于 UDP QOS 的原因会导致视频加载缓慢，另外还会出现视频资源请求 403 错误的情况。
所以，如果不开启 UDP 转发，或 UDP 不转发 80,443 端口，且 UDP 连接未被阻断，会产生上述问题。
这里提供三个 IP，且已在后面附上本地 PING 截图、IPIP 国内 PING 截图，2022/02/03 06:18 时测试全国均可 PING 通：
www.google.com [172.217.24.228]
rr5.sn-8xgp1vo-a5me.googlevideo.com [208.194.21.16]
yt3.ggpht.com [172.217.31.1]
更多 IP，同样可 PING 通，未上传截图：
rr2.sn-8xgp1vo-a5me.googlevideo.com [208.194.21.13]
rr3.sn-8xgp1vo-a5me.googlevideo.com [208.194.21.14]
rr4.sn-8xgp1vo-a5me.googlevideo.com [208.194.21.15]

另外，Cloudflare 的 hCaptcha 也有类似的情况，由于使用了 QUIC 协议，IP 可直连，验证页面底部显示的 IP 同样为本地 IP。

开启 80,443 端口 UDP 转发确实可以解决问题，但由于 UDP QOS，请求会很慢，YouTube 视频加载时间明显更长。

目前看来，似乎没有更好的解决办法？

## 复现步骤(必填)
在 Edge InPrivate 模式下打开验证页面的 URL 尝试复现：
https://www.google.com/sorry/index?continue=
第一次请求时，使用了 H2 协议，其中也有部分请求使用了 H3 协议，页面显示的为服务器 IP，详见第一张截图；
第二次请求时，使用了 H3 协议，页面显示的为本地 IP，详见第二张截图。

第三张截图，为 QUIC 协议直连的情况下，YouTube 视频资源请求 403 错误。

## 你想要实现的目的(必填)
暂无

## 日志信息(必填！)
暂无

## 截图
![one](https://user-images.githubusercontent.com/29210205/152245775-25fe21d8-d47c-4211-bb07-e632cfd5de41.png)
![two](https://user-images.githubusercontent.com/29210205/152249153-a01a6284-5572-49fb-89f6-95c9a577f01f.png)
![youtube_403](https://user-images.githubusercontent.com/29210205/152248564-5f24dd14-d7a2-4b54-801e-ecc81d865f31.png)

![ping](https://user-images.githubusercontent.com/29210205/152246737-fe7d5e99-d31e-411a-b338-28612679a9a7.png)
![ipip_ping_google](https://user-images.githubusercontent.com/29210205/152246745-97838cf4-b2e6-4dfb-904f-6c8e2e1a748b.png)
![ipip_ping_youtube](https://user-images.githubusercontent.com/29210205/152246752-4e57f6ae-cd49-4d18-acc1-97af699d940e.png)
![ipip_ping_yt](https://user-images.githubusercontent.com/29210205/152248016-ab8f0c78-e068-4dba-88bf-4c134a091b25.png)

## 系统相关信息(必填)
passwall 版本 4.48-2
中国列表以外模式
远程 DNS 8.8.8.8
pdnsd 通过TCP节点请求DNS
缓存解析结果 开启
ChinaDNS-NG 开启

**Comment by smallprogram** [comment]
将uri加代理列表，或者用非大陆ip代理方式。

**Comment by BGzErol** [comment]
udp代理填只代理443，然后随便创建个不可用的节点应用到udp代理，把quic断了试试？

**Comment by yk271** [comment]
> udp代理填只代理443，然后随便创建个不可用的节点应用到udp代理，把quic断了试试？

可以解决问题，不过 UDP 转发就不能正常使用了，如果能单独有个”UDP 转发阻断端口“的选项就更好了。

**Comment by yk271** [comment]
Instagram 也有类似情况
scontent-hkg4-1.cdninstagram.com [157.240.199.63]
scontent-hkg4-2.cdninstagram.com [157.240.211.63]
![ig](https://user-images.githubusercontent.com/29210205/152694730-2a89ccbb-3dfb-4fb2-9b0a-a47e7191067f.png)

**Comment by BGzErol** [comment]
> > udp代理填只代理443，然后随便创建个不可用的节点应用到udp代理，把quic断了试试？
> 
> 可以解决问题，不过 UDP 转发就不能正常使用了，如果能单独有个”UDP 转发阻断端口“的选项就更好了。

你想应用的节点是xray的vless或者trojan吗，是的话就把xtls打开，选一个没有udp443后缀的选项，也能达到禁用quic的目的。自建节点的话也可以去把vps的udp443端口给封了，彻底禁用

**Comment by handsomeji** [comment]
试试全局禁用QUIC，在防火墙 自定义规则里面加入
`iptables -t mangle -I PREROUTING -p udp -m multiport --dport 80,443 -j DROP `

**Comment by yk271** [comment]
> 试试全局禁用QUIC，在防火墙 自定义规则里面加入 `iptables -t mangle -I PREROUTING -p udp -m multiport --dport 80,443 -j DROP `

可以解决问题，不过全局禁用会不会对国内连接有影响？（字节、腾讯、阿里、快手的 APP 都有使用 QUIC 协议）
是否可以考虑增加一个”UDP 转发屏蔽端口“的选项，只禁用国外的 QUIC

**Comment by handsomeji** [comment]
下个版本考虑加入

**Comment by handsomeji** [comment]
试下dev分支
