### ISSUE TITLE
在DNS过滤模式中，可否将原先的“自定义DNS”增加回来

### ISSUE THREAD

**Issue by imtv** [xiaorouji/openwrt-package#1756]
自定义DNS对与本地一些特殊DNS设置很有帮助

**Comment by xcyll** [comment]
![6E852BEC-E691-489D-ABA9-98D2B9B871CF](https://user-images.githubusercontent.com/63227888/152737665-e5a33b7f-f322-47bf-8af0-b32449f77560.jpeg)

**Comment by xcyll** [comment]
合并了

**Comment by xcyll** [comment]
合并了 这里可以添加自定义

**Comment by xcyll** [comment]
合并了
