### ISSUE TITLE
运行/etc/init.d/passwall restart报错

### ISSUE THREAD

**Issue by hexsen929** [xiaorouji/openwrt-package#1762]
root@OpenWrt:~# /etc/init.d/passwall restart
/usr/share/passwall/app.sh: /usr/share/passwall/helper_smartdns.sh: line 208: /etc/init.d/smartdns: not found
awk: can't open 'outf=/tmp/dnsmasq.d/passwall/97-proxy_host-noipv6.conf': No such file or directory
awk: can't open 'outf=/tmp/dnsmasq.d/passwall/98-shunt_host-noipv6.conf': No such file or directory
awk: can't open 'outf=/tmp/dnsmasq.d/passwall/98-shunt_host-noipv6.conf': No such file or directory
awk: can't open 'outf=/tmp/dnsmasq.d/passwall/99-gfwlist-noipv6.conf': No such file or directory
sort: standard output: Broken pipe

是我编译的问题吗？
而且编译好了之后只要使用xray总分流，tcp udp就无法运行。。

**Comment by handsomeji** [comment]
Fix.
分流无法使用请检查是否没有geosite和geoip
