### ISSUE TITLE
官方openwrt编译时，勾选IPv6_Nat，会变成PageKite

### ISSUE THREAD

**Issue by xiexiaosheng** [xiaorouji/openwrt-package#1763]
官方openwrt编译时，勾选IPv6_Nat，会变成PageKite

**Comment by ShanStone** [comment]
无法复现，建议删掉一下编译目录的tmp文件夹，然后再make menuconfig试试

**Comment by snakwu** [comment]
@ShanStone  其实不是变，是passwall直接消失，如果 Network  ---> Firewall  --->ip6tables在没有选上的前提下，再勾选passwall里面的ipv6_net，passwall就会直接消失。

**Comment by fuokgfw** [comment]
我也遇到了，不过保存退出之后再进去又好了
