### ISSUE TITLE
重复添加conf-file /tmp/etc/smartdns/passwall.conf到smartdns的custom.conf

### ISSUE THREAD

**Issue by Hotwill** [xiaorouji/openwrt-package#1764]
https://github.com/xiaorouji/openwrt-passwall/blob/1f1b1b809253c9fe686d2e5af0e232c849ae56f2/luci-app-passwall/root/usr/share/passwall/helper_smartdns.sh#L199

这里可能会重复添加conf-file /tmp/etc/smartdns/passwall.conf到smartdns的custom.conf，建议加一个判断。

**Comment by handsomeji** [comment]
Fix.
