### ISSUE TITLE
关于netflix分流的功能建议

### ISSUE THREAD

**Issue by ax003** [xiaorouji/openwrt-package#1768]
## 你的功能请求是否与问题有关？ 请描述。(必填)

近期使用passwall来搭配netflix tv端，都是无法播放，改用ssr+就正常了
## 描述你想要的解决方案 (必填)

参考ssr+，netflix ip库它用的是这个项目https://github.com/QiuSimons/Netflix_IP
可以更新，避免netflix ip更新不及时导致tv端的播放异常

**Comment by handsomeji** [comment]
你可以使用geoip或geosite规则分流

**Comment by ax003** [comment]
> 你可以使用geoip或geosite规则分流

好像还不太一样，不过谢谢大佬

**Comment by xiaoyaozhilv** [comment]
> 你可以使用geoip或geosite规则分流

这个是在哪里添加啊 大佬 是在规则管理那里，奈飞那个栏目里加进去吗？我也是最近遇到这样的问题
