### ISSUE TITLE
google play页面能打开，但是无法下载

### ISSUE THREAD

**Issue by sy19890515** [xiaorouji/openwrt-package#1770]
## 描述bug(必填)
passwall开启gfw模式时，能打开google play页面，也能看到各个应用的信息，还有介绍图片和视频，但是无法下载（不管是更新还是安装新应用），而开启全局模式就可以
目前怀疑是下载的服务器的域名比较特殊，我目前设置的分流规则是：
![(4151WE@Z479E$5 %M$ ERB](https://user-images.githubusercontent.com/9069998/153720650-37ad4577-c973-461e-a528-991c6d7e3d1d.png)

这些应该包含了大部分我知道的google服务器域名，但依然不管用，请问应该怎么做呢？[](url)

**Comment by handsomeji** [comment]
默认代理列表和gfwlist已经包含googleplay域名，检查下节点是否送中？换成1.1.1.1 DNS不要用8.8.8.8看看

**Comment by sy19890515** [comment]
呃，我用的是208.67.222.222，只有1.1.1.1才行吗？
“节点是否送中”怎么检查呢？

**Comment by sy19890515** [comment]
刚试了下，改成1.1.1.1也不行，依然是能打开googleplay页面但是不能下载

**Comment by SakuraFallingMad** [comment]
还有确保下你的线路ip在google的IP库有无问题，有复现过部分ip谷歌判定CN的就无法play下载

**Comment by sy19890515** [comment]
> 还有确保下你的线路ip在google的IP库有无问题，有复现过部分ip谷歌判定CN的就无法play下载

应该不是这个问题，否则的话全局模式也应该不能下载，但是我现在开全局就可以下载

**Comment by sy19890515** [comment]
> 还有确保下你的线路ip在google的IP库有无问题，有复现过部分ip谷歌判定CN的就无法play下载

:joy:好奇怪，我昨天试过开全局可以下载，结果现在再试了一下不行了，有可能是我这边某个节点IP有问题而某个节点没问题，忘记昨天当时用的是哪个节点了
怎么检查我的IP在google的IP库有没有问题呢？

另外为什么一个IP它认为是CN就不让我下载，但又可以打开googleplay页面呢？

修改：我找到那个“全局可以下载，GFW模式无法下载”的节点了，是个美国节点，我平时用新加坡节点比较多，那个下不了，但现在问题又回到为什么“全局模式可以下载，GFW模式能打开页面却无法下载”了（另外也好奇为什么会有些节点即使全局模式能打开页面却无法下载）
@[SakuraFallingMad](https://github.com/SakuraFallingMad)

**Comment by sy19890515** [comment]
请问有人能解答吗，googleplay的下载服务器是哪个域名呢？我想试试加到规则里去，但是不知道怎么找到这个域名

**Comment by 0xffffharry** [comment]
把 googleapis.cn 加到代理域名里面去

**Comment by sy19890515** [comment]
> 把 googleapis.cn 加到代理域名里面去

但是我已经有：
regexp:\.?google.*\..*$
这条规则了，应该包含googleapis.cn吧

修改：不知道为什么我明明加了反斜杠，但是显示不了，你可以看我在1楼的截图里第一条那个正则表达式

**Comment by sy19890515** [comment]
> 把 googleapis.cn 加到代理域名里面去

会不会正则表达式的功能有bug所以导致没有包含这个域名？

**Comment by sy19890515** [comment]
> 把 googleapis.cn 加到代理域名里面去

好奇怪……我一开始试过直接把这个域名加到里面，结果果然能“开gfw模式”下载了，但是我又试着改了一下变成正则表达式的形式，就又不能下载了，然后我再改回域名的形式，也不行了……

**Comment by 0xffffharry** [comment]
regexp:^(.*)googleapis\.cn$

试试这个

或者通配符：

*.googleapis.cn
googleapis.cn

**Comment by sy19890515** [comment]
> regexp:^(.*)googleapis.cn$
> 
> 试试这个
> 
> 或者通配符：
> 
> *.googleapis.cn googleapis.cn

现在不在家，我回家试试
不过昨天我最开始先试着直接写域名，写了以后可以下载，但是之后虽然“试着改成正则表达式以后无法下载”，我又改回域名的写法了，结果发现又无法下载了，之后一直是“不管写域名还是写正则表达式都无法下载”，很奇怪

**Comment by overprince** [comment]
抓个包看看下载请求的域名是什么呗, 印象中有个gvt1 gvt2 的域名你这里就没有

**Comment by sy19890515** [comment]
> 抓个包看看下载请求的域名是什么呗, 印象中有个gvt1 gvt2 的域名你这里就没有


就是不知道怎么对手机抓包:joy:@[overprince](https://github.com/overprince)

**Comment by sy19890515** [comment]
> regexp:^(.*)googleapis.cn$
> 
> 试试这个
> 
> 或者通配符：
> 
> *.googleapis.cn googleapis.cn

刚到家，现在试了下加那个正则表达式，还是无法下载，而下面的*.googleapis.cn这个写法不支持
![image](https://user-images.githubusercontent.com/9069998/154953158-dcd0c4b2-afdd-4695-ac21-2972251a8b82.png)
@[yaotthaha](https://github.com/yaotthaha)

**Comment by sy19890515** [comment]
> 抓个包看看下载请求的域名是什么呗, 印象中有个gvt1 gvt2 的域名你这里就没有

![image](https://user-images.githubusercontent.com/9069998/154953258-db5f7e8c-63da-47fc-9072-cc6b20a30f4e.png)
现在我试着加了这一条，也还是无法下载:joy:@[overprince](https://github.com/overprince)

**Comment by 0xffffharry** [comment]
你用ray分流，然后passwall分流用全局，在ray里分流国内外，可以支持正则

**Comment by sy19890515** [comment]
> 你用ray分流，然后passwall分流用全局，在ray里分流国内外，可以支持正则

我就是用的分流，单独建了一个google的规则，里面就是我在一楼写的那些正则表达式（后来加了下面几楼别人提到的那几条） @[yaotthaha](https://github.com/yaotthaha)

**Comment by 0xffffharry** [comment]
新建一个单独组google 加下面的规则
geosite:google
geosite:google-cn

然后把规则调到china的上方让google国内域名匹配google而不是china

**Comment by sy19890515** [comment]
> 新建一个单独组google 加下面的规则 geosite:google geosite:google-cn
> 
> 然后把规则调到china的上方让google国内域名匹配google而不是china

好的，今晚回家再试试
我原本是用的xray分流，google规则本来就在最上面，不过没有这两条 @yaotthaha

**Comment by sy19890515** [comment]
> geosite:google
> geosite:google-cn

呃，刚试了，还是无法下载……换成全局模式就能下载 @yaotthaha 
![image](https://user-images.githubusercontent.com/9069998/155529300-d787267c-605f-49cd-bb9b-f68fe34283ec.png)
![image](https://user-images.githubusercontent.com/9069998/155529352-6fd8364f-cea7-40b4-b1a3-cb7091e5683f.png)
![image](https://user-images.githubusercontent.com/9069998/155529404-20a2fc30-d2cc-414a-9a8b-73554f9c65e2.png)
![image](https://user-images.githubusercontent.com/9069998/155529440-c63b8b46-a23c-426e-83f9-fc4baa6574d4.png)
![image](https://user-images.githubusercontent.com/9069998/155529538-d649f6de-d4cb-44a2-9d73-d0fc379ab68f.png)

**Comment by 0xffffharry** [comment]
要把模式全部设成全局才可以把所有流量流入ray，不然iptables会抢先把google的部分流量直连，根本流不进ray分流

**Comment by 0xffffharry** [comment]
用ray进行国内外分流就行

**Comment by sy19890515** [comment]
> 用ray进行国内外分流就行

呃，什么意思？是指用大陆白名单模式么？我不想把所有国外网站都走节点，不然steam下载也走节点了，费流量不说还慢得不行…… @yaotthaha

**Comment by 0xffffharry** [comment]
ray不是有条china的规则吗，把这条规则设置成直连不就行了，全局只是把流量流入ray而已，在ray分流

**Comment by sy19890515** [comment]
> ray不是有条china的规则吗，把这条规则设置成直连不就行了，全局只是把流量流入ray而已，在ray分流

我的china就是设置的直连呀

**Comment by 0xffffharry** [comment]
那不就行了吗，直接设置全局

**Comment by sy19890515** [comment]
> 那不就行了吗，直接设置全局
呃，我还是想用gfw模式，不然只有china直连的话怕steam下载也走节点，那样速度太慢了
只是想强制googleplay商店下载走节点，有办法么？

**Comment by 0xffffharry** [comment]
都说了可以在ray里面分流直连流量，你还是好好看看xray，v2ray文档吧

**Comment by sy19890515** [comment]
> 都说了可以在ray里面分流直连流量，你还是好好看看xray，v2ray文档吧

那不一样么？我现在就是用的分流+gfw模式，只有明确被墙的域名才走节点，其余直连，现在googleplay商店无法走节点就得在分流里设置它的域名走节点，不过现在不知道它域名
而改成分流+全局模式就会把指定直连的域名以外的域名走节点，这时候碰到没墙但又不在china规则里的域名就需要手动加到china规则里

**Comment by sy19890515** [comment]
> 都说了可以在ray里面分流直连流量，你还是好好看看xray，v2ray文档吧

而且按理说既然存在这个功能就不应该不生效啊，应该是可以用正则表达式来表示googleplay商店下载也走节点的吧

**Comment by 0xffffharry** [comment]
但是gfw模式不是因为缺少规则把部分google play流量直连了吗。你要么找到全部域名加到passwall的代理列表，然后继续用gfw模式。要么把设置全局把流量全部代理到ray的分流组，再用ray的正则分流google play流量，同时可以设置国内外分流。



注意：passwall分流和ray分流是两回事，passwall分流是在iptables层面，拦截的流量会流向代理，如果代理设置普通节点，那就是直接到节点了，但是如果代理设置ray分流，那就会匹配ray的规则列表决定流量如何流，可以是走节点，也可以直连。

如果代理设置ray分流，设置全局代理，相当于把所有分流的任务交给ray


懂了吗？

**Comment by sy19890515** [comment]
> 但是gfw模式不是因为缺少规则把部分google play流量直连了吗。你要么找到全部域名加到passwall的代理列表，然后继续用gfw模式。要么把设置全局把流量全部代理到ray的分流组，再用ray的正则分流google play流量，同时可以设置国内外分流。
> 
> 注意：passwall分流和ray分流是两回事，passwall分流是在iptables层面，拦截的流量会流向代理，如果代理设置普通节点，那就是直接到节点了，但是如果代理设置ray分流，那就会匹配ray的规则列表决定流量如何流，可以是走节点，也可以直连。
> 
> 如果代理设置ray分流，设置全局代理，相当于把所有分流的任务交给ray
> 
> 懂了吗？

但我主要是担心开全局模式以后，它会把steam的cdn服务器识别成国外网站，导致steam的下载走了节点，这样我不清楚steam的cnd域名的话又会下载特别慢

**Comment by sy19890515** [comment]
> 但是gfw模式不是因为缺少规则把部分google play流量直连了吗。你要么找到全部域名加到passwall的代理列表，然后继续用gfw模式。要么把设置全局把流量全部代理到ray的分流组，再用ray的正则分流google play流量，同时可以设置国内外分流。
> 
> 注意：passwall分流和ray分流是两回事，passwall分流是在iptables层面，拦截的流量会流向代理，如果代理设置普通节点，那就是直接到节点了，但是如果代理设置ray分流，那就会匹配ray的规则列表决定流量如何流，可以是走节点，也可以直连。
> 
> 如果代理设置ray分流，设置全局代理，相当于把所有分流的任务交给ray
> 
> 懂了吗？

![image](https://user-images.githubusercontent.com/9069998/155760180-cd9de4f2-8108-48a7-88a5-ba250e6ff471.png)
![image](https://user-images.githubusercontent.com/9069998/155760602-75eafae9-4222-4499-8db6-f3dabe9edcf5.png)
你看我刚才开了全局模式，然后随便去下个游戏，只有2.几M每秒，然后改成gfw模式，就能上10M了（虽然平时能上50M的，不知道今天怎么这么慢）

**Comment by 0xffffharry** [comment]
geosite:steam

设置成直连不就行了

**Comment by sy19890515** [comment]
> geosite:steam
> 
> 设置成直连不就行了

但首先steam有些域名是被墙了的，比如创意工坊和库存，然后最近商店页面一直抽风，但好友、下载、图片这些却没被墙，得分开设置，我现在其实已经分开设置了的，是手动指定创意工坊和库存还有商店走节点，其余不动
如果geosite:steam直连的话就得找到下载服务器的域名再设置成走节点，又跟google的问题一样了
而且steam只是一个例子，我最终目的是“没被墙的网站，不管国内还是国外的，都直连”，而如果用全局+china直连的话实际效果跟“大陆白名单模式”是一回事了…… @[yaotthaha](https://github.com/yaotthaha)

**Comment by 0xffffharry** [comment]
跟你说不明白了。你还是找google play的域名吧，别用ray分流了

**Comment by sy19890515** [comment]
> 跟你说不明白了。你还是找google play的域名吧，别用ray分流了

……用googleplay域名和分流不冲突啊，我一直用着分流只不过在找域名@[yaotthaha](https://github.com/yaotthaha)

**Comment by 0xffffharry** [comment]
反正你继续找域名就行

**Comment by Diffused7245** [comment]
谷歌的下载服务器是dl.google.com，国内ISP默认会解析到北京和上海的机房，而且速度非常快（还不走梯子服务器流量），V2EX有人说IP被滥用被判定为中国的时候会出问题，你看看你的出口IP是不是被玩坏了。
无痕模式打开谷歌，随便搜点东西，拉到最底下，会看到类似“Japan Tokyo - From your IP address - Update location”的字样，如果显示是国内城市的话，就说明这个IP不干净了，换一个。自建服务器的话安装一个cloudflare warp，就可以用CF的IP盖过去。

**Comment by sy19890515** [comment]
> 谷歌的下载服务器是dl.google.com，国内ISP默认会解析到北京和上海的机房，而且速度非常快（还不走梯子服务器流量），V2EX有人说IP被滥用被判定为中国的时候会出问题，你看看你的出口IP是不是被玩坏了。 无痕模式打开谷歌，随便搜点东西，拉到最底下，会看到类似“Japan Tokyo - From your IP address - Update location”的字样，如果显示是国内城市的话，就说明这个IP不干净了，换一个。自建服务器的话安装一个cloudflare warp，就可以用CF的IP盖过去。

但如果是dl.google.com的话，按理说我的规则里的正则表达式已经包含了这个域名，那么就应该会强制走那条规则才对吧，不应该出现“开全局模式就可以下载，gfw模式就无法下载”的情况啊？@[Marionic0723](https://github.com/Marionic0723)

**Comment by SakuraFallingMad** [comment]
如果在进xray分流前规则在chnlist有域名的话就不会进去了
discussion里有个帖子讲这个的
那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢

**Comment by sy19890515** [comment]
> 如果在进xray分流前规则在chnlist有域名的话就不会进去了 discussion里有个帖子讲这个的 那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢

原来如此……居然还有在chnlist里就忽略规则这种事情……感觉这个是不是算bug？@[SakuraFallingMad](https://github.com/SakuraFallingMad)

**Comment by SakuraFallingMad** [comment]
> > 如果在进xray分流前规则在chnlist有域名的话就不会进去了 discussion里有个帖子讲这个的 那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢
> 
> 原来如此……居然还有在chnlist里就忽略规则这种事情……感觉这个是不是算bug？@[SakuraFallingMad](https://github.com/SakuraFallingMad)

不 也不算吧 估摸着设计是细化分流国外的 也不是拿来给你全部分流的 你需求点出问题是你chnlist默认规则可能夹带了这些东西 还是用适合你的规则

参考#1506

**Comment by sy19890515** [comment]
> > > 如果在进xray分流前规则在chnlist有域名的话就不会进去了 discussion里有个帖子讲这个的 那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢
> > 
> > 
> > 原来如此……居然还有在chnlist里就忽略规则这种事情……感觉这个是不是算bug？@[SakuraFallingMad](https://github.com/SakuraFallingMad)
> 
> 不 也不算吧 估摸着设计是细化分流国外的 也不是拿来给你全部分流的 你需求点出问题是你chnlist默认规则可能夹带了这些东西 还是用适合你的规则
> 
> 参考#1506

呃，我目前对gfw模式是刚需:joy:否则我上的很多网站其实都是国外但没墙的，用大陆白名单或者全局模式都得再手动去配那些网站，数量太多了配不过来，每保存应用一次还得等个半分钟……
只能在需要从googleplay下载的时候临时换成全局或者干脆手机上自己开全局翻了……

**Comment by 0xffffharry** [comment]
> > > > 如果在进xray分流前规则在chnlist有域名的话就不会进去了 discussion里有个帖子讲这个的 那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢
> > > 
> > > 
> > > 原来如此……居然还有在chnlist里就忽略规则这种事情……感觉这个是不是算bug？@[SakuraFallingMad](https://github.com/SakuraFallingMad)
> > 
> > 
> > 不 也不算吧 估摸着设计是细化分流国外的 也不是拿来给你全部分流的 你需求点出问题是你chnlist默认规则可能夹带了这些东西 还是用适合你的规则
> > 参考#1506
> 
> 呃，我目前对gfw模式是刚需😂否则我上的很多网站其实都是国外但没墙的，用大陆白名单或者全局模式都得再手动去配那些网站，数量太多了配不过来，每保存应用一次还得等个半分钟…… 只能在需要从googleplay下载的时候临时换成全局或者干脆手机上自己开全局翻了……

感觉你理解有问题，都说了passwall插件的分流只是判定是否流入passwall TCP节点，也就是说你可以把TCP节点设置成ray分流，让流量再经过ray的分流，你朝思暮想的gfw列表也可以用geosite:gfw分流到远程节点，你不想走的可以设置直连，前提是passwall插件里面的代理模式需要设置成全局，这样ray分流才能处理你的全部流量

我都解释这么清楚了要是还不懂你可以先看看什么是透明代理，看看ray的分流wiki，看看iptables

**Comment by sy19890515** [comment]
> > > > > 如果在进xray分流前规则在chnlist有域名的话就不会进去了 discussion里有个帖子讲这个的 那么，完全靠分流的话，也是全局代理这个诡异的设置方法了，最近几个issue也有提到，还有修复全局代理后tcp inbound的问题呢
> > > > 
> > > > 
> > > > 原来如此……居然还有在chnlist里就忽略规则这种事情……感觉这个是不是算bug？@[SakuraFallingMad](https://github.com/SakuraFallingMad)
> > > 
> > > 
> > > 不 也不算吧 估摸着设计是细化分流国外的 也不是拿来给你全部分流的 你需求点出问题是你chnlist默认规则可能夹带了这些东西 还是用适合你的规则
> > > 参考#1506
> > 
> > 
> > 呃，我目前对gfw模式是刚需😂否则我上的很多网站其实都是国外但没墙的，用大陆白名单或者全局模式都得再手动去配那些网站，数量太多了配不过来，每保存应用一次还得等个半分钟…… 只能在需要从googleplay下载的时候临时换成全局或者干脆手机上自己开全局翻了……
> 
> 感觉你理解有问题，都说了passwall插件的分流只是判定是否流入passwall TCP节点，也就是说你可以把TCP节点设置成ray分流，让流量再经过ray的分流，你朝思暮想的gfw列表也可以用geosite:gfw分流到远程节点，你不想走的可以设置直连，前提是passwall插件里面的代理模式需要设置成全局，这样ray分流才能处理你的全部流量
> 
> 我都解释这么清楚了要是还不懂你可以先看看什么是透明代理，看看ray的分流wiki，看看iptables

关键是我上的网站里需要手动设置直连的过多了……

**Comment by handsomeji** [comment]
建议使用passwall2

**Comment by sy19890515** [comment]
> 建议使用passwall2

咦？出2了？

**Comment by Diffused7245** [comment]
我去，出2了？这就来体验下

**Comment by WYC-2020** [comment]
> 建议使用passwall2

出2了是不是1就不维护了，大佬

**Comment by benzBrake** [comment]
我也遇到了这个神奇的问题，把`googleapis.cn`加入代理列表并不好用而且有个很神奇的地方使用HK的服务器能下载，使用USA的服务器就不行

**Comment by bwb0101** [comment]
避免使用香港节点

**Comment by sy19890515** [comment]
> 避免使用香港节点

跟节点没关系，我用香港节点开全局模式就能下载
我后来解决了，配置了smartdns就好了

**Comment by bwb0101** [comment]
> > 避免使用香港节点
> 
> 跟节点没关系，我用香港节点开全局模式就能下载 我后来解决了，配置了smartdns就好了

应该也跟手机有关系，我小米手机的play商店走的是googleapis.cn这个域名，走香港节点就是转圈

**Comment by sy19890515** [comment]
没，我同一个手机，同一个，之前是开全局就可以下载，gfw模式就不行，而配置了smartdns以后就都可以

Sincerely,
Yi Shi
________________________________

**Comment by sy19890515** [comment]
同一个手机同一个节点

Sincerely,
Yi Shi
________________________________

**Comment by zanjie1999** [comment]
我也遇到了这个问题，因为我手贱的更新了一下我的gfwlist

**Comment by hpqqph** [comment]
同样问题

**Comment by hpqqph** [comment]
ssrp和openclash最后试出端口问题，仅常用端口会出问题，选默认全部端口就好了。passwall不知道从哪里设置端口。

**Comment by jamesqhnu** [comment]
请问这个问题最后怎么解决的

**Comment by zanjie1999** [comment]
> 请问这个问题最后怎么解决的

不知道怎么解决，换成ShadowSocksR Plus+ 用没有问题

**Comment by 0xffffharry** [comment]
> 请问这个问题最后怎么解决的

geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt

**Comment by sy19890515** [comment]
> > 请问这个问题最后怎么解决的
> 
> geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt

这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。

**Comment by sy19890515** [comment]
> > 请问这个问题最后怎么解决的
> 
> 不知道怎么解决，换成ShadowSocksR Plus+ 用没有问题

我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。

**Comment by jamesqhnu** [comment]
这个怎么开呀



 201931331043
 ***@***.***
  



---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2023年05月18日 14:11 收件人  ***@***.***> 抄送至  ***@***.***>***@***.***> 主题  Re: [xiaorouji/openwrt-passwall] google play页面能打开，但是无法下载 (Issue #1770)  

请问这个问题最后怎么解决的
不知道怎么解决，换成ShadowSocksR Plus+ 用没有问题
我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。

**Comment by sy19890515** [comment]
> 这个怎么开呀 201931331043 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2023年05月18日 14:11 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [xiaorouji/openwrt-passwall] google play页面能打开，但是无法下载 (Issue #1770) 请问这个问题最后怎么解决的 不知道怎么解决，换成ShadowSocksR Plus+ 用没有问题 我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

有smartdns插件就行，网上找个配置教程吧

**Comment by zanjie1999** [comment]
> > > 请问这个问题最后怎么解决的
> > 
> > 
> > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> 
> 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。

因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启

**Comment by sy19890515** [comment]
> > > > 请问这个问题最后怎么解决的
> > > 
> > > 
> > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > 
> > 
> > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> 
> 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启

但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题
感觉这也不像是dns污染能解释的

**Comment by zanjie1999** [comment]
> > > > > 请问这个问题最后怎么解决的
> > > > 
> > > > 
> > > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > > 
> > > 
> > > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> > 
> > 
> > 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启
> 
> 但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题 感觉这也不像是dns污染能解释的

那是因为你访问的所谓“国外dns”其实也是被国内抢答污染的
而且还有个问题，passwall好像是根据域名对应的ip来处理gfw模式里的那些域名的，如果一个域名有多个对应ip，比如Google是有可能抽风不走的

**Comment by sy19890515** [comment]
> > > > > > 请问这个问题最后怎么解决的
> > > > > 
> > > > > 
> > > > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > > > 
> > > > 
> > > > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> > > 
> > > 
> > > 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启
> > 
> > 
> > 但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题 感觉这也不像是dns污染能解释的
> 
> 那是因为你访问的所谓“国外dns”其实也是被国内抢答污染的

我考虑过这个可能性，所以我当时试过“所有”我能找到的国外dns，没有一个能解决这个问题。那么如果是因为污染导致的，那唯一解释就是“市面上能找到的所有国外dns，没有一个没被污染”，我觉得这个可能性更低。

**Comment by sy19890515** [comment]
> > > > > > 请问这个问题最后怎么解决的
> > > > > 
> > > > > 
> > > > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > > > 
> > > > 
> > > > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> > > 
> > > 
> > > 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启
> > 
> > 
> > 但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题 感觉这也不像是dns污染能解释的
> 
> 那是因为你访问的所谓“国外dns”其实也是被国内抢答污染的 而且还有个问题，passwall好像是根据域名对应的ip来处理gfw模式里的那些域名的，如果一个域名有多个对应ip，比如Google是有可能抽风不走的

不对，即使是这样，依然不能解释为什么“开了smartdns以后就解决了”这个现象。它能够解决问题，那就说明“我配在里面的至少一个dns服务器是没被污染的”，而我配在smartdns里的所有dns地址我都单独试验过，都不能解决这个问题。

**Comment by zanjie1999** [comment]
> > > > > > > 请问这个问题最后怎么解决的
> > > > > > 
> > > > > > 
> > > > > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > > > > 
> > > > > 
> > > > > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> > > > 
> > > > 
> > > > 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启
> > > 
> > > 
> > > 但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题 感觉这也不像是dns污染能解释的
> > 
> > 
> > 那是因为你访问的所谓“国外dns”其实也是被国内抢答污染的 而且还有个问题，passwall好像是根据域名对应的ip来处理gfw模式里的那些域名的，如果一个域名有多个对应ip，比如Google是有可能抽风不走的
> 
> 不对，即使是这样，依然不能解释为什么“开了smartdns以后就解决了”这个现象。它能够解决问题，那就说明“我配在里面的至少一个dns服务器是没被污染的”，而我配在smartdns里的所有dns地址我都单独试验过，都不能解决这个问题。

smartdns有他独特的算法能检测出多条dns回复中哪条是抢答的，并不使用它，毕竟是抢答，不是劫持，所以会收到>1次回复
adhome套smartdns能得到比较好的效果，但在使用passwall的gfw模式的时候会有奇怪问题

**Comment by sy19890515** [comment]
> > > > > > > > 请问这个问题最后怎么解决的
> > > > > > > 
> > > > > > > 
> > > > > > > geosite:google-cn 走代理即可，具体域名看这里：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/google-cn.txt
> > > > > > 
> > > > > > 
> > > > > > 这个我改了，但是还是无法解决。我后来开了smartdns就好了，虽然我也不理解为什么开smartdns能解决这个问题。
> > > > > 
> > > > > 
> > > > > 因为导致这个问题的问题有两个，一个是dns污染，一个是passwall的dns转发要是炸了不会自动重启
> > > > 
> > > > 
> > > > 但是我在开smartdns之前，试过改成国外dns，各种有名的dns地址都试过了，而且也不止是改passwall自己的dns转发地址，lan的dns地址也改了，都无法解决这个问题 感觉这也不像是dns污染能解释的
> > > 
> > > 
> > > 那是因为你访问的所谓“国外dns”其实也是被国内抢答污染的 而且还有个问题，passwall好像是根据域名对应的ip来处理gfw模式里的那些域名的，如果一个域名有多个对应ip，比如Google是有可能抽风不走的
> > 
> > 
> > 不对，即使是这样，依然不能解释为什么“开了smartdns以后就解决了”这个现象。它能够解决问题，那就说明“我配在里面的至少一个dns服务器是没被污染的”，而我配在smartdns里的所有dns地址我都单独试验过，都不能解决这个问题。
> 
> smartdns有他独特的算法能检测出多条dns回复中哪条是抢答的，并不使用它，毕竟是抢答，不是劫持，所以会收到>1次回复

那反正它最后实际使用的dns总还是我配置在里面的某一个dns吧，而我配置在里面的“所有dns”我都单独试过，都不能解决问题。
我最后实际上就是smartdns+adg+passwall一起用的，最开始不管是单独用passwall还是adg+passwall都碰到这个问题，很烦。

**Comment by Eished** [comment]
我把这两条加入 Proxy 就可以用了：
```
domain:googleapis.cn
domain:xn--ngstr-lra8j.com
```

**Comment by sy19890515** [comment]
> 我把这两条加入 Proxy 就可以用了：
> 
> ```
> domain:googleapis.cn
> domain:xn--ngstr-lra8j.com
> ```

我很久以前就加入这两条了，没帮助，后来打开了smartdns就可以了，不要问我为什么会好，我也没想通😂

**Comment by raygzcn** [comment]
> smartdns

我也是小米手机也是passwall遇到同样问题
请教一下你的smartdns参考哪个教程配置？

**Comment by yr05182008** [comment]
成功

> 新建一个单独组google 加下面的规则 geosite:google geosite:google-cn
> 
> 然后把规则调到china的上方让google国内域名匹配google而不是china
