### ISSUE TITLE
在开启代理之后无法作为服务器对外提供服务

### ISSUE THREAD

**Issue by 0xffffharry** [xiaorouji/openwrt-package#1779]
## 复现步骤(必填)

旁路由开启passwall总开关（全局代理）

旁路由搭建任意服务，并对外开放IPv6访问，防火墙已全部打开，外部无法访问

## 你想要实现的目的(必填)

作为透明网关同时，可以对外提供其他web服务

## 系统相关信息(必填)
  passwall版本 4.41

**Comment by 0xffffharry** [comment]
已解决，需要在开启插件后自己添加 ip rule

ip -6 rule add from <IPv6 地址> lookup main

**Comment by liaoweiliao521** [comment]
> 已解决，需要在开启插件后自己添加 ip rule
> 
> ip -6 rule add from <IPv6 地址> lookup main

请问是在哪里添加这条规则，我的情况和你描述的情况一样。

**Comment by 0xffffharry** [comment]
开启插件后敲命令：
ip -6 rule add from <公网IPv6 地址> lookup main
...（有多个IPv6地址就补上）
关闭插件后敲命令：
ip -6 rule del from <公网IPv6 地址> lookup main
...

可以修改 /etc/init.d/passwall 自动执行

$APP_FILE stop 前面：ip -6 rule del from <公网IPv6 地址> lookup main

$APP_FILE start 后面：ip -6 rule add from <公网IPv6 地址> lookup main

**Comment by liaoweiliao521** [comment]
> 开启插件后敲命令： ip -6 rule add from <公网IPv6 地址> lookup main ...（有多个IPv6地址就补上） 关闭插件后敲命令： ip -6 rule del from <公网IPv6 地址> lookup main ...
> 
> 可以修改 /etc/init.d/passwall 自动执行
> 
> $APP_FILE stop 前面：ip -6 rule del from <公网IPv6 地址> lookup main
> 
> $APP_FILE start 后面：ip -6 rule add from <公网IPv6 地址> lookup main

谢谢你😜

**Comment by 0xffffharry** [comment]
> > 开启插件后敲命令： ip -6 rule add from <公网IPv6 地址> lookup main ...（有多个IPv6地址就补上） 关闭插件后敲命令： ip -6 rule del from <公网IPv6 地址> lookup main ...
> > 可以修改 /etc/init.d/passwall 自动执行
> > $APP_FILE stop 前面：ip -6 rule del from <公网IPv6 地址> lookup main
> > $APP_FILE start 后面：ip -6 rule add from <公网IPv6 地址> lookup main
> 
> 谢谢你😜

目前新版passwall（78bfaa6之前）无法这么做，只能修改passwall源码，可以参考我的fork  （84a7664和a2a0c33）

然后在/etc/config/passwall的global块修改（没有就加上）
option start_script 后面是你启动插件后要运行的脚本的位置
option stop_script 后面是你关闭插件后要运行的脚本的位置

**Comment by liaoweiliao521** [comment]
> > > 开启插件后敲命令： ip -6 rule add from <公网IPv6 地址> lookup main ...（有多个IPv6地址就补上） 关闭插件后敲命令： ip -6 rule del from <公网IPv6 地址> lookup main ...
> > > 可以修改 /etc/init.d/passwall 自动执行
> > > $APP_FILE stop 前面：ip -6 rule del from <公网IPv6 地址> lookup main
> > > $APP_FILE start 后面：ip -6 rule add from <公网IPv6 地址> lookup main
> > 
> > 
> > 谢谢你😜
> 
> 目前新版passwall（78bfaa6之前）无法这么做，只能修改passwall源码，可以参考我的fork （84a7664和a2a0c33）
> 
> 然后在/etc/config/passwall的global块修改（没有就加上） option start_script 后面是你启动插件后要运行的脚本的位置 option stop_script 后面是你关闭插件后要运行的脚本的位置

好的，我去看看，非常感谢
