### ISSUE TITLE
更新4.50后，op主页面打不开！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#1786]
更新4.50后，运行一会op主页面就打不开了，ssh进后台关了passwall，就恢复正常！

**Comment by Diffused7245** [comment]
是不是argon主题，从必应加载背景的，不知为何连不上，现在bing不走代理就行，反正能上谷歌。

**Comment by snakwu** [comment]
> 是不是argon主题，从必应加载背景的，不知为何连不上，现在bing不走代理就行，反正能上谷歌。

是的，bing加直连就行了
