### ISSUE TITLE
passwall 4.50配合smartdns后CPU占用100%

### ISSUE THREAD

**Issue by hululu1068** [xiaorouji/openwrt-package#1787]
## 描述bug(必填)
passwall 4.50配合smartdns后CPU占用100%
排查发现，启动后会给smartdns添加一个域名规则文件
<img width="449" alt="2022-02-22_16-50-23" src="https://user-images.githubusercontent.com/68652362/155098182-dbc1ae99-deaf-460d-bc2d-a68cac0bbf20.png">

<img width="869" alt="2022-02-22_16-56-36" src="https://user-images.githubusercontent.com/68652362/155098255-a945872f-f45e-41b6-b4a2-5f3c0c772590.png">

## 复现步骤(必填)

smartdns配置好后，重定向“作为dnsmasq的上游服务器”
passwall选择国内组“cn”
节点协议 vless
规则使用的是geoip、geosite

## 系统相关信息(必填)

openwrt_x86-64 (官方openwrt_v21.02.2源码)
passwall版本
4.50
xray内核版本
1.5.3

**Comment by hululu1068** [comment]
屏蔽掉后正常
<img width="351" alt="image" src="https://user-images.githubusercontent.com/68652362/155099498-ff4c5620-4967-42a7-8527-52aea085b1bc.png">

<img width="901" alt="image" src="https://user-images.githubusercontent.com/68652362/155099564-73079af7-de41-4fbb-abd3-a18efedeccda.png">

**Comment by handsomeji** [comment]
教程已经发过 不想再复读机
