### ISSUE TITLE
系统日志显示找不到 dnsmasq.d/99-gfwlist

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-package#1789]
## 描述bug(必填)
系统日志显示找不到 dnsmasq.d/99-gfwlist.
dnsmasq无法启动.
可是该目录下存在这个文件.

## 复现步骤(必填)
更换节点系统日志就会出现以上日志.

## 日志信息(必填！)
Tue Feb 22 22:23:52 2022 daemon.crit dnsmasq[6275]: cannot read /tmp/dnsmasq.d/passwall/99-gfwlist.conf: No such file or directory
Tue Feb 22 22:23:52 2022 daemon.crit dnsmasq[6275]: FAILED to start up

## 截图
![image](https://user-images.githubusercontent.com/59167936/155166667-4e16540b-4d4b-4ab0-8dc7-55a4b36cd0f3.png)

## 系统相关信息(必填)
passwall 4.50-1

## 其他信息补充
重启路由、重启dnsmasq与passwall、重刷固件仍然如此.

**Comment by smallprogram** [comment]
我查了一下，我的固件没有这个问题，最好描述一下你的dnsmasq版本，op代码来源。
可以去尝试：
1. passwall reset config
2. 重新编译重刷固件
3. 试试[我的固件](https://github.com/smallprogram/OpenWrtAction/tags)试试

**Comment by yunxi993** [comment]
> 我查了一下，我的固件没有这个问题，最好描述一下你的dnsmasq版本，op代码来源。 可以去尝试：
> 
> 1. passwall reset config
> 2. 重新编译重刷固件
> 3. 试试[我的固件](https://github.com/smallprogram/OpenWrtAction/tags)试试

dnsmasq-full 2.86-10
lean源码

**Comment by smallprogram** [comment]
我刚看了看你的[ARMv8](https://github.com/yunxi993/OpenWrt-ARMv8)Op Ci，鬼知道你精简了什么东西

**Comment by yunxi993** [comment]
算了，拉倒吧，用ssr了.
