### ISSUE TITLE
新版本的passwall，DNS分流不论选择哪种方式，添加了NF或者D+解锁的服务器都无法实现解锁，老版本的解锁正常

### ISSUE THREAD

**Issue by oyanli** [xiaorouji/openwrt-package#1790]
## 描述bug(必填)

新版本的passwall，DNS分流不论选择哪种方式，添加了NF或者D+解锁的服务器都无法实现解锁，老版本的解锁正常
老版本：4.45-1
新版本：4.50-1
NF解锁服务器：使用Dnsmasq SNIproxy一键脚本搭建
节点服务器：使用xray搭建，DNS设置为解锁服务器IP
测试使用为同一服务器

## 复现步骤(必填)

老版本DNS设置：
过滤模式：pdnsd
远程DNS：8.8.8.8
缓存解析结果：勾选
ChinaDNS-NG：勾选

新版本DNS设置：
DNS分流：Dnsmasq
过滤模式：pdnsd
远程DNS：8.8.8.8
缓存解析结果：勾选
ChinaDNS-NG：勾选

DNS设置两版除了新版本多了个Dnsmasq，其它没有任何设置改动

## 你想要实现的目的(必填)

请问这是新版本的BUG，还是需要设置才能实现像老版本那样的解锁

## 系统相关信息(必填)

老版本：4.45-1
新版本：4.50-1

**Comment by handsomeji** [comment]
高级设置
流量嗅探 打勾
流量嗅探只供路由使用 不打勾
试试

**Comment by oyanli** [comment]
> 高级设置流量诱探 打流量诱探只供 路由 使用 不 打勾勾

谢谢大佬，按此设置可以正常解锁了，谢谢！！但发现4.50-1另一个BUG，

节点列表---通过链接添加节点，下面格式的节点不支持了，提示：请输入正确的链接 ，在4.49-1及以前的版本都是支持的，请查验

ss://aes-256-gcm:12345678$@127.0.0.1:1180#负载均衡
vless://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx@127.0.0.1:1190?encryption=none&security=xtls&type=tcp&host=123.xxx&headerType=none&sni=123.xxx&flow=xtls-rprx-splice#负载均衡

**Comment by handsomeji** [comment]
已修复。
