### ISSUE TITLE
使用udp请求dns问题。

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#1793]
一：如果dns模式为用udp请求dns模式下，用REDIRECT，无法请求dns，不能访问国外，如果用TPROXY模式就没问题
二：如果关闭IPv6透明代理(我的节点不支持ipv6），op的动态dns服务里的更新ddns服务列表无法更新，当启用IPv6透明代理，就可正常更新，但开启IPv6透明代理，又会引起全局代理的设备，访问出现问题！
passwall版本为最新4.50

**Comment by snakwu** [comment]
我想我大概知道问题在那里了
前提条件，我的dns服务是禁用ipv6解释的
当在passwall的高级设置勾选上IPv6透明代理(TProxy)代理时，查询结果返回的如图，也就是丢弃了ip6地址，因为我的dns丢弃ipv6地址的，这样返回正确.
![image](https://user-images.githubusercontent.com/5343595/155459840-22ec62e0-53e6-498a-b257-99ece0f4bb1a.png)

当我没有勾上passwall的高级设置勾选上IPv6透明代理(TProxy)代理时，查询结果返回如图，返回的ipv6地址为空域名，所以会引起op自身的访问有些国外有问题，和全局代理的设置有问题。
![image](https://user-images.githubusercontent.com/5343595/155460166-d2dbbd47-73f9-42ec-bc20-af877d3f4eed.png)

在之前的版本有一个禁用ivp6的选项的，不知道为什么新版本取消了。希望可以把那个选项加回去，还有，希望在没有选上IPv6透明代理(TProxy)代理下，返回的ipv6是丢弃，而不是返回空域名，这样应该可以解决这些问题！谢谢

**Comment by handsomeji** [comment]
reverted.

**Comment by snakwu** [comment]
> 恢复。

谢谢大佬，问题解决了，其实这个问题引起是passwall的过滤代理域名 IPv6用的是返回空域名，如果改用丢弃ipv6值，那就不会了，再次感谢！
