### ISSUE TITLE
访问控制不走代理对部分网站失效

### ISSUE THREAD

**Issue by whoshoe** [xiaorouji/openwrt-package#1795]
## 访问控制不走代理对部分网站失效

访问控制中设置某设备TCP和UDP不走代理仍然可以访问CNN等需要代理才能访问的网站。

## 复现步骤(必填)

在访问控制中添加如下设备：
![image](https://user-images.githubusercontent.com/10238980/155520561-1d3a9fb4-b576-45fa-afb5-3ed55a1360d7.png)

## 你想要实现的目的(必填)

手机中不开启代理应用的情况下无法访问cnn.com和google.com等需要代理才能访问的网站。

## 系统相关信息(必填)

最新编译的Passwall版本

## 其他相关信息

TCP代理模式为全局。

**Comment by smallprogram** [comment]
感觉你的设置很怪异，默认代理模式全局，访问控制里设置不代理。 为什么不把默认代理设置为不代理，访问控制添加需要代理的设备呢？

**Comment by whoshoe** [comment]
> 感觉你的设置很怪异，默认代理模式全局，访问控制里设置不代理。 为什么不把默认代理设置为不代理，访问控制添加需要代理的设备呢？

默认代理模式设置为全局是因为有分流的名单，其中包括中国的，我希望所有的流量都通过分流。大部分设备需要代理，只有少数设备不需要代理，所以访问控制里设置不代理比较方便。

**Comment by 0xffffharry** [comment]
IOS WiFi 有一个隐私选项，其实是随机MAC，这个也会影响访问控制的规则，需要关掉

**Comment by whoshoe** [comment]
> IOS WiFi 有一个隐私选项，其实是随机MAC，这个也会影响访问控制的规则，需要关掉

谢谢提醒，我也注意到了这个选项，截图中的和wifi所用的mac以及IP是匹配的。

**Comment by 0xffffharry** [comment]
看看iptables规则？
