### ISSUE TITLE
Socks 长时间链接后无网络 后续更新测试

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-package#1796]
今天全新编译了一个lede固件+全新passwall源码试了下，一开始socks下载BT一切正常没断联5-6个小时，
然后突然无法上网，打开路由器后台发现很长时间无法进入然后提示：
Bad Gateway
The process did not produce any response

ping路由器是通的，断电重启后正常，猜测可能是socks进程守护导致内存爆了？设备是R4S旁路由只开了BBR和passwall
用的qBittorrent 同时下载大概15个任务，全局限制最高500连接数，每个任务下载50连接数，上传1个窗口
节点是xray的VLESS+TLS+WS然后，qBittorrent直接全部连接包括P2P也是走socks5总开关那里，路由器是旁路由模式。

![image](https://user-images.githubusercontent.com/47970938/155527745-eee90250-fa57-4aab-a8ab-9c6189c515c8.png)

_Originally posted by @zhucaidan in https://github.com/xiaorouji/openwrt-passwall/issues/1539#issuecomment-1049833111_

**Comment by tritu** [comment]
It’s like ur luci crashed…

**Comment by zhucaidan** [comment]
> It’s like ur luci crashed…

SSH也无法连接。。。

**Comment by handsomeji** [comment]
Out of memory.
