### ISSUE TITLE
question about the ss

### ISSUE THREAD

**Issue by xcyll** [xiaorouji/openwrt-package#1798]
PW version : 4.5
node[ chacha20-**ietf**-poly1305 ] ----------**ss-rust**

After opening, the node cannot be used.

The tcp log has the following tips :
2022-02-26 DEBUG [shadowsocks_service::local::redir::tcprelay] TCP redirect client, error: Custom { kind: Other, error: "dns resolve ******:port error: No connections available" }

**Comment by xcyll** [comment]
目前改用v2ray里的ss了
(🎈但是用**v2ray方式订阅**ss节点则出现以下情况
 ------------------------------⬇️节点没有选择**chacha20-poly1305**  而是选择了第一行aes-128-gcm

![1](https://user-images.githubusercontent.com/63227888/155840080-edba657f-b622-4f34-bcfa-086139303cc4.png)
切换成1305后 节点可正常使用了

**Comment by xcyll** [comment]
目前改用v2方式订阅
 🎈但是用**v2方式订阅**节点[ 节点类型chacha20-**ietf**-poly1305 ]则出现以下情况：
 ------------------------------⬇️订阅后的节点没有选择**chacha20-poly1305**  而是选择了第一行aes-128-gcm .
------------------------------【**chacha20-poly1305 (alias chacha20-itef-poly1305)**】
![1](https://user-images.githubusercontent.com/63227888/155840080-edba657f-b622-4f34-bcfa-086139303cc4.png)
手动切换成chacha20-poly1305后 节点可正常使用了

**Comment by handsomeji** [comment]
ss-rust测试没有问题。
订阅问题已修复 a4d93e8db3cea6e356d026b018e5dc30e44b0674
