### ISSUE TITLE
服务端创建失败

### ISSUE THREAD

**Issue by caissonfiv** [xiaorouji/openwrt-package#1806]
## 描述bug(必填)

Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /tmp/etc/passwall_server/bin/ss-server)
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_free: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_auth_decrypt: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_setkey: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_finish: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_starts: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_reset: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md5_ret: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_starts: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_set_iv: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_get_size: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_init: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_setup: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_setup: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_free: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_info_from_string: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_finish: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_auth_encrypt: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_info_from_string: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_init: symbol not found
## 复现步骤(必填)

在创建SS服务端的时候出现失败

**Comment by handsomeji** [comment]
二进制程序有问题
