### ISSUE TITLE
更新4.51之后，用那种方式都无法访问国外！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#1808]
更新4.51之后，用那种方式都无法访问国外！
看上去好像没更新了什么，但是什么都不动下，安装更新4.51之后，怎么也上不了去了。
我用的是用udp请求自己的dns，用REDIRECT模式，op本身，还能勉强能ping得通，TPROXY模式下都不通，也试过重置配置都不行。恢复上个版本就正常！

**Comment by xh0823** [comment]
1

**Comment by snakwu** [comment]
@xh0823  我也是官方源码

**Comment by handsomeji** [comment]
不要用firewall4 用firewall(3)
不要用nftables 用iptables

**Comment by snakwu** [comment]
@xiaorouji  大佬，但前面的版本又正常哦

**Comment by Tonkercke** [comment]
同上，使用4.51無論怎麽設置都無法上網，上一個版本一切正常。系統版本：官方發行版openwrt 21.02.2。

**Comment by WXR2727** [comment]
Lean的源码编译 passwall 用Tproxy么

**Comment by xh0823** [comment]
> Lean 的源码编译 passwall 用Tproxy么
1

**Comment by xh0823** [comment]
> 不要用firewall4 用firewall(3) 不要用nftables 用iptables

1

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/88b198cf5d362d46c2f3c07756b98c3551810bf1

**Comment by xh0823** [comment]
> [88b198c](https://github.com/xiaorouji/openwrt-passwall/commit/88b198cf5d362d46c2f3c07756b98c3551810bf1)

谢谢大佬可以了
