### ISSUE TITLE
服务端开启tls速度很慢

### ISSUE THREAD

**Issue by Paris0-0** [xiaorouji/openwrt-package#1813]
## 描述bug(必填)
passwall server端开启tls，外网设备连接后速度特别慢，不管是xray还是trojan-plus的tls开启后都很慢，关闭tls或使用shadowsocks速度正常

## 系统相关信息(必填) 
passwall版本：4.50-3

**Comment by 0xffffharry** [comment]
什么设备

**Comment by Paris0-0** [comment]
newifi d2 ，我又试了下x64设备速度正常，可能是特例，重刷也没用

**Comment by 0xffffharry** [comment]
垃圾设备就不要追求什么性能了

**Comment by Paris0-0** [comment]
额没追求性能，就是开了tls基本就不可用了，关了一切正常
