### ISSUE TITLE
Passwall 服务器端 打不开

### ISSUE THREAD

**Issue by sol1999** [xiaorouji/openwrt-package#1815]
## 日志信息(必填！)
Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /tmp/etc/passwall_server/bin/ss-server)
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_free: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_auth_decrypt: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_setkey: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_finish: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_starts: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_reset: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md5_ret: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_starts: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_update: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_set_iv: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_get_size: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_init: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_setup: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_setup: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_free: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_info_from_string: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_hmac_finish: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_cipher_auth_encrypt: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_info_from_string: symbol not found
Error relocating /tmp/etc/passwall_server/bin/ss-server: mbedtls_md_init: symbol not found

## 截图
![图片](https://user-images.githubusercontent.com/56070782/156376629-bdefdabb-450e-4903-bcc2-8aa3ac1637c6.png)

**Comment by 0xffffharry** [comment]
Error loading shared library libmbedcrypto.so.3: No such file or directory

依赖出了问题

**Comment by Takea3** [comment]
我也这样，怎么解决啊？
