### ISSUE TITLE
关于ip111.cn

### ISSUE THREAD

**Issue by gc89925** [xiaorouji/openwrt-package#1818]
## 你的功能请求是否与问题有关？ 请描述。(必填)
之前一直都有IP111.cn，怎么最近编译出来的版本没了，之前哪里还有个开关可以打开，现在彻底没了，用这个功能用只习惯了，能不能再加回来

**Comment by handsomeji** [comment]
无必要的功能，可以自己浏览器收藏这个网页

**Comment by Diffused7245** [comment]
[ip.skk.moe](https://ip.skk.moe)也不错，但是有点可惜没有从谷歌访问的选项，下面倒是有PING墙外网站的功能。而且偶尔要卡一会，过个人机验证才能进去。

**Comment by zxlhhyccc** [comment]
> [ip.skk.moe](https://ip.skk.moe)也不错，但是有点可惜没有从谷歌访问的选项，下面倒是有PING墙外网站的功能。而且偶尔要卡一会，过个人机验证才能进去。

openclash怎么就可以呢？
