### ISSUE TITLE
324ab7a 版本编译后安装报错，重启路由后hysteria无法正常连接

### ISSUE THREAD

**Issue by kentooo** [xiaorouji/openwrt-package#1823]
## 描述bug(必填)
编译后安装，configuring luci-app-passwall时出错，

## 复现步骤(必填)
1. openwrt sdk 21.02.02编译
2. 安装

## 你想要实现的目的(必填)
fixed it

## 日志信息(必填！)
error info:

```
/usr/share/passwall/app.sh: line 490: can't create /tmp/etc/passwall//tmp/etc/passwall/SOCKS_f2edd122ebdf40b6a8dd50c278a35cf5.json: nonexistent directory
```

## 截图
none

## 系统相关信息(必填)
luci-app-passwall 4.51 dev.324ab7a

**Comment by handsomeji** [comment]
Fix.

**Comment by 0xffffharry** [comment]
hysteria 使用 IPv6 连接时需要加 [] 否则 hysteria 错误退出

**Comment by handsomeji** [comment]
> hysteria 使用 IPv6 连接时需要加 [] 否则 hysteria 错误退出

8a931d583547179e09769118235685f84ef9468b
