### ISSUE TITLE
自动切换因网络状态判断错误不停切换

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#1842]
## 描述bug(必填)
passwall根据https://www.google.com/generate_204的状态（200和204）来判断是否联网
实际使用中返回404，passwall误认为无法联网,反复切换节点。

## 复现步骤(必填)
测试
root@OPENWRT 11:45 PM /# /usr/share/passwall/test.sh test_url "http://www.google.com/generate_204" 5 30
返回404

## 你想要实现的目的(必填)
正确判断网络是否通畅

## 截图
![新建 BMP 图像](https://user-images.githubusercontent.com/50773084/158912186-8a385e69-92de-45c2-a8d7-c6536e803db3.jpg)

## 其他相关信息
/usr/share/passwall/test.sh中的脚本改成返回404也认为网通就行了
case "$status" in
		204|\
		404|\
		200)
			status=200
		;;
	esac
改成返回404也认为网通就行
了

**Comment by 0xffffharry** [comment]
理论上来说只要有 HTTP 状态码就是可以连接的，脚本检测方式不是很合理

**Comment by handsomeji** [comment]
理论上是返回204才是正常的，返回404你确定不是节点问题？

**Comment by ghost** [comment]
![屏幕截图 2022-03-21 221016](https://user-images.githubusercontent.com/50773084/159279449-82b8983e-32a3-450b-80b6-50ac514f0f72.jpg)
![屏幕截图 2022-03-21 221126](https://user-images.githubusercontent.com/50773084/159279494-51d39005-a52a-4ec9-aaca-568a2be59f53.jpg)
用浏览器打开状态码204，脚本返回404，同一个节点
