### ISSUE TITLE
编译菜单中找不到luci-app-passwall选项

### ISSUE THREAD

**Issue by Nicepaul** [xiaorouji/openwrt-package#1851]
编译菜单中找不到luci-app-passwall选项，以前是有的。
编译的是Lean openwrt
在/lede/feeds.conf.default中已添加src-git passwall https://github.com/xiaorouji/openwrt-passwall

./scripts/feeds update -a && ./scripts/feeds install -a
显示：
Create index file './feeds/packages.index' 
Create index file './feeds/luci.index' 
Create index file './feeds/routing.index' 
Create index file './feeds/telephony.index' 
Create index file './feeds/jerryk.index' 
Create index file './feeds/passwall.index' 
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed jerryk.
Installing all packages from feed passwall.

但是make menuconfig后在luci中没有luci-app-passwall，之前这么操作是有的，这次是全新git clone lede再改feeds.conf.default然后feed update/install，怎么也找不到passwall了。
一直是用passwall，编译不了好失落，请大神看一下怎么解决，谢谢！

**Comment by microdockman** [comment]
> https://github.com/coolsnowwolf/lede/issues/9001#issuecomment-1059184060

**Comment by violetice** [comment]
```
# 增加一条
src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall;luci

./scripts/feeds update -a && ./scripts/feeds install -a
```
