### ISSUE TITLE
关于返回至概况按钮优化的建议

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-package#1855]
## 描述bug(必填)
返回至概况按钮应该是，只要用户没有点击保存或者保存引用，然后单击了返回，理论应该作废所有该页的操作，但是实际操作好像并不是这样
## 复现步骤(必填)
选择节点列表,单击添加节点，然后在该页不做任何操作就点击返回至概况，此时会增加一个无效的空白节点
## 你想要实现的目的(必填)
不做任何保存返回不应该增加这个无效节点
## 日志信息(必填！)
无需日志
## 截图
![image](https://user-images.githubusercontent.com/34025388/160241735-000b180e-b173-4116-892d-ef3aa1727b0c.png)
![image](https://user-images.githubusercontent.com/34025388/160241756-2cc8a9a0-a50b-4fe8-b583-1490005a2b6b.png)
![image](https://user-images.githubusercontent.com/34025388/160241763-364a6651-d7d1-4071-a9d2-091106a79733.png)
## 系统相关信息(必填)
最新版本。所有历史版本都应该有这个问题，包括passwall2
## 其他相关信息
无

**Comment by handsomeji** [comment]
这个其实是lua luci的设计问题

**Comment by WYC-2020** [comment]
> 这个其实是lua luci的设计问题

是的，我看了只要用了luci的这个返回就会有问题，openclash没用他的，是自己实现的就没这个问题哈哈，要是关闭了，大佬有时间可以按openclash那个吧返回这些搞下，辛苦了
