### ISSUE TITLE
节点的添加按钮出不来配置界面

### ISSUE THREAD

**Issue by bwb0101** [xiaorouji/openwrt-package#1863]
## 描述bug(必填)
点节点的添加按钮，界面出不来，会报2个302 http重定向，如图
![image](https://user-images.githubusercontent.com/5220242/161030331-9e037ceb-cde8-4eb6-8c32-2443d1307db2.png)
![image](https://user-images.githubusercontent.com/5220242/161030433-90912081-5afe-4f69-9b4e-49a4f4db5071.png)
![image](https://user-images.githubusercontent.com/5220242/161030534-0a2d0788-7088-4771-8cef-259ac8599bf3.png)

最后出来一个空的节点，点击编辑也一样出不来界面，也是302
![image](https://user-images.githubusercontent.com/5220242/161028093-e1835b0f-eb58-46c3-abd6-f0e38f1a1e71.png)

但订阅的节点是可以正常编辑的，就是新增的有问题。

## 系统相关信息(必填)

最后一次编译时间是3.28，LUCI用的是v1版

Microsoft Edge
版本 101.0.1198.0 (正式版本) dev (64 位)

## 其他相关信息

新刷的Lienol固件

**Comment by bwb0101** [comment]
Lienol main分支的固件

这个有问题的节点如果点复制会报错：
/usr/lib/lua/luci/controller/passwall.lua:290: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/usr/lib/lua/luci/controller/passwall.lua:290: in function </usr/lib/lua/luci/controller/passwall.lua:286>

**Comment by handsomeji** [comment]
用官方openwrt会出现吗？如果不会应该是Lienol源码的问题

**Comment by Lienol** [comment]
已回滚
