### ISSUE TITLE
 hysteria的客户端配置文件，新增"retry"参数

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-package#1864]
## 你的功能请求是否与问题有关？ 请描述。(必填)
根据hy的文档https://github.com/HyNetwork/hysteria/wiki/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95
客户端配置里
  "retry": 3, // 启动时连接服务器的重试次数。默认为 0 不重试，负数为无限重试
  "retry_interval": 5, // 重试间隔，单位为秒

我查看了生成的配置文件 "retry"参数为空没生成。即 默认0 不重试。

## 描述你想要的解决方案 (必填)
建议将生成的配置文件，加入
  "retry": -1, // 启动时连接服务器的重试次数。默认为 0 不重试，负数为无限重试
  "retry_interval": 5, // 重试间隔，单位为秒

方便更改了VPS端配置后，重启了hy，客户端会也自动重连。现在是手动保存应用一次passwall。

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/37f598eec05a463e3ab782e40ee722ba2cb6069e
