### ISSUE TITLE
TCP恢复切换不工作

### ISSUE THREAD

**Issue by nitsort** [xiaorouji/openwrt-package#1868]
## 描述bug(必填)

使用Xray分流，节点是Xray Trojan，开启自动切换。
![image](https://user-images.githubusercontent.com/23069540/161364917-c3b5ebf0-9e28-4eda-aaba-21ce3939ff44.png)

切换之后无法自动切回主节点，此时节点列表那里的可用性测试是通的。等到下次当前节点出问题时才能切回来。

另外，这里的当前节点一直显示的是分流节点，切换之后也是。
![image](https://user-images.githubusercontent.com/23069540/161366042-513646f7-8e59-47ce-9cfa-c7676bbf7ba0.png)

## 复现步骤(必填)

1、主节点故障
2、自动切换
3、主节点恢复

## 你想要实现的目的(必填)

主节点恢复时能自动切回来

## 日志信息(必填！)

```
2022-04-02 11:27:40: 自动切换检测：TCP节点【Xray：[🇯🇵 Japan 23 [Premium]]】异常，切换到下一个备用节点检测！
2022-04-02 11:28:20: 自动切换检测：TCP节点【Xray：[🇭🇰 Hong Kong 22 [Premium]]】异常，切换到下一个备用节点检测！
2022-04-02 11:28:22: 自动切换检测：TCP节点【Xray：[🇰🇷 Korea 3 [Premium]]】正常，切换到此节点！
2022-04-02 11:28:25: 自动切换检测：TCP节点切换完毕！
```

## 截图

无

## 系统相关信息(必填)

passwall 4.51

## 其他相关信息

无

**Comment by chenyajunai** [comment]
我也遇到了，切换不回去

**Comment by SakuraFallingMad** [comment]
分流切换策略是，切换分流节点内的“默认节点”
TCP节点当然还是分流节点
那么，切换恢复也是改变的是分流节点中的“默认节点”，由于我不用切换恢复的功能，不清楚是否失效。
请观察。

**Comment by CDLLY** [comment]
我这边passwall总开关，和关闭节点选项失效，只能用init.d启动或者关闭，然后点passwall还会自动收缩侧边菜单...
3月初版本和passwall2没有这些问题...
