### ISSUE TITLE
自动兼容1.17 1.18

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#1878]
自动兼容1.17 1.18

_Originally posted by @WYC-2020 in https://github.com/xiaorouji/openwrt-passwall/issues/1874#issuecomment-1091051614_

**Comment by wazzx** [comment]
今天编译了还是有问题：条件没有改变和上面还是一样的
```
Applying ./patches/010-go-1.18.patch using plaintext:
patching file common/protocol/quic/sniff.go
Hunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file common/protocol/quic/sniff.go.rej
patching file go.mod
Hunk #1 FAILED at 11.
Hunk #2 FAILED at 44.
2 out of 2 hunks FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk #1 FAILED at 209.
1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
Patch failed!  Please fix ./patches/010-go-1.18.patch!
Makefile:109: recipe for target '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.prepared_01c15af36a98bb7511171cac39b529ae_18f1e190c5d53547fed41a3eaa76e9e9' failed
make[2]: *** [/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.prepared_01c15af36a98bb7511171cac39b529ae_18f1e190c5d53547fed41a3eaa76e9e9] Error 1
make[2]: Leaving directory '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/feeds/small/v2ray-core'
time: package/feeds/small/v2ray-core/compile#0.17#2.18#3.35
   ERROR: package/feeds/small/v2ray-core failed to build.
package/Makefile:114: recipe for target 'package/feeds/small/v2ray-core/compile' failed
make[1]: *** [package/feeds/small/v2ray-core/compile] Error 1
make[1]: Leaving directory '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64'
/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:221: recipe for target 'package/luci-app-passwall/compile' failed
make: *** [package/luci-app-passwall/compile] Error 2
```

**Comment by WYC-2020** [comment]
> 今天编译了还是有问题：条件没有改变和上面还是一样的
> 
> ```
> Applying ./patches/010-go-1.18.patch using plaintext:
> patching file common/protocol/quic/sniff.go
> Hunk #1 FAILED at 8.
> 1 out of 1 hunk FAILED -- saving rejects to file common/protocol/quic/sniff.go.rej
> patching file go.mod
> Hunk #1 FAILED at 11.
> Hunk #2 FAILED at 44.
> 2 out of 2 hunks FAILED -- saving rejects to file go.mod.rej
> patching file go.sum
> Hunk #1 FAILED at 209.
> 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> Patch failed!  Please fix ./patches/010-go-1.18.patch!
> Makefile:109: recipe for target '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.prepared_01c15af36a98bb7511171cac39b529ae_18f1e190c5d53547fed41a3eaa76e9e9' failed
> make[2]: *** [/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-aarch64_generic_musl/v2ray-core-5.0.3/.prepared_01c15af36a98bb7511171cac39b529ae_18f1e190c5d53547fed41a3eaa76e9e9] Error 1
> make[2]: Leaving directory '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/feeds/small/v2ray-core'
> time: package/feeds/small/v2ray-core/compile#0.17#2.18#3.35
>    ERROR: package/feeds/small/v2ray-core failed to build.
> package/Makefile:114: recipe for target 'package/feeds/small/v2ray-core/compile' failed
> make[1]: *** [package/feeds/small/v2ray-core/compile] Error 1
> make[1]: Leaving directory '/home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64'
> /home/xxxx/openwrt-sdk-21.02.2-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:221: recipe for target 'package/luci-app-passwall/compile' failed
> make: *** [package/luci-app-passwall/compile] Error 2
> ```

这我不清楚，反正我测试我自己仓库的没任何问题，我和这里的有区别

**Comment by WYC-2020** [comment]
看你这个明显是patch有问题，得更新了
