### ISSUE TITLE
请求恢复UPX压缩选项

### ISSUE THREAD

**Issue by Chikage0o0** [xiaorouji/openwrt-package#1883]
## 你的功能请求是否与问题有关？ 请描述。(必填)
请问删除UPX是有什么原因吗？这对于硬路由来说十分致命。

## 描述你想要的解决方案 (必填)
恢复UPX选项

**Comment by WYC-2020** [comment]
自己fork一份让你revert把，说不定哪天就跑路了哈哈

**Comment by Beginner-Go** [comment]
打个工 买个好点的 ARM 路由吧

**Comment by Chikage0o0** [comment]
> 打个工 买个好点的 ARM 路由吧

部分老设备没必要因此放弃吧，原来那样默认关闭，需要的再自己打开不是挺好的

**Comment by Chikage0o0** [comment]
别这也一刀切啊

**Comment by Beginner-Go** [comment]
建议fork一份然后revert
