### ISSUE TITLE
V2ray/Xray分流规则，AD选项的默认值geosite:category-ads，有误

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-package#1885]
## 描述bug(必填)
默认值是
geosite:category-ads

## 复现步骤(必填)
不确定geosite:category-ads，少了-all是否生效，我是自己发现就改了

## 你想要实现的目的(必填)
文档上的默认值是
geosite:category-ads-all

## 系统相关信息(必填)
Passwall 和 Passwall2都有此问题

## 其他相关信息
V2fly的链接 https://github.com/v2fly/domain-list-community#usage-example
Loyalsoldier的v2ray-rules链接 https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat

geo数据库看了一下是用的Loyalsoldier的加强版。

**Comment by smallprogram** [comment]
改了，你试试把

**Comment by chika0801** [comment]
> 改了，你试试把

3Q~
