### ISSUE TITLE
4.53OP官方版本用不了

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#1888]
无论用什么方式都不可以用，防火墙3或4都是不能用以前官方的防火墙3或4都可以用，今天升级了就用不了. 
插件只有pdnsd和xray

**Comment by wazzx** [comment]
我这边也是op21.02.2，4.53没有问题

**Comment by xh0823** [comment]
> 我也是op21.02.2，4.53没有问题



> 我也是op21.02.2，4.53没有问题

我的是master

**Comment by Beginner-Go** [comment]
应该是官方master更新了什么东西  导致passwall不兼容

**Comment by xh0823** [comment]
> 应该是官方更新的东西导致passwall不升级

感谢各位大佬有时间看看

**Comment by zxlhhyccc** [comment]
> 无论用什么方式都不可以用，防火墙3或4都是不能用以前官方的防火墙3或4都可以用，今天升级了就用不了. 插件只有pdnsd和xray

我也和你的情况一样，在官方master分支下，启动passwall后，显示软件在运行，但实际会导致国内、国外都上不了，表现为：断网状态。而在系统日志中显示找不到passwall数据库文件，查数据库发现passwall是软链接，退回4.52-3版网络正常使用，数据库为文件夹！
![image](https://user-images.githubusercontent.com/45259624/163315695-ab62f477-b4df-4c0d-8bfe-f75356cd8fef.png)
![image](https://user-images.githubusercontent.com/45259624/163315719-2e806a61-eed0-41b3-9a3b-0669cce0abde.png)

**Comment by handsomeji** [comment]
不要装 procd-ujail 坑

**Comment by xh0823** [comment]
> 不要装procd-ujail坑

大佬这个做什么用的，删除这个就可以用了，谢谢大佬
