### ISSUE TITLE
对于不代理的LAN IP的DNS解析问题

### ISSUE THREAD

**Issue by Utaea** [xiaorouji/openwrt-package#1898]
## 描述bug(必填)
使用Passwall给一些LAN IP设置了不走代理，后面这些LAN IP访问一些网站出现了问题，后面经过排查是由于部分域名（如gstatic.com）本身国内有节点，但DNS请求返回的是国外的IP且该IP可能已被GFW封禁导致反而出现问题

后面经过简单排查发现passwall会将gfwlist内的域名放置至dnsmasq.d配置文件夹中，对于gfwlist内的域名的DNS解析请求转发到7914端口再由其他防污染DNS方案获得结果；某些情况下会索性直接设置dnsmasq的上游DNS为passwall自己的防污染DNS方案

这样设计的结果就是，虽然一些LAN IP已经绕过了代理，但是这些设备的DNS请求仍然收到上述机制的影响，对于一些特殊域名如 gstatic.com 就会出现问题，个人认为这样的设计机制不符合“绕过”这一概念，不应直接修改dnsmasq，因为这样会影响到不代理的LAN IP

## 复现步骤(必填)
1. 在“访问控制”中设置IP如192.168.0.123的TCP代理模式为不代理
2. 在Passwall“基本设置”界面正常开启代理，在测试中只开启了TCP节点代理
3. 在IP为192.168.0.123的设备上访问如www.google.cn/chrome，发现浏览器长期卡在白屏，打开审查元素并在Network一栏观察可发现www.gstatic.com请求卡住
4. 同样在该设备上ping www.gstatic.com 或是nslookup www.gstatic.com ，可以发现解析的IP是美国Google的IP而不是谷翔位于北京的IP，且因为美国Google IP几乎全数被封禁因而导致该设备无法访问 www.gstatic.com ，给访问造成很大影响

## 你想要实现的目的(必填)
我目前想到的更好的方案是，passwall启动时，不修改dnsmasq的配置，而是用iptables将需要代理的LAN IP的UDP 53请求转发到 7914 端口上，来实现需要代理的LAN IP的防污染DNS。

## 日志信息(必填！)
无相关日志信息

## 截图
以下就是在IP为192.168.0.123设备上，对www.gstatic.com在passwall开关前后的解析结果截图
![passwall_issue](https://user-images.githubusercontent.com/69945099/163397584-870bd473-0f92-403b-8f50-9e043130011c.png)

## 系统相关信息(必填)
Passwall 版本为 https://github.com/xiaorouji/openwrt-passwall/commit/bad39191e6983da679b4be1e95bc43b25de533df 此 commit 编译而来
Chrome 版本 100.0.4896.75(64 bit)

**Comment by smallprogram** [comment]
> 1. 在“访问控制”中设置IP如192.168.0.123的TCP代理模式为不代理
> 2. 在Passwall“基本设置”界面正常开启代理，在测试中只开启了TCP节点代理
> 3. 在IP为192.168.0.123的设备上访问如www.google.cn/chrome，发现浏览器长期卡在白屏，打开审查元素并在Network一栏观察可发现www.gstatic.com请求卡住

首先，你这个问题就是个悖论。既然访问google了，还不代理。这明显是不可能的。
还有google.cn这个域名本身就是被屏蔽的，你不走代理是不可能访问的，除非你自己架设了个假google.cn并且在GFW做了劫持。

> 4. 同样在该设备上ping [www.gstatic.com](http://www.gstatic.com) 或是nslookup [www.gstatic.com](http://www.gstatic.com) ，可以发现解析的IP是美国Google的IP而不是谷翔位于北京的IP，且因为美国Google IP几乎全数被封禁因而导致该设备无法访问 [www.gstatic.com](http://www.gstatic.com) ，给访问造成很大影响

上面你写的www.gstatic.com想走国内DNS解析。你直接把他加进直连列表里不就行了。让pw开启ICMP劫持，清空你本地的DNS缓存，再ping肯定是国内ip。
![image](https://user-images.githubusercontent.com/6050360/163406786-f89e8397-154a-47bb-b47b-5b51bec63be3.png)

还有你的代理方式，为什么不把全局设置为不代理，代理的ip在访问控制里开启代理。如果你是因为大部分设备都需要代理，这样设置不方便话，那么访问控制里具有IP段的设置方式，也一样能实现。

> 使用Passwall给一些LAN IP设置了不走代理，后面这些LAN IP访问一些网站出现了问题，后面经过排查是由于部分域名（如gstatic.com）本身国内有节点，但DNS请求返回的是国外的IP且该IP可能已被GFW封禁导致反而出现问题
> 
> 后面经过简单排查发现passwall会将gfwlist内的域名放置至dnsmasq.d配置文件夹中，对于gfwlist内的域名的DNS解析请求转发到7914端口再由其他防污染DNS方案获得结果；某些情况下会索性直接设置dnsmasq的上游DNS为passwall自己的防污染DNS方案
> 
> 这样设计的结果就是，虽然一些LAN IP已经绕过了代理，但是这些设备的DNS请求仍然收到上述机制的影响，对于一些特殊域名如 gstatic.com 就会出现问题，个人认为这样的设计机制不符合“绕过”这一概念，不应直接修改dnsmasq，因为这样会影响到不代理的LAN IP

对于Bug描述，我只想说，你拥有一个羊角锤，想要撬钉子，正确的方法应该是用羊角那头去撬钉子，但是非得拿锤子头撬钉子，我也无话可说。

综上这并不属于Bug

**Comment by Utaea** [comment]
首先 www.google.cn 在国内并未被屏蔽，且 https://www.google.cn/chrome 是非常常用的在国内用来下载Chrome的官方网站

其次是我刚刚按照你的方法，将 www.gstatic.com 加入至直连列表，并清除了DNS缓存，但结果依旧是美国Google IP，我不知道是不是我的方法有问题；这里我并不想要这个域名可以被ping，只是用来确认DNS返回的IP到底是什么

再者我也确认过了，默认不开启代理，仅对部分IP开启代理的情况下，上述现象依旧存在

最后我个人认为既然是不代理，那么对于不代理的设备来说其网络环境应该没有任何更改，包括所有链接及DNS设置。确实我们可以通过将gstatic.com加入白名单的方式规避这一问题，但感觉这种方式不好，因为未来可能有别的域名处于虽然在名单里但是在我目前所在的地区可用的状态，以及每次只有遇到问题了才能排查出具体哪个域名随后再加入白名单是很费事的。

也许这个issue不应称之为bug，也许我的应用场景比较小众特殊，但我仍然觉得仅对需要代理的LAN IP进行防污染DNS处理是比较合理的。

**Comment by handsomeji** [comment]
> 其次是我刚刚按照你的方法，将 [www.gstatic.com](http://www.gstatic.com) 加入至直连列表，并清除了DNS缓存，但结果依旧是美国Google IP，我不知道是不是我的方法有问题；这里我并不想要这个域名可以被ping，只是用来确认DNS返回的IP到底是什么

1. gstatic.com 默认存在于代理列表，若要加入直连列表，请先在代理列表把他删掉。
2. gstatic.com 在我的网络环境里，如果不代理，会出现一些莫名其妙的问题。
3. 修改规则列表后，请到DNS选项，清空IPSET后。然后客户端需要清除一下DNS。

**Comment by smallprogram** [comment]
> 首先 [www.google.cn](http://www.google.cn) 在国内并未被屏蔽，且 https://www.google.cn/chrome 是非常常用的在国内用来下载Chrome的官方网站
> 
> 其次是我刚刚按照你的方法，将 [www.gstatic.com](http://www.gstatic.com) 加入至直连列表，并清除了DNS缓存，但结果依旧是美国Google IP，我不知道是不是我的方法有问题；这里我并不想要这个域名可以被ping，只是用来确认DNS返回的IP到底是什么
> 
> 再者我也确认过了，默认不开启代理，仅对部分IP开启代理的情况下，上述现象依旧存在
> 
> 最后我个人认为既然是不代理，那么对于不代理的设备来说其网络环境应该没有任何更改，包括所有链接及DNS设置。确实我们可以通过将gstatic.com加入白名单的方式规避这一问题，但感觉这种方式不好，因为未来可能有别的域名处于虽然在名单里但是在我目前所在的地区可用的状态，以及每次只有遇到问题了才能排查出具体哪个域名随后再加入白名单是很费事的。
> 
> 也许这个issue不应称之为bug，也许我的应用场景比较小众特殊，但我仍然觉得仅对需要代理的LAN IP进行防污染DNS处理是比较合理的。

不知道是我本地网络的问题，还是你网络的特殊性，https://www.google.cn/chrome 这个域名在我这里就是被墙状态。他的真实IP就是142开头的美丽国IP。
![image](https://user-images.githubusercontent.com/6050360/163420964-89037e78-b69f-4943-a28f-e73c094d6631.png)

而国内解析，不同的地区解析的IP都各不同，大部分都是跳转至帝都谷歌云。
![image](https://user-images.githubusercontent.com/6050360/163421654-3d1bf6dd-451c-483b-8c9a-4c48c5feb9e9.png)

我建议还是走代理把，访问原生的。
如果你非要使用国内的谷歌云。那就尝试把全局代理设置为不代理。把你那台不想代理的机器IP排除在访问控制列表之外。如果还不行，就把你那个机器本地设置静态国内DNS。应该可以解决你的问题。

至于你说的“iptables将需要代理的LAN IP的UDP 53请求转发到 7914 端口”这个方案，抱歉，我觉得不能因为小众问题修改业务逻辑。你可以尝试dns2scoks指向你的7914。

**Comment by Utaea** [comment]
> 1. gstatic.com 默认存在于代理列表，若要加入直连列表，请先在代理列表把他删掉。
> 2. gstatic.com 在我的网络环境里，如果不代理，会出现一些莫名其妙的问题。
> 3. 修改规则列表后，请到DNS选项，清空IPSET后。然后客户端需要清除一下DNS。

谢谢，我已将其移除代理列表内，也清空了IPSET和客户端DNS，但测试下来返回的依旧是美国Google IP。有一个细节是因为在网页端修改代理列表提示”提交的安全令牌无效或已过期“，所以我是直接修改了/usr/share/passwall/rules/direct_host和proxy_host并重启的passwall

这里我无意想说google.cn或是gstatic.com就一定在国内完全可以访问，只是想提议对于不代理的设备或许DNS直连会是个更好的办法，能否提供一个选项或是如何。如果讨论下来认为不应采取该提议的话，那这个issue就可以关闭了，我自行想办法解决，谢谢诸位。

**Comment by handsomeji** [comment]
我可以提供一个方案给你
默认节点随便选一个，模式均不代理（包含路由器自身代理模式），访问控制的节点选一个（不能和默认相同），代理模式看自己。（设计缺陷）

**Comment by handsomeji** [comment]
> 谢谢，我已将其移除代理列表内，也清空了IPSET和客户端DNS，但测试下来返回的依旧是美国Google IP。

![image](https://user-images.githubusercontent.com/60100640/163427266-c04485fc-f9e0-4a2c-8355-c04cd3241d37.png)

亲测没有问题

**Comment by Utaea** [comment]
> 我可以提供一个方案给你 默认节点随便选一个，模式均不代理（包含路由器自身代理模式），访问控制的节点选一个（不能和默认相同），代理模式看自己。（设计缺陷）

非常感谢，此法有效，可以正常使用了，目前的话就以这种方式继续用吧。谢谢作者的回复和付出。

**Comment by handsomeji** [comment]
passwall目前有个逻辑就是，如果访问控制里面的节点和默认节点不一致，将会启动一个新的dnsmasq进行分流且iptables重定向DNS。逻辑比较复杂一点，另外如果对分流有更高的需求建议使用passwall2。

**Comment by smallprogram** [comment]
> passwall目前有个逻辑就是，如果访问控制里面的节点和默认节点不一致，将会启动一个新的dnsmasq进行分流且iptables重定向DNS。逻辑比较复杂一点，另外如果对分流有更高的需求建议使用passwall2。

老大，PW2与PW能同时编译不？

**Comment by handsomeji** [comment]
> 老大，PW2与PW能同时编译不？

可以，package名和目录结构没有重复就可以

**Comment by eightsheep67** [comment]
> 我可以提供一个方案给你
> 默认节点随便选一个，模式均不代理（包含路由器自身代理模式），访问控制的节点选一个（不能和默认相同），代理模式看自己。（设计缺陷）

大佬，问一下，用了这个方法，那路由本机要走代理怎么办。我尝试加入192.168.1.1还有127.0.0.1都不行。路由本机ttyd来nslookup google，youtube都是74打头的屏蔽地址。
