### ISSUE TITLE
socks 配置里http监听端口不正常

### ISSUE THREAD

**Issue by petraklux** [xiaorouji/openwrt-package#1899]
passwall版本4.53
socks 配置里
socks主开关  打开 后
但状态显示 前 对勾 后 叉，个人理解是socks监听端口正常，但http监听端口不正常。
passwall版本4.51正常，状态前后都是 对勾。

**Comment by handsomeji** [comment]
更新最新源码试下

**Comment by petraklux** [comment]
最新的源码测试已经OK

**Comment by Falld0wn18** [comment]
最新的版本是不是也有这个问题？测试了一下 socks监听打勾，http监听打叉。
