### ISSUE TITLE
规则列表直连列表不能添加

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#1905]
## 描述bug(必填)
环境：openwrt-sdk-21.02.2,规则列表直连列表不能添加

## 截图

![p2](https://user-images.githubusercontent.com/60512548/163700867-f8b9236f-cff3-4aad-9aee-0c0853b0aaf3.png)
![passwall](https://user-images.githubusercontent.com/60512548/163700870-785203c0-189f-4190-a9e4-5c8d3e726e80.png)

## 系统相关信息(必填)
 4.53.3最新版本

**Comment by handsomeji** [comment]
这垃圾js luci 真的不想兼容它了

**Comment by WYC-2020** [comment]
luci 18.06才是永远的神

**Comment by wazzx** [comment]
再反应一个bug吧，自动切换里面，只要开启，不知道为什么，就会切换到第一个备用节点来。。

**Comment by WYC-2020** [comment]
> 再反应一个bug吧，自动切换里面，只要开启，不知道为什么，就会切换到第一个备用节点来。。

那就证明你那个节点出现过断开的情况，自然别人要切换到备用了，这个应该不算bug吧

**Comment by yunhai20082008** [comment]
我用同样的sdk编译它，会编译太多无关的ipk，比如kmod-can-一大堆，但是编译luci-app-gowebdav就是很简单的几个ipk，这怎么处理

**Comment by wazzx** [comment]
> > 再反应一个bug吧，自动切换里面，只要开启，不知道为什么，就会切换到第一个备用节点来。。
> 
> 那就证明你那个节点出现过断开的情况，自然别人要切换到备用了，这个应该不算bug吧

节点应该是没有问题的，我设置的时间是6分钟一次 6秒 3次才能切换，但是这个是每次都帮我自动切换到备份的第一个节点，并且不仅仅只是我一个人啊

**Comment by wazzx** [comment]
> 我用同样的sdk编译它，会编译太多无关的ipk，比如kmod-can-一大堆，但是编译luci-app-gowebdav就是很简单的几个ipk，这怎么处理

这个我也很好奇怎么搞。

**Comment by yunhai20082008** [comment]
> > 我用同样的sdk编译它，会编译太多无关的ipk，比如kmod-can-一大堆，但是编译luci-app-gowebdav就是很简单的几个ipk，这怎么处理
> 
> 这个我也很好奇怎么搞。

我提交了这个问题，作者把问题给关了，啥回复也没有

**Comment by handsomeji** [comment]
刚编译了个22.03+js luci试了一下没有问题

**Comment by lunerseayu** [comment]
> 刚编译了个22.03+js luci试了一下没有问题

难道luci更新了，我昨天也是一样的问题……

**Comment by BOBINIUNIU** [comment]
有问题的是LuCI 21.02 Lienol (git-1a6d65a),之前的版本好像没问题。

**Comment by handsomeji** [comment]
@BOBINIUNIU 可以把固件发我看看吗

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU 可以把固件发我看看吗
就是用的https://github.com/Lienol/openwrt  21.02分支的最新代码编译的出现了这个问题。
我的固件只保留了自己的网卡驱动，在你的机器上可能无法启动，有需要的话我可以重新编译一个全驱动的。

**Comment by lunerseayu** [comment]
我的版本是，OpenWrt 21.02.2 r16495-bf0c965af0，同样的问题，luci版本为git-20.074.84698-ead5e81。不过我编译只有lxc的镜像。请问是否需要

**Comment by lunerseayu** [comment]
用Lean的luci 22.108.56096-01fdd86+OpenWrt R22.4.1没有问题

**Comment by lunerseayu** [comment]
OpenWrt 21.02.2 r16495-bf0c965af0+luci 22.108.56096-01fdd86,问题依旧。应该是21.02的问题了

**Comment by handsomeji** [comment]
就是luci 21.02的BUG，算了，回滚旧方案吧
