### ISSUE TITLE
使用pdnsd，访问有些网页的时候会先访问失败，过一会刷新后才能打开

### ISSUE THREAD

**Issue by Gleeeeeman** [xiaorouji/openwrt-package#1910]
## 复现步骤(必填)
现在使用的是passwall，dns用的是passwall中自带的“pdnsd 通过TCP节点请求DNS”，其他的都是默认设置。
局域网客户端获取到的dns地址是指向路由器地址的。
现在出现了一个问题，就是访问有一些网站的时候，会先显示找不到dns，然后网页访问失败。过一会再刷新才会刷新出页面。
关掉pdnsd之后就没有这个问题。
猜测问题可能出在，客户端向路由器请求dns的时候，路由器里没有这个域名的缓存，路由器的上游dns服务器回应的速度慢一点，所以路由器就先给客户端返回一个找不到dns的结果。
等过一会上游dns服务器把ip地址发给路由器之后，才能返回正确的结果，然后此时刷新页面就会正常进入。

## 你想要实现的目的(必填)

正常上网的时候如果遇到一个返回dns结果比较慢的网站，浏览器中网页会加载的比较慢，然后顺利进入。
但是如果是用pdnsd之后，页面加载速度很快，但是会先显示无法访问网站，过一会刷新后才可以正常进入。

## 日志信息(必填！)

![image](https://user-images.githubusercontent.com/50981718/163976066-3c5baee8-6a3a-4f1b-ad77-9bfaab81bffd.png)

## 截图

无

## 系统相关信息(必填)
 
passwall 4.43-1

Chromium 86.0.4240.198 （64位）

**Comment by handsomeji** [comment]
反馈问题前请更新最新源码测试再反馈。

**Comment by playcase** [comment]
跟楼主问题完全一样，尝试各种设置没解决，passwall 最新版4.53-3

**Comment by playcase** [comment]
> ## 描述bug(必填)
> ## 复现步骤(必填)
> 现在使用的是passwall，dns用的是passwall中自带的“pdnsd 通过TCP节点请求DNS”，其他的都是默认设置。 局域网客户端获取到的dns地址是指向路由器地址的。 现在出现了一个问题，就是访问有一些网站的时候，会先显示找不到dns，然后网页访问失败。过一会再刷新才会刷新出页面。 关掉pdnsd之后就没有这个问题。 猜测问题可能出在，客户端向路由器请求dns的时候，路由器里没有这个域名的缓存，路由器的上游dns服务器回应的速度慢一点，所以路由器就先给客户端返回一个找不到dns的结果。 等过一会上游dns服务器把ip地址发给路由器之后，才能返回正确的结果，然后此时刷新页面就会正常进入。
> 
> ## 你想要实现的目的(必填)
> 正常上网的时候如果遇到一个返回dns结果比较慢的网站，浏览器中网页会加载的比较慢，然后顺利进入。 但是如果是用pdnsd之后，页面加载速度很快，但是会先显示无法访问网站，过一会刷新后才可以正常进入。
> 
> ## 日志信息(必填！)
> ![image](https://user-images.githubusercontent.com/50981718/163976066-3c5baee8-6a3a-4f1b-ad77-9bfaab81bffd.png)
> 
> ## 截图
> 无
> 
> ## 系统相关信息(必填)
> passwall 4.43-1
> 
> Chromium 86.0.4240.198 （64位）
> 
> ## 其他相关信息

我终于知道原因了，关闭ipv6就解决了，新版passwall dnsl勾选“过滤代理域名 IPv6”也可以。看来作者已经意识到这个问题，特别加这个实验性选项。
