### ISSUE TITLE
tcp代理 tproxy方式下，路由本身通信故障

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#1917]
## 描述bug(必填)
tcp代理 tproxy方式下，路由本身通信故障

## 复现步骤(必填)
1、转发配置-TCP代理方式Tproxy
2、不管勾选与否IPv6透明代理
以上会发生路由本机无法通讯代理地址
之后调整至Redirect模式，现象消失

## 你想要实现的目的(必填)
希望修复，回归早先正常状态，最后一次功能正常为commit 8bce9e72b4f31dcf4cffe473c68e1c2f09654c87

## 日志信息(必填！)
暂无异常系统日志

## 截图
路由内部应用更新秒失败
![image](https://user-images.githubusercontent.com/31793080/164355853-0423550d-fd27-49c3-b54a-fa687defab2d.png)
![image](https://user-images.githubusercontent.com/31793080/164355895-9114d70e-56ad-4b56-a3b0-91daeb6112d0.png)

## 系统相关信息(必填)
luci-app-passwall 4.53-7
Chrome 版本 100.0.4896.127（正式版本） （64 位）

## 其他相关信息
同一本地&云编译环境，除passwall外源码未变更。
故障发生起于commit 33af661703585c5162cd9f1763bf063d1e4ae42d

**Comment by xiaorouji** [comment]
我就在用，正常啊。
你是不是在用的lean固件，试试
https://github.com/xiaorouji/openwrt-passwall2/issues/83#issuecomment-1103608294

**Comment by SakuraFallingMad** [comment]
老大，并没有启用劫持dns的规则，只是adg（53）——dnsmasq（54）——chinadns（5053）——smartdns【国内】（6053）&dnscrypt-proxy【国外】（7053）
这样的套娃，做本地无污染dns。然后passwall国外dns设置本地7053端口。

其他变动都没有变更，就是在最新源码更新后出问题了，我上个版本commit https://github.com/xiaorouji/openwrt-passwall/commit/8bce9e72b4f31dcf4cffe473c68e1c2f09654c87 没问题

只是路由本机能解析ip，但是连接地址就秒失败。chinadns的规则更新&passwall规则更新错误如图：
![image](https://user-images.githubusercontent.com/31793080/164384803-41693510-14bc-417b-91d4-230728cdc454.png)
![image](https://user-images.githubusercontent.com/31793080/164384971-40b59464-c0be-4265-bf3f-e4bac6f2a8e7.png)
奇怪的是，内网子机正常使用

望老大瞅瞅有没其他可能的引发此现象的问题

**Comment by xiaorouji** [comment]
我看到你这一堆DNS头皮已经发麻

**Comment by z1790** [comment]
我也是一样的问题，4.53-4正常，后面的版本就路由器本身不能代理了，53端口的劫持注销，udp不代理端口填上53全试过就是m不行，我的DNS简单，国内运营商的，国外xray doh

**Comment by SakuraFallingMad** [comment]
就内网客户端正常使用而言，我觉得域名和IP对应关系没问题，能排除dns这套娃出问题的可能性，可是路由本身无法代理，包括IP链接，因为我再次发现dnscrypt-proxy无法通过代理链接上游dns。

**Comment by xiaorouji** [comment]
你ssh输入/etc/init.d/passwall看看有无报错

**Comment by SakuraFallingMad** [comment]
![image](https://user-images.githubusercontent.com/31793080/164650602-7f4f6050-6a2f-47f7-abe5-39b6de158266.png)
这算是报错么

**Comment by z1790** [comment]
![image](https://user-images.githubusercontent.com/41429335/164689744-15efcc7b-ae2f-4f64-904b-76eedde09fff.png)
好像没报错 4.53-6的版本，就是路由器本身不能代理 局域网内的设备正常代理
![image](https://user-images.githubusercontent.com/41429335/164690938-26a61db5-f8c4-4c8a-b2e5-5d09025b2f8f.png)

**Comment by z1790** [comment]
我这里找到了原因了，关闭多拨和mwan3就正常了。。应该是有冲突，最新的代码也是一样，4.53-4正常没冲突

**Comment by SakuraFallingMad** [comment]
和 z1790一样，mwan3软件包都要禁用启动项，组件不能启动，哪怕不设置多拨和负载均衡
望考虑兼容，实在不想放弃这个功能

**Comment by handsomeji** [comment]
试一下最新源码

**Comment by z1790** [comment]
最新的源码开启多拨和mwan3 ipv4正常了。。ipv6路由器本身不能代理。。局域网的设备ipv4和6全能代理

**Comment by handsomeji** [comment]
@z1790 再试下

**Comment by z1790** [comment]
最新的代码正常了。。谢谢大佬

**Comment by SakuraFallingMad** [comment]
感谢大佬，我只有v4公网，之前一版本就正常了，v6只能感谢@z1790的测试了
那么issue我关了
