### ISSUE TITLE
启用tproxy后iptables执行报错的问题

### ISSUE THREAD

**Issue by MikeMiao** [xiaorouji/openwrt-package#1924]
## 描述bug(必填)
升级最新版代码后，tproxy模式无法代理。
Kidding9的openwrt，内核版本5.15.31，openwrt分支21.02.2
将passwall源码更新到最新后，发现tproxy模式无法代理，redirect模式正常

## 复现步骤(必填)
将passwall源码更新为最新
将TCP代理模式设置为Tproxy
通过命令行重启passwall，发现iptables命令执行的时候有报错：

> root@OPENWRT 12:18 AM ~# /etc/init.d/passwall restart
iptables v1.8.7 (legacy): unknown option "--restore-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): unknown option "--save-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory

>Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.7 (legacy): unknown option "--restore-mark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (legacy): unknown option "--save-mark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory

>Try `ip6tables -h' or 'ip6tables --help' for more information.

此时是无法正常访问墙外网站的。

opkg安装iptables-mod-conntrack-extra后，报错信息变化如下：

> root@OPENWRT 12:22 AM ~# opkg install iptables-mod-conntrack-extra
Installing iptables-mod-conntrack-extra (1.8.7-1) to root...
Downloading https://op.supes.top/packages/x86_64/kiddin9/iptables-mod-conntrack-extra_1.8.7-1_x86_64.ipk
Installing kmod-ipt-conntrack-extra (5.15.31-1) to root...
Downloading https://op.supes.top/packages/x86_64/kmods/5.15.31/kmod-ipt-conntrack-extra_5.15.31-1_x86_64.ipk
Installing kmod-ipt-raw (5.15.31-1) to root...
Downloading https://op.supes.top/packages/x86_64/kmods/5.15.31/kmod-ipt-raw_5.15.31-1_x86_64.ipk
Configuring kmod-ipt-raw.
Configuring kmod-ipt-conntrack-extra.
Configuring iptables-mod-conntrack-extra.

> root@OPENWRT 12:24 AM ~# /etc/init.d/passwall restart
iptables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory

>Try `iptables -h' or 'iptables --help' for more information.

> ip6tables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory

>Try `ip6tables -h' or 'ip6tables --help' for more information.

尽管有报错，但此时已经可以正常访问墙外网站了

分析iptables.sh 发现有用到socket这个match的语句如下两处：
![image](https://user-images.githubusercontent.com/17871086/164760496-41f57292-4f73-4b0e-9ad2-110723d9e43d.png)
![image](https://user-images.githubusercontent.com/17871086/164760538-381bebf3-102b-4cad-9d47-027589994368.png)

通过openwrt官网了解到，iptables-mod-tproxy这个包应该是包含了socket这个match条件的支持，这个包我是已经安装了的，信息如下：
![image](https://user-images.githubusercontent.com/17871086/164759277-1d0a8058-2d36-4cba-9c22-f2e587e190d4.png)
https://openwrt.org/packages/pkgdata/iptables-mod-tproxy

> root@OPENWRT 12:51 AM ~# opkg list-installed | grep tproxy
iptables-mod-tproxy - 1.8.7-1
kmod-ipt-tproxy - 5.15.31-1
kmod-nf-tproxy - 5.15.31-1

## 你想要实现的目的(必填)
1.了解iptables.sh内两处使用了-m socket语句的作用，如果执行失败，对passwall正常工作有无影响。
2.针对“iptables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory”这个报错，是否有可行的解决方案。

## 日志信息(必填！)
如复现步骤

## 截图
如上

## 系统相关信息(必填)
Kidding9的openwrt，内核版本5.15.31，openwrt分支21.02.2
passwall源码更新到最新

## 其他相关信息
暂无

**Comment by handsomeji** [comment]
iptables-mod-conntrack-extra

**Comment by MikeMiao** [comment]
麻烦再问下，安装iptables-mod-conntrack-extra后，仍然出现下面的错误，这个可以安全的忽略吗？
iptables v1.8.7 (legacy): Couldn't load match `socket':No such file or directory

**Comment by handsomeji** [comment]
还需要 iptables-mod-socket

**Comment by MikeMiao** [comment]
> 还需要 iptables-mod-socket

全网搜索了很久，都没发现openwrt有iptables-mod-socket这个软件包，按官方说明这个match的支持应该是放到tproxy的包里面去了
https://openwrt.org/packages/pkgdata/iptables-mod-tproxy
有可能是这个版本的tproxy包有bug？功能缺失？

**Comment by MikeMiao** [comment]
找了一个内核版本5.4.154的实例看了下，是可以正常加载-m socket的，怀疑还是内核版本的问题，重新编译再测试下

**Comment by MikeMiao** [comment]
使用lede源码重新编译5.15.35内核后故障消失，看起来可能是kmod的bug
