### ISSUE TITLE
When using Pre Proxy, so my bandwidth using 2X or it's same?

### ISSUE THREAD

**Issue by xenstar** [xiaorouji/openwrt-package#1929]
When I am using Pre Proxy, so my proxy bandwidth using 2X, or is it using 1X? 

E.g I use 1GB, but actually the bandwidth usage will be 2GB or 1GB?

![image](https://user-images.githubusercontent.com/55502651/165143578-3a99a424-f86f-4a03-8f69-6dd694c8df2d.png)

Need a clarification. because when I enable the pre-proxy, seems my internet is much more faster, I can even use direct node instead of relay node.

**Comment by handsomeji** [comment]
if the default node same as the default PreProxy node, only the default node will be used, if not, of course, double traffic.
