### ISSUE TITLE
passwall cause high CPU

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#1930]
4.53.11 版本， X86软路由，内存8G, I3865U, passwall跑一段之后出现high CPU, 然后经常有几个莫名其妙的netstat 也占很高的CPU,不知道是不是passwall起的。

![image](https://user-images.githubusercontent.com/20067401/165200711-aede8696-19b8-4918-880d-a3c3e9f656e7.png)

**Comment by GreatMichaelLee** [comment]
经测试发现，是那个节点里头自动ping/tcping的功能会起netstat 监控7913，在某种未知条件下，跑一段时间之后，会导致high CPU.

**Comment by GreatMichaelLee** [comment]
> 经测试发现，是那个节点里头自动ping/tcping的功能会起netstat 监控7913，在某种未知条件下，跑一段时间之后，会导致high CPU.

关闭自动ping后，发现还是会起netstat，不知道在干嘛，每秒钟一下导致高cpu，杀掉passwall后 cpu下去了

**Comment by GreatMichaelLee** [comment]
> > 经测试发现，是那个节点里头自动ping/tcping的功能会起netstat 监控7913，在某种未知条件下，跑一段时间之后，会导致high CPU.
> 
> 关闭自动ping后，发现还是会起netstat，不知道在干嘛，每秒钟一下导致高cpu，杀掉passwall后 cpu下去了

我发现是luci里app.sh这个脚本在不断每秒地调用netstat探测端口是否可用，这是干嘛呀？这样非常耗CPU资源

**Comment by jrnick7** [comment]
我也遇到这个问题，passwall运行一段时间后CPU占用很高，需要重启OP才能恢复

**Comment by handsomeji** [comment]
日志呢？

**Comment by jrnick7** [comment]
看了下日志没有明显报错，只有自动更新订阅和节点切换的记录，但是下面两张图是我实测的，第一张是OP重启前，第二张是OP重启后
<img width="662" alt="5b3ebd4c843f9d2fc5072eb8e3b108f" src="https://user-images.githubusercontent.com/52634460/165880077-322b4b24-c6b9-4bd8-bb95-e4a857633f1b.png">
<img width="648" alt="3047305fcb8a57abaab916390e3bbe3" src="https://user-images.githubusercontent.com/52634460/165880105-e9b57a99-21e8-4a35-969f-5f7bfaf4780c.png">
也不确定是OP固件的问题，还是passwall的问题，但是的确这个问题在我这经常复现。
环境为J4125 esxi虚拟机 2G内存，OP固件版本是DHDAXCW @ FusionWrt R22.4.1 (2022-04-22) / LuCI Master (git-22.108.56096-01fdd86)

**Comment by rabbitrogi** [comment]
你最好看一下你的CPU占用高的时候，你的网络连接数是多少，我曾经也有过这种情况，就是我的软路由被人利用，做了公用proxy，那时候会有上万的网络连接。
发生这种情况，通常是wan口主动联入的流量没有被iptables屏蔽，不排除你的软路由上某个插件行为不正常。
我现在用passwall，通常都是用纯openwrt，只编译一个passwall进来，其它什么都不要，已经很久没有发生过CPU占用过高的情况了。

**Comment by jrnick7** [comment]
似乎找到了原因，是由于开启自动切换的频繁检测（我设置的1分钟一次）及切换会触发高占用的BUG，目前关掉自动切换两天了还未复现高CPU占用

**Comment by GreatMichaelLee** [comment]
> 似乎找到了原因，是由于开启自动切换的频繁检测（我设置的1分钟一次）及切换会触发高占用的BUG，目前关掉自动切换两天了还未复现高CPU占用

是的，这个里面好像老在跑netstat,

**Comment by WYC-2020** [comment]
> 似乎找到了原因，是由于开启自动切换的频繁检测（我设置的1分钟一次）及切换会触发高占用的BUG，目前关掉自动切换两天了还未复现高CPU占用

我开了这个功能，没有这个情况呢，只是我用的是一个老的版本4.50.3
