### ISSUE TITLE
在规则列表中（直连列表 代理列表 屏蔽列表 局域网IP列表 路由Hosts文件）加入内容，会过滤#格式的注释吗？

### ISSUE THREAD

**Issue by tqangxl** [xiaorouji/openwrt-package#1932]
## 描述bug(必填)

在规则列表中（直连列表 代理列表 屏蔽列表 局域网IP列表 路由Hosts文件）加入内容，会过滤#格式的注释吗？
加入后发现编译没有加载进去 

## 复现步骤(必填)

# https://support.google.com/a/answer/10026322?hl=zh-Hans
# https://www.gstatic.com/ipranges/goog.json
# https://www.gstatic.com/ipranges/cloud.json
加入”“代理列表“” IP地址列表内容为如下格式：

#serviceGoogleCloud
34.80.0.0/15
#asia-east1
34.137.0.0/16
#asia-east1
35.185.128.0/19
#"scope": "us-west2"
2600:1900:4120::/44
#"scope": "us-west2"

## 你想要实现的目的(必填)

希望旁路路由器，能通过ss和ChinaDNS-NG科学上网

代理列表的：
   域名黑白名单允许同时启用  &&  IP黑白名单允许同时启用

希望能自动过滤以#开头的 内容（如#"scope": "us-west2"）后，如果启用chinadns-ng 自动加入到ipset

**Comment by handsomeji** [comment]
现在就是自动过滤#开头和空行的
