### ISSUE TITLE
Passwall 4.54 运行不了

### ISSUE THREAD

**Issue by WXR2727** [xiaorouji/openwrt-package#1940]
## 描述bug(必填)
passwall 运行失败

## 复现步骤(必填)
1.通常编译我都是在passwall那边勾选xray core跟pdsnd 这两项

2.然后我之前以为是天灵的源码问题 ， 我试了 lean lede和官方op也是一样问题 运行失败

## 你想要实现的目的(必填)
希望大佬赶紧修复

## 日志信息(必填！)
2022-05-03 16:27:34:   删除相关防火墙规则完成。
2022-05-03 16:27:37：清空并关闭相关程序和缓存完成。
2022-05-03 16:27:37：系统未安装iptables或ipset，无法透明代理！
2022-05-03 16:27:37：运行完成！

## 系统相关信息(必填)
Passwall 4.54 
Google Chorme Version 101.0.4951.41 (Official Build) (x86_64) 

## 其他相关信息
如果可以希望大佬添加以前的dns no filter

**Comment by WXR2727** [comment]
![Screenshot 2022-05-03 at 4 28 01 PM](https://user-images.githubusercontent.com/96520876/166427093-d4f25a78-848e-4fb7-a440-55facd51b980.png)
![Screenshot 2022-05-03 at 4 28 06 PM](https://user-images.githubusercontent.com/96520876/166427101-dac29df0-9bb7-4388-ab22-fb3383d215d5.png)
![Screenshot 2022-05-03 at 4 28 12 PM](https://user-images.githubusercontent.com/96520876/166427104-2a6cf9ad-0d17-4fc0-adc8-ba1ca2f81387.png)
![Screenshot 2022-05-03 at 4 28 19 PM](https://user-images.githubusercontent.com/96520876/166427107-28724153-adc3-4a23-a88e-121f1e757e19.png)

**Comment by WXR2727** [comment]
[openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz](https://github.com/xiaorouji/openwrt-passwall/files/8609374/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz)
这是今天编译的固件

**Comment by jh0072110** [comment]
盲猜你需要在编译的时候选上：
Transparent_Proxy
iptables-mod-conntrack-extra

**Comment by WXR2727** [comment]
> 盲猜你需要在编译的时候选上：
> Transparent_Proxy
> iptables-mod-conntrack-extra

好的 我今晚再尝试一下 ， 编译界面需要去哪里找这两项插件。 因为之前一直以来都是默认

**Comment by WXR2727** [comment]
感谢大佬 问题已解决 原来在编译界面没有勾选Transparent_Prox
![Screenshot 2022-05-03 at 10 32 04 PM](https://user-images.githubusercontent.com/96520876/166473620-40dfbbd3-67d7-43db-b747-da8aa8598261.png)
y

**Comment by WXR2727** [comment]
感谢大佬 问题已解决 原来编译时没有勾选Transparent_Proxy会导致passwall启动失败![Screenshot 2022-05-03 at 10 33 25 PM](https://user-images.githubusercontent.com/96520876/166473880-d2c2907e-c4bc-4272-9b73-743146495531.png)败

**Comment by WXR2727** [comment]
真难受 折腾了那么久 终于解决了

**Comment by 3qp** [comment]
> 盲猜你需要在编译的时候选上： Transparent_Proxy iptables-mod-conntrack-extra

我也跟题主一样的提示，官方的源，编译的时候也选了Transparent Proxy和iptables-mod-conntrack-extra，还是这样的提示。

**Comment by ZhelinCheng** [comment]
> 盲猜你需要在编译的时候选上： Transparent_Proxy iptables-mod-conntrack-extra

大佬我一样，但我是使用的OpenWrt官方x86镜像，然后在软件里安装passwall，没有编译 @jh0072110
