### ISSUE TITLE
劳烦修复下访问控制里面Proxy Mode的中文翻译，谢谢

### ISSUE THREAD

**Issue by shenyz** [xiaorouji/openwrt-package#1941]

**Comment by Beginner-Go** [comment]
汉化文件内有这个翻译
![image](https://user-images.githubusercontent.com/70857188/166632099-829cbdee-ee71-44a5-9922-b57a24d7dd15.png)

**Comment by shenyz** [comment]
> 汉化文件内有这个翻译 ![image](https://user-images.githubusercontent.com/70857188/166632099-829cbdee-ee71-44a5-9922-b57a24d7dd15.png)

![image](https://user-images.githubusercontent.com/2944410/166653895-16a1c1db-2c16-41e2-999e-d097218e5b7b.png)

**Comment by shenyz** [comment]
src-git     add-translate 后编译依然是没有正确翻译
![582478BE39FD7CB31E0D057352D329D0](https://user-images.githubusercontent.com/2944410/166899709-e61d1dd9-d207-4682-8de4-70bbf0e855ea.png)

**Comment by handsomeji** [comment]
Fix.
