### ISSUE TITLE
The same issue like PSW2

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#1942]
描述bug(必填)
https://github.com/xiaorouji/openwrt-passwall2/issues/57
与这个问题相同，看来大佬只修了2没修1（也许？

复现步骤(必填)
![image](https://user-images.githubusercontent.com/50496854/166670047-9160b783-7b56-49a0-bec2-91cb049fc7e7.png)
以如图这种设置来设置自定义DOH时海外部分就会无法连接（预设没问题（我随便打的DOH地址为了截图方便

你想要实现的目的(必填)
大佬有空修好就行=。=

日志信息(必填！)
Xray 1.5.5 (Xray, Penetrates Everything.) OpenWrt (go1.17.9 linux/amd64)
A unified platform for anti-censorship.
2022/05/04 11:09:41 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP_HTTP_2cd02e7462c34feaafda6f576b8ed18f_SOCKS_2cd02e7462c34feaafda6f576b8ed18f_DNS.json
2022/05/04 11:09:42 10.10.10.130:61723 accepted tcp:140.82.114.26:443 [tcp_redir -> fa5c4b5de6c4464db55b5e9f7a1f8d0b]
2022/05/04 11:09:42 10.10.10.123:48433 accepted tcp:54.200.143.172:443 [tcp_redir -> fa5c4b5de6c4464db55b5e9f7a1f8d0b]
2022/05/04 11:09:43 10.10.10.130:61725 accepted tcp:23.32.20.75:443 [tcp_redir -> fa5c4b5de6c4464db55b5e9f7a1f8d0b]

截图
如上

系统相关信息(必填)
https://github.com/xiaorouji/openwrt-passwall/commit/c4fd72badbc5b06faa32927d9bbcb2ba9d3aa2d2
基于此编译

其他相关信息
无

**Comment by xiaorouji** [comment]
测试没有问题的

**Comment by jh0072110** [comment]
> 测试没有问题的

咦、那我这是什么情况…

**Comment by handsomeji** [comment]
Fix.

**Comment by jh0072110** [comment]
> Fix.

在psw2下可以直接设置[DOH地址]作为DNS服务器，psw1下依旧还是得保持[DOH地址,8.8.8.8(example)]这样的配置是么大佬？
