### ISSUE TITLE
PASSWALL  HYsteria协议负载均衡不通,其他协议正常

### ISSUE THREAD

**Issue by yangcao111** [xiaorouji/openwrt-package#1957]
## 描述bug(必填)

如题
## 复现步骤(必填)
passwall中添加2个hysteria协议的2个节点,分别测试连接正常;
启动负载均衡,添加上面2个节点;(2个节点配置相同)
新增1个负载均衡节点,端口号与上面设置一致.
启动此节点后如下报错
## 你想要实现的目的(必填)

不知道是否bug
## 日志信息(必填！)

;35m2022-05-12 22:36:38 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080: No such file or directory
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.99.199#56096
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] target socket address: 142.250.66.68#443
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;35m2022-05-12 22:36:40 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080: No such file or directory
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.99.199#56097
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] target socket address: 142.250.66.68#443
[1;32m2022-05-12 22:36:40 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;35m2022-05-12 22:36:40 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080: No such file or directory
## 系统相关信息(必填)

openwrt-passwall <html>
<body>

4.54-2
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by yangcao111** [comment]
用其他方法曲线实现了....

**Comment by teddy780102** [comment]
楼上是怎么解决的？

**Comment by handsomeji** [comment]
这不是很正常吗？Haproxy不支持UDP

**Comment by yangcao111** [comment]
谢谢，找到原因心里就舒坦了

**Comment by Ding-Kyoma** [comment]
我试过hysteria-faketcp，也不行。照理来说HAProxy应该可以转发TCP的内容啊
虽然可以将hysteria转成socks5节点，但是HAProxy不能正常的判断节点是否正常断联（本地的socks5节点永远是0ms），这个自动判断断联的功能对于我来说还是很重要的。

**Comment by eijs** [comment]
> 用其他方法曲线实现了....

你怎么实现的?
