### ISSUE TITLE
过滤模式选择通过UDP请求dns，dns会停止工作。

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#1968]
## 描述bug(必填)

过滤模式选择通过UDP请求dns，dns会停止工作。TCP模式正常 .

**Comment by WYC-2020** [comment]
udp 是直接用的dnsmasq,不会启动额外的dns服务器的，所以这里检测是没有运行的，你可以用pdnsd中转udp的dns查询，但是没必要，可以自己修改加入这个
