### ISSUE TITLE
运行一段时间后变成全局模式

### ISSUE THREAD

**Issue by BOBINIUNIU** [xiaorouji/openwrt-package#1973]
## 描述bug(必填)

早上访问微博很慢，用IP111测试发现路由变成了全局模式，期间没有对路由器进行过任何设置修改。手动更新规则然后重启PW后恢复正常。
设置了晚上4点自动更新规则，怀疑是规则文件更新失败导致PW无法读取IP库，但是日志显示是更新成功了。

版本：adjust 和 dns2tcp 分支的最新代码
设置：xray, TCP 代理模式默认代理模式/路由器本机 TCP 代理模式: 中国列表以外
DNS: dns2tcp & dnsmasq 没有套娃

## 日志信息(必填！)
日志正常

**Comment by nitsort** [comment]
我也遇到过几次，chnroute更新URL用的默认的，规则更新成功后 chnroute 只有5000多条，正常应该是8000多条。

**Comment by BGzEroll** [comment]
我最近也是设置到凌晨4点也这样，更新后chnroute只有1000多条，白天时间更新或者手动更新又没事，隔壁ssrp在凌晨4点自动更新也直接失败，估计不是更新脚本的问题了，但想来想去还是觉得玄学
ps：ispip.clang.cn已加入强制代理列表

**Comment by Qingzhong125** [comment]
我8月份也遇到了，在DNS上各种折腾，今天刚解决才发现就是bug。

我的解决方法是：设置为其他模式（如GFW），重启后再调回来。
