### ISSUE TITLE
hysteria 1.0.4 hash值错误

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-package#1975]
## 描述bug(必填)
RT
应为d2cb7a3f1b9ae3ac258928fb0d74e19e2066ad164492116c934b4585e0a4a94d

**Comment by Beginner-Go** [comment]
no problem

**Comment by Portan** [comment]
@原来的才是对的吧，@Beinner-Go更新成这个后我这编译反而出错了。
