### ISSUE TITLE
启用的中国列表以外模式，但是国内地址也走了代理

### ISSUE THREAD

**Issue by asiaon123** [xiaorouji/openwrt-package#1980]
## 描述bug(必填)
我选择的模式是中国列表以外模式:

但是在访问国内地址的时候，还是走的代理

## 复现步骤(必填)
我选择的模式是中国列表以外模式:

![image](https://user-images.githubusercontent.com/5396968/169674916-5d684bfa-3a63-45a1-afd5-72f1eb661252.png)
![image](https://user-images.githubusercontent.com/5396968/169674918-1ec0f908-d7e1-470d-9700-32884ecd32f2.png)
![image](https://user-images.githubusercontent.com/5396968/169674985-ecb24a75-fd73-4282-9c9d-b8d3ef0cfacb.png)
![image](https://user-images.githubusercontent.com/5396968/169674940-2f3ecd2e-e078-45ed-ba5e-66dbf4922337.png)

但是我在访问国内域名的时候走的还是代理

例如我访问的头条APP，访问到了 `mssdk3-normal-lf.zijieapi.com` 这个域名，在 `GeoData` 里也是存在的

![image](https://user-images.githubusercontent.com/5396968/169674954-005a5ca7-0cb5-44f0-99d0-58c29525bbf2.png)

可是日志里显示的确实走代理：

![image](https://user-images.githubusercontent.com/5396968/169674912-544de783-e0cf-442b-89f1-8d00ef748d28.png)

## 你想要实现的目的(必填)
不知道什么原因，麻烦大佬确认一下，是我的配置问题还是bug

## 日志信息(必填！)
```
2022/05/22 01:42:20 [Info] [252079380] app/dispatcher: sniffed domain: mssdk3-normal-lf.zijieapi.com
2022/05/22 01:42:20 [Info] [252079380] app/dispatcher: default route for tcp:mssdk3-normal-lf.zijieapi.com:443
2022/05/22 01:42:20 [Info] [252079380] transport/internet/tcp: dialing TCP to tcp:x-jp.redoc.top:443
2022/05/22 01:42:20 [Info] [252079380] proxy/vless/outbound: tunneling request to tcp:mssdk3-normal-lf.zijieapi.com:443 via xxx:443
2022/05/22 01:42:20 [Info] [560960098] proxy/dokodemo: received request for 192.168.121.237:58272
2022/05/22 01:42:20 [Info] [187754728] proxy/dokodemo: received request for 192.168.121.237:58274
2022/05/22 01:42:20 [Info] [4113029973] proxy/dokodemo: received request for 192.168.121.237:44088
2022/05/22 01:42:20 192.168.121.237:44088 accepted tcp:156.251.65.9:443 [tcp_redir >> d65d89f4ff814baa8a116038ce57e2bd]
2022/05/22 01:42:20 192.168.121.237:49764 accepted tcp:128.1.157.226:443 [tcp_redir >> d65d89f4ff814baa8a116038ce57e2bd]
```

## 系统相关信息(必填)
设备: HC5962
passwall: 4.5.4
xray: 1.5.5-1

**Comment by handsomeji** [comment]
使用旧版反馈问题只能关闭

**Comment by asiaon123** [comment]
> 使用旧版反馈问题只能关闭

什么意思？ passwall已经不维护了？使用passwall2了吗？

**Comment by core2duoe6420** [comment]
@asiaon123 你这个问题解决了么，我也遇到了类似的问题

**Comment by microdockman** [comment]
> > 使用旧版反馈问题只能关闭
> 
> 什么意思？ passwall已经不维护了？使用passwall2了吗？

https://github.com/xiaorouji/openwrt-passwall/tree/luci 这个正常。
passwall2我这国内网站也会走代理
