### ISSUE TITLE
关于全局模式下劫持ICMP ping翻墙节点的时间问题

### ISSUE THREAD

**Issue by ximiTech** [xiaorouji/openwrt-package#1982]
## 描述bug(必填)

设置passwall为tcp&udp全局代理模式，使能劫持ICMP。然后在pc端ping翻墙节点的ip。得到的时间不是<1ms，而是一般的ping的时间。

## 复现步骤(必填)

设置passwall为tcp&udp全局代理模式，使能劫持ICMP。然后在pc端ping翻墙节点的ip。得到的时间不是<1ms，而是一般的ping的时间。顺序上没发现什么规律。

## 你想要实现的目的(必填)

期望此时的ping值<1ms。

## 日志信息(必填！)

ping值为正常ping节点的时间。

## 截图

ping值为正常ping节点的时间。

## 系统相关信息(必填)

4.54-3

chrome最新版

## 其他相关信息

无。

**Comment by handsomeji** [comment]
节点没有必要加入blacklist
