### ISSUE TITLE
使用TPROXY时TCP不转发端口功能不生效

### ISSUE THREAD

**Issue by missyea** [xiaorouji/openwrt-package#1986]
## 描述bug(必填)
使用TPROXY时TCP不转发端口功能不生效

## 复现步骤(必填)
TCP代理方式：TPROXY
TCP转发端口：所有
TCP不转发端口：12580

## 你想要实现的目的(必填)
想要在TPROXY下不转发的端口走不走代理，如下REDIRECT方式下的tcping
![微信截图_20220524195634](https://user-images.githubusercontent.com/25414434/170029174-937fd572-5789-4b7d-86e5-b435b6dd6a5b.png)

## 日志信息(必填！)
![微信截图_20220524200254](https://user-images.githubusercontent.com/25414434/170030144-74d5a142-4296-491f-9b43-180b003a86d6.png)
![微信截图_20220524200023](https://user-images.githubusercontent.com/25414434/170029665-54c904fc-3bda-4251-911b-81a0f828f881.png)

## 截图
![微信截图_20220524195442](https://user-images.githubusercontent.com/25414434/170028935-c1eeb235-f2bd-4239-8dd6-7499b39dbd0d.png)

## 系统相关信息(必填)
设备: QEMU Standard PC (i440FX + PIIX - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz : 2 Core 4 Thread
passwall: 4.51.2

## 其他相关信息
无

**Comment by missyea** [comment]
目前使用 TCP转发端口: 1:12579,12581:65535 TCP不转发端口: 不转发 解决这个问题

**Comment by handsomeji** [comment]
请不要使用旧版本反馈问题
