### ISSUE TITLE
订阅节点部分是否可以添加“是否跳过验证 allowInsecure option ”的总开关（TCP快速打开选项也可以做个总开关）

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#1993]
## 你的功能请求是否与问题有关？ 请描述。(必填)
当订阅节点时，当涉及TLS域名证书时，默认是勾选跳过证书验证。也有相关用户在issue提出 #1991 #1992 
## 描述你想要的解决方案 (必填)
是否在passwall一代及二代在“节点订阅”标签页中做一个“是否跳过验证 allowInsecure option ”的总开关（TCP快速打开选项也可以做个总开关）
## 描述你考虑过的替代方案
目前随代码保持默认，但是顾虑未来可能有变化，默认验证可提高安全性，有个总开关亦可维持兼容性

## 附加上下文
![image](https://user-images.githubusercontent.com/31793080/170643513-29dbb9ac-32ac-4aea-a9da-e153fade69ab.png)

**Comment by symonlee** [comment]
添加订阅时 进行设置 手动勾选掉了这个允许不安去链接 选项 但是订阅后 节点还是默认勾选了 这个选项

**Comment by tianiue** [comment]
有人遇到这个问题没有

**Comment by SakuraFallingMad** [comment]
> 有人遇到这个问题没有 [320103.089774] blk_update_request: operation not supported error, dev loop0, sector 488368 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [320164.444457] print_req_error: 10 callbacks suppressed [320164.444461] blk_update_request: operation not supported error, dev loop0, sector 489672 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [321809.714808] blk_update_request: operation not supported error, dev loop0, sector 489624 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [321809.717981] blk_update_request: operation not supported error, dev loop0, sector 489680 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [323341.833615] blk_update_request: operation not supported error, dev loop0, sector 489688 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324078.067200] blk_update_request: operation not supported error, dev loop0, sector 288176 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324083.701139] blk_update_request: operation not supported error, dev loop0, sector 47736 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324083.704338] blk_update_request: operation not supported error, dev loop0, sector 288264 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324083.707745] blk_update_request: operation not supported error, dev loop0, sector 489512 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324083.711237] blk_update_request: operation not supported error, dev loop0, sector 489720 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [324386.797556] blk_update_request: operation not supported error, dev loop0, sector 489704 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [325268.182310] blk_update_request: operation not supported error, dev loop0, sector 489736 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [326352.314273] blk_update_request: operation not supported error, dev loop0, sector 41168 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [326352.317455] blk_update_request: operation not supported error, dev loop0, sector 489752 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [327201.187717] blk_update_request: operation not supported error, dev loop0, sector 489768 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [327201.191076] blk_update_request: operation not supported error, dev loop0, sector 489784 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [327265.953824] blk_update_request: operation not supported error, dev loop0, sector 489800 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [328172.426552] blk_update_request: operation not supported error, dev loop0, sector 489792 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [328172.429809] blk_update_request: operation not supported error, dev loop0, sector 489808 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [330002.779042] blk_update_request: operation not supported error, dev loop0, sector 489816 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [330066.774221] blk_update_request: operation not supported error, dev loop0, sector 489840 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [331233.591154] blk_update_request: operation not supported error, dev loop0, sector 288272 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0 [331293.494236] blk_update_request: operation not supported error, dev loop0, sector 47768 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 0

问隔壁，别在这里叠楼

**Comment by SakuraFallingMad** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/3df9e733c602023c890edd041d7547bc2d846e6c 修复Trojan订阅方面的
