### ISSUE TITLE
naiveproxy-102.0.5005.61-1 编译失败

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-package#2000]
## 描述bug(必填)
commit 9eaec933233881f30ffbdc72f6c92af775a86eb3
编译naiveproxy失败
## 复现步骤(必填)
update [openwrt-passwall](https://github.com/xiaorouji/openwrt-passwall) 代码至9eaec933233881f30ffbdc72f6c92af775a86eb3
make -j 1V=s

## 你想要实现的目的(必填)
修复编译错误 

## 日志信息(必填！)
[3209/3209] LINK ./naive
touch /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.built
rm -rf /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy.installed /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy
mkdir -p /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy
install -d -m0755 /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy/usr/bin
install -m0755 /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/src/out/Release/naive /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy/usr/bin/naive
install -d -m0755 /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy/etc/config /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy/etc/init.d
install -m0600 /LEDE/openwrt-master/feeds/naiveproxy/naiveproxy/files/naiveproxy.config /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy/etc/config/naiveproxy
install: cannot stat '/LEDE/openwrt-master/feeds/naiveproxy/naiveproxy/files/naiveproxy.config': No such file or directory
make[3]: *** [Makefile:173: /LEDE/openwrt-master/build_dir/target-x86_64_musl/naiveproxy-102.0.5005.61-1/.pkgdir/naiveproxy.installed] Error 1
make[3]: Leaving directory '/LEDE/openwrt-master/feeds/naiveproxy/naiveproxy'
time: package/feeds/naiveproxy/naiveproxy/compile#1848.24#135.72#2089.13
    ERROR: package/feeds/naiveproxy/naiveproxy failed to build.
make[2]: *** [package/Makefile:116: package/feeds/naiveproxy/naiveproxy/compile] Error 1
make[2]: Leaving directory '/LEDE/openwrt-master'
make[1]: *** [package/Makefile:110: /LEDE/openwrt-master/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/LEDE/openwrt-master'
make: *** [/LEDE/openwrt-master/include/toplevel.mk:230: world] Error 2

## 截图
日志如上

## 系统相关信息(必填)
openwrt官方 master tree

**Comment by Beginner-Go** [comment]
再试试？

**Comment by openips** [comment]
@Beginner-Go 已经更新完毕 可以编译成功 谢谢
