### ISSUE TITLE
国外网址进行dns解析时，时不时会向国内dns和海外dns一起解析

### ISSUE THREAD

**Issue by laoleic4** [xiaorouji/openwrt-package#2004]
## 描述bug(必填)
如标题所示，但国内dns和海外dns都自定义为内网dns服务器，但从dns日志可以看到海外网址有经过国内dns服务器解析出IPv6，另一个dns也有走，但那个dns服务器是有屏蔽IPv6

## 复现步骤(必填)
访问期间网址给出的解析是有走IPv6，无法完整复现过程（127.0.0.1是解析国内网站用的dns，192.168.5.5是解析海外网址用的dns）
![image](https://user-images.githubusercontent.com/56494512/171324031-ff798829-e4ed-4314-87ff-2d1de2dca56e.png)
![image](https://user-images.githubusercontent.com/56494512/171324097-91bce054-3cdc-47e9-ba36-86863c7934c8.png)

## 你想要实现的目的(必填)
请尽快修复下此功能，加分流只能解决一时的问题

## 日志信息(必填！)
已经过多次重启无法提供

## 截图
如上图所示

## 系统相关信息(必填)
PassWall版本:4.45-1
XRay版本:1.5.2
浏览器版本:Chrome 102.0.5005.61（正式版本） （64 位）

**Comment by handsomeji** [comment]
不要使用旧版本反馈问题
