### ISSUE TITLE
passwall更新订阅后，HAProxy负载均衡再也打不开，重启无效

### ISSUE THREAD

**Issue by PM100Fun** [xiaorouji/openwrt-package#2009]
## 描述bug(必填)

passwall,手工更新订阅后，HAProxy负载均衡线路超时，再看看负载均衡页面，进入界面按键消失，虽然可以开关，但运行状态里面，负载均衡都显示未运行。而且重启无效，最后重装了op
（线路没问题）

## 复现步骤(必填)

1、已配置订阅，打开负责均衡。手工更新订阅
2、负载均衡页面，进入界面按键消失，虽然可以开关，但运行状态里面，负载均衡都显示未运行

## 你想要实现的目的(必填)

更新订阅，或者改变线路设置，不影响负载均衡功能。

## 日志信息(必填！)

已清空

## 系统相关信息(必填)

passwall版本 4.54-3
Chrome 101.0.4951.64

**Comment by hcym** [comment]
我一直都在用22.03里面的，版本号是22.14吧，不然大雕的肯定不能启动luci haproxy，你不妨替换了

**Comment by PM100Fun** [comment]
我发现订阅更新后，有一定概率把负载均衡页面的节点地址，替换成节点列表里面，新建的HAProxy负载均衡，因此打开负载均衡开关也不能启动，后来我把节点地址改回原来的，就可以启动了。

**Comment by showme2005** [comment]
同样也遇到了..我是直接 重置配置...但...过几天负载均衡也会变成"未启动"

**Comment by Amanoshoyichi** [comment]
同样遇到了这个问题，目前有解决吗？

**Comment by josbu** [comment]
同样问题 最新immortalwrt  passwall 最新 显示 运行 打不开
