### ISSUE TITLE
dns分流选择smartdns后，chinadns-ng不显示了，如何开启？

### ISSUE THREAD

**Issue by xiaoyaozhilv** [xiaorouji/openwrt-package#2018]
## 你的功能请求是否与问题有关？ 请描述。(必填)
我选择了smartdns分流，下面有提示怎么配置，我点开教程，https://github.com/luckyyyyy/blog/issues/57，这里面说的是passwall要勾选chinadns-ng，但这个chinadns-ng在选择dnsmasq时候是可以勾选的，选择smartdns就没有了。。。

## 描述你想要的解决方案 (必填)
求大佬给出解答

**Comment by Pacio** [comment]
确实有此问题，勾选smartdns以后就无法勾选chinadns，希望速度修复

**Comment by handsomeji** [comment]
本来就没有这个逻辑
