### ISSUE TITLE
udp連線失敗

### ISSUE THREAD

**Issue by rootmelo92118** [xiaorouji/openwrt-package#2029]
![图片1](https://user-images.githubusercontent.com/32770959/175801037-1bbe90e0-bb45-404c-a21a-51cdbea090a3.png)
已確定卸載docker 該部分問題目前會導致discord無法進入語音 遊戲<原神>無法進入遊戲

**Comment by 0xffffharry** [comment]
kmod-br-netfilter 主要是这个内核模块，卸载了就没事
