### ISSUE TITLE
4.5以上的版本，任何支持的链接中含有127.0.0.1这个IP，链接导入就无效，导入后不显示，换个别的IP就正常了，请检测！！

### ISSUE THREAD

**Issue by oyanli** [xiaorouji/openwrt-package#2031]
## 描述bug(必填)

4.5以上的版本，任何支持的链接中含有127.0.0.1这个IP，链接导入就无效，导入后不显示，换个别的IP就正常了，请检测！！

## 复现步骤(必填)

以下此类链接导入都无效，不显示，换个别的IP就正常了！！！

ss://aes-256-gcm:12345678$@127.0.0.1:1180#负载均衡

vless://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx@127.0.0.1:1190?encryption=none&security=xtls&type=tcp&host=123.xxx&headerType=none&sni=123.xxx&flow=xtls-rprx-splice#负载均衡

vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIui0n+i9veWdh+ihoSIsDQogICJhZGQiOiAiMTI3LjAuMC4xIiwNCiAgInBvcnQiOiAiMTE3MCIsDQogICJpZCI6ICJ4eHh4eHh4eC14eHh4LXh4eHgteHh4eC14eHh4eHh4eHh4IiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0=

## 你想要实现的目的(必填)

希望能够修复这个BUG，谢谢！！

## 系统相关信息(必填)
 passwall版本：
4.51-7，4.54-1，4.54-3

以上版本测试都不行

**Comment by WYC-2020** [comment]
这个是作者限制了而已，作者认为添加的连接是127.0.0.1是无效的 ，你自己去掉即可
![image](https://user-images.githubusercontent.com/34025388/177701822-c45f409e-f2ea-450b-b12c-5a4b94d25d2b.png)
基本的维修方式而已
