### ISSUE TITLE
官方的固件用不了

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#2041]

**Comment by snakwu** [comment]
是官方源码改变了libcurl的默认设置引起不支持https引起的，在编译菜单里找到libcurl配置，设置为openssl就可以了

**Comment by xh0823** [comment]
> 是官方开源改变了libcurl的默认设置引发不支持https引发的，在编译菜单里找到libcurl配置，设置为openssl就可以了

非常感谢，可以了
