### ISSUE TITLE
节点订阅里勾选 允许不安全连接，没有作用！

### ISSUE THREAD

**Issue by y9858** [xiaorouji/openwrt-package#2043]
## 描述bug(必填)
节点订阅里勾选 允许不安全连接，没有作用！不管有没有勾选，订阅的节点AllowInsecure都=0。

## 截图
![1](https://user-images.githubusercontent.com/53130835/179920449-21d374ae-f111-4545-8331-8504334d4e91.png)
![2](https://user-images.githubusercontent.com/53130835/179920473-02bc5778-0f04-48fe-8dd6-f39c97c4038f.png)
![3](https://user-images.githubusercontent.com/53130835/179920489-27acfe1b-f8a7-4cc7-9708-7e550c8cc724.png)
![4](https://user-images.githubusercontent.com/53130835/179920507-1aac314c-e930-4234-bd8d-13e9986713ca.png)

## 系统相关信息(必填)
passwall版本
![5](https://user-images.githubusercontent.com/53130835/179920796-bed39a6b-b2ec-439d-90c4-59190c280235.png)

## 其他相关信息
节点是Trojan节点，使用Xray代理。

**Comment by WYC-2020** [comment]
确定是最新的？我订阅都没你说的这个
![image](https://user-images.githubusercontent.com/34025388/179923516-22140a1a-b7b0-4d83-9986-d29b7c6c189f.png)
直接就是
![image](https://user-images.githubusercontent.com/34025388/179923596-88772943-5d4a-4606-affa-b4f7b374297c.png)

**Comment by y9858** [comment]
> 确定是最新的？我订阅都没你说的这个 ![image](https://user-images.githubusercontent.com/34025388/179923516-22140a1a-b7b0-4d83-9986-d29b7c6c189f.png) 直接就是 ![image](https://user-images.githubusercontent.com/34025388/179923596-88772943-5d4a-4606-affa-b4f7b374297c.png)

你节点不是vless vmess trojan吧？

**Comment by ShanStone** [comment]
检查节点链接是不是指定了AllowInsecure为0，节点指定时使用节点的设定
