### ISSUE TITLE
请问不转发端口和转发屏蔽端口有什么区别？

### ISSUE THREAD

**Issue by Yesinger** [xiaorouji/openwrt-package#2057]
我的需求是除bt外都走代理，bt监听端口该填在不转发端口还是转发屏蔽端口呢？

![Screenshot_2022-07-30-10-47-18](https://user-images.githubusercontent.com/65629812/181919612-01903957-9934-494b-8585-63be36e1eb11.jpg)

**Comment by EarSum** [comment]
TCP 转发端口选为常用，bt一般使用的都是非常用端口
