### ISSUE TITLE
Bug OpenWrt21.02.3-SDK无法编译最新版的v2ray-core: 5.1.0

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#2091]
## 描述bug(必填)
OpenWrt21.02.3-SDK无法编译最新版的v2ray-core: 5.1.0,好像是因为Go需要1.19吗！而目前的那个讨论里面的教程是因为Go还是1.17.12的原因吗！

## 日志信息(必填！)

```
Building targets
github.com/v2fly/v2ray-core/v5/common/protocol/quic
# github.com/v2fly/v2ray-core/v5/common/protocol/quic
../../common/protocol/quic/sniff.go:39:18: undefined: CipherSuiteTLS13
../../common/protocol/quic/sniff.go:155:12: undefined: AEADAESGCMTLS13
note: module requires Go 1.19

make[2]: *** [Makefile:112: /xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-aarch64_generic_musl/v2ray-core-5.1.0/.built] Error 2
make[2]: Leaving directory '/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/feeds/PWpackages/v2ray-core'
time: package/feeds/PWpackages/v2ray-core/compile#2.09#9.73#10.51
    ERROR: package/feeds/PWpackages/v2ray-core failed to build.
make[1]: *** [package/Makefile:116: package/feeds/PWpackages/v2ray-core/compile] Error 1
make[1]: Leaving directory '/home/walt/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64'
make: *** [/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223: package/luci-app-passwall/compile] Error 2
```
尝试手动修改Go到1.19.1，但是还是出现下面报错
```
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://dl.google.com/go/go1.19.1.src.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.2M  100 25.2M    0     0  18.5M      0  0:00:01  0:00:01 --:--:-- 18.5M
tar -C "/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/hostpkg/go-1.19.1" --strip-components=1 -xzf "/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/dl/go1.19.1.src.tar.gz"
[ ! -d ./src/ ] || cp -fpR ./src/* /xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/hostpkg/go-1.19.1

Applying ./patches/001-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-available.patch using plaintext:
patching file src/cmd/link/internal/ld/lib.go
Hunk #1 FAILED at 1391.
1 out of 1 hunk FAILED -- saving rejects to file src/cmd/link/internal/ld/lib.go.rej
Patch failed!  Please fix ./patches/001-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-available.patch!
make[2]: *** [Makefile:371: /xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/build_dir/hostpkg/go-1.19.1/.preparedc9480703bc3a9d37a8d3843e976d374e_18f1e190c5d53547fed41a3eaa76e9e9] Error 1
make[2]: Leaving directory '/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#1.60#11.60#16.31
    ERROR: package/feeds/packages/golang [host] failed to build.
make[1]: *** [package/Makefile:114: package/feeds/packages/golang/host/compile] Error 1
make[1]: Leaving directory '/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64'
make: *** [/xxx/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223: package/v2ray-core/compile] Error 2
```
## 系统相关信息(必填)
4.55-1

**Comment by Gzxhwq** [comment]
上游openwrt master还是1.18.4，这个补丁不适用了
https://github.com/openwrt/packages/blob/master/lang/golang/golang/patches/001-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-available.patch

**Comment by gaoderby** [comment]
之前，手工换成go 1.19可编译通过，但这两天更新后又不行了，因为其他模块又需要go 1.18。貌似无解了！

Building targets
github.com/caddyserver/certmagic
# github.com/caddyserver/certmagic
../../../../../dl/go-mod-cache/github.com/caddyserver/certmagic@v0.17.1/certmagic.go:408:11: undefined: any
../../../../../dl/go-mod-cache/github.com/caddyserver/certmagic@v0.17.1/certmagic.go:428:13: undefined: any
../../../../../dl/go-mod-cache/github.com/caddyserver/certmagic@v0.17.1/config.go:68:66: undefined: any
../../../../../dl/go-mod-cache/github.com/caddyserver/certmagic@v0.17.1/config.go:1115:80: undefined: any
../../../../../dl/go-mod-cache/github.com/caddyserver/certmagic@v0.17.1/solvers.go:699:7: undefined: any
note: module requires Go 1.18

make[3]: *** [Makefile:56: /home/gao/ow21l/build_dir/target-x86_64_musl/hysteria-1.2.1/.built] Error 2
......

**Comment by wazzx** [comment]
目前已经成功搞定了，用22.03的源的golong，希望管理员关闭bug吧
```
pushd feeds/packages/lang

rm -rf golang && svn co https://github.com/openwrt/packages/branches/openwrt-22.03/lang/golang

popd
```

**Comment by AK201314** [comment]
> 目前已经成功搞定了，用22.03的源的golong，希望管理员关闭bug吧
> 
> ```
> pushd feeds/packages/lang
> 
> rm -rf golang && svn co https://github.com/openwrt/packages/branches/openwrt-22.03/lang/golang
> 
> popd
> ```

老哥最近编译也是一直报错，用你的方法OK了，帮看下是不是一样原因哦！
Building targets
github.com/v2fly/v2ray-core/v5/common/protocol/quic
# github.com/v2fly/v2ray-core/v5/common/protocol/quic
../../../../../dl/go-mod-cache/github.com/v2fly/v2ray-core/v5@v5.1.0/common/protocol/quic/sniff.go:39:18: undefined: CipherSuiteTLS13
../../../../../dl/go-mod-cache/github.com/v2fly/v2ray-core/v5@v5.1.0/common/protocol/quic/sniff.go:155:12: undefined: AEADAESGCMTLS13
note: module requires Go 1.19

make[3]: *** [Makefile:43: /workdir/openwrt/build_dir/target-aarch64_cortex-a53+neon_musl/v2ray-plugin-5.1.0/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/package/luci-app-ssr-plus/v2ray-plugin'
time: package/luci-app-ssr-plus/v2ray-plugin/compile#1.03#0.36#0.88
    ERROR: package/luci-app-ssr-plus/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/luci-app-ssr-plus/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53+neon_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by Zeoge** [comment]
> 

这个方法可以，不过不知道原理是啥
