### ISSUE TITLE
全局代理问题

### ISSUE THREAD

**Issue by bestmikecat** [xiaorouji/openwrt-package#2093]
## 描述bug(必填)
使用的网络有登录验证页,使用passwall全局代理,在浏览器中输入代理服务器的ip会跳转到登录验证页

## 复现步骤(必填)
如上,在规则列表的代理列表中填入代理服务器ip仍得不到解决

## 你想要实现的目的(必填)
能正常访问代理服务器ip

## 日志信息(必填！)
无

## 截图
无

## 系统相关信息(必填)
无

## 其他相关信息
无

**Comment by MasterOfStar** [comment]
要访问代理服务器需要先连上外网。
而不认证你就没法访问外网，也就没法访问代理服务器。

**Comment by bestmikecat** [comment]
> 要访问代理服务器需要先连上外网。 而不认证你就没法访问外网，也就没法访问代理服务器。

可以访问外网的,但输入代理ip就会跳转到认证界面,用ShadowSocksR Plus+的"强制走代理的广域网 IP"添加代理服务器ip后就正常了,可在passwall添加代理列表里添加ip却不行.

**Comment by MasterOfStar** [comment]
> > 要访问代理服务器需要先连上外网。 而不认证你就没法访问外网，也就没法访问代理服务器。
> 
> 可以访问外网的,但输入代理ip就会跳转到认证界面,用ShadowSocksR Plus+的"强制走代理的广域网 IP"添加代理服务器ip后就正常了,可在passwall添加代理列表里添加ip却不行.

哦哦，以为你是想绕过认证。
认证了的话估计就是bug了。

本应走代理的ip没有被代理，走了直连

**Comment by maYunLaoXi** [comment]
类似问题，https走代理，http没有走代理。
