### ISSUE TITLE
请支持使用Firewall4(nftables) 

### ISSUE THREAD

**Issue by syk6666** [xiaorouji/openwrt-package#2094]

**Comment by syk6666** [comment]
请支持使用Firewall4(nftables)

**Comment by rabbitrogi** [comment]
在最新的openwrt 22.03.0上运行passwall，由于无法设置防火墙而导致启动失败。

/usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 1226: -t: not found

**Comment by wazzx** [comment]
22.03.0目前过度阶段，需要安装`iptables-nft`
你可以通过 opkg 来安装`iptables-nft`，它可以在使用 nftables 的情况下，提供与之前的命令相同的接口。

**Comment by rabbitrogi** [comment]
> 22.03.0目前过度阶段，需要安装`iptables-nft` 你可以通过 opkg 来安装`iptables-nft`，它可以在使用 nftables 的情况下，提供与之前的命令相同的接口。

OK, 我昨天想到这个方法了，试了一下，果真可以。我还装了ip6tables-nft。多谢你的回答

**Comment by syk6666** [comment]
谢谢谢谢
________________________________
发件人: rabbitrogi ***@***.***>
发送时间: 2022年9月13日 8:07
收件人: xiaorouji/openwrt-passwall ***@***.***>
抄送: syk6666 ***@***.***>; Author ***@***.***>
主题: Re: [xiaorouji/openwrt-passwall] 请支持使用Firewall4(nftables) (Issue #2094)


22.03.0目前过度阶段，需要安装iptables-nft 你可以通过 opkg 来安装iptables-nft，它可以在使用 nftables 的情况下，提供与之前的命令相同的接口。

OK, 我昨天想到这个方法了，试了一下，果真可以。我还装了ip6tables-nft。多谢你的回答

―

**Comment by xh0823** [comment]
> 请支持使用Firewall4(nftables)

没有那个大佬愿意
