### ISSUE TITLE
最近的编译高级设置->ipv6透明代理消失了

### ISSUE THREAD

**Issue by noorall** [xiaorouji/openwrt-package#2104]
## 描述bug(必填)

在最新的passwall中，编译时选中了ipv6 nat，但是在高级设置中ipv6透明代理这一选项消失了，请问是最近移除了吗？

## 复现步骤(必填)

下载最新源码->勾选ipv6 nat->打开高级设置

## 你想要实现的目的(必填)

是否移除了IPV6代理这一功能？如果没有移除，我该怎么让他出现在我的选项中？

## 日志信息(必填！)

暂无日志

## 系统相关信息(必填)

passwall: 最新版
lede: master

**Comment by hexsen929** [comment]
一样的问题，请问楼主解决了吗，我换passwall2也是一样的

**Comment by noorall** [comment]
> 一样的问题，请问楼主解决了吗，我换passwall2也是一样的

解决了，编译的时候勾选kmod-iptables-tproxy

**Comment by noorall** [comment]
solved

**Comment by ololllolo** [comment]
> 解决了

真是奇怪的问题，我也遇到了，更新了源码和passwall以后，编译出来的固件，发现v6部分的代理就失效了。高级设置中也不见了透明代理的选项。
我按照楼主的提示，找了一下，只找到kmod-ipt-tproxy和iptables-mod-tproxy这两项，而且这两项编译我都是打开的，但是固件的问题却是一样的，楼主可以给一点更详细的说明吗？

**Comment by noorall** [comment]
@ololllolo 

啊 那我可能打错了，应该是iptables-mod-tproxy，我在安装这个模块之后就出现了

**Comment by ololllolo** [comment]
嗯，我确认了一下这个是编译在里面的，而且只要passwall里面选择了编译transparent_proxy，这个依赖就自动选择了。看来我的问题还在别的地方，只能再找找了。

**Comment by z1790** [comment]
我也遇到了，最后把lean的源码回滚到了9月10号的版本就正常了
