### ISSUE TITLE
即使不选择passwall，trojan-plus等组件也会默认编译

### ISSUE THREAD

**Issue by saldry** [xiaorouji/openwrt-package#2107]
## 描述bug(必填)

luci-app-passwall的Makefile里默认了Trojan_Plus等组件

```
define Package/$(PKG_NAME)/config
menu "Configuration"
...
config PACKAGE_$(PKG_NAME)_INCLUDE_Trojan_Plus
	bool "Include Trojan-Plus"
	default y
...
endmenu
endef
```
编译时即使没有选择luci-app-passwall，也会默认带上trojan-plus。也就是.config中：
```
# CONFIG_PACKAGE_luci-app-passwall  is not set
...
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
```

如果保持默认，即使是不需要出国功能的设备，也会编译上trojan-plus，只能在编译时主动否掉`CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus`。

`CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus`应该是passwall的附属组件，不选择passwall就不应该被默认添加。

## 复现步骤(必填)

1. 在.config中填入
```
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
```
2. make defconfig
3. 打开.config，发现
```
# CONFIG_PACKAGE_luci-app-passwall  is not set
...
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
```
4. 编译后的镜像包含了trojan-plus

## 你想要实现的目的(必填)

编译时如果不选择luci-app-passwall，`CONFIG_PACKAGE_luci-app-passwall_INCLUDE_`相关组件就不会被默认编译。

## 日志信息(必填！)

没有日志，也不需要

## 截图

没有截图，也不需要

## 系统相关信息(必填)

passwall和浏览器的版本与此无关

## 其他相关信息

- luci-app-ssr-plus和luci-app-vssr也有类似问题。

- 我使用的是ImmortalWrt的源码，自带了passwall

- 找到一个PR lisaac/luci-app-diskman#48 ，给include的包设置`depends on PACKAGE_$(PKG_NAME)`，我试了一下，应该可以解决问题，但passwall本体依赖include的包，这样二者就互为依赖了

**Comment by smallprogram** [comment]
欢迎PR

**Comment by saldry** [comment]
没有PR是因为不太懂，怕整错了

https://github.com/xiaorouji/openwrt-passwall/blob/3ce49fb7089aee23c1854c927ac39a9c692d3741/luci-app-passwall/Makefile#L1-L60

请问这里为什么要把include的这些包设置成依赖呢?

官方的[文档](https://openwrt.org/docs/guide-developer/dependencies#special_notes)，提到

> It is possible to do select and depend on packages outside the usual `DEPENDS` definition.

是不是意味着可以只把这些include的包写在`Package/$(PKG_NAME)/config`中而不写进`PKG_CONFIG_DEPENDS`和`LUCI_DEPENDS`？这样可以避免相互依赖的问题

**Comment by smallprogram** [comment]
我也不是太懂😑

**Comment by wazzx** [comment]
> 我也不是太懂😑

老哥修改回来吧！目前bug实在太麻烦了。

**Comment by WYC-2020** [comment]
我这边 测试 取消 没有你说的这个问题，看config 也没有相关定义

**Comment by WYC-2020** [comment]
选择后：
![image](https://user-images.githubusercontent.com/34025388/196318094-15187da8-0a9f-4da9-b79a-1262b10fc841.png)
取消后：
![image](https://user-images.githubusercontent.com/34025388/196318241-625d0176-9709-4e08-b2d6-05eb910e3401.png)
