### ISSUE TITLE
开启UDP代理时，使用Smartdns分流无法解析

### ISSUE THREAD

**Issue by Xymmh** [xiaorouji/openwrt-package#2111]
### 描述您遇到的bug

当Passwall和Smartdns一起使用时，只要开启UDP代理，Smartdns就无法解析Passwall_Proxy组，导致无法访问代理网站。
怀疑和日志中 - [0]将上游 DNS 服务器 101.6.6.6:53 加入到路由器自身代理的 UDP 转发链  有关。

### 复现此Bug的步骤

DNS设置中选择Smartdns分流，过滤模式选择Requery DNS by UDP，远程DNS任意设置，均可复现此Bug。

### 您想要实现的目的

在开启UDP代理的情况下，仍能正常使用Smartdns解析。

### 日志信息

暂无

### 系统相关信息

passwall版本：git-23.264.55135-f663b9b
smartdns版本：1.2022.09.25-1116

**Comment by Xymmh** [comment]
在开启UDP代理的时候，过滤模式选择Requery DNS by TCP，依然无法解析，感觉问题就出现在了将DNS加入路由转发链这个步骤上。我使用的是Openwrt 22.03，不知道和这个有没有关系。

**Comment by myrisc** [comment]
开upd代理不影响tcp，但是如果dns选udp确实不行，可以正常浏览网页，youtube也可以打开列表，就是无法播放视频，而且新版的如果选smartdns，会自动覆盖openwrt dns设置的几个选项，包括端口，转发服务器，而且如果选择smartdns，远程的服务器不能设置本地

**Comment by Xymmh** [comment]
> 开upd代理不影响tcp，但是如果dns选udp确实不行，可以正常浏览网页，youtube也可以打开列表，就是无法播放视频，而且新版的如果选smartdns，会自动覆盖openwrt dns设置的几个选项，包括端口，转发服务器，而且如果选择smartdns，远程的服务器不能设置本地

能打开是因为smartdns有缓存，视频cdn没缓存所以解析不了，于是就无法播放。

**Comment by wtfr-dot** [comment]
把smartdns第二组上游服务器所属组改为passwall_proxy

**Comment by Xymmh** [comment]
> 把smartdns第二组上游服务器所属组改为passwall_proxy

怎么改？Passwall里设置以后那个conf-file /tmp/etc/smartdns/passwall.conf文件不就自动这样设置了吗？

**Comment by wtfr-dot** [comment]
> > 把smartdns第二组上游服务器所属组改为passwall_proxy
> 
> 怎么改？Passwall里设置以后那个conf-file /tmp/etc/smartdns/passwall.conf文件不就自动这样设置了吗
luci里属于第二dns服务器组里的每一个上游服务器，都有一个所属组设置，一般都是自定义一个组名，但这里要设为pass wall_proxy，跟passwall.conf里对应

**Comment by Xymmh** [comment]
> > > 把smartdns第二组上游服务器所属组改为passwall_proxy
> > 
> > 
> > 怎么改？Passwall里设置以后那个conf-file /tmp/etc/smartdns/passwall.conf文件不就自动这样设置了吗
> > luci里属于第二dns服务器组里的每一个上游服务器，都有一个所属组设置，一般都是自定义一个组名，但这里要设为pass wall_proxy，跟passwall.conf里对应

可是passwall.conf里面已经定义了一个属于passwall_proxy组的DNS啊，和passwall的luci界面里设置的DNS同步。

**Comment by wtfr-dot** [comment]
> > > > 把smartdns第二组上游服务器所属组改为passwall_proxy
> > > 
> > > 
> > > 怎么改？Passwall里设置以后那个conf-file /tmp/etc/smartdns/passwall.conf文件不就自动这样设置了吗
> > > luci里属于第二dns服务器组里的每一个上游服务器，都有一个所属组设置，一般都是自定义一个组名，但这里要设为pass wall_proxy，跟passwall.conf里对应
> 
> 可是passwall.conf里面已经定义了一个属于passwall_proxy组的DNS啊，和passwall的luci界面里设置的DNS同步。

那个是里面定义的passwall_proxy组里面成员是空的，本来是通过调用第二dns服务器的组成员，但是现在不起作用，你看smartdns解析日志就知道了
passwall里面如果远程dns用127.0.0.1:port这种方式它判断这不是远程dns，所以自己生成了一个passwall_proxy组，黑名单里的dns都是通过这个组里的dns进行解析，所以smartdns必须要有上游服务器属于这个组才能真正使用它的dns服务器解析功能
如果passwall里远程dns指定其它的比如1.1.1.1，这时passwall.conf里的端口号变成了passwall内部的dns监听端口号，利用内置的dns进行解析，所以passwall本身就没有利用smartdns里的分组国外dns服务功能

**Comment by Xymmh** [comment]
@cncqcyc 
我的问题还是没有解决。
因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。
但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。

**Comment by wtfr-dot** [comment]
> @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。

你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了

**Comment by Xymmh** [comment]
> > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> 
> 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了

列表里的也不行。而且我自定义设置是有需求的。

**Comment by wtfr-dot** [comment]
> > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > 
> > 
> > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> 
> 列表里的也不行。而且我自定义设置是有需求的。

列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里

**Comment by Xymmh** [comment]
> > > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > > 
> > > 
> > > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> > 
> > 
> > 列表里的也不行。而且我自定义设置是有需求的。
> 
> 列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里

在使用SmartDNS分流时确实不行，使用Dnsmasq分流时可以。

**Comment by Xymmh** [comment]
> > > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > > 
> > > 
> > > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> > 
> > 
> > 列表里的也不行。而且我自定义设置是有需求的。
> 
> 列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里

在使用SmartDNS分流时确实不行，使用D

> > > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > > 
> > > 
> > > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> > 
> > 
> > 列表里的也不行。而且我自定义设置是有需求的。
> 
> 列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里

而且我使用的远程DNS不需要代理即可返回正确结果，代理反而会因为IP不在允许AS里而拒绝返回，所以Passwall这个自动加代理名单的行为完全就是多此一举。

**Comment by wtfr-dot** [comment]
> > > > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > > > 
> > > > 
> > > > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> > > 
> > > 
> > > 列表里的也不行。而且我自定义设置是有需求的。
> > 
> > 
> > 列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里
> 
> 在使用SmartDNS分流时确实不行，使用D
> 
> > > > > @cncqcyc 我的问题还是没有解决。 因为我本来就不是且不想使用smartdns的第二组服务器，我使用的就是一个公网DNS服务器，也就是你说的第二种1.1.1.1的情况。 但在这种情况下，一旦开启UDP代理，国内可以通过smartdns正确解析，但国外就会出现Server Failed的情况。但不开启UDP代理就不会这样。
> > > > 
> > > > 
> > > > 你不用smartdns的第二服务器的远程dns里就不用自定义设置，直接在列表里选就行了
> > > 
> > > 
> > > 列表里的也不行。而且我自定义设置是有需求的。
> > 
> > 
> > 列表里选预置的dns服务器肯定是行的，如果你自定义了一个其它公网dns，smartdns会把这个dns加载进服务器组里，确保这个dns在代理名单里
> 
> 而且我使用的远程DNS不需要代理即可返回正确结果，代理反而会因为IP不在允许AS里而拒绝返回，所以Passwall这个自动加代理名单的行为完全就是多此一举。

passwaal分国内分组和国外分组(远程dns)的目的是国内外分流，远程dns你自定义一个不需要代理的dns本身就不符合逻辑
