### ISSUE TITLE
请求为规则更新提供校验功能

### ISSUE THREAD

**Issue by ololllolo** [xiaorouji/openwrt-package#2113]
### 描述你想要的新功能

现在的规则更新，如果某个规则更新失败，会使用一个不完整的规则来进行分流。例如我设置为每周日5点更新规则，经过一段时间的使用，发现有好多次(大概一半的次数)总是 chnroute 更新出错了，log显示更新只有2000条左右，正常的应该有8000条。读取chnroute这个规则，发现后面的6000条都没有，以至于大部分的访问都分流到代理了（我使用的模式为"中国列表以外"）。
这个问题大概率是因为大家可能在某一个整点时间，比如5点整来更新规则，以至于出现了卡顿。

### 描述你想要的解决方案

1.只要更新后增加一个校验，是否更新成功，如果未成功，重新下载一下规则。就可以解决这个问题了。
2.如果是因为整点大家都在更新，所以出现了卡顿，那么更新规则是否可以增加一个随机的等待时间，避免同一个时间去更新。

### 描述你考虑过的替代方案

1.我曾经手动设置crontab，在一个不是整点的时间更新规则，但是规则更新脚本运行以后，会重置crontab，仍然设置为整点。
2.目前我自己写了一个脚本，在规则更新后使用，下载规则，比较一下和当前的规则文件大小，不一致就调用更新脚本更新一下，然后再校验，成功后退出，不成功则继续调用更新脚本。反复三次不成功，就退出。

**Comment by smallprogram** [comment]
可以考虑一下全局代理使用xray分流，直接用geoip geosite，应该可以临时解决你的问题

**Comment by hcym** [comment]
没事更什么新，绝大多数都是用不到的吧

**Comment by smallprogram** [comment]
> 没事更什么新，绝大多数都是用不到的吧

定时更新规则很有必要的，包括GFW List、chnroute、geoip、geosite等规则源每天都在更新。之所以能安全的科学和快速访问G内网络，除了服务端搭建的好(用了TLS、CDN都手段)以外，主要就是靠这些分流规则避免GFW嗅探权重和G内加速的。
如果长时间不更新，很有可能会出现通过代理访问G内网络的情况，一来访问速度变慢，效率低下，浪费流量；二来GFW很有可能会将你的服务器IP加入观察列表，进行数据包深度解析，分析特征等操作，权重到阈值后就有可能会封端口或者被拉黑IP。
在下愚见，仅供参考

**Comment by smallprogram** [comment]
> ### 描述你想要的新功能
> 现在的规则更新，如果某个规则更新失败，会使用一个不完整的规则来进行分流。例如我设置为每周日5点更新规则，经过一段时间的使用，发现有好多次(大概一半的次数)总是 chnroute 更新出错了，log显示更新只有2000条左右，正常的应该有8000条。读取chnroute这个规则，发现后面的6000条都没有，以至于大部分的访问都分流到代理了（我使用的模式为"中国列表以外"）。 这个问题大概率是因为大家可能在某一个整点时间，比如5点整来更新规则，以至于出现了卡顿。
> 
> ### 描述你想要的解决方案
> 1.只要更新后增加一个校验，是否更新成功，如果未成功，重新下载一下规则。就可以解决这个问题了。 2.如果是因为整点大家都在更新，所以出现了卡顿，那么更新规则是否可以增加一个随机的等待时间，避免同一个时间去更新。
> 
> ### 描述你考虑过的替代方案
> 1.我曾经手动设置crontab，在一个不是整点的时间更新规则，但是规则更新脚本运行以后，会重置crontab，仍然设置为整点。 2.目前我自己写了一个脚本，在规则更新后使用，下载规则，比较一下和当前的规则文件大小，不一致就调用更新脚本更新一下，然后再校验，成功后退出，不成功则继续调用更新脚本。反复三次不成功，就退出。
> 
> ### 其他信息
> _No response_

https://github.com/xiaorouji/openwrt-passwall/blob/be2abcc6c86e99a66e898d4d27c4afe58d3f2d8b/luci-app-passwall/root/usr/share/passwall/rule_update.lua#L98-L215

我看了个六透，啥毛病没有，该校验的也md5校验了，各种情况都考虑到了。实在找不出那有毛病。具体逻辑如下：
1. 先按照前台checked的值把相关gfwlist、chnroute、chroute6、chnlist通过CURL和设置的URI下载到unsort_file_tmp并保存到tmp目录下，再处理为`..rule_name.. "_tmp"`这种文件名
2. 然后跟user/share/passwall/rules下的对应文件md5sum校验对比，一样就放弃输出日志` 版本一致，无需更新。`，不一样就更新，输出日志`rule_name.. " 更新成功，总规则数 " ..count.. " 条。"`，这里count条数来自`..rule_name.. "_tmp"`文件条数。
3. geoip、geosite也是下载到tmp目录下，跟usr/share/v2ray目录下的资源文件sha256sum校验，一样就放弃更新，不一样就`"mkdir -p %s && cp -f %s %s", v2ray_asset_location, "/tmp/geoip.dat", v2ray_asset_location .. "geoip.dat"`覆盖文件。

如果有毛病，有可能是curl函数的问题，或者你的源URI的问题，我尝试删除部分chnroute内容，再更新也没问题。实在不知道咋回事了。curl函数什么timeout,retry都配的好好的。
https://github.com/xiaorouji/openwrt-passwall/blob/be2abcc6c86e99a66e898d4d27c4afe58d3f2d8b/luci-app-passwall/root/usr/share/passwall/rule_update.lua#L58-L71

**Comment by ololllolo** [comment]
> 可以考虑一下全局代理使用xray分流，直接用geoip geosite，应该可以临时解决你的问题

感谢帮助，从现在的状况来看，下载规则文件，校验，更新并无问题。不过这部分的逻辑也不是完全没有问题的，比如我提到的如果从规则提供网站上下载的时候，并未下载完整，只下载了部分数据，这时候passwall是会把这个不完整的规则文件当作一个新的规则来应用。从这个角度看，先下载规则，然后再比较md5，并不能解决本地文件和服务器文件一定是一致的。

如果在高峰期同时向规则提供网站请求下载规则数据，就会出现这种情况，应该还是比较常见的，因为昨天在tg群上有一个网友也遇到和我一样的问题。这个问题其实也不大，最多手动更新一下也能解决。但是我见过一些人说过运行passwall一段时间后，会变成全局代理，我想他们大概也是同样的问题。比如 https://github.com/xiaorouji/openwrt-passwall/issues/1973 https://github.com/xiaorouji/openwrt-passwall/issues/2028

我目前写了个定时运行的脚本，从服务器上先获取规则文件的大小，然后比较一下当前的规则文件，大小不匹配就调用一下passwall的更新脚本再次更新一下，暂时先这么用吧。

再次对帮助表示感谢。

**Comment by smallprogram** [comment]
> > 可以考虑一下全局代理使用xray分流，直接用geoip geosite，应该可以临时解决你的问题
> 
> 感谢帮助，从现在的状况来看，下载规则文件，校验，更新并无问题。不过这部分的逻辑也不是完全没有问题的，比如我提到的如果从规则提供网站上下载的时候，并未下载完整，只下载了部分数据，这时候passwall是会把这个不完整的规则文件当作一个新的规则来应用。从这个角度看，先下载规则，然后再比较md5，并不能解决本地文件和服务器文件一定是一致的。
> 
> 如果在高峰期同时向规则提供网站请求下载规则数据，就会出现这种情况，应该还是比较常见的，因为昨天在tg群上有一个网友也遇到和我一样的问题。这个问题其实也不大，最多手动更新一下也能解决。但是我见过一些人说过运行passwall一段时间后，会变成全局代理，我想他们大概也是同样的问题。比如 #1973 #2028
> 
> 我目前写了个定时运行的脚本，从服务器上先获取规则文件的大小，然后比较一下当前的规则文件，大小不匹配就调用一下passwall的更新脚本再次更新一下，暂时先这么用吧。
> 
> 再次对帮助表示感谢。

能保证新得规则大小一定比老的大吗？还是我把curl得ssl校验加上？

**Comment by smallprogram** [comment]
> > 可以考虑一下全局代理使用xray分流，直接用geoip geosite，应该可以临时解决你的问题
> 
> 感谢帮助，从现在的状况来看，下载规则文件，校验，更新并无问题。不过这部分的逻辑也不是完全没有问题的，比如我提到的如果从规则提供网站上下载的时候，并未下载完整，只下载了部分数据，这时候passwall是会把这个不完整的规则文件当作一个新的规则来应用。从这个角度看，先下载规则，然后再比较md5，并不能解决本地文件和服务器文件一定是一致的。
> 
> 如果在高峰期同时向规则提供网站请求下载规则数据，就会出现这种情况，应该还是比较常见的，因为昨天在tg群上有一个网友也遇到和我一样的问题。这个问题其实也不大，最多手动更新一下也能解决。但是我见过一些人说过运行passwall一段时间后，会变成全局代理，我想他们大概也是同样的问题。比如 #1973 #2028
> 
> 我目前写了个定时运行的脚本，从服务器上先获取规则文件的大小，然后比较一下当前的规则文件，大小不匹配就调用一下passwall的更新脚本再次更新一下，暂时先这么用吧。
> 
> 再次对帮助表示感谢。

能否把脚本帖一下

**Comment by ololllolo** [comment]
因为只有chnroute的规则容易出现错误，所以我的脚本只校验这两个规则，不是很会写脚本，就是简单判断一下。
```
#!/bin/sh
# 规则列表校验脚本

# 脚本变量
## 重试计数器
count=3
## 重试间隔时间(秒)
retry_time=600

## 规则列表地址变量
chnroute_url="https://ispip.clang.cn/all_cn.txt"
chnroute6_url="https://ispip.clang.cn/all_cn_ipv6.txt"

# 创建日志
touch /tmp/log/rules.log

# 获取时间
function now_time()
{
date "+%Y-%m-%d %H:%M:%S"
}

# 规则校验
function rules_check()
{
if [ `wget -t 2 --timeout=60 --spider "$chnroute_url" 2>&1 | grep "Length" | awk '{print $2}'` == `ls -l /usr/share/passwall/rules/chnroute | awk '{print $5}'` ]
	then
		chnroute_update="OK"
		echo `now_time` "国内IPv4地址列表和当前列表匹配!" >> /tmp/log/rules.log
	else
		chnroute_update="NO"
		echo `now_time` "国内IPv4地址列表和当前列表不匹配!" >> /tmp/log/rules.log
fi

if [ `wget -t 2 --timeout=60 --spider "$chnroute6_url" 2>&1 | grep "Length" | awk '{print $2}'` == `ls -l /usr/share/passwall/rules/chnroute6 | awk '{print $5}'` ]
	then
		chnroute6_update="OK"
		echo `now_time` "国内IPv6地址列表和当前列表匹配!" >> /tmp/log/rules.log
	else
		chnroute6_update="NO"
		echo `now_time` "国内IPv6地址列表和当前列表不匹配!" >> /tmp/log/rules.log
fi

if [ $chnroute_update == "OK" ] && [ $chnroute6_update == "OK" ]
	then
		echo `now_time` "规则列表工作正常,脚本退出!" >> /tmp/log/rules.log
		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
		exit
fi
}

# 规则更新
function rules_update()
{
echo `now_time` "检测到规则列表不正确，开始更新规则列表!" >> /tmp/log/rules.log
lua /usr/share/passwall/rule_update.lua log > /dev/null 2>&1
echo `now_time` "更新完成，等待校验!" >> /tmp/log/rules.log
rules_check

if [ $count != 0 ]
	then
		echo `now_time` "规则列表匹配没有成功，等待重新进行更新!" >> /tmp/log/rules.log
		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
	else
		echo `now_time` "由于规则列表已经更新多次仍然未成功匹配，脚本将退出，根据计划列表等待下次运行!" >> /tmp/log/rules.log
		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
		exit
fi
}

# 脚本主循环
echo `now_time` "开始进行规则文件校验!" >> /tmp/log/rules.log

while [ ! $count == 0 ]
do
	count=$((count-1))
	
	sleep $retry_time
	rules_check
	rules_update
done

exit

```

**Comment by smallprogram** [comment]
> 因为只有chnroute的规则容易出现错误，所以我的脚本只校验这两个规则，不是很会写脚本，就是简单判断一下。
> 
> ```
> #!/bin/sh
> # 规则列表校验脚本
> 
> # 脚本变量
> ## 重试计数器
> count=3
> ## 重试间隔时间(秒)
> retry_time=600
> 
> ## 规则列表地址变量
> chnroute_url="https://ispip.clang.cn/all_cn.txt"
> chnroute6_url="https://ispip.clang.cn/all_cn_ipv6.txt"
> 
> # 创建日志
> touch /tmp/log/rules.log
> 
> # 获取时间
> function now_time()
> {
> date "+%Y-%m-%d %H:%M:%S"
> }
> 
> # 规则校验
> function rules_check()
> {
> if [ `wget -t 2 --timeout=60 --spider "$chnroute_url" 2>&1 | grep "Length" | awk '{print $2}'` == `ls -l /usr/share/passwall/rules/chnroute | awk '{print $5}'` ]
> 	then
> 		chnroute_update="OK"
> 		echo `now_time` "国内IPv4地址列表和当前列表匹配!" >> /tmp/log/rules.log
> 	else
> 		chnroute_update="NO"
> 		echo `now_time` "国内IPv4地址列表和当前列表不匹配!" >> /tmp/log/rules.log
> fi
> 
> if [ `wget -t 2 --timeout=60 --spider "$chnroute6_url" 2>&1 | grep "Length" | awk '{print $2}'` == `ls -l /usr/share/passwall/rules/chnroute6 | awk '{print $5}'` ]
> 	then
> 		chnroute6_update="OK"
> 		echo `now_time` "国内IPv6地址列表和当前列表匹配!" >> /tmp/log/rules.log
> 	else
> 		chnroute6_update="NO"
> 		echo `now_time` "国内IPv6地址列表和当前列表不匹配!" >> /tmp/log/rules.log
> fi
> 
> if [ $chnroute_update == "OK" ] && [ $chnroute6_update == "OK" ]
> 	then
> 		echo `now_time` "规则列表工作正常,脚本退出!" >> /tmp/log/rules.log
> 		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
> 		exit
> fi
> }
> 
> # 规则更新
> function rules_update()
> {
> echo `now_time` "检测到规则列表不正确，开始更新规则列表!" >> /tmp/log/rules.log
> lua /usr/share/passwall/rule_update.lua log > /dev/null 2>&1
> echo `now_time` "更新完成，等待校验!" >> /tmp/log/rules.log
> rules_check
> 
> if [ $count != 0 ]
> 	then
> 		echo `now_time` "规则列表匹配没有成功，等待重新进行更新!" >> /tmp/log/rules.log
> 		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
> 	else
> 		echo `now_time` "由于规则列表已经更新多次仍然未成功匹配，脚本将退出，根据计划列表等待下次运行!" >> /tmp/log/rules.log
> 		echo `now_time` "-----------------------------------------" >> /tmp/log/rules.log
> 		exit
> fi
> }
> 
> # 脚本主循环
> echo `now_time` "开始进行规则文件校验!" >> /tmp/log/rules.log
> 
> while [ ! $count == 0 ]
> do
> 	count=$((count-1))
> 	
> 	sleep $retry_time
> 	rules_check
> 	rules_update
> done
> 
> exit
> ```

用xray分流把，或者用passwall2

**Comment by ShanStone** [comment]
按照你的思路弄了下，试试看呢

**Comment by ololllolo** [comment]
> 按照你的思路弄了下，试试看呢

十分感谢，已经拉取最新的代码编译了，看到代码里面有比较下载文件和服务器返回Content-Length的大小，现在工作正常，测试一段时间看看。
