### ISSUE TITLE
关于支持nftables问题。

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#2121]
现在日志报
2022-10-06 00:27:37: 检测到fw4防火墙，但Dnsmasq软件包不满足nftables透明代理要求，如需使用请确保dnsmasq版本在2.87以上并开启nftset支持。
这个。
我用的是dnsmasq-full版本是2.86-14已经是最新版的了，没有找到2.87版，nftset请问是在那里开启，.config整个文件我都找过了没这个选项，我现在应该怎么做，谢谢

**Comment by syazwansaidan93** [comment]
> go for immortalwrt

**Comment by syazwansaidan93** [comment]
> 现在日志报 2022-10-06 00:27:37: 检测到fw4防火墙，但Dnsmasq软件包不满足nftables透明代理要求，如需使用请确保dnsmasq版本在2.87以上并开启nftset支持。 这个。 我用的是dnsmasq-full版本是2.86-14已经是最新版的了，没有找到2.87版，nftset请问是在那里开启，.config整个文件我都找过了没这个选项，我现在应该怎么做，谢谢

https://github.com/immortalwrt/immortalwrt/commit/ab7c30afb523da4801ea9ab1e31e55561abc5ad1

**Comment by snakwu** [comment]
@syazwansaidan93  我是官方源码，应该怎么操作？谢谢

**Comment by lxhao61** [comment]
那目前常用源码Lean大与Lienol大的都不支持，dnsmasq-full版本都低于2.87。
