### ISSUE TITLE
[Bug]: 使用L大源码编译，取消IPV6支持，编译报错提示ipv6/netfilter/nft_reject_ipv6.ko' is missing，不勾选可以成功

### ISSUE THREAD

**Issue by iowclz** [xiaorouji/openwrt-package#2134]
### 描述您遇到的bug

使用L大源码编译，取消IPV6支持，编译报错提示ipv6/netfilter/nft_reject_ipv6.ko' is missing

### 复现此Bug的步骤

取消选择IPV6支持

### 您想要实现的目的

之前取消IPV6支持不报错

### 日志信息

strip.sh: /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra/lib/modules/5.15.72/xt_owner.ko: relocatable
rstrip.sh: /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra/lib/modules/5.15.72/xt_pkttype.ko: relocatable
rstrip.sh: /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra/lib/modules/5.15.72/xt_addrtype.ko: relocatable
rstrip.sh: /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra/lib/modules/5.15.72/xt_quota.ko: relocatable
rstrip.sh: /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra/lib/modules/5.15.72/xt_cgroup.ko: relocatable
Packaged contents of /firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/ipkg-x86_64/kmod-ipt-extra into /firmware_x86/lede/bin/targets/x86/64/packages/kmod-ipt-extra_5.15.72-1_x86_64.ipk
**ERROR: module '/firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.72/net/ipv6/netfilter/nft_reject_ipv6.ko' is missing.**
make[3]: *** [modules/netfilter.mk:1124: /firmware_x86/lede/bin/targets/x86/64/packages/kmod-nft-core_5.15.72-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/firmware_x86/lede/package/kernel/linux'
time: package/kernel/linux/compile#6.32#2.57#7.84
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/firmware_x86/lede'
make[1]: *** [package/Makefile:110: /firmware_x86/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/firmware_x86/lede'
make: *** [/firmware_x86/lede/include/toplevel.mk:230: world] Error 2

### 系统相关信息

内核版本5.15.72

**Comment by ShanStone** [comment]
https://github.com/coolsnowwolf/lede/issues/10239

**Comment by iowclz** [comment]
不选择passwall可以编译成功，勾选就编译失败，一样的提示缺少nft_reject_ipv6.ko




echo "netifd" >> /firmware_x86/lede/staging_dir/target-x86_64_musl/pkginfo/netif                                                                    d.default.install
make[3]: Leaving directory '/firmware_x86/lede/package/network/config/netifd'
time: package/network/config/netifd/compile#0.17#0.09#0.27
make[3]: Entering directory '/firmware_x86/lede/package/firmware/linux-firmware'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/firmware_x86/lede/package/firmware/linux-firmware'
time: package/firmware/linux-firmware/compile#0.18#0.07#0.23
make[3]: Entering directory '/firmware_x86/lede/package/kernel/linux'
mkdir -p /firmware_x86/lede/staging_dir/target-x86_64_musl/root-x86/stamp

SHELL= flock /firmware_x86/lede/tmp/.root-copy.flock -c 'cp -fpR /firmware_x86/l                                                                    ede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kernel/. /firmwar                                                                    e_x86/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /firmware_x86/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kernel_i                                                                    nstalled
ERROR: module '/firmware_x86/lede/build_dir/target-x86_64_musl/linux-x86_64/linu                                                                    x-5.15.72/net/ipv6/netfilter/nft_reject_ipv6.ko' is missing.
make[3]: *** [modules/netfilter.mk:1124: /firmware_x86/lede/bin/targets/x86/64/p                                                                    ackages/kmod-nft-core_5.15.72-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/firmware_x86/lede/package/kernel/linux'
time: package/kernel/linux/compile#2.07#0.34#2.47
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/firmware_x86/lede'
make[1]: *** [package/Makefile:110: /firmware_x86/lede/staging_dir/target-x86_64                                                                    _musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/firmware_x86/lede'
make: *** [/firmware_x86/lede/include/toplevel.mk:230: world] Error 2
