### ISSUE TITLE
[Feature Request]: 首页状态卡片展示问题

### ISSUE THREAD

**Issue by hplee0120** [xiaorouji/openwrt-package#2141]
### 描述你想要的新功能

即使不编译负载均衡，在首页还是会保留这个状态卡片似乎有点多余，是否可以适当优化一下显示逻辑，另外这个github连接和Instagram连接测试个人认为好像没啥意义，保留百度和谷歌（国内和国外）应该就足够了？

### 描述你想要的解决方案

不编译负载均衡时不显示该卡片展示

**Comment by handsomeji** [comment]
这个可能在某次提交不小心删了对应的逻辑代码了。。。
