### ISSUE TITLE
dnsmasq启动失败

### ISSUE THREAD

**Issue by sky2016cn** [xiaorouji/openwrt-package#2142]
### 描述您遇到的bug

只要在“访问控制”里添加设备，网络出现不正常。

### 复现此Bug的步骤

1. 访问控制
2. 设置后，dnsmasq启动失败，网络出现不稳定

### 您想要实现的目的

此前版本没有此现象，希望修复

### 日志信息

Lede固件系统日志提示：
Fri Oct 14 13:11:08 2022 cron.err crond[18410]: crond (busybox 1.35.0) started, log level 5
Fri Oct 14 13:11:14 2022 daemon.crit dnsmasq[20984]: cannot access directory /tmp/etc/passwall/acl/cfg5c30ec/dnsmasq.d: No such file or directory
Fri Oct 14 13:11:14 2022 daemon.crit dnsmasq[20984]: FAILED to start up
Fri Oct 14 13:11:15 2022 cron.err crond[21669]: crond (busybox 1.35.0) started, log level 5

### 系统相关信息

Passwall 版本号：luci-app-passwall	4.55-1

Lede固件x86：OpenWrt R22.10.10，内核版本：5.15.72

**Comment by smallprogram** [comment]
重置passwall试一下，我这边没问题
