### ISSUE TITLE
[Feature Request]: 希望再次增加SS的kcp功能。亦或者把kcp单独拎出来可以配合更多东西使用

### ISSUE THREAD

**Issue by boyyao** [xiaorouji/openwrt-package#2144]
### 描述你想要的新功能

一直用老版本支持kcp。用着非常稳定高效。更新版本后kcp没有了真的有点不太习惯~哈哈

### 描述你想要的解决方案

增加kcptun的支持。

**Comment by WYC-2020** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/b4985a49e2b3ccf8d8e0c84df509ac6d6a1d61ce
fork了 自己撤回呗
