### ISSUE TITLE
不能自定义SS协议的SIP003插件

### ISSUE THREAD

**Issue by qwerttvv** [xiaorouji/openwrt-package#2150]
### 描述你想要的新功能

只能编译时候带上几个SIP003插件，但是不能在界面自定义其他插件，包括插件参数

### 描述你想要的解决方案

希望可以在界面提供自定义插件和插件参数的选项

**Comment by sjtuross** [comment]
这不是可以自定义吗？

![image](https://user-images.githubusercontent.com/940110/196874882-97fb716d-4e3e-4b9a-bded-09d4016ad978.png)

![image](https://user-images.githubusercontent.com/940110/196874776-2aaa80c8-ba04-41ec-b062-a2891996d765.png)

**Comment by qwerttvv** [comment]
> 这不是可以自定义吗？
> 
> ![image](https://user-images.githubusercontent.com/940110/196874882-97fb716d-4e3e-4b9a-bded-09d4016ad978.png)
> 
> ![image](https://user-images.githubusercontent.com/940110/196874776-2aaa80c8-ba04-41ec-b062-a2891996d765.png)

我不用这三个插件

我用其他插件

所以说现在不能自定义

**Comment by qwerttvv** [comment]
@xiaorouji 希望帮忙看下

**Comment by smallprogram** [comment]
Welcome PR
