### ISSUE TITLE
[Bug]: Lienol大的21.02源码编译增加passwall报错缺少依赖

### ISSUE THREAD

**Issue by 281677160** [xiaorouji/openwrt-package#2157]
### 描述您遇到的bug

Lienol大的21.02源码增加passwall编译x86固件报错缺少kmod-inet-diag

### 复现此Bug的步骤

..

### 您想要实现的目的

请问各位大佬们，怎么增加此文件

### 日志信息

WARNING: Makefile 'package/feeds/passwall/sing-box/Makefile' has a dependency on 'kmod-inet-diag', which does not exist

### 截图

![QQ截图20221021230923](https://user-images.githubusercontent.com/66651997/197229505-74bbf1e1-a4e3-484f-a4ed-a4b871ad76ec.png)

### 系统相关信息

..

### 其他信息

..

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/197341691-6c3fe37d-470b-4b85-a5c0-2ec35195db21.png)

**Comment by 281677160** [comment]
感谢回复，可惜Lienol大的21.02的找不到这个东西，要是可以找到的话，我前2天谷歌，百度的都能搞好了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaorouji/openwrt-passwall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaorouji/openwrt-passwall] [Bug]: Lienol大的21.02源码编译增加passwall报错缺少依赖 (Issue #2157)

**Comment by sjkhsl** [comment]
> 感谢回复，可惜Lienol大的21.02的找不到这个东西，要是可以找到的话，我前2天谷歌，百度的都能搞好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xiaorouji/openwrt-passwall" ***@***.***&gt;; 发送时间:&nbsp;2022年10月22日(星期六) 晚上9:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xiaorouji/openwrt-passwall] [Bug]: Lienol大的21.02源码编译增加passwall报错缺少依赖 (Issue #2157) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你解决了吗？我也碰到了！
