### ISSUE TITLE
[Bug]: passwall server功能无法加载防火墙规则

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#2161]
### 描述您遇到的bug

目前在 server/api/app.lua 文件中，判断防火墙类型的代码为
`local nft_flag = sys.exec("command -v fw4") and "1" or "0"`
这个代码测试了下返回值总是1，导致之后server加载防火墙会按照fw4的逻辑
![image](https://user-images.githubusercontent.com/44677306/197544875-f66ba02c-a012-46d1-8d9a-b8e8d717f6a2.png)
![image](https://user-images.githubusercontent.com/44677306/197544782-0847a2eb-8e02-4f92-8de3-43aef4d8bf49.png)

### 复现此Bug的步骤

开启passwall server功能即可复现

### 您想要实现的目的

能够正常分类防火墙类型

### 日志信息

暂无

### 系统相关信息

version: 4.55-2
openwrt: OpenWrt R22.10.20 / LuCI Master (git-22.289.58375-2a380a3)

**Comment by ShanStone** [comment]
已修复，试一下最新源码

**Comment by WROIATE** [comment]
> 已修复，试一下最新源码

测试正常，关闭该issue
