### ISSUE TITLE
[Bug]: 使用分流模式会导致部分网站无法访问 

### ISSUE THREAD

**Issue by asumi233** [xiaorouji/openwrt-package#2165]
### 描述您遇到的bug

当分流模式的默认设置为直连时 部分特定的网站 无法打开  必须将 分流默认动作设置为 代理节点 才能正常访问
问题网站地址：www.tonymacx86.com
我也调整过 优先级分流策略 无用

我的dns分流方案是:mosdns 通过geosite和geoip表 将不同国家的域名 使用不同的dns服务器进行查询
并设置 5335端口作为dnsmasq的上游  在passwall中也设置 5335 dns进行过滤
dns缓存也检查过 跟这个无关 

### 复现此Bug的步骤

1.选择分流
2.默认动作设置为直连
3.访问www.tonymacx86.com 无法打开 没任何响应 换过浏览器也试过了

### 您想要实现的目的

解决这个问题，因为我不知道问题出在哪

### 日志信息

2022-10-27 00:09:32: 清空并关闭相关程序和缓存完成。
2022-10-27 00:09:32: UDP节点没有选择或为空，不代理UDP。
2022-10-27 00:09:32: 过滤服务配置：准备接管域名解析...
2022-10-27 00:09:32:   - 域名解析：使用UDP协议请求DNS（127.0.0.1#5335）...
2022-10-27 00:09:32:   * 要求代理 DNS 请求，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
2022-10-27 00:09:32:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2022-10-27 00:09:32: 开始加载防火墙规则...
2022-10-27 00:09:33: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2022-10-27 00:09:33: 加入所有节点到ipset[vpsiplist]直连完成
2022-10-27 00:09:36: 加载路由器自身 TCP 代理...
2022-10-27 00:09:36:   - [0]，屏蔽代理UDP 端口：80,443
2022-10-27 00:09:37: TCP默认代理：使用TCP节点[v2ray-分流] [中国列表以外](REDIRECT:1041)代理所有端口
2022-10-27 00:09:37: 防火墙规则加载完成！
2022-10-27 00:09:41: 重启 dnsmasq 服务
2022-10-27 00:09:41: 配置定时任务：自动更新规则。
2022-10-27 00:09:41: 运行完成！

### 截图

![image](https://user-images.githubusercontent.com/83440742/198078773-3827759f-ec0a-4778-be9e-615590c07ccd.png)
![image](https://user-images.githubusercontent.com/83440742/198078819-95ba0c43-717c-44fe-b4f0-81682bc43235.png)
![image](https://user-images.githubusercontent.com/83440742/198078866-ce1956c6-0b6f-46a6-90e9-8017c392be6c.png)
![image](https://user-images.githubusercontent.com/83440742/198079576-94b56d32-514f-4c16-a6e3-1d0005e1fbd6.png)

### 系统相关信息

passwall:今天编译的最新版本
chrome：最新 windows平台 已关了安全dns

**Comment by smallprogram** [comment]
**我这边测试了一下，除了DNS外，按照你的两种方式测试了一下，完全正常。**
![image](https://user-images.githubusercontent.com/6050360/198330959-988fd9e9-1a58-439a-aa39-9138aece2b57.png)

**1. 首先我能肯定`www.tonymacx86.com`没有被中国列表外命中，可能原因是你配的DNS解析的IP不在中国列表之外。**
**2. 然后你分流规则中也没有被Proxy规则命中，可能原因你的Proxy规则没写好，我这边写的域名为`geosite:geolocation-!cn`,IP列表为：**
   ```
   149.154.160.0/20
   91.108.4.0/22
   91.108.56.0/24
   109.239.140.0/24
   67.198.55.0/24
   8.8.4.4
   8.8.8.8
   208.67.222.222
   208.67.220.220
   1.1.1.1
   1.1.1.2
   1.0.0.1
   9.9.9.9
   149.112.112.112
   2001:67c:4e8::/48
   2001:b28:f23c::/48
   2001:b28:f23d::/48
   2001:b28:f23f::/48
   2001:b28:f242::/48
   2001:4860:4860::8888
   2001:4860:4860::8844
   2606:4700:4700::1111
   2606:4700:4700::1001
   ```
**3. 以上都没命中，直接走默认直连，所以你打不开**
**4. 当你将默认换为代理，当然所有规则都没命中的前提下，这个`www.tonymacx86.com`肯定是走了代理的，所以能打开**

**综上这可能并不是一个BUG。有可能的原因如下：**
**1. 折腾DNS导致了该问题**
**2. 你的规则以及Geo文件没更新**
**3. 你的分流规则没写好**

**你可以根据以上这三种情况检查一下，如果还不行，请直接使用1.1.1.1的DNS，TCP请求。如果再不行，请重置Passwall**

**Comment by asumi233** [comment]
![image](https://user-images.githubusercontent.com/83440742/198349622-996d4b2a-1093-4dd9-bf0f-23ef35707e2f.png)
这个是 passwall的直连规则
![image](https://user-images.githubusercontent.com/83440742/198349719-f53c76dc-d817-4802-84cc-5219090036e5.png)
这个是mosdns的查询规则 

dnsmasq上游和passwall过滤的dns列表都是这个dns 5335端口

**Comment by asumi233** [comment]
还有这个网站貌似直连是可以打开的  但是 我默认走直连缺打不开 chrome完全没任何响应 过了一会就显示连接失败了

**Comment by smallprogram** [comment]
表示没玩过mosdns，解析这个网址IP是非大陆IP，66.232.110.83
通过测试发现这个IP很有问题，国内外也并非所有地区都能访问443，这也许可以说明问题了：
![image](https://user-images.githubusercontent.com/6050360/198352224-c33ba61f-2ea4-4cd7-8c56-4665873c30d4.png)

**Comment by asumi233** [comment]
OK 谢谢老哥解答 我在切换一下dns试试   smartdns 用官方的那个还是第三方源码的luci呢？

**Comment by smallprogram** [comment]
我编译的固件之前用过官方的，后来是第三方的，都没啥问题，目前我自己用的啥也没用，dns没折腾。
