### ISSUE TITLE
[Feature Request]: Vless-ws-tls-cdn 下 使用 Haproxy

### ISSUE THREAD

**Issue by jyy5206** [xiaorouji/openwrt-package#2173]
### 描述你想要的新功能

以前直接 Vmess-tcp 裸奔，3个 VPS 设置成相同参数后，配置 HAproxy 轻而易举，极大增加了高可用性。
近期 GFW 持续发威，3个 IP 全部炸光。
改为 Vless-ws-tls-cdn 后，目前已使用数天，基本不炸了。

但是只能单个 IP 使用，无法组 HAproxy。
address 倒还好，可以直接填入分配到的 CF cdn IP。
但是里面的 host & ws host 每个 VPS 都不一样，做不到 HAproxy “全部参数一样”的要求。

### 描述你想要的解决方案

在 Vless-ws-tls-cdn下，还是可以组成 HAproxy 使用。

### 描述你考虑过的替代方案

根据网上查询，尝试过把每个VPS用Socks转换成一个socks节点后，再组 HAproxy。
https://github.com/xiaorouji/openwrt-passwall/discussions/1820 
但是发现我的红米 AC2100 因为内存不足崩溃了 。。。

当然，用软路由就不会崩溃。

### 其他信息

恳请各位大佬指点下。

感谢！

**Comment by smallprogram** [comment]
> 但是发现我的红米 AC2100 因为内存不足崩溃了 。。。

这。。。。是问题根源

**Comment by jyy5206** [comment]
> 是的。红米 AC2100 启动时，top 观察到内存不足的提示。
软路由就没问题。

如何能在 AC 2100 上，不用 socks 转换，就能用上 HAproxy 呢？
