### ISSUE TITLE
[Feature Request]: 请求增加 Xray-core 1.6.2版本增加的新流控选项 xtls-rprx-vision

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-package#2176]
### 描述你想要的新功能

在网页中的流控选项中增加 xtls-rprx-vision xtls-rprx-vision-udp443 选项

配置文件是
"streamSettings" 内须为 "security":"tls"+"tlsSettings"

### 描述你想要的解决方案

更新日志 https://github.com/XTLS/Xray-core/releases

https://github.com/XTLS/Xray-core/discussions/1295

**Comment by smallprogram** [comment]
等周末我好好搞一下

**Comment by smallprogram** [comment]
已更新

**Comment by chika0801** [comment]
> 已更新

感谢你
