### ISSUE TITLE
[Feature Request]:请升级一下naive 至 v107.0.5304.87-1

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-package#2177]
### 描述你想要的新功能

RT

### 描述你想要的解决方案

RT

**Comment by NeedforGit** [comment]
我在passwall上用 naive 网页没问题，但是 youtube 的视频打不开，有朋友知道是怎么一回事吗？

在安卓手机上用 app 挂 naive 没问题。

**Comment by openips** [comment]
没遇到问题

**Comment by Beginner-Go** [comment]
7f54b9b56f1c3d71d3f4c5f84496b88ee85a4f25
