### ISSUE TITLE
【已解决】[Bug]: 最新编译openwrt官源+passwall (非passwall2) 开启主开关后ping不通，上一版本相同设置相同节点一切正常。

### ISSUE THREAD

**Issue by microdockman** [xiaorouji/openwrt-package#2186]
### 描述您遇到的bug

版本：openwrt官源最新
           passwall(非passwall2)最新
开启主开关后ping不通，上一版本相同设置相同节点一切正常。

### 复现此Bug的步骤

安装镜像如下，设置如下
https://github.com/microdockman/001/releases/tag/tmp

![x1](https://user-images.githubusercontent.com/31898637/201460453-f363ab9a-69e9-48ea-9710-8d22209549f5.PNG)
![x2](https://user-images.githubusercontent.com/31898637/201460456-174e28ab-018c-4076-ad3b-a23742c6f138.PNG)
![x3](https://user-images.githubusercontent.com/31898637/201460458-1756323d-84f4-4a66-8701-c48ed9941a74.PNG)
![x4](https://user-images.githubusercontent.com/31898637/201460459-b3a22aec-0315-493d-9c0e-f6d0930e12b3.PNG)

### 您想要实现的目的

pawwal主开关启动后网络连接正常

### 日志信息

暂无

### 截图

如上

### 系统相关信息

版本：openwrt官源最新
           passwall(非passwall2)最新

**Comment by hcym** [comment]
刚刚编译的22.03正常工作，还有clash和v2raya，没有大雕ssrp

**Comment by microdockman** [comment]
> 刚刚编译的22.03正常工作，还有clash和v2raya，没有大雕ssrp

也是官源？我这里编译几次也都是这样.奇怪，也没添加任何插件，都是老设置

**Comment by hcym** [comment]
就是官方的，大雕的源码ipv6和什么fullclone实在不喜欢，基本都是用官方的编译，再加ssrplus什么的

**Comment by microdockman** [comment]
> 就是官方的，大雕的源码ipv6和什么fullclone实在不喜欢，基本都是用官方的编译，再加ssrplus什么的

老哥能麻烦你发个diffconfig文件吗，我这找不到问题出哪了

**Comment by hcym** [comment]
明天吧，我都是挂内存的，重启就没了，没什么特殊的，基本上几个月不会变

**Comment by microdockman** [comment]
> 明天吧，我都是挂内存的，重启就没了，没什么特殊的，基本上几个月不会变

好

**Comment by hcym** [comment]
今天还没开工，没有 .config
include/target.mk是我一直用的，其他都没有变动

# Default packages - the really basic set
DEFAULT_PACKAGES:=\
	base-files \
	ca-bundle \
	dropbear \
	fstools \
	libc \
	libgcc \
	libustream-wolfssl \
	logd \
	mtd \
	netifd \
	opkg \
	uci \
	uclient-fetch \
	urandom-seed \
	urngd \
iptables-mod-conntrack-extra iptables-mod-nat-extra kmod-tulip kmod-tun bash coreutils-nohup rootfs-part \
ruby-yaml ruby libcap-bin libcap ip6tables-mod-nat ip-bridge zoneinfo-asia kmod-ipt-nft \
kmod-nf-nathelper kmod-nf-nathelper-extra kmod-ipt-raw kmod-tun \
coreutils coreutils-base64 ipset ip-full iptables-mod-extra kmod-ipt-nat kmod-sensors hysteria \
kmod-ipt-tproxy jsonfilter jshn curl wget htop lm-sensors kmod-ipt-extra kmod-inet-diag kmod-nft-tproxy iptables-mod-tproxy iptables-nft libopenssl-conf \
kmod-nf-nathelper kmod-ipt-raw unzip wget-ssl resolveip kmod-crypto \
kmod-nf-nathelper-extra kmod-crypto-gcm haproxy \
ca-certificates luci luci-compat luci-lib-ipkg luci-lib-json luci-proto-ipv6 \
luci-app-haproxy-tcp luci-app-ssr-plus luci-app-passwall luci-app-openclash v2raya


# For router targets
# For router targets
DEFAULT_PACKAGES.router:=\
	dnsmasq-full \
	firewall4 \
	nftables \
	kmod-nft-offload \
	odhcp6c \
	odhcpd-ipv6only \
	ppp \
	ppp-mod-pppoe

**Comment by hcym** [comment]
电脑才能看到你的图
估计固件没问题，你那些lan口什么的设置我从来不动，就是系统设置
无论官方的大雕的还是其它什么固件

**Comment by microdockman** [comment]
> 电脑才能看到你的图 估计固件没问题，你那些lan口什么的设置我从来不动，就是系统设置 无论官方的大雕的还是其它什么固件

好，多谢老哥了，我抽空试试看。

**Comment by wazzx** [comment]
> 刚刚编译的22.03正常工作，还有clash和v2raya，没有大雕ssrp

我想问一下是22.03.2版本吗！还是22.03的支线，模式是什么模式nftables还是ipset（兼容模式）

**Comment by microdockman** [comment]
passwall 回退到10.20号更新版本，恢复正常了


feeds.conf.default
src-git 3lienol https://github.com/microdockman/Lienol.git^047e47d25f
src-git 4lienol https://github.com/microdockman/Lienol.git^2a10c6c52c

正常版本固件和diffconfig文件
https://github.com/microdockman/001/releases/tag/tmp
5.15.78+passwall2022_10_20.img
diffconfig_passwall2022_10_20

passwall 没有选nftable transparent proxy
dnsmasq-full  加选了Build with IPset support（不知道是不是这个没选的缘故）

**Comment by microdockman** [comment]
擦，就是没选Build with IPset support，dnsmasq-full没选全。。。
已解决
