### ISSUE TITLE
[Feature Request]: trojan plus 支持alpn设置

### ISSUE THREAD

**Issue by planxx** [xiaorouji/openwrt-package#2190]
### 描述你想要的新功能

trojan plus 不支持alpn设置，所以有些trojan节点无法使用，大佬能不能给trojan节点配置加上alpn设置选项……

### 描述你想要的解决方案

trojan plus 不支持alpn设置，所以有些trojan节点无法使用，大佬能不能给trojan节点配置加上alpn设置选项……

### 描述你考虑过的替代方案

无

### 其他信息

无

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/203108472-9183f3eb-f0bb-4340-a3ce-41ab199c6cd5.png)
试试这个，也许能行

**Comment by planxx** [comment]
感谢作者，测试了，确实可行。
