### ISSUE TITLE
[Bug]: v2ray OOM

### ISSUE THREAD

**Issue by github3C** [xiaorouji/openwrt-package#2191]
### 描述您遇到的bug

软路由最近发现间歇性断网
对比系统日志发现断网时会有 OOM 日志, 同时会下方会出现 '/v2ray' 关键字

软路由内存: 2G

### 复现此Bug的步骤

随机发生

### 您想要实现的目的

排查问题原因

### 日志信息

被刷掉了,暂无

### 系统相关信息

- passwall 版本: (20221116拉取的源码)

**Comment by smallprogram** [comment]
OOM的意思是Out Of Memory，换个4G版本的老铁

**Comment by github3C** [comment]
> OOM的意思是Out Of Memory，换个4G版本的老铁

没有4G的设备啊，能从passwall这边限制吗？

**Comment by smallprogram** [comment]
> > OOM的意思是Out Of Memory，换个4G版本的老铁
> 
> 没有4G的设备啊，能从passwall这边限制吗？

不能

**Comment by github3C** [comment]
结。
passwall 需求 `ram≧4G`

**Comment by smallprogram** [comment]
> 结。 passwall 需求 `ram≧4G`

-_-! ，你个杠精，passwall不是需要4G memory，我不知道你用的啥固件，我这边512M的软路由也一样跑的没毛病。我哪知道你都装了啥插件，用的谁的OP源码，用的啥内核，怎么编译的固件。passwall只是个整合了各式各样的代理工具的LUCI插件而已，你报的OOM那是V2ray的问题，跟PW有啥关系。别杠，有杠的功夫你不如好好看看源码，分析分析问题。

**Comment by github3C** [comment]
嗐，这不是代码能力不精，来求助么。。。
照一个网友老哥的说法，修改了下pw的配置，再观察下情况。
自己编译的固件，跑了10天没崩，今天上午又不行了

**Comment by github3C** [comment]
@smallprogram 请教下，passwall启动的进程数是怎么决定的？
比如我查 v2ray 进程，发现启了12个进程

**Comment by smallprogram** [comment]
`root/etc/init.d/passwall`为初始化，调用`usr/share/passwall/app.sh`中的start()方法，进行一些列启动业务，包括调用`helper_dnsmasq.sh` `smartdns.sh`,你可以看看源码，我没仔细看
