### ISSUE TITLE
[Bug]: whatsapp and many other apps call problem

### ISSUE THREAD

**Issue by Recoba86** [xiaorouji/openwrt-package#2194]
### 描述您遇到的bug

WhatsApp audio and video calls and any other app voice call like telegram call or google meet do work when passwall is on!
I tried Twilio test here
https://networktest.twilio.com/
and it shows blocked in the voice section
I think something is not right with UDP because these apps use UDP for call services
OpenWRT 21.02
passwall last version
is it a well-known problem or its just me?
I tried xray core-v2ray core-trojan go but all have problems with audio and video call
Whatsapp chat work but in call show connecting
the 

### 复现此Bug的步骤

all audio call show connecting but wont connect.

### 您想要实现的目的

I want to solve WhatsApp call problems

### 日志信息

No log

### 截图

![Screenshot 2022-11-17 220924](https://user-images.githubusercontent.com/70960815/202530686-683190c2-a949-4308-8f41-7705a762a5f6.png)

### 系统相关信息

passwall last version
OpenWRT 21.02

**Comment by smallprogram** [comment]
Try this, Maybe can help you
![image](https://user-images.githubusercontent.com/6050360/203107258-c850b5e2-a0f2-4601-8a53-976205884038.png)

**Comment by Recoba86** [comment]
tried but no help
still WhatsApp calls don't work!

**Comment by jyy5206** [comment]
Turn Mux = ON.
All audio/video call shall be ok.
![无标题](https://user-images.githubusercontent.com/59772309/207058276-22f600b0-fdb7-4b03-a7b1-8083ffdb9718.png)

**Comment by Recoba86** [comment]
> Turn Mux = ON. All audio/video call shall be ok. ![无标题](https://user-images.githubusercontent.com/59772309/207058276-22f600b0-fdb7-4b03-a7b1-8083ffdb9718.png)

tried it but it doesn't work
problem is still there!
WhatsApp or telegram calls goes connecting
