### ISSUE TITLE
开启“xray分流”后网络中断

### ISSUE THREAD

**Issue by francis5959** [xiaorouji/openwrt-package#2195]
### 描述您遇到的bug

使用单个节点连接都正常，但一旦开启“xray分流”网络连接就中断了。

### 复现此Bug的步骤

passwall开启“xray分流”

### 您想要实现的目的

“xray分流”不工作

### 日志信息

2022-11-18 16:13:13: 删除相关防火墙规则完成。
2022-11-18 16:13:13: 清空并关闭相关程序和缓存完成。
2022-11-18 16:13:14: UDP节点没有选择或为空，不代理UDP。
2022-11-18 16:13:14: 过滤服务配置：准备接管域名解析...
2022-11-18 16:13:14:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2022-11-18 16:13:14:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2022-11-18 16:13:14:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2022-11-18 16:13:14: 开始加载防火墙规则...
2022-11-18 16:13:14: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2022-11-18 16:13:14: 加入所有节点到ipset[vpsiplist]直连完成
2022-11-18 16:13:14: 加载路由器自身 TCP 代理...
2022-11-18 16:13:14:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2022-11-18 16:13:14:   - [0]，屏蔽代理UDP 端口：80,443
2022-11-18 16:13:14: TCP默认代理：使用TCP节点[分流总节点] [中国列表以外](REDIRECT:1041)代理所有端口
2022-11-18 16:13:14: 防火墙规则加载完成！
2022-11-18 16:13:15: 重启 dnsmasq 服务
2022-11-18 16:13:15: 运行完成！

### 截图

![OpenWrt - 基本设置 - LuCI - 10 0 0 1](https://user-images.githubusercontent.com/62682108/202655509-3f252099-2e4b-45ad-b176-6a71f6cd9a0d.png)

### 系统相关信息

Passwall: git-23.314.45059-11b78c0, 11月18日全新安装
openwrt：x86/64，分支22.03.2，内核: 5.15.77

### 其他信息

目前使用passwall 2，分流一切正常。

**Comment by smallprogram** [comment]
我这边没有这中情况，你尝试一下如下方案
1. 更新geosite与geoip
2. 重置passwall

**Comment by locoz666** [comment]
我这有同样情况，在排查后发现本质原因是 基本设置-模式-默认代理模式 设置的影响。  

这里如果设置为 GFW模式，会导致被劫持下来的DNS请求在被转发时并不会按照 规则管理-分流规则 中设定的规则去走，而是会按照不知道哪个GFW列表里的规则去走，所以就直接直连，也就是说会获取到被污染的解析结果。  

最后解决方法就是将 默认代理模式 都设置成 中国列表以外，然后就可以正常使用分流了，不知道为什么 规则列表-代理列表 里的设置不会对 默认代理模式-GFW模式生效，这块设计得很乱。  

---
另外，排查时还发现几个问题：  

1. 被劫持下来的DNS请求并不会按照 基本设置-DNS 的来，而是自己走udp去请求同样的DNS服务器。由于我这边设置的是通过DoH的方式请求DNS，所以日志中能看到非常明显的两种DNS请求，日志中表现为 app/dns 和 proxy/dns 两个模块。

2. 如果不是走 基本设置-DNS 的那套DNS请求流程，似乎还会导致其中的 缓存解析结果 设置失效，尤其是在分流设置中默认节点不稳定的情况下特别明显。正常来说在配置了多节点分流，且让特定的一些域名走一个稳定可靠节点的状态下，即使默认节点挂了也应当可以正常访问这部分域名的，但实际表现是默认节点挂了，直接在DNS解析这一步就被卡着了，全部DNS解析超时。  

3. 即使在 规则管理-分流规则 中已经设置了一个单独且最高优先级的规则（里面填入了境外DNS服务器的地址），并且设置这个规则走另一个稳定可靠的节点（而非默认节点）分流出去，但被劫持下来的DNS请求仍然会走 dns-out 出口出。  

4. 规则管理-分流规则中设置 bittorrent 协议似乎无效，设置后日志中仍然会看到大量来自qBittorrent的连接走 default 出口出去了。

**Comment by francis5959** [comment]
感谢。已正常。以前的版本是不更新那两个数据文件“xray分流”功能是不运行的

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/203009205-d153fdc0-6c86-4692-9a31-6392e711add1.png)
这是开机几分钟passwall2 内存情况 为什么进程里这么多pw2   过一会再发一个图  离死机不愿了

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/203013962-2fd01e4b-d00d-4e1a-b080-967fbd9ff6a3.png)
运行不到半小时 接近挂机了  13个线程 内存每个都占。。。什么情况？？？
![image](https://user-images.githubusercontent.com/73630536/203014119-c01e6c11-7f9e-4139-b5cb-77f4403a36b2.png)
等挂机 那我截个图

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/203014363-b1d72fd7-d592-4300-a920-0e014f48fb01.png)
![image](https://user-images.githubusercontent.com/73630536/203014395-e5401214-f532-40a6-82e1-b752af44adc1.png)
接近挂机

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/203015098-981297c8-2f6d-4a03-b112-952487259378.png)
![image](https://user-images.githubusercontent.com/73630536/203015124-9418add8-a5c4-4ce9-8d25-c5dd23ddac34.png)
我的设备就这样一次次的搞崩 我去换ssr
![image](https://user-images.githubusercontent.com/73630536/203015521-9321e4d6-563f-4253-a38d-3f4bb3998629.png)
关掉ssr内存立马恢复
![image](https://user-images.githubusercontent.com/73630536/203015641-04938dd5-331e-4b89-99c5-0c61858126b3.png)
内存前排也没有ssr的   这一版pw2的问题应该算bug吧

**Comment by yanghonghao6789** [comment]
pw2的版本是F大78+固件包的  设备是n1   
![image](https://user-images.githubusercontent.com/73630536/203016038-6a579664-be1d-4a6b-840e-f1d6ca97fd9c.png)
