### ISSUE TITLE
添加仅限代理白名单内地址的功能

### ISSUE THREAD

**Issue by cyan-river** [xiaorouji/openwrt-package#2197]
### 描述你想要的新功能

我的使用需求特殊，因为网络环境等因素，我有时候需要切到不同的节点才能“正常”访问。
所以对我来说。openwrt里的插件我希望他作为辅助使用。比如，代理github，go等仓库或是其他基础建设服务
平时访问网页时，可能会需要切到其他地区访问。所以我通常会配合别的浏览器插件使用。可是浏览器插件+passwall会导致任何网页都打不开。每次都去openwrt里改代理会很不方便。

![image](https://user-images.githubusercontent.com/46892084/202906591-79d73eab-280f-4051-9bf1-57cd18c2c69c.png)

所以，能否增加一种代理模式。只会代理白名单内域名。其他全部不代理。

### 描述你想要的解决方案

增加一种代理模式。只会代理白名单内域名。其他全部不代理。
如果已经支持了，请告诉我怎么配置。谢谢。

**Comment by locoz666** [comment]
应该是你版本太低了，其实这里是有个 仅使用直连/代理列表 模式的。

**Comment by cyan-river** [comment]
> 应该是你版本太低了，其实这里是有个 仅使用直连/代理列表 模式的。


@locoz666  @smallprogram 
我的版本号显示在web的包管理界面的是3.9-73  ，然后我尝试使用opkg更新。已是最新。openwrt 版本是OpenWrt R20.7.1
我今天尝试了最新的稳定版。发现仓库里没有passwall了，从网上找到的passwall插件包也好像是更低的版本`luci-app-passwall3.6-41all.ipk`。

所以，该咋更新到你说的新版本？

**Comment by smallprogram** [comment]
@Misaka15535 用源码编译
