### ISSUE TITLE
[Question]: 无法使用 Xray 分流

### ISSUE THREAD

**Issue by sky2016cn** [xiaorouji/openwrt-package#2199]
### 描述您遇到的bug

Lede x86 固件，OpenWrt R22.10.20

编译出来的固件，无法使用 Xray 分流

### 复现此Bug的步骤

在 /usr/share 目录中没有v2ray文件夹，没有“geoip.dat”和“geosite.dat”，导致无法使用 Xray 分流，必须手动勾选“geoip”和“geosite”规则更新后，才能使用 Xray 分流

### 您想要实现的目的

希望初始的固件无需更新规则就可以使用xray分流

### 日志信息

Lede x86 固件，OpenWrt R22.10.20

### 系统相关信息

Lede x86 固件，OpenWrt R22.10.20，luci-app-passwall 4.55-2

**Comment by smallprogram** [comment]
xray分流是必须依赖geoip与geosite的，这两个是分流的依据。所以这并不是BUG，你只是不太明白这里的逻辑。
如果你想开箱即用，请在编译时选择如下选项，其实passwall的功能都勾选了，默认就是勾选该项目，但是要注意定时更新
![image](https://user-images.githubusercontent.com/6050360/203104966-7d6583e9-29dd-4ce6-877a-9069ba5fb27a.png)

**Comment by sky2016cn** [comment]
按照您的方法，重新编译后，果然可用，但是近一个月开始编译的固件，默认是不勾选geoip与geosite的，哪怕勾选了所有的Passwall功能！

**Comment by smallprogram** [comment]
我这里默认勾选是因为我同时安装了passwall2，passwall2设计采用xray分流，不包含任何其他分流模式，所以强制依赖geoip与geosite.
而passwall是多样性分流，默认不强制依赖geoip与geosite，你如果只编译pw，默认是不会勾选geoip和geosite的，你不勾选，编译完成再去更新geo也是一样的。

我也可以改一下，之后会提交PR
