### ISSUE TITLE
[Feature Request]: TUIC协议支持请求

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-package#2202]
### 描述你想要的新功能

TUIC协议基于UDP QUIC，使用"cubic", "new_reno", "bbr"等优化网络，不会像hysteria一样多倍发包。

shadowrocket以及surge都已支持，请求开发者加入此协议，谢谢！

### 描述你想要的解决方案

TUIC protocol Github page：
https://github.com/EAimTY/tuic

**Comment by zcc0030** [comment]
同求支持，win下v2rayN可以自定义内核，安卓有sagernet，ios mac有surge，就差软路由支持了

**Comment by houpi** [comment]
同求

**Comment by hcym** [comment]
试过一次，不是一般的慢

**Comment by smallprogram** [comment]
不会整。。。。。。。。。。

**Comment by zhucaidan** [comment]
> 不会整。。。。。。。。。。
啊。。这。。。😂

**Comment by smallprogram** [comment]
你召唤一下xiaorouji、ShanStone、天灵等大佬把。我对luci也是一知半解，没系统学过。只会照葫芦画瓢，你这个需求我看了看，要改的地方应该不少，这几天实在太忙，没啥时间研究。

**Comment by ArcCal** [comment]
不是一般的慢，存在很多莫名其妙的故障

**Comment by hb-0** [comment]
支持，我的节点晚高峰用hysteria测速是很牛(接近宽带上限)，但看youtube，就是一个蛋疼，换用tuic，测速只有hysteria四分之一不到，但是看youtube非常顺畅，稳定观看4k没问题。

**Comment by looksgood3** [comment]
> 不是一般的慢，存在很多莫名其妙的故障

因为写这个协议的大佬，目前代码里使用了大量的unwrap 会有一些不稳定
应该是目前没有太多精力支持
