### ISSUE TITLE
请教Hysteria功能支持 

### ISSUE THREAD

**Issue by francis5959** [xiaorouji/openwrt-package#2204]
### 描述你想要的新功能

1、好像只能使用faketcp协议，udp、wechat-video协议连接都超时；
2、设置界面好像不支持1.3版的端口跳跃，只能填入单端口，多端口值无效

### 描述你想要的解决方案

设置界面支持端口跳跃

### 描述你考虑过的替代方案

无

### 其他信息

passwall：git-23.326.49742-f588991
openwrt：22.03.2，5.15.77

**Comment by sw19999** [comment]
1、端口跳跃还不支持。我也在等这个功能。
2、显示超时不影响使用，UDP超时一样用，混淆密码=obfs   认证密码=auth  只能填写其中一个，根据你的服务器来。就能用了。

**Comment by francis5959** [comment]
刚升级luci-app-passwall，客户端已添加多端口支持，但遗憾的是服务端还没有，我在国内架设了回国服务器。在此感谢

**Comment by Pacio** [comment]
跳跃端口不是已经有了吗？直接填写端口范围，格式xxxxx-xxxxxx
