### ISSUE TITLE
[Feature Request]: 希望能把指纹伪造（utls）功能和mux开启功能作为全局设置

### ISSUE THREAD

**Issue by yoohooyoo** [xiaorouji/openwrt-package#2208]
### 描述你想要的新功能

希望能把指纹伪造（utls）功能和mux开启功能作为全局设置。
目前即使开启，一旦更新订阅，就会丢失。
因为这两个配置不会包含在分享url中。

### 描述你想要的解决方案

把指纹伪造（utls）功能和mux开启功能作为全局设置。

**Comment by wuruiwm** [comment]
希望能够添加mux 全局设置的功能
