### ISSUE TITLE
[Bug]: 10.25号以后的4.55-2版本的passwall，开启科学后，使用SSH工具MobaXterm，所有的外网服务器不能连接

### ISSUE THREAD

**Issue by oyanli** [xiaorouji/openwrt-package#2212]
### 描述您遇到的bug

10.25号以后的4.55-2版本的passwall，开启科学后，使用SSH工具MobaXterm，所有的外网服务器不能连接

机器：
X86: 6413
AMR: R68s

暂时能找到的历史固件是10.25日编译的，此日期固件的passwall版本也是4.55-2，但是可以正常连接，后面11.01固件中同为4.55-2版本的passwall，MobaXterm就不能连接了，之后日期的也不行，看了下都是4.55-2，两款构架的机器都有这个问题，排查了下原因，还是判断应该是passwall的问题，大概是10.25-11.01号之间版本有内容更新，造成了这个情况，应该是规则问题，但是我找了一圈也没发现是什么规则造成的，还请大佬能排查一下，谢谢！！

### 复现此Bug的步骤

MobaXterm版本：

20.1-21.5都试过，都有这个问题

### 您想要实现的目的

请大佬检查下，修正这个问题，谢谢！！

### 日志信息

无

### 系统相关信息

4.55-2当前版，10.25号之前的4.55-2正常

**Comment by wtfr-dot** [comment]
你用的xray吗？xray1.6.1是正式版，以后到目前都是测试版，问题比较多，我也回退一直停在1.6.1不再更新了，也就是25号左右

**Comment by oyanli** [comment]
> 你用的xray吗？xray1.6.1是正式版，以后到目前都是测试版，问题比较多，我也回退一直停在1.6.1不再更新了，也就是25号左右

现在正常的用的版本的确是xray1.6.1的，但是后面的固件带的都是1.6.1以上的，请问怎么回退到1.6.1的核心？

**Comment by wtfr-dot** [comment]
如果是自编译的话很简单，停在某个commit就行了，如果是别人的固件就没法了，因为passwall没有发行版本，也可以试试替换xray的二进制文件
