### ISSUE TITLE
[Feature Request]: 大佬新副本开启了。通过 Cloudflare Warp 增强代理安全性

### ISSUE THREAD

**Issue by gegj** [xiaorouji/openwrt-package#2213]
### 描述你想要的新功能

相关文档：
https://github.com/XTLS/Xray-core/releases/tag/v1.6.5
https://xtls.github.io/document/level-2/warp.html

### 描述你想要的解决方案

通过 Cloudflare Warp 增强代理安全性

**Comment by laaArmy** [comment]
还不如直接屏蔽出口大陆方向的流量

**Comment by ZqinKing** [comment]
国内几乎用不了warp。你只能在vps用用warp。用来解锁一些限制。

**Comment by Pacio** [comment]
xray最近几个版本一直推荐出站设置warp，希望加入该功能

**Comment by handsomeji** [comment]
最新代碼已經可以完美使用。
