### ISSUE TITLE
[Feature Request]: 增加对hysteria 1.3.1新增的客户端fast open参数支持

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-package#2216]
### 描述你想要的新功能

文档 https://hysteria.network/zh/docs/advanced-usage/

"fast_open": false, // 启用 Fast Open (降低连接建立延迟)

Fast Open [#](https://hysteria.network/zh/docs/advanced-usage/#fast-open)
Fast Open 可以为每个连接建立的过程减少一个 RTT ，但代价是牺牲了 SOCKS5/HTTP/TUN 协议的正确语义。当开启时，客户端会始终马上接受任何连接，不会先和服务端确认是否能连通目标地址。如果随后发现服务端到目标地址连接失败，客户端也会不收发任何数据直接关闭连接。

### 描述你想要的解决方案

增加这个选择框

### 描述你考虑过的替代方案

NA

### 其他信息

NA

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/b97c09b81abc99056d5d684bae1a4cb2684e6fb9
