### ISSUE TITLE
[Bug]: 节点列表，通过链接添加节点报错！

### ISSUE THREAD

**Issue by sjkhsl** [xiaorouji/openwrt-package#2218]
### 描述您遇到的bug

在节点列表，通过链接添加节点报错！点击确定后，刷新一下页面发现节点添加进去了，但是选择节点后无法访问gfw列表以外的网站，通过添加-导入分享url就没有问题～

还有一个问题，编译时选择了dnsmasq-full，在passwall的dns设置里没有dnsmasq选项，日志中会提示
 - 以上所列以外及默认：127.0.0.1#15354
 - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！

### 复现此Bug的步骤

节点列表
通过链接添加节点

### 您想要实现的目的

解决问题

### 日志信息

添加节点没有日志信息，dns的日志如下

 - 以上所列以外及默认：127.0.0.1#15354
 - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！

### 系统相关信息

最新版passwall，昨天编译的！
Lede固件，网页服务是nginx

**Comment by sjkhsl** [comment]
追加一个问题，只要启动过一次passwall，之后添加的节点无法连接，ssr就没有问题！相同协议和配置！

**Comment by wazzx** [comment]
> 追加一个问题，只要启动过一次passwall，之后添加的节点无法连接，ssr就没有问题！相同协议和配置！

同阳的问题

**Comment by wazzx** [comment]
XRAY协议：[Xray_onekey](https://github.com/wulabing/Xray_onekey)
支持配置方式：VLESS + TCP + TLS + Nginx + WebSocket
目前Passwall更新到最新版本4.55，ssrplus也是最新版
配置图如下：passwall不能链接 ssrplus没有问题

![xray](https://user-images.githubusercontent.com/60512548/206641705-59573efd-2ce8-4485-b789-c47f6d9a72c5.png)
![ssr](https://user-images.githubusercontent.com/60512548/206641759-2f9900f7-4716-4718-bd78-a82a002620e5.png)
希望开发者看一下谢谢！
原版op21.02.3，自己编译ipk安装！
再反馈一个情况，我这边开始passwall是可以用的，我记得好像是更新了这个[issue](https://github.com/xiaorouji/openwrt-passwall/commit/5be7337f84c0ed859967f2ee07c0d2b7a94d8a65) 以后才不能链接的，开始我认为是服务器的问题没有理会，但是朋友可以。所以重新编译ssrplus就ok了
更新：是自己这边的问题！谢谢开发者
