### ISSUE TITLE
[Bug]: Socks分流节点的默认节点如果不是代理节点，则无法启动

### ISSUE THREAD

**Issue by wuyu8512** [xiaorouji/openwrt-package#2225]
### 描述您遇到的bug

Socks节点功能

### 复现此Bug的步骤

如果选择了分流节点，且默认节点不是代理节点，比如直连或者黑洞，则无法启动

### 您想要实现的目的

正常工作

### 日志信息

  - Socks节点：[TCP]，启动中止 0.0.0.0:1080 某种原因，此 Socks 服务的相关配置已失联，启动中止！

### 系统相关信息

4.55版本

### 其他信息

```
	if [ -n "$server_host" ] && [ -n "$port" ]; then
		check_host $server_host
		[ $? != 0 ] && {
			echolog "  - Socks节点：[$remarks]${server_host} 是非法的服务器地址，无法启动！"
			return 1
		}
		tmp="${server_host}:${port}"
	else
		error_msg="某种原因，此 Socks 服务的相关配置已失联，启动中止！"
	fi
```

看起来是 `if [ -n "$server_host" ] && [ -n "$port" ]; then` 的判断有误

**Comment by handsomeji** [comment]
已修复
