### ISSUE TITLE
[Feature Request]: xray-core 如何回退版本？

### ISSUE THREAD

**Issue by smdx** [xiaorouji/openwrt-package#2226]
### 描述你想要的新功能

xray-core 1.6.6 版本回撤了，想把passwall的内核回退到旧版本要怎么操作啊？谢谢

PS：希望能在pw组件更新界面增加回退功能

### 描述你想要的解决方案

希望能在组件更新界面组件版本回退功能，同版本重新安装功能（防止这种回退再发布同版本号的现象）

**Comment by smallprogram** [comment]
download 特定版本，ssh ，cover

**Comment by tycn888** [comment]
下载对应xray版本，SSH上传替换，设置执行权限，重新启用xray
