### ISSUE TITLE
[Bug]: 规则管理中无法更新/下载 geoip、geosite

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2227]
### 描述您遇到的bug

规则管理中，勾选 geoip/geosite 手动更新后，dat 文件不存在于默认 /usr/share/v2ray/ 路径下。
日志仅返回 “开始更新…”、“更新完毕…” 状态，实际并未完成下载。

其余 gfwlist、chnroute 等可正常更新。

### 复现此Bug的步骤

规则管理中，勾选 geoip/geosite 手动更新。

### 您想要实现的目的

规则管理能正常更新/下载 geoip/geosite。

### 日志信息

2022-12-13 21:59:43: 开始更新规则...
2022-12-13 21:59:43: geoip 开始更新...
2022-12-13 22:00:10: geosite 开始更新...
2022-12-13 22:00:38: 规则更新完毕...
<没下文了>

### 系统相关信息

- Passwall版本: 4.55-1
- 固件版本: ImmortalWrt 18.06-k5.4
- 浏览器版本: Chrome 108.0.5359.99 正式版

**Comment by smallprogram** [comment]
try reset passwall

**Comment by ghost** [comment]
本着分享精神，还是发下解决方法，希望帮助到别人。
问题就在于我的 op 系统是自用的极简版，passwall 缺失了依赖 v2ray-geoip 和 v2ray-geosite。
导致开启 xray 代理后，因为没有 geodata 无法正常工作，国外网站失联无法更新；
而不开启代理，规则源又因为被墙，也无法更新。
最后安装以上两个依赖，开启代理后正常更新。

**Comment by smallprogram** [comment]
> 本着分享精神，还是发下解决方法，希望帮助到别人。
> 
> 问题就在于我的 op 系统是自用的极简版，passwall 缺失了依赖 v2ray-geoip 和 v2ray-geosite。
> 
> 导致开启 xray 代理后，因为没有 geodata 无法正常工作，国外网站失联无法更新；
> 
> 而不开启代理，规则源又因为被墙，也无法更新。
> 
> 最后安装以上两个依赖，开启代理后正常更新。

路由器代理模式选择全局。然后更新geodata就可以了
