### ISSUE TITLE
[Bug]: Luci 导入xray配置链接，将flow停用错误识别为xtls-rprx-vision

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#2228]
### 描述您遇到的bug

Luci 界面导入xray配置链接，将flow停用错误识别为xtls-rprx-vision

### 复现此Bug的步骤

配置如同
![flow](https://user-images.githubusercontent.com/60512548/207508121-a927c1f9-ee71-4cdf-9a24-ef45a84118ad.png)
分享出来的链接
`vless://password@test.com:443?host=&path=%2Fa3bab3de%2F&type=ws&encryption=none&flow=xtls-rprx-vision&security=tls&sni=#%E6%B5%8B%E8%AF%95`
将链接打入Passwall
![Snipaste_2022-12-14_12-48-46](https://user-images.githubusercontent.com/60512548/207508584-f59ddd88-17f2-4fc9-aad5-66515edcb7a0.png)
而导入ShadowSocksR Plus+则没有这个问题
![ssrplus](https://user-images.githubusercontent.com/60512548/207508830-965822d9-d706-4722-b9cb-d39957b4b81a.png)

### 您想要实现的目的

解决问题！

### 日志信息

无

### 系统相关信息

Passwall版本: 4.55（最新版本Dec 8, 2022）
固件版本: openwrt 21.02.3
浏览器版本: Chrome 108.0.5359.99 正式版

**Comment by smdx** [comment]
你的分享链接不就是flow=xtls-rprx-vision?

**Comment by wazzx** [comment]
> 你的分享链接不就是flow=xtls-rprx-vision?


在细看一下，我导出来的图是第一个停用了的

**Comment by smdx** [comment]
> > 你的分享链接不就是flow=xtls-rprx-vision?
> 
> 在细看一下，我导出来的图是第一个停用了的

![Screenshot-2022-12-18_110207](https://user-images.githubusercontent.com/9279217/208279264-2b221299-4bb5-424a-8df6-25931cade2e9.jpg)

**Comment by wazzx** [comment]
> > > 你的分享链接不就是flow=xtls-rprx-vision?
> > 
> > 
> > 在细看一下，我导出来的图是第一个停用了的
> 
> ![Screenshot-2022-12-18_110207](https://user-images.githubusercontent.com/9279217/208279264-2b221299-4bb5-424a-8df6-25931cade2e9.jpg)

第一张图我的配置图片flow是停用，导出来是flow=xtls-rprx-vision，这个不是问题吗！你可以去配置一下。第二我导出来的链接
`vless://password@test.com:443?host=&path=%2Fa3bab3de%2F&type=ws&encryption=none&flow=xtls-rprx-vision&security=tls&sni=#%E6%B5%8B%E8%AF%95`
在ssr-plus可以正常使用。
所以。。
