### ISSUE TITLE
[Feature Request]: 建议增强preproxy功能

### ISSUE THREAD

**Issue by liverpool-fc** [xiaorouji/openwrt-package#2234]
### 描述你想要的新功能

作者您好，passwall的preproxy功能非常实用。但是我在使用过程中有如下需求：default节点不通过preproxy，其余部分分流节点需通过preproxy。而目前开启了default preproxy后，default节点会默认通过default preproxy。

### 描述你想要的解决方案

建议对default节点增加是否通过preproxy的选项。

### 描述你考虑过的替代方案

最好的模式是针对每个分流节点都能选择不同的preproxy，而不只是只有default、default proxy两个选项。例如，我现在有A、B、C、D、E五个节点，针对每个节点都可以选择其余四个节点作为其preproxy。

**Comment by nftbty** [comment]
> default节点不通过preproxy，其余部分分流节点需通过preproxy。而目前开启了default preproxy后，default节点会默认通过default preproxy。

> 建议对default节点增加是否通过preproxy的选项。

其实照目前这种设置，是可以做到默认不走前置，但是分流走前置的，那就是默认不开前置代理，然后需要前代的把前置代理设置成默认节点，此时默认节点承担了2个角色，一个是默认路由的出口，一个是分流规则的前置代理。在逻辑上不是很清晰，不是太合理。当然单纯只是这样的话，只会造成部分人设置的时候有困惑，不能一眼就明白怎么设置。
但其实在有些情况下，这种设置逻辑也会带来实际体验上的不便。
使用场景也是默认节点不用前置代理，某些分流规则需要。可能会出现这种情况，有些节点适合用来当默认节点。比如有很多网站需要原生IP才能正常访问，否则资源就加载不出来，或者像Google，用有些节点来搜索，就没问题，换别的节点，就会每次搜东西都要弹个验证，有时候点一次还过不了，烦得很。我自己的话，还有一个情况，我只用google的主域名，`.hk`看着别扭，强迫症受不了，所以`.hk`的我都会加ncr，不过很多时候是用隐私模式，不能每次都先ncr，所以我会直接用不跳转hk的，不用验证的节点。但可能这个节点作前置代理不太行，不如其他某个节点，甚至我用的机场几十个节点只有几个可以用来作为前置，不知道是不是机场限制了对某些VPS IP的访问。像这些情况，默认节点和前置代理节点这两个角色真的需要分开。
所以我目前这个draft状态的PR #2402，最开始想搞的分流使用负载均衡节点早就搞完了，但都是一个分流模式里的东西，还想继续优化，不得不考虑这个前置代理的问题。刚好看到你这个issue，和我有部分想法是相同的。所以对于把前置代理设置分离，逻辑上不再和和默认节点绑定，默认节点和其他规则一样，添加独立开关，这一块的思路我是确定了。

我想，如果可能的话，是不是一起在讨论贴里面讨论一下，提提各自具体的使用需求，场景，给出一些建议，综合考虑，看怎样实现可以尽量满足各种不同使用场景下的不同需求。这比自己一个人琢磨强多了，也能更快解决问题。

**Comment by gito10** [comment]
@smallprogram 这个应该可以关了吧，前置代理和默认节点完全独立开了，需求也就完成了。下面那个替代方案就不用考虑了，一个是复杂，会搞成链式代理，闭环，而且并不是所有节点都可以用作前置代理，目前这样就是差不多了。最多之后把配置界面优化下，把下拉列表改成CheckBox。
