### ISSUE TITLE
[Feature Request]: 希望推出定时自动切换节点功能

### ISSUE THREAD

**Issue by qwejerrywolf** [xiaorouji/openwrt-package#2237]
### 描述你想要的新功能

由于不同机场在不同时段的表现情况可能不同，希望passwall能推出一个定时自动切换节点的功能

### 描述你想要的解决方案

例如a机场的节点在白天表现很好但是晚高峰表现不佳，而b机场速度平时限速但晚高峰表现稳定，那么可以设置在每天零点到晚上六点使用a机场的节点，而晚上六点到次日零点使用b机场的节点

**Comment by Mr-xn** [comment]
可以看看我的文章 https://mrxn.net/Linux/how-to-auto-change-openwrt-passwall-default-nodes-with-crontab.html
