### ISSUE TITLE
[Bug]: Nat FullCone 未生效

### ISSUE THREAD

**Issue by mikexfreeze** [xiaorouji/openwrt-package#2239]
### 描述您遇到的bug

使用支持 udp 的节点但 Nat 类型仍为 Symmetric
节点肯定没有问题，使用 Netch 测试过。

### 复现此Bug的步骤

设置如下：
![image](https://user-images.githubusercontent.com/16068816/210252264-16b77998-d180-43b0-a9b4-77355c3f0d07.png)
![image](https://user-images.githubusercontent.com/16068816/210252308-39680693-e61c-4d34-b8d9-012628e9a111.png)
![image](https://user-images.githubusercontent.com/16068816/210252355-c162ad42-455b-4479-9a61-081e93f248b9.png)

### 您想要实现的目的

/

### 日志信息

**udp 节点日志：**

Xray 1.7.0 (Xray, Penetrates Everything.) OpenWrt (go1.19.4 linux/arm64)
A unified platform for anti-censorship.
2023/01/02 23:24:53 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/UDP.json
2023/01/02 23:24:53 [Info] transport/internet/udp: listening UDP on 0.0.0.0:1051
2023/01/02 23:24:53 [Warning] core: Xray 1.7.0 started
2023/01/02 23:25:10 [Info] [3037749492] proxy/dokodemo: received request for 192.168.31.3:34394
2023/01/02 23:25:10 [Info] [459542214] proxy/dokodemo: received request for 192.168.31.3:37457
2023/01/02 23:25:10 [Info] [459542214] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:10 192.168.31.3:37457 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:10 192.168.31.3:34394 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:10 [Info] [459542214] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:10 [Info] [3037749492] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:10 [Info] [3037749492] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:10 [Info] [3037749492] proxy/vless/outbound: tunneling request to udp:1.1.1.1:53 via hk.duandiwang.com:50246
2023/01/02 23:25:10 [Info] [459542214] proxy/vless/outbound: tunneling request to udp:1.1.1.1:53 via hk.duandiwang.com:50246
2023/01/02 23:25:13 [Info] [1384255932] proxy/dokodemo: received request for 192.168.31.3:34815
2023/01/02 23:25:13 [Info] [1920529145] proxy/dokodemo: received request for 192.168.31.3:38411
2023/01/02 23:25:13 [Info] [1920529145] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:13 [Info] [1920529145] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:13 [Info] [1384255932] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:13 192.168.31.3:38411 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:13 192.168.31.3:34815 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:13 [Info] [1384255932] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:13 [Info] [1920529145] proxy/vless/outbound: tunneling request to udp:1.1.1.1:53 via hk.duandiwang.com:50246
2023/01/02 23:25:13 [Info] [1384255932] proxy/vless/outbound: tunneling request to udp:1.1.1.1:53 via hk.duandiwang.com:50246
2023/01/02 23:25:16 [Info] [640274523] proxy/dokodemo: received request for 192.168.31.3:44894
2023/01/02 23:25:16 [Info] [640274523] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:16 [Info] [640274523] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:16 192.168.31.3:44894 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 [Info] [1750331412] proxy/dokodemo: received request for 192.168.31.3:56480
2023/01/02 23:25:16 [Info] [1750331412] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:16 192.168.31.3:56480 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 [Info] [1750331412] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:16 [Info] [1470983623] proxy/dokodemo: received request for 192.168.31.3:48029
2023/01/02 23:25:16 [Info] [97246792] proxy/dokodemo: received request for 192.168.31.3:42670
2023/01/02 23:25:16 [Info] [1470983623] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:16 192.168.31.3:48029 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 [Info] [97246792] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:16 192.168.31.3:42670 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 [Info] [1470983623] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:16 [Info] [97246792] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246
2023/01/02 23:25:16 [Info] [342515452] proxy/dokodemo: received request for 192.168.31.3:44795
2023/01/02 23:25:16 [Info] [2913563753] proxy/dokodemo: received request for 192.168.31.3:53891
2023/01/02 23:25:16 [Info] [2913563753] app/dispatcher: default route for udp:1.1.1.1:53
2023/01/02 23:25:16 192.168.31.3:53891 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 192.168.31.3:44795 accepted udp:1.1.1.1:53 [udp_redir >> f4c9d347a83e4ec69eb3aa7793662c64]
2023/01/02 23:25:16 [Info] [2913563753] transport/internet/tcp: dialing TCP to tcp:hk.duandiwang.com:50246

### 系统相关信息

PassWall 版本：luci-app-passwall 4.55-2

**Comment by kumitom** [comment]
我用的版本有个问题是，访问控制里如果自定义节点，NAT=F，用默认节点，NAT=A，即使是同一个节点。
不过我好久没更新版本了，和你可能不是一个问题？访问控制里是否自定义节点，从设置上看区别只有DNS过滤模式（默认里设置的模式在访问控制里没有），不知道是不是这个有影响
