### ISSUE TITLE
[Feature Request]: 小细节是否考虑优化

### ISSUE THREAD

**Issue by hplee0120** [xiaorouji/openwrt-package#2257]
### 描述你想要的新功能

不编译负载均衡时主页状态小卡片还是有负载均衡，还有不编译chinadns-ng时，那个规则列表里的中国域名列表应该也是用不到的吧？

### 描述你想要的解决方案

0

**Comment by malong19890218** [comment]
@xiaorouji 肉鸡大佬，这个还考虑优化一下吗

**Comment by handsomeji** [comment]
`不编译负载均衡时主页状态小卡片还是有负载均衡`
如果把这个小卡片去掉的话，那感觉就缺少了个东西，感觉看不上去不美观了。（我不是很会CSS布局）
`还有不编译chinadns-ng时，那个规则列表里的中国域名列表应该也是用不到的吧？`
现在会用到。

**Comment by hplee0120** [comment]
> `不编译负载均衡时主页状态小卡片还是有负载均衡`
> 如果把这个小卡片去掉的话，那感觉就缺少了个东西，感觉看不上去不美观了。（我不是很会CSS布局）

考虑到对称的话去掉一个的确不太美观，但是是否可以考虑做下减法，比如github和ins连接性，这两个应该没啥意义吧，一般只需要检测百度（国内）和谷歌（国外）就可以了。去掉这两个的话3+3双排还是看空间应该也不太好看，不过似乎可以考虑将6个整成一排？或者如果可行的话可以再增减一个负载均衡。在5-6个之间自适应排列为一行？另外反正其他组件现在也有组件更新了，负载均衡这个软件包也可以添加到组件更新里
