### ISSUE TITLE
[Bug]: 流量嗅探只供路由使用 (Xray) 干扰ssl证书

### ISSUE THREAD

**Issue by xiaotan8** [xiaorouji/openwrt-package#2258]
### 描述您遇到的bug

“流量嗅探只供路由使用 (Xray) ”开启后所有采用xray内核的节点的分流无法访问Google系网站，提示ssl证书错误，手动切换到Vray内核及分流能正常访问。

### 复现此Bug的步骤

![IMG_20230126_011740](https://user-images.githubusercontent.com/62252056/214634964-c195cb24-b8e4-4975-a419-21f97f1b4d83.jpg)
![IMG_20230126_011834](https://user-images.githubusercontent.com/62252056/214635061-78d8c58a-a631-4569-bb3a-5942b1a6be74.jpg)

### 您想要实现的目的

希望修复。

### 日志信息

日志无异常

### 系统相关信息

今天编译的最新版

**Comment by SakuraFallingMad** [comment]
与流量嗅探无关，这边可以复现出xray分流，哪怕分流节点使用ssr也是这样。
![图片](https://user-images.githubusercontent.com/31793080/214982131-10758d0a-478f-4499-81ca-86a5010359b2.png)
应该是节点问题，换了几个就无法复现了.

**Comment by xiaotan8** [comment]
可能是吧，用https://github.com/mack-a/v2ray-agent 搭建的节点全部出现这个问题。但回过来回滚passwall至元旦的版本同样的节点均无这个问题。到底是那个环节的问题呢。当然不开启此选项也不影响使用。

**Comment by xiaotan8** [comment]
> 与流量嗅探无关，这边可以复现出xray分流，哪怕分流节点使用ssr也是这样。 ![图片](https://user-images.githubusercontent.com/31793080/214982131-10758d0a-478f-4499-81ca-86a5010359b2.png) 应该是节点问题，换了几个就无法复现了.

和SmartDNS有关。

**Comment by shinpei710** [comment]
我在使用passwall 4.55-1回国的时候也遇到了这个问题。
节点是自己在腾讯云上建的，没记错的话应该也是xray内核
不过我本来就没开启只供路由使用的选项
于是索性关掉了流量嗅探（反正也用不上分流
顺利解决了
猜想应该passwall与xray内核在流量嗅探功能上交互的bug

**Comment by xlbljz** [comment]
我在使用passwall 4.55-1回国的时候也遇到了这个问题。
节点是自己在腾讯云上建的，没记错的话应该也是xray内核
不过我本来就没开启只供路由使用的选项
于是索性关掉了流量嗅探（反正也用不上分流
顺利解决了
猜想应该passwall与xray内核在流量嗅探功能上交互的bug

**Comment by ZhiboWong** [comment]
> > 与流量嗅探无关，这边可以复现出xray分流，哪怕分流节点使用ssr也是这样。 ![图片](https://user-images.githubusercontent.com/31793080/214982131-10758d0a-478f-4499-81ca-86a5010359b2.png) 应该是节点问题，换了几个就无法复现了.
> 
> 和SmartDNS有关。

我搭配用了MosDNS，是不是也有关系呢？
