### ISSUE TITLE
[Bug]: nftables restart passwall 有很多add element inet fw4报No such file or directory

### ISSUE THREAD

**Issue by jinhill** [xiaorouji/openwrt-package#2259]
### 描述您遇到的bug

执行/etc/init.d/passwall restart会出现很多添加nftset错误

### 复现此Bug的步骤

执行/etc/init.d/passwall restart

### 您想要实现的目的

fix this bug, Tks!

### 日志信息

root@SideRouter:~# /etc/init.d/passwall restart
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
/tmp/etc/passwall_tmp/nftset/chnroute:1:20-29: Error: interval overlaps with an existing one
define chnroute = {1.0.1.0/24, 1.0.2.0/23, 1.0.32.0/19, 1.0.8.0/21, 1.1.0.0/24, 1.1.10.0/23, 1.1.12.0/22, 1.1.16.0/20, 1.1.2.0/23, 1.1.32.0/19, 1.1.4.0/22, 1.1.8.0/24, 1.1.9.0/24, 1.10.0.0/21, 1.10.11.0/24, 1.10.12.0/22, 1.10.16.0/20, 1.10.32.0/19, 1.10.64.0/18, 1.10.8.0/23, 1.116.0.0/15, 1.118.0.0/16, 1.118.0.0/23, 1.118.2.0/24, 1.118.32.0/24, 1.119.0.0/17, 1.119.128.0/17, 1.119.128.0/18, 1.119.192.0/21, 1.119.200.0/22, 1.119.204.0/24, 1.12.0.0/14, 1.180.0.0/14, 1.184.0.0/15, 1.188.0.0/14, 1.192.0.0/13, 1.2.0.0/23, 1.2.10.0/23, 1.2.12.0/22, 1.2.16.0/20, 1.2.2.0/24, 1.2.32.0/19, 1.2.4.0/24, 1.2.5.0/24, 1.2.6.0/23, 1.2.64.0/18, 1.2.8.0/24, 1.2.9.0/24, 1.201.184.0/22, 1.201.188.0/23, 1.202.0.0/15, 1.204.0.0/14, 1.24.0.0/13, 1.3.0.0/16, 1.4.1.0/24, 1.4.16.0/20, 1.4.2.0/23, 1.4.32.0/19, 1.4.4.0/24, 1.4.5.0/24, 1.4.6.0/23, 1.4.64.0/18, 1.4.8.0/21, 1.45.0.0/16, 1.48.0.0/14, 1.48.0.0/15, 1.50.0.0/16, 1.51.0.0/16, 1.56.0.0/13, 1.68.0.0/14, 1.8.0.0/16, 1.8.1.0/24, 1.8.8.0/24, 1.80.0.0/13, 1.88.0.0/14, 1.92.0.0/15, 1.
                   
/tmp/etc/passwall_tmp/nftset/chnroute:3:1-40: Error: Could not process rule: File exists
add element inet fw4 chnroute $chnroute

/tmp/etc/passwall_tmp/nftset/blacklist:1:154-160: Error: interval overlaps with an existing one
define blacklist = {149.154.160.0/20, 91.108.4.0/22, 91.108.56.0/24, 109.239.140.0/24, 67.198.55.0/24, 8.8.4.4, 8.8.8.8, 208.67.222.222, 208.67.220.220, 1.1.1.1, 1.1.1.2, 1.0.0.1, 9.9.9.9, 149.112.112.112,}
                                                                                                                                                         
/tmp/etc/passwall_tmp/nftset/blacklist:3:1-42: Error: Could not process rule: File exists
add element inet fw4 blacklist $blacklist

Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
/tmp/etc/passwall_tmp/nftset/chnroute6:1:21-38: Error: interval overlaps with an existing one
define chnroute6 = {2001:250:2000::/35, 2001:250:4000::/34, 2001:250:8000::/33, 2001:250::/30, 2001:250::/35, 2001:251::/32, 2001:252::/32, 2001:253::/32, 2001:254::/32, 2001:255::/32, 2001:256:100::/48, 2001:256::/32, 2001:4438::/32, 2001:4510::/29, 2001:678:d3c::/48, 2001:67c:aec::/48, 2001:7fa:10::/48, 2001:7fa:5::/48, 2001:c68::/32, 2001:cc0::/32, 2001:da8::/32, 2001:da9::/32, 2001:daa::/32, 2001:dc7::/32, 2001:dd8:1::/48, 2001:dd8:1a::/48, 2001:dd8:5::/48, 2001:dd9::/48, 2001:df0:1bc0::/48, 2001:df0:2180::/48, 2001:df0:25c0::/48, 2001:df0:26c0::/48, 2001:df0:27e::/48, 2001:df0:2d80::/48, 2001:df0:2e00::/48, 2001:df0:2e80::/48, 2001:df0:423::/48, 2001:df0:59c0::/48, 2001:df0:85c0::/48, 2001:df0:8d40::/48, 2001:df0:9c0::/48, 2001:df0:9d40::/48, 2001:df0:ac40::/48, 2001:df0:b180::/48, 2001:df0:bf80::/48, 2001:df0:d880::/48, 2001:df0:f8c0::/48, 2001:df1:2b40::/48, 2001:df1:4580::/48, 2001:df1:5280::/48, 2001:df1:5b80::/48, 2001:df1:5fc0::/48, 2001:df1:6180::/48, 2001:df1:61c0::/48, 2001:df1:6b80::/48, 2001:
                    
/tmp/etc/passwall_tmp/nftset/chnroute6:3:1-42: Error: Could not process rule: File exists
add element inet fw4 chnroute6 $chnroute6

/tmp/etc/passwall_tmp/nftset/blacklist6:1:41-58: Error: interval overlaps with an existing one
define blacklist6 = {2001:67c:4e8::/48, 2001:b28:f23c::/48, 2001:b28:f23d::/48, 2001:b28:f23f::/48, 2001:b28:f242::/48,}
                                        
/tmp/etc/passwall_tmp/nftset/blacklist6:3:1-44: Error: Could not process rule: File exists
add element inet fw4 blacklist6 $blacklist6

Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Assertion failed: nmemb != 0 (utils.c: xmalloc_array: 45)
Aborted
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add element inet fw4 shuntlist { 103.10.124.0/24 }
                     
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add element inet fw4 shuntlist { 103.10.125.0/24 }
 
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add element inet fw4 shuntlist { 155.133.238.0/24 }
                     
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add element inet fw4 shuntlist { 155.133.239.0/24 }
                     
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?

add element inet fw4 shuntlist { 180.76.76.76/32 }
                     
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add element inet fw4 shuntlist { 114.114.114.114/32 }
                     
Error: No such file or directory; did you mean set ‘blacklist6’ in table inet ‘fw4’?
add element inet fw4 shuntlist6 { 2001:67c:4e8::/48 }
                                         
Error: No such file or directory; did you mean set ‘blacklist6’ in table inet ‘fw4’?
add element inet fw4 shuntlist6 { 2606:4700:4700::1111 }
                     
Error: No such file or directory; did you mean set ‘blacklist6’ in table inet ‘fw4’?
add element inet fw4 shuntlist6 { 2606:4700:4700::1001 }
                     
Error: interval overlaps with an existing one
add element inet fw4 laniplist { 192.168.1.2/24, }
                                 
Error: Could not process rule: File exists
add element inet fw4 laniplist { 192.168.1.2/24, }

Error: interval overlaps with an existing one
add element inet fw4 laniplist6 { fe80::20c:29ff:fe82:8825/64, }
                                  
Error: Could not process rule: File exists
add element inet fw4 laniplist6 { fe80::20c:29ff:fe82:8825/64, }

Error: No such file or directory; did you mean set ‘laniplist’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE ip daddr @vpsiplist counter return
                                      
Error: No such file or directory; did you mean set ‘blacklist’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE ip daddr @blocklist counter drop
                                      
Error: No such file or directory; did you mean set ‘laniplist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE ip daddr @vpsiplist counter return
                                             
Error: No such file or directory; did you mean set ‘blacklist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE ip daddr @blocklist counter drop
                                             
Error: No such file or directory; did you mean set ‘laniplist’ in table inet ‘fw4’?
add rule inet fw4 PSW ip daddr @vpsiplist counter return
                               
Error: No such file or directory; did you mean set ‘blacklist’ in table inet ‘fw4’?
add rule inet fw4 PSW ip daddr @blocklist counter drop
                               
Error: No such file or directory; did you mean set ‘laniplist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT ip daddr @vpsiplist counter return
                                      
Error: No such file or directory; did you mean set ‘blacklist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT ip daddr @blocklist counter drop
                                      
Error: No such file or directory; did you mean set ‘laniplist6’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE_V6 ip6 daddr @vpsiplist6 counter return
                                          
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE_V6 ip6 daddr @whitelist6 counter return
                                          
Error: No such file or directory; did you mean set ‘blacklist6’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE_V6 ip6 daddr @blocklist6 counter drop
                                          
Error: No such file or directory; did you mean set ‘laniplist6’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE_V6 ip6 daddr @vpsiplist6 counter return
                                                 
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE_V6 ip6 daddr @whitelist6 counter return
                                                 
Error: No such file or directory; did you mean set ‘blacklist6’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE_V6 ip6 daddr @blocklist6 counter drop
                                                 
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT ip protocol tcp tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @shuntlist counter counter redirect to :1041
                                                                                                          
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE ip protocol udp ip daddr @shuntlist udp dport {80,443} counter drop
                                                             
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_OUTPUT_MANGLE ip protocol udp ip daddr @shuntlist  counter jump PSW_RULE
                                                             
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW ip protocol tcp tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @shuntlist counter redirect to :1041 comment "默认"
                                                                                                   
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE udp dport {80,443} ip daddr @shuntlist counter drop comment "默认"
                                                         
Error: No such file or directory; did you mean set ‘whitelist’ in table inet ‘fw4’?
add rule inet fw4 PSW_MANGLE ip protocol udp  ip daddr @shuntlist counter jump PSW_RULE comment "默认"

### 系统相关信息

passwall:4.56
openwrt:22.03.3
dnsmasq-full v2.88
platform:x86/64

**Comment by wazzx** [comment]
hi！你好，这个问题我也很久就发现了，有反馈，目前主要问题是dnsmasq: v2.86不完全支持[dnsmasq: Support nftables nftsets](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d7f378796f985c902ff7906767c275c40a15347f)，要到2.88才能完全支持，所以目前22.03是一个很尴尬的稳定版，我推断方法可以把SDK的dnsmasq修改到v2.88的编译文件，我直接下载好编译文件编译dnsmasq-full 2.88版本，但是我失败了。所以如果你找到方法可以告诉我一下，谢谢！还有有人看到了知道方法也可以分享一下！谢谢

**Comment by jinhill** [comment]
@wazzx 我当前版本就是dnsmasq-full 2.88
从snapshots分支下载编译好的版本安装就可以，目前基本功能可以使用，我没细测，可能部分用到nftset的功能不正常
wget https://downloads.openwrt.org/snapshots/packages/x86_64/base/dnsmasq-full_2.88-2_x86_64.ipk
wget https://downloads.openwrt.org/snapshots/packages/x86_64/base/libubox20220927_2022-09-27-ea560134-1_x86_64.ipk
opkg install libubox20220927_2022-09-27-ea560134-1_x86_64.ipk dnsmasq-full_2.88-2_x86_64.ipk

**Comment by wazzx** [comment]
> @wazzx 我当前版本就是dnsmasq-full 2.88 从snapshots分支下载编译好的版本安装就可以，目前基本功能可以使用，我没细测，可能部分用到nftset的功能不正常 wget https://downloads.openwrt.org/snapshots/packages/x86_64/base/dnsmasq-full_2.88-2_x86_64.ipk wget https://downloads.openwrt.org/snapshots/packages/x86_64/base/libubox20220927_2022-09-27-ea560134-1_x86_64.ipk opkg install libubox20220927_2022-09-27-ea560134-1_x86_64.ipk dnsmasq-full_2.88-2_x86_64.ipk

要不重新sdk编译一下。看一下情况。

**Comment by uingei** [comment]
@jinhill 报错解决了吗？我在openwrt-22.03分支上git checkout master package/network/services/dnsmasq跟你一样的报错，有什么解决办法提供下
