### ISSUE TITLE
[Bug]: 添加 SS obfs-local节点后 无发正常访问网络

### ISSUE THREAD

**Issue by KleinerSource** [xiaorouji/openwrt-package#2260]
### 描述您遇到的bug

添加 SS obfs-local节点后 无发正常访问网络
节点是正常可以访问的 在pc和手机客户端软件均可正常访问网络

### 复现此Bug的步骤

无论是导入 链接 还是手动编辑 均无法正常访问网络
 可用性测试 是正常的 

### 您想要实现的目的

不知道是什么bug 日志也看不出异常

### 日志信息

节点日志
2023-01-28 18:28:00 INFO: plugin "obfs-local" enabled
2023-01-28 18:28:00 INFO: initializing ciphers... aes-128-gcm
2023-01-28 18:28:00 INFO: listening at 0.0.0.0:1041
2023-01-28 18:28:00 INFO: tcp port reuse enabled
2023-01-28 18:28:00 INFO: running from root user
2023-01-28 18:28:00 [simple-obfs] INFO: obfuscating enabled
2023-01-28 18:28:00 [simple-obfs] INFO: obfuscation http method: GET
2023-01-28 18:28:00 [simple-obfs] INFO: obfuscating hostname: 4e60fcb01391.microsoft.com
2023-01-28 18:28:00 [simple-obfs] INFO: tcp port reuse enabled
2023-01-28 18:28:00 [simple-obfs] INFO: listening at 127.0.0.1:60761
2023-01-28 18:28:00 [simple-obfs] INFO: running from root user
2023-01-28 18:28:00 INFO: redir to 149.154.167.220:443, len=517, recv=517
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=40, recv=40
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=41, recv=41
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=45, recv=45
2023-01-28 18:28:01 INFO: redir to 149.154.167.220:443, len=80, recv=80
2023-01-28 18:28:01 INFO: redir to 149.154.167.220:443, len=409, recv=409
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=40, recv=40
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=45, recv=45
2023-01-28 18:28:01 INFO: redir to 1.1.1.1:53, len=41, recv=41

系统日志
Sat Jan 28 18:23:01 2023 kern.info kernel: [429641.465077] traps: ss-redir[29973] general protection fault ip:7f53301deea3 sp:7ffd80843db8 error:0 in libc.so[7f53301a0000+4b000]
Sat Jan 28 18:23:15 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 31361)
Sat Jan 28 18:23:33 2023 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sat Jan 28 18:23:45 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 31671)
Sat Jan 28 18:23:55 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 3 (new pid: 32056)
Sat Jan 28 18:23:58 2023 kern.info kernel: [429698.405212] traps: ss-redir[32374] general protection fault ip:7f836fddeea3 sp:7ffc03876828 error:0 in libc.so[7f836fda0000+4b000]
Sat Jan 28 18:24:03 2023 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Sat Jan 28 18:24:03 2023 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sat Jan 28 18:24:06 2023 cron.info crond[478]: crond (busybox 1.35.0) started, log level 8
Sat Jan 28 18:24:08 2023 cron.info crond[2106]: crond (busybox 1.35.0) started, log level 8
Sat Jan 28 18:24:08 2023 kern.info kernel: [429708.429033] traps: ss-redir[844] general protection fault ip:7fa328eeaea3 sp:7fffb6781288 error:0 in libc.so[7fa328eac000+4b000]
Sat Jan 28 18:24:14 2023 daemon.info uwsgi-luci: cat: can't open '/tmp/opkg.err': No such file or directory
Sat Jan 28 18:24:14 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 2285)
Sat Jan 28 18:24:18 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 2301)
Sat Jan 28 18:24:58 2023 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Sat Jan 28 18:24:59 2023 daemon.info uwsgi-luci: netstat: showing only processes with your user ID
Sat Jan 28 18:25:07 2023 kern.info kernel: [429767.084680] traps: ss-redir[2840] general protection fault ip:7f81b4aa9747 sp:7ffc00289c58 error:0 in libc.so[7f81b4a98000+4b000]
Sat Jan 28 18:25:31 2023 daemon.info uwsgi-luci: Sat Jan 28 18:25:31 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Sat Jan 28 18:25:31 2023 daemon.info uwsgi-luci: Sat Jan 28 18:25:31 2023 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /cgi-bin/luci/admin/services/passwall/ip?1674901493122 (10.0.0.50)
Sat Jan 28 18:25:38 2023 daemon.info uwsgi-luci: uWSGI worker 3 cheaped.
Sat Jan 28 18:25:44 2023 daemon.info uwsgi-luci: cat: can't open '/tmp/opkg.err': No such file or directory
Sat Jan 28 18:25:45 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 3271)
Sat Jan 28 18:25:51 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 3 (new pid: 3338)
Sat Jan 28 18:26:04 2023 kern.info kernel: [429824.414675] traps: ss-redir[3454] general protection fault ip:7f2e5083eea3 sp:7ffd43b0fb58 error:0 in libc.so[7f2e50800000+4b000]
Sat Jan 28 18:26:31 2023 kern.info kernel: [429851.748310] traps: ss-local[4561] general protection fault ip:7f30fbf1aea3 sp:7ffd32a25e58 error:0 in libc.so[7f30fbedc000+4b000]
Sat Jan 28 18:26:33 2023 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sat Jan 28 18:26:38 2023 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Sat Jan 28 18:26:45 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 4774)
Sat Jan 28 18:27:02 2023 kern.info kernel: [429882.390510] traps: ss-redir[4931] general protection fault ip:7f740ce3eea3 sp:7ffe3ac48858 error:0 in libc.so[7f740ce00000+4b000]
Sat Jan 28 18:27:08 2023 daemon.info uwsgi-luci: uWSGI worker 3 cheaped.
Sat Jan 28 18:27:14 2023 daemon.info uwsgi-luci: cat: can't open '/tmp/opkg.err': No such file or directory
Sat Jan 28 18:27:15 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 5099)
Sat Jan 28 18:27:33 2023 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Sat Jan 28 18:27:45 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 5226)
Sat Jan 28 18:28:01 2023 kern.info kernel: [429941.185985] traps: ss-redir[5379] general protection fault ip:7f57a2bf9ea3 sp:7ffd0ef75508 error:0 in libc.so[7f57a2bbb000+4b000]
Sat Jan 28 18:28:03 2023 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sat Jan 28 18:28:15 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 5575)
Sat Jan 28 18:28:30 2023 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.

### 截图

![image](https://user-images.githubusercontent.com/920875/215261629-9b4f63e2-253f-47f5-8d84-6c4d06c77f7e.png)

### 系统相关信息

passwall版本 git-24.021.55995-d924631

**Comment by handsomeji** [comment]
可用性测试能连通吗？如果能的话可能是固件问题

**Comment by solarflows** [comment]
貌似这个问题很久了原因是ss-local的配置生成有问题（我没有具体的解决办法），具体表现为纯ss的节点+某些算法+obfs无法开启socks5代理（开起来telegram可以用，但是以外的软件都不连通）

**Comment by handsomeji** [comment]
测试正常，请检查是否固件问题
