### ISSUE TITLE
[Feature Request]: 建议增加生成smartdns的域名规则文件的选项

### ISSUE THREAD

**Issue by wtfr-dot** [xiaorouji/openwrt-package#2261]
### 描述你想要的新功能

早前的版本有配合smartdns分流的选项，这个功能很好用，现在取消了，虽然使用上也没有什么问题，但由此带来一个潜在隐私泄露风险：之前有针对smartdns的域名规则文件作为smartdns的附加文件，smartdns会根据此文件进行分流解析，这样即使passwall因故停止运行（几率很小，但还是有），dns解析也会因分流规则而照常分流发出解析请求，只是海外的dns解析会失败，但是新版取消域名规则文件后，passwall这边停止后，由于smartdns那边默认没有分流规则，则会向默认的dns查询，造成dns查询泄露或被劫持，如果smartdns这边也建立一份域名规则表来避免这个现象，那么一是工作量大，二是跟passwall不同步，在正常工作时会造成干扰，最好的办法是将passwall这边的分流规则生成smartdns能识别的规则文件，由smartdns那边调用（smartdns新版刚好有自己添加配置文件的功能）

### 描述你想要的解决方案

规则管理页面增加一个转换smartdns规则文件的选项，然后定义一个保存位置，当passwall更新或操作规则文件后自动更新，此文件由使用者自己决定是否由smartdns使用，这样也不改变现有的任何结构，相当于帮smartdns创建一个规则文件保持与passwall同步

**Comment by haoges** [comment]
最新版的passwall配合smartdns，要怎么设置，小白不会弄，大佬出个教程

**Comment by wtfr-dot** [comment]
设置没什么大的变化
pass wall这边
![QQ截图20230203101634](https://user-images.githubusercontent.com/81218740/216496688-b2f573ab-3eef-43f1-b829-189b76a2c695.jpg)
smartdns这边
![QQ截图20230203101706](https://user-images.githubusercontent.com/81218740/216496757-a00f9ead-c43a-4dbf-b4cd-26013ad3a5ea.jpg)
passwall_proxy组成员的设置
![QQ截图20230203101721](https://user-images.githubusercontent.com/81218740/216496775-af0cc3ff-baff-41f3-ba72-803b24459eae.jpg)

**Comment by handsomeji** [comment]
等待SmartDNS出41版我会重新加入分流选项

**Comment by handsomeji** [comment]
可以先尝鲜一下 [luci-smartdns-new-version](https://github.com/xiaorouji/openwrt-passwall/tree/luci-smartdns-new-version) 分支，注意smartdns版本要最新的 [Release 41 RC1](https://github.com/pymumu/smartdns/releases/tag/Release41-RC1)

**Comment by wtfr-dot** [comment]
感谢！已经用上了，感觉不错！
