### ISSUE TITLE
拉取最新源码后编译Xray-core时报错

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#2263]
### 描述您遇到的bug

拉取最新源码后编译Xray-core报错

### 复现此Bug的步骤

拉取编译

### 您想要实现的目的

成功编译

### 日志信息

CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/x86.5.4/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/x86.5.4/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3" GO_BUILD_DIR="/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3/.go_work/build" GO_BUILD_BIN_DIR="/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/x86.5.4/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3=Xray-core-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3=Xray-core-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3/.go_work/build" GOCACHE="/home/x86.5.4/lede/tmp/go-build" GOMODCACHE="/home/x86.5.4/lede/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/x86.5.4/lede/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1675338619' -linkmode external -extldflags '-L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X github.com/xtls/xray-core/core.build=OpenWrt -X github.com/xtls/xray-core/core.version=1.7.3 -buildid '1675338619' -linkmode external -extldflags '-L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/x86.5.4/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets
../../../../../dl/go-mod-cache/github.com/quic-go/qtls-go1-20@v0.1.0/handshake_client.go:11:2: package crypto/ecdh is not in GOROOT (/home/x86.5.4/lede/staging_dir/hostpkg/lib/go-cross/src/crypto/ecdh)

make[3]: *** [Makefile:90: /home/x86.5.4/lede/build_dir/target-x86_64_musl/Xray-core-1.7.3/.built] Error 1
make[3]: Leaving directory '/home/x86.5.4/lede/feeds/passwall_packages/xray-core'
time: package/feeds/passwall_packages/xray-core/compile#1.03#6.26#6.83
    ERROR: package/feeds/passwall_packages/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall_packages/xray-core/compile] Error 1
make[2]: Leaving directory '/home/x86.5.4/lede'
make[1]: *** [package/Makefile:110: /home/x86.5.4/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.5.4/lede'
make: *** [/home/x86.5.4/lede/include/toplevel.mk:231: world] Error 2

### 系统相关信息

最新版本

**Comment by asiaon123** [comment]
应该是需要升级GO版本到1.20

**Comment by Beginner-Go** [comment]
(because)[https://github.com/XTLS/Xray-core/releases#:~:text=%E8%AF%A5%E7%89%88%E6%9C%AC%EF%BC%88Xray%2Dcore%20v1.7.3%EF%BC%89%E7%9A%84%E7%BC%96%E8%AF%91%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%20Go%201.20%2B]

**Comment by Beginner-Go** [comment]
[because](https://github.com/XTLS/Xray-core/releases/tag/v1.7.3)

**Comment by bi4tms** [comment]
> [because](https://github.com/XTLS/Xray-core/releases/tag/v1.7.3)

已将go升级至1.20，运行仍然报同样的错误

**Comment by kentooo** [comment]
> 

lean代码库和openwrt-22.03 代码库还没有将feeds源中golang的版本更新到1.20，这个得等他们把golang的版本升级到1.20，自己手动升级需要处理patch，最近编译还是在makemenu里面把xray-core给反标记吧

**Comment by zzy19868** [comment]
一样的问题，那就先反标记吧。

**Comment by WYC-2020** [comment]
我已经升级了，编译已完成，有时间我测试了功能再和你们说

**Comment by zzy19868** [comment]
> 

期待你的方案，没有xray分流不行啊。

**Comment by whwhwh93** [comment]
xray-plugin也是报错，应该是一样的问题

**Comment by bi4tms** [comment]
> 我已经升级了，编译已完成，有时间我测试了功能再和你们说

大佬是否已经测试成功，期待公布调整方法

**Comment by zzy19868** [comment]
> > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> 
> 大佬是否已经测试成功，期待公布调整方法

我现在测试下本地拉取修改1.7.3的上一个commit编译试试

**Comment by kentooo** [comment]
> > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > 
> > 
> > 大佬是否已经测试成功，期待公布调整方法
> 
> 我现在测试下本地拉取修改1.7.3的上一个commit编译试试

新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，，
只是还没解决xray-plugin的问题

估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了

**Comment by WYC-2020** [comment]
> > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > 
> > > 
> > > 大佬是否已经测试成功，期待公布调整方法
> > 
> > 
> > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> 
> 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> 
> 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了

看流浪去了 还没来得及验证哈哈

**Comment by WYC-2020** [comment]
先发给你吧，我这边 还得验证其他用了go的又没影响 ，我这边测试 是xray-core 是没问题了，我看已经有人提了patch 不过不是修复go 看你喜欢用那个 我这边继续验证一下其他的库 

> > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > 
> > > 
> > > 大佬是否已经测试成功，期待公布调整方法
> > 
> > 
> > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> 
> 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> 
> 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了

[golang.tar.gz](https://github.com/xiaorouji/openwrt-passwall/files/10608517/golang.tar.gz)

**Comment by WYC-2020** [comment]
建议别升 我测了 很多库 都会有问题因为 他们都还没升级到1.20  因为一个库 升级了go,而导致其他很多库 都的打patches 不值得 单独给编译不过 那两个库打patch吧

**Comment by zzy19868** [comment]
> 



> > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > 
> > > 
> > > 大佬是否已经测试成功，期待公布调整方法
> > 
> > 
> > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> 
> 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> 
> 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了

拉取 4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de 这个commit编译成功，使用正常，xray-core和xray-plugin都是1.7.2版。

**Comment by bi4tms** [comment]
> 先发给你吧，我这边 还得验证其他用了go的又没影响 ，我这边测试 是xray-core 是没问题了，我看已经有人提了patch 不过不是修复go 看你喜欢用那个 我这边继续验证一下其他的库
> 
> > > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > > 
> > > > 
> > > > 大佬是否已经测试成功，期待公布调整方法
> > > 
> > > 
> > > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> > 
> > 
> > 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> > 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了
> 
> [golang.tar.gz](https://github.com/xiaorouji/openwrt-passwall/files/10608517/golang.tar.gz)

已经用你提供的golang包编译通过且没有报错，感谢。
目前就先凑活着用吧。

**Comment by whwhwh93** [comment]
> > > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > > 
> > > > 
> > > > 大佬是否已经测试成功，期待公布调整方法
> > > 
> > > 
> > > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> > 
> > 
> > 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> > 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了
> 
> 拉取 [4fd4bf8](https://github.com/xiaorouji/openwrt-passwall/commit/4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de) 这个commit编译成功，使用正常，xray-core和xray-plugin都是1.7.2版。

我想问一下旧版本怎么拉？feed怎么写？

**Comment by zzy19868** [comment]
> > > > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > > > 
> > > > > 
> > > > > 大佬是否已经测试成功，期待公布调整方法
> > > > 
> > > > 
> > > > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> > > 
> > > 
> > > 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> > > 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了
> > 
> > 
> > 拉取 [4fd4bf8](https://github.com/xiaorouji/openwrt-passwall/commit/4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de) 这个commit编译成功，使用正常，xray-core和xray-plugin都是1.7.2版。
> 
> 我想问一下旧版本怎么拉？feed怎么写？
我没有用feed，整个过程如下
`cd lede
git clone https://github.com/xiaorouji/openwrt-passwall.git -b packages ./package/lean/passwall_package
cd package/lean/passwall_package
git checkout 4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de
git clone https://github.com/xiaorouji/openwrt-passwall.git -b luci ./package/lean/passwall
cp -rf ./package/lean/passwall_package/* ./package/lean/passwall
rm -rf ./package/lean/passwall_package
./scripts/feeds update -a
./scripts/feeds install -a`

**Comment by zzy19868** [comment]
> > > > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > > > 
> > > > > 
> > > > > 大佬是否已经测试成功，期待公布调整方法
> > > > 
> > > > 
> > > > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> > > 
> > > 
> > > 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> > > 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了
> > 
> > 
> > 拉取 [4fd4bf8](https://github.com/xiaorouji/openwrt-passwall/commit/4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de) 这个commit编译成功，使用正常，xray-core和xray-plugin都是1.7.2版。
> 
> 我想问一下旧版本怎么拉？feed怎么写？
我没有写feed，过程如下
`cd lede  
git clone https://github.com/xiaorouji/openwrt-passwall.git -b packages ./package/lean/passwall_package  
cd package/lean/passwall_package  
git checkout 4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de  
git clone https://github.com/xiaorouji/openwrt-passwall.git -b luci ./package/lean/passwall  
cp -rf ./package/lean/passwall_package/* ./package/lean/passwall  
rm -rf ./package/lean/passwall_package  
./scripts/feeds update -a  
./scripts/feeds install -a`

**Comment by zzy19868** [comment]
> > > > > > 我已经升级了，编译已完成，有时间我测试了功能再和你们说
> > > > > 
> > > > > 
> > > > > 大佬是否已经测试成功，期待公布调整方法
> > > > 
> > > > 
> > > > 我现在测试下本地拉取修改1.7.3的上一个commit编译试试
> > > 
> > > 
> > > 新的commit已经解决了openwrt sdk的编译xray-core 1.7.3的问题，， 只是还没解决xray-plugin的问题
> > > 估计快了，主要是openwrt sdk里面包含的golang还是1.19.5，官方的更新得等待一块时间，现在在menuconfig里面只需要反标记xray-plugin就可以编译成功了
> > 
> > 
> > 拉取 [4fd4bf8](https://github.com/xiaorouji/openwrt-passwall/commit/4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de) 这个commit编译成功，使用正常，xray-core和xray-plugin都是1.7.2版。
> 
> 我想问一下旧版本怎么拉？feed怎么写？
`
> cd lede

> git clone https://github.com/xiaorouji/openwrt-passwall.git -b packages ./package/lean/passwall_package

> cd package/lean/passwall_package

> git checkout 4fd4bf8f68fbbbd0d9eca865e68762d6ce3a01de

> git clone https://github.com/xiaorouji/openwrt-passwall.git -b luci ./package/lean/passwall

> cp -rf ./package/lean/passwall_package/* ./package/lean/passwall

> rm -rf ./package/lean/passwall_package

> ./scripts/feeds update -a

> ./scripts/feeds install -a
`

**Comment by WYC-2020** [comment]
等xary-core 上游打tag，发布版本吧，我看最新版已经兼容了非1.20go 编译

**Comment by sbwml** [comment]
https://github.com/sbwml/openwrt_helloworld/commit/8cb71c1ed40e6034d6fbdb6a897ed9cc708c484a

**Comment by WYC-2020** [comment]
> [sbwml/openwrt_helloworld@8cb71c1](https://github.com/sbwml/openwrt_helloworld/commit/8cb71c1ed40e6034d6fbdb6a897ed9cc708c484a)

嗯这就是把xray更新到某一个commit版本，这样是可以避免

**Comment by WYC-2020** [comment]
[fix_go_120.tar.gz](https://github.com/xiaorouji/openwrt-passwall/files/10671242/fix_go_120.tar.gz)
来给你们一个搞好的 直接覆盖就行了

**Comment by Travel2Here** [comment]
> [fix_go_120.tar.gz](https://github.com/xiaorouji/openwrt-passwall/files/10671242/fix_go_120.tar.gz) 来给你们一个搞好的 直接覆盖就行了

好人一生平安，编译中

**Comment by Travel2Here** [comment]
很可惜 我失败了。（升级了上面分享的golang到1.2，同时用了fix_go_120.tar.gz覆盖xray相关。）

o@ubuntu:~/lede$ make -j$(nproc) || make -j1 || make -j1 V=s
make[2]: Entering directory '/home/zo/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/zo/lede/scripts/config'
time: target/linux/prereq#0.07#0.03#0.10
 make[1] world
 make[2] package/cleanup
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[2] package/compile
 make[3] diffconfig buildversion feedsversion
 make[3] -C package/libs/libjson-c host-compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/system/fwtool host-compile
 make[3] -C package/system/usign host-compile
 make[3] -C feeds/luci/modules/luci-base host-compile
 make[3] -C package/utils/lua host-compile
 make[3] -C feeds/packages/libs/libffi host-compile
 make[3] -C package/utils/bzip2 host-compile
 make[3] -C package/libs/gettext-full host-compile
 make[3] -C package/utils/e2fsprogs host-compile
 make[3] -C feeds/packages/lang/golang/golang host-compile
 make[3] -C feeds/packages/libs/gperf host-compile
 make[3] -C package/lean/ucl host-compile
 make[3] -C feeds/packages/libs/boost host-compile
 make[3] -C feeds/packages/lang/ruby host-compile
 make[3] -C package/kernel/gpio-button-hotplug compile
 make[3] -C package/libs/sysfsutils compile
 **make[4] scripts/config/conf
    ERROR: package/feeds/packages/golang [host] failed to build.**
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/zo/lede/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/home/zo/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/zo/lede/scripts/config'

**Comment by sbwml** [comment]
> 很可惜 我失败了。（升级了上面分享的golang到1.2，同时用了fix_go_120.tar.gz覆盖xray相关。）
> 
> o@ubuntu:~/lede$ make -j$(nproc) || make -j1 || make -j1 V=s make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config' time: target/linux/prereq#0.07#0.03#0.10 make[1] world make[2] package/cleanup make[2] target/compile make[3] -C target/linux compile make[2] buildinfo make[2] package/compile make[3] diffconfig buildversion feedsversion make[3] -C package/libs/libjson-c host-compile make[3] -C package/libs/toolchain compile make[3] -C package/libs/ncurses host-compile make[3] -C package/system/fwtool host-compile make[3] -C package/system/usign host-compile make[3] -C feeds/luci/modules/luci-base host-compile make[3] -C package/utils/lua host-compile make[3] -C feeds/packages/libs/libffi host-compile make[3] -C package/utils/bzip2 host-compile make[3] -C package/libs/gettext-full host-compile make[3] -C package/utils/e2fsprogs host-compile make[3] -C feeds/packages/lang/golang/golang host-compile make[3] -C feeds/packages/libs/gperf host-compile make[3] -C package/lean/ucl host-compile make[3] -C feeds/packages/libs/boost host-compile make[3] -C feeds/packages/lang/ruby host-compile make[3] -C package/kernel/gpio-button-hotplug compile make[3] -C package/libs/sysfsutils compile **make[4] scripts/config/conf ERROR: package/feeds/packages/golang [host] failed to build.** make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/home/zo/lede/include/toplevel.mk:231: world] Error 1 make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config'

哈哈   换成这个 https://github.com/sbwml/openwrt_helloworld/tree/v5/v2ray-plugin   go18、19、20  你都能编译

另外你这个go1.20 做的也不对，golang 1.20 开始需要依赖 bootstrap 1.17.3 或以上版本

**Comment by WYC-2020** [comment]
> > 很可惜 我失败了。（升级了上面分享的golang到1.2，同时用了fix_go_120.tar.gz覆盖xray相关。）
> > o@ubuntu:~/lede$ make -j$(nproc) || make -j1 || make -j1 V=s make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config' time: target/linux/prereq#0.07#0.03#0.10 make[1] world make[2] package/cleanup make[2] target/compile make[3] -C target/linux compile make[2] buildinfo make[2] package/compile make[3] diffconfig buildversion feedsversion make[3] -C package/libs/libjson-c host-compile make[3] -C package/libs/toolchain compile make[3] -C package/libs/ncurses host-compile make[3] -C package/system/fwtool host-compile make[3] -C package/system/usign host-compile make[3] -C feeds/luci/modules/luci-base host-compile make[3] -C package/utils/lua host-compile make[3] -C feeds/packages/libs/libffi host-compile make[3] -C package/utils/bzip2 host-compile make[3] -C package/libs/gettext-full host-compile make[3] -C package/utils/e2fsprogs host-compile make[3] -C feeds/packages/lang/golang/golang host-compile make[3] -C feeds/packages/libs/gperf host-compile make[3] -C package/lean/ucl host-compile make[3] -C feeds/packages/libs/boost host-compile make[3] -C feeds/packages/lang/ruby host-compile make[3] -C package/kernel/gpio-button-hotplug compile make[3] -C package/libs/sysfsutils compile **make[4] scripts/config/conf ERROR: package/feeds/packages/golang [host] failed to build.** make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/home/zo/lede/include/toplevel.mk:231: world] Error 1 make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config'
> 
> 哈哈 换成这个 https://github.com/sbwml/openwrt_helloworld/tree/v5/v2ray-plugin go18、19、20 你都能编译
> 
> 另外你这个go1.20 做的也不对，golang 1.20 开始需要依赖 bootstrap 1.17.3 或以上版本

忘记和你

> 很可惜 我失败了。（升级了上面分享的golang到1.2，同时用了fix_go_120.tar.gz覆盖xray相关。）
> 
> o@ubuntu:~/lede$ make -j$(nproc) || make -j1 || make -j1 V=s make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config' time: target/linux/prereq#0.07#0.03#0.10 make[1] world make[2] package/cleanup make[2] target/compile make[3] -C target/linux compile make[2] buildinfo make[2] package/compile make[3] diffconfig buildversion feedsversion make[3] -C package/libs/libjson-c host-compile make[3] -C package/libs/toolchain compile make[3] -C package/libs/ncurses host-compile make[3] -C package/system/fwtool host-compile make[3] -C package/system/usign host-compile make[3] -C feeds/luci/modules/luci-base host-compile make[3] -C package/utils/lua host-compile make[3] -C feeds/packages/libs/libffi host-compile make[3] -C package/utils/bzip2 host-compile make[3] -C package/libs/gettext-full host-compile make[3] -C package/utils/e2fsprogs host-compile make[3] -C feeds/packages/lang/golang/golang host-compile make[3] -C feeds/packages/libs/gperf host-compile make[3] -C package/lean/ucl host-compile make[3] -C feeds/packages/libs/boost host-compile make[3] -C feeds/packages/lang/ruby host-compile make[3] -C package/kernel/gpio-button-hotplug compile make[3] -C package/libs/sysfsutils compile **make[4] scripts/config/conf ERROR: package/feeds/packages/golang [host] failed to build.** make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/home/zo/lede/include/toplevel.mk:231: world] Error 1 make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config'

别升级1.20  直接1.19 加上我这个编译就行了，升级1.20 很多编译不过的

**Comment by WYC-2020** [comment]
> 很可惜 我失败了。（升级了上面分享的golang到1.2，同时用了fix_go_120.tar.gz覆盖xray相关。）
> 
> o@ubuntu:~/lede$ make -j$(nproc) || make -j1 || make -j1 V=s make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config' time: target/linux/prereq#0.07#0.03#0.10 make[1] world make[2] package/cleanup make[2] target/compile make[3] -C target/linux compile make[2] buildinfo make[2] package/compile make[3] diffconfig buildversion feedsversion make[3] -C package/libs/libjson-c host-compile make[3] -C package/libs/toolchain compile make[3] -C package/libs/ncurses host-compile make[3] -C package/system/fwtool host-compile make[3] -C package/system/usign host-compile make[3] -C feeds/luci/modules/luci-base host-compile make[3] -C package/utils/lua host-compile make[3] -C feeds/packages/libs/libffi host-compile make[3] -C package/utils/bzip2 host-compile make[3] -C package/libs/gettext-full host-compile make[3] -C package/utils/e2fsprogs host-compile make[3] -C feeds/packages/lang/golang/golang host-compile make[3] -C feeds/packages/libs/gperf host-compile make[3] -C package/lean/ucl host-compile make[3] -C feeds/packages/libs/boost host-compile make[3] -C feeds/packages/lang/ruby host-compile make[3] -C package/kernel/gpio-button-hotplug compile make[3] -C package/libs/sysfsutils compile **make[4] scripts/config/conf ERROR: package/feeds/packages/golang [host] failed to build.** make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/home/zo/lede/include/toplevel.mk:231: world] Error 1 make[2]: Entering directory '/home/zo/lede/scripts/config' make[2]: 'conf' is up to date. make[2]: Leaving directory '/home/zo/lede/scripts/config'

忘记和你说了 哈哈

**Comment by WYC-2020** [comment]
升级1.20  adg 还有好几个依赖go的都会编译不过，所以我这个是基于 1.19做的 ，我这边用l大的 1.19.4go亲测编译没任何问题，至于1.19.5 我想应该也没问题，没测过，你可以用官方op测试 因为官方op升级到了1.19.5

**Comment by sbwml** [comment]
大佬牛逼

**Comment by WYC-2020** [comment]
> 大佬牛逼

1.20暂时别升级，他作为很多库的基础库在使用，120才出来 很多库都没跟上，更新了一堆问题，就和原来升级boost或者musl一样 到处出问题，等120大部分库都适配了在升级都不迟

**Comment by sbwml** [comment]
> > 大佬牛逼
> 
> 1.20暂时别升级，他作为很多库的基础库在使用，120才出来 很多库都没跟上，更新了一堆问题，就和原来升级boost或者musl一样 到处出问题，等120大部分库都适配了在升级都不迟

我已经早两天就已经在用go1.20 了。我给我自己要用到和未兼容1.20的插件都打过patch，实际上也没几个 ，不兼容的大部分都是 quic-tls 这块，直接更新到上游就行，你说的adg 也是如此，虽然我没在用，但是我在用mosdns ，它有使用adg的dnsproxy 模块，将他更新到上游tls 就能直接在go1.20 上过

我自己用的golang  https://github.com/sbwml/packages_lang_golang/tree/20.x

**Comment by WYC-2020** [comment]
> > > 大佬牛逼
> > 
> > 
> > 1.20暂时别升级，他作为很多库的基础库在使用，120才出来 很多库都没跟上，更新了一堆问题，就和原来升级boost或者musl一样 到处出问题，等120大部分库都适配了在升级都不迟
> 
> 我已经早两天就已经在用go1.20 了。我给我自己要用到和未兼容1.20的插件都打过patch，实际上也没几个 ，不兼容的大部分都是 quic-tls 这块，直接更新到上游就行，你说的adg 也是如此，虽然我没在用，但是我在用mosdns ，它有使用adg的dnsproxy 模块，将他更新到上游tls 就能直接在go1.20 上过
> 
> 我自己用的golang https://github.com/sbwml/packages_lang_golang/tree/20.x

懒得折腾了，能用就行了，没那么多心思更新那些杂七杂八的库，我喜欢偷懒，等他们更新哈哈
