### ISSUE TITLE
[Bug]: 更换节点保存应用后会启动BBR拥塞控制算法选项

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#2267]
### 描述您遇到的bug

每次更换节点保存应用后会启动Turbo ACC 网络加速设置里的BBR拥塞控制算法选项。
关掉bbr后梯子不能爬墙，passwall关开一次后恢复正常，但是bbr也跟着启动。

### 复现此Bug的步骤

.....

### 您想要实现的目的

更换节点不更改bbr设置

### 日志信息

....

### 系统相关信息

2月1日时的版本

**Comment by gnz1123** [comment]
不知道为什么出现这个联动，或许是openwrt的问题。

**Comment by handsomeji** [comment]
新的源码应该不会有这个问题才对
