### ISSUE TITLE
[Bug]: 编译passwall成功，但是找不到luci-app-passwall这个ipk

### ISSUE THREAD

**Issue by 725216** [xiaorouji/openwrt-package#2269]
### 描述您遇到的bug

我用潘多拉的sdk编译的“师夷长技以制夷”，编译成功，没有报错，但是在bin里找不到luci-app-passwal，但是插件都有

### 复现此Bug的步骤

删除了重新编译也是一样的

### 您想要实现的目的

怎么解决

### 日志信息

无

### 系统相关信息

最新的

**Comment by wazzx** [comment]
这个！没有日记什么的,也不知道啊！

**Comment by 725216** [comment]
不知道为什么我的电脑不能上传截图，现在用手机上传了，请看一下

**Comment by 725216** [comment]
![1](https://user-images.githubusercontent.com/22210790/216758520-de763191-827c-4ebc-bf42-c7190946e1c3.jpg)
图片来了

**Comment by wazzx** [comment]
feeds/PWluci

**Comment by whwhwh93** [comment]
我也遇到这个问题，编译前也加了PWluci的feed，最后编译完有pwluci的文件夹但里面是空的。是用原版sdk编译的，是后面选项那一还要选其他什么东西吗？

**Comment by whwhwh93** [comment]
> ![1](https://user-images.githubusercontent.com/22210790/216758520-de763191-827c-4ebc-bf42-c7190946e1c3.jpg)
> 图片来了

你这个好像是编译xray-plugin失败停止，和我不是一个bug，你插件也没编译全吧

**Comment by 725216** [comment]
> 我也遇到这个问题，编译前也加了PWluci的feed，最后编译完有pwluci的文件夹但里面是空的。是用原版sdk编译的，是后面选项那一还要选其他什么东西吗？

你解决了吗？

**Comment by whwhwh93** [comment]
> > 我也遇到这个问题，编译前也加了PWluci的feed，最后编译完有pwluci的文件夹但里面是空的。是用原版sdk编译的，是后面选项那一还要选其他什么东西吗？
> 
> 你解决了吗？

没有，今天luci更新了好多东西，最新版本依然这样

**Comment by whwhwh93** [comment]
> > 我也遇到这个问题，编译前也加了PWluci的feed，最后编译完有pwluci的文件夹但里面是空的。是用原版sdk编译的，是后面选项那一还要选其他什么东西吗？
> 
> 你解决了吗？

重新编译了一下，这回我分成2步，
make package/luci-app-passwall/compile，
这一条命令以后luci是有的;
make package/uci-app-passwall/clean，
make package/index
这两条命令后luci就没有了，具体是哪一条没看。
所以建议就是不要三条命令一起敲，第一条命令敲完以后先把文件取出来，再敲后两条。

**Comment by 725216** [comment]
> 



> 

我只用了

**Comment by 725216** [comment]
我只用了make package/luci-app-passwall/compile V=99

**Comment by whwhwh93** [comment]
> 我只用了make package/luci-app-passwall/compile V=99

make menuconfig的時候看看全局里面以下东西是不是全部打勾了
Select all target specific packages by default                                                    
Select all kernel module packages by default                                                      
Select all userspace packages by default
Cryptographically sign package lists
