### ISSUE TITLE
订阅链接订阅不了

### ISSUE THREAD

**Issue by 725216** [xiaorouji/openwrt-package#2275]
路由是潘多垃固件，今天刚编译的插件，路由恢复出厂后安装的passwall ,但是在订阅不了链接，链接在ssr-plus上正常使用

**Comment by handsomeji** [comment]
没日志。。
且没有用过潘多拉，盲猜可能缺少部分curl命令参数。。。

**Comment by 725216** [comment]
日志提示网络不正常和链接错误

**Comment by 725216** [comment]
另外在编译方法里看见的是安装wget-ssl这个插件，但是编译出的插件没这千wget-ssl,我只安装了wget

**Comment by handsomeji** [comment]
passwall使用curl而不是wget
