### ISSUE TITLE
[Feature Request]: 关于passwall dns的一个小问题

### ISSUE THREAD

**Issue by a2490933694** [xiaorouji/openwrt-package#2276]
### 描述你想要的新功能

最近使用lean的最新源码编译发现dns方面的一些小问题，一开始是这样发现问题的：
某一天发现打开谷歌提示证书有异常，查询证书域名是facebook的，然后去手动重启了下passwall后恢复正常，之后也遇到过几次，后来发现如果不开chinadns-ng就没有遇到这种情况了，出于好奇分析了一下问题。

测试发现这种情况比较容易出现在宽带重新拨号后，不管是手动去关闭再连接接口，还是运营商固定时间自动重拨号，但是lean几个月之前的源码编译是没有这种情况的，然后我看了下提交发现dnsmasq有更新，怀疑可能和这个有关。然后随便测试了一会发现这样一个情况：
如果passwall开了chinadns-ng，再不重启passwall的情况下去重启dnsmasq，就会导致国外网站的域名解析到了不正确的ip上。
我是用这个命令测试的“/etc/init.d/dnsmasq restart”
但是呢，这个情况在旧的源码上也可以复现，所以我怀疑可能是dnsmasq更新了新版有概率在拨号后出现重启的问题。
如果没有开启chinadns-ng，重启dnsmasq不会影响dns解析。

简单来说就是：
passwall的chinadns-ng启用后，如果dnsmasq因为各种原因重启了，但passwall没有重启，就会导致国外dns解析异常。

所以希望大佬能考虑一下，能不能在dnsmasq重启后自动重启passwall

### 描述你想要的解决方案

同上

**Comment by xcyll** [comment]
【版本：op-master最新分支 本地DNS是默认的】
类似问题 不过我没启用那个NG   用的Xray
宽带拨号ip变动时 此时，远程DNS 会失效😯(测试了两个 插件自带xray-doh dns ,第三方smartdns)新的网页访问失败 
此时1⃣️用插件自带远程dns的情况下 PW设置里 清空IPSET 后  远程DNS可恢复正常解析 可正常访问新的网页
2⃣️远程DNS是smartdns情况下 重启下smartdns后 可正访问网页了

**Comment by xcyll** [comment]
手动重拨也试了下 也是上述情况

**Comment by 0x777777A** [comment]
遇到过这问题，不过应该不是dnsmasq版本更新的问题，之前也遇到过，要手动重启下passwall，不然解析结果是被污染的。
不过我不确定是不是拨号引起的，只是偶尔会遇到，L大的源码。

**Comment by 0x777777A** [comment]
实测手动重拨几次，确实有概率遇到国外dns结果污染的问题，passwall重启后解决。

**Comment by xcyll** [comment]
@0x777777A 也许是运营商隔段时间就下发新的IP？此时PW远程dns就会失效？
手动重拨 获得新的IP 我这边远程dns就不能正常解析了 你有时能访问也许是有缓存在 一旦你访问没有缓存的网页可能就访问不了了

**Comment by 0x777777A** [comment]
> @0x777777A 也许是运营商隔段时间就下发新的IP？此时PW远程dns就会失效？ 手动**重拨 直到**获得新的IP 我这边远程dns就不能正常解析了 有时能访问也许是有缓存在 一旦缓存过期或者访问没有缓存的网页可能就访问不了了

确实，我刚试了，不断重新拨号直到IP变化以后，清除本地的dns缓存后无法访问谷歌，ping谷歌结果是199.59.149.239，重启passwall后再次清除本地dns缓存后恢复正常，ping谷歌结果是142.251.220.36，可以正常访问

补充环境信息：我用的是 ss-rust + 开启 chinadns-ng，没有使用smartdns之类的第三方dns插件

@xiaorouji 希望作者重视下这个问题，辛苦了

**Comment by ecrasy** [comment]
我在L大第一次更新到dnsmasq v2.87的时候就碰到了这个问题
后来我转到了OP 官方master分支就没有这个问题
一周前编译的L大固件问题依旧
而且L大的固件在OP重启之后
第一次访问国内任意网站
DNS解析都会卡几秒，chrome一直在resolve dns
测试nslookup github
结果都是新加坡的IP
重启dnsmasq之后才正常
所有情况下我都没有编译chinadns-ng
从我的测试结果来看
我觉得更可能是L大那边的问题

**Comment by chancat87** [comment]
用passwall2代吧

**Comment by a2490933694** [comment]
> 我在L大第一次更新到dnsmasq v2.87的时候就碰到了这个问题 后来我转到了OP 官方master分支就没有这个问题 一周前编译的L大固件问题依旧 而且L大的固件在OP重启之后 第一次访问国内任意网站 DNS解析都会卡几秒，chrome一直在resolve dns 测试nslookup github 结果都是新加坡的IP 重启dnsmasq之后才正常 所有情况下我都没有编译chinadns-ng 从我的测试结果来看 我觉得更可能是L大那边的问题

😂这个问题我也碰到过，看来确实有可能是L大那边的问题，准备换官方试试了

**Comment by symonlee** [comment]
已更新最新代码[ed4834e8288e4244703e0f585374aeb13fdd87a0](https://github.com/xiaorouji/openwrt-passwall/commit/ed4834e8288e4244703e0f585374aeb13fdd87a0)
宽带自动变IP时或者即使重拨直到获得新的IP 
PW自动重新启用 远程dns恢复正常解析

**Comment by xcyll** [comment]
已拉取最新 我这边没问题了

**Comment by Travel2Here** [comment]
> ，准备换官方试试了

同遇到，我还回滚到前面的代码重编译过，不仅是lede里dnsmasq的版本问题，还有防火墙版本也都动过。可能还有别的，没空一一排查也没那么深能力。
这两天的lede编译后有时候pw能正常 有时候不行，表现为国内部分网站不能正常解析打开。
完全新固件不启动pw又都正常，很烦，不知道要问哪边提问题合适 哈哈。
总之就是双方姿势没对好。

*手痒来一把

<img width="669" alt="image" src="https://user-images.githubusercontent.com/99887507/218053424-efcc4c0e-dafe-4e13-9e46-97420654a211.png">

**Comment by wtfr-dot** [comment]
用的lean和passwall最新源码，问题还是出现，没有任何提示有时会突然提示不安全连接，感觉是chinadns-ng的问题，我把它关了再观察一下
