### ISSUE TITLE
[Bug]: 用xtls vision,开前置代理访问提示ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by bbcbbk** [xiaorouji/openwrt-package#2299]
### 描述您遇到的bug

passwall版本: git-24.040.56300-01aa7bb

主节点和落地机均采用xtls vision, 开启netflix分流, 可以正常分流.

一旦打开netflix的前置代理,就访问不了netflix

chrome提示 ERR_SSL_PROTOCOL_ERROR, firefox提示Error code: SSL_ERROR_RX_RECORD_TOO_LONG

看passwall的日志,也正常 无报错

2023/02/10 10:28:03 192.168.1.75:52125 accepted tcp:44.234.232.238:443 [tcp_redir -> Netflix]
2023/02/10 10:28:04 192.168.1.75:52126 accepted tcp:44.234.232.238:443 [tcp_redir -> Netflix]

### 复现此Bug的步骤

主节点和分流节点均用xtls vision, 分流节点用主节点当前置代理

### 您想要实现的目的

用xtls vision分流时,可以使用前置代理

### 日志信息

Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)
A unified platform for anti-censorship.
2023/02/10 10:06:47 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP_SOCKS.json
2023/02/10 10:06:50 100.74.130.155:57246 accepted tcp:8.8.8.8:853 [tcp_redir -> default]
2023/02/10 10:07:03 192.168.1.75:51948 accepted tcp:52.38.7.83:443 [tcp_redir -> Netflix]
2023/02/10 10:07:04 192.168.1.75:51949 accepted tcp:34.107.221.82:80 [tcp_redir -> default]
2023/02/10 10:07:04 192.168.1.75:51950 accepted tcp:34.107.221.82:80 [tcp_redir -> default]
2023/02/10 10:07:07 192.168.1.75:51951 accepted tcp:23.207.98.153:443 [tcp_redir -> Netflix]

### 系统相关信息

passwall版本: git-24.040.56300-01aa7bb

xtls版本 :1.7.5

**Comment by handsomeji** [comment]
这个应该是Xray的问题吧？你应该去Xray反馈

**Comment by bbcbbk** [comment]
> 这个应该是Xray的问题吧？你应该去Xray反馈

有可能，用xtls direct就没问题，好的 我明白啦
