### ISSUE TITLE
[Bug]: 一处细节，socks主开关会闪现

### ISSUE THREAD

**Issue by firkerword** [xiaorouji/openwrt-package#2302]
### 描述您遇到的bug

![photo_2023-02-11_14-40-42](https://user-images.githubusercontent.com/61251923/218244760-037f8dfc-d4b9-460d-8622-4a5b976285a2.jpg)
刷新网页的时候在UDP节点下面之后又会跳到socks配置下面
![photo_2023-02-11_14-43-22](https://user-images.githubusercontent.com/61251923/218244810-11db160c-03c5-4da0-97ee-70f21a57ee68.jpg)

### 复现此Bug的步骤

刷新页面

### 您想要实现的目的

验证bug是否存在并解决

### 日志信息

无

### 系统相关信息

passwall v4.58.3
浏览器：
Microsoft Edge版本 109.0.1518.78 (正式版本) (64 位)
Chrome 版本 110.0.5481.78（正式版本）（64 位）
固件：lean x86-64  5.19.93 R23.2.14 / LuCI Master (git-23.040.60681-9fc2e34)

**Comment by SakuraFallingMad** [comment]
这是网页加载问题，加载完成后页面是正常的

**Comment by firkerword** [comment]
> 这是网页加载问题，加载完成后页面是正常的

无论哪个浏览器都一样

**Comment by y9858** [comment]
> > 这是网页加载问题，加载完成后页面是正常的
> 
> 无论哪个浏览器都一样

雀氏 换了几个浏览器都一样

**Comment by handsomeji** [comment]
是这样的 不是bug
