### ISSUE TITLE
[Feature Request]: 不想所有连接到路由器的设备都能访问国外，《访问控制》希望优化一下

### ISSUE THREAD

**Issue by virxpx** [xiaorouji/openwrt-package#2303]
### 描述你想要的新功能

由于不想所有连接到路由器的设备都能访问国外

**_只想《访问控制》中的规则指定的IP才走指定节点出国_**，

但是如果在《基本设置》中设置tcp和udp节点为 “关闭” ，《访问控制》功能貌似也是无效的。
而如果不把《基本设置》中的tcp和udp设置为关闭，**_貌似就所有连接到路由器的设备都出国了_**。                 

其实把《基本设置》中的tcp和udp线路随便设置一个，然后设置他们全部为tcp/udp不代理也能基本上述的效果，但是总感觉差点意思。 

 希望可以小小优化一下，在把《基本设置》中的tcp/udp节点设置为 "关闭" 之后，仍然可以使用《访问控制》。

### 描述你想要的解决方案

同上所述

**Comment by malong19890218** [comment]
貌似不用关，代理模式都选择不代理，就行

**Comment by mynameisalice** [comment]
遇到同样的问题。

**Comment by SakuraFallingMad** [comment]
我这边遇到的是访控内的主机设置某端口不转发，但是链接是无效的

**Comment by imoldchen** [comment]
最近的版本访问控制确实没法用，特别是用了 nftable 之后，不光udp的控制项都无效了，tcp指定MAC的设备网速只有几十KB/s，本地编译固件一度以为是系统出问题了。

**Comment by xh0823** [comment]
使用nftable，问题一样

**Comment by xcyll** [comment]
最新源码好像故障了 设置如下
tcp节点已勾选
基本设置-模式-都选不代理
访问控制里指定设备代理
---结果指定设备代理失败 不能访问代理域名了
旧的源码一直正常使用@xiaorouji

**Comment by xiaorouji** [comment]
@xcyll  我这里无法复现，请提供详细信息和日志。

**Comment by xiaorouji** [comment]
@xcyll 修复了个BUG，试一下最新的源码

**Comment by xh0823** [comment]
2023-03-05 12:42:54: 删除相关防火墙规则完成。
2023-03-05 12:42:55: 清空并关闭相关程序和缓存完成。
2023-03-05 12:42:55: 使用nftables进行透明代理，一些不支持nftables的组件如chinadns-ng等可能不会正常工作。
2023-03-05 12:42:55: TCP节点：00:00:00:00:00:00:443，监听端口：1041
2023-03-05 12:42:55: 过滤服务配置：准备接管域名解析...
2023-03-05 12:42:55:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2023-03-05 12:42:55:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2023-03-05 12:42:55:   - 节点列表中的域名(vpsiplist)：223.6.6.6,119.29.29.29
2023-03-05 12:42:55:   - 域名白名单(whitelist)：223.6.6.6,119.29.29.29
2023-03-05 12:42:55:   - 代理域名表(blacklist)：127.0.0.1#15353
2023-03-05 12:42:55:   - 防火墙域名表(gfwlist)：127.0.0.1#15353
2023-03-05 12:42:55:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-03-05 12:42:55: 开始加载防火墙规则...
2023-03-05 12:42:59: 加入负载均衡的节点到nftset[vpsiplist]直连完成
2023-03-05 12:42:59: 加入所有节点到nftset[vpsiplist]直连完成
2023-03-05 12:42:59: 加载路由器自身 TCP 代理...
2023-03-05 12:42:59:   - 启用 TPROXY 模式
2023-03-05 12:42:59:   - [0]将上游 DNS 服务器 8.8.8.8:53 加入到路由器自身代理的 TCP 转发链
2023-03-05 12:42:59: 加载路由器自身 UDP 代理...
2023-03-05 12:42:59: 访问控制：
2023-03-05 12:42:59:   - 备注【cfg1430ec】，MAC【00:00:00:00:00:00】，使用TCP节点[00:00:00:00:00:002] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59:   - 备注【cfg1430ec】，MAC【00:00:00:00:00:00】，使用UDP节点[] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59:   - 备注【cfg1530ec】，MAC【00:00:00:00:00:00】，使用TCP节点[00:00:00:00:00:00] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59:   - 备注【cfg1530ec】，MAC【00:00:00:00:00:00】，使用UDP节点[] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59:   - 备注【cfg1630ec】，MAC【00:00:00:00:00:00】，使用TCP节点00:00:00:00:00:00] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59:   - 备注【cfg1630ec】，MAC【00:00:00:00:00:00】，使用UDP节点[] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59: TCP默认代理：使用TCP节点[00:00:00:00:00:00 00:00:00:00:00:00  00:00:00:00:00:00 [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59: UDP默认代理：使用UDP节点[00:00:00:00:00:000 00:00:00:00:00:00  00:00:00:00:00:00] [中国列表以外](TPROXY:1041)代理所有端口
2023-03-05 12:42:59: 防火墙规则加载完成！
2023-03-05 12:43:00: 重启 dnsmasq 服务
2023-03-05 12:43:00: 配置定时任务：自动更新规则。
2023-03-05 12:43:00: 运行完成！

**Comment by xh0823** [comment]
还是一样基本设置选择不代理就全部用不了，选择了中国以外就所有设备都可以科学了

**Comment by xcyll** [comment]
> @xcyll 我这里无法复现，请提供详细信息和日志。

![2023-03-05 131857](https://user-images.githubusercontent.com/63227888/222943317-b5f9536f-2b2d-4f55-9b3e-99f226e50c35.png)

   还是不行
 openwrt master分支 PW最新源码
<details>
<summary>log 2023/03/05 13:13:41</summary>

**<summary>Xray 1.7.5 (Xray, Penetrates Everything.) OpenWrt (go1.19.6 linux/arm64)
A unified platform for anti-censorship.
2023/03/05 05:13:41 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/TCP_SOCKS_DNS.json
2023/03/05 05:13:41 [Debug] app/log: Logger started
2023/03/05 05:13:41 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:1070
2023/03/05 05:13:41 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:1041
2023/03/05 05:13:41 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:15353
2023/03/05 05:13:41 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:15353
2023/03/05 05:13:41 [Info] transport/internet/udp: listening UDP on 127.0.0.1:15353
2023/03/05 05:13:41 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1041
2023/03/05 05:13:41 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1070
2023/03/05 05:13:41 [Info] transport/internet/udp: listening UDP on 0.0.0.0:1070
2023/03/05 05:13:41 [Warning] core: Xray 1.7.5 started
2023/03/05 05:14:14 [Debug] [268446483] proxy/dokodemo: processing connection from: 127.0.0.1:46629
2023/03/05 05:14:14 [Info] [268446483] proxy/dokodemo: received request for 127.0.0.1:46629
2023/03/05 05:14:14 [Info] [268446483] app/dispatcher: taking detour [dns-out] for [udp:1.1.1.2:53]
2023/03/05 05:14:14 127.0.0.1:46629 accepted udp:1.1.1.2:53 [dns-in -> dns-out]
2023/03/05 05:14:14 [Info] [268446483] proxy/dns: handling DNS traffic to tcp:1.1.1.2:53
2023/03/05 05:14:14 [Debug] app/dns: domain play.googleapis.com will use the first DNS: [TCP//1.1.1.2:53]
2023/03/05 05:14:14 [Debug] app/dns: DNS cache is disabled. Querying IP for play.googleapis.com at TCP//1.1.1.2:53
2023/03/05 05:14:14 [Debug] app/dns: TCP//1.1.1.2:53 querying DNS for: play.googleapis.com.
2023/03/05 05:14:14 [Info] app/dispatcher: taking detour [b652fcb608684457a32cd801c5999d56] for [tcp:1.1.1.2:53]
2023/03/05 05:14:14 [Info] transport/internet/tcp: dialing TCP to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:14 DNS accepted tcp:1.1.1.2:53 [dns-in1 -> b652fcb608684457a32cd801c5999d56]
2023/03/05 05:14:14 [Debug] transport/internet: dialing to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:14 [Info] proxy/trojan: tunneling request to tcp:1.1.1.2:53 via point-a.point.mysynology.net:20001
2023/03/05 05:14:14 [Info] app/dns: TCP//1.1.1.2:53 got answer: play.googleapis.com. TypeA -> [172.217.24.106 172.217.24.74 142.250.204.106 142.250.66.74 142.251.220.106 142.250.66.42 142.250.66.138 142.250.66.106 142.251.220.74 142.250.204.42 142.251.220.42 142.251.220.10 142.250.207.74 216.58.200.234 142.250.199.74 216.58.203.74] 301.332032ms
2023/03/05 05:14:16 127.0.0.1:34687 accepted udp:1.1.1.2:53 [dns-in -> dns-out]
2023/03/05 05:14:16 127.0.0.1:34108 accepted udp:1.1.1.2:53 [dns-in -> dns-out]
2023/03/05 05:14:16 [Debug] [529193833] proxy/dokodemo: processing connection from: 127.0.0.1:34108
2023/03/05 05:14:16 [Info] [529193833] proxy/dokodemo: received request for 127.0.0.1:34108
2023/03/05 05:14:16 [Debug] [2180104190] proxy/dokodemo: processing connection from: 127.0.0.1:34687
2023/03/05 05:14:16 [Info] [2180104190] proxy/dokodemo: received request for 127.0.0.1:34687
2023/03/05 05:14:16 [Info] [2180104190] app/dispatcher: taking detour [dns-out] for [udp:1.1.1.2:53]
2023/03/05 05:14:16 [Info] [529193833] app/dispatcher: taking detour [dns-out] for [udp:1.1.1.2:53]
2023/03/05 05:14:16 [Info] [529193833] proxy/dns: handling DNS traffic to tcp:1.1.1.2:53
2023/03/05 05:14:16 [Info] [2180104190] proxy/dns: handling DNS traffic to tcp:1.1.1.2:53
2023/03/05 05:14:16 [Info] [529193833] transport/internet/tcp: dialing TCP to tcp:1.1.1.2:53
2023/03/05 05:14:16 [Debug] transport/internet: dialing to tcp:1.1.1.2:53
2023/03/05 05:14:16 [Debug] app/dns: domain www.instagram.com will use the first DNS: [TCP//1.1.1.2:53]
2023/03/05 05:14:16 [Debug] app/dns: DNS cache is disabled. Querying IP for www.instagram.com at TCP//1.1.1.2:53
2023/03/05 05:14:16 [Debug] app/dns: TCP//1.1.1.2:53 querying DNS for: www.instagram.com.
2023/03/05 05:14:16 DNS accepted tcp:1.1.1.2:53 [dns-in1 -> b652fcb608684457a32cd801c5999d56]
2023/03/05 05:14:16 [Info] app/dispatcher: taking detour [b652fcb608684457a32cd801c5999d56] for [tcp:1.1.1.2:53]
2023/03/05 05:14:16 [Info] transport/internet/tcp: dialing TCP to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Debug] transport/internet: dialing to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Debug] [2428961755] proxy/dokodemo: processing connection from: 100.114.2.118:53624
2023/03/05 05:14:16 [Info] [2428961755] proxy/dokodemo: received request for 100.114.2.118:53624
2023/03/05 05:14:16 100.114.2.118:53624 accepted tcp:1.1.1.2:53 [tcp_redir >> b652fcb608684457a32cd801c5999d56]
2023/03/05 05:14:16 [Info] [2428961755] app/dispatcher: default route for tcp:1.1.1.2:53
2023/03/05 05:14:16 [Info] [2428961755] transport/internet/tcp: dialing TCP to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Debug] transport/internet: dialing to tcp:point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Info] proxy/trojan: tunneling request to tcp:1.1.1.2:53 via point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Info] [2428961755] proxy/trojan: tunneling request to tcp:1.1.1.2:53 via point-a.point.mysynology.net:20001
2023/03/05 05:14:16 [Info] app/dns: TCP//1.1.1.2:53 got answer: www.instagram.com. TypeA -> [157.240.235.174] 133.254923ms
2023/03/05 05:14:27 [Info] [2428961755] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled**
</details>

**Comment by xiaorouji** [comment]
我没有用nftables，我用的iptables应该是正常的。
用命令行输入 /etc/init.d/passwall restart 看看

**Comment by xcyll** [comment]
<details>
<summary>执行命令后</summary>

**<summary> OpenWrt SNAPSHOT, r0-57f2d47
 -----------------------------------------------------
root@OpenWrt:~# /etc/init.d/passwall restart
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} ip daddr 198.18.0.0/16 counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @shuntlist counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @blacklist counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr != @chnroute counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected counter
add rule inet fw4 PSW ip protocol tcp -s {192.168.1.149} counter return comment "cfg1330ec"
                                                         ^^^^^^^
Error: syntax error, unexpected counter
add rule inet fw4 PSW_MANGLE ip protocol udp -s {192.168.1.149} counter return comment "cfg1330ec"**
</details>

**Comment by xcyll** [comment]
> 我没有用nftables，我用的iptables应该是正常的。
> 用命令行输入 /etc/init.d/passwall restart 看看

<details>
<summary>执行命令后</summary>

**<summary> OpenWrt SNAPSHOT, r0-57f2d47
 -----------------------------------------------------
root@OpenWrt:~# /etc/init.d/passwall restart
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} ip daddr 198.18.0.0/16 counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @shuntlist counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr @blacklist counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected -
add rule inet fw4 PSW -s {192.168.1.149} tcp dport {22,25,53,143,465,587,853,993,995,80,443} ip daddr != @chnroute counter redirect to :1041 comment "cfg1330ec"
                      ^
Error: syntax error, unexpected counter
add rule inet fw4 PSW ip protocol tcp -s {192.168.1.149} counter return comment "cfg1330ec"
                                                         ^^^^^^^
Error: syntax error, unexpected counter
add rule inet fw4 PSW_MANGLE ip protocol udp -s {192.168.1.149} counter return comment "cfg1330ec"**
</details>

**Comment by xiaorouji** [comment]
@xcyll 嗯 我大概知道问题了

**Comment by xiaorouji** [comment]
@xcyll 试一下最新的代码

**Comment by xh0823** [comment]
> @xcyll @xh0823试一下最新的代码

谢谢大佬 刚刚测试把基本设置成不代理，访问控制里面生效了

**Comment by xcyll** [comment]
> @xcyll @xh0823 试一下最新的代码

Now it runs normally,
thanks! 🎉

**Comment by handsomeji** [comment]
这个需求也拖得有点久了，最近工作之余有时间的话会优先处理这个需求。

**Comment by xcyll** [comment]
目前**访问控制**里选择节点后，过滤模式只有2种，大佬能把另外2种加上吗 方便套自定义DNS使用
@xiaorouji

**Comment by xcyll** [comment]
![IMG_03048](https://user-images.githubusercontent.com/63227888/223017895-f3b4258b-19ca-4dd2-95fb-cfa9aac34877.jpg)

**Comment by handsomeji** [comment]
加不了 只能用socks

**Comment by xcyll** [comment]
socks吗 我试试 之前没用过这种方案

**Comment by xcyll** [comment]
这样设置可行  socks主开关需要打开吗？
![IMG_0249](https://user-images.githubusercontent.com/63227888/223028128-b8c1edd2-1d67-4354-9266-dde683e8df89.jpg)

**Comment by handsomeji** [comment]
不支持自定义dns 访问控制不能搞太复杂

**Comment by xcyll** [comment]
👌

**Comment by handsomeji** [comment]
@virxpx 试下用 `luci-acl-dev` 分支测试下

**Comment by SakuraFallingMad** [comment]
之前的源码不能实现“访控主机仅不转发某端口“的问题，如图：
![image](https://user-images.githubusercontent.com/31793080/223142334-49bcb3a8-eff7-451a-a0ac-7f04a0011519.png)，子机显示connection refused
不知luci-acl-dev里修复实现了没有。
否则只能用现在这样的访控需求，想更细化下。
![image](https://user-images.githubusercontent.com/31793080/223142866-3c73a45a-2cee-4aef-b3ed-74524ed611ec.png)
![image](https://user-images.githubusercontent.com/31793080/223142926-a2616b73-e91e-4229-9d46-0dccb3e921b9.png)
