### ISSUE TITLE
[Bug]: 自动切换中通过关键字添加、删除备用列表功能失效

### ISSUE THREAD

**Issue by ted-zheng** [xiaorouji/openwrt-package#2310]
### 描述您遇到的bug

自动切换中通过关键字添加、删除备用列表功能失效，输入关键字添加或者删除都不能增加或者减少备用列表，每次列表有变化都只能一个个手动添加

### 复现此Bug的步骤

多次重新编译最新版固件都是这样

### 您想要实现的目的

希望有大神修复这个功能

### 日志信息

日志无记录

### 截图

![image](https://user-images.githubusercontent.com/45898071/218695467-1c1b5ed7-adce-4c90-9105-2256b59106fe.png)

### 系统相关信息

luci-app-passwall	4.58
Google Chrome版本 110.0.5481.77（正式版本） （64 位）

**Comment by WYC-2020** [comment]
那玩意是快速 添加和删除用的，亲测没有任何问题

**Comment by ted-zheng** [comment]
> 那玩意是快速 添加和删除用的，亲测没有任何问题

为什么我的不行呢

**Comment by SakuraFallingMad** [comment]
其实我也不行，immortalwrt openwrt 21.02分支的

**Comment by WYC-2020** [comment]
那就不知道你们怎么玩的了哈哈

**Comment by ted-zheng** [comment]
> 其实我也不行，immortalwrt openwrt 21.02分支的

我现在是(https://github.com/openwrt/openwrt)master分支，也有换别的分支试过，都不行

**Comment by handsomeji** [comment]
可能是js luci的兼容性问题，等我有空测试一下

**Comment by handsomeji** [comment]
最新源码已修复，目前准备（可能）打算重写一套通用的自动切换逻辑。
另外个人觉得js luci还是不好用。。。尤其是改了那个ubus的uci，节点一多渲染就会非常慢。
