### ISSUE TITLE
x86_64固件的passwall现在没有XTLS流控，能不能加入XTLS流控.

### ISSUE THREAD

**Issue by hymslien** [xiaorouji/openwrt-package#2312]
### 描述你想要的新功能

x86_64固件的passwall现在没有XTLS流控，能不能加入XTLS流控.

### 描述你想要的解决方案

x86_64固件的passwall现在没有XTLS流控，能不能加入XTLS流控.

**Comment by Gzxhwq** [comment]
请使用xtls-rprx-vision流控，其他流控方式已经被官方废弃，且可能会在下个版本移除

https://github.com/XTLS/Xray-core/releases/tag/v1.7.5

**Comment by hello-yunshu** [comment]
不是有的嘛？😳
