### ISSUE TITLE
[Bug]: 无法订阅

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [xiaorouji/openwrt-package#2316]
### 描述您遇到的bug

订阅是弹出这个提示：

No page is registered at '/admin/services/passwall/log'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

### 复现此Bug的步骤

订阅的时候弹出这个

### 您想要实现的目的

解决无法正常订阅

### 日志信息

订阅是弹出这个提示：

No page is registered at '/admin/services/passwall/log'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

### 系统相关信息

passwall-4.59-2

**Comment by handsomeji** [comment]
提示说什么就按提示的操作

**Comment by xiangfeidexiaohuo** [comment]
> 提示说什么就按提示的操作

 操作的 依旧啊
