### ISSUE TITLE
[Bug]: 打开passwall 下面提示获取中，然后跳转至404

### ISSUE THREAD

**Issue by ChangAnCN** [xiaorouji/openwrt-package#2323]
### 描述您遇到的bug

404 未找到
对不起，请求的目标未找到。

No page is registered at '/admin/services/cgi-bin/luci'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

无法调度: /cgi-bin/luci/admin/services/cgi-bin/luci

出现以上提示

### 复现此Bug的步骤

openwrt原生镜像 换源后下载passwall
打开passwall
下面提示获取中
跳转至404页面

若在获取结束前选择其他标签页 则不会跳转至404

### 您想要实现的目的

bug得以修复，但貌似没有其他人遇到此状况

### 日志信息

日志为空

### 系统相关信息

passwall 版本：
git-24.048.45459-a74f834

**Comment by handsomeji** [comment]
跟提示做 不行就重启
