### ISSUE TITLE
[Bug]: 为什么在openwrt作为旁路由使用passwall时，部分设备无法科学上网？

### ISSUE THREAD

**Issue by heruxiaofu** [xiaorouji/openwrt-package#2329]
### 描述您遇到的bug

纯小白，在supes.top弄的固件。
一开始的时候一切正常，但是过一段时间就会出现一部分设备无法科学上网的情况。表现为手机可以科学上网，但是电脑不能科学上网。在我修改电脑的的dns服务器之后便可以科学上网。
但过一段时间又不能科学上网了。

### 复现此Bug的步骤

1，仅仅是等待一段时间就会出现

### 您想要实现的目的

希望明白有可能是什么地方出了问题

### 日志信息

不懂

### 系统相关信息

R2S
luci-app-passwall | git-24.048.45459-a74f834

**Comment by microdockman** [comment]
可以再搞个旁路由
192.168.1.1 主路由
192.168.1.10 旁路由（开passwall）
192.168.1.11 旁路由 （不开passwall）
让不能科学的设备从192.168.1.11 上网

查看tcp节点日志会有  192.168.1.10:xx(开passwall的旁路由) accepted tcp:xxx.xxx.xxx.xxx:443 这种记录，然后就会连接不正常

加一个旁路由后就没有上述记录，目前这俩月正常

**Comment by heruxiaofu** [comment]
accepted tcp:
然而我没有在tcp日志上看到这个记录

**Comment by handsomeji** [comment]
FAQ

**Comment by andyjm616** [comment]
也是一样出现此问题，同求解
