### ISSUE TITLE
[Feature Request]: 希望能够恢复以前的DNS无过滤模式

### ISSUE THREAD

**Issue by fangjia052** [xiaorouji/openwrt-package#2332]
### 描述你想要的新功能

现在smartdns和mosdns都能独立完成分流了，可以不需要passwall分流了，强烈建议恢复以前的无过滤模式。现在没有无过滤选项，还需要把passwall中dns填写跟dnsmasq上游一致，多一次分流没有必要。

### 描述你想要的解决方案

恢复以前的无过滤模式，只在dnsmasq填写smartdns或mosdns为上游，让dns分流交由它们完成。

**Comment by handsomeji** [comment]
dns分流没有你想的那么简单。还需要考虑ipset nftset分流，用代理去请求远程DNS等因素。

**Comment by GhostStar** [comment]
现在 AdGuard Home 已经支持分流以及 ipset 的功能，希望增加一个以前的 DNS 无过滤选项交由 AdGuard 进行处理，避免 DNS 多次转发的情况，另外在多次转发的时候 AdGuard Home 难以记录局域网内对应的客户端地址不太好做内网的 DNS 请求审计
