### ISSUE TITLE
[Bug]: 谷歌连接测试、github连接测试，测试的不是路由是不是连接正常

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-package#2339]
### 描述您遇到的bug

以前的版本，不记得是哪个时间的。如果我在外面（非这台路由器下面的网络）登录上路由上点测试，路由可以正常出国的话，会显示测试出的时间，但现在的版本点了以后一直会显示检测中。

### 复现此Bug的步骤

1.基本设置
2.谷歌连接
3.点我测试
4.检测中......

### 您想要实现的目的

点这个测试是测试路由器是否可以正常访问谷歌，github，Instagram。而不是登录路由器管理界面的这台电脑是不是可以正常访问谷歌，github，Instagram。

### 日志信息

无日志

### 截图

![image](https://user-images.githubusercontent.com/61368564/221423356-8a7e2b91-7962-4bee-bca9-52f436f846b1.png)

### 系统相关信息

passwall版本：4.59-2
chrome版本：102.0.5005.167

**Comment by handsomeji** [comment]
路由器本机请求的

**Comment by 13071558875** [comment]
我也有这个问题是不是无法解决
