### ISSUE TITLE
passwall用什么方案解决DNS泄露最好？

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#2341]
### 描述你想要的新功能

用https://ipleak.net/检测，默认设置会泄露DNS，如过滤模式通过TCP请求DNS，请教一下简单易行的解决办法。谢谢！

### 描述你想要的解决方案

请教一下简单易行的解决办法

**Comment by handsomeji** [comment]
使用非全局代理都基本会漏，这是因为规则问题，规则和ip是不完全的。
btw, 可设置默认（不在规则列表内的域名）的DNS走远程DNS。这样可以解决很多泄露问题，但是访问国内部分没有在规则内的网站会有问题。

**Comment by gnz1123** [comment]
> 使用非全局代理都基本会漏，这是因为规则问题，规则和ip是不完全的。 btw, 可设置默认（不在规则列表内的域名）的DNS走远程DNS。这样可以解决很多泄露问题，但是访问国内部分没有在规则内的网站会有问题。

请教btw是什么？

**Comment by keboge** [comment]
btw=by the way
