### ISSUE TITLE
[Bug]: 最新源码配合ChinaDNS-NG使用会导致某些域名解析较慢

### ISSUE THREAD

**Issue by W-Y-99** [xiaorouji/openwrt-package#2350]
### 描述您遇到的bug

标题中所说的“某些域名”是指：既不在gfwlist，也不在Chnlist的域名，在这两个列表中的任意域名都不受影响

具体情况：
如果同时开启“过滤代理域名 IPv6”和“ChinaDNS-NG”，则解析非常慢，Windows CMD用nslookup测试会出现以下提示
DNS request timed out.
    timeout was 2 seconds.

如果只开“ChinaDNS-NG”，不开“过滤代理域名 IPv6”，则解析速度会快一些，但还是有点慢

如果关掉“ChinaDNS-NG”，不管开不开“过滤代理域名 IPv6”，解析速度都非常快

使用的是Lienol大佬21.02源码编译的，上个月的源码编译没有这种问题，我已经刷回去测试过了。

另外，Lienol大佬21.02源码更新到了dnsmasq2.89，passwall这边似乎对ChinaDNS-NG也有更新和改动，目前暂时无法确定是哪边的问题。

### 复现此Bug的步骤

同上

### 您想要实现的目的

优化

### 日志信息

无

### 系统相关信息

4.59

**Comment by xcyll** [comment]
- 最新源码好像故障了 设置如下

基本设置-模式-都选不代理
访问控制里指定设备代理
---结果指定设备代理失败 不能访问代理域名了

**Comment by W-Y-99** [comment]
又来回测试了一下，上面的说的问题依旧复现，但老版本也不完全是没问题的，具体是这样：

我自己有一个域名用于ddns三个不同地点的宽带，方便随时远程桌面（具体域名暂时不方便发这里），由于是私人域名，他肯定不在gfwlist中，也不会在Chnlist中，并且两个列表我也查询过了确实没有。

然后我发现，如果打开了ChinaDNS-NG、过滤代理域名 IPv6，ping测试这样的域名，敲下回车键后，会卡半秒到一秒的样子（最新源码甚至卡2秒以上），无论是在PC还是通过ssh上软路由测试，都有这种情况，关了ChinaDNS-NG后，ping测试敲下回车键秒响应。由于可能受dns缓存影响，我特地在dnspod添加了多个不同的子域名用于测试，问题还是能复现出来的。

另外，我也尝试使用了adguardhome，因为有可视化面板，方便分析问题。使用后发现，每次有卡顿的ping请求，在adguard后台查看记录，解析耗时都不超过20ms。

之后，我尝试使用dig命令直接去测试ChinaDNS-NG的15354端口，发现也是秒响应的，所以问题应该不是出在ChinaDNS-NG上，怀疑是passwall程序内部对这种即不在黑名单、也不在白名单的域名处理逻辑有点问题。

这个情况虽然说无伤大雅，但强迫症表示很难受，希望作者有空时能帮忙看看，非常感谢。 @xiaorouji 🤗

**Comment by Jonnyan404** [comment]
节点是域名的情况下,在lede源码编译后,
首次直接不可用,
如果有IP节点连接过一次以后,会恢复正常.

**Comment by wtfr-dot** [comment]
chinadns-ng最大的问题是无法防污染和dns泄露，按照它的逻辑，不在黑白名单的dns会向所有上游dns服务器进行查询，如果passwall默认是直连，如果查询的是国内dns，那么没有问题，如果是国外dns，则只会向国内dns查询，造成dns泄露，由于国内运营商dns劫持，大量的虚假ip响应，访问的网页会出现安全警告，我之前就出现过这种情况，如果passwall默认设置是代理，则你查询的国内dns会被外网dns解析，按vps代理安全原则，国内ip应该blocked，如果server里有此设置，则此查询得不到响应，如果你没有设置，则会返回查询结果，但往往查询时间会变长，卡顿是否是因为这个原因呢？
我短暂的使用过chinadns-ng，体验都不是很好，基本上都使用的smartdns，使用效果良好，新的smartdns分支简化了smartdns设置，非常建议使用smartdns，能最大程度防止dns污染

**Comment by ChenXi599** [comment]
好像确实有这种情况，但我是这样：
lean源码，过滤IPv6开启，ChinaDNS-NG开启，也是黑名单和白名单同时都不存在的域名，自己在阿里云买的6位数字xyz，用来ddns的。
用dig命令直接去测53端口和ChinaDNS-NG的15354端口，返回结果都很快，但用ping去测就会卡一小会，测了几个子域都一样，不知道实际使用时会有影响吗？
按照ChinaDNS-NG的原理来看，如果国内dns返回结果是国内ip，应该是立即返回给客户端的，如果返回的是国外ip，则丢弃等待可信dns返回结果。不知道ping的时候会卡一会是为什么，dig却很快，ChinaDNS-NG关了再测ping也很快。

**Comment by wtfr-dot** [comment]
如果你仅仅是要处理自己的域名解析，将它写入白名单直连就行了，我就是这样处理的。我编译固件的时候直接就去掉了ipv6，所以对ipv6的影响没有感知。
另外lean的源码从前几个月开始mwan3出现了问题（我还专门提交了bug），包括passwall也会出现使用一段时间部分网站无法解析，需要清空ipset（是否是lean源码问题无从验证），我现在已经转向op官方源码编译了，目前用稳定版编译使用起来还不错。

**Comment by wtfr-dot** [comment]
> 好像确实有这种情况，但我是这样： lean源码，过滤IPv6开启，ChinaDNS-NG开启，也是黑名单和白名单同时都不存在的域名，自己在阿里云买的6位数字xyz，用来ddns的。 用dig命令直接去测53端口和ChinaDNS-NG的15354端口，返回结果都很快，但用ping去测就会卡一小会，测了几个子域都一样，不知道实际使用时会有影响吗？ 按照ChinaDNS-NG的原理来看，如果国内dns返回结果是国内ip，应该是立即返回给客户端的，如果返回的是国外ip，则丢弃等待可信dns返回结果。不知道ping的时候会卡一会是为什么，dig却很快，ChinaDNS-NG关了再测ping也很快。

我的理解是你直接dig端口相当于绕过了passwall，正常的流量是首先经过passwall的过滤处理再流向其它模块，chinadns-ng的国内dns和可信dns解析结果需要采用者自己进行选择，比如抢答模式和公平模式的选择问题等等，这容易造成不确定结果，我觉得最简单和安全的办法就是国外的ip一律走代理，特别是对当前的网络环境而言很重要，虽然会影响部分部分国外网站的访问（passwall也已经将部分常用国外网站进行了直连处理）

**Comment by uingei** [comment]
好像跟ChinaDNS-NG没关系，如果openclash也装了(但不启用)，看openclash的IP Address和Website Access Check状态也不太正常，好像就最近的代码有这毛病，几天前还好好的

**Comment by handsomeji** [comment]
更新最新的luci源码和chinadns-ng新版本试试

**Comment by doge2mars** [comment]
我的passwall开启chinadns-ng后，油管解析不了，有时非常长时间了才解析，关了先把持直连DNS就一切正常了
