### ISSUE TITLE
[Bug]: 规则列表修改后不会立即生效

### ISSUE THREAD

**Issue by minico** [xiaorouji/openwrt-package#2351]
### 描述您遇到的bug

规则列表修改后，点击 “保存应用” 按钮，提示 “没有待应用的更改”，好像需要手动重启 psw 才生效（先禁用然后再启用）。

### 复现此Bug的步骤

规则列表修改后，点击 “保存应用” 按钮，提示 “没有待应用的更改”。

### 您想要实现的目的

规则列表修改后，点击 “保存应用” 按钮，能保存修改，立即生效。

### 日志信息

无

### 系统相关信息

最新版本。

**Comment by xcyll** [comment]
这个一直这样 helloworld也是这样的
不清楚是不是bug
要么随PW其他设置一起启用后生效，要么就直接重启PW后生效

**Comment by xcyll** [comment]
这个一直这样 helloworld也是这样的

**Comment by xcyll** [comment]
不清楚是不是bug
要么随PW其他设置一起启用后生效，要么就直接重启PW后生效

**Comment by handsomeji** [comment]
这是 js luci的问题

**Comment by WYC-2020** [comment]
这luci  就是有bug,现在直接lede配合
![image](https://user-images.githubusercontent.com/34025388/224484518-9844278e-dbcf-47e4-95ab-4f4415cd9af3.png)
这个位置的全部失效根本就没法修改，保存都没用，感觉应该吧luci 分开适配别全部揉在一起

**Comment by xcyll** [comment]
> 这是 js luci的问题

so , got it !
的确我用的是 js luci

**Comment by xcyll** [comment]
> 这luci 就是有bug,现在直接lede配合 ![image](https://user-images.githubusercontent.com/34025388/224484518-9844278e-dbcf-47e4-95ab-4f4415cd9af3.png) 这个位置的全部失效根本就没法修改，保存都没用，感觉应该吧luci 分开适配别全部揉在一起

反正现在这里的更新设置我是勾选后 直接手动更新 就生效了
而不是选择保存应用

**Comment by WYC-2020** [comment]
> > 这luci 就是有bug,现在直接lede配合 ![image](https://user-images.githubusercontent.com/34025388/224484518-9844278e-dbcf-47e4-95ab-4f4415cd9af3.png) 这个位置的全部失效根本就没法修改，保存都没用，感觉应该吧luci 分开适配别全部揉在一起
> 
> 反正现在这里的更新设置我是勾选后 直接手动更新 就生效了 而不是选择保存应用

刚发现了，但是这样感觉并不合理

**Comment by WYC-2020** [comment]
> > 这luci 就是有bug,现在直接lede配合 ![image](https://user-images.githubusercontent.com/34025388/224484518-9844278e-dbcf-47e4-95ab-4f4415cd9af3.png) 这个位置的全部失效根本就没法修改，保存都没用，感觉应该吧luci 分开适配别全部揉在一起
> 
> 反正现在这里的更新设置我是勾选后 直接手动更新 就生效了 而不是选择保存应用

看代码 确实只有在更新哪里的时候才会进行保存，个人不喜欢这样，算了我自己改下

**Comment by minico** [comment]
> > > 这luci 就是有bug,现在直接lede配合 ![image](https://user-images.githubusercontent.com/34025388/224484518-9844278e-dbcf-47e4-95ab-4f4415cd9af3.png) 这个位置的全部失效根本就没法修改，保存都没用，感觉应该吧luci 分开适配别全部揉在一起
> > 
> > 
> > 反正现在这里的更新设置我是勾选后 直接手动更新 就生效了 而不是选择保存应用
> 
> 看代码 确实只有在更新哪里的时候才会进行保存，个人不喜欢这样，算了我自己改下

请教下，自己改的话这个是怎么改啊？

**Comment by handsomeji** [comment]
最新源码已做兼容
