### ISSUE TITLE
[Bug]: X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常

### ISSUE THREAD

**Issue by dfbucy090** [xiaorouji/openwrt-package#2359]
### 描述您遇到的bug

X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常，从去年7月份最后编译的5.15.50版本，hysteria还可以正常使用，包括32位机器，后来编译的32位都不能用，但是其它结构的正常，是不是32位太小众了，所以没有注意？

### 复现此Bug的步骤

每次编译后都用几个类型机器试用，结果去年7月份发现问题，passwall等其他几个app的hysteria插件都不能打开网页，后来认为过段时间就可以自动修复，但是目前状况还是如此。

### 您想要实现的目的

希望大佬能尽快解决这个BUG，虽然小众，但是机器还可以用，hysteria这个插件功能也很好。

### 日志信息

日志没有，就是打不开网页，也不崩溃，看着正常。

### 系统相关信息

32位机器

### 其他信息

X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常，从去年7月份最后编译的5.15.50版本，hysteria还可以正常使用，包括32位机器，后来编译的32位都不能用，但是其它结构的正常，是不是32位太小众了，所以没有注意？

每次编译后都用几个类型机器试用，结果去年7月份发现问题，passwall等其他几个app的hysteria插件都不能打开网页，后来认为过段时间就可以自动修复，但是目前状况还是如此。

**Comment by handsomeji** [comment]
用最新的Hysteria 1.3.4试一下REDIRECT模式是否已正常？

**Comment by dfbucy090** [comment]
> 用最新的Hysteria 1.3.4试一下REDIRECT模式是否已正常？

昨天更新的Hysteria 1.3.4，马上试验，已经正常了，谢谢。
