### ISSUE TITLE
[Bug]: 负载均衡，实际节点恢复后，负载均衡里面节点不恢复

### ISSUE THREAD

**Issue by jxph1123** [xiaorouji/openwrt-package#2367]
### 描述您遇到的bug

负载均衡，实际节点恢复后，负载均衡里面节点不自动恢复，需要手动重启负载均衡才能恢复。

### 复现此Bug的步骤

1.节点使用的是trojan，用trojan-go和xray都一样，实际节点掉线，负载均衡里面节点掉线。
2.实际节点恢复（有可能服务端更换了IP），负载均衡里面节点不恢复。
3.手动重启负载均衡，负载均衡里面节点恢复正常。

### 您想要实现的目的

实际节点恢复后，负载均衡里面节点自动恢复。

### 日志信息

日志显示正常

### 截图

![image](https://user-images.githubusercontent.com/35351787/224211933-9f8eb229-f2e2-452f-841a-5b37297f1838.png)

实际节点可用

![image](https://user-images.githubusercontent.com/35351787/224211989-fa2f6e72-51a5-4eee-977a-6a4ddfa15a39.png)

smartdns解析

![image](https://user-images.githubusercontent.com/35351787/224212220-cb91ce98-f914-41e6-a2b4-812f318e8017.png)

### 系统相关信息

节点类型：trojan ，passwall使用trojan-go和xray都是一样问题。
passwall版本：c60461ffa35c77fcce3c1475ee685f6249b63b6d
haproxy版本：https://github.com/coolsnowwolf/packages/commits/master/net/haproxy  v2.6.6  （换了V2.6.9 V2.2.22 V1.8.15几个版本现象一样。）
DNS采用smartdns解析：https://github.com/pymumu/smartdns   Release 41

**Comment by jxph1123** [comment]
破案了，要用luci-smartdns-new-version里面的smartdns才行，如果用默认passwall版本，自己配置smartdns，其余科学没问题，就负载均衡异常。

**Comment by jxph1123** [comment]
用luci-smartdns-new-version一样效果，只要节点红了就恢复不了了，必须重启passwall。
应该是服务端更换了IP的原因，域名和加密都没变。。但是负载均衡没有刷新最新的IP，大佬能解决吗，谢谢~~

**Comment by hujiao80** [comment]
建议检查一下是不是后台的xray进程挂掉了，passwall的后台线路检查只要进程还活着，不管线路实际通不通，都不会认为线路下线了

**Comment by jxph1123** [comment]
进程没有挂，我观察了几天，应该是节点服务器被墙了后，更换了ip，但是域名没变，而haproxy没有刷新域名ip，以为下线了，所以就不通了。重启下passwall刷新了ip就又通了。

**Comment by jxph1123** [comment]
我改了下，/usr/share/passwall/app这里面，修改了一些代码。

```
		defaults
		    mode                    tcp
		    log                     global
		    option                  tcplog
		    option                  dontlognull
		    option http-server-close
		    #option forwardfor       except 127.0.0.0/8
		    option                  redispatch
		    retries                 2
		    timeout http-request    10s
		    timeout queue           1m
		    timeout connect         10s
		    timeout client          1m
		    timeout server          1m
		    timeout http-keep-alive 10s
		    timeout check           10s
		    maxconn                 3000
                 
		    **#增加dns查询
		    resolvers mydns
		    nameserver dns1 127.0.0.1:53
		    timeout resolve       2m
		    hold valid            2m**
......
		cat <<-EOF >> "${haproxy_file}"
			    server $remark:$bport $bip:$bport weight $lbweight check **resolvers mydns** inter 1500 rise 1 fall 3 $bbackup
		EOF
```


图中加粗的为修改的地方，在带smartdns的版本运行正常，2分钟检查一次服务器的域名，不知道改得对不对。有没有大神优化下，然后PR。谢谢~~

**Comment by jxph1123** [comment]
我改了下，/usr/share/passwall/app这里面，修改了一些代码。

		defaults
		    mode                    tcp
		    log                     global
		    option                  tcplog
		    option                  dontlognull
		    option http-server-close
		    #option forwardfor       except 127.0.0.0/8
		    option                  redispatch
		    retries                 2
		    timeout http-request    10s
		    timeout queue           1m
		    timeout connect         10s
		    timeout client          1m
		    timeout server          1m
		    timeout http-keep-alive 10s
		    timeout check           10s
		    maxconn                 3000
                 
		    **#增加dns查询
		    resolvers mydns
		    nameserver dns1 127.0.0.1:53
		    timeout resolve       2m
		    hold valid            2m**
......
		cat <<-EOF >> "${haproxy_file}"
			    server $remark:$bport $bip:$bport weight $lbweight check **resolvers mydns** inter 1500 rise 1 fall 3 $bbackup
		EOF



图中加粗的为修改的地方，在带smartdns的版本运行正常，2分钟检查一次服务器的域名，不知道改得对不对。有没有大神优化下，然后PR。谢谢~~

**Comment by jxph1123** [comment]
我改了下，/usr/share/passwall/app这里面，修改了一些代码。

```
		defaults
		    mode                    tcp
		    log                     global
		    option                  tcplog
		    option                  dontlognull
		    option http-server-close
		    #option forwardfor       except 127.0.0.0/8
		    option                  redispatch
		    retries                 2
		    timeout http-request    10s
		    timeout queue           1m
		    timeout connect         10s
		    timeout client          1m
		    timeout server          1m
		    timeout http-keep-alive 10s
		    timeout check           10s
		    maxconn                 3000
                 
		    #增加dns查询
		    resolvers mydns
		    nameserver dns1 127.0.0.1:53
		    timeout resolve       2m
		    hold valid                2m
        ............
	 	cat <<-EOF >> "${haproxy_file}"
			    server $remark:$bport $bip:$bport weight $lbweight check resolvers mydns inter 1500 rise 1 fall 3 $bbackup
		EOF         ...........#resolvers mydns 增加dns检查

```
图中#为修改的地方，在带smartdns的版本运行正常，2分钟检查一次服务器的域名，不知道改得对不对。有没有大神优化下，然后PR。谢谢~~

**Comment by jxph1123** [comment]
以上修改来自于haproxy官方文档，水平有限，希望大佬能优化下，谢谢~~
http://docs.haproxy.org/2.6/configuration.html#5.3
