### ISSUE TITLE
[Bug]: 关于feeds.conf.default里添加源的问题

### ISSUE THREAD

**Issue by naoki66** [xiaorouji/openwrt-package#2372]
### 描述您遇到的bug

  make menuconfig 里依旧找不到 luci-app-passwall

### 复现此Bug的步骤

添加源码feeds.conf.default里添加
src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall.git;luci
src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall.git;packages

然后执行./scripts/feeds update -a  &&  ./scripts/feeds install -a后正常正常输出
Create index file './feeds/passwall_luci.index'
Create index file './feeds/passwall_packages.index'
但是   make menuconfig 里依旧找不到 luci-app-passwall

### 您想要实现的目的

源编译里能够找到luci-app-passwall

### 日志信息

Create index file './feeds/passwall_luci.index'
Create index file './feeds/passwall_packages.index'
Collecting package info: done
Collecting target info: done

### 系统相关信息

commit id 8573a91eaebc868e0eb22bb4db761f4b1f4bf716

**Comment by xcyll** [comment]
直接丢到package目录下就行

**Comment by naoki66** [comment]
> 直接丢到package目录下就行

这就失去了随上游更新的能力

**Comment by xcyll** [comment]
可以参考下helloworld 那边 有添加说明

**Comment by xcyll** [comment]
各种方案 选个

**Comment by gito10** [comment]
不是添加到feeds.conf.default，是把这个文件复制为feeds.conf，然后把第三方源添加到这里面。

**Comment by firkerword** [comment]
> > 直接丢到package目录下就行
> 
> 这就失去了随上游更新的能力

云编译吧  没这种烦恼  本地的话git pull

**Comment by dover** [comment]
> 直接丢到package目录下就行

git clone 到package目录下，make menuconfig 里依旧找不到 passwall

**Comment by naoki66** [comment]
> > > 直接丢到package目录下就行
> > 
> > 这就失去了随上游更新的能力
> 
> 云编译吧  没这种烦恼  本地的话git pull

云编译太慢了。加缓存也要1.5小时。
