### ISSUE TITLE
[Bug]: 升级到最新版，xray分流的前置代理无法启用

### ISSUE THREAD

**Issue by aisuyi065** [xiaorouji/openwrt-package#2373]
### 描述您遇到的bug

关掉前置代理，都正常连接的上去

![微信截图_20230312194415](https://user-images.githubusercontent.com/44740975/224542461-bdfcc1d8-9176-4cf5-9178-1fa2cd9bd2d5.png)
![微信截图_20230312194359](https://user-images.githubusercontent.com/44740975/224542465-cf9c884e-648f-45e7-9915-9265866e679e.png)
![微信截图_20230312194509](https://user-images.githubusercontent.com/44740975/224542467-682c9aa6-1fc1-4109-be33-85f3f9dc4066.png)

### 复现此Bug的步骤

修复

### 您想要实现的目的

修复

### 日志信息

修复

### 系统相关信息

修复

**Comment by Gzxhwq** [comment]
是vision吗？是的话是故意的。

https://github.com/XTLS/Xray-core/issues/1612#issuecomment-1418880212

**Comment by handsomeji** [comment]
已使用其它手段支持，请更新最新代码后测试

**Comment by breakings** [comment]
> 已使用其它手段支持，请更新最新代码后测试

借楼反馈个问题，目前使用最新的 pw，服务器用 xray 部署了 vision 流控，设置了双 dns 组，国外组转发给了 7913，连接一段时间后 youtube 无法播放，nslookup 检测正常解析， 换其它协议，如 trojan 和 naive 又完全表现正常，只要用 vless-tcp-vision 就必然复现，前几个版本是正常的，目前没有头绪是哪个环节出了问题。
