### ISSUE TITLE
[Bug]: "显示日志" 页面无日志内容输出

### ISSUE THREAD

**Issue by duanwt1983** [xiaorouji/openwrt-package#2374]
### 描述您遇到的bug

升级到最新版本后，“显示日志”页面没有日志输出，在系统日志里面看到有报错信息，固件版本：OpenWrt R23.3.3 / LuCI Master  ，web服务器用nginx-ssl ，同个固件版本在3.9号时还是正常的

### 复现此Bug的步骤

选择 “规则管理” -- “手动更新” 自动跳转到 “查看日志” 页面中，但无任何信息输出

### 您想要实现的目的

bug修复

### 日志信息

Mon Mar 13 17:54:47 2023 daemon.err nginx[1642]: 2023/03/13 17:54:47 [error] 1771#0: *616 upstream prematurely closed connection while reading response header from upstream, client: 192.168.6.105, server: _lan, request: "GET /cgi-bin/luci/admin/services/passwall/get_log?_=0.6588092425573646 HTTP/1.1", upstream: "uwsgi://unix:////var/run/luci-webui.socket:", host: "192.168.6.253", referrer: "https://192.168.6.253/cgi-bin/luci/admin/services/passwall/log"

### 系统相关信息

luci-app-passwall 版本：4.60-3

**Comment by handsomeji** [comment]
建议还是用 uhttpd 作为默认luci的web服务端
