### ISSUE TITLE
[Bug]: 访问控制的UDP代理坏了

### ISSUE THREAD

**Issue by Gzxhwq** [xiaorouji/openwrt-package#2379]
### 描述您遇到的bug

访问控制下的机器UDP不通了

### 复现此Bug的步骤

1、访问控制
2、选定一台内网主机的mac地址进行单独控制
3、udp选全局，全端口转发，udp节点和tcp节点相同
4、使用节点类型是xray vision or h2 reality，应该和节点类型无关，非访问控制下正常

### 您想要实现的目的

访问控制下udp正常使用

### 日志信息

系统日志并没看到异常，

### 系统相关信息

passwall为最新版本https://github.com/xiaorouji/openwrt-passwall/commit/d628490238537cadf8487706f9c6cfee60aa9e4a
测试机器为一台switch游戏机和一台笔记本电脑，笔记本电脑使用NatTypeTester测试为UdpBlocked

**Comment by Gzxhwq** [comment]
已经查出是当TCP节点和UDP节点相同时，生成的xray配置文件的inbound不会监听udp端口导致

**Comment by handsomeji** [comment]
感谢反馈，已复现。有空会抽点时间去修复。
因为好久无打game了，所以没有发现这个问题。

**Comment by xcyll** [comment]
pubg mobile没另开udp代理 好像也可以玩 也许是走直连了吧

**Comment by Gzxhwq** [comment]
这个bug触发的话，udp是不通的，因为tproxy到了一个没开的端口上去了

**Comment by Gzxhwq** [comment]
好了
