### ISSUE TITLE
[Feature Request]: 为什么把我的jable.tv给block了？感觉这样很不人道啊。。。。。。

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2380]
### 描述你想要的新功能

第一次用。tcp节点直接选翻墙节点时，jable.tv上不去啊，必须用xray分流才行。到底是在哪一步给block了？
另外这块的dns内部处理的详细过程有没有相关文档或者博文介绍？还有各个配置项具体的含义。搜了一下感觉没搜到合适的。
比如这个就看不懂：
![image](https://user-images.githubusercontent.com/37928893/225556197-ef7a22ff-118a-49fa-9e26-120684e64157.png)
在中国列表外的dns查询不是应该放到远程节点去查询吗？
而且我远程的dns为什么要在这里给定义上？远程用什么dns不是应该由远程自己决定比较快吗？
感觉软路由或者是说透明代理这种最大的问题就是dns了，不像http代理根本不需要先本机发出dns请求。

### 描述你想要的解决方案

另外有没有简单的那种配置，就像windows的v2rayn，绕过大陆和局域网地址，这样的。
现在是如果不用xray分流就要使用其他去广告的。用了去广告的除了响应速度会慢一点外，油管用iphone看视频不能开画中画了。

**Comment by gg4924** [comment]
推荐尝试passwall2，设置简单，默认dns设置即可做到毫无dns泄露问题，用哪个地区的节点，就只会检测出节点所在地区的dns服务器。
绕过大陆和局域网，默认xray分流好像就自带的有，国内域名：geosite:cn，国内及私有IP：geoip:cn、geoip:private 位于直连规则即可，默认设置一个节点，还需要注意上下位置优先级的问题。其他规则不需要的可以直接删除。

**Comment by ghost** [comment]
> 推荐尝试passwall2，设置简单，默认dns设置即可做到毫无dns泄露问题，用哪个地区的节点，就只会检测出节点所在地区的dns服务器。
> 
> 绕过大陆和局域网，默认xray分流好像就自带的有，国内域名：geosite:cn，国内及私有IP：geoip:cn、geoip:private 位于直连规则即可，默认设置一个节点，还需要注意上下位置优先级的问题。其他规则不需要的可以直接删除。

passwall2不支持trojango，而且装上2后系统挂了一次，cpu飙高，跟1也有冲突导致所有节点翻不了。还是恢复系统搞好的

**Comment by jdnt** [comment]
感谢分享，楼主好人一生平安！
![image](https://user-images.githubusercontent.com/1711790/227395660-0d7a4ecf-c15a-4764-a921-2a93405362a5.png)
我在虚拟机里架了dns，用的是chinadns-ng+smartdns（国外https+tls），passwall版本4.60-5，reality。盲猜楼主的问题可能出在DNS上，换一个远程试试？

**Comment by ghost** [comment]
> 感谢分享，楼主好人一生平安！
> 
> ![image](https://user-images.githubusercontent.com/1711790/227395660-0d7a4ecf-c15a-4764-a921-2a93405362a5.png)
> 
> 我在虚拟机里架了dns，用的是chinadns-ng+smartdns（国外https+tls），passwall版本4.60-5，reality。盲猜楼主的问题可能出在DNS上，换一个远程试试？

请问你的可以访问jable.tv吗？肯定是dns的问题，用xray分流也访问不了，xray关闭ads功能根本也不起作用，它还是把广告给过滤了，只开dnsmasq的时候不过滤广告，但是jable也上不去，passwall竟然做了和谐网络的事情真是搞笑了。
xray有时候还需要重启否则翻不出去了。这个passwall设置成全局的时候也翻不出去。
openclash不支持naive，对ipv6支持也不好，用它的trojan速度反应也慢，跟节点没关系。哎真是感叹竟然没有一个好用的！我就想要简简单单的国内域名走直连，其他的都走代理，看来只有自己写了。

**Comment by jh0072110** [comment]
可以访问啊……
BTW：这站收藏了

**Comment by handsomeji** [comment]
当你质疑软件的时候，就不会自己找原因排除问题？连日志、版本号等信息也没有提供。

**Comment by ghost** [comment]
> 当你质疑软件的时候，就不会自己找原因排除问题？连日志、版本号等信息也没有提供。

我排除？你这是在掩耳盗铃吗？日志在哪给你提供啊！不是应该你虚心告诉人日志在哪贴上日志吗！我当然只负责反应问题！这个问题是你们确实存在的！这些都是你们破壁程序的bug，还有一堆bug没有提呢！有的已经有人提过了！比如开全局的时候根本连不上网！还有xray的问题修改几项配置再换回原来的设置就又连不上了！xray的ads关闭proxy关闭根本不起作用！我都把操作给你说清了你自己去照着操作啊！我tm真是贱啊费这时间跟你反应！既然做程序还怕被人说bug多？我提的几个问题都被你关了真是太好了，自己玩自己的吧！

**Comment by handsomeji** [comment]
> passwall竟然做了和谐网络的事情真是搞笑了。
> openclash不支持naive，对ipv6支持也不好，用它的trojan速度反应也慢，跟节点没关系。哎真是感叹竟然没有一个好用的！

你这种伸手党我们没有必要为你们提供任何服务。

**Comment by JIDIAN46656** [comment]
用浏览器自带的安全DNS就行了

**Comment by feifeidemaos** [comment]
补充个梯子[点击获取](https://sway.cloud.microsoft/wnzKv7AR8xVCtXyi)

**Comment by xwxyz** [comment]
**分享一个梯，速度快。不卡[速度快不开]**(https://dldsvip.xyz/share.html?channel=s3)
