### ISSUE TITLE
[Feature Request]: 问几个问题，开着xray分流的时候，还需要开着dnsmasq分流吗？

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2381]
### 描述你想要的新功能

才知道如何关闭dnsmasq
另外在lan口定义的dns是所有国内dns的上游吗？
《路由器本机 TCP 代理模式》具体指的是什么？

### 描述你想要的解决方案

no

**Comment by swxk521** [comment]
1.不想要dnsmasq，用passwall2，规则应该是dnsmasq优先处理，处理完后才到xray分流再处理一次。
     passwall2就直接xray，不过我用过，科学不稳定的话，开启自动切换会影响国内连接暂时断开。
       https://github.com/xiaorouji/openwrt-passwall2
2.我想你要改国内DNS的话，应该修改WAN口下发的DNS，改LAN口的DNS ，它应该会下发的你的客户端，如果openwrt防火墙 
    没有劫持53端口，那么你客户端就没有科学了。
3.路由本机代理应该是openwrt上的一些服务需不需要科学
有不对的大佬说下，我自己琢磨的。

**Comment by davidtall** [comment]
> 1.不想要dnsmasq，用passwall2，规则应该是dnsmasq优先处理，处理完后才到xray分流再处理一次。 passwall2就直接xray，不过我用过，科学不稳定的话，开启自动切换会影响国内连接暂时断开。 https://github.com/xiaorouji/openwrt-passwall2 2.我想你要改国内DNS的话，应该修改WAN口下发的DNS，改LAN口的DNS ，它应该会下发的你的客户端，如果openwrt防火墙 没有劫持53端口，那么你客户端就没有科学了。 3.路由本机代理应该是openwrt上的一些服务需不需要科学 有不对的大佬说下，我自己琢磨的。

是不是可以理解为，passwall1全局模式使用xray分流就等于passwall2 ? 我还是不太明白这两个版本之间的区别

**Comment by ghost** [comment]
> 1.不想要dnsmasq，用passwall2，规则应该是dnsmasq优先处理，处理完后才到xray分流再处理一次。
> 
>      passwall2就直接xray，不过我用过，科学不稳定的话，开启自动切换会影响国内连接暂时断开。
> 
>        https://github.com/xiaorouji/openwrt-passwall2
> 
> 2.我想你要改国内DNS的话，应该修改WAN口下发的DNS，改LAN口的DNS ，它应该会下发的你的客户端，如果openwrt防火墙 
> 
>     没有劫持53端口，那么你客户端就没有科学了。
> 
> 3.路由本机代理应该是openwrt上的一些服务需不需要科学
> 
> 有不对的大佬说下，我自己琢磨的。

各种bug罄竹难书 太难用了
