### ISSUE TITLE
[Bug]: 支持smartdns第二服务器的udp://127.0.0.1:6553吗

### ISSUE THREAD

**Issue by threerog** [xiaorouji/openwrt-package#2382]
### 描述您遇到的bug

我之前是使用的老版passwall
其中passwall里的dns分流设置为smartdns
远程DNS为通过udp模式请求smartdns第二服务器127.0.0.1:6553

现在更新最新版passwall好像没有请求模式的选项，而是直接类似于`tls://1.1.1.1`
那现在我升级到最新版后该如何更改远程DNS设置
我尝试这样`udp://127.0.0.1:6553` 但是行不通，国外网站无法访问，国内正常

### 复现此Bug的步骤

.....

### 您想要实现的目的

将老版passwall+smartdns升级到最新版本的passwall

### 日志信息

....

### 系统相关信息

passwall：4.60.4
openwrt：lede
smartdns：1.2023.41

**Comment by handsomeji** [comment]
不支持，以后也不会支持
