### ISSUE TITLE
[Feature Request]: 能不能在ui上增加版本显示

### ISSUE THREAD

**Issue by threerog** [xiaorouji/openwrt-package#2384]
### 描述你想要的新功能

能不能在ui上增加版本显示
方便快速知道当前插件版本

### 描述你想要的解决方案

能不能在ui上增加版本显示
方便快速知道当前插件版本

**Comment by gito10** [comment]
你是说的`luci-app-passwall`的版本，还是`ss`, `trojan`, `xray`这些代理软件的版本？

**Comment by jh0072110** [comment]
> 你是说的`luci-app-passwall`的版本，还是`ss`, `trojan`, `xray`这些代理软件的版本？

luci-psw吧 core版本都能“较容易”的看到啊

**Comment by threerog** [comment]
`luci-app-passwall`的

**Comment by gito10** [comment]
> `luci-app-passwall`的

有时候好多 commits 才更新一下版本号，luci又不像普通 package 可以添加 commit 的 HASH，所以是像 `4.60-4`这样就可以吗？
![image](https://user-images.githubusercontent.com/10704839/226546126-d2683102-3ffe-4eaa-92a8-25d670ba1a95.png)
感觉没什么地方好加，这里可以吗，感觉不太好
隐蔽一点的话，就这里，要点进 FAQ 里去看
![image](https://user-images.githubusercontent.com/10704839/226548175-509977a4-ec9f-482c-8a37-bc96d48203ca.png)

**Comment by threerog** [comment]
显示在组件更新里如何，相对合理一点
只显示版本，不显示更新按钮什么的

**Comment by threerog** [comment]
版本号只要跟makefile里的信息同步即可

**Comment by gito10** [comment]
> 显示在组件更新里如何，相对合理一点 只显示版本，不显示更新按钮什么的

想到一起去了，因为前几天我正好优化了更新组件的代码结构，可以很方便的添加，而且我刚刚想了一下，说不定真的可以实现passwall的自更新。
![image](https://user-images.githubusercontent.com/10704839/226553469-eab944e6-d8e3-4f49-bd5e-262386fcdd7f.png)

**Comment by threerog** [comment]
名称可以显示简称，`luci-app-passwall`太长了
Luci或者Core或者App或者Passwall

**Comment by threerog** [comment]
更完美的话也可以增加个菜单页`关于`
显示passwall的版本及描述以及开源地址，文档地址，bug反馈，开源赞助什么的

纯脑补，可忽略，哈哈

**Comment by gito10** [comment]
> 更完美的话也可以增加个菜单页`关于` 显示passwall的版本及描述以及开源地址，文档地址，bug反馈，开源赞助什么的
> 
> 纯脑补，可忽略，哈哈

就组件更新里很好，等会儿看能不能加个检测更新，只是个检测功能，检测到有新版了就可以手动去更新了。

**Comment by threerog** [comment]
> > 更完美的话也可以增加个菜单页`关于` 显示passwall的版本及描述以及开源地址，文档地址，bug反馈，开源赞助什么的
> > 纯脑补，可忽略，哈哈
> 
> 就组件更新里很好，等会儿看能不能加个检测更新，只是个检测功能，检测到有新版了就可以手动去更新了。

非常棒

**Comment by threerog** [comment]
@nftbty 版本显示有针对分支进行区分和处理吗，显示时能否显示对应的分支，否则分支间容易混乱

**Comment by gito10** [comment]
> @nftbty 版本显示有针对分支进行区分和处理吗，显示时能否显示对应的分支，否则分支间容易混乱

分支的功能完善稳定后，肯定是会合并的，所以那不是正常该考虑的，那就是引入某个新功能的开发测试版，临时拉出来的，而用这些分支的，就算是内测用户吧。
而且不管什么分支，编译完，运行的时候是没有任何指示当前版本是哪个分支的。

**Comment by nftbty** [comment]
而且我所有PR的功能更新都只推给了主分支，也就是说那些临时分支应该是没有检测版本的功能的。
