### ISSUE TITLE
[Feature Request]: 访问控制支持MAC源地址模糊范围匹配

### ISSUE THREAD

**Issue by threerog** [xiaorouji/openwrt-package#2385]
### 描述你想要的新功能

访问控制支持MAC源地址模糊范围匹配
使用场景
虚拟机或虚拟网卡，每次快照后mac地址或者ip都会变化，但是mac地址变化规律始终以`00:15:5D:05:xx:xx`开头
所以能不能支持mac地址的模糊匹配

### 描述你想要的解决方案

访问控制支持MAC源地址模糊范围匹配
使用场景
虚拟机或虚拟网卡，每次快照后mac地址或者ip都会变化，但是mac地址变化规律始终以`00:15:5D:05:xx:xx`开头
所以能不能支持mac地址的模糊匹配

**Comment by handsomeji** [comment]
不支持，建议固定设备的IP地址

**Comment by threerog** [comment]
> 不支持，建议固定设备的IP地址

虚拟机+虚拟网卡 的场景mac地址会频繁变化，ip也就跟着变化，无法准确的固定ip地址

**Comment by handsomeji** [comment]
设备里面设置静态IP
