### ISSUE TITLE
过滤代理域名ipv6导致群晖docker注册表查询失败

### ISSUE THREAD

**Issue by wxg1015** [xiaorouji/openwrt-package#2392]
### 描述您遇到的bug

开启gfw模式 并启用 过滤代理域名ipv6后，进去群晖docker套件 点击注册表(也就是搜索下载镜像的页面)会提示注册表查询失败并且没有任何内容。

### 复现此Bug的步骤

如上  如果无法复现 重启下群晖和路由器 必然复现

### 您想要实现的目的

正常打开群晖docker注册表

### 日志信息

无

### 截图

![Screenshot_2023-03-19-19-13-59-29_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/44153358/226171932-a8234374-d195-4b89-bc15-5fb8e232155f.jpg)

### 系统相关信息

最新版passwall 4.60-3

### 其他信息

_No response

**Comment by handsomeji** [comment]
不过滤代理域名ipv6时正常吗？
用dnsmasq的address实现屏蔽ipv6似乎可能是有问题的。

**Comment by wxg1015** [comment]
> 不过滤代理域名ipv6时正常吗？
> 用dnsmasq的address实现屏蔽ipv6似乎可能是有问题的。

正常的   用中国地址模式也正常好像    话说我发现目前的屏蔽ipv6似乎一旦开启  无论访问控制里单独指定gfw还是不代理似乎都会被屏蔽掉gfwlist里的网站的ipv6？
再有就是最近我看chinadns-ng更新了屏蔽v6相关的功能 以及纯基于域名的分流功能    话说能不能依据这个实现针对不同模式的精准屏蔽ipv6？

**Comment by handsomeji** [comment]
可以使用最新的源码，用gfwlist+chinadns-ng+过滤代理ipv6试试

**Comment by wxg1015** [comment]
> 可以使用最新的源码，用gfwlist+chinadns-ng+过滤代理ipv6试试

额 好久没搭编译环境了   只能等大佬们编译发布了  能问问更新了什么嘛   能实现主模式中国列表下完全屏蔽海外ipv6 同时访问控制里指定gfw模式则只屏蔽gfwlist网站ipv6吗

**Comment by wxg1015** [comment]
> 可以使用最新的源码，用gfwlist+chinadns-ng+过滤代理ipv6试试

再有就是建议把默认gfwlist修改为v2fly/domain-list-community  目前默认的gfwlist有诸多不合理之处   比如m-team.cc 这是个pt站点  绝对不能被代理的  就赫然出现在默认的gfwlist里

**Comment by handsomeji** [comment]
自己改一下下载源就可

**Comment by wxg1015** [comment]
> 自己改一下下载源就可

我知道 改一下就行  我的意思是建议直接默认别用那个  小白上手容易被坑 如果刚好玩pt   v2fly那个我观察过一段时间 感觉挺完美

**Comment by kyon777** [comment]
我也发现了这个问题,目前好像无解,只能在用nas的时候关闭过滤代理域名ipv6,其他大佬有方法可以分享下

**Comment by kyon777** [comment]
貌似用chinadns-ng 是可行的

**Comment by kyon777** [comment]
使用chinadns-ng 是可行的,但是是相当于关闭过滤代理ipv6,因为使用了chinadns-ng, https://fast.com/测速网站不连网.
