### ISSUE TITLE
[Bug]: xray分流设置proxy关闭，设置默认为代理节点时，google.com.hk上不去

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2400]
### 描述您遇到的bug

xray分流设置proxy关闭，设置默认为代理节点时，google.com.hk上不去。
把proxy设置为代理节点时才可以。

### 复现此Bug的步骤

![image](https://user-images.githubusercontent.com/37928893/226828950-7e1a5627-9365-4d73-86bb-a93891971028.png)

### 您想要实现的目的

我理解的默认这条规则应该是其他规则匹配完了没匹配到 剩下的。
按前面这样推测，即使proxy关闭了，xray还是去匹配了，而且匹配上之后，后面就到不了默认规则了，所以没有执行代理。
按道理将某个规则关闭应该是这个规则就不做匹配了啊，这样才符合常理。
我的目的是用xray实现 匹配到direct国内的走直连，其他的都走代理。

### 日志信息

ok

### 系统相关信息

passwall: master
openwrt: 22.03
on VMware
iphone15

**Comment by nftbty** [comment]
这个很明显是哪里有问题的，真正关闭了旁边是不会有“编辑”超链的。你可以点分流总结点旁边的编辑，进去专门的分流节点设置界面看看。这两个地方的设置界面现在不一样，你在里面设置好了再保存应用看看。

我等会把分流模式里使用均衡节点改好了就看看能不能把这两个界面保持一致。

**Comment by fannwong001** [comment]
> 

是proxy关闭，把默认开着。我当时提交完又换了个图，你刷新一下

**Comment by ghost** [comment]
> 这个很明显是哪里有问题的，真正关闭了旁边是不会有“编辑”超链的。你可以点分流总结点旁边的编辑，进去专门的分流节点设置界面看看。这两个地方的设置界面现在不一样，你在里面设置好了再保存应用看看。
> 
> 我等会把分流模式里使用均衡节点改好了就看看能不能把这两个界面保持一致。

这是我为了截图临时修改的，没有保存应用，所以旁边有个编辑。不影响我说的那种情况的结果。
proxy开着的时候，在分流编辑设置那边多了个proxy前置代理。关闭的时候是一样的。

**Comment by xcyll** [comment]
可以试试helloworld那个设置简单点

**Comment by ghost** [comment]
> 可以试试helloworld那个设置简单点

之后试试，看着好像不支持trojango

**Comment by gito10** [comment]
不知道你这个问题现在还能复现吗？
如果问题还在的话，可以看看`/var/etc/passwall/TCP_SOCKS.json`配置文件的`routing`->`rules`部分，看看`google.com.hk`是匹配到哪个规则，还是没有走了默认。
