### ISSUE TITLE
[Feature Request]: 三个分支分别有什么不同

### ISSUE THREAD

**Issue by threerog** [xiaorouji/openwrt-package#2403]
### 描述你想要的新功能

`luci`
`luci-reality-share`
`luci-smartdns-new-version`

### 描述你想要的解决方案

以上三个分支分别有什么不同
每个分支分别适合什么场景使用

**Comment by jh0072110** [comment]
看名字就知道啊：稳定版/带reality分享链接草案的版本/和新smartdns配合的测试版本
BTW：你这个应该发discussions里，发issue不太合适…
