### ISSUE TITLE
[Feature Request]: Xray自身负载均衡模式，random和leastping问题

### ISSUE THREAD

**Issue by jxph1123** [xiaorouji/openwrt-package#2407]
### 描述你想要的新功能

Xray希望加入leastping模式，检测服务器最小延时，目前的Xray默认的负载均衡模式，其中有服务器中断时，会卡在那里访问中断的服务器，影响使用。

### 描述你想要的解决方案

加入leastping模式，检查服务器，其中有服务器中断时，跳过中断的服务器。

**Comment by gito10** [comment]
才看到你之前还发了 issue，那你其实可以在我那个PR下面引用一下这个 issue，然后到这里来讨论。
然后像你昨天那样的问题，其实也可以先发个issue，如果需要谁帮你看看，可以@，如果需要我看看，一起讨论的话，就到我那个讨论帖里面发个引用，然后我们直接到 issue 里面来讨论。这样想你昨天那种问题，别人遇到了，搜issue就会搜到。如果是代码问题，提交修复之后，也可以引用你的 issue，让人知道是解决什么问题的。
如果是功能请求的话，可以先到我的讨论贴说说，如果是简单的直接就弄了，如果觉得需要比较多讨论的话，就由你再开个新的讨论帖，然后在那里讨论。

**Comment by jxph1123** [comment]
> 才看到你之前还发了 issue，那你其实可以在我那个PR下面引用一下这个 issue，然后到这里来讨论。 然后像你昨天那样的问题，其实也可以先发个issue，如果需要谁帮你看看，可以@，如果需要我看看，一起讨论的话，就到我那个讨论帖里面发个引用，然后我们直接到 issue 里面来讨论。这样想你昨天那种问题，别人遇到了，搜issue就会搜到。如果是代码问题，提交修复之后，也可以引用你的 issue，让人知道是解决什么问题的。 如果是功能请求的话，可以先到我的讨论贴说说，如果是简单的直接就弄了，如果觉得需要比较多讨论的话，就由你再开个新的讨论帖，然后在那里讨论。

我是刚发了这个功能请求，就发现你PR里面已经在做了，所以就关掉了，直接在你PR那边讨论了。。

**Comment by gito10** [comment]
> 我是刚发了这个功能请求，就发现你PR里面已经在做了，所以就关掉了，直接在你PR那边讨论了。。

其实那个pr当时只是下面评论的时候突然想到这个问题，那时候还没想到要马上实现，因为要查资料文档什么的，估计要费一番功夫，开发完还要测试。然后是因为跟你一起讨论，边讨论边改，节省了很多不必要的麻烦，才那么快就完成了。然后结果现在这个pr的功能还没完成。其实单单只是添加负载均衡早就完成了。只不过现在前置代理和这个都是在一块，在前置代理的逻辑处理和设置上感觉有点乱，想一步到位优化，但是前置代理这块一直不太好下手，主要没有有需求的人一起讨论提出详细的需求和改进建议。有个前置代理修改需求的，提了个issue后面就没下文了。完全按我自己的需求改吧，怕又会跟其他人的需求冲突。所以想在各种需求之间找个平衡点，弄个容易理解，能满足多数常见的前置代理需求的设置方式。
想想还是先把负载均衡弄好，单独提交。前置代理再慢慢改吧。

**Comment by jxph1123** [comment]
> > 我是刚发了这个功能请求，就发现你PR里面已经在做了，所以就关掉了，直接在你PR那边讨论了。。
> 
> 其实那个pr当时只是下面评论的时候突然想到这个问题，那时候还没想到要马上实现，因为要查资料文档什么的，估计要费一番功夫，开发完还要测试。然后是因为跟你一起讨论，边讨论边改，节省了很多不必要的麻烦，才那么快就完成了。然后结果现在这个pr的功能还没完成。其实单单只是添加负载均衡早就完成了。只不过现在前置代理和这个都是在一块，在前置代理的逻辑处理和设置上感觉有点乱，想一步到位优化，但是前置代理这块一直不太好下手，主要没有有需求的人一起讨论提出详细的需求和改进建议。有个前置代理修改需求的，提了个issue后面就没下文了。完全按我自己的需求改吧，怕又会跟其他人的需求冲突。所以想在各种需求之间找个平衡点，弄个容易理解，能满足多数常见的前置代理需求的设置方式。 想想还是先把负载均衡弄好，单独提交。前置代理再慢慢改吧。

分流没用过，以后有机会用用
