### ISSUE TITLE
[Bug]: 订阅含有IPV6的链接失败

### ISSUE THREAD

**Issue by iceliuhacker** [xiaorouji/openwrt-package#2419]
### 描述您遇到的bug

订阅的内容有ipv4和ipv6节点，发现订阅后只有ipv4的订阅成功，ipv6的节点都忽略了。

### 复现此Bug的步骤

一、节点订阅
二、添加含有ipv6节点的订阅

### 您想要实现的目的

不要忽略ipv6的节点

### 日志信息

无，不需要

### 截图

![image](https://user-images.githubusercontent.com/118520805/228181312-3926cc08-5cfd-4973-9a9c-7cb6a7a918d1.png)

### 系统相关信息

git-24.086.49405-8fb6827

**Comment by handsomeji** [comment]
看了一下订阅代码，应该正常不会被忽略的。
但是有可能是因为订阅节点的ipv6地址包含[]括号？（麻烦确认一下）

**Comment by iceliuhacker** [comment]
> 看了一下订阅代码，应该正常不会被忽略的。 但是有可能是因为订阅节点的ipv6地址包含[]括号？（麻烦确认一下）

vless我觉得是不是应该有才对，因为同样的地址在手机里导入成功，或者能否设置兼容性，无论有没有中括号都能加成功。
之后我用手动模式单独导入某一个带IPV6的URL就出现这样的问题：
![image](https://user-images.githubusercontent.com/118520805/228204374-ed9229e2-8c4c-48d4-80bf-8ac78fa752b5.png)
以下为我的个人建议，从IPV6的结构看：
xxxx:xxxx::xxxx:xxxx
使用的是“:”作为分隔符。
如果带上端口号，由于通常端口和IP之间的分隔符也是“:”，就出现了：
xxxx:xxxx::xxxx:xxxx:456
这样就很容易把456也看作是ipv6的一部分。
因此我推荐使用中括号：
[xxxx:xxxx::xxxx:xxxx]:456
再加上现在浏览器、curl等对ipv6的识别都是中括号，因此我个人推荐兼容中括号是非常有必要的。
以上您看呢？

**Comment by handsomeji** [comment]
我没有ipv6的订阅节点测试。
不过你可以按我说的操作一下试试：
修改/usr/share/passwall/subscribe.lua
https://github.com/xiaorouji/openwrt-passwall/blob/dfe8eaa435a40d7806eb8e46a0909400328fe3b5/luci-app-passwall/root/usr/share/passwall/subscribe.lua#L1133
把这行的`datatypes.ipmask6(result.address)`改成`datatypes.ipmask6(result.address:gsub("%[", ""):gsub("%]", ""))`后
重新订阅看看

**Comment by handsomeji** [comment]
你可以把手动导入的链接在这里发我测试一下，记得把敏感内容改一改

**Comment by iceliuhacker** [comment]
> 你可以把手动导入的链接在这里发我测试一下，记得把敏感内容改一改

感谢！
2种格式我都提供以下：
vless://xxxxxxxx-xxxxxx-xxxxxxxx-xxxxxxxx@[2406:da14::92c4:9954]:7004?security=tls&encryption=none&alpn=h2&headerType=none&fp=random&type=tcp&flow=xtls-rprx-vision&sni=vr-lb.domain.com#176.3.3.3_JP_IPv6-VLESS_VS
vless://xxxxxxxx-xxxxxx-xxxxxxxx-xxxxxxxx@[2406:da14::92c4:9954]:6010?security=reality&encryption=none&alpn=h2&pbk=GpLwEiXslrNfTqH3xI&headerType=none&fp=random&spx=%2F&type=tcp&flow=xtls-rprx-vision&sni=www.microsoft.com&sid=bb9e26a9b665#35.3.3.3_JP_IPv6-VLESS_VS_RL
本来还有一个VMESS_GRPC，但是被BASE64编码了，不方便提供。

**Comment by iceliuhacker** [comment]
> 

这样修改后，vmess系列好了，我想因该是因为vmess用的是json，有双引号作为分割。但是vless系列IPV6和端口都是冒号，导致失败。
我看了下vless代码
                        if Info[2]:find(":") then                 
                                hostInfo = split(Info[2], ":")    
                                result.address = hostInfo[1]      
                                local idx_port = 2                                                          
                                if hostInfo[2]:find("?") then                                       
                                        hostInfo = split(hostInfo[2], "?")
                                        idx_port = 1                                                      
                                end                                                                              
                                if hostInfo[idx_port] ~= "" then port = hostInfo[idx_port] end 
确实用:作为分割，这样就分割出问题了。
另：指纹伪造的值fp=random好像被丢弃了。

**Comment by handsomeji** [comment]
请更新一下最新的源码测试一下

**Comment by liuhgiceblood** [comment]
> 请更新一下最新的源码测试一下

![image](https://user-images.githubusercontent.com/57214775/228546337-030aedca-85d3-4038-92fa-6a1bcf24c600.png)
单独更新了这2个文件，好用了。

**Comment by liuhgiceblood** [comment]
但是独立导出导入这一块是不是没更新？还是因为我更新的文件不全造成？
![image](https://user-images.githubusercontent.com/57214775/228549896-e28f2a8e-223f-49f1-a9df-219f73cff7e9.png)
单独导出某一个节点发现不带中括号，这样就导致导入做截取也就失败。

**Comment by handsomeji** [comment]
你只更新了订阅脚本，没有更新js。

**Comment by iceliuhacker** [comment]
> 你只更新了订阅脚本，没有更新js。

哈哈，我的错，更新了link_share那个文件后解决了。
这一块之前我用到的地方完美了。很赞！

**Comment by jh0072110** [comment]
说到ipv6，借楼问一下，ipv6的tcping都是超时啊……

**Comment by handsomeji** [comment]
> 说到ipv6，借楼问一下，ipv6的tcping都是超时啊……

你的网络问题，检查一下

**Comment by jh0072110** [comment]
> > 说到ipv6，借楼问一下，ipv6的tcping都是超时啊……
> 
> 你的网络问题，检查一下

能连上 但是tcping那里显示的超时 应该…是哪里的问题呢……

**Comment by kumoonkey** [comment]
> > > 说到ipv6，借楼问一下，ipv6的tcping都是超时啊……
> > 
> > 
> > 你的网络问题，检查一下
> 
> 能连上 但是tcping那里显示的超时 应该…是哪里的问题呢……

我的ipv6节点也是能用，但tcping显示超时。
