### ISSUE TITLE
[Bug]: 最新版本的日志问题

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#2421]
### 描述您遇到的bug

最新版本在未编译HAProxy的情况下启动/重启时的日志会出现：
- 找不到 haproxy，无法启动...
- haproxy -f /tmp/etc/passwall/haproxy/config.cfg
这样两行日志

### 复现此Bug的步骤

每次启动psw/重启psw

### 您想要实现的目的

应该是bug吧？我没编译它就是不需要它启动啊=。=

### 日志信息

如上

### 系统相关信息

https://github.com/xiaorouji/openwrt-passwall/commit/dfe8eaa435a40d7806eb8e46a0909400328fe3b5

**Comment by handsomeji** [comment]
最新源码已修复
