### ISSUE TITLE
[Bug]: 组件更新里面Passwall 版本更新能够检查到版本号，但是无法更新成功

### ISSUE THREAD

**Issue by xnxy2012** [xiaorouji/openwrt-package#2422]
### 描述您遇到的bug

[Bug]: 组件更新里面Passwall 版本更新能够检查到版本号，但是无法更新成功过
其他的组件都可以正常更新

### 复现此Bug的步骤

[Bug]: 组件更新里面Passwall 版本更新能够检查到版本号，但是无法更新成功过
其他的组件都可以正常更新

### 您想要实现的目的

能够像其他组件一样更新，免得再去单独编译ipk

### 日志信息

无

### 系统相关信息

4.60-4.61最新版都是如此

**Comment by handsomeji** [comment]
目前还不支持在线更新luci

**Comment by gito10** [comment]
已经在计划中，主要是要搞自动编译发布不勾选任何可选依赖的ipk，其他组件倒是可以直接用openwrt-passwall-build的opkg源安装和更新。

**Comment by gito10** [comment]
做这个是因为 #2384，估计为了方便知道版本的目的应该是和GitHub上最新版对比好知道知否有更新，所以顺便加上了检查版本的功能。目前是检查到更新后，有更新需求的自己手动编译更新或者去那些预编译好的网站下载，手动更新。
当时那个issue在讨论修改的时候，产生了做成自动更新的想法，并且分析过可行性，是没问题的。等我把目前分流模式下使用xray负载均衡节点和前置代理的过渡性设置优化弄好，就会开始搞这个。
