### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cyzzc** [xiaorouji/openwrt-package#2423]
### 描述您遇到的bug

负载均衡中的bug

### 复现此Bug的步骤

负载均衡中的bug

### 您想要实现的目的

希望能修复这个错误

### 日志信息

日志看不出，我发了截图。

### 截图

![QQ截图20230329223456](https://user-images.githubusercontent.com/80954721/228577580-9830e182-8d70-441a-9c84-6e8354fbbf6c.png)

### 系统相关信息

Passwall 版本【 4.61-2 】以上出现这情况

**Comment by iceliuhacker** [comment]
你这问题应该去haproxy开发那边去问。就好比你家的家具，家具坏了不能找开发商。:-)

**Comment by cyzzc** [comment]
> 你这问题应该去haproxy开发那边去问。就好比你家的家具，家具坏了不能找开发商。:-)

明白了，谢谢

**Comment by handsomeji** [comment]
可能是DNS解析不到这个域名，自己排除
