### ISSUE TITLE
[Feature Request]: 日志记录能否选择一个自定义路径

### ISSUE THREAD

**Issue by iceliuhacker** [xiaorouji/openwrt-package#2424]
### 描述你想要的新功能

见笑了，又提东西让你忙了。
![image](https://user-images.githubusercontent.com/118520805/228715336-eef174e9-77a8-4ed4-a70b-60d38fb4f084.png)
希望日志页面增加自定义日志路径输入框
当使用自定义日志的时候，password重启或者应用的时候老的日志改名为带时间戳的文件【文件格式推荐：output.log.2023-03-30_10.15.12】，然后按照定义的路径生成新日志。

### 描述你想要的解决方案

同上

### 描述你考虑过的替代方案

目前我是自己修改app.sh里日志那行解决，但每次更新后需要自己重新修改。

### 其他信息

无

**Comment by gito10** [comment]
也就是说其实你要的是允许日志持久化的功能是吧，你每次重启都是写入一个新的日志文件，原来的更名存档吗？查看日志页面可是有个清空日志的按钮的，不会不小心点到吗？如果要改，这个清空日志的行为也要适配，把旧的日志更名，然后新建日志。

**Comment by gito10** [comment]
不过如果你对整个/var目录都有持久化需求，也可以编译openwrt的时候，启用/var目录的持久化功能，就不会再挂载到tmpfs而是物理存储了。

**Comment by iceliuhacker** [comment]
我已经额外启用新分区单独放日志

**Comment by iceliuhacker** [comment]
> 也就是说其实你要的是允许日志持久化的功能是吧，你每次重启都是写入一个新的日志文件，原来的更名存档吗？查看日志页面可是有个清空日志的按钮的，不会不小心点到吗？如果要改，这个清空日志的行为也要适配，把旧的日志更名，然后新建日志。

查看和清空不需要动啊，因为已经有持久化了，没必要去动历史日志啊。何况这功能也不是给初级用户用的。清理这种事没必要界面操作啊。

**Comment by gito10** [comment]
> 查看和清空不需要动啊，因为已经有持久化了，没必要去动历史日志啊。何况这功能也不是给初级用户用的。清理这种事没必要界面操作啊。

我意思是假如这个持久化功能加上了，然后其他人刚好有需求就开启了，但是他有可能修改配置或者测试的时候需要查看刚刚的日志，然后可能显示的日志太多了，看着很乱，就点了清空日志。如果这里`清空日志`按钮行为不修改的话，那当前这整个日志文件内容就真的什么都没有了。目前关于整个日志这一块就没考虑到持久化这一块，主要是为了临时查看、排错。

不过刚刚打字的时候想到了一个持久化的修改方案，改动量少，只需要改写入日志的地方，其他包括清空日志这里都不用动。
现有这一套日志不去动它，仍然发挥临时查看的作用，需要清空显示日志的也随便清。增加一个日志持久化选项，当启用时，另外在指定目录，以原本的基本名+日期为文件名，写入日志。就是另外增加了一套持久化日志的逻辑，不影响现有的。当然这都是说的passwall本身的日志。
不知道其他组件的日志日否也需要一起持久化，当然不一定所有组件都可以修改日志路径。

新增的选项，2种方案：
1. 用一个CheckBox，表示`启用持久化日志`，然后持久化日志的目录，由passwall预先定义好。
2. 一个输入框，表示`持久化日志路径`，留空表示不启用持久化日志。

**Comment by iceliuhacker** [comment]
其实只要保留xray v2rsy shadow这些东西的日志就可以，我的截图你能看到也只是这块的。至于passwall.自身的日志不需要变更，还是正常保持现在的状态就可以。
日志这块也简单，只需要修改app.sh里ln_run里重定向日志的写法。加上时间戳。output变量在界面做上配置，写入引用变量。
提前感谢你任然同意了日志持久化这块功能。

**Comment by iceliuhacker** [comment]
> 

提前感谢你任然同意了日志持久化这块功能。

**Comment by gito10** [comment]
> 其实只要保留xray v2rsy shadow这些东西的日志就可以，我的截图你能看到也只是这块的。至于passwall.自身的日志不需要变更，还是正常保持现在的状态就可以。 

你意思是passwall自身的日志不用持久化，只要Xray/V2ray/shadowsocks这些组件的日志可以持久化是吧？
当然我只是给你改一下，改完提PR的时候引用一下你这个issue，至于能不能合并，就不知道了。

**Comment by gito10** [comment]
> 日志这块也简单，只需要修改app.sh里ln_run里重定向日志的写法。加上时间戳。

把一些可能影响到的都看了一下，这个跟我预想的不同。本以为V2ray/Xray日志passwall网页上看不了，所以怎么改都比较好。但是，看到代码才意识到主设置里面的 TCP日志和 UDP日志 就是Xray/V2ray这些软件的记录，然后也看了显示日志的调用代码，这个还真不能直接改。这里的日志跟passwall自身日志一样，是有一个临时属性的，每次重启，日志文件都会清空重写，方便检查本次配置的错误。所以这里不能直接调用持久日志，单次运行的临时日志文件还是不能变。还是需要2套日志逻辑，每次运行都需要把日志同时写入一个临时日志，还要追加到持久日志里面去。不过这一块找到方法，可以利用`tee`实现。
但是现在还有一个问题，默认传给app.sh的日志文件名都是`TCP.log`和`UDP.log`，你既然要持久化的话，还是得区分具体软件的吧，持久日志文件名设定成`Xray_TCP_2023-03-31.log`这样的文件名怎么样。毕竟如果UDP和TCP不是同一节点的话，UDP是有单独的日志的，虽然可以都写入同一个文件，但是会混乱吧。

**Comment by gito10** [comment]
点最下面的一个提交。一个`app.sh`，一个`global.lua`，你自己根据差异更新一下。
目前的文件名格式是像`xray_TCP_230331.log`这样，需要调整吗？
[passwall.zh-cn.lmo.txt](https://github.com/xiaorouji/openwrt-passwall/files/11121377/passwall.zh-cn.lmo.txt)
这个中文语言，自己把后面`.txt`去掉就可以了。

**Comment by gito10** [comment]
这里还发了一个中文lmo，可以替换上去。

**Comment by iceliuhacker** [comment]
![image](https://user-images.githubusercontent.com/118520805/229144635-28bb3c94-27d9-4ca0-8741-bb592aa0c466.png)
/mnt/sda3/log/passwall.txt
是我配置的路径，好像应用后没生效。
![image](https://user-images.githubusercontent.com/118520805/229145008-62472630-2050-47c2-b76e-ee7ae06030e6.png)
是这2个文件吗？还是有没更新对的？

**Comment by iceliuhacker** [comment]
生效了。
![image](https://user-images.githubusercontent.com/118520805/229145698-eeeb2ae3-05fb-45f2-a678-2c9d3a7844fe.png)
希望能合并进去。非常感谢。
我觉得这个功能还是非常有用的，因为的确有长期保留日志的需求。

**Comment by iceliuhacker** [comment]
好像你改多了。
![image](https://user-images.githubusercontent.com/118520805/229146666-bdf40484-1111-4146-b27d-6df16efcf5a5.png)
这个只是DNS解析日志吧？应该没有必要保留。不过貌似路径有问题，导致没有生成日志。估计需要我手动添加这个路径，又或者你本意是：
chinadns-ng_ev_20230331.log
？

**Comment by gito10** [comment]
> 好像你改多了。 ![image](https://user-images.githubusercontent.com/118520805/229146666-bdf40484-1111-4146-b27d-6df16efcf5a5.png) 这个只是DNS解析日志吧？应该没有必要保留。不过貌似路径有问题，导致没有生成日志。估计需要我手动添加这个路径，又或者你本意是： chinadns-ng_ev_20230331.log ？

你这个原始文件名是什么。因为我之前看了下，好像就`TCP.log`，`UDP.log`，`DNS.log`，所以直接取的固定位数。
因为是改的ln_run，只要调用它的就会这样，不过可以添加排除，但是这样感觉又不太好。

**Comment by iceliuhacker** [comment]
这个就是ps 进程里提出来的路径。是代码里执行的 tee -a追加到文本的部分。并不是我设定的。

**Comment by gito10** [comment]
> 这个就是ps 进程里提出来的路径。是代码里执行的 tee -a追加到文本的部分。并不是我设定的。

就是你在改成这个之前，在/tmp/etc/passwall/ 里面是什么名字？

**Comment by iceliuhacker** [comment]
因为我不了解整个代码，但是为啥你不直接吧
${file_func:-echolog "  - ${ln_name}"} "$@" >${output} 2>&1 &
这句改为：
${file_func:-echolog "  - ${ln_name}"} "$@" >${persist_log_path}${output}.$(date +%F) 2>&1 &
这样的模式呢？或者顶多加一个persist_log_path是否赋值的判断来做if else

**Comment by iceliuhacker** [comment]
这个路径下所有文件：
![image](https://user-images.githubusercontent.com/118520805/229150128-4b41286a-5006-40d3-a9bd-703334dad57a.png)
应该就是TCP.log吧

**Comment by gito10** [comment]
因为主设置会调用`/tmp/etc/passwall/`下的`TCP.log`和`UDP.log`，直接改会影响页面调用日志显示。

**Comment by iceliuhacker** [comment]
那么这样呢？
if [ -z ${persist_log_path} ]; then
    ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &
else
    mkdir -p ${persist_log_path}
    ${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | tee -a ${persist_log_path}${output}.$(date +%F) >${output} &
fi

**Comment by gito10** [comment]
${output}应该是/tmp/etc/pasaswall/TCP.log 这样的，前面再加`/mnt/sda3/log`就成了`/mnt/sda3/log/tmp/passwall/TCP.log`，路径太长了，我再修改下，查找最后一个“/”和"."的位置，取这中间的完整文件名看看。
不过我是取得最后5-7位，像"TCP.log"就是“TCP”，那个取出"ev/"这三个字符，难道最后是"ev/.log"没有文件名的？
算了直接改成默认不加，判断是UDP和DNS的再加上UDP和DNS后缀。

不过你原来手动改的，换天了怎么办，比如你现在启动的，生成的是2023-03-31.log，过零点了，应该要到2023-04-01.log了，但还是会继续写入0331的。而且几天不重启的话，文件会很大吧？我测试才开一会就140KB了。

**Comment by iceliuhacker** [comment]
> 

换天不需要关注，如果怕文件大，老文件就 gzip一下。其实现在日志大小完全不需要关注，随便一个硬盘都上T了。
${output}如果是/tmp/etc/pasaswall/TCP.log的话，那就反过来。
persist_log_file= ${persist_log_path}${output}.$(date +%F)  #将持久日志路径固定为一个变量
${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | tee -a ${output} > ${persist_log_file} &
gzip `cat /tmp/passwall_persist_log`  & #压缩上次持久化文件名及路径，个人认为最好不要压缩，因为可能CPU耗不起。当然这个也可以做到界面作为可选项。
echo ${persist_log_file} > /tmp/passwall_persist_log   #写入本次持久化文件名及路径
另外我认为没有必要一定要按天切割日志。因为我们的目的是保留日志。切割日志并不是passwall不支持，而是各种应用自身不支持。（其实xray/v2ray支持，但需要额外配api，但这样就非常复杂了。./xray api restartlogger -s 127.0.0.1:65001             #刷新日志）
你有什么其他联系方式吗？加好友聊聊。

**Comment by gito10** [comment]
你的路由什么处理器的。

不是总大小的问题，就一般硬路由来说，一天就算1MB，那都得上硬盘。主要是这个单文件大小的问题。单个文件太大怕有影响，因为日志文件是一直处于打开状态的。你之前出现过最大的单文件是多大的？一般软件打开文本文件都是不建议打开超过4MB左右的文件的，再大几倍虽然也能打开，但是真的会影响，不过那是需要读取，像这种只追加写入的，应该是不用读到内存的。当然根据你之前的经验，只要对设备性能和稳定性没影响就可以。


其实像Xray/V2ray都没配置成输出日志到文件，是直接输出到stdout，然后管道重定向的，目前这种方式，Xray也没办法切割，只能修改配置，把日志直接写入文件，其实我感觉这样更好，只不过就很分散，如果要修改名字的话，要多处修改。弄在标准输出里重定向就是为了整体的统一。

**Comment by iceliuhacker** [comment]
好像我这个地区的号码被标记为骚扰了，无法和你联系。您加我试试？liuhgiceblood

**Comment by iceliuhacker** [comment]
其实单个文件多大不需要关心，因为需要这个的一半都是比较专业的系统管理员，对日志处理早就有非常丰富的经验了，别说几十M，几百上G都是命令行处理和查询，完全不用担心。所以更没有必要去定期做切割，其实我们自己有办法做切割，不需要passwall来做。
另外还有一个办法就是和系统日志一样发送到别的别的服务器。那边就不存在CPU的问题了，至于切割也完全不关passwall的事了。
类似如下：
![image](https://user-images.githubusercontent.com/118520805/229165788-6f919909-346a-4837-ac82-b52fea6fdfe1.png)

**Comment by iceliuhacker** [comment]
需要变量：
persist_log_path=/path/log  #日志路径
sys_log=1  #启用系统日志
protocol=TCP   #协议
app_name   #应用名
以上4个变量根据实际情况额外命名。
以下应用范例。
`if [ -z ${persist_log_path} ] && [ "${sys_log}" != "1" ]; then`
`    ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &   #如果以上2个变量不满足就保持现在的日志模式不变。`
`else`
`    if [ ! -z ${persist_log_path} ]; then    #优先本地日志`
`        mkdir -p ${persist_log_path}`
`        ${file_func:-echolog " - ${ln_name}"} "$@" >> ${persist_log_path}/${protocol}.log.$(data '+%F') 2>&1 &`
`        sys_log=0   #本地日志启用就取消系统日志`
`    fi`
`    if [ "${sys_log}" == "1" ]; then`
`        ${file_func:-echolog "  - ${ln_name}"} "$@" 2>&1 | logger -t PASSWALL_${app_name}_${protocol} &`
`        persist_log_path=''    #清空路径防止写入路径日志`
`    fi`
`fi`

以上仅仅做参考，具体变量名、语法根据情况调整。
系统日志标签我这里使用的：
PASSWALL_应用_协议
的格式，这样在日志服务器那边能根据标签名进行日志分类存储。

**Comment by gito10** [comment]
openwrt系统发送日志到服务器已经另外设置好了是吧，所以这里只需要发送到系统日志，然后就能通过系统日志发送到你们的日志服务器了？

**Comment by iceliuhacker** [comment]
> 

对，是的。passwall只需要把带标签的日志发给logger就可以，后面的就由系统的日志服务处理。
对了，gzip要不加一个选项也行，这个看你个人意愿，加上后代码如下：

`if [ -z ${persist_log_path} ] && [ "${sys_log}" != "1" ]; then`
`    ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &   #如果以上2个变量不满足就保持现在的日志模式不变。`
`else`
`    if [ ! -z ${persist_log_path} ]; then    #优先本地日志`
`        mkdir -p ${persist_log_path}`
`        log_file=${persist_log_path}/${protocol}.log.$(data '+%F')`
`        ${file_func:-echolog " - ${ln_name}"} "$@" >> ${log_file} 2>&1 &`
`        sys_log=0   #本地日志启用就取消系统日志`
`        if [ "$_gzip" == "1" ]; then`
`             _log_list=$(ls ${persist_log_path}/*.log.* | egrep -v "^${log_file}$|.gz$")    #列出所有没有压缩和正在使用的日志`
`              gzip ${_log_list} &`
`         fi`
`    fi`
`    if [ "${sys_log}" == "1" ]; then`
`        ${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | logger -t PASSWALL_${app_name}_${protocol} &`
`        persist_log_path=''    #清空路径防止写入路径日志`
`    fi`
`fi`

**Comment by iceliuhacker** [comment]
```
if [ -z ${persist_log_path} ] && [ "${sys_log}" != "1" ] || [ "${output}" = "/dev/null" ]; then
    ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &   #如果以上2个变量不满足就保持现在的日志模式不变。
else
    if [ ! -z ${persist_log_path} ] && [ -d ${persist_log_path} ]; then    #优先本地日志
        log_file=${persist_log_path}/${protocol}.log.$(data '+%F')
        ${file_func:-echolog " - ${ln_name}"} "$@" >> ${log_file} 2>&1 &
        sys_log=0   #本地日志启用就取消系统日志
        if [ "$_gzip" == "1" ]; then
            _log_list=$(ls ${persist_log_path}/*.log.* | egrep -v "^${log_file}$|.gz$")    #列出所有没有压缩和正在使用的日志
            if [ ! -z ${_log_list} ]; then
                gzip ${_log_list} &
            fi
         fi
    fi
    if [ "${sys_log}" == "1" ]; then
        ${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | logger -t PASSWALL_${app_name}_${protocol} &
        persist_log_path=''    #清空路径防止写入路径日志
    fi
fi
```
调整下，增加文件清单是否为空判断。

**Comment by gito10** [comment]
> if [ -z ${persist_log_path} ] && [ "${sys_log}" != "0" ]; then

后面判断不是`[ "${sys_log}" == "0" ]`吗？

**Comment by iceliuhacker** [comment]
> > if [ -z ${persist_log_path} ] && [ "${sys_log}" != "0" ]; then
> 
> 后面判断不是`[ "${sys_log}" == "0" ]`吗？

啊对，其实我本来应该些!="1"的，这样更严谨，但是忘记把0改为1了。
上面我改了。

**Comment by iceliuhacker** [comment]
```
if [ "${output}" != "/dev/null" ] && [ "${advanced_log}" != "1" ]; then
    ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &   #如果以上2个变量不满足就保持现在的日志模式不变。
else
    if [ -d ${persist_log_path} ]; then    #优先本地日志
        log_file=${persist_log_path}/${protocol}.log.$(data '+%F')
        ${file_func:-echolog " - ${ln_name}"} "$@" >> ${log_file} 2>&1 &
        sys_log=0   #本地日志启用就取消系统日志
        if [ "$_gzip" == "1" ]; then
            _log_list=$(ls ${persist_log_path}/*.log.* | egrep -v "^${log_file}$|.gz$")    #列出所有没有压缩和正在使用的日志
            if [ ! -z ${_log_list} ]; then
                gzip ${_log_list} &
            fi
         fi
    fi
    if [ "${sys_log}" == "1" ]; then
        ${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | logger -t PASSWALL_${app_name}_${protocol} &
        persist_log_path=''    #清空路径防止写入路径日志
    fi
fi
```
