### ISSUE TITLE
建议组件更新只更新正式版如xray

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#2426]
### 描述您遇到的bug

现在xray的正式版是1.75，点击更新显示1.8，还以为1.8出正式版了，更新后有一些问题。
建议以后只更新正式版。

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

无

**Comment by gito10** [comment]
这个改倒是好改，只要把`com.lua`里相应组件的api_url 从`gh_pre_release_url`改成`gh_release_url`就行了。但是这个一直以来V2ray和Xray就是检测全部版本的更新啊，包括packages仓库可以看到，也都是自动拉取了pre-release更新的。如果packages里面是含pre-release的最新版，组件更新里面改成latest release，那不检查的版本比开始安装的时候还低好多个。
所以估计这个要么就自己有需要的自己改，要么就加个检测版本切换开关，可以是一个总开关控制所有组件 ，或者每个组件一个可以单独控制。
这个修改简单，主要是有没有改的必要，这个要看 @xiaorouji 怎么说。

**Comment by jh0072110** [comment]
……那要用reality的怎么办 我认为有旧版需求的可以手动scp core……

**Comment by Felix2yu** [comment]
>更新后有一些问题

你也没说是什么问题，但我猜测不是1.8的bug，而是新版本弃用了旧版本中的一些功能，完全可以手动回退，passwall也并不会自动更新组件。

**Comment by jxph1123** [comment]
可以不用更新啊,如果没有需求,不用更新,组件更新也不会自动更新

**Comment by laaArmy** [comment]
你们提的问题无聊不无聊，你自己不更新不就得了

**Comment by gito10** [comment]
嗯，这个需求还是比较正当的，不是说不更新就行。人是有更新需求，只不过想更正式版，如果正式版没有更新，就不更。要改很快，就是这个选择版本的开关是一个总的管全部，还是每个组件一个独立设置？
