### ISSUE TITLE
[Bug]: passwall 4.62 主界面无法选择naiv节点

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#2433]
### 描述您遇到的bug

Op 21.02.5 pw最新版本

### 复现此Bug的步骤

rt

### 您想要实现的目的

rt

### 日志信息

rt

### 系统相关信息

rt

**Comment by wazzx** [comment]
编译界面选择naiv，默认xray没有删除可以添加节点使用，但是一旦naiv.ipk是后续添加的就不能选择naiv节点

**Comment by gito10** [comment]
> 编译界面选择naiv，默认xray没有删除可以添加节点使用，但是一旦naiv.ipk是后续添加的就不能选择naiv节点

什么意思，是naive通过编译直接集成的没问题，编译时候没选，后期通过ipk安装的就不行，除此以外其他配置都是一模一样？“默认xray没有删除”是什么意思，是后面那种情况把xray删除了吗

**Comment by wazzx** [comment]
> > 编译界面选择naiv，默认xray没有删除可以添加节点使用，但是一旦naiv.ipk是后续添加的就不能选择naiv节点
> 
> 什么意思，是naive通过编译直接集成的没问题，编译时候没选，后期通过ipk安装的就不行，除此以外其他配置都是一模一样？“默认xray没有删除”是什么意思，是后面那种情况把xray删除了吗

你好！大佬，passwall编译的时候没有选择naiv（因为naiv的版本有点低，用的是ssrplus的源编译的ipk）然后上传ipk到系统，在最新版本passwall在主界面无法选择naiv的节点（节点早前已经添加成功），已经F12，重启等，但是如果编译的时候选择了naiv，和passwall一起编译出来，再次上传安装，没有上述问题。

**Comment by gito10** [comment]
大概搞清楚原因了。你编译的时候没选择的话，估计安装之后，`/etc/config/passwall`的`global_app`下面是没有 naive 的 路径的，就是`/usr/bin/naive`，然后主界面判断是否存在是调用的一个函数，具体到“naive”就是这个命令`type -t -p /bin/naive -p  naive`，是不会从`/usr/bin/`去查找的，所以肯定找不到。我在那个命令里加上默认查找`/usr/bin/`目录吧，毕竟passwall用到的几个组件都是在`/usr/bin/`下面的。

不过我刚刚看了passwal和ssrplus，naive版本一样的啊，都是跟进最新版了。

**Comment by gito10** [comment]
提PR了，等合并了再试试吧，或者你把那处修改的地方复制，手工修改到你的路由上面试试。

**Comment by wazzx** [comment]
> 大概搞清楚原因了。你编译的时候没选择的话，估计安装之后，`/etc/config/passwall`的`global_app`下面是没有 naive 的 路径的，就是`/usr/bin/naive`，然后主界面判断是否存在是调用的一个函数，具体到“naive”就是这个命令`type -t -p /bin/naive -p naive`，是不会从`/usr/bin/`去查找的，所以肯定找不到。我在那个命令里加上默认查找`/usr/bin/`目录吧，毕竟passwall用到的几个组件都是在`/usr/bin/`下面的。
> 
> 不过我刚刚看了passwal和ssrplus，naive版本一样的啊，都是跟进最新版了。

开始的时候没有更新到最新版本！

**Comment by gito10** [comment]
> 开始的时候没有更新到最新版本！

现在已经合并了，再有类似的情况应该不会出现了。

**Comment by wazzx** [comment]
> > 开始的时候没有更新到最新版本！
> 
> 现在已经合并了，再有类似的情况应该不会出现了。

谢谢大佬，我有空测试一下！还有一个问题：我这边目前不太确定，最新版本的pw是不是dns有问题，我这边老版本目前奈飞是没有问题的，但是新版本显示奈飞不能使用，哪怕是开启中国列表以外（但是开启了china dns）。

**Comment by gito10** [comment]
> 我这边老版本目前奈飞是没有问题的，但是新版本显示奈飞不能使用，哪怕是开启中国列表以外（但是开启了china dns）。

老版本和新版本是隔了多久的，老版本DNS有下面这一项吗？
![image](https://user-images.githubusercontent.com/10704839/229330063-293b659f-6490-49a3-be86-fce49fa559b1.png)

还有，你老版本正常使用Netflix 是GFWList模式吗？

**Comment by wazzx** [comment]
> > 我这边老版本目前奈飞是没有问题的，但是新版本显示奈飞不能使用，哪怕是开启中国列表以外（但是开启了china dns）。
> 
> 老版本和新版本是隔了多久的，老版本DNS有下面这一项吗？ ![image](https://user-images.githubusercontent.com/10704839/229330063-293b659f-6490-49a3-be86-fce49fa559b1.png)
> 
> 还有，你老版本正常使用Netflix 是GFWList模式吗？

![Screenshot 2023-04-02 11 44 56](https://user-images.githubusercontent.com/60512548/229330176-4b4ee216-92a4-44c8-b31d-579b1464bf6c.png)
老版本是4.60 我的节点上naiv和hys，老版本gfw模式也能使用，新版本是完全打不开奈飞网站！（直接显示区域不可用），使用环境是网页版本（gfw模式，中国外都有尝试）！新版本的奈飞在小米盒子国际版app上面能进去app页面选择视频但是不能加载视频（gfw模式，中国外没有尝试），推特app的视频也是不能加载（gfw模式，中国外没有尝试），但是油管app没有问题（gfw模式，中国外没有尝试）。

**Comment by nftbty** [comment]
你老版和新版使用时所有选项都是设置的一样吗。控制变量测试。如果所有设置都是一样的，还不行，但是原来的可以，就不用改设置尝试了，直接排查错误原因。

**Comment by wazzx** [comment]
> 你老版和新版使用时所有选项都是设置的一样吗。控制变量测试。如果所有设置都是一样的，还不行，但是原来的可以，就不用改设置尝试了，直接排查错误原因。

我刚刚修改了一下，你看一下

**Comment by gito10** [comment]
推特网页版能看视频吗？是不是就是别人发推的视频？如果网页版也看不了的话，打开F12，然后刷新，看一下是哪个域名请求失败。还有就是你的节点是单节点、还是负载均衡或者分流？

**Comment by jxph1123** [comment]
借这个地方反馈下主界面,我拉的最新源码[994c53febf2974651e3cc443861556f26fc76bc7](https://github.com/xiaorouji/openwrt-passwall/commit/994c53febf2974651e3cc443861556f26fc76bc7),清空所以配置,全新安装passwall,主界面成这样..(如果老配置不清空,就和以前一样,清空就是图中样子,之前就是没有清空配置,所以没有发现)  @nftbty 

![image](https://user-images.githubusercontent.com/35351787/229387952-b622b7d1-9e5d-4cbb-80f7-16ac33e0870b.png)

**Comment by gito10** [comment]
> (如果老配置不清空,就和以前一样,清空就是图中样子,之前就是没有清空配置,所以没有发现) 
> 

意思是老配置不清，TCP节点关闭，下面是正常的什么都没有的？
不过目前还保留原来的这个界面，是个过渡方案，规则数一多，就太长了。至于隐藏选项的depends太简单了，没法实现复杂的依赖，想要的效果达不到，还可能一不小心出问题。

分析了代码，应该只有在节点列表只有分流节点，没有添加任何普通节点的情况才存在。

**Comment by wazzx** [comment]
> > (如果老配置不清空,就和以前一样,清空就是图中样子,之前就是没有清空配置,所以没有发现)
> 
> 意思是老配置不清，TCP节点关闭，下面是正常的什么都没有的？ 不过目前还保留原来的这个界面，是个过渡方案，规则数一多，就太长了。至于隐藏选项的depends太简单了，没法实现复杂的依赖，想要的效果达不到，还可能一不小心出问题。
> 
> 你说的清空配置，是不是一个节点都没有了，这个跟别的应该没关系，估计是没有分流节点可选，下面的选项没有依赖可以添加，具体我看看代码。但是passwall默认会有一个分流总结点吧，应该不会出现这个情况。难道你全新安装的节点列表里面没有分流总结点？

f反馈一下这个是如果配置文件有默认的xray分流选项就会有这个界面，可能是把默认的第一个选项载入到主界面了，我这边恢复默认就是这个样子，删除默认xray分流选项后，恢复默认一样的，
反馈一下奈飞的问题，更新到最新版pw，xray默认分流删除后，情况正常了。（不知道是不是xray默认分流在的问题，还是因为最新版本修改的问题）

**Comment by gito10** [comment]
> > > (如果老配置不清空,就和以前一样,清空就是图中样子,之前就是没有清空配置,所以没有发现)
> > 
> > 
> > 意思是老配置不清，TCP节点关闭，下面是正常的什么都没有的？ 不过目前还保留原来的这个界面，是个过渡方案，规则数一多，就太长了。至于隐藏选项的depends太简单了，没法实现复杂的依赖，想要的效果达不到，还可能一不小心出问题。
> > 你说的清空配置，是不是一个节点都没有了，这个跟别的应该没关系，估计是没有分流节点可选，下面的选项没有依赖可以添加，具体我看看代码。但是passwall默认会有一个分流总结点吧，应该不会出现这个情况。难道你全新安装的节点列表里面没有分流总结点？
> 
> f反馈一下这个是如果配置文件有默认的xray分流选项就会有这个界面，可能是把默认的第一个选项载入到主界面了，我这边恢复默认就是这个样子，删除默认xray分流选项后，恢复默认一样的， 反馈一下奈飞的问题，更新到最新版pw，xray默认分流删除后，情况正常了。（不知道是不是xray默认分流在的问题，还是因为最新版本修改的问题）

所以要控制变量测试

**Comment by jxph1123** [comment]
> 。难道你全新安装的节点列表里面没有分流总结点？

意思是就干干净净的系统,初次安装passwall就是这样,应该是楼下说的,默认是有一个xray分流选项,可能是把默认的第一个选项载入到主界面了,之前也是默认xray分流选项,但是没有这些前置代理出现,是否可以加个条件,选择xray分流才会出现?

**Comment by gito10** [comment]
> 反馈一下这个是如果配置文件有默认的xray分流选项就会有这个界面，可能是把默认的第一个选项载入到主界面了，我这边恢复默认就是这个样子，删除默认xray分流选项后，恢复默认一样的， 

你看看这个情况的时候，是不是只有分流节点，没有普通节点。

**Comment by jxph1123** [comment]
> > 反馈一下这个是如果配置文件有默认的xray分流选项就会有这个界面，可能是把默认的第一个选项载入到主界面了，我这边恢复默认就是这个样子，删除默认xray分流选项后，恢复默认一样的，
> 
> 你看看这个情况的时候，是不是只有分流节点，没有普通节点。

对的,初始只有分流节点,其他都没有,干干净净

**Comment by gito10** [comment]
> > 。难道你全新安装的节点列表里面没有分流总结点？
> 
> 意思是就干干净净的系统,初次安装passwall就是这样,应该是楼下说的,默认是有一个xray分流选项,可能是把默认的第一个选项载入到主界面了,之前也是默认xray分流选项,但是没有这些前置代理出现,是否可以加个条件,选择xray分流才会出现?

不是这个情况。只要节点列表有分流节点，就会载入这些选项，只不过如果你没选分流节点，这些是会在加载后隐藏的，每次加载或者刷新的时候可以看到，先是分流规则加载完了，再隐藏，显示当前配置的，你看是不是。
所以只要有分流节点在，就必须提前加载，如果不加载的话，之后选择分流节点就什么都没有。这里的问题就是添加显示依赖的问题，在哪些情况下才显示，这里因为没有普通节点，所以没法添加依赖，没有依赖的默认就会显示。所以这个地方要解决，只能添加个不存在的依赖让它默认隐藏。

**Comment by gito10** [comment]
> 对的,初始只有分流节点,其他都没有,干干净净

再随便添加个节点，就可以正常隐藏，看是不是。

**Comment by gito10** [comment]
其实对于luci的界面开发这一块我是无力吐槽了，其实我是有强迫症，每次加载主界面，是就算你不是用的分流，也要看着它加载完全部规则，然后再看它隐藏，有时候慢的话，或者规则多些的话，就要2-3秒，很无语。但是又不能默认不加载。默认不加载的话，切换到分流，这些规则就没法显示，只能先保存应用一下才能显示。不过刚刚想到一个也许可行的方法。

不知道你们注意到每次进passwall的时候这个情况没有。

**Comment by jxph1123** [comment]
> > 对的,初始只有分流节点,其他都没有,干干净净
> 
> 再随便添加个节点，就可以正常隐藏，看是不是。

不是,好像都不对...增加节点也不对.
![1680486489121](https://user-images.githubusercontent.com/35351787/229393684-7348ac16-f49e-431a-ab3d-81425696bd6d.jpg)
![1680486489143](https://user-images.githubusercontent.com/35351787/229393693-44ba6295-1e53-47d9-b853-f8154db27d9b.jpg)
![1680486489185](https://user-images.githubusercontent.com/35351787/229393698-49713d04-d224-481a-8af5-2387ba03c150.jpg)

**Comment by gito10** [comment]
> 不是,好像都不对...增加节点也不对. ![1680486489121](https://user-images.githubusercontent.com/35351787/229393684-

普通节点，不是负载均衡，就是有具体协议参数的，随便瞎填都可以

**Comment by jxph1123** [comment]
> > 不是,好像都不对...增加节点也不对. ![1680486489121](https://user-images.githubusercontent.com/35351787/229393684-
> 
> 普通节点，不是负载均衡，就是有具体协议参数的，随便瞎填都可以

普通节点都不行,我新增普通节点都有,感觉这个是全局都有

**Comment by gito10** [comment]
> 普通节点都不行,我新增普通节点都有,感觉这个是全局都有

应该不会吧，就是这个逻辑啊。
![image](https://user-images.githubusercontent.com/10704839/229400897-52ad5008-8557-4203-94ca-2ab45b35e75d.png)
如果没有除普通节点以外的节点，才没法添加。我自己把配置备份一下测试吧。

**Comment by jxph1123** [comment]
> > 普通节点都不行,我新增普通节点都有,感觉这个是全局都有
> 
> 应该不会吧，就是这个逻辑啊。 ![image](https://user-images.githubusercontent.com/10704839/229400897-52ad5008-8557-4203-94ca-2ab45b35e75d.png) 如果没有除普通节点以外的节点，才没法添加。我自己把配置备份一下测试吧。

我测试是全局都有那个前置了,包括新建自定义节点,都会出现,感觉是全局了.

**Comment by gito10** [comment]
> 我测试是全局都有那个前置了,包括新建自定义节点,都会出现,感觉是全局了.

我测试了，就是我说的那样，只不过在那种情况下，节点添加后保存不了，需要先把passwall主界面的启用的勾去掉。最佳解决方案是把balancer单独弄一个表，先改。

**Comment by jxph1123** [comment]
> > 我测试是全局都有那个前置了,包括新建自定义节点,都会出现,感觉是全局了.
> 
> 我测试了，就是我说的那样，只不过在那种情况下，节点添加后保存不了，需要先把passwall主界面的启用的勾去掉。最佳解决方案是把balancer单独弄一个表，先改。

大佬优化,我可以测试.

**Comment by gito10** [comment]
@jxph1123 试试，两个文件，一个主界面，一个节点配置界面
[shunt_fix.zip](https://github.com/xiaorouji/openwrt-passwall/files/11134701/shunt_fix.zip)
节点配置按照原有逻辑，不过主界面的增加了一个判断，就是如果当前没有可用的节点，就直接连下面的分流规则都不显示了（这里还可以加个提示“没有可用节点”），然后节点配置页面是没有可用节点也照常显示。在没有节点的情况下，就只有直连和黑洞可以用了，也就是说分流就只能对有些规则禁止联网了，不知道这有没有意义。你看看，然后给个意见。

**Comment by jxph1123** [comment]
> > 我测试是全局都有那个前置了,包括新建自定义节点,都会出现,感觉是全局了.
> 
> 我测试了，就是我说的那样，只不过在那种情况下，节点添加后保存不了，需要先把passwall主界面的启用的勾去掉。最佳解决方案是把balancer单独弄一个表，先改。

有点奇怪.我用老版本的/etc/config/passwall内的配置,一切正常,包括你的新功能,负载均衡,新建节点等都是正常的,但是一旦恢复恢复默认配置，地址栏输入例：[http://192.168.1.1/cgi-bin/luci/admin/services/passwall/reset_config](http://192.168.1.1/cgi-bin/luci/admin/services/passwall#).....就会不正常了,不知道新版本/etc/config/passwall内多了啥.

**Comment by jxph1123** [comment]
> @jxph1123 试试，两个文件，一个主界面，一个节点配置界面 [shunt_fix.zip](https://github.com/xiaorouji/openwrt-passwall/files/11134701/shunt_fix.zip) 节点配置按照原有逻辑，不过主界面的增加了一个判断，就是如果当前没有可用的节点，就直接连下面的分流规则都不显示了（这里还可以加个提示“没有可用节点”），然后节点配置页面是没有可用节点也照常显示。在没有节点的情况下，就只有直连和黑洞可以用了，也就是说分流就只能对有些规则禁止联网了，不知道这有没有意义。你看看，然后给个意见。

确实,下面的分流规则都不显示了.
![image](https://user-images.githubusercontent.com/35351787/229413585-71fec12e-7760-4d3f-85b2-bd622a492253.png)

**Comment by gito10** [comment]
再试试这个
[global.lua.txt](https://github.com/xiaorouji/openwrt-passwall/files/11134791/global.lua.txt)
这是新加了提示的，你觉得是哪种好，可以和节点配置页的对比。
还是说跟原来一样，没有节点也显示全部规则？

**Comment by jxph1123** [comment]
> 再试试这个 [global.lua.txt](https://github.com/xiaorouji/openwrt-passwall/files/11134791/global.lua.txt) 这是新加了提示的，你觉得是哪种好，可以和节点配置页的对比。 还是说跟原来一样，没有节点也显示全部规则？

我觉得这种可以,才符合逻辑点

![image](https://user-images.githubusercontent.com/35351787/229414526-695ae88f-f9ae-43f1-b863-d95044856439.png)

**Comment by gito10** [comment]
那这个提示是只要没有可用节点就显示呢，还是要选择了分流节点才显示好一点。

**Comment by jxph1123** [comment]
> 那这个提示是只要没有可用节点就显示呢，还是要选择了分流节点才显示好一点。

我觉得都行

**Comment by gito10** [comment]
> 我觉得都行

现在reset还有问题没？

**Comment by jxph1123** [comment]
> > 我觉得都行
> 
> 现在reset还有问题没？

没问题哈

**Comment by nftbty** [comment]
> 没问题哈

有空的话，再试试这个看看。主要增加了一个类型选项，设计逻辑是这样：
- 系统上如果同时装了Xray和V2ray，就显示类型供选择。其中Xray支持`底层链式代理转发`，V2ray不支持，也就是类型为V2ray时这个这个选项应该隐藏。
- 如果只装了其中一个，比如Xray，然后分流节点之前设置的类型也是Xray，那就不显示类型，`底层链式代理转发`要显示。
如果只装了V2ray，节点类型也是V2ray，不显示类型，`底层链式代理转发`也不显示。
- 如果只装了V2ray，节点类型是Xray，或者只装了Xray，节点类型是V2ray，就显示类型，并且值为系统安装的那一个，`底层链式代理转发`V2ray不显示，Xray显示。

因为之前测试，从组件更新装了v2ray到/tmp 目录，新建了个V2ray的分流节点。然后路由重启后，v2ray没有了，但是那个分流节点仍是V2ray类型的。所以改了这么个方便在主界面切换V2ray和Xray。当然对于自始至终都只用一种的，还跟以前一样，并不会有这个“类型”显示出来。对于同时装了2个的，切换使用要方便一些，尤其是做测试对比而不是实际应用的时候。
反正我自己测试是没发现问题，符合预期。

**Comment by gito10** [comment]
这个应该可以关了吧。
