### ISSUE TITLE
[Bug]: 局域网代理失效

### ISSUE THREAD

**Issue by smallprogram** [xiaorouji/openwrt-package#2434]
### 描述您遇到的bug

@nftbty
#### 问题1
- [x] 之前版本我将局域网域名列表中的某些IP段屏蔽，通过Xray分流规则设置某些局域网走国内公网上的服务器部署xray服务端代理线路，访问该服务器的内网设备。非局域网的走VPS的Xray代理线路，但是现在这种方式行不通了。Xray版本没有变，都是1.8。如果将代理线路直接换成国内公网上的服务器部署xray服务端代理线路，就没有问题。

#### 问题2
- [x] xray分流中，底层传输方式的链式转发，选项的checkbox一旦勾选保存，在去掉勾选后保存完成后，勾选状态还在。另外不太明白底层传输方式的链式转发是什么意思

#### 问题3
- [x] xray分流中，访问控制中客户端全局代理，更新geodata，通过geodata分流，QQ无法登录。访问控制中客户端代理模式换为中国列表以外，QQ就可以登录了。非常奇怪，之前没这问题。貌似xray分流某些udp流量被阻止

### 复现此Bug的步骤

-

### 您想要实现的目的

-

### 日志信息

-

### 截图

问题1
![image](https://user-images.githubusercontent.com/6050360/229184632-d58629c0-1fb0-4c0c-845c-038c5f6059e0.png)

### 系统相关信息

Passwall版本：4.62-1

**Comment by GreatMichaelLee** [comment]
问题1+问题2，一样的问题，问题2我这边在分流节点里取消后可以保存取消链式转发的配置，应该是保存顺序的问题（我也不懂这个有啥作用，勾和不勾哪个好？）

**Comment by xcyll** [comment]
代理方式:默认不代理 访问控制指定设备代理 
模式:中国列表以外 DNS:内置DNS
 op-master最新源码编译
**分流**貌似**失效** 不走分流的节点 还是走了默认的节点

**Comment by gito10** [comment]
@smallprogram 分流的修改，我主要是增加了负载均衡节点的支持，原来的其他节点的处理逻辑没动，再就是修改了前置代理的逻辑，这两个应该不会有影响。再还有一个，原来每个规则如果同时有IP匹配和域名匹配，是写成2条rule，然后我把每个规则的合在一起写成一个规则了，问题1和3 不知道跟这个有没有关系，因为`util_xray.lua`我就再没动过其他地方了。你对比下两个版本生成的TCP_SOCKS.json配置文件区别在哪里，才好定位。

问题2，这个底层链式转发我没动它，原来就有的。应该是不启用的话，如果你的节点底层不是纯TCP，而是h2、ws、grpc之类的，在设置代理时，这些传输层设置就无效，只会以纯TCP发送到代理。启用的话就会先应用传输层设置包装成相应的h2、ws再发往代理服务器。具体的可以去看Xray官方文档。
这个主界面的设置是同步节点设置页的设置选项做适配修改，使两边设置保持一致。已找到原因。

**Comment by gito10** [comment]
> 不走分流的节点 还是走了默认的节点

这个不走分流的节点是什么意思？
分流模式下不是所有进入xray的流量都要匹配路由规则吗，没匹配到就走最后的默认路由了。

**Comment by xcyll** [comment]
现在在外面没法全新刷机检测问题了 之前是保留配置升级的
方案是默认不代理 指定设备代理
设置的是默认日本节点 奈飞分流节点是香港 登入netflix 结果打开的是奈飞日本

**Comment by gito10** [comment]
> 现在在外面没法全新刷机检测问题了 之前是保留配置升级的 方案是默认不代理 指定设备代理 设置的是默认日本节点 奈飞分流节点是香港 登入netflix 结果打开的是奈飞日本

不用刷机，这一块其实就改了一个`util_xray.lua`，你把现在的改名备份，然后把以前的版本复制过去，就行了。lua写的这些东西，修改保存就立即生效的。像有时候passwall有了新的提交想跟进，又不想麻烦编译，可以直接把修改的文件内容复制，替换路由器上现有的就可以了。
你可以用现在的版本应用一下，把`/tmp/etc/passwall/TCP_xxxxx.json`配置文件复制出来，然后把以前版本的`passwall/util_xray.lua`和`model/cbi/passwall/client/global.lua`替换到路由器相应位置，就恢复成老版了。然后重新保存应用一下，就是你之前的配置了。然后看看是否恢复正常，如果是，那就比较看看这两个配置有什么区别，看是哪里修改引起了。如果`util_xray.lua`换成以前的版本还是跟现在一样，就不是这里的修改引起的。

**Comment by gito10** [comment]
>设置的是默认日本节点 奈飞分流节点是香港 登入netflix 结果打开的是奈飞日本

就是Netflix分流规则没匹配上，导致走了默认？这个可以直接检查下生成的配置，看路由规则那一块有没有错误。

> 方案是默认不代理 指定设备代理

可以控制变量，按照普通的所有设备都代理再看看，应该还是一样，这一块内容应该不相干。估计应该就是路由规则上的问题。

**Comment by gito10** [comment]
> （我也不懂这个有啥作用，勾和不勾哪个好？）

这个是使用前置代理的情况下才需要的参数，不用前置代理的话不用管。用前置代理的情况下，如果你的需要使用前置代理的节点，底层传输方式就是TCP，也不用，如果是下图除了TCP的其他这些，就需要勾选。
![image](https://user-images.githubusercontent.com/10704839/229262711-93828719-6a38-4253-bd26-e87e1176fce6.png)

**Comment by xcyll** [comment]
好久没用分流了 想试试下分流下的负载 结果发现分流本身失效了 奈飞规则是默认的 回去我再尝试你说的情况

**Comment by gito10** [comment]
> 好久没用分流了 想试试下分流下的负载 结果发现分流本身失效了 奈飞规则是默认的 回去我再尝试你说的情况

哦，你是在分流下用的Xray负载均衡节点，不是普通单节点是吧？那你把单节点也试试，看有没有问题，好确认是出在整体上，还是新增的负载均衡没处理到位。
最好是把节点信息去掉后，把配置发上来，尤其是使用负载均衡出问题的，因为我之前开发测试的时候，有遇到过，主要是路由规则的tag和balancer的tag没匹配上，导致走了默认，但我后来都解决了的。

**Comment by xcyll** [comment]
昨晚首先测试的是用负载节点走Youtube结果还是走默认 我也怀疑是负载出问题 后面我改成上面的情形还是分流失效

**Comment by gito10** [comment]
> 昨晚首先测试的是用负载节点走Youtube结果还是走默认 我也怀疑是负载出问题 后面我改成上面的情形还是分流失效

YouTube那个大概的配置可以说一下，我这边可以测试。我说个大概的看是不是一样。前置代理总开关关闭，youtube域名填到一个分流规则，设置香港节点负载均衡，然后默认节点使用台湾单节点。理论上YouTube应该显示HK，但却显示TW了，是不是和你昨天测试配置类似。

**Comment by xcyll** [comment]
是这样的 
另外我其他规则全关闭 只开了YouTube Netflix分流规则

**Comment by gito10** [comment]
破案了，应该就是合并规则，把带domain和ip匹配的写到一个规则里面引起的，因为我之前就有youtube的一个分流规则，但是下面加了一个8.8.8.8的ip。YouTube上去显示TW，然后把ip规则清空，这样就只剩下domain规则，再上去，成HK了。再加上IP规则，又成TW了。
~~不过这个我没想明白啊，本来不就应该可以这样设置吗，怎么domain规则和ip规则还要分开。文档上也没说明这一点啊。
我刚刚还特地搜了，v2ray issue里有人贴的配置就有一个规则同时有域名匹配和IP匹配的，奇了怪了。~~
找到原因了，同一个规则里面多个属性之间不是 `或`的关系，而是`且`的关系，这一点在Xray文档和V2fly网站上都没有提到，反而是在原来`v2ray.com`在[路由功能](https://v2ray.com/chapter_02/03_routing.html#ruleobject)页面有用蓝色框和感叹号强调这个。

**Comment by gito10** [comment]
> #### 问题1
> * [ ]  之前版本我将局域网域名列表中的某些IP段屏蔽，通过Xray分流规则设置某些局域网走国内公网上的服务器部署xray服务端代理线路，访问该服务器的内网设备。非局域网的走VPS的Xray代理线路，但是现在这种方式行不通了。Xray版本没有变，都是1.8。如果将代理线路直接换成国内公网上的服务器部署xray服务端代理线路，就没有问题。

不知道这个问题里面的匹配规则是域名+IP还是单 IP？如果是都有，那就是上面说的问题，如果只有IP规则，那可能就是只要加了IP规则就匹配不了，跟域名+IP写在一起无关。如果是都有，可以进一步确认下，弄一个新规则，只保留IP规则，域名规则不填，看能否连通。

> #### 问题3
> * [ ]  xray分流中，访问控制中客户端全局代理，更新geodata，通过geodata分流，QQ无法登录。访问控制中客户端代理模式换为中国列表以外，QQ就可以登录了。非常奇怪，之前没这问题。貌似xray分流某些udp流量被阻止

因为中国规则是同时有IP和域名的，所以国内规则没匹配上，走了默认，可能是这个原因导致的不能登录，可以把那个默认的单个节点设置成全局再测试下，是不是QQ也登不上去。

**Comment by nftbty** [comment]
反正我先按照原来分开的写法改吧，先把问题解决了，再探究为什么写一起不行。
