### ISSUE TITLE
[Bug]: 4.61 版更新 PASSWALL版本自身 一直提示手工更新

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-package#2436]
### 描述您遇到的bug

[Bug]: 4.61 版更新 PASSWALL版本身 ，一直提示手工更新，面的组件都正常更新成功，如何正确能在线升级 PW。谢谢

### 复现此Bug的步骤

1

### 您想要实现的目的

1

### 日志信息

1

### 截图

1

### 系统相关信息

1

### 其他信息

1

**Comment by loryncien** [comment]
找前几个已关闭的 issue，有解释

**Comment by gito10** [comment]
做这个的原因详见#2384，不过我确实有打算弄passwall的自更新和ipk组件更新。而且看前几个issue，确实有很多人有这个需求，会尽快实现。

**Comment by iamyangyiok** [comment]
> 做这个的原因详见#2384，不过我确实有打算弄passwall的自更新和ipk组件更新。而且看前几个issue，确实有很多人有这个需求，会尽快实现。
感谢辛苦付出。另有个问题请教 我另有个RK3588的设备，装PW LUCI一直报CPU 架构不兼容 日志如下： pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured 。
三种IPK包aarch64_cortex-a53 、aarch64_cortex-a72 、aarch64_generic我都试了，一样错。
这个有办法把LUCI装上不。依赖包安装都没问题。

**Comment by gito10** [comment]
你看你的`/etc/openwrt_release`文件里面`DISTRIB_ARCH`是什么，或者`/etc/os-release`里的`OPENWRT_ARCH`。

**Comment by iamyangyiok** [comment]
> 你看你的`/etc/openwrt_release`文件里面`DISTRIB_ARCH`是什么，或者`/etc/os-release`里的`OPENWRT_ARCH`。

我用UNAME -m 看过 ，显示 AARCH64，但我那3个试了都不行

**Comment by gito10** [comment]
uname 显示的不是太适合openwrt，像K3，bcm4709c，uname 看是armv7l，但是因为不支持FPU，只能当armv5看。但是在openwrt就是`arm_cortax-a9`，没有`-vfp`或`-neon`后缀的，所以其实可以用其他所有`arm_xxxx`不带`vfp`和`neon`后缀的包。

**Comment by iamyangyiok** [comment]
> uname 显示的不是太适合openwrt，像K3，bcm4709c，uname 看是armv7l，但是因为不支持FPU，只能当armv5看。但是在openwrt就是`arm_cortax-a9`，没有`-vfp`或`-neon`后缀的，所以其实可以用其他所有`arm_xxxx`不带`vfp`和`neon`后缀的包。

谢谢 那我再试试

**Comment by iamyangyiok** [comment]
> uname 显示的不是太适合openwrt，像K3，bcm4709c，uname 看是armv7l，但是因为不支持FPU，只能当armv5看。但是在openwrt就是`arm_cortax-a9`，没有`-vfp`或`-neon`后缀的，所以其实可以用其他所有`arm_xxxx`不带`vfp`和`neon`后缀的包。

看了是aarch64_generic，我一开始就装的这个 还是报架构不兼容。 奇怪了

**Comment by iamyangyiok** [comment]
> > uname 显示的不是太适合openwrt，像K3，bcm4709c，uname 看是armv7l，但是因为不支持FPU，只能当armv5看。但是在openwrt就是`arm_cortax-a9`，没有`-vfp`或`-neon`后缀的，所以其实可以用其他所有`arm_xxxx`不带`vfp`和`neon`后缀的包。
> 
> 谢谢 那我再试试

不过 我核心是5.10的。目前3588只有这个

**Comment by gito10** [comment]
> 不过 我核心是5.10的。

普通软件一般对内核版本没什么要求。你的`OPENWRT_ARCH`看了吗，是什么？

**Comment by iamyangyiok** [comment]
> > 不过 我核心是5.10的。
> 
> 普通软件一般对内核版本没什么要求。你的`OPENWRT_ARCH`看了吗，是什么？

看了是aarch64_generic，我一开始就装的这个 ，也还是报架构不兼容。

**Comment by gito10** [comment]
不对啊，你的意思是其他依赖都装上了，就`luci-app-passwall`这个装不上？这个是无架构依赖的啊，是 _all的，肯定不是架构原因，你的ipk从哪找的还是自己编译的？
你从shell用命令安装看看，看全部报错都有哪些，应该是你装的ipk有对某个包的依赖，然后这个依赖包装不上导致的。
你看看是哪个依赖。

还有，你装不上，这个“一直提示手工更新”哪来的？

**Comment by nftbty** [comment]
你从shell用命令安装看看，看全部报错都有哪些，应该是你装的ipk有对某个包的依赖，然后这个依赖包装不上导致的。
你看看是哪个依赖。

**Comment by firkerword** [comment]
> 做这个的原因详见#2384，不过我确实有打算弄passwall的自更新和ipk组件更新。而且看前几个issue，确实有很多人有这个需求，会尽快实现。

没有也不影响  主要是有这个提示却不能升级感觉怪怪的  当然能像openclash一样在线更新更好

**Comment by gito10** [comment]
> 没有也不影响  主要是有这个提示却不能升级感觉怪怪的  当然能像openclash一样在线更新更好

暂时加了提示，而不是只有一个版本号。在实现自更新之前，这样看着是不是稍微好一点。
