### ISSUE TITLE
[Feature Request]: 建议完善节点导出URL功能，支持ipv6地址

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#2440]
### 描述你想要的新功能

现在导出含ipv6地址的节点信息不完整，地址只有前面一段，如：2606:4700:f1:0:8:ba79：：1。导出的结果是服务器地址只有2606，之后的都被忽略了，端口变成4700。
为方便重设重装，建议增加一键导出所有节点连URL。

### 描述你想要的解决方案

无

**Comment by iceliuhacker** [comment]
这个功能前天刚修复玩，最新版已经好了
