### ISSUE TITLE
[Bug]: UDP代理模式bug 导致全部UDP走代理

### ISSUE THREAD

**Issue by threerog** [xiaorouji/openwrt-package#2450]
### 描述您遇到的bug

TCP/UDP代理模式为`仅使用直连/代理列表`时
所有UDP流量都会走代理

其它代理模式时没有这个现象

 

### 复现此Bug的步骤

通过反复测试发现同一ip 例如`10.10.10.10`
首先这个ip并没有在直连/代理列表
通过本地连接这个ip地址(ssh/tcp)确认是我本地实际ip
通过本地访问这个ip地址的网页(tcp)确认是我本地实际ip
通过wireguard连接这个ip地址(udp)确认是代理节点的ip

### 您想要实现的目的

`10.10.10.10`这个ip既然没有在`直连/代理列表`
那TCP不走代理这很合理，因为没有命中范围
但是为什么UDP也走代理

### 日志信息

无

### 系统相关信息

passwall版本：4.62-3
passwall分支： luci-smartdns-new-version

**Comment by handsomeji** [comment]
试下最新的源码
