### ISSUE TITLE
多Socks线路配合HAProxy负载均衡+xray分流无法使用

### ISSUE THREAD

**Issue by smallprogram** [xiaorouji/openwrt-package#2458]
### 描述您遇到的bug

1. 节点配置两个xray vision线路
2. Socks配置中，添加两条socks节点，分别指向这两个xray vision节点，socks端口分别为1081，1082
3. HAProxy中配置两个负载均衡主要节点，分别为127.0.0.1:1081,127.0.0.1:1082，负载均衡端口1181，开启
4. 节点配置添加一个socks节点，备注【socks负载均衡】，地址为127.0.0.1，端口1181，**可用性测试通过**
5. 基本设置中开启xray分流，**默认节点选择任意一个xray vision测试Google，GitHub等，测试通过**
6. 基本设置中开启xray分流，**默认节点选择【socks负载均衡】，测试Google，GitHub等，测试无法连接**

具体如下图：

### 复现此Bug的步骤

![image](https://user-images.githubusercontent.com/6050360/229880267-e5230f05-4ed6-4c2c-af25-924feb2fa9de.png)

### 系统相关信息

Passwall版本：4.26-7

**Comment by gito10** [comment]
`/tmp/etc/passwall/TCP_UDP_SOCKS.json`配置文件手工检查一下有没有错误。主要是tag对不对的上，然后从inbound开始按照路由规则和本地IP端口转发模拟走一遍，看能否正确最终路由到vision节点。

昨天那个CPU占满的是什么原因，找到了吗？

**Comment by gito10** [comment]
我没有Vision节点，只有VMess，Trojan和SS节点，用的专线Trojan节点测试，用了2种方法。
1. 按照你所描述的方法，在Socks配置页面添加1081和1082两个socks节点，分别指向2个Trojan节点。在HAProxy页面使用自定义节点地址，填写`127.0.0.1:1081`和`127.0.0.1:1082`，然后节点列表添加一个Socks类型节点，地址端口为`127.0.0.1:1181`，设置该节点为分流默认节点，可以连通，并且多次测试IP，2个节点IP都有出现。
2. 可以不用在Socks配置手动添加socks转发，直接在HAProxy选择需要均衡的节点，然后把“健康检查类型”改为“可用性测试(passwall 内置实现)”，会自动添加Socks转发，同样测试通过。

从我这边Trojan可以连通情况来看，连通性是没问题的。但你那边的测试，HAProxy的配置也是没问题的。那应该不会是什么大问题，检查`TCP_UDP_SOCKS.json`应该就能看出来。或者你有没有其他类型节点，换其他类型节点有没有这个问题。

**Comment by gito10** [comment]
另外，你把前置代理勾选上，看下面规则的代理设置是不是关闭的，因为我今早发现这个前置代理的总开关关闭后，下面的选项如果选了代理，总开关关闭，并不会清除这个配置，需要先手动关闭。目前修改适配中。

**Comment by smallprogram** [comment]
我的问题，socks设置了密码，键盘敲错了。😂🤣😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁

**Comment by gito10** [comment]
> 我的问题，socks设置了密码，键盘敲错了。😂🤣😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁

你可以试试不自己添加socks转发，在haproxy健康检查改可用性测试，下面直接选择节点，就会自动生成socks转发配置，还挺方便的。

**Comment by smallprogram** [comment]
> 你可以试试不自己添加socks转发，在haproxy健康检查改可用性测试，下面直接选择节点，就会自动生成socks转发配置，还挺方便的。

试过了，非常好用。感谢

**Comment by xcyll** [comment]
> 另外，你把前置代理勾选上，看下面规则的代理设置是不是关闭的，因为我今早发现这个前置代理的总开关关闭后，下面的选项如果选了代理，总开关关闭，并不会清除这个配置，需要先手动关闭。目前修改适配中。
![2023-04-05 170043](https://user-images.githubusercontent.com/63227888/230038288-cb97bab2-3e53-4c00-a866-0eec702c4fdf.png)
前置代理的总开关是指这个👆？意思是开启了默认前置代理（即总开关），分流节点也选择了前置代理的情况下 再次关闭总开关 ，其实并没有清掉前置代理节点这个配置（还需要手动关掉分流节点的前置代理）

**Comment by gito10** [comment]
> > 另外，你把前置代理勾选上，看下面规则的代理设置是不是关闭的，因为我今早发现这个前置代理的总开关关闭后，下面的选项如果选了代理，总开关关闭，并不会清除这个配置，需要先手动关闭。目前修改适配中。
> > ![2023-04-05 170043](https://user-images.githubusercontent.com/63227888/230038288-cb97bab2-3e53-4c00-a866-0eec702c4fdf.png)
> > 前置代理的总开关是指这个👆？意思是开启了默认前置代理（即总开关），分流节点也选择了前置代理的情况下 再次关闭总开关 ，其实并没有清掉前置代理节点这个配置（还需要手动关掉分流节点的前置代理）

现在这个只管默认节点，总开关在上面
![image](https://user-images.githubusercontent.com/10704839/230057043-59f6ea2c-9e40-4e68-8b23-136da561b540.png)
这个问题已经修改适配了，检查一下没有问题就PR了。
