### ISSUE TITLE
编译时在luci下Application找不到passwall

### ISSUE THREAD

**Issue by sclsyin** [xiaorouji/openwrt-package#2465]
### 描述您遇到的bug

编译时在luci下Application找不到passwall

### 复现此Bug的步骤

feeds.conf.default 文件中已添加src-git passwall https://github.com/xiaorouji/openwrt-passwall.git

### 您想要实现的目的

在Luci中有Passwall

### 日志信息

无

### 截图

![image](https://user-images.githubusercontent.com/22511328/230524398-7aaa9bfc-f972-4f66-98cb-d5e47b1089f9.png)

### 系统相关信息

Ubuntu 20.04

**Comment by wtfr-dot** [comment]
你还差一个luci的源，添加一个src-git luci_passwall https://github.com/xiaorouji/openwrt-passwall.git;luci
