### ISSUE TITLE
[Bug]: 当tcp主节点为xray分流时自动切换中的 tcp恢复切换 功能不起作用

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#2474]
### 描述您遇到的bug

![image](https://user-images.githubusercontent.com/104726856/230735555-1cbc4715-5abb-41fc-abad-6da8bd9ee573.png)
设置如图，主节点是xray分流时，备用节点设置为应用到默认节点；
默认节点炸了后默认节点会切换到备用节点，但在原来的默认节点恢复正常后（在节点列表手动进行节点可用性测试也成功），默认节点不会从备用节点切换回去

原默认节点是vmess，备用节点是vless，核心为xray 1.7.5

### 复现此Bug的步骤

如上

### 您想要实现的目的

当xray分流中默认设置的节点正常时，能将备用节点切换回原节点

### 日志信息

2023-04-08 15:16:23: 自动切换检测：TCP节点【Xray：[txczz]】异常，切换到下一个备用节点检测！
2023-04-08 15:16:26: 自动切换检测：TCP节点【Xray：[vless_pb]】正常，切换到此节点！
2023-04-08 15:16:26: 自动切换检测：TCP节点切换完毕！

### 系统相关信息

- Passwall版本：4.59
- xray版本：1.7.5
- 只编译了passwall这一个插件

**Comment by gito10** [comment]
看你用的还是 **4.59**，现在最新版到 **4.63-1** 了，更新了几个挺好的功能。尤其是在提升翻墙可用性和负载均衡方面。
- Xray 负载均衡新增 **LeastPing** 均衡策略，对每个均衡节点定时向 Google 发起连接测试，从中选择延迟最低的节点作为流量出口。
- HAProxy 负载均衡更新不再限制节点的协议、参数必须一致，所有节点都可以放一组负载均衡。而且HAProxy本来就有主备切换功能，如果你真有**主节点可用就使用主节点**的需求，那用HAProxy负载均衡最合适了，它的主备切换肯定比自己脚本实现的强大得多，而且是平滑、无缝切换，不需要杀掉再重启Xray进程。而且可以设置n个主节点和m个备用节点。

当然如果只是单纯的想从几个不太稳的节点中选择当前可用的、最佳的节点作为出口，对节点优先级没有要求的话，也可以使用 LeastPing策略的 Xray负载均衡，同样是平滑无缝切换的。我目前一个分流规则就是使用这个，添加了6个不太稳定的小机场节点，有时候AB能用，有时候DE能用，用这个模式可以保证任何时候都能连通同时又能把那些不太稳的但还有很多流量的节点利用起来。

因此，我觉得目前的自动切换功能应该会越来越没存在感，慢慢被边缘化，到之后甚至可以去掉这个功能。

**Comment by BGzEroll** [comment]
> 看你用的还是 **4.59**，现在最新版到 **4.63-1** 了，更新了几个挺好的功能。尤其是在提升翻墙可用性和负载均衡方面。
> 
> * Xray 负载均衡新增 **LeastPing** 均衡策略，对每个均衡节点定时向 Google 发起连接测试，从中选择延迟最低的节点作为流量出口。
> * HAProxy 负载均衡更新不再限制节点的协议、参数必须一致，所有节点都可以放一组负载均衡。而且HAProxy本来就有主备切换功能，如果你真有**主节点可用就使用主节点**的需求，那用HAProxy负载均衡最合适了，它的主备切换肯定比自己脚本实现的强大得多，而且是平滑、无缝切换，不需要杀掉再重启Xray进程。而且可以设置n个主节点和m个备用节点。
> 
> 当然如果只是单纯的想从几个不太稳的节点中选择当前可用的、最佳的节点作为出口，对节点优先级没有要求的话，也可以使用 LeastPing策略的 Xray负载均衡，同样是平滑无缝切换的。我目前一个分流规则就是使用这个，添加了6个不太稳定的小机场节点，有时候AB能用，有时候DE能用，用这个模式可以保证任何时候都能连通同时又能把那些不太稳的但还有很多流量的节点利用起来。
> 
> 因此，我觉得目前的自动切换功能应该会越来越没存在感，慢慢被边缘化，到之后甚至可以去掉这个功能。

我这4.59不能主节点选择xray分流然后默认节点选择xray均衡负载，我目前有分流需求（例如chatgpt走美国节点，其他走默认节点）
对于LeastPing，我一般都是能用主节点就只用主节点，否则才用备用节点的，因此似乎不太合乎我的需求
HAProxy倒是确实不错，不过终究还是没有自动切换脚本轻量，我的需求用这个脚本就能很好的满足，不过这个脚本似乎在xray分流下检测原节点是否可用这里有点问题_(:з」∠)_

**Comment by BGzEroll** [comment]
> 看你用的还是 **4.59**，现在最新版到 **4.63-1** 了，更新了几个挺好的功能。尤其是在提升翻墙可用性和负载均衡方面。
> 
> * Xray 负载均衡新增 **LeastPing** 均衡策略，对每个均衡节点定时向 Google 发起连接测试，从中选择延迟最低的节点作为流量出口。
> * HAProxy 负载均衡更新不再限制节点的协议、参数必须一致，所有节点都可以放一组负载均衡。而且HAProxy本来就有主备切换功能，如果你真有**主节点可用就使用主节点**的需求，那用HAProxy负载均衡最合适了，它的主备切换肯定比自己脚本实现的强大得多，而且是平滑、无缝切换，不需要杀掉再重启Xray进程。而且可以设置n个主节点和m个备用节点。
> 
> 当然如果只是单纯的想从几个不太稳的节点中选择当前可用的、最佳的节点作为出口，对节点优先级没有要求的话，也可以使用 LeastPing策略的 Xray负载均衡，同样是平滑无缝切换的。我目前一个分流规则就是使用这个，添加了6个不太稳定的小机场节点，有时候AB能用，有时候DE能用，用这个模式可以保证任何时候都能连通同时又能把那些不太稳的但还有很多流量的节点利用起来。
> 
> 因此，我觉得目前的自动切换功能应该会越来越没存在感，慢慢被边缘化，到之后甚至可以去掉这个功能。

更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_

顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果；
这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了

**Comment by gito10** [comment]
> 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_

这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。

> 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了

我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。
**直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连；
**远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。
这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。

**Comment by hplee0120** [comment]
> > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> 
> 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> 
> > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> 
> 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。

这个默认dns从字面上来看的确不太好理解，你不说的话，我的理解以为是直连dns是把大陆域名交给本地dnsmasq解析，其余的走远程，远程是我以为的是所有请求都走设定的远程dns解析呢。
不过是否可以增加一个模式，比如我本地自己起了一个mosdns，我需要用到mosdns的功能和逻辑，比如国内返回双栈结果，国外优先ipv6，或者全部采用ipv4优先，因为我是将mosdns作为dnsmasq上游使用，是否可以增加一个模式，视做dnsmasq返回的dns都是可信的，因为我加了mosdns之后，已经解决污染问题了。

**Comment by hplee0120** [comment]
> > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> 
> 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> 
> > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> 
> 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。

我现在的mosdns逻辑跟你说的远程dns逻辑应该一致，都是采用这个项目，中国域名采用本地dns解析，剩余域名使用可信dns，区别在于mosdns更加灵活，可以安装自己的需求改，比如国内双栈，国外v4优先，比较优雅，而不是直接丢弃v6结果

https://github.com/felixonmars/dnsmasq-china-list

**Comment by BGzEroll** [comment]
> > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> 
> 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> 
> > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> 
> 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。

也就是说
- 代理模式是中国列表以外
- 开启chinadnsng
- **当使用中国列表外时的默认DNS** 选项选择**远程**
dns逻辑便会变成以下吗
- 未匹配中**chnlist**和**gfwlist**的域名会被chinadnsng**同时**发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果，**国内上游**返回结果匹配中chnroute表便采用**国内上游**的结果，否则便采用**可信上游**的结果

**Comment by BGzEroll** [comment]
> > > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> > 
> > 
> > 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> > > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> > 
> > 
> > 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。
> 
> 也就是说
> 
> * 代理模式是中国列表以外
> * 开启chinadnsng
> * **当使用中国列表外时的默认DNS** 选项选择**远程**
>   dns逻辑便会变成以下吗
> * 未匹配中**chnlist**和**gfwlist**的域名会被chinadnsng**同时**发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果，**国内上游**返回结果匹配中chnroute表便采用**国内上游**的结果，否则便采用**可信上游**的结果

看了下chinadns-ng的参数，新版本这边 **当使用中国列表外时的默认DNS** 选择 **直连** 时，chinadns-ng开了 **-d chn** 也就是说
- gfwlist列表里的走可信上游，其余走国内上游
- 选择 **远程** 时参数变为 **-d gfw** ，chnlist中的域名走国内上游，其余域名走可信上游

这样一来，**当使用中国列表外时的默认DNS** 选择 **直连** 时似乎和关闭chinadns-ng直接使用gfwlist没有什么不同，选择 **远程** 时倒是可以用chinadns-ng来加快匹配chnlist
不过原本的  **未匹配中 chnlist 和 gfwlist 的域名会被chinadns-ng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果， 国内上游 返回结果匹配中chnroute表便采用 国内上游 的结果，否则便采用 可信上游 的结果** ，这种逻辑已经包含gfwlist模式且对cdn友好，还能直接屏蔽掉非chnroute6表内的ipv6解析了，不知为何被放弃了_(:з」∠)_

**Comment by jxph1123** [comment]
> > > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> > 
> > 
> > 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> > > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> > 
> > 
> > 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。
> 
> 我现在的mosdns逻辑跟你说的远程dns逻辑应该一致，都是采用这个项目，中国域名采用本地dns解析，剩余域名使用可信dns，区别在于mosdns更加灵活，可以安装自己的需求改，比如国内双栈，国外v4优先，比较优雅，而不是直接丢弃v6结果
> 
> https://github.com/felixonmars/dnsmasq-china-list

你说的这个smartdns一样可以实现，在分支里面有个luci-smartdns-new-version，你可以试试，mosdns貌似和smartdns功能一样?

**Comment by handsomeji** [comment]
> > > > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> > > 
> > > 
> > > 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> > > > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> > > 
> > > 
> > > 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。
> > 
> > 
> > 也就是说
> > 
> > * 代理模式是中国列表以外
> > * 开启chinadnsng
> > * **当使用中国列表外时的默认DNS** 选项选择**远程**
> >   dns逻辑便会变成以下吗
> > * 未匹配中**chnlist**和**gfwlist**的域名会被chinadnsng**同时**发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果，**国内上游**返回结果匹配中chnroute表便采用**国内上游**的结果，否则便采用**可信上游**的结果
> 
> 看了下chinadns-ng的参数，新版本这边 **当使用中国列表外时的默认DNS** 选择 **直连** 时，chinadns-ng开了 **-d chn** 也就是说
> 
> * gfwlist列表里的走可信上游，其余走国内上游
> * 选择 **远程** 时参数变为 **-d gfw** ，chnlist中的域名走国内上游，其余域名走可信上游
> 
> 这样一来，**当使用中国列表外时的默认DNS** 选择 **直连** 时似乎和关闭chinadns-ng直接使用gfwlist没有什么不同，选择 **远程** 时倒是可以用chinadns-ng来加快匹配chnlist 不过原本的 **未匹配中 chnlist 和 gfwlist 的域名会被chinadns-ng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果， 国内上游 返回结果匹配中chnroute表便采用 国内上游 的结果，否则便采用 可信上游 的结果** ，这种逻辑已经包含gfwlist模式且对cdn友好，还能直接屏蔽掉非chnroute6表内的ipv6解析了，不知为何被放弃了_(:з」∠)_

https://github.com/xiaorouji/openwrt-passwall/tree/luci-dev
此前是因为chinadns-ng不支持nftset，所以暂时改了一下逻辑。
新版的chinadns-ng支持了，不过尚未发行正式版。

**Comment by BGzEroll** [comment]
> > > > > 更新到4.63-1试了下HAProxy，效果确实非常棒，不过健康检查类型选择passwall内置的**可用性测试**后会套一层socks，性能占用很大_(:з」∠)_，所以还是希望自动切换的脚本能修一修吧，轻量并且也算好用_(:з」∠)_
> > > > 
> > > > 
> > > > 这个确实是个问题，其实主要问题都不在套一层socks，而是套socks后一个节点一个进程，ss、ssr这些还好，如果是xray类型的节点，每个启动一个xray进程的话，占用确实很吓人，这一块是还可以优化。
> > > > > 顺便想问一下DNS设置中新增的 **当使用中国列表外时的默认DNS** 的逻辑是什么？我在4.59版本中开启chinadnsng后未匹配中chnlist和gfwlist的域名会被chinadnsng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果； 这版本更新后 **当使用中国列表外时的默认DNS** 选项选择 **直连** 时我在adguard中就不会看到有国内域名了，所以有点疑惑现在dns逻辑变成什么样的了
> > > > 
> > > > 
> > > > 我之前就说这样很容易让人搞不明白，建议把这个选项的文字改一下的。 **直连** 就是DNS按照GFWList的模式，GFWList+代理列表的域名走代理请求，其他直连； **远程** 就是DNS按照中国列表以外，中国域名列表+直连列表的域名直连请求，其他走代理请求。 这个选项仅在代理模式为**中国列表以外**时才有效。如果dnsmasq版本在2.87及以上，建议直接使用**远程**，这样DNS请求路径和实际的网络请求路径才匹配，才能获取到离代理节点最近的网站IP。
> > > 
> > > 
> > > 也就是说
> > > 
> > > * 代理模式是中国列表以外
> > > * 开启chinadnsng
> > > * **当使用中国列表外时的默认DNS** 选项选择**远程**
> > >   dns逻辑便会变成以下吗
> > > * 未匹配中**chnlist**和**gfwlist**的域名会被chinadnsng**同时**发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果，**国内上游**返回结果匹配中chnroute表便采用**国内上游**的结果，否则便采用**可信上游**的结果
> > 
> > 
> > 看了下chinadns-ng的参数，新版本这边 **当使用中国列表外时的默认DNS** 选择 **直连** 时，chinadns-ng开了 **-d chn** 也就是说
> > 
> > * gfwlist列表里的走可信上游，其余走国内上游
> > * 选择 **远程** 时参数变为 **-d gfw** ，chnlist中的域名走国内上游，其余域名走可信上游
> > 
> > 这样一来，**当使用中国列表外时的默认DNS** 选择 **直连** 时似乎和关闭chinadns-ng直接使用gfwlist没有什么不同，选择 **远程** 时倒是可以用chinadns-ng来加快匹配chnlist 不过原本的 **未匹配中 chnlist 和 gfwlist 的域名会被chinadns-ng同时发送给国内上游和可信上游解析，再根据chnroute进行选择返回结果， 国内上游 返回结果匹配中chnroute表便采用 国内上游 的结果，否则便采用 可信上游 的结果** ，这种逻辑已经包含gfwlist模式且对cdn友好，还能直接屏蔽掉非chnroute6表内的ipv6解析了，不知为何被放弃了_(:з」∠)_
> 
> https://github.com/xiaorouji/openwrt-passwall/tree/luci-dev 此前是因为chinadns-ng不支持nftset，所以暂时改了一下逻辑。 新版的chinadns-ng支持了，不过尚未发行正式版。

期待新版chinadns-ng正式发布时改回逻辑(～￣▽￣)～。所有疑问都解决了，我这边就关闭issue了(～￣▽￣)～

**Comment by handsomeji** [comment]
最新源码已修复标题问题

**Comment by ceozero** [comment]
> 最新源码已修复标题问题

请问HAProxy 测试延迟现在是多少ms会不用。我经常看到有900多ms的节点还是绿的，有时候负载到这个节点后会很卡，几乎没法用。是否可以自行设置超过多少ms后就不用这个节点负载了。
HAProxy以后是否可以来直接添加xray的负载， 让xray先选优秀的节点在给HAProxy来负载均衡。
个人理解xray的负载均衡是多个烂节点选最优秀一个的走，HAProxy的负载时会按权重平衡到每个绿节点，不知道我理解的有没有问题。。
