### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by dddfgeer** [xiaorouji/openwrt-package#2480]
关于分流功能 建议优化一下

xray 分流总节点那边 设置了分流域名 比如需要设置各种复杂的代码 才能设置 不过有时候设置了 不起效果 建议优化一下这个功能 变得简单上手一些

**Comment by gito10** [comment]
是说的这个地方的设置吗？
![image](https://user-images.githubusercontent.com/10704839/230929274-fdb5ef64-da4b-48e4-a34f-4c0f839409cf.png)

**Comment by dddfgeer** [comment]
是的 太过于复杂 建议优化一下 变得简易上手

**Comment by gito10** [comment]
呃，这个还真没什么可以优化的，V2ray/Xray的路由规则就是这样设定的，一般分流也没有太多需要手动添加的，一些域名直接用纯字符串也就可以了，不一定要加那些前缀。老luci的选项设置控件很有限，没法实现复杂的配置界面。

**Comment by dddfgeer** [comment]
> 呃，这个真什么的，v2ray/xray/xray的的由就是这样这样设定设定，一般是设定这样设定就是是这样是一般一般分流分流也没有多需要需要手动添加前缘。老luci的选项设置控制很有限，没法实现现在复杂的配置界面。

那有办法吗 弃用xray v2ray的分流设置 重新开发一个简单上手的分流

**Comment by xcyll** [comment]
这个分流利用的就是xray/v2ray的分流
简单点的 可以试试—vssr

**Comment by xcyll** [comment]
google 第一个结果就是

**Comment by handsomeji** [comment]
使用geosite和geoip要开全局模式，或可使用passwall2

**Comment by dddfgeer** [comment]
比如我想这样子 某个机场 屏蔽了某个网站 其他机场节点能用这个网站 解决办法 就是使用分流功能分流用其他机场的节点来分流那个网站 不过设置了不起效果 不知道怎么回事

> 使用geosite和geoip要打开全局模式，或者可以使用passwall2
