### ISSUE TITLE
[Bug]: 请问下这个怎么更新？

### ISSUE THREAD

**Issue by haweu** [xiaorouji/openwrt-package#2481]
### 描述您遇到的bug

怎么更新？？

### 复现此Bug的步骤

ChinaDNS-NG 版本【 2023.03.10 】  发现新版本，但未能获得新版本的下载地址。

### 您想要实现的目的

ChinaDNS-NG 版本【 2023.03.10 】  发现新版本，但未能获得新版本的下载地址

### 日志信息

ChinaDNS-NG 版本【 2023.03.10 】  发现新版本，但未能获得新版本的下载地址

### 系统相关信息

passwall：4.61-4

**Comment by nftbty** [comment]
你的路由器是什么架构处理器？不会是mips64或者mips64le吧？你看看`/etc/os-release`里面`OPENWRT_ARCH`是什么，我看看是什么问题。

**Comment by gito10** [comment]
查了下ChinaDNS-NG官方仓库，最新发布的是预览版，官方没有发布预览版的可执行程序，所以这不是bug，已将检测更新改为只检测正式版。
而且因为是预发布版，可能不稳定，可以等稍后确认没问题，发布了稳定版再升级。
如果真有升级需要的话，可以从release下载对应架构的压缩包，把ChinaDNS-NG的ipk解压出来安装。
也可以在这个[源仓库](https://osdn.net/projects/openwrt-passwall-build/storage/)里单独下载ChinaDNS-NG安装。

接下来会对组件更新功能升级加强，暂时只能先这样麻烦一点手动升级了。
这个issue就可以关掉了。

**Comment by haweu** [comment]
> 查了下ChinaDNS-NG官方仓库，最新发布的是预览版，官方没有发布预览版的可执行程序，所以这不是bug，已将检测更新改为只检测正式版。 而且因为是预发布版，可能不稳定，可以等稍后确认没问题，发布了稳定版再升级。 如果真有升级需要的话，可以从release下载对应架构的压缩包，把ChinaDNS-NG的ipk解压出来安装。 也可以在这个[源仓库](https://osdn.net/projects/openwrt-passwall-build/storage/)里单独下载ChinaDNS-NG安装。
> 
> 接下来会对组件更新功能升级加强，暂时只能先这样麻烦一点手动升级了。 这个issue就可以关掉了。

谢谢 明白了

**Comment by haweu** [comment]
cpu 是AArch64 Processor : Cortex-A53 * 4 arm



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianhe ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 晚上11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 请问下这个怎么更新？ (Issue #2481)





 
你的路由器是什么架构处理器？不会是mips64或者mips64le吧？你看看/etc/os-release里面OPENWRT_ARCH是什么，我看看是什么问题。
