### ISSUE TITLE
[Feature Request]: immortalwrt停更18.06，手动下载无法安装4.63

### ISSUE THREAD

**Issue by Java2Boy** [xiaorouji/openwrt-package#2483]
### 描述你想要的新功能

环境：N1 Docker OPENWRT immortalwrt18.06

手动下载ipk文件，提示系统中4.55已是最新版，无法安装

### 描述你想要的解决方案

是否能提供适合18.06版的ipk安装包，非常感谢

**Comment by gito10** [comment]
你是从哪里下载的哪个ipk，应该时有依赖未满足？
~~从我的仓库[release](https://github.com/nftbty/openwrt-passwall/releases)下载试试。~~
官方发布版已经是全部op都可以安装的版本了，第一次升级时请使用`--force-reinstall`参数安装。
