### ISSUE TITLE
[Bug]: B站经常被代理了，评论是代理IP那种，PASSWALL设置如下

### ISSUE THREAD

**Issue by laaArmy** [xiaorouji/openwrt-package#2485]
### 描述您遇到的bug

DNS是ADG，PVE独立的虚拟机，PASSWALL专用的，国内是默认运营商IP，IPV6打开
![QQ截图20230412002217](https://user-images.githubusercontent.com/38807357/231227161-05c01cb5-6619-4648-800e-c07abf674812.png)
![QQ截图20230412002259](https://user-images.githubusercontent.com/38807357/231227167-0ff10b39-b6be-4262-b950-e881fffd80e4.png)

另外我想问下，我中国段这么叠BUFF，规则是同时生效还是只一个
![QQ截图20230412002010](https://user-images.githubusercontent.com/38807357/231227221-d176fdc1-8d7e-4443-9651-76427d901248.png)

### 复现此Bug的步骤

ChinaDNS-NG+远程DNS就会出现（不会立刻出现，通常是早上设置，夜晚回家就发现这个BUG出来了）

### 您想要实现的目的

知道发生原因

### 日志信息

额......这个问题看系统日志能看出什么嘛
PASSWALL自己有日志不

### 系统相关信息

OpenWRT  2022.3.3
内核版本 | 5.15.86
luci-app-passwall git-24.101.45345-4c691b6
chinadns-ng | 2023.04.11-2-36

**Comment by jianminLee** [comment]
你是不是没有看到远程DNS下面那两行字?

**”远程DNS可以避免更多的DNS泄露，但会导致规则列表外的某些国内域名可能会走代理！
直连DNS上网体验可能会更佳，但是会泄露DNS！“**

**Comment by laaArmy** [comment]
> 你是不是没有看到远程DNS下面那两行字?
> 
> **”远程DNS可以避免更多的DNS泄露，但会导致规则列表外的某些国内域名可能会走代理！
> 直连DNS上网体验可能会更佳，但是会泄露DNS！“**

我知道，但只是不确定规则有没有B站
而且我开了直连后，看某些盗版漫画（套了cf的cdn）
在cf页面会卡住，或者图片加载不出

**Comment by jianminLee** [comment]
那你可以把你要看到额盗版漫画站新建一个规则走代理啊！B站很有可能DNS解析到国外了。

**Comment by laaArmy** [comment]
> 那你可以把你要看到额盗版漫画站新建一个规则走代理啊！B站很有可能DNS解析到国外了。

前面这个问题应该跟人家网站无关，是cf出现国内cdn节点后才有这个问题的

至于DNS解析，如果是以前还没出现这个选项，是那种方式解析的？

**Comment by jianminLee** [comment]
你不如直接试试直连DNS，再去看B站试试效果。
你那个盗版漫画用规则一劳永逸，你走代理那CF肯定会返回离你代理最近的CDN节点，CF走代理肯定比你直连要快得多，何况你直连CF目前还有问题。**远程DNS可以避免更多的DNS泄露，但会导致规则列表外的某些国内域名可能会走代理！**，不知道你那个盗版漫画是不是在列表内，如果没有可能和B站一样走了代理，反正是走代理，不如自己加规则。

**Comment by smallprogram** [comment]
> > 你是不是没有看到远程DNS下面那两行字?
> > **”远程DNS可以避免更多的DNS泄露，但会导致规则列表外的某些国内域名可能会走代理！
> > 直连DNS上网体验可能会更佳，但是会泄露DNS！“**
> 
> 我知道，但只是不确定规则有没有B站 而且我开了直连后，看某些盗版漫画（套了cf的cdn） 在cf页面会卡住，或者图片加载不出

尝试一下把高级设置中TCP转发端口设置为所有

**Comment by quanljh** [comment]
借这个issue问一下，为什么最近dashboard的DNS都显示未运行了？
