### ISSUE TITLE
[Bug]: ERROR: package/feeds/passwall/gn [host] failed to build

### ISSUE THREAD

**Issue by Mikaelpeng** [xiaorouji/openwrt-package#2486]
### 描述您遇到的bug

 **ERROR: package/feeds/passwall/gn [host] failed to build.**

make[3]: Entering directory '/home/mikael/openwrt/feeds/passwall/gn'
ninja -C /home/mikael/openwrt/build_dir/hostpkg/gn-2023-02-17-b25a2f8c/out
ninja: Entering directory `/home/mikael/openwrt/build_dir/hostpkg/gn-2023-02-17-b25a2f8c/out'
[1/287] CXX src/base/files/file.o
FAILED: src/base/files/file.o 
g++ -MMD -MF src/base/files/file.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/files/file.cc -o src/base/files/file.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
[2/287] CXX src/base/files/file_path_constants.o
FAILED: src/base/files/file_path_constants.o 
g++ -MMD -MF src/base/files/file_path_constants.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/files/file_path_constants.cc -o src/base/files/file_path_constants.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
[3/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
g++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/command_line.cc -o src/base/command_line.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
[4/287] CXX src/base/environment.o
FAILED: src/base/environment.o 
g++ -MMD -MF src/base/environment.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/environment.cc -o src/base/environment.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
[5/287] CXX src/base/files/file_enumerator.o
FAILED: src/base/files/file_enumerator.o 
g++ -MMD -MF src/base/files/file_enumerator.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/files/file_enumerator.cc -o src/base/files/file_enumerator.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
[6/287] CXX src/base/files/file_path.o
FAILED: src/base/files/file_path.o 
g++ -MMD -MF src/base/files/file_path.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/base/files/file_path.cc -o src/base/files/file_path.o
g++: error: unrecognized command line option '-Wextra-semi'; did you mean '-Wextra'?
ninja: build stopped: subcommand failed.
Makefile:60: recipe for target '/home/mikael/openwrt/build_dir/hostpkg/gn-2023-02-17-b25a2f8c/.built' failed
make[3]: *** [/home/mikael/openwrt/build_dir/hostpkg/gn-2023-02-17-b25a2f8c/.built] Error 1
make[3]: Leaving directory '/home/mikael/openwrt/feeds/passwall/gn'
time: package/feeds/passwall/gn/host-compile#0.12#0.04#0.27
    ERROR: package/feeds/passwall/gn [host] failed to build.
package/Makefile:114: recipe for target 'package/feeds/passwall/gn/host/compile' failed
make[2]: *** [package/feeds/passwall/gn/host/compile] Error 1
make[2]: Leaving directory '/home/mikael/openwrt'
package/Makefile:110: recipe for target '/home/mikael/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/mikael/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mikael/openwrt'
/home/mikael/openwrt/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2

### 复现此Bug的步骤

..

### 您想要实现的目的

..

### 日志信息

..

### 系统相关信息

..

**Comment by WYC-2020** [comment]
真是从来就不搜索一下相关issue

**Comment by WYC-2020** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2443#issue-1650354298
https://github.com/coolsnowwolf/lede/issues/11044
