### ISSUE TITLE
第一次从Release下载passwall ipk升级时，请加上`--force-reinstall`参数安装，之后再升级不需要

### ISSUE THREAD

**Issue by gito10** [xiaorouji/openwrt-package#2489]
- 从release下载ipk升级luci-app-passwall的，如果当前版本是自编译版或从其他渠道下载的，在安装时，请务必带上`--force-reinstall`参数，否则之前因为依赖关系而自动安装的Xray、SS等组件在升级安装时，将被系统自动移除。
- 只是第一次需要`--force-reinstall`，之后再从release页面下载更新，可以照常安装，不受影响。
- 如果已经因为升级导致组件被移除，可以从release下载路由器对应架构的packages，解压后，找到需要的组件，重新按照。如果是组件更新页可以直接下载的组件，也可以直接下载使用。

**Comment by Java2Boy** [comment]
r**t@OpenWRT:/tmp/upload# opkg install luci-app-passwall_4.64-5_all.ipk --force-reinstall
Removing package luci-app-passwall from root...
Not deleting modified conffile /usr/share/passwall/rules/lanlist_ipv4.
Not deleting modified conffile /usr/share/passwall/rules/direct_host.
Installing luci-app-passwall (4.64-5) to root...
Configuring luci-app-passwall.
Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.
iptables v1.8.7 (legacy): unknown option "--restore-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): unknown option "--save-mark"
Try `iptables -h' or 'iptables --help' for more information.
Collected errors:
 * resolve_conffiles: Existing conffile /usr/share/passwall/rules/direct_host is different from the conffile in the new package. The new conffile will be placed at /usr/share/passwall/rules/direct_host-opkg.
 * resolve_conffiles: Existing conffile /usr/share/passwall/rules/lanlist_ipv4 is different from the conffile in the new package. The new conffile will be placed at /usr/share/passwall/rules/lanlist_ipv4-opkg.

固件里：Passwall 版本【 4.55-1 4.64-5 】  最新版本：4.64-5-，目前暂不支持自动更新，如需更新，请自行编译或下载ipk然后手动安装。

**Comment by gito10** [comment]
iptables报错跟 #1924 一样，你可以看看相应的组件都有没有。我翻了一下从4.55-1到4.64-5的Makefile更新，没有新增package依赖，新版跟4.55-1应该是一样的。

最下面是显示同时有2个版本号吗？


你的op是什么版本？
