### ISSUE TITLE
[Bug]: 访问控制开启后无法上网

### ISSUE THREAD

**Issue by lionkingc** [xiaorouji/openwrt-package#2493]
### 描述您遇到的bug

开启<访问控制>想进行分流 , 根据IP走不同节点. 打开后无法上网,查看日志发现TPROXY:11201  TCP和UDP被设置成同一个了.

### 复现此Bug的步骤

1.访问控制
2.创建规则
3.将规则里的TCP节点和UDP节点 指向和基本设置里的不同节点

### 您想要实现的目的

指定的设备走各自的代理

### 日志信息

2023-04-13 10:09:54: 删除相关防火墙规则完成。
2023-04-13 10:09:54: 清空并关闭相关程序和缓存完成。
2023-04-13 10:09:54: TCP节点：[blog]，监听端口：1041
2023-04-13 10:09:54:   - 域名解析 DNS Over TCP...
2023-04-13 10:09:54: UDP节点：[blog]，监听端口：1051
2023-04-13 10:09:54: 过滤服务配置：准备接管域名解析...
2023-04-13 10:09:54:   - 以上所列以外及默认：127.0.0.1#15353
2023-04-13 10:09:54:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-04-13 10:09:54: 开始加载防火墙规则...
2023-04-13 10:09:56: 加入负载均衡的节点到nftset[vpsiplist]直连完成
2023-04-13 10:09:56: 加入所有节点到nftset[vpsiplist]直连完成
2023-04-13 10:09:57: 加载路由器自身 TCP 代理...
2023-04-13 10:09:57:   - 启用 TPROXY 模式
2023-04-13 10:09:57:   - [0]，屏蔽代理UDP 端口：80,443
2023-04-13 10:09:57: 加载路由器自身 UDP 代理...
2023-04-13 10:09:57: 访问控制：
2023-04-13 10:09:57:   - 备注【cfg1530ec】，MAC【00:0C:29:54:48:B2】，使用TCP节点[shop] [全局代理]<TPROXY:11201>代理所有端口
2023-04-13 10:09:57:   - 备注【cfg1530ec】，MAC【00:0C:29:54:48:B2】，使用UDP节点[shop] [全局代理]<TPROXY:11201>代理所有端口
2023-04-13 10:09:57:   - 备注【cfg1630ec】，MAC【00:0C:29:05:17:A1】，使用TCP节点[shop] [全局代理]<TPROXY:11201>代理所有端口
2023-04-13 10:09:57:   - 备注【cfg1630ec】，MAC【00:0C:29:05:17:A1】，使用UDP节点[blog] [全局代理]<TPROXY:1051>代理所有端口
2023-04-13 10:09:57: TCP默认代理：使用TCP节点[blog] [全局代理]<TPROXY:1041>代理所有端口
2023-04-13 10:09:57: UDP默认代理：使用UDP节点[blog] [全局代理]<TPROXY:1051>代理所有端口
2023-04-13 10:09:57: 防火墙规则加载完成！
2023-04-13 10:09:58: 重启 dnsmasq 服务
2023-04-13 10:09:58: 运行完成！

### 系统相关信息

OpenWrt 22.03.3
Passwall 4.64-2
Xray 1.8.0

**Comment by handsomeji** [comment]
能否提供一下更详细的信息：

访问控制的这两个MAC是在同一条里面还是两条？
TCP和UDP 是直接选择节点吗，还是有使用“与TCP相同”？

**Comment by handsomeji** [comment]
我这边用iptables是正常的，也一直在用。
nftables未知是否有此问题

**Comment by lionkingc** [comment]
![ok_11](https://user-images.githubusercontent.com/23330617/232230241-6585665f-6602-4151-bf40-0a531df3558b.jpg)
![ok_22](https://user-images.githubusercontent.com/23330617/232230258-db970c34-112b-40f7-bf17-c893ae59f775.jpg)
![ok_33](https://user-images.githubusercontent.com/23330617/232230262-6df1659f-ea5d-461a-ac86-1da3cf3415f0.jpg)


> 能否提供一下更详细的信息：
> 
> 访问控制的这两个MAC是在同一条里面还是两条？ TCP和UDP 是直接选择节点吗，还是有使用“与TCP相同”？


我重新配了几次,都不行, "访问控制"里的规则 , 只有跟首页"主要" 里一样的TCP节点/UDP节点就可以联网, 走别的代理则不行.

**Comment by lionkingc** [comment]
> 我这边用iptables是正常的，也一直在用。 nftables未知是否有此问题

meta nfproto ipv4 meta l4proto tcp ether saddr 00:0c:29:e0:e2:13 counter packets 282 bytes 22614 meta mark 0x00000001 tproxy ip to :11201 comment "toblog"
ip protocol udp ether saddr 00:0c:29:e0:e2:13 counter packets 0 bytes 0 meta mark 0x00000001 tproxy ip to :11201 comment "toblog"

meta l4proto tcp iif "lo" counter packets 0 bytes 0 meta mark 0x00000001 tproxy to :1041 comment "本机"
meta l4proto tcp counter packets 0 bytes 0 meta mark 0x00000001 tproxy to :1041 comment "默认"
meta l4proto udp iif "lo" counter packets 15 bytes 1140 meta mark 0x00000001 tproxy to :1051 comment "本机"
ip protocol udp ether saddr 00:0c:29:05:17:a1 counter packets 0 bytes 0 meta mark 0x00000001 tproxy ip to :1051 comment "toshop"

nft list ruleset > /root/nftables.conf
在输出的文件里查找端口找到上面这几条规则

**Comment by lionkingc** [comment]
> 我这边用iptables是正常的，也一直在用。 nftables未知是否有此问题

经过对比查找, 最终发现两个分路规则中,有一条多了一个规则 ,手工删除后, 功能正常了.位置在:

	chain PSW_REDIRECT {
		ip protocol udp ether saddr 00:0c:29:05:17:a1 udp dport 53 counter packets 0 bytes 0 redirect to :11401 comment "toshop"
	}

**Comment by lionkingc** [comment]
还发现一个问题,  "acl_rule 访问控制" 里, 如果对每个规则设置了不同的DNS服务器, 例如 
规则1
过滤模式:Xray 
TCP:  远程 DNS 
1.1.1.1 (CloudFlare)
规则2 设置成8.8.8.8

测试出来的DNS 却是  "首页"-"基本设置"-"DNS"-远程 DNS里设的9.9.9.9
说明此功能没有生效.

**Comment by handsomeji** [comment]
那条规则就是劫持对应设备的请求DNS到一个专用的DNS的服务器，你删掉肯定就走了默认的DNS服务器的

**Comment by handsomeji** [comment]
应该要查查看 11401 这个DNS服务器有无成功运行

**Comment by lionkingc** [comment]
> 应该要查查看 11401 这个DNS服务器有无成功运行

好像没有, "查看日志" 里显示的: 使用TCP节点[blog] [全局代理]<TPROXY:11201)代理所有端口
但PSW_REDIRECT里创建的是11401. 删除后改成11201, 该虚拟机依旧无法打开网页.

--------------------------------------------------------------
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      6264/dnsmasq
tcp        0      0 192.168.0.2:53          0.0.0.0:*               LISTEN      6264/dnsmasq
tcp        0      0 127.0.0.1:15353         0.0.0.0:*               LISTEN      4254/xray
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3014/uhttpd
tcp        0      0 127.0.0.1:11301         0.0.0.0:*               LISTEN      5295/xray
tcp        0      0 192.168.0.2:55106       192.xx.xx.xxx:443       ESTABLISHED 4368/xray
tcp        0      0 :::1070                 :::*                    LISTEN      4254/xray
tcp        0      0 :::1041                 :::*                    LISTEN      4254/xray
tcp        0      0 ::1:53                  :::*                    LISTEN      6264/dnsmasq
tcp        0      0 fdda:ba20:cefb::1:53    :::*                    LISTEN      6264/dnsmasq
tcp        0      0 fe80::20c:29ff:feb8:d698:53 :::*                LISTEN      6264/dnsmasq
tcp        0      0 :::11201                :::*                    LISTEN      5295/xray

udp        0      0 127.0.0.1:15353         0.0.0.0:*                           4254/xray
udp        0      0 127.0.0.1:11301         0.0.0.0:*                           5295/xray
udp        0      0 127.0.0.1:53            0.0.0.0:*                           6264/dnsmasq
udp        0      0 192.168.0.2:53          0.0.0.0:*                           6264/dnsmasq
udp        0      0 162.159.200.1:123       0.0.0.0:*                           4368/xray
udp        0      0 :::1051                 :::*                                4368/xray
udp        0      0 :::1070                 :::*                                4254/xray
udp        0      0 ::1:53                  :::*                                6264/dnsmasq
udp        0      0 fdda:ba20:cefb::1:53    :::*                                6264/dnsmasq
udp        0      0 fe80::20c:29ff:feb8:d698:53 :::*                            6264/dnsmasq
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING        557 1997/ubusd          /var/run/ubus/ubus.sock
unix  8      [ ]         DGRAM                       779 2363/logd           /dev/log
unix  3      [ ]         STREAM     CONNECTED       4805 6258/ujail          
unix  3      [ ]         STREAM     CONNECTED        836 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED       2609 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED       4806 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED       2608 3803/ujail          
unix  2      [ ]         DGRAM                      4916 6371/crond          
unix  3      [ ]         STREAM     CONNECTED       1405 2740/netifd         
unix  2      [ ]         DGRAM                      1273 2624/dropbear       
unix  2      [ ]         DGRAM                       558 1997/ubusd          
unix  3      [ ]         STREAM     CONNECTED        560 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED        559 1/procd             
unix  3      [ ]         STREAM     CONNECTED        780 2363/logd           
unix  3      [ ]         STREAM     CONNECTED        835 2417/rpcd           
unix  3      [ ]         STREAM     CONNECTED        781 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED       1775 1997/ubusd          /var/run/ubus/ubus.sock
unix  2      [ ]         DGRAM                      3440 1/procd             
unix  3      [ ]         STREAM     CONNECTED       4827 1997/ubusd          /var/run/ubus/ubus.sock
unix  3      [ ]         STREAM     CONNECTED       4826 6264/dnsmasq        
unix  3      [ ]         STREAM     CONNECTED       1406 1997/ubusd          /var/run/ubus/ubus.sock
unix  2      [ ]         DGRAM                      1403 2740/netifd         
unix  2      [ ]         DGRAM                      1446 2740/netifd         
unix  3      [ ]         STREAM     CONNECTED       1521 1997/ubusd          /var/run/ubus/ubus.sock
unix  2      [ ]         DGRAM                      4834 6264/dnsmasq        
unix  3      [ ]         STREAM     CONNECTED       1520 2811/odhcpd         
unix  2      [ ]         DGRAM                      1691 2944/dropbear       
unix  3      [ ]         STREAM     CONNECTED       1774 3014/uhttpd

**Comment by handsomeji** [comment]
11401 是DNS服务端口
11201 是透明代理端口
缺一不可

**Comment by lionkingc** [comment]
> 应该要查查看 11401 这个DNS服务器有无成功运行

确实, 没有成功运行, 手工运行了下这个配置/tmp/etc/passwall/acl/cfg1530ec/dnsmasq.conf
提示  recompile with HAVE_IPSET defined to enable ipset directives at line 1 of /tmp/etc/passwall/acl/cfg1530ec/dnsmasq.d/ipset.conf 里面生成的内容是 ipset=xxxx
而/tmp/dnsmasq.d/passwall里的ipset.conf是 nftset=xxxx . 
*** 虽然后台设置了使用Nft,但这个访问控制还是会按ipt来生成,导致DNS服务没有运行.
复制过去后, 成功实现功能 !!!~

新的问题出现: 想测下NAT类型,结果发现这条分路的UDP不通. 另一条跟首页相同的分路则是fullcone

**Comment by handsomeji** [comment]
感谢反馈，找到问题所在就好解决了

**Comment by lionkingc** [comment]
> 感谢反馈，找到问题所在就好解决了

下次更新可以让"访问控制"里生成的基于子分路的ipset.conf , 依据后台"防火墙工具"里的设置,来生成对应规则吗.这样就不用重启或者修改其他设置时, 又需要去把ipset.conf 手工改成nftable规则了.谢谢.
---------------------------------------
请问 /tmp/etc/passwall/acl/cfg1530ec/var_udp_port  11201  
TCP和UDP都是11201 是正常的吗?

似乎netstat里的udp只留意到有11301 
目前用NatTypeTester测试UDPtype 显示UDPBlocked

---------------------------------------------------
/tmp/etc/passwall/acl/101ad656e09e415d8b1b23e49fcc3de9_DNS_TCP_SOCKS_11101.json 里

      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "port": 11201,
      "protocol": "dokodemo-door",
      "tag": "tcp_redir"
    },
    {
      "port": 11301,
      "protocol": "dokodemo-door",
      "settings": {
        "port": 53,
        "network": "tcp,udp",
        "address": "1.1.1.1"
      },
      "tag": "dns-in",
      "listen": "127.0.0.1"
    }

**Comment by handsomeji** [comment]
试一下最新代码

**Comment by lionkingc** [comment]
> 试一下最新代码

新代码还没试, 刚找到UDP无效的原因了,  程序生成的/tmp/etc/passwall/acl/xxxx_DNS_TCP_SOCKS_11101.json
里只有"tag": "tcp_redir"  缺少"tag": "udp_redir" 这一项, 补齐代码后, 成功实现udp . 圆满.

**Comment by lionkingc** [comment]
> 试一下最新代码

新代码对访问控制里的分流是正常的了,查看了ipset.config正常,dns的分支配置成功启动.
新生成的acl/xxx.json也有加入udp_redir.   经测试,新发现的小问题 :
*** ACL分流控制中有一条规则无法使用UDP. 
----------------------
之前acl生成的规则, 如果该分流的设置与luci页里的"基本设置"-"主要"-"TCP节点"/"UDP节点" 相同, 则/tmp/etc/passwall/acl/cfg1430ec 里只会有三个文件, 并不会像/cfg1530ec里一样有dns和xray的config

***: 本次更新使得三个文件之一的var_udp_port里的端口变成了1041 , 以前版本是1051,跟随 首页-"主要"里的设置. 主进程里监听的也是1051.

**Comment by lionkingc** [comment]
"基本设置"-"主要"- "UDP 节点" 
 设成"与TCP节点相同" , 统一使用1041 , 则可正常使用

**Comment by cs282111** [comment]
怎么解决?
访问控制目前必须跟主配置一个节点才能上网.
