### ISSUE TITLE
[Bug]: 22.03 fw4模式使用一段时间 系统日志出现nftables cache initialization failed等错误

### ISSUE THREAD

**Issue by imkenf** [xiaorouji/openwrt-package#2494]
### 描述您遇到的bug

使用官方最新openwrt22.03版本编译后出现大量Error: cache initialization failed: Protocol error错误。 重启passwall后正常一段时间后又出现，更换过节点等。
用21版本的源码+fw3，无此问题。尝试更换或使用不同版本的dnsmasq也无解，目前使用的dnsmasq版本为 2.89-4烦请各位大佬帮忙看看。谢谢

### 复现此Bug的步骤

重启或运行一段时间系统日志出现大量 Error: cache initialization failed: Protocol error错误 

### 您想要实现的目的

修复TX

### 日志信息

Thu Apr 13 15:08:37 2023 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 1d
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#6053
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain gmhz.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain archives.gov.tw
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain modernchinastudies.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain proxydns.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain twitter.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain bnrmetal.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain timesofindia.indiatimes.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain internetdefenseleague.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain tuidang.net
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain taiwandaily.net
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain sixth.biz
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain savetibet.de
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain springwood.me
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain friendsoftibet.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain cosmic.monar.ch
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain churchinhongkong.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain londonchinese.ca
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain libertytimes.com.tw
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain de-sci.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain discordapp.net
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain vn.hao123.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain seezone.net
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain igotmail.com.tw
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain vital247.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain iipdigital.usembassy.gov
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain twittbot.net
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain ienergy1.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain pornrapidshare.com
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7913 for domain business-humanrights.org
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: more servers are defined but not logged
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for test
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for local
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 5 names
Thu Apr 13 15:08:37 2023 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Thu Apr 13 15:08:42 2023 daemon.err dnsmasq[2]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[93]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[92]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[92]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[92]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[93]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[92]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 15:46:05 2023 daemon.err dnsmasq[93]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 15:46:06 2023 daemon.err dnsmasq[100]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 15:46:06 2023 daemon.err dnsmasq[99]: nftset inet fw4 gfwlist
Thu Apr 13 20:30:21 2023 kern.info kernel: [315918.184905] dnsmasq[9347]: segfault at 0 ip 00007ff0c8ade763 sp 00007fffa13f1870 error 4 in libnftables.so.1[7ff0c8ac5000+52000]
Thu Apr 13 20:30:21 2023 kern.info kernel: [315918.196596] Code: c6 48 8d 83 04 02 00 00 48 39 f0 73 05 4c 39 ee eb 0c 48 39 c6 73 0b 48 8d 56 2c 48 39 d0 73 02 0f 0b b9 0b 00 00 00 48 89 c7 <f3> a5 e9 10 01 00 00 be 10 00 00 00 48 89 ef ff 15 28 58 08 00 be
Thu Apr 13 20:30:21 2023 daemon.err dnsmasq[638]: nftset inet fw4 blacklist Error: Could not process rule: File exists
Thu Apr 13 20:30:21 2023 daemon.err dnsmasq[645]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[653]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[655]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[655]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[653]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[655]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[653]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[655]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[656]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[660]: nftset inet fw4 gfwlist netlink: Error: Could not process rule: Invalid argument
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[659]: nftset inet fw4 gfwlist Error: No such file or directory
Thu Apr 13 20:31:20 2023 daemon.err dnsmasq[663]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[669]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[666]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[667]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[667]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[666]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[669]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[669]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource temporarily unavailable
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[667]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[666]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[669]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource temporarily unavailable
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[666]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:21 2023 daemon.err dnsmasq[667]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:32:22 2023 daemon.err dnsmasq[672]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:22 2023 daemon.err dnsmasq[672]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:32:22 2023 daemon.err dnsmasq[671]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:32:22 2023 daemon.err dnsmasq[674]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:32:22 2023 daemon.err dnsmasq[674]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:00 2023 daemon.err dnsmasq[683]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[688]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[685]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[685]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[693]: nftset inet fw4 gfwlist
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[693]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[694]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[694]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[694]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[694]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[1]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[1]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[1]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[691]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[691]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[695]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[691]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[695]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[695]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[695]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[700]: nftset inet fw4 blacklist
Thu Apr 13 20:34:02 2023 daemon.err dnsmasq[698]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[721]: nftset inet fw4 gfwlist
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[723]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[721]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[727]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[727]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[726]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[729]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[729]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Resource busy
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[730]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Invalid argument
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[730]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[730]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[730]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[732]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[733]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[733]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[733]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[733]: nftset inet fw4 gfwlist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error
Thu Apr 13 20:35:32 2023 daemon.err dnsmasq[735]: nftset inet fw4 blacklist netlink: Error: cache initialization failed: Protocol error

### 系统相关信息

Passwall  4.62

**Comment by uingei** [comment]
升级 nftables 到 1.0.7 再试试，或者直接用我这个
https://github.com/uingei/openwrt/tree/openwrt-22.03-fw4

**Comment by imkenf** [comment]
谢谢楼上兄弟，查了一下目前nftables 已经是1.2.7版本了呢
![image](https://user-images.githubusercontent.com/52485888/231939016-02af6b0d-6cd4-4463-a577-1244b50170c7.png)

**Comment by uingei** [comment]
Thu Apr 13 20:30:21 2023 kern.info kernel: [315918.184905] dnsmasq[9347]: segfault at 0 ip 00007ff0c8ade763 sp 00007fffa13f1870 error 4 in libnftables.so.1[7ff0c8ac5000+52000]
看起来不是passwall本身的问题
我两个平台都用的luci-smartdns-new-version分支跑着挺正常

**Comment by imkenf** [comment]
我先切换成luci-smartdns-new-version分支试试再反馈，谢谢老哥

**Comment by ShanStone** [comment]
应该是dnsmasq的问题，遇到短时间内大量添加至某一指定nftset就会出现这个错误，可以尝试使用smartdns分流方式

**Comment by imkenf** [comment]
经过几天排查，基本确定是像楼上兄弟说的是分流模式的问题，我用了smartdns，开了两组dns端口，一组是国内，一组是国外。我一直用dnsmasq远程模式对应国外那组dns端口。切换回smartdns选项就没有报这个错误。但又发现几个问题：
1.smartdns的国外组名程序写死了passwall_proxy，不能自定义。
2.dnsmasq模式下写死了127.0.0.1#15353对外的端口，我想修改其他端口无效，如下日志
2023-05-07 21:32:41:   - 域名解析：使用UDP协议请求DNS（127.0.0.1#15353）...
2023-05-07 21:32:41:   * 要求代理 DNS 请求，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
2023-05-07 21:32:41:   - 节点列表中的域名(vpsiplist)：127.0.0.1#6053
2023-05-07 21:32:41:   - 域名白名单(whitelist)：127.0.0.1#6053
2023-05-07 21:32:41:   - 代理域名表(blacklist)：127.0.0.1#15353
2023-05-07 21:32:42:   - 防火墙域名表(gfwlist)：127.0.0.1#15353
2023-05-07 21:32:44:   - 中国域名表(chnroute)：127.0.0.1#6053
2023-05-07 21:32:45:   - 以上所列以外及默认：127.0.0.1#15353

3.另外就是smartdns模式下分流不太正常，因原来4.66-2版本不论是dnsmasq模式还是smartdns国内地址都用国外的解释，就切回3.65-2版本了。

**Comment by fixsssator** [comment]
我也有同样的问题
但是我不能改变 dnsmasq 因为我使用 PBR (Policy Based Routing)
所以问题仍然存在

**Comment by ShanStone** [comment]
> 我也有同样的问题 但是我不能改变 dnsmasq 因为我使用 PBR (Policy Based Routing) 所以问题仍然存在

可以尝试使用ChianDnsNG，确保版本都在最新
![image](https://github.com/xiaorouji/openwrt-passwall/assets/31815718/db2ab185-a170-490e-a543-71568cc929c1)
