### ISSUE TITLE
[Bug]: reality节点只能存在一个

### ISSUE THREAD

**Issue by Pacio** [xiaorouji/openwrt-package#2495]
### 描述您遇到的bug

开启了reality功能的节点只有第一个添加的能正常连通，后续再添加该类节点必然不通还会引起科学失效一会

### 复现此Bug的步骤

就是正常添加节点的步骤，其他所有协议类型的节点只要不开启reality无论添加多少都可以正常连通，只要开启reality功能的节点超过一个就不通

### 您想要实现的目的

能添加多个reality节点并正常使用

### 日志信息

Fri Apr 14 14:00:27 2023 kern.notice kernel: [    2.170501] SCSI subsystem initialized
Fri Apr 14 14:00:27 2023 kern.debug kernel: [    2.172222] libata version 3.00 loaded.
Fri Apr 14 14:00:27 2023 kern.info kernel: [    2.172222] ACPI: bus type USB registered
Fri Apr 14 14:00:27 2023 kern.info kernel: [    2.172222] usbcore: registered new interface driver usbfs
Fri Apr 14 14:00:27 2023 kern.info kernel: [    2.177714] usbcore: registered new interface driver hub
Fri Apr 14 14:00:27 2023 kern.info kernel: [    2.182184] usbcore: registered new device driver usb
Fri Apr 14 14:00:27 2023 kern.info kernel: [    2.187279] pps_core: LinuxPPS API ver. 1 registered
3 2023 daemon.warn miniupnpd[6104]: upnp_event_process_notify: connect(10.0.0.206:2869): Operation timed out

### 系统相关信息

passwall版本：4.64-3
浏览器版本：edge  112.0.1722.46
系统：lede最新版x86源码编译 6.1.23内核

**Comment by handsomeji** [comment]
This is too outrageous...

**Comment by Pacio** [comment]
> This is too outrageous...

我也很不理解~但是该现象我测试了两个版本了，一直存在

**Comment by jh0072110** [comment]
> > This is too outrageous...
> 
> 我也很不理解~但是该现象我测试了两个版本了，一直存在

那…我…里面存的…五个reality节点…是假的嘛……

**Comment by Pacio** [comment]
刚刚把xray服务端和客户端版本都更新到1.8.1，该bug已经消失，看来和passwall没关系~
此贴关闭
