### ISSUE TITLE
[Bug]: high volatility ping Issues!

### ISSUE THREAD

**Issue by Recoba86** [xiaorouji/openwrt-package#2497]
### 描述您遇到的bug

I have passwall and another plugin named luci-app-xray in my openwrt machines
openwrt version is 22.0.3.3 and its running on a virtual machines

problem is when I use passwall to connect to my x-ray nodes ping volatility is very high
here is a photo of the ping test
![image](https://user-images.githubusercontent.com/70960815/232085873-584593ac-b582-4891-b241-a0022dd59bbf.png)

but when I use luci-app-xray ping is very stable, check the image:
![image](https://user-images.githubusercontent.com/70960815/232086658-a5c64cef-105f-4c26-85e5-b79cf2ad6a20.png)

I use the same DNS Server on both plugins
x-ray version is 1.8
and passwall is last version
can anyone help what should I try?
sorry I can't speak Chinese
it's

### 复现此Bug的步骤

using xray nodes

### 您想要实现的目的

to stable ping in passwall

### 日志信息

don't have!

### 系统相关信息

passwall 4.64-3
openwrt 22.03.3
xray core: 1.8

**Comment by handsomeji** [comment]
This is not VPN...
passwall won't proxy ICMP.
