### ISSUE TITLE
[Feature Request]: 关于日志的进一步完善

### ISSUE THREAD

**Issue by iceliuhacker** [xiaorouji/openwrt-package#2504]
### 描述你想要的新功能

自上次完善了日志功能后，发现有部分重要的日志被打到了/dev/null，因此建议再次完善部分日志功能。

### 描述你想要的解决方案

在app.sh里我通过：
echolog "${file_func} $*" $ln_name $output 
发现：
`2023-04-17 11:20:21: /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/acl/30af68582af442ffab5d71e257414f97_DNS_TCP_UDP_SOCKS_11101.json xray /dev/null`
这样的类似内容。也就是有部分需要的日志被打到/dev/null了。鉴于这样，因此需要对[ "${output}" != "/dev/null" ]的判断做一些修改:
`[ "${output}" != "/dev/null" ] && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global sys_log "0")`
建议改为：
方案一，只要ln_name是所需的应用就满足条件：
`echo ${ln_name} | egrep -q 'xray|v2ray|trojan|naiveproxy|brook|ss|hysteria' && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global sys_log "0")`

方案二，只要ln_name不是dns这类辅助应用就满足条件：
`(echo ${ln_name} | grep -q -i dns || exit 0 ) && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global sys_log "0")`

方案三，$@能找到TCP和UDP关键字就满足条件：
`echo $@ | egrep -q 'TCP|UDP' && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global sys_log "0")`

另，有经过多次测试，发现TCP/UDP的日志都是记录到一起的，因此就没有必要区分协议，就删除protocol变量。
完整版如下：
```
        [ -n "${file_func}" ] || echolog "  - 找不到 ${ln_name}，无法启动..."
        echo $@ | egrep -q 'TCP|UDP' && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global s
ys_log "0")
        #[ "${output}" != "/dev/null" ] && local persist_log_path=$(config_t_get global persist_log_path) && local sys_log=$(config_t_get global sys_log "0
")
        if [ -z "$persist_log_path" ] && [ "$sys_log" != "1" ]; then
                ${file_func:-echolog " - ${ln_name}"} "$@" >${output} 2>&1 &
        else
                if [ -n "${persist_log_path}" ]; then
                        mkdir -p ${persist_log_path}
                        local log_file=${persist_log_path}/passwall_${ln_name}_$(date '+%F').log
                        echolog "记录到持久性日志文件：${log_file}"
                        ${file_func:-echolog " - ${ln_name}"} "$@" >> ${log_file} 2>&1 &
                        sys_log=0
                fi
                if [ "${sys_log}" == "1" ]; then
                        echolog "记录 ${ln_name} 到系统日志"
                        ${file_func:-echolog " - ${ln_name}"} "$@" 2>&1 | logger -t PASSWALL_${ln_name} &
                fi
        fi
```

### 描述你考虑过的替代方案

无

### 其他信息

无

**Comment by iceliuhacker** [comment]
@nftbty 好兄弟，来活了……

**Comment by gito10** [comment]
这几天甲流了，跟新冠阳了差不多，坐电脑前没法集中精力，估计得等两天，不过可以先讨论。

**Comment by iceliuhacker** [comment]
> 这几天甲流了，跟新冠阳了差不多，坐电脑前没法集中精力，估计得等两天，不过可以先讨论。

甲流得好几天，这个问题基本方案我也给出了。躺着没事想动脑子的时候可以参考下。

**Comment by liuhgiceblood** [comment]
> 这几天甲流了，跟新冠阳了差不多，坐电脑前没法集中精力，估计得等两天，不过可以先讨论。

这个怎么关闭了……
