### ISSUE TITLE
[Bug]: 最新版本4.64-4的xray 分流节点失效

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#2512]
### 描述您遇到的bug

编译lede的版本合入4.64-4后，xray分流主节点失效，测试连通性不通，实际挂入tcp也不通。各分流结点单独测试没问题。

### 复现此Bug的步骤

none

### 您想要实现的目的

RCA and fix

### 日志信息

Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: lua: /usr/lib/lua/luci/passwall/api.lua:616: attempt to index local 'url' (a nil value)
Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: stack traceback:
Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: 	/usr/lib/lua/luci/passwall/api.lua:616: in function 'parseURL'
Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: 	/usr/lib/lua/luci/passwall/util_xray.lua:678: in function 'func'
Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: 	/usr/lib/lua/luci/passwall/util_xray.lua:1299: in main chunk
Tue Apr 18 16:32:27 2023 daemon.err uhttpd[2619]: 	[C]: ?

### 系统相关信息

4.64-4

**Comment by xiaorouji** [comment]
重启

**Comment by handsomeji** [comment]
操作失误，已修复
