### ISSUE TITLE
升级4.64-4失败[Bug]: 

### ISSUE THREAD

**Issue by ceozero** [xiaorouji/openwrt-package#2513]
### 描述您遇到的bug

root@iStoreOS:~# opkg install /tmp/ipk/luci-app-passwall_4.64-4_all.ipk --force-reinstall
Removing package luci-app-passwall from root...
Installing luci-app-passwall (4.64-4) to root...
Configuring luci-app-passwall.
lua: /usr/lib/lua/luci/passwall/api.lua:616: attempt to index local 'url' (a nil value)
stack traceback:
        /usr/lib/lua/luci/passwall/api.lua:616: in function 'parseURL'
        /usr/lib/lua/luci/passwall/util_xray.lua:678: in function 'func'
        /usr/lib/lua/luci/passwall/util_xray.lua:1299: in main chunk
        [C]: ?

### 复现此Bug的步骤

4.64-3升级安装。使用
opkg install /tmp/ipk/luci-app-passwall_4.64-4_all.ipk
和
opkg install /tmp/ipk/luci-app-passwall_4.64-4_all.ipk --force-reinstall
都报错失败了。

### 您想要实现的目的

这是我的问题还是程序bug？

### 日志信息

Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: lua: /usr/lib/lua/luci/passwall/api.lua:616: attempt to index local 'url' (a nil value)
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: stack traceback:
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/api.lua:616: in function 'parseURL'
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/util_xray.lua:678: in function 'func'
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/util_xray.lua:1299: in main chunk
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	[C]: ?
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: lua: /usr/lib/lua/luci/passwall/api.lua:616: attempt to index local 'url' (a nil value)
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: stack traceback:
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/api.lua:616: in function 'parseURL'
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/util_xray.lua:678: in function 'func'
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	/usr/lib/lua/luci/passwall/util_xray.lua:1299: in main chunk
Tue Apr 18 17:12:54 2023 daemon.notice procd: /etc/rc.d/S99zzz_passwall: 	[C]: ?

### 系统相关信息

passwall 4.64-3 升级到 4.64-4

**Comment by handsomeji** [comment]
操作失误，已修复

**Comment by ceozero** [comment]
> 操作失误，已修复

嗯，升级4.64.5成功了，
虽然有个opkg_conf_load: could not lock /var/lock/opkg.lock: resource temporarily unavailable.的报错，但是无伤大雅了。
