### ISSUE TITLE
[Bug]: 自动更新页面无法选中并保存geosite、geoip自动更新的选项

### ISSUE THREAD

**Issue by solarflows** [xiaorouji/openwrt-package#2516]
### 描述您遇到的bug

在自动更新页面选中geosite和geoip并保存，刷新页面后没有选中，点手动更新也没有更新geosite、geoip。

### 复现此Bug的步骤

1.选择自动更新页面
2.勾选geosite、geoip
3.保存并应用

### 您想要实现的目的

geosite、geoip的自动更新可以保存

### 日志信息

无

### 截图

保存前
![image](https://user-images.githubusercontent.com/57535444/232950426-a8b14fa9-e9bc-4803-952d-5b3fd6357c1d.png)
保存后
![image](https://user-images.githubusercontent.com/57535444/232950486-a08a981e-3c74-49c9-bf62-1d0cb3e32312.png)

### 系统相关信息

Passwall版本：4.64-3
Openwrt版本: OpenWrt R23.4.1

### 其他信息

1.没有看到关于无法写入或者写入错误的任何日志
2.貌似只要选中后手动更新，更新完以后就有了

**Comment by cpuer** [comment]
勾选后，点击手动更新就可以保存了，不知道是bug还是本来就这样设计。

**Comment by WYC-2020** [comment]
就是这样设计的，我原来就说过这个不是很合理来的

> 勾选后，点击手动更新就可以保存了，不知道是bug还是本来就这样设计。
