### ISSUE TITLE
官方原版的openwrt安装passwall无法使用

### ISSUE THREAD

**Issue by YiGeRen-yl** [xiaorouji/openwrt-package#2520]
### 描述您遇到的bug

我用官方得openwrt 系统装passwall
节点延迟都能检测出来 
但是开启后，谷歌检测无法通过
日志显示这些内容

### 复现此Bug的步骤

[Bug]: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法透明代理！

### 您想要实现的目的

我希望在官方原版的openwrt安装passwall

### 日志信息

[Bug]: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法透明代理！

### 系统相关信息

OpenWrt 22.03

**Comment by YiGeRen-yl** [comment]
系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法透明代理！
日志显示这个内容

**Comment by uingei** [comment]
passwall高级设置里防火墙工具选nftables试试

**Comment by YiGeRen-yl** [comment]
> passwall高级设置里防火墙工具选nftables试试

passwall 需要 哪些依赖能说一下吗

**Comment by GreatMichaelLee** [comment]
> passwall高级设置里防火墙工具选nftables试试

passwall里没有nftable这个只有iptables咋回事，已经在lede编译里的Luci->application->luci-app-passwall->configuration里勾上nftable_transparent_proxy了，但编译出来还是没有，不知道咋回事

**Comment by uingei** [comment]
> > passwall高级设置里防火墙工具选nftables试试
> 
> passwall 需要 哪些依赖能说一下吗

iptables 支持需要以下包
dnsmasq-full ipset ipt2socks iptables(或者iptables-zz-legacy) iptables-mod-conntrack-extra iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat ip6tables(或者ip6tables-zz-legacy) ip6tables-mod-nat

nftables 支持需要
dnsmasq-full nftables kmod-nft-socket kmod-nft-tproxy kmod-nft-nat

**Comment by SuPerCxyz** [comment]
![image](https://user-images.githubusercontent.com/17843307/233902669-0ef2ee29-29c5-4b82-a698-0291cf342061.png)
节点日志一直没有额外输出  不知道流量是不是没有转发到passwall
也是官方openwrt安装的  节点延迟和可用性测试都没问题  在其他设备上都能正常使用代理的服务端

**Comment by chanfried** [comment]
我这里是 chinadns-ng （chinadns-ng_2023.05.08-31_x86_64.ipk）升级到最新版就可以了。

**Comment by laaArmy** [comment]
> > > passwall高级设置里防火墙工具选择nftables尝试
> > 
> > 
> > passwall 需要哪些依赖能说一下吗
> 
> iptables 支持需要以下包 dnsmasq-full ipset ipt2socks iptables(或者 iptables-zz-legacy) iptables-mod-conntrack-extra iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat ip6tables(或者ip6tables -zz-legacy) ip6tables-mod-nat
> 
> nftables 支持需要 dnsmasq-full nftables kmod-nft-socket kmod-nft-tproxy kmod-nft-nat

哪里可以找到这个？passwall需要的依赖
