### ISSUE TITLE
[Bug]: haproxy在编译前得配置时被取消勾选后，还是会编译进固件里

### ISSUE THREAD

**Issue by yunhai20082008** [xiaorouji/openwrt-package#2526]
### 描述您遇到的bug

用的openwrt官方和passwall昨天最新源码且只集成了passwall和luci。
因为看了passwall2似乎没有负载均衡，碰巧有人用了passwall也没有负载均衡，我怀疑是不是他没有装haproxy，就也在编译得时候取消了haproxy，发现还是会被编译得，这算是问题吗？

### 复现此Bug的步骤

没有

### 您想要实现的目的

没有

### 日志信息

没有

### 系统相关信息

没有

**Comment by xcyll** [comment]
没遇到过
rm -rf ./tmp && rm -rf .config
make menuconfig
删除配置 重来试试？
