### ISSUE TITLE
[Bug]: Xray的DNS使用自定义的DoH无法正常工作

### ISSUE THREAD

**Issue by bcseputetto** [xiaorouji/openwrt-package#2531]
### 描述您遇到的bug

使用自定义DoH地址无法解析

### 复现此Bug的步骤

基本设置，DNS
过滤模式Xray-DoH
远程DNS 自定义的DoH，例如日本 https://doh-jp.blahdns.com/dns-query
就无法解析

### 您想要实现的目的

希望自定义DoH能正常工作，主要是VPS上自己搭建了DNS服务，想用自己的DoH服务器

### 日志信息

N/A

### 系统相关信息

passwall 4.65-1
openwrt 21.02.3

**Comment by handsomeji** [comment]
格式如下：
https://dns.adguard.com/dns-query,176.103.130.130

**Comment by bcseputetto** [comment]
> 格式如下： https://dns.adguard.com/dns-query,176.103.130.130

成功了，原来要这么写！！
