### ISSUE TITLE
[Bug]: Xray最新协议Reality搭建使用passwall不可以玩魔兽世界，无法通行。

### ISSUE THREAD

**Issue by cccsue88** [xiaorouji/openwrt-package#2533]
### 描述您遇到的bug

[Bug]: Xray最新协议Reality1.81搭建，使用passwall不可以玩魔兽世界，无法通行。

### 复现此Bug的步骤

[Bug]: Xray最新协议Reality1.81搭建，使用passwall不可以玩魔兽世界，无法通行。

### 您想要实现的目的

[Bug]: Xray最新协议Reality1.81搭建，使用passwall不可以玩魔兽世界，无法通行。

### 日志信息

[Bug]: Xray最新协议Reality1.81搭建，使用passwall不可以玩魔兽世界，无法通行。

### 系统相关信息

Passwall 4.65-2

### 其他信息

[Bug]: Xray最新协议Reality1.81搭建，使用passwall不可以玩魔兽世界，无法通行。

**Comment by cccsue88** [comment]
Xray最新协议Reality搭建使用passwall不可以玩魔兽世界，无法通行。无法执行UDP吗

**Comment by Gzxhwq** [comment]
没有测试条件，NAT type tester是Fullcone和双EndPoint Independent没有问题的。

还有一个，如果客户端升级到1.8.1，服务器端也要升级到1.8.1，因为XUDP有更改，开启XUDP Mux且不等于0的情况下，会可能不能往前兼容

**Comment by cccsue88** [comment]
Windows-V2rayN,启用Tun模式才可以正常使用，但是passwall没有这个功能，造成不能通过游戏。

**Comment by cccsue88** [comment]
我用的是openwrt ,passwall,缺少Tun模式。

**Comment by Gzxhwq** [comment]
信息太少了，没法判断问题所在，tun可以的话看样子是规则问题，可以尝试全局走xray看能不能通

**Comment by cccsue88** [comment]
Passwall  TCP UDP 默认代理模式已经更改到全局，他也是不可以。

**Comment by Gzxhwq** [comment]
NAT测试结果是什么？ https://github.com/HMBSbige/NatTypeTester/releases

**Comment by cccsue88** [comment]
![221212](https://user-images.githubusercontent.com/131676335/234298308-1b620635-8944-4805-b0ac-f03a15da2fbb.jpg)

**Comment by swxk521** [comment]
最新版passwall这样正常吗？
![rYSti4GvtA](https://user-images.githubusercontent.com/61259428/234300934-3068e75a-b4d3-46da-8ded-7e83945ae4b7.png)
![Y5n1wrjrvX](https://user-images.githubusercontent.com/61259428/234300957-177432ca-6699-40b3-a81b-fb3477945a73.png)

**Comment by cccsue88** [comment]
我的openwrt passwall  4.65-2   Xary版本1.81

**Comment by Gzxhwq** [comment]
测试结果是符合预期的，应该是其他问题。例如这个https://github.com/xiaorouji/openwrt-passwall2/pull/8

**Comment by cccsue88** [comment]
使用passwall访问youtube是通过的，暴雪游戏是不能用。
![33331](https://user-images.githubusercontent.com/131676335/234303917-60efbf4d-6c30-4b06-b6ad-bbe35adbe742.jpg)

**Comment by swxk521** [comment]
![image](https://user-images.githubusercontent.com/61259428/234304253-8b832808-6e04-4e5c-b319-24acd8cf6c3e.png)
openwrt passwall 4.65-2 Xary版本1.81  Reality并开启mux

**Comment by Gzxhwq** [comment]
这问题不太好定位，只能说应该和reality无关

**Comment by cccsue88** [comment]
能不能在openwrt  passwall增加个启用tun模式.

**Comment by iceliuhacker** [comment]
我觉得你来这里问效果更好。
https://github.com/XTLS/Xray-core/issues

**Comment by handsomeji** [comment]
UDP应该没有问题的，刚玩了一下GTA5联机无问题。
