### ISSUE TITLE
[Bug]: connection speed issue

### ISSUE THREAD

**Issue by Ahmedeisa25** [xiaorouji/openwrt-package#2537]
### 描述您遇到的bug

in othersettings when TCP Redir Ports are "common use" the connection speed is me full speed which is 30mb 
but when i change the TCP Redir Ports to "all" I only get 15mb speed

### 复现此Bug的步骤

.

### 您想要实现的目的

.

### 日志信息

 I need it to get full speed when TCP Redir Ports to "all" to redirect all trafic cause in common use it dosen"t 

### 截图

.

### 系统相关信息

.

### 其他信息

.

**Comment by handsomeji** [comment]
This network environment is not controlled by PassWall.
