### ISSUE TITLE
[Feature Request]: 重启订阅或无法科学时订阅

### ISSUE THREAD

**Issue by niunaiyi** [xiaorouji/openwrt-package#2538]
### 描述你想要的新功能

当盒子重启或passwall启动时，自动订阅。虽然有定时订阅功能，但是也保不齐服务器什么时候失效。这个时候要进入系统，重新订阅，有点麻烦，而且对不熟悉的人不太友好。所以能加上不能科学时重新订阅或重启时自动订阅。

### 描述你想要的解决方案

1。无法科学时，自动订阅。
2。重启时，重新订阅

### 描述你考虑过的替代方案

目前是在启动脚本时加了个延时脚本，60秒后订阅

**Comment by handsomeji** [comment]
这些都是不可抗力因素，一般不会考虑。
自己可写脚本实现。
