### ISSUE TITLE
[Bug]: xray分流奈飞 使用的节点还是默认节点

### ISSUE THREAD

**Issue by gnlhazs123** [xiaorouji/openwrt-package#2539]
### 描述您遇到的bug

用xray分流节点分流奈飞 但是奈飞跑的节点还是默认的那个节点  不知为啥

### 复现此Bug的步骤

使用xray分流节点 

### 您想要实现的目的

解决奈飞分流

### 日志信息

2023-04-27 19:42:37: 清空并关闭相关程序和缓存完成。
2023-04-27 19:42:37: 过滤服务配置：准备接管域名解析...
2023-04-27 19:42:37:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2023-04-27 19:42:37:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2023-04-27 19:42:37:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-04-27 19:42:37: 开始加载防火墙规则...
2023-04-27 19:42:37: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2023-04-27 19:42:37: 加入所有节点到ipset[vpsiplist]直连完成
2023-04-27 19:42:37: 加载路由器自身 TCP 代理...
2023-04-27 19:42:37:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2023-04-27 19:42:37:   - [0]，屏蔽代理UDP 端口：80,443
2023-04-27 19:42:37: 加载路由器自身 UDP 代理...
2023-04-27 19:42:37: 访问控制：
2023-04-27 19:42:38: TCP默认代理：使用TCP节点[分流总节点] [中国列表以外](REDIRECT:1041)代理所有端口
2023-04-27 19:42:38: UDP默认代理：使用UDP节点[分流总节点] [中国列表以外](TPROXY:1041)代理所有端口
2023-04-27 19:42:38: 防火墙规则加载完成！
2023-04-27 19:42:41: 重启 dnsmasq 服务
2023-04-27 19:42:41: 运行完成！

### 系统相关信息

git-23.088.34636-f8cc111
istoreos

**Comment by xcyll** [comment]
xray负载均衡？
https://github.com/xiaorouji/openwrt-passwall/discussions/2391#discussioncomment-5659947

**Comment by xcyll** [comment]
用了xray负载均衡？
https://github.com/xiaorouji/openwrt-passwall/discussions/2391#discussioncomment-5659947

**Comment by gnlhazs123** [comment]
> 用了xray负载均衡？
> [#2391 (comment)](https://github.com/xiaorouji/openwrt-passwall/discussions/2391#discussioncomment-5659947)

没有 啥都没动

**Comment by gnlhazs123** [comment]
> 用了xray负载均衡？
> [#2391 (comment)](https://github.com/xiaorouji/openwrt-passwall/discussions/2391#discussioncomment-5659947)

甚至我重装openwrt都没用

**Comment by xcyll** [comment]
啥都没动？高级设置是默认设置吗

**Comment by xcyll** [comment]
![2023-04-28 174405](https://user-images.githubusercontent.com/63227888/235114700-a2e71142-6a42-40d6-8fa5-701e6d7d6143.png)

**Comment by xcyll** [comment]
规则管理 这两个勾选下 手动更新下 在看看

**Comment by xcyll** [comment]
![2023-04-28 175611](https://user-images.githubusercontent.com/63227888/235118684-80765c01-68ac-4b38-9960-4f556bfa6f5a.png)

**Comment by xcyll** [comment]
手动更新 这两个 再看看

**Comment by xcyll** [comment]
![2023-04-28 180453](https://user-images.githubusercontent.com/63227888/235119098-16d9e8ab-edd4-45fd-9047-1835c792f255.png)

**Comment by xcyll** [comment]
手动更新这两个 再看看

**Comment by xcyll** [comment]
手动更新 这两个 再看看

**Comment by gnlhazs123** [comment]
> 手动更新这两个 再看看

这俩更新过了 刚装github就更新 不然分流根本用不了 说没有geosite那个规则

**Comment by gnlhazs123** [comment]
> 高级设置里流量嗅探开着的吧

开着

**Comment by gnlhazs123** [comment]
> 高级设置里流量嗅探开着的吧

![Uploading IMG_1151.jpeg…]()

**Comment by xcyll** [comment]
最新版吗 清空ipset试试

**Comment by xcyll** [comment]
![023-04-28 181058](https://user-images.githubusercontent.com/63227888/235120332-2c4b1694-d118-41e2-9bbd-5f3ce403fddf.png)

**Comment by gnlhazs123** [comment]
> ![023-04-28 181058](https://user-images.githubusercontent.com/63227888/235120332-2c4b1694-d118-41e2-9bbd-5f3ce403fddf.png)

这个选项在哪？

**Comment by xcyll** [comment]
基本设置 -DNS--

**Comment by xcyll** [comment]
你的是最新版吗

**Comment by xcyll** [comment]
![2023-04-28 1818021](https://user-images.githubusercontent.com/63227888/235121767-1ecb4cba-1c88-40d1-96c5-1bbd67ab8f8b.png)

**Comment by xcyll** [comment]
估计解决不了你的问题  哪里出的问题就不清楚了
不过我这边最新版(23/4)分流没问题--（除了xray-leastPing模式-负载均衡所涉及的分流）

**Comment by gnlhazs123** [comment]
> 估计解决不了你的问题
> 不过我这边最新版(23/4)分流没问题--（除了xray-leastPing模式-负载均衡所涉及的分流）

我回去试试吧 谢谢老哥 不介意的话能留个联系方式吗

**Comment by xcyll** [comment]
istoreos
换个别的固件试试🌝觉得pw应该没问题 不确定🌫

**Comment by xiaorouji** [comment]
流量嗅探 (V2ray/Xray) √

**Comment by handsomeji** [comment]
流量嗅探 (V2ray/Xray)  打钩√
流量嗅探只供路由使用 (Xray) 不打勾

**Comment by czkwg8** [comment]
应该是默认规则优先级的问题，你把NF的提升到Proxy上面就好了
