### ISSUE TITLE
Question about sing-box . . .

### ISSUE THREAD

**Issue by M33FT** [xiaorouji/openwrt-package#2541]
### 描述你想要的新功能

Thank you for your wonderful program. What should I do if I want to use sing-box kernel like V2ray or Xray, which loads all configs in Luci and I can easily make my Node?
Did I understand correctly that you only put sing-box in your Git and you don't have plans for it like Xray and V2ray? it's true ? If it is true, can you tell me when this will happen?

### 描述你想要的解决方案

. . .

**Comment by M33FT** [comment]
@xiaorouji
Is there anyone here to answer me?

**Comment by jh0072110** [comment]
If u wanna use sing-box core for client in openwrt u only can try this project just for now.
https://github.com/immortalwrt/homeproxy
