### ISSUE TITLE
[Bug]: 自定义被墙的网站后仍然无法通过代理打开

### ISSUE THREAD

**Issue by man2018** [xiaorouji/openwrt-package#2544]
### 描述您遇到的bug

是这样的：有几个网站我使用passwall打不开，我在passwall配置里面的代理列表、hosts处都配置了该域名，仍然打不开

### 复现此Bug的步骤

是这样的：有几个网站我使用passwall打不开，我在passwall配置里面的代理列表、hosts处都配置了该域名，仍然打不开

### 您想要实现的目的

这种情况有办法解决吗

### 日志信息

无

### 系统相关信息

4.65-2

**Comment by handsomeji** [comment]
清空 IPSET 后 跟着FAQ做

**Comment by man2018** [comment]
> 清空 IPSET 后 跟着FAQ做

还是无法代理成功呢，这个问题从我用passwall以来一直存在这个问题，我恢复出厂设置都不行

**Comment by wtfr-dot** [comment]
提供的信息太少，打不开的错误信息是什么？passwall的配置？dns解析记录？如果可以提供一下网址测试

**Comment by man2018** [comment]
> 提供的信息太少，打不开的错误信息是什么？passwall的配置？dns解析记录？如果可以提供一下网址测试

passwall版本：4.65-2
sina.com.hk 这个域名需要代理，配置在passwall--规则列表--代理列表 里面（直接添加的sina.com.hk）

passwall基本设置--DNS设置如下：
过滤模式：通过TCP请求DNS
远程DNS：127.0.0.1:5300（这是adguard home）
ChinaDNS-NG：没有勾选
当前用中国列表时的默认DNS：远程DNS

2023-05-04 08:39:42: 删除相关防火墙规则完成。
2023-05-04 08:39:42: 清空并关闭相关程序和缓存完成。
2023-05-04 08:39:42: TCP节点：[reality]，监听端口：1041
2023-05-04 08:39:42: 过滤服务配置：准备接管域名解析...
2023-05-04 08:39:42:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2023-05-04 08:39:42:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2023-05-04 08:39:42:   - 以上所列以外及默认：127.0.0.1#15353
2023-05-04 08:39:42:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-05-04 08:39:42: 开始加载防火墙规则...
2023-05-04 08:39:42: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2023-05-04 08:39:42: 加入所有节点到ipset[vpsiplist]直连完成
2023-05-04 08:39:43: 加载路由器自身 TCP 代理...
2023-05-04 08:39:43:   - 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/5300 端口的访问
2023-05-04 08:39:43:   - [0]，屏蔽代理UDP 端口：80,443
2023-05-04 08:39:43: 加载路由器自身 UDP 代理...
2023-05-04 08:39:43: TCP默认代理：使用TCP节点[reality] [中国列表以外](REDIRECT:1041)代理所有端口
2023-05-04 08:39:43: UDP默认代理：使用UDP节点[reality] [中国列表以外](TPROXY:1041)代理所有端口
2023-05-04 08:39:43: 防火墙规则加载完成！
2023-05-04 08:39:43: 重启 dnsmasq 服务
2023-05-04 08:39:43: 配置定时任务：自动更新规则。
2023-05-04 08:39:43: 运行完成！

**Comment by wangdaye078** [comment]
你访问A网站，而A网站的页面上还有些内容是B域名下面的，B域名也被墙了，而这些内容又是必须的，那你只加A域名到代理列表里面，网页还是会无法打开。
解决办法：用一个能看到代理了什么域名的工具，比如在电脑上用v2rayN就能看到代理了哪些网站，用它把访问A的时候顺带访问的BCD都找出来，然后实验，找出到底哪个是被墙的关键域名。

**Comment by handsomeji** [comment]
先确定你的远程DNS上游走的是代理而不是本地？
查看自定义的域名，解析出来的ip是否已写入blacklist的ipset

**Comment by wtfr-dot** [comment]
试了一下，默认的黑白名单里没有sina.com.hk，dns通过smartdns正常解析出ip为：218.213.85.210，passwall的默认设置为代理也打不开网页，连接直接重置了，但能ping通，应该是走的直连但被阻止了，log里没有任何连接记录，然后将域名加入代理列表里就能通过代理正常访问了，log里也有连接记录，所以应该是你dns解析有问题

补充一下，sina.com.hk要通过代理解析

![image](https://user-images.githubusercontent.com/81218740/236213789-ddd8e414-ab30-4aed-b10a-8709d752d27c.png)

![QQ截图20230504174428](https://user-images.githubusercontent.com/81218740/236202804-dfb146b6-c623-4460-8bbb-a7000a511caf.png)

![微信图片_20230504202721](https://user-images.githubusercontent.com/81218740/236203916-9ae52c05-9aaa-498a-acf9-ee054a7fc72b.jpg)

![image](https://user-images.githubusercontent.com/81218740/236204518-eedb414b-b971-4599-9a49-ef754b427eb8.png)

**Comment by man2018** [comment]
> 然后将域名加入代理列表里就能通过代理正常访问了，log里也有连接记录，所以应该是你dns解析有问题

你是4.65-2版本吗？我的远程DNS是自建的doh（没有被屏蔽）

**Comment by man2018** [comment]
> 试了一下，默认的黑白名单里没有sina.com.hk，dns通过smartdns正常解析出ip为：218.213.85.210，passwall的默认设置为代理也打不开网页，连接直接重置了，但能ping通，应该是走的直连但被阻止了，log里没有任何连接记录，然后将域名加入代理列表里就能通过代理正常访问了，log里也有连接记录，所以应该是你dns解析有问题
> 
> 补充一下，sina.com.hk要通过代理解析
> 
> ![image](https://user-images.githubusercontent.com/81218740/236213789-ddd8e414-ab30-4aed-b10a-8709d752d27c.png)
> 
> ![QQ截图20230504174428](https://user-images.githubusercontent.com/81218740/236202804-dfb146b6-c623-4460-8bbb-a7000a511caf.png)
> 
> ![微信图片_20230504202721](https://user-images.githubusercontent.com/81218740/236203916-9ae52c05-9aaa-498a-acf9-ee054a7fc72b.jpg)
> 
> ![image](https://user-images.githubusercontent.com/81218740/236204518-eedb414b-b971-4599-9a49-ef754b427eb8.png)

我ping和dig 域名都是正常的

**Comment by man2018** [comment]
![image](https://user-images.githubusercontent.com/18020785/236396279-bf5b497b-21db-4a61-93d9-566bd4de6006.png)

**Comment by man2018** [comment]
> 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset

远程DNS的上游DNS在我这都没有被屏蔽，应该是直连

**Comment by wtfr-dot** [comment]
> > 然后将域名加入代理列表里就能通过代理正常访问了，log里也有连接记录，所以应该是你dns解析有问题
> 
> 你是4.65-2版本吗？我的远程DNS是自建的doh（没有被屏蔽）

我是自编译的最新版，显示的是4.65-2，sina.com.hk的ip估计dns解析没有屏蔽，但tcp连接被阻止了，所以需要通过代理连接，我在另外的网络里通过v2rayN连接，发现本身是通过proxy的，但网页显示503，不能打开

**Comment by wtfr-dot** [comment]
> > 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset
> 
> 远程DNS的上游DNS在我这都没有被屏蔽，应该是直连

现在看来不是dns解析的问题，问题应该出在tcp连接上，你检查一下passwall的log，看一下tcp是通过代理还是直连，直连是没有记录的

**Comment by man2018** [comment]
> > > 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset
> > 
> > 
> > 远程DNS的上游DNS在我这都没有被屏蔽，应该是直连
> 
> 现在看来不是dns解析的问题，问题应该出在tcp连接上，你检查一下passwall的log，看一下tcp是通过代理还是直连，直连是没有记录的


2023-05-05 15:26:00: 删除相关防火墙规则完成。
2023-05-05 15:26:00: 清空并关闭相关程序和缓存完成。
2023-05-05 15:26:01: TCP节点：[reality]，监听端口：1041
2023-05-05 15:26:01: 过滤服务配置：准备接管域名解析...
2023-05-05 15:26:01:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2023-05-05 15:26:01:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2023-05-05 15:26:01:   - 以上所列以外及默认：127.0.0.1#15353
2023-05-05 15:26:01:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-05-05 15:26:01: 开始加载防火墙规则...
2023-05-05 15:26:01: 加入负载均衡的节点到ipset[vpsiplist]直连完成
2023-05-05 15:26:01: 加入所有节点到ipset[vpsiplist]直连完成
2023-05-05 15:26:01: 加载路由器自身 TCP 代理...
2023-05-05 15:26:01:   - 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/5300 端口的访问
2023-05-05 15:26:01:   - [0]，屏蔽代理UDP 端口：80,443
2023-05-05 15:26:01: 加载路由器自身 UDP 代理...
2023-05-05 15:26:01: TCP默认代理：使用TCP节点[reality] [中国列表以外](REDIRECT:1041)代理所有端口
2023-05-05 15:26:01: UDP默认代理：使用UDP节点[reality] [中国列表以外](TPROXY:1041)代理所有端口
2023-05-05 15:26:01: 防火墙规则加载完成！
2023-05-05 15:26:02: 重启 dnsmasq 服务
2023-05-05 15:26:02: 配置定时任务：自动更新规则。
2023-05-05 15:26:02: 运行完成！

大佬，你看看

**Comment by man2018** [comment]
> > > > 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset
> > > 
> > > 
> > > 远程DNS的上游DNS在我这都没有被屏蔽，应该是直连
> > 
> > 
> > 现在看来不是dns解析的问题，问题应该出在tcp连接上，你检查一下passwall的log，看一下tcp是通过代理还是直连，直连是没有记录的
> 
> 2023-05-05 15:26:00: 删除相关防火墙规则完成。 2023-05-05 15:26:00: 清空并关闭相关程序和缓存完成。 2023-05-05 15:26:01: TCP节点：[reality]，监听端口：1041 2023-05-05 15:26:01: 过滤服务配置：准备接管域名解析... 2023-05-05 15:26:01: - 域名解析：dns2tcp + 使用(TCP节点)解析域名... 2023-05-05 15:26:01: * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！ 2023-05-05 15:26:01: - 以上所列以外及默认：127.0.0.1#15353 2023-05-05 15:26:01: - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！ 2023-05-05 15:26:01: 开始加载防火墙规则... 2023-05-05 15:26:01: 加入负载均衡的节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加入所有节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加载路由器自身 TCP 代理... 2023-05-05 15:26:01: - 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/5300 端口的访问 2023-05-05 15:26:01: - [0]，屏蔽代理UDP 端口：80,443 2023-05-05 15:26:01: 加载路由器自身 UDP 代理... 2023-05-05 15:26:01: TCP默认代理：使用TCP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: UDP默认代理：使用UDP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: 防火墙规则加载完成！ 2023-05-05 15:26:02: 重启 dnsmasq 服务 2023-05-05 15:26:02: 配置定时任务：自动更新规则。 2023-05-05 15:26:02: 运行完成！
> 
> 大佬，你看看

我的远程DNS可以正确解析出来sina.com.hk的IP，可能问题就出在你说的跟这个IP的tcp连接问题吧，

**Comment by wtfr-dot** [comment]
> > > > 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset
> > > 
> > > 
> > > 远程DNS的上游DNS在我这都没有被屏蔽，应该是直连
> > 
> > 
> > 现在看来不是dns解析的问题，问题应该出在tcp连接上，你检查一下passwall的log，看一下tcp是通过代理还是直连，直连是没有记录的
> 
> 2023-05-05 15:26:00: 删除相关防火墙规则完成。 2023-05-05 15:26:00: 清空并关闭相关程序和缓存完成。 2023-05-05 15:26:01: TCP节点：[reality]，监听端口：1041 2023-05-05 15:26:01: 过滤服务配置：准备接管域名解析... 2023-05-05 15:26:01: - 域名解析：dns2tcp + 使用(TCP节点)解析域名... 2023-05-05 15:26:01: * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！ 2023-05-05 15:26:01: - 以上所列以外及默认：127.0.0.1#15353 2023-05-05 15:26:01: - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！ 2023-05-05 15:26:01: 开始加载防火墙规则... 2023-05-05 15:26:01: 加入负载均衡的节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加入所有节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加载路由器自身 TCP 代理... 2023-05-05 15:26:01: - 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/5300 端口的访问 2023-05-05 15:26:01: - [0]，屏蔽代理UDP 端口：80,443 2023-05-05 15:26:01: 加载路由器自身 UDP 代理... 2023-05-05 15:26:01: TCP默认代理：使用TCP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: UDP默认代理：使用UDP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: 防火墙规则加载完成！ 2023-05-05 15:26:02: 重启 dnsmasq 服务 2023-05-05 15:26:02: 配置定时任务：自动更新规则。 2023-05-05 15:26:02: 运行完成！
> 
> 大佬，你看看

不是这个位置，是在主页面tcp节点那里点日志

**Comment by wtfr-dot** [comment]
刚才又试了一下，结果很有趣，这个应该跟passwall没关系，跟你的国内isp和远程vps有关，通过passwall所有vps都能打开网页，但我用v2rayN试了一下另一个isp，通过同一个vps，显示503错误，换一个vps却能正常打开网页

**Comment by man2018** [comment]
> > > > > 先确定你的远程DNS上游走的是代理而不是本地？ 查看自定义的域名，解析出来的ip是否已写入blacklist的ipset
> > > > 
> > > > 
> > > > 远程DNS的上游DNS在我这都没有被屏蔽，应该是直连
> > > 
> > > 
> > > 现在看来不是dns解析的问题，问题应该出在tcp连接上，你检查一下passwall的log，看一下tcp是通过代理还是直连，直连是没有记录的
> > 
> > 
> > 2023-05-05 15:26:00: 删除相关防火墙规则完成。 2023-05-05 15:26:00: 清空并关闭相关程序和缓存完成。 2023-05-05 15:26:01: TCP节点：[reality]，监听端口：1041 2023-05-05 15:26:01: 过滤服务配置：准备接管域名解析... 2023-05-05 15:26:01: - 域名解析：dns2tcp + 使用(TCP节点)解析域名... 2023-05-05 15:26:01: * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！ 2023-05-05 15:26:01: - 以上所列以外及默认：127.0.0.1#15353 2023-05-05 15:26:01: - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！ 2023-05-05 15:26:01: 开始加载防火墙规则... 2023-05-05 15:26:01: 加入负载均衡的节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加入所有节点到ipset[vpsiplist]直连完成 2023-05-05 15:26:01: 加载路由器自身 TCP 代理... 2023-05-05 15:26:01: - 上游 DNS 服务器 192.168.2.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/5300 端口的访问 2023-05-05 15:26:01: - [0]，屏蔽代理UDP 端口：80,443 2023-05-05 15:26:01: 加载路由器自身 UDP 代理... 2023-05-05 15:26:01: TCP默认代理：使用TCP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: UDP默认代理：使用UDP节点[reality] 中国列表以外代理所有端口 2023-05-05 15:26:01: 防火墙规则加载完成！ 2023-05-05 15:26:02: 重启 dnsmasq 服务 2023-05-05 15:26:02: 配置定时任务：自动更新规则。 2023-05-05 15:26:02: 运行完成！
> > 大佬，你看看
> 
> 不是这个位置，是在主页面tcp节点那里点日志

![IMG_5380](https://user-images.githubusercontent.com/18020785/236404009-9458a473-29c7-4f71-8fe9-7ba4d2e063af.jpeg)
看着这个解析出来的IP被发到了代理节点啊

**Comment by man2018** [comment]
> 刚才又试了一下，结果很有趣，这个应该跟passwall没关系，跟你的国内isp和远程vps有关，通过passwall所有vps都能打开网页，但我用v2rayN试了一下另一个isp，通过同一个vps，显示503错误，换一个vps却能正常打开网页

不知道是不是ISP问题，我用浏览器全局代理就是正常的

**Comment by wtfr-dot** [comment]
> > 刚才又试了一下，结果很有趣，这个应该跟passwall没关系，跟你的国内isp和远程vps有关，通过passwall所有vps都能打开网页，但我用v2rayN试了一下另一个isp，通过同一个vps，显示503错误，换一个vps却能正常打开网页
> 
> 不知道是不是ISP问题，我用浏览器全局代理就是正常的

我刚才用v2rayN和小火箭都试了，在我当前的网络下，其中一个vps打不开网页，所以肯定跟isp有关，你全局能访问的话，那需要仔细检查你的设置，是否其它原因造成的，另外你打开网页提示的错误信息是什么？

**Comment by man2018** [comment]
![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png)
提示ssl失败

**Comment by wtfr-dot** [comment]
这种情况有可能是中间人攻击造成的，检查你是否dns或webrtc泄露

**Comment by man2018** [comment]
> 这种情况有可能是中间人攻击造成的，检查你是否dns或webrtc泄露

我的IP和webrtc都没有问题哈，我刚刚测试了下

**Comment by wtfr-dot** [comment]
单一vps还是多vps负载均衡还是使用的机场？

**Comment by wtfr-dot** [comment]
> ![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png) 提示ssl失败

你这个图片不是通过passwall访问的，用的小火箭？检查你的配置文件，通过passwall访问提示的错误信息是什么？

**Comment by man2018** [comment]
> 单一vps还是多vps负载均衡还是使用的机场？

单一节点，没有负载均衡，我用的是vision+reality

**Comment by man2018** [comment]
> > ![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png) 提示ssl失败
> 
> 你这个图片不是通过passwall访问的，用的小火箭？检查你的配置文件，通过passwall访问提示的错误信息是什么？

我是op里面的passwall啊

**Comment by wtfr-dot** [comment]
> > > ![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png) 提示ssl失败
> > 
> > 
> > 你这个图片不是通过passwall访问的，用的小火箭？检查你的配置文件，通过passwall访问提示的错误信息是什么？
> 
> 我是op里面的passwall啊

喔，是手机通过wifi连路由器访问的，pc连接也是一样的错误信息吗？输https://www.sina.com.hk的情况呢？是否有安全提示?至少passwall应该是没有什么问题的，因为op里装的组件不一样，无法复现你的问题

**Comment by wtfr-dot** [comment]
> > 单一vps还是多vps负载均衡还是使用的机场？
> 
> 单一节点，没有负载均衡，我用的是vision+reality

如果是reality的话建议你改用其它协议试试，现在这个协议并不稳定，还有些bug，而且设置有点考验人，因为我用cdn，无法使用reality，所以没有研究这一块，去看看那边的issue吧，比如这个https://github.com/XTLS/Xray-core/issues/2017

**Comment by wtfr-dot** [comment]
> > > > ![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png) 提示ssl失败
> > > 
> > > 
> > > 你这个图片不是通过passwall访问的，用的小火箭？检查你的配置文件，通过passwall访问提示的错误信息是什么？
> > 
> > 
> > 我是op里面的passwall啊
> 
> 喔，是手机通过wifi连路由器访问的，pc连接也是一样的错误信息吗？输[https://www.sina.com.hk的情况呢？是否有安全提示?至少passwall应该是没有什么问题的，因为op里装的组件不一样，无法复现你的问题](https://www.sina.com.hk%E7%9A%84%E6%83%85%E5%86%B5%E5%91%A2%EF%BC%9F%E6%98%AF%E5%90%A6%E6%9C%89%E5%AE%89%E5%85%A8%E6%8F%90%E7%A4%BA?%E8%87%B3%E5%B0%91passwall%E5%BA%94%E8%AF%A5%E6%98%AF%E6%B2%A1%E6%9C%89%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E5%9B%A0%E4%B8%BAop%E9%87%8C%E8%A3%85%E7%9A%84%E7%BB%84%E4%BB%B6%E4%B8%8D%E4%B8%80%E6%A0%B7%EF%BC%8C%E6%97%A0%E6%B3%95%E5%A4%8D%E7%8E%B0%E4%BD%A0%E7%9A%84%E9%97%AE%E9%A2%98)

不对呀，你手机没有wifi连接标志呀

**Comment by man2018** [comment]
> > > > > ![IMG_5379](https://user-images.githubusercontent.com/18020785/236407469-f2dc41e9-cab0-4b63-a616-5377996d865d.png) 提示ssl失败
> > > > 
> > > > 
> > > > 你这个图片不是通过passwall访问的，用的小火箭？检查你的配置文件，通过passwall访问提示的错误信息是什么？
> > > 
> > > 
> > > 我是op里面的passwall啊
> > 
> > 
> > 喔，是手机通过wifi连路由器访问的，pc连接也是一样的错误信息吗？输[https://www.sina.com.hk的情况呢？是否有安全提示?至少passwall应该是没有什么问题的，因为op里装的组件不一样，无法复现你的问题](https://www.sina.com.hk%E7%9A%84%E6%83%85%E5%86%B5%E5%91%A2%EF%BC%9F%E6%98%AF%E5%90%A6%E6%9C%89%E5%AE%89%E5%85%A8%E6%8F%90%E7%A4%BA?%E8%87%B3%E5%B0%91passwall%E5%BA%94%E8%AF%A5%E6%98%AF%E6%B2%A1%E6%9C%89%E4%BB%80%E4%B9%88%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E5%9B%A0%E4%B8%BAop%E9%87%8C%E8%A3%85%E7%9A%84%E7%BB%84%E4%BB%B6%E4%B8%8D%E4%B8%80%E6%A0%B7%EF%BC%8C%E6%97%A0%E6%B3%95%E5%A4%8D%E7%8E%B0%E4%BD%A0%E7%9A%84%E9%97%AE%E9%A2%98)
> 
> 不对呀，你手机没有wifi连接标志呀

我vpn远程回家，我在家里也是打不开

**Comment by hy817120** [comment]
FAQ
关于DNS问题：
1. 部分浏览器可能有内置的DNS，请务必关闭。如：chrome。 设置 - 安全和隐私设置 - 使用安全 DNS 关闭。
2. 有时候重启后，上不了，尤其是GFW模式。这时请先关闭所有浏览器（重要），Windows客户端请`ipconfig/flushdns`。手机端请关闭WIFI，切一下飞行模式再切回来。
3. 客户端DNS和默认网关必须指向本路由器。
4. 如果你自行配置了错误的DNS流程，后果自负！

照着FAQ就没问题. 我开始也有几个网站打不开,忙活了几天,最后到这儿来了,看到作者回复,再回去认真看看,再查自己pc网卡上的dns,
真是无语了,原来是用的以前自己设置的dns.我说为啥有几个网站打不开,原来是自己问题,
你大概也差不多也是这样,
我真是无语了,忙活了几天,原来是自己问题.真是无语

**Comment by man2018** [comment]
> FAQ 关于DNS问题：
> 
> 1. 部分浏览器可能有内置的DNS，请务必关闭。如：chrome。 设置 - 安全和隐私设置 - 使用安全 DNS 关闭。
> 2. 有时候重启后，上不了，尤其是GFW模式。这时请先关闭所有浏览器（重要），Windows客户端请`ipconfig/flushdns`。手机端请关闭WIFI，切一下飞行模式再切回来。
> 3. 客户端DNS和默认网关必须指向本路由器。
> 4. 如果你自行配置了错误的DNS流程，后果自负！
> 
> 照着FAQ就没问题. 我开始也有几个网站打不开,忙活了几天,最后到这儿来了,看到作者回复,再回去认真看看,再查自己pc网卡上的dns, 真是无语了,原来是用的以前自己设置的dns.我说为啥有几个网站打不开,原来是自己问题, 你大概也差不多也是这样, 我真是无语了,忙活了几天,原来是自己问题.真是无语

你说的这几点，我这都没有设置错误。

**Comment by hy817120** [comment]
> > FAQ 关于DNS问题：
> > 
> > 1. 部分浏览器可能有内置的DNS，请务必关闭。如：chrome。 设置 - 安全和隐私设置 - 使用安全 DNS 关闭。
> > 2. 有时候重启后，上不了，尤其是GFW模式。这时请先关闭所有浏览器（重要），Windows客户端请`ipconfig/flushdns`。手机端请关闭WIFI，切一下飞行模式再切回来。
> > 3. 客户端DNS和默认网关必须指向本路由器。
> > 4. 如果你自行配置了错误的DNS流程，后果自负！
> > 
> > 照着FAQ就没问题. 我开始也有几个网站打不开,忙活了几天,最后到这儿来了,看到作者回复,再回去认真看看,再查自己pc网卡上的dns, 真是无语了,原来是用的以前自己设置的dns.我说为啥有几个网站打不开,原来是自己问题, 你大概也差不多也是这样, 我真是无语了,忙活了几天,原来是自己问题.真是无语
> 
> 你说的这几点，我这都没有设置错误。

检测一下你设备的dns, 或者你路由器是否有装本地dns,比如adguardhome smartdns之类. 还有你是否开启了ipv6.
插件是没有问题,至少我这里没有问题,

**Comment by Rock-w** [comment]
我也遇到了相同的问题，请问解决了吗？

**Comment by aaronzgh** [comment]
有同样的问题，为啥被标记了 stale issue

**Comment by bjzhili** [comment]
我遇到的问题是，www.ipify.org这个网站，加入直连规则了，但是ip显示的还是节点ip，不是我的真实ip

**Comment by gito10** [comment]
>我遇到的问题是，www.ipify.org这个网站，加入直连规则了，但是ip显示的还是节点ip，不是我的真实ip

你加入直连的是`www.ipify.org`还是`ipify.org`？我看了下，用于IP查询的域名，IPv4 是`api.ipify.org`，IPv6 是`api6.ipify.org`，双栈是`api64.ipify.org`。

**Comment by bjzhili** [comment]
> 你加入直连是`www.ipify.org`还是`ipify.org`？我看了下，用于IP查询的域名，IPv4 是`api.ipify.org`，IPv6 是`api6.ipify.org`，双栈是`api64.ipify.org`。

感谢🙏回复，这几个网站都加入了直连列表，依然显示的是我节点的ip

**Comment by gito10** [comment]
> 这几个网站都加入了直连列表，依然显示的是我节点的ip

模式设置里，**使用 直连列表** 有没有勾选？
![IMG_20240527_092524.jpg](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/e8d6d438-db8e-487e-a53a-8dd10f0f3b8c)

**Comment by bjzhili** [comment]
> > 这几个网站都加入了直连列表，依然显示的是我节点的ip
> 
> 模式设置里，**使用 直连列表** 有没有勾选？ ![IMG_20240527_092524.jpg](https://private-user-images.githubusercontent.com/10704839/333931464-e8d6d438-db8e-487e-a53a-8dd10f0f3b8c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzM2MDksIm5iZiI6MTcxNjc3MzMwOSwicGF0aCI6Ii8xMDcwNDgzOS8zMzM5MzE0NjQtZThkNmQ0MzgtZGI4ZS00ODdlLWE1M2EtOGRkMTBmMGYzYjhjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxMjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZjNhZDIyMWQ2Nzk5MzEyZmRmMGUzMDI0OGQzNmQ3NDJlODk0MDhkZWNkZjY4ZjNhZDE0ZjFmOGVhNzEyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qnwYAjvJNDHGM991KjPtbFfDXwWbM_XTQHhB0RwWiQ)

勾选了的。

**Comment by gito10** [comment]
@bjzhili 你的问题跟这个issue 不相关，去 Discussions 开个新的 Q&A 讨论，不要继续在这里发了。
