### ISSUE TITLE
[Bug]: DNS 过滤模式  通过UDP请求dns.   ui界面dns显示未运行

### ISSUE THREAD

**Issue by mcusee** [xiaorouji/openwrt-package#2561]
### 描述您遇到的bug

DNS 过滤模式  通过UDP请求dns.   ui界面dns显示未运行  。  
                          通过tcp请求dns       正常

### 复现此Bug的步骤

显示

### 您想要实现的目的

no

### 日志信息

no

### 系统相关信息

最新版版

**Comment by handsomeji** [comment]
UDP都已经直接请求了，不需要DNS中间件，自然是不显示的
