### ISSUE TITLE
[Bug]: vless使用xtls-rprx-vision流控的问题

### ISSUE THREAD

**Issue by AlexMeiko** [xiaorouji/openwrt-package#2562]
### 描述您遇到的bug

在节点配置里如若关闭xtls则无法选择流控，如若选择流控则必须开启xtls，但最新的xtls-rprx-vision要求security必须是tls而非xtls否则会出现:
 ``` app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to use xtls-rprx-vision, vision "security" must be "tls" ```

### 复现此Bug的步骤

只能手动的去修改/etc/config/passwall
原来:
```
config nodes 'xxxx'
        option protocol 'vless'        
        option encryption 'none'       
        option remarks 'xx'                      
        option add_mode '......'           
        option tls_allowInsecure '1'              
        option tls_serverName 'xxx.xxx.xxx'
        option tls '1'        
        option is_sub '0'                                 
        option type 'Xray'   
        option tcp_guise 'none' 
        option transport 'tcp'
        option address 'xxx.xxx.xxx.xxx'
        option port '443'                    
        option uuid 'xxxxxxx'
        option xtls '1'                       
        option flow 'xtls-rprx-vision'
```
修改后:

```
config nodes 'xxxx'
        option protocol 'vless'        
        option encryption 'none'       
        option remarks 'xx'                      
        option add_mode '......'           
        option tls_allowInsecure '1'              
        option tls_serverName 'xxx.xxx.xxx'
        option tls '1'        
        option is_sub '0'                                 
        option type 'Xray'   
        option tcp_guise 'none' 
        option transport 'tcp'
        option address 'xxx.xxx.xxx.xxx'
        option port '443'                    
        option uuid 'xxxxxxx'
        option xtls '0'                       
        option flow 'xtls-rprx-vision'
```

即把相关节点配置中的
`option xtls '1'`
改为
`option xtls '0'`

才能正常使用

### 您想要实现的目的

在网页中直接配置vision流控

### 日志信息

Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/arm)
A unified platform for anti-censorship.
2023/05/11 22:10:24 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
2023/05/11 22:10:24 [Warning] infra/conf: You are using an old version of XTLS, which is deprecated now and will be removed soon. Please use flow "xtls-rprx-vision" with "tls & tlsSettings" instead.
2023/05/11 22:10:39 [Warning] [1882546844] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to use xtls-rprx-vision, vision "security" must be "tls"
2023/05/11 22:10:39 [Info] [1882546844] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe

### 系统相关信息

-

**Comment by jh0072110** [comment]
哥们你多久没更新插件了…不要问过时的问题
