### ISSUE TITLE
[Bug]: 不能解析订阅vmess协议下的域名地址.

### ISSUE THREAD

**Issue by gaomengzhou** [xiaorouji/openwrt-package#2564]
### 描述您遇到的bug

订阅的机场ip填写的是域名地址, ss的正常。vmess的就是超时.

### 复现此Bug的步骤

在ip地址那用dns域名, vmess测试超时.

### 您想要实现的目的

希望ss。vmess。 都能使用域名解析ip.

### 日志信息

节点列表点击可用性测试不产生日志.

### 系统相关信息

passWall最新版本

**Comment by sunteta** [comment]
这个已经无解了。域名根本就是玄学。。建议还是SSR+吧
