### ISSUE TITLE
[Bug]: PKG_USE_MIPS16已被openwrt主线弃用

### ISSUE THREAD

**Issue by moetayuko** [xiaorouji/openwrt-package#2575]
### 描述您遇到的bug

`PKG_USE_MIPS16:=0`需要被替换为`PKG_BUILD_FLAGS:=no-mips16`，否则会在主线编译失败。但需要一个同时兼容主线与release版本的方案

https://github.com/openwrt/openwrt/commit/5c545bdb365a78b8995ddfa441a6018f7ff3c011
https://github.com/openwrt/openwrt/commit/d440ebb2a80b8ac98d7f5d6025b7946ab824b084
https://github.com/openwrt/packages/commit/565866a47210c9711c29173052063779b6d3bcfc

### 复现此Bug的步骤

N/A

### 您想要实现的目的

使go软件包在openwrt master上编译通过

### 日志信息

N/A

### 系统相关信息

N/A

**Comment by WYC-2020** [comment]
开源就这样，明明可以搞成兼容了非要直接一刀子搞完，苦了那些适配 openwrt的
