### ISSUE TITLE
[Feature Request]: 请问如何在编译OpenWrt-master时设定防火墙工具为默认NFtables

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2576]
### 描述你想要的新功能

将防火墙工具改为默认NFtables

### 描述你想要的解决方案

我尝试修改这个文件，无效。

路径: luci-app-passwall/luasrc/model/cbi/passwall/client/other.lua

---- Use nftables
o = s:option(ListValue, "use_nft", translate("Firewall tools"))
o.default = "1"  /////////////// 尝试将这里改为1,编译完成后还是默认IPtables //////////////
if has_fw3 then
	o:value("0", "IPtables")
end
if has_fw4 then
	o:value("1", "NFtables")
end

![截图 2023-05-17 00-33-28](https://github.com/xiaorouji/openwrt-passwall/assets/3048370/7afee365-6d9d-4a72-9fe2-b3947c857d45)

**Comment by BoscoL** [comment]
OpenWrt 22.03以上版本默认就是NFtables，内置编译 PassWall 时，无需作任何修改。

**Comment by ShanStone** [comment]
默认配置在/usr/share/passwall /0_default_config
option use_nft '0'
新版初始应该会自动切换
