### ISSUE TITLE
[Bug]: `chacha20-ietf` is not a supported method

### ISSUE THREAD

**Issue by leiquan** [xiaorouji/openwrt-package#2577]
### 描述您遇到的bug

loading config "/tmp/etc/passwall/TCP_UDP_SOCKS.json", unsupported method, `chacha20-ietf` is not a supported method

### 复现此Bug的步骤

1、添加SS节点
2、启动
3、失败
4、查看节点日志（不是整体日志）
5、出现上述错误

### 您想要实现的目的

支持该method

### 日志信息

`chacha20-ietf` is not a supported method

### 系统相关信息

版本4.66-4

**Comment by ShanStone** [comment]
建议更换协议，chacha20-ietf协议已经被弃用
