### ISSUE TITLE
[Bug]: nftset typo error

### ISSUE THREAD

**Issue by ecrasy** [xiaorouji/openwrt-package#2578]
### 描述您遇到的bug

dnsmasq 日志：
dnsmasq[1]: nftset inet fw4 passwall_vpsiplist Error: No such file or directory; did you mean set ‘passwall_vpslist’ in table inet ‘fw4’?

查看代码的确出现这个typo错误：
```
$: grep -irn 'passwall_vpslist'
luci-app-passwall/root/usr/share/passwall/iptables.sh:6:   IPSET_VPSLIST="passwall_vpslist"
luci-app-passwall/root/usr/share/passwall/iptables.sh:15:   IPSET_VPSLIST6="passwall_vpslist6"
luci-app-passwall/root/usr/share/passwall/nftables.sh:6:   NFTSET_VPSLIST="passwall_vpslist"
luci-app-passwall/root/usr/share/passwall/nftables.sh:15:   NFTSET_VPSLIST6="passwall_vpslist6"
```

```
$: grep -irn 'passwall_vpsiplist'
luci-app-passwall/root/usr/share/passwall/helper_dnsmasq_add.lua:200:   set_domain_ipset(address, setflag_4 .. "passwall_vpsiplist," .. setflag_6 .. "passwall_vpsiplist6")
```

### 复现此Bug的步骤

系统日志中可见

### 您想要实现的目的

修复该日志提示的错误

### 日志信息

dnsmasq[1]: nftset inet fw4 passwall_vpsiplist Error: No such file or directory; did you mean set ‘passwall_vpslist’ in table inet ‘fw4’?

### 系统相关信息

- Passwall 版本：4.66-4

**Comment by ShanStone** [comment]
fix
