### ISSUE TITLE
[Bug]: nftset trans模块缺乏相应依赖

### ISSUE THREAD

**Issue by ecrasy** [xiaorouji/openwrt-package#2579]
### 描述您遇到的bug

Makefile中默认选中Nftables_Transparent_Proxy
并且Iptables_Transparent_Proxy处于未选中状态
使用此默认Makefile配置编译的程序会导致依赖模块缺失
具体错误可见日志中

### 复现此Bug的步骤

ssh 登录 openwrt
/etc/init.d/passwall restart
输出日志可见错误

### 您想要实现的目的

修复默认Makefile的依赖

### 日志信息
```
iptables v1.8.8 (nf_tables): unknown option "--restore-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.8 (nf_tables): unknown option "--save-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.8 (nf_tables): Couldn't load match `socket':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.8 (nf_tables): unknown option "--restore-mark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.8 (nf_tables): unknown option "--save-mark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.8 (nf_tables): Couldn't load match `socket':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.8 (nf_tables): unknown option "--tproxy-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.8 (nf_tables): unknown option "--tproxy-mark"
Try `iptables -h' or 'iptables --help' for more information.
```

### 系统相关信息

- Passwall 版本：4.66-4 

### 其他信息

手动选中Iptables_Transparent_Proxy模块之后编译程序
则此问题会自动修复
说明Iptables_Transparent_Proxy的依赖同时也是Nftables_Transparent_Proxy的依赖

**Comment by ShanStone** [comment]
你应该是编译安装了iptables-nft，它可以在使用 nftables 的情况下，提供与iptables命令相同的接口。依赖于Iptables_Transparent_Proxy模块是正常的，在设置里将防火墙工具切换至nftables即可。不建议同时编译iptables及nftables，有可能会发生冲突。

**Comment by ecrasy** [comment]
我是使用passwall的默认Makefile测试的，并未特意选中某些模块
一点愚见：
建议开发者将这两个模块透明化处理
用户并不需要知道：
1. 编译时选择了Iptables_Transparent_Proxy或者Nftables_Transparent_Proxy
2. 抑或是编译时两者都选了
用户只需要在运行已经编译好的程序前，配置相应的选项即可。

**Comment by ShanStone** [comment]
> 我是使用passwall的默认Makefile测试的，并未特意选中某些模块 一点愚见： 建议开发者将这两个模块透明化处理 用户并不需要知道：
> 
> 1. 编译时选择了Iptables_Transparent_Proxy或者Nftables_Transparent_Proxy
> 2. 抑或是编译时两者都选了
>    用户只需要在运行已经编译好的程序前，配置相应的选项即可。

默认不会编译iptables-nft。
如果没编译iptables-nft，新版会自动设置，你说的两点要求都应该都能满足。现在看起来可能还需要优化一下检测脚本。

**Comment by ecrasy** [comment]
我测试的时候
iptables-nft是被dockerd默认选了的
因此可能还不只是缺少依赖iptables-nft而已
