### ISSUE TITLE
大佬，4.66-5安装提示依赖有问题，4.66-5之前的版本还有吗

### ISSUE THREAD

**Issue by man2018** [xiaorouji/openwrt-package#2586]
### 描述您遇到的bug

大佬，4.66-5安装提示依赖有问题，4.66-5之前的版本还有吗

### 复现此Bug的步骤

大佬，4.66-5安装提示依赖有问题，4.66-5之前的版本还有吗

### 您想要实现的目的

想找下老版本

### 日志信息

就是提示依赖问题

### 系统相关信息

大佬，4.66-5安装提示依赖有问题，4.66-5之前的版本还有吗

**Comment by yclalone** [comment]
也遇到了提示依赖有问题，把之前的版本卸了，这个版本装不上

**Comment by man2018** [comment]
> 也遇到了提示依赖有问题，把之前的版本卸了，这个版本装不上

先装上老版本，然后单独升级新版本的luci

**Comment by yclalone** [comment]
老版本卸载了 没有了

**Comment by man2018** [comment]
> 老版本卸载了 没有了

https://www.youtube.com/watch?v=fCO920kfLXg 去这里下载

**Comment by yclalone** [comment]
> > 老版本卸载了 没有了
> 
> https://www.youtube.com/watch?v=fCO920kfLXg 去这里下载

这里也是指向这个大佬的github 项目

**Comment by yclalone** [comment]
我的问题解决了，4.66-5可以安装，配置第三方包安装提示依赖有问题或找不到依赖，但是把所有的下载下来上传安装可以成功
