### ISSUE TITLE
[Bug]: Low performance on Wi-Fi

### ISSUE THREAD

**Issue by Armin-kho** [xiaorouji/openwrt-package#2589]
### 描述您遇到的bug

I am currently running Passwall on my Linksys WRT1900ACS v2 router, which is using OpenWrt 22.03.2 r19803-9a599fee93 firmware. However, I have noticed that the Wi-Fi performance is poor when Passwall is running, and I am not able to achieve my full bandwidth. Interestingly, when I conduct a speed test on a LAN connection, I am able to obtain nearly the full bandwidth.

To investigate whether the Wi-Fi issue is caused by Passwall, I disabled Passwall and replicated the same configuration (vless tcp reality) on my phone. I then performed another speed test, and the results were very similar to the test conducted on the LAN connection. This suggests that Passwall is the cause of the problem.

The configurations that I have tested so far and obtained similar results with are Vless tcp tls and Vless tcp reality. It is worth mentioning that I have encountered this issue with previous versions of Passwall as well.

### 复现此Bug的步骤

To investigate the problem and compare the results, I followed these steps:

1. Added a vless tcp tls or vless tcp reality node.
2. Started Passwall on the router.
3. Conducted a speed test on both Wi-Fi and LAN connections.
4. Disabled Passwall.
5. Add the same node that you used on Passwall to your phone's xray client.
6. Conduct a speed test on your phone using the Wi-Fi connection.

### 您想要实现的目的

Achieve a similar level of Wi-Fi performance as when using a LAN connection or when Passwall is deactivated.

### 日志信息

I'm unsure if it's feasible to provide conclusive proof through logs. However, if you believe it's possible, please let me know what specific logs you require and how I can provide them to you.

### All the tests were performed using the same node and same server ### 

[The performance of Vless TCP Reality on Passwall on LAN:](https://www.speedtest.net/result/14779461065)

![Screenshot 2023-05-25 035833](https://github.com/xiaorouji/openwrt-passwall/assets/19794365/5d183444-424b-419a-b53c-d67105945362)

[The performance of Vless TCP Reality on Passwall on Wi-Fi:](https://www.speedtest.net/result/i/5620634168)

![IMG_5999](https://github.com/xiaorouji/openwrt-passwall/assets/19794365/ea927374-304b-49e8-9272-b1f2ba8ba15b)

[Vless tcp Reality performance on Wi-Fi when Passwall is disabled:](https://www.speedtest.net/result/i/5620635186)

![IMG_6001](https://github.com/xiaorouji/openwrt-passwall/assets/19794365/9b81f986-e3a3-4538-b6b9-48a2703365ae)

### 系统相关信息

Passwall Version :  4.66-5
Xray Version : 1.8.1
Firmware Version : OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-23.119.80898-65ef406
Kernel Version : 5.10.146

**Comment by handsomeji** [comment]
This has nothing to do with passwall.
