### ISSUE TITLE
[Bug]: go: unsupported GOOS/GOARCH pair linux/powerpc

### ISSUE THREAD

**Issue by mimta** [xiaorouji/openwrt-package#2594]
### 描述您遇到的bug

Hi
I am trying to compile the passwall for "apm821xx-nand" on "22.04.1-Ubuntu".
I followed https://github.com/xiaorouji/openwrt-passwall/discussions/1603 tutorial, but I get an error when it come to compile the xray-core. Can someone help me please?

### 复现此Bug的步骤

n/a

### 您想要实现的目的

compile xray-core for apm821xx-nand

### 日志信息

```
Finding targets

Building targets

go: unsupported GOOS/GOARCH pair linux/powerpc

make[2]: *** [Makefile:91: /home/mt/openwrt-sdk-22.03.5-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64/build_dir/target-powerpc_464fp_musl/Xray-core-1.8.1/.built] Error 2

make[2]: Leaving directory '/home/mt/openwrt-sdk-22.03.5-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64/feeds/passwall_packages/xray-core'

time: package/feeds/passwall_packages/xray-core/compile#0.51#0.23#0.43

    ERROR: package/feeds/passwall_packages/xray-core failed to build.

make[1]: *** [package/Makefile:116: package/feeds/passwall_packages/xray-core/compile] Error 1

make[1]: Leaving directory '/home/mt/openwrt-sdk-22.03.5-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64'

make: *** [/home/mt/openwrt-sdk-22.03.5-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64/include/toplevel.mk:223: package/xray-core/compile] Error 2
```

### 系统相关信息

- 22.04.1-Ubuntu
- openwrt-sdk-22.03.3-apm821xx-nand_gcc-11.2.0_musl.Linux-x86_64

**Comment by xcyll** [comment]
GO版本低了?切openwrt-master分支试试

**Comment by mimta** [comment]
> The GO version is low? Try cutting the openwrt-master branch

Thank you. how should I do this?

@xiaorouji , @Beginner-Go, @smallprogram , @1715173329 , @Gzxhwq can you please help me? 
thank you

**Comment by czkwg8** [comment]
it seems that go doesn't support 32bit powerpc arch
so you need to port it by yourself probably
But i would say it's about time to buy a new router
ARMv8 is the future
