### ISSUE TITLE
[Feature Request]: 更新订阅时关闭代理

### ISSUE THREAD

**Issue by wkumo** [xiaorouji/openwrt-package#2602]
### 描述你想要的新功能

我一共拥有三个机场 用来作为主备
都开启了自动更新
但是其中有一个机场一直更新失败
询问了客服后得知是屏蔽海外ip更新订阅的
哪怕将更新链接的域名放入直连列表中也没有用，无法更新。

### 描述你想要的解决方案

加入选项 可以在更新前自动关闭主功能

**Comment by jackiejtr** [comment]
看起来是imm？

**Comment by wkumo** [comment]
> 看起来是imm？

不是

**Comment by ShanStone** [comment]
1.将订阅域名添加至直连列表，点击保存并应用。
2.如果不行，请尝试 基本设置/DNS/清空IPSET后再进行订阅
3.或者单独将路由器本机 TCP 代理模式改成gfwlist模式或禁用
