### ISSUE TITLE
[Bug]: 自动更新规则定时任务经常无法重启服务

### ISSUE THREAD

**Issue by chshouyu** [xiaorouji/openwrt-package#2616]
### 描述您遇到的bug

我设置的是每天早上 7 点更新 geosite、geoip 等规则，日志发现有时候似乎只运行了一半，没有出现 “运行完成！” 的字样
网络表现为上不去外网，更严重的有时候失去了 WiFi 连接
只能重启一次路由器才可以

另外，如果手动更新规则，有时候也会出现 ”脚本已经在运行，不重复运行，退出“ 这样的提示

### 复现此Bug的步骤

n/a

### 您想要实现的目的

能够正常执行定时任务

### 日志信息

n/a

### 截图

<img width="788" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/1304342/fee5b2f2-ee6e-4662-9280-d2e6220882c1">

### 系统相关信息

- Passwall 版本：git-24.112.76633-8874590
- openwrt 内核版本：5.15.108

**Comment by wtfr-dot** [comment]
这个bug一直都存在，但是不是每次都会出现，我现在是每一周更新一次，减少bug出现的机率

**Comment by chshouyu** [comment]
@wtfr-dot 大概三五天出现一次，其实也不准，很随机

**Comment by ShanStone** [comment]
试一下啊最新源码看看呢，我这边没问题
