### ISSUE TITLE
[Bug]: vmess 节点添加后无法使用

### ISSUE THREAD

**Issue by leo2430** [xiaorouji/openwrt-package#2617]
### 描述您遇到的bug

passwall版本 4.66-8

导入的vmess节点无法使用，可用性验证超时。
vmess配置在客户端v2rayN中测试通过。

检查配置文件，发现缺少 “额外id” 这一选项，见图

### 复现此Bug的步骤

通过链接添加节点
可用性测试——超时
设置为主节点，无法访问站点

### 您想要实现的目的

上网

### 日志信息

无

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/57786544/56c7eb56-e774-49d7-95af-9a718dd2e222)

### 系统相关信息

passwall版本 4.66-8

openwrt使用的版本是：istoreos-21.02.3-2023060914-x86-64

### 其他信息

新建节点、导入节点、发现配置中都没有  额外id这一选项，，怀疑跟此有关

**Comment by ShanStone** [comment]
alterID？该选项值很早就被弃用了，你是不是很久没升级过luci了。
建议修改服务器配置。

**Comment by leo2430** [comment]
谢谢回复，做了一些测试，确实和alterID 无关。测试结果如下：
vmess+tcp,通过
vmess+ws,通过
vmess+ws+tls, **不通过**
vmess+ws+tls+允许不安全连接，**不通过**
vless+tcp+reality,通过

发现带了tls证书加密的服务器配置，都连接不上，非常奇怪的问题

**Comment by wggglggg** [comment]
tls现在封端口很快的， 基本今天用，明天端口就封了，tls用不了可以vps重新做下试试

**Comment by leo2430** [comment]
测试使用的节点在v2rayN，openclash 等客户端中运行良好。相信不是端口封禁的问题。目前使用了不少于5个vps节点做了这样的测试，无一例外。只要节点使用tls，openwall就无法连接，哪怕我选择允许不安全连接，跳过证书检查，它也无法连接这些节点

**Comment by leo2430** [comment]
我想可能找到了原因，节点使用的docker v2ray镜像文件版本比较低。升级了版本，，同时降低了passwall的版本，可以连接了

**Comment by wggglggg** [comment]
> 

Docker镜像？你不是直接装的物理机哦？

**Comment by xiaohei126** [comment]
@leo2430  我遇到和你同样的问题了，vmess+ws+tls无法上网，vmess+tcp才可以上网，能告知下版本，服务端的版本需要多少
