### ISSUE TITLE
[Bug]: Error on openwrt 23.05

### ISSUE THREAD

**Issue by mohamadkhalaj** [xiaorouji/openwrt-package#2619]
### 描述您遇到的bug

i've got following error while connecting to the xray config:

2023-06-13 14:07:12: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法透明代理！
2023-06-13 14:07:13: 运行完成！

i've upgraded openwrt to 23.05 and i've installed latest version of the passwall 4.66-8

### 复现此Bug的步骤

Openwrt 23.05
passwall 4.66-8
try connecting...

### 您想要实现的目的

connect without any problem

### 日志信息

2023-06-13 14:07:12: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法透明代理！
2023-06-13 14:07:13: 运行完成！

### 系统相关信息

router: mi4a gigabit
mipsel_24kc

**Comment by mohamadkhalaj** [comment]
it was working fine wih the same configurations on openwrt 22

**Comment by ShanStone** [comment]
openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support.
Dnsmasq maybe has performance issues with nftset by now.

**Comment by mohamadkhalaj** [comment]
> openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support. Dnsmasq maybe has performance issues with nftset by now.

Thanks for your help. The previous error message was fixed by replacing Nftables with iptables. However, there is now another error in the system log:

Tue Jun 13 18:10:14 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM

This error occurs when I activate the Passwall connection, causing my router to stop working and requiring it to be restarted.

**Comment by ShanStone** [comment]
> > openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support. Dnsmasq maybe has performance issues with nftset by now.
> 
> Thanks for your help. The previous error message was fixed by replacing Nftables with iptables. However, there is now another error in the system log:
> 
> Tue Jun 13 18:10:14 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
> 
> This error occurs when I activate the Passwall connection, causing my router to stop working and requiring it to be restarted.

dnsmasq on openwrt 23.05 disable ipset support by default，if you want to use iptables，you have to enable it

**Comment by mohamadkhalaj** [comment]
> > > openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support. Dnsmasq maybe has performance issues with nftset by now.
> > 
> > 
> > Thanks for your help. The previous error message was fixed by replacing Nftables with iptables. However, there is now another error in the system log:
> > Tue Jun 13 18:10:14 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
> > This error occurs when I activate the Passwall connection, causing my router to stop working and requiring it to be restarted.
> 
> dnsmasq on openwrt 23.05 disable ipset support by default，if you want to use iptables，you have to enable it

How can i enable it?

**Comment by ShanStone** [comment]
> > > > openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support. Dnsmasq maybe has performance issues with nftset by now.
> > > 
> > > 
> > > Thanks for your help. The previous error message was fixed by replacing Nftables with iptables. However, there is now another error in the system log:
> > > Tue Jun 13 18:10:14 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
> > > This error occurs when I activate the Passwall connection, causing my router to stop working and requiring it to be restarted.
> > 
> > dnsmasq on openwrt 23.05 disable ipset support by default，if you want to use iptables，you have to enable it
> 
> How can i enable it?
> 

compile dnsmasq with openwrt sdk by youself or downgraded dnsmasq。

**Comment by mohamadkhalaj** [comment]
> > > > > openwrt 23.05 use nftables instead of itptables, go to "Other Settings" and change firewall tools to "Nftables".Make sure you had installed kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full with nftset support. Dnsmasq maybe has performance issues with nftset by now.
> > > > 
> > > > 
> > > > Thanks for your help. The previous error message was fixed by replacing Nftables with iptables. However, there is now another error in the system log:
> > > > Tue Jun 13 18:10:14 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
> > > > This error occurs when I activate the Passwall connection, causing my router to stop working and requiring it to be restarted.
> > > 
> > > 
> > > dnsmasq on openwrt 23.05 disable ipset support by default，if you want to use iptables，you have to enable it
> > 
> > 
> > How can i enable it?
> 
> compile dnsmasq with openwrt sdk by youself or downgraded dnsmasq。

Thanks.
