### ISSUE TITLE
请支持Tuic V5

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#2623]
### 描述你想要的新功能

请passwall支持Tuic V5

### 描述你想要的解决方案

Tuic V5在v2rayN使用反映良好，抗封，对运营商比HY温和，请passwall支持Tuic V5

**Comment by laaArmy** [comment]
+1

**Comment by M33FT** [comment]
bump

**Comment by donxv** [comment]
目前可以直接在openwrt运行tuic-client（unknown-linux-musl），然后在passwall添加socks节点

**Comment by HSK077** [comment]
TUICV5支持+1
潛力無限

**Comment by fangkuaiwu** [comment]
TUICV5支持+1

**Comment by Wasoud** [comment]
TUICV5

**Comment by hpqqph** [comment]
Hope to join support！

**Comment by lz595875** [comment]
现在支持了吗
