### ISSUE TITLE
[Bug]: 无法订阅

### ISSUE THREAD

**Issue by haweu** [xiaorouji/openwrt-package#2624]
### 描述您遇到的bug

暂时不支持href="https类型的节点订阅，跳过此节点

### 复现此Bug的步骤

手动订阅时候出现

### 您想要实现的目的

之前可以的啊

### 日志信息

暂时不支持href="https类型的节点订阅，跳过此节点

### 系统相关信息

4.61-4

**Comment by pctoolsx** [comment]
同样的问题。Passwall和Passwall2都如此
