### ISSUE TITLE
[Bug]: WHATSAPP 一直显示连接中

### ISSUE THREAD

**Issue by YiGeRen-yl** [xiaorouji/openwrt-package#2625]
### 描述您遇到的bug

WHATSAPP 一直显示连接中

### 复现此Bug的步骤

打开passwall 无法连接whatapp

### 您想要实现的目的

打开passwall 可以连接whatapp

### 日志信息

日志看不到whatsapp

### 系统相关信息

IPHONE和WINDOWS 都不能用

**Comment by BGzEroll** [comment]
？给你算命？
