### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by milkman-wang** [xiaorouji/openwrt-package#2631]
### 描述你想要的新功能

访问控制里面能否添加一项“只允许以下主机使用代理”，因为路由器在宿舍，不想让大家都用梯子

### 描述你想要的解决方案

访问控制添加设备白名单

**Comment by greennyreborn** [comment]
默认不代理，然后再访问控制里把你自己的机器设置为代理不就行了

**Comment by milkman-wang** [comment]
有道理，我去试试在 2023年6月20日，10:55，Michael Qu ***@***.***> 写道：﻿
默认不代理，然后再访问控制里把你自己的机器设置为代理不就行了
