### ISSUE TITLE
[Bug]: 编译报错， *** [Makefile:52: chinadns-ng] Error 

### ISSUE THREAD

**Issue by 725216** [xiaorouji/openwrt-package#2632]
### 描述您遇到的bug

编译过程中报错

### 复现此Bug的步骤

换设备编译一样问题

### 您想要实现的目的

正常编译

### 日志信息

/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.06.01:chinadns-ng-2023.06.01 -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mipsel-openwrt-linux-uclibc-ld NM="mipsel-openwrt-linux-uclibc-gcc-nm" CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB="mipsel-openwrt-linux-uclibc-gcc-ranlib" STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CROSS="mipsel-openwrt-linux-uclibc-" ARCH="mipsel" ;
make[3]: Entering directory '/home/rxy/passwall/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.06.01'
mipsel-openwrt-linux-uclibc-gcc -pipe -no-pie -O3 -flto -flto-partition=none -s -o chinadns-ng main.o opt.o dns.o dnl.o net.o ipset.o nl.o
mipsel-openwrt-linux-uclibc-gcc: error: unrecognized command line option '-no-pie'
make[3]: *** [Makefile:52: chinadns-ng] Error 1
make[3]: Leaving directory '/home/rxy/passwall/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.06.01'
make[2]: *** [Makefile:39: /home/rxy/passwall/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.06.01/.built] Error 2
make[2]: Leaving directory '/home/rxy/passwall/feeds/passwall_packages/chinadns-ng'
make[1]: *** [package/Makefile:106: package/feeds/passwall_packages/chinadns-ng/compile] Error 2
make[1]: Leaving directory '/home/rxy/passwall'
make: *** [/home/rxy/passwall/include/toplevel.mk:194: package/luci-app-passwall/compile] Error 2

### 系统相关信息

最新的版本

**Comment by dfldylan** [comment]
I have the same problem
