### ISSUE TITLE
在openwrt中的passwall更换不了节点[Bug]: 

### ISSUE THREAD

**Issue by pbclaodentm** [xiaorouji/openwrt-package#2634]
### 描述您遇到的bug

最近 4.66-8发现（之前几个版本估计就有，但没发现），tcp节点选择后，当前节点状态依旧是上一个没变化，清空IPSET后再次检查就发现变成自己选择的那个节点了，也可用通过更新规则来刷新到自己选择的节点。

### 复现此Bug的步骤

主要------TCP节点------选择任意节点都可复现，当前节点一直无变化。
开关进程、重启软路由、都不能刷新到自己选择使用的节点

但清空IPSET，或者更新规则库就可以自动刷新到自己选择的节点

### 您想要实现的目的

自己能够选择节点，确定后生效

### 日志信息

应用节点后无日志

### 系统相关信息

4.66-8

**Comment by looksgood3** [comment]
同样的问题

**Comment by Sia7ash** [comment]
same issue here

**Comment by ShanStone** [comment]
是直接升级的软件包而不是重刷固件的吧。
shell下执行下面命令
rm /etc/rc.d/*zzz_passwall
/etc/init.d/passwall enable
/etc/init.d/ucitrack restart

**Comment by pbclaodentm** [comment]
> 是直接升级的软件包而不是重刷固件的吧。 shell下执行下面命令 rm /etc/rc.d/*zzz_passwall /etc/init.d/passwall enable /etc/init.d/ucitrack restart

谢谢，第三行命令执行后提示not found 什么的没成功，但前两行命令执行成功，现在已经修复了，谢谢你！！！！！

**Comment by pbclaodentm** [comment]
> 是直接升级的软件包而不是重刷固件的吧。 shell下执行下面命令 rm /etc/rc.d/*zzz_passwall /etc/init.d/passwall enable /etc/init.d/ucitrack restart

DHDAXCW's FusionWrt built on 2021.07.18
 -----------------------------------------------------
root@FusionWrt:/# rm /etc/rc.d/*zzz_passwall
root@FusionWrt:/# /etc/init.d/passwall enable
root@FusionWrt:/# /etc/init.d/ucitrack restart
/bin/ash: /etc/init.d/ucitrack: not found
以上补充运行结果，谢谢大佬，不知道原理，最后一个命令感觉无文件可执行，不过也修复了，谢谢
