### ISSUE TITLE
[Bug]: OpenWrt 23.05.0版，安装passwall无法使用透明代理

### ISSUE THREAD

**Issue by q592850** [xiaorouji/openwrt-package#2635]
### 描述您遇到的bug

订阅节点后，选择节点启动，日志提示
系统未安装 iptables 或 ipset 或 dnsmasq没有开启ipset支持，无法使用透明代理

### 复现此Bug的步骤

系统未安装 iptables 或 ipset 或 dnsmasq没有开启ipset支持，无法使用透明代理

### 您想要实现的目的

请教如何解决！

### 日志信息

系统未安装 iptables 或 ipset 或 dnsmasq没有开启ipset支持，无法使用透明代理

### 系统相关信息

OpenWrt 23.05.0

**Comment by czkwg8** [comment]
23.05应该是用的nft

**Comment by laaArmy** [comment]
我也遇到了

**Comment by ShanStone** [comment]
高级设置-防火墙工具 切换为NFtables，确保已安装kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full。
参考https://github.com/xiaorouji/openwrt-passwall/issues/2619

**Comment by laaArmy** [comment]
> 高级设置-防火墙工具 切换为NFtables，确保已安装kmod-nft-socket、kmod-nft-tproxy、kmod-nft-nat、dnsmasq-full。 参考#2619

fw4搞定了，fw3需要哪些软件包？我是ImmortalWrt，fw3的还是不行
这些所需要的软件包列表，哪里可以找到？？？？

**Comment by wp88881990** [comment]
切换为NFtables问题依旧
