### ISSUE TITLE
[Feature Request]: ss-rust ipv6

### ISSUE THREAD

**Issue by ptr7F** [xiaorouji/openwrt-package#2640]

**Comment by Y0J1G3N** [comment]
根据https://github.com/shadowsocks/shadowsocks-rust/issues/809得知，支持ipv6可以把util_shadowsocks.lua的local_tcp_redir_address和local_udp_redir_address的值改为var["-local_tcp_redir_address"] or "::"和var["-local_udp_redir_address"] or "::"。我觉得可以在node_config.lua里增加一个选项是否开启ipv6。

**Comment by Y0J1G3N** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/43652659/2b4930e4-040f-44e9-b5da-1588e54c71ba)
util_shadowsocks.lua只要增加一个判断就可以了

**Comment by Testeera** [comment]
@ShanStone 呼叫大佬

**Comment by iIl1o0O** [comment]
> @ShanStone 呼叫大佬 [shadowsocks/shadowsocks-rust#809](https://github.com/shadowsocks/shadowsocks-rust/issues/809)

我自己解决了，修改util_shadowsocks.lua，
修改：
local local_tcp_redir_address = var["-local_tcp_redir_address"] or "0.0.0.0"
local local_udp_redir_address = var["-local_udp_redir_address"] or "0.0.0.0"
改为：
local_tcp_redir_address = var["-local_tcp_redir_address"] or "::"
local_tcp_redir_address = var["-local_tcp_redir_address"] or "::"
想了个方案，就是在ss-rust节点配置里加个ipv6的开关选项。不知道这样修改的pr，接不接受。

**Comment by ShanStone** [comment]
照上面这位大佬改一下吧，节点没有配置ipv6的情况下，会导致上网有问题，因为设备会优先走ipv6，使用ss-rust时不像v2ray/xray会自动回落到ipv4

**Comment by iIl1o0O** [comment]
下面是我修改，代码不多，大佬可以参考下：
util_shadowsocks.lua:
![image](https://github.com/xiaorouji/openwrt-passwall/assets/43652659/a8a6f952-8630-465f-b025-5d6e7fb3ca96)

node_config.lua:
![image](https://github.com/xiaorouji/openwrt-passwall/assets/43652659/836a11cb-932a-4dd0-b057-367b47e088aa)
