### ISSUE TITLE
[Bug]: 安裝4.66-9后網路不通

### ISSUE THREAD

**Issue by MiKing233** [xiaorouji/openwrt-package#2653]
### 描述您遇到的bug

從4.66-8更新到4.66-9后網路隨即中斷, 檢查發現是與内網連綫不通, 設備ping内網的其他設備是通的, 但是其他設備包括路由器, 都ping不通他, 訪問互聯網沒有問題, 現在看到4.66-9這個版本已經被刪除, 出了新的4.66-10, 是否意味著4.66-9存在問題? 不過現在更新到4.66-10内網依然不通現象依舊, 卸載passwall仍然無法恢復, 能請教一下4.66-9這個版本是動了什麽防火墻設定嗎?

### 复现此Bug的步骤

安裝4.66-9即可復現

### 您想要实现的目的

-

### 日志信息

-

### 系统相关信息

-

**Comment by XXXstyle** [comment]
日志?

**Comment by ShanStone** [comment]
没有对防火墙脚本进行修改，只是加了个依赖检测，漏了个条件，会导致使用iptables时无法正常代理，其他的应该不会影响。尝试过重启路由了吗

**Comment by MiKing233** [comment]
> 日志?

因爲嘗試卸載重新安裝, 所以之前的日志沒了, 下面是4.66-10的log, 現象和4.66-9一樣
2023-07-17 22:27:57: 清空并关闭相关程序和缓存完成。
2023-07-17 22:27:57: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-07-17 22:27:57: TCP节点：[『USA-LA』BWH US Direct | XRay | Rate 1x]，监听端口：1041
2023-07-17 22:27:58:   - 域名解析 DNS Over HTTPS...
2023-07-17 22:27:58: UDP节点：[『USA-LA』BWH US Direct | XRay | Rate 1x]，监听端口：1051
2023-07-17 22:27:58: 过滤服务配置：准备接管域名解析...
2023-07-17 22:27:58:   | - (chinadns-ng) 最高支持4级域名过滤...
2023-07-17 22:27:58:   + 过滤服务：ChinaDNS-NG(:15354)：国内DNS：218.4.4.4,223.5.5.5，可信DNS：127.0.0.1#15353
2023-07-17 22:27:58:   - 以上所列以外及默认：127.0.0.1#15354
2023-07-17 22:27:58:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-07-17 22:27:58: 重启 dnsmasq 服务
2023-07-17 22:27:58: 运行完成！

看起來和之前我印象中的log相比多了iptables-mod-socket提示未安裝

**Comment by XXXstyle** [comment]
> 

"kmod-nft-socket" "kmod-nft-tproxy" "kmod-nft-nat"
手动添加这三个试试看

**Comment by MiKing233** [comment]
> 没有对防火墙脚本进行修改，只是加了个依赖检测，漏了个条件，会导致使用iptables时无法正常代理，其他的应该不会影响。尝试过重启路由了吗

嘗試過重啓設備, 從4.66-9升級到4.66-10, 卸載4.66-9再安裝4.66-10, 都不行, 這是4.66-10下的log
2023-07-17 22:27:57: 清空并关闭相关程序和缓存完成。
2023-07-17 22:27:57: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-07-17 22:27:57: TCP节点：[『USA-LA』BWH US Direct | XRay | Rate 1x]，监听端口：1041
2023-07-17 22:27:58:   - 域名解析 DNS Over HTTPS...
2023-07-17 22:27:58: UDP节点：[『USA-LA』BWH US Direct | XRay | Rate 1x]，监听端口：1051
2023-07-17 22:27:58: 过滤服务配置：准备接管域名解析...
2023-07-17 22:27:58:   | - (chinadns-ng) 最高支持4级域名过滤...
2023-07-17 22:27:58:   + 过滤服务：ChinaDNS-NG(:15354)：国内DNS：218.4.4.4,223.5.5.5，可信DNS：127.0.0.1#15353
2023-07-17 22:27:58:   - 以上所列以外及默认：127.0.0.1#15354
2023-07-17 22:27:58:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-07-17 22:27:58: 重启 dnsmasq 服务
2023-07-17 22:27:58: 运行完成！

**Comment by MiKing233** [comment]
> 

只找得到一個, 另外兩個我的源似乎沒有
![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/38aad3e5-dfdb-4b10-bdac-ea4cfe4b29c7)

**Comment by ShanStone** [comment]
iptables透明代理基础依赖 iptables-mod-socket 未安装...
缺失依赖，请在软件包内安装iptables-mod-socket

**Comment by MiKing233** [comment]
> iptables透明代理基础依赖 iptables-mod-socket 未安装... 缺失依赖，请在软件包内安装iptables-mod-socket

thanks! 安裝后網路已經恢復
![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/8b652db6-17f2-4d05-93a8-9c2df830d79c)
話説這個包我一直都是沒有安裝的, 爲什麽之前的版本都使用正常呢?

還有看zh這位所講的需要這三個kmod包, 我嘗試安裝了zhi只能裝上一個, 請問這一個包有意義嗎, 我裝上后沒有變化, 最後是安裝的iptables-mod-socket才恢復, 現在我可以通過内網IP去訪問設備了
![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/8073cc7e-8cc1-419b-87e3-917b8922d540)


![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/7fdfaf1c-1ff0-4a97-a07f-640bc53f826f)

**Comment by XXXstyle** [comment]
> > iptables透明代理基础依赖 iptables-mod-socket 未安装... 缺失依赖，请在软件包内安装iptables-mod-socket
> 
> thanks! 安裝后網路已經恢復 ![image](https://user-images.githubusercontent.com/26044744/253976088-8b652db6-17f2-4d05-93a8-9c2df830d79c.png) 話説這個包我一直都是沒有安裝的, 爲什麽之前的版本都使用正常呢?
> 
> 還有看zh這位所講的需要這三個kmod包, 我嘗試安裝了zhi只能裝上一個, 請問這一個包有意義嗎, 我裝上后沒有變化, 最後是安裝的iptables-mod-socket才恢復, 現在我可以通過内網IP去訪問設備了 ![image](https://user-images.githubusercontent.com/26044744/253976445-a9ce40dd-82c5-41ef-807c-ab1ecf2eb08e.png)
> 
> ![image](https://user-images.githubusercontent.com/26044744/253976323-7fdfaf1c-1ff0-4a97-a07f-640bc53f826f.png)

我的linux6.1需要的是这三个，复制的时候顺手复制错了。。这一版更新应该是漏掉了所需依赖添加，需要手动添加依赖

**Comment by ShanStone** [comment]
> > iptables透明代理基础依赖 iptables-mod-socket 未安装... 缺失依赖，请在软件包内安装iptables-mod-socket
> 
> thanks! 安裝后網路已經恢復
> ![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/8b652db6-17f2-4d05-93a8-9c2df830d79c)
> 話説這個包我一直都是沒有安裝的, 爲什麽之前的版本都使用正常呢?
> 
> 還有看zh這位所講的需要這三個kmod包, 我嘗試安裝了zhi只能裝上一個, 請問這一個包有意義嗎, 我裝上后沒有變化, 最後是安裝的iptables-mod-socket才恢復, 現在我可以通過内網IP去訪問設備了
> ![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/8073cc7e-8cc1-419b-87e3-917b8922d540)
> 
> 
> ![image](https://github.com/xiaorouji/openwrt-passwall/assets/26044744/7fdfaf1c-1ff0-4a97-a07f-640bc53f826f)
> 

这个依赖脚本引用的不多，但也会导致一些防火墙规则失效，这次把基础的透明代理依赖检测全加上了
上面提到的kmod-nft-tproxy等依赖是使用nftables（fw4）时用到的，你系统用的iptables（fw3），装了这三个也没用，不建议混用，可能会导致冲突

**Comment by MiKing233** [comment]
> > > iptables透明代理基础依赖 iptables-mod-socket 未安装... 缺失依赖，请在软件包内安装iptables-mod-socket
> > 
> > 
> > thanks! 安裝后網路已經恢復
> > ![image](https://user-images.githubusercontent.com/26044744/253976088-8b652db6-17f2-4d05-93a8-9c2df830d79c.png)
> > 話説這個包我一直都是沒有安裝的, 爲什麽之前的版本都使用正常呢?
> > 還有看zh這位所講的需要這三個kmod包, 我嘗試安裝了zhi只能裝上一個, 請問這一個包有意義嗎, 我裝上后沒有變化, 最後是安裝的iptables-mod-socket才恢復, 現在我可以通過内網IP去訪問設備了
> > ![image](https://user-images.githubusercontent.com/26044744/253976928-8073cc7e-8cc1-419b-87e3-917b8922d540.png)
> > ![image](https://user-images.githubusercontent.com/26044744/253976323-7fdfaf1c-1ff0-4a97-a07f-640bc53f826f.png)
> 
> 这个依赖脚本引用的不多，但也会导致一些防火墙规则失效，这次把基础的透明代理依赖检测全加上了 上面提到的kmod-nft-tproxy等依赖是使用nftables（fw4）时用到的，你系统用的iptables（fw3），装了这三个也没用，不建议混用，可能会导致冲突

非常感謝 @ShanStone 和 @XXXstyle 兩位提供Support ,不是兩位及時回復我都准備重裝了, 真的非常感謝!

**Comment by redfrog999** [comment]
对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？

**Comment by MiKing233** [comment]
> 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？

我還是18.06, 你使用的opkg源是哪些呢?

**Comment by XXXstyle** [comment]
> 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？

重新编译的时候手动加上吧，menuconfig里面搜索一下可以找到路径

**Comment by RavenCage** [comment]
> > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> 
> 我還是18.06, 你使用的opkg源是哪些呢?

src/gz immortalwrt_core https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/targets/ramips/mt7621/packages
src/gz immortalwrt_base https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/base
src/gz immortalwrt_helloworld https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/helloworld
src/gz immortalwrt_kenzo https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/kenzo
src/gz immortalwrt_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/luci
src/gz immortalwrt_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/packages
src/gz immortalwrt_passwall_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_luci
src/gz immortalwrt_passwall_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_packages
src/gz immortalwrt_routing https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/routing
src/gz immortalwrt_telephony https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/telephony

这些是我编译时用的源，好像都没有这些依赖包呢。能否分享下能提供这些依赖包的源？非常感谢。

**Comment by RavenCage** [comment]
> > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> 
> 重新编译的时候手动加上吧，menuconfig里面搜索一下可以找到路径

我找了下menuconfig里的kmod相关条目，没有这些依赖包，请问这个怎么解决呢？

**Comment by MiKing233** [comment]
> > > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> > 
> > 
> > 我還是18.06, 你使用的opkg源是哪些呢?
> 
> src/gz immortalwrt_core https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/targets/ramips/mt7621/packages src/gz immortalwrt_base https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/base src/gz immortalwrt_helloworld https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/helloworld src/gz immortalwrt_kenzo https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/kenzo src/gz immortalwrt_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/luci src/gz immortalwrt_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/packages src/gz immortalwrt_passwall_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_luci src/gz immortalwrt_passwall_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_packages src/gz immortalwrt_routing https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/routing src/gz immortalwrt_telephony https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/telephony
> 
> 这些是我编译时用的源，好像都没有这些依赖包呢。能否分享下能提供这些依赖包的源？非常感谢。

以下是我使用的源, 我的是arm_AArch64, Linux5.4.203, 看樣子你的設備架構為mips, 我看了下我使用的源似乎沒有提供對mips的支援, 你可能得去找別的源才行

src/gz openwrt_core file:///www/snapshots/targets/rockchip/armv8/packages
src/gz openwrt_base https://openwrt.cc/snapshots/packages/aarch64_generic/base
src/gz openwrt_luci https://openwrt.cc/snapshots/packages/aarch64_generic/luci
src/gz openwrt_packages https://openwrt.cc/snapshots/packages/aarch64_generic/packages
src/gz openwrt_routing https://openwrt.cc/snapshots/packages/aarch64_generic/routing
src/gz openwrt_telephony https://openwrt.cc/snapshots/packages/aarch64_generic/telephony

**Comment by RavenCage** [comment]
> 

非常感谢，那我就暂时停留在4.66-8好了，也能满足使用需求了。

**Comment by RavenCage** [comment]
> > > > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> > > 
> > > 
> > > 我還是18.06, 你使用的opkg源是哪些呢?
> > 
> > 
> > src/gz immortalwrt_core https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/targets/ramips/mt7621/packages src/gz immortalwrt_base https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/base src/gz immortalwrt_helloworld https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/helloworld src/gz immortalwrt_kenzo https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/kenzo src/gz immortalwrt_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/luci src/gz immortalwrt_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/packages src/gz immortalwrt_passwall_luci https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_luci src/gz immortalwrt_passwall_packages https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/passwall_packages src/gz immortalwrt_routing https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/routing src/gz immortalwrt_telephony https://mirrors.vsean.net/openwrt/releases/18.06-k5.4-SNAPSHOT/packages/mipsel_24kc/telephony
> > 这些是我编译时用的源，好像都没有这些依赖包呢。能否分享下能提供这些依赖包的源？非常感谢。
> 
> 以下是我使用的源, 我的是arm_AArch64, Linux5.4.203, 看樣子你的設備架構為mips, 我看了下我使用的源似乎沒有提供對mips的支援, 你可能得去找別的源才行
> 
> src/gz openwrt_core file:///www/snapshots/targets/rockchip/armv8/packages src/gz openwrt_base https://openwrt.cc/snapshots/packages/aarch64_generic/base src/gz openwrt_luci https://openwrt.cc/snapshots/packages/aarch64_generic/luci src/gz openwrt_packages https://openwrt.cc/snapshots/packages/aarch64_generic/packages src/gz openwrt_routing https://openwrt.cc/snapshots/packages/aarch64_generic/routing src/gz openwrt_telephony https://openwrt.cc/snapshots/packages/aarch64_generic/telephony

非常感谢，那我就暂时停留在4.66-8好了，也能满足使用需求了。

**Comment by XXXstyle** [comment]
> > > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> > 
> > 
> > 重新编译的时候手动加上吧，menuconfig里面搜索一下可以找到路径
> 
> 我找了下menuconfig里的kmod相关条目，没有这些依赖包，请问这个怎么解决呢？
搜索你需要的，如果实在没有你可以去下面的库里看看
https://github.com/kenzok8/small

**Comment by RavenCage** [comment]
> > > > 对于还在使用18.06和21.02的Openwrt用户咋弄呢？我的源里根本找不到这些依赖包，下载的ipk也没法安装，是否意味着不能升级到新版了呢？
> > > 
> > > 
> > > 重新编译的时候手动加上吧，menuconfig里面搜索一下可以找到路径
> > 
> > 
> > 我找了下menuconfig里的kmod相关条目，没有这些依赖包，请问这个怎么解决呢？
> > 搜索你需要的，如果实在没有你可以去下面的库里看看
> > https://github.com/kenzok8/small

好的，非常感谢。

**Comment by BGzEroll** [comment]
> > > iptables透明代理基础依赖 iptables-mod-socket 未安装... 缺失依赖，请在软件包内安装iptables-mod-socket
> > 
> > 
> > thanks! 安裝后網路已經恢復
> > ![image](https://user-images.githubusercontent.com/26044744/253976088-8b652db6-17f2-4d05-93a8-9c2df830d79c.png)
> > 話説這個包我一直都是沒有安裝的, 爲什麽之前的版本都使用正常呢?
> > 還有看zh這位所講的需要這三個kmod包, 我嘗試安裝了zhi只能裝上一個, 請問這一個包有意義嗎, 我裝上后沒有變化, 最後是安裝的iptables-mod-socket才恢復, 現在我可以通過内網IP去訪問設備了
> > ![image](https://user-images.githubusercontent.com/26044744/253976928-8073cc7e-8cc1-419b-87e3-917b8922d540.png)
> > ![image](https://user-images.githubusercontent.com/26044744/253976323-7fdfaf1c-1ff0-4a97-a07f-640bc53f826f.png)
> 
> 这个依赖脚本引用的不多，但也会导致一些防火墙规则失效，这次把基础的透明代理依赖检测全加上了 上面提到的kmod-nft-tproxy等依赖是使用nftables（fw4）时用到的，你系统用的iptables（fw3），装了这三个也没用，不建议混用，可能会导致冲突

能请问下大概什么情况下会引用iptables-mod-socket吗，还是有点担心会漏规则
