### ISSUE TITLE
从4.66-8更新到4.66-11 后无法使用

### ISSUE THREAD

**Issue by pbclaodentm** [xiaorouji/openwrt-package#2659]
### 描述您遇到的bug

软路由固件版本如下，一直都是下载ipk文件更新的，都没啥大问题，能够科学上网，此次更新后出现无法使用的问题。
我的固件版本内核版本
固件版本 | OpenWrt R21.3.27 GDQ v4.1[2021] Compiled by eSir / LuCI Master (git-21.088.17646-3fe6408)
内核版本 | 5.4.106

### 复现此Bug的步骤

任何节点都无法科学出去。看到运行状态中dns一会儿运行中，过一会儿未运行，节点能够自动切换，但切换了所有的备用节点都无法上网，应该和协议无关。

### 您想要实现的目的

目前已经退回4.66-8，已经正常使用，如果新版本有更好的体验，也会继续升级，但目前新版本出现这个问题后，我犹豫了，不敢跟进了。

### 日志信息

没啥有用的日志，我看了passwall的日志，跟之前一样

### 系统相关信息

passwall版本  4.66-11
固件版本 | OpenWrt R21.3.27 GDQ v4.1[2021] Compiled by eSir / LuCI Master (git-21.088.17646-3fe6408)
内核版本 | 5.4.106

**Comment by iamyangyiok** [comment]
同样的问题，4.66-8 升级10-11 都无法使用。重装4.66-8就正常，无以下提示。
PW日志中有提示：
2023-07-19 17:22:29: iptables透明代理基础依赖 iptables-mod-tproxy 未安装...
2023-07-19 17:22:29: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-07-19 17:22:29: iptables透明代理基础依赖 iptables-mod-iprange 未安装...
2023-07-19 17:22:29: iptables透明代理基础依赖 iptables-mod-conntrack-extra 未安装...
2023-07-19 17:22:29: iptables透明代理基础依赖 kmod-ipt-nat 未安装...

固件版本 | ImmortalWrt 18.06-5.4-SNAPSHOT r11928-ae6ff3410 / LuCI openwrt-18.06-k5.4 branch (git-23.178.42687-494cc11)
内核版本 | 5.4.224

**Comment by ShanStone** [comment]
升级4.66-12，现在只会提示依赖问题。
旧版本的话确实是没有这些依赖的，没有就不用管了

**Comment by iamyangyiok** [comment]
> 升级4.66-12，现在只会提示依赖问题。 旧版本的话确实是没有这些依赖的，没有就不用管了

那12能用了 还是依然要装那几个依赖

**Comment by ShanStone** [comment]
> > 升级4.66-12，现在只会提示依赖问题。 旧版本的话确实是没有这些依赖的，没有就不用管了
> 
> 那12能用了 还是依然要装那几个依赖

有些旧没有这些依赖，确认自己依赖装全的话就不用管这些提示了

**Comment by chika0801** [comment]
https://github.com/hanwckf/immortalwrt-mt798x/issues/97

感谢解答 @ShanStone
