### ISSUE TITLE
[Bug]: 12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### ISSUE THREAD

**Issue by ho1003** [xiaorouji/openwrt-package#2661]
### 描述您遇到的bug

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 复现此Bug的步骤

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 您想要实现的目的

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 日志信息

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 截图

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 系统相关信息

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

### 其他信息

12版本无法自动切换节点并且手动切换也变不了别的，始终为第一个节点使用。

**Comment by Nicepaul** [comment]
确实切换不了，希望大神修复

**Comment by pbclaodentm** [comment]
4.66-8我就遇到过了，大佬让运行如下代码
shell下执行下面命令
rm /etc/rc.d/*zzz_passwall
/etc/init.d/passwall enable
/etc/init.d/ucitrack restart

你试试呢，我现在不敢升级8以上的了，问题有点多，我现在用的还是466-8

**Comment by iamyangyiok** [comment]
> 4.66-8我就遇到过了，大佬让运行如下代码 shell下执行下面命令 rm /etc/rc.d/*zzz_passwall /etc/init.d/passwall enable /etc/init.d/ucitrack restart
> 
> 你试试呢，我现在不敢升级8以上的了，问题有点多，我现在用的还是466-8

我也是现在不敢升级12，观望吧 也在还原8了

**Comment by swxk521** [comment]
我这没问题，可以自动切换。

**Comment by redfrog999** [comment]
我这里手动和自动切换都是很正常，通过系统日志和软件日志排查看看。
