### ISSUE TITLE
[Bug]: 新版本节点配置中无XTLS选项，flow中无xtls-rprx-direct选项

### ISSUE THREAD

**Issue by Beurling** [xiaorouji/openwrt-package#2663]
## 老版本（4.55-1）节点配置选项截图
**其中有XTLS、flow中有xtls-rprx-direct选项**

![老版本](https://github.com/xiaorouji/openwrt-passwall/assets/48503044/34d09e86-2397-42e9-811e-d6a9596a3472)

## 新版本（4.66-12）截图
**无XTLS，flow中只有xtls-rprx-vision选项**
![屏幕截图 2023-07-22 170248](https://github.com/xiaorouji/openwrt-passwall/assets/48503044/3c46d6f3-c92a-4daa-8f2d-5c6726092d4e)

### 复现此Bug的步骤

1. 点击节点列表
2. 点击添加
3. 类型选择Xray
4. 协议选择VLESS
5. 勾选TLS

### 您想要实现的目的

XTLS和flow的选择是否会影响节点的使用安全性和速度？
如果是功能更新故意去掉了就没关系，还是说是一个漏掉的bug？
不是很清楚，所以求助一下。

### 日志信息

无相关

### 系统相关信息

4.55-1 与 4.66-12

**Comment by swxk521** [comment]
应该是去掉了

**Comment by Gzxhwq** [comment]
xtls-rprx-direct已经被xray官方抛弃，请改用vision流控，或停留在旧版使用

**Comment by JerryQSJ** [comment]
> xtls-rprx-direct已经被xray官方抛弃，请改用vision流控，或停留在旧版使用

旧版本在哪里可以下载到？谢谢
