### ISSUE TITLE
[Bug]: passwall无法检测异常后重启自己，MOSDNS更新了GeoIP/GeoSite 规则，passwall就趴窝了。

### ISSUE THREAD

**Issue by love768952693** [xiaorouji/openwrt-package#2664]
### 描述您遇到的bug

逻辑上是因为MOSDNS重写了规则，导致passwall得重载才能恢复，但是passwall又没有重载。

只要MOSDNS 修改了配置，或者是更新了GeoIP/GeoSite 规则，passwall就不能使用。

哪怕passwall改用第三方的DNS也一样，因为passwall是依赖openwrt的DNS，而DNS又被mosdns劫持。

### 复现此Bug的步骤

/

### 您想要实现的目的

passwall目前的节点异常切换没有用，在MOSDNS更新规则后，会出现passwall一直无法连接。

提供如下解决方案：
**5毛钱版解决方案**
通过passwall的定时更新规则触发重启，允许用户定时修改为:分与秒，这样MOSDNS5点更新，那么passwall只要过几分钟就好了。

**100元解决方案**
添加个passwall监控openwrt DNS中列表规则的进程，发现自己DNS无法解析后，重启自己。

**知男而上解决方法**
和mosdns开发者协商，双方给通知事件，互相回调对方，来满足无缝启动与切换。

### 日志信息

/

### 截图

/

### 系统相关信息

/

**Comment by BitbeyHub** [comment]
跟我一样一样的👉MosDNS一有什么动作Passwall留学的DNS解析就挂……
1. 你要不要试试 在"/usr/share/mosdns/mosdns.sh"的<"geodata")>下面一行（我是152行）追加一行“sh /usr/share/passwall/iptables.sh flush_ipset &”，以使得局部代码块变成👇
```
    "geodata")
        geodat_update && adlist_update && restart_service && sleep 3s
        sh /usr/share/passwall/iptables.sh flush_ipset &
    ;;
```
这样MosDNS每次自己更新数据库，都能自动连带刷新Passwall的IPSET呢？

---
2. 实在不行再发狠在计划任务里添加一行
```
*/3 * * * * dnsd=`dig -4 +short +retry=0 your.test.domain`; if echo $dnsd | grep -q "timed out"; then sh /usr/share/passwall/iptables.sh flush_ipset; fi
```
搞个3分钟一检测吧，又不会很影响性能……
