### ISSUE TITLE
[Bug]: 过滤代理域名IPv6经常失效

### ISSUE THREAD

**Issue by lwb1978** [xiaorouji/openwrt-package#2671]
### 描述您遇到的bug

由于本人机场不支持ipv6，在电视观看SmartTube时，如果不过滤掉代理域名的ipv6会由于解析到油管的ipv6地址而又连接不到墙外的ipv6地址，导致SmartTube很长时间都无法加载页面信息。但目前PW的“过滤代理域名ipv6”功能不稳定，大概1天左右就失效了，必须点击一次“清空 IPSET”后才能重新生效。

### 复现此Bug的步骤

开启“过滤代理域名ipv6”

### 您想要实现的目的

修复该bug或者是能设置定时清空IPSET。

### 日志信息

/

### 系统相关信息

/

**Comment by cyclc77** [comment]
同样的问题，蹲一下

**Comment by handsomeji** [comment]
DNS过滤模式用的是什么？

**Comment by lwb1978** [comment]
> DNS过滤模式用的是什么？

之前用dnsmasq，不到两天就出问题，后来改用SmartDNS分支luci配合SmartDNS使用，一个多星期了没出过问题。
