### ISSUE TITLE
[Bug]: 从4.66-10开始更新组件负载均衡菜单消失

### ISSUE THREAD

**Issue by Paullaw102** [xiaorouji/openwrt-package#2672]
### 描述您遇到的bug

每次想从4.66-8更新Passwall都会发生负载均衡菜单消失

### 复现此Bug的步骤

按照ssh登录执行 opkg install *.ipk

### 您想要实现的目的

希望尽快解决这个问题

### 日志信息

好似提升组件缺失文件

### 截图

![WX20230726-090304](https://github.com/xiaorouji/openwrt-passwall/assets/37990813/d806023b-a2f1-4ddb-89eb-1e495caef78c)

### 系统相关信息

4.

**Comment by showme2005** [comment]
自己在软件包里找haproxy安装 一下就有了

**Comment by Paullaw102** [comment]
谢谢啦，我试试看

showme2005 ***@***.***> 于2023年7月28日周五 11:23写道：

**Comment by Paullaw102** [comment]
ok,thx

paul luo ***@***.***> 于2023年7月30日周日 15:36写道：

**Comment by pbclaodentm** [comment]
确切的说，安了haproxy也会没有，真正的原因是，得用浏览器恢复隐藏菜单
http://192.168.31.251/cgi-bin/luci/admin/services/passwall/show    地址换成你自己的就行了，进去就有了
