### ISSUE TITLE
如果我想去掉 dnsmasq 依赖，请问该怎么做？

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2674]
只想使用 adguard home 作为本地dns服务器，并且。 

openwrt 自带了 dhcp 服务器，这样就显得 dnsmasq 的功能有点多余了。 

并且 dnsmasq 没有 adguard home 那么强大的dns功能。

如果我去掉 dnsmasq 那么还想正常使用 passwall 我需要安装哪些依赖呢？

**Comment by MiKing233** [comment]
passwall似乎是依賴Dnsmasq的, DNS必須過一次Dnsmasq才行, 應該去不掉

**Comment by ghost** [comment]
> passwall似乎是依賴Dnsmasq的, DNS必須過一次Dnsmasq才行, 應該去不掉

并不是一定依赖 dnsmasq 因为，我使用 adguard 监听默认53端口的效率要比 dnsmasq 高很多。

目前的情况就是把 dnsmasq 端口改成了 5353 转发到的 127.0.0.1 的 adguard 上面。

具体依赖dnsmasq 什么东西不是很清楚，作者也应该回答一下，。

**Comment by iamyangyiok** [comment]
我DHCP都交给ADG了
