### ISSUE TITLE
[Bug]: naiveproxy无法下载

### ISSUE THREAD

**Issue by sjkhsl** [xiaorouji/openwrt-package#2685]
### 描述您遇到的bug

https://github.com/klzgrad/naiveproxy/releases/tag/v113.0.5672.62-1 v113.0.5672.62-1版本已删除

### 复现此Bug的步骤

make download -j8

### 您想要实现的目的

更新naiveproxy版本

### 日志信息

ERROR: package/chajianbao/openwrt-passwall/naiveproxy failed to build.

### 系统相关信息

4.67-1

**Comment by sjkhsl** [comment]
clang-llvmorg-17-init-4759-g547e3456-1也无法下载

**Comment by wazzx** [comment]
希望更新一下到最新版

**Comment by sjkhsl** [comment]
大佬们更新一下呗

**Comment by sjkhsl** [comment]
这问题都没人管吗？

**Comment by wazzx** [comment]
我知道为什么大佬不更新了！其实naiveproxy开发者已经做好了对应构架的软件了！直接下载好拖到/usr/bin目录下权限755重新启动就可以了！

**Comment by sjkhsl** [comment]
> 我知道为什么大佬不更新了！其实naiveproxy开发者已经做好了对应构架的软件了！直接下载好拖到/usr/bin目录下权限755重新启动就可以了！

问题在于新环境编译时，无法下载依赖，没办法编译啊！

**Comment by pangfeng161** [comment]
> 我知道为什么大佬不更新了！其实naiveproxy开发者已经做好了对应构架的软件了！直接下

> 我知道为什么大佬不更新了！其实naiveproxy开发者已经做好了对应构架的软件了！直接下载好拖到/usr/bin目录下权限755重新启动就可以了！

具体怎么操作,小白不懂
