### ISSUE TITLE
[TAB PANNEL MISSING]: 

### ISSUE THREAD

**Issue by maheruf** [xiaorouji/openwrt-package#2686]
### 描述你想要的新功能

Hi guys i have install passwall successfully in my tplink archer c6.  But after install i cant find loadballancing tab in top pannel. How to fix it. 
![d67b2cd94c11f48f8c95d510e3336631 0](https://github.com/xiaorouji/openwrt-passwall/assets/98561002/0930555f-e632-4a7e-b161-0ebebe38e33a)

### 描述你想要的解决方案

.

### 描述你考虑过的替代方案

.

### 其他信息

.

**Comment by handsomeji** [comment]
You need install haproxy.
