### ISSUE TITLE
[Bug]: bing加入代理列表无效

### ISSUE THREAD

**Issue by kay-zhu** [xiaorouji/openwrt-package#2688]
### 描述您遇到的bug

bing.com加入代理列表后无效，还是走的cn.bing.com（必应中国），PassWall2加入后是有效的。

### 复现此Bug的步骤

1.规则列表
2.选“代理列表”
3.添加“bing.com”

### 您想要实现的目的

希望规则设置有效

### 日志信息

2023-08-04 13:36:31: 删除相关防火墙规则完成。
2023-08-04 13:36:32: 清空并关闭相关程序和缓存完成。
2023-08-04 13:36:32: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-08-04 13:36:32: TCP节点：[分流总节点]，监听端口：1041
2023-08-04 13:36:32: 过滤服务配置：准备接管域名解析...
2023-08-04 13:36:32:   - 域名解析：dns2tcp + 使用(TCP节点)解析域名...
2023-08-04 13:36:32:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2023-08-04 13:36:32:   | - (chinadns-ng) 最高支持4级域名过滤...
2023-08-04 13:36:32:   + 过滤服务：ChinaDNS-NG(:15354)：国内DNS：119.29.29.29,8.8.8.8，可信DNS：127.0.0.1#15353
2023-08-04 13:36:32:   - 节点列表中的域名(vpslist)：119.29.29.29,8.8.8.8
2023-08-04 13:36:32:   - 域名白名单(whitelist)：119.29.29.29,8.8.8.8
2023-08-04 13:36:32:   - 代理域名表(blacklist)：127.0.0.1#15353
2023-08-04 13:36:32:   - 防火墙域名表(gfwlist)：默认
2023-08-04 13:36:32:   - 中国域名表(chnroute)：默认
2023-08-04 13:36:32:   - 以上所列以外及默认：127.0.0.1#15354
2023-08-04 13:36:32:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2023-08-04 13:36:32: 开始加载防火墙规则...
2023-08-04 13:36:33: 加入负载均衡的节点到ipset[passwall_vpslist]直连完成
2023-08-04 13:36:33: 加入所有节点到ipset[passwall_vpslist]直连完成
2023-08-04 13:36:33: 加载路由器自身 TCP 代理...
2023-08-04 13:36:33:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2023-08-04 13:36:34:   - [0]，屏蔽代理UDP 端口：80,443
2023-08-04 13:36:34: 加载路由器自身 UDP 代理...
2023-08-04 13:36:34: TCP默认代理：使用TCP节点[分流总节点] [中国列表以外](REDIRECT:1041)代理所有端口
2023-08-04 13:36:34: UDP默认代理：使用UDP节点[分流总节点] [中国列表以外](TPROXY:1041)代理所有端口
2023-08-04 13:36:34: 防火墙规则加载完成！
2023-08-04 13:36:34: 重启 dnsmasq 服务
2023-08-04 13:36:34: 配置定时任务：自动更新规则。
2023-08-04 13:36:34: 运行完成！

### 系统相关信息

-4.67-1
-Microsoft Edge 版本 115.0.1901.188 (正式版本) (64 位)

**Comment by zhaozhao777** [comment]
我一般不配置代理bing，但他很奇怪，F12打开后发现他一直在请求一大堆乱七八糟的东西，导致页面打开很慢。而且有时候会突然自己代理上，反而全局代理的时候，稳定的很，应该是bing自己请求的问题。

**Comment by kay-zhu** [comment]
还是没解决

**Comment by handsomeji** [comment]
测试没有问题。
但我发现你国内DNS也使用了8.8.8.8，请去掉后重启passwall再试试

**Comment by dustingholfman** [comment]
> 测试没有问题。 但我发现你国内DNS也使用了8.8.8.8，请去掉后重启passwall再试试

请问怎么去掉国内dns中的8.8.8.8

**Comment by zhaozhao777** [comment]
> > 测试没有问题。 但我发现你国内DNS也使用了8.8.8.8，请去掉后重启passwall再试试
> 
> 请问怎么去掉国内dns中的8.8.8.8

这个是不在passwall，在openwrt里设置，网络》接口》编辑，  里边有个dns的配置，或者如果你是旁路网关的openwrt，也可以在上级路由上设置。

**Comment by colalan** [comment]
有效的解决办法是在usr/share/passwall/rules/gfwlist中加入bing.com

**Comment by colalan** [comment]
改下usr\share\passwall\rule_update.lua：

27行：

local excluded_domain = {"apple.com","sina.cn","sina.com.cn","baidu.com","byr.cn","jlike.com","weibo.com","zhongsou.com","youdao.com","sogou.com","so.com","soso.com","aliyun.com","taobao.com","jd.com","qq.com","bing.com"}

删除bing.com改为：
local excluded_domain = {"apple.com","sina.cn","sina.com.cn","baidu.com","byr.cn","jlike.com","weibo.com","zhongsou.com","youdao.com","sogou.com","so.com","soso.com","aliyun.com","taobao.com","jd.com","qq.com"}

154行左右以下：

                        if rule_name == "gfwlist" then
                                local domains = {"bing.com"}
                                local gfwlist = io.open(download_file_tmp..k, "r")
                                local decode = api.base64Decode(gfwlist:read("*all"))
                                gfwlist:close()

                                gfwlist = io.open(download_file_tmp..k, "w")
                                gfwlist:write(decode)
                                for i = 1, #domains do
                                        gfwlist:write('\n', domains)
                                end
                                gfwlist:close()
                        end



215行左右以下：

                if rule_type == "domain" then
                        local out = io.open(unsort_file_tmp, "w")
                        for k,v in pairs(domains) do
                                if k ~= "www.bing.com" then
                                        out:write(string.format("%s\n", k))
                                end
                        end
                        out:close()
                end

**Comment by dustingholfman** [comment]
谢谢！

colalan ***@***.***> 于2023年11月1日周三 22:10写道：

**Comment by maike2019** [comment]
是的，我也遇到同样的问题，【 4.76-1 】 。在规则列表--代理列表--添加 bing.com 。
在规则管理 --Sing-Box/Xray 分流规则中 添加Bing规则， 内容填写 
domain:bing.com
here.com
here.net
heremaps.cn
ovi.com.cn
azure
azure-apim.net
azure-dns.com
azure-dns.info
azure-dns.net
azure-dns.org
azure-mobile.net
azure-sphere.com
azure-test.net
azure.cn
azure.com
azure.net
azurecomcdn.net
azurecontainer.io
azurecosmos.net
azurecosmosdb.com
azurecosmosdb.info
azurecosmosdb.net
azuredatabricks.net
azuredevopslaunch.com
azuredigitaltwin.com
azuredigitaltwins.com
azuredigitaltwins.net
azuredns-prd.info
azuredns-prd.org
azureedge-test.net
azureedge.net
azurefd.net
azurefd.us
azureiotcentral.com
azureiotsolutions.com
azureiotsuite.com
azureplanetscale.info
azureplanetscale.net
azureserviceprofiler.com
azuresmartspaces.net
azurestackvalidation.com
azurewebsites.net
chinacloudapi.cn
chinacloudapp.cn
chinacloudsites.cn
cosmosdb.info
cosmosdb.net
devopsms.com
gotcosmos.com
microsofteca.com
microsoftiotcentral.com
serverlesslibrary.net
signalr.net
tryfunctions.com
windowsazure.cn
windowsazure.com
azure.microsoft.com
azuremarketplace.microsoft.com
bbing.com
bibg.com
biing.com
binb.com
binf.com
bing
bing.com
bing.com.cn
bing.net
bing123.com
bing135.com
bing4.com
bingads.com
bingagencyawards.com
bingapis.com
bingapistatistics.com
binginternal.com
bingit.net
bingiton.com
bingj.com
bingpix.com
bingpk.com
bings.com
bingsandbox.com
bingtoolbar.com
bingtranslator.com
bingvisualsearch.com
bingworld.com
biying.cn
biying.com
biying.com.cn
bluehatnights.com
dictate.ms
discoverbing.com
explorebing.com
flipwithsurface.com
mapblast.com
mappoint.com
masalladeloslimites.com
microsoft-give.com
microsoftcloudsummit.com
microsoftdiplomados.com
microsoftlatamholiday.com
microsoftmxfilantropia.com
microsoftpartnersolutions.com
msnmaps.com
msunlimitedcloudsummit.com
myhomemsn.com
office365love.com
office365tw.com
osdinfra.net
renovacionoffice.com
sprinklesapp.com
working-bing-int.com
bj1.api.bing.com
emoi-cncdn.bing.com
cn.bing.com
cn.bing.net
ditu.live.com
a-msedge.net
c-msedge.net
e-msedge.net
edgesuite.net
evoke-windowsservices-tas.msedge
microsoftedge.com
microsoftedgeinsider.com
msedge.net
s-msedge.net
femalefounderscomp.com
m12.vc
adaptivecards.io
api-extractor.com
apisof.net
appcenter.ms
blazor.net
botframework.com
codethemicrobit.com
devopsassessment.net
dot.net
exp-tas.com
gamesstack.com
graphengine.io
insiderdevtour.com
jwt.ms
microbit.org
microsoftadc.com
microsoftgamestack.com
microsoftiotinsiderlabs.com
microsoftreactor.cn
microsoftreactor.com.cn
microsoftreactor.info
microsoftreactor.net
microsoftreactor.org
microsoftsilverlight.com
microsoftsilverlight.net
microsoftsilverlight.org
microsoftsqlserver.com
mmdnn.com
mono-project.com
msdn.com
msinnovationchallenge.com
mspairlift.com
msropendata.com
nuget.org
nugettest.org
opentranslatorstothings.org
poshtestgallery.com
pwabuilder.com
reactorms.com.cn
sankie.net
sqlserveronlinux.com
timelinestoryteller.com
uwpcommunitytoolkit.com
vfsforgit.com
vfsforgit.org
xamarin.com
developer.microsoft.com
dtlgalleryint.cloudapp.net
poshtestgallery.cloudapp.net
psg-int-centralus.cloudapp.net
psg-int-eastus.cloudapp.net
microsoft-online.cn
microsoft-online.com.cn
microsoftnews.cc
microsoftnews.cn
microsoftnews.com
microsoftnews.net
microsoftnews.org
microsoftnewsforkids.com
microsoftnewsforkids.net
microsoftnewsforkids.org
microsoftnewskids.com
microsoftnewskids.net
microsoftnewskids.org
microsoftol.com
microsoftol.com.cn
microsoftusercontent.com
msn.cn
msn.com
msn.com.cn
msn.com.nsatc.net
msn.com.tw
msnewskids.com
msnewskids.net
msnewskids.org
msnkids.com
winmp.cn
o365cn.com
o365files.cn
o365weve-dev.com
o365weve-ppe.com
o365weve.com
office
office.com
office.net
office365.com
officedev.cn
1drv.com
1drv.ms
livefilestore.com
onedrive.co
onedrive.co.uk
onedrive.com
onedrive.eu
onedrive.live.com
onedrive.net
onedrive.org
storage.live.com
groupme.com
skype.com
skype.net
skypeassets.com
skypeassets.net
skypeforbusiness.com
sway-cdn.com
sway-extensions.com
sway.com
visualstudio-staging.com
visualstudio.co
visualstudio.co.uk
visualstudio.com
visualstudio.eu
visualstudio.net
vsassets.io
vscode-unpkg.net
vscode-webview.net
vscode.dev
live.cn
live.com.akadns.net
sclive.net
windowslive.cn
wlxrs.com
aicscience.com
mmais.com.cn
msminico.cn
msminico.com.cn
msxiaobing.com
msxiaoice.com
msxiaona.cn
officeplus.cn
renlifang.com
cortana.ai
cortanaanalytics.com
cortanaskills.com
forzamotorsport.net
forzaracingchampionship.com
forzarc.com
gamepass.com
msgamestudios.com
orithegame.com
renovacionxboxlive.com
tellmewhygame.com
xbox.co
xbox.com
xbox.eu
xbox.org
xbox360.co
xbox360.com
xbox360.eu
xbox360.org
xboxab.com
xboxgamepass.com
xboxgamestudios.com
xboxlive.cn
xboxlive.com
xboxone.co
xboxone.com
xboxone.eu
xboxplayanywhere.com
xboxservices.com
xboxstudios.com
xbx.lv
callersbane.com
minecraft.net
minecraftshop.com
mojang.com
beth.games
bethesda.net
bethesdagamestudios.com
bethsoft.com
Applicationinsights.io
Applicationinsights.net
aadrm.com
acompli.net
aka.ms
ankarazirvesi2018.com
applicationinsights.io
applicationinsights.net
aria.ms
asp.net
aspnetcdn.com
assets-yammer.com
azurerms.com
binads.com
bluehatil.com
boswp.com
brazilpartneruniversity.com
breakdown.me
centralvalidation.com
ch9.ms
charticulator.com
cloudapp.net
cloudappsecurity.com
crmdynint-gcc.com
crmdynint.com
crossborderexpansion.com
docs.com
dwh5.com
dynamics.com
efproject.net
engkoo.com
fasttrackreadysupport.com
fluidpreview.com
footprintdns.com
gameuxmasterguide.com
gears5.com
gearspop.com
gearstactics.com
getmicrosoftkey.com
gfx.ms
gigjam.com
helpshift.com
hockeyapp.net
hololens.com
hotmail
hotmail.co
hotmail.com
hotmail.eu
hotmail.net
hotmail.org
hummingbird.ms
ie10.com
ie11.com
ie8.co
ie9.com
imaginecup.pl
img-prod-cms-rt-microsoft-com
ingads.com
internetexplorer.co
internetexplorer.com
intunewiki.com
iotinactionevents.com
joinms.com
joinms.com.cn
joinmva.com
kidgrid.tv
kumo.com
latampartneruniversity.com
live.com
live.com.au
live.eu
live.net
livingyourambition.com
localytics.com
lync.com
makecode.org
managedmeetingrooms.com
meetfasttrack.com
meetyourdevices.com
mepn.com
microsoft
microsoft-int.com
microsoft-ppe.com
microsoft-sap-events.com
microsoft-sbs-domains.com
microsoft-smb.cn
microsoft.az
microsoft.be
microsoft.by
microsoft.ca
microsoft.cat
microsoft.ch
microsoft.cl
microsoft.com
microsoft.com.akadns.net
microsoft.com.nsatc.net
microsoft.cz
microsoft.de
microsoft.dk
microsoft.ee
microsoft.es
microsoft.eu
microsoft.fi
microsoft.ge
microsoft.hu
microsoft.io
microsoft.is
microsoft.it
microsoft.jp
microsoft.lt
microsoft.lu
microsoft.lv
microsoft.md
microsoft.net
microsoft.pl
microsoft.pt
microsoft.red
microsoft.ro
microsoft.rs
microsoft.ru
microsoft.se
microsoft.si
microsoft.tv
microsoft.ua
microsoft.uz
microsoft.vn
microsoft365.com
microsoftaccountguard.com
microsoftads.com
microsoftadvertising.com
microsoftadvertisingregionalawards.com
microsoftaffiliates.com
microsoftapps.azurewebsites.net
microsoftazuread-sso.com
microsoftcloud.com
microsoftcloudworkshop.com
microsoftcommunitytraining.com
microsoftemail.com
microsoftestore.com.hk
microsofthouse.com
microsofthouse.net
microsoftinternetsafety.net
microsoftlatamaitour.com
microsoftlinc.com
microsoftonline-p.com
microsoftonline-p.net
microsoftonline.com
microsoftpartnercommunity.com
microsoftready.com
microsoftsiteselection.com
microsoftstore.com
microsoftstore.com.cn
microsoftstore.com.hk
microsoftstream.com
microsoftteams.com
microsofttradein.com
microsofttranslator.com
microsoftuwp.com
momentumms.com
morphcharts.com
mpnevolution.com
ms-studiosmedia.com
ms365surfaceoffer.com
msa.akadns6.net
msads.net
msappproxy.net
msauth.cn
msauth.net
msauthimages.net
mschallenge2018.com
msecnd.net
msft.info
msft.net
msftauth.cn
msftauth.net
msftauthimages.net
msftcenterone.cn
msftconnecttest.com
msfteducation.ca
msftidentity.com
msftnet.org
msgamesresearch.com
msidentity.com
msignitechina.com
msocdn.com
msocsp.com
msopentech.cn
mspil.cn
msra.cn
mstea.ms
msturing.org
msudalosti.com
msvevent.com
mymicrosoft.com
nextechafrica.net
nxta.org
oaspapps.com
oaspapps.com.akadns.net
onecollector.cloudapp.aria
onecollector.cloudapp.aria.akadns.net
onenote.com
onenote.net
onestore.ms
onmicrosoft.com
opticsforthecloud.net
optimizely.com
outingsapp.com
outlook.cn
outlook.com
outlookgroups.ms
outlookmobile.com
passport.net
phonefactor.net
pixapp.net
playfabapi.cn
playfabcn.com
powerappscdn.net
powerautomate.com
powerbi.com
powershellgallery.com
projectmurphy.net
projectsangam.com
pxt.io
s-microsoft.com
s-msft.com
s-msn.com
sfbassets.com
sfbassets.net
sfx.ms
sharepoint.cn
sharepoint.com
sharepointonline.com
skype
staffhub.ms
successwithteams.com
surface.com
svc.ms
syncshop.cn
sysinternals.com
tailwindtraders.com
techhub.ms
tenor.com
tfsallin.net
trafficmanager.net
translatetheweb.com
unlocklimitlesslearning.com
userpxt.io
uservoice.com
videobreakdown.com
videoindexer.ai
virtualearth.net
vsallin.net
wbd.ms
what-fan.net
windows.com
windows.net
windows-int.net
windows-ppe.net
windows.com
windows.net
windows.nl
windows8.hk
windowscommunity.net
windowsmarketplace.com
windowsphone-int.com
windowsphone.com
windowssearch.com
windowsupdate.com
winhec.com
winhec.net
yammer.com
yammerusercontent.com
g.akamaiedge.net
a1158.g.akamai.net
a122.dscg3.akamai.net
a767.dscg3.akamai.net
cs11.wpc.v0cdn.net
cs9.wac.phicdn.net
b.akamaiedge.net
spoprod-a.akamaihd.net
windows.com.akadns.net
prod-video-cms-rt-microsoft-com.akamaized.net
statics-marketingsites-eas-ms-com.akamaized.net
statics-marketingsites-neu-ms-com.akamaized.net
vip5.afdorigin-prod-am02.afdogw.com
img-prod-cms-rt-microsoft-com.akamaized.net
img-s-msn-com.akamaized.net
mwf-service.akamaized.net
officecdn-microsoft-com.akamaized.net
statics-marketingsites-eus-ms-com.akamaized.net
statics-marketingsites-wcus-ms-com.akamaized.net
同样没有效果，并且我已经把给规则放在第三个位置了，第一个是AD去广告，第二个是BT 黑洞。
