### ISSUE TITLE
请求增加Cortex-A5架构的依赖包集合

### ISSUE THREAD

**Issue by Tsubamei** [xiaorouji/openwrt-package#2690]
### 描述你想要的新功能

玩客云上的晶晨S805芯片使用的Cortex-A5架构，用目前的依赖包安装测试显示 架构不符安装失败

### 描述你想要的解决方案

A5架构是在A8和A9架构之后出的32位架构，FPU为VFPv4 (optional)

**Comment by iamyangyiok** [comment]
S805该放弃了

**Comment by laaArmy** [comment]
钉子户
