### ISSUE TITLE
[Bug]: openwrt 22.03.5 纯原版编译，无法开启代理，日志一片空白。

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-package#2691]
纯原版 openwrt 编译后无法开启代理，日志一片空白。

附件 config 文件。

[config.txt](https://github.com/xiaorouji/openwrt-passwall/files/12267455/config.txt)

目前不知道是什么影响的，或者缺少什么依赖，还请各位大佬帮忙瞧一眼。

没有具体的日志信息，我就不上传截图了。

烦请大佬动小手编译一下便知。

**Comment by uingei** [comment]
22.03建议还是用fw3编译吧，fw4就用23.05

**Comment by ghost** [comment]
> 22.03建议还是用fw3编译吧，fw4就用23.05

FW3 FW4如何选择呢。

**Comment by uingei** [comment]
默认就是fw4，要fw3最简单的办法就是先创建一个简单的配置文件
cat >> .config <<EOF
        CONFIG_PACKAGE_firewall=y
        # CONFIG_PACKAGE_firewall4 is not set
        CONFIG_PACKAGE_kmod-ipt-offload=y
        # CONFIG_PACKAGE_kmod-nft-offload is not set
        CONFIG_PACKAGE_ip6tables-zz-legacy=y
        CONFIG_PACKAGE_iptables-zz-legacy=y
        # CONFIG_PACKAGE_nftables-json is not set
        # CONFIG_PACKAGE_nftables-nojson is not set
        EOF
