### ISSUE TITLE
[Bug]: 目前不支持ipv6格式的dns解析吗？

### ISSUE THREAD

**Issue by Pacio** [xiaorouji/openwrt-package#2695]
### 描述您遇到的bug

目前不支持ipv6格式的dns解析吗？默认的1.1.1.1一切正常，突然想试试ipv6格式的dns，发现全部不通

### 复现此Bug的步骤

![image](https://github.com/xiaorouji/openwrt-passwall/assets/6836705/48c7282d-d285-41d6-be42-ad30dfcd4114)

### 您想要实现的目的

使用ipv6格式dns

### 日志信息

和系统无关

### 系统相关信息

全部最新版本

**Comment by handsomeji** [comment]
使用ipv6 dns你要 IPv6透明代理(TProxy)

**Comment by Pacio** [comment]
> 使用ipv6 dns你要 IPv6透明代理(TProxy)

用了啊~都开了，一切正常，ip.sb测试也能识别ipv6国外地址，就是dns设置v6格式就不通
