### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FanYang426** [xiaorouji/openwrt-package#2696]
### 描述您遇到的bug

提示缺少依赖libopenssl3

### 复现此Bug的步骤

安装passlall就报错

### 您想要实现的目的

希望出一个依赖包

### 日志信息

，

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/101784592/c3a3f93b-ce4a-48e2-861e-f5372f962a3d)

### 系统相关信息

，

### 其他信息

，

**Comment by Q-Qian** [comment]
请问找到libopenssl3这个依赖包了吗？我也遇到了同样的问题

**Comment by Peterzhangnoise** [comment]
+1

**Comment by samlee111** [comment]
https://dl.openwrt.ai/packages-23.05/x86_64/base/libopenssl3_3.0.11-1_x86_64.ipk
你们要是其他架构的，往上级菜单去找找
