### ISSUE TITLE
[Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-package#2699]
### 描述您遇到的bug

[Bug]: 红米AX6000 237 OP 7月1日版 用近来PW版本会不定时系统崩溃。
装了PW4.66-8以后及最4.67-1 都会不定时的OP后台崩溃 WEB登录不了，暂时能上网， PW失效，过下DHCP之类也会失效。 已经不断换系统多次，只到装回4.66-5就正常了。 另想问下 怎么下载老版本的PW。

### 复现此Bug的步骤

[Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。

### 您想要实现的目的

[Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。

### 日志信息

[Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。

### 系统相关信息

[Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。

**Comment by iamyangyiok** [comment]
因为 没法进后台 看不到实时日志 回放日志没有异常，感觉是和DNS冲突啥的。

**Comment by iamyangyiok** [comment]
但是DNS DHCP服务我用默认  的DNSMASQ或ADG 都分开开代替 也一样没效果

**Comment by Pacio** [comment]
跑pcdn了吧~应该不是pw的锅

**Comment by iamyangyiok** [comment]
没 就日常用



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月11日 00:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaorouji/openwrt-passwall] [Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。 (Issue #2699) |

跑pcdn了吧~应该不是pw的锅

**Comment by Pacio** [comment]
> 没 就日常用
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年08月11日 00:52 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [xiaorouji/openwrt-passwall] [Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。 (Issue #2699) | 跑pcdn了吧~应该不是pw的锅 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你换ssrp对比测试一下~

**Comment by iamyangyiok** [comment]
> > 没 就日常用
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年08月11日 00:52 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [xiaorouji/openwrt-passwall] [Bug]: 红AX6000 237的IP用近来PW版本会不定时系统崩溃。 (Issue #2699) | 跑pcdn了吧~应该不是pw的锅 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 你换ssrp对比测试一下~

新进展 昨天换上又换了4668 ，如果不开CHINA NGDNS就解国内很卡，就开了，开了暂时没有崩。观察中

**Comment by iamyangyiok** [comment]
现在最新进展， 也装较新的PW版本， 只要不开CHINA-NG DNS 用段时就会OP崩溃，OP后台都进不去，选上了CHINA-NG就一直正常。

**Comment by zhupn** [comment]
Mi AC2100 有同样问题。 自己排查好像是geoip.dat 过大导致的。

**Comment by iamyangyiok** [comment]
> Mi AC2100 有同样问题。 自己排查好像是geoip.dat 过大导致的。

我不过大，就是不能关CHINANG-DNS.. 我想取消 CHINANG-DNS
