### ISSUE TITLE
[Bug]: nftables 性能问题

### ISSUE THREAD

**Issue by moetayuko** [xiaorouji/openwrt-package#2703]
### 描述您遇到的bug

用的是GFW列表模式。使用几天后 passwall 开头的几个 nftables set 会变得十分庞大，而与此同时网络性能会急剧降低。本来能基本跑满千兆公网，在 set 变大以后下载速度会掉到百兆左右

印象中 iptables + ipset 对性能影响没有这么离谱（包括 iptables-nft），因为在这个模式下代理 ip 名单仍然在 ipset 里面。

此外，luci 里关闭 passwall 主开关后那几个 set 不会删掉，所以 set 变大以后关闭或重启 passwall 服务并不会改善网络状况，而需要重启系统

### 复现此Bug的步骤

RT

### 您想要实现的目的

改善 nftables 网络性能

### 日志信息

n/a

### 系统相关信息

- 4.67-4-smartdns-dev-brach
- OpenWrt 23.05.0-rc2

**Comment by handsomeji** [comment]
我暂时还没完全切换到nftables，所以有待各位测试。
DNS选项里面有个 `清空 IPSET` 按钮，可清空set

**Comment by SakuraFallingMad** [comment]
借楼提一嘴，nftables方式使用好像还能优化，在op-23.05下，调整过网络配置后，Passwall就不能正常使用了，必须要重启之后正常。能复现的就是在Passwall启动后，随意调整和nftables有关的设置后，如果不再重启Passwall，Passwall是无法使用的。

**Comment by ShanStone** [comment]
为set尝试添加了timeout参数，会自动清除长时间未使用的ip，先用一段时间看看情况

**Comment by Peterzhangnoise** [comment]
> 
你这还好，起码还能用，我这直接用不了了，节点咋样检测可用性都是超时

**Comment by jh0072110** [comment]
你们都用的什么设备性能这么差……

**Comment by moetayuko** [comment]
> 你们都用的什么设备性能这么差……

这跟设备性能差不差是两码事，你不能以国产安卓 app 的态度去做软件

**Comment by xh0823** [comment]
借楼问问大佬系统日志里面好多这样的，官方的x86版本
Sat Sep  2 11:30:17 2023 daemon.err dnsmasq[5]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
Sat Sep  2 11:30:17 2023 daemon.err dnsmasq[6]: nftset inet fw4 passwall_chnroute Error: Could not process rule: File exists
Sat Sep  2 11:30:18 2023 daemon.err dnsmasq[22]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
Sat Sep  2 11:30:18 2023 daemon.err dnsmasq[22]: nftset inet fw4 passwall_chnroute6 netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[350]: nftset inet fw4 passwall_gfwlist
Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[367]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[367]: nftset inet fw4 passwall_chnroute6 netlink: Error: cache initialization failed: Protocol error
Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[368]: nftset inet fw4 passwall_gfwlist
Sat Sep  2 11:32:18 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Resource busy

**Comment by ShanStone** [comment]
> 借楼问问大佬系统日志里面好多这样的，官方的x86版本
> Sat Sep  2 11:30:17 2023 daemon.err dnsmasq[5]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
> Sat Sep  2 11:30:17 2023 daemon.err dnsmasq[6]: nftset inet fw4 passwall_chnroute Error: Could not process rule: File exists
> Sat Sep  2 11:30:18 2023 daemon.err dnsmasq[22]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
> Sat Sep  2 11:30:18 2023 daemon.err dnsmasq[22]: nftset inet fw4 passwall_chnroute6 netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:14 2023 daemon.err dnsmasq[350]: nftset inet fw4 passwall_gfwlist
> Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[367]: nftset inet fw4 passwall_gfwlist6 netlink: Error: cache initialization failed: Resource busy
> Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[367]: nftset inet fw4 passwall_chnroute6 netlink: Error: cache initialization failed: Protocol error
> Sat Sep  2 11:32:16 2023 daemon.err dnsmasq[368]: nftset inet fw4 passwall_gfwlist
> Sat Sep  2 11:32:18 2023 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: Error: cache initialization failed: Resource busy

dnsmasq在遇到短时间大量添加ip到nftset时会出现，应该算上游的问题，勾选启用chinadns-ng，应该可以避免这个问题。

**Comment by xh0823** [comment]
> > 借楼问大佬系统日志里面好多这样的，官方的x86版本
> > Sat Sep 2 11:30:17 2023 daemon.err dnsmasq[5]: nftset inet fw4 passwall_gfwlist6 netlink: Error: 缓存初始化失败: 资源繁忙
> > Sat Sep 2 11:30:17 2023 daemon.err dnsmasq[6]: nftset inet fw4 passwall_chnroute 错误：无法处理规则：文件存在
> > 周六 9 月 2 日 11:30:18 2023 daemon.err dnsmasq[22]：nftset inet fw4 passwall_gfwlist6 netlink ：错误：缓存初始化失败：资源繁忙
> > 2023年9月2日星期六11:30:18 daemon.err dnsmasq[22]：nftset inet fw4 passwall_chnroute6 netlink：错误：缓存初始化失败：协议错误2023年9月2日星期六
> > 11:32:14守护进程.err dnsmasq[1]：nftset inet fw4 passwall_gfwlist6 netlink：错误：缓存初始化失败：协议错误
> > 2023 年 9 月 2 日星期六 11:32:14 daemon.err dnsmasq[1]: nftset inet fw4 passwall_gfwlist netlink: 错误：缓存初始化失败：协议错误 2023 年 9 月 2 日 11:32:14 星期六 daemon.err dnsmasq[1]：nftset 
> > inet fw4 passwall_gfwlist netlink：错误：缓存初始化失败：协议错误
> > 2023 年 9 月 2 日星期六 11:32:14 daemon.err dnsmasq[1]：nftset inet fw4 passwall_gfwlist netlink：错误：缓存初始化失败：协议错误 9 月 2 日星期六
> > 11:32： 14 2023 daemon.err dnsmasq[1]：nftset inet fw4 passwall_gfwlist netlink：错误：缓存初始化失败：协议错误
> > 周六 9 月 2 日 11:32:14 2023 daemon.err dnsmasq[1]：nftset inet fw4 passwall_gfwlist netlink：错误：缓存初始化失败：协议错误
> > 2023 年 9 月 2 日 11:32:14 星期六 daemon.err dnsmasq[1]：nftset inet fw4 passwall_gfwlist netlink：错误：缓存初始化失败：协议错误 2023 年 9 月 2 日 11:32:14 星期六 daemon.err dnsmasq[350]：
> > nftset inet fw4 passwall_gfwlist 
> > 2023 年 9 月 2 日星期六 11:32:16 daemon.err dnsmasq[367]：nftset inet fw4 passwall_gfwlist6 netlink：错误：缓存初始化失败：资源繁忙 2023 年 9 月 2 日
> > 11:32:16 星期六 daemon.err dnsmasq[367]： nftset inet fw4 passwall_chnroute6 netlink：错误：缓存初始化失败：协议错误
> > 2023 年 9 月 2 日 11:32:16 daemon.err dnsmasq[368]：nftset inet fw4 passwall_gfwlist 2023 年 9 月 2 日
> > 11:32:18 星期六 daemon.err dnsmasq[1 ]: nftset inet fw4 passwall_gfwlist netlink: 错误: 缓存初始化失败: 资源繁忙
> 
> dnsmasq 在遇到短时间大量添加 ip 到 nftset 时应该会出现，应该算上游的问题，勾选启用 chinadns-ng，可以避免这个问题。

谢谢大佬，勾选启用 chinadns-ng，可以了，但是dns泄露了
