### ISSUE TITLE
[Bug]: passwall 重启有出现报错信息

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#2704]
### 描述您遇到的bug

在ssh里，service passwall restart 出现提示：
`usr/share/passwall/app.sh: /usr/share/passwall/nftables.sh: line 1154: can't create : nonexistent directory
/usr/share/passwall/app.sh: /usr/share/passwall/nftables.sh: line 1222: can't create : nonexistent directory
`

### 复现此Bug的步骤

1、ssh连接路由器
2、输入“service passwall restart”
3、成功复现

### 您想要实现的目的

希望能无报错运行

### 日志信息

暂无

### 截图

暂无

### 系统相关信息

Passwall 版本: 4.67-4
Openwrt版本： ImmortalWrt 23.05-SNAPSHOT, r26915-79875c8dc2

**Comment by smallprogram** [comment]
尝试了一下，没有复现该问题。
我试试执行`uci -q get firewall.passwall.path`是否能够正常返回一个有效的目录路径，我的固件没有问题，不知道你的固件是否成功

**Comment by SakuraFallingMad** [comment]
嗯，我重新配置了没问题了
