### ISSUE TITLE
[Feature Request]: 建议保留节点自动切换，这个功能还是挺有用的

### ISSUE THREAD

**Issue by Hello-Panda1975** [xiaorouji/openwrt-package#2706]
### 描述你想要的新功能

4.67-4升级到4.68-1，节点自动切换功能没了，这个功能还是挺有用的，建议保留

### 描述你想要的解决方案

4.67-4升级到4.68-1，节点自动切换功能没了，这个功能还是挺有用的，建议保留

**Comment by handsomeji** [comment]
移到socks配置里面了

**Comment by woni928** [comment]
> 移到socks配置里面了
感谢，为什么要移到socks哪里？
还有这个socks到底是干什么的，又怎么用？

**Comment by wgjwillis** [comment]
之前的标签页设置【节点自动切换】，设置简单，逻辑清晰。socks设置本地自动切换的意义是什么？为了节约标签吗？？请各位不吝留言，请求大佬恢复自动切换标签。

**Comment by gnaiqgnoh85** [comment]
> 移到socks配置里面了

都会弄，但有几个能真的弄明白的。怎么想的。

**Comment by Rain113113** [comment]
> 移到socks配置里面了

大哥 在哪里  能截个图吗  怎么设置
