### ISSUE TITLE
 [Bug]: SOCKS设置自动切换以后，steam经常断连

### ISSUE THREAD

**Issue by Hello-Panda1975** [xiaorouji/openwrt-package#2708]
### 描述您遇到的bug

SOCKS设置自动切换以后，steam经常断连

### 复现此Bug的步骤
版本4.68-1
1.SOCKS设置中添加SOCKS节点
2.在passwall节点列表中新建SOCKS节点，指向第一步的Socks节点
3.使用用第2步建好的节点，steam断连
4.切换回订阅节点，steam正常链接
5.再切到第2步建的节点，steam正常链接
6.重启软路由，重启电脑，steam断连
### 您想要实现的目的

4.67-4没有以上问题，建议下个版本节点自动切换能不能改回4.67的样式？

### 日志信息

SOCKS设置自动切换以后，steam经常断连

 [Bug]: 
_No response_

### 系统相关信息

4.68-1

**Comment by handsomeji** [comment]
可能是切换了不同地区的节点，DNS问题。
你可把新建的socks节点切换成xray + socks类型，试试。

**Comment by Hello-Panda1975** [comment]
xray+socks，今天试了没碰到断联了

**Comment by aaronzgh** [comment]
> 可能是切换了不同地区的节点，DNS问题。 你可把新建的socks节点切换成xray + socks类型，试试。

新建的 socks节点 这里说的切换类型是指2个配置项分别设置成 xray 和 socks 吗？
没有看到有哪个配置项，里面可以选择 “xray+socks” 这样
