### ISSUE TITLE
关于负载均衡

### ISSUE THREAD

**Issue by hm-Private** [xiaorouji/openwrt-package#2709]
### 描述你想要的新功能

每次负载均衡都要手动添加对应节点，如果更新，有些节点名称不一样就会消失

### 描述你想要的解决方案

可以像自动切换那样，用正则筛选方式添加节点吗？

**Comment by showme2005** [comment]
顺便在问个负载均衡节点是咖啡色的问题。。不知道是机场的问题 还是passwall或者是haproxy的问题，，升级2.8的haproxy也是一样的咖啡色

**Comment by xllxll** [comment]
> 顺便在问个负载均衡节点是咖啡色的问题。。不知道是机场的问题 还是passwall或者是haproxy的问题，，升级2.8的haproxy也是一样的咖啡色

我使用也是同样的 down 颜色,重启能使用几分钟后又变回down. 不能自己变回激活状态.

**Comment by hm-Private** [comment]
> Stale Issue

希望支持，这样会更方便一点，每次更新订阅，都会通过正则筛选，将指定地区节点导入

**Comment by xllxll** [comment]
> > 顺便在问个负载均衡节点是咖啡色的问题。。不知道是机场的问题 还是passwall或者是haproxy的问题，，升级2.8的haproxy也是一样的咖啡色
> 
> 我使用也是同样的 down 颜色,重启能使用几分钟后又变回down. 不能自己变回激活状态.

的确一直存在这些问题.希望有所改进吧.
