### ISSUE TITLE
关于自动切换的问题

### ISSUE THREAD

**Issue by bcseputetto** [xiaorouji/openwrt-package#2715]
### 描述您遇到的bug

之前的自动切换，我可以只切换分流里的前置代理节点，现在的Socks里的自动切换，我要怎么设置才能达到一致的目的？
还有一个BUG，Socks配置页面，节点不能选分流，但回到基本设置主页面那里Socks节点又可以选分流，让人很是疑惑。
不过我的重点还是如何才能达到跟之前自动切换一样只切换的分流里的前置代理节点。

### 复现此Bug的步骤

N/A

### 您想要实现的目的

N/A

### 日志信息

N/A

### 系统相关信息

passwall 4.68-1

**Comment by woni928** [comment]
我也有这个问题，哪位同学帮忙解释下

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2708

**Comment by bcseputetto** [comment]
> #2708

我大概懂怎么操作了
添加Socks，配置节点，和自动切换。
然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点
请问这么操作对吗？
![1](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/46e0b9e0-5b30-4ab7-a029-4d0e8e2a2dd2)
![2](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/6b1a00de-5434-4a04-865d-24a6aeae01d6)
![3](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/3ef7b01f-cc50-4fc8-af78-578b72ba2010)

**Comment by handsomeji** [comment]
也可以不用专门创建节点，可以直接在选择节点的时候自定义输入 socks://127.0.0.1:1081

**Comment by woni928** [comment]
> > #2708
> 
> 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？ ![1](https://user-images.githubusercontent.com/29139573/263523839-46e0b9e0-5b30-4ab7-a029-4d0e8e2a2dd2.png) ![2](https://user-images.githubusercontent.com/29139573/263523843-6b1a00de-5434-4a04-865d-24a6aeae01d6.png) ![3](https://user-images.githubusercontent.com/29139573/263523846-3ef7b01f-cc50-4fc8-af78-578b72ba2010.png)

按照你的设置  为什么我的不行？
日志当中显示  节点正常 切换完毕  然而无法翻墙

**Comment by bcseputetto** [comment]
> > > #2708
> > 
> > 
> > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？ 
> 
> 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙

我这边测试是正常的，你可以贴一下你配置的截图
注意Socks也有个主开关，记得打开

**Comment by woni928** [comment]
> > > > #2708
> > > 
> > > 
> > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > 
> > 
> > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> 
> 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开

<img width="845" alt="1" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/6e56a7f6-4c3e-420b-a354-1745515beddf">
<img width="1048" alt="2" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/eac21717-f6ea-4098-b32c-29e723f56f40">
<img width="965" alt="3" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/2202c2bb-25dc-441e-9a7a-44f1d1917136">
<img width="995" alt="4" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/d1ca0ad3-972c-4fc7-89cc-58b5dba75e75">
<img width="1934" alt="5" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/785b59b0-64e8-4495-9cfa-6d89ec9f46b4">

无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。

**Comment by bcseputetto** [comment]
> > > > > #2708
> > > > 
> > > > 
> > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > 
> > > 
> > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > 
> > 
> > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> 

> 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。

你可以尝试在节点列表测试一下Socks是否连通
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/da1161e8-aebc-4a95-9d13-459b894ce006)

**Comment by woni928** [comment]
> > > > > > #2708
> > > > > 
> > > > > 
> > > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > > 
> > > > 
> > > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > > 
> > > 
> > > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> 
> > 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。
> 
> 你可以尝试在节点列表测试一下Socks是否连通 ![image](https://user-images.githubusercontent.com/29139573/264431441-da1161e8-aebc-4a95-9d13-459b894ce006.png)

<img width="1070" alt="6" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/93fd7817-d640-4307-89b9-09f6a566b052">
通的  但是翻不了墙 国内网正常

**Comment by bcseputetto** [comment]
> > > > > > > #2708
> > > > > > 
> > > > > > 
> > > > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > > > 
> > > > > 
> > > > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > > > 
> > > > 
> > > > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> > 
> > 
> > > 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。
> > 
> > 
> > 你可以尝试在节点列表测试一下Socks是否连通 ![image](https://user-images.githubusercontent.com/29139573/264431441-da1161e8-aebc-4a95-9d13-459b894ce006.png)
> 
> <img alt="6" width="1070" src="https://user-images.githubusercontent.com/28220733/264641304-93fd7817-d640-4307-89b9-09f6a566b052.png"> 通的 但是翻不了墙 国内网正常

我突然发现你上面，默认前置代理节点是关闭状态，你这个不打开，不会走前置代理的
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/3f9030d0-d0cc-408e-98b0-013f3b2e20af)

**Comment by woni928** [comment]
> > > > > > > > #2708
> > > > > > > 
> > > > > > > 
> > > > > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > > > > 
> > > > > > 
> > > > > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > > > > 
> > > > > 
> > > > > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> > > 
> > > 
> > > > 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。
> > > 
> > > 
> > > 你可以尝试在节点列表测试一下Socks是否连通 ![image](https://user-images.githubusercontent.com/29139573/264431441-da1161e8-aebc-4a95-9d13-459b894ce006.png)
> > 
> > 
> > <img alt="6" width="1070" src="https://user-images.githubusercontent.com/28220733/264641304-93fd7817-d640-4307-89b9-09f6a566b052.png"> 通的 但是翻不了墙 国内网正常
> 
> 我突然发现你上面，默认前置代理节点是关闭状态，你这个不打开，不会走前置代理的 ![image](https://user-images.githubusercontent.com/29139573/264645983-3f9030d0-d0cc-408e-98b0-013f3b2e20af.png)

打开了 还是翻不了墙 日志显示是正确的：已经切换到正常的节点。
<img width="887" alt="7" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/7641f37e-69c4-445c-aad6-f7ddacdd7997">
<img width="644" alt="8" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/a0c2fa01-d33f-4415-a09b-9d92cf694b33">

**Comment by bcseputetto** [comment]
> > > > > > > > > #2708
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > > > > > 
> > > > > > 
> > > > > > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> > > > 
> > > > 
> > > > > 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。
> > > > 
> > > > 
> > > > 你可以尝试在节点列表测试一下Socks是否连通 ![image](https://user-images.githubusercontent.com/29139573/264431441-da1161e8-aebc-4a95-9d13-459b894ce006.png)
> > > 
> > > 
> > > <img alt="6" width="1070" src="https://user-images.githubusercontent.com/28220733/264641304-93fd7817-d640-4307-89b9-09f6a566b052.png"> 通的 但是翻不了墙 国内网正常
> > 
> > 
> > 我突然发现你上面，默认前置代理节点是关闭状态，你这个不打开，不会走前置代理的 ![image](https://user-images.githubusercontent.com/29139573/264645983-3f9030d0-d0cc-408e-98b0-013f3b2e20af.png)
> 
> 打开了 还是翻不了墙 日志显示是正确的：已经切换到正常的节点。 <img alt="7" width="887" src="https://user-images.githubusercontent.com/28220733/264914201-7641f37e-69c4-445c-aad6-f7ddacdd7997.png"> <img alt="8" width="644" src="https://user-images.githubusercontent.com/28220733/264914206-a0c2fa01-d33f-4415-a09b-9d92cf694b33.png">

你这新截的图，【默认前置代理】不也还是关闭的吗？如果你真的打开了不行，那我也不确定咋回事了。

**Comment by woni928** [comment]
> > > > > > > > > > #2708
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我大概懂怎么操作了 添加Socks，配置节点，和自动切换。 然后在节点列表添加一个本地的Socks节点，然后在Xray/V2ray分流的前置代理节点里使用那个本地Socks节点 请问这么操作对吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 按照你的设置 为什么我的不行？ 日志当中显示 节点正常 切换完毕 然而无法翻墙
> > > > > > > 
> > > > > > > 
> > > > > > > 我这边测试是正常的，你可以贴一下你配置的截图 注意Socks也有个主开关，记得打开
> > > > > 
> > > > > 
> > > > > > 无法翻墙，但是国内正常上网。退回到4.67-4版本，自动切换正常，上国内网也正常。
> > > > > 
> > > > > 
> > > > > 你可以尝试在节点列表测试一下Socks是否连通 ![image](https://user-images.githubusercontent.com/29139573/264431441-da1161e8-aebc-4a95-9d13-459b894ce006.png)
> > > > 
> > > > 
> > > > <img alt="6" width="1070" src="https://user-images.githubusercontent.com/28220733/264641304-93fd7817-d640-4307-89b9-09f6a566b052.png"> 通的 但是翻不了墙 国内网正常
> > > 
> > > 
> > > 我突然发现你上面，默认前置代理节点是关闭状态，你这个不打开，不会走前置代理的 ![image](https://user-images.githubusercontent.com/29139573/264645983-3f9030d0-d0cc-408e-98b0-013f3b2e20af.png)
> > 
> > 
> > 打开了 还是翻不了墙 日志显示是正确的：已经切换到正常的节点。 <img alt="7" width="887" src="https://user-images.githubusercontent.com/28220733/264914201-7641f37e-69c4-445c-aad6-f7ddacdd7997.png"> <img alt="8" width="644" src="https://user-images.githubusercontent.com/28220733/264914206-a0c2fa01-d33f-4415-a09b-9d92cf694b33.png">
> 
> 你这新截的图，【默认前置代理】不也还是关闭的吗？如果你真的打开了不行，那我也不确定咋回事了。

试过了，确实不行。算了，不折腾了，回滚到以前的版本。谢谢耐心的解答！

**Comment by handsomeji** [comment]
@woni928 可用性连通是证明没问题的。我看你的用法有问题，你将socks作为了前置代理节点，而默认节点却不是socks节点又不是使用前置代理。

**Comment by laaArmy** [comment]
> https://github.com/xiaorouji/openwrt-passwall/issues/2708

大佬..能加回来么

**Comment by xinjiawei** [comment]
这改动，太蠢了，真是完全的傻逼改动

**Comment by hbtx99099** [comment]
> 也可以不用专门创建节点，可以直接在选择节点的时候自定义输入 socks://127.0.0.1:1081

今天请假在家弄了三个小时，最终成功使我的软路由进入死循环。
无论这样的更改背后有什么思考，请不要在打哑谜了，给个推荐设置方法吧！！！

**Comment by imjamespan** [comment]
成功设置了，但是IPv6地址丢失了

**Comment by start2021-better** [comment]
> @woni928 可用性连通是证明没问题的。我看你的用法有问题，你将socks作为了前置代理节点，而默认节点却不是socks节点又不是使用前置代理。

这是看糊涂了，这个修改的处理逻辑是太混乱的毫无逻辑章法。谁能梳理下系统处理逻辑（不解释清楚，反人类啊的逻辑处理真要这样玩吗），应该如何的配置自动切换呢？还是修改后就是为了搞晕打家吗？
