### ISSUE TITLE
关于TCP节点的自动切换功能

### ISSUE THREAD

**Issue by mitsukileung** [xiaorouji/openwrt-package#2720]
### 描述您遇到的bug

更新版本后怎样设置TCP节点的自动切换？之前有自动切换的选项菜单，新版没有这个菜单要怎样设置？

### 复现此Bug的步骤

N/A

### 您想要实现的目的

N/A

### 日志信息

N/A

### 截图

No response

### 系统相关信息

4.69-1

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2708

**Comment by mitsukileung** [comment]
> #2708

明白了，像俄罗斯套娃一样，谢谢！
