### ISSUE TITLE
节点自动切换没了

### ISSUE THREAD

**Issue by zuixinxuting** [xiaorouji/openwrt-package#2721]
### 描述你想要的新功能

节点自动切换没了

### 描述你想要的解决方案

节点自动切换能不能加回去阿

**Comment by bcseputetto** [comment]
#2715 
#2708 
#2720

**Comment by keke1975** [comment]
其实他的意思是，passwall的4.66版在“节点订阅”和"高级设置"之间，本来有一个“自动切换”，现在4.69这个功能没有了。想请问一下要怎么样才能把它加回来？
![Snipaste_2023-08-28_04-41-54](https://github.com/xiaorouji/openwrt-passwall/assets/61652857/1ea1378b-121b-4bcb-8271-5ed404777985)

**Comment by uingei** [comment]
新模式内存占用比原来多了不少

**Comment by mnubytpk** [comment]
> 其实他的意思是，passwall的4.66版在“节点订阅”和"高级设置"之间，本来有一个“自动切换”，现在4.69这个功能没有了。想请问一下要怎么样才能把它加回来？ ![Snipaste_2023-08-28_04-41-54](https://user-images.githubusercontent.com/61652857/263553049-1ea1378b-121b-4bcb-8271-5ed404777985.jpg)

我更新到4.69-1之后，也遇到了同样的问题

**Comment by mitsukileung** [comment]
> 新模式内存占用比原来多了不少

这个倒没有什么感觉，好像内存占用都差不多吧

**Comment by laaArmy** [comment]
真蠢的设计.......

**Comment by binweite** [comment]
为什么自动切换没有了？

**Comment by cp088** [comment]
同问

**Comment by X-Firefly** [comment]
同问

**Comment by csco11298754** [comment]
同问，为什么自动切换节点的功能取消了啊，大佬。

**Comment by uingei** [comment]
> 同问，为什么自动切换节点的功能取消了啊，大佬。

自动切换在 Socks配置 里

**Comment by csco11298754** [comment]
> > 同问，为什么自动切换节点的功能取消了啊，大佬。
> 
> 自动切换在 Socks配置 里

这个该怎么配置？
系统默认配置是
TCP 节点 Socks 监听端口：1070
Socks 监听端口：1081

**Comment by wgjwillis** [comment]
请各位不吝留言，请求大佬恢复自动切换标签。

**Comment by gnaiqgnoh85** [comment]
Socks如何配置 HTTP监听端口怎么填。抱歉，我没有说清楚问题，启用自动切换的前提，是必须启用Socks，还是不需要启用。具体怎么用

**Comment by lizhiwei8061** [comment]
去掉的目的是啥呢？

**Comment by aaronzgh** [comment]
同问

（为啥这个没有看到解决方案或者是调整的原因之类的 close 回复，issue 就被 close 了呢

**Comment by mitsukileung** [comment]
> 同问
> 
> （为啥这个没有看到解决方案或者是调整的原因之类的 close 回复，issue 就被 close 了呢

你认真看看二楼的三个链接，哪里不是明摆着有解决方法！

**Comment by zhuangli888** [comment]
我的方法：不是设置“前置代理”，而是打开“sock配置”，把主节点和备用节点这些全部设置好之后，重新回到主界面，把“默认”设置为“soke配置【1081端口】”。如果没有这个选项，就直接填“127.0.0.1:8081”。

![Image](https://github.com/user-attachments/assets/52cc365a-e8c9-45b9-942a-4902cda1c358)
