### ISSUE TITLE
出了个新协议juicity，请求支持

### ISSUE THREAD

**Issue by aisuyi065** [xiaorouji/openwrt-package#2730]
### 描述你想要的新功能

https://github.com/juicity/juicity
什么时候会支持这个新协议呢，就像hysteria一样

### 描述你想要的解决方案

1

### 描述你考虑过的替代方案

1

### 其他信息

1

**Comment by Travel2Here** [comment]
More stable.
More actively maintained.
Better UDP implementation.
Better compatibility and consistency with clients in Golang.
基于tuic调优，看介绍性能不错~游戏玩家的福音。关注ing~

**Comment by handsomeji** [comment]
最近会先优先引入sing-box

**Comment by SakuraFallingMad** [comment]
> 最近会先优先引入sing-box

是准备用sing-box替代xray嘛

**Comment by handsomeji** [comment]
sing-box 数据结构清晰，且DNS模块完善。
目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev

**Comment by SakuraFallingMad** [comment]
> sing-box 数据结构清晰，且DNS模块完善。 目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev

期待这个，这样可以考虑裁减组件依赖了。

**Comment by gg4924** [comment]
> sing-box 数据结构清晰，且DNS模块完善。 目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev

期待在passwall上实现，喜欢passwall2的简洁，不过我使用passwall2一切换节点或者保存应用设置游戏就断线，passwall则没有这个问题。

**Comment by swxk521** [comment]
> > sing-box 数据结构清晰，且DNS模块完善。 目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev
> 
> 期待在passwall上实现，喜欢passwall2的简洁，不过我使用passwall2一切换节点或者保存应用设置游戏就断线，passwall则没有这个问题。

现在变成了用sock5切换节点，不会说切换节点，会断线，除非是要科学的游戏。看大佬意思是sing-box为主了，passwall2更新应该比较快。

**Comment by gg4924** [comment]
> > > sing-box 数据结构清晰，且DNS模块完善。 目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev
> > 
> > 
> > 期待在passwall上实现，喜欢passwall2的简洁，不过我使用passwall2一切换节点或者保存应用设置游戏就断线，passwall则没有这个问题。
> 
> 现在变成了用sock5切换节点，不会说切换节点，会断线，除非是要科学的游戏。看大佬意思是sing-box为主了，passwall2更新应该比较快。

并非是需要科学的游戏，我默认直连，仅代理需要代理的网络，就这样切换节点都会掉线，玩游戏的时候更改下设置都不敢。后来换了passwall就行了，随便更改设置，更新订阅，切换节点，无任何影响。

**Comment by swxk521** [comment]
> > > > sing-box 数据结构清晰，且DNS模块完善。 目前passwall2差不多完成。https://github.com/xiaorouji/openwrt-passwall2/tree/singbox-dev
> > > 
> > > 
> > > 期待在passwall上实现，喜欢passwall2的简洁，不过我使用passwall2一切换节点或者保存应用设置游戏就断线，passwall则没有这个问题。
> > 
> > 
> > 现在变成了用sock5切换节点，不会说切换节点，会断线，除非是要科学的游戏。看大佬意思是sing-box为主了，passwall2更新应该比较快。
> 
> 并非是需要科学的游戏，我默认直连，仅代理需要代理的网络，就这样切换节点都会掉线，玩游戏的时候更改下设置都不敢。后来换了passwall就行了，随便更改设置，更新订阅，切换节点，无任何影响。

新版改了啊，除非你重启主程序，会断线，利用SOCK5自动换节点并不会断线。

**Comment by gg4924** [comment]
> 新版改了啊，除非你重启主程序，会断线，利用SOCK5自动换节点并不会断线。

我昨天就用新版试过啊，因为看见更新了说试试，一样断线，手动切换分流节点断线，保存更改设置断线。我两个游戏，1个游戏开1个不会断，多开就会掉线其中1个，偶尔不掉，另外一个游戏一切就断，都是不需要科学的游戏。

**Comment by swxk521** [comment]
> 



> 



> > 新版改了啊，除非你重启主程序，会断线，利用SOCK5自动换节点并不会断线。
> 
> 我昨天就用新版试过啊，因为看见更新了说试试，一样断线，手动切换分流节点断线，保存更改设置断线。我两个游戏，1个游戏开1个不会断，多开就会掉线其中1个，偶尔不掉，另外一个游戏一切就断，都是不需要科学的游戏。

手动的话确实会断线，但是一般设置好的话，没必要一直手动搞，自动切换并不会断直连的游戏，passwall2现在快完善了。看自己选择吧。

**Comment by gg4924** [comment]
> > 
> 
> > 
> 
> > > 新版改了啊，除非你重启主程序，会断线，利用SOCK5自动换节点并不会断线。
> > 
> > 
> > 我昨天就用新版试过啊，因为看见更新了说试试，一样断线，手动切换分流节点断线，保存更改设置断线。我两个游戏，1个游戏开1个不会断，多开就会掉线其中1个，偶尔不掉，另外一个游戏一切就断，都是不需要科学的游戏。
> 
> 手动的话确实会断线，但是一般设置好的话，没必要一直手动搞，自动切换并不会断直连的游戏，passwall2现在快完善了。看自己选择吧。

恩，我现在用passwall挺好，还没碰到问题。我一般是不会更改设置的，节点分流设置好了基本不变，只是测试下，passwall2玩游戏有不太踏实的感觉。

**Comment by luckmc** [comment]
期待passwall可以用sing-box

**Comment by Terutoki** [comment]
Juicity会启动一个Socks的，可以临时用Socks对接一下

<img width="599" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/b36aefb8-f89a-45df-a8f6-2b2679aeb6e6">
