### ISSUE TITLE
[Bug]: vless grpc REALITY 协议可用性测试

### ISSUE THREAD

**Issue by swxk521** [xiaorouji/openwrt-package#2732]
### 描述您遇到的bug

vless grpc REALITY 和vless h2 REALITY 协议可用性测试超时，无法使用，实际使用没问题。
会导致节点自动切换。希望大佬修复一下
找了一下，不知道这个能不能解决问题，大佬看看
https://github.com/xiaorouji/openwrt-passwall/issues/1303

### 复现此Bug的步骤

同上

### 您想要实现的目的

同上

### 日志信息

同上

### 系统相关信息

最新版

**Comment by handsomeji** [comment]
可用性测试超时应该是不能用才对，确认能用？

**Comment by swxk521** [comment]
确认能用，手机端nekobox没问题.,有机场和自己建的都超时，但奇怪的是设置为udp节点，sock5转的，udp没问题，设置为tcp节点还是超时
