### ISSUE TITLE
[Bug]: hysteria、v2ray-plugin、brook报错－openwrt23.05

### ISSUE THREAD

**Issue by ted-zheng** [xiaorouji/openwrt-package#2734]
### 描述您遇到的bug

编译过程中hysteria、v2ray-plugin、brook三项报错，无法编译成功，8月27日还成功编译过。

### 复现此Bug的步骤

使用make clean，make dirclean，rm -rf ./tmp清理后问题仍然存在

### 您想要实现的目的

顺利通过编译

### 日志信息

make[3] -C package/system/mtd compile
 make[3] -C package/network/ipv6/odhcp6c compile
 make[3] -C package/system/urngd compile
 make[3] -C package/libs/libbpf compile
 make[3] -C package/utils/busybox compile
 make[3] -C package/system/ubox compile
 make[3] -C package/utils/ucode compile
 make[3] -C package/network/config/netifd compile
 make[3] -C feeds/packages/net/cgi-io compile
 make[3] -C package/network/utils/iwinfo compile
 make[3] -C package/network/services/odhcpd compile
 make[3] -C feeds/packages/libs/boost compile
 make[3] -C feeds/packages/net/haproxy compile
 make[3] -C package/libs/uclient compile
    ERROR: package/feeds/kenzo/hysteria failed to build.
    ERROR: package/feeds/kenzo/v2ray-plugin failed to build.
    ERROR: package/feeds/passwall/brook failed to build.
 make[4] scripts/config/conf
^Cmake: *** [/home/udb/openwrt/include/toplevel.mk:232: world] 中断

### 系统相关信息

固件源：https://github.com/openwrt/openwrt.git，main分支

### 其他信息

feed 源：
src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
#src-git video https://github.com/openwrt/video.git
#src-git targets https://github.com/openwrt/targets.git
#src-git oldpackages http://git.openwrt.org/packages.git
#src-link custom /usr/src/openwrt/custom-feed
src-git kenzo https://github.com/kenzok8/small
src-git passwall https://github.com/xiaorouji/openwrt-passwall

**Comment by Gzxhwq** [comment]
如无意外是这几个还没有适配 Go 1.21，只能等上游更新了。

**Comment by microdockman** [comment]
https://github.com/microdockman/packages_golang

这个是替换过的，用的  https://github.com/coolsnowwolf/packages  换的，只换了https://github.com/coolsnowwolf/packages/tree/master/lang/golang 这个文件夹，

现在编译正常，官方是1.21
换成1.20的就可以了
