### ISSUE TITLE
[Bug]: 已订阅节点无法删除

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#2735]
### 描述您遇到的bug

拉取最新4.69-2-smartdns-dev-brach编译的固件无法删除已订阅节点
同时更新订阅出现“ /usr/share/passwall/subscribe.lua:1271: attempt to index upvalue 'debug' (a boolean value)”报错

### 复现此Bug的步骤

更新及删除节点

### 您想要实现的目的

修复bug

### 日志信息

见上

### 系统相关信息

4.69-2-smartdns-dev-brach

**Comment by SakuraFallingMad** [comment]
luci分支也有类似错误。节点订阅的已订阅节点删除按钮功能失常。
