### ISSUE TITLE
自动切换有问题

### ISSUE THREAD

**Issue by woni928** [xiaorouji/openwrt-package#2739]
### 描述你想要的新功能

希望恢复到原来位置，并能正常使用。

### 描述你想要的解决方案

自从自动切换更好位置后，我就没有成功过。

### 描述你考虑过的替代方案

希望恢复到原来位置

**Comment by woni928** [comment]
<img width="981" alt="1" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/061b1ef2-c7cf-4624-8967-2a5aa56aa18c">
<img width="792" alt="2" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/a18b0bf4-51ee-44d5-9c1e-98deb0707c31">
<img width="1090" alt="3" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/e1c4c409-74a7-479a-a4b9-d68ae6dbff0f">
4.69-4 
问题：切换完成，但是无法翻墙！！

**Comment by handsomeji** [comment]
都说了你用法有问题，你创建了个socks又怎样？TCP节点又没有使用它！

**Comment by woni928** [comment]
> 都说了你用法有问题，你创建了个socks又怎样？TCP节点又没有使用它！

那应该怎么设置才是正确的？给个图文教程吧，谢谢。也参考其了他人的设置但就是不成功。

**Comment by handsomeji** [comment]
创建个节点，Xray + socks 类型，地址为127.0.0.1，端口为1081。然后TCP使用该节点

**Comment by woni928** [comment]
> 创建个节点，Xray + socks 类型，地址为127.0.0.1，端口为1081。然后TCP使用该节点

<img width="1094" alt="1" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/e423565f-4cd5-4a85-a1d4-8f93a08fbd94">

哎 折腾了半天 原来是姿势不对 非常感谢！
原来的位置又直接又明显，为什么要换地方？

**Comment by handsomeji** [comment]
原来的只针对于TCP节点，不够灵活。不能满足我的需求，现在更利于扩展，而且支持多个socks

**Comment by woni928** [comment]
多个Socks怎么玩？

**Comment by Rain113113** [comment]
> 1081

用户名和密码填什么 还是不填  大哥

**Comment by ryeqaq** [comment]
请问使用socks切换以后我使用socks代理端口输入1070还是1081呢

**Comment by tanst** [comment]
分流节点是不是用不了
