### ISSUE TITLE
[Bug]: 无法安装hysteria

### ISSUE THREAD

**Issue by barney2022** [xiaorouji/openwrt-package#2745]
### 描述您遇到的bug

hysteria未安装，但是点击更新以后提示已是最新版本

### 复现此Bug的步骤

1.点击组件更新
2.点击hysteria检查更新
出现情况：hysteria 【无】已是最新版本

### 您想要实现的目的

修复BUG

### 日志信息

111

### 系统相关信息

Passwall 版本【 git-24.246.56158-2d38f4e 】 
Microsoft Edge 版本 116.0.1938.69 (正式版本) (64 位)

**Comment by Recoba86** [comment]
I Have This Problem Too and cant Install Hysteria v2

**Comment by handsomeji** [comment]
Hysteria2 和 1 有点区别，暂未更新逻辑。

**Comment by A1s2xD** [comment]
Same problem

**Comment by baiguke2019** [comment]
下次不手贱 点更新了
