### ISSUE TITLE
[Bug]: 最新版编译后无法使用

### ISSUE THREAD

**Issue by small-white-rabbit** [xiaorouji/openwrt-package#2746]
### 描述您遇到的bug

使用最新版的openwrt 5.15.130 内核 编译最新版hysteria2.0 ，更新到路由器上后，所有面板状态正常，但是无法正常链接外网，国内网络不影响

### 复现此Bug的步骤

更新固件后打开passwall 

面板状态正常

日志正常

但是无法联通外网

### 您想要实现的目的

是否需要修改添加什么才能正常运行？

### 日志信息

无

### 系统相关信息

最新版passwall hysteria2.0版本

**Comment by handsomeji** [comment]
Hysteria2 和 1 有点区别，暂未更新逻辑。
