### ISSUE TITLE
language: 

### ISSUE THREAD

**Issue by ayanagroup-official** [xiaorouji/openwrt-package#2747]
### 描述你想要的新功能

how to change language to english?

i can't read "WATCH LOGS"

### 描述你想要的解决方案

![image](https://github.com/xiaorouji/openwrt-passwall/assets/94752371/7b797f9e-0fed-46f0-bad7-c145ad475031)

**Comment by rayhanbone** [comment]
![Clipboard-1](https://github.com/xiaorouji/openwrt-passwall/assets/91767844/b6576e43-ba14-424e-ba77-5e5b4d34cedd)
No problem for me

**Comment by ayanagroup-official** [comment]
> ![Clipboard-1](https://user-images.githubusercontent.com/91767844/266365090-b6576e43-ba14-424e-ba77-5e5b4d34cedd.png) No problem for me

How to

**Comment by smallprogram** [comment]
> ![Clipboard-1](https://user-images.githubusercontent.com/91767844/266365090-b6576e43-ba14-424e-ba77-5e5b4d34cedd.png) No problem for me

How to ????

**Comment by smallprogram** [comment]
@ayanagroup-official 
why close？
