### ISSUE TITLE
[Bug]: ImmortalWrt OpenWRT 23.05分支的  Passwall版本 4.69-4    Socks自动切换功能无效

### ISSUE THREAD

**Issue by laaArmy** [xiaorouji/openwrt-package#2748]
### 描述您遇到的bug

 Socks自动切换功能无效

### 复现此Bug的步骤

创建一个Socks节点，然后添加自己的梯子，并且设定自动切换
主节点指向上面

都是Passwall+MosDNS
ImmortalWrt OpenWRT 23.05分支编译的  Passwall版本 4.69-4  无效果，日志没有任何异常提示，但此时主节点服务器我已经关闭了

朋友的n1   openwrt.ai最新版的，同样的设置，却有效果，主节点服务器关闭后会自动切换
唯一不同的是我家是电信+移动，利用负载均衡指定了部分节点的WAN出口
如图
或许是需要什么依赖？？？？

### 您想要实现的目的

是BUG呢，还是说缺少了某个依赖？？？

### 日志信息

日志没有节点异常提示，空的

### 截图

![QQ截图20230907165047](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/d50e6029-fed5-454c-8ce6-27f9d8f416bc)
![QQ图片20230907165128](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/fe1fbf4e-48c9-4cd1-86f4-98aef16fd80f)
![QQ图片20230907165700](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/fc222542-4878-4985-ac67-c6f1237a4986)
![QQ图片20230907165736](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/fff681d2-c36c-47fa-9c23-08928e7558ea)

### 系统相关信息

Passwall 版本
【 4.69-4 】

**Comment by handsomeji** [comment]
输入下面命令看看：
`command -v curl`

`curl -I -o /dev/null -skL --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" -x "socks5h://127.0.0.1:1081" --connect-timeout 10 --retry 1 -w %{http_code} https://www.google.com/generate_204`

**Comment by laaArmy** [comment]
> command -v curl

输入第一条吗？
什么也没啊
![QQ截图20230907205330](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/93072cd6-8c10-4945-9b08-d84da436c048)

**Comment by handsomeji** [comment]
200或204状态码证明节点是正常的

**Comment by laaArmy** [comment]
> 200或204状态码论证是正常的

哦哦，明白你意思了
关闭节点
![QQ截图20230907210101](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/dab24d3b-c25f-46f3-a05c-4ea9d627275b)
![QQ截图20230907210134](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/38131aa0-204c-4c48-9c45-230a58dd8a2d)
![QQ截图20230907210208](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/4f0b3d8b-6223-4aa8-9c72-f41d88664449)

**Comment by handsomeji** [comment]
`top -bn1 | grep -v grep | grep passwall/ | grep "socks_auto_switch"`
`ls -l /usr/share/passwall`

**Comment by laaArmy** [comment]
> `top -bn1 | grep -v grep | grep passwall/ | grep "socks_auto_switch"` `ls -l /usr/share/passwall`

![QQ截图20230907210714](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/5b994c74-7453-446a-8cf9-b8767b366a3a)

**Comment by handsomeji** [comment]
自动切换脚本没有启动。为什么没有权限？
`chmod +x /usr/share/passwall/socks_auto_switch.sh`
`/etc/init.d/passwall restart`
然后再试试看

**Comment by laaArmy** [comment]
> ls -l /usr/share/passwall

可以了
![QQ截图20230907211054](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/b4c76a5f-36e9-485c-8f1b-6d9193453c77)
![QQ截图20230907211210](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/d20fb994-3282-4203-97c4-cb18d715135a)

**Comment by laaArmy** [comment]
[.config.txt](https://github.com/xiaorouji/openwrt-passwall/files/12549469/default.config.txt)

**Comment by laaArmy** [comment]
> 自动切换脚本没有启动。为什么没有权限？ `chmod +x /usr/share/passwall/socks_auto_switch.sh` `/etc/init.d/passwall restart` 然后再试试看

master和openwrt23.05编译的都是这样
干干净净拉源码编译的
今天刚刷，配置好没多久，上面那个文件是我编译的配置文件，希望能提供到帮助

**Comment by handsomeji** [comment]
你是手动拖的源码？
不是用git clone？

**Comment by laaArmy** [comment]
> 你是手动拖的源码？
> 不是用git clone？

git clone拖的,imm github底下有个编译教程，就是用那个

我双线宽带，电信开了负载均衡让节点指向移动那边
估计负载均衡有BUG，间歇性断网，必须得重新开启一下passwall

**Comment by SakuraFallingMad** [comment]
imm那里的Passwall是我搬运过去的，好像也发现socks_auto_switch.sh没有+x

**Comment by laaArmy** [comment]
> imm那里的Passwall是我搬运过去的，好像也发现socks_auto_switch.sh没有+x

而且我用负载均衡，只能指定WAN出口了，对应的WAN出口挂了还不能切换别的WAN，也是开了这功能后，会间歇性断网
不知道是否也是对应脚本没有权限的原因？

**Comment by wtfr-dot** [comment]
用了mwan3没有？如果用了mwan3并且使用nft的话passwall会出现问题

**Comment by laaArmy** [comment]
> 用了mwan3没有？如果用了mwan3并且使用nft的话passwall会出现问题

没

问题大概解决了，负载均衡的脚本也没权限

**Comment by SakuraFallingMad** [comment]
我原封搬运的，不太清楚为何没权限 @xiaorouji，求助

**Comment by handsomeji** [comment]
因为你不是linux并且不是git操作的

**Comment by laaArmy** [comment]
> 我原封搬运的，不太清楚为何没有权限@xiaorouji，求助

你是怎么编译的？我是WSL

**Comment by SakuraFallingMad** [comment]
> > 我原封搬运的，不太清楚为何没有权限@xiaorouji，求助
> 
> 你是怎么编译的？我是WSL

我理解他的意思了，我修改immortalwrt那里的，会修复

**Comment by laaArmy** [comment]
> > > 我原封搬运的，不太清楚为何没有权限@xiaorouji，求助
> > 
> > 你是怎么编译的？我是WSL
> 
> 我理解他的意思了，我修改immortalwrt那里的，会修复

大佬，我负载均衡那边的1181进不去，你看看是不是也是这个原因

**Comment by SakuraFallingMad** [comment]
> > > > 我原封搬运的，不太清楚为何没有权限@xiaorouji，求助
> > > 
> > > 
> > > 你是怎么编译的？我是WSL
> > 
> > 
> > 我理解他的意思了，我修改immortalwrt那里的，会修复
> 
> 大佬，我负载均衡那边的1181进不去，你看看是不是也是这个原因

应该是的haproxy_check.sh确实缺执行权限

**Comment by laaArmy** [comment]
> > > > > 我原封搬运的，不太清楚为何没有权限@xiaorouji，求助
> > > > 
> > > > 
> > > > 你是怎么编译的？我是WSL
> > > 
> > > 
> > > 我理解他的意思了，我修改immortalwrt那里的，会修复
> > 
> > 
> > 大佬，我负载均衡那边的1181进不去，你看看是不是也是这个原因
> 
> 应该是的haproxy_check.sh确实缺执行权限

给了权限再重启固件也进不去
