### ISSUE TITLE
[Bug]: enable and disable sniffing in Xray Settings

### ISSUE THREAD

**Issue by rivandraa** [xiaorouji/openwrt-package#2749]
### 描述您遇到的bug

An error message occurs when enabling or disabling sniffing in Xray Settings

### 复现此Bug的步骤

1. Go to other settings
2. enable or disable sniffing in Xray Settings
3. save

### 您想要实现的目的

-

### 日志信息

-

### 截图

![Screenshot_1](https://github.com/xiaorouji/openwrt-passwall/assets/139041404/da3d17fb-d226-4b2e-8e0d-9b6933261942)

### 系统相关信息

passwall 4.70-2
OpenWrt 23.05.0-rc3 

### 其他信息

-

**Comment by handsomeji** [comment]
The next version will fix.

**Comment by handsomeji** [comment]
try the latest version
