### ISSUE TITLE
[Bug]: 使用sing-box时，tuic协议无法正确的配置拥塞算法和中继模式 

### ISSUE THREAD

**Issue by kentooo** [xiaorouji/openwrt-package#2752]
### 描述您遇到的bug

使用sing-box时，tuic协议无法正确的配置拥塞算法和中继模式，
在luci中进行配置，选择拥塞算法和中继模式之后，保存配置会将这两项的配置重置为默认选项

同时在/etc/config/passwall文件中，没有相应的option条目，配置文件内容如下
```
config nodes 'xxxxxxxx'
	option remarks 'server name'
	option type 'sing-box'
	option protocol 'tuic'
	option address 'server.address'
	option port '1234'
	option password 'password'
	option uuid '12345678-1234-1234-1234-123456781234'
	option tls_serverName 'tls.server.name'
```

### 复现此Bug的步骤

1. 添加node，选择sing-box/tuic
2. 填写各字段
3. 保存并应用/保存
4. [bug]拥塞算法和中继模式选项会被重置
5. 使用添加的tuic节点，无法连接

### 您想要实现的目的

能够正确的配置sing-box/tuic节点，并成功连接和使用节点

### 日志信息

日志一切正常

### 系统相关信息

openwert-23.05_rc3 (x86_64)
passwall: 4.70-2

**Comment by handsomeji** [comment]
下个版本将会修复

**Comment by bi4tms** [comment]
> 下个版本将会修复

大佬请问新的sing-box对比xray优势在什么地方

**Comment by handsomeji** [comment]
试一下最新的版本

**Comment by kentooo** [comment]
> 试一下最新的版本

嗯，新版已经正常了
