### ISSUE TITLE
[Feature Request]: sing-box

### ISSUE THREAD

**Issue by wintekk** [xiaorouji/openwrt-package#2753]
### 描述你想要的新功能

能否提供一下sing-box依赖文件的ipk，升级时提示缺少依赖文件
![IMG_0019](https://github.com/xiaorouji/openwrt-passwall/assets/32199008/968b47b2-7873-4fea-afb7-83e1b6db2e90)

### 描述你想要的解决方案

提供一个sing-box依赖文件的ipk

**Comment by code777tsu** [comment]
@wintekk  解决方法：请到  https://op.dllkids.xyz/    网站，找到自己的cpu型号进如package搜索缺失的依赖（例如sing-box），先自行安装依赖，再使用iStore安装本体。

**Comment by MiKing233** [comment]
> 

所以爲何不直接提供sing-box的ipk文件, 明明Packages Version裏面都有
<html>
<body>


🧊 sing-box | 1.3.6
-- | --



</body>
</html>

**Comment by handsomeji** [comment]
@smallprogram 自动编译actions炸了，看看修一下

**Comment by smallprogram** [comment]
> @smallprogram 自动编译actions炸了，看看修一下

嗯，我再看看

**Comment by donnyxray** [comment]
Please consider making such dependencies optional. Many of us don't need or want sing-box anyway. It just takes space.

**Comment by smallprogram** [comment]
> Please consider making such dependencies optional. Many of us don't need or want sing-box anyway. It just takes space.

make menuconfig

**Comment by smallprogram** [comment]
Fixed
@xiaorouji 老大，是否可以将packages与luci独立成两个repository,这样我感觉更好一点

**Comment by smallprogram** [comment]
@xiaorouji 老大我有点强迫症，能否这样：
将passwall1的库命名为openwrt-passwall

**Comment by manbowuhao** [comment]
安装 4.70-4(OpenWrt 22.03.5)
正在执行软件包管理器
Package luci-app-passwall (4.69-4) installed in root is up to date.
错误
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall
下载的Packages Version依赖包里也没有看到这个依赖（sing-box）请问老大怎么解决

**Comment by smallprogram** [comment]
> 安装 4.70-4(OpenWrt 22.03.5)
> 
> 正在执行软件包管理器
> 
> Package luci-app-passwall (4.69-4) installed in root is up to date.
> 
> 错误
> 
> Collected errors:
> 
>  * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall
> 
> 下载的Packages Version依赖包里也没有看到这个依赖（sing-box）请问老大怎么解决

昨天更的workflow。没更新版本。等下一个passwall版本更新后就有了
