### ISSUE TITLE
[Feature Request]: add balancing protocol on sing-box

### ISSUE THREAD

**Issue by rivandraa** [xiaorouji/openwrt-package#2755]
### 描述你想要的新功能

add balancing protocol to sing-box

### 描述你想要的解决方案

I want to use 2 or more proxies on sing-box to balance the load, sing-box can't find a balancing protocol like the xray

### 描述你考虑过的替代方案

current alternative, I have to use balancing protocol on xray

### 其他信息

![IMG_20230908_074514_721](https://github.com/xiaorouji/openwrt-passwall/assets/139041404/b86da7e0-851b-4eb7-b1d8-f5642af7616e)

Add this protocol on sing-box

**Comment by Gzxhwq** [comment]
sing-box 自身并不支持 load balance
