### ISSUE TITLE
[Bug]: 使用sing-box时，VELSS的xtls-rprx-vision无法正确生成配置

### ISSUE THREAD

**Issue by smy116** [xiaorouji/openwrt-package#2756]
### 描述您遇到的bug

使用sing-box时，在webui的flow选择xtls-rprx-vision，保存后运行，在/tmp/etc/passwall/下生成的json配置文件漏了flow这个参数，导致无法正常连接服务器。

### 复现此Bug的步骤

在webui的flow选择xtls-rprx-vision，保存后运行

### 您想要实现的目的

无。

### 日志信息

无。

### 截图

![截图_20230908091516](https://github.com/xiaorouji/openwrt-passwall/assets/7192700/ee7fe149-605e-475c-9bc0-55d963a992ed)
![截图_20230908091908](https://github.com/xiaorouji/openwrt-passwall/assets/7192700/5fe0fb58-7404-4ba5-94bc-950c56c9d9bc)

### 系统相关信息

Passwall版本：4.70-2

**Comment by Travel2Here** [comment]
singbox的分流能用吗？我死活不行 配上后都启动不起来APP

**Comment by hcym** [comment]
分流哪里还是选择xray，节点类型可以用box，感觉没什么本质区别，就是wireguard可以用了，原来死活不能用，泪流满面，

**Comment by smy116** [comment]
> singbox的分流能用吗？我死活不行 配上后都启动不起来APP

可以的

**Comment by Travel2Here** [comment]
> 分流哪里还是选择xray，节点类型可以用box，感觉没什么本质区别，就是wireguard可以用了，原来死活不能用，泪流满面，

我主场景总分流和节点类型都只能是原本的xray，换成sb的不行。
只有单节点是sb，部分协议能通，比如ss vless这类，像socks 分流等协议都不通…

**Comment by jxph1123** [comment]
xray的负载均衡测速，sing-box是不是也不行哇

**Comment by handsomeji** [comment]
试下最新的版本

**Comment by smy116** [comment]
> 试下最新的版本

4.70-3版本已测试可用。谢谢
