### ISSUE TITLE
[Bug]: 关于sb的一些测试

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#2758]
### 描述您遇到的bug

DNS选sb的doh会导致无法连接

### 复现此Bug的步骤

同上

### 您想要实现的目的

我也不知道为什么，用dns2socks或者别的dns服务一直会导致Disney Plus有点怪怪的，以前一直使用xray的doh就相安无事，但如果主线路core换成sing的话是无法独立使用xray的doh的对吧，换成sb的doh也无法连接所以……

### 日志信息

好像不需要提供…吧？

### 系统相关信息

4.70-2

**Comment by handsomeji** [comment]
试下最新的版本

**Comment by jh0072110** [comment]
感谢大佬，已修复
