### ISSUE TITLE
[Feature Request]: Passwall什么时候能增加Hysteria2协议的支持

### ISSUE THREAD

**Issue by ho1003** [xiaorouji/openwrt-package#2762]
### 描述你想要的新功能

Passwall什么时候能增加Hysteria2协议的支持

### 描述你想要的解决方案

Passwall什么时候能增加Hysteria2协议的支持

### 描述你考虑过的替代方案

Passwall什么时候能增加Hysteria2协议的支持

### 其他信息

Passwall什么时候能增加Hysteria2协议的支持

**Comment by Gzxhwq** [comment]
已经通过sing-box支持了

**Comment by manhuaxian** [comment]
请问为什么很多节点在小火箭上显示是通的，在passwall上显示的却是不通；另外，hy2节点是不是只支持手搓，没法订阅啊，我用订阅链接，提示不支持hy2，确定是最新版啊。
2023-10-04 15:29:27: 暂时不支持hysteria2类型的节点订阅，跳过此节点。
Sing-Box 版本【 1.6.0-alpha.2 】

**Comment by haohaoget** [comment]
> 请问为什么很多节点在小火箭上显示是通的，在passwall上显示的却是不通；另外，hy2节点是不是只支持手搓，没法订阅啊，我用订阅链接，提示不支持hy2，确定是最新版啊。 2023-10-04 15:29:27: 暂时不支持hysteria2类型的节点订阅，跳过此节点。 Sing-Box 版本【 1.6.0-alpha.2 】

我现在最新版Hysteria 版本 【 v2.2.0 】Sing-Box 版本 【 1.7.0-alpha.3 】订阅仍然提示：暂时不支持hysteria2类型的节点订阅，跳过此节点。
请求支持订阅
