### ISSUE TITLE
[Feature Request]: 添加节点时，希望可以隐藏未安装对应核心的类型选项

### ISSUE THREAD

**Issue by sbwml** [xiaorouji/openwrt-package#2763]
### 描述你想要的新功能

各位开发大佬好，我在构建 luci-app-passwall 时，`Brook`、`Hysteria`、`Trojan-Go` 这三个核心均未选中，但我在添加节点时却能看到这三个类型的选项，请问这是预期行为吗？

我的包列表：https://r5s.cooluc.com/releases/openwrt-23.05/v23.05.0-rc3/manifest.txt?preview

![1](https://github.com/xiaorouji/openwrt-passwall/assets/16485166/a6aeaf8a-ad5d-4a7c-bb20-fe78d3e8655b)

![2](https://github.com/xiaorouji/openwrt-passwall/assets/16485166/2aa919b4-98fe-47a9-bc82-01404b8fd144)

### 描述你想要的解决方案

如果这是预期行为，请问大佬们可以修改让其仅显示已安装的核心对应的类型选项吗？因为添加一个核心不存在的类型时，它是不可能工作的，这可能会错误引导一些不太熟悉该插件的小白们。

**Comment by sbwml** [comment]
cc @xiaorouji

**Comment by swxk521** [comment]
passwall2有同样问题，另外提议，sing-box已经集成hysteria和tuic，测试hy hy2 tuic都正常使用
可以考虑移除相关插件，用sing-box

**Comment by JSZMonkey** [comment]
新版本订阅更新 vmess 节点的时候 默认协议都自动选择 sing-box 导致节点无法使用，请修复

**Comment by alterem** [comment]
新版本订阅更新 vmess 节点的时候 默认协议都自动选择 sing-box 导致节点无法使用，请修复

**Comment by xcyll** [comment]
补充下：目前切到sing-box使用了 使用时发现
未安装xray情况下 在高级设置里仍然有Xray的设置

![2023-09-09 200628](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/4549911e-ec71-4ea5-8688-f5f7713fc9f1)

**Comment by xcyll** [comment]
另新加的Sing-box对应的geoip & geosite如何更新啊@xiaorouji

**Comment by handsomeji** [comment]
已修复，感谢反馈
