### ISSUE TITLE
[Bug]: 全部采用sing-box发现的两点问题~

### ISSUE THREAD

**Issue by jxph1123** [xiaorouji/openwrt-package#2765]
### 描述您遇到的bug

1.我全部用了sing-box节点，然后开haproxy负载均衡，为啥还有`xray run -c /tmp/etc/passwall/SOCKS_TCP.json`，这是正常的吗？求教。
2.自动订阅`Trojan节点使用类型`选择了`sing-box`，但是部分节点还是识别成xray taojan节点。如下图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/36df8f4c-3ed1-4996-92d9-6687451b0ec2)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/d809b751-36ca-4533-8b22-502acf8bdd88)

```
 1992     1 root     S     716m 173%   1% /tmp/etc/passwall/bin/sing-box run -c /tmp/etc/passwall/haproxy_gHSpyZe0_2084.json
   12     2 root     SW       0   0%   1% [ksoftirqd/0]
 2031     1 root     S    34516   8%   1% /tmp/etc/passwall/bin/haproxy -f /tmp/etc/passwall/haproxy/config.cfg
 2127     1 root     S     1000   0%   0% /tmp/etc/passwall/bin/ipt2socks_TCP_UDP -l 1041 -b 0.0.0.0 -s 127.0.0.1 -p 1181 -R -v
 2338     1 root     S    26444   6%   0% /usr/sbin/smartdns -f -c /var/etc/smartdns/smartdns.conf
 1297     2 root     SW       0   0%   0% [napi/-13]
 1282     2 root     SW       0   0%   0% [napi/-6]
 1294     2 root     SW       0   0%   0% [napi/-10]
 1292     2 root     SW       0   0%   0% [napi/-8]
 2238  2168 network  S     6704   2%   0% /usr/sbin/hostapd -s -g /var/run/hostapd/global
 1299     2 root     SW       0   0%   0% [napi/-15]
 1300     2 root     SW       0   0%   0% [napi/-16]
 1291     2 root     SW       0   0%   0% [napi/-7]
30837 30724 root     R     1292   0%   0% top
31926     2 root     IW       0   0%   0% [kworker/u8:1-ev]
 2172     1 root     S     720m 174%   0% /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/SOCKS_TCP.json
 1707     1 root     S     716m 173%   0% /tmp/etc/passwall/bin/sing-box run -c /tmp/etc/passwall/haproxy_9x3G8zxT_2083.json
 1425     1 root     S     716m 173%   0% /tmp/etc/passwall/bin/sing-box run -c /tmp/etc/passwall/haproxy_DmLcBIzs_2082.json
```

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/4ae6b9a4-3afa-4a75-bd07-d8aa0bfb9b5c)

**Comment by handsomeji** [comment]
是否订阅配置里面没有使用Sing-Box？

**Comment by jxph1123** [comment]
> 是否订阅配置里面没有使用Sing-Box？


 设置了的，很奇怪，部分Trojan能变成Sing-Box，部分还是xray。

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/bc57366a-82f1-4169-aeaf-ae00061ddb34)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/50094b91-9f68-4d98-aafc-ecd5ac0cc6cd)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/8f91d9fd-05ae-4d0c-90bb-b3a522d727e7)

**Comment by jxph1123** [comment]
> 是否订阅配置里面没有使用Sing-Box？

又重新编译了，订阅正常了。不过还是有xray在运行。
