### ISSUE TITLE
[Bug]: The vmess node is recognized as a sing-box, causing the node to become unusable.

### ISSUE THREAD

**Issue by alterem** [xiaorouji/openwrt-package#2766]
### 描述您遇到的bug

The vmess node is recognized as a sing-box, causing the node to become unusable.

When the new version subscribes to update the vmess node, the default protocol automatically selects sing-box, causing the node to be unusable. Please fix it.

### 复现此Bug的步骤

resubscribe

### 您想要实现的目的

Node is in normal use

### 日志信息

none

### 截图

<img width="743" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/16953053/f804d930-397d-4423-abe9-225bd6ddb881">
<img width="747" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/16953053/8e2b8ab8-bbe6-4dd4-8004-7111c6bfc7c1">

### 系统相关信息

<img width="747" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/16953053/3316d02e-72f9-4f94-ad24-b8be0b31417e">

**Comment by xiaorouji** [comment]
I don't have vmess node now. If you can, please provide a node.
send to xiaoroujixxoo@gmail.com

**Comment by alterem** [comment]
> I don't have vmess node now. If you can, please provide a node. send to [xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

Have you received it?

**Comment by sjcta** [comment]
同样vmess的订阅地址全部被识别成sing-box协议了，无法直接使用，需要订阅后手动一个一个改成vmess协议后才能使用……

**Comment by xiaorouji** [comment]
[util_sing-box.zip](https://github.com/xiaorouji/luci-app-passwall/files/12569496/util_sing-box.zip)
把此文件解壓後講lua文件覆蓋到路由器/usr/share/passwall/裡面，然後再試試看

**Comment by sjcta** [comment]
测试结果如下：
A. 老版本(4.69)中已经导入的xray vmess协议的机场节点信息，在更新4.70后，节点列表中虽然显示V2ray类型，但编辑节点后，类型标记成了socks。
B. 4.70版本中新导入的机场v2ray节点或vmess协议的节点信息依然被标记成 Sing-box类型Vmess协议，无法直接使用

> [util_sing-box.zip](https://github.com/xiaorouji/luci-app-passwall/files/12569496/util_sing-box.zip) 把此文件解壓後講lua文件覆蓋到路由器/usr/share/passwall/裡面，然後再試試看

**Comment by alterem** [comment]
> [util_sing-box.zip](https://github.com/xiaorouji/luci-app-passwall/files/12569496/util_sing-box.zip) 把此文件解壓後講lua文件覆蓋到路由器/usr/share/passwall/裡面，然後再試試看

It still needs to manually modify the node type to Xray to use it normally, because it is still recognized as sing-box.

**Comment by handsomeji** [comment]
I know xray can be used, but the problem to solve now is use vmess with sing-box.

**Comment by alterem** [comment]
> I know xray can be used, but the problem to solve now is use vmess with sing-box.

Yes, but I don't know if it has anything to do with the service provider.

**Comment by alterem** [comment]
4.70-5 seems to have fixed this issue

**Comment by alterem** [comment]
@xiaorouji thk U
