### ISSUE TITLE
[Bug]:luci-app-passwall安装过程中的报错 

### ISSUE THREAD

**Issue by kentooo** [xiaorouji/openwrt-package#2767]
### 描述您遇到的bug

安装过程中出现报错

```
/usr/share/passwall/app.sh: eval: line 246: -local_http_port: not found
/usr/share/passwall/app.sh: eval: line 246: 2087: not found
```

### 复现此Bug的步骤

opkg install luci-app-passwall

### 您想要实现的目的

如果有可能，修正错误比较好，虽然目前没有影响使用

### 日志信息

无

### 系统相关信息

passwall: 4.70-4
openwrt: 23.05_rc3

**Comment by handsomeji** [comment]
Fix.
