### ISSUE TITLE
[Bug]: 订阅不上啊singbox

### ISSUE THREAD

**Issue by mmeiwenlong** [xiaorouji/openwrt-package#2769]
### 描述您遇到的bug

如图

### 复现此Bug的步骤

如图

### 您想要实现的目的

那那那那那那能用

### 日志信息

如图

### 截图

![QQ截图20230910150405](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/04a362f6-ed95-47c3-ba96-5bbe2ac551c2)
![QQ截图20230910150722](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/7b2a157c-f480-429b-aa05-35d1009fbd39)

### 系统相关信息

如图

**Comment by handsomeji** [comment]
dler ? 
用smart的那個

**Comment by mmeiwenlong** [comment]
> dler ? 
> 用smart的那個

用这个也是一样提示，不知哪里问题，![Screenshot_2023-09-11-20-11-09-248_com.android.chrome.jpg](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/94be947e-7bb2-4541-9616-28ec361c9c89)

**Comment by handsomeji** [comment]
就用通用的订阅地址
