### ISSUE TITLE
sing-box的shadowtls用法不对

### ISSUE THREAD

**Issue by Gzxhwq** [xiaorouji/openwrt-package#2776]
@xiaorouji 

shadowtls是双outbound的，现在生成的配置只有shadowtls一个outbound

https://sing-box.sagernet.org/examples/shadowtls/#client

**Comment by handsomeji** [comment]
照着文档出站设计的，我并未实际使用过。

**Comment by Gzxhwq** [comment]
sing-box有官方示例的，就是上面那个，你可以看看。我改了半天改不动了，要改的地方有点多。

![图片](https://github.com/xiaorouji/openwrt-passwall/assets/8738520/c49efbe7-152b-4531-8a10-4cd5033e039e)

**Comment by bbswww** [comment]
请大神麻烦重新改一下客户端相关文件的配置，要不然用不了

**Comment by leungxt** [comment]
v3的确是用不了，少一个填密码的地方

**Comment by bbswww** [comment]
还请大神可以修复一下这个问题

**Comment by leungxt** [comment]
谢谢，4.70.9已经修复了这个问题
