### ISSUE TITLE
4.68-5带的依赖包已经安装了，4.70-4还是安装不上

### ISSUE THREAD

**Issue by Hello-Panda1975** [xiaorouji/openwrt-package#2777]
root@QWRT:/tmp/upload# opkg install *.ipk
Package luci-app-passwall (4.69-4) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall

**Comment by Hello-Panda1975** [comment]
找了一个sing-box的IPK文件，又提示缺少另外一个依赖，kmod-netlink-diag要在那里能下载到？
root@QWRT:/tmp/upload# opkg install *.ipk
Unknown package 'sing-box'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
 * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package sing-box.

**Comment by mirthlesslk** [comment]
借楼提问，这个新改的分支要咋用，src-git添加了链接之后luci提示找不到依赖
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'chinadns-ng', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'dns2socks', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'dns2tcp', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'tcping', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'brook', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'hysteria', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'naiveproxy', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-rust-sslocal', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-rust-ssserver', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'simple-obfs', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'trojan-plus', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'tuic-client', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'v2ray-plugin', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'xray-plugin', which does not exist

**Comment by firkerword** [comment]
> 找了一个sing-box的IPK文件，又提示缺少另外一个依赖，kmod-netlink-diag要在那里能下载到？ root@QWRT:/tmp/upload# opkg install *.ipk Unknown package 'sing-box'. Collected errors:
> 
> * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
> * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
> * opkg_install_cmd: Cannot install package sing-box.

安装不上是依赖没装齐，费那劲不如直接编译好

**Comment by firkerword** [comment]
> 借楼提问，这个新改的分支要咋用，src-git添加了链接之后luci提示找不到依赖 WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'chinadns-ng', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'dns2socks', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'dns2tcp', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'tcping', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'brook', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'hysteria', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'naiveproxy', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-rust-sslocal', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-rust-ssserver', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'simple-obfs', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'trojan-plus', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'tuic-client', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'v2ray-plugin', which does not exist WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'xray-plugin', which does not exist

git clone -b packages https://github.com/xiaorouji/openwrt-passwall.git

**Comment by Hello-Panda1975** [comment]
> > 找了一个sing-box的IPK文件，又提示缺少另外一个依赖，kmod-netlink-diag要在那里能下载到？ root@QWRT:/tmp/upload# opkg install *.ipk Unknown package 'sing-box'. Collected errors:
> > 
> > * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
> > * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
> > * opkg_install_cmd: Cannot install package sing-box.
> 
> 安装不上是依赖没装齐，费那劲不如直接编译好

我也知道是依赖不齐啊，能补齐需要的依赖不更好嘛

**Comment by Gzxhwq** [comment]
kmod是内核相关的，是和内核一起编译出来的，配对使用

**Comment by redfrog999** [comment]
自行编译即可解决。

**Comment by bcseputetto** [comment]
推荐来使用iStoreOS，内核版本和内核vermagic和OpenWrt官方的opkg源完全一致，可以后续安装kmod内核模块。而不是那些高大全编译的新版本内核，不同vermagic，也不提供自己的opkg源，直接用OpenWrt官方的开发快照源，啥kmod都装不上

**Comment by redfrog999** [comment]
> 推荐来使用iStoreOS，内核版本和内核vermagic和OpenWrt官方的opkg源完全一致，可以后续安装kmod内核模块。而不是那些高大全编译的新版本内核，不同vermagic，也不提供自己的opkg源，直接用OpenWrt官方的开发快照源，啥kmod都装不上

这个开发版用的是闭源还是开源驱动呢？
