### ISSUE TITLE
Xray分流和规则列表谁优先级高

### ISSUE THREAD

**Issue by laaArmy** [xiaorouji/openwrt-package#2778]
![IMG_20230912_040650_866.jpg](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/b18f99de-1149-4a99-a713-2f6696bcffe8)

![IMG_20230912_040652_441.jpg](https://github.com/xiaorouji/openwrt-passwall/assets/38807357/3a595217-35c5-476e-8366-384d2bfd31fb)

如图，这两张图，谁优先级高？

**Comment by MiKing233** [comment]
所以直接把要直連的和代理域名寫到上面的列表裏面不就可以了, 感覺下面這個完全是重複的功能

**Comment by WROIATE** [comment]
> 所以直接把要直連的和代理域名寫到上面的列表裏面不就可以了, 感覺下面這個完全是重複的功能

你要理解不是所有的工具都像xray一样具有分流功能
passwall2就没有做这种冗余，因为只支持xray、singbox
