### ISSUE TITLE
sing-box内核使用机场VMESS节点无法使用的问题

### ISSUE THREAD

**Issue by fxljay** [xiaorouji/openwrt-package#2779]
最新版PASSWALL，使用了singbox内核后，机场的VMESS订阅的节点全部无法使用，求助怎样设置。

**Comment by hxlls** [comment]
好像目前sing box 还是有问题，我就算是sing box 订阅的，用singbox 分流总节点一样是不可用，换成RAY 就没问
![image](https://github.com/xiaorouji/openwrt-passwall/assets/43886952/74a64a3c-77ef-4ff7-a5a2-cc34ef3a7e15)

**Comment by XXXstyle** [comment]
看到最近都在说singbox，是xray不好用了，还是singbox有什么过人之处吗

**Comment by ypkin** [comment]
本人小白，singbox 分流、节点导入导出、tuic协议、ssr本地服务都有问题，相反老版本上述问题都没有，目前退回4.69-4。

**Comment by handsomeji** [comment]
Fix
