### ISSUE TITLE
passwall 使用sing-box内核，日志大量错误

### ISSUE THREAD

**Issue by tanbx** [xiaorouji/openwrt-package#2782]
使用最新版的4.70-4passwall，配置sing-box内核，当dns采用fakeDNS时，可以正常启动和使用，但日志有大量错误。
![屏幕截图 2023-09-12 215843](https://github.com/xiaorouji/openwrt-passwall/assets/108619712/fdb2200e-78ec-4e2c-aa63-b2d51e75938e)
![屏幕截图 2023-09-12 215922](https://github.com/xiaorouji/openwrt-passwall/assets/108619712/c85727fc-ce33-4ad5-9753-23f393d7a4f7)
![屏幕截图 2023-09-12 215955](https://github.com/xiaorouji/openwrt-passwall/assets/108619712/4bd52da1-ea9f-4618-8caf-d77a6c090831)
![屏幕截图 2023-09-13 085621](https://github.com/xiaorouji/openwrt-passwall/assets/108619712/4610d031-bfc4-49cb-99c4-2bee778b0c3a)

**Comment by manbowuhao** [comment]
正在执行软件包管理器
Package luci-app-passwall (4.70-5) installed in root is up to date.
错误
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall

**Comment by handsomeji** [comment]
应该是fakeip只能处理A AAAA类型的DNS请求。
看日志貌似是无法处理HTTPS查询类型。

**Comment by handsomeji** [comment]
下个版本调一下逻辑

**Comment by sjs76** [comment]
4.7版本以后我的机场除了ss节点可以用v2ray节点就都是超时，已经退回694版本了。

**Comment by handsomeji** [comment]
@sjs76 你使用最新版本测试过了吗？有问题应该反馈问题，找到问题所在去解决。

**Comment by handsomeji** [comment]
@tanbx  用最新版本重新配置DNS试试

**Comment by tanbx** [comment]
> @tanbx 用最新版本重新配置DNS试试

4.70-6已测试，问题解决，谢谢
