### ISSUE TITLE
openwrt 重启后passwall未正常运行启动

### ISSUE THREAD

**Issue by sjcta** [xiaorouji/openwrt-package#2785]
Passwall 版本【 git-24.255.56205-ea99bb7 】

TCP节点：sing-box分流节点
UDP节点：与TCP节点相同
Socks主开关：开启

重启后，主开关处于勾选状态，但TCP,UDP等均未运行。需要重新开关一次主开关才能正常。

**Comment by laaArmy** [comment]
一看就是用openwrt.ai的

**Comment by xcyll** [comment]
看下passwall日志 
重启需要等待一定的时间
