### ISSUE TITLE
4.70-6缺少luci-lua-runtime無法安裝

### ISSUE THREAD

**Issue by MiKing233** [xiaorouji/openwrt-package#2786]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall

OpenWrt版本是ImmortalWrt 18.06-k5.4
注意到Passwall Info中
💽 Passwall Version: 4.70-6
⚙️ OpenWrt SDK Version: 23.05-rc3

是否意味著舊版本的OpenWrt已不再被支援?

**Comment by snowie2000** [comment]
尝试了很多办法，似乎都没有办法忽略这个依赖。最终大力出奇迹：

[luci-lua-runtime_all_fake.zip](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip)

装上这个假依赖包就可以了。这个包除了给你的opkg满足依赖外不会有任何效果。

**Comment by RavenCage** [comment]
> 尝试了很多办法，似乎都没有办法忽略这个依赖。最终大力出奇迹：
> 
> [luci-lua-runtime_all_fake.zip](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip)
> 
> 装上这个假依赖包就可以了。这个包除了给你的opkg满足依赖外不会有任何效果。

感谢分享，另外一个大力奇迹就是用winzip把ipk里的control文件改了，最后一个luci-lua-runtime给删掉就OK啦。

**Comment by Sleepbuild** [comment]
感謝您，我安裝了您的[luci-lua-runtime_all_fake.zip]後成功更新了470-6並且也成功安裝了sing-box，感謝您，這個困擾我一個星期了。

**Comment by snowie2000** [comment]
> > 尝试了很多办法，似乎都没有办法忽略这个依赖。最终大力出奇迹：
> > [luci-lua-runtime_all_fake.zip](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip)
> > 装上这个假依赖包就可以了。这个包除了给你的opkg满足依赖外不会有任何效果。
> 
> 感谢分享，另外一个大力奇迹就是用winzip把ipk里的control文件改了，最后一个luci-lua-runtime给删掉就OK啦。

我也尝试过这个方法，但不知道处于什么原因，opkg依然不允许我安装，最终只能用上述方法了

**Comment by RavenCage** [comment]
> > > 尝试了很多办法，似乎都没有办法忽略这个依赖。最终大力出奇迹：
> > > [luci-lua-runtime_all_fake.zip](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip)
> > > 装上这个假依赖包就可以了。这个包除了给你的opkg满足依赖外不会有任何效果。
> > 
> > 
> > 感谢分享，另外一个大力奇迹就是用winzip把ipk里的control文件改了，最后一个luci-lua-runtime给删掉就OK啦。
> 
> 我也尝试过这个方法，但不知道处于什么原因，opkg依然不允许我安装，最终只能用上述方法了

这个方法不完美，装上后更新其他组件有问题。就是这个方法是最完美的。咔咔。

**Comment by MiKing233** [comment]
整理了一些依賴包, 他們只是用於滿足一些安裝依賴, 沒有任何實質性功能
[https://mirrors.mknetwork.net/?f=/openWrt-packages/luci-compat](url)

**Comment by snowie2000** [comment]
很讚，感謝！

**Comment by RavenCage** [comment]
> 整理了一些依賴包, 他們只是用於滿足一些安裝依賴, 沒有任何實質性功能 [https://mirrors.mknetwork.net/?f=/openWrt-packages/luci-compat](url)

非常感谢，满足强迫症了。

**Comment by Fegor** [comment]
能否整合到release下载包里？

**Comment by MiKing233** [comment]
> 能否整合到release下载包里？

不能, 这些其实是高版本系统自带的包, 只有低版本安装才会出现这个问题

**Comment by guominfang** [comment]
> > > 尝试了很多办法，似乎都没有办法忽略这个依赖。最终大力出奇迹：
> > > [luci-lua-runtime_all_fake.zip](https://github.com/xiaorouji/openwrt-passwall/files/12605732/luci-lua-runtime_all_fake.zip)
> > > 装上这个假依赖包就可以了。这个包除了给你的opkg满足依赖外不会有任何效果。
> > 
> > 
> > 感谢分享，另外一个大力奇迹就是用winzip把ipk里的control文件改了，最后一个luci-lua-runtime给删掉就OK啦。
> 
> 我也尝试过这个方法，但不知道处于什么原因，opkg依然不允许我安装，最终只能用上述方法了

请问如何假装安装这个zip的

**Comment by f63531119** [comment]
感谢解决问题
