### ISSUE TITLE
 sb-tun is not compatible with Firewale 4

### ISSUE THREAD

**Issue by rivandraa** [xiaorouji/openwrt-package#2788]
![Screenshot_3](https://github.com/xiaorouji/openwrt-passwall/assets/139041404/3d515129-da5c-4dbc-b2a0-1f95f6ca3844)

![Screenshot_4](https://github.com/xiaorouji/openwrt-passwall/assets/139041404/1f7ea67f-8a09-4056-9c8c-377f7cafa581)

Passwall Version: 4.70-6
OpenWRT 23.05.0-rc3

**Comment by handsomeji** [comment]
passwall还未使用tun，你是哪里来的tun接口？

**Comment by rivandraa** [comment]
if I turn off passwall, sb-tun disappears on the firewall

**Comment by handsomeji** [comment]
The passwall code does not use TUN and cannot be solved.

**Comment by handsomeji** [comment]
maybe https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/sing-box/files.
exec
```
/etc/init.d/sing-box stop
/etc/init.d/sing-box disable
```

**Comment by Terutoki** [comment]
> The passwall code does not use TUN and cannot be solved.

I'm not sure if the following code is causing this issue?

<img width="826" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/2dbe848f-8532-4ab0-b830-ee31aac66bc0">

<img width="921" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/6260f56f-1c18-45e3-b1f2-d86310dcff9e">

**Comment by rivandraa** [comment]
> maybe https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/sing-box/files. exec
> 
> ```
> /etc/init.d/sing-box stop
> /etc/init.d/sing-box disable
> ```

Yes, that's right, after sing-box is stopped or turned off, sb-tun becomes inactive
