### ISSUE TITLE
新版Passwall的sing-box不支持vmess+gRPC

### ISSUE THREAD

**Issue by Terutoki** [xiaorouji/openwrt-package#2790]
<img width="567" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/1a062c31-d12b-4a6f-8113-a887578cd318">

**Vmess的传输方式中无法选择gRPC**

<img width="583" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/827c5e69-f0f0-49e2-b08f-3f9bf264983f">

**Comment by handsomeji** [comment]
你的sing-box没有编译 gRPC 支持

**Comment by Terutoki** [comment]
> 你的sing-box没有编译 gRPC 支持

非常感谢，看起来应该是这个问题。

<img width="673" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/1f49aafb-0bc5-459d-b5c8-3c19b5dc448a">

**Comment by Terutoki** [comment]
发现了一个gRPC的issue，现在代码中的serviceName应该改成service_name才能work的。

http://sing-box.sagernet.org/configuration/shared/v2ray-transport/#grpc

<img width="1310" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/31648892/e849bd6a-620d-4d7b-bfaa-ddb701dedbbd">

**Comment by Gzxhwq** [comment]
这里有一个问题，如果没有编译grpc tag，sing-box默认是用性能更好的grpc-lite的，并不是没有grpc，但是需要双端sing-box。或者服务器端sing-box，客户端clash-meta

而*ray是用性能较差的标准grpc，需要sing-box编译grpc tag才能兼容，只是这样就不能用grpc-lite了
