### ISSUE TITLE
xray/v2ray的https支持

### ISSUE THREAD

**Issue by snowie2000** [xiaorouji/openwrt-package#2791]
按照官方的说明文档，socks5和http均是支持tls的，但是目前http并没有tls相关的配置项。麻烦加一下

**Comment by xiaorouji** [comment]
给个示例 json 配置文件看看

**Comment by snowie2000** [comment]
只要把tls相关的选项打开即可。我测试过，目前的passwall可以正确生成对应的配置文件。

实际上就是https=tls+http，tls本身就是独立的一个section

**Comment by snowie2000** [comment]
4.70-10依然没有实现吧，这个是很难做到吗？我记得很早前我有自己改过luci的，好像不难的样子

**Comment by snowie2000** [comment]
4.71-2依然无法在http下启用tls，请把他改成和socks一样的。
