### ISSUE TITLE
更新了版本，Netflix无辜不解了

### ISSUE THREAD

**Issue by aisuyi065** [xiaorouji/openwrt-package#2792]
只是更新了passwall最新版，有了sin-box后，Netflix变成了只能看自制剧
sg的vps是全解的，passwall更新前也是能看非自制剧的，
浏览器打开Netflix也是显示的sg的网页

**Comment by jh0072110** [comment]
NF不解锁也能怪到psw身上啊…那只是NF瞎JB杀人而已

**Comment by handsomeji** [comment]
先用单节点看看正常否

**Comment by aisuyi065** [comment]
> 先用单节点看看正常否

单节点也不行，没升级前都是正常的
