### ISSUE TITLE
[Bug]: sing-box fakedns分流疑问

### ISSUE THREAD

**Issue by tanbx** [xiaorouji/openwrt-package#2797]
### 描述您遇到的bug

用最新的4.70-7，sing-box分流，dns用sing-box的fakedns，查看op中的config文件。
 "category-ads-all"为什么和 "geolocation-!cn"用同一DNS？

  "dns": {
    "disable_cache": true,
    "rules": [
      {
        "disable_cache": true,
        "geosite": [
          "category-ads-all",
          "openai",
          "geolocation-!cn",
          "netflix"
        ],
        "query_type": [
          "A",
          "AAAA"
        ],
        "domain_keyword": [
          "store.steampowered.com"
        ],
        "server": "remote_fakeip"
      },
............

### 复现此Bug的步骤

no

### 您想要实现的目的

这样合适？

### 日志信息

无

### 系统相关信息

4.70-7

**Comment by hcym** [comment]
box目录下吗？p1和p2我用的都基本正常，就没看其他地方

**Comment by tanbx** [comment]
> box目录下吗？p1和p2我用的都基本正常，就没看其他地方
是passwall运行中使用的配置文件 /tmp/etc/passwall/TCP_UDP_SOCKS_DNS.json

**Comment by tanbx** [comment]
生产的配置文件/tmp/etc/passwall/TCP_UDP_SOCKS_DNS.json
route中没问题，就是dns中把"category-ads-all"和"geolocation-!cn"放在同一dns应该是不正确的做法。

**Comment by handsomeji** [comment]
没懂什么意思？你意思是说 黑洞规则应该直接block dns？

**Comment by tanbx** [comment]
> 没懂什么意思？你意思是说 黑洞规则应该直接block dns？
我看其它sing-box客户端配置样例，都是把category-ads-all 放block dns的

**Comment by tanbx** [comment]
{
                "tag": "dns_block",
                "address": "rcode://success"
            }
        ],
        "rules": [
            {
                "geosite": [
                    "category-ads-all"
                ],
                "server": "dns_block",
                "disable_cache": true
            },

**Comment by handsomeji** [comment]
最新commit已增加黑洞DNS规则
