### ISSUE TITLE
[Bug]: sing-box下访问控制设置局域网某台机器全局代理后，该机器无法联网

### ISSUE THREAD

**Issue by zcluo** [xiaorouji/openwrt-package#2798]
### 描述您遇到的bug

节点都是sing-box，分流也用sing-box。访问控制设置局域网某台机器全局代理后，该机器无法联网

### 复现此Bug的步骤

节点都是sing-box，分流也用sing-box。访问控制设置局域网某台机器全局代理后，该机器无法联网

### 您想要实现的目的

节点都是sing-box，分流也用sing-box。访问控制设置局域网某台机器全局代理后，该机器可以正常通过节点全局访问外网

### 日志信息

无

### 系统相关信息

4.70-6

**Comment by handsomeji** [comment]
试下最新的源码

**Comment by zcluo** [comment]
> 试下最新的源码

-8版本已验证可以使用。谢谢。
