### ISSUE TITLE
[Bug]: 4.70-8的sing-box的DNS应该还是有问题，选DOH和TCP模式都无法解析域名

### ISSUE THREAD

**Issue by zcluo** [xiaorouji/openwrt-package#2800]
### 描述您遇到的bug

 4.70-8的sing-box的DNS应该还是有问题，选DOH和TCP模式都无法解析域名

### 复现此Bug的步骤

基本设置-》DNS-》过滤模式SING-BOX

### 您想要实现的目的

DNS的SING-BOX过滤模式正常工作

### 日志信息

见截图

### 截图

![sing-box-doh](https://github.com/xiaorouji/openwrt-passwall/assets/642516/778ecf4e-2a56-49f1-89df-d18c217e352c)

### 系统相关信息

4.70-8

**Comment by zcluo** [comment]
DNS换成TCP和XRAY就正常了。

**Comment by jh0072110** [comment]
你如果是xray节点就只能用xray的dns（反之亦然

**Comment by zcluo** [comment]
我的节点是配置的SB的

**Comment by zcluo** [comment]
又重新试了下只有配置8844\8888有问题我记得在sb的配置里可以指定dns远程的出口是否可以考虑增加配置？或是目前机制是走的proxy?

**Comment by jh0072110** [comment]
> 我的节点是配置的SB的

那不知道了，我用着没问题啊，要不你把缓存和chinadns都开开试试？或者重置一下psw…

**Comment by jxph1123** [comment]
用smartdns版本，没有问题

**Comment by smzdmmmm** [comment]
FakeDNS选中

**Comment by ypkin** [comment]
代理模式选 “中国列表以外”还是不能解析！！

**Comment by jxph1123** [comment]
> 代理模式选 “中国列表以外”还是不能解析！！

你的dnsmasq是哪个版本？
