### ISSUE TITLE
关于最新版本4.70-8的Xray DNS问题

### ISSUE THREAD

**Issue by bcseputetto** [xiaorouji/openwrt-package#2808]
### 描述你想要的新功能

最新版本的XrayDNS DoH变成了 TCP+DoH组合，请问这是为何？我是自建DoH，希望所有的DNS查询都能传入我自己的DNS，变成TCP+DOH后，是否会有一些查询进入TCP的DNS呢？~~Sing-BOX虽然有仅DoH的选项，但目前Sing-BOX的分流似乎有问题，geo文件无法下载，DNS也一堆EOF错误~~
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/af77ce46-ddf4-4f06-9fb4-19cd38712058)

### 描述你想要的解决方案

希望能把DNS查询全部传入我自己的DNS

**Comment by bcseputetto** [comment]
关于Sing-Box的问题我发现是xray和sing-box的mux实现方式不同造成的(或者是当前passwall的sing-box mux有问题)，打开mux立马就不能用了，三种都不行，节点是Vless协议

**Comment by Gzxhwq** [comment]
sing-box和xray的mux不同，xray并没有实现mux.cool以外的mux方式，世界提交的PR也被拒了

**Comment by bcseputetto** [comment]
> sing-box和xray的mux不同，xray并没有实现mux.cool以外的mux方式，世界提交的PR也被拒了

那我的Vless在xray下可以用mux，sing-box下不能用了，有什么解决办法吗？还是说我要动节点服务器的服务端？

**Comment by Gzxhwq** [comment]
两边都不开mux，或者两边都用xray/sing-box

**Comment by bcseputetto** [comment]
> 两边都不开mux，或者两边都用xray/sing-box

服务端我用的还是 v2ray vless

**Comment by Gzxhwq** [comment]
> > 两边都不开mux，或者两边都用xray/sing-box
> 
> 服务端我用的还是 v2ray vless

xray的mux现在暂时还能和v2ray的兼容（除了vision）

**Comment by bcseputetto** [comment]
> > > 两边都不开mux，或者两边都用xray/sing-box
> > 
> > 
> > 服务端我用的还是 v2ray vless
> 
> xray的mux现在暂时还能和v2ray的兼容（除了vision）

我现在passwall暂时用 Xray跑TCP，Sing-Box跑DoH DNS，目前状况良好。Sing-Box这个mux用不上了，那恐怕暂时无法把Vless交给Sing-Box跑了

**Comment by Gzxhwq** [comment]
> > > > 两边都不开mux，或者两边都用xray/sing-box
> > > 
> > > 
> > > 服务端我用的还是 v2ray vless
> > 
> > 
> > xray的mux现在暂时还能和v2ray的兼容（除了vision）
> 
> 我现在passwall暂时用 Xray跑TCP，Sing-Box跑DoH DNS，目前状况良好。Sing-Box这个mux用不上了，那恐怕暂时无法把Vless交给Sing-Box跑了

建议还是尽早放弃v2ray的vless。
1、v2ray的vless已经没人维护，v2ray开发组一直都想移除vless的支持
2、xray开发者打算对xray大改（大砍）功能，未来vless或者mux相关功能改（或删），也会导致与v2ray的vless兼容失效

**Comment by bcseputetto** [comment]
> > > > > 两边都不开mux，或者两边都用xray/sing-box
> > > > 
> > > > 
> > > > 服务端我用的还是 v2ray vless
> > > 
> > > 
> > > xray的mux现在暂时还能和v2ray的兼容（除了vision）
> > 
> > 
> > 我现在passwall暂时用 Xray跑TCP，Sing-Box跑DoH DNS，目前状况良好。Sing-Box这个mux用不上了，那恐怕暂时无法把Vless交给Sing-Box跑了
> 
> 建议还是尽早放弃v2ray的vless。 1、v2ray的vless已经没人维护，v2ray开发组一直都想移除vless的支持 2、xray开发者打算对xray大改（大砍）功能，未来vless或者mux相关功能改（或删），也会导致与v2ray的vless兼容失效

那我要动服务端的话，是把服务端从v2ray换到xray或者sing-box，协议的话是回去用Vmess吗？v2ray官方推荐换到Trojan

**Comment by Gzxhwq** [comment]
协议继续用vless。因为xray未来可能会砍掉vmess。
服务器端换到xray或者sing-box都可以，sing-box一般都会跟进市面上的新协议，还有一些独有的较前卫的功能（例如ECH）

**Comment by bcseputetto** [comment]
> 协议继续用vless。因为xray未来可能会砍掉vmess。 服务器端换到xray或者sing-box都可以，sing-box一般都会跟进市面上的新协议，还有一些独有的较前卫的功能（例如ECH）

好，我考虑将来服务端迁移到 xray+vless，但你看看关于passwall新版xray dns的问题，为啥把DoH变成tcp+doh组合了，虽然DoH依然是默认DNS，但我发现日志里还是有一些向tcp dns的连接

**Comment by bcseputetto** [comment]
```
2023/09/19 07:08:15 DNS accepted https://dns.****.cc/dns-query/**** [dns-in1 -> default]
2023/09/19 07:08:20 127.0.0.1:45265 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2023/09/19 07:08:28 127.0.0.1:42622 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2023/09/19 07:08:28 127.0.0.1:51776 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2023/09/19 07:08:28 127.0.0.1:40391 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2023/09/19 07:08:28 127.0.0.1:34114 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
```

**Comment by bcseputetto** [comment]
以及之前Xray 自定义DoH的时候格式似乎是这样的
https://dns.domain.com/dns-query,ip_address
现在似乎Xray和Sing-Box的自定义DoH，都不需要加 ,ip_address

**Comment by Gzxhwq** [comment]
> > 协议继续用vless。因为xray未来可能会砍掉vmess。 服务器端换到xray或者sing-box都可以，sing-box一般都会跟进市面上的新协议，还有一些独有的较前卫的功能（例如ECH）
> 
> 好，我考虑将来服务端迁移到 xray+vless，但你看看关于passwall新版xray dns的问题，为啥把DoH变成tcp+doh组合了，虽然DoH依然是默认DNS，但我发现日志里还是有一些向tcp dns的连接

https://github.com/xiaorouji/openwrt-passwall/discussions/2789

这里大佬回答了

**Comment by bcseputetto** [comment]
#2531
现在自定DoH不需要加 ,ip_address 了？

**Comment by Gzxhwq** [comment]
> 以及之前Xray 自定义DoH的时候格式似乎是这样的 https://dns.domain.com/dns-query,ip_address 现在似乎Xray和Sing-Box的自定义DoH，都不需要加 ,ip_address

xray我不清楚，但是sing-box是可以指定dns给dns的域名做解析的，passwall默认是用国内的dns解析doh/dot服务器的域名

**Comment by bcseputetto** [comment]
我发现 xray和sing-box似乎都可以解析DoH了，不需要在DoH后面加上IP地址

**Comment by Gzxhwq** [comment]
> 我发现 xray和sing-box似乎都可以解析DoH了，不需要在DoH后面加上IP地址

那就是passwall先做了预解析，把之前要手动填写的ip地址自动先解析一次，再帮你填上了。
xray自己是没有sing-box这种这么方便的机制的。
