### ISSUE TITLE
[Bug]: sing-box的shadowsocks中加密方式保存后会随机（几率还挺大的）变成none

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#2809]
### 描述您遇到的bug

RT，也不是每次都会变，但是会很大几率随即变成none

### 复现此Bug的步骤

![Jietu20230919-175338](https://github.com/xiaorouji/openwrt-passwall/assets/50496854/d5b4bf4a-6a6e-4366-9081-36819fe63671)
大概就这样，保存就变成了none

### 您想要实现的目的

Pls fix it

### 日志信息

需要吗

### 系统相关信息

4.70-8

**Comment by Gzxhwq** [comment]
我这里无法重现，感觉不像是passwall的问题，更像是luci的问题，试试清空luci cache

**Comment by jh0072110** [comment]
> 我这里无法重现，感觉不像是passwall的问题，更像是luci的问题，试试清空luci cache

额 我也不知道怎么回事 给我哥远程的时候也发现了这个问题……
