### ISSUE TITLE
[Bug]: 手动添加规则ipv6域名强制走代理，但不生效 byr.pt

### ISSUE THREAD

**Issue by pengkaiwei** [xiaorouji/openwrt-package#2811]
### 描述您遇到的bug

手动添加规则byr.pt，强制走代理
但是不生效，访问还是没有走代理

设置中打开IPv6透明代理(TProxy)，也无效
服务器支持ipv6

### 复现此Bug的步骤

GFW模式

### 您想要实现的目的

手动添加国内ipv6域名，可能强制走代理

### 日志信息

手动添加国内ipv6域名，可能强制走代理

### 系统相关信息

Passwall 版本【 4.66-6 】  Brook 版本【 20230606 】  Hysteria 版本【 1.3.4 】  ChinaDNS-NG 版本【 2023.06.01 】  Trojan-Go 版本【 0.10.6 】  V2ray 版本【 5.7.0 】  Xray 版本【 1.8.4 】

TCP 默认代理模式
GFW 列表

 UDP 默认代理模式
GFW 列表

 路由器本机 TCP 代理模式
中国列表以外

 路由器本机 UDP 代理模式
GFW 列表

### 其他信息

谢谢！

**Comment by handsomeji** [comment]
Not using the latest version feedback, unable to resolve.
