### ISSUE TITLE
[Bug]: 原版hysteria因为懒加载延迟请求，导致vps的ip没有加到passwall_vpslist中一直连接不上

### ISSUE THREAD

**Issue by maskedeken** [xiaorouji/openwrt-package#2816]
### 描述您遇到的bug

原版hysteria因为懒加载延迟请求，导致vps的ip没有加到passwall_vpslist中一直连接不上。如果修改util_hysteria2.lua，改为lazy: false，则没有问题

### 复现此Bug的步骤

创建hysteria配置，连接

### 您想要实现的目的

原版hysteria功能正常

### 日志信息

hysteria的日志一直报
connect error: timeout: no recent network activity

### 系统相关信息

immortalwrt 23.05 x86_64

**Comment by Gzxhwq** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/cf2d0e485835d2a327ea3b560129919e5da73742
