### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jiaoting** [xiaorouji/openwrt-package#2821]
### 描述您遇到的bug

<img width="733" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/12553424/6dfd5709-3339-4114-a88e-7d44dd1e8185">

### 复现此Bug的步骤

在iostoreOS里安装

### 您想要实现的目的

这个提示是什么原因？

### 日志信息

<img width="733" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/12553424/4e359c86-95ef-4780-82ff-f9ccb268ef7e">

### 系统相关信息

passwall 4.70-10

**Comment by Pacio** [comment]
https://github.com/AUK9527/Are-u-ok/tree/main/x86

**Comment by Gzxhwq** [comment]
这种问题应该往istore提
