### ISSUE TITLE
[Bug]: 今天升级了4.70-10版本，但是v2ray插件却没了，只剩下了xray

### ISSUE THREAD

**Issue by wang923345843** [xiaorouji/openwrt-package#2823]
### 描述您遇到的bug

使用openwrt系统，是aarch64_generic版本，分别手动下载了第一个和第二个，以及依赖安装包，安装完成后界面只有xray，没有v2ray的任何字眼了

### 复现此Bug的步骤

1,软件包界面删除了passwall4.66版本，下载了ipk，然后安装ipk，最后passwall界面就这样了

### 您想要实现的目的

如何能让v2ray回来
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/0a357093-6b70-4cf1-8261-11d0a75dbfb8)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/c50cab1c-fe1a-49cc-91df-63ca9cc0b8fd)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/eb8da612-d300-4fe4-b6cf-75ddc003fed0)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/01578718-91d1-460f-8faa-c921ce8cf502)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/9232f26e-08d7-4e79-886f-734444829b59)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/100781270/7e755cda-c768-463b-8721-078962d49b84)

### 日志信息

无

### 系统相关信息

4.70-10

**Comment by Gzxhwq** [comment]
v2ray的支持已经移除了，请使用xray或者sing-box

**Comment by liyuhaolol** [comment]
> v2ray的支持已经移除了，请使用xray或者sing-box

额，我也是最近重新编译关注了一下这个问题，可以冒昧的问一下，为啥把v2ray的支持给移除了么。
