### ISSUE TITLE
[Bug]: 4.70-10版本，所有SSR节点均无法使用

### ISSUE THREAD

**Issue by Giglizeng** [xiaorouji/openwrt-package#2827]
### 描述您遇到的bug

4.69-1版本下，均能正常使用各SSR节点，升级后均无法使用，有时延显示，但可用性测试均显示超时，且切换节点后，网页也不能打开，确定无法使用。

### 复现此Bug的步骤

暂无

### 您想要实现的目的

希望解决

### 日志信息

暂无日志，已回退4.69版本

### 系统相关信息

4.70-10

**Comment by jh0072110** [comment]
这不是Bug，随着时代的发展，旧社会的产物就被默默抛弃了（狗头

**Comment by Giglizeng** [comment]
好的，谢谢！

**Comment by Gzxhwq** [comment]
就算改炸了，也不应该修了，就让他烂掉，然后移除吧

**Comment by SakuraFallingMad** [comment]
魅影始终ssr，不过分流下ssr还是正常的。。。

**Comment by Giglizeng** [comment]
我的节点多数是SSR的，所以暂时退回4.69使用吧，没办法

**Comment by jxph1123** [comment]
希望可以修复，毕竟还是个独立协议

**Comment by xiaorouji** [comment]
不提供节点，怎么修复呢

**Comment by WYC-2020** [comment]
试试别升级那个openssl，我回退这玩意一切正常，l那边吧openssl升级到了3.0我测试是helloword和passwall都会有问题直接没法用，也是ssr节点，回退后一切正常

**Comment by Giglizeng** [comment]
好的，我回头试试

**Comment by Chanhangfai** [comment]
> 试试别升级那个openssl，我回退这玩意一切正常，l那边吧openssl升级到了3.0我测试是helloword和passwall都会有问题直接没法用，也是ssr节点，回退后一切正常

怎样回退? 能分享方法吗?

**Comment by Giglizeng** [comment]
同问回退的方法，或者终止、挂起这个进程可以吗？谢谢！

**Comment by kumoonkey** [comment]
我用的4.70-8版本，用SSR没问题啊。

**Comment by Giglizeng** [comment]
> 啊

我用的是4.70-10，自己搭的SSR节点正常，但机场提供的SSR节点都不行，同样的节点，在之前版本或v2rayn等上都正常

**Comment by kumoonkey** [comment]
我用的是机场的SSR节点没问题。这个只和v2ray core或xray core有关系，和passwall没关系吧？

**Comment by Giglizeng** [comment]
> 我用的是机场的SSR节点没问题。这个只和v2ray core或xray core有关系，和passwall没关系吧？

现在不确定，我知道的情况不止我一个人，4.70之后SSR节点不正常是相对比较普遍的情况，也有说是openssl是测试版的缘故

**Comment by WYC-2020** [comment]
> > 试试别升级那个openssl，我回退这玩意一切正常，l那边吧openssl升级到了3.0我测试是helloword和passwall都会有问题直接没法用，也是ssr节点，回退后一切正常
> 
> 怎样回退? 能分享方法吗?

你用的l的仓库 直接克隆了替换里面的openssl就行了啊，如果用的Action 编译的那就直接吧原来的删除用新的替换就行了啊 这个简单

**Comment by WYC-2020** [comment]
> > 我用的是机场的SSR节点没问题。这个只和v2ray core或xray core有关系，和passwall没关系吧？
> 
> 现在不确定，我知道的情况不止我一个人，4.70之后SSR节点不正常是相对比较普遍的情况，也有说是openssl是测试版的缘故

我这边是 测试是openssl导致的，因为相同配置 一个升级了openssl 一个没升级，然后 编译的固件 升级了那个就不行 没升级的就行，你可以试试

**Comment by xuhuanzy** [comment]
> > > 我用的是机场的SSR节点没问题。这个只和v2ray core或xray core有关系，和passwall没关系吧？
> > 
> > 
> > 现在不确定，我知道的情况不止我一个人，4.70之后SSR节点不正常是相对比较普遍的情况，也有说是openssl是测试版的缘故
> 
> 我这边是 测试是openssl导致的，因为相同配置 一个升级了openssl 一个没升级，然后 编译的固件 升级了那个就不行 没升级的就行，你可以试试

解决了, 原因是openssl3.0遗弃了一大批不安全算法, 节点使用了遗弃算法那就不能用

**Comment by SakuraFallingMad** [comment]
试试，OpenSSL编译时，编译libopenssl-legacy吧。

**Comment by Giglizeng** [comment]
> 试试，OpenSSL编译时，编译libopenssl-legacy吧。

谢谢

**Comment by WYC-2020** [comment]
> 试试，OpenSSL编译时，编译libopenssl-legacy吧。

试过没戏，暂时先停留在老版本

**Comment by WYC-2020** [comment]
> > > > 我用的是机场的SSR节点没问题。这个只和v2ray core或xray core有关系，和passwall没关系吧？
> > > 
> > > 
> > > 现在不确定，我知道的情况不止我一个人，4.70之后SSR节点不正常是相对比较普遍的情况，也有说是openssl是测试版的缘故
> > 
> > 
> > 我这边是 测试是openssl导致的，因为相同配置 一个升级了openssl 一个没升级，然后 编译的固件 升级了那个就不行 没升级的就行，你可以试试
> 
> 解决了, 原因是openssl3.0遗弃了一大批不安全算法, 节点使用了遗弃算法那就不能用

所以说还是 暂时用老版本吧，能玩就行

**Comment by xuhuanzy** [comment]
> > 试试，OpenSSL编译时，编译libopenssl-legacy吧。
> 
> 试过没戏，暂时先停留在老版本

看看机场节点加密算法是什么, 在不在openssl3遗弃算法里, 然后看看libopenssl3+libopenssl-legacy这两个库装了没有.
我是这个问题.

**Comment by WYC-2020** [comment]
> > > 试试，OpenSSL编译时，编译libopenssl-legacy吧。
> > 
> > 
> > 试过没戏，暂时先停留在老版本
> 
> 看看机场节点加密算法是什么, 在不在openssl3遗弃算法里, 然后看看libopenssl3+libopenssl-legacy这两个库装了没有. 我是这个问题.

那是必须装上了的，暂时还是用老版本了 懒得折腾

**Comment by Giglizeng** [comment]
> > > 试试，OpenSSL编译时，编译libopenssl-legacy吧。
> > 
> > 
> > 试过没戏，暂时先停留在老版本
> 
> 看看机场节点加密算法是什么, 在不在openssl3遗弃算法里, 然后看看libopenssl3+libopenssl-legacy这两个库装了没有. 我是这个问题.

谢谢指点

**Comment by SakuraFallingMad** [comment]
如果是升级安装openwrt的话，还要启用这个legacy provider，在/etc/config/openssl
`config engine 'devcrypto'
        option enabled '1'
        option builtin '1'

config provider 'legacy'
        option enabled '1'
`
可以运行  `openssl list -providers` 测试是否启用

**Comment by pbclaodentm** [comment]
其实跟着升级这么多次，确实没发现有啥大变化而且出问题的概率很大，估计自己用的协议就那么几个老的，所以一直停在4.66-8，反正对于使用者来说透明才是最好的。

**Comment by WYC-2020** [comment]
> 如果是升级安装openwrt的话，还要启用这个legacy provider，在/etc/config/openssl `config engine 'devcrypto' option enabled '1' option builtin '1'
> 
> config provider 'legacy' option enabled '1' `可以运行 `openssl list -providers` 测试是否启用

这方法亲测有效，如果已经用的3.0的 可以按这个设置 就能兼容了，但是 如果没用3.0的就不建议升级了，这个升级了 增加了协议太多，对于那种小容量的机器是得不偿失，精简能满足自己就是王道，我先把这个升级了顺便把依赖改了 要不然没人会去手动选择legacy

**Comment by Giglizeng** [comment]
> 如果是升级安装openwrt的话，还要启用这个legacy provider，在/etc/config/openssl `config engine 'devcrypto' option enabled '1' option builtin '1'
> 
> config provider 'legacy' option enabled '1' `可以运行 `openssl list -providers` 
非常感谢！

**Comment by SakuraFallingMad** [comment]
> > 如果是升级安装openwrt的话，还要启用这个legacy provider，在/etc/config/openssl `config engine 'devcrypto' option enabled '1' option builtin '1'
> > config provider 'legacy' option enabled '1' `可以运行 `openssl list -providers` 测试是否启用
> 
> 这方法亲测有效，如果已经用的3.0的 可以按这个设置 就能兼容了，但是 如果没用3.0的就不建议升级了，这个升级了 增加了协议太多，对于那种小容量的机器是得不偿失，精简能满足自己就是王道，我先把这个升级了顺便把依赖改了 要不然没人会去手动选择legacy

个人认为，较为妥协的覆盖全协议的，小容量机器的选择备案测试只安装Shadowsocks_Libev_Client+ShadowsocksR_Libev_Client+Simple_Obfs+singbox+tuic_client+brook+haproxy

**Comment by Giglizeng** [comment]
> openssl list -providers

修改了文件，但此命令：openssl list -providers无法运行，请问是什么原因，谢谢！

**Comment by Giglizeng** [comment]
> 如果是升级安装openwrt的话，还要启用这个legacy provider，在/etc/config/openssl `config engine 'devcrypto' option enabled '1' option builtin '1'
> 
> config provider 'legacy' option enabled '1' `可以运行 `openssl list -providers` 测试是否启用

![image](https://github.com/xiaorouji/openwrt-passwall/assets/145970037/3fdfc44d-e340-4920-bdb5-8199273d1b7d)
显示运行后，SS和SSR节点依然不行，openssl版本为3.0.11

**Comment by Giglizeng** [comment]
> libopenssl

请问如何查看，如何添加库，我是小白，非常感谢！

**Comment by Giglizeng** [comment]
综合[SakuraFallingMad](https://github.com/SakuraFallingMad)，以及[xuhuanzy](https://github.com/xuhuanzy)的方法得以解决，再次感谢大家！本帖终结！
