### ISSUE TITLE
[Bug]: sing-box分流启动时，报错category-games@!cn not exists!

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#2830]
### 描述您遇到的bug

sing-box分流启动时，报错category-games@!cn not exists!，看了下是分流第二条规则`ProxyGame`里添加的
https://github.com/xiaorouji/openwrt-passwall/blob/addb208c8795f5fb1d39084ec408a734c4a96041/luci-app-passwall/root/usr/share/passwall/0_default_config#L158-L162
查阅了下v2ray的geosite，并没有包含!cn这个属性，也没看到涉及反选的语法，不清楚这块是否为bug

### 复现此Bug的步骤

使用sing-box分流

### 您想要实现的目的

不报错

### 日志信息

```
ERROR router: failed to initialize geosite: read geosite: code category-games@!cn not exists!
```

### 系统相关信息

昨天9月25日编译的最新passwall，这个passwall1、2都存在

**Comment by Gzxhwq** [comment]
geosite:category-games 下面并没有 @!cn的标签，这个用法是错的，起码几个常用的库都是引用v2fly/domain-list-community的数据。

虽然*ray没报错，但是这个条目应该就是不成立的。

**Comment by swxk521** [comment]
默认规则有些多杂了，留下几个主要规则，其他大家自定义就好了。
