### ISSUE TITLE
[Bug]: IPv6节点不能正常检测延时

### ISSUE THREAD

**Issue by kumoonkey** [xiaorouji/openwrt-package#2833]
### 描述您遇到的bug

添加IPv6节点，无论是IP地址方式还是域名(只能解析为IPv6地址)方式，节点检测都是超时，但能正常使用。

### 复现此Bug的步骤

添加IPv6节点

### 您想要实现的目的

能正常检测延时

### 日志信息

无

### 系统相关信息

Passwall 版本	【 4.70-8 】

### 其他信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/62165277/1c717e3f-a0da-4240-9bb5-fb496820b0e7)

**Comment by hcym** [comment]
这个一直比较灵异，有的版本可以，编译配置一模一样，大雕的ssrp也是如此，哪个源码很少变化的

**Comment by kumoonkey** [comment]
我用的是这里的版本，硬件是R2S和X86
https://github.com/stupidloud/nanopi-openwrt/releases
无论哪个版本，IPv6节点延时检测都是超时。

**Comment by gnz1123** [comment]
这应该不是passwall的问题，有的人编译的固件v6延迟一直都正常，有的偶尔几个版本会出现这个问题。

**Comment by hcym** [comment]
肯定不是pass的事，一旦有延迟显示，，p1p2p＋也有，没有就都没有。而且用官方master，2305，大雕的lede，还有imm那边的都有这些情况，也完全不影响使用，因为我的都是ipv6检点，对这个比较敏感，毕竟看线路状态直观
