### ISSUE TITLE
[Bug]: 拉取最新源码编译hysteria失败

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#2836]
### 描述您遇到的bug

拉取最新源码编译x86、r2s固件编译hysteria失败

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

修复bug

### 日志信息

Building targets
golang.org/x/exp/constraints
golang.org/x/crypto/internal/alias
golang.org/x/crypto/cryptobyte/asn1
github.com/apernet/quic-go/internal/utils/ringbuffer
golang.org/x/net/internal/iana
github.com/apernet/hysteria/core/internal/pmtud
image/color
github.com/pelletier/go-toml/v2/internal/characters
crypto/sha1
runtime/cgo
github.com/apernet/hysteria/core/errors
github.com/apernet/quic-go/internal/protocol
golang.org/x/crypto/chacha20
github.com/apernet/quic-go/congestion
golang.org/x/crypto/internal/poly1305
golang.org/x/sys/cpu
github.com/apernet/hysteria/core/internal/congestion/common
github.com/apernet/hysteria/core/internal/congestion/brutal
golang.org/x/crypto/cryptobyte
golang.org/x/crypto/hkdf
golang.org/x/crypto/chacha20poly1305
github.com/apernet/quic-go/quicvarint
github.com/apernet/quic-go/internal/utils/linkedlist
github.com/apernet/quic-go/internal/utils/tree
golang.org/x/exp/rand
golang.org/x/net/bpf
golang.org/x/sys/unix
golang.org/x/net/http2/hpack
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
github.com/quic-go/qpack
golang.org/x/text/unicode/norm
golang.org/x/text/secure/bidirule
github.com/davecgh/go-spew/spew
net
github.com/pmezard/go-difflib/difflib
github.com/stretchr/objx
golang.org/x/net/idna
gopkg.in/yaml.v3
net/http/internal/testcert
internal/saferio
encoding/gob
github.com/txthinking/runnergroup
github.com/apernet/hysteria/app/internal/url
image
rsc.io/qr/gf256
rsc.io/qr/coding
golang.org/x/crypto/blake2b
github.com/patrickmn/go-cache
rsc.io/qr
github.com/hashicorp/golang-lru/v2/internal
github.com/mdp/qrterminal/v3
github.com/hashicorp/golang-lru/v2/simplelru
github.com/hashicorp/golang-lru/v2
github.com/klauspost/cpuid/v2
github.com/libdns/libdns
go.uber.org/atomic
go.uber.org/multierr
go.uber.org/zap/buffer
go.uber.org/zap/internal/bufferpool
go.uber.org/zap/internal/color
go.uber.org/zap/internal/exit
github.com/fsnotify/fsnotify
go.uber.org/zap/zapcore
github.com/spf13/afero/internal/common
github.com/spf13/afero/mem
golang.org/x/text/runes
html/template
github.com/spf13/jwalterweatherman
github.com/spf13/viper/internal/encoding
github.com/subosito/gotenv
github.com/hashicorp/hcl/hcl/strconv
github.com/hashicorp/hcl/hcl/token
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/parser
go.uber.org/zap/internal
github.com/hashicorp/hcl/json/token
github.com/hashicorp/hcl/json/scanner
crypto/x509
github.com/apernet/hysteria/core/internal/congestion/bbr
# github.com/apernet/hysteria/core/internal/congestion/bbr
../../core/internal/congestion/bbr/bandwidth_sampler.go:634:28: undefined: min
../../core/internal/congestion/bbr/bandwidth_sampler.go:641:18: undefined: max
../../core/internal/congestion/bbr/bandwidth_sampler.go:666:17: undefined: max
../../core/internal/congestion/bbr/bandwidth_sampler.go:668:18: undefined: max
../../core/internal/congestion/bbr/bandwidth_sampler.go:671:43: undefined: min
../../core/internal/congestion/bbr/bandwidth_sampler.go:822:21: undefined: min
../../core/internal/congestion/bbr/bbr_sender.go:393:10: undefined: min
../../core/internal/congestion/bbr/bbr_sender.go:566:9: undefined: max
../../core/internal/congestion/bbr/bbr_sender.go:816:20: undefined: max
../../core/internal/congestion/bbr/bbr_sender.go:824:17: undefined: max
../../core/internal/congestion/bbr/bbr_sender.go:824:17: too many errors
note: module requires Go 1.21
github.com/apernet/quic-go/internal/utils
golang.org/x/net/internal/socket
net/textproto
vendor/golang.org/x/net/http/httpproxy
github.com/txthinking/socks5
vendor/golang.org/x/net/http/httpguts
golang.org/x/net/ipv6
golang.org/x/net/ipv4
mime/multipart
golang.org/x/net/http/httpguts
github.com/apernet/go-tproxy
github.com/oschwald/maxminddb-golang
github.com/apernet/hysteria/extras/obfs
crypto/tls
github.com/apernet/hysteria/extras/transport/udphop
golang.org/x/crypto/ocsp
github.com/spf13/pflag
github.com/mitchellh/mapstructure
github.com/oschwald/geoip2-golang
github.com/apernet/hysteria/extras/outbounds/acl
github.com/spf13/cast
github.com/hashicorp/hcl/json/parser
github.com/hashicorp/hcl
github.com/spf13/viper/internal/encoding/dotenv
github.com/hashicorp/hcl/hcl/printer
gopkg.in/ini.v1
github.com/spf13/cobra
github.com/spf13/viper/internal/encoding/hcl
github.com/spf13/viper/internal/encoding/json
github.com/pelletier/go-toml/v2/internal/danger
github.com/pelletier/go-toml/v2/unstable
github.com/pelletier/go-toml/v2/internal/tracker
github.com/pelletier/go-toml/v2
github.com/spf13/viper/internal/encoding/ini
github.com/spf13/viper/internal/encoding/yaml
net/http/httptrace
github.com/miekg/dns
github.com/quic-go/qtls-go1-20
net/http
github.com/spf13/viper/internal/encoding/toml
github.com/apernet/quic-go/internal/qtls
github.com/apernet/quic-go/internal/qerr
github.com/apernet/quic-go/internal/wire
github.com/apernet/quic-go/internal/flowcontrol
github.com/apernet/quic-go/logging
github.com/apernet/quic-go/internal/handshake
github.com/apernet/quic-go/internal/congestion
github.com/apernet/quic-go/internal/ackhandler
github.com/apernet/quic-go/internal/logutils
github.com/apernet/quic-go
github.com/apernet/hysteria/core/internal/protocol
net/http/httptest
github.com/apernet/hysteria/extras/masq
github.com/apernet/hysteria/core/internal/frag
github.com/babolivier/go-doh-client
go.uber.org/zap
github.com/spf13/afero
github.com/stretchr/testify/assert
github.com/mholt/acmez/acme
github.com/magiconair/properties
github.com/stretchr/testify/mock
github.com/mholt/acmez
github.com/apernet/hysteria/core/internal/utils
github.com/apernet/quic-go/http3
github.com/spf13/viper/internal/encoding/javaproperties
net/http/httputil
github.com/spf13/viper
github.com/caddyserver/certmagic

make[3]: *** [Makefile:62: /home/x86.6.1/lede/build_dir/target-x86_64_musl/hysteria-app-v2.0.3/.built] Error 1
make[3]: Leaving directory '/home/x86.6.1/lede/feeds/passwall_packages/hysteria'
time: package/feeds/passwall_packages/hysteria/compile#68.35#7.19#40.86
    ERROR: package/feeds/passwall_packages/hysteria failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall_packages/hysteria/compile] Error 1
make[2]: Leaving directory '/home/x86.6.1/lede'
make[1]: *** [package/Makefile:110: /home/x86.6.1/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.6.1/lede'
make: *** [/home/x86.6.1/lede/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

最新版本

**Comment by Gzxhwq** [comment]
hy 2.0.3要求go 1.21，lean那边还没升级到1.21
