### ISSUE TITLE
[Bug]: lean源码编译v2ray-plugin报错

### ISSUE THREAD

**Issue by firkerword** [xiaorouji/openwrt-package#2838]
### 描述您遇到的bug

https://github.com/coolsnowwolf/packages/commit/f937504996886608d3803b63cc6288790bc6a19e
lean源码更新go版本后，v2ray-plugin又出现错误

### 复现此Bug的步骤

lean源码编译

### 您想要实现的目的

修复BUG

### 日志信息

Building targets
github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

make[3]: *** [Makefile:44: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-5.7.0/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/openwrt-passwall/v2ray-plugin'
time: package/openwrt-passwall/v2ray-plugin/compile#0.65#0.44#0.96
    ERROR: package/openwrt-passwall/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/openwrt-passwall/v2ray-plugin/compile] Error 1

### 系统相关信息

PKG_NAME:=luci-app-passwall
PKG_VERSION:=4.70-10

**Comment by bi4tms** [comment]
v2ray-plugin作者那边已经出了更新，不知道是否会合并 @Gzxhwq

**Comment by swxk521** [comment]
+1
