### ISSUE TITLE
[Feature Request]: 关于HAproxy负债均衡和Socks主备切换

### ISSUE THREAD

**Issue by sixrui** [xiaorouji/openwrt-package#2839]
### 描述你想要的新功能

请教一下，在HAproxy负载均衡里当设置多个主节点时，这个负载均衡并非是自动选择一个延迟或网速最好的服务器进行连接，而是指多个服务器共同承担网络流量吧？
另外如果只设置一个主多个备当故障切换用的时候，和Socks节点配置里的主备切换，哪个好用一点？

### 描述你想要的解决方案

最佳方式的节点优选和故障切换

**Comment by handsomeji** [comment]
負載均衡使用passwall內置可實現 多線程帶寬疊加+故障切換。
如果不需要疊加多線程帶寬，請直接使用socks的自動切換。
