### ISSUE TITLE
[Bug]: 请求更新仓库brook到支持go 1.21版本

### ISSUE THREAD

**Issue by lwb1978** [xiaorouji/openwrt-package#2841]
### 描述您遇到的bug

现在各大仓库的go版本均更新到了1.21版，而且Sing-box、hysteria也要求高版本编译，导致passwall-packages仓库的brook编译错误，建议老大打个补丁升级一下。

### 复现此Bug的步骤

拉取passwall-packages仓库的brook

### 您想要实现的目的

编译成功

### 日志信息

无

### 系统相关信息

最新版本

**Comment by super27036** [comment]
同样问题，brook 编译错误

**Comment by lwb1978** [comment]
还有v2ray-core也炸了

**Comment by lxiaya** [comment]
[010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798875/010-update-iploc-to-fix-build-for-riscv64.patch)
[020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798876/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch)
替换brook/patches文件夹的patch

**Comment by lxiaya** [comment]
> 还有v2ray-core也炸了

[v2ray-core.zip](https://github.com/xiaorouji/openwrt-passwall/files/12798912/v2ray-core.zip)
解压替换v2ray-core文件夹

**Comment by authon** [comment]
> > 还有v2ray-core也炸了
> 
> [v2ray-core.zip](https://github.com/xiaorouji/openwrt-passwall/files/12798912/v2ray-core.zip) 解压替换v2ray-core文件夹

GitHub action怎么搞

**Comment by lwb1978** [comment]
> > > 还有v2ray-core也炸了
> > 
> > 
> > [v2ray-core.zip](https://github.com/xiaorouji/openwrt-passwall/files/12798912/v2ray-core.zip) 解压替换v2ray-core文件夹
> 
> GitHub action怎么搞

拉 immortalwrt 仓库的相关代码

**Comment by lwb1978** [comment]
> [010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798875/010-update-iploc-to-fix-build-for-riscv64.patch) [020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798876/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch) 替换brook/patches文件夹的patch

感谢回复，我直接拉immortalwrt仓库的相关组件来解决的，但是作为passwall的必备依赖，只是觉得passwall官方应该更新自己的库才是。

**Comment by lxiaya** [comment]
> > [010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798875/010-update-iploc-to-fix-build-for-riscv64.patch) [020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/xiaorouji/openwrt-passwall/files/12798876/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch) 替换brook/patches文件夹的patch
> 
> 感谢回复，我直接拉immortalwrt仓库的相关组件来解决的，但是作为passwall的必备依赖，只是觉得passwall官方应该更新自己的库才是。

建个自己的库，想怎么换怎么改都可以 还可以按照自己需求精简定制！

**Comment by Gzxhwq** [comment]
Fixed.
