### ISSUE TITLE
[Bug]: 编译passwall报错，已安装go1.21。

### ISSUE THREAD

**Issue by tianhbd** [xiaorouji/openwrt-package#2842]
### 描述您遇到的bug

官方openwrt23.5源码，已编译出固件，单独编译passwall时候始终报错。

### 复现此Bug的步骤

openwrt/build_dir/target-x86_64_musl/linux-x86_64下ipset-7.17目录存在问题，反复删除重新编译好几次。

### 您想要实现的目的

完整编译出插件。

### 日志信息

configure: error: Invalid kernel source directory /lib/modules/4.15.0-213-generic/source
Makefile:74: recipe for target '/home/tian/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ipset-7.17/.configured_68b329da9893e34099c7d8ad5cb9c940' failed
make[2]: *** [/home/tian/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ipset-7.17/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/tian/openwrt/package/network/utils/ipset'
time: package/network/utils/ipset/compile#40.30#2.32#42.99
    ERROR: package/network/utils/ipset failed to build.
package/Makefile:118: recipe for target 'package/network/utils/ipset/compile' failed
make[1]: *** [package/network/utils/ipset/compile] Error 1
make[1]: Leaving directory '/home/tian/openwrt'
/home/tian/openwrt/include/toplevel.mk:230: recipe for target 'package/feeds/passwall/luci-app-passwall/compile' failed
make: *** [package/feeds/passwall/luci-app-passwall/compile] Error 2

### 系统相关信息

4.70.10

**Comment by Gzxhwq** [comment]
23.05 SDK编译测试通过。
你的是ipset编译问题，与passwall没有直接关联。请检查你的编译环境和方法。

**Comment by tianhbd** [comment]
感谢🙏🏻
