### ISSUE TITLE
[Bug]: 搭配hysteria2 使用会间歇性断外网

### ISSUE THREAD

**Issue by small-white-rabbit** [xiaorouji/openwrt-package#2845]
### 描述您遇到的bug

用hy2的时候 google会时不时的打不开，像间歇性断网一样，换回老版hy1就是正常的，不知道是我的个例还是普遍现象

也不能确定是否是节点hy2服务端部署有问题，来看看有没有相似情况的兄弟

另一个问题就是添加节点hy2不能直接链接添加，如果使用节点内导入又需要手动把密码加进去，希望能够修复这个问题

### 复现此Bug的步骤

RT

### 您想要实现的目的

   RT

### 日志信息

   RT

### 系统相关信息

   RT

**Comment by small-white-rabbit** [comment]
补充：发现一个类似问题的兄弟，但是用的不是hy2，所以会不会是最新版passwall哪里有问题所以导致间歇性断外网

**Comment by Gzxhwq** [comment]
sing-box的tuic和hy2，官版的hy2，都曾经见到有人反馈过断流现象

**Comment by swxk521** [comment]
> 补充：发现一个类似问题的兄弟，但是用的不是hy2，所以会不会是最新版passwall哪里有问题所以导致间歇性断外网

不是passwall问题，passwall本质还是用的hysteria和sing-box，估计是hy2本身的问题，毕竟刚出不久，等迭代几次应该就差不多了。不过我用hy2问题不大，udp方面比hy1好。

**Comment by microdockman** [comment]
> sing-box的tuic和hy2，官版的hy2，都曾经见到有人反馈过断流现象

sing-box vmess 直接就是网站打不开，gmail可以YouTube不可以，
xray       vmess一切正常，但是订阅就默认都是sing-box vmess
是不是sing-box 要选其他协议才可以

**Comment by zakizou** [comment]
passwall和passwall2都会断流连不上，同样的hy2节点，ios和Windows的客户端没有这个问题，而且规则模式（只开了屏蔽广告）下断流，直连的也会断

**Comment by wzs1566** [comment]
同样的问题。h2会突然断网，然后重启passwall、重启openwrt都没有，但是用手机测试后发现节点没问题。有时运行状态显示TCP、UDP没运行，换非h2的节点才能重启passwall

**Comment by 466878778** [comment]
我测试是 启用 端口跳跃 只要到端口跳跃时间点 就断网了，关了端口跳跃 使用固定端口好像就没问题，不知道是hy2 客户端的bug 还是 passwall 页里面设置跟hy2 里面的设置对不上 的原因。总之关了端口跳跃就没问题
