### ISSUE TITLE
[Bug]:   ERROR: package/feeds/packages/sing-box failed to build.

### ISSUE THREAD

**Issue by ted-zheng** [xiaorouji/openwrt-package#2847]
### 描述您遇到的bug

编译失败：ERROR: package/feeds/packages/sing-box failed to build.，哪位大神帮忙看看原因，编译系统用的：ubuntu23.10

### 复现此Bug的步骤

全部删除，重新clone也一样无法完成编译

### 您想要实现的目的

完成编译

### 日志信息

make[3]: Leaving directory '/home/udb/openwrt/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#0.29#0.06#0.31
make[3]: Entering directory '/home/udb/openwrt/feeds/packages/net/sing-box'
rm -f /home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.built
touch /home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/udb/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/udb/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/sagernet/sing-box" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/sagernet/sing-box/cmd/sing-box" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3" GO_BUILD_DIR="/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.go_work/build" GO_BUILD_BIN_DIR="/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/udb/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3=sing-box-1.4.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/include -I/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include/fortify -I/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3=sing-box-1.4.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/lib -L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro" GOPATH="/home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.go_work/build" GOCACHE="/home/udb/openwrt/tmp/go-build" GOMODCACHE="/home/udb/openwrt/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash ../../lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1696622369' -linkmode external -extldflags '-L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/lib -L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib -fuse-ld=bfd -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X github.com/sagernet/sing-box/constant.Version=1.4.3 -buildid '1696622369' -linkmode external -extldflags '-L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/lib -L/home/udb/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib -fuse-ld=bfd -Wl,-z,now -Wl,-z,relro'" -tags "with_clash_api,with_gvisor,with_quic,with_reality_server,with_utls,with_wireguard" 
Finding targets

Building targets
go: downloading github.com/klauspost/compress v1.15.15
../../../../../dl/go-mod-cache/github.com/sagernet/utls@v0.0.0-20230309024959-6732c2ab36f2/u_handshake_client.go:15:2: github.com/klauspost/compress@v1.15.15: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.15.15.zip: 403 Forbidden

make[3]: *** [Makefile:149: /home/udb/openwrt/build_dir/target-x86_64_musl/sing-box-1.4.3/.built] Error 1
make[3]: Leaving directory '/home/udb/openwrt/feeds/packages/net/sing-box'
time: package/feeds/packages/sing-box/compile#1.48#0.35#18.55
    ERROR: package/feeds/packages/sing-box failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/sing-box/compile] Error 1
make[2]: Leaving directory '/home/udb/openwrt'
make[1]: *** [package/Makefile:114: /home/udb/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/udb/openwrt'
make: *** [/home/udb/openwrt/include/toplevel.mk:232：world] 错误 2

### 系统相关信息

openwrt源码：https://github.com/openwrt/openwrt:main

feed源：
src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main

**Comment by Gzxhwq** [comment]
下不到包，开全局梯子吧

**Comment by ted-zheng** [comment]
> 下不到包，开全局梯子吧

make[3]: Entering directory '/home/udb/openwrt/feeds/passwall_packages/gn'
ninja -C /home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/out
ninja: Entering directory `/home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/out'
[1/5] CXX src/gn/resolved_target_deps_unittest.o
FAILED: src/gn/resolved_target_deps_unittest.o 
g++ -MMD -MF src/gn/resolved_target_deps_unittest.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/resolved_target_deps_unittest.cc -o src/gn/resolved_target_deps_unittest.o
In file included from ../src/gn/resolved_target_deps.h:8,
                 from ../src/gn/resolved_target_deps_unittest.cc:5:
../src/base/containers/span.h:393:12: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
  393 | span<const uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
      |            ^~~~~~~
../src/base/containers/span.h:393:75: error: template argument 1 is invalid
  393 | span<const uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
      |                                                                           ^
../src/base/containers/span.h: In function 'int base::as_bytes(span<T, Extent>)':
../src/base/containers/span.h:395:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
  395 |   return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
      |                                  ^~~~~~~
../src/base/containers/span.h:395:34: error: expected '>' before 'uint8_t'
../src/base/containers/span.h:395:34: error: expected '(' before 'uint8_t'
  395 |   return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
      |                                  ^~~~~~~
      |                                  (
../src/base/containers/span.h:395:34: error: 'uint8_t' was not declared in this scope
  395 |   return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
      |                                  ^~~~~~~
../src/base/containers/span.h:19:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   18 | #include "base/stl_util.h"
  +++ |+#include <cstdint>
   19 | 
../src/base/containers/span.h:395:42: error: expected primary-expression before '>' token
  395 |   return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
      |                                          ^
../src/base/containers/span.h:395:69: error: expected ')' before '}' token
  395 |   return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
      |                                                                     ^
      |                                                                     )
../src/base/containers/span.h: At global scope:
../src/base/containers/span.h:401:6: error: 'uint8_t' was not declared in this scope
  401 | span<uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
      |      ^~~~~~~
../src/base/containers/span.h:401:6: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
../src/base/containers/span.h:401:69: error: template argument 1 is invalid
  401 | span<uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
      |                                                                     ^
../src/base/containers/span.h: In function 'int base::as_writable_bytes(span<T, Extent>)':
../src/base/containers/span.h:403:28: error: 'uint8_t' does not name a type
  403 |   return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
      |                            ^~~~~~~
../src/base/containers/span.h:403:28: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
../src/base/containers/span.h:403:35: error: expected '>' before '*' token
  403 |   return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
      |                                   ^
../src/base/containers/span.h:403:35: error: expected '(' before '*' token
  403 |   return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
      |                                   ^
      |                                   (
../src/base/containers/span.h:403:36: error: expected primary-expression before '>' token
  403 |   return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
      |                                    ^
../src/base/containers/span.h:403:63: error: expected ')' before '}' token
  403 |   return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
      |                                                               ^
      |                                                               )
../src/base/containers/span.h:403:63: error: cannot convert '<brace-enclosed initializer list>' to 'int' in return
[2/5] CXX src/gn/desc_builder.o
FAILED: src/gn/desc_builder.o 
g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
../src/gn/desc_builder.cc: In member function 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)':
../src/gn/desc_builder.cc:179:21: error: redundant move in return statement [-Werror=redundant-move]
  179 |     return std::move(res);
      |            ~~~~~~~~~^~~~~
../src/gn/desc_builder.cc:179:21: note: remove 'std::move' call
../src/gn/desc_builder.cc: In instantiation of 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const std::vector<T>&) [with T = Value]':
../src/gn/desc_builder.cc:193:27:   required from here
../src/gn/desc_builder.cc:170:25: error: redundant move in return statement [-Werror=redundant-move]
  170 |     return std::move(res);
      |                         ^
../src/gn/desc_builder.cc:170:25: note: remove 'std::move' call
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:61: /home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/.built] Error 1
make[3]: Leaving directory '/home/udb/openwrt/feeds/passwall_packages/gn'
time: package/feeds/passwall_packages/gn/host-compile#1.88#0.11#1.57
    ERROR: package/feeds/passwall_packages/gn [host] failed to build.
make[2]: *** [package/Makefile:118: package/feeds/passwall_packages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/udb/openwrt'
make[1]: *** [package/Makefile:114: /home/udb/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/udb/openwrt'
make: *** [/home/udb/openwrt/include/toplevel.mk:232：world] 错误 2

@Gzxhwq 还是没过，不过错误不一样了

**Comment by Gzxhwq** [comment]
不要编译naiveproxy，或者在别处找最新的naiveproxy源。
