### ISSUE TITLE
请求同时支持hysteria和hysteria2协议

### ISSUE THREAD

**Issue by hrgfdz** [xiaorouji/openwrt-package#2848]
### 描述你想要的新功能

hysteria V1 V2不兼容,目前还有V1版本的需求，但是[4.70-10]版本仅支持hysteria2协议，请问能不能同时支持V1与V2版本？

### 描述你想要的解决方案

RT

### 描述你考虑过的替代方案

RT

### 其他信息

RT

**Comment by Gzxhwq** [comment]
sing-box就能同时支持v1和v2 hys协议

**Comment by hrgfdz** [comment]
> sing-box可以同时支持v1和v2 hys协议

但是sing-box内核的hysteria协议不支持端口跳跃功能，能否麻烦加上这个端口跳跃功能呢？

**Comment by Gzxhwq** [comment]
> > sing-box可以同时支持v1和v2 hys协议
> 
> 但是sing-box内核的hysteria协议不支持端口跳跃功能，能否麻烦加上这个端口跳跃功能呢？

这个你去sing-box提，但是世界貌似不太觉得这个功能有用，所以一直都没加。所以提了应该也是close issue。

**Comment by hrgfdz** [comment]
> > > sing-box可以同时支持v1和v2 hys协议
> > 
> > 
> > 但是sing-box内核的hysteria协议不支持端口跳转功能，能否麻烦加上这个端口跳转功能呢？
> 
> 你去唱歌盒提了，但是世界不太觉得这个功能有用，所以一直都没有增加。所以提了也应该关闭问题。

好的，谢谢

**Comment by hrgfdz** [comment]
> > > > sing-box可以同时支持v1和v2 hys协议
> > > 
> > > 
> > > 但是sing-box内核的歇斯底里协议不支持端口跳转功能，能否麻烦加上这个端口跳转功能呢？
> > 
> > 
> > 你去唱歌盒提了，但是世界不太觉得这个功能有用，所以一直都没有增加。所以提了也应该关闭问题。
> 
> 好的，谢谢

sing-box确实没有计划支持端口跳跃功能，所以还是请求passwall同时支持hy1和hy2，因为我这边运营商QOS很严重，有端口跳跃功能可以很好解决这个问题，且目前hy2并不完善！

**Comment by Gzxhwq** [comment]
官方版Hysteria并没有同时提供hy1和hy2的协议支持，而Hysteria 1.x 和 Hysteria 2.x 是不能同时存在的。
如果一定需要使用Hysteria 1.x，你可以回退Passwall到支持Hysteria 1.x的版本 https://github.com/xiaorouji/openwrt-passwall/commit/a0c4d70dc62151e987819d51687e6a0ffef42d58 ，并等待Hysteria 2.x完善。

**Comment by hrgfdz** [comment]
> 官方版Hysteria并没有同时提供hy1和hy2的协议支持，而Hysteria 1.x 和 Hysteria 2.x 是不能同时存在的。 如果一定需要使用Hysteria 1.x，你可以回退Passwall到支持Hysteria 1.x的版本 [a0c4d70](https://github.com/xiaorouji/openwrt-passwall/commit/a0c4d70dc62151e987819d51687e6a0ffef42d58) ，并等待Hysteria 2.x完善。

好的，再次感谢
