### ISSUE TITLE
[Feature Request]: 22.03 中旧版 Iptables 的吞吐量较慢，请使用 NFtables

### ISSUE THREAD

**Issue by samboytech** [xiaorouji/openwrt-package#2849]
### 描述你想要的新功能

首先，请原谅我的语言，因为我正在使用谷歌翻译。 由于防火墙规则是 22.03 和 dnsmasq-full 2.86 中遗留的 Iptables 并使用 Iptables-nft 进行转换，因此速度吞吐量非常慢，慢了十倍 当所有流量（端口）重定向时
https://github.com/moby/moby/issues/39590

尝试旁加载 dnsmasq-full 2.87 或更高版本，出现错误：无法安装 dnsmasq-full，缺少 libubus20210603

### 描述你想要的解决方案

是否可以在 22.03 上安装 dnsmasq-full 2.87 并将防火墙设置为使用 NFtables？ 请评论如何安装它。 多谢

**Comment by handsomeji** [comment]
If for simplicity, please use openwrt 23.05 or openwrt main branch.
