### ISSUE TITLE
[Bug]: ERROR: package/feeds/passwall_packages/gn [host] failed to build.

### ISSUE THREAD

**Issue by ted-zheng** [xiaorouji/openwrt-package#2850]
### 描述您遇到的bug

naiveproxy编译无法通过

### 复现此Bug的步骤

重新拉取源码编译问题相同

### 您想要实现的目的

修复问题，顺利完成编译。

### 日志信息

make[3]: Entering directory '/home/udb/openwrt/feeds/passwall_packages/gn'
ninja -C /home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/out
ninja: Entering directory `/home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/out'
[1/5] CXX src/gn/resolved_target_deps_unittest.o
FAILED: src/gn/resolved_target_deps_unittest.o
g++ -MMD -MF src/gn/resolved_target_deps_unittest.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/resolved_target_deps_unittest.cc -o src/gn/resolved_target_deps_unittest.o
In file included from ../src/gn/resolved_target_deps.h:8,
from ../src/gn/resolved_target_deps_unittest.cc:5:
../src/base/containers/span.h:393:12: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
393 | span<const uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
| ^~~~~~~
../src/base/containers/span.h:393:75: error: template argument 1 is invalid
393 | span<const uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
| ^
../src/base/containers/span.h: In function 'int base::as_bytes(span<T, Extent>)':
../src/base/containers/span.h:395:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
395 | return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
| ^~~~~~~
../src/base/containers/span.h:395:34: error: expected '>' before 'uint8_t'
../src/base/containers/span.h:395:34: error: expected '(' before 'uint8_t'
395 | return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
| ^~~~~~~
| (
../src/base/containers/span.h:395:34: error: 'uint8_t' was not declared in this scope
395 | return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
| ^~~~~~~
../src/base/containers/span.h:19:1: note: 'uint8_t' is defined in header ''; did you forget to '#include '?
18 | #include "base/stl_util.h"
+++ |+#include
19 |
../src/base/containers/span.h:395:42: error: expected primary-expression before '>' token
395 | return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
| ^
../src/base/containers/span.h:395:69: error: expected ')' before '}' token
395 | return {reinterpret_cast<const uint8_t*>(s.data()), s.size_bytes()};
| ^
| )
../src/base/containers/span.h: At global scope:
../src/base/containers/span.h:401:6: error: 'uint8_t' was not declared in this scope
401 | span<uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
| ^~~~~~~
../src/base/containers/span.h:401:6: note: 'uint8_t' is defined in header ''; did you forget to '#include '?
../src/base/containers/span.h:401:69: error: template argument 1 is invalid
401 | span<uint8_t, (X == dynamic_extent ? dynamic_extent : sizeof(T) * X)>
| ^
../src/base/containers/span.h: In function 'int base::as_writable_bytes(span<T, Extent>)':
../src/base/containers/span.h:403:28: error: 'uint8_t' does not name a type
403 | return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
| ^~~~~~~
../src/base/containers/span.h:403:28: note: 'uint8_t' is defined in header ''; did you forget to '#include '?
../src/base/containers/span.h:403:35: error: expected '>' before '' token
403 | return {reinterpret_cast<uint8_t>(s.data()), s.size_bytes()};
| ^
../src/base/containers/span.h:403:35: error: expected '(' before '' token
403 | return {reinterpret_cast<uint8_t>(s.data()), s.size_bytes()};
| ^
| (
../src/base/containers/span.h:403:36: error: expected primary-expression before '>' token
403 | return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
| ^
../src/base/containers/span.h:403:63: error: expected ')' before '}' token
403 | return {reinterpret_cast<uint8_t*>(s.data()), s.size_bytes()};
| ^
| )
../src/base/containers/span.h:403:63: error: cannot convert '' to 'int' in return
[2/5] CXX src/gn/desc_builder.o
FAILED: src/gn/desc_builder.o
g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
../src/gn/desc_builder.cc: In member function 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)':
../src/gn/desc_builder.cc:179:21: error: redundant move in return statement [-Werror=redundant-move]
179 | return std::move(res);
| ~~~~~~~~~^~~~~
../src/gn/desc_builder.cc:179:21: note: remove 'std::move' call
../src/gn/desc_builder.cc: In instantiation of 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const std::vector&) [with T = Value]':
../src/gn/desc_builder.cc:193:27: required from here
../src/gn/desc_builder.cc:170:25: error: redundant move in return statement [-Werror=redundant-move]
170 | return std::move(res);
| ^
../src/gn/desc_builder.cc:170:25: note: remove 'std::move' call
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:61: /home/udb/openwrt/build_dir/hostpkg/gn-2023-04-05-28b7b6c5/.built] Error 1
make[3]: Leaving directory '/home/udb/openwrt/feeds/passwall_packages/gn'
time: package/feeds/passwall_packages/gn/host-compile#1.88#0.11#1.57
ERROR: package/feeds/passwall_packages/gn [host] failed to build.
make[2]: *** [package/Makefile:118: package/feeds/passwall_packages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/udb/openwrt'
make[1]: *** [package/Makefile:114: /home/udb/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/udb/openwrt'
make: *** [/home/udb/openwrt/include/toplevel.mk:232：world] 错误 2

### 系统相关信息

openwrt源码：https://github.com/openwrt/openwrt:main

feed源：
src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main

**Comment by ted-zheng** [comment]
没人碰到和我一样的问题吗？

**Comment by ted-zheng** [comment]
没人和我碰到一样的问题吗？

**Comment by smallprogram** [comment]
我这边没有任何问题，请检查你的网络环境
