### ISSUE TITLE
[Bug]: 负载均衡未绑定在127.0.0.1地址上

### ISSUE THREAD

**Issue by kumoonkey** [xiaorouji/openwrt-package#2851]
### 描述您遇到的bug

现在的passwall负载均衡支持创建一个socks5接口，通过这个socks5接口转换到其它协议，这样负载均衡就可以使用各种不同协议的节点了，这是一个很好的特性。但是存在一个问题，虽然配置界面显示配置在127.0.0.1地址上，实际这个socks5是绑定在所有IP地址上的，这样就对外开放了一个socks5接口，有一定的不安全性。

### 复现此Bug的步骤

配置负载均衡，使用passwall内置的可用性检测。

### 您想要实现的目的

负载均衡socks5接口可以只绑定在127.0.0.1地址上，增加安全性。

### 日志信息

无日志

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/62165277/0bb3f845-47d4-4fa7-8448-9c459a0cde43)

### 系统相关信息

Passwall 版本	【 4.70-8 】

**Comment by handsomeji** [comment]
為什麼默認防火墻規則要accept呢？
