### ISSUE TITLE
[Bug]: 最新源码更新的sing-box无法下载导致编译失败

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#2853]
### 描述您遇到的bug

拉取最新源码，因sing-box无法下载导致编译失败@Gzxhwq

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

通过编译

### 日志信息

curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/SagerNet/sing-box/tar.gz/v1.5.3?/sing-box-1.5.3.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 339k 0 339k 0 0 233k 0 --:--:-- 0:00:01 --:--:-- 234k
Hash of the downloaded file does not match (file: e050f8a588d92547ba277fc8980af8ede544c345684c20e4b008fbc1b1371fb8, requested: 4a57d8ad9c56538067d29c426c21041c982e3d02ce7b898c13d39c91f8f39c7e) - deleting download.
curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/sing-box-1.5.3.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 169 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (22) The requested URL returned error: 404
Download failed.
curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/sing-box-1.5.3.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 169 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
curl: (22) The requested URL returned error: 404
Download failed.
curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/sing-box-1.5.3.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 153 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
curl: (22) The requested URL returned error: 404
Download failed.

### 系统相关信息

最新

**Comment by Gzxhwq** [comment]
Fixed.
