### ISSUE TITLE
[Bug]: op隔段时间pw报错，重启会好但是隔断时间依然报错

### ISSUE THREAD

**Issue by lizhiwei8061** [xiaorouji/openwrt-package#2858]
### 描述您遇到的bug

不知道是固件问题还是pw问题，出现问题就无法上网了
![pw](https://github.com/xiaorouji/openwrt-passwall/assets/121220591/cb79f090-6242-4642-b14f-61ce8d42f7e2)

### 复现此Bug的步骤

0

### 您想要实现的目的

0

### 日志信息

0

### 系统相关信息

0

**Comment by handsomeji** [comment]
固件问题/空间满了。

**Comment by lizhiwei8061** [comment]
> 巩固问题/空间满了。

好的 那我先不用pw了
