### ISSUE TITLE
[Feature Request]: 规则列表里 增加按关键字过滤网址

### ISSUE THREAD

**Issue by Helifengworld** [xiaorouji/openwrt-package#2860]
### 描述你想要的新功能

passwall 规则列表 直连 代理  屏蔽 规则里只能按完整域名来添加规则，
希望增加按域名关键字来增加，因为有很多大站有太多的子域名。
类似于。Openclash 规则覆写里的 按域名关键字添加

### 描述你想要的解决方案

类似于。Openclash 规则覆写里的 按域名关键字添加

**Comment by handsomeji** [comment]
请使用Passwall2，并配置对应的分流规则。
