### ISSUE TITLE
[Bug]: 升级 4.71.1 提示  pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall

### ISSUE THREAD

**Issue by Helifengworld** [xiaorouji/openwrt-package#2861]
### 描述您遇到的bug

从 4.7.10 升级 4.71.1 怎么也不成功

以前从其他版本升级 到 4.7.10很顺利。

这次新版本 4.71.1 提示  pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall

但是这个依赖不知道从哪里找。 Releases 列表里打包好的所有依赖里也找不到

希望修复这个问题

### 复现此Bug的步骤

升级4.71.1出现 pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall

### 您想要实现的目的

正常升级4.71.1

### 日志信息

nothing...

### 截图

![Snipaste_2023-10-16_10-01-55](https://github.com/xiaorouji/openwrt-passwall/assets/114859092/5f2ceb63-15db-4ea4-9d45-a87a860411f8)

### 系统相关信息

finalshell

**Comment by tianhbd** [comment]
编译的时候选上就行了。

**Comment by smallprogram** [comment]
#2786

**Comment by Helifengworld** [comment]
> #2786

这个办法真是个人才。。直接解决。万分感谢！！！！
