### ISSUE TITLE
[Bug]: 拉取最新源码报错，提示luci-app-passwall无法编译

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#2863]
### 描述您遇到的bug

luci-app-passwall无法编译 @xiaorouji @smallprogram 

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

修复bug

### 日志信息

install -d -m0755 /home/x86.6.1/lede/bin/packages/x86_64/passwall
/home/x86.6.1/lede/staging_dir/host/bin/fakeroot /home/x86.6.1/lede/staging_dir/host/bin/bash /home/x86.6.1/lede/scripts/ipkg-build -m "" /home/x86.6.1/lede/build_dir/target-x86_64_musl/luci-app-passwall/ipkg-all/luci-app-passwall /home/x86.6.1/lede/bin/packages/x86_64/passwall
/home/x86.6.1/lede/staging_dir/host/bin/find: '/home/x86.6.1/lede/build_dir/target-x86_64_musl/luci-app-passwall/ipkg-all/luci-app-passwall/etc/config/passwall': No such file or directory
Packaged contents of /home/x86.6.1/lede/build_dir/target-x86_64_musl/luci-app-passwall/ipkg-all/luci-app-passwall into /home/x86.6.1/lede/bin/packages/x86_64/passwall/luci-app-passwall_4.71-2 -smartdns-dev_all.ipk
bash: line 0: [: /home/x86.6.1/lede/bin/packages/x86_64/passwall/luci-app-passwall_4.71-2: binary operator expected
make[3]: *** [/home/x86.6.1/lede/feeds/luci/luci.mk:256: /home/x86.6.1/lede/bin/packages/x86_64/passwall/luci-app-passwall_4.71-2] Error 2
make[3]: Leaving directory '/home/x86.6.1/lede/feeds/passwall/luci-app-passwall'
time: package/feeds/passwall/luci-app-passwall/compile#2.06#0.92#4.37
    ERROR: package/feeds/passwall/luci-app-passwall failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/luci-app-passwall/compile] Error 1
make[2]: Leaving directory '/home/x86.6.1/lede'
make[1]: *** [package/Makefile:110: /home/x86.6.1/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.6.1/lede'
make: *** [/home/x86.6.1/lede/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

最新版本

**Comment by handsomeji** [comment]
重新拉再试下

**Comment by bi4tms** [comment]
> 重新拉再试下

 @xiaorouji
重新拉取后编译依旧报错，日志如下：
ln -s /home/x86.6.1/lede/bin/targets/x86/64/packages/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86; ln -s /home/x86.6.1/lede/bin/packages/x86_64/base/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86; ln -s /home/x86.6.1/lede/bin/packages/x86_64/luci/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86; ln -s /home/x86.6.1/lede/bin/packages/x86_64/packages/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86; ln -s /home/x86.6.1/lede/bin/packages/x86_64/passwall/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86; ln -s /home/x86.6.1/lede/bin/packages/x86_64/passwall_packages/*.ipk /home/x86.6.1/lede/staging_dir/packages/x86;  
find /home/x86.6.1/lede/staging_dir/target-x86_64_musl/root-x86 -type d | xargs -r chmod 0755
rm -rf /home/x86.6.1/lede/build_dir/target-x86_64_musl/root-x86 /home/x86.6.1/lede/build_dir/target-x86_64_musl/root.orig-x86
mkdir -p /home/x86.6.1/lede/build_dir/target-x86_64_musl/root-x86/tmp
IPKG_NO_SCRIPT=1 IPKG_INSTROOT=/home/x86.6.1/lede/build_dir/target-x86_64_musl/root-x86 TMPDIR=/home/x86.6.1/lede/build_dir/target-x86_64_musl/root-x86/tmp /home/x86.6.1/lede/staging_dir/host/bin/opkg --offline-root /home/x86.6.1/lede/build_dir/target-x86_64_musl/root-x86 --force-postinstall --add-dest root:/ --add-arch all:100 --add-arch x86_64:200 install $(cat /home/x86.6.1/lede/tmp/opkg_install_list)
/home/x86.6.1/lede/staging_dir/host/bin/opkg: unrecognized option '-smartdns-dev_all.ipk'
opkg must have one sub-command argument
usage: opkg [options...] sub-command [arguments...]
where sub-command is one of:

Package Manipulation:
	update			Update list of available packages
	upgrade <pkgs>		Upgrade packages
	install <pkgs>		Install package(s)
	configure <pkgs>	Configure unpacked package(s)
	remove <pkgs|regexp>	Remove package(s)
	flag <flag> <pkgs>	Flag package(s)
	 <flag>=hold|noprune|user|ok|installed|unpacked (one per invocation)

Informational Commands:
	list			List available packages
	list-installed		List installed packages
	list-upgradable		List installed and upgradable packages
	list-changed-conffiles	List user modified configuration files
	files <pkg>		List files belonging to <pkg>
	search <file|regexp>	List package providing <file>
	find <regexp>		List packages whose name or description matches <regexp>
	info [pkg|regexp]	Display all info for <pkg>
	status [pkg|regexp]	Display all status for <pkg>
	download <pkg>		Download <pkg> to current directory
	compare-versions <v1> <op> <v2>
	                    compare versions using <= < > >= = << >>
	print-architecture	List installable package architectures
	depends [-A] [pkgname|pat]+
	whatdepends [-A] [pkgname|pat]+
	whatdependsrec [-A] [pkgname|pat]+
	whatrecommends[-A] [pkgname|pat]+
	whatsuggests[-A] [pkgname|pat]+
	whatprovides [-A] [pkgname|pat]+
	whatconflicts [-A] [pkgname|pat]+
	whatreplaces [-A] [pkgname|pat]+

Options:
	-A			Query all packages not just those installed
	-V[<level>]		Set verbosity level to <level>.
	--verbosity[=<level>]	Verbosity levels:
					0 errors only
					1 normal messages (default)
					2 informative messages
					3 debug
					4 debug level 2
	-f <conf_file>		Use <conf_file> as the opkg configuration file
	--conf <conf_file>
	--cache <directory>	Use a package cache
	-d <dest_name>		Use <dest_name> as the the root directory for
	--dest <dest_name>	package installation, removal, upgrading.
				<dest_name> should be a defined dest name from
				the configuration file, (but can also be a
				directory name in a pinch).
	-o <dir>		Use <dir> as the root directory for
	--offline-root <dir>	offline installation of packages.
	--verify-program <path>	Use the given program to verify usign signatures
	--add-arch <arch>:<prio>	Register architecture with given priority
	--add-dest <name>:<path>	Register destination with given path

Force Options:
	--force-depends		Install/remove despite failed dependencies
	--force-maintainer	Overwrite preexisting config files
	--force-reinstall	Reinstall package(s)
	--force-overwrite	Overwrite files from other package(s)
	--force-downgrade	Allow opkg to downgrade packages
	--force-space		Disable free space checks
	--force-postinstall	Run postinstall scripts even in offline mode
	--force-remove	Remove package even if prerm script fails
	--force-checksum	Don't fail on checksum mismatches
	--no-check-certificate Don't validate SSL certificates
	--noaction		No action -- test only
	--download-only	No action -- download only
	--nodeps		Do not follow dependencies
	--nocase		Perform case insensitive pattern matching
	--size			Print package size when listing available packages
	--strip-abi		Print package name without appended ABI version
	--force-removal-of-dependent-packages
				Remove package and all dependencies
	--autoremove		Remove packages that were installed
				automatically to satisfy dependencies
	-t			Specify tmp-dir.
	--tmp-dir		Specify tmp-dir.
	-l			Specify lists-dir.
	--lists-dir		Specify lists-dir.

 regexp could be something like 'pkgname*' '*file*' or similar
 e.g. opkg info 'libstd*' or opkg search '*libop*' or opkg remove 'libncur*'
make[2]: *** [package/Makefile:70: package/install] Error 1
make[2]: Leaving directory '/home/x86.6.1/lede'
make[1]: *** [package/Makefile:111: /home/x86.6.1/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/x86.6.1/lede'
make: *** [/home/x86.6.1/lede/include/toplevel.mk:231：world] 错误 2

**Comment by bi4tms** [comment]
试了一下，5.15内核可以编译，6.1内核的x86和r2s编译均报上述错误
@xiaorouji
