### ISSUE TITLE
[Feature Request]: 缺少依赖包libopenssl3

### ISSUE THREAD

**Issue by CharlieVSAngel** [xiaorouji/openwrt-package#2869]
### 描述你想要的新功能

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libopenssl3 for haproxy
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall:
 * 	libopenssl3
 * opkg_install_cmd: Cannot install package luci-app-passwall.

### 描述你想要的解决方案

是否能加入各个版本的libopenssl3的依赖包，X86和a53的，谢谢！

**Comment by sbwml** [comment]
哈哈，因为 Build with **⚙️ OpenWrt SDK Version: 23.05-rc3**

除了openssl3 以外，还依赖 `luci-lua-runtime` 呢。

这意味着 https://github.com/xiaorouji/openwrt-passwall/releases 的成品，只能用于 openwrt-23.05 固件。

**Comment by sbwml** [comment]
哈哈，haproxy 由 openwrt feeds 提供，出现 `libopenssl3` 依赖不满足都是因为非官方源码的固件却使用了 openwrt 最新的包安装源导致。

不过 Passwall Build with **⚙️ OpenWrt SDK Version: 23.05-rc3**，说明它会依赖 `luci-lua-runtime` ，这意味着 https://github.com/xiaorouji/openwrt-passwall/releases 的成品，只能用于 **openwrt-23.05** / **openwrt-snapshots** 固件。
