### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wodahsnk** [xiaorouji/openwrt-package#2870]
### 描述您遇到的bug

不知道为什么 除了v2ray类型节点 其他节点都正常就 v2ray节点不能用

### 复现此Bug的步骤

，

### 您想要实现的目的

v2ray节点正常使用

### 日志信息

，

### 截图

![photo_2023-10-19_20-14-39](https://github.com/xiaorouji/openwrt-passwall/assets/24026493/c75f4768-da4e-4828-8cf5-ec068e3dcd53)
![photo_2023-10-19_20-15-05](https://github.com/xiaorouji/openwrt-passwall/assets/24026493/a562fac5-9f33-4732-b44f-ae9a31381a89)

### 系统相关信息

最新版本把应该是

**Comment by Gzxhwq** [comment]
v2ray的支持已经移除了，请使用xray或者sing-box
