### ISSUE TITLE
[Bug]: 安装最新版本后没有显示reality

### ISSUE THREAD

**Issue by tcpqueue** [xiaorouji/openwrt-package#2875]
### 描述您遇到的bug

请问为什么安装最新passwall添加节点有些路由器没有显示reailty

### 复现此Bug的步骤

上传passwall_packages_ipk_aarch64_cortex-a53  和passwall 插件
opkg install *.ipk
```

root@QWRT:/tmp/pass2# opkg install *.ipk
Installing luci-app-mosdns (1.5.13) to root...
Installing mosdns (5.2.1-1) to root...
Installing v2dat (2022-12-15-47b8ee51-1) to root...
Installing luci-i18n-mosdns-zh-cn (git-23.271.70451-e31521d) to root...
Package mosdns (5.2.1-1) installed in root is up to date.
Package v2dat (2022-12-15-47b8ee51-1) installed in root is up to date.
Not downgrading package v2ray-geoip on root from 202309280037-1 to 2023-09-28.
Not downgrading package v2ray-geosite on root from 20230930105558-1 to 2023-09-28.
Configuring mosdns.
Configuring v2dat.
Configuring luci-app-mosdns.
Configuring luci-i18n-mosdns-zh-cn.
root@QWRT:/tmp/pass2# opkg install *.ipk
Installing brook (20230606-2) to root...
Package chinadns-ng (2023.06.01-1) installed in root is up to date.
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Installing hysteria (2.1.0-1) to root...
Package microsocks (1.0.3-1) installed in root is up to date.
Installing naiveproxy (113.0.5672.62-1-1) to root...
Upgrading shadowsocks-rust-sslocal on root from 1.16.2-1 to 1.17.0-1...
Installing shadowsocks-rust-ssserver (1.17.0-1) to root...
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Unknown package 'shadowsocksr-libev-ssr-server'.
Installing simple-obfs (0.0.5-1) to root...
Unknown package 'sing-box'.
Package tcping (0.3-1) installed in root is up to date.
Installing trojan-go (0.10.6-1) to root...
Package trojan-plus (10.0.3-2) installed in root is up to date.
Package tuic-client (1.0.0-1) installed in root is up to date.
Package v2ray-geoip (202309280037-1) installed in root is up to date.
Package v2ray-geosite (20230930105558-1) installed in root is up to date.
Upgrading v2ray-plugin on root from 5.7.0-1 to 5.8.0-2...
Package xray-core (1.8.4-1) installed in root is up to date.
Installing xray-plugin (1.8.4-1) to root...
Configuring hysteria.
Configuring shadowsocks-rust-ssserver.
Configuring trojan-go.
Configuring naiveproxy.
Configuring v2ray-plugin.
Configuring xray-plugin.
Configuring shadowsocks-rust-sslocal.
Configuring brook.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libopenssl3 for shadowsocksr-libev-ssr-server
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-server found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-server.
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
	But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.
 * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
 * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package sing-box.

```
路由器后台进入 passwall 
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44940833/73a71cb8-bae4-4e52-a220-2f9e87541a4f)

但是我另外一台路由器就没有这个毛病
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44940833/b4c15edd-b885-4f01-b2e4-aaf8edd051c8)

### 您想要实现的目的

可以配置reality节点

### 日志信息

root@QWRT:/tmp/pass2# opkg install *.ipk
Installing luci-app-mosdns (1.5.13) to root...
Installing mosdns (5.2.1-1) to root...
Installing v2dat (2022-12-15-47b8ee51-1) to root...
Installing luci-i18n-mosdns-zh-cn (git-23.271.70451-e31521d) to root...
Package mosdns (5.2.1-1) installed in root is up to date.
Package v2dat (2022-12-15-47b8ee51-1) installed in root is up to date.
Not downgrading package v2ray-geoip on root from 202309280037-1 to 2023-09-28.
Not downgrading package v2ray-geosite on root from 20230930105558-1 to 2023-09-28.
Configuring mosdns.
Configuring v2dat.
Configuring luci-app-mosdns.
Configuring luci-i18n-mosdns-zh-cn.
root@QWRT:/tmp/pass2# opkg install *.ipk
Installing brook (20230606-2) to root...
Package chinadns-ng (2023.06.01-1) installed in root is up to date.
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Installing hysteria (2.1.0-1) to root...
Package microsocks (1.0.3-1) installed in root is up to date.
Installing naiveproxy (113.0.5672.62-1-1) to root...
Upgrading shadowsocks-rust-sslocal on root from 1.16.2-1 to 1.17.0-1...
Installing shadowsocks-rust-ssserver (1.17.0-1) to root...
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Unknown package 'shadowsocksr-libev-ssr-server'.
Installing simple-obfs (0.0.5-1) to root...
Unknown package 'sing-box'.
Package tcping (0.3-1) installed in root is up to date.
Installing trojan-go (0.10.6-1) to root...
Package trojan-plus (10.0.3-2) installed in root is up to date.
Package tuic-client (1.0.0-1) installed in root is up to date.
Package v2ray-geoip (202309280037-1) installed in root is up to date.
Package v2ray-geosite (20230930105558-1) installed in root is up to date.
Upgrading v2ray-plugin on root from 5.7.0-1 to 5.8.0-2...
Package xray-core (1.8.4-1) installed in root is up to date.
Installing xray-plugin (1.8.4-1) to root...
Configuring hysteria.
Configuring shadowsocks-rust-ssserver.
Configuring trojan-go.
Configuring naiveproxy.
Configuring v2ray-plugin.
Configuring xray-plugin.
Configuring shadowsocks-rust-sslocal.
Configuring brook.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libopenssl3 for shadowsocksr-libev-ssr-server
 * pkg_hash_fetch_best_installation_candidate: Packages for shadowsocksr-libev-ssr-server found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-ssr-server.
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
	But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.
 * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
 * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package sing-box.

### 系统相关信息

Passwall Version: 4.71-2
op:21.02.6 
L大的qwrt

**Comment by tcpqueue** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44940833/11b7047f-4613-4055-bdb6-6c72c35a22a6)
安装后我在软件包查询显示这个版本，好像版本对不上？但是确实安装的是最新的

**Comment by Gzxhwq** [comment]
你贴的log里面就没有passwall的安装记录啊
