### ISSUE TITLE
Hysteria 版本需要 1版本和2版本共存，现在只能用2，2现在还不完善

### ISSUE THREAD

**Issue by luowei729** [xiaorouji/openwrt-package#2880]
### 描述你想要的新功能

Hysteria 版本需要 1版本和2版本共存，现在只能用2，2现在还不完善

### 描述你想要的解决方案

使1版本和2版本能共存

**Comment by Gzxhwq** [comment]
Hysteria 1.x 和 2.x 不是平行的关系，是更新迭代的关系，1.x是旧版本，如果要用1.x的hysteria，可以把passwall同样停留在支持hysteria 1.x的旧版本，等待hysteria 2.x完善后续功能。

**Comment by luowei729** [comment]
> Hysteria 1.x 和 2.x 不是平行的关系，是更新迭代的关系，1.x是旧版本，如果要用1.x的hysteria，可以把passwall同样停留在支持hysteria 1.x的旧版本，等待hysteria 2.x完善后续功能。

hy1和hy2版本互不兼容啊，他们不是迭代关系，是2种协议，况且hy2现在开发并未Releases，你兼容hy2没问题，但是hy1也是成熟的协议，没理由要放弃他

**Comment by luowei729** [comment]
> Hysteria 1.x 和 2.x 不是平行的关系，是更新迭代的关系，1.x是旧版本，如果要用1.x的hysteria，可以把passwall同样停留在支持hysteria 1.x的旧版本，等待hysteria 2.x完善后续功能。

hy1和hy2版本互不兼容啊，他们不是迭代关系，是2种协议，况且hy2现在开发并未Releases，你兼容hy2没问题，但是hy1也是成熟的协议，没理由要放弃他

**Comment by luowei729** [comment]
> Hysteria 1.x 和 2.x 不是平行的关系，是更新迭代的关系，1.x是旧版本，如果要用1.x的hysteria，可以把passwall同样停留在支持hysteria 1.x的旧版本，等待hysteria 2.x完善后续功能。

calsh mate 等都同时兼容 hy1和hy2，你这样会给用户代理困扰，hy1端口跳跃，tun模式，功能都很完善

**Comment by Gzxhwq** [comment]
hysteria 2.x 早就已经是正式Release了，
https://github.com/apernet/hysteria/releases

1.x的开发也已经相当于停止了。
https://github.com/apernet/hysteria/tree/hy1

还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。

sing-box也同样支持hy1和hy2协议。

**Comment by luowei729** [comment]
> hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> 
> 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> 
> 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> 
> sing-box也同样支持hy1和hy2协议。

ss和ssr协议也停止开发了，你不应该放弃支持么

**Comment by Gzxhwq** [comment]
> > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > sing-box也同样支持hy1和hy2协议。
> 
> ss和ssr协议也停止开发了，你不应该放弃支持么

你要搞清楚，Hy 1.x和 Hy 2.x 是同一个软件的不同版本，不是两个软件包，你要做的首先是说服所有op软件的维护者把hy1.x和hy 2.x分开成2个包同时维护。

**Comment by luowei729** [comment]
> > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > sing-box也同样支持hy1和hy2协议。
> 
> ss和ssr协议也停止开发了，你不应该放弃支持么

hy1出来这么久，没有被墙识别，经过6月时间考研的

**Comment by Gzxhwq** [comment]
> > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > sing-box也同样支持hy1和hy2协议。
> > 
> > 
> > ss和ssr协议也停止开发了，你不应该放弃支持么
> 
> hy1出来这么久，没有被墙识别，经过6月时间考研的

你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能

**Comment by luowei729** [comment]
> > > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > > sing-box也同样支持hy1和hy2协议。
> > > 
> > > 
> > > ss和ssr协议也停止开发了，你不应该放弃支持么
> > 
> > 
> > hy1出来这么久，没有被墙识别，经过6月时间考研的
> 
> 你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能

作为客户端，别的客户端都能做到同时兼容，如果不想太复杂实现，可以默认提供一个1版本，用户可以手动检查更新成2，是不是更好

**Comment by luowei729** [comment]
> > > > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > > > sing-box也同样支持hy1和hy2协议。
> > > > 
> > > > 
> > > > ss和ssr协议也停止开发了，你不应该放弃支持么
> > > 
> > > 
> > > hy1出来这么久，没有被墙识别，经过6月时间考研的
> > 
> > 
> > 你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能
> 
> 作为客户端，别的客户端都能做到同时兼容，如果不想太复杂实现，可以默认提供一个1版本，用户可以手动检查更新成2，是不是更好

我同时也给clash mate for android提了建议，他们将在下个版本同时兼容
https://github.com/MetaCubeX/ClashMetaForAndroid/issues/164

**Comment by Gzxhwq** [comment]
> > > > > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > > > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > > > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > > > > sing-box也同样支持hy1和hy2协议。
> > > > > 
> > > > > 
> > > > > ss和ssr协议也停止开发了，你不应该放弃支持么
> > > > 
> > > > 
> > > > hy1出来这么久，没有被墙识别，经过6月时间考研的
> > > 
> > > 
> > > 你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能
> > 
> > 
> > 作为客户端，别的客户端都能做到同时兼容，如果不想太复杂实现，可以默认提供一个1版本，用户可以手动检查更新成2，是不是更好
> 
> 我同时也给clash mate for android提了建议，他们将在下个版本同时兼容 [MetaCubeX/ClashMetaForAndroid#164](https://github.com/MetaCubeX/ClashMetaForAndroid/issues/164)

Clash是自己实现的内核，passwall只是一个wrapper，并没有自己的内核，情况是完全不同的。
Passwall同时支持hy1和hy2可以，用sing-box内核就可以了。
Hysteria内核并没有实现v1和v2协议同时存在。

**Comment by luowei729** [comment]
> > > > > > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > > > > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > > > > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > > > > > sing-box也同样支持hy1和hy2协议。
> > > > > > 
> > > > > > 
> > > > > > ss和ssr协议也停止开发了，你不应该放弃支持么
> > > > > 
> > > > > 
> > > > > hy1出来这么久，没有被墙识别，经过6月时间考研的
> > > > 
> > > > 
> > > > 你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能
> > > 
> > > 
> > > 作为客户端，别的客户端都能做到同时兼容，如果不想太复杂实现，可以默认提供一个1版本，用户可以手动检查更新成2，是不是更好
> > 
> > 
> > 我同时也给clash mate for android提了建议，他们将在下个版本同时兼容 [MetaCubeX/ClashMetaForAndroid#164](https://github.com/MetaCubeX/ClashMetaForAndroid/issues/164)
> 
> Clash是自己实现的内核，passwall只是一个wrapper，并没有自己的内核，情况是完全不同的。 Passwall同时支持hy1和hy2可以，用sing-box内核就可以了。 Hysteria内核并没有实现v1和v2协议同时存在。

Passwall同时支持hy1和hy2可以，用sing-box内核就可以了。如何切换到sing-bos内核

**Comment by Gzxhwq** [comment]
> > > > > > > > hysteria 2.x 早就已经是正式Release了， https://github.com/apernet/hysteria/releases
> > > > > > > > 1.x的开发也已经相当于停止了。 https://github.com/apernet/hysteria/tree/hy1
> > > > > > > > 还继续支持旧版的话，那就全套用旧版得了。反正新版也主要是多了sing-box相关的支持。
> > > > > > > > sing-box也同样支持hy1和hy2协议。
> > > > > > > 
> > > > > > > 
> > > > > > > ss和ssr协议也停止开发了，你不应该放弃支持么
> > > > > > 
> > > > > > 
> > > > > > hy1出来这么久，没有被墙识别，经过6月时间考研的
> > > > > 
> > > > > 
> > > > > 你应该和hysteria的作者提，为什么不能同时支持hy1和hy2协议，和支持hy1的所有功能
> > > > 
> > > > 
> > > > 作为客户端，别的客户端都能做到同时兼容，如果不想太复杂实现，可以默认提供一个1版本，用户可以手动检查更新成2，是不是更好
> > > 
> > > 
> > > 我同时也给clash mate for android提了建议，他们将在下个版本同时兼容 [MetaCubeX/ClashMetaForAndroid#164](https://github.com/MetaCubeX/ClashMetaForAndroid/issues/164)
> > 
> > 
> > Clash是自己实现的内核，passwall只是一个wrapper，并没有自己的内核，情况是完全不同的。 Passwall同时支持hy1和hy2可以，用sing-box内核就可以了。 Hysteria内核并没有实现v1和v2协议同时存在。
> 
> Passwall同时支持hy1和hy2可以，用sing-box内核就可以了。如何切换到sing-bos内核

“类型”选sing-box

**Comment by luowei729** [comment]
这样实现订阅会有问题，需要在订阅里面加个hy节点使用类型，将hy1指向sing-box才行

**Comment by Gzxhwq** [comment]
> 这样实现订阅会有问题，需要在订阅里面加个hy节点使用类型，将hy1指向sing-box才行

可以把hysteria://这个URI直接导入给sing-box，你可以开个issue，看有没人愿意提PR吧。

**Comment by luowei729** [comment]
我测试ios 的 Shadowrocket 可以正常更新hy2，并且可以正常使用，passwall不能订阅
2023-11-01 19:09:05: 开始订阅...
2023-11-01 19:09:05: 正在订阅:【test】https://test.
2023-11-01 19:09:05: 成功解析【test】节点数量: 0
2023-11-01 19:09:05: 更新失败，没有可用的节点信息
2023-11-01 19:09:05: 订阅完毕...

**Comment by luowei729** [comment]
> > 这样实现订阅会有问题，需要在订阅里面加个hy节点使用类型，将hy1指向sing-box才行
> 
> 可以把hysteria://这个URI直接导入给sing-box，你可以开个issue，看有没人愿意提PR吧。

我测ios 的 小火箭可以订阅 hy2 ,passwall不能订阅hy2

2023-11-01 19:09:05: 开始订阅...
2023-11-01 19:09:05: 正在订阅:【test】https://tes
2023-11-01 19:09:05: 暂时不支持hysteria2类型的节点订阅，跳过此节点。
2023-11-01 19:09:05: 成功解析【test】节点数量: 0
2023-11-01 19:09:05: 更新失败，没有可用的节点信息
2023-11-01 19:09:05: 订阅完毕...
