### ISSUE TITLE
[Feature Request]: 前置节点可以设置到每个节点里面吗？

### ISSUE THREAD

**Issue by XavierPENROSE** [xiaorouji/openwrt-package#2882]
### 描述你想要的新功能

目前前置节点功能好像只能针对总分流节点，是否可以做到编辑每个节点的时候就选择是否需要前置节点呢？

### 描述你想要的解决方案

可以实现单个节点编辑时就选择前置节点。

**Comment by gito10** [comment]
目前前置代理只应用于分流模式，有个总开关决定是否启用前置代理，启用总开关，可以选择前置代理出口节点，每个分流规则会显示独立开关是否使用前置，应该是覆盖了绝大多数的使用场景的。
至于其他普通类型单节点，有一些是xray/simg-box不支持的，用的各自的客户端程序，要改成支持前置很麻烦，也没必要，这种情况可以直接新建分流节点，关闭其他规则，只保留默认，再开启前置，实际上就配置成了单节点加前置了。

**Comment by XavierPENROSE** [comment]
> 目前前置代理只应用于分流模式，有个总开关决定是否启用前置代理，启用总开关，可以选择前置代理出口节点，每个分流规则会显示独立开关是否使用前置，应该是覆盖了绝大多数的使用场景的。 至于其他普通类型单节点，有一些是xray/simg-box不支持的，用的各自的客户端程序，要改成支持前置很麻烦，也没必要，这种情况可以直接新建分流节点，关闭其他规则，只保留默认，再开启前置，实际上就配置成了单节点加前置了。

我理解您讲的，我现在有三个xray节点，都不是很稳定，我想都中转后做负载均衡，这样比只用一个节点好很多，如果要实现这个功能，目前是不是只能建3个分流节点后再把它们负载均衡一下？

**Comment by XavierPENROSE** [comment]
> 目前前置代理只应用于分流模式，有个总开关决定是否启用前置代理，启用总开关，可以选择前置代理出口节点，每个分流规则会显示独立开关是否使用前置，应该是覆盖了绝大多数的使用场景的。 至于其他普通类型单节点，有一些是xray/simg-box不支持的，用的各自的客户端程序，要改成支持前置很麻烦，也没必要，这种情况可以直接新建分流节点，关闭其他规则，只保留默认，再开启前置，实际上就配置成了单节点加前置了。

刚刚试了下，分流节点只能添加一个，所以我刚刚讲的方法不行。

**Comment by gito10** [comment]
>  我理解您讲的，我现在有三个xray节点，都不是很稳定，我想都中转后做负载均衡，这样比只用一个节点好很多，如果要实现这个功能，目前是不是只能建3个分流节点后再把它们负载均衡一下？

我现在正在用的就有好多都不太稳，这种情况直接使用负载均衡就可以了，根据自己设备性能使用xray内置均衡，或者haproxy均衡。

我目前分流模式，默认规则和大流量下载规则用的xray内置均衡，leastping策略，自动使用每次测试延迟最低的节点。只要每组均衡节点里面不是全部挂了，就总是可用的。像我专门弄个大流量规则，就是把一些便宜机场节点和低倍率节点（不太稳，但可用时速度很快）组负载均衡，承载apkmirror，YouTube，Google Play，GitHub下载等相关域名的流量。

**Comment by XavierPENROSE** [comment]
> > 我理解您讲的，我现在有三个xray节点，都不是很稳定，我想都中转后做负载均衡，这样比只用一个节点好很多，如果要实现这个功能，目前是不是只能建3个分流节点后再把它们负载均衡一下？
> 
> 我现在正在用的就有好多都不太稳，这种情况直接使用负载均衡就可以了，根据自己设备性能使用xray内置均衡，或者haproxy均衡。
> 
> 我目前分流模式，默认规则和大流量下载规则用的xray内置均衡，leastping策略，自动使用每次测试延迟最低的节点。只要每组均衡节点里面不是全部挂了，就总是可用的。像我专门弄个大流量规则，就是把一些便宜机场节点和低倍率节点（不太稳，但可用时速度很快）组负载均衡，承载apkmirror，YouTube，Google Play，GitHub下载等相关域名的流量。

您是用passwall实现xray内置负载均衡吗？我不太会，能否指点一下，谢谢。

**Comment by XavierPENROSE** [comment]
> > 我理解您讲的，我现在有三个xray节点，都不是很稳定，我想都中转后做负载均衡，这样比只用一个节点好很多，如果要实现这个功能，目前是不是只能建3个分流节点后再把它们负载均衡一下？
> 
> 我现在正在用的就有好多都不太稳，这种情况直接使用负载均衡就可以了，根据自己设备性能使用xray内置均衡，或者haproxy均衡。
> 
> 我目前分流模式，默认规则和大流量下载规则用的xray内置均衡，leastping策略，自动使用每次测试延迟最低的节点。只要每组均衡节点里面不是全部挂了，就总是可用的。像我专门弄个大流量规则，就是把一些便宜机场节点和低倍率节点（不太稳，但可用时速度很快）组负载均衡，承载apkmirror，YouTube，Google Play，GitHub下载等相关域名的流量。

找到了，非常感谢。

**Comment by gito10** [comment]
配置好了吗？

**Comment by XavierPENROSE** [comment]
> 配置好了吗？

xray自带的负载均衡配置好了，好像比用HAproxy稳一点，我持续观察几天。

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/e43b4290bc884ebfa977d4a8e6c95034e7ee3ca4

为杜绝无限套娃行为，目前只支持一层。
