### ISSUE TITLE
[Bug]:  关于实验性功能：过滤代理域名 IPv6  引起OP自身代理的问题

### ISSUE THREAD

**Issue by xcyll** [xiaorouji/openwrt-package#2956]
### 描述您遇到的bug

当勾选这个选项时 openwrt系统的软件包不能更新列表 怀疑与返回的结果有空域名有关 ::
![141245](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/17a8dd7f-fa8c-4bdd-9c10-4a5c0d056346)

### 复现此Bug的步骤

- 过滤模式是--**Sing-Box**
- 路由器本机 **勾选代理**

![③ 2024-02-23 134112](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/679a2ec9-9dac-4251-b71c-ff0320866ebd)

### 您想要实现的目的

启用过滤代理域名 IPv6后
返回的IPv6是丢弃，而不是返回空域名

### 日志信息

①开启实验性功能后测试了下如下
![① 2024-02-23 133452](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/db74273d-000a-4e08-9060-300a6e8ec133)
②期待的效果
![② 2024-02-23 133531](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/c81c8634-37f1-4fa6-b97d-4ad1e8e948f9)

### 系统相关信息

version4.74-1

**Comment by xcyll** [comment]
已更新新版，问题已解决👍

**Comment by jh0072110** [comment]
我一直没太搞明白这个选项的功用，是粗暴的嘎掉IPv6还是？

**Comment by dsyo2008** [comment]
> 我一直没太搞明白这个选项的功用，是粗暴的嘎掉IPv6还是？

就是走ipv4，屏蔽ipv6可以理解吧
