### ISSUE TITLE
[Bug]: TCP和UDP 显示“未运行”，但是实际是可以翻墙的

### ISSUE THREAD

**Issue by SixGod9** [xiaorouji/openwrt-package#2957]
### 描述您遇到的bug

TCP和UDP 显示“未运行”，但是实际是可以翻墙的

### 复现此Bug的步骤

TCP和UDP 显示“未运行”，但是实际是可以翻墙的

### 您想要实现的目的

希望可以正常显示

### 日志信息

TCP和UDP 显示“未运行”，但是实际是可以翻墙的

### 截图

TCP和UDP 显示“未运行”，但是实际是可以翻墙的

### 系统相关信息

TCP和UDP 显示“未运行”，但是实际是可以翻墙的

**Comment by xcyll** [comment]
没遇到过
第三方主题不兼容引起？
