### ISSUE TITLE
[Feature Request]: 带混淆的SS AEAD订阅适配Sing-Box订阅类型

### ISSUE THREAD

**Issue by 22ccy** [xiaorouji/openwrt-package#2959]
### 描述你想要的新功能

Sing-Box支持带混淆插件的SS AEAD节点，目前定义订阅类型选择Sing-Box，实际还是使用Shadowsocks Libev添加的节点，需要一个一个改成Sing-Box，并勾选插件选项才行。

### 描述你想要的解决方案

选择Sing-Box类型后，带混淆的SS AEAD节点也使用Sing-Box Shadowsocks

**Comment by handsomeji** [comment]
請提供一個帶插件的SS節點鏈接來支援

**Comment by 22ccy** [comment]
> 請提供一個帶插件的SS節點鏈接來支援

ss://YWVzLTEyOC1nY206eHh4eHh4eHg@test.com:8888/?plugin=obfs-local%3Bobfs%3Dhttp%3Bobfs-host%3Dtest.microsoft.com&group=#HKG

大概就是这样

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/a663e601b6c81edc21624a9d7ef653f72ae112b1
