### ISSUE TITLE
[Bug]: 安装不了luci界面

### ISSUE THREAD

**Issue by wingswing1** [xiaorouji/openwrt-package#2964]
### 描述您遇到的bug

提示:
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall
 * opkg_download_pkg: Package luci-app-passwall is not available from any configured src.
 * opkg_install_pkg: Failed to download luci-app-passwall. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-passwall.

### 复现此Bug的步骤

opkg安装luci时出现

### 您想要实现的目的

修复

### 日志信息

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall
 * opkg_download_pkg: Package luci-app-passwall is not available from any configured src.
 * opkg_install_pkg: Failed to download luci-app-passwall. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-passwall.

### 系统相关信息

4.74-3

**Comment by shidevil** [comment]
安装 https://github.com/xiaorouji/openwrt-passwall/issues/2786#issuecomment-1718871865

**Comment by wingswing1** [comment]
> 安装 [#2786 (comment)](https://github.com/xiaorouji/openwrt-passwall/issues/2786#issuecomment-1718871865)

太感谢了 解决问题了

**Comment by hjmhrx** [comment]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libmbedtls12 for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency ipt2socks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency ssocks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency pdnsd-alt for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocks-libev-ss-redir for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocks-libev-ss-local for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocks-libev-ss-server for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocksr-libev-alt for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocksr-libev-ssr-local for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency shadowsocksr-libev-server for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency xray for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency v2ray for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency trojan-plus for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency naiveproxy for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency brook for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency chinadns-ng for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2socks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency v2ray-plugin for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency simple-obfs for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 *

**Comment by RickyGuo** [comment]
没用，依赖安装了，fake 也也装了，还是不行
