### ISSUE TITLE
過去的not china list等同新版如何設置？

### ISSUE THREAD

**Issue by alan21j** [xiaorouji/openwrt-package#2966]
### 描述你想要的新功能

一直在用not china list，將一切非國内的網站全部proxy，以前設置很簡單，現在不知怎麽設置。
麻煩大大

### 描述你想要的解决方案

如何像過去簡單設定區分not china list全部proxy

**Comment by HikaruChang** [comment]
![Screenshot](https://github.com/xiaorouji/openwrt-passwall/assets/16264281/b0ee5caa-2a56-479a-a2c7-c1af74295e5e)

**Comment by Chanhangfai** [comment]
I also wanna to know how to set to GFW as there no option for that, I've tried several combination but still not the same as GFW mode. It's important for NAS, Thanks a lot

**Comment by SakuraFallingMad** [comment]
> I also wanna to know how to set to GFW as there no option for that, I've tried several combination but still not the same as GFW mode. It's important for NAS, Thanks a lot

Keep these options as following:
1.Use Direct List:enabled
2.Use Proxy List:enabled
3.Use Block List:enabled
4.Use GFW List:enabled
5.China List: keep closed (Important)
6. TCP&UDP default proxy mode: keep non-proxy mode (Important)

That means the pure gfw mode. if you want to set device alone,please go to the access control tab, same options as that above.

**Comment by Nicepaul** [comment]
![WechatIMG270](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/54bcc0f9-ff7a-4b3e-9492-0bd9b388aa34)
![WechatIMG269](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/8b395ff7-7bea-480c-9dc5-afdec3c1147c)
![WechatIMG271](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/8b5d469f-fc0c-4c22-86c9-23720402417a)

**Comment by Henshufu** [comment]
新版尝试在访问控制按楼上设置GFW，NAS的做种客户端也还是会走代理。
