### ISSUE TITLE
[Bug]: 开启IPv6透明代理(TProxy)后重启路由器，iptables会报错

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#2968]
### 描述您遇到的bug

开启IPv6透明代理(TProxy)后重启路由器，iptables报错

### 复现此Bug的步骤

1. 开启IPv6透明代理(TProxy)
2. 重启路由器
3. 查看openwrt-系统日志

### 您想要实现的目的

开启ipv6代理后重启路由不再报错

### 日志信息

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 258: -A: not found

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 259: -A: not found

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 260: -A: not found

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 411: -A: not found

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 412: -A: not found

Tue Feb 27 12:46:56 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: /usr/share/passwall/iptables.sh: line 413: -A: not found

**passwall日志正常**

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/3ffbca33-3102-4c52-ab78-a88cebb2bc81)
模式如上图

### 系统相关信息

passwall为最新源码编译
ImmortalWrt 21.02-SNAPSHOT（编译于2.27 9:39）

**Comment by handsomeji** [comment]
Fix.
