### ISSUE TITLE
[Bug]: 更新新版本后，谷歌连接和github连接 点击时显示都是失败的

### ISSUE THREAD

**Issue by smzdmmmm** [xiaorouji/openwrt-package#2970]
### 描述您遇到的bug

更新新版本后，谷歌连接和github连接 点击时显示都是失败的。PC端可以访问GOOGLE，油管也能正常使用，但是WIFI到手机端和盒子端就无法连上了！

### 复现此Bug的步骤

谷歌连接和github连接 点击时显示都是失败的

### 您想要实现的目的

wifi 手机端和盒子端无法正常打开GOOGLE和油管

### 日志信息

2024-02-27 15:49:57: 删除相关防火墙规则完成。
2024-02-27 15:49:58: 清空并关闭相关程序和缓存完成。
2024-02-27 15:49:58: TCP节点：[]，监听端口：
2024-02-27 15:49:58: - 域名解析 DNS Over HTTPS (https://1.1.1.1/dns-query)
2024-02-27 15:49:58: UDP节点没有选择或为空，不代理UDP。
2024-02-27 15:49:58: 过滤服务配置：准备接管域名解析...
2024-02-27 15:49:58:   | - (chinadns-ng) 最高支持4级域名过滤...
2024-02-27 15:49:58:   + 过滤服务：ChinaDNS-NG(:15354)：国内DNS：211.137.58.20,211.137.64.163，可信DNS：127.0.0.1#15353
2024-02-27 15:49:59:   - 节点列表中的域名(vpslist)：211.137.58.20,211.137.64.163
2024-02-27 15:49:59:   - 域名白名单(whitelist)：211.137.58.20,211.137.64.163
2024-02-27 15:49:59:   - 代理域名表(blacklist)：127.0.0.1#15353
2024-02-27 15:49:59:   - 防火墙域名表(gfwlist)：默认
2024-02-27 15:49:59:   - 中国域名表(chnroute)：默认
2024-02-27 15:49:59:   - 以上所列以外及默认：127.0.0.1#15354
2024-02-27 15:49:59:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！

### 系统相关信息

Passwall 版本【 4.75-1 】

**Comment by EuraGoods** [comment]
same problem

**Comment by GreatMichaelLee** [comment]
最近是有这个问题，不过我的是百度失败，我默认选的是远程dns.  时好时不好，找不到原因

**Comment by sjs76** [comment]
我觉得和ChinaDNS-NG有关，关闭ChinaDNS-NG，同时选择直连DNS就恢复链接了。如果选远程DNS大概率连接丢失。同时我还发现 一个问题，从4.74版本之后似乎访问控制就无法正常工作了，无法限制客服端访问外网了。任意机器都可以随意访问。

**Comment by keke1975** [comment]
我也是同上边一样，百度失败但是能正常上网。
![Snipaste_2024-02-27_23-06-47](https://github.com/xiaorouji/openwrt-passwall/assets/61652857/64ad8ae1-37db-4dd5-8092-e2e4c62b8cc0)

**Comment by EuraGoods** [comment]
> 我也是同上边一样，百度失败但是能正常上网。 ![Snipaste_2024-02-27_23-06-47](https://private-user-images.githubusercontent.com/61652857/308224460-64ad8ae1-37db-4dd5-8092-e2e4c62b8cc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDY5MDEsIm5iZiI6MTcwOTA0NjYwMSwicGF0aCI6Ii82MTY1Mjg1Ny8zMDgyMjQ0NjAtNjRhZDhhZTEtMzdkYi00ZGQ1LTgwOTItZTJlNGM2MmI4Y2MwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE1MTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MzYwODkyNmY5YzI4ZjY0MDkzZTIyMGNkYTMwZTBmMTQxZjU1YWU1MTgzNjljMDYyMjVmYjM4M2U2OGJjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z-LJMtgpQNNBgciXM0E4qV8jP2U9HcV530lKXvx_oSI)

我是百度正常，其他3个测速失败

我点开看了TCP节点下面日志：
+0000 2024-02-27 15:08:20 ERROR dns: exchange failed for www.google.com. IN A: context canceled
+0000 2024-02-27 15:08:20 ERROR dns: exchange failed for www.google.com. IN A: context canceled

**Comment by smzdmmmm** [comment]
和你们的刚好相反，百度成功，GOOGLE连接和GITHUB连接失败。PC端正常上网，WIFI手机端和盒子端不能上油管和谷歌

**Comment by Chanhangfai** [comment]
我是百度ping失败但是能正常上网, GOOGLE连接和GITHUB ping正常.  PC端打开GOOGLE和油管正常，但WIFI手机端和盒子端不能上. 设定是关闭ChinaDNS-NG选远程DNS 4.75-2版 新版设置有点檬了 作者能出个教程或简单說明吗? 怎设等于之前的GFW mode 之类的 感谢

**Comment by CharlesLocke** [comment]
其实那几个规则列表你们不要取消勾选，尤其是直连规则，否则本地DNS大概率走远程。

**Comment by smzdmmmm** [comment]
希望快点出个图片设置教程，快点恢复以上问题，WIFI手机和电视盒子都不能出国呀

**Comment by ShanStone** [comment]
设置教程看这里 https://github.com/xiaorouji/openwrt-passwall/discussions/2929#discussioncomment-8556858
不能使用的话，内核切换回xray/v2ray看看呢，有可能和这个有关联 https://github.com/xiaorouji/openwrt-passwall/issues/2960

**Comment by SakuraFallingMad** [comment]
检查下dig domain -p 15353 是不是超过512B了。
如果超过了，套用chinadns-ng就会出问题，因为其不支持监听tcp端口

**Comment by GreatMichaelLee** [comment]
> 我也是同上边一样，百度失败但是能正常上网。 ![Snipaste_2024-02-27_23-06-47](https://private-user-images.githubusercontent.com/61652857/308224460-64ad8ae1-37db-4dd5-8092-e2e4c62b8cc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDAxMDQsIm5iZiI6MTcwOTEzOTgwNCwicGF0aCI6Ii82MTY1Mjg1Ny8zMDgyMjQ0NjAtNjRhZDhhZTEtMzdkYi00ZGQ1LTgwOTItZTJlNGM2MmI4Y2MwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjY2U5NDdlN2Y5N2I4OTU4MzgwMzc4MThlYjBjYjU3MThmNzNkZDY4MTk1M2NhOWFhYTAzNmY3NDE4ZjcyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eeKqJmB7aYF_dRjsuvbPUDaIYpdYDLFfpkUW43161Jc)

我跟你的一样，刚编译了4.75-3还是一样的问题，但上网没任何影响，就是这个检测百度有问题，强迫症....
![image](https://github.com/xiaorouji/openwrt-passwall/assets/20067401/5eb0e5de-6db8-4d9f-821a-8c36be27636b)

**Comment by livingfree2023** [comment]
smartdns+ChinaDNS时google失败，
dns2socks 时 instagram失败
最好能自定义检测URL？

**Comment by etsam** [comment]
> 我也是同上边一样，百度失败但是能正常上网。 ![Snipaste_2024-02-27_23-06-47](https://private-user-images.githubusercontent.com/61652857/308224460-64ad8ae1-37db-4dd5-8092-e2e4c62b8cc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjQ0ODUsIm5iZiI6MTcwOTQyNDE4NSwicGF0aCI6Ii82MTY1Mjg1Ny8zMDgyMjQ0NjAtNjRhZDhhZTEtMzdkYi00ZGQ1LTgwOTItZTJlNGM2MmI4Y2MwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAwMDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YmI3NTVhYzZmOGY4YTc3OGFjNTAwNDkyMzk5ODBhZDg5MzI1ZWJkMzY0N2FmZTY5ZGIyNjc2Y2I2ODFkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scNjB-3V0H875bs9Ua_cmGlktQRZ9upfhnx2EJFEXLU)

你在浏览器打开一个百度的首页不关 然后再点PW的百度测速 看看能显示PING值不，

**Comment by yeung1981** [comment]
我也遇到类似问题，4.71以后各个版本都不稳定。
1. 原来的订阅能用，现在直接订阅下来，检测全部超时
2.手动输入配置可以，但是只能使用24小时，一到24小时，节点检测正常，但是网站检测和实际使用都不行
3. 删除配置后重新输入又好了

**Comment by yeung1981** [comment]
而且感觉比较挑协议，VMESS下各种问题更多，用Trojan-Plus还算好，就是只能坚持24小时

**Comment by Suysker** [comment]
我也遇到过检测百度有问题。
貌似是国内的dns解析使用的是openwrt的ip（不是默认的223.5.5.5），实际openwrt在本地查询dns的时候，不知为何dnsmasq的53端口refused了。（可以使用openwrt自带的网络诊断
局域网内的设备都能正常进行dns查询和网络连接。

过滤服务配置：准备接管域名解析...
- 域名解析：使用UDP协议请求DNS（127.0.0.1#5353）...
 * 要求代理 DNS 请求，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
 - 节点列表中的域名(vpslist)：192.168.2.1
 - 域名白名单(whitelist)：192.168.2.1
 - 代理域名表(blacklist)：127.0.0.1#5353
 - 防火墙域名表(gfwlist)：127.0.0.1#5353
 - 中国域名表(chnroute)：192.168.2.1
 - 以上所列以外及默认：127.0.0.1#5353
 - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！

<img width="1710" alt="{B77FE699-D955-412e-925D-1FEC670B0234}" src="https://github.com/xiaorouji/openwrt-passwall/assets/61983976/bfd603a3-a53f-42d6-93f1-8f7be765a92f">
<img width="1452" alt="{DC8AC16A-A1E0-43ed-B0DA-D5C59B81C4AA}" src="https://github.com/xiaorouji/openwrt-passwall/assets/61983976/bb94ca4c-893c-48fc-aa2d-a6c30765dd93">
<img width="1467" alt="{704AC625-8B33-4df7-B33B-0BA2BACEF75D}" src="https://github.com/xiaorouji/openwrt-passwall/assets/61983976/886f895e-02a5-4a26-a663-a68aba1ad1c4">

最后我是把dns模式里的直连，改成代理（127.0.0.1:5353）才解决的

**Comment by handsomeji** [comment]
請更新到最新代碼再做測試發log。

**Comment by smzdmmmm** [comment]
4.75-6 正常了：）

**Comment by Suysker** [comment]
> 我也遇到过检测百度有问题。 貌似是国内的dns解析使用的是openwrt的ip（不是默认的223.5.5.5），实际openwrt在本地查询dns的时候，不知为何dnsmasq的53端口refused了。（可以使用openwrt自带的网络诊断 局域网内的设备都能正常进行dns查询和网络连接。
> 
> 过滤服务配置：准备接管域名解析...
> 
> * 域名解析：使用UDP协议请求DNS（127.0.0.1#5353）...
> 
> * 要求代理 DNS 请求，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
> 
> * 节点列表中的域名(vpslist)：192.168.2.1
> * 域名白名单(whitelist)：192.168.2.1
> * 代理域名表(blacklist)：127.0.0.1#5353
> * 防火墙域名表(gfwlist)：127.0.0.1#5353
> * 中国域名表(chnroute)：192.168.2.1
> * 以上所列以外及默认：127.0.0.1#5353
> * PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
> 
> 最后我是把dns模式里的直连，改成代理（127.0.0.1:5353）才解决的

4.75-6版本 adg用使用53端口替换dnsmasq全部都正常了（用重定向53端口到adg会使op本地发起的53端口查询全部refused

**Comment by etsam** [comment]
@xiaorouji   passwall2 有没有修复啊 我把crul降级到8.5 重新编译 百度依旧测试“连接失败 ”
xray分流显示正常 选择singbox就不行。
 
![111](https://github.com/xiaorouji/openwrt-passwall/assets/24689501/3397a874-e98a-47f4-a9b8-ed357be7483d)
![222](https://github.com/xiaorouji/openwrt-passwall/assets/24689501/32472a98-190e-42ff-9759-0c0fde50e6ce)

**Comment by Wssfh** [comment]
我也这样，关了chinadns-ng就好了，不知道哪的问题，之前还好好的。

**Comment by seaskyleader** [comment]
我也是同样的问题，上个版本没问题，更新后只有百度检测是通的，其他都是失败，可以正常上网！
