### ISSUE TITLE
[Feature Request]: 最近更新的节奏非常的快，没其他要求，纯粹为作者们打call

### ISSUE THREAD

**Issue by Jasonzhang2023** [xiaorouji/openwrt-package#2972]
### 描述你想要的新功能

给我们小白赋能，让我们有科学的发展观，内心无比感激！

### 描述你想要的解决方案

纯粹打call贴！

**Comment by Jasonzhang2023** [comment]
每个版本我都安装在openwrt上（1个X86笔记本电脑改硬路由，2个X86黑群晖跑虚拟机软路由，还有一个arm架构的openwrt），目前还没有遇到问题。
就是一些依赖，在我的老版本openwrt上缺依赖，iptables-mod-tproxy、iptables-mod-socket、 iptables-mod-iprange、 iptables-mod-conntrack-extra、 kmod-ipt-nat，用opkg安装了也不行。但不影响使用。不知道什么原因，可能是openwrt比较老。

后续每个版本迭代安装，遇到问题及时反馈，为软件做一点贡献。

**Comment by BGzEroll** [comment]
这个还是建议发到discussion那去吧，issues不是这样用的😂
