### ISSUE TITLE
[Bug]: 最近几个版本，通过TCP请求自定义DNS时无法正常工作

### ISSUE THREAD

**Issue by Soolita** [xiaorouji/openwrt-package#2973]
### 描述您遇到的bug

DNS过滤模式选择“通过TCP请求DNS”，远程DNS选择自定义，那么DNS完全无法收到解析请求，也就无法正常访问外网
![微信图片_20240228113628](https://github.com/xiaorouji/openwrt-passwall/assets/18568963/63cb44b3-436d-4a43-b24d-af4d22c5c89e)

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

PW版本[4.74-4]

**Comment by handsomeji** [comment]
內網為什麼要用TCP？

**Comment by BGzEroll** [comment]
你请求的内网dns服务器有监听tcp 53端口吗

**Comment by Soolita** [comment]
> 你请求的内网dns服务器有监听tcp 53端口吗

 有的，192.168.1.8创建了两个AdGuard Home,一个使用udp 53端口，直接设为旁路由dns，另一个使用tcp 53端口，给国外解析用，之前版本一直是正常的，新版本不能用了

**Comment by iamyangyiok** [comment]
我也感觉不正常，时好时坏。

**Comment by Soolita** [comment]
暂时调整为UDP解析，工作正常

![微信图片_20240229155314](https://github.com/xiaorouji/openwrt-passwall/assets/18568963/f1ee8c50-699d-4791-a468-384bc08fb07f)
