### ISSUE TITLE
[Bug]: 过滤代理域名 IPv6 功能时好时坏

### ISSUE THREAD

**Issue by guojiahao999** [xiaorouji/openwrt-package#2974]
### 描述您遇到的bug

我国内的网络环境需要使用ipv6 但是访问双栈的网站 例如Netflix 就会受到ipv6的影响 无法正常访问 开启过滤代理域名 IPv6 时好时坏 只有在Dnsmasq 过滤 IPv6 AAAA 记录才可以 PASSWALL的 开启过滤代理域名 IPv6 经常不好用

### 复现此Bug的步骤

我国内的网络环境需要使用ipv6 但是访问双栈的网站 例如Netflix 就会受到ipv6的影响 无法正常访问 开启过滤代理域名 IPv6 时好时坏 只有在Dnsmasq 过滤 IPv6 AAAA 记录才可以 PASSWALL的 开启过滤代理域名 IPv6 经常不好用

### 您想要实现的目的

我国内的网络环境需要使用ipv6 但是访问双栈的网站 例如Netflix 就会受到ipv6的影响 无法正常访问 开启过滤代理域名 IPv6 时好时坏 只有在Dnsmasq 过滤 IPv6 AAAA 记录才可以 PASSWALL的 开启过滤代理域名 IPv6 经常不好用

### 日志信息

我国内的网络环境需要使用ipv6 但是访问双栈的网站 例如Netflix 就会受到ipv6的影响 无法正常访问 开启过滤代理域名 IPv6 时好时坏 只有在Dnsmasq 过滤 IPv6 AAAA 记录才可以 PASSWALL的 开启过滤代理域名 IPv6 经常不好用

### 系统相关信息

我国内的网络环境需要使用ipv6 但是访问双栈的网站 例如Netflix 就会受到ipv6的影响 无法正常访问 开启过滤代理域名 IPv6 时好时坏 只有在Dnsmasq 过滤 IPv6 AAAA 记录才可以 PASSWALL的 开启过滤代理域名 IPv6 经常不好用

**Comment by lwb1978** [comment]
这个问题已经很久了，开启过滤代理域名ipv6时间长了就失效，可能是xray或者Dnsmasq本身的问题，搞不懂。我现在改用passwall-smartdns版本搭配smartdns使用，开启过滤代理域名ipv6很稳，你也可以直接装smartdns搭配主线版本的passwall，就是配置相对复杂一些。

**Comment by handsomeji** [comment]
不是寫了 實驗性功能？
你可以使用Sing-Box或Xray的DNS過濾模式代替。
