### ISSUE TITLE
[Bug]: 关于观看IG短视频莫名卡顿的修复

### ISSUE THREAD

**Issue by q2051839** [xiaorouji/openwrt-package#2976]
### 描述您遇到的bug

联通1000光纤+WIFI5(TP)+自建代理（高速并且尝试过多种自建协议，包括XTLS,SHDOW-TLS.NAIVE等）。看IG视频超过一定数目的时候莫名卡顿（此问题超过1年，播放一半定住不动，不会缓存好自动播放），刷下一条乃至以后的视频都亏卡顿。必须重启APP。

### 复现此Bug的步骤

我在安卓与苹果端都遇到这个问题，一直以为是节点，或者缓存的问题。但是，前日更改了高级设置中的“不转发QUIC”取消勾选后（此为默认勾选选项），播放正常，实测超过40小时。

### 您想要实现的目的

QUIC端口开启转发以后。一切正常。没有故障或者减速出现。

### 日志信息

无日志

### 系统相关信息

passwall    openwrt  TPROXY代理模式
实测安卓苹果双端都有此问题。

### 其他信息

并不作为BUG上报，只是希望解决遇到同样问题

**Comment by Soolita** [comment]
我也碰到这个问题，有很多视频看几秒卡几秒，我一直还以为是节点的问题

**Comment by woni928** [comment]
<img width="978" alt="1" src="https://github.com/xiaorouji/openwrt-passwall/assets/28220733/cde42552-3fcc-4954-b5d3-b0742881c523">

修改这里为：不使用？

**Comment by q2051839** [comment]
> <img alt="1" width="978" src="https://private-user-images.githubusercontent.com/28220733/308564530-cde42552-3fcc-4954-b5d3-b0742881c523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzg0NzYsIm5iZiI6MTcwOTI3ODE3NiwicGF0aCI6Ii8yODIyMDczMy8zMDg1NjQ1MzAtY2RlNDI1NTItM2ZjYy00OTU0LWI1ZDMtYjA3NDI4ODFjNTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MjU0Njk2ODZhYWIxNDBlODIyMDkyNjk2Njk3ZDQwYzcwNTgxMWY5YjhiODJkMjFlMDc3MzZkNmNlMGM2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CKGJBpwZuVJiluZKjjIqltQoPVoJAy8q94DlGRiHVRk">
> 
> 修改这里为：不使用？

是的。不知道我改之后不卡顿是否是个例，望改后能复

**Comment by handsomeji** [comment]
這個應該不是passwall問題。
