### ISSUE TITLE
[Feature Request]: 当节点都失效时，主动去更新订阅

### ISSUE THREAD

**Issue by zy-xhd** [xiaorouji/openwrt-package#2978]
### 描述你想要的新功能

在订阅中添加一个失效后更新订阅的功能
当订阅中的节点都无效了，就去主动更新订阅
现在的自动更新订阅不好用，每天只能更新一次，可能白天用着用着就挂了，然后要等到设置的时间才会去自动更新

### 描述你想要的解决方案

在订阅中添加一个失效后更新订阅的功能
当订阅中的节点都无效了，就去主动更新订阅
现在的自动更新订阅不好用，每天只能更新一次，可能白天用着用着就挂了，然后要等到设置的时间才会去自动更新

**Comment by iamyangyiok** [comment]
我觉得不如增加一个 时间间隔订阅，不按天 ，按时间间隔。

**Comment by iamyangyiok** [comment]
我现是手动改计划任务的 1小时同步一次。

**Comment by zy-xhd** [comment]
> 我现是手动改计划任务的 1小时同步一次。

请问如何修改的？插件中我没看到有这个选项

**Comment by zy-xhd** [comment]
> 我觉得不如增加一个 时间间隔订阅，不按天 ，按时间间隔。

这个也可以，设置更新可以频繁一点

**Comment by chopper-ufo** [comment]
我建議你換一個比較穩定的機場

**Comment by zy-xhd** [comment]
> 我建議你換一個比較穩定的機場

比如说？我现在用的justmysocks，我需要洛杉矶的服务器
