### ISSUE TITLE
[Bug]: 升级475-3后速度非常慢

### ISSUE THREAD

**Issue by love-dy** [xiaorouji/openwrt-package#2985]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/efca3823-c44b-4775-b60e-bfaa9c289d6d)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/b401814a-3f7d-4c63-8241-265f26b5ca4f)
升级475-3后这样的速度还在转圈圈，看看百度的速度，我是直连用smartdns，远程用adguard, 用了一年多了，以前的版本速度杠杠的，模式选择也很简单，现在大佬好像想把 passwall 1和2合并的感觉，passwall简单易用的特性快没有了，自从升级475-3后，都不想用路由器科学上网了，因为开个v2rayN速度都比这快，至少视频不转圈圈, 秒开

### 复现此Bug的步骤

![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/a31be662-eb25-4b1e-b876-09b721720c18)

### 您想要实现的目的

![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/99d2fe57-6239-417c-9f35-086d3c6bccba)
很难明白哪些影响了速度

### 日志信息

同上

### 截图

同上

### 系统相关信息

passwall版本 475-3

### 其他信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/15624c42-9cf9-4928-bfbe-8dcea358cada)
按说这速度4k基本也是秒开的，虽然不是很快

**Comment by iamyangyiok** [comment]
我今天准备回退471， 这几天时不时上不了的问题 我实在搞累了

**Comment by Chanhangfai** [comment]
设置錯误 作者更新了整个逻辑 我用着起飞

**Comment by hcym** [comment]
老版设置直观点，新的也能用，性能应该比老的好

**Comment by love-dy** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/113014261/ed626d11-dd12-4f78-aad4-1f2cf3932c04)

我想锅找到了
1.如果选 通过udp请求dns就不能看视频，无限转圈圈
2.如果远程dns 设置成 127.0.0.1:5335 （用adguard home做dns服务器）也不能看视频，无限转圈圈

现在只能选 通过tcp请求dns, 远程dns只能选1111或8888之类的，不能选本地的，这样圈圈转一会 凑合能看了
473版本没有这个问题，以前我一直都用adguard做个缓存用

还有一个问题，用ssr也会转圈圈，这就和passwall没关系了，反正这次升级一塌糊涂，什么都有问题

**Comment by handsomeji** [comment]
log?

**Comment by hcym** [comment]
127.0.0.1:5335
mosdns必须用的，不然ipv6不能开
其他都是默认，也不会看日志

**Comment by 0769559** [comment]
为了hy2从老版本升上来后问题感觉很多，一开始升上475-3报错iptables-mod-socket，这个插件库都找不着 想着降回去更折腾就选择重刷个新的openwrt。刷完后依赖齐了不报错，但是现在的版本添加订阅后默认的分流根本用不了外网打开都浏览不了，后面挨个试 只有sing-box才能正常。也只有选sing-box后 passwall里的dns才显示运行中。选其他的时候dns显示未运行 也没看见log有什么报错（或者单纯是我看不懂

以前还觉得软件简单易食用，现在感觉越来越复杂了。

**Comment by e54385991** [comment]
通过udp请求dns 搭配MOSDNS等 
比如 127.0.0.1:5335 很容易导致出问题 4.7.3到是没啥问题
