### ISSUE TITLE
[Bug]: 4.75-3 DNS选项没有直连或者远程DNS选项

### ISSUE THREAD

**Issue by sunlt77** [xiaorouji/openwrt-package#2986]
### 描述您遇到的bug

4.75-3 DNS选项没有直连或者远程DNS选项

### 复现此Bug的步骤

4.75-3 DNS选项没有直连或者远程DNS选项

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

4.75-3

**Comment by firkerword** [comment]
如图设置
![image](https://github.com/xiaorouji/openwrt-passwall/assets/61251923/427e6c1e-7a96-4f37-b3b2-07188ae02e2d)

**Comment by Nicepaul** [comment]
勾选“ChinaDNS-NG”之后在“ChinaDNS-NG 域名默认标签”有“远程DNS”
