### ISSUE TITLE
[Bug]: 代理列表和使用中国列表冲突

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#2987]
### 描述您遇到的bug

代理列表和使用中国列表冲突
样例为byr.pt，在代理列表中添加该域名，中国列表默认直连，浏览器得到的响应错误ERR_SSL_UNRECOGNIZED_NAME_ALERT，在路由器上使用curl能正常返回
将中国列表改为关闭浏览器可恢复正常

### 复现此Bug的步骤

1. 开启IPv6代理
2. 在代理列表中添加byr.pt
3. 模式中，代理列表开启，中国列表选择直连
4. 浏览器访问https://byr.pt

### 您想要实现的目的

保持过去的默认逻辑，用户填写的列表优先级最高

### 日志信息

因为看起来没有路由到，日志中并没有访问记录

### 系统相关信息

 passwall 4.75-3 
 Edge、Chrome
 尝试过重启电脑、路由器、换设备测试

**Comment by love-dy** [comment]
473版本我用着还挺好的，475质的飞跃飞得心拔凉拔凉的，想退回也不知道怎么退，第一次感觉到爬梯爬的绝望

**Comment by WROIATE** [comment]
> 473版本我用着还挺好的，475质的飞跃飞得心拔凉拔凉的，想退回也不知道怎么退，第一次感觉到爬梯爬的绝望

按bump记录切分支编译就行了

**Comment by handsomeji** [comment]
清空設備DNS緩存，瀏覽器也會有緩存，可嘗試關掉瀏覽器後，清空本機DNS緩存，再嘗試。

**Comment by WROIATE** [comment]
> 清空設備DNS緩存，瀏覽器也會有緩存，可嘗試關掉瀏覽器後，清空本機DNS緩存，再嘗試。

这个我尝试过无痕、换浏览器、换设备了（包括手机、电脑），最后确认是passwall的问题是因为我使用手机上的sager用流量正常

**Comment by WROIATE** [comment]
我在issue里补充下测试的环境

**Comment by WROIATE** [comment]
这个issue是超时关了吗😂
@xiaorouji 请问你那边能复现这个问题吗？

**Comment by handsomeji** [comment]
沒有復現。

**Comment by handsomeji** [comment]
你試試不要開IPV6

**Comment by WROIATE** [comment]
> 你試試不要開IPV6

主要是北邮人外网只有v6，而且非常严格，不允许国内运营商的网段访问，只能走代理。
目前是把中国列表关闭了，然后用sing-box的分流

> 沒有復現。

我这边晚上再试试把配置全部初始化再验证下

**Comment by WROIATE** [comment]
我这边完全干净编译测试，还是有这个问题...
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44677306/2aafa01d-5a17-4ab0-b037-1841db0394a1)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44677306/89ffc76c-abbc-4c03-846e-e92aedc527e0)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/44677306/b7fd79be-b7a5-49ca-a1c3-ef6ace24c297)

**Comment by iamyangyiok** [comment]
> > 473版本我用着还挺好的，475质的飞跃飞得心拔凉拔凉的，想退回也不知道怎么退，第一次感觉到爬梯爬的绝望
> 
> 按bump记录切分支编译就行了

请教下 编译时如何BUMP老版本生成

**Comment by WROIATE** [comment]
> 请教下 编译时如何BUMP老版本生成

git tag 看下有哪些版本，切分支

**Comment by BGzEroll** [comment]
我这边复现了，配置和你的相同，在代理列表中添加**ip.3322.net**，结果如下：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/b9ace9f7-e74f-4e08-9794-3d6b3645d24d)
已测试所用节点无任何审计（自建vps），中国列表设置为不使用后可以打开**ip.3322.net**，返回vps的ip

**Comment by handsomeji** [comment]
請說明一下出現問題時是用iptables還是nftables？
but, 我這裡沒有使用IPv6，所以不排除是IPv6透明代理的問題。
對於這種只有ipv6而沒有ipv4的域名，如果不想使用IPv6透明代理，還是有辦法讓他走代理的，讓內核能嗅探出域名就行，目前passwall預留了FakeIP網段強制走代理的防火墻規則：
可以使用Sing-Box或Xray，開啟了流量嗅探。可以在規則列表 - 路由Hosts文件填入
`198.18.0.1 byr.pt`

而對於 `ip.3322.net`，我在使用iptables透明代理沒有復現。

**Comment by WROIATE** [comment]
> 請說明一下出現問題時是用iptables還是nftables？

我这里使用的是iptables

**Comment by BGzEroll** [comment]
> 請說明一下出現問題時是用iptables還是nftables？ but, 我這裡沒有使用IPv6，所以不排除是IPv6透明代理的問題。 對於這種只有ipv6而沒有ipv4的域名，如果不想使用IPv6透明代理，還是有辦法讓他走代理的，讓內核能嗅探出域名就行，目前passwall預留了FakeIP網段強制走代理的防火墻規則： 可以使用Sing-Box或Xray，開啟了流量嗅探。可以在規則列表 - 路由Hosts文件填入 `198.18.0.1 byr.pt`
> 
> 而對於 `ip.3322.net`，我在使用iptables透明代理沒有復現。

我用的iptables测试的，也是打开了ipv6透明代理，流量探测仅供路由使用，不只是3322.net，我填入baidu.com等等都会打不开

**Comment by BGzEroll** [comment]
> 請說明一下出現問題時是用iptables還是nftables？ but, 我這裡沒有使用IPv6，所以不排除是IPv6透明代理的問題。 對於這種只有ipv6而沒有ipv4的域名，如果不想使用IPv6透明代理，還是有辦法讓他走代理的，讓內核能嗅探出域名就行，目前passwall預留了FakeIP網段強制走代理的防火墻規則： 可以使用Sing-Box或Xray，開啟了流量嗅探。可以在規則列表 - 路由Hosts文件填入 `198.18.0.1 byr.pt`
> 
> 而對於 `ip.3322.net`，我在使用iptables透明代理沒有復現。

今天用23.05试了下，nftables下也会发生该问题

**Comment by xcyll** [comment]
v4的环境别的网址测试没问题

**Comment by xcyll** [comment]
V6就不清楚了 没V6节点

**Comment by BGzEroll** [comment]
我在代理列表里填入并访问baidu.com，开启F12后会有这种报错：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/16e0d591-2437-45f6-8446-d029391da91f)
页面中有些元素一直加载不出来并最后报timeout。

上图的错误提示和我开启**使用 gfwlist**后访问google.com，F12中的报错如出一辙，google.com上自己的头像以及左边的google应用列表点不开。

不知道是不是gfwlist的代理逻辑出了问题，但我看防火墙规则似乎没啥问题😂

**Comment by bcseputetto** [comment]
请尝试检查该域名解析出来的IPv6记录，然后将这个IPv6填入代理列表的IP里面，再试一下
我发现IP会优先于域名。

**Comment by BGzEroll** [comment]
> 请尝试检查该域名解析出来的IPv6记录，然后将这个IPv6填入代理列表的IP里面，再试一下 我发现IP会优先于域名。

已尝试关闭ipv6代理+填写ip至该列表+关闭Windows ipv6协议，问题依旧

**Comment by bcseputetto** [comment]
@BGzEroll 应该不需要关闭IPv6代理和Windows的IPv6

**Comment by BGzEroll** [comment]
找到原因了，tcp代理为tproxy时会出现该情况，redirect下则不会 @xiaorouji

**Comment by handsomeji** [comment]
感謝反饋，已復現。

**Comment by handsomeji** [comment]
試下最新commit
