### ISSUE TITLE
[Bug]: 分流规则列表必须安装Xray才能显示

### ISSUE THREAD

**Issue by snowie2000** [xiaorouji/openwrt-package#2992]
### 描述您遇到的bug

分流规则列表可以同时应用在sing-box和xray等，但目前如果没有安装xray则根本不显示，但依然能在sing-box分流中看到，这是不正确的。

### 复现此Bug的步骤

不安装xray，进入规则管理，看不到分流列表。
新建分流结点，依然可以看到各种“隐形”分流

### 您想要实现的目的

在sing-box等其他支持分流的软件安装的情况下，即便没有xray也应该显示分流列表。

### 日志信息

无

### 系统相关信息

4.75-6

**Comment by gito10** [comment]
单单只是让分流规则在装有 sing-box 时也显示，倒是好改，加几行代码的事。
不过刚刚搜了一下，sing-box 从 1.8.0 起已废弃 [GeoIP](https://sing-box.sagernet.org/zh/configuration/route/geoip/) 和 [GeoSite](https://sing-box.sagernet.org/zh/configuration/route/geosite/)，迁移到 rule-set 规则集，详见[迁移指南](https://sing-box.sagernet.org/zh/migration/#geoip)。目前使用 "geoip" 和 "geosite"的配置格式随时可能在之后的某个版本移除。
所以passwall如果要支持sing-box分流的话，可以开始进行迁移工作了。

**Comment by xcyll** [comment]
之前有过相关疑问 咋不分开 原来如此
singbox与xray兼容 共用资源
https://github.com/xiaorouji/openwrt-passwall/issues/2962#issue-2152117522

**Comment by xcyll** [comment]
之前有过相关疑问 咋不分开 原来如此
singbox与xray兼容 
https://github.com/xiaorouji/openwrt-passwall/issues/2962#issue-2152117522

**Comment by snowie2000** [comment]
> 单单只是让分流规则在装有 sing-box 时也显示，倒是好改，加几行代码的事。 不过刚刚搜了一下，sing-box 从 1.8.0 起已废弃 [GeoIP](https://sing-box.sagernet.org/zh/configuration/route/geoip/) 和 [GeoSite](https://sing-box.sagernet.org/zh/configuration/route/geosite/)，迁移到 rule-set 规则集，详见[迁移指南](https://sing-box.sagernet.org/zh/migration/#geoip)。目前使用 "geoip" 和 "geosite"的配置格式随时可能在之后的某个版本移除。 所以passwall如果要支持sing-box分流的话，可以开始进行迁移工作了。

这就有点恶心了，看了下，不是一点点的不兼容，根本就是完全独立的一套新的了

**Comment by gito10** [comment]
> 之前有过相关疑问 咋不分开 原来如此 singbox与xray兼容 [#2962 (comment)](https://github.com/xiaorouji/openwrt-passwall/issues/2962#issue-2152117522)

之前表述不太准，也不是sing-box原来和xray兼容，而是都使用 `"geoip":"cn"` 这样的配置格式，在 passwall 的层面来说，是可以一套设置UI兼容这2个后端的。当然现在sing-box改了配置，也还是可以兼容的，只是要修改sing-box后端的配置生成代码就可以，然后根据新的 rule-set，可能会多一两个sing-box独有的配置选项，比如使用**local**还是**remote**规则，本地规则文件存放的路径，远程规则下载的baseURL。
现在sing-box 从1.8.0起是`"rule-set":"geoip-cn"`，这里的’geoip-cn‘只是一个 **tag**了，另外还要在 `rules`同级配一个
```
"rule_set": [
      {
        "tag": "geoip-cn",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
        "download_detour": "proxy"
      }
]
```
或
```
"rule_set": [
      {
        "tag": "geoip-cn",
        "type": "local",
        "format": "binary",
        "path": "/path/to/rule-set/geoip-cn.srs"
      }
]
```
其实改成这种每个子集单独一个文件还是有好处的，只需要下载需要的规则集就行了，刚看了一下，
geoip-cn.srs          39.4KB
geosite-cn.srs        32.4KB
geosite-google.srs 8.43KB
就不需要下整个geoip.dat (10.2MB) 和 geosite.dat (5.57MB)了，使用`remote`方式的话，还可以设置指定间隔时间（不设置默认1天）更新，无须重启服务。

**Comment by xcyll** [comment]
我现在已切singbox主用了
未编译xray时的确有“隐形”分流可用
但没有UI入口添加新的分流规则了

**Comment by gito10** [comment]
就目前来说，要解决只装sing-box不显示分流规则的问题，只需要修改`/usr/lib/lua/luci/model/cbi/passwall/client/rule.lua`，把第3行
`local has_xray = api.finded_com("xray")` 改为
`local has_xray = api.finded_com("xray") or api.finded_com("sing-box")`
或者你们自用的，没装 xray 的，直接改为
`local has_xray = api.finded_com("sing-box")`就可以显示了。
至于配置迁移的事，那是之后的事了（其实也不麻烦），毕竟现在只是废弃还没移除。我在想迁移配置的话，是直接改为rule-set配置，还是增加版本号检测，sing-box 1.8.0以上使用 rule-set配置，以下使用目前的配置。

**Comment by snowie2000** [comment]
从下载大小的角度来说确实是更小更灵活的，但是从ui角度就相当不方便了，毕竟原来一个.dat就全包含了，规则中只管用就是了，现在就需要每个规则给一个url输入框，而且xray还用不了，依然要留着原来的geosite

**Comment by gito10** [comment]
> 从下载大小的角度来说确实是更小更灵活的，但是从ui角度就相当不方便了，毕竟原来一个.dat就全包含了，规则中只管用就是了，现在就需要每个规则给一个url输入框，而且xray还用不了，依然要留着原来的geosite

倒不用每个 rule-set 一个输入框，我是打算在**规则管理**主页面，**V2ray/Xray 资源文件目录**下面（如图），增加选项，如果装有singbox，就显示2个文本框，用于设置**sing-geoip**和**sing-geosite**的默认下载的基URL，比如官方默认的`https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs`这个下载URL，那默认的 **baseURL**就是
`https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/`，**geosite**的就是
`https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/`。
规则设置里还是跟往常一样直接用`geoip:cn`这样就行，后台会用**geoip**的 baseURL+"geoip-cn.srs"合成完整URL。另外还可以新增一个`srs-url:`规则，后面直接填srs的下载url，以防有些用户同时用到默认仓库的规则集和某些第三方维护的规则集，那么第三方的srs文件url就可以使用`srs-url:`来指定。
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/d036181d-7bbe-4d56-8ef4-364e6fd36712)

**Comment by snowie2000** [comment]
如果sing-box迁移后，tag能和原来的geoip和geosite继续保持一致的话，这个确实是很棒的方案

**Comment by WROIATE** [comment]
> 目前使用 "geoip" 和 "geosite"的配置格式随时可能在之后的某个版本移除。 所以passwall如果要支持sing-box分流的话，可以开始进行迁移工作了。

感觉passwall的能力应该是聚焦在防火墙操作上，至于用什么代理最好都不要去各个特殊兼容，不然维护成本蛮高的，再加上一些小众的代理，用的人不多也要兼容（或者想要支持）
如果能把passwall的这些代理的功能抽象成接口，以插件开发的形式暴露出来，不管后续拓展还是去除，估计会方便很多，也能够让更多的开发者容易参与，当然shell要做到抽象感觉也很困难......只能说各位维护的人员真的太辛苦了

**Comment by xcyll** [comment]
> 就目前来说，要解决只装sing-box不显示分流规则的问题，只需要修改`/usr/lib/lua/luci/model/cbi/passwall/client/rule.lua`，把第3行 `local has_xray = api.finded_com("xray")` 改为 `local has_xray = api.finded_com("xray") or api.finded_com("sing-box")` 或者你们自用的，没装 xray 的，直接改为 `local has_xray = api.finded_com("sing-box")`就可以显示了。 至于配置迁移的事，那是之后的事了（其实也不麻烦），毕竟现在只是废弃还没移除。我在想迁移配置的话，是直接改为rule-set配置，还是增加版本号检测，sing-box 1.8.0以上使用 rule-set配置，以下使用目前的配置。

没装 xray （仅装了singbox)直接改后  重启插件 规则管理里 分流规则未显示 
新代码仅编译singbox后也未显示

**Comment by xcyll** [comment]
> 就目前来说，要解决只装sing-box不显示分流规则的问题，只需要修改`/usr/lib/lua/luci/model/cbi/passwall/client/rule.lua`，把第3行 `local has_xray = api.finded_com("xray")` 改为 `local has_xray = api.finded_com("xray") or api.finded_com("sing-box")` 或者你们自用的，没装 xray 的，直接改为 `local has_xray = api.finded_com("sing-box")`就可以显示了。 至于配置迁移的事，那是之后的事了（其实也不麻烦），毕竟现在只是废弃还没移除。我在想迁移配置的话，是直接改为rule-set配置，还是增加版本号检测，sing-box 1.8.0以上使用 rule-set配置，以下使用目前的配置。

测试了下
没装 xray时 直接改为local has_xray = api.finded_com("sing-box")  重启插件后 规则管理里 -- 分流规则仍未显示

**Comment by xcyll** [comment]
最新代码业已刷机 仍未显示分流规则入口

**Comment by xcyll** [comment]
![① 2024-03-06 204822](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/55c63508-ce2a-4708-8a23-bd574d192751)
![② 2024-03-06 204932](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/def3bb39-d983-4622-babe-317b0246b97f)

**Comment by xcyll** [comment]
最新代码业已刷机 仍未显示分流规则入口

**Comment by gito10** [comment]
我机器上目前缺少kmod，装不了sing-box，所以之前没测试，刚刚用别的程序改名sing-box试了一下，确实不行。排查了一下，大概确定问题出在组件名称定义和组件程序查找上，我先改试。

**Comment by gito10** [comment]
组件里定义的名称是`singbox`，没有中间的`-`，所以查找组件也得用`singbox`，
改成`has_xray = api.finded_com("singbox")`就行了。

**Comment by xcyll** [comment]
![③ 2024-03-06 213402](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/da4508da-54b4-4c2f-9dd7-491c56804e85)

**Comment by xcyll** [comment]
可以了👍

**Comment by xcyll** [comment]
![2024-03-06 213656](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/8bd68f55-e3ec-4b15-8a9f-3f59c22a7442)
大佬 求教 这个怎么改？

**Comment by xcyll** [comment]
![2024-03-06 24224](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/5a0855f5-1f4a-483b-94e0-79203e427d36)

**Comment by xcyll** [comment]
大佬 求教 这个怎么改？
@nftbty

**Comment by gito10** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/4ff1b084-8de3-491f-8c05-4c08fb310c70)

我的和你怎么不同，我的没有在线、下线，也不叫“编辑”而是“修改”。你点编辑，然后把类型修改为sing-box，协议分流就可以了。

**Comment by xcyll** [comment]
用的openwrt master分支编译的 
这个翻译有点问题 个人认为 应该翻译成 上移 下移 
是的目前是手动改的 xray手动下拉切换成sing-box
改代码是不是比较麻烦
@nftbty

**Comment by gito10** [comment]
哦，你的意思是passwall新装上去，如果装有singbox，就默认把分流总结点改成sing-box类型的？

**Comment by xcyll** [comment]
是的

**Comment by xcyll** [comment]
只是看起来怪怪的 在没有装xray的情况下 显示xray分流

**Comment by VwEl** [comment]
> > 之前有过相关疑问 咋不分开 原来如此 singbox与xray兼容 [#2962 (comment)](https://github.com/xiaorouji/openwrt-passwall/issues/2962#issue-2152117522)
> 
> 之前表述不太准，也不是sing-box原来和xray兼容，而是都使用 `"geoip":"cn"` 这样的配置格式，在 passwall 的层面来说，是可以一套设置UI兼容这2个后端的。当然现在sing-box改了配置，也还是可以兼容的，只是要修改sing-box后端的配置生成代码就可以，然后根据新的 rule-set，可能会多一两个sing-box独有的配置选项，比如使用**local**还是**remote**规则，本地规则文件存放的路径，远程规则下载的baseURL。 现在sing-box 从1.8.0起是`"rule-set":"geoip-cn"`，这里的’geoip-cn‘只是一个 **tag**了，另外还要在 `rules`同级配一个
> 
> ```
> "rule_set": [
>       {
>         "tag": "geoip-cn",
>         "type": "remote",
>         "format": "binary",
>         "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
>         "download_detour": "proxy"
>       }
> ]
> ```
> 
> 或
> 
> ```
> "rule_set": [
>       {
>         "tag": "geoip-cn",
>         "type": "local",
>         "format": "binary",
>         "path": "/path/to/rule-set/geoip-cn.srs"
>       }
> ]
> ```
> 
> 其实改成这种每个子集单独一个文件还是有好处的，只需要下载需要的规则集就行了，刚看了一下， geoip-cn.srs 39.4KB geosite-cn.srs 32.4KB geosite-google.srs 8.43KB 就不需要下整个geoip.dat (10.2MB) 和 geosite.dat (5.57MB)了，使用`remote`方式的话，还可以设置指定间隔时间（不设置默认1天）更新，无须重启服务。

设置了geosite:jp之后dmm.co.jp还是会提示このサービスはお住まいの地域からは
ご利用になれません，只有 把dmm.co.jp放进去才能正常访问

**Comment by gito10** [comment]
> 设置了geosite:jp之后dmm.co.jp还是会提示このサービスはお住まいの地域からは
ご利用になれません，只有 把dmm.co.jp放进去才能正常访问

估计你用的规则源，jp里面不包含那个网站，你查查它的源码，看是不是。

**Comment by ruliuyan** [comment]
升级了也好，手里有个ax6s，以前的神机现在变成了内存困难户。这几天用了最新版的pw和pw2，在pw里面singbox解析geodata数据可能出现oom，对于ad-all出现格式兼容问题，只能用xray；在pw2里面singbox解析geodata可行，但启动的前面两分钟cpu持续处于高位，明显感觉处理geodata很吃力，xray解析必然触发oom。
相应的，oc处理geodata(全量)也必然触发oom，但如果只用拆分后的rule-set就很轻松，加上geoip(oc使用的是精简版Country mmdb)也很轻松就能拉起来，如果加上geosite必然触发oom，但是rule-set加上geoip足够用了。
前两天翻到问题，说是smartdns解析geodata也是内存爆炸。
随着geodata的数据量不停地膨胀，全量加载的话小内存设备已经没活路了。再不改继续这样下去没有512的内存都没资格科学上网了

**Comment by snowie2000** [comment]
相反的geoview解析geosite一直不会占用很多内存，解析geoip才是内存大户。geoip比geosite要大得多，还有一个合并cidr的过程超级吃内存。

adg本身就是内存大户，低配机器别用adg

**Comment by snowie2000** [comment]
geoview一定要升级到最新版，对geosite有内存优化
