### ISSUE TITLE
代理的主机无法访问.cn的域名[Bug]: 

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#2995]
### 描述您遇到的bug

代理的主机无法访问.cn的域名，其他全部正常是不是我哪里没有设置好还是插件没有安装，谢谢各位大佬了

### 复现此Bug的步骤

代理的主机无法访问.cn的域名

### 您想要实现的目的

代理的主机可以正常访问.cn的域名

### 日志信息

![屏幕截图 2024-03-06 184244](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/f068b6fa-798b-4166-9d93-d102d91ba554)

### 截图

![屏幕截图 2024-03-06 184339](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/61cc073f-d043-4f23-92f4-f2c5a80a3260)
![屏幕截图 2024-03-06 183705](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/6b2bbbbc-3dab-4a30-b10b-6a91b19daac4)
![屏幕截图 2024-03-06 183640](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/1ebd4b8a-5a7e-4886-835f-0be3e04f7d87)
![屏幕截图 2024-03-06 183605](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/10000b45-2d82-4e38-a9b7-3b067208ea30)
![屏幕截图 2024-03-06 183550](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/b74fde19-b061-4c53-8d81-acbe1823bcdb)

### 系统相关信息

Passwall 版本 4.75-6

**Comment by xh0823** [comment]
![屏幕截图 2024-03-09 015225](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/7301d3f8-ae2d-4fac-8f3f-16b0e1c5c3d9)
![屏幕截图 2024-03-09 015250](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/c1e773f9-3edb-4fc0-8126-a0ee4b2e7469)
![屏幕截图 2024-03-09 015530](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/6d2c0a70-4ca1-4a4f-9822-6846d39e5be1)
测试了不开启ChinaDNS-NG就可以打开cn域名，不开的话测试dns又泄露了，主界面不开ChinaDNS-NG，在访问控制里面启用ChinaDNS-NG好像没有生效

**Comment by xh0823** [comment]
![屏幕截图 2024-03-09 015225](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/71fa3ce4-a376-4ac1-8d1c-6de173695887)
![屏幕截图 2024-03-09 015530](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/4f5ff520-b0a6-4a0e-8ddd-b88aab83024b)
![屏幕截图 2024-03-09 015250](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/4214570c-129d-47b4-97d3-92569d962d07)

 测试了不开启ChinaDNS-NG就可以打开cn域名，不开的话测试dns又泄露了，主界面不开ChinaDNS-NG，在访问控制里面启用ChinaDNS-NG好像没有生效

**Comment by xh0823** [comment]
![屏幕截图 2024-03-11 013956](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/94781c58-5976-4812-8459-cd01e0d919d2)
经过不断测试发现不打开 GFW列表 所以cn域名都可以正常打开了，但是打开的速度明显感觉是比别的慢，那个大佬知道怎么检查一下看看为什么cn的域名都慢，是哪里解析有问题吗

**Comment by suyuanhua** [comment]
可以尝试 手动更新规则列表（规则管理 手动更新） 之后再试试。我遇到类似情况，passwall升级后.cn无法访问但其他域名都正常，后来手动更新后故障消失。

**Comment by xh0823** [comment]
> 可以尝试手动更新规则列表（规则管理手动更新）之后再尝试。我遇到类似情况，passwall升级后.cn无法访问但其他域名都正常，后来手动更新后故障消失。
现在的问题是所以.cn的域名，你没有感觉比国内其他的要慢一点吗，现在打开是正常了，而且下面没有代理的主机访问.cn域名感觉也是慢，

**Comment by suyuanhua** [comment]
> > 可以尝试手动更新规则列表（规则管理手动更新）之后再尝试。我遇到类似情况，passwall升级后.cn无法访问但其他域名都正常，后来手动更新后故障消失。
> > 现在的问题是所以.cn的域名，你没有感觉比国内其他的要慢一点吗，现在打开是正常了，而且下面没有代理的主机访问.cn域名感觉也是慢，

访问速度没有变化，路由信息也没有变化。只是在打开的第一时间，可能是因为Chinadns-ng的原因有一个停顿，猜测是dns查询的过程引起的时延。

**Comment by handsomeji** [comment]
沒有復現。
