### ISSUE TITLE
[Feature Request]: 请求加回4.75.5版本之前的“路由器本机代理模式”配置项

### ISSUE THREAD

**Issue by tiehu** [xiaorouji/openwrt-package#3001]
### 描述你想要的新功能

在4.75.6版本中，“路由器本机 TCP/UDP 代理模式”的选项被移除，转而使用一个“本机代理”的勾选框来让用户决定是否需要让路由器使用代理。
然而，这个选项的逻辑与过去版本的“路由器本机 TCP/UDP 代理模式”似乎并不相同，具体表现在：
●4.75.5及之前，当在“路由器本机 TCP/UDP 代理模式”选择的模式具有更高的优先级，将覆盖默认的代理模式。例如，如果将默认TCP代理模式设置为不代理，而路由器本机TCP代理模式选择代理，那么本机TCP将会走代理。
●4.75.6中，在默认代理模式为不代理的情况下，勾选“本机代理”，本机将不会走代理。只有在默认代理模式设置为代理的情况下才会走代理（不确定这是否是预期中的行为）。

为什么我有这样的需求：
在过去的版本中，我通过将默认代理模式设置为不代理，并结合访问控制功能来实现设备白名单（只有访问控制中指定的设备使用代理），同时使用路由器本机代理模式的选项来在此基础上确保路由器自身可以走代理（方便更新软件包源等）。
当前版本（4.75.6）下，我似乎找不到同样简单的方式来完成这个需求（如果我错了请告诉我）。

### 描述你想要的解决方案

我的第一个想法是或许可以考虑加回4.75.5版本之前的“路由器本机代理模式”配置项，来简单地解决这个问题。

### 描述你考虑过的替代方案

替代的解决方案是确保在勾选“本机代理”后，无论默认代理模式设置为何，路由器本机都会使用代理。

### 其他信息

我感觉目前版本的这个设计可能是有意为之的，所以才选择开启FR Issue。如果这其实是一个预期外的bug的话烦请修改一下Issue标签。

**Comment by SakuraFallingMad** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2991

与此有关的优化。可以做相应的设置改动

**Comment by tiehu** [comment]
> https://github.com/xiaorouji/openwrt-passwall/issues/2991
> 
> 与此有关的优化。可以做相应的设置改动

不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。
私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。

此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？
如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。

**Comment by SakuraFallingMad** [comment]
> > #2991
> > 与此有关的优化。可以做相应的设置改动
> 
> 不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。 私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。
> 
> 此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？ 如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。

您提出的第一点，吾认为逻辑上没有多大变化，依据可以从执行的日志中可以提现出来。
第二点默认代理为不代理，但是总开关没有关闭，其逻辑应该还是启动代理组件。只不过代理的判断由您设置的黑白名单、访问控制列表设置以及规则列表（如gfw与中国列表）设置等组成。

**Comment by tiehu** [comment]
> > > #2991
> > > 与此有关的优化。可以做相应的设置改动
> > 
> > 
> > 不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。 私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。
> > 此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？ 如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。
> 
> 您提出的第一点，吾认为逻辑上没有多大变化，依据可以从执行的日志中可以提现出来。 第二点默认代理为不代理，但是总开关没有关闭，其逻辑应该还是启动代理组件。只不过代理的判断由您设置的黑白名单、访问控制列表设置以及规则列表（如gfw与中国列表）设置等组成。

感谢答疑，对此我还有以下疑问：
1.如果逻辑和之前的版本没有差异，那么为什么4.75.6版本中在开启总开关，并勾选本机代理的情况下，将默认代理模式设置为不代理将导致本机代理失效？这是预期中的设计还是预期外的结果？
2.当前版本下，能否实现以下需求：
让来自不在白名单（访问控制列表）中设备的流量完全使用本地DNS进行解析（无论域名是国内还是国外、是否位于GFW列表中）并直接直连出站（就像Passwall不存在一样），而对路由器本机和在白名单内的设备则进行DNS分流和流量代理。

**Comment by SakuraFallingMad** [comment]
> > > > #2991
> > > > 与此有关的优化。可以做相应的设置改动
> > > 
> > > 
> > > 不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。 私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。
> > > 此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？ 如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。
> > 
> > 
> > 您提出的第一点，吾认为逻辑上没有多大变化，依据可以从执行的日志中可以提现出来。 第二点默认代理为不代理，但是总开关没有关闭，其逻辑应该还是启动代理组件。只不过代理的判断由您设置的黑白名单、访问控制列表设置以及规则列表（如gfw与中国列表）设置等组成。
> 
> 感谢答疑，对此我还有以下疑问： 1.如果逻辑和之前的版本没有差异，那么为什么4.75.6版本中在开启总开关，并勾选本机代理的情况下，将默认代理模式设置为不代理将导致本机代理失效？这是预期中的设计还是预期外的结果？ 2.当前版本下，能否实现以下需求： 让来自不在白名单（访问控制列表）中设备的流量完全使用本地DNS进行解析（无论域名是国内还是国外、是否位于GFW列表中）并直接直连出站（就像Passwall不存在一样），而对路由器本机和在白名单内的设备则进行DNS分流和流量代理。

1.用最新的源码试试你所说的需求
2.关于这个设置，可能的做法，概况这边开启总开关，关闭gfw列表，直连中国列表，默认代理不代理。在访问控制里，白名单设备，设置相应设置，新建一个本机的访问控制，源地址设置为0.0.0.0

**Comment by tiehu** [comment]
> > > > > #2991
> > > > > 与此有关的优化。可以做相应的设置改动
> > > > 
> > > > 
> > > > 不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。 私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。
> > > > 此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？ 如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。
> > > 
> > > 
> > > 您提出的第一点，吾认为逻辑上没有多大变化，依据可以从执行的日志中可以提现出来。 第二点默认代理为不代理，但是总开关没有关闭，其逻辑应该还是启动代理组件。只不过代理的判断由您设置的黑白名单、访问控制列表设置以及规则列表（如gfw与中国列表）设置等组成。
> > 
> > 感谢答疑，对此我还有以下疑问： 1.如果逻辑和之前的版本没有差异，那么为什么4.75.6版本中在开启总开关，并勾选本机代理的情况下，将默认代理模式设置为不代理将导致本机代理失效？这是预期中的设计还是预期外的结果？ 2.当前版本下，能否实现以下需求： 让来自不在白名单（访问控制列表）中设备的流量完全使用本地DNS进行解析（无论域名是国内还是国外、是否位于GFW列表中）并直接直连出站（就像Passwall不存在一样），而对路由器本机和在白名单内的设备则进行DNS分流和流量代理。
> 
> 1.用最新的源码试试你所说的需求
> 2.关于这个设置，可能的做法，概况这边开启总开关，关闭gfw列表，直连中国列表，默认代理不代理。在访问控制里，白名单设备，设置相应设置，新建一个本机的访问控制，源地址设置为0.0.0.0

1.看了一下commit，好像自最新版之后还没有针对这个问题的代码修改，决定暂时等一等。
2.请问“新建一个本机的访问控制，源地址设置为0.0.0.0”是什么意思？如果设置为0.0.0.0，不就相当于直接匹配了所有源IP吗？

**Comment by SakuraFallingMad** [comment]
> > > > > > #2991
> > > > > > 与此有关的优化。可以做相应的设置改动
> > > > > 
> > > > > 
> > > > > 不是很确定流量在进入分流总节点前的行为是怎么样的，但如果逻辑是如[此处讨论](https://github.com/xiaorouji/openwrt-passwall/discussions/2989)一样由上往下命中的话，我个人认为此问题可能是由于“本机代理”的优先级被设置为比“默认代理模式”更低的原因。 私以为“默认代理模式”永远应该被放在最后处理，因为它用于匹配未被其他任何规则命中的流量，被放在它之后匹配的所有规则都会失效。
> > > > > 此外想问一下有关DNS路由的问题，我注意到即使将默认代理模式设置为不代理，某些情况下DNS解析仍然会通过远程DNS而非本地DNS进行，请问这是预期行为吗？ 如果可以的话，希望知道当前passwall的DNS路由是怎样的处理流程。
> > > > 
> > > > 
> > > > 您提出的第一点，吾认为逻辑上没有多大变化，依据可以从执行的日志中可以提现出来。 第二点默认代理为不代理，但是总开关没有关闭，其逻辑应该还是启动代理组件。只不过代理的判断由您设置的黑白名单、访问控制列表设置以及规则列表（如gfw与中国列表）设置等组成。
> > > 
> > > 
> > > 感谢答疑，对此我还有以下疑问： 1.如果逻辑和之前的版本没有差异，那么为什么4.75.6版本中在开启总开关，并勾选本机代理的情况下，将默认代理模式设置为不代理将导致本机代理失效？这是预期中的设计还是预期外的结果？ 2.当前版本下，能否实现以下需求： 让来自不在白名单（访问控制列表）中设备的流量完全使用本地DNS进行解析（无论域名是国内还是国外、是否位于GFW列表中）并直接直连出站（就像Passwall不存在一样），而对路由器本机和在白名单内的设备则进行DNS分流和流量代理。
> > 
> > 
> > 1.用最新的源码试试你所说的需求
> > 2.关于这个设置，可能的做法，概况这边开启总开关，关闭gfw列表，直连中国列表，默认代理不代理。在访问控制里，白名单设备，设置相应设置，新建一个本机的访问控制，源地址设置为0.0.0.0
> 
> 1.看了一下commit，好像自最新版之后还没有针对这个问题的代码修改，决定暂时等一等。 2.请问“新建一个本机的访问控制，源地址设置为0.0.0.0”是什么意思？如果设置为0.0.0.0，不就相当于直接匹配了所有源IP吗？

https://github.com/xiaorouji/openwrt-passwall/issues/2991

看下这个issue是否符合你的需求思路，主要我的基本设置是最简单，内网内都是分流代理为主。

**Comment by handsomeji** [comment]
是預期行為。
現在，你可以把首頁的配置當成是一套默認策略組。
https://github.com/xiaorouji/openwrt-passwall/discussions/2989
根據你的需求，你可以先更新到最新版本。
如果你只希望指定的設備和路由器本機走代理，那就勾選模式裡面的路由器本機代理，不要勾選客戶端代理。然後創建訪問控制，使用全局配置即可。
