### ISSUE TITLE
大佬，你好，访问控制希望可以增加tcp或udp直接请求dns选项，谢谢[Feature Request]: 

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#3003]
### 描述你想要的新功能
访问控制里面的dns过滤模式只有这两个选项
![Screenshot_20240308_151138](https://github.com/xiaorouji/openwrt-passwall/assets/5343595/ae593426-d009-4e27-9cbc-c44c6ca61ad2)

### 描述你想要的解决方案

希望可以像主dns设置那样，可以通过tcp或者udp直接请求dns，谢谢
![Screenshot_20240308_151153](https://github.com/xiaorouji/openwrt-passwall/assets/5343595/64e13a4c-47f7-4bf4-8394-938eb14d7b43)

**Comment by xcyll** [comment]
使用场景：指定设备代理
之前的旧版本只要 **访问控制**-指定的设备那里-选择默认节点还可以套用主DNS那里的设置 (如：通过udp请求DNS-127.0.0.1:5335)
![① 2024-03-08 153836](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/345a418c-5a05-4d1f-96f5-756abcead4bf)

改过后的访问控制 节点选择项里 没有该 **默认** 选项了 只能选择具体节点了 可否考虑加回去

**Comment by xcyll** [comment]
借楼顺带提下
目前使用场景：指定设备代理
之前的旧版本只要 **访问控制**-指定的设备那里-选择默认节点还可以套用主DNS那里的设置 (如：通过udp请求DNS-127.0.0.1:5335)
![① 2024-03-08 153836](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/345a418c-5a05-4d1f-96f5-756abcead4bf)

改过后的访问控制 节点选择项里 没有该 **默认** 选项了 只能选择具体节点了和使用访问控制那里的DNS设置了 可否考虑加回去 
@xiaorouji

**Comment by xcyll** [comment]
或者访问控制里亦加入 通过TCP或者UDP请求DNS 选项

**Comment by xcyll** [comment]
5335端口的DNS服务 希望也可以用于 访问控制 下的所有设备

**Comment by xcyll** [comment]
至于访问控制下增加自定义DNS这个问题 之前有问过大佬 

![② 2024-03-08 161937](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/7c45322c-144f-4db3-9c49-315e44bdf453)

**Comment by xcyll** [comment]
至于访问控制下增加自定义DNS这个问题 之前有问过大佬 
![② 2024-03-08 161937](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/bfade5d3-1ef8-405d-a6b7-522c21dd0f23)

**Comment by BGzEroll** [comment]
> 使用场景：指定设备代理 之前的旧版本只要 **访问控制**-指定的设备那里-选择默认节点还可以套用主DNS那里的设置 (如：通过udp请求DNS-127.0.0.1:5335) ![① 2024-03-08 153836](https://private-user-images.githubusercontent.com/63227888/311155853-345a418c-5a05-4d1f-96f5-756abcead4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTA3NzUsIm5iZiI6MTcwOTg5MDQ3NSwicGF0aCI6Ii82MzIyNzg4OC8zMTExNTU4NTMtMzQ1YTQxOGMtNWEwNS00ZDFmLTk2ZjUtNzU2YWJjZWFkNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA5MzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OTNkZGEwMWU1M2ZkN2I3NDczYTY1NjM0NjUzMzdmZWExZDZlZjg4MmUyZTg2MzVhZmVjYjllYjg0YzJkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aly1qw5X90GzXnx5gHJjaQnRADEIzBnFhzBhwF4D9a4)
> 
> 改过后的访问控制 节点选择项里 没有该 **默认** 选项了 只能选择具体节点了和使用访问控制那里的DNS设置了 可否考虑加回去 @xiaorouji

4.75-2还有**使用全局配置**这个选项，不知道为何之后就没了😂希望能加回来吧，还有访问控制的**过滤模式**也希望加个**使用全局配置**的选项吧

**Comment by handsomeji** [comment]
暫無計劃，太臃腫
