### ISSUE TITLE
[Bug]: 最新版本4.75-6无法获取ChinaDNS-NG下载地址

### ISSUE THREAD

**Issue by liuwleo** [xiaorouji/openwrt-package#3005]
### 描述您遇到的bug

最新版本4.75-6无法获取ChinaDNS-NG下载地址

### 复现此Bug的步骤

<img width="867" alt="Snipaste_2024-03-08_19-26-59" src="https://github.com/xiaorouji/openwrt-passwall/assets/49121177/24a90c19-2572-4d3a-a654-ee58b9d0b150">

### 您想要实现的目的

望给予修复

### 日志信息

<img width="867" alt="Snipaste_2024-03-08_19-26-59" src="https://github.com/xiaorouji/openwrt-passwall/assets/49121177/476f0a69-a79a-4a62-a36b-092ea55222eb">

### 截图

<img width="867" alt="Snipaste_2024-03-08_19-26-59" src="https://github.com/xiaorouji/openwrt-passwall/assets/49121177/679dce04-360e-4947-a8e1-c61ad6fc4a0c">

### 系统相关信息

版本：4.75-6

**Comment by xcyll** [comment]
![IMG_6493](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/10297945-25b9-4281-bf47-d5d2bac34f7f)
確實如此

**Comment by Jasonzhang2023** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122073349/abda1aaf-c0e9-4f0d-be12-8de12f51610f)
the same issue.

**Comment by gito10** [comment]
不是passwall版本问题，是chinadns-ng 新版 release 文件命名格式改了，得重新适配。看更新日志，是新版本构建方式有重大更改，不再使用Makefile。

**Comment by xcyll** [comment]
有大佬更新了 重新编译吧 旧的机制已弃用
![IMG_6497](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/2b02cfac-d9fc-4cbb-a652-09e1e9500995)

**Comment by FunnyFly-ZW** [comment]
@nftbty  已经修了 f07d0a054bd87811645805342c1a60f9b35e253a

**Comment by minfengyk** [comment]
拉取最新源码，编译后仍无法获取最新下载地址。

**Comment by nftbty** [comment]
> 拉取最新源码，编译后仍无法获取最新下载地址。

你编译的时候还没合并，现在是合并了。
其实不用重新编译，你直接修改路由上对应的文件，照着我那个提交，修改你自己架构对应的那行，然后测试行不行。

**Comment by gito10** [comment]
@liuwleo 你把最新pr #3011 的修改手动修改到路由上试试，应该是可以了。

**Comment by liuwleo** [comment]
感谢

**Comment by gito10** [comment]
好了是吧？你路由是什么架构的？

**Comment by liuwleo** [comment]
x86平台

**Comment by gito10** [comment]
> x86平台

是不是`x86_64`？这次新发布的二进制程序，x86_64 有 `x86_64`、`x86_64_v2`、`x86_64_v3`、`x86_64_v4`四个版本，我给匹配的 v4 版本，你机器能正常跑起来chinadns-ng吗？

**Comment by liuwleo** [comment]
對，X86-64。但是試用半天后，發現有異常，表現為打開後，出現DNS錯誤，youtube沒有預覽圖。所以關閉了。

**Comment by babyhz** [comment]
x86_64平台更新 4.75-8 后ChinaDNS-NG 可以检测版本更新，但是点击更新后提示“客户端文件不适合当前设备。chinadns-ng__/tmp/chinadns-ng_download.MDBOnJ”

**Comment by gito10** [comment]
@babyhz @liuwleo 把`/usr/lib/lua/luci/passwall/com.lua`第65行最后的`x86_64_v4`改为`x86_64_v3`、`x86_64_v2`和`x86_64`分别试一下，看最高支持的是哪个版本。

**Comment by liuwleo** [comment]
都不行，全部为：客户端文件不适合当前设备。chinadns-ng__/tmp/chinadns-ng_download.（此后缀版本不同，显示也不同。）

**Comment by gito10** [comment]
> x86_64

无后缀的，改成`x86_64@` 试试。

**Comment by liuwleo** [comment]
我的意思是报错信息后缀更具不同版本，都不一样

**Comment by tmpaxx** [comment]
我刚编译的也有同样的问题

**Comment by gito10** [comment]
你用 
x86_64_v4
x86_64_v3
x86_64_v2
x86_64@
这4个版本都报错，都不能成功运行？这次新版，x86_64架构总共就这4个版本。

**Comment by tmpaxx** [comment]
4个版本都报错  客户端文件不适合当前设备。chinadns-ng__/tmp/chinadns-ng_download.后缀变化

**Comment by handsomeji** [comment]
因為有lua緩存。
改了之後需要 `rm -rf /tmp/luci-*` 再試
確定清空lua緩存再試嗎？
我這裡只能用x86_64和x86_64_v2 這兩個版本

**Comment by gito10** [comment]
估计也就是扩展指令集要求的不同，用v2、v3、v4还不如直接标明最低扩展指令集版本。

**Comment by liuwleo** [comment]
> 因為有lua緩存。 改了之後需要 `rm -rf /tmp/luci-*` 再試 確定清空lua緩存再試嗎？ 我這裡只能用x86_64和x86_64_v2 這兩個版本

的确，按照您的方法，更新成功。V2版本

**Comment by gito10** [comment]
那 x86_64架构的是改为v2版，还是干脆直接无后缀版了？

**Comment by fxckme** [comment]
改V2版本成功~
清緩存：rm -rf /tmp/luci-*

**Comment by NeedforGit** [comment]
> @babyhz @liuwleo 把`/usr/lib/lua/luci/passwall/com.lua`第65行最后的`x86_64_v4`改为`x86_64_v3`、`x86_64_v2`和`x86_64`分别试一下，看最高支持的是哪个版本。

感谢！
