### ISSUE TITLE
[Feature Request]: 令人困惑的[基本设置]-[模式]

### ISSUE THREAD

**Issue by krkrchan** [xiaorouji/openwrt-package#3008]
### 描述你想要的新功能

1、模式设置变成了TCP/UDP默认代理模式+路由器本机代理+客户端代理，感觉有些重复且难以理解。
我无法理解这几项设置的优先级。例如，我设置：TCP默认[代理]，UDP默认[不代理]，本机[是]，客户端[否]，那他们的具体运行效果到底是怎样的？

2、在[访问控制]设置界面，TCP 、UDP节点不能设置为同基本设置-主要 项下的设置。

### 描述你想要的解决方案

1、我还是喜欢老的模式设置样式：TCP/UDP默认代理模式和本机TCP/UDP代理模式，简洁明了。

2、增加【与基本设置相同】选项。

**Comment by pangzhaoyhy** [comment]
疑问,不知这样改有什么意义

**Comment by handsomeji** [comment]
現在，你可以把首頁的配置當成是一套默認策略組。
https://github.com/xiaorouji/openwrt-passwall/discussions/2929#discussioncomment-8556858
https://github.com/xiaorouji/openwrt-passwall/discussions/2989#discussion-6308210
訪問控制優先級最高。
訪問控制已有全局選項
