### ISSUE TITLE
[Feature Request]: 访问控制将TCP/UDP转发端口选项独立出来

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3013]
### 描述你想要的新功能

需求：nas需要**仅代理tcp的80和443**端口，其他例如节点与dns设置想要保持全局设置。
在4.75-7中访问控制添加了使用全局配置的选项，但勾选后并不能自定义需要转发的端口，希望能将**TCP/UDP转发端口**选项独立成**TCP/UDP不转发端口**一样的选项

### 描述你想要的解决方案

希望勾选**使用全局配置**后能将**TCP/UDP转发端口**选项独立成**TCP/UDP不转发端口**一样的选项

**Comment by Henshufu** [comment]
还没有升级新版本，之前的版本，中国列表之外模式，不转发端口填了也是无效的。选GFW模式才能生效。

**Comment by handsomeji** [comment]
先用不转发端口实现吧
1:79,81:442,444:65535

**Comment by handsomeji** [comment]
試下最新版本

**Comment by BGzEroll** [comment]
> 試下最新版本

已升到最新版本，路由与功能一切正常
