### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by dxmsk** [xiaorouji/openwrt-package#3014]
### 描述你想要的新功能

希望能加回自动切换功能

### 描述你想要的解决方案

因为节点不太稳定时常有些被炸，每次都要手动进去换

### 描述你考虑过的替代方案

也可以在分流规则里加上自动切换功能

**Comment by BGzEroll** [comment]
自动切换在socks配置里有

**Comment by dxmsk** [comment]
> 自动切换在socks配置有

用了用不了分流🥹

**Comment by BGzEroll** [comment]
> > 自动切换在socks配置有
> 
> 用了用不了分流🥹

你可以把分流的默认节点设置为该socks

**Comment by lllrrr2** [comment]
iptables透明代理基础依赖 iptables-mod-socket 未安装 ，openwrt 21版及以下都没有这个包，是不是无法使用自动切换。22-23版就可以用socket来自动切换。感觉以前那种切换方式更通用些

**Comment by BGzEroll** [comment]
> iptables透明代理基础依赖 iptables-mod-socket 未安装 ，openwrt 21版及以下都没有这个包，是不是无法使用自动切换。22-23版就可以用socket来自动切换。感觉以前那种切换方式更通用些

这包在21.02里集成在tproxy模块里了，不需要理会

**Comment by lllrrr2** [comment]
> > iptables透明代理基础依赖 iptables-mod-socket 未安装 ，openwrt 21版及以下都没有这个包，是不是无法使用自动切换。22-23版就可以用socket来自动切换。感觉以前那种切换方式更通用些
> 
> 这包在21.02里集成在tproxy模块里了，不需要理会

再请教一下，openwrt 19版能用socket自动切换吧，我用了官方19.07的源码编译后，没法使用，建的sock节点测试都能通，但就是测试谷歌和github都提示无法连接
![image](https://github.com/xiaorouji/openwrt-passwall/assets/61368564/17bcc98b-b0e7-4d5d-8041-25ed7fc0e062)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/61368564/7f10b278-b9ee-440e-b0ac-8415417337e8)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/61368564/a5bd8912-885a-495f-a2a9-3db7e84e8bd9)
