### ISSUE TITLE
[Bug]: 开启访问控制后重启openwrt，openwrt日志中有报错

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3018]
### 描述您遇到的bug

开启访问控制后重启openwrt，openwrt日志会报错：
**Mon Mar 11 20:28:25 2024 daemon.notice procd: /etc/rc.d/S99passwall: cat: can't open '/tmp/etc/passwall/acl/default/rule_list': No such file or directory**

但似乎并不会影响使用，代理一切正常

### 复现此Bug的步骤

1.开启访问控制
2.重启openwrt

### 您想要实现的目的

希望能修复该报错

### 日志信息

passwall日志一切正常
openwrt日志报错：**Mon Mar 11 20:28:25 2024 daemon.notice procd: /etc/rc.d/S99passwall: cat: can't open '/tmp/etc/passwall/acl/default/rule_list': No such file or directory**

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/d3844235-29eb-4e38-9ba4-24abdf925b7b)

### 系统相关信息

Passwall为[a522569](https://github.com/xiaorouji/openwrt-passwall/commit/a52256988ab2a3e236603b740f0f35d4c06696c8)最新commit

openwrt版本：ImmortalWrt 21.02-SNAPSHOT

**Comment by handsomeji** [comment]
下個版本會修正。
