### ISSUE TITLE
[Bug]: acl里tcp proxy drop port 里有俩use global setting

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#3019]
### 描述您遇到的bug

acl里tcp proxy drop port 里有俩use global setting

### 复现此Bug的步骤

Acl tab
Create one setting 
Move to tcp proxy drop port

### 您想要实现的目的

修复错误

### 日志信息

No logs

### 截图

![Screenshot_2024-03-11-22-35-50-078_com android chrome](https://github.com/xiaorouji/openwrt-passwall/assets/31793080/508cddf5-dce1-46fe-9554-5ea5e5a27db2)

### 系统相关信息

截止目前最新源码

**Comment by handsomeji** [comment]
下個版本會修正。
