### ISSUE TITLE
[Bug]: 6.6内核V2ray-plugin编译不过，6.1内核正常

### ISSUE THREAD

**Issue by kxdn3** [xiaorouji/openwrt-package#3020]
### 描述您遇到的bug

云编译6.6内核V2ray-plugin编译错误，6.1下正常

### 复现此Bug的步骤

无

### 您想要实现的目的

麻烦修复

### 日志信息

make[3] -C package/openwrt-passwall/simple-obfs compile
112
 make[3] -C package/openwrt-passwall/v2ray-plugin compile
113
    ERROR: package/openwrt-passwall/v2ray-plugin failed to build.
114
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
115
make: *** [/home/runner/work/OpenWrt-haiibo/OpenWrt-haiibo/openwrt/include/toplevel.mk:231: world] Error 1

### 系统相关信息

最新源码，lede源码

**Comment by kxdn3** [comment]
确认是golang上游的问题，解决了 
# 移除 openwrt feeds 自带的核心包
rm -rf feeds/packages/net/{xray-core,v2ray-core,v2ray-geodata,sing-box}
git clone https://github.com/sbwml/openwrt_helloworld package/helloworld

# 更新 golang 1.22 版本
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang

**Comment by uingei** [comment]
v2ray 早前被移除了，我想问留这个 plugin 有什么用？

**Comment by SakuraFallingMad** [comment]
> v2ray 早前被移除了，我想问留这个 plugin 有什么用？

那是给shadowsocks的sip003插件
