### ISSUE TITLE
[Feature Request]: 关于sing-box bittorrent协议直连

### ISSUE THREAD

**Issue by yjd0608** [xiaorouji/openwrt-package#3022]
### 描述你想要的新功能

sing-box是不是不支持分流bittorrent？用sing-box分流速度起不来（可能是这部分流量走了机场，机场貌似把这个审计掉了），换xray立马快了，分流规则都是一样的，将bittorrent协议直连。（设置成转发常用端口后正常，不过还是想转发全部端口）

### 描述你想要的解决方案

无，讨论一下。

**Comment by handsomeji** [comment]
不支持，就算是Xray的BT嗅探也其實有問題。
