### ISSUE TITLE
[Feature Request]: passwall19.07和23.05版本有何区别

### ISSUE THREAD

**Issue by 97668589** [xiaorouji/openwrt-package#3024]
### 描述你想要的新功能

passwall19.07和23.05版本有何区别

### 描述你想要的解决方案

passwall19.07和23.05版本有何区别

**Comment by jh0072110** [comment]
你问错地方了吧…

**Comment by gito10** [comment]
确实，这个应该在讨论里问。
区别的话，在于19.07版编译的是给旧版op（低于23.05）用的，而23.05以上因为luci转为使用ucode而不是lua，默认是不带lua环境的，所以基于lua的旧版luci App想正常安装使用，会添加一个额外的依赖包 lua-luci-runtime（名字不一定对，就这个意思）。
而旧版op是根本没有这个包的，如果安装23.05版sdk编译的，会报依赖错误。

**Comment by IceCokes** [comment]
@nftbty 老哥我想问下，如果是基于Lean大雕源码（不是基于Luci 18.06的吗）编译的固件安装19.07版使用会有问题吗，我试了下能正常安装就是不知道使用会不会有问题。

**Comment by Jasonzhang2023** [comment]
> 确实，这个应该在讨论里问。 区别的话，在于19.07版编译的是给旧版op（低于23.05）用的，而23.05以上因为luci转为使用ucode而不是lua，默认是不带lua环境的，所以基于lua的旧版luci App想正常安装使用，会添加一个额外的依赖包 lua-luci-runtime（名字不一定对，就这个意思）。 而旧版op是根本没有这个包的，如果安装23.05版sdk编译的，会报依赖错误。

懂了
另外名字的全名是：luci-lua-runtime_all.ipk
这个我安装过，是你说的缺乏依赖
