### ISSUE TITLE
[Feature Request]: new passwall couldnet url test

### ISSUE THREAD

**Issue by Sepehrdibaj** [xiaorouji/openwrt-package#3026]
### 描述你想要的新功能

ho o use last version of passwall and url test didnt work and timeot but server works ! in check this problem with  50 difrent server

### 描述你想要的解决方案

ho o use last version of passwall and url test didnt work and timeot but server works ! in check this problem with  50 difrent server

**Comment by handsomeji** [comment]
check your curl.
