### ISSUE TITLE
[Bug]: 开启socks自动切换时，会向瓦工发送很多 smtp 请求，导致瓦工mass mailing报错

### ISSUE THREAD

**Issue by Anyone20** [xiaorouji/openwrt-package#3028]
### 描述您遇到的bug

1，昨天瓦工突然报错
<img width="1293" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/3a213bc0-0918-4182-b68f-0c49852dab36">

登录瓦工后台查看，提示 Mass Mailing，使用瓦工发送了很多垃圾邮件，处罚是服务器被暂停，并被扣 100 分

2，尝试解决
Google 后有类似案例 [https://glglife.com/index.php/2021/09/25/ban-wa-gong-massmailing-wen-ti-jie-jue/](https://glglife.com/index.php/2021/09/25/ban-wa-gong-massmailing-wen-ti-jie-jue/)

按帖子方法瓦工屏蔽相关端口，passwall 不转发相关端口
<img width="862" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/8c5163ce-ea76-4c15-9c6c-89596a99fbc9">
<img width="530" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/3be71633-034a-4147-a8a7-930ce5a019dd">
<img width="538" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/40b2d50c-dbb4-4054-9fb1-0e31562768df">

发现仍会有一些 smtp、imap 之类的请求：
<img width="638" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/11874b40-4ee4-46aa-ba09-115a1fc77e65">
<img width="1001" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/cadcc12b-296c-4443-b187-8aeb5f1fde27">
<img width="584" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/4b38581e-6e55-4019-af99-61276bcc57a5">

经过多次测试，当passwall 使用的scoks 自动切换时，会有这些请求：
<img width="1115" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/3efe69a6-a546-47a5-9349-04db07df78eb">

当关闭 scoks自动切换后，这些请求就没有了
<img width="1029" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/07c76415-5db7-492c-9dae-9f06c23134d6">

socks 自动切换是按照这个方法设置的：[https://wp.gxnas.com/13924.html](https://wp.gxnas.com/13924.html)

请教大佬，这种情况该怎么处理？

### 复现此Bug的步骤

启用 socks节点

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

passwall版本：4.75-9，4.73-4都有这个问题

**Comment by yk271** [comment]
这是把 socks 端口暴露给外网了吧，检查防火墙配置

**Comment by handsomeji** [comment]
為什麼你們都喜歡把防火墻默認入站數據打開？

**Comment by Anyone20** [comment]
> 為什麼你們都喜歡把防火墻默認入站數據打開？

要访问内网，所以打开了。
passwall服务端启用，通过代理访问内网。
是不是 socks 自动切换方式不安全？现在使用 xray 的负载均衡模式正常，不知道该模式是否支持自动切换，自动恢复。

**Comment by Anyone20** [comment]
> 这是把 socks 端口暴露给外网了吧，检查防火墙配置

这个 socks 端口是内网使用的吧。能否实现屏蔽外网访问该端口，内网可以访问该端口？

**Comment by yk271** [comment]
访问内网用端口转发去转发指定端口，不要开那个入站

**Comment by handsomeji** [comment]
請增加安全意識，默認不要放行所有端口，僅把需要外網訪問的port單獨放行。

**Comment by Anyone20** [comment]
> 访问内网用端口转发去转发指定端口，不要开那个入站
> 請增加安全意識，默認不要放行所有端口，僅把需要外網訪問的port單獨放行。

好的，感谢，这样可以。
