### ISSUE TITLE
[Bug]: 改版后，ss订阅节点插件默认为无，需手动选择

### ISSUE THREAD

**Issue by kxdn3** [xiaorouji/openwrt-package#3032]
### 描述您遇到的bug

passwall改版后，ss订阅机场用shadowsocks-libev就爬墙不了，后来发现插件默认为无，需要每个节点更改obfs插件选择V2ray-plugin才能正常

### 复现此Bug的步骤

…

### 您想要实现的目的

ss节点会自动选择obfs插件

### 日志信息

无

### 截图

![IMG_1487](https://github.com/xiaorouji/openwrt-passwall/assets/51870018/9b9b6359-735a-4688-9303-355d781f5823)

### 系统相关信息

最新passwall源码，最新lean源码

**Comment by gito10** [comment]
另一个issue下面让你对比下正确和错误的参数值，可以把正确的值和错误的值都贴到这里来。

**Comment by kxdn3** [comment]
> 另一个issue下面让你对比下正确和错误的参数值，可以把正确的值和错误的值都贴到这里来。

好，等我回家了搞

**Comment by kxdn3** [comment]
> 另一个issue下面让你对比下正确和错误的参数值，可以把正确的值和错误的值都贴到这里来。

晚上重新试了下，obfs插件选择V2ray-plugin也是爬不了的🤣

**Comment by kxdn3** [comment]
手动设置的话必须选择Sing-Box ，插件选择obfs-local才正常，选V2ray-plugin也不行，而用shadowsocks Libev的话就没有obfs-local插件，只有V2ray-plugin，所以就不能用

**Comment by lwb1978** [comment]
编译的时候选择Simple_Obfs了吗？

**Comment by gito10** [comment]
> 手动设置的话必须选择Sing-Box ，插件选择obfs-local才正常，选V2ray-plugin也不行，而用shadowsocks Libev的话就没有obfs-local插件，只有V2ray-plugin，所以就不能用

之前#3009里就提醒过你，安装ss-libev和obfs 插件试试，后来看你说手动选择v2ray-plugin才正常，还以为你的节点就是用的v2ray插件呢。
看了op官方源，没有，#3009 下面昨天我有发一个链接，那里面有下载的，就是这个[openwrt-passwall-build](https://sourceforge.net/projects/openwrt-passwall-build/files/)。

**Comment by kxdn3** [comment]
查了下确实没有…我也没动编译啊，可能改版前做了依赖？

**Comment by kxdn3** [comment]
关了吧，添加了CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs=y 解决了🤣
