### ISSUE TITLE
编译成功了，找不到文件？

### ISSUE THREAD

**Issue by 725216** [xiaorouji/openwrt-package#3035]
### 描述您遇到的bug

插件选择里我选择了下面的这些：
 [ ] Include Shadowsocks Rust Server                              │ │  
  │ │    [*] Include ShadowsocksR Libev Client                            │ │  
  │ │    [ ] Include ShadowsocksR Libev Server                            │ │  
  │ │    [*] Include Simple-Obfs (Shadowsocks Plugin)                     │ │  
  │ │    [ ] Include Sing-Box                                             │ │  
  │ │    [ ] Include Trojan-Plus                                          │ │  
  │ │    [*] Include V2ray_Geodata                                        │ │  
  │ │    [*] Include V2ray-Plugin (Shadowsocks Plugin)                    │ │  
  │ │    [*] Include Xray                                                 │ │  
  │ │    [*] Include Xray-Plugin (Shadowsocks Plugin

编译成功，没有报错，

**为什么少了一些插件呢？少了v2ray和xray?**

### 复现此Bug的步骤

sdk编译

### 您想要实现的目的

正常编译出插件

### 日志信息

> postinst; ( echo "#!/bin/sh"; echo "[ -x "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_luci_i18n_passwall_zh_cn_postinst" > postinst-pkg; chmod 0755 postinst-pkg; )
install -d -m0755 /home/rxy/PandoraBox-SDK/bin/packages/mipsel_1004kc_dsp/base
/home/rxy/PandoraBox-SDK/scripts/ipkg-build -c -o 0 -g 0 /home/rxy/PandoraBox-SDK/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/luci-app-passwall/ipkg-all/luci-i18n-passwall-zh-cn /home/rxy/PandoraBox-SDK/bin/packages/mipsel_1004kc_dsp/base
Packaged contents of /home/rxy/PandoraBox-SDK/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/luci-app-passwall/ipkg-all/luci-i18n-passwall-zh-cn into /home/rxy/PandoraBox-SDK/bin/packages/mipsel_1004kc_dsp/base/luci-i18n-passwall-zh-cn_4.75-9_all.ipk
if [ -f /home/rxy/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/pkginfo/luci-app-passwall.default.install.clean ]; then rm -f /home/rxy/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/pkginfo/luci-app-passwall.default.install /home/rxy/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/pkginfo/luci-app-passwall.default.install.clean; fi
make[2]: Leaving directory '/home/rxy/PandoraBox-SDK/package/helloworld/luci-app-passwall'
make[1]: Leaving directory '/home/rxy/PandoraBox-SDK'

### 系统相关信息

编译最新版本

**Comment by 725216** [comment]
另外用命令make package/xray-core/compile V=99编译xray或v2ray时，下载在文件时会出错，go1.20.6.linux-.tar.gz这个文件应该是不存在的


Download failed.
--2024-03-16 21:05:08--  https://sources.openwrt.org/go1.20.6.linux-.tar.gz
Resolving sources.openwrt.org (sources.openwrt.org)... 2a03:4000:3b:221::1, 185.163.119.85
Connecting to sources.openwrt.org (sources.openwrt.org)|2a03:4000:3b:221::1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-16 21:05:10 ERROR 404: Not Found.

**Comment by lwb1978** [comment]
v2ray 只是插件没有程序，xray编译需要go1.22

**Comment by 725216** [comment]
> v2ray 只是插件没有程序，xray编译需要go1.22

不是1.22的问题，是下载的文件 https://sources.openwrt.org/go1.20.6.linux-.tar.gz，
go1.20.6.linux-.tar.gz这个应该是不存在的，应该怎么修改？

**Comment by 725216** [comment]
> v2ray 只是插件没有程序，xray编译需要go1.22
另外编译出了luci-app-passwall，但是少了v2ray,单独用上面的命令就出了上面的错误

![2024-03-17 08-54-12屏幕截图](https://github.com/xiaorouji/openwrt-passwall/assets/22210790/bce739d2-d4aa-47b6-9b87-e1b2d903d1ff)

**Comment by sbwml** [comment]
> > v2ray 只是插件没有程序，xray编译需要go1.22
> 
> 不是1.22的问题，是下载的文件 [https://sources.openwrt.org/go1.20.6.linux-.tar.gz，](https://sources.openwrt.org/go1.20.6.linux-.tar.gz%EF%BC%8C) go1.20.6.linux-.tar.gz这个应该是不存在的，应该怎么修改？

1.20.6 是 bootstrap go，你应该检查你的网络状态，因为只当 makefile 中的 GO_SOURCE_URLS 下载不了文件，openwrt 的构建脚本才会在已有的所有源中尝试下载（当然这个尝试下载是绝对失败的，因为go 根本不可能会出现在op下载源）

直接 `make xxx/xxx/xray/compile V=s` 的方式编译单个插件，你才能真正找到出现问题的原因和处理办法。以你现在得到的所有信息，几乎没有价值。只能算命

**Comment by 725216** [comment]
> > > v2ray 只是插件没有程序，xray编译需要go1.22
> > 
> > 
> > 不是1.22的问题，是下载的文件 [https://sources.openwrt.org/go1.20.6.linux-.tar.gz，](https://sources.openwrt.org/go1.20.6.linux-.tar.gz%EF%BC%8C) go1.20.6.linux-.tar.gz这个应该是不存在的，应该怎么修改？
> 
> 1.20.6 是 bootstrap go，你应该检查你的网络状态，因为只当 makefile 中的 GO_SOURCE_URLS 下载不了文件，openwrt 的构建脚本才会在已有的所有源中尝试下载（当然这个尝试下载是绝对失败的，因为go 根本不可能会出现在op下载源）
> 
> 直接 `make xxx/xxx/xray/compile V=s` 的方式编译单个插件，你才能真正找到出现问题的原因和处理办法。以你现在得到的所有信息，几乎没有价值。只能算命

应该跟网络没关系，按你的说法是网络问题，那么我在腾讯云上开了一个香港云服务器，为什么也是报一样的错呢、。而且最主要的问题是编译完了少了插件，正常情况不是选择了插件，只要编译luci-app-passwall,插件自动就编译出来了？
![1](https://github.com/xiaorouji/openwrt-passwall/assets/22210790/35ce4589-ea77-47ee-b63f-24116e2c5b0d)

**Comment by sbwml** [comment]
> > > > v2ray 只是插件没有程序，xray编译需要go1.22
> > > 
> > > 
> > > 不是1.22的问题，是下载的文件 [https://sources.openwrt.org/go1.20.6.linux-.tar.gz，](https://sources.openwrt.org/go1.20.6.linux-.tar.gz%EF%BC%8C) go1.20.6.linux-.tar.gz这个应该是不存在的，应该怎么修改？
> > 
> > 
> > 1.20.6 是 bootstrap go，你应该检查你的网络状态，因为只当 makefile 中的 GO_SOURCE_URLS 下载不了文件，openwrt 的构建脚本才会在已有的所有源中尝试下载（当然这个尝试下载是绝对失败的，因为go 根本不可能会出现在op下载源）
> > 直接 `make xxx/xxx/xray/compile V=s` 的方式编译单个插件，你才能真正找到出现问题的原因和处理办法。以你现在得到的所有信息，几乎没有价值。只能算命
> 
> 应该跟网络没关系，按你的说法是网络问题，那么我在腾讯云上开了一个香港云服务器，为什么也是报一样的错呢、。而且最主要的问题是编译完了少了插件，正常情况不是选择了插件，只要编译luci-app-passwall,插件自动就编译出来了？ ![1](https://private-user-images.githubusercontent.com/22210790/313471487-35ce4589-ea77-47ee-b63f-24116e2c5b0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzkyODUsIm5iZiI6MTcxMDY3ODk4NSwicGF0aCI6Ii8yMjIxMDc5MC8zMTM0NzE0ODctMzVjZTQ1ODktZWE3Ny00N2VlLWI2M2YtMjQxMTZlMmM1YjBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OGRmYjA1MDhkYjgzOWJiMjczMGVlOTE0NmY0NzAzZGFiZmQ1MjYxODYyMzMwZWNhODY2MWE0MjA2Yzk1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbN8wX6Wef6mvYZG9InvWhCQWbs0xtYnEKPMZkNBIbs)

看到问题所在了。`go1.20.6.linux-.tar.gz` 

你的 golang 来自哪里？

**Comment by 725216** [comment]
> > > > > v2ray 只是插件没有程序，xray编译需要go1.22
> > > > 
> > > > 
> > > > 不是1.22的问题，是下载的文件 [https://sources.openwrt.org/go1.20.6.linux-.tar.gz，](https://sources.openwrt.org/go1.20.6.linux-.tar.gz%EF%BC%8C) go1.20.6.linux-.tar.gz这个应该是不存在的，应该怎么修改？
> > > 
> > > 
> > > 1.20.6 是 bootstrap go，你应该检查你的网络状态，因为只当 makefile 中的 GO_SOURCE_URLS 下载不了文件，openwrt 的构建脚本才会在已有的所有源中尝试下载（当然这个尝试下载是绝对失败的，因为go 根本不可能会出现在op下载源）
> > > 直接 `make xxx/xxx/xray/compile V=s` 的方式编译单个插件，你才能真正找到出现问题的原因和处理办法。以你现在得到的所有信息，几乎没有价值。只能算命
> > 
> > 
> > 应该跟网络没关系，按你的说法是网络问题，那么我在腾讯云上开了一个香港云服务器，为什么也是报一样的错呢、。而且最主要的问题是编译完了少了插件，正常情况不是选择了插件，只要编译luci-app-passwall,插件自动就编译出来了？ ![1](https://private-user-images.githubusercontent.com/22210790/313471487-35ce4589-ea77-47ee-b63f-24116e2c5b0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzkyODUsIm5iZiI6MTcxMDY3ODk4NSwicGF0aCI6Ii8yMjIxMDc5MC8zMTM0NzE0ODctMzVjZTQ1ODktZWE3Ny00N2VlLWI2M2YtMjQxMTZlMmM1YjBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OGRmYjA1MDhkYjgzOWJiMjczMGVlOTE0NmY0NzAzZGFiZmQ1MjYxODYyMzMwZWNhODY2MWE0MjA2Yzk1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbN8wX6Wef6mvYZG9InvWhCQWbs0xtYnEKPMZkNBIbs)
> 
> 看到问题所在了。`go1.20.6.linux-.tar.gz`
> 
> 你的 golang 来自哪里？

https://github.com/xiaorouji/openwrt-passwall/issues/3020这个帖子里的
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang

**Comment by sbwml** [comment]
考虑用openwrt 官方仓库的golang pr 吧。你现在用的这个不适用于你的环境，因为无法读取到你的宿主机 HOST_ARCH 信息
