### ISSUE TITLE
[Bug]: 订阅失败“暂时不支持href="https类型的节点订阅”

### ISSUE THREAD

**Issue by Anyone20** [xiaorouji/openwrt-package#3038]
### 描述您遇到的bug

每次手动或者自动订阅时
---
<img width="1952" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/c107ddbc-f3a8-4ea6-b6b1-ee1bc7adf049">

总是提示：暂时不支持href="https类型的节点订阅，跳过此节点。
---
<img width="608" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/e349b131-fa53-4ce5-9e74-764bce2a6c9c">

当删除 UA 或者修改其他 UA 后，可以成功订阅一次。下次又会提示：**暂时不支持href="https类型的节点订阅，跳过此节点。**
---
<img width="728" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/c8f45a08-054e-458c-ab27-a366e59deb36">

每次更新都要手动删除 UA 才能更新，有点麻烦。请教大佬怎么解决？谢谢
---

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

4.59

**Comment by neohugz** [comment]
一次都未成功过

**Comment by Anyone20** [comment]
> 一次都未成功过

我这边删除 ua 后，第一次可以成功。第二次就不行了。

**Comment by handsomeji** [comment]
你的訂閱鏈接能直接從瀏覽器打開並下載？

**Comment by Anyone20** [comment]
> 你的訂閱鏈接能直接從瀏覽器打開並下載？

可以打开，不是下载

<img width="782" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/297b54ff-897d-4fdd-b535-3904039351e3">

**Comment by handsomeji** [comment]
確定是標準訂閱格式？命令行輸入以下看看反饋結果。把訂閱URL換成你的。
`curl -skL --retry 3 --connect-timeout 3 --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36' "訂閱URL"`

**Comment by Anyone20** [comment]
> 確定是標準訂閱格式？命令行輸入以下看看反饋結果。把訂閱URL換成你的。 `curl -skL --retry 3 --connect-timeout 3 --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36' "訂閱URL"`

结果如图：
<img width="890" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/2a8e5d12-ed23-4577-b99d-b9e49e23afe0">

每次得到的结果都是这个

**Comment by handsomeji** [comment]
你用返回的數據用base64解碼一下看看唄，一般能返回正常的標準訂閱格式應該是沒問題的。

**Comment by Anyone20** [comment]
> 你用返回的數據用base64解碼一下看看唄，一般能返回正常的標準訂閱格式應該是沒問題的。
解码后结果如图：
<img width="1070" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/99570708/8b360e7a-7d23-4b11-a213-68e474fc684c">

**Comment by Anyone20** [comment]
> 你用返回的數據用base64解碼一下看看唄，一般能返回正常的標準訂閱格式應該是沒問題的。


经测试，[4.76-1](https://github.com/xiaorouji/openwrt-passwall/releases/tag/4.76-1)已经可以正常订阅。
感谢大佬！

**Comment by iamyangyiok** [comment]
> > 你用返回的數據用base64解碼一下看看唄，一般能返回正常的標準訂閱格式應該是沒問題的。
> 
> 经测试，[4.76-1](https://github.com/xiaorouji/openwrt-passwall/releases/tag/4.76-1)已经可以正常订阅。 感谢大佬！

我还是不行 刚全部订阅不了 在4.73上全没问题

**Comment by Cupcc** [comment]
同样的问题，5.3日 还是无法订阅

**Comment by Weiwei1210** [comment]
5.5日也不能订阅
