### ISSUE TITLE
[Bug]: 不能与lede的仓库同时云编译

### ISSUE THREAD

**Issue by herofence** [xiaorouji/openwrt-package#3039]
### 描述您遇到的bug

连续有10多天了，都不能通过github action 同时来编译lede和passwall固件，以前是能正常编译的
用immortalwrt的源码仓库（https://github.com/immortalwrt/immortalwrt）也能正常编译

### 复现此Bug的步骤

1、下载源码
git clone --depth=1 --single-branch https://github.com/xiaorouji/openwrt-passwall.git
git clone --depth=1 --single-branch https://github.com/xiaorouji/openwrt-passwall2 luci-app-passwall2
git clone --depth=1 --single-branch https://github.com/xiaorouji/openwrt-passwall-packages.git
2、配置菜单
CONFIG_PACKAGE_luci-app-passwall=y
3、云编译
make -j$(nproc) || make -j1 V=s

### 您想要实现的目的

能像以前一样正常云编译成功

### 日志信息

Configuring autosamba.
Configuring kmod-amazon-ena.
Configuring kmod-e1000e.
Configuring autocore-x86.
Configuring luci-i18n-upnp-zh-cn.
Configuring luci-i18n-lucky-zh-cn.
Configuring kmod-button-hotplug.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring coreutils-nohup.
Configuring luci-i18n-nlbwmon-zh-cn.
Configuring dnsmasq-full.
 * pkg_hash_check_unresolved: cannot find dependency chinadns-ng for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2socks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2tcp for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency microsocks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall-zh-cn:
 * 	chinadns-ng
 * 	dns2socks
 * 	dns2tcp
 * 	microsocks
 * 	tcping
 * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/runner/work/Common/Common/owrt'
make[1]: *** [package/Makefile:111: /home/runner/work/Common/Common/owrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/runner/work/Common/Common/owrt'
make: *** [/home/runner/work/Common/Common/owrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

### 截图

<img width="987" alt="屏幕截图 2024-03-17 181848" src="https://github.com/xiaorouji/openwrt-passwall/assets/113574064/f26eaa26-477a-4f0b-80c2-219e19cb0161">

### 系统相关信息

lede和passwall都是直接用的源码仓库，最新的版本
lede：https://github.com/coolsnowwolf/lede
passwall:https://github.com/xiaorouji/openwrt-passwall

### 其他信息

我使用的编译菜单：
下载源码：https://github.com/herofence/Common/blob/main/Scripts/Plugins.sh
2、配置菜单：https://github.com/herofence/Common/blob/main/Config/General.txt
3、编译程序：
https://github.com/herofence/Common/blob/main/.github/workflows/X64-Lede.yml
https://github.com/herofence/Common/blob/main/.github/workflows/OWRT-CORE.yml

**Comment by sbwml** [comment]
当你描述的和你任务流真实执行的是一致的话。这个
![image](https://github.com/xiaorouji/openwrt-passwall/assets/16485166/3751e15e-a7d1-4ec8-8f38-bbc13a0b304c)
标签应该就不会被盲目的扣上去

**Comment by kxdn3** [comment]
可以编译成功的

**Comment by lwb1978** [comment]
检查自己的编译脚本和配置文件，我这边云编译正常。

**Comment by nantayo** [comment]
![1](https://github.com/xiaorouji/openwrt-passwall/assets/77558823/863f8fcc-43bc-4065-9043-f57525407068)
云编译初始化环境的时候加 upgrade 偶尔就会导致编译失败……临时用来编译而已，不用升级也无所谓的

**Comment by herofence** [comment]
感谢大家的帮助，是我自己知识储备不足，再次谢谢大家
