### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tuhaibin1973** [xiaorouji/openwrt-package#3040]
### 描述您遇到的bug

passwall 节点设置中，只能选取 trojan-plus,没有trojan-go 选项。

### 复现此Bug的步骤

在节点中选择协议，没有 trojan-go
busybox 也没有 trojan-go

### 您想要实现的目的

希望能够支持 trojan-go 协议

### 日志信息

next..

### 系统相关信息

4.75-10

**Comment by tuhaibin1973** [comment]
> ### 描述您遇到的bug
> passwall 节点设置中，只能选取 trojan-plus,没有trojan-go 选项。
> 
> ### 复现此Bug的步骤
> 在节点中选择协议，没有 trojan-go busybox 也没有 trojan-go
> 
> ### 您想要实现的目的
> 希望能够支持 trojan-go 协议
> 
> ### 日志信息
> next..
> 
> ### 截图
> _No response_
> 
> ### 系统相关信息
> 4.75-10
> 
> ### 其他信息
> _No response_

是不具备这个功能，还是我理解不对？

**Comment by handsomeji** [comment]
trojan-go已經好久無更新，並已remove。請使用Sing-Box或Xray代替。
