### ISSUE TITLE
[Bug]: 更新ChinaDNS-NG版本失败

### ISSUE THREAD

**Issue by binge8** [xiaorouji/openwrt-package#3041]
### 描述您遇到的bug

软路由，大雕源码编译的，passwall版本【 4.75-10 】点更新ChinaDNS-NG提示：客户端文件不适合当前设备。chinadns-ng__/tmp/chinadns-ng_download.DmLidA。现版本【 2023.10.28 】能检测到新版本2024.3.7，点更新就报错。

### 复现此Bug的步骤

能检测到新版本2024.3.7，点更新就报错。

### 您想要实现的目的

强迫症状患者，还喜欢追新，希望正常更新

### 日志信息

客户端文件不适合当前设备。chinadns-ng__/tmp/chinadns-ng_download.DmLidA

### 系统相关信息

软路由，大雕源码编译的，passwall版本【 4.75-10 】

**Comment by neohugz** [comment]
可以手动更新

**Comment by binge8** [comment]
> 可以手动更新

手动怎么搞啊 ，小白请教

**Comment by sjs76** [comment]
> > 可以手动更新
> 
> 手动怎么搞啊 ，小白请教

YouTube搜 悟空的日常 博主，里有视频教程。

**Comment by xyuelin** [comment]
> > > 可以手动更新
> > 
> > 
> > 手动怎么搞啊 ，小白请教
> 
> YouTube搜 悟空的日常 博主，里有视频教程。

欺诈啊，我去看了，没有。

**Comment by binge8** [comment]
> > > 可以手动更新
> > 
> > 
> > 手动怎么搞啊 ，小白请教
> 
> YouTube搜 悟空的日常 博主，里有视频教程。

臭傻逼骗子，我也去找一圈没找到   arm确实可以更新，x86不行

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/3005

有發issue的時間和看所謂的垃圾youtube視頻，還不如找找歷史issue.

**Comment by binge8** [comment]
> #3005
> 
> 有發issue的時間和看所謂的垃圾youtube視頻，還不如找找歷史issue.

改成v2  再rm -rf那个 确实成功了
