### ISSUE TITLE
[Bug]: 为啥这个总是处于禁用状态

### ISSUE THREAD

**Issue by mmeiwenlong** [xiaorouji/openwrt-package#3043]
### 描述您遇到的bug

![QQ截图20240318165245](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/5742d6a3-50e5-4b8a-8d6a-d1f4296d3078)

### 复现此Bug的步骤

![QQ截图20240318165245](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/b551878e-0d74-453d-ad0c-c13d4ad6c635)

### 您想要实现的目的

应该是启用状态吧

### 日志信息

无，没启用sign-box就是这样？

### 系统相关信息

4.75-10

**Comment by handsomeji** [comment]
這個是sing-box這個package自帶的init.d，passwall不需要它。
