### ISSUE TITLE
[Bug]: PW和PW2安装得2选1了

### ISSUE THREAD

**Issue by uingei** [xiaorouji/openwrt-package#3050]
### 描述您遇到的bug

Collected errors:
 * check_data_file_clashes: Package luci-app-passwall wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/www/luci-static/resources/qrcode.min.js
	But that file is already provided by package  * luci-app-passwall2
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * check_data_file_clashes: Package luci-app-passwall wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/www/luci-static/resources/qrcode.min.js
	But that file is already provided by package  * luci-app-passwall2
 * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.

### 复现此Bug的步骤

同时安装PW和PW2

### 您想要实现的目的

两个都装

### 日志信息

Collected errors:
 * check_data_file_clashes: Package luci-app-passwall wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/www/luci-static/resources/qrcode.min.js
	But that file is already provided by package  * luci-app-passwall2
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * check_data_file_clashes: Package luci-app-passwall wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/www/luci-static/resources/qrcode.min.js
	But that file is already provided by package  * luci-app-passwall2
 * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.

### 系统相关信息

Passwall 版本 4.76-1
passwall2 版本 1.28-3

**Comment by hcym** [comment]
好像是

**Comment by handsomeji** [comment]
Try the latest commit.
