### ISSUE TITLE
[Feature Request]: 中文界面无法显示

### ISSUE THREAD

**Issue by luyingwei80** [xiaorouji/openwrt-package#3051]
### 描述你想要的新功能

本插件通过OPENWRT官方MAIN分支编译的固件即便选择界面语言为简体中文依然呈英文显示，不知哪里还需要设置？

### 描述你想要的解决方案

希望能给出解决方案。

**Comment by BGzEroll** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/0079e1df-5e5b-43f5-91ce-0ffa151c546e)
试试

**Comment by luyingwei80** [comment]
这与浏览器缓存没有关系，即便通过无痕浏览模式依然显示英文。
![image](https://github.com/xiaorouji/openwrt-passwall/assets/67801546/486e7622-68a5-4422-827f-1e30a5855108)

**Comment by uingei** [comment]
openwrt-23.05 分支编译的中文正常，master 分支没试过

**Comment by gito10** [comment]
看看`/usr/lib/lua/luci/i18n/`下面的语言文件，表示简中的是`zh-cn`、`zh-Hans`或者别的什么，找到passwall的，是不是和其他的不一致。
还有passwall是自己编译的还是从release下载的，如果是下载的，语言文件是否是下的luci23.05编译版本。

**Comment by luyingwei80** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/67801546/c7e12141-7578-4364-b2b2-c84dffbd80d1)
文件看着没啥问题。另，passwall是直接git clone这里的源码到feeds里直接编译的。我是直接编译openwrt官方的main分支而非23.05稳定版分支，看了恩山论坛上有人说是最新官方的openwrt对简中的定义又有变化，但没给出实际可解决的方案。

> 看`/usr/lib/lua/luci/i18n/`下面的语言文件，表示简中的、`zh-cn`或者`zh-Hans`其他什么，找到passwall的，是不是和其他的不一致。 还有passwall是自己编译的还是从release下载的，如果是下载的，语言文件是否是下面的luci23.05编译版本。

**Comment by kxdn3** [comment]
openwrt-23.05好用吗

**Comment by luyingwei80** [comment]
> openwrt-23.05好用吗

还没尝试编译这个版本，回头试试看

**Comment by lllrrr2** [comment]
这个问题我有遇到过，是浏览器的问题，你开无痕模式打开，看看是不是正常的，基本是浏览器的缓存问题

**Comment by luyingwei80** [comment]
> 这个问题我有遇到过，是浏览器的问题，你开无痕模式打开，看看是不是正常的，基本是浏览器的缓存问题

早先就试过无痕模式，但并无效果。换了浏览器也是如此。

**Comment by lllrrr2** [comment]
刚才openwrt-23.05 分支编译的中文正常

**Comment by luyingwei80** [comment]
> 刚才openwrt-23.05 分支编译的中文正常

嗯，应该是最新6.1.82内核的MAIN分支的缘故。希望能早日更新支持最新MAIN分支。

**Comment by luyingwei80** [comment]
目前用以下方式在openwrt官方main分支编译下能正确显示中文了，方法如下供参考：

1. 将po目录下的zh-cn目录改名为zh_Hans。
2. 编辑passwall.po，在头部添加以下内容：
msgid ""
msgstr ""
"openwrt/luciapplicationspasswall/zh_Hans/>\n"
"Language: zh_Hans\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 5.5-dev\n"

**Comment by xcyll** [comment]
用的架构	：ARMv8
版本：**openwrt** main分支 
主题：Bootstrap
界面汉化正常显示 无异常

**Comment by xcyll** [comment]
主题不兼容？
