### ISSUE TITLE
[Bug]: openwrt23.05 lienol固件保存没有任何显示

### ISSUE THREAD

**Issue by qq1316237299** [xiaorouji/openwrt-package#3058]
### 描述您遇到的bug

openwrt23.05 lienol固件保存没有任何显示 openwrt主题也用了原版主题bootstrap也是没有任何显示。用了ssrP是会有正在保存配置跳出来。

### 复现此Bug的步骤

openwrt23.05 lienol固件保存没有任何显示 openwrt主题也用了原版主题bootstrap也是没有任何显示。用了ssrP是会有正在保存配置跳出来。

### 您想要实现的目的

openwrt23.05 lienol固件保存没有任何显示 openwrt主题也用了原版主题bootstrap也是没有任何显示。用了ssrP是会有正在保存配置跳出来。

### 日志信息

Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 114.114.114.114#53 for domain douyucdn.cn
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 223.5.5.5#53 for domain douyucdn.cn
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 114.114.114.114#53 for domain doh.pub
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 223.5.5.5#53 for domain doh.pub
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 114.114.114.114#53 for domain cdn-ali.content.steamchina.com
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 223.5.5.5#53 for domain cdn-ali.content.steamchina.com
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using nameserver 127.0.0.1#15353 for domain github.global.ssl.fastly.net
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: more servers are defined but not logged
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for test
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for onion
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for localhost
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for local
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for invalid
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for bind
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for bss.pandora.xiaomi.com
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using only locally-known addresses for o2o.api.xiaomi.com
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: using 13 more local addresses
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: read /etc/hosts - 12 names
Sun Mar 24 15:51:00 2024 daemon.info dnsmasq[15385]: read /tmp/hosts/dhcp.cfg01411c - 0 names
Sun Mar 24 15:51:00 2024 cron.err crond[15484]: crond (busybox 1.36.1) started, log level 5

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/b54ea111-7824-4d52-96d8-dcbe6e8a9458)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/4018f670-8173-4199-82fe-2e9a90f04d99)

### 系统相关信息

 4.76-1
edge 122.0.2365.92

**Comment by handsomeji** [comment]
feature.

**Comment by qq1316237299** [comment]
> feature

是正常的对吧大佬
