### ISSUE TITLE
[Bug]: 昨天更新chinadns-ng编译不了

### ISSUE THREAD

**Issue by kxdn3** [xiaorouji/openwrt-package#3061]
### 描述您遇到的bug

hash值都不对，麻烦修复

### 复现此Bug的步骤

无

### 您想要实现的目的

修复

### 日志信息

无

### 系统相关信息

最新

**Comment by kxdn3** [comment]
hash值都不对

**Comment by qingtian110** [comment]
action 更新二进制会有个bug，上游tag发布后，机器人已经检测到新版本，但是实际上二进制文件还没有编译好上传，导致机器人检查文件hash 会变成页面404 的hash 就炸了。要解决这种问题估计只能让机器人在半夜的时候去更新，因为这个时间段二进制文件肯定会存在。

@lwb1978

**Comment by lwb1978** [comment]
> action 更新二进制会有个bug，上游tag发布后，机器人已经检测到新版本，但是实际上二进制文件还没有编译好上传，导致机器人检查文件hash 会变成页面404 的hash 就炸了。要解决这种问题估计只能让机器人在半夜的时候去更新，因为这个时间段二进制文件肯定会存在。
> 
> @lwb1978

大佬已经删除了action中关于自动更新chinadns的相关代码，现在改为纯手动更新。

**Comment by qingtian110** [comment]
> > action 更新二进制会有个bug，上游tag发布后，机器人已经检测到新版本，但是实际上二进制文件还没有编译好上传，导致机器人检查文件hash 会变成页面404 的hash 就炸了。要解决这种问题估计只能让机器人在半夜的时候去更新，因为这个时间段二进制文件肯定会存在。
> > @lwb1978
> 
> 大佬已经删除了action中关于自动更新chinadns的相关代码，现在改为纯手动更新。

哦哦 ，手动的那要靠谱

**Comment by qingtian110** [comment]
@lwb1978 话说能不能把 naiveproxy 和 shadowsocks-rust 也换成二进制的方式？

原因：
naiveproxy：这个东西在本地虚拟机源码编译一次太炸裂了，辣鸡电脑i5 6代 vm虚拟机下，单这个插件的耗时就已经2小时了。。。
shadowsocks-rust：它没法从源码编译给 mips 设备使用了。只能二进制。

**Comment by lwb1978** [comment]
> @lwb1978 话说能不能把 naiveproxy 和 shadowsocks-rust 也换成二进制的方式？
> 
> 原因： naiveproxy：这个东西在本地虚拟机源码编译一次太炸裂了，辣鸡电脑i5 6代 vm虚拟机下，单这个插件的耗时就已经2小时了。。。 shadowsocks-rust：它没法从源码编译给 mips 设备使用了。只能二进制。

你上面两个需求建议直接引用 @sbwml 大佬的仓库就可以迎刃而解。
https://github.com/sbwml/openwrt_helloworld
