### ISSUE TITLE
[Bug]: socks自动切换失败

### ISSUE THREAD

**Issue by binge8** [xiaorouji/openwrt-package#3065]
### 描述您遇到的bug

软路由，lede仓库编译的，和pw都是最新代码，开启socks自动切换，没有选择恢复切换，开启定时更新规则，每次更新完规则就一直切换节点，确定备用的线路都是没问题的，pw手动停用后再启用，就正常了。同样的设置和代码在armv8上却正常

### 复现此Bug的步骤

开启socks自动切换，没有选择恢复切换，开启定时更新规则，每次更新完规则就一直切换节点，确定备用的线路都是没问题的，pw手动停用后再启用，就正常了。

### 您想要实现的目的

希望正常切换，正确识别节点连通性

### 日志信息

无

### 系统相关信息

pw4.76-1

**Comment by Nicepaul** [comment]
确实有这样的问题，我的是X64系统，所以已经不使用socks自动切换了

**Comment by binge8** [comment]
> 确实有这样的问题，我的是X64系统，所以已经不使用socks自动切换了

那还有什么方法自动切换

**Comment by Nicepaul** [comment]
> > 确实有这样的问题，我的是X64系统，所以已经不使用socks自动切换了
> 
> 那还有什么方法自动切换

手动切换

**Comment by binge8** [comment]
> > > 确实有这样的问题，我的是X64系统，所以已经不使用socks自动切换了
> > 
> > 
> > 那还有什么方法自动切换
> 
> 手动切换

再见兄dei

**Comment by lwb1978** [comment]
可以改用xray的负载均衡代替自动切换，具体参考这个：
https://github.com/xiaorouji/openwrt-passwall/issues/3009

**Comment by ghost** [comment]
程式碼bug沒得辯的啦 回報完bug靜等修復吧 XD

**Comment by lwb1978** [comment]
现在xray 和 Haproxy的负载均衡已经比较完善，效果和稳定性也比socks自动切换好，翻看之前issues和discussions大神的对话得知有可能会把socks自动切换取消。

**Comment by binge8** [comment]
测试了两天，发现打开ChinaDNS-NG就会出现这个问题，不开ChinaDNS-NG好像就正常了

**Comment by handsomeji** [comment]
自動切換檢測是把域名傳過去服務端解析的(除非服務端沒有配置DNS上游)，與本機配置的DNS無關。可能導致失敗的原因是無法解析節點的IP。或是curl的問題(可能性不大)
