### ISSUE TITLE
[Feature Request]: 希望增加定时“清空 IPSET”功能或者命令行方式执行“清空 IPSET”

### ISSUE THREAD

**Issue by Nicepaul** [xiaorouji/openwrt-package#3066]
### 描述你想要的新功能

Lean X64 Openwrt 6.1.82，passwall  4.76-1 。因为最近在使用新版Passwall时，不定时发现youtube或google网站打不开，但是其他网站都是没问题。发现这时候只要点击“清空 IPSET”，youtube或google网站就可以正常打开了。所以能不能增加个增加定时“清空 IPSET”功能，或者给出如何在命令行方式下执行“清空 IPSET”也行，在crontab里定时运行该命令也是一样效果。

### 描述你想要的解决方案

Lean X64 Openwrt 6.1.82，passwall  4.76-1 。因为最近在使用新版Passwall时，不定时发现youtube或google网站打不开，但是其他网站都是没问题。发现这时候只要点击“清空 IPSET”，youtube或google网站就可以正常打开了。所以能不能增加个增加定时“清空 IPSET”功能，或者给出如何在命令行方式下执行“清空 IPSET”也行，在crontab里定时运行该命令也是一样效果。

**Comment by ghost** [comment]
你所遇到的現象跟這個沒什麼關係
應該檢查的設定其實是網頁介面中有關於 passwall DNS的設定，看看是不是爲 dns2socks 即dns通過遠程代理節點解析，并且中國列表以外選用的是遠程DNS爲默認
當然，如果你使用的代理方案爲hysteria的話，你所遇到的情況也可能跟最近程式更新有關，即通過tproxy代理流量時不穩定的問題，其他人也有所回報

**Comment by ghost** [comment]
當然，如果編譯openwrt firmware的時候，iptables和ip6tables組件沒有選擇完整也會有這個情形

**Comment by Nicepaul** [comment]
> 你所遇到的現象跟這個沒什麼關係 應該檢查的設定其實是網頁介面中有關於 passwall DNS的設定，看看是不是爲 dns2socks 即dns通過遠程代理節點解析，并且中國列表以外選用的是遠程DNS爲默認 當然，如果你使用的代理方案爲hysteria的話，你所遇到的情況也可能跟最近程式更新有關，即通過tproxy代理流量時不穩定的問題，其他人也有所回報

![WX20240328-071846@2x](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/5d556995-2ca7-436d-9105-78cc56ce8f71)

**Comment by Nicepaul** [comment]
> 當然，如果編譯openwrt firmware的時候，iptables和ip6tables組件沒有選擇完整也會有這個情形

![WX20240328-071912@2x](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/8031e83a-55b1-431b-a353-754263bf0d9e)

**Comment by Nicepaul** [comment]
> 當然，如果編譯openwrt firmware的時候，iptables和ip6tables組件沒有選擇完整也會有這個情形

![Uploading WX20240328-072239@2x.png…]()

**Comment by Nicepaul** [comment]
> 當然，如果編譯openwrt firmware的時候，iptables和ip6tables組件沒有選擇完整也會有這個情形

![WX20240328-072239@2x](https://github.com/xiaorouji/openwrt-passwall/assets/32355166/1c161b89-fd01-4066-a303-b38a62b798a7)

**Comment by Michaol** [comment]
我也会出现这个情况，最明显是YouTube，甚至其他都能打开，唯独卡YouTube，清除ipset马上恢复正常。查看log看不到任何问题，很奇怪。

**Comment by greathch** [comment]
我也会这样，老版本没问题

**Comment by Nicepaul** [comment]
close

**Comment by ghost** [comment]
使用xray解析dns時，如果路由自身代理爲無，則dns爲直連！！！！！！

使用xray解析dns時，如果路由自身代理爲無，則dns爲直連！！！！！！

使用xray解析dns時，如果路由自身代理爲無，則dns爲直連！！！！！！

切勿在不代理路由器本機的情形下使用本模式！！！！！！！！

**Comment by ghost** [comment]
使用xray解析dns時，如果路由自身代理爲無，則dns爲直接連接的！！！！！！

使用xray解析dns時，如果路由自身代理爲無，則dns爲直接連接的！！！！！！

使用xray解析dns時，如果路由自身代理爲無，則dns爲直接連接的！！！！！！

切勿在不代理路由器本機的情形下使用本模式！！！！！！！！
