### ISSUE TITLE
[Feature Request]: 希望勾选使用全局配置后，能让访问控制中的设备使用的列表也与全局保持一致

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3069]
### 描述你想要的新功能

访问控制中勾选**使用全局配置**，如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/9e9bea8a-5fed-40ce-9e4f-886ae8809fd0)

模式中取消勾选**使用 直连列表**、**使用 代理列表**、**使用 屏蔽列表**，如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/3427d198-6296-4388-b099-bdf424ba1136)

访问控制中的设备仍然会使用**直连**、**代理**以及**屏蔽**这三个列表，如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/fe58a66d-5b1a-4e53-8f34-65c255ad2b79)

### 描述你想要的解决方案

希望能让访问控制中的设备使用的列表也与全局一致

**Comment by handsomeji** [comment]
確認是代碼遺漏了。下個版本將修正。
