### ISSUE TITLE
[Bug]: 在 XDR6088 上使用时会导致路由器宕机重启

### ISSUE THREAD

**Issue by Max-Qiu** [xiaorouji/openwrt-package#3070]
### 描述您遇到的bug

版本：openwrt官方版2023.05.3+passwall4.76

连续请求任意网页 或者 使用Chrome批量打开（无痕模式）收藏夹中的网址

表现出网页打开慢，再过几秒钟openwrt管理端也打不开，再过几秒钟路由器宕机并自动从其

### 复现此Bug的步骤

1. 使用openwrt官方版2023.05.3+passwall4.76编译 xdr6088 固件并刷机
2. 在默认未启用passwall时，无痕模式批量打开网页，无需代理的网页均可正常打开
3. 开启passwall，选择节点并使用中国列表以外模式，其他配置保持默认，再次无痕模式批量打开网页，出现网页打开慢或打不开，并且路由器宕机
4. 修改本机的dns地址为114.114.114.114（虽然这个操作并不符合FAQ中的“客户端DNS和默认网关必须指向本路由器”），再次无痕模式批量打开网页，所有网页均可正常打开，连Google也能打开
5. 关闭xdr6088中的passwall，在群晖虚拟机中安装openwrt官方版2023.05.3+passwall4.76并配置好，修改本地网关和DNS为旁路网关，再次无痕模式批量打开网页，所有网页均正常

注：
1. 在xdr6088中使用openwrt官方版2023.05.2+passwall4.72时，虽然偶尔遇到网页打开慢的问题，但是没遇到过宕机的问题
2. 初步怀疑是xdr6088性能太弱了

### 您想要实现的目的

可以在xdr6088中正常使用新版本

### 日志信息

暂时不知道如何采集日志，因为路由器宕机重启后，看到的启动日志都清空了，连内核日志都重新开始打印

### 系统相关信息

openwrt官方版2023.05.3+passwall4.76

**Comment by xh0823** [comment]
是内存问题开ChinaDNS-NG就可以解决，我现在稳定2天都正常运行

**Comment by kxdn3** [comment]
OpenWrt版本真新

**Comment by jackiezhang29** [comment]
> ChinaDNS-N

兄弟，请教下，我用smartdns，dns里，udp直接走127.0.0.1:5335，没有开chinadns-ng，我单节点使用没有问题，但一旦使用分流，软路由我设置多少G内存会全部占满，临时空间4G空间也会写满，重启passwall服务，一切正常，但没过多久又占满内存了，是不是因为我没开chinadns-ng？

**Comment by wtfr-dot** [comment]
用的redirect模式吗？用这种模式内存占用很大，用tproxy模式

**Comment by jackiezhang29** [comment]
> 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式

但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满

**Comment by wtfr-dot** [comment]
> > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> 
> 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满

我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点

**Comment by jackiezhang29** [comment]
> > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > 
> > 
> > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> 
> 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点

我是分流出现问题，单个节点没有问题，这也和tproxy有关？我可以尝试下

**Comment by jackiezhang29** [comment]
> > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > 
> > 
> > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> 
> 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点

tproxy模式很多外网都上不去

**Comment by wtfr-dot** [comment]
> > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > 
> > > 
> > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > 
> > 
> > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> 
> tproxy模式很多外网都上不去

跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug

**Comment by jackiezhang29** [comment]
> > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > 
> > > > 
> > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > 
> > > 
> > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > 
> > 
> > tproxy模式很多外网都上不去
> 
> 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug

我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题

**Comment by wtfr-dot** [comment]
> > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > 
> > > > > 
> > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > 
> > > > 
> > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > 
> > > 
> > > tproxy模式很多外网都上不去
> > 
> > 
> > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> 
> 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题

不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何

**Comment by wtfr-dot** [comment]
> smartdns端会重复调用上游服务器 ？什么意思 @wtfr-dot

在smartdns里会一般会启用第二服务器，第二服务器里放了一些墙外dns解析器成员，pass wall如果用udp127.0.0.1这种方式，smartdns会把它直接当作一个服务器加载，但是smardns在解析墙外dns时本身就调用的第二服务器内的成员，结果在调用127.0.0.1时，它本身也是指向的第二服务器的，然后它会再调用一次里面的dns解析器，smartdns的log里可以看得到这个过程

**Comment by jackiezhang29** [comment]
> > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > 
> > > > > > 
> > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > 
> > > > > 
> > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > 
> > > > 
> > > > tproxy模式很多外网都上不去
> > > 
> > > 
> > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > 
> > 
> > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> 
> 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何

但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题

**Comment by wtfr-dot** [comment]
> > > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > > 
> > > > > > > 
> > > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > > 
> > > > > > 
> > > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > > 
> > > > > 
> > > > > tproxy模式很多外网都上不去
> > > > 
> > > > 
> > > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > > 
> > > 
> > > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> > 
> > 
> > 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何
> 
> 但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题

你用tproxy是不是内存问题解决了？因为你用的第三方固件，他们通常会做一些优化，但兼容性好不好就不好说了，另外如果你装的插件很多的话也有可能会出现问题，我用的官方代码自己编译的，只用自己需要的，用tproy方式再也没有这个问题，但是只要改为redirect模式就会出现爆内存的问题，特别是打开直连模式

**Comment by jackiezhang29** [comment]
> > > > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > > > 
> > > > > > > 
> > > > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > > > 
> > > > > > 
> > > > > > tproxy模式很多外网都上不去
> > > > > 
> > > > > 
> > > > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > > > 
> > > > 
> > > > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> > > 
> > > 
> > > 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何
> > 
> > 
> > 但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题
> 
> 你用tproxy是不是内存问题解决了？因为你用的第三方固件，他们通常会做一些优化，但兼容性好不好就不好说了，另外如果你装的插件很多的话也有可能会出现问题，我用的官方代码自己编译的，只用自己需要的，用tproy方式再也没有这个问题，但是只要改为redirect模式就会出现爆内存的问题，特别是打开直连模式

tproxy连上网都不正常，很多网站要么上不去，要么速度很慢

**Comment by wtfr-dot** [comment]
> > > > > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > > > > 
> > > > > > > 
> > > > > > > tproxy模式很多外网都上不去
> > > > > > 
> > > > > > 
> > > > > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > > > > 
> > > > > 
> > > > > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> > > > 
> > > > 
> > > > 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何
> > > 
> > > 
> > > 但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题
> > 
> > 
> > 你用tproxy是不是内存问题解决了？因为你用的第三方固件，他们通常会做一些优化，但兼容性好不好就不好说了，另外如果你装的插件很多的话也有可能会出现问题，我用的官方代码自己编译的，只用自己需要的，用tproy方式再也没有这个问题，但是只要改为redirect模式就会出现爆内存的问题，特别是打开直连模式
> 
> tproxy连上网都不正常，很多网站要么上不去，要么速度很慢

清空ipset没有？必须清空ipset，另外可以恢复默认设置重新设置一下

**Comment by jackiezhang29** [comment]
> > > > > > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > > > > > 
> > > > > > > > 
> > > > > > > > tproxy模式很多外网都上不去
> > > > > > > 
> > > > > > > 
> > > > > > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > > > > > 
> > > > > > 
> > > > > > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> > > > > 
> > > > > 
> > > > > 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何
> > > > 
> > > > 
> > > > 但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题
> > > 
> > > 
> > > 你用tproxy是不是内存问题解决了？因为你用的第三方固件，他们通常会做一些优化，但兼容性好不好就不好说了，另外如果你装的插件很多的话也有可能会出现问题，我用的官方代码自己编译的，只用自己需要的，用tproy方式再也没有这个问题，但是只要改为redirect模式就会出现爆内存的问题，特别是打开直连模式
> > 
> > 
> > tproxy连上网都不正常，很多网站要么上不去，要么速度很慢
> 
> 清空ipset没有？必须清空ipset，另外可以恢复默认设置重新设置一下

和tproxy无关

**Comment by wtfr-dot** [comment]
> > > > > > > > > > > > 用的redirect模式吗？用这种模式内存占用很大，用tproxy模式
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 但不至于我软路由设置了8G内存会被用尽，临时空间3.8G会被写满
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我也是软路由，分配的1g内存，在很早以前我用redirect模式发现连接数暴涨到上限，内存也爆满，试过调到4g勉强能支撑，后来就再也没用这个模式了，改用tproxy模式后再也没出现爆内存的问题，1g内存长期稳定在占用百分之四十几，你如果现在用redirect模式爆内存极大可能是这个原因，特别是用dnsmasq，用smartdns好点
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > tproxy模式很多外网都上不去
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 跟tproxy模式无关，应该跟你设置有关，你的passwall是自编译的还是下的ipk？如果你要配合smartdns使用，要自己编译luci-smartdns-dev分支，main分支没有对smartdns优化，而且udp127.0.0.1这种方法很早就不适用了，即使之前能用在smartdns端也会有重复调用上游服务器的bug
> > > > > > > 
> > > > > > > 
> > > > > > > 我是通过imm固件编译器网站，把所需插件输入后，自行编译，然后下载写入esxi的，你的意思是smartdns对passwall的支持并不好？我也用过mosdns，也会出现内存写满的问题
> > > > > > 
> > > > > > 
> > > > > > 不是smartdns对passwall支持不好，是smartdns没有针对任何其它插件进行特别优化，其它插件都是通过附加文件的方式融入smartdns，目前我知道的只有passwall有专门针对smartdns的编译分支，只是一直是dev阶段，没有正式ipk发布，另外我没有用过第三方固件，不知道兼容性如何
> > > > > 
> > > > > 
> > > > > 但我通过单节点使用，也是用smartdns，没有任何问题，所以我觉得不是这个问题
> > > > 
> > > > 
> > > > 你用tproxy是不是内存问题解决了？因为你用的第三方固件，他们通常会做一些优化，但兼容性好不好就不好说了，另外如果你装的插件很多的话也有可能会出现问题，我用的官方代码自己编译的，只用自己需要的，用tproy方式再也没有这个问题，但是只要改为redirect模式就会出现爆内存的问题，特别是打开直连模式
> > > 
> > > 
> > > tproxy连上网都不正常，很多网站要么上不去，要么速度很慢
> > 
> > 
> > 清空ipset没有？必须清空ipset，另外可以恢复默认设置重新设置一下
> 
> 和tproxy无关

每人用的固件和环境不同，我这里只是提供一个思路，反正在我这里爆内存100%与redirect模式有关系

**Comment by xcyll** [comment]
``` 
smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build: 1.2024.02.08-0828 (Release43-141-g9ee27e7))
 ICMP ping is disabled, no ipv6 icmp check feature
 IPV6 is not ready or speed check is disabled, disable IPV6 features
add server 1.1.1.1:443, type: https
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 58970, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 28, id: 58970, query-num: 1
 reply alive.github.com qtype: 28, rcode: 0, reply: 1
 result: alive.github.com, client: 127.0.0.1, qtype: 28, id: 58970, group: default, time: 0ms
 force qtype 28 soa
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 58326, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 65, id: 58326, query-num: 1
 reply alive.github.com qtype: 65, rcode: 0, reply: 1
 result: alive.github.com, client: 127.0.0.1, qtype: 65, id: 58326, group: default, time: 0ms
 force qtype 65 soa
 recv query packet from 127.0.0.1, len = 46, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 46, id = 10598, tc = 0, rd = 1, ra = 0, rcode = 0
 query ccp-lh.googleusercontent.com from 127.0.0.1, qtype: 28, id: 10598, query-num: 1
 reply ccp-lh.googleusercontent.com qtype: 28, rcode: 0, reply: 1
 result: ccp-lh.googleusercontent.com, client: 127.0.0.1, qtype: 28, id: 10598, group: default, time: 0ms
 force qtype 28 soa
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 17035, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 1, id: 17035, query-num: 1
 send query to server 1.1.1.1:443

**Comment by xcyll** [comment]
> > smartdns端会重复调用上游服务器 ？什么意思 @wtfr-dot
> 
> 在smartdns里会一般会启用第二服务器，第二服务器里放了一些墙外dns解析器成员，pass wall如果用udp127.0.0.1这种方式，smartdns会把它直接当作一个服务器加载，但是smardns在解析墙外dns时本身就调用的第二服务器内的成员，结果在调用127.0.0.1时，它本身也是指向的第二服务器的，然后它会再调用一次里面的dns解析器，smartdns的log里可以看得到这个过程

用的不是dev分支版
单独上传了smartdns插件测试了 看日志好像没啥问题啊
【smartdns仅仅作为为6053端口的DNS服务器，smartdns未启用内部黑白名单功能】pw中远程DNS UDP---127.0.0.1:6053
smardns没设置转发👇↓
![2024-03-28 232928](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/260c878a-1688-4422-a8f4-d61fe3d60e57)

**Comment by xcyll** [comment]
**log**
 ``` 
smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build: 1.2024.02.08-0828 (Release43-141-g9ee27e7))
 ICMP ping is disabled, no ipv6 icmp check feature
 IPV6 is not ready or speed check is disabled, disable IPV6 features
add server 1.1.1.1:443, type: https
-------
【smartdns启动后 成功加载了添加的1.1.1.1dns 但没发现127.0.0.1:6053加载的情况】
-------
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 58970, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 28, id: 58970, query-num: 1
 reply alive.github.com qtype: 28, rcode: 0, reply: 1
 result: alive.github.com, client: 127.0.0.1, qtype: 28, id: 58970, group: default, time: 0ms
 force qtype 28 soa
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 58326, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 65, id: 58326, query-num: 1
 reply alive.github.com qtype: 65, rcode: 0, reply: 1
 result: alive.github.com, client: 127.0.0.1, qtype: 65, id: 58326, group: default, time: 0ms
 force qtype 65 soa
 recv query packet from 127.0.0.1, len = 46, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 46, id = 10598, tc = 0, rd = 1, ra = 0, rcode = 0
 query ccp-lh.googleusercontent.com from 127.0.0.1, qtype: 28, id: 10598, query-num: 1
 reply ccp-lh.googleusercontent.com qtype: 28, rcode: 0, reply: 1
 result: ccp-lh.googleusercontent.com, client: 127.0.0.1, qtype: 28, id: 10598, group: default, time: 0ms
 force qtype 28 soa
 recv query packet from 127.0.0.1, len = 34, type = 0
 request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 34, id = 17035, tc = 0, rd = 1, ra = 0, rcode = 0
 query alive.github.com from 127.0.0.1, qtype: 1, id: 17035, query-num: 1
 send query to server 1.1.1.1:443

**Comment by Max-Qiu** [comment]
使用htop查看CPU和内存，刚看到dnsmasq吃CPU和内存，然后ssh就卡死了，再然后路由器宕机重启

![m](https://github.com/xiaorouji/openwrt-passwall/assets/30647194/245e768e-8750-48a6-8638-9375b2f6620e)

**Comment by Max-Qiu** [comment]
> 是内存问题开ChinaDNS-NG就可以解决，我现在稳定2天都正常运行

确实，开了 `ChinaDNS-NG` 就好了

另外，我还发现，开了之后内存占用反而变少了

关闭状态：157M左右
开启状态：100M左右

**Comment by handsomeji** [comment]
猜測是Dnsmasq處理規則的性能問題。最新代碼做了一些Dnsmasq的優化調整，但仍然建議使用`ChinaDNS-NG`。

**Comment by Nicepaul** [comment]
> ChinaDNS-NG

测试了一下，用ChinaDNS-NG发现有DNS泄露问题，用Dnsmasq没有泄露

**Comment by Max-Qiu** [comment]
> 猜測是Dnsmasq處理規則的性能問題。最新代碼做了一些Dnsmasq的優化調整，但仍然建議使用`ChinaDNS-NG`。

感谢，已测试 4.76-2 版本，不开启 `ChinaDNS-NG` 已可以正常使用

**Comment by Max-Qiu** [comment]
> > ChinaDNS-NG
> 
> 测试了一下，用ChinaDNS-NG发现有DNS泄露问题，用Dnsmasq没有泄露

和 `ChinaDNS-NG` 没关系，你看看是不是用的智能DNS或者直连DNS，这两种都会泄露，我测试了远程DNS，没发现泄露

**Comment by BGzEroll** [comment]
> > ChinaDNS-NG
> 
> 测试了一下，用ChinaDNS-NG发现有DNS泄露问题，用Dnsmasq没有泄露

你所谓的dns泄漏就是chinadns-ng正常运作。。。
另外这所谓的dns泄漏并不需要理会。。。也不知道谁整出的这说法。。。

**Comment by Nicepaul** [comment]
> > > ChinaDNS-NG
> > 
> > 
> > 测试了一下，用ChinaDNS-NG发现有DNS泄露问题，用Dnsmasq没有泄露
> 
> 和 `ChinaDNS-NG` 没关系，你看看是不是用的智能DNS或者直连DNS，这两种都会泄露，我测试了远程DNS，没发现泄露

远程DNS,用https://ipleak.net/    测试的
