### ISSUE TITLE
[Bug]: 不定时发现youtube或google网站打不开，但是其他网站都是没问题

### ISSUE THREAD

**Issue by Nicepaul** [xiaorouji/openwrt-package#3072]
### 描述您遇到的bug

Lean X64 Openwrt 6.1.82，passwall 4.76-1 。因为最近在使用新版Passwall时，不定时发现youtube或google网站打不开，但是其他网站都是没问题。发现这时候只要点击“清空 IPSET”，youtube或google网站就可以正常打开了。老版本没有问题，也就最新编译的新版本会有这个问题，大概这半个月左右的事。

### 复现此Bug的步骤

不定时出现

### 您想要实现的目的

希望能正常访问youtube或google。可以增加个增加定时“清空 IPSET”功能，或者给出如何在命令行方式下执行“清空 IPSET”也行，在crontab里定时运行该命令也是一样效果。

### 日志信息

无日志报错

### 系统相关信息

Lean X64 Openwrt 6.1.82，Passwall 4.76-1 ，Chrome Version 123.0.6312.86 (Official Build) (x86_64)

**Comment by leungxt** [comment]
我也有这个问题，所以又切换回4.73-3，一切都好了

**Comment by SilasQin** [comment]
实际上是dns解析的问题，不过你要实现清除ipset这个功能的话，看看iptable.sh那个脚本就知道了

**Comment by mirthlesslk** [comment]
用lede出现少一点，用imm出现多一点，就是设置完passwall参数然后就是打不开，ipset清空一下有时可以有时不行

**Comment by BGzEroll** [comment]
试试把**使用 GFW列表**取消勾选，逻辑改了后勾选貌似会同时使用chnroute和gfwlist表（在至少4-71之前我在iptables/nftables里是不会看到匹配到gfwlist的流量发往**PSW_RULE**的），也就是说**大陆白名单模式**与**gfwlist模式**共存，在我这会经常造成www.gstatic.com等网站打不开，出现google系网站慢、连接超时、F12一片红等奇奇怪怪的问题，一取消勾选**使用 GFW列表**后就好了😂

环境：imm23.05，nftables，开启ipv6透明代理

**4.1,17:57更新：我上述的应该与此[issues](https://github.com/xiaorouji/openwrt-passwall/issues/3080)相关，现已修复**

**Comment by leungxt** [comment]
> 试试把**使用 GFW列表**取消勾选，逻辑改了后勾选貌似会同时使用chnroute和gfwlist表（在至少4-71之前我在iptables/nftables里是不会看到匹配到gfwlist的流量发往**PSW_RULE**的），也就是说**代理大陆外地址**与**gfwlist模式**共存，在我这会经常造成www.gstatic.com等网站打不开，出现google系网站慢、连接超时、F12一片红等奇奇怪怪的问题，一取消勾选**使用 GFW列表**后就好了😂

我取消了还是会有问题，一开始是OK的，过一会还是会出现楼主说的问题，后来切回旧版本4.73-3才彻底好了

**Comment by BGzEroll** [comment]
> > 试试把**使用 GFW列表**取消勾选，逻辑改了后勾选貌似会同时使用chnroute和gfwlist表（在至少4-71之前我在iptables/nftables里是不会看到匹配到gfwlist的流量发往**PSW_RULE**的），也就是说**代理大陆外地址**与**gfwlist模式**共存，在我这会经常造成www.gstatic.com等网站打不开，出现google系网站慢、连接超时、F12一片红等奇奇怪怪的问题，一取消勾选**使用 GFW列表**后就好了😂
> 
> 我取消了还是会有问题，一开始是OK的，过一会还是会出现楼主说的问题，后来切回旧版本4.73-3才彻底好了

取消后清除浏览器缓存和dns缓存以及清空ipset试试

**Comment by kxdn3** [comment]
同样的问题

**Comment by uingei** [comment]
最近几个版本没遇到过问题，难道模式不一样？用的中国列表外

**Comment by Nicepaul** [comment]
> 实际上是dns解析的问题，不过你要实现清除ipset这个功能的话，看看iptable.sh那个脚本就知道了

好的，我试试

**Comment by SilasQin** [comment]
> 我也有这个问题，所以又切换回4.73-3，一切都好了

比较好奇你们怎么切版本的，我有个N1盒子，好像切不了版本，切了就装不上，只能重刷固件

**Comment by leungxt** [comment]
> > 我也有这个问题，所以又切换回4.73-3，一切都好了
> 
> 比较好奇你们怎么切版本的，我有个N1盒子，好像切不了版本，切了就装不上，只能重刷固件

https://github.com/xiaorouji/openwrt-passwall/tags 到这里下载相应的ipk文件，上传到openwrt里安装即可

**Comment by chazikai24** [comment]
gfw模式最近突然发现telegram连不上了，gfwlist里倒是有telegram的规则。
大陆白名单倒是能用。

**Comment by handsomeji** [comment]
telegram用的是IP，不是域名。
默認的代理列表已經加入了，請檢查是否沒有勾選使用

**Comment by kxdn3** [comment]
6.6内核今天又遇到了，过几小时就打不开土鳖，谷歌正常， 5.15内核正常

**Comment by handsomeji** [comment]
是否使用了Sing-Box DNS ？

**Comment by Nicepaul** [comment]
> 是否使用了Sing-Box DNS ？

没有。我这几天发现把TCP代理方式设置为REDIRECT就一切正常，如果用TPROXY就会有奇奇怪怪的问题。

**Comment by 363843342** [comment]
还有其他解决方案吗？

**Comment by taxtigerno1** [comment]
我现在发觉用了passwall后用网页打开YouTube和gmail都没有问题，但是使用YouTube和gmail的app却一直连不上网？请问怎么回事

**Comment by R8KwEwN2hvrhY** [comment]
> 我现在发觉用了passwall后用网页打开YouTube和gmail都没有问题，但是使用YouTube和gmail的app却一直连不上网？请问怎么回事

最后一条规则用代理就可以了，上面匹配不到规则？
