### ISSUE TITLE
[Bug]: Chinadns-ng HASH MD5错误

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#3073]
### 描述您遇到的bug

touch /home/builder/lede_x86/staging_dir/target-x86_64_musl/root-x86/stamp/.resolveip_installed
echo "resolveip" >> /home/builder/lede_x86/staging_dir/target-x86_64_musl/pkginfo/resolveip.default.install
make[3]: Leaving directory '/home/builder/lede_x86/package/network/utils/resolveip'
time: package/network/utils/resolveip/compile#0.10#0.05#0.14
make[3]: Entering directory '/home/builder/lede_x86/package/utils/lua'
make[3]: Leaving directory '/home/builder/lede_x86/package/utils/lua'
time: package/utils/lua/host-compile#0.12#0.06#0.16
make[3]: Entering directory '/home/builder/lede_x86/feeds/passwall/chinadns-ng'
mkdir -p /home/builder/lede_x86/dl
SHELL= flock /home/builder/lede_x86/tmp/.chinadns-ng@x86_64-linux-musl@x86_64@fast+lto.flock -c '       /home/builder/lede_x86/scripts/download.pl "/home/builder/lede_x86/dl" "chinadns-ng@x86_64-linux-musl@x86_64@fast+lto" "8adf68d15068a3a27588772deb19be0a9804077a075aa8dad9dafa12a154c529" "" "https://github.com/zfl9/chinadns-ng/releases/download/2024.03.27"    '
Hash of the local file chinadns-ng@x86_64-linux-musl@x86_64@fast+lto does not match (file: f2cb388d150b836228dc114d25867fc649fdd56a6ff04d35c1ef6df5025f0888, requested: 8adf68d15068a3a27588772deb19be0a9804077a075aa8dad9dafa12a154c529) - deleting download.
make[3]: *** [Makefile:63: /home/builder/lede_x86/dl/chinadns-ng@x86_64-linux-musl@x86_64@fast+lto] Error 2
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/chinadns-ng'
time: package/feeds/passwall/chinadns-ng/compile#0.09#0.05#0.12
    ERROR: package/feeds/passwall/chinadns-ng failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/chinadns-ng/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2
builder@Build-Server:/home/builder/lede_x86$

### 复现此Bug的步骤

lean编译报错

### 您想要实现的目的

fix it

### 日志信息

touch /home/builder/lede_x86/staging_dir/target-x86_64_musl/root-x86/stamp/.resolveip_installed
echo "resolveip" >> /home/builder/lede_x86/staging_dir/target-x86_64_musl/pkginfo/resolveip.default.install
make[3]: Leaving directory '/home/builder/lede_x86/package/network/utils/resolveip'
time: package/network/utils/resolveip/compile#0.10#0.05#0.14
make[3]: Entering directory '/home/builder/lede_x86/package/utils/lua'
make[3]: Leaving directory '/home/builder/lede_x86/package/utils/lua'
time: package/utils/lua/host-compile#0.12#0.06#0.16
make[3]: Entering directory '/home/builder/lede_x86/feeds/passwall/chinadns-ng'
mkdir -p /home/builder/lede_x86/dl
SHELL= flock /home/builder/lede_x86/tmp/.chinadns-ng@x86_64-linux-musl@x86_64@fast+lto.flock -c '       /home/builder/lede_x86/scripts/download.pl "/home/builder/lede_x86/dl" "chinadns-ng@x86_64-linux-musl@x86_64@fast+lto" "8adf68d15068a3a27588772deb19be0a9804077a075aa8dad9dafa12a154c529" "" "https://github.com/zfl9/chinadns-ng/releases/download/2024.03.27"    '
Hash of the local file chinadns-ng@x86_64-linux-musl@x86_64@fast+lto does not match (file: f2cb388d150b836228dc114d25867fc649fdd56a6ff04d35c1ef6df5025f0888, requested: 8adf68d15068a3a27588772deb19be0a9804077a075aa8dad9dafa12a154c529) - deleting download.
make[3]: *** [Makefile:63: /home/builder/lede_x86/dl/chinadns-ng@x86_64-linux-musl@x86_64@fast+lto] Error 2
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/chinadns-ng'
time: package/feeds/passwall/chinadns-ng/compile#0.09#0.05#0.12
    ERROR: package/feeds/passwall/chinadns-ng failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/chinadns-ng/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2
builder@Build-Server:/home/builder/lede_x86$

### 系统相关信息

最新版本

**Comment by wtfr-dot** [comment]
把本地dl目录下已经下载下来的删掉重新编译就可以了

**Comment by lwb1978** [comment]
因为chinadns-ng官方已不再提供makefile方式编译，所以编译固件时只能采用下载对应的二进制文件方式。本地编译时对下载回来的文件会有缓存，所以每次chinadns-ng更新后开启新编译前需要先删除chinadns-ng已下载文件，否则就会因为文件是旧的而sha256是新的导致校验不通过编译失败。

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall-packages/commit/3d7f5d1013e3758d43c3e1132884a13a062ba700
