### ISSUE TITLE
[Bug]: 还是无法订阅 hysteria2 链接

### ISSUE THREAD

**Issue by tanst** [xiaorouji/openwrt-package#3074]
### 描述您遇到的bug

已经编译了最新版
https://github.com/xiaorouji/openwrt-passwall/commit/710ab2bed0bc0d1a421673b110c0e291d761d25c

### 复现此Bug的步骤

#3067

### 您想要实现的目的

能支持解析这种混合的订阅链接
hysteria2://
vless://

### 日志信息

最新日志：
丢弃节点: US-SJC, 找不到可使用二进制

### 系统相关信息

Passwall 版本	【 4.76-2 】

### 其他信息
是不是因为我的 hy2 是用 sing-box 的缘故？我没有编译单独的 hy2

**Comment by handsomeji** [comment]
修改hysteria訂閱類型為sb保存后重新訂閱

**Comment by tanst** [comment]
> 修改hysteria訂閱類型為sb保存后重新訂閱

因为默认就是有且只有一个sb，就没点保存，希望可以有个默认值。
手动保存一下可以了。

**Comment by handsomeji** [comment]
默認值就是原版，但是你沒有編譯，界面上沒有同步。
