### ISSUE TITLE
[Bug]: 添加hysteria2节点中 QUIC 流接收窗口 和 QUIC 连接接收窗口 的定义颠倒了

### ISSUE THREAD

**Issue by Weiitit** [xiaorouji/openwrt-package#3076]
### 描述您遇到的bug

添加hysteria2节点中 QUIC 流接收窗口 和 QUIC 连接接收窗口 的定义颠倒了。

在hysteria2.lua中颠倒了：
o = s:option(Value, option_name("_**recv_window_conn**_"), translate("QUIC stream receive window"))    //QUIC 流接收窗
o.rewrite_option = o.option

o = s:option(Value, option_name("_**recv_window**_"), translate("QUIC connection receive window"))    //QUIC 连接接收窗口
o.rewrite_option = o.option

正确应该是
o = s:option(Value, option_name("recv_window"), translate("QUIC stream receive window"))    //QUIC 流接收窗
o.rewrite_option = o.option

o = s:option(Value, option_name("recv_window_conn"), translate("QUIC connection receive window"))    //QUIC 连接接收窗口
o.rewrite_option = o.option

问题是从Youtube一个视频中看到的，可以从[41:11](https://www.youtube.com/watch?v=Ml6idsXZhZg&list=WL&index=11&t=2471s)看一下

### 复现此Bug的步骤

手动添加hysteria2节点

### 您想要实现的目的

修复hysteria2.lua文件

### 日志信息

略

### 系统相关信息

这问题应该从支持hysteria2开始就存在

**Comment by Weiitit** [comment]
https://github.com/xiaorouji/openwrt-passwall/pull/3077
这样修改是解决了问题，但输入框 QUIC connection receive window //QUIC 连接接收窗口 会在 QUIC stream receive window //QUIC 流接收窗 上，不符合 Hysteria2 解释 流控制接收窗口大小 的顺序，有点别扭。最好还是 QUIC stream receive window //QUIC 流接收窗 在上好理解。
![123](https://github.com/xiaorouji/openwrt-passwall/assets/147345563/0cfc815c-8431-4d86-8457-8c9f28909b3e)

**Comment by lwb1978** [comment]
> #3077 这样修改是解决了问题，但输入框 QUIC connection receive window //QUIC 连接接收窗口 会在 QUIC stream receive window //QUIC 流接收窗 上，不符合 Hysteria2 解释 流控制接收窗口大小 的顺序，有点别扭。最好还是 QUIC stream receive window //QUIC 流接收窗 在上好理解。 ![123](https://private-user-images.githubusercontent.com/147345563/318287936-0cfc815c-8431-4d86-8457-8c9f28909b3e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDgyMjksIm5iZiI6MTcxMjY0NzkyOSwicGF0aCI6Ii8xNDczNDU1NjMvMzE4Mjg3OTM2LTBjZmM4MTVjLTg0MzEtNGQ4Ni04NDU3LThjOWYyODkwOWIzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwNzMyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODg4MTE2ZDdiYjg1NTFhMTE5ZmE4YTU3YWExYTE3ZDk0NThlNTMzYzJkZGQ3NjNhOWRiNzliMzY1MGNkNTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L1sSuKCktQ1MEyNyO3wznx2KFkXOLFK9kcUdLAF41g0)

已修改，楼主可以关闭issues了。

**Comment by peaceanddemocracy** [comment]
软件中的设置顺序和服务端是一样的，但中文释义颠倒了很容易误导
