### ISSUE TITLE
[Bug]: tcp代理模式为tproxy时，代理列表失效

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3080]
### 描述您遇到的bug

tcp代理模式为**tproxy**时，代理列表失效且列表中的域名timeout
参考此[issues](https://github.com/xiaorouji/openwrt-passwall/issues/2987)

我将**ip.3322.net**加入代理列表，**tproxy**下出现timeout，改为**redirect**则成功打开网页，返回vps的ip

### 复现此Bug的步骤

1.将ip.3322.net添加至代理列表
2.tcp模式为tproxy
4.清空ipset、浏览器缓存以及dns缓存
5.访问ip.3322.net，此时网站应为打不开的状态
6.tcp模式改为redirect
7.再次访问ip.3322.net

### 您想要实现的目的

tcp代理模式为tproxy时，代理列表正常工作

### 日志信息

系统日志正常无报错
passwall日志正常无报错

### 截图

模式设置如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/7467d651-6c88-4005-89e6-a3075b7ba19b)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/5518b59a-b9de-4666-9886-9678b8a382fa)

### 系统相关信息

环境：immortalwrt 23.05，passwall 4.76-2。

### 其他信息

另外，此bug可能波及到了gfwlist模式

**Comment by handsomeji** [comment]
用 TProxy 的話需要注意一下有沒有編譯 mwan3？即使沒有使用也可能衝突

**Comment by BGzEroll** [comment]
> 用 TProxy 的話需要注意一下有沒有編譯 mwan3？即使沒有使用也可能衝突

无编译，这是我的[编译配置](https://github.com/BGzEroll/BGzErol-openwrt-mt7981/blob/main/360t7-23.config)

**Comment by wtfr-dot** [comment]
> 用 TProxy 的話需要注意一下有沒有編譯 mwan3？即使沒有使用也可能衝突

我一直用mwan3而且使用TProxy都没有问题，但是只能用iptables，只要用nftables就会与passwall冲突，感觉应该是mwan3还没原生支持nftables的原因，所以目前止步于openwrt-22.03

**Comment by handsomeji** [comment]
試下最新commit

**Comment by BGzEroll** [comment]
> 試下最新commit

已测试，成功修复，辛苦了

**Comment by yinb2207** [comment]
我的也是这个情况，暂时没有解决，不过有的机场就没事，有的机场却不行，我也很奇怪
