### ISSUE TITLE
节点里的MUX参数设置

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-package#3081]
### 描述你想要的新功能

节点里的MUX参数设置，可否在高级设置里，增加一个默认开启的选项。现在只能一个节点一个节点去调。

### 描述你想要的解决方案

节点里的MUX参数设置有设为默认开启的选项

**Comment by BGzEroll** [comment]
给当下想用的节点手动开启便好，感觉如无特别必要的，还是勿增实体好

**Comment by xcyll** [comment]
即使增加 默认也保持关闭为好
![024-04-01 132317](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/be4fb781-0428-49ba-9b49-30c0aa962aef)
