### ISSUE TITLE
[Feature Request]: passwall 4.76版本还有全局模式吗，怎么没有找到在哪里，以前老版的有全局模式

### ISSUE THREAD

**Issue by zzduci** [xiaorouji/openwrt-package#3083]
### 描述你想要的新功能

passwall 4.76版本还有全局模式吗，怎么没有找到在哪里，以前老版的有全局模式，有知道的在哪个菜单下面吗

### 描述你想要的解决方案

passwall 4.76版本还有全局模式吗，怎么没有找到在哪里，以前老版的有全局模式，有知道的在哪个菜单下面吗

**Comment by lwb1978** [comment]
中国列表、TCP默认代理模式、UDP默认代理模式都设置为代理应该就是全局了。

**Comment by zzduci** [comment]
> 中国列表、TCP默认代理模式、UDP默认代理模式都设置为代理应该就是全局了。

![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/77cb24c9-8344-4440-8a3e-dbd0584347bf)
哪几个打勾？

**Comment by lwb1978** [comment]
是下面的选项选择：代理

**Comment by zzduci** [comment]
> 是下面的选项选择：代理

![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/670767d2-8423-4201-8a78-5f48106b7d6b)
没有别的选项了，以前老版本这里可以选全局

**Comment by lwb1978** [comment]
![629aed5f67ac7bb06b44b3e5e06cb55](https://github.com/xiaorouji/openwrt-passwall/assets/86697442/c6ba7e09-dc95-4169-8a0c-45953812b1d3)
另外，你要先把版本更新到最新版本，否则就是鸡同鸭讲。

**Comment by zzduci** [comment]
> ![629aed5f67ac7bb06b44b3e5e06cb55](https://private-user-images.githubusercontent.com/86697442/318368704-c6ba7e09-dc95-4169-8a0c-45953812b1d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTcwODUsIm5iZiI6MTcxMTk1Njc4NSwicGF0aCI6Ii84NjY5NzQ0Mi8zMTgzNjg3MDQtYzZiYTdlMDktZGM5NS00MTY5LThhMGMtNDU5NTM4MTJiMWQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjg4MTAyMzUzMDkxZDM5N2U4MGI1ZTFjZjMyMTE5MmY2ODM2MWE5ODA2YzRiYTU1YTYxMmQzOWY1Yjg1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rOMy-lqPnSFugOCBYRjVPKh4EevD75_MaMvpFJDuk8) 另外，你要先把版本更新到最新版本，否则就是鸡同鸭讲。
已经是最新的版本了
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/4b0c5ac0-a1c7-4769-914c-73246059fcd2)已经是最新的版本了

**Comment by handsomeji** [comment]
GFW不勾選，中國列表不使用，默認代理模式選代理就是全局模式

**Comment by zzduci** [comment]
> GFW不勾選，中國列表不使用，默認代理模式選代理就是全局模式

![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/115a21e0-a993-476e-b512-a006fbc0f1af)
这样设置后，到网站测IP确实都变成了VPS的IP，但有一个网站打开还是打不开，只有开全局才可以打开https://anyfastcloud.com/              而且我的选项和你的这个有点不一样，没有“代理”只有下面这几个选项
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/1133ac41-9794-4c33-b794-bc524fbcc4f0)

**Comment by lwb1978** [comment]
至于你的设置跟我们的不一样你要检查你是否还安装了openclash而导致passwall的po翻译被污染，passwall本身是没有翻译成“必须代理的流量”这个说法的。你直接选择“必须代理的流量”这个选项就行，中文翻译被openclash覆盖而已，本质上就是“代理”。

**Comment by zzduci** [comment]
> 至于你的设置跟我们的不一样你要检查你是否还安装了openclash而导致passwall的po翻译被污染，passwall本身是没有翻译成“必须代理的流量”这个说法的。你直接选择“必须代理的流量”这个选项就行，中文翻译被openclash覆盖而已，本质上就是“代理”。

是的，确实安装了openclash，不折腾了，就随便用算了，再次谢谢两位的热心解答

**Comment by lwb1978** [comment]
> > 至于你的设置跟我们的不一样你要检查你是否还安装了openclash而导致passwall的po翻译被污染，passwall本身是没有翻译成“必须代理的流量”这个说法的。你直接选择“必须代理的流量”这个选项就行，中文翻译被openclash覆盖而已，本质上就是“代理”。
> 
> 是的，确实安装了openclash，不折腾了，就随便用算了，再次谢谢两位的热心解答

建议你更新到4.76-3版本，已经添加了全局模式的设置。

**Comment by zzduci** [comment]
> > > 至于你的设置跟我们的不一样你要检查你是否还安装了openclash而导致passwall的po翻译被污染，passwall本身是没有翻译成“必须代理的流量”这个说法的。你直接选择“必须代理的流量”这个选项就行，中文翻译被openclash覆盖而已，本质上就是“代理”。
> > 
> > 
> > 是的，确实安装了openclash，不折腾了，就随便用算了，再次谢谢两位的热心解答
> 
> 建议你更新到4.76-3版本，已经添加了全局模式的设置。

![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/9dfd33ec-a7b2-40f2-b85e-f33284c44d41)
牛，速度真快，我按你的建议升级到了4.76-3，并删除了openclash，终于可以和你们的一样了

**Comment by zzduci** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/58b27aab-383a-47fe-b3a0-36c0e7f3ff4d)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/d119f7e8-c91a-4177-ac20-e4a0b368066d)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/0558c2c8-00c6-42e2-8109-1611fb5cda9b)
还有一个问题就是，我在IP查询网站ip111.cn,上面查询显示全部都是国外的IP了，按道理来说这个就是全局了，但这个网站还是打不开，识别的还是我的IPV6的国内IP，我也把这个网站anyfastcloud.com
加入到了代理列表了（见第一张图），但还是没有走代理的IP去访问这个网站，这种又是什么引起的呢，疑惑不解中

**Comment by zzduci** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/3a519701-cdb9-4c74-a56b-83e82c69d703)

**Comment by lwb1978** [comment]
你是否已经开启了IPV6的透明代理？还有你的机场是否支持IPV6代理？

**Comment by zzduci** [comment]
> 你是否已经开启了IPV6的透明代理？还有你的机场是否支持IPV6代理？

![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/953a3dc0-65ff-48f3-9ddb-c004f54edaba)
是不是这里开启IPV6透明代理，如果是的话，那就是开启了的，机场是纯IPV6的VPS装的WARP添加的IPV4，我是用的优选IPV6连接的

**Comment by lwb1978** [comment]
试试关闭ipv6透明代理，或者dns那里勾选过滤代理域名ipv6

**Comment by zzduci** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/adea28b1-8955-4c08-9e7b-4a28d57a4787)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/ca1363e2-d871-458c-bbdf-b83c82584c93)
按照这个设置之后，也把网站添加到了代理列表，但还是打不开，还有这个网站也是这样https://v2rayssr.com/

**Comment by lwb1978** [comment]
远程dns设置成8.8.8.8试试。

**Comment by zzduci** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/bb7e512a-4cef-4e31-87b5-f2e0a8b2065d)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/279538dc-e2d0-4b78-8a35-1532c8c9b6f0)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/122016328/0db87e9b-16a1-4d26-b5a6-2126cf453bef)
还是一样的

**Comment by lwb1978** [comment]
你vps是纯ipv6所以比较复杂一些了，因为你是转的ipv4，所以还得排查vps上服务端的问题，快速判断的办法就是在电脑上安装windows版的翻墙软件连接你的机场看看是否能正常访问，如果可以就是pw的问题，如果不行那就行vps那边的问题。

**Comment by zzduci** [comment]
> 你vps是纯ipv6所以比较复杂一些了，因为你是转的ipv4，所以还得排查vps上服务端的问题，快速判断的办法就是在电脑上安装windows版的翻墙软件连接你的机场看看是否能正常访问，如果可以就是pw的问题，如果不行那就行vps那边的问题。

按你说的，我把openwrt里面的passwall关了，服务端VPS什么也没有动，用电脑版的V2RAYNG,用同样的客户端节点配置导入后，可以成功访问，上面不能访问的两个网站，终于可以成功打开了，还不是用的全局模式，就是普通的绕过大陆模式，两个网站都可以正常打开，这是不是说明是passwall的问题了，具体原因我也不知道

**Comment by zzduci** [comment]
补充一下，我搞忘记说了，我是旁路由的模式出现的上述情况
