### ISSUE TITLE
[Bug]: 官方23.05.3源码已经默认firewall4了~但是passwall好像还没完全适配吗？

### ISSUE THREAD

**Issue by Pacio** [xiaorouji/openwrt-package#3088]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall/assets/6836705/f3934cb8-c5df-4378-9657-cd28df7e4c5d)

### 复现此Bug的步骤

官方23.05.3源码
+最新版passwall 

高级设置里面防火墙工具切换nftables，等待一会就有大量日志报错

### 您想要实现的目的

不再报错

### 日志信息

如上

### 系统相关信息

passwall版本：4.76-3
浏览器：edge最新版
<html>
<body>

主机名称 | OpenWrt
-- | --
型号 | Default string Default string
架构 | Intel(R) Pentium(R) Gold 8505 x 5C 6T (2540.869MHz, 35.0°C)
目标平台 | x86/64
固件版本 | OpenWrt 23.05.3 r23809-234f1a2efa / LuCI openwrt-23.05 branch git-24.073.29889-cd7e519

</body>
</html>

**Comment by BGzEroll** [comment]
检查下dnsmasq用的是不是dnsmasq-full看看

**Comment by Pacio** [comment]
> dnsmasq

是full版

**Comment by BGzEroll** [comment]
> > dnsmasq
> 
> 是full版

那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件

**Comment by Pacio** [comment]
> > > dnsmasq
> > 
> > 
> > 是full版
> 
> 那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件

5.15内核的吗？我现在是6.6

**Comment by BGzEroll** [comment]
> > > > dnsmasq
> > > 
> > > 
> > > 是full版
> > 
> > 
> > 那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件
> 
> 5.15内核的吗？我现在是6.6

是的，5.15内核。我看23.05分支仍然是5.15内核，你是自己替换了内核版本吗

此外你是iptables和nftables混用了吗

**Comment by wtfr-dot** [comment]
我用官方openwrt-23.05编译passwall，运行时会强制使用nftables，根本无法使用iptables，也没有报错信息，只是因为我使用mwan3，使用fw4会有问题所以一直使用22.03

**Comment by Pacio** [comment]
> > > > > dnsmasq
> > > > 
> > > > 
> > > > 是full版
> > > 
> > > 
> > > 那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件
> > 
> > 
> > 5.15内核的吗？我现在是6.6
> 
> 是的，5.15内核。我看23.05分支仍然是5.15内核，你是自己替换了内核版本吗
> 
> 此外你是iptables和nftables混用了吗

是的，用的这位大神的~https://github.com/sbwml/r4s_build_script

**Comment by Pacio** [comment]
> 我用官方openwrt-23.05编译passwall，运行时会强制使用nftables，根本无法使用iptables，也没有报错信息，只是因为我使用mwan3，使用fw4会有问题所以一直使用22.03
晚上编译一下immortalwrt的源码~master分支和23.05分支哪个更稳定啊？求教

**Comment by Pacio** [comment]
> > > dnsmasq
> > 
> > 
> > 是full版
> 
> 那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件

晚上编译一下immortalwrt的源码~master分支和23.05分支哪个更稳定啊？求教

**Comment by wtfr-dot** [comment]
master分支本来就不稳定，毫无疑问官方的23.05是最稳定的，我用官方源码编译基本上不会出现莫名其妙的问题

**Comment by BGzEroll** [comment]
> > > > dnsmasq
> > > 
> > > 
> > > 是full版
> > 
> > 
> > 那就不清楚了，我也在用23.05不过是immortalwrt的，passwall在我这边运行得十分正常，或许你应该检查下你的编译配置文件
> 
> 晚上编译一下immortalwrt的源码~master分支和23.05分支哪个更稳定啊？求教

23.05

**Comment by wazzx** [comment]
同样的bug 
内核5.15.150 
op版本23.05.3
rockchip/armv8
官方sdk编译
pw：4.76-3 
![AM](https://github.com/xiaorouji/openwrt-passwall/assets/60512548/4f31adf1-d793-4ef7-8338-aea27be29256)

**Comment by qingtian110** [comment]
这和内核版本无关，即使你在openwrt 23.05 使用 4.19、5.4 、5.15 这些内核，同样会出现这样的情况。

这个问题抛给 dnsmasq 的 nftset 方面就对了。虽然它抛出异常日志，但是科学却工作，也就很离奇。

这个情况早在 openwrt 22.03 的时候就已经开始了，至今未解。反而用 iptables 方案是最稳定的。

**Comment by qingtian110** [comment]
但是可以确定的是，nftset 规则写入过多导致。

**Comment by Pacio** [comment]
> 但是可以确定的是，nftset 规则写入过多导致。

你好，我昨晚编译了immort的23.5源码~默认配置没动就勾选了几个自己用的插件~不知道为什么编译好以后显示存在旧版iptables规则？我看了一下默认配置文件，只有firewall4勾选了~不知道哪来的iptables规则?
![image](https://github.com/xiaorouji/openwrt-passwall/assets/6836705/d39a4038-bcbe-41c9-8b82-9e8f9648cb52)

**Comment by breeze303** [comment]
很多插件会依赖一些iptables，你需要自己一个个找出来去掉才行

**Comment by Pacio** [comment]
> 很多插件会依赖一些iptables，你需要自己一个个找出来去掉才行

已经找到了，就是dockerman的问题~设置option iptables '0'可以删除iptables规则但是任然无法消除该提示，除非不编译dockerman

**Comment by BGzEroll** [comment]
> > 很多插件会依赖一些iptables，你需要自己一个个找出来去掉才行
> 
> 已经找到了，就是dockerman的问题~设置option iptables '0'可以删除iptables规则但是任然无法消除该提示，除非不编译dockerman

不建议在主路由上配置任何与docker相关的东西

**Comment by qingtian110** [comment]
> > 很多插件会依赖一些iptables，你需要自己一个个找出来去掉才行
> 
> 已经找到了，就是dockerman的问题~设置option iptables '0'可以删除iptables规则但是任然无法消除该提示，除非不编译dockerman

因为 dockerd 工作基础就是 iptables，如果你跑 docker 的时候可以不用网络的话，hack dockerd 的makefile 去掉ipt依赖就不会出现这个情况。

但创建的容器就不能使用桥接网络了。

实际上 nft-iptables 并不会带来任何坏处

**Comment by Pacio** [comment]
> > > 很多插件会依赖一些iptables，你需要自己一个个找出来去掉才行
> > 
> > 
> > 已经找到了，就是dockerman的问题~设置option iptables '0'可以删除iptables规则但是任然无法消除该提示，除非不编译dockerman
> 
> 因为 dockerd 工作基础就是 iptables，如果你跑 docker 的时候可以不用网络的话，hack dockerd 的makefile 去掉ipt依赖就不会出现这个情况。
> 
> 但创建的容器就不能使用桥接网络了。
> 
> 实际上 nft-iptables 并不会带来任何坏处

你好，这两天发现dockerman有重大bug，只要开启网速就降低至少一半~这怎么回事啊

**Comment by lbg2008** [comment]
我用23.02的passwall新版，国内网站打开速度会变慢，换回21.02就正常

**Comment by handsomeji** [comment]
更新最新源碼，使用 ChinaDNS-NG 處理吧。
