### ISSUE TITLE
[Bug]: 运行了一会，出现好多进程。

### ISSUE THREAD

**Issue by jlzsss** [xiaorouji/openwrt-package#3090]
### 描述您遇到的bug

运行了一会，就打不开概览，要重启才行，但是过一会又打不开。

### 复现此Bug的步骤

程序运行一会（大约30分钟），就会出现此问题。

### 您想要实现的目的

麻烦修复一下。

### 日志信息

root@OpenWrt:~# ps | grep passwall
 4071 root      3432 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
 4072 root      1732 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
 4220 root      4568 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
 4221 root      2016 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
10762 root      1476 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
12993 root      4888 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
12994 root      2096 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
14471 root     1225m S    /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/HTTP_SOCKS_aAccBzjK.json
14639 root     1226m S    /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/acl/default/TCP_UDP_SOCKS.json
14666 root       768 S    /tmp/etc/passwall/bin/dns2tcp -L 127.0.0.1#15353 -R 127.0.0.1#5335 -v
14702 root      1056 S    /tmp/etc/passwall/bin/chinadns-ng -v -b 127.0.0.1 -l 15354 -c 127.0.0.1#5433,127.0.0.1#6080 -t 127.0.0.1#15353 -g /tmp/etc/passwall/chinadns_gfwlist -A passwall_gfwlist,passwall_gfwlist6 -d chn -f
15526 root      3852 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
15527 root      1836 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
15592 root     1226m S    /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/acl/myshunt_TCP_UDP_11201.json
15633 root       900 S    /tmp/etc/passwall/bin/dns2socks_acl_cfg1330ec 127.0.0.1 11101 127.0.0.1 5335 0.0.0.0 11301
15662 root      2860 S    /tmp/etc/passwall/bin/chinadns-ng -v -b 127.0.0.1 -l 11501 -c 127.0.0.1#5433,127.0.0.1#6080 -t 127.0.0.1#11301 -4 passwall_chnroute -6 passwall_chnroute6 -m /tmp/etc/passwall/chinadns_chnlist -M -a -g /tmp/etc/passwall/chinadns_gfwlist -A passwall_gfwlist,passwall_gfwlist6 -f
15716 dnsmasq   3388 S    /tmp/etc/passwall/bin/dnsmasq_cfg1330ec -C /tmp/etc/passwall/acl/cfg1330ec/dnsmasq.conf -x /tmp/etc/passwall/acl/cfg1330ec/dnsmasq.pid
23633 root      2920 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
23634 root      1604 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
23687 root      2172 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
23740 root      5192 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
23741 root      2172 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
26882 root      4220 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
26883 root      1928 S    sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'
30477 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """'mangle-OUTPUT-PSW'""" -m mark --mark 0x1 -j RETURN
30498 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """"'mangle-OUTPUT-PSW'"""" -j RETURN
30518 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """"""'mangle-OUTPUT-PSW'"""""" -j RETURN
30535 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """""'mangle-OUTPUT-PSW'""""" -m mark --mark 0x1 -j RETURN
30553 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """""""'mangle-OUTPUT-PSW'""""""" -m mark --mark 0x1 -j RETURN
30565 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """""""'mangle-OUTPUT-PSW'""""""" -m mark --mark 0x1 -j RETURN
30570 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """""""""'mangle-OUTPUT-PSW'""""""""" -m mark --mark 0x1 -j RETURN
30582 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -m comment --comment """""""""'mangle-OUTPUT-PSW'""""""""" -m mark --mark 0x1 -j RETURN
30601 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """""""""""'mangle-OUTPUT-PSW'""""""""""" -j RETURN
30616 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """""""""""'mangle-OUTPUT-PSW'""""""""""" -j RETURN
30627 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """""'mangle-OUTPUT-PSW'""""" -j RETURN
30639 root      1640 S    {iptables.sh} /bin/sh /usr/share/passwall/iptables.sh insert_rule_before /usr/sbin/iptables -t mangle -w OUTPUT mwan3 -o lo -m comment --comment """""'mangle-OUTPUT-PSW'""""" -j RETURN
30645 root      1588 S    grep passwall

### 系统相关信息

PassWall 使用的是[4.76-3]，貌似这几个版本都会出现此问题。
使用的是 EDGE 浏览器，版本是 123.0.2420.65

**Comment by laaArmy** [comment]
解决了吗

**Comment by jlzsss** [comment]
还没有

**Comment by jlzsss** [comment]
问题已解决

**Comment by gito10** [comment]
问题出在哪里，怎么解决的？
是passwall的bug还是自己配置上的问题，可以简单说明一下吗，之后有遇到类似问题的可以参考参考。

**Comment by jlzsss** [comment]
> 问题出在哪里，怎么解决的？ 是passwall的bug还是自己配置上的问题，可以简单说明一下吗，之后有遇到类似问题的可以参考参考。
我弄错了，问题没有解决，不好意思。

**Comment by gito10** [comment]
既然问题还没有解决，那你把你的配置情况大概说一下，把passwall的日志贴上来。
还有你的OpenWrt系统是什么版本。
你贴出来的进程，除了`sh -c exec 1000>&-; config() { echo "You cannot use UCI in firewall includes!" >&2; exit 1; }; . '/var/etc/passwall.include'`，其他都是正常的，看样子你应该是开了访问控制。
而多出来的那十几个，是你openwrt系统产生的。

**Comment by jlzsss** [comment]
确实是 DNS 设置问题，感谢大神提醒。
