### ISSUE TITLE
[Feature Request]: 更新最新版后，油管打开非常慢，Pixiv还上不去了

### ISSUE THREAD

**Issue by bilibili2077** [xiaorouji/openwrt-package#3091]
### 描述你想要的新功能

配置都没动过，同样的节点其他代理工具能上去pixiv，打开油管的速度也就2秒之内，但是更新最新版以后pixiv上不去，打开油管需要10秒以上，不知道这次更新动了什么，把pixiv的域名放到代理规则里也没有，不知道什么情况!
![屏幕截图 2024-04-02 200624](https://github.com/xiaorouji/openwrt-passwall/assets/95119149/3d64ff93-4033-46a6-9a30-18c73f245bfc)
![屏幕截图 2024-04-02 200638](https://github.com/xiaorouji/openwrt-passwall/assets/95119149/f7a26dda-7c04-48fc-9a24-2ecd01643460)

### 描述你想要的解决方案

有谁遇到过吗？

**Comment by soar68** [comment]
我也遇到了，最近更新的这几个版本都有这个问题，油管打开速度很慢

**Comment by Nicepaul** [comment]
有时候还打不开

**Comment by bilibili2077** [comment]
经过一天的测试，好像是xray的分流出错了，换成sinbox就没事！

**Comment by woni928** [comment]
> 经过一天的测试，好像是xray的分流出错了，换成sinbox就没事！

你开启IPv6后，dns不会泄露？

**Comment by bilibili2077** [comment]
> > 经过一天的测试，好像是xray的分流出错了，换成sinbox就没事！
> 
> 你开启IPv6后，dns不会泄露？

不会的，用mosdns

**Comment by gito10** [comment]
可以大概说一下使用xray分流时的配置吗，比如：
- 开没开前置代理；
- 各规则选择的节点都是xray类型的吗，还是有非xray类型的；
- 有没有用到xray负载均衡节点，或者haproxy负载均衡节点；
- DNS 过滤模式。

昨天优化修改xray分流部分代码时，确实发现好几个地方有问题，不过基本都是跟在分流里使用xray负载均衡节点相关的。最新提交把我发现的一些小问题都修复了，但估计跟你的情况没什么关系，你可以试试。
还有，如果是xray分流问题，怎么会只影响 YouTube和 pixiv，这俩你是放一个规则里的吗，包含这两个网站的规则用的什么类型的节点？

**Comment by gito10** [comment]
还有你说更新最新版后出现的，也就是说之前没出现，那更新之前是什么版本？
你可以按照commit提交逐步回退试试，看具体是哪个commit之后出现的问题。

**Comment by gito10** [comment]
#3092 也说是4.76-2分流正常，更新到4.76-3就有问题，而且更新到我最新的提交#3100 后又恢复正常，但我修的都是远在4.76-2 之前，去年就存在的bug，有点玄。

看你描述里说“这次更新”，也是指从 v4.76-2 到 v4.76-3吗？

**Comment by mars-m9** [comment]
最新源码我遇到的问题是：Xray 使用前置代理时，打开所有代理的网站都非常慢，不使用前置代理则非常快。
具体测试结果如下：
前置代理节点都是 Socks 自动切换去套普通 SS 节点
分流类型 Xray，中转节点 Xray Vmess，打开代理网站卡顿
分流类型 Xray，中转节点 Sing-Box Vmess，打开代理网站卡顿
分流类型 Sing-Box，中转节点 Xray Vmess，打开代理网站卡顿
分流类型 Sing-Box，中转节点 Sing-Box Vmess，打开代理网站流畅
切回3月10日编译的版本，卡顿均未复现。
