### ISSUE TITLE
[Bug]: 更新4.76-3后，分流失效

### ISSUE THREAD

**Issue by guochan2019** [xiaorouji/openwrt-package#3092]
### 描述您遇到的bug

x86，昨天上午编译，passwall从4.76-2升级到4.76-3，相同的配置，更新后Xray分流全部失效，外网出不去，折腾半天没用，又刷回4.76-2

### 复现此Bug的步骤

正常刷机配置后出现

### 您想要实现的目的

Xray分流

### 日志信息

正常刷机配置后出现

### 系统相关信息

Passwall 4.76-3，EDGE

**Comment by BGzEroll** [comment]
xray分流我一直在用，都是正常的。检查是否使用了不存在的geodata

**Comment by guochan2019** [comment]
> xray分流我一直在用，都是正常的。检查是否使用了不存在的geodata

你好，我的也都正常，就是升级4.76-3后出现的，你现在也用4.76-3么？geodata常规操作这个我知道，而且我在自己的两台软路由上都试过，同样的问题

**Comment by lwb1978** [comment]
我arm和x86两台路由更新4.76-3后都可以正常xray分流

**Comment by pbclaodentm** [comment]
我的也正常，就是找不到以前passwall里负载均衡菜单了，不知道为啥，当然最近新刷的23.05的op，新装的最新的passwall，你这个不能分流的问题，你注意下顺序，就是“规则管理”里“Sing-Box/Xray 分流规则”的顺序，你想让谁分流出去，比如我就是netflix，就放第一，直连放最后，默认放倒数第二个即可

**Comment by guochan2019** [comment]
楼上的几位兄弟，我不知道你们用的什么设备，是自己编译还是安装的插件，我又反复试了好几次，今天又编译了一次，结果还是不行，我看到https://github.com/xiaorouji/openwrt-passwall/issues/3091里也有人提到分流的问题，所以此issues我认为的确存在，我自己编译使用passwall有几年了，常规的更新使用应该不是问题所在。

**Comment by lwb1978** [comment]
我的一台是r68s 一台是n4100，用lede 6.6内核编译，没有编译mwan3和加速插件，m3我用不上、现在我路由性能过剩也用不上加速。貌似pw跟w3和加速有一定冲突。

**Comment by guochan2019** [comment]
看到Tianhe Y更新代码，今早编译安装后4.76-3分流正常了，此帖关闭

**Comment by gito10** [comment]
> 看到Tianhe Y更新代码，今早编译安装后4.76-3分流正常了，此帖关闭

虽然我更新的是分流部分，也的确发现了很多地方有些小bug，不过都是分流模式下使用xray负载均衡节点相关的，其中最主要的有2个：
- 多个分流规则选择了同一个xray负载均衡节点（如果balancer的fallback也是一个balancer，所有用到的balancer出现重复，会造成xray无法运行，首页状态显示未运行）。
- 默认规则如果选择xray负载均衡节点，同时DNS 模式使用xray，会导致passwall设置的dns走默认节点出站路由失效，不过这个影响看个人设置了。

而且这些问题都是远在 v4.76-2 之前就存在的，并不是v4.76-2到4.76-3之间引入的。

你的分流应该没有用到xray负载均衡节点吧，就很玄学。

昨天提交PR后，有在下面回复说这次更新后，也许还能解决掉一些尚未发现的bug，不会真被我说中了吧，可我说的未知bug也都是有用到xray负载均衡才会出现的。

**Comment by guochan2019** [comment]
> > 看到Tianhe Y更新代码，今早编译安装后4.76-3分流正常了，此帖关闭
> 
> 虽然我更新的是分流部分，也的确发现了很多地方有些小bug，不过都是分流模式下使用xray负载均衡节点相关的，其中最主要的有2个：
> 
> * 多个分流规则选择了同一个xray负载均衡节点（如果balancer的fallback也是一个balancer，所有用到的balancer出现重复，会造成xray无法运行，首页状态显示未运行）。
> * 默认规则如果选择xray负载均衡节点，同时DNS 模式使用xray，会导致passwall设置的dns走默认节点出站路由失效，不过这个影响看个人设置了。
> 
> 而且这些问题都是远在 v4.76-2 之前就存在的，并不是v4.76-2到4.76-3之间引入的。
> 
> 你的分流应该没有用到xray负载均衡节点吧，就很玄学。
> 
> 昨天提交PR后，有在下面回复说这次更新后，也许还能解决掉一些尚未发现的bug，不会真被我说中了吧，可我说的未知bug也都是有用到xray负载均衡才会出现的。

是的大神，我使用的Xray分流节点全部都是负载均衡，不过测试时我切换到正常节点好像也不分流，今早的更新后就正常了，不好说到底是因为啥，总之是感谢大神

**Comment by gito10** [comment]
我也是因为自己有需求，原来分流模式不能使用Xray负载均衡节点，因为自己有需求，所以去年自己给加上了。
最近，又终于等到xray负载均衡leastping策略支持fallback，就赶紧给适配了。
昨天也是想设置成类似这样的：
```
rule-a ---> balancer-1
rule-b ---> balancer-2 --fallback--> balancer-1
```
结果设置完直接不运行，就去看代码，问题找到了，本来只解决这个问题不用修改那么多代码的。然后还发现其他好几个地方有问题或者有待优化，就一起改了。

其他人好像都不太使用xray的负载均衡，尤其是分流+负载均衡这种，所以之前都不支持leastping和在分流里使用。
像这个issue提出的问题，其实就不单是分流的问题，而是在xray balancer和其他功能的适配问题上。因为在xray里的balancer，不像singbox里的urltest是个普通出站协议，它是在路由设置里的，所以在代码层面需要特殊处理适配。


你这个提出几天都没有什么有效建议，也没找出问题所在，也在于你没说明清楚情况。其实我前几天就看到你这个issue，但真没以为你也在分流里用balancer，跟其他人一样以为你自己配置的问题，所以直接忽略了。

再有类似的问题，一定把全部情况说明清楚，尤其涉及到几种特殊用法的（分流，xray负载均衡，socks自动切换，haproxy的2种负载均衡），尤其多种组合使用的，说清楚才好定位问题。

如果是涉及到xray负载均衡相关的问题或者功能建议，也可以直接到讨论里面有个“Xray负载均衡讨论”，在那里面提。

**Comment by guochan2019** [comment]
> 我也是因为自己有需求，原来分流模式不能使用Xray负载均衡节点，因为自己有需求，所以去年自己给加上了。 最近，又终于等到xray负载均衡leastping策略支持fallback，就赶紧给适配了。 昨天也是想设置成类似这样的：
> 
> ```
> rule-a ---> balancer-1
> rule-b ---> balancer-2 --fallback--> balancer-1
> ```
> 
> 结果设置完直接不运行，就去看代码，问题找到了，本来只解决这个问题不用修改那么多代码的。然后还发现其他好几个地方有问题或者有待优化，就一起改了。
> 
> 其他人好像都不太使用xray的负载均衡，尤其是分流+负载均衡这种，所以之前都不支持leastping和在分流里使用。 像这个issue提出的问题，其实就不单是分流的问题，而是在xray balancer和其他功能的适配问题上。因为在xray里的balancer，不像singbox里的urltest是个普通出站协议，它是在路由设置里的，所以在代码层面需要特殊处理适配。
> 
> 你这个提出几天都没有什么有效建议，也没找出问题所在，也在于你没说明清楚情况。其实我前几天就看到你这个issue，但真没以为你也在分流里用balancer，跟其他人一样以为你自己配置的问题，所以直接忽略了。
> 
> 再有类似的问题，一定把全部情况说明清楚，尤其涉及到几种特殊用法的（分流，xray负载均衡，socks自动切换，haproxy的2种负载均衡），尤其多种组合使用的，说清楚才好定位问题。
> 
> 如果是涉及到xray负载均衡相关的问题或者功能建议，也可以直接到讨论里面有个“Xray负载均衡讨论”，在那里面提。

好的，再次感谢！！！

**Comment by hcym** [comment]
下午 编译的，用的大雕库，基本正常，基本默认值，分流和负载后备均衡都是，用官方mster的话昨天编译的p2有点事，p1可以。
