### ISSUE TITLE
[Bug]: passwall的自动检测延迟ping显示超时

### ISSUE THREAD

**Issue by bikioxo** [xiaorouji/openwrt-package#3093]
### 描述您遇到的bug

passwall的自动检测延迟ping显示超时，，但是节点都可用

### 复现此Bug的步骤

进入节点列表刷新，自动ping节点全部显示超时，但是节点都可用

### 您想要实现的目的

自动ping节点显示正常

### 日志信息

No response

### 截图

No response

### 系统相关信息

Passwall 版本【 4.75-10 】

### 其他信息

No response

**Comment by firkerword** [comment]
时空穿越了？

**Comment by bikioxo** [comment]
> 时空穿越了？

什么意思了
