### ISSUE TITLE
在OpenWrt里面PassWall添加规则列表，直连列表添加6000多行的IP地址后无法保存

### ISSUE THREAD

**Issue by taizhourenjia** [xiaorouji/openwrt-package#3095]
### 描述您遇到的bug

在OpenWrt里面PassWall添加规则列表，直连列表添加6000多行的IP地址后无法保存
添加的IP列表下载地址为
https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

### 复现此Bug的步骤

passwall
规则列表
直连列表
添加6000多行的IP地址规则

### 您想要实现的目的

需要手动写入国内IP地址，强制直连

### 日志信息

没有

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/81817891/90e26711-a853-456a-906b-f97c3ce7942c)

### 系统相关信息

passwall版本4.72-2 
电脑win11
浏览器chrome

**Comment by gito10** [comment]
直接在规则管理里面把中国IP段的源换成你上面那个地址然后更新，再代理模式中国列表选直连不就好了吗，为什么非要手动填。

**Comment by taizhourenjia** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81817891/a2fa325d-4605-4940-b86f-3c7da0388928)
请问是这样吗？

**Comment by gito10** [comment]
>请问是这样吗？

就是这个意思，不过你这图片里填的有问题啊，复制了2遍，删了重新添加一次就行了。
再就是记得把代理模式里面中国列表设置检查下，是不是直连。
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/27452c5d-0e42-4372-b5f7-ef7436462e7d)
