### ISSUE TITLE
[Bug]: 为什么负载均衡标签都没有了呢，运行状态还有他未运行状态，何解？

### ISSUE THREAD

**Issue by pbclaodentm** [xiaorouji/openwrt-package#3096]
### 描述您遇到的bug

负载均衡找不到那里去了 ，标签都没了。

### 复现此Bug的步骤

服务里点击passwall进入，观看菜单，只有：基本设置、节点列表、节点列表、节点订阅、高级设置、组件更新、规则管理、规则列表、访问控制、服务器端、查看日志
老版本里能看到的负载均衡消失了，我尝试安装了haproxy后，passwall里依然无法看到此功能，服务里反而有了一个负载均衡。

### 您想要实现的目的

怎么实现负载均衡功能，现在找不到入口了

### 日志信息

日志里基本和这个无关了，我也更新过几次了，现在都是最新的，包括插件依赖包都重新下载这里的每个安过一次

### 系统相关信息

我的passwall版本是4.76-3
op的内核版本是5.15.148

**Comment by pbclaodentm** [comment]
找到原因了，默认被隐藏了这个菜单，确切的说，安了haproxy也会没有，真正的原因是，得用浏览器恢复隐藏菜单
http://IP管理地址/cgi-bin/luci/admin/services/passwall/show    比如我就进这个就可以看到负载均衡菜单了
我是在FAQ里看到的........
关于DNS问题：
1. 部分浏览器可能有内置的DNS，请务必关闭。如：chrome。 设置 - 安全和隐私设置 - 使用安全 DNS 关闭。
2. 有时候重启后，上不了，尤其是GFW模式。这时请先关闭所有浏览器（重要），Windows客户端请`ipconfig /flushdns`。手机端请关闭WIFI，切一下飞行模式再切回来。
3. 客户端DNS和默认网关必须指向本路由器。
4. 如果你自行配置了错误的DNS流程，后果自负！
可以使用负载均衡实现故障切换功能。
恢复默认配置方法，地址栏输入例：[http://IP管理地址/cgi-bin/luci/admin/services/passwall/reset_config](http://IP管理地址/cgi-bin/luci/admin/services/passwall/settings#)
隐藏菜单方法，地址栏输入例：[http://IP管理地址/cgi-bin/luci/admin/services/passwall/hide](http://IP管理地址/cgi-bin/luci/admin/services/passwall/settings#)
当你隐藏后想再次显示，地址栏输入例：[http://IP管理地址/cgi-bin/luci/admin/services/passwall/show](http://IP管理地址/cgi-bin/luci/admin/services/passwall/settings#)

**Comment by lwb1978** [comment]
我觉得并不是默认隐藏，而是你之前没有安装hap，检测到没有组件所以隐藏负载均衡菜单并写入了luci的配置或者临时文件，你安装了hap并运行了show后重写了配置或者清理了临时文件后就显示出来了。以上我没看代码全靠猜测的。

**Comment by didiplus** [comment]
你的猜测没错，我没有安装hap之前，访问上面的链接也没有这个配置项，安装完hap后就有了。

**Comment by undefine-man** [comment]
实测手动安装haproxy后重启就可以看到“负载均衡”标签选项

**Comment by cygbs** [comment]
> 实测手动安装haproxy后重启就可以看到“负载均衡”标签选项

我这里需要安装后多访问几次用于显示菜单的网址，然后清空浏览器对于路由器管理界面的缓存。
