### ISSUE TITLE
[Bug]: 节点订阅 手动订阅全部  Xray负载均衡后备节点设置被清空

### ISSUE THREAD

**Issue by ywx1983cn** [xiaorouji/openwrt-package#3098]
### 描述您遇到的bug

节点订阅 手动订阅全部  Xray负载均衡后备节点设置被清空 

### 复现此Bug的步骤

节点订阅 手动订阅全部  Xray负载均衡后备节点设置被清空 

### 您想要实现的目的

后备节点不被清空

### 日志信息

4.76-3

### 系统相关信息

4.76-3

**Comment by gito10** [comment]
目前我用的配置是把后备设为另一个xray负载均衡节点，这个不受影响。
我把后备改成一个ss类型单节点试了下，确实会丢失。

**Comment by lwb1978** [comment]
估计得修改subscribe.lua的代码，我打开看了一下，无奈水平不足直接懵圈。
