### ISSUE TITLE
[Bug]: openwrt-23.05 fw3重启防火墙时有关于passwall的错误

### ISSUE THREAD

**Issue by wtfr-dot** [xiaorouji/openwrt-package#3103]
### 描述您遇到的bug

用官方最新openwrt-23.05源码编译passwall的smartdns分支，由于mwan3的原因没有使用fw4，全部编译的fw3，偶然发现在reload防火墙时提示passwall.include和passwall_server.include都有错误发生

### 复现此Bug的步骤

sshd进路由器后台reload防火墙，出现此错误信息，passwall清空ipset再reload防火墙同样出现

### 您想要实现的目的

检查并修正错误

### 日志信息

![QQ截图20240405230746](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/30e08ee4-1cb5-4e0c-926e-02b753239757)

### 系统相关信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/42ab086b-4e9f-49f3-9eb9-31c4f765465a)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/76f8fce4-33f4-45d7-b982-3f5c365af4ab)

**Comment by uingei** [comment]
是不是 ip6tables-mod-nat 没装？

**Comment by wtfr-dot** [comment]
> 是不是 ip6tables-mod-nat 没装？

确实没装，我装上试试

**Comment by wtfr-dot** [comment]
确实是缺少iptables-mod-nat引起的
