### ISSUE TITLE
[Feature Request]: ipset配置文件存储空间优化

### ISSUE THREAD

**Issue by ZqinKing** [xiaorouji/openwrt-package#3105]
### 描述你想要的新功能

/tmp路径下dnsmasq和etc/passwall_tmp中ipset的配置文件能否使用软连接，这样只保存一份源文件，可以节省6~7M左右i的空间。

### 描述你想要的解决方案

使用软连接，或者直接修改配置读取路径，运行时仅保留一份ipset配置文件。

**Comment by gito10** [comment]
/tmp/etc/passwall_tmp/ 这个目录应该是生成配置的临时目录，生成完毕，复制到相应目录后，应该删掉了，可能忘了删了的？

**Comment by kxdn3** [comment]
自己删除试试

**Comment by ZqinKing** [comment]
> 自己删除试试

可以删除，支部不过页面配置后会重新生成。

**Comment by gito10** [comment]
手动删除肯定是不行的，要修改相应代码，不用了自动删除。

**Comment by handsomeji** [comment]
緩存文件。
如果你的Openwrt裝了 `procd-ujail` dnsmasq將沒有權限使用軟連接，否則會使用軟連接的。
