### ISSUE TITLE
[Bug]: 相同的配置，Passwll用Xray和Sing-box都无法正确连结WireGuard节点。

### ISSUE THREAD

**Issue by Azreulo** [xiaorouji/openwrt-package#3106]
### 描述您遇到的bug

`{
    "interface_name": "WARP",
    "local_address": [
        "172.16.0.2/32",
        "2606:-------------------/128"
    ],
    "mtu": 1408,
    "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
    "private_key": "-------------------------",
    "server": "----------",
    "server_port": ----------,
    "system_interface": false,
    "tag": "proxy",
    "type": "wireguard"
}`
（敏感信息替换为--------）
这样的配置文件，在NekoRay中使用Sing-box内核，能正确连结WireGuard，但是在Passwall中，相同的配置，却连结不上。

其中两个选项：
1、额外的对称加密密钥。
请问这个选项是必须的吗？需要从哪里获取这个密钥？
2、Reserved
同样，这个选项从何获取？

### 复现此Bug的步骤

添加一个WireGuard（Warp Team）信息。

### 您想要实现的目的

使用WireGuard。

### 日志信息

无。如需要请回复。

### 系统相关信息

Passwall：4.73.-3

**Comment by gito10** [comment]
Android版NekoBox有自动申请cloudflare warp配置的功能，不知道你的配置是不是PC版NekoRay里用同样功能生成的。
反正我用手机NekoBox点修改配置，最底下一行reserved是4个字母的base64字符串，passwall里这一项我有作适配处理，可以直接把这个base64填上去。PC版上直接查看配置应该也有这一项吧。

**Comment by gito10** [comment]
team的话，只能用官方客户端吧，获取配置好像只能抓包？去年试过，具体记不太清了。现在有工具可以直接导出warp team的配置吗？

**Comment by Azreulo** [comment]
> team的话，只能用官方客户端吧，获取配置好像只能抓包？去年试过，具体记不太清了。现在有工具可以直接导出warp team的配置吗？

是的，可以直接把Team的配置导出，使用官方WireGuard客户端连接。

**Comment by Azreulo** [comment]
> Android版NekoBox有自动申请cloudflare warp配置的功能，不知道你的配置是不是PC版NekoRay里用同样功能生成的。 反正我用手机NekoBox点修改配置，最底下一行reserved是4个字母的base64字符串，passwall里这一项我有作适配处理，可以直接把这个base64填上去。PC版上直接查看配置应该也有这一项吧。

我是把Team的配置导出了，可以在WireGuard里连接，可以在NekoRay里连接，但是Passwall里连接失败，不知道是缺少配置还是哪里配置出错。

**Comment by gito10** [comment]
那你用nekoray连上warp，查看IP是哪里的，我去年测试时，应该显示是你本省（可能是其他市），就确实是直连连上的。如果显示境外地址，可能并不是直连，而是走了passwall的代理节点中转连上的。warp在访问cloudflare以外的网站时，分配的出口IP是跟客户端IP归属一个地方的。

我用NekoBox生成一个warp配置，直接连接，连不上，加个前置代理，就可以连上。
前置代理是HK的，测IP也是HK的，把前置换TW，测IP也变TW了。
你可以先连上测IP看看，是不是跟你所在相同。

排除这个问题后，大概就是配置上缺了warp的routeid，对应wireguard的reserved。
至于passwall大概是没有问题的，去年我用warp和warp team都试过，没问题。就是可以直连的IP不好找。

**Comment by Azreulo** [comment]
> 那你用nekoray连上warp，查看IP是哪里的，我去年测试时，应该显示是你本省（可能是其他市），就确实是直连连上的。如果显示境外地址，可能并不是直连，而是走了passwall的代理节点中转连上的。warp在访问cloudflare以外的网站时，分配的出口IP是跟客户端IP归属一个地方的。
> 
> 我用NekoBox生成一个warp配置，直接连接，连不上，加个前置代理，就可以连上。 前置代理是HK的，测IP也是HK的，把前置换TW，测IP也变TW了。 你可以先连上测IP看看，是不是跟你所在相同。
> 
> 排除这个问题后，大概就是配置上缺了warp的routeid，对应wireguard的reserved。 至于passwall大概是没有问题的，去年我用warp和warp team都试过，没问题。就是可以直连的IP不好找。

我测试一下。
我记得Warp会根据你的IP地址来分配就近节点。
但是其实可以优选的。我用的就是优选的方案。

**Comment by gito10** [comment]
我昨天修改调试前置代理bug时，因为手机nekobox测试warp直连连不上，走前置代理能连上，很适合作为测试用的落地节点。
然后我发现xray是能连接上的，~~但是sing-box确实好像不通，我等会再测试下。~~
你打开nekoray生成的sing-box配置文件，和passwall生成的配置文件（/tmp/etc/passwall/acl/default/TCP_UDP_开头的json文件），对比2个文件的outbound部分看有什么不同。

---
更新

后来测试用纯sing-box，即前置代理节点是sing-box的，wireguard也是sing-box的，可以成功连上。而且还发现sing-box 的WireGuard 的Reserved参数同时支持`[n1,n2,n3]`和 **base64字串**，passwall其实可以不用进行转换。
我再进一步测试其他情况。

**Comment by hahach** [comment]
额外对称密钥不必须。
reserved这个参数只有部分地区的warp节点有这个参数，在账户生成的时候就要记下来，必须填上才能用。没有这个参数的就不要填。
我昨天刚转的passwall，刚刚看到这个issue，试了下xray添加wireguard。
我是zerotruth账户，添加后是可以使用的，但是节点里面的tcping是报错的，这个东西导致我昨天加的时候以为passwall里的xray也没做好wireguard的支持，没想到居然可以。

**Comment by handsomeji** [comment]
> 额外对称密钥不必须。 reserved这个参数只有部分地区的warp节点有这个参数，在账户生成的时候就要记下来，必须填上才能用。没有这个参数的就不要填。 我昨天刚转的passwall，刚刚看到这个issue，试了下xray添加wireguard。 我是zerotruth账户，添加后是可以使用的，但是节点里面的tcping是报错的，这个东西导致我昨天加的时候以为passwall里的xray也没做好wireguard的支持，没想到居然可以。

wireguard 使用的是 `udp`，你`tcping`當然是timeout.
