### ISSUE TITLE
[Feature Request]: haproxy版本太老了能否更新

### ISSUE THREAD

**Issue by kxdn3** [xiaorouji/openwrt-package#3107]
### 描述你想要的新功能

编译的haproxy还是两年前的2.66版本，能否更新到2.9

### 描述你想要的解决方案

更新到最新稳定版

**Comment by uingei** [comment]
haproxy 自行替换编译就行 [openwrt/packages](https://github.com/openwrt/packages/tree/openwrt-23.05/net/haproxy)

**Comment by gito10** [comment]
haproxy 包openwrt官方仓库就有，直接从系统opkg 更新就可以，看你op上opkg源是哪个版本的还是snapshots的。23.05.3和snapshots目前都是2.86版的。

**Comment by lwb1978** [comment]
楼主用的应该是LEDE的源编译，LEDE那边把精力都放到系统更新和适配上，仓库软件的维护不是很积极，一些软件比较老，要新版只能自行替换了

**Comment by gito10** [comment]
packages、luci仓库可以改成openwrt的源，选择合适的版本就可以了。

**Comment by Jasonzhang2023** [comment]
可以下载ipk，比较傻瓜模式，我是从这里下载的：https://op.dllkids.xyz/packages/

**Comment by hcym** [comment]
我是重度haproxy用户，根本没必要
而且新版的不能用luci app
只能用pass内置的，稍微复杂了一点

**Comment by lwb1978** [comment]
> 我是重度haproxy用户，根本没必要 而且新版的不能用luci app 只能用pass内置的，稍微复杂了一点

2.86应该还可以用 luci app，2.9就不知道了

**Comment by kxdn3** [comment]
> haproxy 自行替换编译就行 [openwrt/packages](https://github.com/openwrt/packages/tree/openwrt-23.05/net/haproxy)

已经编译进固件

**Comment by kxdn3** [comment]
编译进去了，好多报错啊

4 thread compile
31
WARNING: Makefile 'package/net/haproxy/libs/libmpc/Makefile' has a dependency on 'libmpfr', which does not exist
32
WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatchling/host', which does not exist
33
WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-requirements-txt/host', which does not exist
34
WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-vcs/host', which does not exist
35
WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'liblucihttp-ucode', which does not exist
36
WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'ucode-mod-log', which does not exist

**Comment by gito10** [comment]
你OP是什么版本的，直接从官方源下一个安装吧。

**Comment by hcym** [comment]
都说了重度用户，各种组合都反复试过，新版和openssl也有依赖，别瞎搞什么替换覆盖

**Comment by lwb1978** [comment]
缺依赖，缺啥

> 编译进去了，好多报错啊
> 
> 4 thread compile 31 WARNING: Makefile 'package/net/haproxy/libs/libmpc/Makefile' has a dependency on 'libmpfr', which does not exist 32 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatchling/host', which does not exist 33 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-requirements-txt/host', which does not exist 34 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-vcs/host', which does not exist 35 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'liblucihttp-ucode', which does not exist 36 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'ucode-mod-log', which does not exist

具体不知道你编译的是什么版本，但可以肯定的是你所用来编译的系统缺少组件，我在LEDE里拉取immortalwrt仓库的2.86版haproxy云编译成功。

**Comment by ZqinKing** [comment]
passwall中的haproxy都是从127.0.0.1发起的请求，所以新版旧版没有差别。一些特性是用不上的。

**Comment by kxdn3** [comment]
> 缺依赖，缺啥
> 
> > 编译进去了，好多报错啊
> > 4 thread compile 31 WARNING: Makefile 'package/net/haproxy/libs/libmpc/Makefile' has a dependency on 'libmpfr', which does not exist 32 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatchling/host', which does not exist 33 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-requirements-txt/host', which does not exist 34 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-vcs/host', which does not exist 35 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'liblucihttp-ucode', which does not exist 36 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'ucode-mod-log', which does not exist
> 
> 具体不知道你编译的是什么版本，但可以肯定的是你所用来编译的系统缺少组件，我在LEDE里拉取immortalwrt仓库的2.86版haproxy云编译成功。

我去看了你编译的，也缺依赖🥲
WARNING: Makefile 'package/feeds/packages/curl/Makefile' has a dependency on 'libngtcp2', which does not exist

**Comment by kxdn3** [comment]
> 缺依赖，缺啥
> 
> > 编译进去了，好多报错啊
> > 4 thread compile 31 WARNING: Makefile 'package/net/haproxy/libs/libmpc/Makefile' has a dependency on 'libmpfr', which does not exist 32 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatchling/host', which does not exist 33 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-requirements-txt/host', which does not exist 34 WARNING: Makefile 'package/net/haproxy/utils/mpremote/Makefile' has a build dependency on 'python-hatch-vcs/host', which does not exist 35 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'liblucihttp-ucode', which does not exist 36 WARNING: Makefile 'package/net/haproxy/net/uspot/Makefile' has a dependency on 'ucode-mod-log', which does not exist
> 
> 具体不知道你编译的是什么版本，但可以肯定的是你所用来编译的系统缺少组件，我在LEDE里拉取immortalwrt仓库的2.86版haproxy云编译成功。

最新改的这个也编译不成功
# 拉取immortalwrt仓库组件
 rm -rf feeds/packages/net/{haproxy,msd_lite,curl}
 merge_package master https://github.com/immortalwrt/packages feeds/packages/net net/haproxy net/msd_lite net/curl

**Comment by lwb1978** [comment]
> haproxy

我这个是curl，跟haproxy两码事，我上面这段代码你都没搞清楚我要干什么吧，我劝你还是不要去升级什么版本了。
