### ISSUE TITLE
[Bug]: 现在有俩中国列表=。=

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#3108]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall/assets/50496854/746400e8-4e0c-4ebd-9704-6e2e902b81b5)

### 复现此Bug的步骤

点进去就能看到（狗头

### 您想要实现的目的

大佬有空修修就行

### 日志信息

不需要

### 系统相关信息

https://github.com/xiaorouji/openwrt-passwall/commit/1b13dd2c0346a782820098fcb4b97d17288240ac

**Comment by lwb1978** [comment]
一个应该是“中国域名列表”，一个应该是“中国IP列表”，大佬偷懒了。
@xiaorouji

**Comment by kxdn3** [comment]
我咋没有这个

**Comment by xcyll** [comment]
![2024-04-08 131644](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/bffcfc93-d90e-4d22-a936-8ae8a47516e2)

**Comment by xcyll** [comment]
> 我咋没有这个

最新版才有的4.76-4

**Comment by kxdn3** [comment]
看第一个图我以为模式里面😅

**Comment by jh0072110** [comment]
> ![2024-04-08 131644](https://private-user-images.githubusercontent.com/63227888/320361246-bffcfc93-d90e-4d22-a936-8ae8a47516e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTQ3NjIsIm5iZiI6MTcxMjU1NDQ2MiwicGF0aCI6Ii82MzIyNzg4OC8zMjAzNjEyNDYtYmZmY2ZjOTMtZDkwZS00ZDIyLWE5MzYtOGFlOGE0NzUxNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA1MzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWQ5ZWY2ZWIyOTkzOWY1NzE4Mzg4M2IzNTcwM2YxMmJhMWE1NDczYjY0NjU5NTgyNjIwMDdhNjFjODJkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDPDJPU1Ok_1qQPakvDJEMLp7wBkpq1azptF9Yd_O40)

骚瑞我截图截的太不全面哈哈哈哈

**Comment by woni928** [comment]
确实如此，等大佬有时间更新
