### ISSUE TITLE
[Feature Request]: 端口跳跃功能支持不完善

### ISSUE THREAD

**Issue by laaArmy** [xiaorouji/openwrt-package#3110]
### 描述你想要的新功能

openwrt23.05   passwall是4.76.4
sing-box内核hy2协议
不支持这种30000-40000这种端口跳跃写法

### 描述你想要的解决方案

RT

**Comment by handsomeji** [comment]
Sing-Box 不支持端口跳躍。

**Comment by laaArmy** [comment]
> Sing-Box 不支持端口跳躍。

啊这样吗，我看见nekobox安卓有啊，而且我自己用得一键脚本也是带了sing-box端口跳跃
