### ISSUE TITLE
[求助]: 拜托了别关issue, ssh连接显示本地ip地址

### ISSUE THREAD

**Issue by HeInfinity** [xiaorouji/openwrt-package#3115]
### 描述您遇到的bug

建立好网络后, 使用ssh连接中转机发现中转机显示我本地ip地址, 但是落地鸡能够正确显示落地ip. 我想请问到底是哪里出现了问题. 
感谢各位大佬回答!
使用v2rayN的tun模式连接ssh时就没有这个问题

### 复现此Bug的步骤

1/ 中转机和落地鸡使用的ssh端口均不是22端口, 但是我在passwall中设置了tcp/udp端口所有转发
2/ 在passwall的代理规则里已经添加了中转机和落地鸡的ip, 在singbox/xray规则中也已经先于direct设置了他们的ip走代理

### 您想要实现的目的

让我的中转机在ssh连接时能够正确使用落地鸡连接

### 日志信息

确实没有相关日志, 我使用了wireshark和tcpdump进行抓包, 但是也没有什么结果

### 截图

![1](https://github.com/xiaorouji/openwrt-passwall/assets/95559330/7ffdddd9-64b6-4c60-9098-7fb09409c2e9)
![2](https://github.com/xiaorouji/openwrt-passwall/assets/95559330/d8a985a2-359b-4d45-ad05-0810ab4adcee)
![3](https://github.com/xiaorouji/openwrt-passwall/assets/95559330/91d66c08-349e-452a-b802-37a98f82f861)

### 系统相关信息

passwall版本: 4.76-1
openwrt: immortalwrt 23.05.2
hysteria2版本: 2.4.0

**Comment by HeInfinity** [comment]
我查看nftables的时候发现有这段代码, 然后紧接着passwall_gfwlist, 是否在这个内容里的ip都会使用直连的方式?
```
        set passwall_vpslist {
                type ipv4_addr
                flags interval,timeout
                auto-merge
                elements = { 127.0.0.1, 152.x.x.x }
        }
```
为什么会有这个猜想呢? 因为当我把另一台中转机添加到passwall后, 原本显示落地鸡ip连接的中转机B也显示了我真实ip

```
        set passwall_vpslist {
                type ipv4_addr
                flags interval,timeout
                auto-merge
                elements = { 127.0.0.1, 152.x.x.x,
                             192.x.x.x }
        }
```

**Comment by gito10** [comment]
问题描述不够清楚，你所说的“显示本地IP”和“显示落地IP”是什么意思，是执行什么命令查到的IP还是怎么回事。
还有passwall的大概配置也说一下。

**Comment by BGzEroll** [comment]
节点ip或域名会被添加到vpslist，vpslist表会走直连，这是保证你在路由器开启透明代理后依旧可以使用客户端直接连接vps，而不会被链式代理

**Comment by HeInfinity** [comment]
> 问题描述不够清楚，你所说的“显示本地IP”和“显示落地IP”是什么意思，是执行什么命令查到的IP还是怎么回事。 还有passwall的大概配置也说一下。

大佬. 是这样的, 我的配置是中转+落地, 由于落地流量大 ip好, 中转可以免费换ip. 所以中转承担风险, 将所有流量全部中转到落地.
我通过ssh连接两台服务器后, 在ssh login in ip show时, 发现中转显示我的真实的ip, 但是其他服务器都能正常显示落地ip

我最开始怀疑是服务器配置有问题, 但是通过v2rayN的tun模式可以使用落地ip连接中转. 所以不是服务器配置问题
又怀疑是immortalwrt防火墙设置有问题, 在网上找到了关闭drop-wan-ssh的"解决方法", 但是我的immortalwrt没有这个选项.
最后我认为可能是passwall的设置出了问题, 所以将所有服务器的ip都添加到了passwall的代理规则中, 并且将tcp转发端口设置为<所有>

但是仍然无法解决, 所以, 有了这个issue.

**Comment by HeInfinity** [comment]
> 节点ip或域名会被添加到vpslist，vpslist表会走直连，这是保证你在路由器开启透明代理后依旧可以使用客户端直接连接vps，而不会被链式代理

大佬, 请问如果我想通过代理的方式连接中转, 我应该如何设置呢?

**Comment by wtfr-dot** [comment]
你的路径本来就是国内直连中转然后转发到落地ip，中转机显示你的国内ip不是很正常吗？如果你是防止国内探查你访问中转的真实IP你应该用cf之类的cdn

**Comment by HeInfinity** [comment]
> 你的路径本来就是国内直连中转然后转发到落地ip，中转机显示你的国内ip不是很正常吗？如果你是防止国内探查你访问中转的真实IP你应该用cf之类的cdn

感谢回复! 但是我还是没明白: 我已经落地了, 为什么不是从落地访问中转机, 而是直连的.

**Comment by wtfr-dot** [comment]
> > 你的路径本来就是国内直连中转然后转发到落地ip，中转机显示你的国内ip不是很正常吗？如果你是防止国内探查你访问中转的真实IP你应该用cf之类的cdn
> 
> 感谢回复! 但是我还是没明白: 我已经落地了, 为什么不是从落地访问中转机, 而是直连的.

落地是你的目的地，怎么可能是从落地访问中转，那是回程，回程是落地到中转再到国内，中转对于国内始终是直连

**Comment by HeInfinity** [comment]
> > > 你的路径本来就是国内直连中转然后转发到落地ip，中转机显示你的国内ip不是很正常吗？如果你是防止国内探查你访问中转的真实IP你应该用cf之类的cdn
> > 
> > 
> > 感谢回复! 但是我还是没明白: 我已经落地了, 为什么不是从落地访问中转机, 而是直连的.
> 
> 落地是你的目的地，怎么可能是从落地访问中转，那是回程，回程是落地到中转再到国内，中转对于国内始终是直连

有一点明白了, 我画了个图感觉通了. (但仅仅是感觉)
我最开始想的是: (ssh)电脑→(ssh)中转→(ssh)落地→(ssh)中转
理解后, 相当于是(ssh)电脑→(ssh)中转
如果我在中转设置透明代理是否可以得到方式一? 因为我想要的是方式一

**Comment by Blackcf** [comment]
你先学学计算机网络的相关知识

**Comment by HeInfinity** [comment]
> 你先学学计算机网络的相关知识

你倒不如先回答问题后，再来装。

**Comment by HeInfinity** [comment]
> 你先学学计算机网络的相关知识

你回答问题后，你再说教，我觉得都是合理的，欣然接受。你直接这么说，一显得你很无知，二显得你毫无教养。

**Comment by HeInfinity** [comment]
问题已解决，感谢上面前两位大佬的解答！

**Comment by HeInfinity** [comment]
> > 你先学学计算机网络的相关知识
> 
> 你回答问题后，你再说教，我觉得都是合理的，欣然接受。你直接这么说，一显得你很无知，二显得你毫无教养：两者结合便是无能。
