### ISSUE TITLE
希望不要删除自动切换

### ISSUE THREAD

**Issue by 2360153524** [xiaorouji/openwrt-package#3120]
### 描述你想要的新功能

希望作者大大能重新加入自动切换功能，真的很需要求求了

### 描述你想要的解决方案

增加功能

**Comment by gito10** [comment]
没删啊，在首页下面socks配置里面，你添加一个socks节点就知道了。

**Comment by hahach** [comment]
> 没删啊，在首页下面socks配置里面，你添加一个socks节点就知道了。

刚开始用passwall，借这个issue问一下，既然自动切换是用开一个socks代理实现的，为什么访问控制里选择节点的时候不能选这个socks节点呢。我希望访问控制的节点也是有自动切换功能的。

当然，按我的理解，在节点里创建一个socks节点应该能满足我的需求，但是感觉有点怪怪的。

试了下，确实上面的方式可以实现，但是在分流总结点里可以直接选socks节点。在访问控制里却不能选，会感觉逻辑上不统一。

**Comment by gito10** [comment]
> 刚开始用passwall，借这个issue问一下，既然自动切换是用开一个socks代理实现的，为什么访问控制里选择节点的时候不能选这个socks节点呢。我希望访问控制的节点也是有自动切换功能的。
> 
> 当然，按我的理解，在节点里创建一个socks节点应该能满足我的需求，但是感觉有点怪怪的。
> 
> 试了下，确实上面的方式可以实现，但是在分流总结点里可以直接选socks节点。在访问控制里却不能选，会感觉逻辑上不统一。

原本的Socks配置这个功能，就不是给passwall自己用的，在节点列表手动添加对应的socks节点都是没有意义的。是在支持了自动切换以后，passwall使用Socks节点才有了意义。不过之后有自动切换需求的，也都是自己新建socks节点配置的。

至于现在socks转发配置会自动在节点列表添加对应socks节点的功能，是在1个月以前才添加的，有些地方就没有考虑到，比如你说的访问控制里面，这个我等会看看好不好加。

**Comment by gito10** [comment]
刚刚在自己路由上试了一下，并不是自动生成节点，而是分流模式做了特殊处理，只在分流模式下可用的虚节点。即使首页的TCP/UDP节点选择里也没有。
最好还是手动添加吧。

不过也可以做个自动添加节点的功能。

**Comment by hahach** [comment]
> 刚刚在自己路由上试了一下，并不是自动生成节点，而是分流模式做了特殊处理，只在分流模式下可用的虚节点。即使首页的TCP/UDP节点选择里也没有。 最好还是手动添加吧。
> 
> 不过也可以做个自动添加节点的功能。

对，捋了下思路，socks功能相当于本地开了个inbound是socks的服务端，这个服务端的outbound就是socks节点里面配置的内容，自动切换是用脚本定时测连接性，不行就切换这个服务端的配置文件来实现的。
所以开启这个功能后，本地的服务端就开启了。（这玩意和界面里的服务器端是不一样的）

感觉这个虚节点可以不用创建到“节点列表”里，以防没搞明白的朋友编辑修改了端口，导致出什么差错。但是在有选择节点的地方，把它当做一个节点来看待，就像分流模式里面一样？当然，只是个建议哈，具体逻辑的选择，以开发者的思路为准
