### ISSUE TITLE
[Bug]: 过滤代理域名 IPv6 失效 （4.76-4）

### ISSUE THREAD

**Issue by MeissenSheep** [xiaorouji/openwrt-package#3123]
### 描述您遇到的bug

4.76-4版本下，更新组件版本到：ChinaDNS-NG 版本【 2024.04.13 】  Sing-Box 版本【 1.8.11 】  Xray 版本【 1.8.10 】  Hysteria 版本【 v2.4.1 】情况下，勾选过滤代理域名 IPv6这个功能会导致断网。

### 复现此Bug的步骤

更新组件版本到：ChinaDNS-NG 版本【 2024.04.13 】  Sing-Box 版本【 1.8.11 】  Xray 版本【 1.8.10 】  Hysteria 版本【 v2.4.1 】

### 您想要实现的目的

修复该功能

### 日志信息

无

### 系统相关信息

4.76-4 浏览器Edge 123.0.2420.81

### 其他信息

测试系统版本：官方OpenWRT、iStoreOS以及第三方编译版本

**Comment by lwb1978** [comment]
是否启用了ChinaDNS-NG？因2024.04.13版本ChinaDNS-NG的 “--no-ipv6 规则修改（与旧版规则不兼容），新规则分为两大类：tag:*、ip:*” ，在passwall适配新改动前启用ChinaDNS-NG会导致IPv6过滤失败，如果需要过滤代理域名IPv6建议关闭ChinaDNS-NG。
@xiaorouji

**Comment by nftbty** [comment]
复现步骤你的DNS设置是怎样的没说明，别人怎么照你的设置复现。
你可以每个模式以及ChinaDNS-NG 开/关组合都试一下，看哪些组合有问题。

**Comment by MeissenSheep** [comment]
> 是否启用了ChinaDNS-NG？因2024.04.13版本ChinaDNS-NG的 “--no-ipv6 规则修改（与旧版规则不兼容），新规则分为两大类：tag:_、ip:_” ，在passwall适配新改动前启用ChinaDNS-NG会导致IPv6过滤失败，如果需要过滤代理域名IPv6建议关闭ChinaDNS-NG。 @xiaorouji

现在确实是如此解决的，谢谢！

**Comment by lwb1978** [comment]
目前还没看到完整的ChinaDNS-NG说明，盲猜了一下新版命令，你如果有空可以测试一下，
[app.sh.txt](https://github.com/xiaorouji/openwrt-passwall/files/14993999/app.sh.txt)
把上面文件改名为app.sh替换/usr/share/passwall/app.sh后，重新启用ChinaDNS-NG看看能否过滤IPv6

**Comment by MeissenSheep** [comment]
> 目前还没看到完整的ChinaDNS-NG说明，盲猜了一下新版命令，你如果有空可以测试一下， [app.sh.txt](https://github.com/xiaorouji/openwrt-passwall/files/14993999/app.sh.txt) 把上面文件改名为app.sh替换/usr/share/passwall/app.sh后，重新启用ChinaDNS-NG看看能否过滤IPv6

ok，有空我试下，谢谢！

**Comment by lwb1978** [comment]
> > 目前还没看到完整的ChinaDNS-NG说明，盲猜了一下新版命令，你如果有空可以测试一下， [app.sh.txt](https://github.com/xiaorouji/openwrt-passwall/files/14993999/app.sh.txt) 把上面文件改名为app.sh替换/usr/share/passwall/app.sh后，重新启用ChinaDNS-NG看看能否过滤IPv6
> 
> ok，有空我试下，谢谢！

我回到家后也测试了，修改应该没有问题，勾选过滤代理域名 IPv6不再导致断网，并且可以正常过滤代理域名的ipv6。
