### ISSUE TITLE
希望加上netflix客户端规则 或者tun模式 目前除了电视客户端不走v6 手机电脑都没问题 很苦恼

### ISSUE THREAD

**Issue by ligx90** [xiaorouji/openwrt-package#3128]
### 描述你想要的新功能

客户端规则 或者tun模式 目前除了电视客户端不走v6 手机电脑都没问题 很苦恼

### 描述你想要的解决方案

客户端规则 或者tun模式 目前除了电视客户端不走v6 手机电脑都没问题 很苦恼

**Comment by gito10** [comment]
你需要代理Netflix，可以开非中国列表代理模式，或者使用GFWList模式的话，搜一下Netflix服务的域名列表，添加到代理列表，也就行了。
GitHub上应该有很多维护这些域名列表的repo。

**Comment by gito10** [comment]
还有你描述里提到**v6**，不清楚你大概什么配置，具体是要解决什么问题，你可以把这些描述清楚，别人才好帮你定位问题，给出建议，或者修复Bug。

**Comment by ligx90** [comment]
> 还有你描述里提到的**v6**，坟墓你大概什么配置，具体是要解决什么问题，你可以把这些描述说清楚，别人才好帮定位问题，给出建议，或者修复Bug。

我是绕过大陆模式 好像类似猫咪那种虚拟网卡走v6才能解锁netflix 手机电脑都没事 就lg电视webOS自带的客户端只能看自制剧
![WX20240418-114600@2x](https://github.com/xiaorouji/openwrt-passwall/assets/66711886/51746b53-7b59-4193-9d7b-d3be63cdc035)

**Comment by gito10** [comment]
你出口IPv4和出口IPv6是同一个节点的吗？

你这个情况，现在就是代理出口IP的v4地址只能看自制剧，v6不限制，但你的电视客户端走的IPv4。
你的问题就是要解决电视走节点IPv6地址访问 Netflix 服务。
你先查一查你的电视系统版本，搜一下是否支持IPv6协议栈。或者从路由器确定电视是否获取到IPv6地址。

- 如果电视支持IPv6，那就是电视客户端主动选择了IPv4地址，这个看是不是客户端软件版本的问题或者设置之类的问题，这个我不了解。解决办法的话，大概就是屏蔽Netflix域名的IPv4地址，只返回IPv6地址，让客户端只能使用IPv6地址访问；

- 如果电视不支持IPv6，就只能走IPv4代理，直接请求域名，让代理节点去请求DNS，然后使用IPv6地址访问。实现方式如果客户端支持设置显式代理（Socks5/HTTP），可以把代理设为passwall开放的socks端口；不支持显示代理的话，就只能使用 FakeIP，或者开启Xray的 **流量嗅探**，关闭**流量嗅探只供路由使用**，或者开启Sing-Box的 **覆盖连接目标地址**。这样最终发往代理节点的请求就是域名而不是IP，如果代理节点是双栈的，并且目标服务器支持IPv6的话，通常代理节点都会使用IPv6地址来请求服务。这个我是亲测过，IPv4连接的HK代理节点，走代理检测IP地址，显示为HK的IPv6地址。

**Comment by ligx90** [comment]
我也不知道了有点复杂我听不懂了😄 lg电视真头疼
<img width="947" alt="QQ20240419-112108@2x" src="https://github.com/xiaorouji/openwrt-passwall/assets/66711886/7bc71161-a63b-421b-8d30-d92909ab3c8c">
<img width="1057" alt="QQ20240419-112144@2x" src="https://github.com/xiaorouji/openwrt-passwall/assets/66711886/b63d2700-c4b4-4b2b-a891-81baf5684e30">

**Comment by gito10** [comment]
看你电视是有IPv6地址的，
电视有浏览器吗，访问 https://ipv6-test.com 或 https://test-ipv6.com 看能不能正常访问IPv6服务。

或者简单点，不管支不支持IPv6，你都可以把节点类型切换为sing-box，dns使用sing-box，开启FakeDNS。再用电视试试。
或者不用FakeDNS的话，高级设置里xray或sing-box确保以下设置跟图中一样试试。
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/8d9e274a-3b64-4291-8cb5-51edc95e6eaf)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10704839/67905bbb-1e83-4e25-98d9-3469898ffc3a)

**Comment by ligx90** [comment]
请问必须是sing-box模式才可以吗？我用的x-ui默认的xray一个内核
![Uploading QQ20240419-145100@2x.png…]()

**Comment by ligx90** [comment]
我知道了 是我v6解锁掉了😄 好垃圾的鸡，我放弃了 买只解锁机算了
