### ISSUE TITLE
[Bug]: 访问控制列表 不支持IPV6

### ISSUE THREAD

**Issue by Diffused7245** [xiaorouji/openwrt-package#3129]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall/assets/76898556/98ee72ce-4fc1-4f04-a866-887bca3403d1)

### 复现此Bug的步骤

访问控制随便添加一个IPV6地址段就会报错，最后显示保存了但实际上也不生效

### 您想要实现的目的

特定源IPV6不走代理，不过如果是同一台机器，IPV4走，IPV6不走。
按照MAC地址判断时，则这个MAC地址对应机器的V4和V6都不走。

### 日志信息

没有

### 系统相关信息

Passwall 版本【 4.75-3 】  ChinaDNS-NG 版本【 2023.10.28 】  Sing-Box 版本【 1.8.6 】  Xray 版本【 1.8.8 】  Hysteria 版本【 无 】 
openwrt版本是immortalwrt SNAPSHOT

**Comment by lwb1978** [comment]
就我理解来说，ipv6本身很复杂，你电脑获取的是公网ipv6的话本身都不经过路由nat，代理就更加不可能了。如果你电脑要经过路由nat ipv6的话就只能是内网的v6，那开启ipv6就没任何意义了。另外PW是将各种代理插件进行整合提供可视化的设置，要实现ipv6代理的话先要各种如：xray sing-box tp等等核心支持v6 nat才行，这并不是PW的bug

**Comment by lwb1978** [comment]
打个比方，如果你电脑获取的是公网的ipv6，你关掉你电脑的ipv4，这时你访问国外网站的流量是不会经过代理而是直连过去的。这样就很好理解为什么源地址不能填写ipv6地址了，因为不支持6 to 6代理。

**Comment by handsomeji** [comment]
`就我理解来说，ipv6本身很复杂，你电脑获取的是公网ipv6的话本身都不经过路由nat，代理就更加不可能了。`
其實是可以的。不過我目前沒有使用IPv6，無法做詳細的測試。

**Comment by handsomeji** [comment]
@qweasdbnm24 
請貼上日誌，不要覺得沒有用。這能直接定位知道你用的什麼版本和依賴。

**Comment by gito10** [comment]
但是还有个问题，一般家宽的IPv6都是动态前缀，随时会变，要进行源地址检测的话，只能进行后缀匹配，设备就需要稳定的IPv6地址后缀，最好是 EUI64 或者 DHCPv6 静态分配。像Windows 一般使用的是隐私地址，虽然也是相对稳定的。
但每个设备都有多个IPv6地址，DHCPv6分配的不说，SLAAC 生成的就有好几个。尤其是Windows（其它系统不了解），会生成很多临时地址，在传出连接时一般都是用的临时地址，这样还真不好进行源地址匹配。

**Comment by handsomeji** [comment]
對於IPv6，源地址最好是使用DUID或MAC匹配。

**Comment by woni928** [comment]
我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！

**Comment by ZqinKing** [comment]
> 我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！

使用smartdns进行分组，国外组关闭IPv6。这样不会影响国内的IPTV（大部分都是IPv6源）。

**Comment by lwb1978** [comment]
> > 我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！
> 
> 使用smartdns进行分组，国外组关闭IPv6。这样不会影响国内的IPTV（大部分都是IPv6源）。
如果是使用smartdns的话，直接编译passwall-smartdns分支搭配smartdns使用效果是最完美的。

**Comment by ZqinKing** [comment]
> 打个比方，如果你电脑获取的是公网的ipv6，你关掉你电脑的ipv4，这时你访问国外网站的流量是不会经过代理而是直连过去的。这样就很好理解为什么源地址不能填写ipv6地址了，因为不支持6 to 6代理。

IPv6代理从工具层面都是支持的。像xray之类都可以支持。IPv6的难点在于公网进来后不能像IPv4一样通过DHCP或者其他手段指定网关。当然如果passwall所在的设备本身就是拨号设备的话那就没这个问题了。

**Comment by ZqinKing** [comment]
> > > 我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！
> > 
> > 
> > 使用smartdns进行分组，国外组关闭IPv6。这样不会影响国内的IPTV（大部分都是IPv6源）。
> > 如果是使用smartdns的话，直接编译passwall-smartdns分支搭配smartdns使用效果是最完美的。

其实最完美的还需要搭配mosdns，进行dns防泄漏。DNS可以套娃，smartdns+adg+mosdns。配置合理的话用起来很舒服。配的不好查问题比较烦。

**Comment by lwb1978** [comment]
> > > > 我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！
> > > 
> > > 
> > > 使用smartdns进行分组，国外组关闭IPv6。这样不会影响国内的IPTV（大部分都是IPv6源）。
> > > 如果是使用smartdns的话，直接编译passwall-smartdns分支搭配smartdns使用效果是最完美的。
> 
> 其实最完美的还需要搭配mosdns，进行dns防泄漏。DNS可以套娃，smartdns+adg+mosdns。配置合理的话用起来很舒服。配的不好查问题比较烦。

确实只是用smartdns的话是会dns泄漏的，但是smartdns+adg+mosdns这套组合下来有点复杂，也会影响一点dns查询速度吧（虽然可能肉眼无法感知）。

**Comment by woni928** [comment]
> > > > 我是联通的公网IPv6。只要一打开，奈飞就打不开，nds就会泄漏。目前没有找到解决方法！
> > > 
> > > 
> > > 使用smartdns进行分组，国外组关闭IPv6。这样不会影响国内的IPTV（大部分都是IPv6源）。
> > > 如果是使用smartdns的话，直接编译passwall-smartdns分支搭配smartdns使用效果是最完美的。
> 
> 其实最完美的还需要搭配mosdns，进行dns防泄漏。DNS可以套娃，smartdns+adg+mosdns。配置合理的话用起来很舒服。配的不好查问题比较烦。

passwall搭配了mosdns  pc端无泄露可以正常奈飞，但是手机却依然dns泄露，奈飞也打不开。不知道什么原因！

**Comment by handsomeji** [comment]
經測試，訪問控制使用 MAC 可以 IPv4+IPv6 沒有問題。
請更新到最新版本再做測試反饋。

**Comment by woni928** [comment]
> 經測試，訪問控制使用 MAC 可以 IPv4+IPv6 沒有問題。 請更新到最新版本再做測試反饋。

必须用访问控制才能实现？如果终端很多的话，岂不是每台都要设置？

**Comment by mirthlesslk** [comment]
passwall的访问控制只有这一点觉得麻烦，每一个设备都要输入mac，不如限定ip方便

**Comment by handsomeji** [comment]
本來打算給源地址加入IPv6地址的匹配，但是想了一下好像又沒必要。就算加上也只能匹配IPv6的流量。不如直接用MAC匹配。
MAC 匹配是可以直接同時支持IPv4+IPv6的。
另外，如果需要代理IPv6 IP流量，請務必打開高級設置 - IPv6透明代理。
