### ISSUE TITLE
官方的main无法正常打开

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#3130]
### 描述您遇到的bug

官方的main无法正常打开

### 复现此Bug的步骤

如果没有选择开机启动的话，就无法打开

### 您想要实现的目的

可以正常开关

### 日志信息

按了保存应用感觉没有按一样

### 系统相关信息

4.76-5

**Comment by xcyll** [comment]
昨天编译了最新的 openwrt（master分支）
passwall的确不能进行 保存应用 操作了（即 **保存应用** 失效 ）由于不能启动所以没有日志信息

**Comment by xcyll** [comment]
但此时再操作下更新节点订阅 
之前保存的应用 就生效了 日志也跑起来了

**Comment by hahach** [comment]
我在lede里直接编译的4月12日的版本，也有这个问题，只有重置ipset配置，才能应用新设置。
因为当时是第一次用passwall，我以为是特色（
但是前天出新release了，直接下载覆盖安装，就没有这个问题了。

**Comment by xcyll** [comment]
应该是与最近op官方luci-base的改动有关

**Comment by xcyll** [comment]
**保存应用** 失效
与最近OP官方luci-base的改动有关

**Comment by King-Of-Knights** [comment]
@xcyll 研究了半天，感谢大佬，luci回退到2月10号的版本解决了问题

**Comment by handsomeji** [comment]
沒有使用main branch，坐等PR。。

**Comment by SakuraFallingMad** [comment]
我在用main branch，但是每次修改配置都是先保存，然后点击pedding change那里再应用，所以。。。没发现保存应用这玩意儿是坏的。。

**Comment by ShanStone** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60

**Comment by xh0823** [comment]
> [40751a4](https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60)

感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用

**Comment by ShanStone** [comment]
> > [40751a4](https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60)
> 
> 感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用

这个应该是正常的吧

**Comment by xcyll** [comment]
> > 感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用
> 
> 这个应该是正常的吧

他的意思应该是改版之前在高级设置 下的 **保存** 等效于 **保存应用** 效果（高级设置下没**保存应用**选项 只有**保存**选项）
![2024-04-21 121401](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/1262c007-50e2-4942-93e0-fbc01d7fd0ec)
改动后的新版 高级设置下的 **保存** 仅代表 修改配置 
![12024-04-21 121544](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/b63b68f4-740d-41be-ac77-180dcd9bfb31)

**Comment by xcyll** [comment]
> > > [40751a4](https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60)
> > 
> > 
> > 感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用
> 
> 这个应该是正常的吧
他的意思应该是改版之前在高级设置 下的 **保存** 等效于 **保存应用** 效果（高级设置下没**保存应用**选项 只有**保存**选项）
![2024-04-21 121401](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/1262c007-50e2-4942-93e0-fbc01d7fd0ec)
改动后的新版 高级设置下的 **保存** 仅代表 修改配置 
![12024-04-21 121544](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/b63b68f4-740d-41be-ac77-180dcd9bfb31)

**Comment by SakuraFallingMad** [comment]
> > > > [40751a4](https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60)
> > > 
> > > 
> > > 感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用
> > 
> > 
> > 这个应该是正常的吧
> > 他的意思应该是改版之前在高级设置 下的 **保存** 等效于 **保存应用** 效果（高级设置下没**保存应用**选项 只有**保存**选项）
> > ![2024-04-21 121401](https://private-user-images.githubusercontent.com/63227888/324222757-1262c007-50e2-4942-93e0-fbc01d7fd0ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzQwMzYsIm5iZiI6MTcxMzY3MzczNiwicGF0aCI6Ii82MzIyNzg4OC8zMjQyMjI3NTctMTI2MmMwMDctNTBlMi00OTQyLTkzZTAtZmJjMDFkN2ZkMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZDM0OTZiM2Q2OWJlNzNlYzU1YjhkZGRkNDEyMzZlMzhmYzE4NmMxNzM5ZGIzODdlZTRhZDQyM2ZlYjA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.30TzuGAiw3PcTMi3Qcwb3RRsG9oDxyXnZjfM2oQaHew)
> > 改动后的新版 高级设置下的 **保存** 仅代表 修改配置
> > ![12024-04-21 121544](https://private-user-images.githubusercontent.com/63227888/324222814-b63b68f4-740d-41be-ac77-180dcd9bfb31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzQwMzYsIm5iZiI6MTcxMzY3MzczNiwicGF0aCI6Ii82MzIyNzg4OC8zMjQyMjI4MTQtYjYzYjY4ZjQtNzQwZC00MWJlLWFjNzctMTgwZGNkOWJmYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDM4MWE4YjdiNGNlZWY5YzZiNDU5M2Y5M2RhMmQxYmE0NWRlYzk5MzUwMTA4ZjdjOTE3ODY0M2Q3YmIwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fXmlRBBmiqUyXoWlBoZmh-zP1bBCIyY3keiLCCS-ELc)

或许是指的是这个吧
![image](https://github.com/xiaorouji/openwrt-passwall/assets/31793080/d12c21a6-0e67-4e71-8520-8cf78d093739)
在高级设置只要打开了ipv6的tproxy选项，在里面无论调整什么设置或者不调整直接点击应用，都会出现重复设置改设置的pedding change

就是看着比较麻烦，但是没有对任何设置作改动。

**Comment by xh0823** [comment]
感谢各位大佬了，但是不影响使用

**Comment by xcyll** [comment]
> @xcyll 研究了半天，感谢大佬，luci回退到2月10号的版本解决了问题

  山石兄已对官方luci作了兼容处理 更新最新代码试试

**Comment by xh0823** [comment]
> > > > > [40751a4](https://github.com/xiaorouji/openwrt-passwall/commit/40751a447bd352644b88cc1ba5dd01b618f51d60)
> > > > 
> > > > 
> > > > 感谢几位大佬，可以正常使用了，但是高级设置里面保存了后出来《未保存的配置: 2》在按保存应用就可以应用
> > > 
> > > 
> > > 这个应该是正常的吧
> > > 他的意思应该是改版之前在高级设置 下的 **保存** 等效于 **保存应用** 效果（高级设置下没**保存应用**选项 只有**保存**选项）
> > > ![2024-04-21 121401](https://private-user-images.githubusercontent.com/63227888/324222757-1262c007-50e2-4942-93e0-fbc01d7fd0ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzQwMzYsIm5iZiI6MTcxMzY3MzczNiwicGF0aCI6Ii82MzIyNzg4OC8zMjQyMjI3NTctMTI2MmMwMDctNTBlMi00OTQyLTkzZTAtZmJjMDFkN2ZkMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZDM0OTZiM2Q2OWJlNzNlYzU1YjhkZGRkNDEyMzZlMzhmYzE4NmMxNzM5ZGIzODdlZTRhZDQyM2ZlYjA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.30TzuGAiw3PcTMi3Qcwb3RRsG9oDxyXnZjfM2oQaHew)
> > > 改动后的新版 高级设置下的 **保存** 仅代表 修改配置
> > > ![12024-04-21 121544](https://private-user-images.githubusercontent.com/63227888/324222814-b63b68f4-740d-41be-ac77-180dcd9bfb31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzQwMzYsIm5iZiI6MTcxMzY3MzczNiwicGF0aCI6Ii82MzIyNzg4OC8zMjQyMjI4MTQtYjYzYjY4ZjQtNzQwZC00MWJlLWFjNzctMTgwZGNkOWJmYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDM4MWE4YjdiNGNlZWY5YzZiNDU5M2Y5M2RhMmQxYmE0NWRlYzk5MzUwMTA4ZjdjOTE3ODY0M2Q3YmIwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fXmlRBBmiqUyXoWlBoZmh-zP1bBCIyY3keiLCCS-ELc)
> 
> 或许是指的是这个吧 ![image](https://private-user-images.githubusercontent.com/31793080/324223285-d12c21a6-0e67-4e71-8520-8cf78d093739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTkwMDQsIm5iZiI6MTcxMzY5ODcwNCwicGF0aCI6Ii8zMTc5MzA4MC8zMjQyMjMyODUtZDEyYzIxYTYtMGU2Ny00ZTcxLTg1MjAtOGNmNzhkMDkzNzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDExMjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NGQ5NDRjMjNjNmI0MmYwZjUyZTVkZjlmNGRkMGU5OTg4YmI5MmFjYTRlN2U0ZDU1NDFkY2ZjYmUyYTA1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WLrRCyoHUstd59htzvsnp2OzHwti_hPFNUTs9ypibp8) 在高级设置只要打开了ipv6的tproxy选项，在里面无论调整什么设置或者不调整直接点击应用，都会出现重复设置改设置的pedding change
> 
> 就是看着比较麻烦，但是没有对任何设置作改动。

说的是这个

**Comment by xcyll** [comment]
漏了一处适配 负载均衡管理界面打不开  
socks5--【127.0.0.1#1181: Connection refused】
 @ShanStone 大佬有空看下 （OP/LUCI-官方的锅）
![①024-04-22 000231](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/80c1961a-848a-4af9-bd18-4673ca79b6a0)
![②2024-04-21 222003](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/08376479-1fcf-454f-8aef-1457afdaf707)
### 日志信息
```
[1;32m2024-04-21 23:12:09 INF:[0m [main] server address: 127.0.0.1#1181
[1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: ::1#1041
[1;32m2024-04-21 23:12:09 INF:[0m [main] udp cache maximum size: 256
[1;32m2024-04-21 23:12:09 INF:[0m [main] udp socket idle timeout: 60
[1;32m2024-04-21 23:12:09 INF:[0m [main] number of worker threads: 1
[1;32m2024-04-21 23:12:09 INF:[0m [main] enable tcp transparent proxy
[1;32m2024-04-21 23:12:09 INF:[0m [main] verbose mode (affect performance)
------省略------
[1;32m2024-04-21 23:12:28 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#1181 ...
[1;35m2024-04-21 23:12:28 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#1181: Connection refused
```

**Comment by xcyll** [comment]
漏了一处适配 **负载均衡**登陆界面打不开  
@ShanStone @xiaorouji 
大佬有空看下 
![①024-04-22 000231](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/ab5aff99-5076-400f-907c-53b019bceefb)
![②2024-04-21 222003](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/53eeab11-3cd9-44c5-be7c-90b393d0c30e)
### 日志信息
```
[1;32m2024-04-21 23:12:09 INF:[0m [main] server address: 127.0.0.1#1181
[1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: ::1#1041
[1;32m2024-04-21 23:12:09 INF:[0m [main] udp cache maximum size: 256
[1;32m2024-04-21 23:12:09 INF:[0m [main] udp socket idle timeout: 60
[1;32m2024-04-21 23:12:09 INF:[0m [main] number of worker threads: 1
[1;32m2024-04-21 23:12:09 INF:[0m [main] enable tcp transparent proxy
[1;32m2024-04-21 23:12:09 INF:[0m [main] verbose mode (affect performance)
------省略------
[1;32m2024-04-21 23:12:28 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#1181 ...
[1;35m2024-04-21 23:12:28 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#1181: Connection refused
```

**Comment by ShanStone** [comment]
> 漏了一处适配 **负载均衡**登陆界面打不开  
> @ShanStone @xiaorouji 
> 大佬有空看下 
> ![①024-04-22 000231](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/ab5aff99-5076-400f-907c-53b019bceefb)
> ![②2024-04-21 222003](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/53eeab11-3cd9-44c5-be7c-90b393d0c30e)
> ### 日志信息
> ```
> [1;32m2024-04-21 23:12:09 INF:[0m [main] server address: 127.0.0.1#1181
> [1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: 0.0.0.0#1041
> [1;32m2024-04-21 23:12:09 INF:[0m [main] listen address: ::1#1041
> [1;32m2024-04-21 23:12:09 INF:[0m [main] udp cache maximum size: 256
> [1;32m2024-04-21 23:12:09 INF:[0m [main] udp socket idle timeout: 60
> [1;32m2024-04-21 23:12:09 INF:[0m [main] number of worker threads: 1
> [1;32m2024-04-21 23:12:09 INF:[0m [main] enable tcp transparent proxy
> [1;32m2024-04-21 23:12:09 INF:[0m [main] verbose mode (affect performance)
> ------省略------
> [1;32m2024-04-21 23:12:28 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#1181 ...
> [1;35m2024-04-21 23:12:28 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#1181: Connection refused
> ```

haproxy通过app.sh直接调用的，如果psw有日志，haproxy也应该会运行的，看一下有什么错误日志么
这个功能我没用过，不太熟悉

**Comment by xcyll** [comment]
刚刷入OP最新构建 HAPROXY正常使用 @ShanStone
