### ISSUE TITLE
有三个建议

### ISSUE THREAD

**Issue by bncolin** [xiaorouji/openwrt-package#3131]
### 描述你想要的新功能

1，希望能够把自动切换节点选项加回来，这样应该会比较直观
2，作者能否加上更新日志，这样可以根据自己情况是否更新
3，如果github上能放上wiki说明文档就太好了，有不明白的也不用到处问了，翻文档就好了

### 描述你想要的解决方案

只是个人的一点建议

### 描述你考虑过的替代方案

无

**Comment by bcseputetto** [comment]
1、自动切换功能没有删，只是改到Socks配置里面实现了
2、想看更新内容可以看 commit

**Comment by bcseputetto** [comment]
关于自动切换
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/0340336d-8f84-44a8-9c0f-13ec9d9baede)
在Socks配置里，配置好节点和自动切换的节点，可以看到 Socks监听1081，你只需要在主要那边使用这个Socks1081就行了
这样的好处是，自动切换比以前更灵活，以前自动切换是直接切主节点或者前置节点，现在你可以设置多组Socks配置，来使用自动切换。
比如设置 香港组，台湾组，日本组，美国组，然后在各组里面添加各个国家/地区的节点。然后在主要那里使用，可以直接作为主节点，也可以在分流里面使用。
新的自动切换，明显比以前要更好

**Comment by 91Metis** [comment]
> 关于自动切换 ![image](https://private-user-images.githubusercontent.com/29139573/323941660-0340336d-8f84-44a8-9c0f-13ec9d9baede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MjY5NjMsIm5iZiI6MTcxMzUyNjY2MywicGF0aCI6Ii8yOTEzOTU3My8zMjM5NDE2NjAtMDM0MDMzNmQtOGY4NC00NGE4LTljMGYtMTNlYzlkOWJhZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDExMzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMDJhOWNhMDYzYTVkMWUwMzRlNzI2MWM1ZDA3NjRlZjFlNTIzNjQyOGJkMzk3YWQwYjVjNTA4YTJjM2UyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nxS2-wC7G-Qla6LFMhud603syPHkI0MM97mmafQuA1Y) 在Socks配置里，配置好节点和自动切换的节点，可以看到 Socks监听1081，你只需要在主要那边使用这个Socks1081就行了 这样的好处是，自动切换比以前更灵活，以前自动切换是直接切主节点或者前置节点，现在你可以设置多组Socks配置，来使用自动切换。 比如设置 香港组，台湾组，日本组，美国组，然后在各组里面添加各个国家/地区的节点。然后在主要那里使用，可以直接作为主节点，也可以在分流里面使用。 新的自动切换，明显比以前要更好

可是socks的话不是不加密嘛？

**Comment by bcseputetto** [comment]
@91Metis 只是局域网内使用为什么要加密？

**Comment by 91Metis** [comment]
> @91Metis 只是局域网内使用为什么要加密？

啊  学习了  谢谢！

**Comment by bcseputetto** [comment]
@91Metis 不知道你误会了什么，如果你需要在公网使用Socks，可以用passwall，服务端那边的选项，那边提供带身份验证的Socks，并且自动帮你修改防火墙设置，供你在公网使用，但注意安全

**Comment by 91Metis** [comment]
> @91Metis 不知道你误会了什么，如果你需要在公网使用Socks，可以用passwall，服务端那边的选项，那边提供带身份验证的Socks，并且自动帮你修改防火墙设置，供你在公网使用，但注意安全

我以为开启Socks以后是直接用Socks连外网- -  看来不是

**Comment by bcseputetto** [comment]
> 我以为开启Socks以后是直接用Socks连外网- - 看来不是

@91Metis Socks配置里面一样是要选节点的，所以实际还是用节点，只不过它是相当于把节点转换成了Socks，供你使用

**Comment by lwb1978** [comment]
> > 我以为开启Socks以后是直接用Socks连外网- - 看来不是
> 
> @91Metis Socks配置里面一样是要选节点的，所以实际还是用节点，只不过它是相当于把节点转换成了Socks，供你使用

你可以把它看成菜鸟驿站，用什么快递（翻墙协议）发，收件人是谁（提供分流或者是直接代理），他不管，它只负责中转和切换。

**Comment by 91Metis** [comment]
> > 我以为开启Socks以后是直接用Socks连外网- - 看来不是
> 
> @91Metis Socks配置里面一样是要选节点的，所以实际还是用节点，只不过它是相当于把节点转换成了Socks，供你使用

明白了  谢谢！

**Comment by bcseputetto** [comment]
【主要】TCP节点：Socks 127.0.0.1:1081
【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4
像这样直接在主要的TCP节点使用
_____
也可以像下面这样在分流里使用
【主要】TCP节点：Xray分流[默认：Socks 127.0.0.1:1081；分流规则A：Socks 127.0.0.1:1082；分流规则B：Socks 127.0.0.1:1083]
【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4
【Socks配置】台湾组 监听1082 节点：台湾1，自动切换：台湾2、台湾3、台湾4
【Socks配置】日本组 监听1083 节点：日本1，自动切换：日本2、日本3、日本4
_____
这要和以前的自动切换只能切主节点和前置节点相比来说要灵活的多
已经解释的很通俗易懂了，希望大家都能懂

**Comment by 91Metis** [comment]
> > > 我以为开启Socks以后是直接用Socks连外网- - 看来不是
> > 
> > 
> > @91Metis Socks配置里面一样是要选节点的，所以实际还是用节点，只不过它是相当于把节点转换成了Socks，供你使用
> 
> 你可以把它看成菜鸟驿站，用什么快递（翻墙协议）发，收件人是谁（提供分流或者是直接代理），他不管，它只负责中转和切换。

嗯嗯   - -结合另一个大佬的解答  一下子明白了

**Comment by 91Metis** [comment]
> 【主要】TCP节点：Socks 127.0.0.1:1081 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 像这样直接在主要的TCP节点使用
> 
> 也可以像下面这样在分流里使用 【主要】TCP节点：Xray分流[默认：Socks 127.0.0.1:1081；分流规则A：Socks 127.0.0.1:1082；分流规则B：Socks 127.0.0.1:1083] 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 【Socks配置】台湾组 监听1082 节点：台湾1，自动切换：台湾2、台湾3、台湾4 【Socks配置】日本组 监听1083 节点：日本1，自动切换：日本2、日本3、日本4
> 
> 这要和以前的自动切换只能切主节点和前置节点相比来说要灵活的多 已经解释的很通俗易懂了，希望大家都能懂

大佬，我按照上面的图片设置了一下。但是开启以后无法连接google，但是通过点击passwall里的谷歌连接和Github连接按钮却显示正常，这个是哪里出问题了呀？可以帮我看看么。
![屏幕截图 2024-04-19 201724](https://github.com/xiaorouji/openwrt-passwall/assets/63533710/807e268a-39fd-45a2-b847-f289e15d703c)
![屏幕截图 2024-04-19 201914](https://github.com/xiaorouji/openwrt-passwall/assets/63533710/8497a823-0d25-4065-97dd-a11402bd5385)
![屏幕截图 2024-04-19 202306](https://github.com/xiaorouji/openwrt-passwall/assets/63533710/c00c5982-95a3-4687-839d-1b8beed7a276)

**Comment by lwb1978** [comment]
> ### 描述你想要的新功能
> 1，希望能够把自动切换节点选项加回来，这样应该会比较直观 2，作者能否加上更新日志，这样可以根据自己情况是否更新 3，如果github上能放上wiki说明文档就太好了，有不明白的也不用到处问了，翻文档就好了
> 
> ### 描述你想要的解决方案
> 只是个人的一点建议
> 
> ### 描述你考虑过的替代方案
> 无
> 
> ### 其他信息
> _No response_

针对第二第三点我谈谈我的看法，去年大名鼎鼎的小猫咪删库跑路事件应该大家都有耳闻，你好世界也在长时间不更新后删库了，现在就剩下酸酸乳不拉屎和pw在坚持，pw的issues也才在风头过后刚刚开放不久，虽然pw是什么app懂得都懂，但也不能把类似说明什么的刻在额头上当显眼包，容易被查水表。我也借贴感谢小肉鸡等一众大佬的无私奉献。

**Comment by bcseputetto** [comment]
@91Metis 你的主要设置错了，没让你把主要的 Socks监听端口改成1081，你两个端口设一样干什么

**Comment by bcseputetto** [comment]
@91Metis 如果你不是用分流，那么你应该去节点列表，添加一个新的Socks节点，然后地址是 127.0.0.1，端口是1081，然后在 主要，TCP节点使用它

**Comment by lwb1978** [comment]
> > 【主要】TCP节点：Socks 127.0.0.1:1081 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 像这样直接在主要的TCP节点使用
> > 也可以像下面这样在分流里使用 【主要】TCP节点：Xray分流[默认：Socks 127.0.0.1:1081；分流规则A：Socks 127.0.0.1:1082；分流规则B：Socks 127.0.0.1:1083] 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 【Socks配置】台湾组 监听1082 节点：台湾1，自动切换：台湾2、台湾3、台湾4 【Socks配置】日本组 监听1083 节点：日本1，自动切换：日本2、日本3、日本4
> > 这要和以前的自动切换只能切主节点和前置节点相比来说要灵活的多 已经解释的很通俗易懂了，希望大家都能懂
> 
> 大佬，我按照上面的图片设置了一下。但是开启以后无法连接google，但是通过点击passwall里的谷歌连接和Github连接按钮却显示正常，这个是哪里出问题了呀？可以帮我看看么。 ![屏幕截图 2024-04-19 201724](https://private-user-images.githubusercontent.com/63533710/323955145-807e268a-39fd-45a2-b847-f289e15d703c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxNDUtODA3ZTI2OGEtMzlmZC00NWEyLWI4NDctZjI4OWUxNWQ3MDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZTc3ZmI5YzU3ZjQ0MjI4ZDE2ZmNiMTBmNzkxZjIyODNkZjk2ODc4YTRjNzk4Y2E1MWM0ZDU0OTk4MThlYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZHHPNFL0_6jezej2OTf6urpU-LtFKnEdJUqjk6YoZM) ![屏幕截图 2024-04-19 201914](https://private-user-images.githubusercontent.com/63533710/323955168-8497a823-0d25-4065-97dd-a11402bd5385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxNjgtODQ5N2E4MjMtMGQyNS00MDY1LTk3ZGQtYTExNDAyYmQ1Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTk1OGIwMzZhNjQyYmQ3NTQzYTQwNTNhMTNjNjdkZTU3MGVjYmEwNDcxZDAzNjY1OTM0ZWNmYzY5Y2RjYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CR7APCrMIrO5M-8bGJYjYd0XfVR6ooGUxL2pW3T5Crc) ![屏幕截图 2024-04-19 202306](https://private-user-images.githubusercontent.com/63533710/323955180-c00c5982-95a3-4687-839d-1b8beed7a276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxODAtYzAwYzU5ODItOTVhMy00Njg3LTgzOWQtMWI4YmVlZDdhMjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YTg2OTI2N2I0NTI3ZmUyZTFhNGRmYTBkMWQ2YWZkNDBhNDIwZTFjOGQ2MzBhZWZkNjA4MTFjNjQ3MjA1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ekpa-IhdJeFsc6gx2pBVS50-Oen09aucjabrC_wyCSA)

TCP 节点 Socks 监听端口你不要改成1081啊，冲突了，保持默认的1070

**Comment by bcseputetto** [comment]
@lwb1978 话说起来，当前源码的 chinadns-ng 过滤代理域名IPv6打勾后，好像没有正常向 chinadns-ng的配置里面写 代理组的 `no-ipv6`
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/4d25bb7d-877b-4776-b5f2-093c08c804cd)

**Comment by 91Metis** [comment]
> @91Metis 如果你不是用分流，那么你应该去节点列表，添加一个新的Socks节点，然后地址是 127.0.0.1，端口是1081，然后在 主要，TCP节点使用它

好像可以了~0 0我太菜了

**Comment by 91Metis** [comment]
> @91Metis 如果你不是用分流，那么你应该去节点列表，添加一个新的Socks节点，然后地址是 127.0.0.1，端口是1081，然后在 主要，TCP节点使用它

![1](https://github.com/xiaorouji/openwrt-passwall/assets/63533710/2a9384e7-a22a-4504-adb5-f7c4b62ca4ed)
![2](https://github.com/xiaorouji/openwrt-passwall/assets/63533710/e2d39c68-391c-432c-8b78-9a8cba3f5cc8)
大佬是这样嘛？

**Comment by 91Metis** [comment]
> > > 【主要】TCP节点：Socks 127.0.0.1:1081 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 像这样直接在主要的TCP节点使用
> > > 也可以像下面这样在分流里使用 【主要】TCP节点：Xray分流[默认：Socks 127.0.0.1:1081；分流规则A：Socks 127.0.0.1:1082；分流规则B：Socks 127.0.0.1:1083] 【Socks配置】香港组 监听1081 节点：香港1，自动切换：香港2、香港3、香港4 【Socks配置】台湾组 监听1082 节点：台湾1，自动切换：台湾2、台湾3、台湾4 【Socks配置】日本组 监听1083 节点：日本1，自动切换：日本2、日本3、日本4
> > > 这要和以前的自动切换只能切主节点和前置节点相比来说要灵活的多 已经解释的很通俗易懂了，希望大家都能懂
> > 
> > 
> > 大佬，我按照上面的图片设置了一下。但是开启以后无法连接google，但是通过点击passwall里的谷歌连接和Github连接按钮却显示正常，这个是哪里出问题了呀？可以帮我看看么。 ![屏幕截图 2024-04-19 201724](https://private-user-images.githubusercontent.com/63533710/323955145-807e268a-39fd-45a2-b847-f289e15d703c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxNDUtODA3ZTI2OGEtMzlmZC00NWEyLWI4NDctZjI4OWUxNWQ3MDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZTc3ZmI5YzU3ZjQ0MjI4ZDE2ZmNiMTBmNzkxZjIyODNkZjk2ODc4YTRjNzk4Y2E1MWM0ZDU0OTk4MThlYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZHHPNFL0_6jezej2OTf6urpU-LtFKnEdJUqjk6YoZM) ![屏幕截图 2024-04-19 201914](https://private-user-images.githubusercontent.com/63533710/323955168-8497a823-0d25-4065-97dd-a11402bd5385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxNjgtODQ5N2E4MjMtMGQyNS00MDY1LTk3ZGQtYTExNDAyYmQ1Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTk1OGIwMzZhNjQyYmQ3NTQzYTQwNTNhMTNjNjdkZTU3MGVjYmEwNDcxZDAzNjY1OTM0ZWNmYzY5Y2RjYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CR7APCrMIrO5M-8bGJYjYd0XfVR6ooGUxL2pW3T5Crc) ![屏幕截图 2024-04-19 202306](https://private-user-images.githubusercontent.com/63533710/323955180-c00c5982-95a3-4687-839d-1b8beed7a276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzAxMTEsIm5iZiI6MTcxMzUyOTgxMSwicGF0aCI6Ii82MzUzMzcxMC8zMjM5NTUxODAtYzAwYzU5ODItOTVhMy00Njg3LTgzOWQtMWI4YmVlZDdhMjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YTg2OTI2N2I0NTI3ZmUyZTFhNGRmYTBkMWQ2YWZkNDBhNDIwZTFjOGQ2MzBhZWZkNjA4MTFjNjQ3MjA1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ekpa-IhdJeFsc6gx2pBVS50-Oen09aucjabrC_wyCSA)
> 
> TCP 节点 Socks 监听端口你不要改成1081啊，冲突了，保持默认的1070

0 0改回来了又，然后又照着另一位大佬说的那样设置了一下  好像行了

**Comment by bcseputetto** [comment]
> 大佬是这样嘛？

@91Metis 对，没错，是这样，你的回复里面不要夹杂太多引用，会变得很长

**Comment by 91Metis** [comment]
@bcseputetto 嗯嗯  - -抱歉

**Comment by lwb1978** [comment]
> @lwb1978 话说起来，当前源码的 chinadns-ng 过滤代理域名IPv6打勾后，好像没有正常向 chinadns-ng的配置里面写 代理组的 `no-ipv6` ![image](https://private-user-images.githubusercontent.com/29139573/323962075-4d25bb7d-877b-4776-b5f2-093c08c804cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzM5MDQsIm5iZiI6MTcxMzUzMzYwNCwicGF0aCI6Ii8yOTEzOTU3My8zMjM5NjIwNzUtNGQyNWJiN2QtODc3Yi00Nzc2LWI1ZjItMDkzYzA4YzgwNGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzMzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTk5M2U4M2NkZTliNTZlNTM1Mjg3NTNmMmRjMjBkODMzNzM1YWI1YTg1YzUzMDZkZmFhM2M0YWIzMDg1ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFOG3cwoWFzvXITV68fjGVwlPm1BpLN-MUufs4yfpuw)

我大致看了下肉鸡大佬今天的修改是有echo no-ipv6的代码，但具体哪里出的问题还不知道，app.sh代码好复杂，我这半桶水要慢慢细品，得肉鸡大佬出马才行。
@xiaorouji

**Comment by handsomeji** [comment]
> @lwb1978 话说起来，当前源码的 chinadns-ng 过滤代理域名IPv6打勾后，好像没有正常向 chinadns-ng的配置里面写 代理组的 `no-ipv6` ![image](https://private-user-images.githubusercontent.com/29139573/323962075-4d25bb7d-877b-4776-b5f2-093c08c804cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTY4MzUsIm5iZiI6MTcxMzU1NjUzNSwicGF0aCI6Ii8yOTEzOTU3My8zMjM5NjIwNzUtNGQyNWJiN2QtODc3Yi00Nzc2LWI1ZjItMDkzYzA4YzgwNGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE5NTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmODQyNDdiZTBkMmVhMTNjODBjOTdjYWYzNWRlOGVlZDk1OWRkMjliOGViMWNkNzAyYmJkMjkyZGMyMDRlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oWt1xqsBtIsSF0BRbkXMQJNUAQTBkyMXMZ0FA_DTILI)

Fix.

**Comment by xcyll** [comment]
> > @lwb1978 话说起来，当前源码的 chinadns-ng 过滤代理域名IPv6打勾后，好像没有正常向 chinadns-ng的配置里面写 代理组的 `no-ipv6`
> 
> Fix.

大佬 此版本更新后
启用过滤代理域名 IPv6后
返回的IPv6又变成了丢弃 ::  ，而不是返回空域名
![2024-04-20 1404618](https://github.com/xiaorouji/openwrt-passwall/assets/63227888/304930ad-8c64-4bff-b655-9611c2b75714)
@xiaorouji
