### ISSUE TITLE
最新版显示错误

### ISSUE THREAD

**Issue by gssiwmd** [xiaorouji/openwrt-package#3132]
### 描述您遇到的bug

sock代理实际启动了，但貌似显示错误

### 复现此Bug的步骤

![image](https://github.com/xiaorouji/openwrt-passwall/assets/161112901/cec8aee6-f1d2-49e5-bcc9-fb2137ac485a)

### 您想要实现的目的

修改显示错误

### 日志信息

无

### 系统相关信息

最新版

**Comment by lwb1978** [comment]
手动在终端复制下面代码运行看是否有输出：
/bin/busybox top -bn1 | grep -v 'grep' | grep '/tmp/etc/passwall/bin/' | grep 'default' | grep 'TCP'
如果有就清理一下浏览器缓存再看看状态是否正常。
另外提交问题时请不要懒到连版本号都不愿意输入，写个最新版非常不利于排查问题。PW的大佬有时会在24小时内更新两次，你所谓的最新不一定就是最新。

**Comment by mervinniu** [comment]
4.77-2_x86_64，openwrt22.3.06，复现此问题。

**Comment by gssiwmd** [comment]
> 手动在终端复制下面代码运行看是否有输出： /bin/busybox top -bn1 | grep -v 'grep' | grep '/tmp/etc/passwall/bin/' | grep 'default' | grep 'TCP' 如果有就清理一下浏览器缓存再看看状态是否正常。 另外提交问题时请不要懒到连版本号都不愿意输入，写个最新版非常不利于排查问题。PW的大佬有时会在24小时内更新两次，你所谓的最新不一定就是最新。

无输出。

**Comment by gssiwmd** [comment]
此外，当负载均衡在运行中，选单一节点，根本就连接不上。

**Comment by lwb1978** [comment]
运行这段代码看，并把结果截图上来看看
/bin/busybox top -bn1 | grep -v 'grep' | grep '/tmp/etc/passwall/bin/'  | grep 'TCP'

**Comment by gssiwmd** [comment]
> 运行这段代码看，并把结果截图上来看看 /bin/busybox top -bn1 | grep -v 'grep' | grep '/tmp/etc/passwall/bin/'  | grep 'TCP'

![image](https://github.com/xiaorouji/openwrt-passwall/assets/161112901/f5279191-2534-4c84-b24c-b0e084b5ca1f)

**Comment by gssiwmd** [comment]
运行负载均衡模式正常，
![image](https://github.com/xiaorouji/openwrt-passwall/assets/161112901/5f796a3c-1761-4116-9fde-48bdbf72ad1b)

再换成单节点后就无法连接了。运行代码无输出
![image](https://github.com/xiaorouji/openwrt-passwall/assets/161112901/4f64a202-fdab-4ed7-b1ec-4129b05d8b4c)

**Comment by lwb1978** [comment]
按理说你截图中输出的第二条是能匹配上下面这条命令的：
/bin/busybox top -bn1 | grep -v 'grep' | grep '/tmp/etc/passwall/bin/' | grep 'default' | grep 'TCP' 
但你前面说没有任何输出就奇怪了，肉鸡大佬看看呗。
@xiaorouji

**Comment by handsomeji** [comment]
沒有任何日誌有什麼好說的。。。
未運行請查看節點日誌。
