### ISSUE TITLE
[Bug]: 【luci-smartdns-dev】 版本【模式】中的【使用 直连列表】和【使用 屏蔽列表】遇到了 bug

### ISSUE THREAD

**Issue by icanoncn** [xiaorouji/openwrt-package#3133]
### 描述您遇到的bug

我在使用 【luci-smartdns-dev】 版本时遇到了 bug：
bug 出现在【模式】中的【使用 直连列表】和【使用 屏蔽列表】这两个选项
只选择【使用 直连列表】，系统不会把【直连列表】添加到 【/tmp/etc/smartdns/passwall.conf】
只选择【使用 屏蔽列表】，系统会把【直连列表添】和【屏蔽列表】都加到 【/tmp/etc/smartdns/passwall.conf】

### 复现此Bug的步骤

1. 我在【直连列表】、【代理列表】、【屏蔽列表】中添加了 3 个测试域名：

<img width="1121" alt="01" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/d46434c8-78d3-47fc-b3fb-f8d4e5a80259">
<img width="1118" alt="02" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/2a30c116-f2e9-4031-bb13-3fd2cd66c90a">
<img width="1109" alt="03" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/553c9e99-2155-45f1-8d95-c443ee5b32c6">

2. 把所有的列表都启用时，规则时正常的。

<img width="1599" alt="04" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/63bbd42e-482e-48df-8c18-c43b5efaf0e2">

3. 只选择【使用直连列表】时，并没有添加 【直连列表】

<img width="1585" alt="05" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/20c2deea-d487-41b6-9457-b26d1d1d01ab">

4. 只选择【使用屏蔽列表】时，会添加 【直连列表】和【屏蔽列表】两条规则

<img width="1603" alt="06" src="https://github.com/xiaorouji/openwrt-passwall/assets/36954988/67b28b0b-88f9-4816-aefb-7ba0835db954">

### 您想要实现的目的

我检查了我的配置文件，没有发现问题，希望这不是我的个例，多谢大佬。

### 日志信息
暂无

### 系统相关信息

- Passwall 版本：【 4.77-2-smartdns-dev 】
- 浏览器版本：【Microsoft Edge - Version 124.0.2478.51 (Official build) (64-bit)】

**Comment by handsomeji** [comment]
用最新源代碼試試。

**Comment by icanoncn** [comment]
多谢大佬，【 4.77-3-smartdns-dev 】已经解决。
