### ISSUE TITLE
[Bug]: 海外DNS的UDP请求不走代理

### ISSUE THREAD

**Issue by pmkol** [xiaorouji/openwrt-package#3135]
### 描述您遇到的bug

使用的是xray，在xray名单中与代理列表中，均设置了8.8.8.8 1.1.1.1等海外DNS的IP规则的，TCP与UDP都选择了xray的trojan，同时也设置了UDP转发端口选择了全部。

但在电脑上使用q命令或nslookup命令测试：

nslookup www.google.com 8.8.8.8
q www.google.com @8.8.8.8
返回的是污染地址，说明UDP 53 没代理出去

q www.google.com @tcp://8.8.8.8
返回的是正确地址，说明TCP 53 已代理出去

补充说明：
发现在路由器上，使用命令
dig www.google.com @8.8.8.8
返回的是正确地址，在路由器上UDP53是代理出去的

所以貌似问题是在客户端没有将UDP53代理出去

是BUG还是哪没配置对？

### 复现此Bug的步骤

-

### 您想要实现的目的

-

### 日志信息

2024-04-24 02:44:03: 执行启动延时 15 秒后再启动!
2024-04-24 02:44:22: 清空并关闭相关程序和缓存完成。
2024-04-24 02:44:22: TCP节点：[分流总节点]，监听端口：1041
2024-04-24 02:44:22: 开启实验性IPv6透明代理(TProxy)，请确认您的节点及类型支持IPv6！
2024-04-24 02:44:22: DNS域名解析：
2024-04-24 02:44:22:   - udp://127.0.0.1#5553
2024-04-24 02:44:22:   * 要求代理 DNS 请求，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
2024-04-24 02:44:22:   - 节点列表中的域名(vpslist)：127.0.0.1#5553
2024-04-24 02:44:22:   - 域名白名单(whitelist)：127.0.0.1#5553
2024-04-24 02:44:22:   - 代理域名表(blacklist)：127.0.0.1#5553
2024-04-24 02:44:22:   - V2ray/Xray分流规则(ProxyGame)：127.0.0.1#5553
2024-04-24 02:44:22:   - V2ray/Xray分流规则(Netflix)：127.0.0.1#5553
2024-04-24 02:44:22:   - V2ray/Xray分流规则(OpenAI)：127.0.0.1#5553
2024-04-24 02:44:22:   - V2ray/Xray分流规则(TikTok)：127.0.0.1#5553
2024-04-24 02:44:22:   - V2ray/Xray分流规则(Proxy)：127.0.0.1#5553
2024-04-24 02:44:22:   - 默认：127.0.0.1#5553
2024-04-24 02:44:22:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-04-24 02:44:22: 开始加载防火墙规则...
2024-04-24 02:44:24:   - [0]追加ISP IPv4 DNS到白名单：192.168.1.1
2024-04-24 02:44:24: 加入负载均衡的节点到nftset[passwall_vpslist]直连完成
2024-04-24 02:44:24:   - [0]追加直连DNS到nftables：127.0.0.1:5553
2024-04-24 02:44:24:   - 【路由器本机】，不代理 TCP 端口[22,3306]
2024-04-24 02:44:24:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-04-24 02:44:24:   - 上游 DNS 服务器 127.0.0.1 已在直接访问的列表中，不强制向 UDP 代理转发对该服务器 UDP/5553 端口的访问
2024-04-24 02:44:24: 加入所有节点到nftset[passwall_vpslist]直连完成
2024-04-24 02:44:25:   - 【默认】，不代理 TCP 端口[22,3306]
2024-04-24 02:44:25:   - 【默认】，屏蔽代理 UDP 端口[443]
2024-04-24 02:44:25:   - 【默认】，使用 TCP 节点[分流总节点](TPROXY:1041)
2024-04-24 02:44:25:   - 【默认】，使用 UDP 节点[分流总节点](TPROXY:1041)
2024-04-24 02:44:25: 防火墙规则加载完成！
2024-04-24 02:44:29: 重启 dnsmasq 服务
2024-04-24 02:44:29: 配置定时任务：自动更新规则。
2024-04-24 02:44:29: 运行完成！

### 系统相关信息

4.77-3

**Comment by bilibili2077** [comment]
xray和singbox的分流一直有问题，节点换成singbox就无法打开pixiv，换成xray就能打开，不管换成GFW模式还是中国列表外都是一样，自从上次大版本更新后就一直这样！

**Comment by SakuraFallingMad** [comment]
![图片](https://github.com/xiaorouji/openwrt-passwall/assets/31793080/426f11f3-9520-49c6-96ea-0635413fca90)
可能还是要自己测试下自己手搓分流配置吧。

**Comment by xcyll** [comment]
需要你的节点服务器也要支持UDP代理

**Comment by xcyll** [comment]
除了插件支持 节点服务器本身也要支持UDP代理

**Comment by pmkol** [comment]
> ![图片](https://private-user-images.githubusercontent.com/31793080/324409961-426f11f3-9520-49c6-96ea-0635413fca90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODQ1OTksIm5iZiI6MTcxMzc4NDI5OSwicGF0aCI6Ii8zMTc5MzA4MC8zMjQ0MDk5NjEtNDI2ZjExZjMtOTUyMC00OWM2LTk2ZWEtMDYzNTQxM2ZjYTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDExMTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3N2MxZmRiYTM5MDNlOTYyOWEzZWIzMmYyYjA0YzkzYWI5ZDU0ODFhZjY4ZmY4YTBmOTc2ZjBiZTBhN2RkMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZphqmnWiHzzLfYGIwX912JRBDb33ICGALvssK7bTvzI) 可能还是要自己测试下自己手搓分流配置吧。

应该和分流无关，开全局模式一样有这个问题

**Comment by pmkol** [comment]
> 除了插件支持 节点服务器本身也要支持UDP代理

可以确定是支持的，之前用别的路由器固件，这里是没问题的，服务端没有任何改动

**Comment by gito10** [comment]
@pmkol 既然你描述的问题是关于DNS的，但你既没有说明你的DNS设置情况，也没有贴出passwall日志。

上面的pixiv截图应该不是回复的你的问题，而是那位说sing-box分流打不开pixiv的。

**Comment by qingtian110** [comment]
我的设置
![image](https://github.com/xiaorouji/openwrt-passwall/assets/87856890/1c5f5309-6333-4697-8588-a24ff32b2be4)

没有任何问题
![image](https://github.com/xiaorouji/openwrt-passwall/assets/87856890/4be56ddb-0270-48f7-a0d9-47a565c90dc0)

如果你也这样设置还是有问题，那就是你 UDP 节点根本不工作。测试 UDP 工不工作最好用的方式是 NatTypeTester 测试全锥型。

![image](https://github.com/xiaorouji/openwrt-passwall/assets/87856890/0c88682b-7cb8-466c-9bba-c421de155f89)

如果公网IP 是你 UDP 节点的 IP 才能证明你的 UDP 节点是好的。

**Comment by ZqinKing** [comment]
你应该先把系统的iptable的NAT那块先附上。有些openwrt是无脑转走的。

**Comment by pmkol** [comment]
> 我的设置 ![image](https://private-user-images.githubusercontent.com/87856890/324722595-1c5f5309-6333-4697-8588-a24ff32b2be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDEyODgsIm5iZiI6MTcxMzkwMDk4OCwicGF0aCI6Ii84Nzg1Njg5MC8zMjQ3MjI1OTUtMWM1ZjUzMDktNjMzMy00Njk3LTg1ODgtYTI0ZmYzMmIyYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE5MzYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzlmNmEzY2EyNjMyNTdmOGUwZWI3Y2QzMGU2ODgyYzMwMDFmYTEwMTBlNGJjM2FlOGRlYjBmMmRjN2IxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sj2qzlgIfn2BK-s5xvvQzKErZIwvwiOQreRJb-s5U_4)
> 
> 没有任何问题 ![image](https://private-user-images.githubusercontent.com/87856890/324722428-4be56ddb-0270-48f7-a0d9-47a565c90dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDEyODgsIm5iZiI6MTcxMzkwMDk4OCwicGF0aCI6Ii84Nzg1Njg5MC8zMjQ3MjI0MjgtNGJlNTZkZGItMDI3MC00OGY3LWEwZDktNDdhNTY1YzkwZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE5MzYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjdkNzVkZDIxZmVlZmIwMzdhM2ZlZTJlNzNmNzkzMjc4NzI1NWY5M2YwNWFiNTVlYzlmN2I0YmIzZGFjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulhf6gkBsZZJa10_2ZErtpagIF1FA7BnVe3ZFyewf80)
> 
> 如果你也这样设置还是有问题，那就是你 UDP 节点根本不工作。测试 UDP 工不工作最好用的方式是 NatTypeTester 测试全锥型。
> 
> ![image](https://private-user-images.githubusercontent.com/87856890/324723319-0c88682b-7cb8-466c-9bba-c421de155f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDEyODgsIm5iZiI6MTcxMzkwMDk4OCwicGF0aCI6Ii84Nzg1Njg5MC8zMjQ3MjMzMTktMGM4ODY4MmItN2NiOC00NjZjLTliYmEtYzQyMWRlMTU1Zjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE5MzYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODUxZGNlOWI5NTllOGU5NDBiYTFmNDBkZmZkZGU3MWI3MGZhMjdiYmIzMjJjNDQ5ZDhkY2FhNTc4MGUxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BaW547iXfvI--EZtK88YqCZis_dt8wiABvIbiOCvrYQ)
> 
> 如果公网IP 是你 UDP 节点的 IP 才能证明你的 UDP 节点是好的。

PortRestrictedCone 有时显示为 PortRestrictedCone 有时显示为 FullCone
公网地址 为 代理服务器的 IP:Port

显示这个应该可以确定UDP节点是好的吧

**Comment by pmkol** [comment]
> 你应该先把系统的iptable的NAT那块先附上。有些openwrt是无脑转走的。

这个应该在哪里看，不是很熟悉OP的系统，是防火墙设置中，勾选全锥形 NAT么？

发现在路由器上dig测试，UDP53是代理出去的，能返回正确结果，但是在客户端上就不行，的确有可能是转发问题

**Comment by pmkol** [comment]
> @pmkol 既然你描述的问题是关于DNS的，但你既没有说明你的DNS设置情况，也没有贴出passwall日志。
> 
> 上面的pixiv截图应该不是回复的你的问题，而是那位说sing-box分流打不开pixiv的。

应该和DNS设置没关系，因为是直接用命令+IP去请求海外DNS的，固件中的DNS负责的是解析域名，这种请求就没用到路由器上的DNS

日志已经附上了，说明一下，本地5553的DNS是无污染的，所以直接用了UDP请求

补充说明：

发现在路由器上，使用命令
dig [www.google.com](http://www.google.com/) @8.8.8.8
返回的是正确地址，在路由器上UDP53是代理出去的

貌似问题是在客户端没有将UDP53代理出去，这种情况是我哪里没设置对么？

**Comment by gito10** [comment]
你op用的哪个的，lean、Lienol、官方或者什么？有的op比如lean的默认开启了DNS劫持，UDP53和TCP53都被劫持了，路由自身指定DNS服务器查询不受影响，但客户端不管指定那个甚至不存在的服务器地址，都会被劫持走路由器本机53端口。

验证方法，客户端用多个不同服务商DNS查询同一个域名（可以就用国内DNS查国内域名），是否都是一样的结果。还可以用随便虚假的IP查，是否也返回了一样的结果。如果是，那么路由开启了DNS劫持，你在客户端指定的走8.8.8.8是无效的，那就还是passwall的DNS设置问题。如果没开劫持，再排查其他问题。

另外在路由器上，nslookup或dig的时候，不要指定DNS服务器，让它走默认的本机53端口，走本机53端口结果正确才能完全排除DNS设置问题。

**Comment by ZqinKing** [comment]
> 同服务商DNS查询同一个域名（可以

iptables -t nat -L

**Comment by nftbty** [comment]
> iptables -t nat -L

这个输出不一定人人看得懂，知道哪个规则的作用是劫持DNS的，还是直接查DNS有直观感受，尤其是用一个不存在的DNS服务器IP也返回结果的时候。

**Comment by pmkol** [comment]
> 你op用的哪个的，lean、Lienol、官方或者什么？有的op比如lean的默认开启了DNS劫持，UDP53和TCP53都被劫持了，路由自身指定DNS服务器查询不受影响，但客户端不管指定那个甚至不存在的服务器地址，都会被劫持走路由器本机53端口。
> 
> 验证方法，客户端用多个不同服务商DNS查询同一个域名（可以就用国内DNS查国内域名），是否都是一样的结果。还可以用随便虚假的IP查，是否也返回了一样的结果。如果是，那么路由开启了DNS劫持，你在客户端指定的走8.8.8.8是无效的，那就还是passwall的DNS设置问题。如果没开劫持，再排查其他问题。
> 
> 另外在路由器上，nslookup或dig的时候，不要指定DNS服务器，让它走默认的本机53端口，走本机53端口结果正确才能完全排除DNS设置问题。

使用的是openwrt官方23.05的自编译固件，只编译了极少插件，这是固件的下载位置
https://github.com/pmkol/openwrt_build_script/releases

dig 走默认DNS，无论是在软路由上，还是在客户端上，返回的都是无污染结果，所以可以排除是DNS设置问题

现在比较奇怪的问题是，在软路由上dig 8.8.8.8，UDP是代理出去的，拿到的结果正确，在客户端上dig就是污染结果，说明客户端的UDP 8.8.8.8没有代理出去，但在客户端上做webrtc测试，或用 NatTypeTester 测试全锥型，显示的是代理服务器IP，看起来UDP又是代理出去的，貌似只有DNS53的UDP在客户端没有被代理出去

**Comment by pmkol** [comment]
> > 同服务商DNS查询同一个域名（可以
> 
> iptables -t nat -L

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere  

信息是这样的，是这里有问题么

**Comment by nftbty** [comment]
> 信息是这样的，是这里有问题么

你是官方23.05版的op，应该是firewall4和nftables吧，你看看passwall高级设置-转发设置里面是iptables还是nftables。

**Comment by gito10** [comment]
> 信息是这样的，是这里有问题么

你用的官方23.05，应该是nftables了。
往上翻了下你的日志，确实是nftables。
所以需要查看nftables而不是iptables。

但是你系统上又有iptables，而且看输出，还有规则，你这是混用iptables和nftables的情况啊。

**Comment by pmkol** [comment]
> > 信息是这样的，是这里有问题么
> 
> 你用的官方23.05，应该是nftables了。 往上翻了下你的日志，确实是nftables。 所以需要查看nftables而不是iptables。
> 
> 但是你系统上又有iptables，而且看输出，还有规则，你这是混用iptables和nftables的情况啊。

我在passwall转发配置那，改成了iptables后的输出

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
PSW_REDIRECT  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain PSW (0 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             match-set passwall_lanlist dst
RETURN     all  --  anywhere             anywhere             match-set passwall_vpslist dst
RETURN     all  --  anywhere             192.168.1.3          /* 'WAN_IP_RETURN' */
RETURN     all  --  anywhere             anywhere             /* 'Ä¬ÈÏ' */ match-set passwall_whitelist dst
RETURN     tcp  --  anywhere             anywhere             /* 'Ä¬ÈÏ' */

Chain PSW_OUTPUT (0 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             match-set passwall_lanlist dst
RETURN     all  --  anywhere             anywhere             match-set passwall_vpslist dst
RETURN     all  --  anywhere             anywhere             match-set passwall_whitelist dst
RETURN     all  --  anywhere             anywhere             mark match 0xff

Chain PSW_REDIRECT (1 references)
target     prot opt source               destination

**Comment by SakuraFallingMad** [comment]
尽量不要混用，据说混用会出现配置后，和预期不一样的结果

**Comment by pmkol** [comment]
> 尽量不要混用，据说混用会出现配置后，和预期不一样的结果

要如何解决混用问题呢，对OP不太熟悉，除了passwall选择nftables或iptables外，还需要哪里也改动这些

**Comment by handsomeji** [comment]
Fix.
