### ISSUE TITLE
[Bug]: 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。

### ISSUE THREAD

**Issue by qq1316237299** [xiaorouji/openwrt-package#3137]
### 描述您遇到的bug

477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。

### 复现此Bug的步骤

477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。

### 您想要实现的目的

477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。

### 日志信息

477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/2d971676-078c-41c9-b314-fce96d61567e)

### 系统相关信息

477-3

**Comment by qq1316237299** [comment]
> ### 描述您遇到的bug
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 复现此Bug的步骤
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 您想要实现的目的
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 日志信息
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 截图
> ![image](https://private-user-images.githubusercontent.com/42686656/324377203-2d971676-078c-41c9-b314-fce96d61567e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzMzNzQsIm5iZiI6MTcxMzc3MzA3NCwicGF0aCI6Ii80MjY4NjY1Ni8zMjQzNzcyMDMtMmQ5NzE2NzYtMDc4Yy00MWM5LWIzMTQtZmNlOTZkNjE1NjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4MDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NmJhZjM2NWJkZTA3Yjg5MDA3NzVlNzliYTAzZDNiOGNmMjgwNGZiNTJjMTE2MmY4ZGFlNmRlYjcyNWY4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smxg1QnNcGwf_YdFRNlYK4vJYGb675A1QKtCyeU-KeA)
> 
> ### 系统相关信息
> 477-3   X86
> 
> ### 其他信息
> _No response_

**Comment by qq1316237299** [comment]
> ### 描述您遇到的bug
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 复现此Bug的步骤
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 您想要实现的目的
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 日志信息
> 477-3 ChinaDNS-NG 版本没更新，导致不能连上代理 我用其他代理软件更新了ChinaDNS-NG 版本才可以正常使用。
> 
> ### 截图
> ![image](https://private-user-images.githubusercontent.com/42686656/324377203-2d971676-078c-41c9-b314-fce96d61567e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzM1ODEsIm5iZiI6MTcxMzc3MzI4MSwicGF0aCI6Ii80MjY4NjY1Ni8zMjQzNzcyMDMtMmQ5NzE2NzYtMDc4Yy00MWM5LWIzMTQtZmNlOTZkNjE1NjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzFjMzJlMzEwYWM5MThmMGEzZWIwMGJkOTIyNjAyMDcyZDU2MzczMjljYWJiNmIzYjIzMDhmZGNmYzBiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TorKl0jXt7IVVqbfDuOOn97QZ6s2yPNHS9pBpj3eZLA)
> 
> ### 系统相关信息
> 477-3
> 
> ### 其他信息
> _No response_

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/b71802b6-d0f4-49cb-9f80-560436ee9869)

**Comment by gito10** [comment]
ChinaDNS-NG 通过GitHub更新，即使不开代理应该也能连的上的。
而且 ChinaDNS-NG 也不是代理连通的必要条件，可以先不勾选ChinaDNS-NG，连上代理，更新完后再启用。

**Comment by qq1316237299** [comment]
> ChinaDNS-NG 通过GitHub更新，即使不开代理应该也能连的上的。 而且 ChinaDNS-NG 也不是代理连通的必要条件，可以先不勾选ChinaDNS-NG，连上代理，更新完后再启用。

好的，谢谢
