### ISSUE TITLE
[Bug]:  4.77-3经常断流  

### ISSUE THREAD

**Issue by qq1316237299** [xiaorouji/openwrt-package#3141]
### 描述您遇到的bug

试过关闭ChinaDNS-NG和打开ChinaDNS-NG  都是经常性断流 ，这个版本可能有什么问题。

### 复现此Bug的步骤

试过关闭ChinaDNS-NG和打开ChinaDNS-NG  都是经常性断流 ，这个版本可能有什么问题。

### 您想要实现的目的

希望可以恢复到之前那么好用

### 日志信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/ecd1b2e5-d480-4af8-a7ef-6b14890e53bb)

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/1ffde854-95cd-4666-b776-911ca57ac3a1)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/ecd1b2e5-d480-4af8-a7ef-6b14890e53bb)

### 系统相关信息

477-3
Microsoft Edge
版本 124.0.2478.51 (正式版本) (64 位)

**Comment by qq1316237299** [comment]
> ### 描述您遇到的bug
> 试过关闭ChinaDNS-NG和打开ChinaDNS-NG 都是经常性断流 ，这个版本可能有什么问题。
> 
> ### 复现此Bug的步骤
> 试过关闭ChinaDNS-NG和打开ChinaDNS-NG 都是经常性断流 ，这个版本可能有什么问题。
> 
> ### 您想要实现的目的
> 希望可以恢复到之前那么好用
> 
> ### 日志信息
> ![image](https://private-user-images.githubusercontent.com/42686656/324745117-ecd1b2e5-d480-4af8-a7ef-6b14890e53bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTk0NDksIm5iZiI6MTcxMzg1OTE0OSwicGF0aCI6Ii80MjY4NjY1Ni8zMjQ3NDUxMTctZWNkMWIyZTUtZDQ4MC00YWY4LWE3ZWYtNmIxNDg5MGU1M2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDBmMGVjNmFhZTc5MGY4NWEwMjc3OTE4OTg1MjU2ZWIwNTNmNWM1YTRlODIxN2Q2YTdlZWMxMDc1OGU3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkD0bh51sRdVjrClovJ-ziCR3h8yUGbMOceREcu-b74)
> 
> ### 截图
> ![image](https://private-user-images.githubusercontent.com/42686656/324744276-1ffde854-95cd-4666-b776-911ca57ac3a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTk0NDksIm5iZiI6MTcxMzg1OTE0OSwicGF0aCI6Ii80MjY4NjY1Ni8zMjQ3NDQyNzYtMWZmZGU4NTQtOTVjZC00NjY2LWI3NzYtOTExY2E1N2FjM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDUxMzY5OTc3OWJkYThlNzBmNzE0ZWJhMzgzZDZiMGExMzJjNWEwNWMyNjViNGJlOTc2ZWZmODE1NTFmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4lJ3qfpYfvSf9KkmXQyG9iHtpic2JwEbg2Z2TV_H-d0) ![image](https://private-user-images.githubusercontent.com/42686656/324745117-ecd1b2e5-d480-4af8-a7ef-6b14890e53bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTk0NDksIm5iZiI6MTcxMzg1OTE0OSwicGF0aCI6Ii80MjY4NjY1Ni8zMjQ3NDUxMTctZWNkMWIyZTUtZDQ4MC00YWY4LWE3ZWYtNmIxNDg5MGU1M2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDBmMGVjNmFhZTc5MGY4NWEwMjc3OTE4OTg1MjU2ZWIwNTNmNWM1YTRlODIxN2Q2YTdlZWMxMDc1OGU3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkD0bh51sRdVjrClovJ-ziCR3h8yUGbMOceREcu-b74)
> 
> ### 系统相关信息
> 477-3 Microsoft Edge 版本 124.0.2478.51 (正式版本) (64 位)
> 
> ### 其他信息
> _No response_

![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/cddf1657-f743-4b99-a999-99848166ce10)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/42686656/a5cf6f50-49e0-4bf1-8a1b-9967551af5f2)

**Comment by qq1316237299** [comment]
发现问题了 ，应该是我浏览器开了 设置 - 安全和隐私设置 - 使用安全 DNS 关闭

**Comment by gito10** [comment]
你再仔细确认下，是不是passwall的问题，不是的话，issue就关掉吧。

**Comment by qq1316237299** [comment]
> 你再仔细确认下，是不是passwall的问题，不是的话，issue就关掉吧。

好的，不是passwall的问题  但是有个问题  还是上次我开的issue  更新op 是默认配置更新的 一定要去更新下ChinaDNS-NG 才能使用passwall  以前一直都是更新就有用的

**Comment by gito10** [comment]
> 好的，不是passwall的问题  但是有个问题  还是上次我开的issue  更新op 是默认配置更新的 一定要去更新下ChinaDNS-NG 才能使用passwall  以前一直都是更新就有用的

什么意思？是更新op后，chinadns-ng就回到旧版，导致用不了吗？ChinaDNS-NG新版相对以前有了非兼容性的改动，passwall适配了新版就不兼容旧版了。
op固件的内置的chinadns-ng没有更到最新吗？

**Comment by qq1316237299** [comment]
> > 好的，不是passwall的问题  但是有个问题  还是上次我开的issue  更新op 是默认配置更新的 一定要去更新下ChinaDNS-NG 才能使用passwall  以前一直都是更新就有用的
> 
> 什么意思？是更新op后，chinadns-ng就回到旧版，导致用不了吗？ChinaDNS-NG新版相对以前有了非兼容性的改动，passwall适配了新版就不兼容旧版了。 op固件的内置的chinadns-ng没有更到最新吗？

是的 是2024 3月份的版本好像
