### ISSUE TITLE
[Bug]: 4.77-3 不开PW V6正常获取，开PW就没V6了，

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-package#3144]
### 描述您遇到的bug

4.77-3 不开PW V6正常获取，开PW就没V6了，TEST-IPV6 检查不到V6地址，DNS 没开V6 过滤。

### 复现此Bug的步骤

4.77-3 不开PW V6正常获取，开PW就没V6了，TEST-IPV6 检查不到V6地址，DNS 没开V6 过滤。

### 您想要实现的目的

4.77-3 不开PW V6正常获取，开PW就没V6了，TEST-IPV6 检查不到V6地址，DNS 没开V6 过滤。

### 日志信息

4.77-3 不开PW V6正常获取，开PW就没V6了，TEST-IPV6 检查不到V6地址，DNS 没开V6 过滤。

### 系统相关信息

4.77-3 不开PW V6正常获取，开PW就没V6了，TEST-IPV6 检查不到V6地址，DNS 没开V6 过滤。

**Comment by gito10** [comment]
请认真填写issue，尤其是 ***复现步骤*** 和 ***日志信息*** ，否则别人没法排查是你自己配置问题还是真的Bug。

至少我刚刚测试，IPv6是没问题的。

**Comment by hcym** [comment]
刚刚开始用，好像没有什么事，2305的。其他的插件都没用，更应该没有什么问题。

**Comment by BGzEroll** [comment]
和passwall无关，请自己找固件作者

**Comment by bcseputetto** [comment]
可以尝试用 https://ipw.cn/ 测试，这个域名一般不会走代理，就算你开启代理客户端一般也不会受到影响
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/dcd0046e-3842-4e97-b7b2-5ed752e5da76)

**Comment by ghost** [comment]
當使用PassWall以「全局」方式代理流量，並且希望代理IPv6流量時，請不要開啓「代理路由器自身流量」相應選項。

如果不開啓這個選項的話，就可以正常代理IPv6流量了。
