### ISSUE TITLE
[Bug]: socks5节点疯狂产生日志

### ISSUE THREAD

**Issue by 631122919** [xiaorouji/openwrt-package#3148]
### 描述您遇到的bug

在使用sock5节点并打开日志会产生大量日志最终导致内存不足崩溃重启

### 复现此Bug的步骤

1选择局域网socks节点
2打开日志功能

### 您想要实现的目的

解决该问题

### 日志信息

[1;32m2024-04-27 15:21:17 INF:[0m [main] server address: 192.168.3.1#1080
[1;32m2024-04-27 15:21:17 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2024-04-27 15:21:17 INF:[0m [main] listen address: ::#1041
[1;32m2024-04-27 15:21:17 INF:[0m [main] udp cache maximum size: 256
[1;32m2024-04-27 15:21:17 INF:[0m [main] udp socket idle timeout: 60
[1;32m2024-04-27 15:21:17 INF:[0m [main] number of worker threads: 1
[1;32m2024-04-27 15:21:17 INF:[0m [main] enable tcp transparent proxy
[1;32m2024-04-27 15:21:17 INF:[0m [main] enable udp transparent proxy
[1;32m2024-04-27 15:21:17 INF:[0m [main] use redirect instead of tproxy
[1;32m2024-04-27 15:21:17 INF:[0m [main] verbose mode (affect performance)
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 117.41.143.177#42928
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 1.1.1.1#53
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#45736
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 8.8.4.4#853
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#45866
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 1.0.0.1#443
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#55074
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 103.2.57.5#443
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:23 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 117.41.143.177#34614
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 1.1.1.1#53
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 117.41.143.177#34620
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 1.1.1.1#53
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.201#57078
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.197.71.89#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#38970
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.198.162.78#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#60082
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 8.8.4.4#853
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#41830
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 1.0.0.1#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#33636
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 103.2.57.6#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#38974
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.198.162.78#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#38980
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.198.162.78#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#38990
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.198.162.78#443
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] try to connect to 192.168.3.1#1080 ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_connect_cb] connect to 192.168.3.1#1080 succeeded
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_send_authreq_cb] send to 192.168.3.1#1080, nsend:3
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 192.168.3.1#1080, nrecv:2
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_authresp_cb] send to 192.168.3.1#1080, nsend:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 192.168.3.1#1080, nrecv:10
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.3.1#39004
[1;32m2024-04-27 15:21:26 INF:[0m [tcp_tproxy_accept_cb] target socket address: 20.198.162.78#443

### 系统相关信息

4.77-4

**Comment by gito10** [comment]
这个passwall没办法，可能这个程序运行就是会输出这么多信息。要么把日志关了，或者实在调试需要，用高级日志功能里的持久化日志，把日志文件写入硬盘就不会占用内存了。不用看日志了再把日志记录关掉。
