### ISSUE TITLE
[Bug]: luci-i18n-passwall-zh-cn	git-24.116.32732-007cee2 翻译错误

### ISSUE THREAD

**Issue by naoki66** [xiaorouji/openwrt-package#3152]
### 描述您遇到的bug

[规则管理] -----Sing-Box/Xray 分流规则
菜单显示“在线、下线”
实际上应该是 上移、下移 

### 复现此Bug的步骤

[规则管理] -----Sing-Box/Xray 分流规则
自定义规则里面
菜单显示“在线、下线”
实际上应该是 上移、下移 ，右键提示却正确，没有问题。

### 您想要实现的目的

修改为 上移、下移

### 日志信息

详见截图

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/22931306/65ab32b4-bc94-445f-a9ce-abffde91141e)

### 系统相关信息

 
luci-app-passwall | 4.77-4
 
luci-i18n-passwall-zh-cn | git-24.116.32732-007cee2

**Comment by gito10** [comment]
这个翻译是系统的锅。

**Comment by xcyll** [comment]
master下是这样的
https://github.com/xiaorouji/openwrt-passwall/issues/2992#issuecomment-1980922382

**Comment by xcyll** [comment]
helloworld那边也有人提过相同问题https://github.com/fw876/helloworld/issues/1412

**Comment by sbwml** [comment]
现有固件修复：
```bash
sed -i 's/<%:Up%>/<%:Move up%>/g' /usr/lib/lua/luci/view/cbi/tblsection.htm
sed -i 's/<%:Down%>/<%:Move down%>/g' /usr/lib/lua/luci/view/cbi/tblsection.htm
```


OpenWrt 源码修复：
```bash
sed -i 's/<%:Up%>/<%:Move up%>/g' feeds/luci/modules/luci-compat/luasrc/view/cbi/tblsection.htm
sed -i 's/<%:Down%>/<%:Move down%>/g' feeds/luci/modules/luci-compat/luasrc/view/cbi/tblsection.htm
```


![image](https://github.com/xiaorouji/openwrt-passwall/assets/16485166/52ee1bed-0d80-40c5-a0a2-9ffb3f3f4c9e)
