### ISSUE TITLE
[Bug]: Installation of openwrt-passwall fails

### ISSUE THREAD

**Issue by MickeMannen** [xiaorouji/openwrt-package#3156]
### 描述您遇到的bug

I get the following error when installing passwall on my OpenWrt device, not sure if this is an error or if I have missed some dependencies!

Configuring luci-app-passwall2. 
lua: /usr/lib/lua/luci/passwall2/api.lua:5: module 'luci.sys' not found: 
no field package.preload['luci.sys'] 
no file './luci/sys.lua' 
no file '/usr/share/lua/luci/sys.lua' 
no file '/usr/share/lua/luci/sys/init.lua' 
no file '/usr/lib/lua/luci/sys.lua' 
no file '/usr/lib/lua/luci/sys/init.lua' 
no file './luci/sys.so' 
no file '/usr/lib/lua/luci/sys.so' 
no file '/usr/lib/lua/loadall.so' 
no file './luci.so' 
no file '/usr/lib/lua/luci.so' 
no file '/usr/lib/lua/loadall.so' 
stack traceback: 
[C]: in function 'require' 
/usr/lib/lua/luci/passwall2/api.lua:5: in main chunk 
[C]: in function 'require' 
/usr/lib/lua/luci/passwall2/server_app.lua:4: in main chunk 
[C]: ?

### 复现此Bug的步骤

opkg install luci-app-passwall

### 您想要实现的目的

Be able to install passwall

### 日志信息

Openwrt 23.5.5
Luci-app-passwall2 4.77-5

### 系统相关信息

Openwrt 23.5.5
Luci-app-passwall2 4.77-5

### 其他信息

Very sorry if i have missed anything in the bug report - the translator wasnt working....
If this is known please let me know

**Comment by gito10** [comment]
Is your ipk file download from github releases?

Download & install the one start with 'luci-23.05-'.
Before install it, run `opkg update` first.
Then install the ipk, opkg will auto install a package `lua-luci-runtime`.

**Comment by nftbty** [comment]
are your ipk file download from github releases?
Download & install the one start with 'luci-23.05-'.
Before install it, run `opkg update` first.
Then install the ipk, opkg will auto install a package `lua-luci-runtime`.

**Comment by MickeMannen** [comment]
thank you for a super fast reply!
I added the feed master.dl.sourceforge.net/project/openwrt-passwall-build for luci passwall installation
i will check if lua-luci-runtime was installed too and get back if it solved the issue

//Micke

**Comment by gito10** [comment]
your openwrt-passwall-build brunch is releases/packages-23.05 ?

**Comment by MickeMannen** [comment]
Problem solved
I checked luci-lua-runtime and that one was an old version - made an update of the package and then I could install openwrt-passwall

yes, my openwrt-passwall build is from releases/packages-23.05

thank you for all help

**Comment by MickeMannen** [comment]
Now it works
thank you for all help
