### ISSUE TITLE
[Bug]: can't use shadowsocks server

### ISSUE THREAD

**Issue by Sepehrdibaj** [xiaorouji/openwrt-package#3158]
### 描述您遇到的bug

hi i use shadowraket rust and xray core for use shadow raket servers but both of them didnt work , 

### 复现此Bug的步骤

hi i use shadowraket rust and xray core for use shadow raket servers but both of them didnt work , 

### 您想要实现的目的

hi i use shadowraket rust and xray core for use shadow raket servers but both of them didnt work , 

### 日志信息

hi i use shadowraket rust and xray core for use shadow raket servers but both of them didnt work , 

### 截图

hi i use shadowraket rust and xray core for use shadow raket servers but both of them didnt work , 

### 系统相关信息

last version

**Comment by gito10** [comment]
shadowraket? Shadowsocks?
what is your configuration? please upload the passwall log info.

**Comment by Sepehrdibaj** [comment]
sry Shadowsocks i test with shadowsocks-rust and xray core 
xray core work with vless and vmss config but didnt work on Shadowsocks 
in this log i use 
2024-04-30 15:16:25: 删除nftables防火墙规则完成。
2024-04-30 15:16:29: 清空并关闭相关程序和缓存完成。
2024-04-30 15:16:30: nftables透明代理基础依赖 kmod-nft-socket 未安装...
2024-04-30 15:16:30: nftables透明代理基础依赖 kmod-nft-tproxy 未安装...
2024-04-30 15:16:30: 127.0.0.1#15353 （直连DNS：1.0.0.1,1.1.1.1, 远程DNS：8.8.8.8）
2024-04-30 15:16:30:   - [0]节点列表中的域名(vpslist)：1.0.0.1,1.1.1.1,
2024-04-30 15:16:30:   - [0]默认：127.0.0.1#15353
2024-04-30 15:16:30: 开始加载防火墙规则...
2024-04-30 15:16:31:   - [0]追加ISP IPv4 DNS到白名单：1.0.0.1
2024-04-30 15:16:31:   - [0]追加ISP IPv4 DNS到白名单：1.1.1.1
2024-04-30 15:16:31:   - [0]追加ISP IPv4 DNS到白名单：5.200.200.200
2024-04-30 15:16:31:   - [0]追加ISP IPv4 DNS到白名单：8.8.8.8
2024-04-30 15:16:31: 加入负载均衡的节点到nftset[passwall2_vpslist]直连完成
2024-04-30 15:16:31: 加入所有节点到nftset[passwall2_vpslist]直连完成
2024-04-30 15:16:31:   - [0]追加直连DNS到nftables：1.0.0.1:53
2024-04-30 15:16:31:   - [0]追加直连DNS到nftables：1.1.1.1:53
2024-04-30 15:16:32: 【默认】，使用 TCP 节点[分流总节点](REDIRECT:1041)
2024-04-30 15:16:32: 【默认】，使用 UDP 节点[分流总节点](TPROXY:1041)
2024-04-30 15:16:32: 防火墙规则加载完成！
2024-04-30 15:16:36: 重启 dnsmasq 服务
2024-04-30 15:16:36: 运行完成！

2024-04-30 15:24:15: 删除nftables防火墙规则完成。
2024-04-30 15:24:19: 清空并关闭相关程序和缓存完成。
2024-04-30 15:24:19: nftables透明代理基础依赖 kmod-nft-socket 未安装...
2024-04-30 15:24:19: nftables透明代理基础依赖 kmod-nft-tproxy 未安装...
2024-04-30 15:24:19: 127.0.0.1#15353 （直连DNS：1.0.0.1,1.1.1.1, 远程DNS：8.8.8.8）
2024-04-30 15:24:19:   - [0]节点列表中的域名(vpslist)：1.0.0.1,1.1.1.1,
2024-04-30 15:24:19:   - [0]默认：127.0.0.1#15353
2024-04-30 15:24:20: 开始加载防火墙规则...
2024-04-30 15:24:20:   - [0]追加ISP IPv4 DNS到白名单：1.0.0.1
2024-04-30 15:24:20:   - [0]追加ISP IPv4 DNS到白名单：1.1.1.1
2024-04-30 15:24:20:   - [0]追加ISP IPv4 DNS到白名单：5.200.200.200
2024-04-30 15:24:20:   - [0]追加ISP IPv4 DNS到白名单：8.8.8.8
2024-04-30 15:24:20: 加入负载均衡的节点到nftset[passwall2_vpslist]直连完成
2024-04-30 15:24:20: 加入所有节点到nftset[passwall2_vpslist]直连完成
2024-04-30 15:24:21:   - [0]追加直连DNS到nftables：1.0.0.1:53
2024-04-30 15:24:21:   - [0]追加直连DNS到nftables：1.1.1.1:53
2024-04-30 15:24:22: 【默认】，使用 TCP 节点[分流总节点](REDIRECT:1041)
2024-04-30 15:24:22: 【默认】，使用 UDP 节点[分流总节点](TPROXY:1041)
2024-04-30 15:24:22: 防火墙规则加载完成！
2024-04-30 15:24:26: 重启 dnsmasq 服务
2024-04-30 15:24:26: 运行完成！

**Comment by Sepehrdibaj** [comment]
Xray 1.8.11 (Xray, Penetrates Everything.) OpenWrt (go1.22.2 linux/arm64)
A unified platform for anti-censorship.
2024/04/30 11:57:56 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/acl/default/global.json
2024/04/30 11:58:01 192.168.41.107:60520 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:01 192.168.41.107:60521 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:01 192.168.41.107:60522 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:02 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:02 192.168.41.107:60523 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:03 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:03 127.0.0.1:48621 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:03 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:04 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:04 192.168.41.107:60524 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:05 127.0.0.1:52948 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:05 127.0.0.1:52591 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:05 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:05 127.0.0.1:52597 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:05 127.0.0.1:34499 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:05 127.0.0.1:56387 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:05 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:05 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:05 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:06 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:06 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:06 192.168.41.107:60525 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:06 192.168.41.107:60527 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:06 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:06 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:06 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:06 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:06 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:06 127.0.0.1:38018 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:07 192.168.41.107:60529 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:07 127.0.0.1:56930 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 127.0.0.1:53295 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 127.0.0.1:53571 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 127.0.0.1:56523 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 127.0.0.1:52291 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:07 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:07 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 192.168.41.107:60530 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:08 192.168.41.107:60532 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:08 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:08 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:09 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:09 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:09 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:09 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:09 192.168.41.107:60534 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:09 127.0.0.1:38734 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:09 127.0.0.1:58678 accepted udp:0.0.0.0:0 [dns-in -> dns-out]
2024/04/30 11:58:09 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:09 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:09 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:09 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:09 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:10 192.168.0.149:45518 accepted tcp:216.239.38.120:443 [tcp_redir -> default]
2024/04/30 11:58:10 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:10 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:10 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:10 [Error] app/dns: failed to read response length > io: read/write on closed pipe
2024/04/30 11:58:10 192.168.41.107:60536 accepted tcp:140.233.186.5:18000 [tcp_redir -> default]
2024/04/30 11:58:10 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:10 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:10 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:11 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]
2024/04/30 11:58:11 DNS accepted tcp:8.8.8.8:53 [dns-in1 -> default]

**Comment by gito10** [comment]
What's the **Encrypt Method** of your ss node?

may be something wrong with your shadowsocks node, or some parameters you set are incorrect.

There is one point to pay attention: the `chacha20-poly1305` method in Xray, is called `chacha20-ietf-poly1305` in ss-libev, ss-rust and sing-box. Xray don't support non-AEAD method (include the  `chacha20-poly1305` in other ss clients).


And what is your DNS config in passwall? Could you take a snapshot and upload it to here?

**Comment by gito10** [comment]
I saw your main(TCP/UDP) node is the shunt node, does the node of ***default*** rule work correctly?
It seems DNS error. In shunt mode, the DNS queries are through the ***default*** node.
You can change the ***TCP Node*** to the single shadowsocks node, to check whether it works.

**Comment by Sepehrdibaj** [comment]
i have qusation how can i instal shadowsocks-libev on ax3000t ? passwall remove it from pakge but its best for shadowsocs

**Comment by gito10** [comment]
> i have qusation how can i instal shadowsocks-libev on ax3000t ? passwall remove it from pakge but its best for shadowsocs

You can install it by opkg directly, this pkg has been in the official openwrt source many years.
**shadowsocks-libev-ss-redir** for transparent proxy
**shadowsocks-libev-ss-local** for socks5 proxy
You should install both of them.
