### ISSUE TITLE
[Bug]: xray无法启动

### ISSUE THREAD

**Issue by liverpool-fc** [xiaorouji/openwrt-package#3159]
### 描述您遇到的bug

如题

### 复现此Bug的步骤

如题

### 您想要实现的目的

如题

### 日志信息

略

### 系统相关信息

最新版本/usr/lib/lua/luci/passwall/util_xray.lua文件619行末尾有个多余的逗号，会导致xray无法启动

**Comment by uingei** [comment]
多谢，刚更新，去掉逗号能跑了

**Comment by lxhao61** [comment]
> ### 描述您遇到的bug
> 如题
> 
> ### 复现此Bug的步骤
> 如题
> 
> ### 您想要实现的目的
> 如题
> 
> ### 日志信息
> 略
> 
> ### 截图
> _No response_
> 
> ### 系统相关信息
> 最新版本/usr/lib/lua/luci/passwall/util_xray.lua文件619行末尾有个多余的逗号，会导致xray无法启动
> 
> ### 其他信息
> _No response_

一样问题。

**Comment by gito10** [comment]
fixed
