### ISSUE TITLE
从4.77-4开始，安装后docker容器无法启动，反复重启

### ISSUE THREAD

**Issue by 58285474** [xiaorouji/openwrt-package#3160]
### 描述您遇到的bug

从4.77-4开始，安装后docker容器无法启动，反复重启

### 复现此Bug的步骤

从4.77-4开始，安装后docker容器无法启动，反复重启

### 您想要实现的目的

从4.77-4开始，安装后docker容器无法启动，反复重启

### 日志信息

从4.77-4开始，安装后docker容器无法启动，反复重启

### 系统相关信息

从4.77-4开始，安装后docker容器无法启动，反复重启

**Comment by kxdn3** [comment]
docker容器使用正常

**Comment by 58285474** [comment]
> docker容器使用正常

我用了smartdns，端口53

**Comment by 58285474** [comment]
我也搞不懂什么原因呢，我26个容器，部分容器反复重启

**Comment by sbwml** [comment]
虽然不太清楚你的情况，但是可以断定的是问题的出现与 passwall 无关。

你应该去找那些失败的容器日志。

发自我的iPhone

**Comment by 58285474** [comment]
> 虽然不太清楚你的情况，但是可以断定的是问题的出现与 passwall 无关。
> 
> 
> 
> 你应该去找那些失败的容器日志。
> 
> 
> 
> 发自我的iPhone
> 
> 
> 
> > 在 2024年5月2日，06:39，58285474 ***@***.***> 写道：
> 
> > 
> 
> > ﻿
> 
> > 我也搞不懂什么原因呢，我26个容器，部分容器反复重启
> 
> > 
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you commented.
> 
> 
容器太多了，智能家居也多，没时间搞，换回4.77-3完全没问题

**Comment by gito10** [comment]
>容器太多了，智能家居也多，没时间搞，换回4.77-3完全没问题

但是从 **4.77-3** 到 **4.77-4** 之间，除去无关紧要的提交，也就3个提交有实质性的代码修改：
* 40751a4
* 355a741
* cf7003f

其中，前2个修改比较少，要不你试试从 4.77-3开始依次应用这几个修改，或者从4.77-4依次回退，找一下具体是哪个提交引起的这个问题。

**Comment by 58285474** [comment]
> >容器太多了，智能家居也多，没时间搞，换回4.77-3完全没问题
> 
> 
> 
> 但是从 **4.77-3** 到 **4.77-4** 之间，除去无关紧要的提交，也就3个提交有实质性的代码修改：
> 
> * 40751a4
> 
> * 355a741
> 
> * cf7003f
> 
> 
> 
> 其中，前2个修改比较少，要不你试试从 4.77-3开始依次应用这几个修改，或者从4.77-4依次回退，找一下具体是哪个提交引起的这个问题。

能否帮忙编译一下带有smartdns的分支ipk，esir的高大全5.15内核，我怀疑是我装的ipk有问题

**Comment by gito10** [comment]
>能否帮忙编译一下带有smartdns的分支ipk

刚刚修改了 SmartDNS 分支的自动编译workflow，可以手动触发 SmartDNS分支的编译。想要编译SmartDNS分支ipk，fork本仓库，以后SmartDNS分支更新了，可以同步代码以后，到Actions里面手动触发 Auto compile，分支选`luci-smartdns-dev`就行，编译完会上传到你自己仓库的release。

这次我在本仓库手动触发了一次编译，目前可以在releases下载。

**Comment by 58285474** [comment]
> 刚刚修改了 SmartDNS 分支的自动编译workflow，可以手动触发 SmartDNS分支的编译。想要编译SmartDNS分支ipk，fork本仓库，以后SmartDNS分支更新了，可以同步代码以后，到Actions里面手动触发 Auto compile，分支选`luci-smartdns-dev`就行，编译完会上传到你自己仓库的release。
> 
> 
> 
> 这次我在本仓库手动触发了一次编译，目前可以在releases下载。

看了下日志，从4.77-3到4.77-5日志提示透明代理什么的没装上，应该是5.15内核不支，怎么办？

**Comment by gito10** [comment]
>看了下日志，从4.77-3到4.77-5日志提示透明代理什么的没装上，应该是5.15内核不支，怎么办？

透明代理内核模块是否真的未安装，不能看passwall的日志，可以去luci页面-系统-软件包 里面，看已安装的packages里面有没有提示的那几个。

**Comment by 58285474** [comment]
确实已经安装了，真是搞不明白了，5.15的内核，怎么搞都不行
> >看了下日志，从4.77-3到4.77-5日志提示透明代理什么的没装上，应该是5.15内核不支，怎么办？
> 
> 透明代理内核模块是否真的未安装，不能看passwall的日志，可以去luci页面-系统-软件包 里面，看已安装的packages里面有没有提示的那几个。

**Comment by frank-pv** [comment]
遇到了和你一模一样的问题，4.76。2-4.77.3正常，4.77.4-4.77.5升级后。immortalwrt 下的docker无法联网

**Comment by 58285474** [comment]
> 遇到了和你一模一样的问题，4.76。2-4.77.3正常，4.77.4-4.77.5升级后。immortalwrt 下的docker无法联网

你的问题解决了吗？我的还不行，目前还停留在4.77.3

**Comment by 58285474** [comment]
> 遇到了和你一模一样的问题，4.76。2-4.77.3正常，4.77.4-4.77.5升级后。immortalwrt 下的docker无法联网

兄弟，解决了吗？
