### ISSUE TITLE
[Bug]: Passwall 下出现Disney+ 代码83和93

### ISSUE THREAD

**Issue by King-Of-Knights** [xiaorouji/openwrt-package#3161]
### 描述您遇到的bug

大佬好，我的测试设备为Google TV电视棒，软路由固件为LEDE最新版，同样的节点，有以下结果：

1. Netflix、YouTube、HBO Go，V2rayNG和passwall均正常，同时可以解锁自制剧；
2. Disney+ 使用V2rayNG正常，使用软路由的passwall，账户界面正常，进入界面显示代码93或者83

  怀疑可能与DNS有关，研究了一天无果，请大佬给点提示

### 复现此Bug的步骤

- 透明代理，客户端DNS指向为软路由，在passwall中过滤了IPv6地址
- 直连DNS为LEDE TurboACC中DNS缓存中DNS
- 代理模式为中国列表外，规则管理、规则列表等为默认设置，
- 未设置访问控制、分流等选项，保持默认

### 您想要实现的目的

正常访问Disney+

### 日志信息

```
2024-05-01 11:02:56:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-05-01 11:07:43: 删除iptables防火墙规则完成。
2024-05-01 11:07:46: 清空并关闭相关程序和缓存完成。
2024-05-01 11:07:46: TCP节点：[🇹🇼 TW台湾|GZ]，监听端口：1041
2024-05-01 11:07:46: DNS域名解析：
2024-05-01 11:07:46:   - Xray DNS(127.0.0.1#15353) -> tcp://9.9.9.9
2024-05-01 11:07:46:   - ChinaDNS-NG(127.0.0.1#15354)：直连DNS：127.0.0.1#5333，可信DNS：127.0.0.1#15353
2024-05-01 11:07:46:   - 节点列表中的域名(vpslist)：127.0.0.1#5333
2024-05-01 11:07:46:   - 域名白名单(whitelist)：默认
2024-05-01 11:07:46:   - 代理域名表(blacklist)：默认
2024-05-01 11:07:46:   - 防火墙域名表(gfwlist)：默认
2024-05-01 11:07:46:   - 中国域名表(chnroute)：默认
2024-05-01 11:07:46:   - 默认：127.0.0.1#15354
2024-05-01 11:07:46:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-05-01 11:07:46: 开始加载防火墙规则...
2024-05-01 11:07:46:   - [0]追加ISP IPv4 DNS到白名单：10.192.0.14
2024-05-01 11:07:46:   - [0]追加ISP IPv4 DNS到白名单：10.192.0.18
2024-05-01 11:07:46:   - [0]追加ISP IPv6 DNS到白名单：fe80::1
2024-05-01 11:07:46:   - [0]加入负载均衡的节点到ipset[passwall_vpslist]
2024-05-01 11:07:46:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-05-01 11:07:46:   - [0]追加直连DNS到iptables：127.0.0.1:5333
2024-05-01 11:07:46:   - 访问控制：
2024-05-01 11:07:46:      - 【默认】，屏蔽代理 UDP 端口[80,443]
2024-05-01 11:07:46:      - 【默认】，使用 TCP 节点[TW台湾|GZ](REDIRECT:1041)
2024-05-01 11:07:46:      - 【默认】，使用 UDP 节点[TW台湾|GZ](TPROXY:1041)
2024-05-01 11:07:46: 防火墙规则加载完成！
2024-05-01 11:07:50: 重启 dnsmasq 服务
2024-05-01 11:07:50: 配置定时任务：自动更新规则。
2024-05-01 11:07:50: 配置定时任务：自动更新【XX】订阅。
2024-05-01 11:07:50: 运行完成！
```

### 系统相关信息

PassWall版本：4.77-5

**Comment by King-Of-Knights** [comment]
做了一些研究，似乎和IPv6有关，把`高级设置`里面的`IPv6透明代理(TProxy)`打开就好了，我尝试过DNS里面的`过滤代理域名 IPv6`，但好像这个开关是没有效果的，日志里面还是请求了
```
nrdp-ipv6.prod.ftl.netflix.com
ipv6-c003-hkg002-pccw-isp.1.oca.nflxvideo.net
```
这样的域名

**Comment by gito10** [comment]
**过滤代理域名IPv6** 是针对一般双栈服务器，过滤IPv6地址，只返回IPv4地址。但你这情况应该是客户端检测到设备有IPv6地址，直接请求了IPv6单栈服务器，这时候如果不开IPv6代理，开启过滤会直接解析不到地址，不开过滤会尝试用IPv6地址直连，能不能连上，或者连上能不能工作就不知道了。

如果不开IPv6代理或者节点不支持IPv6，可以使用FakeDNS/FakeIP。
或者直接禁用设备IPv6支持，客户端软件检测不到IPv6，就只能请求IPv4或者双栈服务器了。

**Comment by gito10** [comment]
所以这并不是什么bug，我就把这个关了。

**Comment by King-Of-Knights** [comment]
> **过滤代理域名IPv6** 是针对一般双栈服务器，过滤IPv6地址，只返回IPv4地址。但你这情况应该是客户端检测到设备有IPv6地址，直接请求了IPv6单栈服务器，这时候如果不开IPv6代理，开启过滤会直接解析不到地址，不开过滤会尝试用IPv6地址直连，能不能连上，或者连上能不能工作就不知道了。
> 
> 如果不开IPv6代理或者节点不支持IPv6，可以使用FakeDNS/FakeIP。 或者直接禁用设备IPv6支持，客户端软件检测不到IPv6，就只能请求IPv4或者双栈服务器了。

感谢大佬耐心回答，目前我感觉**过滤IPv6开关**没有作用，打开以后还是会请求IPv6地址

**Comment by gito10** [comment]
>目前我感觉过滤IPv6开关没有作用，打开以后还是会请求IPv6地址

不是这个没作用。它的作用是dns服务器返回的结果里面有IPv6地址时给你过滤掉，只返回IPv4地址，当服务器只有IPv6地址返回的就是空结果。
它并不能阻止客户端发送IPv6单栈的域名请求。想让客户端不发送IPv6服务器的域名请求，只能禁用设备IPv6支持。或者看你用的客户端软件有没有不使用IPv6的选项。否则就必须开启IPv6透明代理，并且代理节点要支持IPv6。

**Comment by gito10** [comment]
或者客户端软件支持设置HTTP/Socks5代理的话，也可以试试直接设置代理。一般设了代理之后，网络请求会直接用域名，而不会发起DNS请求（也有支持Socks5转发DNS的，比如Firefox）。

**Comment by nftbty** [comment]
或者客户端软件支持设置HTTP/Socks5代理的话，也可以试试直接设置代理。一般设了代理之后，网络请求会直接用域名，而不会发起DNS请求（也有支持Socks5转发DNS的，比如Firefox）。

**Comment by King-Of-Knights** [comment]
> 或者客户端软件支持设置HTTP/Socks5代理的话，也可以试试直接设置代理。一般设了代理之后，网络请求会直接用域名，而不会发起DNS请求（也有支持Socks5转发DNS的，比如Firefox）。

🧐，有一个疑惑，网络连接最终还是通过IP连接，如果传回去是一个域名，不还是得想办法查询IP嘛

**Comment by gito10** [comment]
一般HTTP/Socks代理，以及Xray/Sing-Box开启FakeIP/FakeDNS 或者流量嗅探，都是使用域名直接作为目的地址发送给代理服务器，服务器接收到代理请求后，发现目的是域名，会自己发起DNS请求。
也就是说DNS请求并不是没有了，而是从客户端转到了服务端。

**Comment by King-Of-Knights** [comment]
> 一般HTTP/Socks代理，以及Xray/Sing-Box开启FakeIP/FakeDNS 或者流量嗅探，都是使用域名直接作为目的地址发送给代理服务器，服务器接收到代理请求后，发现目的是域名，会自己发起DNS请求。 也就是说DNS请求并不是没有了，而是从客户端转到了服务端。

这么说，那就是代理软件劫持了客户端的DNS请求，最后还是想办法给客户端喂一个IP地址，应该是和远程DNS是一样的作用

**Comment by gito10** [comment]
>这么说，那就是代理软件劫持了客户端的DNS请求，最后还是想办法给客户端喂一个IP地址

FakeIP/FakeDNS 就是你说的这样，给客户端的DNS请求返回一个 **198.18.0.0/16** IP段内的IP，在客户端用这个假IP发起请求时，还原为域名。
但是HTTP/Socks代理不是，是客户端本身在设置了代理以后，就不发起DNS请求了。因为除了Socks5，其他Socks和HTTP代理都不支持代理UDP流量。

最后，开启流量嗅探，用嗅探出的覆盖目标IP地址，客户端正常发起DNS请求，通过代理也正常拿到IP地址，但是在Xray/Sing-Box这边，被还原为域名，服务端收到的还是域名请求，还是会发起DNS请求重新获取IP地址。
这种主要适用于分流场景，Xray不支持DNS分流，所有分流规则域名的DNS请求都走默认节点，拿到的IP地址是离默认节点最近的。如果分流有多个国家/地区的节点，比如默认HK，但是有的分流规则走JP，有的走US。那么走JP和US的拿到的IP就不是最好的，可能访问比较慢。这时候开启流量嗅探覆盖目标地址，或者FakeDNS，服务器那边就会自己发起DNS请求，拿到最近的IP。

**Comment by King-Of-Knights** [comment]
> > 这么说，那就是代理软件劫持了客户端的DNS请求，最后还是想办法给客户端喂一个IP地址
> 
> FakeIP/FakeDNS 就是你说的这样，给客户端的DNS请求返回一个 **198.18.0.0/16** IP段内的IP，在客户端用这个假IP发起请求时，还原为域名。 但是HTTP/Socks代理不是，是客户端本身在设置了代理以后，就不发起DNS请求了。因为除了Socks5，其他Socks和HTTP代理都不支持代理UDP流量。
> 
> 最后，开启流量嗅探，用嗅探出的覆盖目标IP地址，客户端正常发起DNS请求，通过代理也正常拿到IP地址，但是在Xray/Sing-Box这边，被还原为域名，服务端收到的还是域名请求，还是会发起DNS请求重新获取IP地址。 这种主要适用于分流场景，Xray不支持DNS分流，所有分流规则域名的DNS请求都走默认节点，拿到的IP地址是离默认节点最近的。如果分流有多个国家/地区的节点，比如默认HK，但是有的分流规则走JP，有的走US。那么走JP和US的拿到的IP就不是最好的，可能访问比较慢。这时候开启流量嗅探覆盖目标地址，或者FakeDNS，服务器那边就会自己发起DNS请求，拿到最近的IP。

感谢大佬精彩详细的分析，我有些粗浅理解和些许疑问，希望大佬指教:

1. 流量嗅探是否是针对客户端和服务端解析出IP地址不一样的情况，比如客户端通过本地DNS解析出是一个JP地址，确定需要被代理并发送给服务端，但是服务端本身在US，因此需要服务端嗅探出真实域名，并且解析出一个US的IP地址，优化连接速度；
2. 如果全局都是Fake DNS，那流量嗅探就是从客户端连接的198.18段里面，嗅探真实域名，发送到服务端去查询真实IP；
3. 我在服务端的Xray搞过DNS流媒体解锁，就是把geosite:netflix 写到Xray的DNS项里面，我感觉这个就是Xray的DNS分流，是否与大佬所述Xray DNS不支持分流不符

**Comment by gito10** [comment]
1 和 2 理解没问题。
3 的话，忘了之前在哪看的，说Sing-Box支持DNS路由，Xray不支持。刚刚搜了一下，V2ray/Xray确实支持 DNS分流，就和Dnsmasq、ChinaDNS-NG类似的不同域名走不同上游DNS服务器。

准确的说法应该是，目前不直接支持DNS流量根据要查询的域名进行路由匹配，走相应出站节点查询，也就是DNS请求和实际连接走相同出站。简称没什么简单的词表达这个意思，就暂且叫DNS路由吧。

虽然可以用多个不同的上游DNS，比如 8.8.8.8、8.8.4.4、1.1.1.1、1.0.0.1、9.9.9.9 等，然后将这些不同DNS设置不同路由。但是知名DNS服务商地址总共也就那几个，分流规则一多，就没有那么多DNS服务器来分。

不过结合我之前的一个想法，也许可以变通实现DNS路由。具体行不行得把目前手头上的事忙完了，再仔细看看配置文档，才能确定，现在说不准。

**Comment by gito10** [comment]
Xray通过配置实现 **DNS路由**，让分流域名的 **DNS请求** 和 **实际连接** 走同一出站代理这一需求，经手写配置文件测试，确实可以实现。之后就看Passwall上面好不好实现了。

下面贴出了配置示例，只配置了DNS入站 和 DNS路由（利用DNS分流实现，不同域名发送到不同的 dokodemo 端口入站，修改目的地址端口为 **8.8.8.8:53**，对不同的DNS入站指定路由规则走不通出站，实现不同域名使用同一个DNS服务器，走不同代理查询。因为可以使用相同DNS，有别于DNS分流，所以暂叫它 **DNS按查询域名路由**，或简称 **DNS路由**）
<details>
<summary>配置示例</summary>

```json
{
  "outbounds": [
    {
      "tag": "proxy-hk",
      "protocol": "shadowsocks",
      "settings": {},
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },
    {
      "tag": "proxy-tw",
      "protocol": "shadowsocks",
      "settings": {},
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },
    {
      "proxySettings": {
        "tag": "default"
      },
      "settings": {
        "nonIPQuery": "drop",
        "port": 53,
        "network": "tcp",
        "address": "8.8.8.8"
      },
      "protocol": "dns",
      "tag": "dns-out"
    },
    {
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blackhole"
    }
  ],
  "log": {
    "loglevel": "debug"
  },
  "dns": {
    "disableFallback": false,
    "queryStrategy": "UseIPv4",
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "address": "127.0.0.1",
        "port": 15531,
        "domains": [
          "domain:www.bing.com"
        ]
      },
      {
        "address": "127.0.0.1",
        "port": 15532,
        "domains": [
          "domain:www.google.com"
        ]
      }
    ],
    "disableCache": true,
    "tag": "dns"
  },
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "inboundTag": [
          "dns-hk"
        ],
        "outboundTag": "proxy-hk"
      },
      {
        "type": "field",
        "inboundTag": [
          "dns-tw"
        ],
        "outboundTag": "proxy-tw"
      },
      {
        "type": "field",
        "inboundTag": [
          "dns"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "direct"
      }
    ],
    "domainStrategy": "AsIs",
    "domainMatcher": "hybrid"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": false,
        "statsUserDownlink": false
      }
    }
  },
  "inbounds": [
    {
      "port": 15530,
      "protocol": "dokodemo-door",
      "settings": {
        "port": 53,
        "network": "tcp,udp",
        "address": "8.8.8.8"
      },
      "tag": "dns-in",
      "listen": "127.0.0.1"
    },
    {
      "port": 15531,
      "protocol": "dokodemo-door",
      "settings": {
        "port": 53,
        "network": "tcp,udp",
        "address": "8.8.8.8"
      },
      "tag": "dns-hk",
      "listen": "127.0.0.1"
    },
    {
      "port": 15532,
      "protocol": "dokodemo-door",
      "settings": {
        "port": 53,
        "network": "tcp,udp",
        "address": "8.8.8.8"
      },
      "tag": "dns-tw",
      "listen": "127.0.0.1"
    }
  ]
}
```

</details>

**Comment by King-Of-Knights** [comment]
> Xray通过配置实现 **DNS路由**，让分流域名的 **DNS请求** 和 **实际连接** 走同一出站代理这一需求，经手写配置文件测试，确实可以实现。之后就看Passwall上面好不好实现了。
> 
> 配置示例
> ```json
> {
>   "outbounds": [
>     {
>       "tag": "proxy-hk",
>       "protocol": "shadowsocks",
>       "settings": {},
>       "streamSettings": {
>         "sockopt": {
>           "mark": 255
>         }
>       }
>     },
>     {
>       "tag": "proxy-tw",
>       "protocol": "shadowsocks",
>       "settings": {},
>       "streamSettings": {
>         "sockopt": {
>           "mark": 255
>         }
>       }
>     },
>     {
>       "proxySettings": {
>         "tag": "default"
>       },
>       "settings": {
>         "nonIPQuery": "drop",
>         "port": 53,
>         "network": "tcp",
>         "address": "8.8.8.8"
>       },
>       "protocol": "dns",
>       "tag": "dns-out"
>     },
>     {
>       "streamSettings": {
>         "sockopt": {
>           "mark": 255
>         }
>       },
>       "settings": {
>         "domainStrategy": "UseIPv4"
>       },
>       "protocol": "freedom",
>       "tag": "direct"
>     },
>     {
>       "protocol": "blackhole",
>       "tag": "blackhole"
>     }
>   ],
>   "log": {
>     "loglevel": "debug"
>   },
>   "dns": {
>     "disableFallback": false,
>     "queryStrategy": "UseIPv4",
>     "disableFallbackIfMatch": true,
>     "servers": [
>       {
>         "address": "127.0.0.1",
>         "port": 15531,
>         "domains": [
>           "domain:www.bing.com"
>         ]
>       },
>       {
>         "address": "127.0.0.1",
>         "port": 15532,
>         "domains": [
>           "domain:cn.bing.com"
>         ]
>       }
>     ],
>     "disableCache": true,
>     "tag": "dns"
>   },
>   "routing": {
>     "rules": [
>       {
>         "type": "field",
>         "inboundTag": [
>           "dns-in"
>         ],
>         "outboundTag": "dns-out"
>       },
>       {
>         "type": "field",
>         "inboundTag": [
>           "dns-hk"
>         ],
>         "outboundTag": "proxy-hk"
>       },
>       {
>         "type": "field",
>         "inboundTag": [
>           "dns-tw"
>         ],
>         "outboundTag": "proxy-tw"
>       },
>       {
>         "type": "field",
>         "network": "tcp,udp",
>         "outboundTag": "proxy-tw",
>         "domains": [
>           "domain:youtube.com",
>           "domain:ytimg.com",
>           "domain:googlevideo.com",
>           "domain:duckduckgo.com",
>           "domain:sspanel.net"
>         ]
>       },
>       {
>         "type": "field",
>         "inboundTag": [
>           "dns"
>         ],
>         "outboundTag": "direct"
>       },
>       {
>         "type": "field",
>         "network": "tcp,udp",
>         "outboundTag": "direct"
>       }
>     ],
>     "domainStrategy": "AsIs",
>     "domainMatcher": "hybrid"
>   },
>   "policy": {
>     "levels": {
>       "0": {
>         "statsUserUplink": false,
>         "statsUserDownlink": false
>       }
>     }
>   },
>   "inbounds": [
>     {
>       "port": 15530,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "port": 53,
>         "network": "tcp,udp",
>         "address": "8.8.8.8"
>       },
>       "tag": "dns-in",
>       "listen": "127.0.0.1"
>     },
>     {
>       "port": 15531,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "port": 53,
>         "network": "tcp,udp",
>         "address": "8.8.8.8"
>       },
>       "tag": "dns-hk",
>       "listen": "127.0.0.1"
>     },
>     {
>       "port": 15532,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "port": 53,
>         "network": "tcp,udp",
>         "address": "8.8.8.8"
>       },
>       "tag": "dns-tw",
>       "listen": "127.0.0.1"
>     }
>   ]
> }
> ```

顺便加入`"domainStrategy": "UseIPv4"`，这样就能控制访问某些网站的IPv6了

**Comment by gito10** [comment]
刚好之前有个 讨论帖 #2934，就是关于 Xray DNS 路由的（原标题问的 DNS分流，实际就是问的 按查询域名路由，我把标题给改了），我把刚刚那段和配置示例发到那里了。
如果对 DNS 按域名路由 这个有兴趣的话，可以去那个讨论帖。
