### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by kyynelson** [xiaorouji/openwrt-package#3165]
### 描述你想要的新功能

我公司是用微软全家桶的，我在公司挂了openwrt passwall 1 的梯子的，GFW模式，扫fiddler把全部微软的服务网址都列进直连列表了，onedrive 同步流量的确没走梯子，但公司IT检测到了用梯子登陆了。我觉得passwall 挺好用的，主要是简单，但这个情况我只能考虑openclash，但好烦！

### 描述你想要的解决方案

我的需求就是就是加个微软的服务做例外直连就行，毕竟它不需要走流量啊。我扫出来的列表如下，得肯定不止这些：

akamaihd.net
azure-apim.net
azure.com
azure.net
azureedge.net
azurewebsitesdocker.com
dynamics.com
live.net
microsoft.com
microsoftcloud.com
microsoftdoud.com
microsoftonline.com
modpim.com
msftauth.net
msn.cn
msn.com
msocdn.com
office.com
office.net
office365.com
powerapps.com
powerautomate.com
sharepoint.com
sharepointonline.com
skype.com
svc.ms
trafficmanager.net
visualstudio.com
windows.net

### 描述你考虑过的替代方案

openclash

### 其他信息

谢谢，粉丝一枚。

**Comment by gito10** [comment]
passwall只提供直连/代理列表订阅，以及各一个自定义列表供手动添加。没有也不会去维护任何域名列表。

对于你的情况，你是使用的仅代理gfw列表模式。微软服务都没被墙，不应该出现在gfwlist中，请检查下你所用的gfwlist源，是否多余添加了很多不应添加的域名，可以换一个更精准些的不额外添加可直连访问服务的gfwlist源。
另外，即使使用的全局或非中国列表代理模式，想排除微软服务，也应该由你们自己去维护这个域名列表，手动添加到direct_host列表，或者搜索网上有没有现成的维护各个网络公司服务域名的列表，然后订阅到中国域名列表。
你的直连域名遗漏了登录服务，可以继续想办法抓包出来，或者到网上搜索，最多到discussion发求助贴，看有没有人能提供适当帮助或有效信息。
