### ISSUE TITLE
[Bug]:nftset inet fw4 passwall_shuntlist netlink 报错的原因猜想

### ISSUE THREAD

**Issue by pmkol** [xiaorouji/openwrt-package#3166]
### 描述您遇到的bug

daemon.err dnsmasq[29]: nftset inet fw4 passwall_shuntlist netlink: Error: cache initialization failed: Protocol error
daemon.err dnsmasq[1]: nftset inet fw4 passwall_shuntlist netlink: Error: Could not process rule: Invalid argument

上述这两个报错应该是老问题了，今天在测试分流规则时，无意发现只出现了两条，而不是之前会连续出现很多条，猜测出了一个引起报错的原因，作者可以测试一下。

---

猜测这个报错可能是二次分流导致的，这里拿trojan代理举例：

当用户使用xray分流时，某条分流规则里选择了走torjan代理，实际上torjan会受到passwall自带的分流规则影响，也就是说当xray分流后，同时又要经过passwall的规则再次分流，很大概率是这里造成的冲突。

之前我虽然把passwall的规则改成了全局代理，但实际上dnsmasq与nft还是会加载一些分流名单，而我今天整理规则时，正好清空了几个名单，这时报错的数量就减少了，这就是我得出这个推测的点。

而之所以有些人无法复现这个BUG，是因为他们都使用了passwall的分流，而没有使用xray或sing-box的分流，所以复现不了。

作者可以测试一下，因为目前即使我将分流名单清空并使用全局，passwall貌似还是会加载一些规则，所以我这里没法继续测试来证实猜测。

如果测试确定是这个问题导致的，只需要当用户选择使用xray或sing-box分流时，passwall自动走全局代理不再加载任何规则就可以解决了。

### 复现此Bug的步骤

使用nftables+xray分流

### 您想要实现的目的

-

### 日志信息

daemon.err dnsmasq[29]: nftset inet fw4 passwall_shuntlist netlink: Error: cache initialization failed: Protocol error
daemon.err dnsmasq[1]: nftset inet fw4 passwall_shuntlist netlink: Error: Could not process rule: Invalid argument

### 系统相关信息

-

**Comment by xcyll** [comment]
OpenWrt **:** 23.05-SNAPSHOT r0-e444075
PW **:** 4.77-5
未开启分流 V6代理 未用chinadns-ng

**Comment by xcyll** [comment]
OpenWrt **:** 23.05-SNAPSHOT r0-e444075
PW **:** 4.77-5
未开启分流 & V6代理 未启用chinadns-ng

**Comment by xcyll** [comment]
再次出现
```
Thu May  2 10:48:37 2024 daemon.err dnsmasq[12]: nftset inet fw4 passwall_whitelist netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6
Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:38 2024 daemon.err dnsmasq[17]: nftset inet fw4 passwall_whitelist Error: Could not process rule: File exists
Thu May  2 10:48:38 2024 daemon.err dnsmasq[20]: nftset inet fw4 passwall_chnroute Error: Could not process rule: File exists
Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Invalid argument
Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
Thu May  2 10:48:47 2024 daemon.err dnsmasq[40]: nftset inet fw4 passwall_chnroute6 Error: Could not process rule: File exists
Thu May  2 10:48:47 2024 daemon.err dnsmasq[46]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error

**Comment by pmkol** [comment]
> 再次出现
> 
> ```
> Thu May  2 10:48:37 2024 daemon.err dnsmasq[12]: nftset inet fw4 passwall_whitelist netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[18]: nftset inet fw4 passwall_whitelist6 netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[17]: nftset inet fw4 passwall_whitelist Error: Could not process rule: File exists
> Thu May  2 10:48:38 2024 daemon.err dnsmasq[20]: nftset inet fw4 passwall_chnroute Error: Could not process rule: File exists
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Invalid argument
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[41]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[40]: nftset inet fw4 passwall_chnroute6 Error: Could not process rule: File exists
> Thu May  2 10:48:47 2024 daemon.err dnsmasq[46]: nftset inet fw4 passwall_chnroute netlink: Error: cache initialization failed: Protocol error
> ```

你自己测不出来的，passwall即使开全局，关掉加载自定义规则，还是会向防火墙里写东西，只能等作者或者有插件开发能力的用户验证下
