### ISSUE TITLE
[Bug]: S99passwall: Error: Could not process rule: No such file or directory

### ISSUE THREAD

**Issue by maxy1** [xiaorouji/openwrt-package#3171]
### 描述您遇到的bug

Hello, Its trying to add a rule but says file not found.

### 复现此Bug的步骤

System Log

### 您想要实现的目的

To fix the error. 

### 日志信息

`Sat May  4 03:26:15 2024 cron.err crond[3919]: crond (busybox 1.36.1) started, log level 5
Sat May  4 03:26:22 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 03:26:22 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_DIVERT meta l4proto tcp socket transparent 1 mark set 1 counter accept
Sat May  4 03:26:22 2024 daemon.notice procd: /etc/rc.d/S99passwall:                                               ^^^^^^^^^^^^^^^^^^
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_MANGLE ip protocol udp iif lo counter meta mark 1 tproxy ip to :1041 comment "本机"
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall:                                                                         ^^^^^^^^^^^^^^^^^^
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_MANGLE ip protocol udp counter meta mark 1 tproxy ip to :1041 comment "默认"
Sat May  4 03:26:23 2024 daemon.notice procd: /etc/rc.d/S99passwall:                                                                  ^^^^^^^^^^^^^^^^^^
Sat May  4 03:26:28 2024 cron.err crond[5401]: crond (busybox 1.36.1) started, log level 5`

### 截图

![3Capture](https://github.com/xiaorouji/openwrt-passwall/assets/22884474/cd34c7d6-085c-4b2d-86c5-51cc60e726fe)
![Capture](https://github.com/xiaorouji/openwrt-passwall/assets/22884474/0fafff18-8292-46a8-b1c0-925216ca93e9)

### 系统相关信息
Architecture | Intel(R) Celeron(R) CPU N2840 @ 2.16GHz x 2C 2T (554.117MHz, 40.0°C) Target Platform | x86/64 Firmware Version | ImmortalWrt 23.05.0-rc3 r26804-a3639e76d6 / LuCI openwrt-23.05 branch git-23.159.69121-0052e9f Kernel Version | 5.15.120 
Passwall Version  4.76-4

**Comment by ShanStone** [comment]
please install kmod-nft-socket kmod-nft-tproxy kmod-nft-nat

**Comment by maxy1** [comment]
> please install kmod-nft-socket kmod-nft-tproxy kmod-nft-nat

Thank you. I installed it after that I got few boot loading erros. so I reinstalled it with  
install ipt2socks. it seems fixed.

**Comment by maxy1** [comment]
I am sorry I replied too soon. It didn't fix the issue. 
I installed 
kmod-nft-socket 
kmod-nft-tproxy 
kmod-nft-nat

But after a reboot system stops with error message 
`kmodloader: failed to mmap /lib/modules/ nf_socket_ipv4.ko
kmodloader: invalid endianess : 0

kmodloader: invalid endianess : 0
kmodloader: failed to load the .modinfo section from /lib/modules/5.127/nf_tproxy_ipv4.ko
kmodloader: invalid endianess : 0
kmodloader: failed to load the .modinfo section from /lib/modules/5.127/nf_tproxy_ipv6.ko
kmodloader: invalid endianess : 0
kmodloader: failed to load the .modinfo section from /lib/modules/5.127/nft_tproxy.ko`

My Architecture is x86/64

How to fix the issue ?

**Comment by ShanStone** [comment]
kernel modules doesn't match you kernel version, try to prebuild kernel modules in the firmware
https://firmware-selector.immortalwrt.org/
![2024-05-05](https://github.com/xiaorouji/openwrt-passwall/assets/31815718/dd9ba5bf-3eee-4a92-8702-932b258cb25c)

**Comment by maxy1** [comment]
Thank you. How do I add the luci-app-passwall_4.76-4 to the same build?

**Comment by ShanStone** [comment]
wait for update from immortalwrt software source，or download the ipk from gitHub，then install it manually
ref: https://github.com/xiaorouji/openwrt-passwall/issues/2489

**Comment by maxy1** [comment]
> wait for update from immortalwrt software source，or download the ipk from gitHub，then install it manually ref: #2489

Hi, I need to do fresh install but need old version of passwall. If I put luci-app-passwall in to build config Its adding the latest version. But how do I add old version of passwall to the build? Or is not possible to add old version ? and if I want old version I have to do it manually ?

**Comment by ShanStone** [comment]
> > wait for update from immortalwrt software source，or download the ipk from gitHub，then install it manually ref: #2489
> 
> Hi, I need to do fresh install but need old version of passwall. If I put luci-app-passwall in to build config Its adding the latest version. But how do I add old version of passwall to the build? Or is not possible to add old version ? and if I want old version I have to do it manually ? 

if you want to use specific old version of passwall,you have to install luci-app-passwall manually, passwall in the firmware is the lastest by default.

**Comment by maxy1** [comment]
Hi, Ok got it. 
Thank you. 

One more question. 

If I add luci-app-passwall in to build config Its adding all the packages such as

`-shadowsocks-libev-ss-server.
-shadowsocksr-libev-ssr-redir.
-shadowsocks-libev-ss-redir.
-shadowsocksr-libev-ssr-local.
-shadowsocks-libev-ss-local.`

But I am not using them. What I am using is Xray and Sing-Box. Is there anyway to stop adding shadowsocks ?

**Comment by ShanStone** [comment]
> Hi, Ok got it. 
> Thank you. 
> 
> One more question. 
> 
> If I add luci-app-passwall in to build config Its adding all the packages such as
> 
> `-shadowsocks-libev-ss-server.
> -shadowsocksr-libev-ssr-redir.
> -shadowsocks-libev-ss-redir.
> -shadowsocksr-libev-ssr-local.
> -shadowsocks-libev-ss-local.`
> 
> But I am not using them. What I am using is Xray and Sing-Box. Is there anyway to stop adding shadowsocks ?

all of this packages can be configured,
run command "make menuconfig"
Then go to Luci application luci-app-passwall, unselect the packages you don't want.
Or modify .conf to unselected packages, ref: https://github.com/xiaorouji/openwrt-passwall/blob/main/.github/workflows/Auto%20compile%20with%20openwrt%20sdk.yml

**Comment by maxy1** [comment]
> > Hi, Ok got it.
> > Thank you.
> > One more question.
> > If I add luci-app-passwall in to build config Its adding all the packages such as
> > `-shadowsocks-libev-ss-server. -shadowsocksr-libev-ssr-redir. -shadowsocks-libev-ss-redir. -shadowsocksr-libev-ssr-local. -shadowsocks-libev-ss-local.`
> > But I am not using them. What I am using is Xray and Sing-Box. Is there anyway to stop adding shadowsocks ?
> 
> all of this packages can be configured, run command "make menuconfig" Then go to Luci application luci-app-passwall, unselect the packages you don't want. Or modify .conf to unselected packages, ref: https://github.com/xiaorouji/openwrt-passwall/blob/main/.github/workflows/Auto%20compile%20with%20openwrt%20sdk.yml

Sorry I am very new to this. From where I have to run the make menuconfig ?

**Comment by ShanStone** [comment]
Are you use the web image builder?
https://firmware-selector.immortalwrt.org
Don't add luci-app-passwall to the conf,install the ipk for github and install ipk manually.
