### ISSUE TITLE
[Feature Request]: 建议支持TOR洋葱协议

### ISSUE THREAD

**Issue by gnz1123** [xiaorouji/openwrt-package#3172]
### 描述你想要的新功能

连接代理tor网桥，多个方法多一条出路。

### 描述你想要的解决方案

连接代理tor网桥，多个方法多一条出路。

**Comment by gito10** [comment]
如果某个passwall现有的工具（比如 Xray 或 Sing-Box）支持了Tor 出站，那么添加支持倒也简单。但是现在都没有，要支持Tor的话，得引入新的工具，从头适配，工作量大很多，相比于真正有这个需求的用户数，是划不来的。而且目前应该也都没多余的时间来开发这个。
