### ISSUE TITLE
[Bug]: daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory

### ISSUE THREAD

**Issue by maxy1** [xiaorouji/openwrt-package#3173]
### 描述您遇到的bug

Hi, I have immortalwrt installed on a PC 

`Architecture | Intel(R) Celeron(R) CPU N2840 @ 2.16GHz x 2C 2T (554.117MHz, 40.0°C)
Target Platform | x86/64
Firmware Version | ImmortalWrt 23.05.0-rc3 r26804-a3639e76d6 / LuCI openwrt-23.05 branch git-23.159.69121-0052e9f
Kernel Version | 5.15.120
`

and I installed Passwall on it. Passwall seems be not functioning properly as internet becomes unstable sometimes. So I checked the logs and I see few errors under system logs.  

### 复现此Bug的步骤

Erros can see under logs. 

### 您想要实现的目的

Fix the error 

### 日志信息

`Sat May  4 16:57:25 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 16:57:25 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_DIVERT meta l4proto tcp socket transparent 1 mark set 1 counter accept
Sat May  4 16:57:25 2024 daemon.notice procd: /etc/rc.d/S99passwall:                                               ^^^^^^^^^^^^^^^^^^
Sat May  4 16:57:26 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 16:57:26 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_MANGLE ip protocol udp iif lo counter meta mark 1 tproxy ip to :1041 comment "本机"
Sat May  4 16:57:26 2024 daemon.notice procd: /etc/rc.d/S99passwall:                                                                         ^^^^^^^^^^^^^^^^^^
Sat May  4 16:57:27 2024 daemon.notice procd: /etc/rc.d/S99passwall: Error: Could not process rule: No such file or directory
Sat May  4 16:57:27 2024 daemon.notice procd: /etc/rc.d/S99passwall: add rule inet fw4 PSW_MANGLE ip protocol udp counter meta mark 1 tproxy ip to :1041 comment "默认"
Sat May  4 16:57:27 2024 daemon.notice procd: /etc/rc.d/S99passwall:  `

### 系统相关信息

Passwall Version : 4.76-4 
Platform | x86/64

**Comment by gito10** [comment]
#3171 reopened, close this one.
