### ISSUE TITLE
[Bug]: sing-box在启动项里面是禁止状态

### ISSUE THREAD

**Issue by mmeiwenlong** [xiaorouji/openwrt-package#3174]
### 描述您遇到的bug

sing-box在启动项里面是禁止状态·起用不了

### 复现此Bug的步骤

![QQ截图20240504151920](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/467cf33b-ec42-4f78-9681-415e4bb5a163)

### 您想要实现的目的

相处于启用状态，

### 日志信息

![QQ截图20240504151920](https://github.com/xiaorouji/openwrt-passwall/assets/44661424/485ba3b9-8cd1-4481-8893-6ead2ff2f382)

### 系统相关信息

4.77-5
谷歌浏览器版本 124.0.6367.79（正式版本） （64 位）

**Comment by gito10** [comment]
passwall本来就只用到sing-box的可执行程序，你说的是sing-box包自带的配置没有开启自启动，与passwall毫无关系，这些东西都不用管。
