### ISSUE TITLE
最新的smartdns版本的疑问

### ISSUE THREAD

**Issue by jxph1123** [xiaorouji/openwrt-package#3175]
### 描述您遇到的bug

同样的设置，之前版本使用 IP111测试，从国外测试是我的代理地址，如图：
![下载 (4)](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/4ce5706d-2ab1-4c92-8180-86365a829994)
目前版本 [151dfa8aff0505d6819645693b0abb3676c04945](https://github.com/xiaorouji/openwrt-passwall/commit/151dfa8aff0505d6819645693b0abb3676c04945) 使用ip111测试，从国外测试变成 中国地址了，如题：
![下载 (5)](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/0a7698a6-03d9-4f1a-bccc-37b108d06dd6)
设置没变，如下：
![下载 (7)](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/76e7cc21-669d-4843-ab76-c600aac68a73)
![下载 (6)](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/c0c43b7b-e1e4-4e12-8425-fd56673e003c)

我猜测之前版本是默认采用远程DNS模式，目前版本默认直连DNS模式？类似下面设置，我设置成直连DNS时，使用ip111测试，从国外测试是 中国地址，设置成远程DNS时，使用ip111测试，从国外测试是我的代理地址。。是否smartdns版本需要加一个直连NDS和远程DNS选项？
![image](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/8e3e5505-2f0e-4ca5-b038-9fbcae877079)

### 复现此Bug的步骤

采用4.77-3-smartdns-dev版本和目前版本可以复现

### 您想要实现的目的

是否smartdns版本需要加一个直连NDS和远程DNS选项？

### 日志信息

2024-05-05 11:01:19: 清空并关闭相关程序和缓存完成。
2024-05-05 11:01:20: TCP节点：[负载均衡-Xray]，监听端口：1041
2024-05-05 11:01:20: DNS域名解析：
2024-05-05 11:01:20:   - 节点列表中的域名(vpslist)使用分组：cn
2024-05-05 11:01:20:   - 域名白名单(whitelist)使用分组：cn
2024-05-05 11:01:20:   - 代理域名表(blacklist)使用分组：passwall_proxy
2024-05-05 11:01:21:   - 防火墙域名表(gfwlist)使用分组：passwall_proxy
2024-05-05 11:01:26:   - 中国域名表(chnroute)使用分组：cn
2024-05-05 11:01:26:   - 请让SmartDNS作为Dnsmasq的上游或重定向！
2024-05-05 11:01:27:   - 域名解析：使用SmartDNS，请确保配置正常。
2024-05-05 11:01:27: 开始加载防火墙规则...
2024-05-05 11:01:28:   - [0]追加ISP IPv4 DNS到白名单：XXXX
2024-05-05 11:01:28:   - [0]追加ISP IPv4 DNS到白名单：XXXX
2024-05-05 11:01:28:   - [0]追加ISP IPv6 DNS到白名单：XXXX
2024-05-05 11:01:28:   - [0]追加ISP IPv6 DNS到白名单：XXXX
2024-05-05 11:01:28: 加入负载均衡的节点到ipset[passwall_vpslist]直连完成
2024-05-05 11:01:28: 加入所有节点到ipset[passwall_vpslist]直连完成
2024-05-05 11:01:42:   - [0]追加直连DNS到iptables：127.0.0.1:6053
2024-05-05 11:01:56:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-05-05 11:02:15:   - 【默认】，屏蔽代理 UDP 端口[443]
2024-05-05 11:02:20:   - 【默认】，使用 TCP 节点[负载均衡-Xray](TPROXY:1041)
2024-05-05 11:02:25:   - 【默认】，使用 UDP 节点[负载均衡-Xray](TPROXY:1041)
2024-05-05 11:02:25: 防火墙规则加载完成！
2024-05-05 11:02:29: 重启 dnsmasq 服务
2024-05-05 11:02:29: 运行完成！

### 系统相关信息

 [151dfa8aff0505d6819645693b0abb3676c04945](https://github.com/xiaorouji/openwrt-passwall/commit/151dfa8aff0505d6819645693b0abb3676c04945)

**Comment by wtfr-dot** [comment]
你的日志信息把运营商的dns暴露了，快改一下。
你远程dns组排除了默认组，passwall这边默认直连的话，只要没在gfw或者代理规则内的域名都会走直连

**Comment by jxph1123** [comment]
> 你的日志信息把运营商的dns暴露了，快改一下。 你远程dns组排除了默认组，passwall这边默认直连的话，只要没在gfw或者代理规则内的域名都会走直连

我的smartdns默认组都是国外DNS，之前版本应该是CN直连，其余没在CN内的都会走代理，最近这个版本好像变了。我smartdns和passwall设置都没变过。

**Comment by wtfr-dot** [comment]
> > 你的日志信息把运营商的dns暴露了，快改一下。 你远程dns组排除了默认组，passwall这边默认直连的话，只要没在gfw或者代理规则内的域名都会走直连
> 
> 我的smartdns默认组都是国外DNS，之前版本应该是CN直连，其余没在CN内的都会走代理，最近这个版本好像变了。我smartdns和passwall设置都没变过。

passwall这边增加了排除默认组这个选项，你勾选了，所以它不是默认组了，smartdns那里只需要设国内组，这样的话，不在代理范围的域名就会走国内组直连

**Comment by jxph1123** [comment]
> 
> passwall这边增加了排除默认组这个选项，你勾选了，所以它不是默认组了，smartdns那里只需要设国内组，这样的话，不在代理范围的域名就会走国内组直连

不是这样的，排除默认组只是排除了1.1.1.1那些自定义的DNS服务器排除出默认组。smartdns那里设了国内组，应该是国内列表走国内组，其他非国内列表全部走代理（包括未识别国内国外的都走代理组）。
我前面描述了的，passwall不一样的版本，我同样的配置，ip111 出现了不一样的结果。

**Comment by wtfr-dot** [comment]
> > passwall这边增加了排除默认组这个选项，你勾选了，所以它不是默认组了，smartdns那里只需要设国内组，这样的话，不在代理范围的域名就会走国内组直连
> 
> 不是这样的，排除默认组只是排除了1.1.1.1那些自定义的DNS服务器排除出默认组。smartdns那里设了国内组，应该是国内列表走国内组，其他非国内列表全部走代理（包括未识别国内国外的都走代理组）。 我前面描述了的，passwall不一样的版本，我同样的配置，ip111 出现了不一样的结果。

因为你passwall这里默认dns选的直连，也就是没在代理范围内的域名走直连，即就是走smartdns的国内组，而不是走代理组，你默认dns需要选远程才能达到你想要的效果，另外需要在直连列表里把cn域名加进去，否则很多国内域名会走远程解析

**Comment by jxph1123** [comment]
> 因为你passwall这里默认dns选的直连，也就是没在代理范围内的域名走直连，即就是走smartdns的国内组，而不是走代理组，你默认dns需要选远程才能达到你想要的效果，另外需要在直连列表里把cn域名加进去，否则很多国内域名会走远程解析


之前版本的逻辑应该是对的，我DNS模式里面选的是 `中国列表``直连`，应该是`中国列表`是`直连`，`中国列表以外`是`代理`，目前的版本逻辑好像变了。
![下载 (4)](https://github.com/xiaorouji/openwrt-passwall/assets/35351787/98351dc0-6737-41c9-9791-59e43b83c67f)

**Comment by wtfr-dot** [comment]
> > 因为你passwall这里默认dns选的直连，也就是没在代理范围内的域名走直连，即就是走smartdns的国内组，而不是走代理组，你默认dns需要选远程才能达到你想要的效果，另外需要在直连列表里把cn域名加进去，否则很多国内域名会走远程解析
> 
> 之前版本的逻辑应该是对的，我DNS模式里面选的是 `` 中国列表``直连 ``，应该是`中国列表`是`直连`，`中国列表以外`是`代理`，目前的版本逻辑好像变了。 ![下载 (4)](https://private-user-images.githubusercontent.com/35351787/328168221-98351dc0-6737-41c9-9791-59e43b83c67f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTY4NzYsIm5iZiI6MTcxNDk5NjU3NiwicGF0aCI6Ii8zNTM1MTc4Ny8zMjgxNjgyMjEtOTgzNTFkYzAtNjczNy00MWM5LTk3OTEtNTllNDNiODNjNjdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExNTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTdhMWUzYzExODFlZWMwYTIzM2QwNDE4MjdkZDM5NGZlMTA4ODE0ZWU1MjZiOTFkMmNhNWVkZjlmZmI1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aBP3RrOnozyQsG-QL7fVR8z7kp-f472iA6W5wNtqP5s)

这个地方并不是针对dns设置的，下面这个才是
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/6ba03f76-c369-4c97-be3d-4adaa15e1f34)

其实配合smartdns可以用原来的老办法了，用udp连smartdns的第二服务器组

**Comment by jxph1123** [comment]
> 其实配合smartdns可以用原来的老办法了，用udp连smartdns的第二服务器组

这个我知道，但是用smartdns那个设置更友好点，我只是反馈下和之前版本的区别，大佬能随手修复一波就更好了。

**Comment by uingei** [comment]
有个疑问，既然 53 853 443 端口都是默认转发的，DNS 也在代理列表里，smartdns 自动配置 proxy-server 是不是有点多余了

**Comment by wtfr-dot** [comment]
以前smartdns是没有这些选项，passwall也没有监听tcp端口的选择，同样可以走代理解析dns，设置的方法不同而已，代码是不断完善的，功能也不断增多，弄懂原理你可以自己选择怎么用，比如我现在passwall就没用smartdns分支，用主分支实现同样的功能

**Comment by jackiezhang29** [comment]
> > > 因为你passwall这里默认dns选的直连，也就是没在代理范围内的域名走直连，即就是走smartdns的国内组，而不是走代理组，你默认dns需要选远程才能达到你想要的效果，另外需要在直连列表里把cn域名加进去，否则很多国内域名会走远程解析
> > 
> > 
> > 之前版本的逻辑应该是对的，我DNS模式里面选的是 ` 中国列表`直连 ``，应该是`中国列表`是`直连`，`中国列表以外`是`代理`，目前的版本逻辑好像变了。 ![下载 (4)](https://private-user-images.githubusercontent.com/35351787/328168221-98351dc0-6737-41c9-9791-59e43b83c67f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTY4NzYsIm5iZiI6MTcxNDk5NjU3NiwicGF0aCI6Ii8zNTM1MTc4Ny8zMjgxNjgyMjEtOTgzNTFkYzAtNjczNy00MWM5LTk3OTEtNTllNDNiODNjNjdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExNTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTdhMWUzYzExODFlZWMwYTIzM2QwNDE4MjdkZDM5NGZlMTA4ODE0ZWU1MjZiOTFkMmNhNWVkZjlmZmI1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aBP3RrOnozyQsG-QL7fVR8z7kp-f472iA6W5wNtqP5s)
> 
> 这个地方并不是针对dns设置的，下面这个才是 ![image](https://private-user-images.githubusercontent.com/81218740/328170545-6ba03f76-c369-4c97-be3d-4adaa15e1f34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Nzk2NjIsIm5iZiI6MTcxNjQ3OTM2MiwicGF0aCI6Ii84MTIxODc0MC8zMjgxNzA1NDUtNmJhMDNmNzYtYzM2OS00Yzk3LWJlM2QtNGFkYWExNWUxZjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1NDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNzQzOWI4Y2EzYWVlYmU5MTg2N2U3N2QxOTNhNWIzZmM3YmRiNTM1ZGExM2NmOWMzODY3ZjVhYThkYmUzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFstdfcIoBTYkZc1_VTekCStjkkqFmG9oa9ODIJAMps)
> 
> 其实配合smartdns可以用原来的老办法了，用udp连smartdns的第二服务器组

我想请教一下，那个过滤代理域名ipv6，打勾和不打勾的区别是啥，找了很多资料，都没有非常确切的表达

**Comment by gito10** [comment]
>我想请教一下，那个过滤代理域名ipv6，打勾和不打勾的区别是啥，找了很多资料，都没有非常确切的表达

直接举个例吧，比如想把 **bing.com**加到代理列表让Bing走代理访问国际版，在不开启IPv6 透明代理（比如节点不支持等原因）情况下，如果不开启 **过滤代理域名IPv6**，浏览器请求时会得到2个IPv4地址和2个IPv6地址，通常浏览器会优先选择IPv6地址来发起连接，那么就会变成IPv6直连。
因为Bing 本来国内就可以直连访问，所以Bing检测到你的IPv6地址是中国的，就会跳转 **cn.bing.com**。而开启过滤，就会把结果中IPv6地址去掉再返回给客户端，对于Bing来说，浏览器只能拿到IPv4地址，就只能走代理访问Bing。（如果是IPv6单栈的服务器，就只能返回空结果，无法访问服务）
换成其他被墙网站，估计会有一个优先尝试IPv6地址，不通然后使用IPv4地址连接的过程（猜测）。但是如果服务器支持HTTP3，也许可以IPv6 QUIC 直连。去年还是前年，不过滤IPv6的话，看YouTube，可以IPv6+QUIC直连 **googlevideo.com**，加载视频不消耗代理节点流量，速度还快。今年没试过，估计不行了。

**Comment by jackiezhang29** [comment]
> > 我想请教一下，那个过滤代理域名ipv6，打勾和不打勾的区别是啥，找了很多资料，都没有非常确切的表达
> 
> 直接举个例吧，比如想把 **bing.com**加到代理列表让Bing走代理访问国际版，在不开启IPv6 透明代理（比如节点不支持等原因）情况下，如果不开启 **过滤代理域名IPv6**，浏览器请求时会得到2个IPv4地址和2个IPv6地址，通常浏览器会优先选择IPv6地址来发起连接，那么就会变成IPv6直连。 因为Bing 本来国内就可以直连访问，所以Bing检测到你的IPv6地址是中国的，就会跳转 **cn.bing.com**。而开启过滤，就会把结果中IPv6地址去掉再返回给客户端，对于Bing来说，浏览器只能拿到IPv4地址，就只能走代理访问Bing。（如果是IPv6单栈的服务器，就只能返回空结果，无法访问服务） 换成其他被墙网站，估计会有一个优先尝试IPv6地址，不通然后使用IPv4地址连接的过程（猜测）。但是如果服务器支持HTTP3，也许可以IPv6 QUIC 直连。去年还是前年，不过滤IPv6的话，看YouTube，可以IPv6+QUIC直连 **googlevideo.com**，加载视频不消耗代理节点流量，速度还快。今年没试过，估计不行了。

那如果我使用了mosdns或者smartdns，在海外dns设置了禁用ipv6解析的话，同时，passwall设置了中国列表以外，是不是这个功能开与否的意义就不大了？

**Comment by gito10** [comment]
>那如果我使用了mosdns或者smartdns，在海外dns设置了禁用ipv6解析的话，同时，passwall设置了中国列表以外，是不是这个功能开与否的意义就不大了？

是把passwall的远程DNS设置为mosdns或者smartdns的监听地址吗，如果上游dns本身有过滤功能，确实passwall可以不开。
不过也看dns分流是dnsmasq还是dnsmasq+chinadns-ng。dnsmasq实际上不支持过滤，而是使用全0替换。如果是chinadns-ng，可以对比测试下由chinadns-ng过滤和mosdns/smartdns过滤在dns解析速度、内存占用等方面哪个方案更优。

**Comment by jackiezhang29** [comment]
> > 那如果我使用了mosdns或者smartdns，在海外dns设置了禁用ipv6解析的话，同时，passwall设置了中国列表以外，是不是这个功能开与否的意义就不大了？
> 
> 是把passwall的远程DNS设置为mosdns或者smartdns的监听地址吗，如果上游dns本身有过滤功能，确实passwall可以不开。 不过也看dns分流是dnsmasq还是dnsmasq+chinadns-ng。dnsmasq实际上不支持过滤，而是使用全0替换。如果是chinadns-ng，可以对比测试下由chinadns-ng过滤和mosdns/smartdns过滤在dns解析速度、内存占用等方面哪个方案更优。

我直接就使用了dnsmasq，劫持了5335端口，所有的远程交给mosdns处理，但在使用过程中，一旦使用smartdns第二服务器处理远程DNS，会出现DNS泄漏的问题

**Comment by uingei** [comment]
> > > 那如果我使用了mosdns或者smartdns，在海外dns设置了禁用ipv6解析的话，同时，passwall设置了中国列表以外，是不是这个功能开与否的意义就不大了？
> > 
> > 
> > 是把passwall的远程DNS设置为mosdns或者smartdns的监听地址吗，如果上游dns本身有过滤功能，确实passwall可以不开。 不过也看dns分流是dnsmasq还是dnsmasq+chinadns-ng。dnsmasq实际上不支持过滤，而是使用全0替换。如果是chinadns-ng，可以对比测试下由chinadns-ng过滤和mosdns/smartdns过滤在dns解析速度、内存占用等方面哪个方案更优。
> 
> 我直接就使用了dnsmasq，劫持了5335端口，所有的远程交给mosdns处理，但在使用过程中，一旦使用smartdns第二服务器处理远程DNS，会出现DNS泄漏的问题

可能是 smartdns 有问题，自从 smartdns 升级到 snapshot 好像没出现过 DNS 泄露

**Comment by wtfr-dot** [comment]
> > > > 那如果我使用了mosdns或者smartdns，在海外dns设置了禁用ipv6解析的话，同时，passwall设置了中国列表以外，是不是这个功能开与否的意义就不大了？
> > > 
> > > 
> > > 是把passwall的远程DNS设置为mosdns或者smartdns的监听地址吗，如果上游dns本身有过滤功能，确实passwall可以不开。 不过也看dns分流是dnsmasq还是dnsmasq+chinadns-ng。dnsmasq实际上不支持过滤，而是使用全0替换。如果是chinadns-ng，可以对比测试下由chinadns-ng过滤和mosdns/smartdns过滤在dns解析速度、内存占用等方面哪个方案更优。
> > 
> > 
> > 我直接就使用了dnsmasq，劫持了5335端口，所有的远程交给mosdns处理，但在使用过程中，一旦使用smartdns第二服务器处理远程DNS，会出现DNS泄漏的问题
> 
> 可能是 smartdns 有问题，自从 smartdns 升级到 snapshot 好像没出现过 DNS 泄露

dns泄漏跟smartdns无关，看我的issue#3216
