### ISSUE TITLE
[Feature Request]: 增加新的订阅设置项

### ISSUE THREAD

**Issue by ChienHoWee** [xiaorouji/openwrt-package#3182]
### 描述你想要的新功能

能否在“节点订阅”里面新增一个Singbox默认的“域名解析策略”设置项，目前拉取订阅后默认是ipv6优先，但经常需要用到ipv4优先，每一个节点都要进去重新设置有点麻烦。

### 描述你想要的解决方案

在“订阅设置”里增加手动设置Singbox的“域名解析策略”的选项。

**Comment by gito10** [comment]
刚看了一下 订阅部分代码，增加这个比较简单。

我拿手机版 NekoBox 对比了下，NekoBox 每个节点的具体设置里面没有域名解析策略，只有在App设置里面有一个总的选项来控制所有。
我就在想，是否一样可以采用在高级设置的 Sing-Box 设置里增加一项 **服务器域名解析策略**，作为默认配置。而每个节点默认是不设这一选项，采用高级设置里设置的值。但也保留每个节点单独的设置，可以设为不同于默认值的其他策略。

看你描述，难不成很多节点都是提供双栈接入吗，而且有些需要IPv6优先，有些需要IPv4优先？这样的话，就不是订阅设置的总设置里添加这一项，而是每个订阅都需要单独的 **域名解析策略** 设置。

**Comment by lwb1978** [comment]
NeKoBox比passwall多个“自动”选项，不知道sing-box是否支持这个参数，如果支持的话建议passwall加上自动的选项并设为默认值。
@nftbty

**Comment by ChienHoWee** [comment]
> 刚看了一下 订阅部分代码，增加这个比较简单。
> 
> 我拿手机版 NekoBox 对比了下，NekoBox 每个节点的具体设置里面没有域名解析策略，只有在App设置里面有一个总的选项来控制所有。 我就在想，是否一样可以采用在高级设置的 Sing-Box 设置里增加一项 **服务器域名解析策略**，作为默认配置。而每个节点默认是不设这一选项，采用高级设置里设置的值。但也保留每个节点单独的设置，可以设为不同于默认值的其他策略。
> 
> 看你描述，难不成很多节点都是提供双栈接入吗，而且有些需要IPv6优先，有些需要IPv4优先？这样的话，就不是订阅设置的总设置里添加这一项，而是每个订阅都需要单独的 **域名解析策略** 设置。

可能我的话有些让你误解，我所想要实现的功能就是你的这句：“我就在想，是否一样可以采用在高级设置的 Sing-Box 设置里增加一项 **服务器域名解析策略**，作为默认配置。而每个节点默认是不设这一选项，采用高级设置里设置的值。但也保留每个节点单独的设置，可以设为不同于默认值的其他策略。”

**Comment by gito10** [comment]
@lwb1978 我翻了下 [Sing-Box 文档](https://sing-box.sagernet.org/configuration/shared/dial/#domain_strategy)，确实只有4个选项。另外，文档里还有这一句：
>If set, the requested domain name will be resolved to IP before connect.

如果该参数未设置，并不是默认其值为4个选项中的某一个，而是不提前由sing-box自己解析。应该是直接发起连接，由系统DNS进行解析，如果是双栈服务器，最终选择哪个地址也由系统控制。当然这只是根据上面文档那句话推断的，并没有去看源码。

NekoBox的自动不知道是不设置该参数，还是做额外的判断动作来决定设置哪个值。等会我去看看它源码。

---

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/1b022eb2f1d6a939531d8ccdc5b3fa5495f1a2ee/app/src/main/java/moe/matsuri/nb4a/SingBoxOptionsUtil.kt#L10-L28
```kotlin
    fun domainStrategy(tag: String): String {
        fun auto2AsIs(key: String): String {
            return (DataStore.configurationStore.getString(key) ?: "").replace("auto", "")
        }
        return when (tag) {
            "dns-remote" -> {
                auto2AsIs("domain_strategy_for_remote")
            }
            "dns-direct" -> {
                auto2AsIs("domain_strategy_for_direct")
            }
            // server
            else -> {
                auto2AsIs("domain_strategy_for_server")
            }
        }
    }
```
从源码看，应该就是空值，不设置该参数。

**Comment by lwb1978** [comment]
> 从源码看，应该就是空值，不设置该参数。

我也看了sing-box的说明，觉得应该就是空值
https://github.com/SagerNet/sing-box/blob/dev-next/docs/configuration/shared/listen.zh.md?plain=1#L88-L95

`#### domain_strategy

可选值： `prefer_ipv4` `prefer_ipv6` `ipv4_only` `ipv6_only`。

如果设置，请求的域名将在路由之前解析为 IP。

如果 `sniff_override_destination` 生效，它的值将作为后备。`

**Comment by SakuraFallingMad** [comment]
按目前的版本，domain_strategy变成了prefer_ipv6/节点这样的默认赋值，而不是空值。支持在订阅设置里设计个与“跳过证书验证”类似的总开关，`prefer_ipv4` `prefer_ipv6` `ipv4_only` `ipv6_only` `空值`。 以及在节点设置里增加`空值`选项。
