### ISSUE TITLE
[Bug]: 影响tailscale打洞

### ISSUE THREAD

**Issue by hisune** [xiaorouji/openwrt-package#3189]
### 描述您遇到的bug

问题描述：
passwall影响tailscale打洞，而bypass没有这个问题，表现是：打开了passwall开关就无法打洞，关闭立马成功（ping openwrt的IP，关闭后直接降到10+ms的延迟）。

tailscale网络环境：
自建的headscale，服务器在新加坡

尝试了将这台新加坡服务器的IP加入了直连列表，还是不行

### 复现此Bug的步骤

如上

### 您想要实现的目的

开启代理的时候能同时打洞成功

### 日志信息

没有异常日志

### 系统相关信息

passwall版本：git-25.103.55295-cc971fc
tailscale版本：1.58.2-1

**Comment by chazikai24** [comment]
tailscale长时间不用之后，感觉会自动“休眠”。
我这边用之前ping一会，几十秒就延时就讲到10ms左右了。

**Comment by ghost** [comment]
重要的事情說三邊：
關掉路由器自身代理！
關掉路由器自身代理！
關掉路由器自身代理！

這樣就可以正常讓路由器自身安裝的tailscale工作了，在關閉路由器自身代理之前，請確保passwall dns選項是通過dns2socks解析的，不然dns請求就變成不經過代理伺服器了。這不是bug，這是個feature。

**Comment by guochan2019** [comment]
我也同时在用tailscale和passwall，没有你说的问题呀

**Comment by Nicepaul** [comment]
联通线路，去年tailscale打洞一直成功，今年偶尔成功。

**Comment by kxdn3** [comment]
打洞正常的

**Comment by gotodragon** [comment]
一直使用tailscale N年，从tailcale 1.3X的版本，一直到1.66.1的版本，仅tailscale的1.62.1的版本经常掉线，和passwall无关，应该是设置的问题，本结论均为官网服务器非自建headscale服务器，供参考。

**Comment by chazikai24** [comment]
> 一直使用tailscale N年，从tailcale 1.3X的版本，一直到1.66.1的版本，仅tailscale的1.62.1的版本经常掉线，和passwall无关，应该是设置的问题，本结论均为官网服务器非自建headscale服务器，供参考。

1.66版本开始新增了几个参数，两个子网互通需要额外参数 --snat-subnet-routes=false --stateful-filtering=false

**Comment by Nicepaul** [comment]
controlplane.tailscale.com
log.tailscale.io
这两条加入直连

**Comment by fhb302** [comment]
同样存在这个问题，怎么也解决不了，目前路由器本机可以打洞成功，但是下面的设备却不行

**Comment by xkdvSrPD** [comment]
> 同样存在这个问题，怎么也解决不了，目前路由器本机可以打洞成功，但是下面的设备却不行

same
