### ISSUE TITLE
[Bug]: 使用主分支编译的版本连接检测显示0.00ms

### ISSUE THREAD

**Issue by smdx** [xiaorouji/openwrt-package#3190]
### 描述您遇到的bug

使用主分支编译的版本连接检测显示0.00ms，使用luci-smartdns-dev分支编译的版本和passwall2都能正常显示数值

### 复现此Bug的步骤

开启pw后点击百度、google测试

### 您想要实现的目的

能正常显示数值

### 日志信息

OpenWrt R24.5.1 / LuCI Master (git-24.130.56871-0191870)
==================================
Xray 1.8.11 (Xray, Penetrates Everything.) OpenWrt (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
2024/05/10 02:59:05 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall/acl/default/TCP_UDP_SOCKS.json
2024/05/10 02:59:06 [Warning] core: Xray 1.8.11 started

### 截图

![2024-05-10_110653](https://github.com/xiaorouji/openwrt-passwall/assets/9279217/027c8629-3847-4b55-a289-aa253282163a)

![2024-05-10_110640](https://github.com/xiaorouji/openwrt-passwall/assets/9279217/697da43d-9189-4078-8419-7aea066e4ccb)

pw检测:

![2024-05-10_111526](https://github.com/xiaorouji/openwrt-passwall/assets/9279217/e01594d7-42bb-4b85-bd7e-a6d8ba36f679)

pw2检测
![2024-05-10_111535](https://github.com/xiaorouji/openwrt-passwall/assets/9279217/fc8ab213-94d0-4745-98e7-f606fa1ecb5c)

### 系统相关信息

passwall 4.77-5
edge 115.0.1901.203
Cent Browser 5.1.1130.82

**Comment by gito10** [comment]
main 分支和 luci-smartdns-dev 分支都是什么时候编译的，编译时各自位于哪个提交？
按照都是目前最新代码来看，main分支多出的几个提交，并不会引起该问题。

试试更新后删除/tmp目录下的luci缓存，重启passwall，再点看看。

**Comment by smdx** [comment]
main 分支是今天早上编译的，luci-smartdns-dev 分支是上周5

luci缓存是/tmp/luci-indexcache吗？删除了重启pw测试还是一样。

**Comment by mmeiwenlong** [comment]
2024-05-09 21:38:37:   - V2ray/Xray分流规则(ProxyGame)：127.0.0.1#15353
2024-05-09 21:38:37:   - V2ray/Xray分流规则(OpenAI)：127.0.0.1#15353
2024-05-09 21:38:37:   - V2ray/Xray分流规则(Proxy)：127.0.0.1#15353
2024-05-09 21:38:37:   - V2ray/Xray分流规则(Netflix)：127.0.0.1#15353
2024-05-09 21:38:37:   - 默认：127.0.0.1#5333
借道问下，代理不知怎么搞的，这个是走127.0.0.1了吧，搞的测速都是0，现在怎么怎么改回来丫
https://github.com/xiaorouji/openwrt-passwall/issues/3184

**Comment by gito10** [comment]
我刚刚也编译了main分支最新版，装上测试，并没有跟你出现一样的问题。

看你用的op应该也是lean的？那刚好你可以用我刚刚编译的试试，在[我的releases](https://github.com/nftbty/openwrt-passwall/releases)

**Comment by mmeiwenlong** [comment]
> 我刚刚也编译了主分支最新版本，安装上测试，并没有出现同样的问题。
> 
> 你看你用的操作也应该是精益的吗？那正好你可以用我刚刚编译的尝试，在[我的版本中](https://github.com/nftbty/openwrt-passwall/releases)

刚更了还是一样。

**Comment by gito10** [comment]
> 刚更了还是一样。

我是跟题主说的，你的问题，在你提的issue下面我有回复，目前可以确定的是跟你贴的那段日志无关。

你的首页连接测试，是否跟题主一样为0ms？

**Comment by smdx** [comment]
> > 刚更了还是一样。
> 
> 我是跟题主说的，你的问题，在你提的issue下面我有回复，目前可以确定的是跟你贴的那段日志无关。
> 
> 你的首页连接测试，是否跟题主一样为0ms？

你这版本没问题，看了下我用的软件仓库sbwml/openwrt_helloworld 发现根目录下有个passwall的补丁不知道是不是这个的原因，我rm掉它重新编译试试。感谢大佬抽空解答
