### ISSUE TITLE
[Feature Request]: 每隔若干时间自动更新订阅

### ISSUE THREAD

**Issue by LolipopJ** [xiaorouji/openwrt-package#3192]
### 描述你想要的新功能

目前 PassWall 提供的订阅自动更新功能最多支持指定**每天的某个小时时刻**执行：

![luci-app-passwall-auto-update](https://github.com/xiaorouji/openwrt-passwall/assets/42314340/0666e8a3-5dee-485d-bdf5-6e2d5a6f5dff)

但是对于某些经常更换 IP 地址的订阅来说，每天执行一次是不够的，作为用户常常在发现原来的 IP 地址不可用时，手动前往页面执行订阅请求。

因此希望能够提供类似于 `luci-app-openclash` 的选项，**每 N 分钟**循环执行更新订阅。

### 描述你想要的解决方案

`luci-app-openclash` 提供了两种更新模式，一种是每天定时更新；另一种如下图所示，每隔若干分钟更新：

![luci-app-openclash-auto-update](https://github.com/xiaorouji/openwrt-passwall/assets/42314340/c99c8f61-6dc5-4fbd-8c57-8368a830a664)

### 其他信息

目前 PassWall 提供的订阅自动更新功能基于 `crontab`，例如在每天四点执行一次更新订阅操作：

```bash
0 4 * * * lua /usr/share/passwall/subscribe.lua start cfgXXXXXX > /dev/null 2>&1 &
```

在功能追加前，可以手动修改定时任务。例如每 2 小时执行一次更新订阅操作：

```bash
0 */2 * * * lua /usr/share/passwall/subscribe.lua start cfgXXXXXX > /dev/null 2>&1 &
```

但是 PassWall 会管理  `crontab`，删掉所有已有规则再重新写入。因此需要把循环更新订阅的命令写在可执行文件中，再在  `crontab` 中调用。例如：

```bash
0 */2 * * * ~/scripts/auto-update-passwall-sub.sh
```

**Comment by lwb1978** [comment]
这个建议不错，实现难度不大

**Comment by lwb1978** [comment]
![1](https://github.com/xiaorouji/openwrt-passwall/assets/86697442/aabcebcf-59da-44c4-aeb3-3252f5620d5a)
-----------------------
![2](https://github.com/xiaorouji/openwrt-passwall/assets/86697442/176912a5-de12-4f6b-98ce-e749aa83d208)
-----------------------
![3](https://github.com/xiaorouji/openwrt-passwall/assets/86697442/dd2ba423-dbe0-45f1-833b-e3f891061425)
-----------------------
代码修改完成了，等我上个RP完成后再提交新的修改。

**Comment by LolipopJ** [comment]
> 代码修改完成了，等我上个RP完成后再提交新的修改。

Respect！

**Comment by wingswing1** [comment]
> ## ![1](https://private-user-images.githubusercontent.com/86697442/329828119-aabcebcf-59da-44c4-aeb3-3252f5620d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODQ0NTYsIm5iZiI6MTcxNjI4NDE1NiwicGF0aCI6Ii84NjY5NzQ0Mi8zMjk4MjgxMTktYWFiY2ViY2YtNTlkYS00NGM0LWFlYjMtMzI1MmY1NjIwZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YjgyMGY1MWQ1MzUwYjNkZTI2YmExY2UzMjI4Zjc1OTI1NGEwNTQ2ZmUzY2IxOTNlZTY4YTY0ZDJlYmEwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eu_YTIGqjDiCeQwQ0vuGMP1RJhKtlzPuYCFbsmotEz4)
> ## ![2](https://private-user-images.githubusercontent.com/86697442/329828132-176912a5-de12-4f6b-98ce-e749aa83d208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODQ0NTYsIm5iZiI6MTcxNjI4NDE1NiwicGF0aCI6Ii84NjY5NzQ0Mi8zMjk4MjgxMzItMTc2OTEyYTUtZGUxMi00ZjZiLTk4Y2UtZTc0OWFhODNkMjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YTM4YzBhZGZmZWViYzBiZThmNTFmMjBhNzE1NTdjZmVlNWU0YTZhYjg1YjBkMmE5NWFkOTE2NTc1MGMyYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WIIRs0ndBQVN_xIfA_R8shDfpRgXY2Dy2vizcjyJ9GI)
> ## ![3](https://private-user-images.githubusercontent.com/86697442/329828140-dd2ba423-dbe0-45f1-833b-e3f891061425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODQ0NTYsIm5iZiI6MTcxNjI4NDE1NiwicGF0aCI6Ii84NjY5NzQ0Mi8zMjk4MjgxNDAtZGQyYmE0MjMtZGJlMC00NWYxLTgzM2ItZTNmODkxMDYxNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzkxMzQxNjIyZTEzNTAyOTUxNzI4YmM3NWRjZDk3ZmNmYWJhZTY5NjNlNDVmNTVjNmJiMGUyMzBjMGU1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pRON_E04ImBvpny70Tk7Jr0qZji4O6kVnikbYv_io0I)
> 代码修改完成了，等我上个RP完成后再提交新的修改。

那个大神，我记得以前是可以自动切换代理的，现在为什么不支持了呢？？可以修复吗？
