### ISSUE TITLE
[Bug]: 无法订阅sub "/passwall/subscribe.lua:1266: attempt to index upvalue 'debug' (a boolean value)"

### ISSUE THREAD

**Issue by dadaasd0405** [xiaorouji/openwrt-package#3197]
### 描述您遇到的bug
R2s连接猫和路由器。登录R2s的后台，使用OpenWrt的passwall。

 节点订阅时出现问题：` /usr/share/passwall/subscribe.lua:1266: attempt to index upvalue 'debug' (a boolean value)`。添加单个节点无问题，但是节点订阅就会失败，并且此前添加的单个节点也在节点列表中消失，此时节点列表中只显示`Xray 分流：分流总节点`。

### 复现此Bug的步骤

节点订阅-添加-在订阅备注（机场）和SSR/V2RAY订阅URL地址输入相关信息-保存应用-手动更新-保存应用-打开基本设置中总开关-设置TCP,UDP节点-保存应用

### 您想要实现的目的

成功订阅机场节点

### 日志信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/169685689/9dc55e95-b0e4-46a0-b97d-8a223a1ee39a)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/169685689/c5d9ca54-d7ad-4512-b31d-af114146192d)

### 系统相关信息

版本 124.0.6367.119（正式版本） （64 位）
![image](https://github.com/xiaorouji/openwrt-passwall/assets/169685689/b13cfe23-6b3e-4a8a-b040-075ddb330e30)

**Comment by lwb1978** [comment]
先更新到最新版吧，你这个版本都是一年前的了。
