### ISSUE TITLE
[Bug]: 测速单线程只有150mbps左右

### ISSUE THREAD

**Issue by onthehide288** [xiaorouji/openwrt-package#3198]
### 描述您遇到的bug

测速单线程死活上不去，用Windows的v2rayn倒是没这个问题，不会是配置问题，虽然虚拟机，但是配置给的很高了，e5 2696v4给了8个核心了，依然是这样，更低配置的虚拟化Windows下v2rayn是没事的

ps：最新版passwall也是如此
还有就是多线程是随便上千兆甚至两千兆的
但是单线程测速、下载，就是卡在150mbps左右上不去

**Comment by marcuccilli** [comment]
有没有

> ### 描述您遇到的bug
> 测速单线程死活上不去，用Windows的v2rayn倒是没这个问题，不会是配置问题，虽然虚拟机，但是配置给的很高了，e5 2696v4给了8个核心了，依然是这样，更低配置的虚拟化Windows下v2rayn是没事的
> 
> ps：最新版passwall也是如此 还有就是多线程是随便上千兆甚至两千兆的 但是单线程测速、下载，就是卡在150mbps左右上不去

有没有考虑过是ISP限制单线？

**Comment by onthehide288** [comment]
> 有没有
> 
> > ### 描述您遇到的bug
> > 测速单线程死活上不去，用Windows的v2rayn倒是没这个问题，不会是配置问题，虽然虚拟机，但是配置给的很高了，e5 2696v4给了8个核心了，依然是这样，更低配置的虚拟化Windows下v2rayn是没事的
> > ps：最新版passwall也是如此 还有就是多线程是随便上千兆甚至两千兆的 但是单线程测速、下载，就是卡在150mbps左右上不去
> 
> 有没有考虑过是ISP限制单线？

但是v2rayn客户端倒是完全没问题，单线测速比passwall的测速快很多

**Comment by CYWL520** [comment]
老哥方便问下你后来是怎么解决的吗。我现在的问题跟你这个一模一样。谢谢

**Comment by Meilinhost** [comment]
遇到相同问题 有解法吗

**Comment by xkdvSrPD** [comment]
same issue
