### ISSUE TITLE
[Bug]: 访问控制出错 Failed to execute cbi dispatcher target for entry '/admin/services/passwall/acl_config/cfg1330ec

### ISSUE THREAD

**Issue by guhill1** [xiaorouji/openwrt-package#3204]
### 描述您遇到的bug

passwall 访问控制,修改或者添加时出现报错:
/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute cbi dispatcher target for entry '/admin/services/passwall/acl_config/cfg1330ec'.
The called action terminated with an exception:
...ib/lua/luci/model/cbi/passwall/client/acl_config.lua:190: attempt to concatenate local 'TCP_PROXY_DROP_PORTS' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 复现此Bug的步骤

passwall=>访问控制=>添加或者修改

### 您想要实现的目的

修复bug

### 日志信息

/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute cbi dispatcher target for entry '/admin/services/passwall/acl_config/cfg1330ec'.
The called action terminated with an exception:
...ib/lua/luci/model/cbi/passwall/client/acl_config.lua:190: attempt to concatenate local 'TCP_PROXY_DROP_PORTS' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 系统相关信息

Passwall 版本	【 4.77-5 】
浏览器版本 vivaldi 6.7.3329.31 (Stable channel) （64 位） 
firefox 126.0 (64 位)
windows 11 22h2 os内部版本 22.621.3592 64bit

**Comment by gito10** [comment]
按照你的步骤试了下，并不能复现。
而且在GitHub比较活跃的有好几个用户都用访问控制，没有反馈有bug。

**Comment by guhill1** [comment]
> 按照你的步骤试了下，并不能复现。 而且在GitHub比较活跃的有好几个用户都用访问控制，没有反馈有bug。
查了一下"TCP_PROXY_DROP_PORTS"的意思,我大概明白了,
可能我的是从老的passwall升级过来的配置,现在我已经找到了解决办法,访问控制=>先删除所有规则,高级设置=>TCP转发屏蔽端口=>再选择不使用,再保存一下,就解决了.

**Comment by nodexbit32** [comment]
> 按照你的步骤试了下，并不能复现。 而且在GitHub比较活跃的有好几个用户都用访问控制，没有反馈有bug。

查了一下"TCP_PROXY_DROP_PORTS"的意思,我大概明白了,
可能我的是从老的passwall升级过来的配置,找到了解决办法,访问控制=>先删除所有规则,高级设置=>TCP转发屏蔽端口=>再选择不使用,再保存一下,就解决了.

**Comment by crossgg** [comment]
> > 按照你的步骤试了下，并不能复现。 而且在GitHub比较活跃的有好几个用户都用访问控制，没有反馈有bug。
> 
> 查了一下"TCP_PROXY_DROP_PORTS"的意思,我大概明白了, 可能我的是从老的passwall升级过来的配置,找到了解决办法,访问控制=>先删除所有规则,高级设置=>TCP转发屏蔽端口=>再选择不使用,再保存一下,就解决了.

同样的问题，搞定了 谢谢

**Comment by 0x5e** [comment]
+1，同样的问题，解决了
