### ISSUE TITLE
[Bug]: 用潘多拉sdk编译的启动不了？

### ISSUE THREAD

**Issue by 725216** [xiaorouji/openwrt-package#3205]
### 描述您遇到的bug

编译出来的ipk，安装不报错，启动不了

### 复现此Bug的步骤

根本不能启动

### 您想要实现的目的

正常使用

### 日志信息

Fri May 17 18:26:45 2024 daemon.info detect_internet[2092]: Exiting...
Fri May 17 18:26:45 2024 daemon.info detect_internet[2657]: lan_dev:br-lan lan_ip:192.168.1.1 redirect:off
Fri May 17 18:26:45 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: line 277: syntax error: bad substitution
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Received SIGUSR1.
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: pthread_create internet_thread 
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Executing /lib/detect_internet/01-internet_led
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Executing /lib/detect_internet/02-board_internet_led
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Network changed.Start a detect now...
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Executing /lib/detect_internet/01-internet_led
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Turning on LED internet:blue for device eth0.2.
Fri May 17 18:26:46 2024 daemon.info detect_internet[2657]: Executing /lib/detect_internet/02-board_internet_led
Fri May 17 18:26:46 2024 user.notice firewall: Reloading firewall due to ifup of wan (eth0.2)
Fri May 17 18:26:48 2024 cron.info crond[2863]: crond (busybox 1.24.1) started, log level 5
Fri May 17 18:26:48 2024 daemon.info dnsmasq-dhcp[2481]: DHCPREQUEST(br-lan) 192.168.1.101 50:b7:c3:01:f0:5e 
Fri May 17 18:26:48 2024 daemon.info dnsmasq-dhcp[2481]: DHCPACK(br-lan) 192.168.1.101 50:b7:c3:01:f0:5e DESKTOP-INDA4NN
Fri May 17 18:26:48 2024 daemon.info detect_internet[2657]: Received SIGUSR1.
Fri May 17 18:26:49 2024 user.notice ddns-scripts[2924]: 3322: PID '2924' started at 2024-05-17 18:26
Fri May 17 18:26:49 2024 user.warn ddns-scripts[2924]: 3322: Service section disabled! - TERMINATE
Fri May 17 18:26:49 2024 user.warn ddns-scripts[2924]: 3322: PID '2924' exit WITH ERROR '1' at 2024-05-17 18:26
Fri May 17 18:26:49 2024 user.notice firewall: Reloading firewall due to ifup of wan6 (eth0.2)
Fri May 17 18:26:49 2024 daemon.info detect_internet[2657]: Network changed.Start a detect now...
Fri May 17 18:26:54 2024 daemon.err block: /dev/sda1 is already mounted on /mnt/sda1
Fri May 17 18:27:00 2024 daemon.notice procd: /etc/rc.d/S99passwall: /etc/rc.common: line 143: flock: not found
Fri May 17 18:27:00 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: line 277: syntax error: bad substitution
Fri May 17 18:27:00 2024 daemon.notice procd: /etc/rc.d/S99passwall: /usr/share/passwall/app.sh: line 277: syntax error: bad substitution
Fri May 17 18:27:00 2024 daemon.notice procd: /etc/rc.d/S99passwall: /etc/rc.common: line 143: flock: not found
Fri May 17 18:27:01 2024 daemon.notice procd: /etc/rc.d/S99uhttpd: 4+0 records in
Fri May 17 18:27:01 2024 daemon.notice procd: /etc/rc.d/S99uhttpd: 4+0 records out
Fri May 17 18:27:01 2024 daemon.info procd: - init complete -

### 截图

![1](https://github.com/xiaorouji/openwrt-passwall/assets/22210790/b8ac07ae-6e11-423f-a245-328964680ed6)

### 系统相关信息

最新版本

**Comment by hcym** [comment]
官方的最好，其次大雕的

**Comment by ShanStone** [comment]
/etc/rc.common: line 143: flock: not found
你的固件有安装 util-linux吗

**Comment by 725216** [comment]
> 官方的最好，其次大雕的
mtk的，潘多拉得信号好些

**Comment by lwb1978** [comment]
既然会编译怎么不看日志呢？flock: not found，把这个在百度一搜就搜到是没有安装 util-linux

**Comment by 725216** [comment]
> 既然会编译怎么不看日志呢？flock: not found，把这个在百度一搜就搜到是没有安装 util-linux

刚看了潘多拉软件包里没这个ipk

**Comment by 725216** [comment]
> /etc/rc.common: line 143: flock: not found 你的固件有安装 util-linux吗
我在正常用passwall的ImmortalWrt的固件上也没看到这个东西

**Comment by lwb1978** [comment]
'make menuconfig' Base system→busybox→linux system utilities→flock Y
或者直接修改config，找到并修改为：CONFIG_BUSYBOX_CONFIG_FLOCK=y
