### ISSUE TITLE
[Bug]: 添加管理规则后不能启动

### ISSUE THREAD

**Issue by Kuron88** [xiaorouji/openwrt-package#3211]
### 描述您遇到的bug

只要 用使用分流总节点，就会出现这样的情况，不能修改分流的规则，也不能添加，添加了后，要想能启动，就得设置成关闭的状态才可以启动，要是添加或修改了管理规则的任何一个，直接选择开启或者是默认或是节点，就会导致无法启动

### 复现此Bug的步骤

1.添加或者修改openai的域名，或者是添加规则域名都会会无法启动

### 您想要实现的目的

能自由添加或者删除管理规则

### 日志信息

Mon May 20 09:50:32 2024 daemon.info hostapd: wlan1: STA 70:bb:e9:ac:9f:63 WPA: pairwise key handshake completed (RSN)
Mon May 20 09:50:32 2024 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED 70:bb:e9:ac:9f:63
Mon May 20 10:01:00 2024 cron.err crond[15569]: user root: parse error at 7
Mon May 20 10:57:48 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 10:59:07 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 10:59:08 2024 cron.err crond[25988]: crond (busybox 1.36.0) started, log level 5
Mon May 20 10:59:12 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 10:59:22 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 10:59:29 2024 cron.err crond[27939]: crond (busybox 1.36.0) started, log level 5
Mon May 20 11:05:14 2024 daemon.info hostapd: wlan1: STA 50:5a:65:4b:d9:9d IEEE 802.11: authenticated
Mon May 20 11:05:14 2024 daemon.info hostapd: wlan1: STA 50:5a:65:4b:d9:9d IEEE 802.11: associated (aid 5)
Mon May 20 11:05:14 2024 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 50:5a:65:4b:d9:9d auth_alg=open
Mon May 20 11:05:14 2024 daemon.info hostapd: wlan1: STA 50:5a:65:4b:d9:9d RADIUS: starting accounting session 8375C1462C17EF3E
Mon May 20 11:05:14 2024 daemon.info hostapd: wlan1: STA 50:5a:65:4b:d9:9d WPA: pairwise key handshake completed (RSN)
Mon May 20 11:05:14 2024 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED 50:5a:65:4b:d9:9d
Mon May 20 11:19:08 2024 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED f2:dc:ad:f9:00:bf
Mon May 20 11:19:08 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf IEEE 802.11: disassociated due to inactivity
Mon May 20 11:19:09 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Mon May 20 11:54:47 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf IEEE 802.11: authenticated
Mon May 20 11:54:47 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf IEEE 802.11: associated (aid 2)
Mon May 20 11:54:47 2024 daemon.notice hostapd: wlan1: AP-STA-CONNECTED f2:dc:ad:f9:00:bf auth_alg=open
Mon May 20 11:54:47 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf RADIUS: starting accounting session 9788BFD49FC698EF
Mon May 20 11:54:47 2024 daemon.info hostapd: wlan1: STA f2:dc:ad:f9:00:bf WPA: pairwise key handshake completed (RSN)
Mon May 20 11:54:47 2024 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED f2:dc:ad:f9:00:bf
Mon May 20 12:43:14 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:44:35 2024 cron.err crond[30543]: crond (busybox 1.36.0) started, log level 5
Mon May 20 12:44:54 2024 cron.err crond[32420]: crond (busybox 1.36.0) started, log level 5
Mon May 20 12:45:22 2024 cron.err crond[621]: crond (busybox 1.36.0) started, log level 5
Mon May 20 12:45:23 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:45:28 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:45:33 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:45:42 2024 cron.err crond[2452]: crond (busybox 1.36.0) started, log level 5
Mon May 20 12:47:39 2024 cron.err crond[3368]: crond (busybox 1.36.0) started, log level 5
Mon May 20 12:47:40 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:47:45 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 12:47:59 2024 cron.err crond[5312]: crond (busybox 1.36.0) started, log level 5
Mon May 20 14:28:59 2024 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 70:bb:e9:ac:9f:63
Mon May 20 14:28:59 2024 daemon.info hostapd: wlan1: STA 70:bb:e9:ac:9f:63 IEEE 802.11: disassociated due to inactivity
Mon May 20 14:29:00 2024 daemon.info hostapd: wlan1: STA 70:bb:e9:ac:9f:63 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Mon May 20 16:40:43 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:42:06 2024 cron.err crond[12644]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:42:13 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:42:18 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:42:27 2024 cron.err crond[14678]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:42:53 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:43:25 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:43:29 2024 cron.err crond[15693]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:43:35 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:43:40 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:43:49 2024 cron.err crond[17711]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:43:55 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:44:24 2024 cron.err crond[18420]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:44:45 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:44:50 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:44:51 2024 cron.err crond[20553]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:45:04 2024 cron.err crond[21256]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:45:24 2024 cron.err crond[23268]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:47:59 2024 cron.err crond[25280]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:47:59 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:04 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:09 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:14 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:19 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:24 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:48:25 2024 cron.err crond[27561]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:48:48 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:51:17 2024 cron.err crond[28501]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:51:41 2024 cron.err crond[30583]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:51:44 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:52:40 2024 cron.err crond[31638]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:53:04 2024 cron.err crond[1249]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:54:23 2024 cron.err crond[2228]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:54:31 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:54:44 2024 cron.err crond[4369]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:55:00 2024 cron.err crond[4995]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:55:12 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:55:21 2024 cron.err crond[7121]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:55:42 2024 cron.err crond[7808]: crond (busybox 1.36.0) started, log level 5
Mon May 20 16:55:49 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:55:54 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 16:56:02 2024 cron.err crond[9884]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:01:34 2024 cron.err crond[11807]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:01:54 2024 cron.err crond[13910]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:02:08 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:02:21 2024 cron.err crond[14545]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:02:32 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:02:41 2024 cron.err crond[16670]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:04:59 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:05:03 2024 cron.err crond[17714]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:05:09 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:05:39 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:05:45 2024 cron.err crond[19871]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:07:07 2024 cron.err crond[20766]: crond (busybox 1.36.0) started, log level 5
Mon May 20 17:07:39 2024 daemon.err uhttpd[2143]: netstat: showing only processes with your user ID
Mon May 20 17:07:49 2024 cron.err crond[22818]: crond (busybox 1.36.0) started, log level 5

### 截图

![QQ截图20240520170642](https://github.com/xiaorouji/openwrt-passwall/assets/29248355/044f8451-1676-4b15-95aa-f686220ff63e)

### 系统相关信息

Passwall 版本：4.77-5 
Google版本 124.0.6367.119

**Comment by uingei** [comment]
试了下添加 geosite:tiktok 可以正常启动，添加 geosite:tikto 就不行

**Comment by Kuron88** [comment]
我直接把openai这个选项里面添加 geosite:chatgpt.com 和geosite:copilot.microsoft.com后就无法启动，单独添加成一个规则也是不行，我试了passwall和passwall2这2个插件都有这样的问题

**Comment by uingei** [comment]
换成

domain:chatgpt.com
full:copilot.microsoft.com

这样试下

**Comment by Kuron88** [comment]
![QQ截图20240520185914](https://github.com/xiaorouji/openwrt-passwall/assets/29248355/1f3d298f-a5d1-458d-95a8-cbd332f4ead5)
换成这样就其它的都没有问题，就是gpt的官网能登陆，但是gpt回复就出错

**Comment by Kuron88** [comment]
![QQ截图20240520190123](https://github.com/xiaorouji/openwrt-passwall/assets/29248355/eabc8b79-dbb6-49ff-a272-65b581b67e24)
我开始以为是节点的问题，但是我用V2rayN的windows版本试了同一个节点，电脑端的就没有问题

**Comment by SakuraFallingMad** [comment]
> 我直接把openai这个选项里面添加 geosite:chatgpt.com 和geosite:copilot.microsoft.com后就无法启动，单独添加成一个规则也是不行，我试了passwall和passwall2这2个插件都有这样的问题

不是这么填的，geosite是根据[https://github.com/v2fly/domain-list-community](url)里的规则来的，自行添加请根据说明来。

**Comment by wtfr-dot** [comment]
规则管理里面添加规则要按规范来，添加了不支持的格式就会出错，chatgpt我直接添加geosite:openai，打开chatgpt使用一点问题都没有，这种预定义域名表依赖于geosite数据，需要你及时更新数据，默认的下载源数据量不太够，如果你是软路由，建议将规则文件的下载源全部选上，另外你检查一下会不会哪个配置造成的问题，从你描述的bug来看应该是这样的，恢复默认设置重新配置试试

**Comment by SakuraFallingMad** [comment]
> ![QQ截图20240520185914](https://private-user-images.githubusercontent.com/29248355/332041968-1f3d298f-a5d1-458d-95a8-cbd332f4ead5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MjcsIm5iZiI6MTcxNjIwODMyNywicGF0aCI6Ii8yOTI0ODM1NS8zMzIwNDE5NjgtMWYzZDI5OGYtYTVkMS00NThkLTk1YTgtY2JkMzMyZjRlYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWE3Njk4NmNjZmYwMzExM2ZmYzdlZmVhNDgwYWU3OWEwMTFmMzZjOTU3NDZiMDdlMzUwZjZlNGE4NTM2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OuTKbVGxBn1Q7Pdna0O5aPJzH0ECD8NIinhQD87jog) 换成这样就其它的都没有问题，就是gpt的官网能登陆，但是gpt回复就出错

我的使用经验是还要添加geoip:cloudflare，当然还要看你是否是增强库

**Comment by Kuron88** [comment]
> > ![QQ截图20240520185914](https://private-user-images.githubusercontent.com/29248355/332041968-1f3d298f-a5d1-458d-95a8-cbd332f4ead5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MjcsIm5iZiI6MTcxNjIwODMyNywicGF0aCI6Ii8yOTI0ODM1NS8zMzIwNDE5NjgtMWYzZDI5OGYtYTVkMS00NThkLTk1YTgtY2JkMzMyZjRlYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWE3Njk4NmNjZmYwMzExM2ZmYzdlZmVhNDgwYWU3OWEwMTFmMzZjOTU3NDZiMDdlMzUwZjZlNGE4NTM2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OuTKbVGxBn1Q7Pdna0O5aPJzH0ECD8NIinhQD87jog) 换成这样就其它的都没有问题，就是gpt的官网能登陆，但是gpt回复就出错
> 
> 我的使用经验是还要添加geoip:cloudflare，当然还要看你是否是增强库

这个怎么判断是不是增强库

**Comment by SakuraFallingMad** [comment]
> > > ![QQ截图20240520185914](https://private-user-images.githubusercontent.com/29248355/332041968-1f3d298f-a5d1-458d-95a8-cbd332f4ead5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MjcsIm5iZiI6MTcxNjIwODMyNywicGF0aCI6Ii8yOTI0ODM1NS8zMzIwNDE5NjgtMWYzZDI5OGYtYTVkMS00NThkLTk1YTgtY2JkMzMyZjRlYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWE3Njk4NmNjZmYwMzExM2ZmYzdlZmVhNDgwYWU3OWEwMTFmMzZjOTU3NDZiMDdlMzUwZjZlNGE4NTM2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OuTKbVGxBn1Q7Pdna0O5aPJzH0ECD8NIinhQD87jog) 换成这样就其它的都没有问题，就是gpt的官网能登陆，但是gpt回复就出错
> > 
> > 
> > 我的使用经验是还要添加geoip:cloudflare，当然还要看你是否是增强库
> 
> 这个怎么判断是不是增强库

看你更新的geosite与geoip来源说明

**Comment by Kuron88** [comment]
![QQ截图20240520215023](https://github.com/xiaorouji/openwrt-passwall/assets/29248355/0342ee59-e76f-436f-9bc3-01a0ed307214)
我的规则就是自带的这些

**Comment by wtfr-dot** [comment]
我的是这样的，你可以在网上搜
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/6d5c4822-ae9b-488b-a3f1-962f75c73c3b)

**Comment by Kuron88** [comment]
> > ![QQ截图20240520185914](https://private-user-images.githubusercontent.com/29248355/332041968-1f3d298f-a5d1-458d-95a8-cbd332f4ead5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MjcsIm5iZiI6MTcxNjIwODMyNywicGF0aCI6Ii8yOTI0ODM1NS8zMzIwNDE5NjgtMWYzZDI5OGYtYTVkMS00NThkLTk1YTgtY2JkMzMyZjRlYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWE3Njk4NmNjZmYwMzExM2ZmYzdlZmVhNDgwYWU3OWEwMTFmMzZjOTU3NDZiMDdlMzUwZjZlNGE4NTM2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OuTKbVGxBn1Q7Pdna0O5aPJzH0ECD8NIinhQD87jog) 换成这样就其它的都没有问题，就是gpt的官网能登陆，但是gpt回复就出错
> 
> 我的使用经验是还要添加geoip:cloudflare，当然还要看你是否是增强库

你这个QQ截图看不了，不知道你是怎么添加geoip:cloudflare的

**Comment by Kuron88** [comment]
> 我的是这样的，你可以在网上搜 ![image](https://private-user-images.githubusercontent.com/81218740/332091649-6d5c4822-ae9b-488b-a3f1-962f75c73c3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTQ2NDksIm5iZiI6MTcxNjIxNDM0OSwicGF0aCI6Ii84MTIxODc0MC8zMzIwOTE2NDktNmQ1YzQ4MjItYWU5Yi00ODhiLWEzZjEtOTYyZjc1YzczYzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0MTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NzA1OGI3NGZlZTIzNjc1ZjRiM2VmNmUzOTIyY2ZiYTJlNmVmOGIzMjQxMWYwMTBlMDFkNjQ0OWZjOTQ3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhdzIHzMiOvHQYfjgCUxBBTSpz_WcqxU3CGzRn0Zp44)

我也跟你这样设置后，现在gpt也正常使用了，谢谢大佬的指点
