### ISSUE TITLE
更新到6.6.31后出现只有百度检测是通的，其他三项都检测失败，上网正常！[Bug]: 

### ISSUE THREAD

**Issue by seaskyleader** [xiaorouji/openwrt-package#3212]
### 描述您遇到的bug

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 复现此Bug的步骤

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 您想要实现的目的

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 日志信息

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 截图

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 系统相关信息

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

### 其他信息

不知道是什么原因，配置没有问题，退回6.6.30后正常了！！

**Comment by gito10** [comment]
首先，passwall最新版本才4.77-5，没有过6开头的，用的哪里的修改版去对应地方反馈。
其次，issue未认真按照模板填写。

**Comment by 598673A** [comment]
我也遇到了同样的问题，6.6.31应该说的是openwrt的版本，我这边用的是openwrt最新的6.6.62版本编译，也是遇到了这个问题，路由器本机代理无效，但局域网代理正常，用immortalwrt版本的openwrt就没有问题。
