### ISSUE TITLE
[Feature Request]: 节点配置中增加前置节点选项

### ISSUE THREAD

**Issue by Saxon-Sun** [xiaorouji/openwrt-package#3217]
### 描述你想要的新功能

能否在节点配置中增加前置节点选项   
可以直接在自己编辑的节点里选择前置的机场节点，感觉比选落地节点方便（分流里面有 但是想通过节点配置中实现）

### 描述你想要的解决方案

节点配置中增加前置节点选项

**Comment by gito10** [comment]
这个确实，从去年3月修改分流代码的时候就打算改的，然后忘了。
后来xiaorouji 给节点配置加了落地节点，不过这个确实不直观，选节点的时候不能直接看到最终出站节点是哪个。本来今年4月有想着改一下的，不过也因为有其他优先级更高的功能修改搁置了。

我先看看，改动量不大的话，抽时间把这个改了。不过这个改成在主界面直接可以选择的话，节点配置里面的落地节点配置项就可以删掉了吧？

**Comment by Saxon-Sun** [comment]
> 这个确实，从去年3月修改分流代码的时候就打算改的，然后忘了。 后来xiaorouji 给节点配置加了落地节点，不过这个确实不直观，选节点的时候不能直接看到最终出站节点是哪个。本来今年4月有想着改一下的，不过也因为有其他优先级更高的功能修改搁置了。
> 
> 我先看看，改动量不大的话，抽时间把这个改了。不过这个改成在主界面直接可以选择的话，节点配置里面的落地节点配置项就可以删掉了吧？

对，要是能直接能主界面不选择分流节点也能选择前置节点的话会更好的，这样就更直观了，在配置里面选择落地节点确实看不出来，还有就是有些协议的前置节点貌似选了也不能够前置，比如前置选择是trojan 节点选择REALITY，貌似好像根本连接不通不知道啥情况，能前置的节点还有些讲究

**Comment by gito10** [comment]
本来打算把这个改了，就发 4.78-1 的，不过看了下，要改的话还不是个简单事，因为支持前置代理的工具只有Xray 和 Sing-Box，所以直接在节点配置里面针对 Xray类型 和 Sing-Box类型 节点 单独添加一项 落地节点或前置代理节点，实现起来要简单些。
不过也还是可以改的，但是可能短时间不一定弄得出来，主要没时间。

**Comment by Saxon-Sun** [comment]
> 本来打算把这个改了，就发 4.78-1 的，不过看了下，要改的话还不是个简单事，因为支持前置代理的工具只有Xray 和 Sing-Box，所以直接在节点配置里面针对 Xray类型 和 Sing-Box类型 节点 单独添加一项 落地节点或前置代理节点，实现起来要简单些。 不过也还是可以改的，但是可能短时间不一定弄得出来，主要没时间。

实在不行也可以先把节点配置里改成前置代理节点暂时先用用吧 等大佬有时间再改一下吧（感觉选落地节点有点不太好用）

**Comment by gito10** [comment]
>感觉选落地节点有点不太好用

选落地节点的话逻辑上看确实不如反过来选前置节点。
- 一是不直观，选节点的时候，不知道我选的节点到底落地是哪个，而反过来即使不清楚前置是哪个也不要紧，只要能中转通就行，选节点的时候可以很直观地知道这个节点就是最终的出口（落地）节点；
- 二是选落地节点的话，一个节点只能选择一个落地，反过来理解，一个节点只能作为最多一个节点的前置，但实际可能是某个节点就适合作为中转/前置，而又有其他多个节点需要该节点作为前置，就跟分流里一样，多个节点用一个前置，这种只有反过来选前置才行。

**Comment by Saxon-Sun** [comment]
> > 感觉选落地节点有点不太好用
> 
> 选落地节点的话逻辑上看确实不如反过来选前置节点。
> 
> * 一是不直观，选节点的时候，不知道我选的节点到底落地是哪个，而反过来即使不清楚前置是哪个也不要紧，只要能中转通就行，选节点的时候可以很直观地知道这个节点就是最终的出口（落地）节点；
> * 二是选落地节点的话，一个节点只能选择一个落地，反过来理解，一个节点只能作为最多一个节点的前置，但实际可能是某个节点就适合作为中转/前置，而又有其他多个节点需要该节点作为前置，就跟分流里一样，多个节点用一个前置，这种只有反过来选前置才行。

对的对的 就是大佬说的意思 ，我是想着在负载均衡里面添加机场的节点用作前置代理中转，但是在编辑节点时发现是选择落地节点的 ，我又得反过来设置 ，所以逻辑上确实有点问题感觉，毕竟落地节点基本只有一个，而前置节点可能会多个，也不够直观 不知道自己选了哪个节点在主页上面

**Comment by gito10** [comment]
>毕竟落地节点基本只有一个，而前置节点可能会多个

这个你是不是说反了，落地节点可能有多个，前置代理一般就一个吧。
毕竟前置代理只要能同时连通本地和落地节点就行，只起个中转作用，它的IP无所谓。而落地节点是实际访问目标服务器的那个节点，目标服务器会将该节点的IP识别为用户IP地址。

**Comment by Saxon-Sun** [comment]
> > 毕竟落地节点基本只有一个，而前置节点可能会多个
> 
> 这个你是不是说反了，落地节点可能有多个，前置代理一般就一个吧。 毕竟前置代理只要能同时连通本地和落地节点就行，只起个中转作用，它的IP无所谓。而落地节点是实际访问目标服务器的那个节点，目标服务器会将该节点的IP识别为用户IP地址。

不是的，比如我是自己有服务器的 但是服务器直连国内速度不快，我用机场的节点作为中转（机场的节点有时候会被送中），我的落地ip就是一直不变 不会乱跑，所以我前置节点多个无所谓，不管ban了哪个还有其他的选择，我的使用场景就和套CDN一样，前置不管是什么都无所谓，落地保持不变

**Comment by mingtianquan** [comment]
其实每个节点可以设置落地节点挺好。 现在的版本就是这样，但是现在的版本  落地节点不支持sock5，

**Comment by AllenKingW** [comment]
我也想说这个问题的，我发现前置代理在基本设置里只能选择一个选项，如果有不同国家的落地，那么就没办法了。所以要么前置代理基本设置里可以选择不同的国家代理，要么就在单个节点的设置里添加前置代理的选项，这样就很方便通过airplane做链式代理了。非常感谢作者的passwall，祝越做越好！！！

**Comment by handsomeji** [comment]
我這周有空弄弄看~~~

**Comment by AllenKingW** [comment]
牛牛牛，小猫咪是dialer-proxy。支持v2ray！！！

**Comment by AllenKingW** [comment]
> 牛牛牛，小猫咪是dialer-proxy。支持v2ray！！！
支持passwall！

**Comment by maxlixiang** [comment]
这个功能还挺重要的，不同节点用不同的前置代理。

**Comment by maxlixiang** [comment]
目前有什么替代方案能实现不同节点使用不同前置代理么？

**Comment by maxlixiang** [comment]
> > > 毕竟落地节点基本只有一个，而前置节点可能会多个
> > 
> > 
> > 这个你是不是说反了，落地节点可能有多个，前置代理一般就一个吧。 毕竟前置代理只要能同时连通本地和落地节点就行，只起个中转作用，它的IP无所谓。而落地节点是实际访问目标服务器的那个节点，目标服务器会将该节点的IP识别为用户IP地址。
> 
> 不是的，比如我是自己有服务器的 但是服务器直连国内速度不快，我用机场的节点作为中转（机场的节点有时候会被送中），我的落地ip就是一直不变 不会乱跑，所以我前置节点多个无所谓，不管ban了哪个还有其他的选择，我的使用场景就和套CDN一样，前置不管是什么都无所谓，落地保持不变

请问现在有没有临时替代方案？

**Comment by handsomeji** [comment]
Try the latest commit.

**Comment by lwb1978** [comment]
这个issues半年后终于有着落了。
感谢小肉鸡的回归，但也很想念@nftbty ，希望nftbty有空能继续回来一起维护pw。

**Comment by snakwu** [comment]
> 这个issues半年后终于有着落了。 感谢小肉鸡的回归，但也很想念@nftbty ，希望nftbty有空能继续回来一起维护pw。

肉鸡最近很卖力，辛苦了，也感谢你一直在维护

**Comment by ismailshosho376-maker** [comment]
passwall的前置多选，不知道大佬有没有解决
