### ISSUE TITLE
[Bug]: 编译出错

### ISSUE THREAD

**Issue by Kuron88** [xiaorouji/openwrt-package#3219]
### 描述您遇到的bug

编译出错

### 复现此Bug的步骤

全新拉取的源码，打掉的lede，加入这个插件后怎么编译都是报这个错误

### 您想要实现的目的

解决编译出错

### 日志信息

{standard input}: Assembler messages:
{standard input}:4260: Error: opcode not supported on this processor: mips2 (mips2) `sync'
{standard input}:4535: Error: opcode not supported on this processor: mips2 (mips2) `sync'
make[4]: *** [Makefile:25: libev/ev.o] Error 1
make[4]: Leaving directory '/home/kuron/lede/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
make[3]: *** [Makefile:45: /home/kuron/lede/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1/.built] Error 2
make[3]: Leaving directory '/home/kuron/lede/feeds/passwall/dns2tcp'
time: package/feeds/passwall/dns2tcp/compile#0.40#0.12#0.52
    ERROR: package/feeds/passwall/dns2tcp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/dns2tcp/compile] Error 1
make[2]: Leaving directory '/home/kuron/lede'
make[1]: *** [package/Makefile:110: /home/kuron/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kuron/lede'
make: *** [/home/kuron/lede/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

passwall：477-5

**Comment by gito10** [comment]
你这个问题跟luci-app-passwall本身无关，是passwall依赖的一些packages无法编译，去 [xiaorouji/openwrt-passwall-packages](https://github.com/xiaorouji/openwrt-passwall-packages/issues)问问，而且也不一定是packages本身的问题。
