### ISSUE TITLE
[Bug]: Passwall 最新版，用官方源码编译时一起编译安装，添加节点后，打开节点列表超级慢

### ISSUE THREAD

**Issue by clion007** [xiaorouji/openwrt-package#3225]
### 描述您遇到的bug

用官方源码编译时一起编译安装 Passwall 最新版，添加节点后，打开节点列表超级慢，而且节点越多越慢，添加几百个节点甚至都打不开这个节点列表的页面，直接返回错误提示页面。但是用Lean大或者lienol大的源码编译的相同版本就不会出现这种情况，列表打开很快，请帮忙解决，谢谢！

### 复现此Bug的步骤

1、用官方源码编译固件，加入最新版passwall；
2、联网；
3、订阅节点；
4、点击打开节点列表，然后就是漫长的等待，一直打不开，而且整个passwall的相关连接都变的很慢。

### 您想要实现的目的

路由器后台配置passwall，打开节点列表是响应及时，不要很长时间页面都出不来。

### 日志信息

日志没有错误信息

### 系统相关信息

最新版passwall，google内核浏览器，openwrt官方23.05源码编译的固件。X86架构，内存充足，千兆带宽网络。

**Comment by lwb1978** [comment]
这个锅其实不能算pw的，官方的界面是基于js的，而lede是lua，官方向下兼容lua，pw就是采用lua开发的，所以界面的表现上肯定是在lede上是最好的，lua在官方op上时有些地方显示很别扭，比如错位、按钮大小不统一等等。你也可以试试immortalwrt看，这个版本是基于官方优化的，我就用这个版本，打开列表还算正常，40个节点一点就开，但反应速度还是不如lede，毕竟原生支持lua。

**Comment by Saxon-Sun** [comment]
> 这个锅其实不能算pw的，官方的界面是基于js的，而lede是lua，官方向下兼容lua，pw就是采用lua开发的，所以界面的表现上肯定是在lede上是最好的，lua在官方op上时有些地方显示很别扭，比如错位、按钮大小不统一等等。你也可以试试immortalwrt看，这个版本是基于官方优化的，我就用这个版本，打开列表还算正常，40个节点一点就开，但反应速度还是不如lede，毕竟原生支持lua。

我用immortalwrt 23.05不知道为啥50个节点都要转七八秒才会显示出来 很卡感觉 节点越少就越快了

**Comment by clion007** [comment]
> > 这个锅其实不能算pw的，官方的界面是基于js的，而lede是lua，官方向下兼容lua，pw就是采用lua开发的，所以界面的表现上肯定是在lede上是最好的，lua在官方op上时有些地方显示很别扭，比如错位、按钮大小不统一等等。你也可以试试immortalwrt看，这个版本是基于官方优化的，我就用这个版本，打开列表还算正常，40个节点一点就开，但反应速度还是不如lede，毕竟原生支持lua。
> 
> 我用immortalwrt 23.05不知道为啥50个节点都要转七八秒才会显示出来 很卡感觉 节点越少就越快了

嗯嗯，就是节点越少越快，多了就很卡

**Comment by clion007** [comment]
> 这个锅其实不能算pw的，官方的界面是基于js的，而lede是lua，官方向下兼容lua，pw就是采用lua开发的，所以界面的表现上肯定是在lede上是最好的，lua在官方op上时有些地方显示很别扭，比如错位、按钮大小不统一等等。你也可以试试immortalwrt看，这个版本是基于官方优化的，我就用这个版本，打开列表还算正常，40个节点一点就开，但反应速度还是不如lede，毕竟原生支持lua。

哦哦，原来是这样，除了界面实现的不同，Lean大的源码和官方的还有哪些不同呢？我看他一直只有一个master分支，也没有版本控制，版本上还一直保持在18。

**Comment by clion007** [comment]
这样说的话，其实官方的基于js的界面性能上是不如lua吗？为什么官方不继续使用lua 的界面呢？

**Comment by Saxon-Sun** [comment]
> > 这个锅其实不能算pw的，官方的界面是基于js的，而lede是lua，官方向下兼容lua，pw就是采用lua开发的，所以界面的表现上肯定是在lede上是最好的，lua在官方op上时有些地方显示很别扭，比如错位、按钮大小不统一等等。你也可以试试immortalwrt看，这个版本是基于官方优化的，我就用这个版本，打开列表还算正常，40个节点一点就开，但反应速度还是不如lede，毕竟原生支持lua。
> 
> 哦哦，原来是这样，除了界面实现的不同，Lean大的源码和官方的还有哪些不同呢？我看他一直只有一个master分支，也没有版本控制，版本上还一直保持在18。

lean的luci版本一直都是18.06，但是不知道为什么23.06兼容lua会这么卡，要是专门出个js版本的passwall lua改js工作量估计会不小，不行只能将就先用了

**Comment by lwb1978** [comment]
> 这样说的话，其实官方的基于js的界面性能上是不如lua吗？为什么官方不继续使用lua 的界面呢？

不是这么理解的，如果是原生的js的luci是很快的，但是兼容lua就慢。

**Comment by lwb1978** [comment]
> lean的luci版本一直都是18.06，但是不知道为什么23.06兼容lua会这么卡，要是专门出个js版本的passwall lua改js工作量估计会不小，不行只能将就先用了

改js几乎不现实，lua在lede等18.06的版本和官方都能用，官方可以向下兼容lua，虽然界面显示效率低些（不影响代理效果和速度），但js就不能在18.06版上使用。从维护成本来讲不可能同时做js和lua两个版本，那得需要一个团队了，所以不光是PW，小猫咪和ssr不拉屎等其他爬墙插件也都只有lua版本。

**Comment by Saxon-Sun** [comment]
> > lean的luci版本一直都是18.06，但是不知道为什么23.06兼容lua会这么卡，要是专门出个js版本的passwall lua改js工作量估计会不小，不行只能将就先用了
> 
> 改js几乎不现实，lua在lede等18.06的版本和官方都能用，官方可以向下兼容lua，虽然界面显示效率低些（不影响代理效果和速度），但js就不能在18.06版上使用。从维护成本来讲不可能同时做js和lua两个版本，那得需要一个团队了，所以不光是PW，小猫咪和ssr不拉屎等其他爬墙插件也都只有lua版本。

我知道 但是以后应该迟早会弃用，毕竟官方现在也在用js了，js在web中开发比较成熟了，js在跨平台开发和兼容性方面表现优异，要是改js也会弃用lua了 两个版本一起维护肯定不现实

**Comment by lwb1978** [comment]
> 我知道 但是以后应该迟早会弃用，毕竟官方现在也在用js了，js在web中开发比较成熟了，js在跨平台开发和兼容性方面表现优异，要是改js也会弃用lua了 两个版本一起维护肯定不现实

这点你可能就不太了解了，大雕的LEDE不会更新到js的会死守18.06这条线，lede支持的软硬路由多国内各种新奇特的路由他能第一时间适配，用户数量很多，所以lua和fw3（防火墙3）基本不会弃用。

**Comment by Saxon-Sun** [comment]
> > 我知道 但是以后应该迟早会弃用，毕竟官方现在也在用js了，js在web中开发比较成熟了，js在跨平台开发和兼容性方面表现优异，要是改js也会弃用lua了 两个版本一起维护肯定不现实
> 
> 这点你可能就不太了解了，大雕的LEDE不会更新到js的会死守18.06这条线，lede支持的软硬路由多国内各种新奇特的路由他能第一时间适配，用户数量很多，所以lua和fw3（防火墙3）基本不会弃用。

原来如此 这还真的不太了解

**Comment by gito10** [comment]
而且我觉得就算要改，或者说出一个新的代理工具，不一定非得用uci格式配置，也不一定非得用luci的界面技术。完全可以用一种语言（哪怕是某种脚本语言）写一个webUI配置的代理工具，这样工具就不局限于openwrt可用，其他系统的路由或者非路由设备都可以安装运行。如果想要集成到某些路由器界面（op的luci或其他厂商自己的界面）或者面板，只需要很少量的代码，实现简单的开关和打开设置页，和相应的启动脚本/服务文件（op的init.d，systemd的service文件之类）。

话说这种想法很容易就能想到，Linux上应该有人做过类似的工具吧，我搜搜看。

**Comment by Saxon-Sun** [comment]
> 而且我觉得就算要改，或者说出一个新的代理工具，不一定非得用uci格式配置，也不一定非得用luci的界面技术。完全可以用一种语言（哪怕是某种脚本语言）写一个webUI配置的代理工具，这样工具就不局限于openwrt可用，其他系统的路由或者非路由设备都可以安装运行。如果想要集成到某些路由器界面（op的luci或其他厂商自己的界面）或者面板，只需要很少量的代码，实现简单的开关和打开设置页，和相应的启动脚本/服务文件（op的init.d，systemd的service文件之类）。
> 
> 话说这种想法很容易就能想到，Linux上应该有人做过类似的工具吧，我搜搜看。

你说的是不是类似大鹅[daed](https://github.com/daeuniverse/daed)这种打开一个自己开发的web进行配置代理

**Comment by gito10** [comment]
这个打开慢的问题最多也只能看看节点列表部分源代码，看能不能尽量精简优化代码，抠一点性能出来，不过估计是没太大用，主要性能问题还是出在新版op的luci库部分。
