### ISSUE TITLE
类型里没有v2ray选项了

### ISSUE THREAD

**Issue by ishadow0** [xiaorouji/openwrt-package#3226]
### 描述你想要的新功能

几年前编译的版本可选则v2ray，但这两天不管是新编译的（已选择v2ray）还是下载release里的最新版都是如此，可选类型少了很多

### 描述你想要的解决方案

v2ray已经放弃了？

**Comment by BGzEroll** [comment]
有更好的xray和singbox用为啥要用回v2ray

**Comment by ishadow0** [comment]
> 有更好的xray和singbox用为啥要用回v2ray

因为自己搭建的v2ray很稳定，就不想再动了，万一ip被墙了就得不偿失

**Comment by lwb1978** [comment]
> > 有更好的xray和singbox用为啥要用回v2ray
> 
> 因为自己搭建的v2ray很稳定，就不想再动了，万一ip被墙了就得不偿失

你不知道xray和singbox都可以兼容v2ray的吗？内核组件越多越难维护，稳定性越难保证，不单是v2ray，pw还去掉了好几个依赖，因为他们基本都可以用xray或者singbox代替。

**Comment by gito10** [comment]
以后提问类去 Discussion 发
