### ISSUE TITLE
[Bug]: “使用自定义探测网址”、“探测间隔” 选项出现在非 Xray 节点中

### ISSUE THREAD

**Issue by mars-m9** [xiaorouji/openwrt-package#3231]
### 描述您遇到的bug

如题，截图如下，该选项对于非 Xray 节点应该并没有什么用。实际勾选后也没有跳出“探测网址”的选项。
![QQ截图20240529034953](https://github.com/xiaorouji/openwrt-passwall/assets/160640204/274f22e4-4c1e-4dd1-a462-5006b39b3e66)

### 复现此Bug的步骤

选择非 Xray 节点，选项出现。

### 您想要实现的目的

调整选项显示逻辑。

### 日志信息

不适用

### 系统相关信息

4.77-5

**Comment by lwb1978** [comment]
确实存在这个问题。
@nftbty

**Comment by gito10** [comment]
看了代码，思考了很久，基于目前设置逻辑，没有什么好的解决办法，主要是老版luci的depends太简陋了，好多设想的条件没法设置，keyA==valueA, keyB!=valueB 这样的都不行，只有个 `!reverse` 把全部等于变成不等于。

1.8.12开始支持random和roundRobin的健康检查只选择aliveOnly的节点，但并没有一个单独的aliveOnly参数来控制，而是看fallbackTag，没设置fallback就无脑选出站，设了fallbackTag，才会根据监测结果选择可用的出站。所以random和roundRobin需要判断后备节点是否设置。但是我之前的判断条件存在这个bug（主要luci行为难以理解，目前的条件是fallback_node != ""，在xray类型下改成其他协议，fallback_node这个选项消失，说明判断不成立，也就是fallback_node==""，类型改为非xray，fallback_node同样不显示，但是不知道为什么，fallback_node!=""的判断却又为true了）。

目前来说，要避免这个问题，只能改判断条件，不能使用不为空的判断，就只能把后备节点选项列表里的节点全部添加depends，但是这样真的很蠢，查看网页源码，控件的`data-depends`属性会超级长，会严重影响luci页面加载速度（节点越多越慢），所以肯定不能用这种改法。

继续想解决方案
1. 要么就跟我之前改前置代理时一样，加个是否启用后备节点的开关选项，然后判断这个开关的值就行了。但是这样又增加了设置选项的复杂度。
2. 要么直接后备节点值列表里去掉“无”，也不加开关，也就是说强制必须设一个后备节点。这样可以省去fallback_node的判断。

我比较倾向于第2点，因为用负载均衡的就是想保证代理的高可用性，所以对于强制设置后备节点是可以接受的。
@lwb1978 你觉得按哪种改法好一点，1还是2？

**Comment by lwb1978** [comment]
@nftbty 今天我也研究了一下代码，觉得确实难判断，我还是倾向于你说的第一点，这样可以让用户选择是否启用后备节点，这个开关连同后备节点下拉列表一起控制，不勾选时所有后备节点相关设置都隐藏，同时去掉后备节点下拉列表的无。第一种方式留给用户的自由空间更大一些。
另外我也是刚刚接触lua不久，今天研究xray.lua代码，才知道有!reverse这么个东西，我准备继续优化一下前些天pr的自动更新的代码，我代码里弄了很长的depends，当时也是被depends不支持keyB!=valueB搞得头疼。

**Comment by gito10** [comment]
不过 random 和 roundRobin 策略，不指定 fallback_node的话，目前的xray版本只会无脑随机或者无脑下一个，不会判断节点可用性，这种基本没用，还是强制启用fallback_node，让 balancer 只选择可用出站的好。
就剩下一个 leastping，这个启不启用fallback_node 对 balancer 行为没影响。

**Comment by gito10** [comment]
先按照强制启用 fallback_node 改了，把这个Bug消除。
后续要不要加开关，看反馈情况吧。

**Comment by BGzEroll** [comment]
> 先按照强制启用 fallback_node 改了，把这个Bug消除。 后续要不要加开关，看反馈情况吧。

个人感觉这对不想使用任何fallback策略的用户会有些不妥

**Comment by gito10** [comment]
> 个人感觉这对不想使用任何fallback策略的用户会有些不妥

fallback也就多选一个节点的事。

主要吧，总共3个策略，就有2个（random和roundRobin）不指定一个fallback节点的话，根本不会判断均衡节点可用性，即使节点故障了，仍会被选择。（xray 1.8.12 添加的，我也不太理解为什么要用这种设置逻辑，其实之前看到有个issue还是pr，有提到加个aliveOnly参数，开启时会根据观测结果从当前可用的出站里选择，这种就很好。其实也可以不加参数，默认启用观测，只选择可用节点，因为不带可用性判断的均衡策略其实并没有什么意义）

**Comment by BGzEroll** [comment]
> > 个人感觉这对不想使用任何fallback策略的用户会有些不妥
> 
> fallback也就多选一个节点的事。
> 
> 主要吧，总共3个策略，就有2个（random和roundRobin）不指定一个fallback节点的话，根本不会判断均衡节点可用性，即使节点故障了，仍会被选择。（xray 1.8.12 添加的，我也不太理解为什么要用这种设置逻辑，其实之前看到有个issue还是pr，有提到加个aliveOnly参数，开启时会根据观测结果从当前可用的出站里选择，这种就很好。其实也可以不加参数，默认启用观测，只选择可用节点，因为不带可用性判断的均衡策略其实并没有什么意义）

![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/3f41eb4a-9fca-4baf-923b-6d0bf82a3d22)
不知道是不是我理解有误。在更改后是**非负载均衡协议**如vless、vmess，也必须要选择一个后备节点了是吗

**Comment by gito10** [comment]
你还没更新吧，所以你看看这个issue提的是什么问题，还有上面的讨论。你图片显示的问题和楼主的问题其实是一个原因。

更新后就好了。
