### ISSUE TITLE
[Feature Request]: 建议Revert "luci: eliminate JS LuCI behavior"这个commit

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3232]
### 描述你想要的新功能

![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/55feb493-a4d3-4279-a39a-8ec921f6d0f0)
自有这个commit后，在一些地方点保存，右上角会显示**未保存的配置**

如**勾选IPV6透明代理**后点击保存，会有如下情况：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/67511548-10e0-4721-83a8-22bd976971ec)
此时需要手动点一次保存并应用，虽然配置似乎是已经写入了的，但还是会留有这luci的提示。

另外在**规则管理**处创建新的分流规则，在创建完后将该规则任意**上移**或**下移**并点击**保存**，将会使得**配置更新的URL**全部丢失，如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/cfa323f4-90c0-45fb-be01-eea3a1402333)

luci提示如图：
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/bd899cfb-34de-4029-a765-5e1b2c1859a9)

### 描述你想要的解决方案

希望**Revert "luci: eliminate JS LuCI behavior**。
此外我认为每次更改都让luci暂停个几秒也可以起到防止操作过于频繁的作用，或许并不需要去除这个转圈等待的行为

我之前一直都是fork后自行revert掉该commit的，以为之后会修复该问题。我不懂luci，考虑到以后会有不断的更新，我这样一直手动自行revert下去也不是好办法😂。

### 其他信息

**系统信息如图：**
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/61d4289b-72b3-4104-af53-d621fa7660d6)

**passwall及组件版本如图：**
![image](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/ec204377-01d7-4b7b-824a-ba177b0415f9)

openwrt 23.05与passwall均为最新源码，于2024.05.29 上午9点编译

**Comment by lwb1978** [comment]
其实我也认为Revert比较好，我不了解老大这样做的目的是什么，但Revert以后我觉得使用体验上还舒服一些。希望老大们能考虑一下。
@xiaorouji @nftbty

**Comment by gito10** [comment]
我没用过js luci，不清楚情况，但之前xiaorouji做这一修改，应该是有原因的。是不是哪个issue或者discussion提出了某个问题而做出的修改。
因为不了解情况，所以我不太好处理，看其他人清不清楚情况。

**Comment by BGzEroll** [comment]
> 我没用过js luci，不清楚情况，但之前xiaorouji做这一修改，应该是有原因的。是不是哪个issue或者discussion提出了某个问题而做出的修改。 因为不了解情况，所以我不太好处理，看其他人清不清楚情况。

我翻了下该commit附近的时间，并未发现issues里有报关于luci的bug，或许这个commit就是单纯去除JS的转圈圈等待的

**Comment by lwb1978** [comment]
> > 我没用过js luci，不清楚情况，但之前xiaorouji做这一修改，应该是有原因的。是不是哪个issue或者discussion提出了某个问题而做出的修改。 因为不了解情况，所以我不太好处理，看其他人清不清楚情况。
> 
> 我翻了下该commit附近的时间，并未发现issues里有报关于luci的bug，或许这个commit就是单纯去除JS的转圈圈等待的

正是去除了转圈圈等待会让人在点击“保存并应用”的时候有点懵，点击后界面没有任何提示，不清楚是否刚才点没点中按钮，所以一度我在点击“保存并应用”后手动切换到日志去看是否启动脚本已经执行完了，体验并不好。我在github上面瞎逛的时候看到很多fork了pw的人都Revert了这个提交，其中也包括了例如 @sbwml 这样的大佬。

**Comment by gito10** [comment]
那就revert吧
