### ISSUE TITLE
[Bug]: 使用GFW模式无法进行代理

### ISSUE THREAD

**Issue by tangqiu0205** [xiaorouji/openwrt-package#3234]
### 描述您遇到的bug

一切都是默认设置, 在模式设置tag里设置模式为GFW列表后无法进行代理, 切换为中国列表以外则正常代理.

### 复现此Bug的步骤

![image](https://github.com/xiaorouji/openwrt-passwall/assets/37826977/97992f25-43df-4cc2-a008-adbeed04d100)

### 您想要实现的目的

希望可以正常使用GFW模式

### 日志信息

2024-05-30 11:20:18: 删除iptables防火墙规则完成。
2024-05-30 11:20:19: 清空并关闭相关程序和缓存完成。
2024-05-30 11:20:19: TCP节点：[🇺🇸美国 03 | 专线]，监听端口：1041
2024-05-30 11:20:20: UDP节点没有选择或为空，不代理UDP。
2024-05-30 11:20:20: DNS域名解析：
2024-05-30 11:20:20:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-05-30 11:20:20:   - ChinaDNS-NG(127.0.0.1#15353)：直连DNS：1.1.1.1,8.8.8.8，可信DNS：tcp://1.1.1.1#53
2024-05-30 11:20:20:   - 节点列表中的域名(vpslist)：1.1.1.1,8.8.8.8
2024-05-30 11:20:20:   - 域名白名单(whitelist)：默认
2024-05-30 11:20:20:   - 代理域名表(blacklist)：默认
2024-05-30 11:20:20:   - 防火墙域名表(gfwlist)：默认
2024-05-30 11:20:20:   - 默认：127.0.0.1#15353
2024-05-30 11:20:20:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-05-30 11:20:20: 开始加载防火墙规则...
2024-05-30 11:20:21:   - [0]追加ISP IPv4 DNS到白名单：1.1.1.1
2024-05-30 11:20:21:   - [0]追加ISP IPv4 DNS到白名单：8.8.8.8
2024-05-30 11:20:21:   - [0]加入负载均衡的节点到ipset[passwall_vpslist]
2024-05-30 11:20:21:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-05-30 11:20:21:   - [0]追加直连DNS到iptables：1.1.1.1:53
2024-05-30 11:20:21:   - [0]追加直连DNS到iptables：8.8.8.8:53
2024-05-30 11:20:21:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-05-30 11:20:21:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2024-05-30 11:20:21:   - 访问控制：
2024-05-30 11:20:21:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-05-30 11:20:22:      - 【默认】，使用 TCP 节点[🇺🇸美国 03 | 专线](REDIRECT:1041)
2024-05-30 11:20:22: 防火墙规则加载完成！
2024-05-30 11:20:22: 重启 dnsmasq 服务
2024-05-30 11:20:22: 配置定时任务：自动更新【one】订阅。
2024-05-30 11:20:22: 运行完成！

### 截图

<img width="893" alt="屏幕截图 2024-05-30 112242" src="https://github.com/xiaorouji/openwrt-passwall/assets/37826977/b8e55343-a3ba-4131-95d8-642231b93d02">

### 系统相关信息

Passwall:  4.77-5
EDGE: 125.0.2535.51

**Comment by lwb1978** [comment]
我一直使用gfw模式，没有发现异常。看下你的dns设置，另外试试把gfw列表删除重新更新列表看。

**Comment by tangqiu0205** [comment]
> 我一直使用gfw模式，没有发现异常。看下你的dns设置，另外试试把gfw列表删除重新更新列表看。

dns 设置如下, 另外gfw列表里的内容无法编辑,我删除不了
![图片](https://github.com/xiaorouji/openwrt-passwall/assets/37826977/e15b40d6-cb4c-4fce-8e79-faa81f9cbe44)

openwrt dns 设置
![图片](https://github.com/xiaorouji/openwrt-passwall/assets/37826977/e55ff5c3-088d-4a7d-8396-10827b5170ad)

**Comment by Nicepaul** [comment]
应该是DNS的问题。DNS分流设置为Dnsmasq试一试。下图是我用的，一切正常
<img width="467" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/32355166/0c14db5b-88a0-4fda-818c-c24023825210">

**Comment by tangqiu0205** [comment]
> 应该是DNS的问题。DNS分流设置为Dnsmasq试一试。下图是我用的，一切正常 <img alt="image" width="467" src="https://private-user-images.githubusercontent.com/32355166/335067606-0c14db5b-88a0-4fda-818c-c24023825210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTIxNjgsIm5iZiI6MTcxNzA1MTg2OCwicGF0aCI6Ii8zMjM1NTE2Ni8zMzUwNjc2MDYtMGMxNGRiNWItODhhMC00ZmRhLTgxOGMtYzI0MDIzODI1MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNjQyODA0ZWFhZTg2NWJkNzY1ZGExMzJlMTM5NjllODc2NzU3YzBjMTBiNzU2NTc2OTkwM2ZhNmNmNWMxZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ORo4YA2NeTUsxtkk64h0tqmeqLmv8u_al-NVtHWdA7M">

还是不行, 以下是我的设置
![图片](https://github.com/xiaorouji/openwrt-passwall/assets/37826977/295a63cf-d86c-4b3b-9f8b-22461fa566b3)

**Comment by tangqiu0205** [comment]
我发现讨论区有几个网友和我有一样的问题.
<img width="680" alt="屏幕截图 2024-05-30 134806" src="https://github.com/xiaorouji/openwrt-passwall/assets/37826977/6c8dfb6d-b9cd-414d-bbec-c36e6ad910d9">

**Comment by lwb1978** [comment]
> dns 设置如下, 另外gfw列表里的内容无法编辑,我删除不了 !

要ssh登陆路由去删除gfw文件

**Comment by lwb1978** [comment]
> 我发现讨论区有几个网友和我有一样的问题. <img alt="屏幕截图 2024-05-30 134806" width="680" src="https://private-user-images.githubusercontent.com/37826977/335072859-6c8dfb6d-b9cd-414d-bbec-c36e6ad910d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTI0MTgsIm5iZiI6MTcxNzA1MjExOCwicGF0aCI6Ii8zNzgyNjk3Ny8zMzUwNzI4NTktNmM4ZGZiNmQtYjljZC00MTRkLWJiZWMtYzM2ZTZhZDkxMGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYzFlNTdmZjU2NmI4YWJlNTBkOTM3YzZmZGU3MTg4M2VlMDJlZGFiNDYyYzMwYWU2NzQzNzc3NTdmY2NiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OKoR9jTVOW3tOMH4dN4Kz-Nt6GfKougcihRnBDtgDHM">

你也是旁路由模式？

**Comment by Nicepaul** [comment]
我之前也有过youtube不能访问，不能用tproxy，改成redirect就好了。但是有的passwall版本用tproxy是没问题的
<img width="445" alt="image" src="https://github.com/xiaorouji/openwrt-passwall/assets/32355166/fc59f777-8b6d-49f8-96ee-f170e9dcf39e">

**Comment by tangqiu0205** [comment]
> > dns 设置如下, 另外gfw列表里的内容无法编辑,我删除不了 !
> 
> 要ssh登陆路由去删除gfw文件

好的, 我来试下

> 你也是旁路由模式？

是的 我也是

**Comment by tangqiu0205** [comment]
> > dns 设置如下, 另外gfw列表里的内容无法编辑,我删除不了 !
> 
> 要ssh登陆路由去删除gfw文件

已测试, 还是无法使用
![图片](https://github.com/xiaorouji/openwrt-passwall/assets/37826977/abae2602-88c2-4683-942a-085dfbc43fbb)

**Comment by tangqiu0205** [comment]
突然发现PC上电报客户端竟然可以, 所以也不是全部都用不了, 无法理解了

**Comment by tangqiu0205** [comment]
突然发现PC上电报客户端竟然可以, 所以也不是全部都用不了, 无法理解了

**Comment by ghost** [comment]
GFW模式下需要將dns模式修改爲dns2socks才能正常代理上網。
在分流模式下，若沒有打開 「路由器本機代理」那麼也需要讓dns模式處於dns2socks才能正常代理上網。

**Comment by ghost** [comment]
若以上方法無效，則說明該固件編譯時，選擇的組件不正確，或者編譯時沒有成功加入gfwlist。

**Comment by tangqiu0205** [comment]
> GFW模式下需要將dns模式修改爲dns2socks才能正常代理上網。 在分流模式下，若沒有打開 「路由器本機代理」那麼也需要讓dns模式處於dns2socks才能正常代理上網。


> 若以上方法無效，則說明該固件編譯時，選擇的組件不正確，或者編譯時沒有成功加入gfwlist。

以上方法都无效, 我暂时考虑还是规则处理的BUG.

**Comment by lwb1978** [comment]
旁路由是玄学，比较不好处理。

**Comment by gito10** [comment]
>突然发现PC上电报客户端竟然可以

电报是直接连IP，没有域名，不经过DNS解析。这种情况，说明你的网配置通了，DNS代理有问题。
你可以验证下，用 tcping 连接几个墙外IP，应该能连通，然后nslookup 某个墙外域名，应该无法返回结果。

如果确实如此的话，重点排查DNS，看是哪里问题导致远程DNS不通的。

**Comment by tangqiu0205** [comment]
大概知道问题所在了, 在路由器开启IPV6的情况下,客户端会优先使用IPV6的IP,所以就跳过了旁路由.
贴两个链接:
https://www.right.com.cn/forum/thread-745591-1-1.html
https://www.v2ex.com/t/818661

**Comment by CharlesLocke** [comment]
有一种情况是部分国产手机内置了DNS，这时候需要重定向客户端DNS到dnsmasq。

**Comment by zhouLife** [comment]
旁路由 一样。GFW模式下PC上不了谷歌 youtube。 手机可以上

**Comment by yiheng603** [comment]
好像问题是出在端口的设置里的默认网关和DNS，我是修改这些参数就好了，没有修改前，部分设置能正常借代理

**Comment by frehedhuang** [comment]
> 大概知道问题所在了, 在路由器开启IPV6的情况下,客户端会优先使用IPV6的IP,所以就跳过了旁路由. 贴两个链接: https://www.right.com.cn/forum/thread-745591-1-1.html https://www.v2ex.com/t/818661

多谢，同样的问题，果然是IPv6的锅。禁用后正常
