### ISSUE TITLE
[Bug]: 4.77.4之后的版本会导致docker 容器无法联网

### ISSUE THREAD

**Issue by frank-pv** [xiaorouji/openwrt-package#3235]
### 描述您遇到的bug

问题：passwall 4.76.2-4.77.3 下的docker container联网正常，在升级到4.77.4-4.77.5版本后，immortalwrt 下的docker无法联网

### 复现此Bug的步骤

1、将PW版本从4.76.2升级到4.77.5，并将R5C LAN口接通设备，必定复现

### 您想要实现的目的

修复bug

### 日志信息

[nft list.zip](https://github.com/xiaorouji/openwrt-passwall/files/15494584/nft.list.zip)

### 系统相关信息

系统：immortalwrt 22.05 master 自编译
设备：R5C

**Comment by pianranjinghong** [comment]
#3209

**Comment by gito10** [comment]
参考楼上引用的issue，了解原因。
在官方出正式解决方案之前，暂时缓解可以用楼上的方法，将那两条命令添加到 防火墙-自定义规则。

**Comment by frank-pv** [comment]
> 参考楼上引用的issue，了解原因。 在官方出正式解决方案之前，暂时缓解可以用楼上的方法，将那两条命令添加到 防火墙-自定义规则。

好的谢谢你
