### ISSUE TITLE
[Bug]: smartdns-dev 4.77-6版本TCP,UDP,DNS,负载均衡都示未运行

### ISSUE THREAD

**Issue by EastonSun** [xiaorouji/openwrt-package#3240]
### 描述您遇到的bug

smartdns-dev 4.77-6的TCP、UDP、DNS、负载均衡都显示为未运行，但不管内网和外网都正常

### 复现此Bug的步骤

![微信截图_20240601181851](https://github.com/xiaorouji/openwrt-passwall/assets/52378245/0935784a-f6fc-4062-a89d-d369c1e39d03)
![微信截图_20240601181955](https://github.com/xiaorouji/openwrt-passwall/assets/52378245/b6f072c8-e268-44e0-ad9b-16aa37f2ad61)
![微信截图_20240601181932](https://github.com/xiaorouji/openwrt-passwall/assets/52378245/f55df9f1-2a39-4128-a515-c95dbcb143ac)

### 您想要实现的目的

能显示正常

### 日志信息

2024-06-01 17:54:11: 删除nftables防火墙规则完成。
2024-06-01 17:54:14: 清空并关闭相关程序和缓存完成。
2024-06-01 17:54:14: HAPROXY 负载均衡：
2024-06-01 17:54:14:   * 控制台端口：1188
2024-06-01 17:54:14:   +  入口 127.0.0.1:1181
2024-06-01 17:54:14:   | - 出口节点：*.*.*.*:56165，权重：2
2024-06-01 17:54:14:   | - 出口节点：*.*.*.*:61943，权重：1
2024-06-01 17:54:14: TCP节点：[负载均衡]，监听端口：1041
2024-06-01 17:54:14: 开启实验性IPv6透明代理(TProxy)，请确认您的节点及类型支持IPv6！
2024-06-01 17:54:14: DNS域名解析：
2024-06-01 17:54:14:   - 节点列表中的域名(vpslist)使用分组：CN
2024-06-01 17:54:14:   - 代理域名表(blacklist)使用分组：passwall_proxy
2024-06-01 17:54:14:   - 防火墙域名表(gfwlist)使用分组：passwall_proxy
2024-06-01 17:54:14:   - 中国域名表(chnroute)使用分组：CN
2024-06-01 17:54:14:   - 请让SmartDNS作为Dnsmasq的上游或重定向！
2024-06-01 17:54:14:   - 域名解析：使用SmartDNS，请确保配置正常。
2024-06-01 17:54:14: 开始加载防火墙规则...
2024-06-01 17:54:15:   - [0]加入负载均衡的节点到nftset[passwall_vpslist]直连完成
2024-06-01 17:54:16:   - [1]加入所有节点到nftset[passwall_vpslist]直连完成
2024-06-01 17:54:16:   - [0]追加直连DNS到nftables：127.0.0.1:5553
2024-06-01 17:54:16:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-06-01 17:54:16:   - 访问控制：
2024-06-01 17:54:16:      - 【ProxyEnable】，MAC【】，屏蔽代理 UDP 端口[443]
2024-06-01 17:54:16:      - 【ProxyEnable】，MAC【】，使用 TCP 节点[负载均衡](TPROXY:1041)
2024-06-01 17:54:16:      - 【ProxyEnable】，MAC【】，使用 UDP 节点[负载均衡](TPROXY:1041)
2024-06-01 17:54:16:      - 【ProxyEnable】，MAC【】，屏蔽代理 UDP 端口[443]
2024-06-01 17:54:17:      - 【ProxyEnable】，MAC【】，使用 TCP 节点[负载均衡](TPROXY:1041)
2024-06-01 17:54:17:      - 【ProxyEnable】，MAC【】，使用 UDP 节点[负载均衡](TPROXY:1041)
2024-06-01 17:54:18: 防火墙规则加载完成！
2024-06-01 17:54:21: 重启 dnsmasq 服务
2024-06-01 17:54:21: 配置定时任务：自动更新规则。
2024-06-01 17:54:21: 运行完成！

### 系统相关信息

![微信截图_20240601182712](https://github.com/xiaorouji/openwrt-passwall/assets/52378245/08d50ff1-58f2-49f0-890c-fd34550e6dcb)

**Comment by gito10** [comment]
更新之前是什么版本，4.77-5-smartdns-dev吗？
最新的也就只是把smartdns的2个提交rebase到4.77-6，没有改动代码。我自己用的是主分支4.77-6，状态显示正常。按理说不应该会出现这个问题。

不过我之前也遇到过显示未运行的情况，不过是我把xray移动到硬盘，然后建了个软链到 /usr/bin/xray，passwall里xray的路径仍旧指定的 /usr/bin/xray，这时运行passwall，状态就会显示未运行，后来直接把passwall里xray路径改到硬盘实际文件路径，不用软链，就正常了。

**Comment by gito10** [comment]
@lwb1978 好像你是用的smartdns分支？更到4.7.7-6版了吗，有没有题主一样的问题？

**Comment by EastonSun** [comment]
> 更新之前是什么版本，4.77-5-smartdns-dev吗？ 最新的也就只是把smartdns的2个提交rebase到4.77-6，没有更新代码。我自己用的只是主分支4.77-6，状态显示正常。按理说不应该出现这个问题。
> 
> 不过我之前也遇到未显示未运行的情况，不过我把xray放在硬盘上，然后建了一个软链到/usr/bin/xray，passwall里xray的路径仍旧命名为/usr/bin/xray，这时运行passwall，状态就会显示未运行，后来直接把passwall里xray路径改到硬盘实际文件路径，不用软链，就正常了。

以前用的是主分支，今天下午重新编译的smartdns-dev和openwrt

**Comment by bi4tms** [comment]
出现同样的问题，长期使用-smartdns-dev版本，更到4.7.7-6后出现TCP、UDP、DNS、负载均衡显示为未运行，回退至4.7.7-5后正常
@nftbty

**Comment by lwb1978** [comment]
> @lwb1978 好像你是用的smartdns分支？更到4.7.7-6版了吗，有没有题主一样的问题？

我的仓库还没有同步主仓库的更新，不过我的仓库代码都是手动同步smartdns-dev分支到主分支最新代码，没有问题，我看看主仓库的代码哪里有什么问题不。

**Comment by lwb1978** [comment]
> @lwb1978 好像你是用的smartdns分支？更到4.7.7-6版了吗，有没有题主一样的问题？

@nftbty 
找到问题了,luci-app-passwall/luasrc/controller/passwall.lua中
214行：local dns_shunt = ucic:get(appname, "@global[0]", "dns_shunt") or "dnsmasq"
ucic 应该为 uci

**Comment by redfrog999** [comment]
21.02是不是被抛弃了？我编译出来的4.77-6在21.02的硬路由上不但没显示，直接没法使用了。

**Comment by lwb1978** [comment]
> 21.02是不是被抛弃了？我编译出来的4.77-6在21.02的硬路由上不但没显示，直接没法使用了。

首页不显示状态的bug跟你能不能用没关系，pw只是个翻墙组件的综合管理插件，只有脚本，没有二进制文件，自身没有任何系统版本的限制，你编译出来不能用请自行查系统日志，看缺少什么系统组件，又或者是ss、xray、sing-box等等这些核心组件能否在你的系统上面运行。如果真是ss、xray、sing-box等等这些核心抛弃了21.02，那请到对应的仓库提意见。

**Comment by redfrog999** [comment]
> > 21.02是不是被抛弃了？我编译出来的4.77-6在21.02的硬路由上不但没显示，直接没法使用了。
> 
> 首页不显示状态的bug跟你能不能用没关系，pw只是个翻墙组件的综合管理插件，只有脚本，没有二进制文件，自身没有任何系统版本的限制，你编译出来不能用请自行查系统日志，看缺少什么系统组件，又或者是ss、xray、sing-box等等这些核心组件能否在你的系统上面运行。如果真是ss、xray、sing-box等等这些核心抛弃了21.02，那请到对应的仓库提意见。

可能我没说明白。我编译的PSW-Smartdns版最新版在21.02完全没法用了，我只带了Xray内核，PSW可以检测到，但是无法运行。配置文件是承继4.77-5来的。现在回退到4.77-5完全正常。我猜应该是4.77-6有点问题，我看了日志空白一片，发现压根没有运行起来。暂时就回到4.77-5，再跑个23.05版本对比看看什么情况，再反馈。

**Comment by lwb1978** [comment]
> > > 21.02是不是被抛弃了？我编译出来的4.77-6在21.02的硬路由上不但没显示，直接没法使用了。
> > 
> > 
> > 首页不显示状态的bug跟你能不能用没关系，pw只是个翻墙组件的综合管理插件，只有脚本，没有二进制文件，自身没有任何系统版本的限制，你编译出来不能用请自行查系统日志，看缺少什么系统组件，又或者是ss、xray、sing-box等等这些核心组件能否在你的系统上面运行。如果真是ss、xray、sing-box等等这些核心抛弃了21.02，那请到对应的仓库提意见。
> 
> 可能我没说明白。我编译的PSW-Smartdns版最新版在21.02完全没法用了，我只带了Xray内核，PSW可以检测到，但是无法运行。配置文件是承继4.77-5来的。现在回退到4.77-5完全正常。我猜应该是4.77-6有点问题，我看了日志空白一片，发现压根没有运行起来。暂时就回到4.77-5，再跑个23.05版本对比看看什么情况，再反馈。

你在这里下个4.77-6回去试试不就知道了，pw只是脚本，不对系统做任何限制，从4.77-5到4.77-6修改的代码也并不多，如果你要非要编译无错版本，那可以到我的pw仓库去拉代码，我的代码是最新且无错的。

**Comment by redfrog999** [comment]
> > > > 21.02是不是被抛弃了？我编译出来的4.77-6在21.02的硬路由上不但没显示，直接没法使用了。
> > > 
> > > 
> > > 首页不显示状态的bug跟你能不能用没关系，pw只是个翻墙组件的综合管理插件，只有脚本，没有二进制文件，自身没有任何系统版本的限制，你编译出来不能用请自行查系统日志，看缺少什么系统组件，又或者是ss、xray、sing-box等等这些核心组件能否在你的系统上面运行。如果真是ss、xray、sing-box等等这些核心抛弃了21.02，那请到对应的仓库提意见。
> > 
> > 
> > 可能我没说明白。我编译的PSW-Smartdns版最新版在21.02完全没法用了，我只带了Xray内核，PSW可以检测到，但是无法运行。配置文件是承继4.77-5来的。现在回退到4.77-5完全正常。我猜应该是4.77-6有点问题，我看了日志空白一片，发现压根没有运行起来。暂时就回到4.77-5，再跑个23.05版本对比看看什么情况，再反馈。
> 
> 你在这里下个4.77-6回去试试不就知道了，pw只是脚本，不对系统做任何限制，从4.77-5到4.77-6修改的代码也并不多，如果你要非要编译无错版本，那可以到我的pw仓库去拉代码，我的代码是最新且无错的。

好滴，感谢，硬路由升级psw挺麻烦的。等会儿拉你的代码跑下试试。

**Comment by lwb1978** [comment]
> 好滴，感谢，硬路由升级psw挺麻烦的。等会儿拉你的代码跑下试试。

另外你没描述清楚是pw的日志空白还是xray的日志空白，如果是xray启动不了你要确定你的xray编译是否正确。
还有你用4.77-5时，xray是什么版本的？

**Comment by redfrog999** [comment]
> > 好滴，感谢，硬路由升级psw挺麻烦的。等会儿拉你的代码跑下试试。
> 
> 另外你没描述清楚是pw的日志空白还是xray的日志空白，如果是xray启动不了你要确定你的xray编译是否正确。 还有你用4.77-5时，xray是什么版本的？

是PSW日志空白，刚才编译完23.05，PSW可以跑起来了，就是首页无显示，xray是1.8.13。等会儿再用你的源码跑下21.02看看什么情况。

**Comment by redfrog999** [comment]
> > > 好滴，感谢，硬路由升级psw挺麻烦的。等会儿拉你的代码跑下试试。
> > 
> > 
> > 另外你没描述清楚是pw的日志空白还是xray的日志空白，如果是xray启动不了你要确定你的xray编译是否正确。 还有你用4.77-5时，xray是什么版本的？
> 
> 是PSW日志空白，刚才编译完23.05，PSW可以跑起来了，就是首页无显示，xray是1.8.13。等会儿再用你的源码跑下21.02看看什么情况。

拉大佬的源码现在21.02跟23.05都正常了。再次感谢。

**Comment by lwb1978** [comment]
主仓库smartdns分支最新代码已经修复。
