### ISSUE TITLE
[Bug]: vless+grpc这种模式的节点无法使用

### ISSUE THREAD

**Issue by 97668589** [xiaorouji/openwrt-package#3241]
### 描述您遇到的bug

vless+grpc这种模式的节点，无法使用，xray内核已经更新到1.8.13最新版，passwall也是最新版，请修复问题，谢谢！

### 复现此Bug的步骤

xray内核已经更新到1.8.13最新版，passwall也是最新版

### 您想要实现的目的

请修复问题，谢谢！

### 日志信息

直接不通

### 系统相关信息

软路由xray内核已经更新到1.8.13最新版，passwall也是最新版

**Comment by gito10** [comment]
描述不够清楚，不太明白到底是：
- 之前版本可以使用，新版本不能用了，或者passwall 界面设置支持这种组合，但是设置后实际并不能成功运行，或者报错，这是bug；
- 原来就一直不支持这种用法，是xray某个版本新加的功能，希望passwall支持，这是feature request。

**Comment by 97668589** [comment]
之前好像可用，现在不行了，不知道啥问题

**Comment by gito10** [comment]
检查下生成的xray配置文件，在 /tmp/etc/passwall/acl/default/ 下面 TCP_开头的json文件。打开检查下outbound配置哪里不对。

（对了，同节点在手机或PC上试过是可以连通的吧？，可以和PC或者手机生成的配置文件对比下，主要是outbound部分，有什么不同）

**Comment by 97668589** [comment]
是的手机电脑可以正常使用，放软路由就不行了

**Comment by 97668589** [comment]
好的，我研究研究

**Comment by 97668589** [comment]
配置页面里要勾选tcpMptcp就可以了，不知道这个选项是什么意思

**Comment by gito10** [comment]
电脑和手机不启用MPTCP能通吗？

**Comment by 97668589** [comment]
> 电脑和手机不启用MPTCP能通吗？

电脑手机没这个选项

**Comment by gito10** [comment]
> 电脑手机没这个选项

电脑和手机端是xray内核还是sing-box内核

**Comment by 97668589** [comment]
> > 电脑手机没这个选项
> 
> 电脑和手机端是xray内核还是sing-box内核

都是xray内核

**Comment by gito10** [comment]
> 都是xray内核

那你可以找到passwall和电脑端生成的xray配置文件，对比下outbounds部分，有哪些区别。
passwall生成的配置文件在 /tmp/etc/passwall/acl/default/，TCP_UDP_ 开头的json文件。
