### ISSUE TITLE
[Feature Request]: ChinaDNS-NG 参数调整建议

### ISSUE THREAD

**Issue by dusty-97** [xiaorouji/openwrt-package#3242]
### 描述你想要的新功能

具体问题详见：zfl9/chinadns-ng#173
简单描述下问题：
当节点挂掉时，请求 tag:none 但 IP 为国内且没有 AAAA 记录的域名时会出现异常，在 Windows 及 iOS 系统中访问网页不会出现问题，但 Linux 中 cURL 会报错 ```curl: (6) Couldn't resolve host xxx``` 或是请求等待时间较长，与作者交流后发现是 AAAA 记录 no-ip 的问题，于是需要等待远程 DNS 响应 AAAA 结果，由于节点挂掉，无法拿到远程 DNS 响应，所以出现了异常情况。
建议在 Passwall 中为 ChinaDNS-NG 增加 ```noip-as-chnip``` 参数的选项，让用户自行选择是否接受国内 DNS 的 no-ip 响应，使用该参数后即使节点挂掉，也不影响所有国内请求。

模拟异常的方法：远程 DNS 设置为一个非 DNS 的 IP，例如 188.177.166.155
举例异常的域名：kwx.cc （不存在于任何列表之中，但解析 IP 为国内，且没有 AAAA 记录）

@xiaorouji @nftbty @lwb1978 

### 描述你想要的解决方案

建议在 Passwall 中为 ChinaDNS-NG 增加 ```noip-as-chnip``` 参数的选项，让用户自行选择是否接受国内 DNS 的 no-ip 响应，使用该参数后即使节点挂掉，也不影响全部国内请求。

### 描述你考虑过的替代方案

对于 WAN 口没有 IPv6 的环境，直接 no-ipv6 过滤掉所有 AAAA 响应，或是直接增加一个“过滤所有域名 IPv6”的选项。

### 其他信息

[--noip-as-chnip 选项的作用](https://github.com/zfl9/chinadns-ng?tab=readme-ov-file#--noip-as-chnip-%E9%80%89%E9%A1%B9%E7%9A%84%E4%BD%9C%E7%94%A8)

**Comment by gito10** [comment]
--noip-as-chnip 选项最后有这一句
>默认拒绝 china 上游的 no-ip 结果是为了避开 gfw 污染，防止 gfw 故意对某些域名返回空 answer (no-ip)。

不知道国内DNS是否有对某些域名故意返回空结果的问题

**Comment by dusty-97** [comment]
> --noip-as-chnip 选项最后有这一句
> 
> > 默认拒绝 china 上游的 no-ip 结果是为了避开 gfw 污染，防止 gfw 故意对某些域名返回空 answer (no-ip)。
> 
> 不知道国内DNS是否有对某些域名故意返回空结果的问题

一般来说，这种情况国内DNS使用DoT/DoH可解，只有部分地区的运营商或反诈中心会劫持DNS返回空。
反馈的时候也有考虑到这种情况，所以目前的建议是作为一个可选项，例如命名为“接受国内 DNS 空响应”。

**Comment by dusty-97** [comment]
在目前的逻辑下，其实也影响了 tag:none + china ip + no ipv6 域名的 cURL 请求效率，必须等待远程 DNS 返回 AAAA 结果，远程 DNS 挂掉时就会导致 cURL 请求失败或等待过长的时间。这个问题修改国内 DNS 是不能解决的，只能调整  ChinaDNS-NG 的参数（--noip-as-chnip 或者 no-ipv6 全部）。

**Comment by yyshell** [comment]
感觉现在96110比gfw还恶心，好多正常的地址被劫持。

**Comment by BGzEroll** [comment]
或许，节点挂掉了你应该及时更换节点，而不是冒着可能会导致dns污染的风险接受china上游的no-ip

**Comment by dusty-97** [comment]
> 或许，节点挂掉了你应该及时更换节点，而不是冒着可能会导致dns污染的风险接受china上游的no-ip

gfw 污染不存在 no-ip 的情况，只有运营商和反诈才会这么做，国内使用 DoT/DoH 即可解决。
另外，还有使用 no-ipv6 过滤所有域名的替代方案（目前只能过滤代理列表），对于不使用 IPv6 的人来说是最合适的解决方案了。

目前的逻辑确实影响了国内访问，即使节点没有挂掉，cURL 请求 tag:none 网站的响应速度也会比没有开启 ChinaDNS-NG 时慢（即 cURL 必须等待 AAAA 响应，而国内大多数网站不支持 IPv6，国内 DNS AAAA 响应了 no-ip，此时必须等待远程 DNS AAAA 响应 no-ip，cURL 才能开始向国内 IPv4 地址发送请求）。不管节点有没有挂掉，都不能影响国内访问才对。

**Comment by BGzEroll** [comment]
> > 或许，节点挂掉了你应该及时更换节点，而不是冒着可能会导致dns污染的风险接受china上游的no-ip
> 
> gfw 污染不存在 no-ip 的情况，只有运营商和反诈才会这么做，国内使用 DoT/DoH 即可解决。 另外，还有使用 no-ipv6 过滤所有域名的替代方案（目前只能过滤代理列表），对于不使用 IPv6 的人来说是最合适的解决方案了。
> 
> 目前的逻辑确实影响了国内访问，即使节点没有挂掉，cURL 请求 tag:none 网站的响应速度也会比没有开启 ChinaDNS-NG 时慢（即 cURL 必须等待 AAAA 响应，而国内大多数网站不支持 IPv6，国内 DNS AAAA 响应了 no-ip，此时必须等待远程 DNS AAAA 响应 no-ip，cURL 才能开始向国内 IPv4 地址发送请求）。不管节点有没有挂掉，都不能影响国内访问才对。

在有dns缓存的情况下或许初次访问的稍高点的响应并不会太影响体验。而且并不能保证gfw对域名不会返回空ip，你提到了**国内使用 DoT/DoH**，这便增加了组件，那为何不将这些组件应用于可信上游，直接在可信上游对AAAA解析请求直接返回no-ip？

**Comment by dusty-97** [comment]
> > > 或许，节点挂掉了你应该及时更换节点，而不是冒着可能会导致dns污染的风险接受china上游的no-ip
> > 
> > 
> > gfw 污染不存在 no-ip 的情况，只有运营商和反诈才会这么做，国内使用 DoT/DoH 即可解决。 另外，还有使用 no-ipv6 过滤所有域名的替代方案（目前只能过滤代理列表），对于不使用 IPv6 的人来说是最合适的解决方案了。
> > 目前的逻辑确实影响了国内访问，即使节点没有挂掉，cURL 请求 tag:none 网站的响应速度也会比没有开启 ChinaDNS-NG 时慢（即 cURL 必须等待 AAAA 响应，而国内大多数网站不支持 IPv6，国内 DNS AAAA 响应了 no-ip，此时必须等待远程 DNS AAAA 响应 no-ip，cURL 才能开始向国内 IPv4 地址发送请求）。不管节点有没有挂掉，都不能影响国内访问才对。
> 
> 在有dns缓存的情况下或许初次访问的稍高点的响应并不会太影响体验。而且并不能保证gfw对域名不会返回空ip，你提到了**国内使用 DoT/DoH**，这便增加了组件，那为何不将这些组件应用于可信上游，直接在可信上游对AAAA解析请求直接返回no-ip？

确实没有办法保证gfw不会返回空ip，但目前确实没有发现gfw会这么做。我提出的建议是可选项，并非强制接受空ip，这也是 ChinaDNS-NG 自带的可选配置。
另外，我在替代方案中提到了，ChinaDNS-NG 本身就提供了过滤 AAAA 的选项（no-ipv6），没有必要再套一层其他组件，这只会让配置更复杂。

每个人都有不同的需求和预算，有的人用一年上千的机场，有的人用一年一两百的机场，或是自建，但都无法保证节点能长期稳定在线。无论如何，保证国内请求不受影响，并尽可能让配置简单化才是最重要的。

**Comment by dusty-97** [comment]
> Stale Issue

No!

**Comment by gito10** [comment]
#3283
试试

**Comment by yyysuo** [comment]
这种情况下，接受AAAA的空响应就行了，A的空响应可以不接受，这样体验更好一些，要不然像下列域名很可能无法访问了
https://c.mi.com/global/
https://www.fx168news.com/
