### ISSUE TITLE
[Feature Request]: 关于DNS，远程DoH的自定义填写

### ISSUE THREAD

**Issue by bcseputetto** [xiaorouji/openwrt-package#3247]
### 描述你想要的新功能

目前DNS的Xray DoH和Sing-box DoH，填写自定义远程DNS时，格式是
URL
或者
URL,IP
比如
https://dns.abc.com/dns-query
或者
https://dns.abc.com/dns-query,123.123.123.123
希望在此处的IP格式能够支持IPv6

### 描述你想要的解决方案

URL,IP 的IP能够支持IPv6格式
https://dns.abc.com/dns-query,2001:2001::123:123:123:123
当前可以通过直接修改 /etc/config/passwall 配置文件，来让它强行以这样的配置工作。
目前看来只是 luci上限制了IPv6格式

**Comment by CharlesLocke** [comment]
![2024-06-04_21-36-29](https://github.com/xiaorouji/openwrt-passwall/assets/22140090/9b139397-be41-4619-9a1b-9434e3ccd607)
你好，不知道我这样用对不对。

**Comment by bcseputetto** [comment]
@CharlesLocke 这样应该是可以的，但我的SSL证书并没有签发在IP上，得用域名
所以需要 域名,ip 的格式，你这个其实就相当于 单域名 的格式了，后面不加ip

**Comment by gito10** [comment]
刚看了代码，这个要支持IPv6地址格式很好改，但是我想应该要加限制条件，比如IPv6透明代理开启才允许输入v6地址，要不远程DNS就成直连了。

不过，为何要用v6地址呢，一般公共DNS不都是双栈的，v4通用性还更高。难不成是自己搭建的DNS服务，只有v6单栈？不过有v6地址的一般也有v4地址吧，难道通过v6地址的延迟更低？

**Comment by bcseputetto** [comment]
@nftbty 这是因为我是自建DNS，DNS和节点在同一台服务器上。我这台服务器是双栈接入的，有IPv4和IPv6
passwall不是有一个特性，就是节点IP会加入直连列表(节点白名单)，导致DNS可能也会走直连，所以我才想节点走IPv4，DNS走IPv6

**Comment by gito10** [comment]
不对啊，你的自建DNS和节点在一台服务器，那你的远程DNS本来也就是直连，只不过走v4是DoH直连，对外表现HTTPS；走v6是DoH外面套一层代理协议，对外表现看代理协议。

所以你用v6地址其实流量路径是一样的，反而还要多一次加密解密，怎么看都不如直接用v4地址直连。

唯一的差异可能就是请求的源IP地址，DoH直连是你国内客户端IP，走代理是服务器本机IP？

**Comment by bcseputetto** [comment]
@nftbty 抱歉，再补充一些信息，我目前所在地方有前置审计，所以节点作为落地使用，有使用前置代理。如果DNS直连可能被 TCP RESET

**Comment by gito10** [comment]
先简单修改允许输入IPv6地址，后续考虑要不要加上限制条件，比如开启IPv6透明代理，或者节点和DNS都是Xray或都是Sing-Box情况下，才允许输入IPv6地址。
