### ISSUE TITLE
[Feature Request]: passwall 链式代理，也叫前置代理  落地代理（无法设置sock5这种类型的）

### ISSUE THREAD

**Issue by mingtianquan** [xiaorouji/openwrt-package#3250]
### 描述你想要的新功能

passwall 链式代理，也叫前置代理  落地代理（无法设置sock5这种类型的）

### 描述你想要的解决方案

vless和vmess这种的节点无法选择    落地节点 无法选择sock5 类型的节点

**Comment by OF65FUpwyvvy** [comment]
设置socks必须选择内核
前置代理vless的内核是xray，那socks也必须选xray
![chrome_E9Xl62VCao](https://github.com/xiaorouji/openwrt-passwall/assets/70679435/4dc5872a-2951-4409-8604-6ff9626c3d54)

**Comment by gito10** [comment]
目前落地节点和前置代理类型必须同时为Xray或 Sing-Box。
因为只有这俩支持多协议+前置代理，所以节点配置里只有这两个类型的节点才有落地节点选项，能选的节点也只有类型一样的节点。

其他类型的前置代理目前没时间做，需要的话可以改用分流节点来实现，其他规则都关闭，只选一个默认节点，其实配置上是等效的，只是配置界面看起来很复杂。

**Comment by nftbty** [comment]
目前落地节点和前置代理类型必须同时为Xray或 Sing-Box。
因为只有这俩支持多协议+前置代理，所以节点配置里只有这两个类型的节点才有落地节点选项，能选的节点也只有类型一样的节点。

其他类型的前置代理目前没时间做，需要的话可以改用分流节点来实现，其他规则都关闭，只选一个默认节点，其实配置上是等效的，只是配置界面看起来很复杂。

**Comment by pp-X** [comment]
奇怪分流可以实现，但是在节点里面落地节点设置了不行

**Comment by laaArmy** [comment]
我也是，在节点里面设置是无效的
