### ISSUE TITLE
[Feature Request]: 新增删除gfwlist,chnroute(6),chnlist,geoip,geosite(网络规则列表)的选项

### ISSUE THREAD

**Issue by AlephZHAO** [xiaorouji/openwrt-package#3255]
### 描述你想要的新功能

新增**删除**`gfwlist,chnroute(6),chnlist,geoip,geosite`的选项，于`规则管理-规则版本-手动更新`旁边
方便在下载完成网络列表后对其进行管理、删除。

### 描述你想要的解决方案

于`规则管理-规则版本-手动更新`旁边，增加“删除部分/所有规则列表”，可以删除全部的网络列表或自行选择删除部分的网络列表。

**Comment by lwb1978** [comment]
这需求……你确定删除了这些文件PW还能工作吗？

**Comment by dl250** [comment]
我用最新源码编译的固件，passwall显示延迟，但是无法连接谷歌怎么回事，节点正常，没升级固件插件版本为 4.76-1没问题，今天拉取最新源码编译，插件连通谷歌有延迟，但是无法上谷歌，节点在手机上正常，切换DNS分流那里，还是无法连接谷歌

**Comment by AlephZHAO** [comment]
> 这需求……你确定删除了这些文件PW还能工作吗？

感谢回复！
可能有时不需要PW继续工作了，比如不使用PW时，删除所有规则，考虑到有的路由存储空间不大，所以删除掉这么多的规则会释放一些存储空间。
不过这步操作是有替选方案的，不落实这个需求也相对来说没有什么影响。
