### ISSUE TITLE
[Bug]:  DNS 无法解析 

### ISSUE THREAD

**Issue by Klosw** [xiaorouji/openwrt-package#3260]
### 描述您遇到的bug

我在使用过程中部分域名会出现无法解析的问题 , 浏览器提示  DNS_PROBE_FINISHED_NXDOMAIN 

$> nslookup help.steampowered.com
服务器: OpenWrt.lan
Address: fd6b:29d4:d150::1

DNS request timed out.
timeout was 2 seconds.

$> nslookup help.steampowered.com 8.8.8.8
服务器: dns.google
Address: 8.8.8.8

非权威应答:
名称: help.steampowered.com
Address: 23.42.184.162 

### 复现此Bug的步骤

1. 重置配置
2. 新增 sing-box Hysteria2 节点 , 
3. 后打开 Socks 配置 配置添加新增的 sing-box Hysteria2  用于做自动切换, 
4. 新增刚刚的自动切换 Socks 配置 节点
5. 勾选TCP节点为刚刚配置的自动切换节点
6. 修改首页DNS配置 改成 Dnsmasq  (我这边选择 Dnsmasq + ChinaDNS-NG ,连Google都无法访问), 远端DNS修改为 8.8.8.8 
7. 浏览器切换到无痕模式 打开 amd.com 等待许久 提示 无法访问 提示 DNS_PROBE_FINISHED_NXDOMAIN 
8. 手动在规则列表添加amd.com走代理 就能正常访问 

版本降级到 4.77-3 就能正常解析相关DNS  (4.77-4 , 4.77-5 未测速直接降级到的 4.77-3 )

### 您想要实现的目的

能正常解析DNS

### 日志信息

2024-06-12 13:55:14: 删除iptables防火墙规则完成。
2024-06-12 13:55:14: 删除nftables防火墙规则完成。
2024-06-12 13:55:17: 清空并关闭相关程序和缓存完成。
2024-06-12 13:55:18: 分析 Socks 服务的节点配置...
2024-06-12 13:55:18:   - Socks节点：[tokyo_cdn-singbox_hysteria2]147.78.243.205:17600，启动 0.0.0.0:1081
2024-06-12 13:55:19: TCP节点：[自动切换]，监听端口：1041
2024-06-12 13:55:19: UDP节点没有选择或为空，不代理UDP。
2024-06-12 13:55:19: DNS域名解析：
2024-06-12 13:55:19:   - dns2tcp(127.0.0.1#15353) -> tcp://8.8.8.8:53
2024-06-12 13:55:19:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-06-12 13:55:19:   - 节点列表中的域名(vpslist)：223.5.5.5,119.29.29.29
2024-06-12 13:55:19:   - 域名白名单(whitelist)：223.5.5.5,119.29.29.29
2024-06-12 13:55:19:   - 代理域名表(blacklist)：127.0.0.1#15353
2024-06-12 13:55:19:   - 防火墙域名表(gfwlist)：127.0.0.1#15353
2024-06-12 13:55:25:   - 中国域名表(chnroute)：默认
2024-06-12 13:55:25:   - 默认：223.5.5.5,119.29.29.29
2024-06-12 13:55:25:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-06-12 13:55:26: 开始加载防火墙规则...
2024-06-12 13:55:26:   - [0]追加ISP IPv4 DNS到白名单：119.6.6.6
2024-06-12 13:55:26:   - [0]追加ISP IPv4 DNS到白名单：221.10.251.52
2024-06-12 13:55:26:   - [0]追加ISP IPv6 DNS到白名单：2408:8001:7000::
2024-06-12 13:55:26:   - [0]加入负载均衡的节点到ipset[passwall_vpslist]
2024-06-12 13:55:26:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-06-12 13:55:26:   - [0]追加直连DNS到iptables：223.5.5.5:53
2024-06-12 13:55:26:   - [0]追加直连DNS到iptables：119.29.29.29:53
2024-06-12 13:55:26:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-06-12 13:55:26:   - [0]将上游 DNS 服务器 8.8.8.8:53 加入到路由器自身代理的 TCP 转发链
2024-06-12 13:55:27:   - 访问控制：
2024-06-12 13:55:27:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-06-12 13:55:27:      - 【默认】，使用 TCP 节点[自动切换](REDIRECT:1041)
2024-06-12 13:55:27: 防火墙规则加载完成！
2024-06-12 13:55:29: 重启 dnsmasq 服务
2024-06-12 13:55:30: 运行完成！

 

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall/assets/13143959/db17e643-046e-4c9d-9911-6aa3b67bbb81)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/13143959/ff1bbcdb-cb8d-43de-8746-c6a247f07e87)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/13143959/2d4eacc5-0e4f-4d69-8ecc-1a592df584e0)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/13143959/aeba6809-020e-4ddc-9e27-9bca8b19a699)

![image](https://github.com/xiaorouji/openwrt-passwall/assets/13143959/17e3ec06-4b35-407a-8e7e-bf1c3fabeb47)

### 系统相关信息

Passwall 版本 【 4.77-6 】 releases的发行版 

OpenWrt  23.05.3 r23809-234f1a2efa  

内核版本  6.6.23 

防火墙自己开放了部分端口转发

运行的插件  KMS passwall ddns upnp SQM智能队列管理

**Comment by BGzEroll** [comment]
我猜是因为最近的commit为了修复dns重定向而把udp53端口给放行了，所以没法代理udp的53端口。
改用tcp来解析吧。

**Comment by lwb1978** [comment]
> 我猜是因为最近的commit为了修复dns重定向而把udp53端口给放行了，所以没法代理udp的53端口。 改用tcp来解析吧。

楼主没把环境说明清楚，比如PW的编译时间，是自己拉取最新代码编译还是用releases的发行版，如果是发行版就还没有dns重定向功能，如果是自己编译并已经有了重定向功能，关闭后再测试就知道是不是重定向功能影响了。
另外建议楼主把自己的环境和dns等相关设置也一并告知，只提个问题并说“没有复现步骤”是没人能处理的。

**Comment by Klosw** [comment]
> 我猜是因为最近的commit为了修复dns重定向而把udp53端口给放行了，所以没法代理udp的53端口。 改用tcp来解析吧。

你这个是说修改 pw 中远程DNS 解析修改成 TCP 吗 , 其实修改成TCP 还是 UDP 都不行 ,把域名加入代理列表 就能解析 . 很是奇怪

**Comment by Klosw** [comment]
> > 我猜是因为最近的commit为了修复dns重定向而把udp53端口给放行了，所以没法代理udp的53端口。 改用tcp来解析吧。
> 
> 楼主没把环境说明清楚，比如PW的编译时间，是自己拉取最新代码编译还是用releases的发行版，如果是发行版就还没有dns重定向功能，如果是自己编译并已经有了重定向功能，关闭后再测试就知道是不是重定向功能影响了。 另外建议楼主把自己的环境和dns等相关设置也一并告知，只提个问题并说“没有复现步骤”是没人能处理的。

这么和你说吧  都是默认的,Dnsmasq 也是默认基本上没有修改配置 , 就加了几个 hs2 节点(肯定是正常的) , 其他的 就没改过 ,你说要啥复现步骤 ,开着 pw 就无法解析DNS,关了就能解析了 ,我能怎么办 ,pw里面关于DNS的改来改去就是无法解析 . 

如果是你说的没有DNS重定向 要怎么解决改呢

**Comment by wtfr-dot** [comment]
你那日志里的信息显示你的passwall根本不是用的默认设置，而且混用了iptables和nftables，udp又没有代理节点，怎么可能解析udp://8.8.8.8？如果你是自己编译的就二选一，而且最新源码有dns重定向，提问题首先要介绍自己的使用环境，固件版本，是否自编译，配置信息等等

**Comment by Klosw** [comment]
> 你那日志里的信息显示你的passwall根本不是用的默认设置，而且混用了iptables和nftables，udp又没有代理节点，怎么可能解析udp://8.8.8.8？如果你是自己编译的就二选一，而且最新源码有dns重定向，提问题首先要介绍自己的使用环境，固件版本，是否自编译，配置信息等等

TCP 也不行呀

**Comment by Klosw** [comment]
> iptables和nftables

关于这个实在是 改成 iptables 不行 改成 nftables 也不行呀  
关于你说的 UDP 哪个,怎么改效果都一样(就是TCP也会出现DNS无法解析),把域名写到 代理列表 就能解析了 , 不写就无法解析

**Comment by Klosw** [comment]
> 使用环境，固件版本，是否自编译


 这几个不是写了吗, 要提供什么怎么提供,我不清楚你们需要哪些信息 ,又没有文档规范告诉我需要提供哪些系统信息 ,日志信息 ,我也不清楚怎么获取你们需要的 系统信息 以及日志信息 ,如果需要你说怎么提供,我这边就怎么提供呗

**Comment by Klosw** [comment]
> 你那日志里的信息显示你的passwall根本不是用的默认设置，而且混用了iptables和nftables，udp又没有代理节点，怎么可能解析udp://8.8.8.8？如果你是自己编译的就二选一，而且最新源码有dns重定向，提问题首先要介绍自己的使用环境，固件版本，是否自编译，配置信息等等

不是自己编译的,是直接下载的最新版本ipk进行安装的,我感觉这个和远程DNS关系不大,理论上DNS怎么都能解析不是吗, 我选UDP我也能正常上google的(所以应该不是UDP问题吧),你说了那么多,也没啥有用的,或者说啥时候出个新版本 ,我再安装一个新版本看看??

**Comment by lwb1978** [comment]
看了这么多回复，没法交流了，一直在质疑，能否心平气和，楼主现在不是解决问题的心态。
大家让你介绍环境你一直就不提，是否还运行或者安装有其他依赖防火墙工作的软件，比如mwan3等等，打死不说，每个回复都是带反问句，实在聊不下去了。
话说大家都用得好好的，用不了的要先从自身的环境找原因，要是都用不了，pw早就删库下架了。

**Comment by Klosw** [comment]
> 看了这么多回复，没啥好说的，一直在质疑，能否心平气和，楼主现在不在关心你的心态。 大家介绍环境你一直就不提，是否还运行或者安装其他依赖防火墙的软件，比如mwan3等等，打死不说，每个都带反问，实在不行就下去了。 话说大家都用得好好的，要先从自身的环境找原因，要都是用得着，早就删库了。
 
其实我的意思是,要怎么提供你所谓的环境介绍,有没有模版,比如需要执行什么命令,把命令的返回数据给到你们这边

> 是否还运行或者安装其他依赖防火墙的软件

我不清楚是否还运行其他的依赖防火墙软件 ,固件里面就 运行了 KMS passwall  ddns  upnp SQM智能队列管理 自己在防火墙开放了部分端口

**Comment by FK20100010** [comment]
> 还运行或者安装有其他依赖防火墙工作的软件，比如mwan3等等，打死不说，每个回复都是带反问句，实在聊不下去了。 话说大家都用得好好的，用不了的要先从自身的环境找原因，要是都用不了，pw早就删库下架了。

我自己编译的也出现这个问题了，而且pw版本显示4.77-5 ，ChinaDNS-NG 版本还是23年的
后面把ChinaDNS-NG 版本更新到2024.05.12就没问题了

**Comment by Klosw** [comment]
> > 还运行或者安装有其他依赖防火墙工作的软件，比如mwan3等等，打死不说，每个回复都是带反问句，实在聊不下去了。 话说大家都用得好好的，用不了的要先从自身的环境找原因，要是都用不了，pw早就删库下架了。
> 
> 我自己编译的也出现这个问题了，而且pw版本显示4.77-5 ，ChinaDNS-NG 版本还是23年的 后面把ChinaDNS-NG 版本更新到2024.05.12就没问题了

我也不清楚我这个是啥问题 用的是别人编译的固件 .ChinaDNS-NG 最新版本,也没法访问Google

**Comment by FK20100010** [comment]
> > > 还运行或者安装有其他依赖防火墙工作的软件，比如mwan3等等，打死不说，每个回复都是带反问句，实在聊不下去了。 话说大家都用得好好的，用不了的要先从自身的环境找原因，要是都用不了，pw早就删库下架了。
> > 
> > 
> > 我自己编译的也出现这个问题了，而且pw版本显示4.77-5 ，ChinaDNS-NG 版本还是23年的 后面把ChinaDNS-NG 版本更新到2024.05.12就没问题了
> 
> 我也不清楚我这个是啥问题 用的是别人编译的固件 .ChinaDNS-NG 最新版本,也没法访问Google

刚看了原来我编译的源码带了旧版本的pw跟ChinaDNS-NG，我是jdc ax1800pro😂😂😁

**Comment by Klosw** [comment]
> > > > 还运行或者安装有其他依赖防火墙工作的软件，比如mwan3等等，打死不说，每个回复都是带反问句，实在聊不下去了。 话说大家都用得好好的，用不了的要先从自身的环境找原因，要是都用不了，pw早就删库下架了。
> > > 
> > > 
> > > 我自己编译的也出现这个问题了，而且pw版本显示4.77-5 ，ChinaDNS-NG 版本还是23年的 后面把ChinaDNS-NG 版本更新到2024.05.12就没问题了
> > 
> > 
> > 我也不清楚我这个是啥问题 用的是别人编译的固件 .ChinaDNS-NG 最新版本,也没法访问Google
> 
> 刚看了原来我编译的源码带了旧版本的pw跟ChinaDNS-NG，我是jdc ax1800pro😂😂😁

我用的是别人的固件   我是虚拟机虚拟的x86的  [固件应该是这个](https://x86.cooluc.com/releases/openwrt-23.05/v23.05.3)
