### ISSUE TITLE
[Feature Request]:  IPK compile for for  MIPS 1004Kc V2.15

### ISSUE THREAD

**Issue by ingnelson** [xiaorouji/openwrt-package#3268]
### 描述你想要的新功能

Hello . Can you compile or create an IPK  file for my router :

cat /proc/cpuinfo
```
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : Hualink,HC841
processor               : 0
cpu model               : MIPS 1004Kc V2.15
```

I am trying but I can not do it myself .
I want to use passwall on my router.

Please.

### 描述你想要的解决方案

IPK  file for   MIPS 1004Kc V2.15

### 描述你考虑过的替代方案

IPK  file for   MIPS 1004Kc V2.15

**Comment by gito10** [comment]
soc MT7621, is `mipsel_24kc` in openwrt.

try the ipks for `mipsel_24kc` arch.

**Comment by ingnelson** [comment]
@nftbty 

This is the error : 

`Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-ipt-ipset
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipt-ipset found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-conntrack-netlink
 * pkg_hash_check_unresolved: cannot find dependency chinadns-ng for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2socks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2tcp for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.`

**Comment by gito10** [comment]
which version of openwrt are you using?
official or 3rd party, release or snapshot?

You can try `opkg update` before installing passwall.

**Comment by ingnelson** [comment]
@nftbty  I think it is a custom openwrt firmware is called : The Rooter .
My router is : Huastlink-HC851

This the link for all the firmware:
http://aturnofthenut.com/autobuilds/

I am not sure if I can install the original openwrt firmware on my Huastlink-HC851 router .

**Comment by ingnelson** [comment]
@nftbty what do you think? , is there I way I can use passwall on my router Huastlink-HC851 or I have to buy a different router ?

**Comment by bcseputetto** [comment]
@ingnelson 
```
cat /etc/os-release
```
Please execute the above command on the router terminal to obtain the firmware version information.

Note that certain kernel-dependent kmods must be completely consistent with the kernel's version and vermagic. This means that if the firmware you are using does not initially include these kmods, subsequent installation will be very difficult unless the party compiling the router firmware provides these kmods.

After resolving the kmod issues, the correct steps to install passwall should start with installing the dependent packages, which are in the zip archive within the project's release.

**Comment by bcseputetto** [comment]
Dependencies you need to resolve:

1. Some kmods: Certain kmods depend on the kernel and must be consistent with the kernel version and vermagic. This might be the most challenging issue to address. Either the firmware initially includes these kmods, or the router firmware provider offers the corresponding kmods on their own software source server, but this is quite difficult.

2. The packages chinadns-ng, dns2socks, dns2tcp, and tcping are all provided in the zip archive within the project's release. Find the archive with the corresponding architecture name and install it.

3. The luci-lua-runtime has been provided since OpenWrt 23.05. If you are not using version 23.05 or later, try using luci packages that include 19.07 in their name.

**Comment by ingnelson** [comment]
@bcseputetto  take a look please and let me know.


```
root@Huastlink:~# cat /etc/os-release
NAME="OpenWrt"
VERSION="22.03-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 22.03-SNAPSHOT"
VERSION_ID="22.03-snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r0-9676aa8c"
OPENWRT_BOARD="ramips/mt7621"
OPENWRT_ARCH="mipsel_24kc"
OPENWRT_TAINTS="no-all override"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 22.03-SNAPSHOT r0-9676aa8c"

```


```
root@Huastlink:~# cat /proc/cpuinfo
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : Hualink,HC841
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 586.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0f                                                                                                                                                             fb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_                                                                                                                                                             dcache userlocal vint perf_cntr_intr_bit cdmm perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 586.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0f                                                                                                                                                             fb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_                                                                                                                                                             dcache userlocal vint perf_cntr_intr_bit cdmm perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 2
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 586.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0f                                                                                                                                                             fb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_                                                                                                                                                             dcache userlocal vint perf_cntr_intr_bit cdmm perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 1
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 3
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 586.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0f                                                                                                                                                             fb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_                                                                                                                                                             dcache userlocal vint perf_cntr_intr_bit cdmm perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 1
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by bcseputetto** [comment]
@ingnelson 
`OPENWRT_ARCH="mipsel_24kc"`

Based on the information you provided, your OpenWrt ARCH is mipsel_24kc, and the OpenWrt version branch is 22.03.

![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/8c586bcc-0594-42b5-9cb0-c99c1b34dca2)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/29139573/f1048439-ae81-4eaa-b210-231163fcc504)

Therefore, you can download the luci packages that include 19.07 in their filenames, as well as the dependency zip archive for mipsel_24kc shown in the picture above.

However, the size of this dependency file might be too large for the flash capacity of your wireless router. You can choose not to install certain dependencies as needed.

Among these, chinadns-ng, dns2socks, dns2tcp, and tcping are mandatory. For the remaining dependencies, you can choose to install sing-box as your main proxy core program, as it supports a wide range of proxy protocols.

However, this still does not resolve the issue of missing kmod dependencies in your firmware.

**Comment by bcseputetto** [comment]
@ingnelson 
Although you have not yet responded, I can confirm that it is very difficult to install kmods via opkg because they need to match your kernel version and vermagic.
```
pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.218-1-af90120edfaf9c6e4a88d01a690199ea) for kmod-nf-reject
```
An error like the one above indicates that the installed kmod requires a kernel version or vermagic that does not match.

You need to find the developer who built this router firmware and have them include `kmod-nf-reject`, `kmod-nf-ipt`, `kmod-nf-log`, `kmod-ipt-core`, `kmod-nfnetlink`, `kmod-ipt-ipset`, `kmod-nf-conntrack`, and `kmod-nf-conntrack-netlink` in the firmware from the beginning.

If this is difficult to achieve, I think it would be a better option for you to purchase another router to use passwall, especially one that is officially supported by OpenWrt and has sufficient flash size.

**Comment by ingnelson** [comment]
@bcseputetto thank for your reply.  I am going to ask the developer if they can include those packages in the firmware, otherwise I have to purchase another router like ZBT W1608  and install the official openwrt and then swap the 5G module from my router to the new one.
