### ISSUE TITLE
[Feature Request]: Passwall能否支持V2Board自动导出的订阅链接

### ISSUE THREAD

**Issue by fengziX** [xiaorouji/openwrt-package#3271]
### 描述你想要的新功能

问了机场主, 他们的订阅链接是V2Board自动导出的, 就是一串很长的字母
用windows下的Clashmeta,V2ray和singbox都能正常导入全部节点(包含SS,VLESS和HY2)
但是passwall订阅就会显示一个节点"去除x条不合适线路"

### 描述你想要的解决方案

Passwall能否支持V2Board自动导出的订阅链接? 就是一串很长的字母

**Comment by fengziX** [comment]
忘了说了, "去除x条不合适线路" , 去除的就是hy2的节点 ,可以手动导入hy2的节点, 就是不能订阅

**Comment by lwb1978** [comment]
你用的什么版本的passwall ？我查看pw的订阅代码，没有看到“去除x条不合适线路”的这个提示的输出。

**Comment by solarflows** [comment]
> 你用的什么版本的passwall ？我查看pw的订阅代码，没有看到“去除x条不合适线路”的这个提示的输出。

它这个是面板自动转换的，具体应该也是通过UA，它检测UA的类型，passwall这种使用浏览器UA的会直接认为无法识别hy2的节点，面板自动生成一个节点叫去除x条不合适线路。🤣

**Comment by lwb1978** [comment]
pw的ua是可以自定义的，你自己修改成这个机场能认的试试。

**Comment by fengziX** [comment]
> pw的ua是可以自定义的，你自己修改成这个机场能认的试试。

几个自带的UA试过了还是认不到HY2，手动设置UA为V2rayNG也没有，明天再试试clashmeta。。。

**Comment by lwb1978** [comment]
我搜索了一下，好像（不确定）v2ray的ua是：Go-http-client/1.1 你把这个填到pw的ua去试试。

**Comment by solarflows** [comment]
> > pw的ua是可以自定义的，你自己修改成这个机场能认的试试。
> 
> 几个自带的UA试过了还是认不到HY2，手动设置UA为V2rayNG也没有，明天再试试clashmeta。。。

我看了xboard的源码，和v2board一样，通过UA确定客户端是否在hy2的支持列表，进而决定是否返回hy2节点，passwall不在列表内。[源码链接](https://github.com/cedar2025/Xboard/blob/dev/app/Http/Controllers/V1/Client/ClientController.php)。
你可以试试看这个ua，但是也有可能返回的订阅信息是passwall不支持的类型。如果是这样子只能反过来让服务端来适配客户端了。
`v2rayN/6.31`

**Comment by lwb1978** [comment]
> 
> 我看了xboard的源码，和v2board一样，通过UA确定客户端是否在hy2的支持列表，进而决定是否返回hy2节点，passwall不在列表内。[源码链接](https://github.com/cedar2025/Xboard/blob/dev/app/Http/Controllers/V1/Client/ClientController.php)。 你可以试试看这个ua，但是也有可能返回的订阅信息是passwall不支持的类型。如果是这样子只能反过来让服务端来适配客户端了。 `v2rayN/6.31`

ｂ(￣▽￣)ｄ ，按照xboard的源码，把ua设置成他列表里面的那几个客户端应该就可以获取到hy2了，根据现在一些客户端的最新版比如可以设置成下面其中一个：
NekoBox/1.3.1
sing-box/1.9.3
v2rayN/6.45

**Comment by solarflows** [comment]
搞完开始午休忘记回复了，v2rayN的可以用。老兄，passwall是不是只支持base64加密的订阅信息啊？

**Comment by lwb1978** [comment]
> 搞完开始午休忘记回复了，v2rayN的可以用。老兄，passwall是不是只支持base64加密的订阅信息啊？

看PW的订阅代码，确实目前只支持base64的解密，毕竟这个加解密的方式不需要密钥，也比较简单，如果机场用其他加密方式的话就得用专用的客户端了。

**Comment by gito10** [comment]
> 搞完开始午休忘记回复了，v2rayN的可以用。老兄，passwall是不是只支持base64加密的订阅信息啊？

用subconverter转换啊，公共服务不放心，可以在路由上安装，我passwall订阅链接都是本机subconverter转换的，主要是添加flag，调整节点名称格式。

**Comment by solarflows** [comment]
不瞒您说，我也是用的subconverter做订阅整合跟转换，我把它部署在homeassistant上面了，但是subconverter好像也不能在v2board系获得hy2的节点。(不改UA的情况下)

**Comment by fengziX** [comment]
> > 我看了xboard的源码，和v2board一样，通过UA确定客户端是否在hy2的支持列表，进而决定是否返回hy2节点，passwall不在列表内。[源码链接](https://github.com/cedar2025/Xboard/blob/dev/app/Http/Controllers/V1/Client/ClientController.php)。 你可以试试看这个ua，但是也有可能返回的订阅信息是passwall不支持的类型。如果是这样子只能反过来让服务端来适配客户端了。 `v2rayN/6.31`
> 
> ｂ(￣▽￣)ｄ ，按照xboard的源码，把ua设置成他列表里面的那几个客户端应该就可以获取到hy2了，根据现在一些客户端的最新版比如可以设置成下面其中一个： NekoBox/1.3.1 sing-box/1.9.3 v2rayN/6.45

确实可以订阅了, 感谢,  @lwb1978 要不把这几个软件UA也加入进passwall的订阅选项里面?

**Comment by lwb1978** [comment]
> 
> 确实可以订阅了, 感谢, @lwb1978 要不把这几个软件UA也加入进passwall的订阅选项里面?

这个可以有，过后我提交个PR。

**Comment by lwb1978** [comment]
ua设置中已经添加了v2rayN选项并设置为默认，这个帖子可以关闭了。
