### ISSUE TITLE
[Bug]: 页面/hide隐藏后无法输入网址直接正常访问了。

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-package#3272]
### 描述您遇到的bug

选页面隐藏后 ，输入 路由IP/cgi-bin/luci/admin/service/passwall 原来能正常进入，现在软件框架出来了，但中间内容会报错如下：
对不起，请求的目标未找到。
404 请求错误
No page is registered at '/admin/services/passwall'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

无法调度: /cgi-bin/luci/admin/service/passwall

### 复现此Bug的步骤

选隐藏/HIDE 然后进页面地址无法访问

### 您想要实现的目的

隐藏后 能通过页面地址进入使用

### 日志信息

无  没提示

### 系统相关信息

PW 4.77
chrome 100以上版本

### 其他信息

PASSWALL  4.77

**Comment by lwb1978** [comment]
试试/show 后能否显示出来？

**Comment by gito10** [comment]
这个不是bug，是我之前修改的时候，没想到有人会隐藏菜单入口后，还会手动输网址进入，直接判断如果入口隐藏，那么passwall的其他菜单不再加载。

要修改也很简单，问题是是否真的有必要。如果经常需要进后台的话，就不要隐藏了吧。

而且，即使改成跟以前一样，菜单隐藏也加载全部子菜单，URL /admin/services/passwall 也是没内容的，必须在后面加上具体的子菜单URL `/settings` 才能显示出来。

**Comment by gito10** [comment]
刚刚尝试了一下，仅隐藏菜单入口，但保留 `/services/passwall` URL注册，可行。只需要把菜单入口名称改为空串或者`nil`。

等会提交修改

**Comment by iamyangyiok** [comment]
> 刚刚尝试了一下，仅隐藏菜单入口，但保留 `/services/passwall` URL注册，可行。只需要把菜单入口名称改为空串或者`nil`。
> 
> 等会提交修改

谢谢 主要是隐藏自己知道能进就好， 外面有密码保护。主要是有时 怕 叫电信类的师傅来调拨号   看到了。真知道这个地址的，肯定也会SHOW进来，所以隐藏掉菜单就蛮好的。

**Comment by gito10** [comment]
试试 #3274 的修改，看能不能正常隐藏，并且 url 使用 `/admin/services/passwall` 成功进入passwall 页面。
在我的路由上是没问题的，不过我的系统luci库之前自己有过优化修改，之前 controller.lua 中 `index()`函数无法访问到全局定义变量的问题，在我的设备上就不存在，但正常的系统就会报错。

所以这次就不直接提交了，先提个PR，其他设备先测试没问题了，再合并。

**Comment by lwb1978** [comment]
> 试试 #3274 的修改，看能不能正常隐藏，并且 url 使用 `/admin/services/passwall` 成功进入passwall 页面。 在我的路由上是没问题的，不过我的系统luci库之前自己有过优化修改，之前 controller.lua 中 `index()`函数无法访问到全局定义变量的问题，在我的设备上就不存在，但正常的系统就会报错。
> 
> 所以这次就不直接提交了，先提个PR，其他设备先测试没问题了，再合并。

合并吧，ImmortalWrt 23.05上测试没有问题。
