### ISSUE TITLE
[Bug]: 无法解析“大机场”的订阅

### ISSUE THREAD

**Issue by xtxt19931207** [xiaorouji/openwrt-package#3273]
### 描述您遇到的bug

一直在用这个机场，之前是可以正常解析的，但是现在解析成功显示节点数为0，不知道是什么原因？
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10117261/7b67c52b-b836-4585-b7ff-dbcc6b38ca6e)

### 复现此Bug的步骤

点击手动订阅

### 您想要实现的目的

正常解析

### 日志信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/10117261/272e9466-85c0-421f-8563-9316605b8d23)

### 系统相关信息

passwall版本：4.55-2

**Comment by lwb1978** [comment]
你这个不能算bug只能算增强，现在5花8门的机场很多，一些机场的订阅数据格式不是常规标准，需要专用客户端，要全部兼容的话估计工作量很大，加上机场订阅是要钱的，大家总不能让免费开发pw的几个大佬们花钱买机场回来分析订阅数据吧。pw是开源的，如果懂lua和shell编写的人可以加油助力提交代码。

**Comment by lwb1978** [comment]
另外，你把你的机场订阅地址复制到浏览器里面打开看页面显示什么？

**Comment by 1WuNeiGui** [comment]
> 另外，你把你的机场订阅地址复制到浏览器里面打开看页面显示什么？

我把在passwall里无法订阅的链接复制到浏览器中，直接是空白页面，啥都没有，该订阅链接里的节点全为hysteria2节点

**Comment by 1WuNeiGui** [comment]
不过我把订阅链接复制到V2rayNg里面是可以更新的，而且把里面单一的hy2节点复制到passwall里也是可以使用的，应该就是机场商家订阅链接的问题，导致无法更新

**Comment by lwb1978** [comment]
复制到浏览器里打开都是空白页，那pw怎么解析得了，不过你可以试试在订阅设置那里修改一下“用户代理(User-Agent)”，或者修改"允许不安全的链接"看看。

**Comment by 1WuNeiGui** [comment]
我允许了不安全的连接，用户代理四个都试了，但是还是不行。

**Comment by bcseputetto** [comment]
@1WuNeiGui 这种情况，你应该先去机场的页面重新复制一下订阅链接，或者重置一次订阅链接，你用浏览器打开订阅链接至少里面得要有内容，passwall才能订阅节点，订阅链接打开是空的，passwall拿头解析啊

**Comment by 1WuNeiGui** [comment]
> @1WuNeiGui 这种情况，你应该先去机场的页面重新复制一下订阅链接，或者重置一次订阅链接，你用浏览器打开订阅链接至少里面得要有内容，passwall才能订阅节点，订阅链接打开是空的，passwall拿头解析啊

没有用，重置了也还是一样，复制到浏览器里直接空白，我的两个纯hysteria的机场都是这种情况，基本上只有他网站里推荐的客户端可以解析出节点，passwall、openclash都解析不出。不过openclash可以现在clash verge里导入订阅，拿到.yaml配置文件后再上传到openclash

**Comment by bcseputetto** [comment]
复制到浏览器里空白，那就意味着订阅链接没有内容，既然没有内容，passwall自然就无法解析，这不是passwall能解决的，你应该去找机场问问，而openclash专用的订阅，那个应该是获取 .yaml 文件，跟平常的订阅不太一样，平常的订阅里面应该是一堆乱码，也就是用base64之类转换过的节点信息，比如 ss://节点信息，这样转换成base64后的内容

**Comment by 1WuNeiGui** [comment]
嗯嗯，我已经去机场提交工单了，但是大概率是不会给解决的，先用别的机场了

**Comment by lwb1978** [comment]
> 嗯嗯，我已经去机场提交工单了，但是大概率是不会给解决的，先用别的机场了

你试试把PW的ua设置成下面3个其中1个看看能否订阅：
NekoBox/1.3.1
sing-box/1.9.3
v2rayN/6.45

**Comment by 1WuNeiGui** [comment]
> > 嗯嗯，我已经去机场提交工单了，但是大概率是不会给解决的，先用别的机场了
> 
> 你试试把PW的ua设置成下面3个其中1个看看能否订阅： NekoBox/1.3.1 sing-box/1.9.3 v2rayN/6.45

谢谢大佬，经过实测，我的机场订阅链接将ua设置为v2rayN/6.45可以解析出节点正常订阅了，不过有一个小小的问题，就是在节点列表页面，所有的节点的TCPing都显示超时，但是Ping和URL测试是正常的。
![屏幕截图 2024-06-24 160650](https://github.com/xiaorouji/openwrt-passwall/assets/95472175/4569a76b-827e-45cd-92e9-204e88508c39)

**Comment by lwb1978** [comment]
有一种可能，这个机场的节点不采用tcp，只采用udp端口，那tcping就指定超时了。

**Comment by 1WuNeiGui** [comment]
> 有一种可能，这个机场的节点不采用tcp，只采用udp端口，那tcping就指定超时了。

感谢大佬的回复，我在clash verge windows客户端里看了一下，节点确实都是UDP类型的

**Comment by xtxt19931207** [comment]
> > 嗯嗯，我已经去机场提交工单了，但是大概率是不会给解决的，先用别的机场了
> 
> 你试试把PW的ua设置成下面3个其中1个看看能否订阅：
> NekoBox/1.3.1
> sing-box/1.9.3
> v2rayN/6.45
感谢，按你说的能够正常订阅。

**Comment by ChiangYuen** [comment]
> > 嗯嗯，我已经去机场提交工单了，但是大概率是不会给解决的，先用别的机场了
> 
> 你试试把PW的ua设置成下面3个其中1个看看能否订阅： NekoBox/1.3.1 sing-box/1.9.3 v2rayN/6.45

感谢，果然是这个问题，改为v2rayN/6.45，就可以了！

**Comment by gito10** [comment]
好一个洛阳铲

@ChiangYuen 另外可以试一下填写
`NekoBox/1.3.1 sing-box/1.9.3 v2rayN/6.45`
和
`v2rayN/6.45 NekoBox/1.3.1 sing-box/1.9.3`
这样多个标识的，能不能订阅。
