### ISSUE TITLE
希望加上 Xray 的 SplitHTTP 传输协议。

### ISSUE THREAD

**Issue by lxhao61** [xiaorouji/openwrt-package#3278]
### 描述你想要的新功能

Xray 新出 SplitHTTP 传输协议，希望支持。

### 描述你想要的解决方案

希望加上 Xray 的 SplitHTTP 传输协议。

**Comment by lwb1978** [comment]
@nftbty 老大看看

**Comment by lxhao61** [comment]
请大神加上 Xray 的 SplitHTTP 传输协议。

**Comment by lwb1978** [comment]
已完成适配，但我没有SplitHTTP节点，现在只能确保正确生成配置文件，至于能否正常工作没法调试。
如果大家有SplitHTTP节点的话可拉取最新代码进行测试。

**Comment by lxhao61** [comment]
已测试，目前一切正常。

**Comment by lwb1978** [comment]
> 已测试，目前一切正常。

好的
