### ISSUE TITLE
[Bug]: 访问控制 不能添加局域网ip

### ISSUE THREAD

**Issue by love-dy** [xiaorouji/openwrt-package#3281]
### 描述您遇到的bug

访问控制 不能添加局域网ip，保存完后还是什么都没有

### 复现此Bug的步骤

访问控制

### 您想要实现的目的

屏蔽局域网ip 科学上网

### 日志信息

没有

### 截图

没有

### 系统相关信息

没有

### 其他信息

没有

**Comment by gito10** [comment]
这什么都没有，怎么判断是什么问题，至少把你想要设置的地方，和想要设置的值，截几个图吧。

**Comment by love-dy** [comment]
没有描述清楚吗？里面不是有个访问控制吗，点添加 保存 然后还是什么都没有，，最后想着重启一下试试，没想到重启后什么都没有了，自己恢复出厂设置了，几年了第一次遇到这种情况，也不能确定就是passwall的问题，现在都不敢轻易重启了

**Comment by gito10** [comment]
那应该不太可能是passwall的问题

**Comment by ZqinKing** [comment]
这更像是存储空间满了。

**Comment by WROIATE** [comment]
如果存储没满，看下你的文件系统是不是挂载和格式有问题

**Comment by withlqs** [comment]
相同问题+1，访问控制配置好+启用之后，日志里没有显示有访问控制添加的规则

**Comment by withlqs** [comment]
> 2024-06-26 16:23:04: 删除nftables防火墙规则完成。
> 2024-06-26 16:23:08: 清空并关闭相关程序和缓存完成。
> 2024-06-26 16:23:08: TCP节点：[ XXXXX ]，监听端口：1041
> 2024-06-26 16:23:08: DNS域名解析：
> 2024-06-26 16:23:08:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
> 2024-06-26 16:23:08:   - ChinaDNS-NG(127.0.0.1#15353)：直连DNS：119.29.29.29,223.5.5.5，可信DNS：tcp://1.1.1.1#53
> 2024-06-26 16:23:08:   - 节点列表中的域名(vpslist)：119.29.29.29,223.5.5.5
> 2024-06-26 16:23:08:   - 域名白名单(whitelist)：默认
> 2024-06-26 16:23:08:   - 代理域名表(blacklist)：默认
> 2024-06-26 16:23:08:   - 防火墙域名表(gfwlist)：默认
> 2024-06-26 16:23:08:   - 中国域名表(chnroute)：默认
> 2024-06-26 16:23:08:   - 默认：127.0.0.1#15353
> 2024-06-26 16:23:08:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
> 2024-06-26 16:23:08: 开始加载防火墙规则...
> 2024-06-26 16:23:09:   - [0]追加ISP IPv4 DNS到白名单：119.29.29.29
> 2024-06-26 16:23:09:   - [0]追加ISP IPv4 DNS到白名单：223.5.5.5
> 2024-06-26 16:23:09:   - [0]加入负载均衡的节点到nftset[passwall_vpslist]直连完成
> 2024-06-26 16:23:09:   - [1]加入所有节点到nftset[passwall_vpslist]直连完成
> 2024-06-26 16:23:09:   - [0]追加直连DNS到nftables：119.29.29.29:53
> 2024-06-26 16:23:09:   - [0]追加直连DNS到nftables：223.5.5.5:53
> 2024-06-26 16:23:09:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
> 2024-06-26 16:23:09:   - 访问控制：
> 2024-06-26 16:23:09:      - 【默认】，使用 TCP 节点[ XXXXX ](TPROXY:1041)
> 2024-06-26 16:23:09:      - 【默认】，使用 UDP 节点[ XXXXX ](TPROXY:1041)
> 2024-06-26 16:23:09: 防火墙规则加载完成！
> 2024-06-26 16:23:12: 重启 dnsmasq 服务
> 2024-06-26 16:23:12: 配置定时任务：自动更新规则。
> 2024-06-26 16:23:12: 配置定时任务：自动更新【 XXXXX 】订阅。
> 2024-06-26 16:23:12: 运行完成！

![passwall](https://github.com/xiaorouji/openwrt-passwall/assets/6522162/3a673583-9365-4170-b1df-d2c0e0668ff5)

**Comment by lyjhyjyes** [comment]
同样问题，新版passwall不太会用，无法控制局域网设备，而且打开国外网页效果不佳
