### ISSUE TITLE
[Bug]: 订阅有问题，对ipv6节点有异常过滤

### ISSUE THREAD

**Issue by luowei729** [xiaorouji/openwrt-package#3284]
### 描述您遇到的bug

当前4.77-6 版本   hy1节点 订阅解析有问题 端口会多加一个 /
导致 hy1 ipv6节点会被过滤掉，hy1 ipv4节点虽然能订阅添加，但是端口数字后面多个 / 节点不能使用
给我个邮箱，我邮件发给你测试订阅地址

### 复现此Bug的步骤

当前4.77-6 版本   hy1节点 订阅解析有问题 端口会多加一个 /
导致 hy1 ipv6节点会被过滤掉，hy1 ipv4节点虽然能订阅添加，但是端口数字后面多个 / 节点不能使用
给我个邮箱，我邮件发给你测试订阅地址

### 您想要实现的目的

当前4.77-6 版本   hy1节点 订阅解析有问题 端口会多加一个 /
导致 hy1 ipv6节点会被过滤掉，hy1 ipv4节点虽然能订阅添加，但是端口数字后面多个 / 节点不能使用
给我个邮箱，我邮件发给你测试订阅地址

### 日志信息

2024-06-25 05:29:20: 开始订阅...
2024-06-25 05:29:20: 正在订阅:【xx】https://xxxxxx/api/v1/client/subscribe?token=
2024-06-25 05:29:21: 丢弃过滤节点: sing-box 节点, Hy-ipv6日本东京
2024-06-25 05:29:21: 丢弃过滤节点: sing-box 节点, Hy-ipv6中国香港
2024-06-25 05:29:21: 成功解析【xx】节点数量: 14
2024-06-25 05:29:21: 更新【TCP节点】第一匹配节点：Hy2-香港
2024-06-25 05:29:21: 更新【HAProxy负载均衡节点列表[1]】第一匹配节点：Hy2-ipv6香港
2024-06-25 05:29:21: 更新【HAProxy负载均衡节点列表[2]】第一匹配节点：Hy-香港
2024-06-25 05:29:21: 更新【HAProxy负载均衡节点列表[3]】第一匹配节点：Hy-东京
2024-06-25 05:29:21: 更新【HAProxy负载均衡节点列表[4]】第一匹配节点：Hy2-ipv6东京

### 系统相关信息

4.77-6 版本

**Comment by luowei729** [comment]
找到原因了，hy1节点  订阅解析有问题   端口会多加一个  /
导致 hy1 ipv6节点会被过滤掉，hy1 ipv4节点虽然能订阅添加，但是端口数字后面多个 /   节点不能使用
![image](https://github.com/xiaorouji/openwrt-passwall/assets/10611605/3a6f60b7-ad42-45c3-8425-548ba62c62ca)

测试下来，passwall对  订阅实现的不好，建议参考下  其他开源项目的实现  如 ：
 https://github.com/hiddify/hiddify-next
 https://github.com/clash-verge-rev/clash-verge-rev
 这2个项目订阅功能兼容性很好

**Comment by lwb1978** [comment]
参考没多大用，所用平台不同，编程语言也不同，你能提供一下你机场里的hy1的链接进行调试修改更好，提供时把域名做一下脱敏处理。

**Comment by luowei729** [comment]
> 参考没多大用，所用平台不同，编程语言也不同，你能提供一下你机场里的hy1的链接进行调试修改更好，提供时把域名做一下脱敏处理。

这是测试订阅地址设置了有效期，用了cloudflare works 反代域名，works的这个域名是被墙的，需要开代理才能打开订阅：
https://sub.sublink.workers.dev/api/v1/client/subscribe?token=365c3a89f0f3c0b1d1f6f12186fea830

**Comment by luowei729** [comment]
> 参考没多大用，所用平台不同，编程语言也不同，你能提供一下你机场里的hy1的链接进行调试修改更好，提供时把域名做一下脱敏处理。

我不会开发，借鉴他们的项目，单独搞个处理订阅的模块，嵌入到passwall

**Comment by lwb1978** [comment]
我通过你的订阅获取到了hy链接，你可以把你的订阅删除了，以免泄漏，我把几个链接处理后发到这里，看哪位大佬有空可以先处理一下，我这几天外出没电脑，如果到时其他大佬们还没处理的话，我回家后试试，具体链接如下（修改ip了，只用于测试导入，无法连接的）:
hysteria://128.154.212.99:44444/?protocol=udp&auth=d16a53e3-5583-449e-af05-fb3c29414424&insecure=1&peer=sublink.cloudns.ch&upmbps=100&downmbps=100#Hy-%E9%A6%96%E5%B0%94
hysteria://[2400:38e0:1:404a::a4]:44447/?protocol=udp&auth=d16a53e3-5583-449e-af05-fb3c29414424&insecure=1&peer=sublink.cloudns.ch&upmbps=150&downmbps=150#Hy-ipv6%E6%97%A5%E6%9C%AC%E4%B8%9C%E4%BA%AC
hysteria://[2a06:dfc1:8b46:394e:be24:11ff:fe3c:2cd1]:44448/?protocol=udp&auth=d16a53e3-5583-449e-af05-fb3c29414424&insecure=1&peer=sublink.cloudns.ch&upmbps=500&downmbps=500#Hy-ipv6%E4%B8%AD%E5%9B%BD%E9%A6%99%E6%B8%AF

**Comment by lwb1978** [comment]
在通过链接导入这里测试确实如楼主所说有问题，v4链接导入后端口后面有斜杠，v6链接无法导入。

**Comment by luowei729** [comment]
> 在通过链接导入这里测试确实如楼主所说有问题，v4链接导入后端口后面有斜杠，v6链接无法导入。

需要对订阅这块了解的老哥把订阅这个模块功能搞一下，支持识别多种导入方式 clash 订阅格式，sing-box订阅格式等搞个开关，设置订阅的时候可以选

**Comment by lwb1978** [comment]
已经修正Hysteria订阅问题，我这边测试没有问题，也提交了PR，你下载下面的文件把文件名重命名，将后缀.txt删除，用ssh上传到路由/usr/share/passwall目录替换原文件后也测试一下。

[subscribe.lua.txt](https://github.com/user-attachments/files/15980893/subscribe.lua.txt)

**Comment by luowei729** [comment]
> 已经修正Hysteria订阅问题，我这边测试没有问题，也提交了PR，你下载下面的文件把文件名重命名，将后缀.txt删除，用ssh上传到路由/usr/share/passwall目录替换原文件后也测试一下。
> 
> [subscribe.lua.txt](https://github.com/user-attachments/files/15980893/subscribe.lua.txt)

测试订阅正常了，感谢大佬
