### ISSUE TITLE
刚刚更新完，就打不开了

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#3286]
### 描述您遇到的bug

官方的main，刚刚更新完，就打不开了

### 复现此Bug的步骤

官方的main，刚刚更新完，就打不开了

### 您想要实现的目的

官方的main，可以正常打开

### 日志信息

官方的main，刚刚更新完，就打不开了

### 截图

![屏幕截图 2024-06-25 135221](https://github.com/xiaorouji/openwrt-passwall/assets/62717864/d4217449-0a30-4dbe-a8a8-08114e7df81c)

### 系统相关信息

4.776最新版

**Comment by hcym** [comment]
呵呵，不折腾不舒服斯基
也是luci挂了

**Comment by gito10** [comment]
已修复
