### ISSUE TITLE
[Bug]: 不定期会出现本地远程同时解析dns

### ISSUE THREAD

**Issue by wtfr-dot** [xiaorouji/openwrt-package#3288]
### 描述您遇到的bug

遇到过好几次本地远程同时解析的情况了，其它朋友也反应过，特别是Google的域名，通过清空ipset操作会恢复正常，我看了一下解析记录，从规则的角度来说不应该出现这种情况，而且同时解析的域名也不是Google的冷僻域名，这是否与chinadns-ng有关，虽然我没有启用它，但编译了的，列举几个解析记录：
127.0.0.1 query mtalk.google.com, type 1, time 0ms, speed: 49.5ms, group default, 
[2024-06-25 19:53:37,958] 127.0.0.1 query mtalk.google.com, type 1, time 0ms, speed: -0.1ms, group us,
127.0.0.1 query clients4.google.com, type 1, time 0ms, speed: 0.1ms, group default
[2024-06-25 19:54:49,198] 127.0.0.1 query clients4.google.com, type 1, time 0ms, speed: -0.1ms, group us
127.0.0.1 query www.google.com, type 1, time 0ms, speed: 0.1ms, group default
[2024-06-25 19:57:25,739] 127.0.0.1 query www.google.com, type 1, time 0ms, speed: -0.1ms, group us
 127.0.0.1 query support.google.com, type 1, time 265ms, speed: -0.1ms, group us,
[2024-06-25 20:05:06,765] 127.0.0.1 query support.google.com, type 1, time 320ms, speed: 0.1ms, group default,
127.0.0.1 query google.com, type 1, time 0ms, speed: 0.1ms, group default, 
[2024-06-25 20:10:28,129] 127.0.0.1 query google.com, type 1, time 0ms, speed: -0.1ms, group us, 
可以看到，Google最常见的域名解析都出现了这种情况，请大佬再查看一下代码是否某个环节有点bug，我再试试去掉chinadns-ng模块试试

### 复现此Bug的步骤

由于频繁更新固件，单一版本的固件使用时间都不长，而且有时固件也不会出现问题，无法预知什么时候出现

### 您想要实现的目的

正确的dns分流解析

### 日志信息

见上

### 系统相关信息

![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/1aeb3a67-87de-4d0f-ac2f-efafac97b1eb)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/ae575a4a-2826-45d6-b1de-c97cd1fe1024)

**Comment by wtfr-dot** [comment]
刚刚才发现chinadns-ng已经成依赖了，只能望大佬们排查了

**Comment by wtfr-dot** [comment]
另外，出现本地远程同时解析后路由好像也有问题，比如www.Google.com的ip解析出来后通常走的是本地解析的ip，因为这是打开网页提示不安全，很明显被劫持了，但通过网页的帮助打开support.google.com又能正常打开帮助页，应该是路由环节出了问题，但路由规则是应该没有问题的

**Comment by lwb1978** [comment]
> 刚刚才发现chinadns-ng已经成依赖了，只能望大佬们排查了

依赖并不意味它会时刻运行，你dns分流不选择:Dnsmasq + ChinaDNS-NG，那么他就不会运行。

**Comment by lwb1978** [comment]
另外你要截图一下你PW的dns设置界面上来，否则大家都没得帮你分析。
还有就是是否启用了分流，代理使用了什么模式都要交代一下。

**Comment by wtfr-dot** [comment]
我dns分流没选择:Dnsmasq + ChinaDNS-NG，它确实也没运行，我远程使用的udp传给smartdns，passwall的dns都没有运行，发生的现象更像是chinadns-ng的行为逻辑
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/90943ff1-a862-495f-bd49-5fa09291e2e9)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/d54e6447-ef8b-40eb-b6ef-1eb4e22133f7)
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/f889da0f-ea96-4491-94be-c81f35f917a3)

出现这种问题时配置是没有变化的，而且不是每次都出现，更像是某个时刻触发了某个bug，这应该是在路由判断阶段

**Comment by wtfr-dot** [comment]
从最后发出连接的情况来看，走的应该是直连，因为本地远程都解析出了结果，但走的是本地解析的ip地址，而且当我将分流规则的“direct”提到“proxy”前面时更容易出现本该走代理的直接走了直连，也是偶尔出现这种情况，像某一时刻突然失控了一样，分流策略采用的是AsIs
我在#3216中提到过将“direct”提到“proxy”前会出现问题，所以我后面的分流配置一直采用的是“direct”放在最后，目前除了这个issue提到的问题，其它问题到是没有出现过了

**Comment by wtfr-dot** [comment]
另外是否与规则下载不成功后的处理有关系，最近这几天都出现了下载某些规则失败，或者是规则下载完成，但停留在了“规则更新完毕...”这个提示不动，不过发现这个情况后我都会再手动更新一次，我截图的这个是重新编译的固件，重新下载成功了的，整个流程也是走完了的，出现问题的那个日志则不是
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/f6ce5614-00ea-47b1-9479-b41259ae2fa2)

**Comment by lwb1978** [comment]
既然这样为何不直接编译pw smartdns的版本，你现在的用法dns走了弯路，多个香炉多个鬼，现在不好说是pw问题还是你远程dns的上游的问题。另外你的dns显示未运行，那中间估计会有环节有问题。

**Comment by wtfr-dot** [comment]
> 既然这样为何不直接编译pw smartdns的版本，你现在的用法dns走了弯路，多个香炉多个鬼，现在不好说是pw问题还是你远程dns的上游的问题。另外你的dns显示未运行，那中间估计会有环节有问题。

目前smartdns分支更新不及时，所以我转到主分支上了，另外我现在的用法dns并没有走弯路，smartdns分支虽然是把规则文件和配置以conf方式加入smartdns，但路由判断同样是在passwall这边进行的，处理流程是一样的，而且smartdns这边只是单纯进行解析，而且它的行为也没有错，因为它只接受passwall发过来的查询请求，我在smartdns没配置任何ipset等分流设置，它的行为是很单纯的
dns显示未运行我不知道是以什么条件判定的，不过我采用AsIs本身xray的dns模块也不处理dns解析（好像选IPIfNonMatch也显示未运行），说到这，远程采用udp://127.0.0.1:6553这种方式历史上在某些阶段是有问题的，会不会在处理这种方式时有某种bug？

**Comment by wtfr-dot** [comment]
另外防火墙mangle表里127.0.0.1:6053这个规则是smartnds处理dnsmsaq转发过来的dns查询的监听地址，但它重来没有任何流量，想必是它处于lanlist这个规则的后面造成的，这样的话这条规则实际上是没用的，但逻辑上它应该参与进去
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/09af30e0-1125-41e6-abc7-4b7ccce82e45)

**Comment by lwb1978** [comment]
> 另外防火墙mangle表里127.0.0.1:6053这个规则是smartnds处理dnsmsaq转发过来的dns查询的监听地址，但它重来没有任何流量，想必是它处于lanlist这个规则的后面造成的，这样的话这条规则实际上是没用的，但逻辑上它应该参与进去 ![image](https://private-user-images.githubusercontent.com/81218740/343002307-09af30e0-1125-41e6-abc7-4b7ccce82e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzUzMjQsIm5iZiI6MTcxOTM3NTAyNCwicGF0aCI6Ii84MTIxODc0MC8zNDMwMDIzMDctMDlhZjMwZTAtMTEyNS00MWU2LWFiYzctNGI3Y2NjZTgyZTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA0MTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOThlYTc0MWQ4MTA3NDkxMGZiYTQ3ZDUyYjI1ZDY4M2FlYTExNmQ5ZTg0ZWI0MmZlMmNhOWRiNzE1MWJiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FK6nz4yhER9D8mZ5Uk0LWPxFrJFLzvlAc5KV8utbPxA)

你看看其他链表里面是否还有6053的规则，如果没有，他们之间估计直接走的udp通讯不经过防火墙了？要不dnsmsaq的上游不通的话直连域名应该就没法解析了。

**Comment by wtfr-dot** [comment]
> > 另外防火墙mangle表里127.0.0.1:6053这个规则是smartnds处理dnsmsaq转发过来的dns查询的监听地址，但它重来没有任何流量，想必是它处于lanlist这个规则的后面造成的，这样的话这条规则实际上是没用的，但逻辑上它应该参与进去 ![image](https://private-user-images.githubusercontent.com/81218740/343002307-09af30e0-1125-41e6-abc7-4b7ccce82e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzUzMjQsIm5iZiI6MTcxOTM3NTAyNCwicGF0aCI6Ii84MTIxODc0MC8zNDMwMDIzMDctMDlhZjMwZTAtMTEyNS00MWU2LWFiYzctNGI3Y2NjZTgyZTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA0MTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOThlYTc0MWQ4MTA3NDkxMGZiYTQ3ZDUyYjI1ZDY4M2FlYTExNmQ5ZTg0ZWI0MmZlMmNhOWRiNzE1MWJiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FK6nz4yhER9D8mZ5Uk0LWPxFrJFLzvlAc5KV8utbPxA)
> 
> 你看看其他链表里面是否还有6053的规则，如果没有，他们之间估计直接走的udp通讯不经过防火墙了？要不dnsmsaq的上游不通的话直连域名应该就没法解析了。
其它链表没有这条规则，这条规则只存在于mangle表output链的PSW_OUTPUT链里，我尝试将这条规则提到最前面，分流策略改为IPOnDemand，dns还是没运行，也没有流量，
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/6f011f76-6f26-41ba-a52f-c390158aa5b3)

同时将dnsmasq的日志输出到系统日志查看是正常转发到6053端口并正确得到了IP的

daemon.info dnsmasq[1]: 16 192.168.100.229/63443 query[A] club.api.autohome.com.cn from 192.168.100.229
Wed Jun 26 13:56:31 2024 daemon.info dnsmasq[1]: 16 192.168.100.229/63443 forwarded club.api.autohome.com.cn to 127.0.0.1#6053
Wed Jun 26 13:56:31 2024 daemon.info dnsmasq[1]: 16 192.168.100.229/63443 reply club.api.autohome.com.cn is <CNAME>
Wed Jun 26 13:56:31 2024 daemon.info dnsmasq[1]: 16 192.168.100.229/63443 ipset add passwall_whitelist 58.144.149.35 cn
Wed Jun 26 13:56:31 2024 daemon.info dnsmasq[1]: 16 192.168.100.229/63443 ipset add passwall_whitelist6 58.144.149.35 cn

smartdns的解析记录也对应上了的

[2024-06-26 13:56:30,618] 127.0.0.1 query club.autohome.com.cn, type 1, time 0ms, speed: 43.6ms, group default, result 103.75.155.245
[2024-06-26 13:56:30,772] 127.0.0.1 query x.autoimg.cn, type 1, time 0ms, speed: 38.6ms, group default, result 101.72.199.35
[2024-06-26 13:56:30,780] 127.0.0.1 query msg.autohome.com.cn, type 1, time 0ms, speed: 40.3ms, group default, result 103.75.155.236
[2024-06-26 13:56:30,781] 127.0.0.1 query m1.autoimg.cn, type 1, time 0ms, speed: 3.7ms, group default, result 113.207.45.39, 113.207.45.41, 113.207.45.36, 113.207.45.42, 113.207.45.37, 113.207.45.40
[2024-06-26 13:56:30,789] 127.0.0.1 query sou.autohome.com.cn, type 1, time 0ms, speed: 39.9ms, group default, result 103.75.155.236
[2024-06-26 13:56:30,804] 127.0.0.1 query www.autohome.com.cn, type 1, time 0ms, speed: 4.8ms, group default, result 113.207.105.35
[2024-06-26 13:56:30,805] 127.0.0.1 query img.autohome.com.cn, type 1, time 0ms, speed: 4.5ms, group default, result 113.207.105.35
[2024-06-26 13:56:30,819] 127.0.0.1 query sou.api.autohome.com.cn, type 1, time 1ms, speed: 39.4ms, group default, result 113.207.105.41
[2024-06-26 13:56:30,873] 127.0.0.1 query p-vp.autohome.com.cn, type 1, time 0ms, speed: 11.7ms, group default, result 101.206.162.71, 59.80.47.66
[2024-06-26 13:56:31,006] 127.0.0.1 query vr.api.autohome.com.cn, type 1, time 0ms, speed: 7.0ms, group default, result 58.144.149.35
[2024-06-26 13:56:31,007] 127.0.0.1 query g.autoimg.cn, type 1, time 0ms, speed: 8.5ms, group default, result 113.207.105.35
[2024-06-26 13:56:31,022] 127.0.0.1 query club.api.autohome.com.cn, type 1, time 0ms, speed: 2.7ms, group default, result 58.144.149.35
[2024-06-26 13:56:31,030] 127.0.0.1 query la.autohome.com.cn, type 1, time 0ms, speed: 20.3ms, group default, result 14.205.47.136
[2024-06-26 13:56:31,122] 127.0.0.1 query i3.autoimg.cn, type 1, time 0ms, speed: 10.7ms, group default, result 59.80.47.66, 101.206.162.71

**Comment by wtfr-dot** [comment]
我在dnsmasq的日志里看见这样的记录：
Wed Jun 26 17:59:48 2024 daemon.info dnsmasq[1]: 81431 192.168.100.21/50101 forwarded android.googleapis.com to 127.0.0.1#6553
Wed Jun 26 17:59:48 2024 daemon.info dnsmasq[1]: 81431 192.168.100.21/50101 ipset add passwall_blacklist 142.250.176.10 googleapis.com
Wed Jun 26 17:59:48 2024 daemon.info dnsmasq[1]: 81431 192.168.100.21/50101 reply android.googleapis.com is 142.250.176.10
从这个记录来看passwall分流路由后也是给dnsmasq，让它转发给6553端口，这样看来是跟smartdns分支有点不同，不过这个处理也没错吧，看起来googleapis.com像是动态加入ipset的blacklist，但实际上googleapis.com这个域名本身就在自定义的代理列表里
![image](https://github.com/xiaorouji/openwrt-passwall/assets/81218740/c495daed-f415-4a38-97b2-9ba6b2b3b708)

**Comment by lwb1978** [comment]
之前有人反馈过类似问题，好像是说dnsmasq下ipset内容达到一定数量后就容易出错，类似于溢出，我以前没用smartdns版本前，dns分流采用dnsmasq，过滤代理域名的ipv6一两天肯定就失效，因为我的节点不支持v6，过滤代理ipv6就成了刚需，否则油管会转圈圈很久。换了smartdns后各种问题就没有了。或许你可以试试编译imm或者官方的23.05，采用nftset看这个情况还存在吗？
另外你上面说pw smartdns版本更新慢，你如果需要smartdns版也可以拉取我的仓库，我仓库里的smartdns版我会手搓到最新与主分支同步。

**Comment by wtfr-dot** [comment]
> 之前有人反馈过类似问题，好像是说dnsmasq下ipset内容达到一定数量后就容易出错，类似于溢出，我以前没用smartdns版本前，dns分流采用dnsmasq，过滤代理域名的ipv6一两天肯定就失效，因为我的节点不支持v6，过滤代理ipv6就成了刚需，否则油管会转圈圈很久。换了smartdns后各种问题就没有了。或许你可以试试编译imm或者官方的23.05，采用nftset看这个情况还存在吗？ 另外你上面说pw smartdns版本更新慢，你如果需要smartdns版也可以拉取我的仓库，我仓库里的smartdns版我会手搓到最新与主分支同步。

也许是吧，我下的规则文件也比较全，我的固件就是基于官方23.05自己编译iptables版本的，因为使用了mwan3，所以没用nftables，由于这个问题很少几率出现，先再继续观察一下，后续出问题再说，多谢！🙏

**Comment by lwb1978** [comment]
另外mwan3也会对pw有影响，会无脑劫持所有流量到它那边先，之前回复过几个网友的问题，出了各种奇怪的问题后都是卸载了mwan3后就正常了。

**Comment by wtfr-dot** [comment]
> 另外mwan3也会对pw有影响，会无脑劫持所有流量到它那边先，之前回复过几个网友的问题，出了各种奇怪的问题后都是卸载了mwan3后就正常了。

我一直在用mwan3，这个问题很难说不是它引起的，目前我发现的问题是如果在luci界面上操作了mwan3或者ssh对它reload等非它自己静默操作的话由于它会清除ipset等操作造成mangle表output链mwan3和passwall的规则链顺序错乱而使得passwall无法代理远程连接，只有清空passwall的ipset重新加载防火墙规则来解决，平常不手动mwan3，让它自己的链接追踪控制不会出问题，但也说不好是它偶尔抽风引起的，总之防火墙、mwan3和passwall这三者存在相互关系，如果没搞清楚容易出问题，最后passwall的ipset清空大法是解决问题的关键

**Comment by wtfr-dot** [comment]
> > 另外mwan3也会对pw有影响，会无脑劫持所有流量到它那边先，之前回复过几个网友的问题，出了各种奇怪的问题后都是卸载了mwan3后就正常了。
> 
> 我一直在用mwan3，这个问题很难说不是它引起的，目前我发现的问题是如果在luci界面上操作了mwan3或者ssh对它reload等非它自己静默操作的话由于它会清除ipset等操作造成mangle表output链mwan3和passwall的规则链顺序错乱而使得passwall无法代理远程连接，只有清空passwall的ipset重新加载防火墙规则来解决，平常不手动mwan3，让它自己的链接追踪控制不会出问题，但也说不好是它偶尔抽风引起的，总之防火墙、mwan3和passwall这三者存在相互关系，如果没搞清楚容易出问题，最后passwall的ipset清空大法是解决问题的关键
不过如果真的是mwan3引起的话，它可能不会只有极少数域名出现本地远程同时解析这种问题，这更像是dnsmasq的ipset操作出错造成的，你说的有些网友反应的无脑劫持所有流量应该就是mwan3因为某些原因动了防火墙，而它的hook变成了处于passwall规则链的前面造成的，这在passwall的iptables脚本里专门有处理，只是没有动态监控而采取动作，只能人工操作，不过一般不动路由器设置也基本上不会有问题，再加上passwall偶尔也需要手动清空一下ipset来解决某些问题

**Comment by lwb1978** [comment]
或许pw能支持tun的话可能就没有这些问题了。

**Comment by wtfr-dot** [comment]
mwan3的作者一直不出mwan4我们也很无奈呀，不过搞清楚问题后使用起来也没有太大的问题

**Comment by lwb1978** [comment]
pw有看门狗程序，如果有好点的办法监控到mwan3对防火墙进行了操作，就执行ipset清空操作也是一个下策。

**Comment by wtfr-dot** [comment]
mwan3后面版本有链接追踪功能监控网络变化，这可能使得它不需要清空ipset来刷新，我目前使用体会是只要不手动操作它，还有不手动重启防火墙等基本上没啥问题，如果动了它们，可以按顺序防火墙、mwan3、passwall重启操作就恢复正常了
