### ISSUE TITLE
[Bug]: 以Shadowsocks节点为主的订阅中，四个Hysteria2节点显示为“去除4条不合适线路”

### ISSUE THREAD

**Issue by Tsubamei** [xiaorouji/openwrt-package#3294]
### 描述您遇到的bug

机场的节点大部分是Shadowsocks的，但其中有四个是Hysteria2的，这四个节点在“节点列表”中显示为“去除4条不合适线路”，并且无法使用

### 复现此Bug的步骤

尝试在“节点订阅中”更改“Hysteria2节点使用类型”为sing-box或Hysteria2，但均出现此问题

### 您想要实现的目的

可以正常显示Hysteria2节点

### 日志信息

-

### 系统相关信息

- Passwall版本：4.77-6
-

**Comment by lwb1978** [comment]
但凡你翻一下前些天的issues就不会发个bug的帖子。

**Comment by gito10** [comment]
#3271
