### ISSUE TITLE
[Bug]: 苹果上whatsapp问题

### ISSUE THREAD

**Issue by SZ-MB** [xiaorouji/openwrt-package#3301]
### 描述您遇到的bug

之前有个版本whatsapp能用上，但最新更新这个版本whatsapp又连不上了。好像只有苹果是这样，安卓上whatsapp是正常的，

### 复现此Bug的步骤

使用上出现

### 您想要实现的目的

希望苹果whatsapp能像安卓whatsapp一样能连上，之前某个版本是可以的。

### 日志信息

没有

### 系统相关信息

git-25.180.44951-b47dc41

**Comment by gito10** [comment]
这不是什么bug，就一个规则的问题。iOS的WhatsApp 用不了，那就是它的某个服务器域名或IP没添加到代理列表，比如你用的gfw列表不全，可以换个GFW列表源更新下，或者使用多个源，passwall会自动整合。
如果还是不行，查一下iOS版WhatsApp独有的域名或IP，然后手动添加到代理列表。
