### ISSUE TITLE
[Feature Request]: 建议为 ChinaDNS-NG 增加直连 DNS 选项

### ISSUE THREAD

**Issue by Hyyyy11** [xiaorouji/openwrt-package#3302]
### 描述你想要的新功能

ChinaDNS-NG 重写后的版本已支持 DoT 上游，建议增加直连 DNS 选项，默认“跟随系统”，额外增加阿里云、腾讯云 DoT 服务器以及自定义选项，这样就可以少套娃一层 AdGuard Home，避免运营商劫持 DNS。
印象中之前尝试 Passwall2 有看到直连 DNS 的选项，不知道为什么 Passwall 没有。

### 描述你想要的解决方案

同上

**Comment by lwb1978** [comment]
加这个功能不难，最大的问题是不是所有版本的chinadns-ng都支持dot，必须是wolfssl版，但现在其他翻墙插件和imm或lede的openwrt仓库所带的chinadns都不是wolfssl版，假如pw做了chinadns的dot支持后，因为用户自身问题路由里的chinadns不是wolfssl版而用不了或者报错，到时就各种来这里吐槽或者报bug了。

**Comment by lwb1978** [comment]
之前就因为chinadns更新后不再兼容旧版本的一些参数，pw这边先适配了新版本，但很多用户路由里因为不止pw一个科学插件chinadns还是老版本，在使用pw时出现dns故障就各种过来报bug，现在的处理办法也只能是检测chinadns版本，版本低了就在日志里面提醒用户更新而已。

**Comment by Pacio** [comment]
> 之前就因为chinadns更新后不再兼容旧版本的一些参数，pw这边先适配了新版本，但很多用户路由里因为不止pw一个科学插件chinadns还是老版本，在使用pw时出现dns故障就各种过来报bug，现在的处理办法也只能是检测chinadns版本，版本低了就在日志里面提醒用户更新而已。

大神能不能单独开个分支给我们这些使用最新版chinadns的人用啊~

**Comment by lwb1978** [comment]
功能已经添加，该帖子关闭。
