### ISSUE TITLE
[Bug]: 使用Hysteria2时出现链接问题

### ISSUE THREAD

**Issue by HoshinoDesu** [xiaorouji/openwrt-package#3311]
### 描述您遇到的bug

当我启用"Hysteria2"节点后，在Passwall中可以正常检测延迟，但是在我的浏览器中无法正常浏览Google Youtube等网站（如图）
会偶发性的正常连接一两次，但是速度不正常（指达不到电脑中直接使用支持Hysteria2的客户端的速度），且重启Passwall后再次出现访问Google"隐私设置错误"
![QQ_1720886330427](https://github.com/user-attachments/assets/95e78546-55ec-4ee6-b0dd-8b5bbd0634a5)
![QQ_1720886348288](https://github.com/user-attachments/assets/6bc21d97-396f-4c74-aad6-c3738dcc42e9)

### 复现此Bug的步骤

添加连接Hysteria2节点

### 您想要实现的目的

正常链接Hysteria2节点

### 日志信息

Passwall日志
```
2024-07-14 00:07:12: 删除iptables防火墙规则完成。
2024-07-14 00:07:13: 清空并关闭相关程序和缓存完成。
2024-07-14 00:07:13: TCP节点：[152.*.*.*:443]，监听端口：1041
2024-07-14 00:07:13: UDP节点没有选择或为空，不代理UDP。
2024-07-14 00:07:13: DNS域名解析：
2024-07-14 00:07:13:   - dns2tcp(127.0.0.1#15353) -> tcp://127.0.0.1:6553
2024-07-14 00:07:13:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-07-14 00:07:13:   - 节点列表中的域名(vpslist)：119.29.29.29,223.5.5.5
2024-07-14 00:07:13:   - 域名白名单(whitelist)：119.29.29.29,223.5.5.5
2024-07-14 00:07:13:   - 代理域名表(blacklist)：127.0.0.1#15353
2024-07-14 00:07:14:   - 防火墙域名表(gfwlist)：127.0.0.1#15353
2024-07-14 00:07:17:   - 中国域名表(chnroute)：默认
2024-07-14 00:07:18:   - 默认：119.29.29.29,223.5.5.5
2024-07-14 00:07:18:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-07-14 00:07:18: 开始加载防火墙规则...
2024-07-14 00:07:18:   - [0]追加ISP IPv6 DNS到白名单：fe80::8e53:c3ff:feda:8bb0
2024-07-14 00:07:18:   - [0]加入负载均衡的节点到ipset[passwall_vpslist]
2024-07-14 00:07:18:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-07-14 00:07:19:   - [0]追加直连DNS到iptables：119.29.29.29:53
2024-07-14 00:07:19:   - [0]追加直连DNS到iptables：223.5.5.5:53
2024-07-14 00:07:19:   - 上游 DNS 服务器 127.0.0.1 已在直接访问的列表中，不强制向 TCP 代理转发对该服务器 TCP/6553 端口的访问
2024-07-14 00:07:19:   - 访问控制：
2024-07-14 00:07:19:      - 【默认】，使用 TCP 节点[152.70.118.132:443](REDIRECT:1041)
2024-07-14 00:07:19: 防火墙规则加载完成！
2024-07-14 00:07:20: 重启 dnsmasq 服务
2024-07-14 00:07:20: 运行完成！
```

### 系统相关信息

Passwall版本:4.77-6
浏览器版本:Chrome 123.0.6312.105
Hysteria 版本:2.5.0

**Comment by lwb1978** [comment]
hy的程序改用sing-box试试

**Comment by HoshinoDesu** [comment]
> hy的程序改用sing-box试试

已经尝试过，问题依旧，我也更换过路由器设备，也是相同的问题

**Comment by lwb1978** [comment]
没用过hy节点，也没有hy节点测试所以不好评价，你可以试试手动在pw里调节一下该节点里的一些参数试试。

**Comment by HoshinoDesu** [comment]
> 没用过hy节点，也没有hy节点测试所以不好评价，你可以试试手动在pw里调节一下该节点里的一些参数试试。

节点参数调整过，Copy了朋友的hy2节点也是这个问题，在本机的V2N软件中导入使用完全正常，丢进passwall后就爆了...
我的发现是类似于Google，YouTube，Twitch等网站会出现随机的证书乱飘情况导致无法开启，而mail.google.com，translate.google.com这种的可以正常开启，而局域网内的其他设备（例如手机等）则可以正常开启Google，YouTube等，不清楚是什么地方出了错

**Comment by HoshinoDesu** [comment]
> 没用过hy节点，也没有hy节点测试所以不好评价，你可以试试手动在pw里调节一下该节点里的一些参数试试。

我尝试在Chrome浏览器中指定了1.1.1.1 Cloudflare DNS，问题解决了，但是这么做感觉治标不治本，我在Openwrt中启用了SmartDNS，Passwall插件中指定了使用了SmartDNS分流国外的DOH DNS，在使用Hysteria2之前一切正常，不清楚为什么这次出错了，在网上搜索到了其他类似的症状，都是被污染成了Facebook的SSL证书，太奇怪了....

**Comment by swiftwindpro** [comment]
> > 没用过hy节点，也没有hy节点测试所以不好评价，你可以试试手动在pw里调节一下该节点里的一些参数试试。
> 
> 我尝试在Chrome浏览器中指定了1.1.1.1 Cloudflare DNS，问题解决了，但是这么做感觉治标不治本，我在Openwrt中启用了SmartDNS，Passwall插件中指定了使用了SmartDNS分流国外的DOH DNS，在使用Hysteria2之前一切正常，不清楚为什么这次出错了，在网上搜索到了其他类似的症状，都是被污染成了Facebook的SSL证书，太奇怪了....

怪不得，我也出现这个问题，暂时无解

**Comment by hefei5495** [comment]
我也是同样的问题诶，google的证书也变成了facebook的证书了，提示不安全的连接，目前把DNS-->DNS重定向选项选上就好了

**Comment by KennanChan** [comment]
> 我也是同样的问题诶，google的证书也变成了facebook的证书了，提示不安全的连接，目前把DNS-->DNS重定向选项选上就好了

我这儿勾上也不行呢，有谁知道为啥吗，google的证书时不时就抽风飘移到facebook了

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by digitalhivehub** [comment]
自建 Hysteria 2 遇到了这个问题，Google，v2ex 之类的网站会出现证书异常（被替换成了Facebook证书，原因未知）
最后在 Hysteria 2 配置中添加了协议嗅探 (Sniff)，这个问题就再也没出现过了
```yaml
sniff:
  enable: true 
  timeout: 2s 
  rewriteDomain: false 
  tcpPorts: 80,443,8000-9000 
  udpPorts: all
```

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by kiwi5656** [comment]
same issue.

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by FkBigBrother** [comment]
> x

牛逼，治好了我的症状

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by ax003** [comment]
> 我尝试在Chrome浏览器中指定了1.1.1.1 Cloudflare DNS，问题解决了，但是这么做感觉治标不治本，我在Openwrt中启用了SmartDNS，Passwall插件中指定了使用了SmartDNS分流国外的DOH DNS，在使用Hysteria2之前一切正常，不清楚为什么这次出错了，在网上搜索到了其他类似的症状，都是被污染成了Facebook的SSL证书，太奇怪了....

你后来怎么解决的？我现在openwrt（主路由）+passwall+hysteria2就出现同样问题，之前openwrt（旁路由）就没有问题

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by xkdvSrPD** [comment]
same issue.

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by liu296** [comment]
> 自建 Hysteria 2 遇到了这个问题，Google，v2ex 之类的网站会出现证书异常（被替换成了Facebook证书，原因未知） 最后在 Hysteria 2 配置中添加了协议嗅探 (Sniff)，这个问题就再也没出现过了
> 
> sniff:
>   enable: true 
>   timeout: 2s 
>   rewriteDomain: false 
>   tcpPorts: 80,443,8000-9000 
>   udpPorts: all


passwall里面Hysteria 2 配置在哪改啊

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Rock-w** [comment]
same issue

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by anddyshen** [comment]
遇到同样问题，请问在哪里修改，passwall和passwall2都是同样的问题。

**Comment by hefei5495** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by ax003** [comment]
> 遇到同样问题，请问在哪里修改，passwall和passwall2都是同样的问题。

后来我是定位在dns问题上，搭一个smartdns，用它来做境外域名解析解决的

**Comment by HoshinoDesu** [comment]
服务端开启嗅探就能解决



---原始邮件---
发件人: "Jason ***@***.***&gt;
发送时间: 2025年11月1日(周六) 上午9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 使用Hysteria2时出现链接问题 (Issue #3311)


ax003 left a comment (xiaorouji/openwrt-passwall#3311)
  
遇到同样问题，请问在哪里修改，passwall和passwall2都是同样的问题。
  
后来我是定位在dns问题上，搭一个smartdns，用它来做境外域名解析解决的

**Comment by ax003** [comment]
> 服务端开启嗅探就能解决
> […](#)
> 
> ---原始邮件---
> 发件人: "Jason ***@***.***&gt;
> 发送时间: 2025年11月1日(周六) 上午9:26
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 使用Hysteria2时出现链接问题 (Issue [#3311](https://github.com/xiaorouji/openwrt-passwall/issues/3311))
> 
> 
> ax003 left a comment ([xiaorouji/openwrt-passwall#3311](https://github.com/xiaorouji/openwrt-passwall/issues/3311))
> 
> 遇到同样问题，请问在哪里修改，passwall和passwall2都是同样的问题。
> 
> 后来我是定位在dns问题上，搭一个smartdns，用它来做境外域名解析解决的
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可能具体情况不同，检查了一下服务器端，sniff是打开的

**Comment by KennanChan** [comment]
最近还遇到个诡异现象，google.com被重定向到google.cn/m，有遇到过的吗？

**Comment by HoshinoDesu** [comment]
你的IP被送中了，换台机



---原始邮件---
发件人: "Kennan ***@***.***&gt;
发送时间: 2025年11月1日(周六) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 使用Hysteria2时出现链接问题 (Issue #3311)


KennanChan left a comment (xiaorouji/openwrt-passwall#3311)
 
最近还遇到个诡异现象，google.com被重定向到google.cn/m，有遇到过的吗？

**Comment by KennanChan** [comment]
> 你的IP被送中了，换台机
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 
> 发件人: "Kennan ***@***.***&gt;
> 
> 发送时间: 2025年11月1日(周六) 下午4:33
> 
> 收件人: ***@***.***&gt;;
> 
> 抄送: ***@***.******@***.***&gt;;
> 
> 主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 使用Hysteria2时出现链接问题 (Issue #3311)
> 
> 
> 
> 
> 
> KennanChan left a comment (xiaorouji/openwrt-passwall#3311)
> 
>  
> 
> 最近还遇到个诡异现象，google.com被重定向到google.cn/m，有遇到过的吗？
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

纳尼？哪个IP呀？客户端还是机场的服务器？
