### ISSUE TITLE
建议添加接口控制，覆盖wireguard接口

### ISSUE THREAD

**Issue by ruimingblackjack160** [xiaorouji/openwrt-package#3312]
### 描述你想要的新功能

环境是openwrt 安装passwall2，手机通过wireguard创建wireguard接口接入openwrt， 手机端链接wireguard后国内访问正常，不能通过passwall2。以前使用ssrplus控制里可以直接添加接口，手机就能访问外网了。

### 描述你想要的解决方案

在访问控制选项里添加接口控制，可以控制那些接口可以访问passwall。

**Comment by zhoufla** [comment]
wireguard + passwall2使用问题，检查下自己客户端所有流量是否都走wireguard。

**Comment by ruimingblackjack160** [comment]
使用ssr+wireguard是好的，改用passwall不能访问国外。hysteria速度非常快，计划改到passwall。passwall分流的方式也搞不清楚，好像全部走的是代理。
