### ISSUE TITLE
[Bug]: 安卓旁路由DNS解析失败

### ISSUE THREAD

**Issue by uselibrary** [xiaorouji/openwrt-package#3315]
### 描述您遇到的bug

【场景】Passwall版本4.77-6；安卓（小米 Hyper OS）；旁路由；IPv4/IPv6双栈
【Bug】仅填写一个DNS（即旁路由IP地址），则浏览器（via，firefox）无法正常连接，但是chrome，telegram等能正常浏览。
【临时解决方法】在备用DNS中填写1.1.1.1或者9.9.9.9等，浏览器即可正常浏览，但明显感觉国内网站有延迟。
【备注】iOS和Windows都正常，无需填写额外的1.1.1.1

![photo_2024-07-16_21-46-56](https://github.com/user-attachments/assets/35e99a2a-d891-4800-ace4-5531720c3cd3)

![photo_2024-07-16_21-46-55](https://github.com/user-attachments/assets/decfba81-29e5-452a-b31f-ce9b8199437a)

### 复现此Bug的步骤

1. WiFi接入，仅填写一个DNS，即旁路由IP地址
2. 浏览器（如via,firefox等）无法正常访问谷歌，但chrome可以；同时，telegram和Google play等则正常。
3. 若添加附加DNS为1.1.1.1，则所有浏览器都正常，但此时国内网站的访问明显有延迟，不确定是DNS解析消耗时间导致的还是出现了意外的全局代理。

### 您想要实现的目的

希望知道出现此现象的原因，如能解决则更好。

### 日志信息

2024-07-16 22:31:37: 删除nftables防火墙规则完成。
2024-07-16 22:31:38: 清空并关闭相关程序和缓存完成。
2024-07-16 22:31:38: TCP节点：[xray]，监听端口：1041
2024-07-16 22:31:38: DNS域名解析：
2024-07-16 22:31:38:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-07-16 22:31:38:   - ChinaDNS-NG(127.0.0.1#15353)：直连DNS：192.168.1.1，可信DNS：tcp://1.1.1.1#53
2024-07-16 22:31:38:   - 节点列表中的域名(vpslist)：192.168.1.1
2024-07-16 22:31:38:   - 域名白名单(whitelist)：默认
2024-07-16 22:31:38:   - 代理域名表(blacklist)：默认
2024-07-16 22:31:38:   - 防火墙域名表(gfwlist)：默认
2024-07-16 22:31:38:   - 中国域名表(chnroute)：默认
2024-07-16 22:31:38:   - 默认：127.0.0.1#15353
2024-07-16 22:31:38:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-07-16 22:31:38: 开始加载防火墙规则...
2024-07-16 22:31:40:   - [0]追加ISP IPv4 DNS到白名单：192.168.1.1
2024-07-16 22:31:40:   - [0]加入负载均衡的节点到nftset[passwall_vpslist]直连完成
2024-07-16 22:31:40:   - [1]加入所有节点到nftset[passwall_vpslist]直连完成
2024-07-16 22:31:40:   - [0]追加直连DNS到nftables：192.168.1.1:53
2024-07-16 22:31:41:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-07-16 22:31:41:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2024-07-16 22:31:41:   - 访问控制：
2024-07-16 22:31:41:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-07-16 22:31:41:      - 【默认】，使用 TCP 节点[xray](REDIRECT:1041)
2024-07-16 22:31:41:      - 【默认】，使用 UDP 节点[xray](TPROXY:1041)
2024-07-16 22:31:41: 防火墙规则加载完成！
2024-07-16 22:31:43: 重启 dnsmasq 服务
2024-07-16 22:31:43: 配置定时任务：自动更新规则。
2024-07-16 22:31:43: 运行完成！

### 系统相关信息

Passwall 4.77-6
小米 hyper OS
树莓派4B OpenWRT 23.05

**Comment by CharlesLocke** [comment]
打开 DNS重定向没 ？

**Comment by uselibrary** [comment]
> 打开 DNS重定向没 ？

尝试过，没有效果（严格来说，在短暂起效几十秒之后就失效，依旧是DNS问题）。
一个可能稳定的方法：在手机的私有DNS中填写dns.google使用dot，可以实现较良好的状态。

**Comment by lwb1978** [comment]
> > 打开 DNS重定向没 ？
> 
> 尝试过，没有效果（严格来说，在短暂起效几十秒之后就失效，依旧是DNS问题）。 一个可能稳定的方法：在手机的私有DNS中填写dns.google使用dot，可以实现较良好的状态。

确定是pw最新代码里面的重定向，不是网络dhcp里的重定向，pw的重定向功能加入后不包含在releases的4.77-6的发布中。

**Comment by uselibrary** [comment]
> > > 打开 DNS重定向没 ？
> > 
> > 
> > 尝试过，没有效果（严格来说，在短暂起效几十秒之后就失效，依旧是DNS问题）。 一个可能稳定的方法：在手机的私有DNS中填写dns.google使用dot，可以实现较良好的状态。
> 
> 确定是pw最新代码里面的重定向，不是网络dhcp里的重定向，pw的重定向功能加入后不包含在releases的4.77-6的发布中。

我之前测试DNS重定向，是在DHCP/DNS中自建规则实现的，测试无效。目前使用的是5月31日发布的4.77-6版本，查找到6月8日在[#3254](https://github.com/xiaorouji/openwrt-passwall/pull/3254)中新添加了Passwall的DNS重定向功能。目前只能继续等待发布新的版本？

**Comment by lwb1978** [comment]
下载添加此功能所涉及的文件替换路由上面的相关文件或者自行用最新代码编译新版本。

**Comment by lwb1978** [comment]
> > > > 打开 DNS重定向没 ？
> > > 
> > > 
> > > 尝试过，没有效果（严格来说，在短暂起效几十秒之后就失效，依旧是DNS问题）。 一个可能稳定的方法：在手机的私有DNS中填写dns.google使用dot，可以实现较良好的状态。
> > 
> > 
> > 确定是pw最新代码里面的重定向，不是网络dhcp里的重定向，pw的重定向功能加入后不包含在releases的4.77-6的发布中。
> 
> 我之前测试DNS重定向，是在DHCP/DNS中自建规则实现的，测试无效。目前使用的是5月31日发布的4.77-6版本，查找到6月8日在[#3254](https://github.com/xiaorouji/openwrt-passwall/pull/3254)中新添加了Passwall的DNS重定向功能。目前只能继续等待发布新的版本？

4.78.1已发布，下载试试

**Comment by uselibrary** [comment]
> > > > > 打开 DNS重定向没 ？
> > > > 
> > > > 
> > > > 尝试过，没有效果（严格来说，在短暂起效几十秒之后就失效，依旧是DNS问题）。 一个可能稳定的方法：在手机的私有DNS中填写dns.google使用dot，可以实现较良好的状态。
> > > 
> > > 
> > > 确定是pw最新代码里面的重定向，不是网络dhcp里的重定向，pw的重定向功能加入后不包含在releases的4.77-6的发布中。
> > 
> > 
> > 我之前测试DNS重定向，是在DHCP/DNS中自建规则实现的，测试无效。目前使用的是5月31日发布的4.77-6版本，查找到6月8日在[#3254](https://github.com/xiaorouji/openwrt-passwall/pull/3254)中新添加了Passwall的DNS重定向功能。目前只能继续等待发布新的版本？
> 
> 4.78.1已发布，下载试试

感谢发布 4.78.1 新版本，基本确认问题出现在安卓侧，而非passwall侧。
- 在Windows平台测试，DNS重定向功能正常，手动修改DNS为任意IP（如114.115.116.117）都能返回正确的解析；
- 在安卓（小米 HyperOS）上依旧失效，需配合dot（如dns.google）才能正常工作。

**解决方法**
1. passwall开启DNS重定向；2. . 手机开启dot；3旁路由禁用IPv6（可选）。可实现和Windows相同效果。

以下是额外的禁止旁路由的IPv6设置，否则偶发DNS失效（以下更改不影响实际的IPv6使用）：
1. `网络 » 接口 » lan » DHCP服务器 » IPv6设置`，禁用RA 服务、DHCPv6 服务、NDP 代理
2. `网络 » 接口 » lan » 高级设置`，取消委托 IPv6 前缀，并禁用IPv6 分配长度

**Comment by CharlesLocke** [comment]
小米的设备你可以参考这个帖子https://v2ex.com/t/838579
还是建议你禁用IPv6并打开DNS重定向。

**Comment by nbeeeeeeeeee** [comment]
国内安卓一般内置114.114.114.114 ，导致失效，在防火墙ban掉114.114.114.114 即可 ，除题主爆出浏览器异常外，play商店也会异常，导致不能下载，禁用下面两个dns即可 ipv6的dns见图
![image](https://github.com/user-attachments/assets/0fe7a4f0-6275-40ab-a444-d074b91a1c1b)

**Comment by uselibrary** [comment]
> 小米的设备你可以参考这个帖子https://v2ex.com/t/838579 还是建议你禁用IPv6并打开DNS重定向。

系统除了IsInCnRegion外，可能还存在"内网DNS检测"，当出现"不常见/稳定"的DNS，强制使用硬编码的内建DNS。目前只能通过强制指定DNS来解决问题。

**Comment by uselibrary** [comment]
> 国内安卓一般内置114.114.114.114 ，导致失效，在防火墙ban掉114.114.114.114 即可 ，除题主爆出浏览器异常外，play商店也会异常，导致不能下载，禁用下面两个dns即可 ipv6的dns见图 ![image](https://private-user-images.githubusercontent.com/81787436/349842982-0fe7a4f0-6275-40ab-a444-d074b91a1c1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDEzNDQsIm5iZiI6MTcyMTMwMTA0NCwicGF0aCI6Ii84MTc4NzQzNi8zNDk4NDI5ODItMGZlN2E0ZjAtNjI3NS00MGFiLWE0NDQtZDA3NGI5MWExYzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwODE3NjUwMmJiYmNhMTk5NDRiNzEwOTczMTBkN2ZiOTNiMDc0YTdhZmI1NjM3NWU5ODM5MDc0OTE1ZDJhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0BTKBAEVd0o2xhMat9Shlw5-mQCelTLXXUHIg5_1WV8)

感谢新方法

**Comment by CloudOKC** [comment]
相同問題，apple設備添加訪問控制(全選項default)正常，android設備不行, 4.77-6和4.78-1相同，測試舊版4.75-10，4.76-5正常，immortal 23.05.3

**Comment by bertsir** [comment]
也可能是主路由器IPV6 DNS通告导致的，折腾了一周定位解决了，我的主路由是小米的，不支持WEB后台关通告，开启SSH后
cp -p /etc/config/dhcp /etc/dhcp.before-ipv6-dns.bak
uci set dhcp.lan.ra_dns='0'
uci set dhcp.lan.dns_service='0'
uci commit dhcp
/etc/init.d/odhcpd reload
关闭手机WIFI，重连之后就不需要私人DNS了，完美能走旁路由，给后来的人填个坑吧
