### ISSUE TITLE
[Bug]: brook missing

### ISSUE THREAD

**Issue by hawie** [xiaorouji/openwrt-package#3318]
### 描述您遇到的bug

界面当中没有出现brook的选项了。最后一个支持brook的版本是哪个？

### 复现此Bug的步骤

无brook节点选项。

### 您想要实现的目的

希望保留brook的支持。某特殊时期，只有brook链路幸免。

### 日志信息

无brook节点选项。

### 系统相关信息

无brook节点选项。

**Comment by lwb1978** [comment]
因brook太过小众，作者没有精力维护这么多组件，在今年1月29日移除支持，这跟bug没有本质关联。

**Comment by bcseputetto** [comment]
特殊时期，节点是否能幸免于难，跟协议是否是brook无关，不是brook一样可以幸免于难。
brook从 [luci: drop Brook](https://github.com/xiaorouji/openwrt-passwall/commit/1c3a7160219870e72e9e18446fdecd590b15b47d) 4.74-1起就不再可用。
并且由于Chinadns-ng之类的组件，你也没办法继续使用老旧版本的passwall，会出现兼容问题，使用旧的passwall，意味着你某些组件也需要使用旧版本。

**Comment by hawie** [comment]
> 特殊时期，节点是否能幸免于难，跟协议是否是brook无关，不是brook一样可以幸免于难。 brook从 [luci: drop Brook](https://github.com/xiaorouji/openwrt-passwall/commit/1c3a7160219870e72e9e18446fdecd590b15b47d) 4.74-1起就不再可用。 并且由于Chinadns-ng之类的组件，你也没办法继续使用老旧版本的passwall，会出现兼容问题，使用旧的passwall，意味着你某些组件也需要使用旧版本。

谢谢！已下载4.73-3支持的最后一个版本，先用起来了。
弱弱的请教一下，假设服务端是自主VPS，目前安装哪个协议最坚固？有一段时间没有关注这个了。

**Comment by hawie** [comment]
> 因brook太过小众，作者没有精力维护这么多组件，在今年1月29日移除支持，这跟bug没有本质关联。

理解。明白了。谢谢。

**Comment by lwb1978** [comment]
> > 特殊时期，节点是否能幸免于难，跟协议是否是brook无关，不是brook一样可以幸免于难。 brook从 [luci: drop Brook](https://github.com/xiaorouji/openwrt-passwall/commit/1c3a7160219870e72e9e18446fdecd590b15b47d) 4.74-1起就不再可用。 并且由于Chinadns-ng之类的组件，你也没办法继续使用老旧版本的passwall，会出现兼容问题，使用旧的passwall，意味着你某些组件也需要使用旧版本。
> 
> 谢谢！已下载4.73-3支持的最后一个版本，先用起来了。 弱弱的请教一下，假设服务端是自主VPS，目前安装哪个协议最坚固？有一段时间没有关注这个了。

可以不夸张的说，没有一个协议保证是坚固的，自建vps很容易被墙，没被墙的都是看运气，要坚固还得花钱购买流量转发服务器。
