### ISSUE TITLE
[Feature Request]: 分流规则 的 从文件中加载域名 功能移除了吗？

### ISSUE THREAD

**Issue by puteulanus** [xiaorouji/openwrt-package#3320]
### 描述你想要的新功能

旧版本（4.76-2）有这个，感觉作为一个外部修改规则的方式还挺好用的，我拿来自动生成 PT 站直连 tracker 域名：https://github.com/puteulanus/passwall-geosite-pt ，在规则里只需要写一个 ext:pt.dat:tracker 就好了

新版（4.77-6）我看从 文件中加载域名 的描述没有了，规则里写 ext 的话 passwall 似乎工作不正常，这个功能是被移除了吗？

因为 PT 站有些 tracker 域名时不时会变，手动改还挺麻烦的，用程序直接去改 passwall 配置文件的话又怕有点啥格式问题直接给改坏了

### 描述你想要的解决方案

请问这个功能还有加回来的可能吗，或者有没有替代的方案？

**Comment by gito10** [comment]
刚翻看了历史提交，功能并未移除，只是说明里去掉了，应该是 c7e6d6a 这个提交。
你再试试，功能应该跟以前一样。

---
刚刚又在最新代码确认了，相关功能代码都还在，试了没问题的话，我把说明再加回去。

**Comment by puteulanus** [comment]
> 刚翻看了历史提交，功能并未移除，只是说明里去掉了，应该是 [c7e6d6a](https://github.com/xiaorouji/openwrt-passwall/commit/c7e6d6ad3a1823a6c96775568bf0b0e5d118b95e) 这个提交。 你再试试，功能应该跟以前一样。
> 
> 刚刚又在最新代码确认了，相关功能代码都还在，试了没问题的话，我把说明再加回去。

重新试了一下，确实能用

可能那天是因为其他原因工作不正常的，加上看到描述消失/把对应规则删除之后正好恢复正常了，就以为是不支持这个规则语法导致的了
