### ISSUE TITLE
[Bug]: socks日志无限增长导致炸硬盘和系统

### ISSUE THREAD

**Issue by MeowRay** [xiaorouji/openwrt-package#3321]
### 描述您遇到的bug

passwall socks日志无限增长导致磁盘100%，也无法关闭日志功能
此时面板无法重启passwalll服务
rm -rf /tmp/etc/passwall/SOCKS_xxxxxxxxxxxxx.log 无效（应该是被占用了导致没释放）
此时如果reboot，会导致openwrt配置丢失，包括系统用户名密码

### 复现此Bug的步骤

启用socks
![image](https://github.com/user-attachments/assets/b3fc888f-b7d8-4ad1-bc7d-48bb2e5fbfb7)
持续建立连接，直到日志写炸硬盘

### 您想要实现的目的

可关闭socks日志功能或者添加日志上限

### 日志信息

系统已炸故无

### 系统相关信息

passwall 4.77
chrome 126.0.6478.182

### 其他信息

额外补充个可能存在的问题：
长时间多台机器使用同socks可能导致cpu突然飙升100%并保持且openwrt失联，具体原因不明，没有有效日志
![image](https://github.com/user-attachments/assets/e6c1bcc9-662d-4345-a549-9769f86832aa)

**Comment by lwb1978** [comment]
tmp目录是内存空间，怎么会炸硬盘？

**Comment by lwb1978** [comment]
日志本身作为调试使用，日常建议关闭。另外经查看代码和实际测试，socks日志功能可以正常开关。

**Comment by MeowRay** [comment]
> 日志本身作为调试使用，日常建议关闭。另外经查看代码和实际测试，socks日志功能可以正常开关。

我没有手动开启日志，设置是默认的，
似乎旧版本?基本设置下方的socks设置里是没有开关日志选项的，
当日志被刷满tmp后reboot确实可能会导致系统配置丢失


还是建议添加最大日志上限，否则长期还是存在隐患

**Comment by lwb1978** [comment]
每个socks节点里面都分别有日志开关选项，另外所有核心程序均不是pw开发，pw无法在这些核心组件不提供日志上限接口时对其进行设置。
