### ISSUE TITLE
[Bug]: trojan 文件缺失 passwall_packages_ipk_arm_cortex-a9_vfpv3-d16 t

### ISSUE THREAD

**Issue by Armyphil** [xiaorouji/openwrt-package#3323]
### 描述您遇到的bug

最后两个更新中提到包含TROJAN协议，但压缩文件打包后并没有包含TROJAN协议。passwall_packages_ipk_arm_cortex-a9_vfpv3-d16 t

### 复现此Bug的步骤

下载ZIP文件，解压ZIP文件，检查文件。passwall_packages_ipk_arm_cortex-a9_vfpv3-d16 t

### 您想要实现的目的

我需要这个文件

### 日志信息

最后两个更新中提到包含TROJAN协议，但压缩文件打包后并没有包含TROJAN协议。

### 系统相关信息

MacBook intel

**Comment by lwb1978** [comment]
trojan-go已经很久没有更新，pw也早已经将其remove。如需要使用trojan协议请用Sing-Box或Xray代替。

**Comment by Armyphil** [comment]
On my server is the normal trojan protocol installed, if I install trojan plus or xray on my router in open wrt, is this compatible ?
Or do I need to also update my server ?
我的服务器上安装了普通的木马协议，如果我在 open wrt 中的路由器上安装 trojan plus 或 xray，这兼容吗？
或者我还需要更新我的服务器吗？

**Comment by gito10** [comment]
`trojan` protocol in Xray & Sing-Box is the normal trojan protocol.

You can download xray  at  `App Update` page in passwall.
