### ISSUE TITLE
[Bug]: 官方openwrt-19.07编译passwall，naiveproxy出错

### ISSUE THREAD

**Issue by eearphon** [xiaorouji/openwrt-package#3326]
### 描述您遇到的bug

编译 ramips_mt7621_DEVICE_newifi-d1 固件，只选 luci-app-passwall ，编译正常，选上 naiveproxy 就编译失败

### 复现此Bug的步骤

编译

### 您想要实现的目的

正常编译

### 日志信息

ninja: Entering directory `/opt/openwrt/openwrt_openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[287/287] LINK gn_unittests
touch /opt/openwrt/openwrt_openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built
install -d -m0755 /opt/openwrt/openwrt_openwrt/staging_dir/hostpkg/bin/
install -m0755 /opt/openwrt/openwrt_openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out/gn /opt/openwrt/openwrt_openwrt/staging_dir/hostpkg/bin/
mkdir -p /opt/openwrt/openwrt_openwrt/staging_dir/hostpkg/stamp
touch /opt/openwrt/openwrt_openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built
touch /opt/openwrt/openwrt_openwrt/staging_dir/hostpkg/stamp/.gn_installed
make[3]: Leaving directory '/opt/openwrt/openwrt_openwrt/feeds/passwall_packages/gn'
time: package/feeds/passwall_packages/gn/host-compile#961.44#90.20#1048.13
make[3]: Entering directory '/opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy'
mkdir -p /opt/openwrt/openwrt_openwrt/dl
SHELL= flock /opt/openwrt/openwrt_openwrt/tmp/.naiveproxy-122.0.6261.43-1.tar.gz.flock -c '     /opt/openwrt/openwrt_openwrt/scripts/download.pl "/opt/openwrt/openwrt_openwrt/dl" "naiveproxy-122.0.6261.43-1.tar.gz" "c45fbec6390791678490b7f5df7441c120eda4af92c1aaa6c15dbe5b4ca649b6" "" "https://codeload.github.com/klzgrad/naiveproxy/tar.gz/v122.0.6261.43-1?"    '
touch /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.prepared_20ea6aa5002c15e7b4831f43ca195a58_6664517399ebbbc92a37c5bb081b5c53_check
. /opt/openwrt/openwrt_openwrt/include/shell.sh; gzip -dc /opt/openwrt/openwrt_openwrt/dl/naiveproxy-122.0.6261.43-1.tar.gz | tar -C /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1
( pushd /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src ; mkdir -p "chrome/build/pgo_profiles" ; cp -fpR "/opt/openwrt/openwrt_openwrt/dl/chrome-linux-6261-1707846690-1391fcc4772c0b31e214f533af5cafa87e4ccf40.profdata" "chrome/build/pgo_profiles" ; mkdir -p "third_party/llvm-build/Release+Asserts" ; tar -xzf "/opt/openwrt/openwrt_openwrt/dl/clang-llvmorg-18-init-16072-gc4146121e940-5.tgz" -C "third_party/llvm-build/Release+Asserts" ; echo -e "llvmorg-18-init-16072-gc4146121e940-5" > "third_party/llvm-build/Release+Asserts/cr_build_revision" ; popd ; )
/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src /opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy
/opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy
touch /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.prepared_20ea6aa5002c15e7b4831f43ca195a58_6664517399ebbbc92a37c5bb081b5c53
rm -f /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.configured_*
rm -f /opt/openwrt/openwrt_openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.naiveproxy_installed
( pushd "/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src" ; . ../init_env.sh "mipsel" "24kc" "" "/opt/openwrt/openwrt_openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl" ; export naive_flags+=" ${naive_ccache_flags}" ; mkdir -p "out" ; gn gen "out/Release" --args="${naive_flags}" --script-executable="python" ; popd ; )
/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src /opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy
ERROR at //build/toolchain/concurrent_links.gni:108:19: Script returned non-zero exit code.
  _command_dict = exec_script("get_concurrent_links.py", _args, "scope")
                  ^----------
Current dir: /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/out/Release/
Command: python /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/build/toolchain/get_concurrent_links.py --mem_per_link_gb=3
Returned 1.
stderr:

Traceback (most recent call last):
  File "/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/build/toolchain/get_concurrent_links.py", line 17, in <module>
    import gn_helpers
  File "/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/build/toolchain/../gn_helpers.py", line 556
    if not shutil.which(f'autoninja{suffix}'):
                                           ^
SyntaxError: invalid syntax

See //build/gn_logs.gni:5:1: whence it was imported.
import("//build/toolchain/concurrent_links.gni")
^----------------------------------------------
See //BUILD.gn:18:1: whence it was imported.
import("//build/gn_logs.gni")
^---------------------------
/opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy
touch /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.built
touch /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.built_check
MAKEFLAGS="" /opt/openwrt/openwrt_openwrt/staging_dir/hostpkg/bin/ninja  -j1 -C "/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/out/Release" naive
ninja: Entering directory `/opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/src/out/Release'
ninja: error: loading 'build.ninja': No such file or directory
make[3]: *** [Makefile:127: /opt/openwrt/openwrt_openwrt/build_dir/target-mipsel_24kc_musl/naiveproxy-122.0.6261.43-1/.built] Error 1
make[3]: Leaving directory '/opt/openwrt/openwrt_openwrt/feeds/passwall_packages/naiveproxy'
time: package/feeds/passwall_packages/naiveproxy/compile#4.49#4.68#7.84
make[2]: *** [package/Makefile:113: package/feeds/passwall_packages/naiveproxy/compile] Error 2
make[2]: Leaving directory '/opt/openwrt/openwrt_openwrt'
make[1]: *** [package/Makefile:107: /opt/openwrt/openwrt_openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/opt/openwrt/openwrt_openwrt'
make: *** [/opt/openwrt/openwrt_openwrt/include/toplevel.mk:227: world] Error 2

### 系统相关信息

Ubuntu 22.04.4 LTS

**Comment by lwb1978** [comment]
核心组件不是pw制作，naiveproxy编译失败请到出品方反馈:https://github.com/klzgrad/naiveproxy

或者你可以拉取这个仓库的naiveproxy进行编译:https://github.com/sbwml/openwrt_helloworld
