### ISSUE TITLE
[Bug]: 编译报错 不管用哪个openwrt源码都报错 请问是什么原因

### ISSUE THREAD

**Issue by zhongyingbiao** [xiaorouji/openwrt-package#3328]
### 描述您遇到的bug

mkdir -p /home/biaoge/openwrt/staging_dir/hostpkg/stamp
touch /home/biaoge/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/.built
touch /home/biaoge/openwrt/staging_dir/hostpkg/stamp/.rust_installed
make[3]: Leaving directory '/home/biaoge/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#11902.32#995.02#2683.24
make[2]: Leaving directory '/home/biaoge/openwrt'
make[1]: *** [package/Makefile:123: /home/biaoge/openwrt/staging_dir/target-x86_64_musl/stamp/.pac                                                                                               kage_compile] Error 2
make[1]: Leaving directory '/home/biaoge/openwrt'
make: *** [/home/biaoge/openwrt/include/toplevel.mk:232: world] Error 2

### 复现此Bug的步骤

编译失败了

### 您想要实现的目的

寻找解决方案

### 日志信息

mkdir -p /home/biaoge/openwrt/staging_dir/hostpkg/stamp
touch /home/biaoge/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/.built
touch /home/biaoge/openwrt/staging_dir/hostpkg/stamp/.rust_installed
make[3]: Leaving directory '/home/biaoge/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#11902.32#995.02#2683.24
make[2]: Leaving directory '/home/biaoge/openwrt'
make[1]: *** [package/Makefile:123: /home/biaoge/openwrt/staging_dir/target-x86_64_musl/stamp/.pac                                                                                               kage_compile] Error 2
make[1]: Leaving directory '/home/biaoge/openwrt'
make: *** [/home/biaoge/openwrt/include/toplevel.mk:232: world] Error 2

### 系统相关信息

最新版

**Comment by gito10** [comment]
从你这错误看不出来是passwall相关组件编译失败，请先确定是哪个package编译失败。编译错误发生后，应该会给个命令，用单线程，输出详细日志重新编译一遍，查看错误具体原因。
是哪个package错误，再去相应repo提issue。
