### ISSUE TITLE
[Bug]:  Passwall 使用负载均衡功能，ipt2sock 会有内存溢出的情况

### ISSUE THREAD

**Issue by 625045508** [xiaorouji/openwrt-package#3330]
### 描述您遇到的bug

如题，使用passwall 的负载均衡时，大概10分钟左右，ipt2sock 进程就会被 kill掉，观察发现 ipt2sock 进程内存会持续占用走高，观察了一会儿，从十几兆增加到 512MB, 直到被杀死，不太能确认是否和我 softether VPN有冲突。在进程被杀死时， Softethervpn 也会掉线，但是可以直接再连上，上传不了截图头大；只开启负载均衡功能，不使用自己添加的 负载均衡节点，是没问题的，很正常。

### 复现此Bug的步骤

1.配置 负载均衡 开启，并添加需要负载均衡的机场节点。
2.在节点列表添加自定义节点：负载均衡，使用socks协议，指向 127.0.0.1  端口 1181，无用户密码。
3.passwall使用 负载均衡 节点
4. 10分钟左右就会内存使用率拉满。被kill掉，导致外网掉线。

### 您想要实现的目的

希望可以解决这个问题

### 日志信息

内核日志，有截图，没复制
```
[oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=ipt2socks_defau,pid=4811,uid=0

Out of memory: Killed process 4811 (ipt2socks_defau) total-vm:1573792kB, anon-rss:1126076kB, file-rss:4kB, shmem-rss:4kB, UID:0 pgtables:2256kB oom_score_adj:0
device tap_soft left promiscuous mode
```

### 截图

![passwall](https://github.com/user-attachments/assets/9e445d5c-2df5-4371-9c77-6c7a3d2527b6)

### 系统相关信息

passwall版本：4.78-1-smartdns-dev

**Comment by 625045508** [comment]
Passwall 版本 ：4.77-6-smartdns-dev ;  ipt2socks 1.1.4-3 正常，
 Passwall 版本 ：4.78-1-smartdns-dev ;  ipt2socks 1.1.4-3 异常， 
SoftEtherVPN 版本都是 5.02.5185-1 ，尝试更新 OpenWrt 内核，编译，没解决问题。 使用的 [lede]源(https://github.com/coolsnowwolf/lede)

**Comment by bcseputetto** [comment]
试试用 sing-box socks 或者 xray socks 来跑socks，看看内存占用会不会改善。
负载均衡的节点如果能用 sing-box/xray跑，也用sing-box/xray跑
![QQ_1721669812474](https://github.com/user-attachments/assets/2501b391-7545-42ef-9b10-d71573422498)

**Comment by 625045508** [comment]
> 试试用 sing-box socks 或者 xray socks 来跑socks，看看内存占用会不会改善。 负载均衡的节点如果能用 sing-box/xray跑，也用sing-box/xray跑 ![QQ_1721669812474](https://private-user-images.githubusercontent.com/29139573/351059577-2501b391-7545-42ef-9b10-d71573422498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzEwMzYsIm5iZiI6MTcyMTY3MDczNiwicGF0aCI6Ii8yOTEzOTU3My8zNTEwNTk1NzctMjUwMWIzOTEtNzU0NS00MmVmLTliMTAtZDcxNTczNDIyNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE3NTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODE3ZWZhZjczNzQ3YTc3NTI3OGQwNjA1NjVhYWIxZmVmY2I5NTRhZWQ0YjQ2NzI0NGYxYzBhZmE4NzY5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Au5rterESQVETU10a7F-rqysd0R3AdORoNRyTHLtOio)

是的，我暂时就这样解决负载均衡问题的，使用 sing-box 的socks协议，或 xray的 socks协议跑着都还正常。已经这样跑了一天了，不过就是有外网断连的情况，需要刷新一次，才能打开网页，还在排查。头大
![image](https://github.com/user-attachments/assets/000e4ddd-c912-4574-b04d-3f2563d43561)

**Comment by iamyangyiok** [comment]
> > 试试用 sing-box socks 或者 xray socks 来跑socks，看看内存占用会不会改善。 负载均衡的节点如果能用 sing-box/xray跑，也用sing-box/xray跑 ![QQ_1721669812474](https://private-user-images.githubusercontent.com/29139573/351059577-2501b391-7545-42ef-9b10-d71573422498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzEwMzYsIm5iZiI6MTcyMTY3MDczNiwicGF0aCI6Ii8yOTEzOTU3My8zNTEwNTk1NzctMjUwMWIzOTEtNzU0NS00MmVmLTliMTAtZDcxNTczNDIyNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE3NTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODE3ZWZhZjczNzQ3YTc3NTI3OGQwNjA1NjVhYWIxZmVmY2I5NTRhZWQ0YjQ2NzI0NGYxYzBhZmE4NzY5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Au5rterESQVETU10a7F-rqysd0R3AdORoNRyTHLtOio)
> 
> 是的，我暂时就这样解决负载均衡问题的，使用 sing-box 的socks协议，或 xray的 socks协议跑着都还正常。已经这样跑了一天了，不过就是有外网断连的情况，需要刷新一次，才能打开网页，还在排查。头大 ![image](https://private-user-images.githubusercontent.com/56428179/351063726-000e4ddd-c912-4574-b04d-3f2563d43561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjIzNDIsIm5iZiI6MTcyMTc2MjA0MiwicGF0aCI6Ii81NjQyODE3OS8zNTEwNjM3MjYtMDAwZTRkZGQtYzkxMi00NTc0LWIwNGQtM2YyNTYzZDQzNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE5MTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1M2Y1MmM2MmI5NzIyYTMzYjY4MjQwMTM4NzIzNmM4OGQxNjIzYTRlOTlmNDY0ZTEwNTcyOWUxYWFmYjRkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pns98XhVzDI7mOHNDKGVYYNREdchu_ypQf-9x72GAQU)

问个别的 你这个监视器用的什么应用

**Comment by 625045508** [comment]
> > > 试试用 sing-box socks 或者 xray socks 来跑socks，看看内存占用会不会改善。负载均衡的节点如果能用 sing-box/xray跑，也用sing-box/xray跑![QQ_1721669812474](https://private-user-images.githubusercontent.com/29139573/351059577-2501b391-7545-42ef-9b10-d71573422498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzEwMzYsIm5iZiI6MTcyMTY3MDczNiwicGF0aCI6Ii8yOTEzOTU3My8zNTEwNTk1NzctMjUwMWIzOTEtNzU0NS00MmVmLTliMTAtZDcxNTczNDIyNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE3NTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODE3ZWZhZjczNzQ3YTc3NTI3OGQwNjA1NjVhYWIxZmVmY2I5NTRhZWQ0YjQ2NzI0NGYxYzBhZmE4NzY5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Au5rterESQVETU10a7F-rqysd0R3AdORoNRyTHLtOio)
> > 
> > 
> > 是的，我暂时就这样解决负载均衡问题的，使用 sing-box 的袜子协议，或 xray的 socks协议跑着都还正常。已经这样跑了一天了，不过就是有外网断连的情况，需要刷新一次，才能打开网页，还在排查。头大![图像](https://private-user-images.githubusercontent.com/56428179/351063726-000e4ddd-c912-4574-b04d-3f2563d43561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjIzNDIsIm5iZiI6MTcyMTc2MjA0MiwicGF0aCI6Ii81NjQyODE3OS8zNTEwNjM3MjYtMDAwZTRkZGQtYzkxMi00NTc0LWIwNGQtM2YyNTYzZDQzNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE5MTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1M2Y1MmM2MmI5NzIyYTMzYjY4MjQwMTM4NzIzNmM4OGQxNjIzYTRlOTlmNDY0ZTEwNTcyOWUxYWFmYjRkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pns98XhVzDI7mOHNDKGVYYNREdchu_ypQf-9x72GAQU)
> 
> 问个别的 你这个监视器用的什么应用

btop

**Comment by hcym** [comment]
是有漏，头痛

**Comment by winice-test** [comment]
涉及到ipt2sock的一个子问题是log太大导致tmp满了。可以编辑/usr/share/passwall/app.sh，把第410那个_extra_param="${_extra_param} -v"注释调。
