### ISSUE TITLE
[Bug]: 自动掉线，未运行

### ISSUE THREAD

**Issue by gitbruc** [xiaorouji/openwrt-package#3332]
### 描述您遇到的bug

最近用一两天passwall的tcp udp就会自动变成未运行，不知道咋回事，我用的负载均衡端口

### 复现此Bug的步骤

passwall使用 负载均衡 节点

### 您想要实现的目的

希望可以解决这个问题

### 日志信息

无

### 系统相关信息

 4.78-1，实测lede和23.05.4都会出现这个问题

**Comment by lwb1978** [comment]
无日志、无设置界面截图、无工作环境，没人能帮，至少我这里是正常工作的。

**Comment by gitbruc** [comment]
> 无日志、无设置界面截图、无工作环境，没人能帮，至少我这里是正常工作的。

这日志也太长了，这种一两天出一次错的不好找啊，你既然正常那就不是bug了，我自己研究一下吧，谢谢

**Comment by lwb1978** [comment]
系统日志可先不用，至少要发pw的日志上来看看。

**Comment by gitbruc** [comment]
> 系统日志可先不用，至少要发pw的日志上来看看。

![chrome_73R8XTus6J](https://github.com/user-attachments/assets/cf440d9e-798e-400e-94c3-7964c5eb9ba3)
![chrome_DsNX0XrtnE](https://github.com/user-attachments/assets/e2d053b1-07f3-4c15-b6fd-0c3f0368c636)
![chrome_nWSYsdPAR3](https://github.com/user-attachments/assets/24122ffc-001b-425c-924f-1b6ae65c5174)
![chrome_QruovMITPp](https://github.com/user-attachments/assets/08054d50-2185-4c2e-8860-f8c44ae78e53)
![chrome_szayFiJI3d](https://github.com/user-attachments/assets/f1855263-de8c-4fd9-93a3-0c3be1fb6044)
这样行吗？

**Comment by 625045508** [comment]
我和你一样，我也是用负载均衡，前面也是 会自动变成未运行，其实是自动被 kill 掉了，开负载均衡服务没问题，使用负载均衡节点，就会遇到这情况，后面我观察是， ipt2socks 服务内存不断增加，导致内存不足，进程被随机杀死了，扩大了内存也不行，还是会占满，现在只能单节点使用， 不用负载均衡，或者回退到 Passwall 4.77-6-smartdns-dev版本 ; ipt2socks 1.1.4-3版本，就正常了
https://github.com/xiaorouji/openwrt-passwall/issues/3330

**Comment by gitbruc** [comment]
> 我和你一样，我也是用负载均衡，前面也是 会自动变成未运行，其实是自动被 kill 掉了，开负载均衡服务没问题，使用负载均衡节点，就会遇到这情况，后面我观察是， ipt2socks 服务内存不断增加，导致内存不足，进程被随机杀死了，扩大了内存也不行，还是会占满，现在只能单节点使用， 不用负载均衡，或者回退到 Passwall 4.77-6-smartdns-dev版本 ; ipt2socks 1.1.4-3版本，就正常了 #3330

谢谢，持续关注你的issue

**Comment by wtfr-dot** [comment]
你用了smartdns吗？6053端口和5335端口是不是指向的smartdns

**Comment by gitbruc** [comment]
> 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns

是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼

**Comment by SakuraFallingMad** [comment]
> > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> 
> 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼

远程dns部分如果不是设置tcp|udp等方式，xray|sing-box是在配置里直接走代理的，你设了localhost不会出问题？

**Comment by wtfr-dot** [comment]
> > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> 
> 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼

你这个设置可能会存在两个问题：1、采用纯dnsmasq分流方式容易出现分流错误，有远程直连同时解析dns的现象，造成dns污染，某些网站访问就会异常，比如Google的网站就有可能出问题，好像默认的健康检查就是访问的Google，你可以排查自动停止运行是否与这个有关，而且这种方式占用内存较大，注意观察内存占用情况。2、你远程同时配置了内置xray的dns解析又发给smartdns，这在配置上通过了，但逻辑上可能会出问题，xray的dns解析根据你的策略配置不同可能会根据路由规则配置进行一次分流，看起来15353端口也激活了，这个端口好像是chinadns-ng用的，是否用内置dns会自动激活chinadns-ng？这个我没有研究，总之，我觉得整个流程有点乱，采用smartdns解析dns又没有编译smartdns分支的话，其实现在设置也非常简单，跟早期的pw分流设置一样，也很好用，但是分流方式要采用dnsmasq+chinadns-ng，可以最大限度降低直连远程同时解析造成的dns污染，另外，你说某些网站ping不通，其实这个很好排查，smartdns有很详细的debug日志，我也强烈怀疑跟dns污染有关，可以参考我的设置试试
![image](https://github.com/user-attachments/assets/3853b86e-433e-4412-8e1f-12ea6ffd728d)

**Comment by gitbruc** [comment]
> > > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> > 
> > 
> > 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼
> 
> 远程dns部分如果不是设置tcp|udp等方式，xray|sing-box是在配置里直接走代理的，你设了localhost不会出问题？

日志说不强制转发代理访问

**Comment by gitbruc** [comment]
> > > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> > 
> > 
> > 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼
> 
> 你这个设置可能会存在两个问题：1、采用纯dnsmasq分流方式容易出现分流错误，有远程直连同时解析dns的现象，造成dns污染，某些网站访问就会异常，比如Google的网站就有可能出问题，好像默认的健康检查就是访问的Google，你可以排查自动停止运行是否与这个有关，而且这种方式占用内存较大，注意观察内存占用情况。2、你远程同时配置了内置xray的dns解析又发给smartdns，这在配置上通过了，但逻辑上可能会出问题，xray的dns解析根据你的策略配置不同可能会根据路由规则配置进行一次分流，看起来15353端口也激活了，这个端口好像是chinadns-ng用的，是否用内置dns会自动激活chinadns-ng？这个我没有研究，总之，我觉得整个流程有点乱，采用smartdns解析dns又没有编译smartdns分支的话，其实现在设置也非常简单，跟早期的pw分流设置一样，也很好用，但是分流方式要采用dnsmasq+chinadns-ng，可以最大限度降低直连远程同时解析造成的dns污染，另外，你说某些网站ping不通，其实这个很好排查，smartdns有很详细的debug日志，我也强烈怀疑跟dns污染有关，可以参考我的设置试试 ![image](https://private-user-images.githubusercontent.com/81218740/351936926-3853b86e-433e-4412-8e1f-12ea6ffd728d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk1ODYsIm5iZiI6MTcyMTg3OTI4NiwicGF0aCI6Ii84MTIxODc0MC8zNTE5MzY5MjYtMzg1M2I4NmUtNDMzZS00NDEyLThlMWYtMTJlYTZmZmQ3MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTU3ODI4ZGQ2OTExZDk1NWMzNTk2NWJlNmUxY2I4NDg5YWUwMjRlOGUwNmUwNmJjNTcxZDA1ZWJkZDUwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.419tDTpAwW6r7kmOK9il9J9Pd71VRrElPpmjH3Vv2PM)

其实我一开始就是跟你一样的配置，只不过是纯dnsmasq没有dnsng，在早期的passwall版本4.70之前一直用的稳稳的速度也很快，但是最近就会出现有的网站ping不通等各种情况我才进行改变的，也用过你的配置加上了dnsng，但是最后试下来只有变成xray/singbox的dns转发才会一切正常；我再研究一下smartdns的配置和日志，谢谢

**Comment by wtfr-dot** [comment]
> > > > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> > > 
> > > 
> > > 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼
> > 
> > 
> > 你这个设置可能会存在两个问题：1、采用纯dnsmasq分流方式容易出现分流错误，有远程直连同时解析dns的现象，造成dns污染，某些网站访问就会异常，比如Google的网站就有可能出问题，好像默认的健康检查就是访问的Google，你可以排查自动停止运行是否与这个有关，而且这种方式占用内存较大，注意观察内存占用情况。2、你远程同时配置了内置xray的dns解析又发给smartdns，这在配置上通过了，但逻辑上可能会出问题，xray的dns解析根据你的策略配置不同可能会根据路由规则配置进行一次分流，看起来15353端口也激活了，这个端口好像是chinadns-ng用的，是否用内置dns会自动激活chinadns-ng？这个我没有研究，总之，我觉得整个流程有点乱，采用smartdns解析dns又没有编译smartdns分支的话，其实现在设置也非常简单，跟早期的pw分流设置一样，也很好用，但是分流方式要采用dnsmasq+chinadns-ng，可以最大限度降低直连远程同时解析造成的dns污染，另外，你说某些网站ping不通，其实这个很好排查，smartdns有很详细的debug日志，我也强烈怀疑跟dns污染有关，可以参考我的设置试试 ![image](https://private-user-images.githubusercontent.com/81218740/351936926-3853b86e-433e-4412-8e1f-12ea6ffd728d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk1ODYsIm5iZiI6MTcyMTg3OTI4NiwicGF0aCI6Ii84MTIxODc0MC8zNTE5MzY5MjYtMzg1M2I4NmUtNDMzZS00NDEyLThlMWYtMTJlYTZmZmQ3MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTU3ODI4ZGQ2OTExZDk1NWMzNTk2NWJlNmUxY2I4NDg5YWUwMjRlOGUwNmUwNmJjNTcxZDA1ZWJkZDUwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.419tDTpAwW6r7kmOK9il9J9Pd71VRrElPpmjH3Vv2PM)
> 
> 其实我一开始就是跟你一样的配置，只不过是纯dnsmasq没有dnsng，在早期的passwall版本4.70之前一直用的稳稳的速度也很快，但是最近就会出现有的网站ping不通等各种情况我才进行改变的，也用过你的配置加上了dnsng，但是最后试下来只有变成xray/singbox的dns转发才会一切正常；我再研究一下smartdns的配置和日志，谢谢

采用这种方式如果你在luci界面操作了dhcp、防火墙等后，然后如果不清空pw的ipset，几乎100%会出现直连和远程同时解析dns的情况，我通过抓包已经证实了，包括用chinadns-ng，只是它有一个比对环节，会把解析回来的受污染的ip尽量阻止而表现不出来，但实际上分流的过程已经出现问题了，这个我也通过抓包证实了，所以最好的办法就是养成清空ipset的习惯，一个取巧的办法就是将规则更新设为每天深夜，这样间接起到定期清空ipset的作用，目前这个配置除了这一点外（这个问题应该跟整个系统有关，不算真正的bug）其它方面使用起来都很好

**Comment by gitbruc** [comment]
> > > > > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> > > > 
> > > > 
> > > > 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼
> > > 
> > > 
> > > 你这个设置可能会存在两个问题：1、采用纯dnsmasq分流方式容易出现分流错误，有远程直连同时解析dns的现象，造成dns污染，某些网站访问就会异常，比如Google的网站就有可能出问题，好像默认的健康检查就是访问的Google，你可以排查自动停止运行是否与这个有关，而且这种方式占用内存较大，注意观察内存占用情况。2、你远程同时配置了内置xray的dns解析又发给smartdns，这在配置上通过了，但逻辑上可能会出问题，xray的dns解析根据你的策略配置不同可能会根据路由规则配置进行一次分流，看起来15353端口也激活了，这个端口好像是chinadns-ng用的，是否用内置dns会自动激活chinadns-ng？这个我没有研究，总之，我觉得整个流程有点乱，采用smartdns解析dns又没有编译smartdns分支的话，其实现在设置也非常简单，跟早期的pw分流设置一样，也很好用，但是分流方式要采用dnsmasq+chinadns-ng，可以最大限度降低直连远程同时解析造成的dns污染，另外，你说某些网站ping不通，其实这个很好排查，smartdns有很详细的debug日志，我也强烈怀疑跟dns污染有关，可以参考我的设置试试 ![image](https://private-user-images.githubusercontent.com/81218740/351936926-3853b86e-433e-4412-8e1f-12ea6ffd728d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk1ODYsIm5iZiI6MTcyMTg3OTI4NiwicGF0aCI6Ii84MTIxODc0MC8zNTE5MzY5MjYtMzg1M2I4NmUtNDMzZS00NDEyLThlMWYtMTJlYTZmZmQ3MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTU3ODI4ZGQ2OTExZDk1NWMzNTk2NWJlNmUxY2I4NDg5YWUwMjRlOGUwNmUwNmJjNTcxZDA1ZWJkZDUwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.419tDTpAwW6r7kmOK9il9J9Pd71VRrElPpmjH3Vv2PM)
> > 
> > 
> > 其实我一开始就是跟你一样的配置，只不过是纯dnsmasq没有dnsng，在早期的passwall版本4.70之前一直用的稳稳的速度也很快，但是最近就会出现有的网站ping不通等各种情况我才进行改变的，也用过你的配置加上了dnsng，但是最后试下来只有变成xray/singbox的dns转发才会一切正常；我再研究一下smartdns的配置和日志，谢谢
> 
> 采用这种方式如果你在luci界面操作了dhcp、防火墙等后，然后如果不清空pw的ipset，几乎100%会出现直连和远程同时解析dns的情况，我通过抓包已经证实了，包括用chinadns-ng，只是它有一个比对环节，会把解析回来的受污染的ip尽量阻止而表现不出来，但实际上分流的过程已经出现问题了，这个我也通过抓包证实了，所以最好的办法就是养成清空ipset的习惯，一个取巧的办法就是将规则更新设为每天深夜，这样间接起到定期清空ipset的作用，目前这个配置除了这一点外（这个问题应该跟整个系统有关，不算真正的bug）其它方面使用起来都很好

非常感谢，我已经重新配置了smartdns和自动更新规则列表，目前一切正常🙏🏻️

**Comment by 625045508** [comment]
> > > > > 你用了smartdns吗？6053端口和5335端口是不是指向的smartdns
> > > > 
> > > > 
> > > > 是的，但是只用5335的话不知道为啥有的网站ping不通，比如docker.com；只能加上passwall自带的其他dns，加上之后它就只用passwall自带的了，不用5335了。很是奇怪，头疼
> > > 
> > > 
> > > 你这个设置可能会存在两个问题：1、采用纯dnsmasq分流方式容易出现分流错误，有远程直连同时解析dns的现象，造成dns污染，某些网站访问就会异常，比如Google的网站就有可能出问题，好像默认的健康检查就是访问的Google，你可以排查自动停止运行是否与这个有关，而且这种方式占用内存较大，注意观察内存占用情况。2、你远程同时配置了内置xray的dns解析又发给smartdns，这在配置上通过了，但逻辑上可能会出问题，xray的dns解析根据你的策略配置不同可能会根据路由规则配置进行一次分流，看起来15353端口也激活了，这个端口好像是chinadns-ng用的，是否用内置dns会自动激活chinadns-ng？这个我没有研究，总之，我觉得整个流程有点乱，采用smartdns解析dns又没有编译smartdns分支的话，其实现在设置也非常简单，跟早期的pw分流设置一样，也很好用，但是分流方式要采用dnsmasq+chinadns-ng，可以最大限度降低直连远程同时解析造成的dns污染，另外，你说某些网站ping不通，其实这个很好排查，smartdns有很详细的debug日志，我也强烈怀疑跟dns污染有关，可以参考我的设置试试 ![image](https://private-user-images.githubusercontent.com/81218740/351936926-3853b86e-433e-4412-8e1f-12ea6ffd728d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk1ODYsIm5iZiI6MTcyMTg3OTI4NiwicGF0aCI6Ii84MTIxODc0MC8zNTE5MzY5MjYtMzg1M2I4NmUtNDMzZS00NDEyLThlMWYtMTJlYTZmZmQ3MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTU3ODI4ZGQ2OTExZDk1NWMzNTk2NWJlNmUxY2I4NDg5YWUwMjRlOGUwNmUwNmJjNTcxZDA1ZWJkZDUwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.419tDTpAwW6r7kmOK9il9J9Pd71VRrElPpmjH3Vv2PM)
> > 
> > 
> > 其实我一开始就是跟你一样的配置，只不过是纯dnsmasq没有dnsng，在早期的passwall版本4.70之前一直用的稳稳的速度也很快，但是最近就会出现有的网站ping不通等各种情况我才进行改变的，也用过你的配置加上了dnsng，但是最后试下来只有变成xray/singbox的dns转发才会一切正常；我再研究一下smartdns的配置和日志，谢谢
> 
> 采用这种方式如果你在luci界面操作了dhcp、防火墙等后，然后如果不清空pw的ipset，几乎100%会出现直连和远程同时解析dns的情况，我通过抓包已经证实了，包括用chinadns-ng，只是它有一个比对环节，会把解析回来的受污染的ip尽量阻止而表现不出来，但实际上分流的过程已经出现问题了，这个我也通过抓包证实了，所以最好的办法就是养成清空ipset的习惯，一个取巧的办法就是将规则更新设为每天深夜，这样间接起到定期清空ipset的作用，目前这个配置除了这一点外（这个问题应该跟整个系统有关，不算真正的bug）其它方面使用起来都很好

都用Chinadns-ng分流了，还需要开SmartDNS嘛，直接Passwall默认Dnsmasq+Chinadns-ng 指几个远程DNS解析国外不就行了
