### ISSUE TITLE
请问如何在/etc/opkg/customfeeds.conf添加您的项目链接，其他网站的我会弄

### ISSUE THREAD

**Issue by lyjhyjyes** [xiaorouji/openwrt-package#3335]
### 描述你想要的新功能

比如我设置了
src/gz fanqiang https://opkg.xxxx.com/openwrt-23.05/aarch64_generic/
请问您的GitHub项目如何添加

### 描述你想要的解决方案

比如我设置了
src/gz fanqiang https://opkg.xxxx.com/openwrt-23.05/aarch64_generic/
请问您的GitHub项目如何添加

### 描述你考虑过的替代方案
目前我是下载完整安装包，然后逐个安装ipk，达到升级passwall的目的
_No response_

**Comment by handsomeji** [comment]
No source.
