### ISSUE TITLE
[Feature Request]: VLAN Support

### ISSUE THREAD

**Issue by woogx** [xiaorouji/openwrt-package#3339]
### 描述你想要的新功能

首先，这现在并不是一个问题，我只想知道，如果我在原始的openWRT上加上vlan，然后加装passwall，那passwall可以把所有或者需要vlan下流量通过passwall分流吗？

### 描述你想要的解决方案

首先，这现在并不是一个问题，我只想知道，如果我在原始的openWRT上加上vlan，然后加装passwall，那passwall可以把所有或者需要vlan下流量通过passwall分流吗？

**Comment by woogx** [comment]
稍微说一下，我并没有在实际环境下做这个。现在只是在gns3上模拟。所有vlan都已经弄好。下一步就是加装passwall了。想偷个懒看看有没有现成的方案。

**Comment by hcym** [comment]
这个没关系的，我一直用vlan交换单臂路由
网络口上指定对应的eth0.1什么的完事了

**Comment by gito10** [comment]
passwall和是否使用VLAN是没影响的，直接用就行。
你的使用场景描述不清，你的关注点VLAN和Passwall，放一起讨论，是想实现个什么需求，这个不说清楚，别人没法帮你分析。
