### ISSUE TITLE
[Bug]: 当前4.78-1运行状态这里，点击点我检测疑似有bug。

### ISSUE THREAD

**Issue by dobetter** [xiaorouji/openwrt-package#3342]
### 描述您遇到的bug

版本：4.78-1
运行状态这里，点击点我检测疑似有bug：谷歌、Github、Instagram连测速会失败。
百度正常，虽然现实失败，但是实际上正常翻墙和代理。
回退到4.77-3，一切正常。

### 复现此Bug的步骤

安装4.78-1。
运行状态这里，点击点我检测：谷歌、Github、Instagram连测速会失败。

### 您想要实现的目的

正常检测网络情况

### 日志信息

无

### 系统相关信息

4.78-1

### 其他信息

无

**Comment by lwb1978** [comment]
代理模式是选gfw还是绕过大陆或者是其他，截个图看看，另外提供一下你的curl是什么版本？

**Comment by dobetter** [comment]
curl -V
curl 8.7.1 (x86_64-openwrt-linux-gnu) libcurl/8.7.1 mbedTLS/2.28.8 nghttp2/1.57.0
Release-Date: 2024-03-27
Protocols: file ftp ftps http https ipfs ipns mqtt
Features: alt-svc HSTS HTTP2 HTTPS-proxy IPv6 Largefile SSL threadsafe

![image](https://github.com/user-attachments/assets/9a3ca589-4df7-41e2-9bc1-acefd4cac1f7)

**Comment by dobetter** [comment]
代理模式：下面几个轮流切换测试也是一样的。

**Comment by lwb1978** [comment]
你的情况跟这个讨论中出现的问题应该是一样的，原因可能是出在了mbedTLS
https://github.com/xiaorouji/openwrt-passwall/discussions/3249

**Comment by Pacio** [comment]
朋友你好，请问修复后问题还存在吗？我最近也遇到这问题了，每晚必出这Bug

**Comment by dobetter** [comment]
我目前是回退到之前编译的版本。
> 朋友你好，请问修复后问题还存在吗？我最近也遇到这问题了，每晚必出这Bug
