### ISSUE TITLE
[Feature Request]: sing-box占用8080端口

### ISSUE THREAD

**Issue by kxdn3** [xiaorouji/openwrt-package#3344]
### 描述你想要的新功能

sing-box占用8080端口，导致hectorqin/reader容器不能使用，偏偏这个容器写死了端口，不能更改，请教如何更改sing-box端口

### 描述你想要的解决方案

更改端口

**Comment by kxdn3** [comment]
没办吗？

**Comment by lwb1978** [comment]
这个问题建议你到sing-box那边问一下，pw并不使用这个端口，如果确定你路由中8080端口是sing-box在监听，那有可能是sing-box的小猫咪模式的端口，具体也不是很了解。

**Comment by kxdn3** [comment]
> 这个问题建议你到sing-box那边问一下，pw并不使用这个端口，如果确定你路由中8080端口是sing-box在监听，那有可能是sing-box的小猫咪模式的端口，具体也不是很了解。

我用netstat -ltnp | grep 8080命令查询到的，但是很奇怪？刷完机第一次启动aing-box并没有占用，且功能一切正常，重启后就占用了

**Comment by yuban10703** [comment]
```
root@ImmortalWrt:~# cat /etc/sing-box/config.json
{
  "log": {
    "level": "info"
  },
  "dns": {
    "servers": [
      {
        "address": "tls://8.8.8.8"
      }
    ]
  },
  "inbounds": [
    {
      "type": "shadowsocks",
      "listen": "::",
      "listen_port": 8080,
      "sniff": true,
      "network": "tcp",
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ],
  "outbounds": [
    {
      "type": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      }
    ]
  }
}
root@ImmortalWrt:~#
```

我并没有启用任何singbox的节点,也没有在服务器端开singbox的服务器,也没安装除passwall以外的代理插件,但是singbox貌似会用这个配置文件默认启动,所以会占用8080端口,不知道什么原因
![image](https://github.com/user-attachments/assets/61c4c2f7-2282-43ac-8fb3-4c07230e6117)
删除/etc/sing-box/config.json后
![image](https://github.com/user-attachments/assets/e20025f5-58dd-44e1-8ff6-3a8ac92cdc0a)

**Comment by kxdn3** [comment]
修改"listen_port": 8080, 会如何

**Comment by yuban10703** [comment]
修改后肯定就不占用了,但是为什么singbox会莫名其妙起一个服务端,而且可以公网访问....

**Comment by handsomeji** [comment]
這個不是由passwall生成並運行的，應該是編譯的sing-box包裡包含的。
`/etc/init.d/sing-box stop`
`/etc/init.d/sing-box disable`
