### ISSUE TITLE
[Bug]: trojan协议导入丢失部分配置

### ISSUE THREAD

**Issue by admin4264** [xiaorouji/openwrt-package#3349]
### 描述您遇到的bug

订阅地址解析后自动导入的Trojan协助全部丢失option transport 'ws' 的配置字段

### 复现此Bug的步骤

类似trojan://f7fc5080-bd91-4491-9713-6215d66d60f8@g03.xnnet.com:443?allowInsecure=1&peer=&sni=&udp=0&type=ws#%F0%9F%87%AF%F0%9F%87%B5%20%E6%97%A5%E6%9C%AC%20%C2%B9%20x%201.0 这样的链接会丢失type=ws的配置
如果手动配置好后导出链接则会丢失allowInsecure=1&peer=&sni=&udp=0&type=一整列

### 您想要实现的目的

bug修复

### 日志信息

无

### 截图

![屏幕截图 2024-08-04 122144](https://github.com/user-attachments/assets/35444aae-03b4-4294-8726-d2d2c0e87d71)
![屏幕截图 2024-08-04 122203](https://github.com/user-attachments/assets/8f49b50c-6f68-4a1c-8ebe-4d3fc0760aec)

### 系统相关信息

当前版

**Comment by lwb1978** [comment]
fix
