### ISSUE TITLE
[Bug]: 负载均衡拒绝连接

### ISSUE THREAD

**Issue by lanruihua026** [xiaorouji/openwrt-package#3357]
### 描述您遇到的bug

<img width="661" alt="屏幕截图 2024-08-08 153647" src="https://github.com/user-attachments/assets/b380ba11-dc7e-45d1-89e6-b768c58325f4">

![屏幕截图 2024-08-08 153732](https://github.com/user-attachments/assets/79a457a7-1ba1-4868-924b-233fcf48fa52)

如上图所示，负载均衡处于打开状态，但后台无法进入，这bug似乎一直存在。

### 复现此Bug的步骤

使用lean大佬的源码，源码一旦更新便自动编译，在线刷入最新的固件且勾选保留配置。

### 您想要实现的目的

修复负载均衡拒绝连接，不可用

### 日志信息

Fri Aug 16 09:47:39 2024 user.notice ucitrack: Setting up /etc/config/passwall reload trigger for non-procd /etc/init.d/passwall
Fri Aug 16 09:47:39 2024 user.notice ucitrack: Setting up /etc/config/passwall_server reload trigger for non-procd /etc/init.d/passwall_server
Fri Aug 16 09:47:39 2024 user.notice ucitrack: Setting up /etc/config/passwall2 reload trigger for non-procd /etc/init.d/passwall2
Fri Aug 16 09:47:39 2024 user.notice ucitrack: Setting up /etc/config/passwall2_server reload trigger for non-procd /etc/init.d/passwall2_server

### 系统相关信息

Passwall: 4.78-1
基于Lean源码编译的openwrt，软路由R68s

**Comment by bcseputetto** [comment]
既然你都截图了，为什么不顺便截一下passwall负载均衡的页面呢，下面节点部分不用，至少上半部分截一下

**Comment by lanruihua026** [comment]
![image](https://github.com/user-attachments/assets/b6825957-2ae2-458c-b57a-6cf5e2ceaf40)
重新短接线刷系统后，问题得以解决，当时是istore os最新版，通过在线更新方式上传自己编译镜像刷机，不勾选保留配置文件。

**Comment by bcseputetto** [comment]
所以是正常了？iStoreOS为啥不用 .run 包安装
https://github.com/bcseputetto/Are-u-ok
问题解决可以关闭这个issue

**Comment by djgend** [comment]
其实不用刷机的，我也碰到类似问题。haproxy由于分流加负载均衡再加上模式选择配置错误，均衡后台界面无法打开了。有两种方式可以解决，用passwall重置脚本功能，在基本设置的faq里，重置之前保险起见可以手动备份一下修改过的地址集和配置信息等，不过我重置后发现修改过的配置还是保留下来。还有一种就是opkg重装最新版的passwall，可以油管奶瓶有教程。我是通过reset config恢复的，只要知道大不了就reinstall就好了。多点重置和复位按钮，这个haproxy很容易突然崩溃，因为它要求主用、备用，端口号，协议，密码等要设置正确，建议少用几组做负载均衡很容易炸cpu。我现在用三个一组，一主一备。
