### ISSUE TITLE
[Bug]: 无法正确解析3xui导出的shadowsocks(ws+tls)链接

### ISSUE THREAD

**Issue by MeowRay** [xiaorouji/openwrt-package#3358]
### 描述您遇到的bug

无法正确解析3xui导出的shadowsocks链接
测试节点配置为 shadowsocks ws tls

ss://HETSS9L7CXJUFJVNA79Y766PD8B7@xxxxxx.com:443?type=ws&path=%2Ftestpath&host=xxxxxx.com&security=tls&fp=&alpn=h3%2Ch2%2Chttp%2F1.1&sni=xxxxxx.com#test-1%40ss

### 复现此Bug的步骤

1. 3xui 创建shadowsocks ws tls
2. 导出分享链接
3. passwall添加节点
4. passwall导入分享URL

### 您想要实现的目的

正确处理导入，
目前似乎会默认使用 sing-box的的shadowsocks，但sing-box内似乎没有启用tls的选项

### 日志信息

![image](https://github.com/user-attachments/assets/2e4b19a4-f472-4526-a5da-e76845857ec6)

### 系统相关信息

![image](https://github.com/user-attachments/assets/09c713ca-2bdd-49a8-ab0c-b95f7d33605b)

**Comment by MeowRay** [comment]
同时，手动修改为xray并且设置完毕后无法导出链接，点击无反应console报错
![image](https://github.com/user-attachments/assets/e7060c92-ade6-46c1-9656-fa1e81ae2e1e)

**Comment by lwb1978** [comment]
试试在节点列表-通过链接添加节点是否正常导入，导入分享url和导出分享url功能只是把功能做出来了，需要优化的地方很多。

**Comment by lwb1978** [comment]
shadowsocks的默认程序需要你事先在节点订阅界面设置好。

**Comment by MeowRay** [comment]
> 试试在节点列表-通过链接添加节点是否正常导入，导入分享url和导出分享url功能只是把功能做出来了，需要优化的地方很多。

不行

![image](https://github.com/user-attachments/assets/805e121e-b671-4a7d-a83b-40018234984b)

**Comment by lwb1978** [comment]
fix

**Comment by lwb1978** [comment]
@MeowRay 我在界面上开启了sing-box 对 ss tls的支持，但具体是否能用不清楚，如果你有环境的话帮测试下。

**Comment by MeowRay** [comment]
> @MeowRay 我在界面上开启了sing-box 对 ss tls的支持，但具体是否能用不清楚，如果你有环境的话帮测试下。

源码编译？

**Comment by lwb1978** [comment]
> > @MeowRay 我在界面上开启了sing-box 对 ss tls的支持，但具体是否能用不清楚，如果你有环境的话帮测试下。
> 
> 源码编译？

如果有能力的话就自行编译最新代码，要不就等待新版发布吧。
