### ISSUE TITLE
[Bug]: 为哈我模式选项里是这个“必须代理的流量”，更新到最新了也还是这样

### ISSUE THREAD

**Issue by pbclaodentm** [xiaorouji/openwrt-package#3360]
### 描述您遇到的bug

模式里：
中国列表、TCP 默认代理模式、UDP 默认代理模式 正常的选项里应该显示是“代理”，但我这几个选项里头代理全是“必须代理的流量”，我更新了passwall和所有依赖，发现还是这样的，这是什么原因造成的呢？

### 复现此Bug的步骤

打开模式里  中国列表 等这几个选项里查看

### 您想要实现的目的

如何变成正常的表述，并了解造成此问题的原因

### 日志信息

无

### 截图

![xuanxiang](https://github.com/user-attachments/assets/433d4b0a-4a66-4cb8-97f2-9c1077e99e47)

### 系统相关信息

Passwall 版本【 4.78-1 】

**Comment by lwb1978** [comment]
因为你装有其他的代理软件，同样的英文被其他代理软件翻译去了，不影响使用，除非你卸载其他代理软件。这个pw没办法解决，是openwrt的特性。

**Comment by bcseputetto** [comment]
这是因为你装了passwall的同时，也装了openclash，才变成这样
![QQ_1723454314633](https://github.com/user-attachments/assets/84027666-2565-486f-b510-7e1e60576b7e)
openclash的po影响了passwall

**Comment by chapiom** [comment]
我这边也是这样，不知道为什么gfwlist模式没有了，openclash没有开启。

**Comment by chapiom** [comment]
卸载了openclash没有这个必须代理了，但是选项变成了代理和不代理，没有gfwlist啊。

**Comment by bcseputetto** [comment]
@chapiom 新版本请通过“切换”右侧的四个按钮来切换模式，点"GFW列表"，就是gfwlist模式

**Comment by chapiom** [comment]
> @chapiom 新版本请通过“切换”右侧的四个按钮来切换模式，点"GFW列表"，就是gfwlist模式

点了GFW列表，就变成不代理了

**Comment by bcseputetto** [comment]
> 点了GFW列表，就变成不代理了

@chapiom 对啊，就是这样的，你只想要gfw列表代理，那个默认代理模式就应该是不代理
新版的passwall模式那里有几个选项，分别是
使用直连列表:规则列表里的直连列表，勾上后直连列表生效，直连列表里的规则走直连
使用代理列表: 规则列表里的代理列表，勾上后代理列表生效，代理列表里的规则走代理
使用屏蔽列表: 规则列表里的屏蔽列表，勾上后屏蔽列表生效，屏蔽列表里的规则将被屏蔽
使用GFW列表:勾上后GFW列表生效，GFW列表的规则将走代理
中国列表:包含三个列表分别是中国域名列表，中国IPv4列表，中国IPv6列表，可选是否使用该列表，或者选择该列表的规则走直连或者代理
TCP/UDP默认代理模式:这个并不是总控制，而是当没有命中上面所有规则时，是否要代理。
所以如果你只是要gfw列表的域名才走代理，这个默认就应该是不代理，没有任何问题。

**Comment by chapiom** [comment]
> > 点了GFW列表，就变成不代理了
> 
> @chapiom 对啊，就是这样的，你只想要gfw列表代理，那个默认代理模式就应该是不代理 新版的passwall模式那里有几个选项，分别是 使用直连列表:规则列表里的直连列表，勾上后直连列表生效，直连列表里的规则走直连 使用代理列表: 规则列表里的代理列表，勾上后代理列表生效，代理列表里的规则走代理 使用屏蔽列表: 规则列表里的屏蔽列表，勾上后屏蔽列表生效，屏蔽列表里的规则将被屏蔽 使用GFW列表:勾上后GFW列表生效，GFW列表的规则将走代理 中国列表:包含三个列表分别是中国域名列表，中国IPv4列表，中国IPv6列表，可选是否使用该列表，或者选择该列表的规则走直连或者代理 TCP/UDP默认代理模式:这个并不是总控制，而是当没有命中上面所有规则时，是否要代理。 所以如果你只是要gfw列表的域名才走代理，这个默认就应该是不代理，没有任何问题。

我这样设了以后，还是在墙内，墙外的网站完全打不开。
