### ISSUE TITLE
[Bug]: 开启DNS 重定向导致53端口SYN-flood问题

### ISSUE THREAD

**Issue by cococle** [xiaorouji/openwrt-package#3363]
### 描述您遇到的bug

开启DNS 重定向导致53端口SYN-flood问题

### 复现此Bug的步骤

开启DNS 重定向导致53端口SYN-flood问题

### 您想要实现的目的

开启DNS 重定向导致53端口SYN-flood问题

### 日志信息

开启DNS 重定向导致53端口SYN-flood问题

### 系统相关信息

开启DNS 重定向导致53端口SYN-flood问题

**Comment by cococle** [comment]
日志里面报错这个：openwrt kern.info kernel: [19051.988065] TCP: request_sock_TCP: Possible SYN flooding on port 53. Sending cookies.  Check SNMP counters.

**Comment by lwb1978** [comment]
这种情况你要检查路由系统，路由上都开了什么软件，网络的使用环境。你没有提供更多有效信息，无法讨论，这应该只是个例。

**Comment by cococle** [comment]
最新版本PS，没有其他插件，开启DNS 重定向就会报错
Tue Aug 20 09:38:57 2024 kern.info kernel: [30551.929755] TCP: request_sock_TCP: Possible SYN flooding on port 53. Sending cookies.  Check SNMP counters.
