### ISSUE TITLE
[Feature Request]: 希望可以再xray选择节点的时候提供落地代理的选项

### ISSUE THREAD

**Issue by lilith-rong** [xiaorouji/openwrt-package#3364]
### 描述你想要的新功能

希望可以再前置代理的旁边直接新增落地代理选项，可以再替换机场的节点的同时，保留落地区域，可以更方便的管理分流
现在的落地代理似乎是每个节点单独设置的，希望可以将落地节点的设置也和前置节点一样，分离开来

### 描述你想要的解决方案

希望可以再前置代理下方新增落地代理的选项

**Comment by lwb1978** [comment]
现在 @nftbty 还在考虑是否将落地节点修改为前置节点设置，工程量比较庞大，具体工作需要等老大有时间才能开展。

**Comment by lilith-rong** [comment]
> 现在 @nftbty 还在考虑是否将落地节点修改为前置节点设置，工程量比较庞大，具体工作需要等老大有时间才能开展。

不管怎么说，大佬们都是辛苦了，等大佬们有空再说
