### ISSUE TITLE
[Bug]: TUIC连接失败超时

### ISSUE THREAD

**Issue by superabbite1** [xiaorouji/openwrt-package#3372]
### 描述您遇到的bug

无法通过订阅导入TUIC节点，手动添加后无法连接，节点是没有问题的，手机和电脑客户端都可以正常使用。是不是手动配置的不正确？TLS ALPN 这个要怎么填？

![QQ截图20240819233427](https://github.com/user-attachments/assets/920c23d3-f34f-4c5a-8104-aa055db26390)
![QQ截图20240819233447](https://github.com/user-attachments/assets/1780aab5-40b4-438f-b812-40ae3a337635)

### 复现此Bug的步骤

无法通过订阅导入TUIC节点，手动添加后无法连接，节点是没有问题的，手机和电脑客户端都可以正常使用。是不是手动配置的不正确？TLS ALPN 这个要怎么填？

### 您想要实现的目的

正常连接使用

### 日志信息

无

### 系统相关信息

Passwall 版本
【 4.68-5 4.71-2 4.58-3 】

**Comment by lwb1978** [comment]
请提供一个TUIC节点的订阅链接，把链接里的域名做脱敏处理

**Comment by salehmack** [comment]
一直在使用passwall tuic节点 也曾遇到过类似问题 是通过重建节点 根据服务器端调整客户端参数 最终确定两边参数一致后就通了 目前使用大概半个月左右了一直很正常 TLS ALPN一般服务器端会使用h3 具体还是要参考服务器端的配置

**Comment by superabbite1** [comment]
> 请提供一个TUIC节点的订阅链接，把链接里的域名做脱敏处理

http://110.42.188.171/test.html

**Comment by superabbite1** [comment]
> 一直在使用passwall tuic节点 也曾遇到过类似问题 是通过重建节点 根据服务器端调整客户端参数 最终确定两边参数一致后就通了 目前使用大概半个月左右了一直很正常 TLS ALPN一般服务器端会使用h3 具体还是要参考服务器端的配置

我的电脑v2rayN和手机app上这个节点都正常用的

**Comment by lwb1978** [comment]
> > 请提供一个TUIC节点的订阅链接，把链接里的域名做脱敏处理
> 
> http://110.42.188.171/test.html

pw代码中并没有做tuic的导入支持，理论上不算bug，另外你提供的这个链接没有参考价值，这个链接并没有tls，udp，alpn等参数，只有最基本的账号、密码和服务器、端口，等什么时候有空我再自己导一个链接来搞吧，毕竟现在这个协议用的人不多。还要就是这个协议原生客户端已经永久停止开发，楼主如果想用可以用sing-box的tuic类型手动配置一下，这个配置相对简单些。个人觉得原生的tuic可以移除支持了，可以减少维护量。

**Comment by lwb1978** [comment]
最新代码已添加tuic导入/导出和订阅的支持，默认采用sing-box作为tuic客户端。

**Comment by jaqueline-law** [comment]
alpn用H3。alpn用H3。alpn用H3。
如果还不行，在passwall中用sing-box中的tuic，而不是直接用tuic。alpn用H3。

**Comment by xuemingxx** [comment]
> alpn用H3。alpn用H3。alpn用H3。 如果还不行，在passwall中用sing-box中的tuic，而不是直接用tuic。alpn用H3。

太牛了，看了一天不知道哪里有问题，手机上小火箭可以用，电脑小火箭也可以用，但是一到passwall里就超时。。alpn一改成h3就好了！感谢感谢🙏
