### ISSUE TITLE
[Bug]: ip被绑架了,playerapp 转圈圈

### ISSUE THREAD

**Issue by smzdmmmm** [xiaorouji/openwrt-package#3378]
### 描述您遇到的bug

google时间都是国内的，与IP地的时间都不一致，全是国内地址时间。player app，更新一直出不去转圈圈。

### 复现此Bug的步骤

player app无法更新应用

### 您想要实现的目的

player app无法更新应用

### 日志信息

player app无法更新应用

### 系统相关信息

 4.78-1

**Comment by lwb1978** [comment]
检查你自己的设置和节点，这情况跟pw无关。
