### ISSUE TITLE
[Bug]: 日志中出现很多dns错误提示

### ISSUE THREAD

**Issue by smdx** [xiaorouji/openwrt-package#3379]
### 描述您遇到的bug

各位大佬好，在日志中出现很多dns错误提示，这个是什么原因？怎么解决？谢谢

### 复现此Bug的步骤

1，DNS 分流 Dnsmasq
2，直连dns是mosdns
3，过滤模式Xray，请求协议是TCP+DoH

### 您想要实现的目的

解决错误提示

### 日志信息

2024/08/24 04:44:16 [Error] app/dns: failed to retrieve response for thetracker.org. > Post "https://1.1.1.1/dns-query": context canceled
2024/08/24 04:44:16 127.0.0.1:55398 accepted udp:208.67.222.222:53 [dns-in -> dns-out]
2024/08/24 04:44:16 [Error] app/dns: failed to retrieve response for tracker.corpscorp.online. > Post "https://1.1.1.1/dns-query": context canceled
2024/08/24 04:44:22 127.0.0.1:58792 accepted udp:208.67.222.222:53 [dns-in -> dns-out]
2024/08/24 04:44:22 [Error] app/dns: failed to retrieve response for servandroidkino.ru. > Post "https://1.1.1.1/dns-query": context canceled
2024/08/24 04:44:22 127.0.0.1:53953 accepted udp:208.67.222.222:53 [dns-in -> dns-out]
2024/08/24 04:44:24 10.0.0.26:40780 accepted tcp:216.239.32.223:443 [tcp_redir -> default]
2024/08/24 04:44:26 127.0.0.1:54161 accepted udp:208.67.222.222:53 [dns-in -> dns-out]

### 截图

![2024-08-24_124105](https://github.com/user-attachments/assets/38a284e9-555d-4b8f-8f8e-57ab13cbf15e)

![2024-08-24_124022](https://github.com/user-attachments/assets/da5a8032-7226-47c4-b39f-f1ab53d78c2a)

### 系统相关信息

luci-app-passwall | 4.78-1
Xray 1.8.23 (Xray, Penetrates Everything.) OpenWrt (go1.22.6 linux/amd64)

**Comment by bozheng1988** [comment]
同样的问题困扰了好几个月，不定时会遇到有时候几分钟有时候几天出现；部分情况只是远程DNS挂，有时候全部DNS都挂了，只能重启插件才能解决
