### ISSUE TITLE
[Bug]: ss订阅异常

### ISSUE THREAD

**Issue by Jack9708** [xiaorouji/openwrt-package#3380]
### 描述您遇到的bug

上个月的源码无此问题。

从订阅中取出的节点链接为：
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp4eHh4eHhAeHh4eC54eHh4eC5jb206NTYwMDE#Hong%20Kong-01

实际添加后效果如图：
![QQ20240825-163348](https://github.com/user-attachments/assets/909eea72-29df-4b44-9bb0-079d6c84aca9)

### 复现此Bug的步骤

同上

### 您想要实现的目的

修复

### 日志信息

这个不重要

### 系统相关信息

4.78-1

**Comment by Jack9708** [comment]
@lwb1978

**Comment by lwb1978** [comment]
是订阅错误还是导入错误呢？我看一下源码

**Comment by Jack9708** [comment]
> 是订阅错误还是导入错误呢？我看一下源码

订阅和导入都是一样的，都是图上那样~

**Comment by lwb1978** [comment]
我测试了，通过“导入分享url”是正确的，订阅不正确，已修复，主要是当时增强ss订阅代码时没有考虑到全段base64加密的订阅链接。
