### ISSUE TITLE
[Feature Request]: 节点订阅、列表的自动更新时间设定，申请给到10分钟级。

### ISSUE THREAD

**Issue by cat00fish** [xiaorouji/openwrt-package#3387]
### 描述你想要的新功能

节点订阅、规则列表的自动更新时间设置，最小单位是小时。申请增加以10分钟为单位的层级选择。以便更精细化控制。

### 描述你想要的解决方案

节点订阅、规则列表的自动更新时间设置，申请增加以10分钟为单位的层级选择。

**Comment by bcseputetto** [comment]
订阅节点的更新很可能会重启服务，10分钟意味着你10分钟就会重启一次，你真的要这么短时间更新订阅？

**Comment by kxdn3** [comment]
啥节点这么不稳定需要频繁订阅…建议抛弃

**Comment by cat00fish** [comment]
订阅时间的设置有两种模式。说的不是间隔时间循环模式。而是定时更新模式，一天最多只能有一次的…。   现在是只能在整点更新，希望是再到精确小时后面的十分钟，比如6点20分

**Comment by cat00fish** [comment]
就是因为每次订阅会重启，最好是安排在凌晨以后，代理使用少时进行。如果备用机场或节点类型多了，又只能整点订阅，就会排不开。

**Comment by bcseputetto** [comment]
> 订阅时间的设置有两种模式。说的不是间隔时间循环模式。而是定时更新模式，一天最多只能有一次的…。 现在是只能在整点更新，希望是再到精确小时后面的十分钟，比如6点20分
就是因为每次订阅会重启，最好是安排在凌晨以后，代理使用少时进行。如果备用机场或节点类型多了，又只能整点订阅，就会排不开。

@cat00fish 那也不是不行，passwall是通过crontab计划任务来实现定时更新规则和定时更新订阅的，你可以设置完自动更新订阅后，手动修改计划任务即可。你可以在OpenWrt的网页后台，找到`系统`-`计划任务`，里面应该有passwall添加的更新订阅计划任务，例子如下
```
0 8 * * * lua /usr/share/passwall/subscribe.lua start cfg2a4b92 cron > /dev/null 2>&1 &
```
这是一个crontab计划任务，注意前面五位，这个是cron表达式
这里是五位cron表达式，分别是 `分 时 天 月 周`，在某位上为`*`则代表`每分`，`每时`，`每天`以此类推
所以`0 8 * * *`代表每天8点0分执行cron表达式后面的命令
你可以把它改成`20 8 * * *`，就代表每天8点20分执行cron表达式后面的命令
![QQ_1725594339034](https://github.com/user-attachments/assets/fb4ae17a-b852-4653-b6e2-060464b19ecc)

当然除了网页后台上修改，你也可以在终端里修改，终端执行
```console
crontab -e
```
就可以打开crontab计划任务的编辑模式，可以在里面添加或修改。

**Comment by cat00fish** [comment]
太好了,受教,多谢!
