### ISSUE TITLE
[Bug]: “自动切换”选项缺失

### ISSUE THREAD

**Issue by flycld8** [xiaorouji/openwrt-package#3388]
### 描述您遇到的bug

升级最近2个版本后发现主页“自动切换”选项卡缺失，还请核实添加。

### 复现此Bug的步骤

升级最近2个版本后发现主页“自动切换”选项卡缺失，还请核实添加。

### 您想要实现的目的

遇故障自动切换。

### 日志信息

遇故障无法自动切换。

### 系统相关信息

4.76-4.77

**Comment by lwb1978** [comment]
这个功能早已去除，相关功能在socks中或者采用负载均衡
