### ISSUE TITLE
[Bug]: 4.78-2 版本 6.6.49内核 ImmortalWRT X86版本 透明代理模式不工作

### ISSUE THREAD

**Issue by chenxuan5858** [xiaorouji/openwrt-package#3393]
### 描述您遇到的bug

4.78-2 版本 6.6.49内核 ImmortalWRT X86版本 透明代理模式不工作

### 复现此Bug的步骤

高级设置tproxy代理失败，只能redirect

### 您想要实现的目的

使用透明代理

### 日志信息

暂无

### 系统相关信息

passwall：4.78-2

**Comment by lwb1978** [comment]
我两台路由arm和x86都是imm 6.6.49 使用tproxy没有任何问题，而且还开启了ipv6代理，你检查下自己漏编译了什么或者有没有其他的插件冲突，另外看一下日志，别以为它没有用。

**Comment by chenxuan5858** [comment]
好的

**Comment by chenxuan5858** [comment]
试过了，上一个版本没有问题，编译依赖没有变化

**Comment by chenchsha** [comment]
4.78-2用一段时间，要清空ipset才行，之前4.78-1不会

**Comment by chenxuan5858** [comment]
我再试试

**Comment by qingtian110** [comment]
OpenWrt 版本：23.05.4
内核版本：Linux 6.6.50
Dnsmasq 版本：2.90-2
Passwall 版本：4.78-2

iptables + tproxy 表示很稳定（我没有使用 nftables，如果你使用 nftables 进行过滤，不稳定是正常的。毕竟 nftset 目前半残废状态）

![image](https://github.com/user-attachments/assets/8aeec1b9-f613-4cbb-94e7-e5dccc0d9701)
![image](https://github.com/user-attachments/assets/cbca972c-db1c-44e8-97f1-8e4ce70043e9)

**Comment by ghost** [comment]
請您不要與其他 代理插件 一起編譯，此外，您需要確保在編譯時前綴以iptables和ip6tables還有kmod-ipt以及kmod-ip6全選。

**Comment by chenxuan5858** [comment]
我再试试

**Comment by WongKwongYu** [comment]
是不是ipset太老了，登录路由器，软件包里面看看ipset有没有更新

**Comment by smallprogram** [comment]
@lwb1978 我也有这毛病，immortalwrt的mian分支自己编译的，pw好多功能都不正常，Dnsmasq-full等等依赖都选了，无论iptables还是nftables，redirect还是tcpoxy,抽风似的，不知道啥毛病，之前用lean的源码没问题。你是自己编译的固件还是怎么搞的？

```
ipset  7.21-r1
dnsmasq-full  2.90-r3
```

**Comment by lwb1978** [comment]
> @lwb1978 我也有这毛病，immortalwrt的mian分支自己编译的，pw好多功能都不正常，Dnsmasq-full等等依赖都选了，无论iptables还是nftables，redirect还是tcpoxy,抽风似的，不知道啥毛病，之前用lean的源码没问题。你是自己编译的固件还是怎么搞的？

我也是imm的mian源码云编译的（详见我的仓库），ipt和nft均可以正常工作。我两台路由，x86和rockchip都没有问题。

**Comment by smallprogram** [comment]
> > @lwb1978 我也有这毛病，immortalwrt的mian分支自己编译的，pw好多功能都不正常，Dnsmasq-full等等依赖都选了，无论iptables还是nftables，redirect还是tcpoxy,抽风似的，不知道啥毛病，之前用lean的源码没问题。你是自己编译的固件还是怎么搞的？
> 
> 我也是imm的mian源码云编译的（详见我的仓库），ipt和nft均可以正常工作。我两台路由，x86和rockchip都没有问题。

我知道啥毛病了，mwan3干掉就好了。雷人。。。。。这东西劫持流量

**Comment by lwb1978** [comment]
mwan3这玩意老生常谈了，在lede下还好些，在imm或者官方op的话就各种冲突。它基于fw3开发的，但是现如今fw4都这么多年了，也并没有继续开发mwan4，也许作者已经放弃这个项目了。

**Comment by chenxuan5858** [comment]
mwan3我属于必须用的，我双线接入，ipset运营商分流，之前试过爱快，没办法进行vlan桥接，iptv组播进不来，加上爱快网络设置鸡肋，vlan和局域网还得分开，逻辑混乱，我还是回到了openwrt，mwan3必须用，现在还是用的上个版本的passwall，没啥问题。

**Comment by lwb1978** [comment]
但4.78-2对iptables的小修改并未涉及到透明代理核心，那些优化即使删除掉都不会影响pw代理功能，只有nftables进行了较大的调整。

**Comment by chenxuan5858** [comment]
> 但4.78-2对iptables的小修改并未涉及到透明代理核心，那些优化即使删除掉都不会影响pw代理功能，只有nftables进行了较大的调整。

我也是这么理解的，但是就很奇怪，上个版本一点儿问题没有，就先这样吧
