### ISSUE TITLE
[Feature Request]: 偶然注意到chinadns-ng aarch64版的已经支持硬件加速，组件更新中是否可以替换成硬件加速版本的呢？

### ISSUE THREAD

**Issue by milkman-wang** [xiaorouji/openwrt-package#3396]
### 描述你想要的新功能

组件更新中chinadns-ng aarch64版的替换成硬件加速版本

### 描述你想要的解决方案

更新源替换成chinadns-ng+wolfssl@aarch64-linux-musl@generic+v8a@fast+lto，如https://github.com/zfl9/chinadns-ng/releases/download/2024.04.30/chinadns-ng+wolfssl@aarch64-linux-musl@generic+v8a@fast+lto

**Comment by SakuraFallingMad** [comment]
arm的并不是所有的支持硬件加速，所以用无加速版本

**Comment by lwb1978** [comment]
楼上正解，比如树莓派就不支持硬件加速，另外家用路由这点访问量，用不用硬件加速根本无感。

**Comment by sbwml** [comment]
对于 AARCH64，openwrt 默认具备且启用内核 aes 驱动的设备其实就是瑞芯微的 aarch64 架构。

刚刚看了一下这个 repo 的古往今来。似乎是有尝试对瑞芯微平台使用 chinadns-ng+wolfssl 版本进行更新（[commit](https://github.com/xiaorouji/openwrt-passwall/commit/da4eecc94c3aeadc70997e7500bd7396e88c1210)）

-------

但是这个 `board` 的值获取应该是会有意外，它应该是可以通过这样的方式来获取平台信息

```lua
echo $(. /etc/openwrt_release ; echo ${DISTRIB_TARGET%%/*})
```

这将会得到标准的 target 信息，如：`rockchip`、`bcm27xx`、`x86` 等
