### ISSUE TITLE
[Bug]: 今天的更新，貌似会把路由带崩

### ISSUE THREAD

**Issue by guochan2019** [xiaorouji/openwrt-package#3399]
### 描述您遇到的bug

今天的更新[luci: set ipset timeout to 2d]，早上编译完成后刷机(x86 ikuai虚拟机)，至中午时分PVE突然失联，以为是停电，结果一看是PVE卡死，想到早上刚更新op，重新开机后打开控制台，看到op启动完成后，后面一堆报错代码不断在跑，心想可能跟这个有关。回到昨天之前的版本后，一切正常。上来报告一下，不好意思，代码一直跑，也不会在控制台载屏

### 复现此Bug的步骤

需要在有op启动界面才能看到，后台是否有log不清楚

### 您想要实现的目的

不好意思，无

### 日志信息

不好意思，无

### 截图

不好意思，无

### 系统相关信息

edge

**Comment by lwb1978** [comment]
问题已经确认，重新编辑2楼内容进行答复应该更容易让更多人看见。（9.15）
----------
已经确认是lede切换到gcc12后，ipset版本太低导致该问题，处理方法建议如下:
1.如果是自编译的lede固件，可拉取openwrt官方源中最新ipset替换lede自带的以后重新编译，源地址:`https://github.com/openwrt/openwrt/tree/main/package/network/utils/ipset`
2.如果使用的是其他人编译的固件或者不想重新编译的，可以登陆路由器，在软件管理中将ipset升级到最新版本。

**Comment by guochan2019** [comment]
> 发passwall运行日志，和系统版本看看

不好意思大佬，我已经恢复到旧版了，恢复完看到启动后的状态，才想到可能跟更新有关，当时因为要干活，也没想那么多，也只是猜测

**Comment by lwb1978** [comment]
高级设置里你用的防火墙工具是什么？iptables还是nftables？

**Comment by guochan2019** [comment]
iptables，报错的就是跟iptable有关的内容，一直滚动，我也没仔细看，当时急着恢复系统干活

**Comment by lwb1978** [comment]
经过实体路由测试，并未出现楼主说的报错的情况，问题需要进一步核实，暂时保留该问题。

**Comment by piaoyizy** [comment]
` Fri Sep 13 23:25:33 2024 daemon.notice procd: /etc/rc.d/S99openclash: OpenClash Restart...
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.883333] ipset[4743]: segfault at ffffffffa49e7f70 ip 00007f59f918567a sp 00007ffea49e6d68 error 5 in libc.so[7f59f9140000+55000] likely on CPU 1 (core 0, socket 2)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.883984] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.885730] ipset[4744]: segfault at 9a74f6e ip 00007f675990067a sp 00007fff09a742c8 error 4 in libc.so[7f67598bb000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.886349] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.888538] ipset[4745]: segfault at 1aaeff69 ip 00007fecd2e4c67a sp 00007ffc1aaee0c8 error 4 in libc.so[7fecd2e07000+55000] likely on CPU 1 (core 0, socket 2)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.889139] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.890741] ipset[4746]: segfault at ffffffffcb6e6f6b ip 00007fa7e52d767a sp 00007ffecb6e62a8 error 5 in libc.so[7fa7e5292000+55000] likely on CPU 2 (core 0, socket 4)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.891352] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.892887] ipset[4747]: segfault at ffffffffe588ff6b ip 00007fd2843e167a sp 00007ffde588e748 error 5 in libc.so[7fd28439c000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.893504] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.895068] ipset[4748]: segfault at ffffffff8a2b5f6b ip 00007efe66dc867a sp 00007ffc8a2b3d58 error 5 in libc.so[7efe66d83000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.895675] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.897726] ipset[4749]: segfault at ffffffff9ff8ff63 ip 00007f9958c0e67a sp 00007ffe9ff8f4f8 error 5 in libc.so[7f9958bc9000+55000] likely on CPU 1 (core 0, socket 2)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.898336] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.900171] ipset[4750]: segfault at ffffffffbcbedf63 ip 00007f785c03267a sp 00007fffbcbed1f8 error 5 in libc.so[7f785bfed000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.900785] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.902599] ipset[4751]: segfault at fffffffffabf5f71 ip 00007f0cf223d67a sp 00007ffffabf56d8 error 5 in libc.so[7f0cf21f8000+55000] likely on CPU 2 (core 0, socket 4)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.903222] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.904738] ipset[4752]: segfault at fffffffff0a28f6f ip 00007f08eaf8067a sp 00007ffff0a28118 error 5 in libc.so[7f08eaf3b000+55000] likely on CPU 2 (core 0, socket 4)
Fri Sep 13 23:25:33 2024 kern.info kernel: [   22.905339] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
`


我也遇到了，esxi环境，我后来启动时候，趁passwall延迟30秒启动，把开关关掉了。

**Comment by lwb1978** [comment]
你们使用的openwrt是什么版本的？从上面的日志看ipset有内存泄露的情况。

**Comment by guochan2019** [comment]
> 你们使用的openwrt是什么版本的？从上面的日志看ipset有内存泄露的情况。
我跑的代码好象跟楼上兄弟的还不太一样，不过我看只了一部分就关机了，也不确定，我的op是今早自编译的lede 6.6.50，而且我恢复的是11号编译的版本，没有此问题，所以有理由怀疑是今天的更新

**Comment by lwb1978** [comment]
在网上查资料有提到虚拟机中ipset有缺陷，具体我无法证实，先把这个提交Revert吧，Revert后大家有条件再编译测试一下是否虚拟机还报错。

**Comment by smdx** [comment]
在PVE遇到相同问题，昨天早上编译的版本更新后在pve查看资源占用异常，然后拨号后网内不能正常上网在passwall测试网络却是正常的。lean openwrt最新源码r6847-2c01ece84

**Comment by lwb1978** [comment]
应该跟lede切换到gcc12后有关，详见：https://github.com/coolsnowwolf/lede/issues/12461

**Comment by smdx** [comment]
好的，那只能降gcc版本使用了。谢谢告知

**Comment by lwb1978** [comment]
> 好的，那只能降gcc版本使用了。谢谢告知

或者拉取openwrt官方源最新的ipset试试：https://github.com/openwrt/openwrt/tree/main/package/network/utils/ipset

**Comment by smdx** [comment]
> > 好的，那只能降gcc版本使用了。谢谢告知
> 
> 或者拉取openwrt官方源最新的ipset试试：https://github.com/openwrt/openwrt/tree/main/package/network/utils/ipset

好的，谢谢

**Comment by lanruihua026** [comment]
我也是发现只要开passwall cpu风扇就狂转，温度飙升到75°，小主机是n6000，直接物理安装openwrt，基于lean源码编译，只要关掉passwall cpu占用率立刻下降，温度也下降

**Comment by lwb1978** [comment]
> 我也是发现只要开passwall cpu风扇就狂转，温度飙升到75°，小主机是n6000，直接物理安装openwrt，基于lean源码编译，只要关掉passwall cpu占用率立刻下降，温度也下降

如果你也是这两天编译的lede和passwall，也是报ipset错误，就按照楼上的方法重新编译lede，如果不是就自行从系统方面解决，比如更换系统，排除插件冲突。

**Comment by guochan2019** [comment]
> > 好的，那只能降gcc版本使用了。谢谢告知
> 
> 或者拉取openwrt官方源最新的ipset试试：https://github.com/openwrt/openwrt/tree/main/package/network/utils/ipset

lean那边提交了新更新，刚编译新固件，目前已经正常，谢谢大佬，此帖关闭

**Comment by lwb1978** [comment]
> > > 好的，那只能降gcc版本使用了。谢谢告知
> > 
> > 
> > 或者拉取openwrt官方源最新的ipset试试：https://github.com/openwrt/openwrt/tree/main/package/network/utils/ipset
> 
> lean那边提交了新更新，刚编译新固件，目前已经正常，谢谢大佬，此帖关闭

这次lede处理得还算快，毕竟他们自家的ssrp也用不了。
