### ISSUE TITLE
[Bug]: /usr/lib/lua/luci/passwall/util_sing-box.lua 文件TUIC出错。

### ISSUE THREAD

**Issue by shan869** [xiaorouji/openwrt-package#3403]
### 描述您遇到的bug

服务端开启TUIC，JSON会报错UUID为列表，出错。
关于TUIC协议部分，正确的代码为：if node.protocol == "tuic" then
	if node.uuid then
		local users = {}
		for i = 1, #node.uuid do
			users[i] = {
				name = node.uuid[i],
				uuid = node.uuid[i],
				password = node.password
			}
		end
		tls.alpn = (node.tuic_alpn and node.tuic_alpn ~= "") and {
			node.tuic_alpn
		} or nil
		protocol_table = {
			users = users,
			congestion_control = node.tuic_congestion_control or "cubic",
			zero_rtt_handshake = (node.tuic_zero_rtt_handshake == "1") and true or false,
			heartbeat = node.tuic_heartbeat .. "s",
			tls = tls
		}
	end
end

### 复现此Bug的步骤

服务端，注意时服务端！！！打开SINGBOX ，选择TUIC  保存配置时就会报错。估计没人用，所以没发现。

### 您想要实现的目的

修改BUG

### 日志信息

修改BUG

### 系统相关信息

最新的HY2.51版本

**Comment by shan869** [comment]
[31mFATAL[0m[0000] decode config at /tmp/etc/passwall_server/01554d77372646f78bcb702e75d4b22f.json: inbounds[0].users[0].uuid: json: cannot unmarshal array into Go value of type string  日志报错信息。

**Comment by lwb1978** [comment]
楼主能否直接提交个PR上来？

**Comment by shan869** [comment]
> 楼主能否直接提交个PR上来？

抱歉 我不是很懂GITHUB的操作。麻烦大神您了。我的代码也是CHATGPT写的，试过是对的。

**Comment by lwb1978** [comment]
好的，感谢反馈，我得空修复一下代码。
