### ISSUE TITLE
[Feature Request]: UDP noises

### ISSUE THREAD

**Issue by Graveyard9988** [xiaorouji/openwrt-package#3404]
### 描述你想要的新功能

details:
https://xtls.github.io/config/outbounds/freedom.html
https://github.com/XTLS/Xray-core/pull/3711
https://github.com/XTLS/Xray-core/pull/3794#issuecomment-2351329251

### 描述你想要的解决方案

.

**Comment by lwb1978** [comment]
Adaptation completed, please test.
