### ISSUE TITLE
X-ray负载均衡请求功能

### ISSUE THREAD

**Issue by hm-Private** [xiaorouji/openwrt-package#3408]
### 描述你想要的新功能

就是能不能在添加节点的地方可以利用关键词添加，不然有时候机场节点没了都不知道，后备节点也希望通过关键词多点，这样用xray 负载均衡就省心多了

### 描述你想要的解决方案

Xray 负载均衡可以通过节点关键词自动添加，而不需要手动去添加
![IMG_2571](https://github.com/user-attachments/assets/81e7b954-314a-4217-a5b9-ef66e20bef55)

**Comment by hm-Private** [comment]
跪求此功能，大佬😂

**Comment by Nicepaul** [comment]
+1
