### ISSUE TITLE
[Bug]: 访问控制失败，限制ip也能出国

### ISSUE THREAD

**Issue by Nicepaul** [xiaorouji/openwrt-package#3412]
### 描述您遇到的bug

之前访问控制IP限制出国是没问题的，最新编译访问控制失效

### 复现此Bug的步骤

无

### 您想要实现的目的

访问控制功能恢复

### 日志信息

无

### 截图

<img width="535" alt="iShot_2024-09-25_07 36 49" src="https://github.com/user-attachments/assets/a72460eb-df41-4bdd-9c02-b1dc84ffda62">
<img width="421" alt="iShot_2024-09-25_07 32 03" src="https://github.com/user-attachments/assets/d4d98907-279d-434c-b209-74cb68487cf5">
<img width="727" alt="iShot_2024-09-25_07 31 35" src="https://github.com/user-attachments/assets/63cfde20-027d-4d7d-9ce4-f87f01621b14">

### 系统相关信息

Lean x64 openwrt
自行编译的passwall  4.78-2
chrome Version 129.0.6668.60 (Official Build) (x86_64)

**Comment by redfrog999** [comment]
确实有问题，不打开客户端访问，代理全不生效，即使设定了访问控制也是如此。如果开启客户端访问，受限制的设备还是可以代理访问。期待开发大佬修复。谢谢。

**Comment by lwb1978** [comment]
经在ImmortalWrt 23.05 FW4 的 nftables 及 iptables 下测试，访问控制没有问题。

**Comment by redfrog999** [comment]
> 经在ImmortalWrt 23.05 FW4 的 nftables 及 iptables 下测试，访问控制没有问题。

好啦，我的已经搞定，PSW本身没问题，我换新的固件没有重新配置，用的旧配置就会出问题。现在删掉原来的访问控制内容，重新设定一次就好了。有这个问题的不妨试试这个办法。

**Comment by mirthlesslk** [comment]
> > 经在ImmortalWrt 23.05 FW4的nftables及iptables下测试，访问控制没有问题。
> 
> 好啦，我的已经没搞定了，PSW本身问题，我换新的固件没有重新配置，用的旧配置就会出问题。现在删掉原来的访问控制内容，重新设置一次就好了。有这个问题的旋转方法。

原来是这样，我说之前怎么不太对劲，那如果保留配置刷入固件岂不是每次都要重新设置一遍？

**Comment by SakuraFallingMad** [comment]
> > > 经在ImmortalWrt 23.05 FW4的nftables及iptables下测试，访问控制没有问题。
> > 
> > 
> > 好啦，我的已经没搞定了，PSW本身问题，我换新的固件没有重新配置，用的旧配置就会出问题。现在删掉原来的访问控制内容，重新设置一次就好了。有这个问题的旋转方法。
> 
> 原来是这样，我说之前怎么不太对劲，那如果保留配置刷入固件岂不是每次都要重新设置一遍？

应该更新的时候涉及的哪个地方，那里需要重新配置比较保险

**Comment by Nicepaul** [comment]
或者给个配置导出导入功能，每次升级，配置导出再导入一次，是不是就可以避免很多潜在的异常

**Comment by Nicepaul** [comment]
经测试，删除配置再重新添加，还是有一点问题：比如限制IP出国的手机上，tiktok还是能看直播，但是刷到的其他视频是定格的。之前限制好了是完全刷不到视频的，只有黑屏。

**Comment by redfrog999** [comment]
> 经测试，删除配置再重新添加，还是有一点问题：比如限制IP出国的手机上，tiktok还是能看直播，但是刷到的其他视频是定格的。之前限制好了是完全刷不到视频的，只有黑屏。

我这里用的是2203固件，重新设定后，按照手机MAC地址限制，海外APP没有能用的，海外网站除非直连能上否则一定啥页面都没有。PSW没有啥问题呢。
