### ISSUE TITLE
[Bug]: 规则列表失效 域名写到直连继续走代理

### ISSUE THREAD

**Issue by pover0k** [xiaorouji/openwrt-package#3415]
### 描述您遇到的bug

将域名gspe1-ssl.ls.apple.com放到直连列表 查看日志发现依然走代理

### 复现此Bug的步骤

DNS-通过TCP请求dns 8.8.8.8 启用chinadns-ng
规则列表-直连列表填入gspe1-ssl.ls.apple.com

### 您想要实现的目的

修复规则列表直连域名走代理bug

### 日志信息

2024/09/27 06:26:08 [Info] [3467381728] proxy/dokodemo: received request for 192.168.2.121:65396
2024/09/27 06:26:08 [Info] [3467381728] app/dispatcher: sniffed domain: gspe1-ssl.ls.apple.com
2024/09/27 06:26:08 [Info] [3467381728] app/dispatcher: default route for tcp:gspe1-ssl.ls.apple.com:443
2024/09/27 06:26:08 [Info] [3467381728] transport/internet/tcp: dialing TCP to tcp:代理IP:443
2024/09/27 06:26:08 from 192.168.2.121:65396 accepted tcp:23.49.104.42:443 [tcp_redir >> O8PiLPPY]
2024/09/27 06:26:09 [Info] [3467381728] proxy/vless/outbound: tunneling request to tcp:gspe1-ssl.ls.apple.com:443 via 代理IP:443

### 截图

![image](https://github.com/user-attachments/assets/f6194e73-4eb1-4ece-894c-8192d5353979)

### 系统相关信息

passwall版本：4.78-2
iPadOS safari版本：18.0

**Comment by pover0k** [comment]
截图是旧版本的 新版本我测试过一样的问题

**Comment by bjzhili** [comment]
我也遇到同样的问题，请问你解决了吗？我的emby DDNS解析的也是节点地址，embydens使用的是这个域名www.ipify.org获取embyServerIP地址我已将 api64.ipify.org，api.ipify.org，ipify.org，www.ipify.org都加入了直连列表，还是走的代理。不知道是不是和节点类型有关系我用的是xray vless。反之我将ip138.com 加入代理列表，依然获取的是我的真实ip地址。
