### ISSUE TITLE
[Bug]: passwall服务器端 配置连接后 客户端访问国内国外站点全走国外dns解析

### ISSUE THREAD

**Issue by Mousehk** [xiaorouji/openwrt-package#3416]
### 描述您遇到的bug

![1727436996559](https://github.com/user-attachments/assets/f259fc0a-1db3-496e-ab6f-b90a81e1a346)

### 复现此Bug的步骤

![1727436919022](https://github.com/user-attachments/assets/43ed375c-16c6-492c-992a-fe98c1bcba16)

### 您想要实现的目的

可不可以指定dns解析ip防止客户端连接后因国外dns造成部分软件无法正常使用

### 日志信息

Xray 24.9.19 (Xray, Penetrates Everything.) bc28cad (go1.23.1 linux/arm64)
A unified platform for anti-censorship.
2024/09/27 19:15:13 [Info] infra/conf/serial: Reading config: &{Name:/tmp/etc/passwall_server/dc389d2b0d544989a1c28159b16a42c6.json Format:json}
2024/09/27 19:15:13 [Warning] core: Xray 24.9.19 started
2024/09/27 19:19:57 from 153.36.134.200:16110 accepted tcp:157.148.54.28:80 [direct]
2024/09/27 19:19:57 from 153.36.134.200:16111 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:57 from 153.36.134.200:16112 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16113 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16114 accepted tcp:114.247.154.5:443 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16115 accepted udp:1.1.1.1:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16116 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16118 accepted tcp:114.247.154.4:443 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16119 accepted tcp:122.193.7.205:14000 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16121 accepted udp:58.240.57.33:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16340 accepted udp:58.240.57.33:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16117 accepted tcp:dns.google:443 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16120 accepted udp:58.240.57.33:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16339 accepted udp:58.240.57.33:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16343 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16344 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16341 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16342 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16345 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:58 from 153.36.134.200:16346 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16347 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16349 accepted tcp:dns.google:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16348 accepted tcp:dns.google:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16350 accepted tcp:dns.google:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16352 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16353 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16351 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16354 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16355 accepted tcp:dns.google:443 [direct]
2024/09/27 19:19:59 from 153.36.134.200:16356 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:00 from 153.36.134.200:16357 accepted tcp:dns.google:443 [direct]
2024/09/27 19:20:00 from 153.36.134.200:16358 accepted tcp:dns.google:443 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11110 accepted tcp:112.65.193.154:443 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11114 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11111 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11113 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11112 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11115 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:00 from 153.36.134.200:11116 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11117 accepted udp:157.240.196.15:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11122 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11123 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11126 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11124 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11119 accepted tcp:content-autofill.googleapis.com:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11121 accepted tcp:content-autofill.googleapis.com:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11129 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11120 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11128 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11125 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11127 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:01 from 153.36.134.200:11118 accepted tcp:requality.android.shouji.sogou.com:80 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11130 accepted tcp:h.trace.qq.com:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11348 accepted udp:157.240.196.15:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11350 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11351 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:01 from 153.36.134.200:11349 accepted tcp:optimizationguide-pa.googleapis.com:443 [direct]
2024/09/27 19:20:02 from 153.36.134.200:11352 accepted udp:157.240.196.15:443 [direct]
2024/09/27 19:20:02 from 153.36.134.200:11353 accepted tcp:mtalk.google.com:5228 [direct]
2024/09/27 19:20:03 from 153.36.134.200:16359 accepted udp:157.240.196.15:443 [direct]
2024/09/27 19:20:03 from 153.36.134.200:16360 accepted tcp:cmgate.vip.qq.com:443 [direct]
2024/09/27 19:20:03 from 153.36.134.200:16361 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:03 from 153.36.134.200:16362 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:03 from 153.36.134.200:16363 accepted udp:8.8.4.4:443 [direct]
2024/09/27 19:20:04 from 153.36.134.200:16364 accepted tcp:readaloud.googleapis.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16590 accepted udp:157.240.196.15:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16368 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16367 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16369 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16365 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16591 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16366 accepted tcp:encrypted-tbn3.gstatic.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16588 accepted tcp:www.google.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16587 accepted tcp:www.google.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16589 accepted tcp:www.google.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16595 rejected proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2024/09/27 19:20:05 from 153.36.134.200:16594 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16596 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16593 accepted tcp:static.xx.fbcdn.net:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16592 accepted tcp:static.xx.fbcdn.net:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16598 accepted tcp:www.baidu.com:443 [direct]
2024/09/27 19:20:05 from 153.36.134.200:16597 accepted tcp:www.baidu.com:443 [direct]
2024/09/27 19:20:06 from 153.36.134.200:16599 accepted tcp:150.109.29.169:8081 [direct]
2024/09/27 19:20:06 from 153.36.134.200:16600 accepted tcp:ms.bdstatic.com:443 [direct]
2024/09/27 19:20:08 from 153.36.134.200:16601 accepted tcp:157.255.6.252:8002 [direct]
2024/09/27 19:20:09 from 153.36.134.200:16602 accepted tcp:169.47.71.232:8000 [direct]
2024/09/27 19:20:09 from 153.36.134.200:11354 accepted tcp:3gimg.qq.com:80 [direct]
2024/09/27 19:20:10 from 153.36.134.200:11355 accepted tcp:3gimg.qq.com:80 [direct]
2024/09/27 19:20:10 from 153.36.134.200:11356 accepted tcp:3gimg.qq.com:443 [direct]
2024/09/27 19:20:11 from 153.36.134.200:11357 accepted tcp:hpd.baidu.com:443 [direct]
2024/09/27 19:20:11 from 153.36.134.200:11358 accepted tcp:t11.baidu.com:443 [direct]
2024/09/27 19:20:11 from 153.36.134.200:11359 accepted tcp:hectorstatic.baidu.com:443 [direct]
2024/09/27 19:20:14 from 153.36.134.200:11360 accepted tcp:short.weixin.qq.com:80 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16603 accepted tcp:m.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16604 accepted tcp:m.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16605 accepted tcp:m.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16606 accepted tcp:hm.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16607 accepted tcp:feed.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16608 accepted tcp:h2tcbox.baidu.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16609 accepted tcp:s.bdstatic.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16610 accepted tcp:sv.bdstatic.com:443 [direct]
2024/09/27 19:20:16 from 153.36.134.200:16611 accepted tcp:s.bdstatic.com:443 [direct]
2024/09/27 19:20:19 from 153.36.134.200:16612 accepted tcp:140.143.89.242:8000 [direct]
2024/09/27 19:20:20 from 153.36.134.200:16613 accepted tcp:hpd.baidu.com:443 [direct]
2024/09/27 19:20:21 from 153.36.134.200:16616 accepted tcp:ext.baidu.com:443 [direct]
2024/09/27 19:20:21 from 153.36.134.200:16614 accepted tcp:ext.baidu.com:443 [direct]
2024/09/27 19:20:21 from 153.36.134.200:16615 accepted tcp:ext.baidu.com:443 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11361 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11362 accepted tcp:59.82.120.213:80 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11363 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11364 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11366 accepted udp:8.8.4.4:53 [direct]
2024/09/27 19:20:24 from 153.36.134.200:11365 accepted udp:8.8.4.4:53 [direct]

### 系统相关信息

passwall最新版本

**Comment by lwb1978** [comment]
dns解析是客户端的事，跟服务端无关

**Comment by Mousehk** [comment]
问题:内网下设备国内国外dns能正常分流，用服务端配置连接的设备只能走国外dns无法正常分流，导致一直app不能使用。大佬有没有思路可以让客户端设备指定dns地址或者分流的
