### ISSUE TITLE
[Bug]: 节点列表无法显示

### ISSUE THREAD

**Issue by ted-zheng** [xiaorouji/openwrt-package#3422]
### 描述您遇到的bug

节点列表无法正常显示

### 复现此Bug的步骤

节点列表选项卡显示如上信息，无法显示节点信息。

### 您想要实现的目的

修复bug

### 日志信息

Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/template.lua:181: Failed to execute template 'cbi/map'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:181: Failed to execute template 'cbi/tblsection'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:181: Failed to execute template 'cbi/dvalue'.
A runtime error occurred: ...lib/lua/luci/model/cbi/passwall/client/node_list.lua:122: attempt to index local 'protocol' (a nil value)
stack traceback:
...lib/lua/luci/model/cbi/passwall/client/node_list.lua:122: in function 'cfgvalue'
[string "/usr/lib/lua/luci/view/cbi/dvalue.htm"]:2: in main chunk
stack traceback:
[C]: in function 'error'
/usr/lib/lua/luci/template.lua:181: in function
(tail call): ?
/usr/lib/lua/luci/cbi.lua:257: in function 'render'
/usr/lib/lua/luci/cbi.lua:1473: in function 'render'
[string "/usr/lib/lua/luci/view/cbi/tblsection.htm"]:128: in main chunk
stack traceback:
[C]: in function 'error'
/usr/lib/lua/luci/template.lua:181: in function
(tail call): ?
/usr/lib/lua/luci/cbi.lua:257: in function 'render'
/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
[string "/usr/lib/lua/luci/view/cbi/map.htm"]:6: in main chunk

In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:1003:48)
  called from anonymous function (/www/cgi-bin/luci:39:13)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^

### 系统相关信息

Passwall版本：4.78-2,Google Chrome 版本 129.0.6668.89（正式版本）（64 位）

**Comment by lwb1978** [comment]
请自行检查系统，并确认你的pw是在本仓库拉取且没有修改过的？
你所提的这个属于最基础的功能，不可能存在错误。

**Comment by x2x4com** [comment]
<img width="1982" height="1440" alt="Image" src="https://github.com/user-attachments/assets/3ac34fca-19e5-43a2-ae24-9bdafc75b4bc" />

没有任何修改，直接ipk安装的，官网，某天忽然就这样了

**Comment by x2x4com** [comment]
OrigVersion: 25.6.x beta 
Fix: ipk update to 25.11.27-r1
