### ISSUE TITLE
[Feature Request]: 使用节点失效后自动更新订阅 | 订阅更新不影响当前有效节点

### ISSUE THREAD

**Issue by rockbenben** [xiaorouji/openwrt-package#3432]
### 描述你想要的新功能

近期 JustMySocks 节点每天都会失效，使用域名节点需要等待 DNS 更新，而使用 IP 节点则需要及时更新订阅。对于我们来说，更新 IP 节点信息可能是最简单的方法。

#### 失效后自动更新订阅

目前，Passwall 的节点订阅是通过定时或循环的方式进行的，但每天节点失效的时间并不固定。能否在 Passwall 上添加一个选项，当节点失效时，可以自动更新订阅。

#### 订阅更新后不重启

如果上一个方案无法实现，可以增加订阅循环的频率，使订阅更新不会影响正常使用的节点服务。

例如，将更新频率设置为每 5 分钟一次。但在当前节点有效的情况下，更新订阅后并不会立即生效，而是仅更新非使用中的节点信息。在节点切换后，才会使用新的订阅信息。

### 描述你想要的解决方案

1. 当前使用的节点失效后，自动更新订阅。
2. 缩短订阅更新频率（如每 5 分钟一次）。更新订阅后，不会影响当前使用的有效节点，而是仅更新非使用中的节点信息（不重启passwall）。这样，当当前节点失效后，将自动切换到新订阅的节点，同时之前失效的节点信息也会在此时得到更新。

**Comment by lwb1978** [comment]
这种情况你应该考虑更换一个机场，而不是要求一个免费软件去迎合它的不稳定，而且这并不是普遍的需求，开发难度不小，跟定制差不多了。

**Comment by rockbenben** [comment]
嗯，准备换了。之前几年一直很稳，最近半个月天天要换。谢谢！

**Comment by zzj6116** [comment]
> 嗯，准备换了。之前几年一直很稳，最近半个月天天要换。谢谢！

我的 JustMySocks连续五年了都好好的，最近一个多月也是每天都失效，需要手动清空所有节点，然后手动订阅才能更新出来新节点，不清空已经失效的节点的话，不能成功订阅新的节点，换了好几个插件都是这样。目前没有找到很好的办法。
