### ISSUE TITLE
[Bug]: 4.78-3 ChinaDNS-ng 不定期崩溃

### ISSUE THREAD

**Issue by azhuge233** [xiaorouji/openwrt-package#3433]
### 描述您遇到的bug

ChinaDNS-ng 不定期出现问题，表现为：

- 设备无法打开网站（直连 IP 似乎不受影响）
- 查看系统日志，有输出
  `kern.info kernel: [527898.271762] chinadns-ng[4417]: segfault at xxxxxxxx ip xxxxxxx sp xxxxxx error 4 in chinadns-ng[216000+77000] likely on CPU x (core x, socket 0)`
  `kern.info kernel: [527898.287145] Code: xx xx xx xx ...`
- 内核日志也有与系统日志相同的输出

出现问题后，重新在 Passwall 主界面点击保存并应用后可以恢复正常，但仍会不定期出现相同问题
ChinaDNS-ng 更换过同版本下的 x86_64_v2，也会出错

现在只能将 ChinaDNS-ng 退回 2024.07.21 版本，退回后正常

### 复现此Bug的步骤

因为是不定期出现问题，不清楚触发条件

### 您想要实现的目的

Passwall 稳定运行

### 日志信息

系统日志
```
...
Fri Oct 11 13:14:53 2024 daemon.warn miniupnpd[7329]: upnp_event_process_notify: connect(192.168.16.40:2869): Operation timed out
Fri Oct 11 13:14:53 2024 daemon.warn miniupnpd[7329]: upnp_event_process_notify: connect(192.168.16.40:2869): Operation timed out
Fri Oct 11 13:20:13 2024 kern.info kernel: [527898.271762] chinadns-ng[4417]: segfault at 7f8e35ddc050 ip 00000000002307cd sp 00007fff388857b0 error 4 in chinadns-ng[216000+77000] likely on CPU 1 (core 1, socket 0)
Fri Oct 11 13:20:13 2024 kern.info kernel: [527898.287145] Code: 89 5c 24 50 0f b7 0d 06 c2 fd ff 66 89 4c 24 54 41 89 c5 66 89 44 24 52 48 8d 84 24 1a 01 00 00 48 89 44 24 40 48 8b 44 24 08 <48> 8b 40 10 48 89 44 24 48 83 3d 13 e2 05 00 00 0f 84 80 01 00 00
Fri Oct 11 13:27:02 2024 cron.err crond[15595]: crond (busybox 1.36.0) started, log level 5
Fri Oct 11 13:27:05 2024 cron.err crond[19058]: crond (busybox 1.36.0) started, log level 5
...
```

内核日志
```
...
[527898.271762] chinadns-ng[4417]: segfault at 7f8e35ddc050 ip 00000000002307cd sp 00007fff388857b0 error 4 in chinadns-ng[216000+77000] likely on CPU 1 (core 1, socket 0)
[527898.287145] Code: 89 5c 24 50 0f b7 0d 06 c2 fd ff 66 89 4c 24 54 41 89 c5 66 89 44 24 52 48 8d 84 24 1a 01 00 00 48 89 44 24 40 48 8b 44 24 08 <48> 8b 40 10 48 89 44 24 48 83 3d 13 e2 05 00 00 0f 84 80 01 00 00
...
```

### 截图

DNS 设置
<img width="576" alt="Snipaste_2024-10-11_13-48-55" src="https://github.com/user-attachments/assets/e8610e33-041e-49e3-a835-8b8bacb91672">

组件版本（ChinaDNS-ng 已经退回上个版本）
<img width="306" alt="Snipaste_2024-10-11_13-49-38" src="https://github.com/user-attachments/assets/0fd8e686-352c-4ffc-bd59-3f19b6a6b3ea">

系统日志
<img width="916" alt="Snipaste_2024-10-11_13-54-48" src="https://github.com/user-attachments/assets/f1218dce-5f24-4d37-b889-d165a1ed546e">

内核日志
<img width="916" alt="Snipaste_2024-10-11_13-55-01" src="https://github.com/user-attachments/assets/1323731a-6a0a-44fa-af2a-640957de5dfe">

### 系统相关信息

Passwall 信息
- Passwall 版本：4.78-3
- ChinaDNS-NG 版本：2024.09.08 wolf-ssl
- Xray 版本：24.9.30

系统信息
- Openwrt：`Linux OpenWrt 6.1.73 #0 SMP PREEMPT_DYNAMIC Thu Jan 18 09:40:58 2024 x86_64 GNU/Linux`
- CPU：J4125
- 内存：4GB

### 其他信息

之前在 Passwall 4.78-2 版本的时候就将 ChinaDNS-ng 升到过 2024.09.08，那时就会发生上述问题，也是重新启动 Passwall 恢复，但还是会不定时出问题
之前几个版本都没有出现过类似问题

**Comment by lwb1978** [comment]
chinadns的问题请到该项目反馈，这个不是pw开发的
