### ISSUE TITLE
[Bug]: 最近的版本开cn的域名用了代理

### ISSUE THREAD

**Issue by xh0823** [xiaorouji/openwrt-package#3437]
### 描述您遇到的bug

最近的版本开cn的域名用了代理，无论是防火墙还是中国列表以外都一样

### 复现此Bug的步骤

最近的版本开cn的域名用了代理，无论是防火墙还是中国列表以外都一样

### 您想要实现的目的

开cn的域名可以正常使用

### 日志信息

最近的版本开cn的域名用了代理，无论是防火墙还是中国列表以外都一样

### 截图

![屏幕截图 2024-10-13 103130](https://github.com/user-attachments/assets/a746303f-32bf-45a5-a10b-2a395cdaa106)

### 系统相关信息

Passwall 版本
【 4.78-3 】 
ChinaDNS-NG 版本
【 2024.09.08 】 
Sing-Box 版本
【 1.9.7 】 
Xray 版本
【 24.9.30 】

**Comment by quanljh** [comment]
并没有，如果你仔细看log 就会发现这个cn的测试网站实际上是用的
ipv4.lookup.test-ipv6.com
ipv6.lookup.test-ipv6.com
去查你的地址的。如果你吧这两个加到直连列表你会发现结果会变成你的国内地址

**Comment by xh0823** [comment]
哦 谢谢大佬的解惑，还有一个问题现在的分片功能不能用了，同一个被墙的节点用手机可以，

**Comment by quanljh** [comment]
分片我没用过，你可以关掉这个issue，然后开一个新的带上log 问下
