### ISSUE TITLE
[Feature Request]: 希望能自定义tproxy的目的地址

### ISSUE THREAD

**Issue by BGzEroll** [xiaorouji/openwrt-package#3440]
### 描述你想要的新功能

最近我一直在主路由上通过passwall将非大陆ip的流量筛选出来，再通过socks转发到局域网上的n100主机上，这样每当有新协议或者更新时我便不需要再去折腾主路由。
但上述方法始终都要经过core，对于单纯的流量转发来说性能上的开销还是有点大，所有希望**能够利用tproxy直接将流量转发到局域网内的其他服务器上**

### 描述你想要的解决方案

能够利用tproxy直接将流量转发到局域网内的其他服务器上

### 其他信息

我曾利用[该项目](https://github.com/padavanonly/luci-app-mwan3helper-chinaroute)的思路对passwall进行改造过，但由于能力有限，不知流量卡在哪一步了，并未达成预期效果。

**Comment by BGzEroll** [comment]
这几天再次尝试魔改了下passwall，将nftables.sh中的
```
REDIRECT() {
	local s="counter redirect"
	[ -n "$1" ] && {
		local s="$s to :$1"
		[ "$2" == "MARK" ] && s="counter meta mark set $1"
		[ "$2" == "TPROXY" ] && {
			s="counter meta mark 1 tproxy to :$1"
		}
		[ "$2" == "TPROXY4" ] && {
			s="counter meta mark 1 tproxy ip to :$1"
		}
		[ "$2" == "TPROXY6" ] && {
			s="counter meta mark 1 tproxy ip6 to :$1"
		}

	}
	echo $s
}
```

改为了
```
REDIRECT() {
	local s="counter redirect"
	[ -n "$1" ] && {
		local s="$s to :$1"
		[ "$2" == "MARK" ] && s="counter meta mark set $1"
		[ "$2" == "TPROXY" ] && {
			s="counter meta mark 1 return"
		}
		[ "$2" == "TPROXY4" ] && {
			s="counter meta mark 1 return"
		}
		[ "$2" == "TPROXY6" ] && {
			s="counter meta mark 1 return"
		}

	}
	echo $s
}
```
并配合策略路由(IPv6同理)
```
ip route add default via 192.168.191.98 dev br-lan table 100
ip -6 route add default via fd00::114:514 dev br-lan table 100
```
成功达成了初步的预期效果，7981上可以通过硬件加速将需要代理的流量转发到n100上，且cpu占用率为0，但前提是**对mark为1的流量进行MASQUERADE**。我摸索了几天都无法摆脱srcnat，一但不对mark为1的流量进行srcnat，n100那边的xray core便不会接受到请求，这一点我也不知道究竟是为何

而开启MASQUERADE会使被代理的流量出现两点问题：
1. UDP行为异常
2. 多了一层nat（虽然这个对TCP来说不是特别重要）

tproxy方面估计也不太能直接将流量转发到非本机ip，关于流量转发方面的疑问不知有无大佬救救（

**Comment by solarflows** [comment]
天才，我也有想法不过只是想法，这方面了解很少，当年在mt7621上用mwan3玩过一次，无奈7621性能孱弱，放弃了。其实我感觉这个功能可以不要passwall，或者说直接将流量转发独立成一个插件，这样子搭配硬路由搭配Linux主机美滋滋。

**Comment by BGzEroll** [comment]
> 天才，我也有想法不过只是想法，这方面了解很少，当年在mt7621上用mwan3玩过一次，无奈7621性能孱弱，放弃了。其实我感觉这个功能可以不要passwall，或者说直接将流量转发独立成一个插件，这样子搭配硬路由搭配Linux主机美滋滋。

若是能在psswall上实现的话就最好了，毕竟passwall的访问控制和dns解析模式是真的好用

**Comment by woni928** [comment]
支持一下，希望大佬们出个解决方案！
