### ISSUE TITLE
[Bug]: Hysteria2无法使用Sing-Box启动

### ISSUE THREAD

**Issue by kkqy** [xiaorouji/openwrt-package#3443]
### 描述您遇到的bug

我导入的Hysteria节点，类型选择Sing-box，协议选择Hysteria2，保存以后，能够通过URL测速出来延迟。
但是当我把它当作TCP和UDP节点使用的时候，就用不了了。
但如果类型直接选Hysteria2，是能正常使用的，我记得较早以前，我通过Sing-Box使用Hysteria2的节点是没问题的啊，最近的几次更新不支持了，必须使用原生的Hysteria2来使用Hysteria2节点？

但神奇的是，如果我不是直接使用这个Sing-Box HY2节点，而是使用XRay的分流节点，然后把Sing-Box HY2节点设置为XRay分流的默认节点，又能正常工作了！？

进一步发现，通过XRay分流节点使用Sing-Box HY2节点的时候，路由器进程里有sing-box的进程，而直接使用Sing-Box HY2节点，路由器里没有sing-box进程，难道是因为什么原因sing-box没启动起来，或者出错以后推出了？我看插件的日志，只输出了三行就没后续了，也没报错，是卡在什么地方了吗？

再一次尝试，把分流节点的类型从xray改为sing-box，也用不了了，进程列表里都没有sing-box进程。
也就是说sing-box节点只能在测速和作为xray的分流节点才能正常工作。

### 复现此Bug的步骤

1. 添加或者导入Hysteria2节点，类型不要选Hysteria2，而是选择singbox，协议选Hysteria2
2. 在节点列表对该节点进行URL测速，能测出来延迟
3. 使用此节点，打开“主开关”，访问不了谷歌，日志里出现三条记录，就没后续了，进程里也没有sing-box进程

### 您想要实现的目的

解决sing-box节点无法直接使用的问题。

### 日志信息

2024-10-16 11:40:31: 清空并关闭相关程序和缓存完成。
2024-10-16 11:40:31: TCP节点：[xxx.xxx.com]，监听端口：1041
2024-10-16 11:40:31: UDP节点：与TCP节点相同

正常情况下后面还应该有其它日志，但是使用 Sing-box 分流节点 或者 sing-box HY2 节点启动以后就只有这三条

### 系统相关信息

- Passwall版本：4.78-3
- Sing-Box版本： 1.10.0

**Comment by GongZi-666** [comment]
确实。用passwall里的singbox可以解析出机场的hy2节点，但是选择对应hy2节点后无法油管，tg可以收到消息。另外负载均衡自建节点后，无法添加到主页面或者说主页面无法识别到新建立的负载均衡的节点。

**Comment by apollogeek** [comment]
The same problem

**Comment by lwb1978** [comment]
我没有hy2的节点，无法测试，能否帮找一个免费的hy2节点用于测试。因为涉及敏感信息，请不要发自用的节点。

**Comment by kkqy** [comment]
> 我没有hy2的节点，无法测试，能否帮找一个免费的hy2节点用于测试。因为涉及敏感信息，请不要发自用的节点。

我暂时没找到免费节点，但是我感觉测试这个问题并不一定需要可用节点，编一个都可以，比如：
`hysteria2://test@8.8.8.8:888/?sni=www.google.com#www.google.com`
因为哪怕它实际连不上，但问题还没到“启动后”用不了那一步，而是启动的时候，日志都戛然而止，没有任何报错，sing-box也没有启动。

**Comment by lwb1978** [comment]
已修复

**Comment by kkqy** [comment]
> 已修复

更新以后又出现新的问题 https://github.com/xiaorouji/openwrt-passwall/issues/3464

**Comment by hgq5** [comment]
我的问题更奇怪，在PC上能TG，油管、IG、X都上不了，用passwall上的Google、GitHub、IG测试又有延迟显示，但是在平板上一切都正常

**Comment by Sun5Kong** [comment]
> 我的问题更奇怪，在PC上能TG，油管、IG、X都上不了，用passwall上的Google、GitHub、IG测试又有延迟显示，但是在平板上一切都正常

一样的情况。。。一直没有看到有人反馈，还以为我的个例呢。。。
我是只有在使用sing-box分流时会这样，换成xray分流就都正常了。。。
目前还没找到原因和解决方案。。。

**Comment by xkdvSrPD** [comment]
> > 我的问题更奇怪，在PC上能TG，油管、IG、X都上不了，用passwall上的Google、GitHub、IG测试又有延迟显示，但是在平板上一切都正常
> 
> 一样的情况。。。一直没有看到有人反馈，还以为我的个例呢。。。 我是只有在使用sing-box分流时会这样，换成xray分流就都正常了。。。 目前还没找到原因和解决方案。。。

same issue
