### ISSUE TITLE
[Bug]: 域名后缀匹配不生效

### ISSUE THREAD

**Issue by yakiisama** [xiaorouji/openwrt-package#3446]
### 描述您遇到的bug

直连列表里面写了  eg: *.abc.com  ， 但其实还是走了代理。是不支持这样的规则吗

### 复现此Bug的步骤

/

### 您想要实现的目的

/

### 日志信息

/

### 系统相关信息

4.78.1

**Comment by lwb1978** [comment]
鉴于DNSMASQ和ChinDNS-NG的限制，规则列表并不支持你写的这种格式，也不支持有*号的通配符域名。
比如要匹配域名*.abc.com，那么正确的写法是abc.com，会匹配所有以abc.com结尾的域名。
