### ISSUE TITLE
[Feature Request]: 为负载均衡节点探测添加超时时间选项

### ISSUE THREAD

**Issue by davidzhang12138** [xiaorouji/openwrt-package#3448]
### 描述你想要的新功能

希望在负载均衡节点的配置中，增加一个**“超时时间”**选项，允许用户在探测节点时设定一个最大响应时间（如200ms、500ms等）。如果节点的探测时间超过设定的超时时间，则判定该节点不可用。

### 描述你想要的解决方案

![image](https://github.com/user-attachments/assets/371bdb04-dabb-4c37-a281-e4931a192581)
在现有的配置上直接增加超时时间参数。

**Comment by lwb1978** [comment]
xray的leastPing策略好像并没有timeout的参数，如果xray本身不支持，pw可没办法自己造一个出来。
