### ISSUE TITLE
[Bug]: 更换sing-box后报错

### ISSUE THREAD

**Issue by alterem** [xiaorouji/openwrt-package#3449]
### 描述您遇到的bug

界面没有提示，显示TCP没有运行；
手动执行命令： /etc/init.d/passwall restart 提示报错：
/usr/share/passwall/app.sh: eval: line 271: syntax error: unexpected ";;"

### 复现此Bug的步骤

更换所有节点类型为sing-box
更换分流类型为sing-box
更换dns为sing-box

![image](https://github.com/user-attachments/assets/9d0dee71-3c7f-4395-8b04-e99995c5cf36)
![image](https://github.com/user-attachments/assets/7b78cce0-8703-4985-8080-49241be22b37)
![image](https://github.com/user-attachments/assets/2433d1f3-c184-435f-8a76-193f072f3f4e)

### 您想要实现的目的

更换X-ray为sing box

### 日志信息

无日志，手动执行命令： /etc/init.d/passwall restart 提示报错：
/usr/share/passwall/app.sh: eval: line 271: syntax error: unexpected ";;"

<img width="557" alt="image" src="https://github.com/user-attachments/assets/6c666654-8164-499d-b189-23ac54a8a8fa">

### 系统相关信息

![image](https://github.com/user-attachments/assets/7da1f7d5-fa71-4308-afeb-6725a13ea7cb)
![image](https://github.com/user-attachments/assets/4e0a293b-e02e-473d-a73b-013d2d388de8)

**Comment by lwb1978** [comment]
要使用sing-box分流，需要先手动下载好它的规则数据库上传到指定位置后再启动sing-box，正常运行后今后sing-box的规则它会自行更新，确认你是否已经下载了规则数据库。
另外不要手动运行/etc/init.d/passwall restart

**Comment by alterem** [comment]
> 要使用sing-box分流，需要先手动下载好它的规则数据库上传到指定位置后再启动sing-box，正常运行后今后sing-box的规则它会自行更新，确认你是否已经下载了规则数据库。

确定有对应的数据库文件， 页面的TCP、UDP、DNS的运行状态提示未运行

**Comment by lwb1978** [comment]
fix
