### ISSUE TITLE
[Bug]: OP最新官方源码，无法访问国外。

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-package#3450]
### 描述您遇到的bug

不知道OP官方又更新了个啥子，搞到现在编译出来，passswall的设置页面显示运行正常，日志也没显示出有问题，但是不论怎么设置远程DNS，都没有转发过去，引起无法访问国外。回退源码就正常使用。

### 复现此Bug的步骤

无论怎么设置远程DNS，页面的DNS也显示正常运行，实质是没有转发过去。

### 您想要实现的目的

正常运行访问国外

### 日志信息

。。。

### 系统相关信息

Passwall 版本【 4.78-3 】  ChinaDNS-NG 版本【 2024.10.14 】  Sing-Box 版本【 无 】  Xray 版本【 24.10.16 】  Hysteria 版本【 无 】

**Comment by xh0823** [comment]
官方更新了dnsmasq的几个功能，我的是防火墙模式开不了，用中国以外可以用但是dns泄露全部是电信的dns

**Comment by snakwu** [comment]
正好，我就是用防火墙模式😂

**Comment by catsimple** [comment]
https://github.com/xiaorouji/openwrt-passwall2/issues/677
回退dnsmasq，等修

**Comment by lwb1978** [comment]
这个情况得老大出山了
@xiaorouji

**Comment by snakwu** [comment]
@xiaorouji 呼叫大佬，over

**Comment by xh0823** [comment]
> 这个情况得老大出山了 @xiaorouji

既然是大佬出山可以把分片功能修复下吗，用workers搭建的节点用不了开了分片也不行，手机开分片了可以用

**Comment by ZqinKing** [comment]
/etc/ini.t/dnsmasq脚本修改了运行配置文件/var/etc/dnsmasq.conf.cfg01411c中临时配置目录导致。
临时解决方法：
将/etc/ini.t/dnsmasq文件中将“/tmp/dnsmasq${cfg:+.$cfg}.d”修改为“/tmp/dnsmasq.d”即可恢复正常。

**Comment by xh0823** [comment]
> /etc/ini.t/dnsmasq脚本修改了运行配置文件/var/etc/dnsmasq.conf.cfg01411c中临时配置目录导致。 临时解决方法： 将/etc/ini.t/dnsmasq文件中将“/tmp/dnsmasq${cfg:+.$cfg}.d”修改为“/tmp/dnsmasq.d”即可恢复正常。

感谢大佬，现在可以正常开防火墙模式了，但是dns还是泄露了

**Comment by ZqinKing** [comment]
> > /etc/ini.t/dnsmasq脚本修改了运行配置文件/var/etc/dnsmasq.conf.cfg01411c中临时配置目录导致。 临时解决方法： 将/etc/ini.t/dnsmasq文件中将“/tmp/dnsmasq${cfg:+.$cfg}.d”修改为“/tmp/dnsmasq.d”即可恢复正常。
> 
> 感谢大佬，现在可以正常开防火墙模式了，但是dns还是泄露了

DNS泄露是chainadns-ng导致的，智能模式就会泄露。

**Comment by SakuraFallingMad** [comment]
immortalwrt也跟进更新了，慢慢等大佬修复了。

**Comment by xh0823** [comment]
> > > /etc/ini.t/dnsmasq脚本修改了运行配置文件/var/etc/dnsmasq.conf.cfg01411c中临时配置目录导致。 临时解决方法： 将/etc/ini.t/dnsmasq文件中将“/tmp/dnsmasq${cfg:+.$cfg}.d”修改为“/tmp/dnsmasq.d”即可恢复正常。
> > 
> > 
> > 感谢大佬，现在可以正常开防火墙模式了，但是dns还是泄露了
> 
> DNS泄露是chainadns-ng导致的，智能模式就会泄露。
选择远程一样泄露，而且我现在怎么选择dnsmasq也会加载chainadns-ng

**Comment by lwb1978** [comment]
已经做了兼容适配，有条件的话请大家测试一下，如果没有问题将发布一个新版以应对。
