### ISSUE TITLE
[Bug]: 如何在高级设置中显示Xray 设置和Sing-Box 设置

### ISSUE THREAD

**Issue by neckyaan** [xiaorouji/openwrt-package#3454]
### 描述您遇到的bug

Passwall 版本	【 4.78-3 】全新安装后，在高级设置中显示Xray 设置和Sing-Box 设置下面为尚无任何配置，如图：
![捕获](https://github.com/user-attachments/assets/9c790cc0-6a7a-44f8-a512-fbc6b109dd7e)
![image](https://github.com/user-attachments/assets/20c3b2d3-3f9d-4d06-b93e-676982373a7d)

### 复现此Bug的步骤

全新安装后，在高级设置中显示Xray配置为尚无任何配置

### 您想要实现的目的

请教如何才能显示？如果需要配置xray，请问具体的文件路径？

### 日志信息

无

### 截图

![image](https://github.com/user-attachments/assets/a24b2e93-9a64-41b9-a757-b3c550023c05)

### 系统相关信息

Passwall 版本	【 4.78-3 】
 Chrome 
版本 130.0.6723.59（正式版本） （64 位）

**Comment by lwb1978** [comment]
请自行检查你的系统和安装过程，这并不是pw的问题，安装后可执行下面的链接恢复PW的默认配置试试：
http://路由器IP/cgi-bin/luci/admin/services/passwall/reset_config
