### ISSUE TITLE
[Bug]: 新版dnsmasq修改了临时配置目录，导致功能异常。

### ISSUE THREAD

**Issue by ZqinKing** [xiaorouji/openwrt-package#3455]
### 描述您遇到的bug

上游修改了dnsmasq的临时文件目录，不再是/tmp/dnsmasq.d了。导致功能失效
目前的dnsmasq配置如下：
cat /var/etc/dnsmasq.conf.cfg01411c
# auto-generated config file from /etc/config/dhcp
conf-file=/etc/dnsmasq.conf
dhcp-authoritative
domain-needed
localise-queries
read-ethers
enable-ubus=dnsmasq
expand-hosts
bind-dynamic
local-service
cache-size=1000
port=53
edns-packet-max=1232
domain=lan
local=/lan/
addn-hosts=/tmp/hosts
dhcp-leasefile=/tmp/dhcp.leases
resolv-file=/tmp/resolv.conf.d/resolv.conf.auto
stop-dns-rebind
rebind-localhost-ok
dhcp-broadcast=tag:needs-broadcast
conf-dir=/tmp/dnsmasq.cfg01411c.d
user=dnsmasq
group=dnsmasq

dhcp-ignore-names=tag:dhcp_bogus_hostname
conf-file=/usr/share/dnsmasq/dhcpbogushostname.conf

bogus-priv
conf-file=/usr/share/dnsmasq/rfc6761.conf
no-dhcp-interface=br-lan

### 复现此Bug的步骤

passwall功能失效，同时导致DNS异常，因为原本在/var/etc/dnsmasq.conf.cfg01411c中配置的转发，开启pw后会从/var/etc/dnsmasq.conf.cfg01411c中删除写入/tmp/dnsmasq.d/的临时dnsmasq-passwall.conf中，
然而新的dnsmasq已经不再使用/tmp/dnsmasq.d为临时目录。导致dnsmasq本身的转发功能都失效了。

### 您想要实现的目的

麻烦大佬适配一下新版本。

### 日志信息

源码中修改的文件为：./package/network/services/dnsmasq/files/dnsmasq.init

### 系统相关信息

pw版本：4.78-3

### 其他信息

dnsmasq更新了临时配置文件目录，导致与passwall不兼容，望修复适配。

**Comment by ppyohhh** [comment]
能有多少人更新dnsmasq  人家不可能为了新版dnsmasq重新弄个版本。

**Comment by ZqinKing** [comment]
> 能有多少人更新dnsmasq 人家不可能为了新版dnsmasq重新弄个版本。

大兄弟，这是主线更新引入的

**Comment by lwb1978** [comment]
已经做了兼容适配，有条件的话请大家测试一下，如果没有问题将发布一个新版以应对。
