### ISSUE TITLE
[Feature Request]: 请问我电脑的网关设置成openwrt之后, passwall是如何把数据包转发到代理的? 

### ISSUE THREAD

**Issue by tess1199** [xiaorouji/openwrt-package#3459]
### 描述你想要的新功能

请问我电脑的网关设置成openwrt之后, passwall是如何把数据包转发到代理的? 
是不是要tcp/udp分别转发呢? 需要什么软件和功能才能做到?
在ubuntu下可以用多种软件配合起到相同的作用吗???

### 描述你想要的解决方案

请问我电脑的网关设置成openwrt之后, passwall是如何把数据包转发到代理的? 
是不是要tcp/udp分别转发呢? 需要什么软件和功能才能做到?
在ubuntu下可以用多种软件配合起到相同的作用吗???

**Comment by lwb1978** [comment]
issues是接受软件功能建议和反馈bug的地方，你要学习知识应该去相关论坛或电报群，github上的开源软件只提供你使用或拿去修改，但不会给你提供教学，更不会教你本仓库以外的东西。
总之github不是学习和讨论技术的地方，建议不要再提这类问题，不信你可以去ssrp、openclash或者homeproxy那边提一下同样的问题看。
