### ISSUE TITLE
[Feature Request]: releases缺少相关包

### ISSUE THREAD

**Issue by chris6868** [xiaorouji/openwrt-package#3460]
### 描述你想要的新功能

release发布的版本里缺少v2ray-core这个包，安装后也不支持v2ray协议

### 描述你想要的解决方案

添加一下这个包

### 描述你考虑过的替代方案

单独提供一个下载链接

**Comment by chris6868** [comment]
passwall_packages_ipk_x86_64版本缺少，其他包没看

**Comment by lwb1978** [comment]
为了减少维护量，pw早已移除了v2ray-core的依赖，v2ray所支持的协议sing-box和xray都能支持。
