### ISSUE TITLE
[Bug]: 点击百度 谷歌 测速 一直显示 检测中，谷歌可以打开

### ISSUE THREAD

**Issue by realbartain** [xiaorouji/openwrt-package#3461]
### 描述您遇到的bug
共遇到4个问题
1. passwall添加完节点后，点击 百度 谷歌 github等测速，一直显示测速中，实际谷歌可以打开
2. 节点列表测速 TCP 自动有测速数值，点击 Ping 测试 也显示数值， 点击URL测试 显示错误
3. 节点订阅失败，这个订阅地址是正常使用的
4. 安装passwall 出现 error，如图
Collected errors :
opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

详细介绍
1. passwall添加完节点后，点击 百度 谷歌 github等测速，一直显示测速中，实际谷歌可以打开
![Screenshot_2024-10-28-08-35-16-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/ec31734a-2ae0-4990-8837-2504ba17c7b7)

2. 节点列表测速 TCP 自动有测速数值，点击 Ping 测试 也显示数值， 点击URL测试 显示错误

3. 节点订阅失败，这个订阅地址是正常使用的
日志
2024-10-28 14:22:56: 【js】订阅失败，可能是订阅地址失效，或是网络问题，请诊断！
2024-10-28 14:22:56: 更新失败，没有可用的节点信息
2024-10-28 14:22:56: 订阅完毕...

4.安装passwall 出现 error，如图 
Collected errors :
 opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

### 复现此Bug的步骤

1.安装passwall 出现 error，如图 
Collected errors :
 opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

我不确定是不是这个error导致的 百度谷歌测速 问题
![Screenshot_2024-10-28-08-27-40-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8ef3a893-f814-451e-9719-a7b7fc2d699f)

5. 我的是硬路由 兆能M2路由器，闪存128M，overlay 只有65M，直接安装passwall最后会提示xray 和 v2ray空间不足，
所以我是先安装了所有依赖和插件，最后安装的passwall 和 语言包, 安装完最后提示Collected errors，参见1 

这是先安装完所有依赖和插件，点击安装passwall 时的截图
![Screenshot_2024-10-28-08-26-56-44](https://github.com/user-attachments/assets/5570395a-9018-41de-abe7-a67dd2954542)

### 您想要实现的目的

1. 点击百度 谷歌测速， 可以测正常显示
2. 这个安装时出现的errors，opkg.lock 有什么用，error可能会有其他什么影响 
Collected errors :
 opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.
### 日志信息

这个在哪里看，日志好像没有这个

### 系统相关信息

passwall 4.78-3版本

**Comment by lwb1978** [comment]
这个是你系统问题，重点检查curl组件和openssl。

**Comment by realbartain** [comment]
> 这个是你系统问题，重点检查curl组件和openssl。

我这个有4个问题，请问 哪个问题 跟 curl组件 和openssl 有关系， 谢谢 大佬

1. passwall添加完节点后，点击 百度 谷歌 github等测速，一直显示测速中，实际谷歌可以打开
2. 节点列表测速 TCP 自动有测速数值，点击 Ping 测试 也显示数值， 点击URL测试 显示错误
3. 节点订阅失败，这个订阅地址是正常使用的
4. 安装passwall 出现 error，如图
Collected errors :
opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

**Comment by lwb1978** [comment]
123

**Comment by realbartain** [comment]
> 123
curl 安装了 
curl | 8.10.1-r1 和  libcurl4 | 8.10.1-r1
![image](https://github.com/user-attachments/assets/f4f59495-016d-4051-bccb-2257b028c3fe)

但是 openssl 安装了libopenssl-conf ， libopenssl-legacy，libopenssl3

![image](https://github.com/user-attachments/assets/76ec4f7d-5cc8-4f3e-b4e6-e247e085721d)

openssl-util 和 apk-openssl  需要安装不？ 
![image](https://github.com/user-attachments/assets/e165c34c-5a7d-46cd-9648-0f0d161ab572)

麻烦大佬 给指明安装哪些

**Comment by lwb1978** [comment]
重新编译系统或者换一个吧，不止你一个人出现过这个问题，问题就出在curl，每个人的使用环境千差万别，怎么修帮不了你，比如:
https://github.com/xiaorouji/openwrt-passwall/discussions/3004
