### ISSUE TITLE
[Bug]: 更新4.78-4以后，主开关切换不起作用。

### ISSUE THREAD

**Issue by kkqy** [xiaorouji/openwrt-package#3464]
### 描述您遇到的bug

更新以后，“主开关” 从关闭变为打开，点击“保存并应用”以后，按道理应该会启动passwall，但是实际上日志里没有任何动静，感觉只是保存了配置文件，并没有真正地”应用“
这个时候我必须在 shell里面执行 /etc/init.d/passwall restart 才会真正地启动

### 复现此Bug的步骤

1. 先确保passwall处于停止状态
2. 将“主开关”变为打开
3. 点击“保存并应用”
4. 只是保存了配置，但是passwall并没有启动，需要手动执行`/etc/init.d/passwall restart`后才会真正启动

### 您想要实现的目的

这个问题应该是4.78-4更新以后出现的，之前就是正常的。

### 日志信息

没有日志

### 系统相关信息

- Passwall版本：4.78-4

**Comment by lwb1978** [comment]
最近的修改并没有涉及到主开关有关的代码。

**Comment by lwb1978** [comment]
我在我两台路由上反复开、关 主开关-保存应用 都能正常完成开启、停止PW，没有出现无法启动的情况。

**Comment by xh0823** [comment]
> 最近的修改并没有涉及到主开关有关的代码。

大佬可以看看分片功能吗，workers和pages只能用http1.1才可以正常连接h2和h3都不能正常连接，小火箭和安卓都可以连接

**Comment by kkqy** [comment]
> 我在我两台路由上反复开、关 主开关-保存应用 都能正常完成开启、停止PW，没有出现无法启动的情况。

可能是我先卸载passwall再安装新版本passwall后无意中触发的什么BUG，我重启路由以后就正常了。

**Comment by lwb1978** [comment]
> > 最近的修改并没有涉及到主开关有关的代码。
> 
> 大佬可以看看分片功能吗，workers和pages只能用http1.1才可以正常连接h2和h3都不能正常连接，小火箭和安卓都可以连接

术业有专攻，我没有用分片，对这块不了解，看看久未谋面的 @nftbty 大佬或者 @Pacalini 大佬能否帮看看这个问题。

**Comment by xh0823** [comment]
> > > 最近的修改并没有涉及到主开关有关的代码。
> > 
> > 
> > 大佬可以看看分片功能吗，workers和pages只能用http1.1才可以正常连接h2和h3都不能正常连接，小火箭和安卓都可以连接
> 
> 术业有专攻，我没有用分片，对这块不了解，看看久未谋面的 @nftbty 大佬或者 @Pacalini 大佬能否帮看看这个问题。

好的谢谢解答，还是等大佬看看是不是有什么问题吧，谢谢

**Comment by Vanisn** [comment]
我也遇到了同样的情况。需要重启机器，才能实现passwall服务开启或关闭
