### ISSUE TITLE
[Bug]: 更新4.78.4直接崩了

### ISSUE THREAD

**Issue by lilaoye88** [xiaorouji/openwrt-package#3465]
### 描述您遇到的bug

x86软路由immortalWrt，安装4.78.3一直稳定使用，今天手工升级到4.78.4，直接崩了，安装时看到信息在删除一些什么其他的插件。passwall就不工作了。后来重置路由器全新安装passwall4.78.4，也不行。socks配置那里，socks主开关打开了，下面添加的socks节点也是xx状态，不能用。已经恢复到4.78.3了。

### 复现此Bug的步骤

直接下载4.78.4安装包升级安装

### 您想要实现的目的

修复4.78.4的问题

### 日志信息

已经恢复了，没记录日志

### 系统相关信息

4.78.3 4.78.4 chrome

**Comment by lwb1978** [comment]
再看吧，3到4之间的升级不至于崩掉，issues也已经有同学升级到4正常使用了，你的应该属于个案，因为没有提供更多有效信息如截图什么的，所以无法分析。

**Comment by lilaoye88** [comment]
崩没什么，时候来重置软路由后重新安装passwall，socks用不了。因为我要做负载均衡，所以要建立多个socks节点。主开关启用了，但是状态哪里是xx。只能截图正常状态，因为已经重装回4.78.3了。
![1730269096908](https://github.com/user-attachments/assets/521aba29-8404-47af-91a0-492777886947)
重新安装4.78.4，所有的插件都是解压的4.78.4的压缩包。然后socks状态是xx。截图是4.78.3的正常状态。
![1730269177187](https://github.com/user-attachments/assets/9677ae59-b6b5-4b08-a953-9b9922044279)

除了socks不能开启，直接选节点是可以用的。然后就做不了负载均衡而已。

**Comment by lwb1978** [comment]
3到4没有动过socks代码，早前也有人反馈socks崩溃，换xray的socks就行。pw只是个luci插件，并不涉及二进制文件运行，所有二进制组件都不是pw开发，这种情况也基本无解。我这里两台路由都是自己编译的imm 23.05  6.x内核，也使用负载均衡，socks从没有出错过。

**Comment by solarflows** [comment]
估摸着应该是卸载的时候opkg把依赖全删了(部分软件的依赖是内核模块，但是openwrt的软件源没有包含相应版本的内核模块，导致安装虽然成功了，但是缺一部分东西，部分功能就开不起来)，另一种可能是楼主使用了imgtovmdk，偶尔貌似会导致启动盘有空间但是写不进去东西。

**Comment by lilaoye88** [comment]
> 估摸着应该是卸载的时候opkg把依赖全删了(部分软件的依赖是内核模块，但是openwrt的软件源没有包含相应版本的内核模块，导致安装虽然成功了，但是缺一部分东西，部分功能就开不起来)，另一种可能是楼主使用了imgtovmdk，偶尔貌似会导致启动盘有空间但是写不进去东西。

卸载旧luci时候取消了自动删除未使用依赖选项的。再说安装的时候immmortal不是会自动安装缺少的依赖吗。是安装新luci的时候显示删除什么什么的。应该是个例。可能和安装ddnsto以后一直显示有个错误，没去清除它有关系。肯定和什么imgtovmdk没关系。自己编译的immortal，除了passwall，其他什么都没选，挂在ESXI上面的X86_64镜像。后续安装了mosdns和ddnsto。
![1730412620916](https://github.com/user-attachments/assets/4f57b01c-eb93-49ad-a350-0a5e90087ece)
安装ddnsto后错误是这个
![1730412783584](https://github.com/user-attachments/assets/bc0cecde-daa9-4321-ad0a-1b7e50044aeb)
清除方法是这个。更新passwall导致不能用时，这个错误一直没处理。有可能是这个原因。
刚好这两天要刷台360T7，再试试。

**Comment by lilaoye88** [comment]
![1730430505831](https://github.com/user-attachments/assets/59ec1f18-adf4-43b6-9eeb-1a9c1713a709)
现在是4.78.3，手机老的38块钱无限流量套餐，加的10块钱/月，100兆宽带，移动光纤。速度很快，截图先。升级完4.78.4看看会不会慢。慢了就怪作者。嘿嘿
