### ISSUE TITLE
[Feature Request]: 本地socks服务希望能增加用户密码校验并在配置中增加配置选项

### ISSUE THREAD

**Issue by frankiejun** [xiaorouji/openwrt-package#3467]
### 描述你想要的新功能

本地socks服务希望能增加用户密码校验并在配置中增加配置选项

![passwall](https://github.com/user-attachments/assets/9923f3bc-5e77-4d4c-a49d-aba629062194)

### 描述你想要的解决方案

socks5本来自带用户密码校验选项，只需增加参数即可。
界面增加用户名和密码2个输入框。

**Comment by mars-m9** [comment]
这是用来做自动切换的，没必要。你可以用服务器端，能设置用户名和密码。

**Comment by lxzcl** [comment]
上面的回答不足以满住特定情况下的需求，
config socks 'Y1j7hK8I'                                                                                                                         
        option enabled '1'                                                                                                                      
        option port '1081'                                                                                                                      
        option node '7MOZqCrD'                                                                                                                  
        option http_port '2081'                                                                                                                 
        option log '1'                                                                                                                          
        option enable_autoswitch '1'                                                                                                            
        option autoswitch_testing_time '30'                                                                                                     
        option autoswitch_connect_timeout '3'                                                                                                   
        option autoswitch_restore_switch '1'                                                                                                    
        option autoswitch_probe_url 'https://www.google.com/generate_204'                                                                       
        option autoswitch_retry_num '3'                                                                                                         
        list autoswitch_backup_node 'CoXa5pmR'

以上是一个sock的配置，我该如何在代码里添加http的认证账号和密码？
