### ISSUE TITLE
[Feature Request]: 关闭路由器自身代理功能，外网设备需要连接路由的服务器端翻墙，怎么办。

### ISSUE THREAD

**Issue by shan869** [xiaorouji/openwrt-package#3468]
### 描述你想要的新功能

關掉路由器自身代理！
這樣就可以正常讓路由器自身安裝的tailscale工作了，在關閉路由器自身代理之前，請確保passwall dns選項是通過dns2socks解析的，不然dns請求就變成不經過代理伺服器了。這不是bug，這是個feature。这是我看到的情况。
但是，我的网络需要关闭自身代理才能稳定使用tailscale,可外网设备使用服务器端就不能翻墙了，请问有什么方法解决吗？

### 描述你想要的解决方案

我想路由关闭自身代理，但是外网设备连接服务器端时能够实现翻墙。

### 描述你考虑过的替代方案

我想路由关闭自身代理，但是外网设备连接服务器端时能够实现翻墙。

### 其他信息

我想路由关闭自身代理，但是外网设备连接服务器端时能够实现翻墙。

**Comment by shan869** [comment]
或者说我需要tailscale不走代理，然后外网设备能用服务器端翻墙。

**Comment by shan869** [comment]
对了 ,关了自身代理功能后，使用tailscale是能翻墙的，但是我不能用这个方案。我需要用服务器端的方式翻墙。

**Comment by ghost** [comment]
![Screenshot From 2024-11-04 11-13-13](https://github.com/user-attachments/assets/1e979111-caf7-44b3-997f-6396045c7bfe)

您只需要關掉 「路由器本機代理」 這個開關即可，其他諸如模式之類的無需操作。（例如圖片所示）它不會影響LAN設備。

**Comment by shan869** [comment]
> ![Screenshot From 2024-11-04 11-13-13](https://private-user-images.githubusercontent.com/84697424/382630541-1e979111-caf7-44b3-997f-6396045c7bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTA0MTcsIm5iZiI6MTczMDY5MDExNywicGF0aCI6Ii84NDY5NzQyNC8zODI2MzA1NDEtMWU5NzkxMTEtY2FmNy00NGIzLTk5N2YtNjM5NjA0NWM3YmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDAzMTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjc5YjMxMjJmOTk4MGU3NTlhNTJlOGYxZjAzZjUyYjU2YjZlZmY3ZGY4ZTkwZjdmNDk5Yzg3NGY2Y2M5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mOCiSuIVLtWTqhFhN4u0fZ-6oqZ-Cy-cMDQtN4GMD9Q)
> 
> 您只需要關掉 「路由器本機代理」 這個開關即可，其他無需操作。（例如圖片所示）它不會影響LAN設備。

你没理解我需求。關掉 「路由器本機代理】，tailscale确实恢复正常，而且LAN设备也可以翻。但是我有外网设备，不方便使用tailscale，只能开启路由器的服务器端，外网设备连接这个服务端。但是由于路由器本身已关闭本机代理功能，所以连接了路由器服务端的设备依然无法代理，只是能访问LAN。

**Comment by shan869** [comment]
我需要用IPV6访问路由服务器端，并获得代理能力。

**Comment by mitsukileung** [comment]
> 我需要用IPV6访问路由服务器端，并获得代理能力。

请问找到解决方法了吗？
