### ISSUE TITLE
让passwall直接使用机场的ipv6地址访问墙外

### ISSUE THREAD

**Issue by ceowing** [xiaorouji/openwrt-package#3469]
### 描述你想要的新功能

让passwall直接使用机场的ipv6地址访问墙外，我在dns里面开启了过滤代理域名 [IPv6]
还是访问不了奈飞，用ipleak.net 测试ipv4，dns不泄露了，但是ipv6还是用我本地电脑的地址，，图片中就是我电脑的ipv6
![微信截图_20241104133034](https://github.com/user-attachments/assets/267f3e71-e78f-41a5-8767-a561d0700426)
![微信截图_20241104133329](https://github.com/user-attachments/assets/b4a5eb16-9c45-48dc-8131-362ad39efd84)

### 描述你想要的解决方案

我想让passwall 用机场的ipv6地址去访问国外的，家里各种设备都是用这个地址去访问国外的网站，这样可以实现吗？像在电脑安装ssr的软件那样，直接用的ipv4和ipv6访问的国外网站
![微信截图_20241104133711](https://github.com/user-attachments/assets/b46bf87b-bac2-41ea-9248-df1f7ab9e410)

**Comment by ghost** [comment]
您好，passwall本身可以使用代理出口的ipv6訪問網絡，至於為何勾選了相應選項但不生效，這說明您的路由器固件存在以下三種情況。
1.路由器安裝了docker
2.路由器存在與passwall同類的代理應用，例如openclash
3.編譯時，路由器iptables模組選擇的不完整

您的路由器固件必然會有以上三種情形中的一種，或者三種情形都同時存在，請您自行嘗試解決路由器固件的問題後再試。

**Comment by ghost** [comment]
您好，passwall和docker無法共存，和openclash等第三方代理應用也無法共存，建議您調整編譯設置後，再試。

**Comment by ghost** [comment]
您好，如果您的路由器選擇的是「全局代理」那麼在這種情形下，您需要關閉路由器自身代理才能正常代理IPv6連線。

**Comment by ceowing** [comment]
您好，我是在esxi 里面安装了ikuai+iStore，在iStore里面运行的passwall，安装其他的类似的软件，iStore自带有docker

**Comment by ceowing** [comment]
> 您好，passwall本身可以使用代理出口的ipv6訪問網絡，至於為何勾選了相應選項但不生效，這說明您的路由器固件存在以下三種情況。 1.路由器安裝了docker 2.路由器存在與passwall同類的代理應用，例如openclash 3.編譯時，路由器iptables模組選擇的不完整
> 
> 您的路由器固件必然會有以上三種情形中的一種，或者三種情形都同時存在，請您自行嘗試解決路由器固件的問題後再試。

谢谢回复，我尝试解决一下，看看是不是以上这几种情况

**Comment by ghost** [comment]
> > 您好，passwall本身可以使用代理出口的ipv6訪問網絡，至於為何勾選了相應選項但不生效，這說明您的路由器固件存在以下三種情況。 1.路由器安裝了docker 2.路由器存在與passwall同類的代理應用，例如openclash 3.編譯時，路由器iptables模組選擇的不完整
> > 您的路由器固件必然會有以上三種情形中的一種，或者三種情形都同時存在，請您自行嘗試解決路由器固件的問題後再試。
> 
> 谢谢回复，我尝试解决一下，看看是不是以上这几种情况

您只需要編譯的時候去除docker和其他同類代理應用即可，這是一個已知問題，由於iptables規則的衝突，passwall無法與docker和其他代理組件共存。

**Comment by woni928** [comment]
> > > 您好，passwall本身可以使用代理出口的ipv6訪問網絡，至於為何勾選了相應選項但不生效，這說明您的路由器固件存在以下三種情況。 1.路由器安裝了docker 2.路由器存在與passwall同類的代理應用，例如openclash 3.編譯時，路由器iptables模組選擇的不完整
> > > 您的路由器固件必然會有以上三種情形中的一種，或者三種情形都同時存在，請您自行嘗試解決路由器固件的問題後再試。
> > 
> > 
> > 谢谢回复，我尝试解决一下，看看是不是以上这几种情况
> 
> 您只需要編譯的時候去除docker和其他同類代理應用即可，這是一個已知問題，由於iptables規則的衝突，passwall無法與docker和其他代理組件共存。

passwall和docker，openclash不能编译在同一个固件当中？这就尴尬了！

**Comment by woni928** [comment]
楼主，你这是什么设置的，dns才不会泄漏？
