### ISSUE TITLE
[Bug]: nftset语法在immortalWrt上不被支持

### ISSUE THREAD

**Issue by snowie2000** [xiaorouji/openwrt-package#3470]
### 描述您遇到的bug

目前nftables.sh中的定义：
```
insert_nftset() {
	local nftset_name="${1}"; shift
	local timeout_argument="${1}"; shift
	local defalut_timeout_argument="3650d"
	local nftset_elements

	[ -n "${1}" ] && {
		if [ "$timeout_argument" == "-1" ]; then
			nftset_elements=$(echo -e $@ | sed 's/\s/, /g')
		elif [ "$timeout_argument" == "0" ]; then
			nftset_elements=$(echo -e $@ | sed "s/\s/ timeout $defalut_timeout_argument, /g" | sed "s/$/ timeout $defalut_timeout_argument/")
		else
			nftset_elements=$(echo -e $@ | sed "s/\s/ timeout $timeout_argument, /g" | sed "s/$/ timeout $timeout_argument/")
		fi
		mkdir -p $TMP_PATH2/nftset
		cat > "$TMP_PATH2/nftset/$nftset_name" <<-EOF
			define $nftset_name = {$nftset_elements}	
			add element $NFTABLE_NAME $nftset_name \$$nftset_name
		EOF
		nft -f "$TMP_PATH2/nftset/$nftset_name"
		rm -rf "$TMP_PATH2/nftset"
	}
}
```
是define了一个ip列表，然后`add element $NFTABLE_NAME $nftset_name \$$nftset_name`，然而经过我几个小时的踩坑经历，immortalWrt 23.05版本中并不支持使用这个语法，它只支持`add element $NFTABLE_NAME $nftset_name {$nftset_elements}`

否则会导致创建出来的nftset是空的，或者里面只有一个0.0.0.0/0的全局值。并且先定义再使用也没有实际意义。

### 复现此Bug的步骤

应用后生成的nftset不正确，导致所有规则全部需要通过cpu匹配，降低了性能并且不符合设计

### 您想要实现的目的

直接用`add element $NFTABLE_NAME $nftset_name {$nftset_elements}` 或使用其他兼容语法。

### 日志信息

无

### 系统相关信息

版本：4.78-4
设备：r2s immortalWrt 23.05

**Comment by snowie2000** [comment]
根据多个AI模型和各处能找到的资料，nft add element不能支持使用define出来的变量作为ip列表

**Comment by lwb1978** [comment]
@ShanStone 老大能否验证一下？

**Comment by lwb1978** [comment]
照理说immortalWrt是跟openwrt官方基本同步的，只是针对国人进行了优化，如果immortalWrt不支持那么openwrt官方也应该不支持。

你直接将代码中的`add element $NFTABLE_NAME $nftset_name \$$nftset_name`替换成`add element $NFTABLE_NAME $nftset_name {$nftset_elements}`后问题是否解决了？

**Comment by snowie2000** [comment]
我后来发现是另一个问题导致的，那就是保存并应用配置不会清空nftset，必须点击dns选项卡下的重置nftset才行，导致某次修改添加了
0.0.0.0/0后，无论什么修改都无法让nftset有任何变化了，这个才是真的bug

**Comment by lwb1978** [comment]
我对防火墙这块不太熟悉，我之前也发现了，如果使用ipt时保存应用是会清空ipset的，但是使用nft时保存应用不会进行nftset清空操作，不知道之前写防火墙时大佬们是出于什么目的考虑的，因为摸不透原理所以我不敢动这个代码。

**Comment by snowie2000** [comment]
怎么看都是个bug，不清空nftset只一直往上叠肯定是不对的嘛

**Comment by lwb1978** [comment]
> 怎么看都是个bug，不清空nftset只一直往上叠肯定是不对的嘛

不一定是bug，可能初衷是为了保留缓存，不过我得空看下代码，可先将0.0.0.0/0进行排除。

**Comment by snowie2000** [comment]
我又补充了#3474，也是和nftset相关的另一组bug集合。你并不需要排除0.0.0.0/0，那个issue解释了这一点

保留缓存的意义何在不是很明白。另外只往上累加而不清理，这必然导致每次修改规则只会增不会减，减少的规则全部不会生效，每次都不得不应用，重置，毫无意义。而且iptables版本明明是清空的

**Comment by snowie2000** [comment]
我在iptables模式下重新测试发现现在iptables版也不会清空ipset了，这是哪个版本引入的修改吗？

**Comment by lwb1978** [comment]
我的路由也是imm，一直都是自编译的主分支，从23.05到现在的24.10这段代码都是可以使用的：
```
define $nftset_name = {$nftset_elements}	
add element $NFTABLE_NAME $nftset_name \$$nftset_name
```
今天测试了：`add element $NFTABLE_NAME $nftset_name {$nftset_elements}`
同样是没有问题的，nft list 也都能看到正确的加入了ip，我先将代码更换成下面这行吧，看以后实际中大家的反馈。
