### ISSUE TITLE
Xray传输方式为SpiltHTTP时缺少reallity配置

### ISSUE THREAD

**Issue by fnoopv** [xiaorouji/openwrt-package#3473]
### 描述您遇到的bug

如题所述

### 复现此Bug的步骤

1,新增节点
2.协议选择vless
3.传输方式选择splitHTTP，此时reality配置隐藏了，无法进行配置

### 您想要实现的目的

传输方式为splitHTTP时能正常配置reality

### 日志信息

无

### 截图

<img width="531" alt="mmexport1730735907968" src="https://github.com/user-attachments/assets/dd4c2f52-e42f-40d0-ba17-d94504c8fc7a">
<img width="696" alt="mmexport1730735909861" src="https://github.com/user-attachments/assets/dcbea75c-922e-4e49-90aa-0ce3d418e234">

### 系统相关信息

passwall: 4.78-4

**Comment by lwb1978** [comment]
请确认一下xray的SpiltHTTP支持reallity了吗？
在官方搜索了一下，上个月还有人问是否支持`https://github.com/XTLS/Xray-core/issues/3870`

**Comment by fnoopv** [comment]
https://github.com/XTLS/Xray-core/pull/3816
已经支持了

**Comment by fnoopv** [comment]
https://github.com/mmmray/Xray-core/blob/134ff296564379f88c5ca3d25508c3e07308f416/infra/conf/transport_internet.go#L829-L830

**Comment by lwb1978** [comment]
已适配。

**Comment by fnoopv** [comment]
辛苦
