### ISSUE TITLE
[Bug]: nftables的nftset内ip集不合理/不正确

### ISSUE THREAD

**Issue by snowie2000** [xiaorouji/openwrt-package#3474]
### 描述您遇到的bug

有几个相关的问题，一并提出
- https://github.com/xiaorouji/openwrt-passwall/blob/9d7929ea122c5de455cb1043980f66d02877207d/luci-app-passwall/root/usr/share/passwall/nftables.sh#L830-L834 此处获取了所有规则列表内指定的ip地址，但并没有考虑该规则是否是启用的（即对应的分流是否为关闭）这导致没有被使用的规则也被错误的加入到了nftset中。如果觉得这个问题不大，请看下一条

-  由于未被使用的规则一样会被加入到列表，并且tcp和udp规则的列表没有分开，这使得如果我有一条udp规则，该规则尝试代理所有端口为53的udp请求，ip范围为0.0.0.0/0，这将导致passwall_shuntlist直接被覆盖为0.0.0.0/0，从而使得所有请求全部走singbox/xray，直接变成全局状态，性能明显下降

-  https://github.com/xiaorouji/openwrt-passwall/blob/9d7929ea122c5de455cb1043980f66d02877207d/luci-app-passwall/root/usr/share/passwall/nftables.sh#L833 从这里可以看到它只判断列表中ipv4的结果范围，原意应该是为了排除ipv6，但代码没有考虑到`geoip:xx`的情况，所以所有geoip的结果集会被全部丢弃，所有结果均不生效。

### 复现此Bug的步骤

1. 创建一个规则udp
2. 端口53，ip范围0.0.0.0/0
3. 应用
4. 所有数据全部走了代理

### 您想要实现的目的

udp和tcp的列表应该分开

geoip应该被正确解析并放入shuntlist中

### 日志信息

无

### 系统相关信息

4.78-4

**Comment by snowie2000** [comment]
geoip复现步骤：
1. 新建一个规则
2. 目标ip geoip:us
3. 给该规则目标设置为黑洞
4. 应用

美国地区的网站依然可以正常打开。

**Comment by lwb1978** [comment]
防火墙本来就不支持geoip:这种类型，必须要xray或sing-box，所以这种类型的要进入核心的，但具体处理流程我也搞不懂了。

**Comment by snowie2000** [comment]
> 防火墙本来就不支持geoip:这种类型，必须要xray或sing-box，所以这种类型的要进入核心的，但具体处理流程我也搞不懂了。

防火墙显然不能识别geoip，所以应该将geoip内的ip列表解析回CIDR，然后加入到列表内，最终交给应用进行分流处理，否则由于set中不存在对应的ip集，数据包根本没有机会进入应用内进行分流判断

**Comment by lwb1978** [comment]
粗看了一下，这段代码好像确实有问题，把所有的分流ip都加入了防火墙，并没有区分哪些ip是代理、直连和屏蔽的。能力问题实在搞不懂原设计思路。也许正因为不够完善且复杂，所以后来小肉鸡搞了PW2，PW2分流由xray完成，去掉了规则列表的设置。

**Comment by lwb1978** [comment]
细想一下，其实应该可以将1楼的这段代码屏蔽，一是如果不启用分流总节点时不应该加载分流规则里面的ip；二是屏蔽掉后开启分流时可以直接由xray或者sing-box的核心来进行处理，可以处理得更精准。楼主如果有空的话可以试试屏蔽这段代码后的效果。

**Comment by snowie2000** [comment]
确实是可以全部交给应用来处理的，我之前错误的加入了0.0.0.0/0后，就进入了这样的状态，但这会导致一些问题：
- 所有流量都交给了应用层处理，而不是硬件层，导致硬路由变成了软路由，硬件加速完全失效，并且直连的流量也要消耗cpu，这样一来pw和clash比就没什么优势了，在低配机器上都是性能杀手
- 在gfw模式下，流量遵守的规则是
  - 非黑名单非规则一律直连
  - 按规则列表进行分流
  - 按默认结点出口
  在全部走cpu分流后，第一条就不再成立，所有流量都会走默认出口

**Comment by snowie2000** [comment]
经过一段折腾把nftables重新切换到iptables后发现，iptables也存在相同的问题，udp和tcp混合列表，不支持geoip

**Comment by lwb1978** [comment]
防火墙不支持geoip这种是必然的，我现在打算是在力所能及的基础上先初步改一下ipt和nft的脚本，不启用分流时不导入分流规则中的ip，如果需要导入时区分出直连和代理ip，其他的等大佬们出山吧。本想是来帮大佬们搬砖的，没成想各路大佬一夜间全闭关了，不知道是不是换赛道了。

**Comment by lwb1978** [comment]
粗略的先修改了一下代码，至少各个分流规则的ip去它该去的地方，没用到的也不会添加到ipset了，至于说tcp和udp由于当初设计就是共用了ipset，要分别控制的话要大改，成本太高了。
另外，geoip的话可能只能由xray或sing-box内部进行处理了，这两个核心应该没有geoip匹配结果输出回ipset的功能，即使有的话数据流进核心再流出防火墙进行一轮匹配的话效率更慢。

**Comment by snowie2000** [comment]
我的意思是需要一个程序根据geoip:xx生成一段CIDR值，然后将该列表加入ipset中，从而实现geoip规则也能生效的目的，这样可以让防火墙顺利捕获到对应地区的数据包，交给核心去分流处理。
现在的问题是由于不能识别geoip导致防火墙根本就不处理对应的ip数据包，核心中虽然有对应的分流规则实际上各种用不了

**Comment by lwb1978** [comment]
> 我的意思是需要一个程序根据geoip:xx生成一段CIDR值，然后将该列表加入ipset中，从而实现geoip规则也能生效的目的，这样可以让防火墙顺利捕获到对应地区的数据包，交给核心去分流处理。 现在的问题是由于不能识别geoip导致防火墙根本就不处理对应的ip数据包，核心中虽然有对应的分流规则实际上各种用不了

PW只是个厨师，把各种食材和调味料做成一盘菜，你总不能让厨师自己养猪、种菜、晒180天的酱油吧。

**Comment by snowie2000** [comment]
https://github.com/Loyalsoldier/geoip

这个程序（同时也是pw的geoip默认提供者）就支持将geoip反向解析为csv等容易处理的格式，人家已经提供了对应的调料和食材了

**Comment by snowie2000** [comment]
https://github.com/user-attachments/assets/013c91a7-bd12-47fd-b6d2-c482a990f514

我录制了一段转换过程的视频

**Comment by lwb1978** [comment]
建议你能参与一起开发，尝试修改和完善代码PR上来，开源社区是欢迎大家共同维护代码的，PW的各路大佬现在都隐退了，我参与维护几个月以来也只是小打小闹修复和完善了一些老代码（能力和精力有限），发现一个人单打独斗确实很伤脑也很累。

**Comment by snowie2000** [comment]
我要自己能修早就修了，我对nft十分不熟悉，对iptables还好一些。并且不会lua……

**Comment by qingtian110** [comment]
> 发现一个人单打独斗确实很伤脑也很累

passwall 会不会考虑用 js 重做

**Comment by lwb1978** [comment]
> 
> passwall 会不会考虑用 js 重做

大概率应该不会，工程量不是一般的大，除非小肉鸡能拉起一个团队各自分工，而且最主要的是lede应该还有一大批用户。

**Comment by snowie2000** [comment]
> 建议你能参与一起开发，尝试修改和完善代码PR上来，开源社区是欢迎大家共同维护代码的，PW的各路大佬现在都隐退了，我参与维护几个月以来也只是小打小闹修复和完善了一些老代码（能力和精力有限），发现一个人单打独斗确实很伤脑也很累。

如果可以把geoip和geosite的转换工具做成ipk加入到pw的依赖列表中的，是不是就可以利用他们把v2系列的文件转换成pw可以处理的ip和域名呢？

**Comment by lwb1978** [comment]
如果能有人写一个小巧支持openwrt全平台的工具那这个问题就引刃而解了。

**Comment by handsomeji** [comment]
> 建议你能参与一起开发，尝试修改和完善代码PR上来，开源社区是欢迎大家共同维护代码的，PW的各路大佬现在都隐退了，我参与维护几个月以来也只是小打小闹修复和完善了一些老代码（能力和精力有限），发现一个人单打独斗确实很伤脑也很累。

Thank you for your continued support and hard work.
I have immigrated to a foreign country, so the demand has decreased.
I mainly use the return china mode.
