### ISSUE TITLE
[Bug]: xray分流无效

### ISSUE THREAD

**Issue by chris6868** [xiaorouji/openwrt-package#3481]
### 描述您遇到的bug

xray分流无效，查询后看大家说需要开启xray的流量嗅探，但是最新的版本没有这个设置，是去掉该功能了，还是需要安装什么依赖包，感谢大佬

### 复现此Bug的步骤

无

### 您想要实现的目的

xray可以分流

### 日志信息

无

### 系统相关信息

 4.78-4-x86

**Comment by lwb1978** [comment]
我一直使用xray分流，并没有出现失效的情况，设置xray分流配置时是要考虑策略先后命中顺序的。

**Comment by snowie2000** [comment]
在gfw模式下，不再gfw列表中的域名如果用geosite写的话，不会被分流。

**Comment by lwb1978** [comment]
> 在gfw模式下，不再gfw列表中的域名如果用geosite写的话，不会被分流。

没这回事，xray分流方式下，我一直用geosite分谷歌、油管等走不同国家节点。

**Comment by snowie2000** [comment]
> > 在gfw模式下，不再gfw列表中的域名如果用geosite写的话，不会被分流。
> 
> 没这回事，xray分流方式下，我一直用geosite分谷歌、油管等走不同国家节点。

首先你的设置必须是tcp默认为分流，如果tcp默认为不分流，那么由于dnsmasq的ipset.conf中不会包含geosite网址，根本不可能进core来分流

**Comment by snowie2000** [comment]
我专门测试过，无论在规则列表中写什么geosite，ipset.conf文件根本毫无变化，那么对应的连接靠什么规则才能被iptables捕获呢？iptables并没有按域名匹配的能力，只能依靠dnsmasq来实现，而无论是dnsmasq还是pw都不具备解析geosite的能力，必须让他进xray或sing-box核心分流才行

**Comment by lwb1978** [comment]
> 在gfw模式下，不再gfw列表中的域名如果用geosite写的话，不会被分流。

没注意看，不在gfw列表内的是没办法了，毕竟现在条件不允许，先天性不具备解析geosite能力。

**Comment by snowie2000** [comment]
如果把相关工具做成ipk是否就可以支持？

**Comment by lwb1978** [comment]
可以的，只要能解析ip或域名数据库并且有相关的输入输出接口就行。

**Comment by snowie2000** [comment]
> 可以的，只要能解析ip或域名数据库并且有相关的输入输出接口就行。

我创建了一个项目，可以实现ip和domain相关的所有功能：https://github.com/snowie2000/geoview

**Comment by chris6868** [comment]
> 我一直使用xray分流，并没有出现失效的情况，设置xray分流配置时是要考虑策略先后命中顺序的。

youtube的分流规则在第一个，给youtube配置的一个香港节点，但是访问的确实美国的youtube，配置美国节点是代理分流，倒数第二个，所以这个顺序是越前面越优先还是越后面越优先
