### ISSUE TITLE
[Bug]: 最新版本的gfw模式失效

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#3483]
### 描述您遇到的bug

os：openwrt23.05.5
pw：passwall4.78-4 （afff9eec8e271b89cab6d8675bc4a9f16a412a6c）版本。
默认情况下passwall的gfw模式失去效果

### 复现此Bug的步骤

默认gfw模式下无法链接外网，但是在中国列表外可以连接
默认gfw模式下：TCP 默认代理模式 和 UDP 默认代理模式 都是默认不代理
中国列表外：TCP 默认代理模式 和 UDP 默认代理模式 都是默认代理
在GFW模式下：TCP 默认代理模式 和 UDP 默认代理模式 修改为代理可以连接外网
如图：
![默认](https://github.com/user-attachments/assets/e7e87eb4-fd63-438b-83ef-80d5901da483)
![代理模式有效](https://github.com/user-attachments/assets/649c841f-1406-4335-8540-bb7866563ef8)

### 您想要实现的目的

修改bug

### 日志信息

无

### 系统相关信息

无

**Comment by lwb1978** [comment]
贴dns设置截图和日志上来看看

**Comment by lwb1978** [comment]
经过测试确认，标准GFW代理模式下，无论是dnsmasq或者是chinadns-ng分流模式下均正常进行科学访问，请自行检查你的路由pw上游是否套有其他的dns插件。

**Comment by yiheng603** [comment]
我遇到的问题跟楼主完全一样
Passwall 版本【 24.12.17 】  ChinaDNS-NG 版本【 2024.11.17 】  Sing-Box 版本【 1.10.3 】  Xray 版本【 24.12.15 】  Hysteria 版本【 v2.6.0 】

**Comment by yiheng603** [comment]
就是感觉这个GW list没有调用，GWF List里是空的，可以read list，但保存后就变成空白了，GWF list空白的所以就不起作用了，应该是软件的BUG

**Comment by lwb1978** [comment]
> 就是感觉这个GW list没有调用，GWF List里是空的，可以read list，但保存后就变成空白了，GWF list空白的所以就不起作用了，应该是软件的BUG

这个列表本来就是只让你看，不是让你保存的，你保存后想在看就继续点读取列表。我加这个按钮就是让你们在打开这个页面的时候不立即加载10万条数据以至于某些人的浏览器卡死。你gfw失效自己找原因吧。

**Comment by pbclaodentm** [comment]
> 经过测试确认，标准GFW代理模式下，无论是dnsmasq或者是chinadns-ng分流模式下均正常进行科学访问，请自行检查你的路由pw上游是否套有其他的dns插件。

还得是大佬牛，一句话就解决了困扰我多年的问题，我也是一直用最新版的pw，目前都更新到25.5.16，切换到GFW模式，就会出现莫名其妙的问题，比如测试正常，但看youtube看几秒就开始 转圈之类的，由于是旁路由，我关闭了所有上下游的ipv6等依然无法解决，一直用的是“中国列表以外”模式正常使用，刚才看到让检查dns，我就直接关闭了旁路有上的smart dns 和AdGuard Home，目前切换到GFW就感觉没问题了，速度很快，也不转圈了。         btw，这两个模式有啥不同之处呢，感觉都一样感受上感觉不出啥差别，怎么测试这两个模式的差别呢？
