### ISSUE TITLE
[Bug]: passwall添加新的节点，会导致现有节点断线

### ISSUE THREAD

**Issue by qq1527949891** [xiaorouji/openwrt-package#3488]
### 描述您遇到的bug

passwall添加新的节点，会导致现有节点断线，尤其在使用访问控制功能的时候，局域网客户机稳定练连接，如果这个时候去修改某个节点或者新增某个节点的时候，就会导致所有在线的节点掉线，请问是否有办法可以解决

### 复现此Bug的步骤

节点列表，点击添加，前提节点列表存在节点，并且节点正在呗使用，这个使用添加新的节点，就会导致呗使用的节点掉线了

### 您想要实现的目的

我希望在添加节点或者修改节点的时候，保持现有节点不掉线路，我使用的全是SK5,都是单条添加的，不是订阅

### 日志信息

添加的时候好像没有日志产生

### 系统相关信息

4.78-4

**Comment by lwb1978** [comment]
插件开发之初就是这样设计的，并不是什么bug。pw各板块都密切关联，牵一发而动全身，一处小小的配置改动就需要重新加载Core。pw只是个插件，它无法直接与各个Core进行交互，只能写好配置让Core来读取，通知Core读取新配置的办法就是kill掉然后重新启动它。
