### ISSUE TITLE
[Bug]: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法使用iptables+ipset透明代理

### ISSUE THREAD

**Issue by hubgha163** [xiaorouji/openwrt-package#3489]
### 描述您遇到的bug

openwrt 23.05.4 dnsmasq-full不支持ipset, 只支持nftset,安装passwall后提示系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法使用iptables+ipset透明代理

### 复现此Bug的步骤

openwrt 23.05.4

### 您想要实现的目的

openwrt 23.05.4

### 日志信息

系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法使用iptables+ipset透明代理

### 系统相关信息

passwall4.78-4

**Comment by lwb1978** [comment]
pw高级设置里面防火墙工具选择nftables，你非要用iptables吗？如果非要用iptables，那么就自行把iptables的依赖安装全了。这是最基础的东西了……
