### ISSUE TITLE
[Feature Request]: 自动更新订阅应该提供选项“绕过代理”更新

### ISSUE THREAD

**Issue by wingkinl** [xiaorouji/openwrt-package#3491]
### 描述你想要的新功能

当订阅的线路失效后，即使开启了定时自动更新订阅也因为无法联网而更新失败。以至于用户必须手动执行下述步骤：

1. 关闭主开关
2. 手动订阅更新
3. 重新开启主开关

### 描述你想要的解决方案

在节点订阅设置里提供选项让用户选择绕过代理更新

### 描述你考虑过的替代方案

或者使用某种逻辑，先临时关闭代理开关，更新订阅，最后再重新打开代理。
或者提供某种api，让用户可以在 ssh 里调用打开/关闭开关，更新订阅等功能。

**Comment by lwb1978** [comment]
程序设计是自动判断的，优先通过代理更新，如果代理更新失败则改用直连更新

**Comment by wingkinl** [comment]
> 程序设计是自动判断的，优先通过代理更新，如果代理更新失败则改用直连更新

这个设计很合逻辑，但实际情况是我已经在订阅里设置了每天早上8点更新（因为我观察发现早上7点多开始断），但查看日志发现更新失败了，还是得手动跑一遍关闭-更新-开启的三步才能正常更新。

**Comment by lwb1978** [comment]
这种情况很好理解，你的机场链接是国外域名或者解析出来是国外ip，开启pw后你机场的ip已经被写到了代理的ipset中，当你节点失效后由于你没有开启自动切换或者负载均衡，或者你所有节点全部都失效了，那么所有添加到代理的ipset都不通了，这时你就必须得关闭pw，删除代理ipset，那么才能让你的机场从直连访问。
你要解决这个问题也简单，直接把你机场域名添加到直连列表就行，以后就全部通过直连访问你的机场。

**Comment by wingkinl** [comment]
> 你要解决这个问题也简单，直接把你机场域名添加到直连列表就行，以后就全部通过直连访问你的机场。

感谢！我昨天按这个办法修改了设置，确实可以了。不过，如果能在订阅里提供选项直连，可能还是会方便用户。但不管怎样，我满意现在这个方法。

**Comment by lwb1978** [comment]
> > 你要解决这个问题也简单，直接把你机场域名添加到直连列表就行，以后就全部通过直连访问你的机场。
> 
> 感谢！我昨天按这个办法修改了设置，确实可以了。不过，如果能在订阅里提供选项直连，可能还是会方便用户。但不管怎样，我满意现在这个方法。

这个后期有空再弄，毕竟有变相解决的办法，目前还有其他优先级要高一些的工作要做。

**Comment by saogongchenmoon** [comment]
> > 你要解决这个问题也简单，直接把你机场域名添加到直连列表就行，以后就全部通过直连访问你的机场。
> 
> 感谢！我昨天按这个办法修改了设置，确实可以了。不过，如果能在订阅里提供选项直连，可能还是会方便用户。但不管怎样，我满意现在这个方法。

你好，请问你直连列表里添加的是机场订阅链接还是机场官网的域名？
最近Justmysocks频繁更新ip，导致自动更新总是失效，哪怕订阅更新里选直连也不行，必须手动关闭，更新，再开，或者选择一个可用的节点才能更新成功，我试着把订阅链接放在直连列表里，没有成功，现在测试下机场官网域名看看。
