### ISSUE TITLE
[Bug]: openwrt和imm主线更新成了apk导致pw依赖检测无法过了。编译也有问题。

### ISSUE THREAD

**Issue by ZqinKing** [xiaorouji/openwrt-package#3495]
### 描述您遇到的bug

主线升级apk导致通过opkg确定依赖出现问题，从而影响功能。同时原有的PKG_VERSION和PKG_RELEASE也导致apk无法正常签名。

### 复现此Bug的步骤

是用最新主线无法正常编译及使用。

### 您想要实现的目的

适配主线更新的apk

### 日志信息

kmod-nft-socket
kmod-nft-tproxy
kmod-nft-nat
均检测未安装。

### 系统相关信息

4.78-4

**Comment by uingei** [comment]
似乎要加上 PKG_REALVERSION 变量了

**Comment by hcym** [comment]
用2410，足够新了

**Comment by ZqinKing** [comment]
> 似乎要加上 PKG_REALVERSION 变量了

是的，PKG_VERSION:=4.78 PKG_RELEASE:=4就可以正常编译，当然关闭USE_APK恢复opkg也是可以的。

**Comment by ZqinKing** [comment]
> 用2410，足够新了

是的，现阶段用24.10比较稳妥

**Comment by lwb1978** [comment]
下个版本将采用发布时间作为版本号，不过现在很多依赖也还并没有修改

**Comment by Aukansh** [comment]
app.sh修改213跟217行
			[ -s "/lib/apk/packages/${depends}.list" ] || echolog "$tables透明代理基础依赖 $depends 未安装..."
		done
	else
		for depends in "kmod-nft-socket" "kmod-nft-tproxy" "kmod-nft-nat"; do
			[ -s "/lib/apk/packages/${depends}.list" ] || echolog "$tables透明代理基础依赖 $depends 未安装..."

**Comment by lwb1978** [comment]
@xiaobaishu1 感谢提供，我没有这么新的版本，不知道新的目录，请再次确认一下是/lib/apk不是/usr/lib/apk目录吧，我这就修改代码

**Comment by ZqinKing** [comment]
> /usr/lib/apk

不是/usr/lib/apk

**Comment by lwb1978** [comment]
> > /usr/lib/apk
> 
> 不是/usr/lib/apk

感谢

**Comment by ZqinKing** [comment]
> 下个版本将采用发布时间作为版本号，不过现在很多依赖也还并没有修改

好多插件都有这个问题呢，所以现阶段主线编译还是建议关闭USE_APK。保持opkg。
