### ISSUE TITLE
[Bug]: 使用passwall 使用节点，一切都能ping通，就是打不开YouTube等网页

### ISSUE THREAD

**Issue by mahemin0725** [xiaorouji/openwrt-package#3498]
### 描述您遇到的bug

网页底部状态显示节点国家和4个图标都点亮。但是无法打开YouTube网页，显示你没有联网，请检查网络连接。
但是相同节点，使用SSR+相同节点访问正常，感觉是DNS问题。
所有DNS设置都是使用插件默认

### 复现此Bug的步骤

1.添加可用节点
2. 选择节点。打开主开关
3. 一开始点击谷歌和ins测试连接失败，过一会就都可以ping通
4. 网页底部显示节点的国家，4个图标都点亮。
5. 就是无法打开YouTube网页，无法使用Google等网页
6. 怀疑是默认DNS问题
7. 使用SSR+，一切正常，节点是好的。

### 您想要实现的目的

想用passwall 和passwall 2来科学

### 日志信息

2024-11-16 03:47:11: 清空并关闭相关程序和缓存完成。
2024-11-16 03:47:11: TCP节点：[a6f8d8e6-vless_reality_vision]，监听端口：1041
2024-11-16 03:47:11: UDP节点：与TCP节点相同
2024-11-16 03:47:11: DNS域名解析：
2024-11-16 03:47:11:   * 请确认上游 DNS 支持 TCP/DoT/DoH 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-11-16 03:47:11:   - ChinaDNS-NG(127.0.0.1#15353)：直连DNS：223.5.5.5，可信DNS：tcp://1.1.1.1#53
2024-11-16 03:47:11:   - 防火墙域名表(gfwlist)：tcp://1.1.1.1#53
2024-11-16 03:47:11:   - 中国域名表(chnroute)：223.5.5.5
2024-11-16 03:47:11:   - 域名白名单(whitelist)：223.5.5.5
2024-11-16 03:47:11:   - 代理域名表(blacklist)：tcp://1.1.1.1#53
2024-11-16 03:47:11:   - 节点列表中的域名(vpslist)：223.5.5.5
2024-11-16 03:47:11:   - 默认：127.0.0.1#15353
2024-11-16 03:47:11:   - ChinaDNS-NG已作为Dnsmasq上游，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-11-16 03:47:12: 开始加载防火墙规则...
2024-11-16 03:48:24:   - [0]追加ISP IPv4 DNS到白名单：223.5.5.5
2024-11-16 03:48:24:   - [1]加入所有IPv4节点到nftset[passwall_vpslist]直连完成
2024-11-16 03:48:24:   - [1]加入所有IPv6节点到nftset[passwall_vpslist6]直连完成
2024-11-16 03:48:25:   - [0]追加WAN IP到nftables：10.0.0.2
2024-11-16 03:48:25:   - [0]追加直连DNS到nftables：223.5.5.5:53
2024-11-16 03:48:25:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-11-16 03:48:26:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2024-11-16 03:48:26:   - 访问控制：
2024-11-16 03:48:26:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-11-16 03:48:26:      - 【默认】，使用 TCP 节点[a6f8d8e6-vless_reality_vision](REDIRECT:1041)
2024-11-16 03:48:26:      - 【默认】，使用 UDP 节点[a6f8d8e6-vless_reality_vision](TPROXY:1041)
2024-11-16 03:48:26: 防火墙规则加载完成！
2024-11-16 03:48:27: 重启 dnsmasq 服务
2024-11-16 03:48:27: 配置定时任务：自动更新规则。
2024-11-16 03:48:27: 运行完成！

### 截图

<img width="1374" alt="截屏2024-11-16 03 48 51" src="https://github.com/user-attachments/assets/7d5020c9-b17e-4e65-802b-e0dec0280024">
<img width="1379" alt="截屏2024-11-16 03 50 07" src="https://github.com/user-attachments/assets/9724c05d-38f8-41ea-aa7f-64794cb88d71">
<img width="1171" alt="截屏2024-11-16 03 50 44" src="https://github.com/user-attachments/assets/4c861c1a-e5ea-4358-81f0-f56dca5264af">

### 系统相关信息

Passwall 版本【 25.319.35174~4ae9bbc 】

**Comment by Aukansh** [comment]
![image](https://github.com/user-attachments/assets/2fbfdf24-c628-4711-8e5c-baf651c39a73)
![image](https://github.com/user-attachments/assets/a1d5a5f6-d92f-4f30-b0b9-85975812f469)
![image](https://github.com/user-attachments/assets/ee6b5a59-ee56-4fd5-bdcf-71c6d7856708)
![image](https://github.com/user-attachments/assets/15dd2e1c-b73a-4b06-a879-86ca6d9b3ee0)

**Comment by lwb1978** [comment]
你使用了smartdns，
1.在使用pw1主线版本的话测试本地dns不要用自动，设置为实际dns地址
2.在使用pw-smartdns版本的话远程dns不要用smartdns的127.0.0.1:15335地址，设置成远程实际dns地址。
3.关闭smartdns后测试

**Comment by lwb1978** [comment]
我现在怀疑是你smartdns设置有问题

**Comment by mahemin0725** [comment]
<img width="1512" alt="截屏2024-11-16 13 13 13" src="https://github.com/user-attachments/assets/1013ac98-0571-4506-94e8-58484df580e4">
<img width="1512" alt="截屏2024-11-16 13 13 08" src="https://github.com/user-attachments/assets/f09de35c-7570-4fd0-8311-d1dbee861290">
<img width="1304" alt="截屏2024-11-16 13 17 14" src="https://github.com/user-attachments/assets/e0ac2e9a-f247-46a4-896c-b984a3f043ee">
<img width="1512" alt="截屏2024-11-16 13 17 36" src="https://github.com/user-attachments/assets/02cff9f4-229e-4851-b06c-5d722dc5e00d">
<img width="1512" alt="截屏2024-11-16 13 17 54" src="https://github.com/user-attachments/assets/7c89f351-5cc3-4d77-9c51-aaffdd7f7d5a">

首先感谢2位大佬的回复！
本人确实不太懂智能DNS在哪里设置？如果需要可以回复里指导一下吗？
我直连DNS已经修改了阿里DNS，远程DNS也指定了谷歌dns，访问油管、谷歌等网站，依旧无法打开。如果需要截图，我可以再给。
这个问题困扰了很久，大约在今年3、4月份之后的passwall 不区分1和2的版本（R4s的openwrt.ai网站编译）的固件后，一直都无法使用，可能是我们这些小白都遇到的问题吧。能在帮忙看看吗？
再次感谢！

**Comment by Aukansh** [comment]
> <img alt="截屏2024-11-16 13 13 13" width="1512" src="https://private-user-images.githubusercontent.com/62441899/386821236-1013ac98-0571-4506-94e8-58484df580e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzczNTEsIm5iZiI6MTczMTczNzA1MSwicGF0aCI6Ii82MjQ0MTg5OS8zODY4MjEyMzYtMTAxM2FjOTgtMDU3MS00NTA2LTk0ZTgtNTg0ODRkZjU4MGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNTU1NzMxMzQ0MWI2ZTE3NDljZTMwYjAxNzY5NzQ0YzBhOWY1Mjk1NWNhMDk3ODc3MDRjODViMDVlY2U0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.baj3B8b8VHb9iW2ReZFqThlaaW4h-2t0O3BbMXGcgvw"> <img alt="截屏2024-11-16 13 13 08" width="1512" src="https://private-user-images.githubusercontent.com/62441899/386821282-f09de35c-7570-4fd0-8311-d1dbee861290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzczNTEsIm5iZiI6MTczMTczNzA1MSwicGF0aCI6Ii82MjQ0MTg5OS8zODY4MjEyODItZjA5ZGUzNWMtNzU3MC00ZmQwLTgzMTEtZDFkYmVlODYxMjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZDhiNWEwMjkwODgwMTAwNDNjNDg5NGFmOWFlMDJkNmZkYmZlMzk5YzQ2ZjBlZmI4MWE1MzI5MTEzNWZhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NAfkHU5VODMUeZKxiz8b616-tFdJpKyc8jWT8vrE2Ms"> <img alt="截屏2024-11-16 13 17 14" width="1304" src="https://private-user-images.githubusercontent.com/62441899/386821480-e0ac2e9a-f247-46a4-896c-b984a3f043ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzczNTEsIm5iZiI6MTczMTczNzA1MSwicGF0aCI6Ii82MjQ0MTg5OS8zODY4MjE0ODAtZTBhYzJlOWEtZjI0Ny00NmE0LTg5NmMtYjk4NGEzZjA0M2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmE2NmZmNTRhZGVlMTY4MTYyZTNkZTkwODFlNmI2NWNkNDJhNTRhMjIyOTUyZWFjMWIxYjg1MTAzY2ZjOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RWqqXn9RCbpHT_QLI3gJEMbdCYmONbdmkV_N5hWYPLI"> <img alt="截屏2024-11-16 13 17 36" width="1512" src="https://private-user-images.githubusercontent.com/62441899/386821483-02cff9f4-229e-4851-b06c-5d722dc5e00d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzczNTEsIm5iZiI6MTczMTczNzA1MSwicGF0aCI6Ii82MjQ0MTg5OS8zODY4MjE0ODMtMDJjZmY5ZjQtMjI5ZS00ODUxLWIwNmMtNWQ3MjJkYzVlMDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzFjYWI1N2JiNzA1MDg4N2JmMzVlZmQ5ODY0OWMwNmNhNzBlN2RkN2UwMmYyNDIyN2M5NzMzYzE2ZjMzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z_4QxNTiDWsCqBUf__q-KcgcO_6KQ7HAJ3RcrtIuuSM"> <img alt="截屏2024-11-16 13 17 54" width="1512" src="https://private-user-images.githubusercontent.com/62441899/386821486-7c89f351-5cc3-4d77-9c51-aaffdd7f7d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MzczNTEsIm5iZiI6MTczMTczNzA1MSwicGF0aCI6Ii82MjQ0MTg5OS8zODY4MjE0ODYtN2M4OWYzNTEtNWNjMy00ZDc3LTljNTEtYWFmZmRkN2Y3ZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZTE3YjgxNjVhOTU5NDI0YWZlYTVjMTU1YWZiOTRkMjAzNDIwN2JlYzAzZjRiMGFlYzhjNmYwZDdlY2ZjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LiiicD55oqwl0933eS2w6Kpxl4kOJZ0lfVu8qR0YSl0">
> 首先感谢2位大佬的回复！ 我确实不太懂智能DNS在哪里设置？如果需要可以回复里指导一下吗？ 我直连DNS已经修改了阿里DNS，远程DNS也指定了谷歌dns，访问油管、谷歌等网站，仍然无法打开。如果需要截图，我可以再给。 这个问题困扰了很久，大约在今年3、4月份之后的passwall不区分1和2的版本（R4s的openwrt.ai网站编译）的固件后，一直无法使用，可能是我们这些小白都遇到的问题吧。能帮忙看看吗？ 再次感谢！

你的插件几百个肯定有劫持冲突！你固件就装一个passwall看看能不能用不就知道是不是其他插件的锅了！

**Comment by GaeaRuiW** [comment]
我也遇到了同樣的問題，請問樓主解決了嘛

**Comment by mahemin0725** [comment]
没有，我退回到了老版本的Passwall就好了，我试过就单独一个Passwall依旧不行。。

> 我也遇到了同樣的問題，請問樓主解決了嘛

**Comment by EclipseEra** [comment]
> 没有，我退回到了老版本的Passwall就好了，我试过就单独一个Passwall依旧不行。。
> 
> > 我也遇到了同樣的問題，請問樓主解決了嘛

可以给一下老版本的passwall版本么，我也是vless和torjan能ping通但不能用，ssr的节点一切正常，谢谢

**Comment by EclipseEra** [comment]
> 没有，我退回到了老版本的Passwall就好了，我试过就单独一个Passwall依旧不行。。
> 
> > 我也遇到了同樣的問題，請問樓主解決了嘛

可以给一下老版本的passwall版本号么，我也是vless和torjan能ping通但不能用，ssr的节点一切正常，谢谢

**Comment by dddibbb** [comment]
我是设置了分流节点以后，只有YouTube打不开，其他都能访问，YouTube也能Ping通，就是打不开网页。

**Comment by annce** [comment]
cmd里输ipconfig /flushdns
还不行的话清浏览器缓存

**Comment by gonixoud** [comment]
> 我也遇到同样的问题，请楼主解决啦

请问是怎么解决的 求教
