### ISSUE TITLE
[Bug]: XHTTP 下行分离配置 alpn 没生效

### ISSUE THREAD

**Issue by lxhao61** [xiaorouji/openwrt-package#3502]
### 描述您遇到的bug

XHTTP 下行分离配置 alpn 没生效。

### 复现此Bug的步骤

XHTTP 下行分离配置 alpn 没生效，具体表现为加载配置中 TCP_UDP_SOCKS.json 中无此参数。

### 您想要实现的目的

1、希望 XHTTP 下行分离配置 alpn 参数设置有效，下行可以用 HTTP/3 传输。
2、另外希望响应作者倡议：[GUI 可以正式将 SplitHTTP 更名为 XHTTP](https://github.com/XTLS/Xray-core/releases/tag/v24.11.11) 。

### 日志信息

此无必须日志。

### 系统相关信息

passwall 版本 4.78-4

**Comment by lwb1978** [comment]
@Pacalini 下行分离代码从你在PW2提交的代码搬过来的，得空看看提交的代码是否有误。🤝

**Comment by lwb1978** [comment]
Fix from: @Pacalini
