### ISSUE TITLE
[Bug]: 在使用分流节点时的异常dns请求行为

### ISSUE THREAD

**Issue by jjlizz** [xiaorouji/openwrt-package#3503]
### 描述您遇到的bug

在使用xray分流节点时存在异常dns请求行为

### 复现此Bug的步骤

1.运行模式设置只有大陆直连，其余代理
2.节点使用xray分流节点，使用xray分流规则进行进一步分流，如节点列表中分别有US和HK两个节点，设置默认节点为HK，"domain:youtube.com"使用US节点
3.DNS使用chinadns-ng分流，直连dns为国内dns如223.5.5.5，远程dns经过xray代理使用可信dns如1.1.1.1，默认dns为“智能，不接受直连dns空响应”
4.当客户端访问其余经过默认节点的域名，如x.com，dns请求通过设置中的远程dns完成，返回可信的地址，域名可以正常访问，当客户端访问youtube.com时，命中xray分流规则，预计应该同样使用远程dns返回可信地址，但程序的实际行为为，只向直连dns发送了dns请求（即便设置默认dns在检测到是直连域名时应该同时向直连dns和远程dns发送请求，在这里也只向直连dns发送了请求），直连dns返回了空响应或者被污染的地址，客户端访问youtube.com失败。

### 您想要实现的目的

1.dns分流应同样对分流节点生效，即在命中xray分流规则后，如果xray分流规则为直连，则使用直连dns进行查询，如果是其他非默认的代理节点，应使用远程dns进行查询
2.如果上述效果无法达到，应至少强制使用远程dns而非直连dns进行查询，以免返回被污染的结果导致访问失败

### 日志信息

none

### 系统相关信息

Passwall版本：本人使用11.16日的源码进行自行编译，但该问题似乎出现在所有版本中

**Comment by quanljh** [comment]
> 即便设置默认dns在检测到是直连域名时应该同时向直连dns和远程dns发送请求，在这里也只向直连dns发送了请求
1. 有chinadns ng 的log 嘛，你怎么知道只向直连dns发出了请求
2. 试试看换成默认dns 换成远程

**Comment by jjlizz** [comment]
编译11.17版本后似乎dns分流已经彻底失效
设置如下

**_dns分流：chinadns-ng
直连dns协议：通过udp请求
直连dns：10.0.0.1:53（docker自建第一个adguardhome，转发多个国内dns上游）
过滤模式：通过udp请求
远程dns：10.0.0.1:61000（docker自建第二个adguardhome，通过xray伪装转发多个可信dns上游）
默认dns：远程dns_**

以上设置似乎无论使用任何节点，根据adguardhome日志，所有dns请求均通过直连dns向国内dns上游查询

**Comment by gitbruc** [comment]
只用dnsmasq，我也不正常，不用ng就好了
