### ISSUE TITLE
[Bug]: SOCKS分流24.11.18版本TCP节点失败

### ISSUE THREAD

**Issue by hermanb001** [xiaorouji/openwrt-package#3507]
### 描述您遇到的bug

更新24.11.18后，SOCKS分流的TCP节点失败

### 复现此Bug的步骤

1. 主页面创建SOCKS，选择Singbox，添加vless节点
2. 创建分流节点，选择第一步创建的SOCKS作为默认节点
3. 主页面TCP节点选择分流节点，保存应用

### 您想要实现的目的

4.78版本没有问题

### 日志信息

![image](https://github.com/user-attachments/assets/a5c169b9-ef97-4422-bbcf-9aeccb51a0c6)

### 截图

![image](https://github.com/user-attachments/assets/216852ff-5d0c-4726-957b-f30b6f485640)

### 系统相关信息

Passwall 版本24.11.18，LUCI 23.05

**Comment by lwb1978** [comment]
你提到的几个关键的地方设置的截图来看看，因为表述得不是很清楚

**Comment by hermanb001** [comment]
![image](https://github.com/user-attachments/assets/741840b3-9fb2-4ff7-95af-00a8f66c5419)
![image](https://github.com/user-attachments/assets/37539a6b-c508-43b4-9738-c7ecb2ef6fb4)
![image](https://github.com/user-attachments/assets/5dea87d8-83c4-4d74-a163-95c58295ffd7)

**Comment by lwb1978** [comment]
试试改用xray分流正常吗？

**Comment by hermanb001** [comment]
![image](https://github.com/user-attachments/assets/6e418d10-9ca6-451d-a409-febe52d2fe83)
![image](https://github.com/user-attachments/assets/8f04e2cc-1456-443e-8522-980d63caabae)
选择xray之后

**Comment by lwb1978** [comment]
@xiaorouji

**Comment by mofanxt** [comment]
@xiaorouji 看起来和[这次 commit](https://github.com/xiaorouji/openwrt-passwall/commit/659051a9762b507d75d686a6de8d39d7a31ea875) 有关？
passwall2 也有一个类似的问题，我提了 issue：https://github.com/xiaorouji/openwrt-passwall2/issues/696

**Comment by lwb1978** [comment]
老大这几天提交了几个 utils 修改，不过我使用xray分流倒是没发现问题。

**Comment by hermanb001** [comment]
老大撤销了11.18，我已经安装了，怎么退回4.78？
