### ISSUE TITLE
[Bug]:节点加了域名就超时 用正常的普通节点就正常 

### ISSUE THREAD

**Issue by AW222121312** [xiaorouji/openwrt-package#3510]
### 描述您遇到的bug

节点加了域名就超时 用正常的普通节点就正常    在正常手机小火箭上使用正常 都可以使用

### 复现此Bug的步骤

在正常手机小火箭上使用正常 都可以使用 

### 您想要实现的目的

不知道是不是设置问题 passwall版本为4.6的 在正常手机小火箭上使用正常 都可以使用

### 日志信息

节点加了域名就超时 用正常的普通节点就正常    

### 截图

节点加了域名就超时 用正常的普通节点就正常   

### 系统相关信息

在正常手机小火箭上使用正常 都可以使用

### 其他信息

在正常手机小火箭上使用正常 都可以使用

**Comment by h2clr** [comment]
我的也差不多 从上一个版本开始不能用了
REALITY+vision 不能用

只有vision 就可以。

但其他插件没问题。

最新的版本还是不能用

**Comment by pata166** [comment]
lede 23.05最新编译固件，拉取passwall最新24.18
默认设置passwall无异常
协议-VLESS_Reality_Vision
搭配mosdns也是Ok

**Comment by handsomeji** [comment]
@lwb1978

**Comment by lwb1978** [comment]
1、2楼的同学能否提供节点测试？我没有这类节点，如果可以的话我再发邮箱地址。

**Comment by quanljh** [comment]
reality+vison 最近这几个版本我都没问题，请检查自己的设置。

**Comment by lwb1978** [comment]
既然不肯提供节点测试，那就当没问题了。关闭~
