### ISSUE TITLE
[Bug]: trojan订阅解析错误，跳过此节点。

### ISSUE THREAD

**Issue by firkerword** [xiaorouji/openwrt-package#3511]
### 描述您遇到的bug

![image](https://github.com/user-attachments/assets/de74a2a0-2901-471f-962d-8e8ef196d02a)
机场的订阅链接升级之后无法订阅成功，提示：解析错误，跳过此节点

### 复现此Bug的步骤

机场订阅更新

### 您想要实现的目的

寻求解决办法。

### 日志信息

上图所示

### 系统相关信息

![image](https://github.com/user-attachments/assets/1a256fe8-9676-4d26-a1b5-b64bf6cc3c0a)
X86-64系统

**Comment by lwb1978** [comment]
fix
