### ISSUE TITLE
[Bug]: Passwall luci-smartdns-dev 24.11.18版没有smartdns的选项

### ISSUE THREAD

**Issue by redfrog999** [xiaorouji/openwrt-package#3512]
### 描述您遇到的bug

刚刚编译的24.11.18版，DNS选项的子项里没有出现以前一直有的smartdns选项，是不是出现了bug。现在只有Dnsmasq和Chinadns-NG（推荐）这两个选项了。

### 复现此Bug的步骤

1.点击DNS
2.点选DNS分流
3.可以看到分流选项只有两个。

### 您想要实现的目的

恢复smartdns子选项

### 日志信息

这个并不需要。

### 截图

![快照2](https://github.com/user-attachments/assets/a1f87fc7-033c-471c-9e83-b62459b274cc)

### 系统相关信息

Passwall版本 24.11.18-smartdns-dev
ungoogleChrome 130.0.6723.91

**Comment by lwb1978** [comment]
已修复
