### ISSUE TITLE
[Bug]: 使用LEDE 源码编译固件无法拉取最新版本

### ISSUE THREAD

**Issue by pata166** [xiaorouji/openwrt-package#3513]
### 描述您遇到的bug

feeds.conf.default添加src-git passwall https://github.com/xiaorouji/openwrt-passwall
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2
后一直拉取的[4.78-3]
之后更新的版本无法拉取
添加sed -i '1i src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
sed -i '2i src-git small https://github.com/kenzok8/small' feeds.conf.default
也是一样

虚拟机重新全新安装，再编译也是一样

### 复现此Bug的步骤

Passwall 版本【 4.78-3 】  最新版本：24.11.18，目前暂不支持自动更新，如需更新，请自行编译或下载 ipk 然后手动安装。

### 您想要实现的目的

  之前编译正常

### 日志信息

  Passwall 版本【 4.78-3 

### 系统相关信息

Passwall 版本【 4.78-3 】

**Comment by gssiwmd** [comment]
错误同上

**Comment by pata166** [comment]
4.78-3之前版本编译可以正常更新

**Comment by gssiwmd** [comment]
找到原因了：lede luci-23.05中居然包含luci-app-passwall和luci-app-passwall2

**Comment by lwb1978** [comment]
服了，这也来pw反馈bug，另外pw从来就没支持过自动更新自身。

**Comment by whatpig** [comment]
> 找到原因了：lede luci-23.05中居然包含luci-app-passwall和luci-app-passwall2

怎么解决的？
