### ISSUE TITLE
[Bug]: smartdns版本名字还是不对，APK编译会出错

### ISSUE THREAD

**Issue by kxjhcmc** [xiaorouji/openwrt-package#3515]
### 描述您遇到的bug

ERROR: failed to create package: /workdir/openwrt/bin/packages/x86_64/base/luci-app-passwall-24.11.18.smartdns-r4.apk: package version is invalid

### 复现此Bug的步骤

不需要

### 您想要实现的目的

修复

### 日志信息

ERROR: failed to create package: /workdir/openwrt/bin/packages/x86_64/base/luci-app-passwall-24.11.18.smartdns-r4.apk: package version is invalid

### 系统相关信息

passwall  24.11.18

**Comment by lwb1978** [comment]
没搞清apk版本号的规则，估计不允许带字符，不知道是否支持如：24.11.18.74 带4个小数点数字的版本号？

**Comment by kxjhcmc** [comment]
> 没搞清apk版本号的规则，估计不允许带字符，不知道是否支持如：24.11.18.74 带4个小数点数字的版本号？

下面是chatgpt提供信息，供参考：
根据你提供的错误信息，ERROR: failed to create package: ... package version is invalid，问题主要出在版本号的格式上。以下是一些可能导致这个错误的原因，以及相应的解决建议：

可能的问题
版本号格式不符合规范：

24.11.18.smartdns-r4 的格式可能不符合预期。通常，版本号应为 MAJOR.MINOR.PATCH 格式，附加信息应该以 + 开头。
附加信息位置不当：

在版本号后直接添加 .smartdns-r4 可能导致解析错误。标准做法是使用 + 连接附加信息。
版本号的合法性：

确保版本号的每一部分都是数字，并且符合语义。某些系统可能对版本号的合法性有严格要求。
解决建议
修改版本号格式：

将版本号修改为符合规范的格式，例如：
luci-app-passwall-24.11.18+smartdns-r4.apk
检查 APKBUILD 文件：

在 APKBUILD 文件中，确保 pkgver 和 pkgrel 的定义是正确的，并且与文件名保持一致。
使用标准版本号：

确保版本号的主版本号（MAJOR）从 1 开始，避免使用年份或其他非标准数字。
重新编译：

修改完成后，重新运行编译命令，检查是否仍然存在错误。
示例
如果你的 APKBUILD 文件中有如下内容：

pkgname=luci-app-passwall
pkgver=24.11.18
pkgrel=1
那么将生成的 APK 文件名应为：

luci-app-passwall-24.11.18+smartdns-r4.apk
遵循这些建议后，应该可以解决版本号无效的问题。如果问题仍然存在，请检查编译日志中是否有其他相关错误信息。

**Comment by lwb1978** [comment]
已将smartdns合并到主线
