### ISSUE TITLE
[Bug]: IPv6节点tcping功能失效

### ISSUE THREAD

**Issue by ZqinKing** [xiaorouji/openwrt-package#3516]
### 描述您遇到的bug

如题，节点地址为IPv6，在节点列表中tcping会显示超时，实际节点可用。

### 复现此Bug的步骤

添加IPv6节点

### 您想要实现的目的

修复IPv6节点的tcping

### 日志信息

如图

### 截图

![image](https://github.com/user-attachments/assets/c354c41a-4a2f-485a-a356-29b4b068d712)

### 系统相关信息

最新版

**Comment by gnz1123** [comment]
这个可能是op版本的原因经常遇到，换成ping就正常了.

**Comment by lwb1978** [comment]
你的ipv6节点地址是ip6地址还是域名？我测试ip6地址tcping是正常的。

**Comment by ZqinKing** [comment]
是地址，请问tcping的依赖，v4和v6是一样的吗？可能是缺组件了。

**Comment by ZqinKing** [comment]
> 你的ipv6节点地址是ip6地址还是域名？我测试ip6地址tcping是正常的。

请教一下大佬，这是tcping版本问题吗？
root@AX6600:~# tcping --help
tcping: unrecognized option: -
tcping, (C) 2003 folkert@vanheusden.com

Usage
tcping [options] <destination>

Options:
  <destination>      dns name or ip address
  -c <count>         count how many times to connect
  -f                 flood connect (no delays)
  -h                 print help and exit
  -i <interval>      interval delay between each connect (e.g. 1)
  -p <port>          portnr portnumber (e.g. 80)
  -q                 quiet, only returncode
  -t <timeout>       time to wait for response (e.g. 3)

root@AX6600:~# tcping -c 1 -i 1 -t 2 2603:c024:9:8ffe:1e51:17a6:1531:34fb -p 443
2603:c024:9:8ffe:1e51:17a6:1531:34fb: Name or service not known
root@AX6600:~# tcping-simple 2603:c024:9:8ffe:1e51:17a6:1531:34fb 443
2603:c024:9:8ffe:1e51:17a6:1531:34fb port 443 open.

**Comment by ZqinKing** [comment]
是不是这个版本不对，看了一下源码，它是不支持IPv6地址的。
![image](https://github.com/user-attachments/assets/27014a00-4c8c-4939-a475-77b3022e9b9a)

**Comment by lwb1978** [comment]
我是用openwrt-passwall-packages仓库的tcping
```
tcping -help
tcping version 0.3
Usage: tcping [-fqhv] [-p port] [-c count] [-i interval] [-t timeout] destination
-p port         Port number (default port 80)
-c count        How many times to connect
-i interval     Delay between each connect
-f              Flood connect (no delays)
-q              Quiet, only returncode
-t              Set timeout when connecting
-h              This help text
```
