### ISSUE TITLE
[Bug]: 一直存在的bug，每次看油管live直播看個20秒左右，視頻就提示系統錯誤，同樣節點在電腦端直接開v2Ray就不會視頻提示錯誤。

### ISSUE THREAD

**Issue by okfate** [xiaorouji/openwrt-package#3517]
### 描述您遇到的bug

平時看油管視頻是沒問題的，但是只有看live直播視頻，每20秒左右就一定跳出下面的頁面提示，刷新後，依舊會重複。但是電腦端掛相同節點，直接看live就沒問題。
![123](https://github.com/user-attachments/assets/c868e54d-f7c4-4c7e-be45-eb9e4feab1e0)

### 复现此Bug的步骤

平時看油管視頻是沒問題的，但是只有看live直播視頻，每20秒左右就一定跳出下面的頁面提示，刷新後，依舊會重複。但是電腦端掛相同節點，直接看live就沒問題。

### 您想要实现的目的

怎麼解決這個問題？之前版本也是這樣，現在更新最新版本還是這樣。

### 日志信息

平時看油管視頻是沒問題的，但是只有看live直播視頻，每20秒左右就一定跳出下面的頁面提示，刷新後，依舊會重複。但是電腦端掛相同節點，直接看live就沒問題。

### 系统相关信息

24.11.18-4

**Comment by handsomeji** [comment]
測試無問題，請自行 F12 debug一下。看下有無報紅或者有其他域名沒有進行代理。

**Comment by okfate** [comment]
> 測試無問題，請自行 F12 debug一下。看下有無報紅或者有其他域名沒有進行代理。

解決了，是路由器ADguard把dns攔截了 .jnn-pa.googleapis.com
