### ISSUE TITLE
[Feature Request]: 新加的smartdns 增加默认dns 选项

### ISSUE THREAD

**Issue by quanljh** [xiaorouji/openwrt-package#3519]
### 描述你想要的新功能

昨天新加的 0a5c58a97e8a743a7de803def9d6f6f1d3457f15 试了下感觉可以加个默认路由功能，比如我想默认走远程路由，现在默认就是default 的路由

### 描述你想要的解决方案

加一行到/tmp/etc/smartdns/passwall.conf 搞定

domain-rules /./ -n passwall_proxy -speed-check-mode none -d no -no-serve-expired

**Comment by lwb1978** [comment]
我现在正在优化smartdns的一些设置，刚好可以讨论一下

**Comment by lwb1978** [comment]
@quanljh 
我正想加上默认路由的功能，比如直连组是cn，如果默认直连，则：
`domain-rules /./ -n cn`
默认远程，则：
`domain-rules /./ -n passwall_proxy -speed-check-mode none -d no -no-serve-expired`
这时是否还需要保留“从默认组排除”的这个选项？

**Comment by quanljh** [comment]
我觉得默认直连是不用设置的，如果 /tmp/etc/smartdns/passwall.conf 的rules 一个都匹配不到 就会通过default 分组出去
默认远程的话 我觉得 “从默认组排除” 还是要的，比如你现在我设置了 udp:1.1.1.1
`server udp://1.1.1.1 -group passwall_proxy -proxy passwall-proxy-server -exclude-default-group`
如果不加的话，我理解dns请求国内域名的时候也会向这个udp:1.1.1.1去请求, 但其实我只需要向国内的dns 服务器请求

**Comment by quanljh** [comment]
我自己的环境在 helper_smartdns_add.lua 加了下面一行，测了一下没什么问题。
UI 我没写过，不然我可以提个Draft PR
![image](https://github.com/user-attachments/assets/b5208a1e-1654-41d6-acc0-9ab592964486)

**Comment by lwb1978** [comment]
> 我自己的环境在 helper_smartdns_add.lua 加了下面一行，测了一下没什么问题。 UI 我没写过，不然我可以提个Draft PR ![image](https://private-user-images.githubusercontent.com/38105306/388496263-b5208a1e-1654-41d6-acc0-9ab592964486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTA1ODAsIm5iZiI6MTczMjE5MDI4MCwicGF0aCI6Ii8zODEwNTMwNi8zODg0OTYyNjMtYjUyMDhhMWUtMTY1NC00MWQ2LWFjYzAtOWFiNTkyOTY0NDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExNTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTUxYzIyZjUzOTZhOWYyNmUzNzZlMWFjMmY4NTgzY2Q1ZTI4YjE0MTdkM2E0NjlmM2QzMmI5MWEwMGI4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wOpEiPExyRxyvJl4FVFWwZSiDF6qyCSGN_I6fY-bm0c)

这个配置我准备废除了，刚刚写完全新的配置方式，更加直观流程更清晰，所以先不要提PR

**Comment by lwb1978** [comment]
> @quanljh 我正想加上默认路由的功能，比如直连组是cn，如果默认直连，则： `domain-rules /./ -n cn` 默认远程，则： `domain-rules /./ -n passwall_proxy -speed-check-mode none -d no -no-serve-expired` 这时是否还需要保留“从默认组排除”的这个选项？

其实我在想，加了这个在策略最前面进行托底（越靠前优先级越低）排不排除已经不重要了，看托底的是本地还是远程dns。
已经测试通过。

**Comment by snakwu** [comment]
![我刚想问来着，这个功能怎么找不到，dns模式内有两个一dnsmaq，一个是chinang，没有smartdns，已经拉取了最新代码

**Comment by lwb1978** [comment]
你没装smartdns，当然没有

**Comment by snakwu** [comment]
> 你没装smartdns，当然没有

我smartdns是装在内网的其他机器上的，一定要编译加进op吗 谢谢

**Comment by ZqinKing** [comment]
有个小建议，可以利用luci-app-smartdns的第二服务器，增加规则即可，因为有些参数pw不太方便调，如果能搭配luci-app-smatrdns的第二服务器，那么服务器本身的配置就可以在第二服务器的配置项里调整，比如禁用aaaa之类的，pw只需负责分流规则配置。

**Comment by lwb1978** [comment]
> 有个小建议，可以利用luci-app-smartdns的第二服务器，增加规则即可，因为有些参数pw不太方便调，如果能搭配luci-app-smatrdns的第二服务器，那么服务器本身的配置就可以在第二服务器的配置项里调整，比如禁用aaaa之类的，pw只需负责分流规则配置。

你既然想用第二服务器就不要使用smartdns模式就行，本身做smartdns就是为了方便使用。

**Comment by quanljh** [comment]
Tested, looks good, thanks

**Comment by quanljh** [comment]
@lwb1978 
默认远程感觉还是要排除default group， 不排除每次都要去query 远程dns
这样直接拖慢了国内dns 的查询速度，是说今天怎么感觉打开网页速度慢了一丢丢。
```
[2024-11-22 23:41:46,633][DEBUG][     dns_server.c:7196] query xiaohongshu.com from 127.0.0.1, qtype: 1, id: 24245, query-num: 10
[2024-11-22 23:41:46,633][ INFO][     dns_server.c:5264] RULE-MATCH, type: 6, domain: xiaohongshu.com, rule: xiaohongshu.com.
[2024-11-22 23:41:46,633][ INFO][     dns_server.c:5264] RULE-MATCH, type: 7, domain: xiaohongshu.com, rule: xiaohongshu.com.
[2024-11-22 23:41:46,633][ INFO][     dns_server.c:5264] RULE-MATCH, type: 8, domain: xiaohongshu.com, rule: xiaohongshu.com.
[2024-11-22 23:41:46,633][DEBUG][     dns_client.c:3855] send query to server 1.1.1.1:53
[2024-11-22 23:41:46,633][DEBUG][     dns_client.c:3855] send query to server 223.5.5.5:53
[2024-11-22 23:41:46,633][DEBUG][     dns_client.c:3855] send query to server 114.114.114.114:53
[2024-11-22 23:41:46,633][DEBUG][     dns_client.c:3855] send query to server 192.168.1.1:53
```

**Comment by lwb1978** [comment]
@quanljh 也就是说默认远程的话还需要排除掉远程dns的default group？

**Comment by quanljh** [comment]
我觉得最好排除，log 里面看出 其实查询国内dns 的时候完全不需要走远程dns

**Comment by lwb1978** [comment]
如果是查国外的话，如果没排除国内组的default group，那么是不是也会在国内组查呢？

**Comment by quanljh** [comment]
不会因为查国外指定了 nameserver， 也就是group，所以只会用这个查询
server udp://1.1.1.1 -group **passwall_proxy** -proxy passwall-proxy-server -exclude-default-group
domain-rules /./ -nameserver **passwall_proxy** -speed-check-mode none -d no -no-serve-expired

**Comment by lwb1978** [comment]
那我改下代码吧，任何情况下都排除国外组的default-group，直接写死怎么样？如果需要国内组也排除default-group的话就搞不掂了，毕竟没法去控制smartdns那边的配置。

**Comment by quanljh** [comment]
我刚刚测过了 直接写死没问题 因为passwall这边设置的dns其实就是远程dns。

**Comment by lwb1978** [comment]
已提交修改

**Comment by jxph1123** [comment]
> > @quanljh 我正想加上默认路由的功能，比如直连组是cn，如果默认直连，则： `domain-rules /./ -n cn` 默认远程，则： `domain-rules /./ -n passwall_proxy -speed-check-mode none -d no -no-serve-expired` 这时是否还需要保留“从默认组排除”的这个选项？
> 
> 其实我在想，加了这个在策略最前面进行托底（越靠前优先级越低）排不排除已经不重要了，看托底的是本地还是远程dns。 已经测试通过。


能否有第三种选择模式“默认”，相当于和之前一样，如果 /tmp/etc/smartdns/passwall.conf 的rules一个都匹配不到，就会通过smartdns的default分组出去。目的是我在smartdns里面的default里，可以定义国内和国外两种dns，用于解析passwall.conf剩余的域名（毕竟不算多了），这样可以避免剩余域名选择一种远程DNS或直连DNS有可能解析不到的局限性。

![image](https://github.com/user-attachments/assets/2f0e167e-f94f-4861-bcff-a30d1c1ef9a2)

**Comment by lwb1978** [comment]
修改这个不难，但是从易用性出发，单纯的直连和远程基本都能理解的了，如果加一个默认进去可能大部分用户都懵圈，而且还需要在smartdns那边做相应的设置，如果设置不正确可能效果适得其反，比如照成dns泄漏等。
说实话，加这个默认上去如果没有说明或者不会看代码的话，我也搞不清它的实际作用。

**Comment by jxph1123** [comment]
> 修改这个不难，但是从易用性出发，单纯的直连和远程基本都能理解的了，如果加一个默认进去可能大部分用户都懵圈，而且还需要在smartdns那边做相应的设置，如果设置不正确可能效果适得其反，比如照成dns泄漏等。 说实话，加这个默认上去如果没有说明或者不会看代码的话，我也搞不清它的实际作用。

收到，谢谢大佬。这样也行，我到smartdns那边配置想想办法。

**Comment by jxph1123** [comment]
> 修改这个不难，但是从易用性出发，单纯的直连和远程基本都能理解的了，如果加一个默认进去可能大部分用户都懵圈，而且还需要在smartdns那边做相应的设置，如果设置不正确可能效果适得其反，比如照成dns泄漏等。 说实话，加这个默认上去如果没有说明或者不会看代码的话，我也搞不清它的实际作用。

大佬，反馈个问题，开了远程DNS后，从smartdns日志看，cn分组的测速没有了（按道理只是不在列表内的走passwall_proxy分组，不应该会影响cn分组），如下图：

![XA9 @TCV~ 7OQVC9SL17O 9](https://github.com/user-attachments/assets/6d1a1ce5-4ba0-4aa8-b78d-0e36e5e6b01c)

开直连DNS，cn分组测试正常，如下图

![%1QGEP$A6_780YH{C5DX708](https://github.com/user-attachments/assets/61977de3-05f5-42c7-8c8f-47be7ca047ff)

**Comment by lwb1978** [comment]
首先你要确认你的域名是否是在中国列表内，如果在，那么你是否已经使用了中国列表列表，如果条件不达到，那么你的域名将根据你默认设置远程或者直连来确定。
从你日志来看你的域名是用cn来解析了，但具体为什么它没有测速我也解释不了了，因为我生成的配置cn组是没有写任何限制测速的参数。这个已经超出了pw能解释的范围，得把你`tmp/etc/smartdns/passwall.conf`的内容拿去smartdns那边问了。

**Comment by quanljh** [comment]
简单看了下smartdns 的代码，domain rules 好像不继承默认设置中的speek-check-mode, 而且很多都是required_argument, 测试加上-speed-check-mode ping,tcp:80 会开启测速。
https://github.com/pymumu/smartdns/blob/fdc1a41967477698c1e320fb55592df3c6213045/src/dns_conf.c#L4866C1-L4886C4

**Comment by lwb1978** [comment]
> 简单看了下smartdns 的代码，domain rules 好像不继承默认设置中的speek-check-mode, 而且很多都是required_argument, 测试加上-speed-check-mode ping,tcp:80 会开启测速。 https://github.com/pymumu/smartdns/blob/fdc1a41967477698c1e320fb55592df3c6213045/src/dns_conf.c#L4866C1-L4886C4

good，那这个就好办了，直接给直连的组加上测速代码如何？测速模式你有好的建议吗？

**Comment by quanljh** [comment]
我建议是从smartdns的设置中扣出来，把required_argument 都补上，但是我还也想问下smartdns 为啥不自动继承默认设置。

**Comment by lwb1978** [comment]
> 我建议是从smartdns的设置中扣出来，把required_argument 都补上，但是我还也想问下smartdns 为啥不自动继承默认设置。

我刚想这么说，不谋而合

**Comment by jxph1123** [comment]
我看生成的配置只有`  domain-rules /./ -nameserver cn   `和  `domain-rules /./ -nameserver passwall_proxy -speed-check-mode none -d no -no-serve-expired `这一点区别，smartdns配置不变的情况下，`  domain-rules /./ -nameserver cn`   这个就能正常测速。

**Comment by lwb1978** [comment]
> > 我建议是从smartdns的设置中扣出来，把required_argument 都补上，但是我还也想问下smartdns 为啥不自动继承默认设置。
> 
> 我刚想这么说，不谋而合

**Comment by quanljh** [comment]
我去smartdns那边问下

**Comment by lwb1978** [comment]
已经更新代码，给国内组补上了一些必要的参数（从smartdns读取）新代码经过测试，默认为远程时国内组测速正常。
可以测试一下。

**Comment by quanljh** [comment]
加了一个comment

**Comment by lwb1978** [comment]
/etc/smartdns/custom.conf下得就不管了，否则越搞越复杂了，反正pw的设置总在最后，pw的优先级最高

**Comment by lwb1978** [comment]
> 加了一个comment

这个啥意思？

**Comment by quanljh** [comment]
就是commit 上加了一个comment 😂

**Comment by quanljh** [comment]
> /etc/smartdns/custom.conf下得就不管了，否则越搞越复杂了，反正pw的设置总在最后，pw的优先级最高

其实也就是读下这个文件，它应该就是最高优先级，but 可以以后优化

**Comment by jxph1123** [comment]
> 已经更新代码，给国内组补上了一些必要的参数（从smartdns读取）新代码经过测试，默认为远程时国内组测速正常。 可以测试一下。

看日志是正常了，感谢大佬

**Comment by jxph1123** [comment]
> 我建议是从smartdns的设置中扣出来，把required_argument 都补上，但是我还也想问下smartdns 为啥不自动继承默认设置。

其实我一直在奇怪为啥选直连DNS的时候能读到配置？测速正常？

**Comment by lwb1978** [comment]
再次提交修改，把默认值和/etc/smartdns/custom.conf读取都加上了，就是代价有点高，读个参数要了不少代码量。

**Comment by quanljh** [comment]
> 其实我一直在奇怪为啥选直连DNS的时候能读到配置？测速正常？

我拿源码随便测了下发现
选默认时 `domain-rules /b.com/ -nameserver default ` 看起来会继承或者是代码里面默认配置了speed check mode
选远程时 `domain-rules /./ -nameserver test -speed-check-mode none` 这个全局设置影响了 `b.com` 的speed check mode。 
![image](https://github.com/user-attachments/assets/e4772e06-230a-48a3-8b3b-fdfccd2ccb75)
诡异的behavior，b.com 使用的default group，但是却会受到 test group 的speed check mode 影响，
具体code 没仔细debug，明天有时间研究

> 再次提交修改，把默认值和/etc/smartdns/custom.conf读取都加上了，就是代价有点高，读个参数要了不少代码量。

感谢，明天我测测看，其实这样看来也就远程dns 的时候需要处理

**Comment by lwb1978** [comment]
一看便知你代码玩得比我三脚猫的溜，我在PW这里也就打打下手，如果你有兴趣可多多交流，一起研究。

**Comment by quanljh** [comment]
我也是菜逼 哈哈

**Comment by quanljh** [comment]
> 诡异的behavior，b.com 使用的default group，但是却会受到 test group 的speed check mode 影响，
具体code 没仔细debug，明天有时间研究

又抽空看了下源码， 其实还是make sense 的,  smartdns 对设置里面的domain rules创建规则时，
`speed-check-mode ping` 会作为默认配置

`domain-rules /b.com/ -nameserver default `  会给 `b.com` 创建一条 nameserver default 的 规则

`domain-rules /./ -nameserver test -speed-check-mode none`  会给 `.` 也就是 `default` domain 创建2条规则： 1条nameserver的规则和1条 speed-check-mode 的规则

当 request `b.com` 时，默认会先把默认配置 `speed-check-mode ping` set 上， 然后匹配到`default` group的规则, `speed-check-mode` 就被override 了。

主要注意的就是 `/./`  上面的规则会override 默认规则

**Comment by lwb1978** [comment]
domain-rules /./ -nameserver test -speed-check-mode none
domain-rules /b.com/ -nameserver default

意思是这样的话 b.com会被覆盖掉默认规则？

**Comment by quanljh** [comment]
对 b.com 就会用-speed-check-mode none

**Comment by lwb1978** [comment]
所以把策略的参数补齐就很有必要了，你再捋捋看远程组还应该添加什么参数，以免被直连的影响到

**Comment by lwb1978** [comment]
远程组response-mode不知道是否应该加上，看文档这个好像都不适合远程查询，因为代理不支持ping
```
模式：[first-ping|fastest-ip|fastest-response]
[first-ping]: 最快ping响应地址模式，DNS上游最快查询时延+ping时延最短，查询等待与链接体验最佳;
[fastest-ip]: 最快IP地址模式，查询到的所有IP地址中ping最短的IP。需等待IP测速;
[fastest-response]: 最快响应的DNS结果，DNS查询等待时间最短，返回的IP地址可能不是最快。
```
默认是第一个。

**Comment by quanljh** [comment]
不用单独处理，-speed-check-mode none 测试禁用了的话， first-ping 和 fastest-ip 都不生效的。

**Comment by openwrtledediy** [comment]
提一个建议，模式改成全局后，是否可以去除远程直连DNS的选项，DNS选项只保留类似于ssr plus的"使用本机5335端口dns"，谢谢
