### ISSUE TITLE
[Feature Request]: 这个，负载均衡怎么才能运行？同一协议同机场的怎么设置才能负载均衡，我记得原来有设置选项，能设置比重啥的，现在真找不啊？！

### ISSUE THREAD

**Issue by hanjia115** [xiaorouji/openwrt-package#3522]
### 描述你想要的新功能

负载均衡怎么才能运行？同一协议同机场的怎么设置才能负载均衡，我记得原来有设置选项，能设置比重啥的，现在真找不啊？！

### 描述你想要的解决方案

负载均衡点击进去可以直接设置，可以提示满足哪些条件。

### 描述你考虑过的替代方案

没有

### 其他信息

无

**Comment by hanjia115** [comment]
小肉鸡大佬？

**Comment by lwb1978** [comment]
你的固件缺少haproxy
