### ISSUE TITLE
[Bug]: 主开关无效

### ISSUE THREAD

**Issue by xiaowuap** [xiaorouji/openwrt-package#3523]
### 描述您遇到的bug

passwall开机自启/主开关均无效（不启动），此时无任何日志输出。只有通过节点订阅-手动订阅全部才能开启/关闭passwall

### 复现此Bug的步骤

正常开启关闭passwall主开关

### 您想要实现的目的

应当正常启动/关闭

### 日志信息

无

### 系统相关信息

Passwall 24.11.18
OpenWrt 23.05.5 r24106-10cc5fcd00 / LuCI openwrt-23.05 branch git-24.322.79771-ee4c08d

**Comment by xiaowuap** [comment]
安装coreutils-nohup bash dnsmasq-full curl ca-certificates ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base后解决，不知道是缺了啥。。。。。

**Comment by xiaowuap** [comment]
未解决

**Comment by xiaowuap** [comment]
且开机自启失灵

**Comment by gssiwmd** [comment]
还有一个问题是运行几个小时后，代理不通，节点测试也不通，需要重新按《保存&应用》按键后恢复。

**Comment by Aukansh** [comment]
> 且开机自启失灵

描述也不准确！什么开机不能自启动？不是开机60秒后再自行启动么？自己去高级里面看

**Comment by xiaowuap** [comment]
> > 且开机自启失灵
> 
> 描述也不准确！什么开机不能自启动？不是开机60秒后再自行启动么？自己去高级里面看

首次调的时候就已经改为5s了，不要太过主观带入。。。。

**Comment by xiaowuap** [comment]
> 还有一个问题是运行几个小时后，代理不通，节点测试也不通，需要重新按《保存&应用》按键后恢复。

你的保存应用还有用，我这里保存应用按了完全没反应

**Comment by wazzx** [comment]
固件版本：OpenWrt 23.05.5 r24106-10cc5fcd00
Passwall 版本【 24.11.18 】 ad768316eb4f6427c603b11b61cfca3b1885c5b1 最新版本
目前已经稳定运行4小时，中间开关5次以上，默认60s启动，没有上述问题出现。

**Comment by lwb1978** [comment]
自己固件上找原因吧，pw出来不是一两天了，连启动都启动不了的话早关仓库了。
