### ISSUE TITLE
[Bug]: 添加节点，类型为空是怎么回事

### ISSUE THREAD

**Issue by ring0li** [xiaorouji/openwrt-package#3530]
### 描述您遇到的bug

我想手工添加个节点，然后订阅机场，可是添加节点页面，类型选项为空
重新删除，重启，再安装，也不行

### 复现此Bug的步骤

如上

### 您想要实现的目的

不为空

### 日志信息

无

### 截图

![image](https://github.com/user-attachments/assets/7234543f-0957-42c1-a3f1-1f25b22a62aa)

### 系统相关信息

路由器：TP-Link TL-XDR6088
版本：immortalWrt 23.05.4 r28061-399f9a1db3 / LuCI openwrt-23.05 branch git-24.265.44782-0ff45d8
luci-app-passwall  4.78-4
luci-i18n-passwall-zh-cn  git-24.279.24064-ce03020

**Comment by lwb1978** [comment]
啥core组件都没装，能有类型就见鬼了。

**Comment by ring0li** [comment]
> 啥core组件都没装，能有类型就见鬼了。

我是软件管理直接安转的，依赖不是默认安转了么？  请问我哪个依赖没安转啊？

**Comment by ring0li** [comment]
> 啥core组件都没装，能有类型就见鬼了。

好了 回滚ImmortalWrt版本了。好了
