### ISSUE TITLE
[Bug]: passwall(Passwall 版本【 24.11.23-r1 】)，Instagram 连接失败（实际可以正常访问）

### ISSUE THREAD

**Issue by pata166** [xiaorouji/openwrt-package#3532]
### 描述您遇到的bug

![1](https://github.com/user-attachments/assets/f9469705-09c2-4f7e-a908-84ea47a8f6dd)
![2](https://github.com/user-attachments/assets/8df26e41-89f9-4a3d-96ec-5b3a9c676928)
![3](https://github.com/user-attachments/assets/29458c31-492b-4708-8623-e2ffa6e6fda9)

### 复现此Bug的步骤

实际使用无异常，就是如上图：Instagram 连接失败，实际是正常的

### 您想要实现的目的

这算BUG？

### 日志信息

.

### 系统相关信息

Passwall 版本【 24.11.23-r1 】)

**Comment by zhousoul** [comment]
同样情况
