### ISSUE TITLE
[Feature Request]: 恢复对TROJAN-GO的支持

### ISSUE THREAD

**Issue by robinhoo1973** [xiaorouji/openwrt-package#3536]
### 描述你想要的新功能

在查找对trojan-go的支持过程中发现九个月前drop了对其的支持，希望能够加回来。

### 描述你想要的解决方案

在查找对trojan-go的支持过程中发现九个月前drop了对其的支持，希望能够加回来。

**Comment by Aukansh** [comment]
不管是Xray还是Sing-Box都包含了这些协议了！安装其中一个不就行了！trojan-go都好几年没更新了！

**Comment by robinhoo1973** [comment]
目前的其它方式，只支持websocket，但其他的如Shadowsock加密等trojan-go特有功能均不支持

**Comment by snowie2000** [comment]
那些trojan-go特有的功能都是作者自己发明出来的，绝大多数第三方软件也都不兼容，只支持标准的trojan功能，所以你搭出来的结点基本上就是和私有协议差不多……

**Comment by lwb1978** [comment]
为减少维护量，只能废除掉小众core的支持
