### ISSUE TITLE
[Feature Request]: 增加手工设定分流规则为黑白名单的选项

### ISSUE THREAD

**Issue by moetayuko** [xiaorouji/openwrt-package#3538]
### 描述你想要的新功能

目前会自动将直连的分流规则加入 shunt_direct_host，设置代理的则加入 shunt_proxy_host。这在大多数情况下没有问题，但个别特殊用途会误分类

例如我通过如下规则给 UnblockNeteaseMusic 分流
```
config shunt_rules 'ncm_direct'
        option remarks 'ncm_direct'
        option network 'tcp,udp'
        option domain_list 'domain:music.163.com'
        option source '网关wan口ip'

config shunt_rules 'ncm'
        option remarks 'ncm'
        option network 'tcp,udp'
        option domain_list 'domain:music.163.com'

config nodes 'myshunt'
        ...
        option ncm 'v1n2XpnU'
        option ncm_direct '_direct'

config nodes 'v1n2XpnU'
        option remarks 'UnblockNeteaseMusic'
        option type 'Xray'
        option protocol 'http'
        option address '127.0.0.1'
        option port '5200'
        option tls '0'
        option tcpMptcp '0'
        option tcpNoDelay '0
```
其中 v1n2XpnU 是 UnblockNeteaseMusic 开的端口。music.163.com 会被同时加入 shunt_direct_host 和 shunt_proxy_host，从而产生混乱。

显然，music.163.com 不应被加入 shunt_proxy_host，而且因为他本来就在 chnlist 里，所以也不需要加进 shunt_direct_host

### 描述你想要的解决方案

在分流规则页面增加选项，允许用户选择：
* 黑名单
* 白名单
* 不加

**Comment by lwb1978** [comment]
目前shunt列表只有chinadns和smartdns会生成，它们两个有优先级，直连优先级比代理的高，不会混乱，且分流规则在访问控制也可以添加，一套规则可能不同的节点有不同的设置方式，所以这种情况下luci难以判断到底哪个才是真正直连或者代理，但即使都加入shunt_proxy_host中也不用担心，只不过流量会通过xray或者sing-box再次分流，会走到正确出口。

**Comment by lwb1978** [comment]
pw只是个ui，所运行的脚本做不了这么精细的活，只能最大程度的让流量通过防火墙不通过核心，但达不到的就还是得交给core来做了。能通过防火墙走的理论上不占用这么多系统资源，进入xray和sing-box的话可能要耗些cpu。
pw只能尽力了。

**Comment by moetayuko** [comment]
> 目前shunt列表只有chinadns和smartdns会生成，它们两个有优先级，直连优先级比代理的高，不会混乱，且分流规则在访问控制也可以添加，一套规则可能不同的节点有不同的设置方式，所以这种情况下luci难以判断到底哪个才是真正直连或者代理，但即使都加入shunt_proxy_host中也不用担心，只不过流量会通过xray或者sing-box再次分流，会走到正确出口。

shunt_proxy_host 会用远程 dns 解析成海外 ip，重新进核心以后即使直连也很慢

**Comment by lwb1978** [comment]
我不是说了吗，有优先级啊，直连列表是国内dns解析，他的优先级比shunt_proxy_host高

**Comment by moetayuko** [comment]
> 我不是说了吗，有优先级啊，直连列表是国内dns解析，他的优先级比shunt_proxy_host高

`/var/etc/smartdns/passwall.conf`:
```
domain-set -name passwall-whitehost -file /tmp/etc/passwall/acl/default/shunt_direct_host
domain-rules /domain-set:passwall-whitehost/ -nameserver local -nftset #4:inet#passwall#passwall_whitelist,#6: inet#passwall#passwall_whitelist6 -d yes -c ping,tcp:80,tcp:443 -r first-ping -rr-ttl-min 600
domain-set -name passwall-shuntlist -file /tmp/etc/passwall/acl/default/shunt_proxy_host
domain-rules /domain-set:passwall-shuntlist/ -nameserver passwall_proxy -speed-check-mode none -no-serve-expired -d no -nftset #4:inet#passwall#passwall_shuntlist,#6:inet#passwall#passwall_shuntlist6
```

`/tmp/etc/passwall/acl/default/shunt_direct_host`:
```
api.steampowered.com
music.163.com
```
`/tmp/etc/passwall/acl/default/shunt_proxy_host`:
```
store.steampowered.com
music.163.com
```

`/var/log/smartdns/smartdns.log`:
```
[2024-11-28 19:23:33,618][DEBUG][     dns_server.c:7202] query music.163.com from 192.168.5.3, qtype: 5, id: 39996, query-num: 1
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 0, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 6, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 7, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 8, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 10, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 11, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][ INFO][     dns_server.c:5270] RULE-MATCH, type: 14, domain: music.163.com, rule: music.163.com.
[2024-11-28 19:23:33,618][DEBUG][     dns_server.c:6582] unsupported qtype: 5, domain: music.163.com
[2024-11-28 19:23:33,618][DEBUG][     dns_client.c:3854] send query to server 1.1.1.1:853
[2024-11-28 19:23:33,618][DEBUG][     dns_client.c:2375] tls server 1.1.1.1 connecting.
[2024-11-28 19:23:33,618][ INFO][     dns_client.c:4251] request: music.163.com, qtype: 5, id: 17344, group: passwall_proxy
[2024-11-28 19:23:33,618][DEBUG][          proxy.c:546 ] server passwall-proxy-server select auth method is 0
[2024-11-28 19:23:33,619][DEBUG][          proxy.c:665 ] server passwall-proxy-server proxy dest: 127.0.0.1:1070
[2024-11-28 19:23:33,619][DEBUG][          proxy.c:724 ] success connect to socks5 proxy server passwall-proxy-server
```

music.163.com 同时出现在 shunt_direct_host 和 shunt_proxy_host，生成的 smartdns 配置文件里 whitehost 确实排在 shuntlist 前面，但最终解析的时候分到了 passwall_proxy 组，走的是远程 dns

**Comment by moetayuko** [comment]
> 目前shunt列表只有chinadns和smartdns会生成

简单起见是不是可以在「模式」那个 tab 下面加一个是否使用分流规则的勾，不勾选的话即使 smartdns 也不生成分流列表。这样的话分流规则不影响 dns，流量全部进核心，也就避免我的问题了

**Comment by moetayuko** [comment]
> 我不是说了吗，有优先级啊，直连列表是国内dns解析，他的优先级比shunt_proxy_host高

刚刚又试了一下，smartdns 规则优先级似乎是靠后的高（试下来是这样但文档里面没写），所以要让 shunt_direct_host 比 shunt_proxy_host 的优先级高的话应该把 `domain-rules /domain-set:passwall-whitehost/` 放到 `domain-rules /domain-set:passwall-shuntlist/` 之后

**Comment by lwb1978** [comment]
本来这样，要不你把你的生成的配置贴上来看看

**Comment by lwb1978** [comment]
越后加载的优先级越高，那就是越往配置的下面优先级越高，你再捋捋😂

**Comment by moetayuko** [comment]
https://github.com/xiaorouji/openwrt-passwall/pull/3539
改了以后生成的配置是这样的
```
domain-set -name passwall-shuntlist -file /tmp/etc/passwall/acl/default/shunt_proxy_host
domain-rules /domain-set:passwall-shuntlist/ -nameserver passwall_proxy -speed-check-mode none -no-serve-expired -d no -nftset #4:inet#passwall#passwall_shuntlist,#6:inet#passwall#passwall_shuntlist6
domain-set -name passwall-whitehost -file /tmp/etc/passwall/acl/default/shunt_direct_host
domain-rules /domain-set:passwall-whitehost/ -nameserver local -nftset #4:inet#passwall#passwall_whitelist,#6:inet#passwall#passwall_whitelist6 -d yes -c ping,tcp:80,tcp:443 -r first-ping -rr-ttl-min 600
```

shunt_direct_host 在 shunt_proxy_host 之后，所以 shunt_direct_host 比 shunt_proxy_host 优先级高，当某个域名同时出现在两个表里面的时候会按照 shunt_direct_host 的规则解析

具体到我的情况就是，改之前 music.163.com 会被 cf dns 解析成香港 ip，现在会被大陆 dns 解析成大陆 ip

**Comment by lwb1978** [comment]
ok，不过我现在加个功能需要修改，所以会跟你的提交冲突，我先关掉你的提交，我一起改了

**Comment by moetayuko** [comment]
ok

**Comment by moetayuko** [comment]
@lwb1978 能给这里加一个额外的条件吗，我开了直连列表但想让分流规则里的 direct 进核心

https://github.com/xiaorouji/openwrt-passwall/blob/e49143de740cf8bfe5e2d9472d560c7a400520ff/luci-app-passwall/root/usr/share/passwall/helper_smartdns_add.lua#L496-L500

现在这样会让 smartdns 把 music.163.com 加到 passwall_whitelist 里，我基于 source 的分流规则就不起作用了

---

发现前几天把分流规则的优先级调到黑白名单之后了，163.com 在 chnlist 里，所以也会让上面的分流规则失效 https://github.com/xiaorouji/openwrt-passwall/commit/0d03e8e0bb68c02fc1b3da2aad872dee68110357

**Comment by lwb1978** [comment]
大家的需求都不一样，所以很难面面俱到，有用户不想直连的进核心，而有人又想进核心，如果想流量进核心还不如用pw2算了。
另外你说的163.com的问题，是因为chinadns不支持域名full，而smartdns的domain-rules也不支持，他们判断域名的时候会从域名最长的label进行匹配，所以music.163.com会匹配到163.com。

**Comment by lwb1978** [comment]
```
if USE_DIRECT_LIST == "1" then 	 
      domain_rules_str = domain_rules_str .. " " .. set_type .. " #4:" .. setflag .. "passwall_whitelist,#6:" .. setflag .. "passwall_whitelist6"
 else 
	domain_rules_str = domain_rules_str .. " " .. set_type .. " #4:" .. setflag .. "passwall_shuntlist,#6:" .. setflag .. "passwall_shuntlist6"
 end 
```
这部分的原始代码思路中，小肉鸡没有做判断，直连都是进whitelist的，这样会导致不开白名单列表的话直接变死流量，我前些天才改了不开白名单时就进核心去，不至于变死流量。

**Comment by moetayuko** [comment]
> 大家的需求都不一样，所以很难面面俱到，有用户不想直连的进核心，而有人又想进核心，如果想流量进核心还不如用pw2算了。 

我想让普通的直连不进核心，分流的进，所以需要 if 那里有个开关，类似这样
```lua
if USE_DIRECT_LIST == "1" and shunt_direct_to_whitelist then 
 	domain_rules_str = domain_rules_str .. " " .. set_type .. " #4:" .. setflag .. "passwall_whitelist,#6:" .. setflag .. "passwall_whitelist6" 
 else 
 	domain_rules_str = domain_rules_str .. " " .. set_type .. " #4:" .. setflag .. "passwall_shuntlist,#6:" .. setflag .. "passwall_shuntlist6" 
 end
```
shunt_direct_to_whitelist 默认为 true，保证现有行为不变

在 https://github.com/xiaorouji/openwrt-passwall/commit/0d03e8e0bb68c02fc1b3da2aad872dee68110357 之前，把上面的 if 改掉就够了，但现在 whitelist 在 nftset 里的优先级高于 shuntlist，所以当 music.163.com 的 ip 同时出现在 shuntlist 和 whitelist 的时候流量会按 whitelist 走，进不去核心。不知道为啥要调分流的优先级

> 另外你说的163.com的问题，是因为chinadns不支持域名full，而smartdns的domain-rules也不支持，他们判断域名的时候会从域名最长的label进行匹配，所以music.163.com会匹配到163.com。

目前没发现存在这方面的问题，把上面的 if 改掉以后 music.163.com 的 ip 会正常加入 shuntlist

**Comment by lwb1978** [comment]
这就叫公说公有理婆说婆有理，look:
https://github.com/xiaorouji/openwrt-passwall/issues/3544

**Comment by lwb1978** [comment]
fork回去自己按想要的改就行了，实在没法满足所有人的想法和需求，而且还是在开源免费的情况下。

**Comment by moetayuko** [comment]
> 这就叫公说公有理婆说婆有理，look: #3544

那个帖子太长了，没看明白到底在讲啥

我对 passwall 是这么理解的：
1. 仅通过 ip 域名就能区分的简单流量直接走直连、代理列表就行，不用进核心
2. 需要基于 source、协议、端口分流的“复杂”流量才进核心处理，而「xray 分流」功能控制的是如何给**进核心的流量**分流

基于上述理解，所有分流规则里出现的域名 ip 都应该无脑进核心，否则直接写在其他几个列表里就可以了。即使一个域名同时出现在分流和其他几个列表，也应该进核心处理，所以分流的 nftset 优先级也需要最高。从这个角度来讲，降低分流的优先级产生的问题会比解决的问题更多

**Comment by moetayuko** [comment]
至于开启 geosite 解析后产生的优先级问题，我想能不能不动 shuntlist，而是把直连的 geosite 和 geoip 加到 chnlist 里

**Comment by lwb1978** [comment]
我觉得pw1存在的意义和优势应该是直连的流量可以直接走防火墙，可以最大程度保证国内访问的性能和速度，大流量时可以硬件加速，那么直连应该优先级最高。pw2本来就是为分流而生，为何非要把pw1改成pw2呢？

**Comment by moetayuko** [comment]
> 我觉得pw1存在的意义和优势应该是直连的流量可以直接走防火墙，可以最大程度保证国内访问的性能和速度，大流量时可以硬件加速，那么直连应该优先级最高。pw2本来就是为分流而生，为何非要把pw1改成pw2呢？

个别流量进核心分流，大部分走防火墙直连，不矛盾吧

**Comment by lwb1978** [comment]
难就难在怎么判断你说的“个别流量”，另外你不要跟另外一个帖子的人一样漏了考虑访问控制，ipset就这么几个，都是共用的。

**Comment by moetayuko** [comment]
> 难就难在怎么判断你说的“个别流量”

这个好办啊，就是本帖顶楼说的方法。在分流规则页面增加选项，允许用户单独给每条 shunt_rules 设置防火墙规则，三选一：
1. 自动（当前行为）。if _node_id == "_direct" 则加入 passwall_whitelist，否则 passwall_shuntlist
2. 无脑加入 passwall_shuntlist
3. 不加任何 nftset

> 另外你不要跟另外一个帖子的人一样漏了考虑访问控制，ipset就这么几个，都是共用的。

访问控制只能控流量来源吧，控不了目标
