### ISSUE TITLE
[Feature Request]: 关于passwall编译的组件取舍

### ISSUE THREAD

**Issue by YEYEv50** [xiaorouji/openwrt-package#3541]
### 描述你想要的新功能

在OP编译中，passwall哪些组件是可以去除的？不然编译的固件太大了。节点类型个人都是选择使用singbox。
![屏幕截图 2024-11-28 230631](https://github.com/user-attachments/assets/793ebc33-6fbf-4332-bd82-0bc24d31640c)
![屏幕截图 2024-11-28 230732](https://github.com/user-attachments/assets/1f41adc0-9ce9-4286-aecc-45c32baa9d36)

### 描述你想要的解决方案

同上

**Comment by lwb1978** [comment]
看你是什么类型的路由，闪存多大的来决定，x86的就无所谓了，全选都行

**Comment by YEYEv50** [comment]
> 看你是什么类型的路由，闪存多大的来决定，x86的就无所谓了，全选都行

是硬路由。常用singbox，除了ipt和nft，下面的组件哪些可以取消不影响使用？

**Comment by lwb1978** [comment]
![1](https://github.com/user-attachments/assets/28287064-c492-44c4-adca-fc901edb47ce)
如果你是官方或者imm的op，pw只保留这两个就可以

**Comment by YEYEv50** [comment]
> ![1](https://private-user-images.githubusercontent.com/86697442/390999245-28287064-c492-44c4-adca-fc901edb47ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODg3NzIsIm5iZiI6MTczMjg4ODQ3MiwicGF0aCI6Ii84NjY5NzQ0Mi8zOTA5OTkyNDUtMjgyODcwNjQtYzQ5Mi00NGM0LWFkY2EtZmM5MDFlZGI0N2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Y2UwMmRhYWQ2MWVjYjM1Yzk2ZmJlZDg2ZjJkYjBmZDAyMmE2ZTYwZGVmYzEzOTlkMzQ0OThlZTExNmZmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AwkhhMOj8HOAXJyCYdp8u8jS94v9wf2Zdci6hGFb2C4) 如果你是官方或者imm的op，pw只保留这两个就可以

如果LEDE的话就保留 ipt和singbox是吧 。

**Comment by lwb1978** [comment]
对

**Comment by YEYEv50** [comment]
> 对

好的，非常感谢。
