### ISSUE TITLE
[Feature Request]: Please add dependency packages for CPU architecture: arm_comtex-a5-vfpv4

### ISSUE THREAD

**Issue by xingxiangxp** [xiaorouji/openwrt-package#3545]
### 描述你想要的新功能

Please add dependency packages for CPU architecture: arm_comtex-a5-vfpv4

### 描述你想要的解决方案

Please add dependency packages for CPU architecture: arm_comtex-a5-vfpv4

**Comment by qingtian110** [comment]
https://opkg.cooluc.com/openwrt-24.10/arm_cortex-a5_vfpv4/

**Comment by handsomeji** [comment]
下個版本的action自動編譯就會有了。。
