### ISSUE TITLE
[Bug]: mt76 / gl-mifi-mcu 在 ipq50xx-arm 架构上的机器编译失败.

### ISSUE THREAD

**Issue by WhaleFell** [xiaorouji/openwrt-package#3548]
### 描述您遇到的bug

使用的这个仓库进行编译: [openwrt-redmi-ax3000](https://github.com/hzyitc/openwrt-redmi-ax3000/)

`.config` 未添加 passwall 时编译成功.
`.config` 添加 passwall 后编译失败

多线程提示:  mt76 编译失败:
![multiple thread build error mt76 failed](https://github.com/user-attachments/assets/4e15b466-9e72-4645-aa16-3a6490eedae2)

单线程 `make -j1 V=s` 提示 gl-mifi-mcu 编译失败:
![j1 gl mifi mcu failed](https://github.com/user-attachments/assets/340a8fd4-364c-48aa-953d-45f5062f3883)

### 复现此Bug的步骤

复现仓库: [Undefined-R-0/openwrt-redmi-ax3000-offical/tree/9ed65d1a416d8e6eb755e9fe0765360863f93857](https://github.com/Undefined-R-0/openwrt-redmi-ax3000-offical/tree/9ed65d1a416d8e6eb755e9fe0765360863f93857)

Note: `.config.success` 是可以正常编译的原版, `.config` 是仅添加 passwall 后的配置.

### 您想要实现的目的

正常编译

### 日志信息

See Above Comments

### 截图

See Above Comments

### 系统相关信息

Passwall 最新版

### 其他信息

See Above Comments

**Comment by WhaleFell** [comment]
Firmware repo related issue: [https://github.com/hzyitc/openwrt-redmi-ax3000/issues/99](https://github.com/hzyitc/openwrt-redmi-ax3000/issues/99)

**Comment by uingei** [comment]
.config.success 里只加一行 CONFIG_PACKAGE_luci-app-passwall=y 试试，你这两个config对比了下区别好多

**Comment by lwb1978** [comment]
只有luci-app-passwall是pw的，如果是其他core组件导致编译失败请自行到相关的仓库提
