### ISSUE TITLE
[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### ISSUE THREAD

**Issue by coolzhi** [xiaorouji/openwrt-package#3550]
### 描述您遇到的bug

[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### 复现此Bug的步骤

[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### 您想要实现的目的

[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### 日志信息

[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### 截图

[Bug]: 规则列表那个界面一点 整个后台web 就死掉了

### 系统相关信息

【 4.78-1 】【 24.12.1 】  这个两个版本都有这个问题

**Comment by coolzhi** [comment]
有试了下微软的edeg浏览器会这样。用chrome就没问题

**Comment by xcyll** [comment]
同样情况 
chrome内核 会出现 这个问题 但又并不是100 %出现 我刷机启动后 大多时候点这个规则列表 就页面卡住了 要等很久 后续不知是不是缓存 又可正常一段时间
目前换火狐了 一次都没出现此问题了 截至此刻 我觉得是浏览器的锅  不知道这边能不能优化下 不能的话只能换浏览器
别的入口界面暂未发现卡的问题

**Comment by xcyll** [comment]
用的immortal 24分支
最新版edeg浏览器 chrome浏览器都有几率复现

**Comment by Tsubamei** [comment]
实测点击“规则列表”标签后，Chromium 131内核的Chrome和Edge浏览器都会卡死；
124内核会卡住几秒，然后正常加载，但每点一次子标签的列表都会卡住几秒；
86内核完全没问题，Firefox浏览器完全没问题。
补充：Arm A53架构，版本号24.12.1，iStoreOS 22.03.7中运行

**Comment by mcusee** [comment]
X86，中国列表（域名）标签，也会卡Chrome和Edge浏览器都会卡死

**Comment by lyp49472060** [comment]
cpu跑满一段时间，没有卡死！

**Comment by lwb1978** [comment]
几个月前小肉鸡在规则列表里加入gfw和中国列表域名和ip的显示，打开这个页面要加载几万个数据，所以如果路由的闪存速度不够或者电脑（浏览器）比较卡的情况会加载很慢，我现在没想到怎么按需加载好，又或者直接先屏蔽掉不让显示？我反正平时也不会去看这几个列表。听听大家意见。

**Comment by xcyll** [comment]
> 几个月前小肉鸡在规则列表里加入gfw和中国列表域名和ip的显示，打开这个页面要加载几万个数据，所以如果路由的闪存速度不够或者电脑（浏览器）比较卡的情况会加载很慢，我现在没想到怎么按需加载好，又或者直接先屏蔽掉不让显示？我反正平时也不会去看这几个列表。听听大家意见。

换用火狐一次都没卡过了

**Comment by xcyll** [comment]
某些内核浏览器卡 换回之前的显示界面（即去掉后3个只能读取，不能编辑的子显示菜单） 不确定能否解决问题 
我这边路由 电脑 性能是足够的 但用chrome就是有很大机率卡住在点击规则列表页面时
![2024-12-09 181059](https://github.com/user-attachments/assets/5ce516b4-c6dc-47db-a4de-8464f3d168a0)

**Comment by xcyll** [comment]
最新imm24分支 最新pw 最新chrome浏览器 
路由刷机 使用 貌似问题消失了 点规则列表不卡了 继续观察。。。

**Comment by smallprogram** [comment]
做了性能改进，应该不会再卡死了，如果再卡死就证明你的设备性能太拉跨了。
~~不会写Lazy Loading，那个大神会写给改改，测试目前解决了该问题~~

**Comment by redfrog999** [comment]
我还没更新最新commit，实测23.05和21.02,7621和7981都没有卡死捏？好奇怪，按说7621性能蛮老的呢。

**Comment by lwb1978** [comment]
> 做了性能改进，应该不会再卡死了，如果再卡死就证明你的设备性能太拉跨了。 ~不会写Lazy Loading，那个大神会写给改改，测试目前解决了该问题~

我改成ajax静态读取了，还卡的话可以把设备砸了吧。😄

**Comment by WeskerC** [comment]
会卡死，我用的N100当软路由，内存8g，跟设备性能无关，这肯定是个BUG

**Comment by lwb1978** [comment]
> 会卡死，我用的N100当软路由，内存8g，跟设备性能无关，这肯定是个BUG

你用的什么版本的pw？早就改成ajax读取了，要是用了最新版还卡那就找系统的原因吧。我n4100到7621没见卡死过。

**Comment by WeskerC** [comment]
> > 会卡死，我用的N100当软路由，内存8g，跟设备性能无关，这肯定是个BUG
> 
> 你用的什么版本的pw？早就改成ajax读取了，要是用了最新版还卡那就找系统的原因吧。我n4100到7621没见卡死过。

我用的passwall 1，版本的话是上个月刚从Are-U-OK下的包 PassWall_4.78-1 2024-08-04编译的
我在 Are-U-OK那边也提交了issue，没人理我

**Comment by lwb1978** [comment]
你的pw的版本太老了都半年过去了。你不会直接在这里下载新版安装上吗？

**Comment by WeskerC** [comment]
> 你的pw的版本太老了都半年过去了。你不会直接在这里下载新版安装上吗？

欸，好的，小白请问下载哪一个好呢？X86的系统 然后我是否需要先卸载然后再安装？
