### ISSUE TITLE
[Bug]: 保留配置刷新系统后首次启动PW无法正常启动

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-package#3554]
### 描述您遇到的bug

如题，保留配置刷新编译的系统后，PW无法启动

### 复现此Bug的步骤

原配置为使用Xray分流，刷新系统后查看日志提示AIGC中的规则无法正常加载
切换为不使用Xray分流的节点，并且在规则管理中手动更新规则后，再切换为Xray分流后可解决该问题

### 您想要实现的目的

修复bug

### 日志信息

未保存

### 系统相关信息

最新

**Comment by uingei** [comment]
最近是有这个问题,以前编译完刷机就OK,现在都要手动重启一下pw才行

**Comment by bi4tms** [comment]
> 刚才试了下23.05分支又是好的

应该是最近3个版本才出现的这个问题，大雕的源应该还没有更新到最新版。

**Comment by uingei** [comment]
> > 刚才试了下23.05分支又是好的
> 
> 应该是最近3个版本才出现的这个问题，大雕的源应该还没有更新到最新版。

24.10分支要手动重启,xray pw和23.05下的版本一致

**Comment by bi4tms** [comment]
> > > 刚才试了下23.05分支又是好的
> > 
> > 
> > 应该是最近3个版本才出现的这个问题，大雕的源应该还没有更新到最新版。
> 
> 24.10分支要手动重启,xray pw和23.05下的版本一致

和分支应该没什么关系，看日志应该与geoip的规则表有关，导致xray分流取法启动

**Comment by lwb1978** [comment]
不知道你们系统用的哪里的依赖包，是他们的geodata数据太老了，如果是自己编译的话自己更换成这边的依赖包。

**Comment by lwb1978** [comment]
如果不会的话最简单的就是事先准备好新版本的geoip和geosite，刷系统后手动上传到路由覆盖掉旧的数据库以后再启动pw。

**Comment by bi4tms** [comment]
> 不知道你们系统用的哪里的依赖包，是他们的geodata数据太老了，如果是自己编译的话自己更换成这边的依赖包。

你好，我用的还是老版本的luci，通过添加源的方式编译，应该如何更换依赖包

**Comment by lwb1978** [comment]
只能个举例子，具体还得根据你自己的环境（路径），比如：
1.先移除openwrt仓库那边自带的所有core组件：
`rm -rf feeds/packages/net/{xray-core,v2ray-core,v2ray-geodata,sing-box,pdnsd-alt,brook,chinadns-ng,dns2socks,dns2tcp,gn,hysteria,ipt2socks,microsocks,naiveproxy,shadowsocks-rust,shadowsocksr-libev,simple-obfs,tcping,trojan,trojan-go,trojan-plus,tuic-client,v2ray-plugin,xray-plugin,gn}`
2.然后拉取passwall的packages仓库：
`git clone https://github.com/xiaorouji/openwrt-passwall-packages package/passwall-packages`

**Comment by uingei** [comment]
多次测试 openwrt 23.05 分支启动没问题，24.10下启动就无法访问
