### ISSUE TITLE
[Bug]: recursive dependency detected

### ISSUE THREAD

**Issue by yyshell** [xiaorouji/openwrt-package#3555]
### 描述您遇到的bug

递归的依赖问题

### 复现此Bug的步骤

when run "make defconfig", it shows that "recursive dependency detected"

### 您想要实现的目的

消除这个error

### 日志信息

$ make defconfig
tmp/.config-package.in:63065:error: recursive dependency detected!
tmp/.config-package.in:63065:   symbol PACKAGE_luci-app-passwall depends on PACKAGE_geoview
tmp/.config-package.in:101871:  symbol PACKAGE_geoview is selected by PACKAGE_luci-app-passwall
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

#
# No change to .config
#

### 系统相关信息

2024.12.08

**Comment by lwb1978** [comment]
请测试拉取一下 https://github.com/xiaorouji/openwrt-passwall-packages 仓库的最新提交看是否还有递归依赖问题。

**Comment by yyshell** [comment]
> 请测试拉取一下 https://github.com/xiaorouji/openwrt-passwall-packages 仓库的最新提交看是否还有递归依赖问题。

问题依旧，我已经make dirclean了，但还是不行。

**Comment by lwb1978** [comment]
@moetayuko makefile我不熟，你看这个问题能否处理一下。

**Comment by moetayuko** [comment]
无法复现

**Comment by yyshell** [comment]
> 无法复现

您能试试immortalwrt吗？我这边确实能轻松复现的。

**Comment by moetayuko** [comment]
> > 无法复现
> 
> 您能试试immortalwrt吗？我这边确实能轻松复现的。

imm master 分支，还是复现不了

**Comment by yyshell** [comment]
两位大佬破案了，最近immortalwrt把passwall加入luci-application默认配置了，我还是像以前那样，把passwall加入到feeds.conf.default中，估计重复冲突了。
