### ISSUE TITLE
[Bug]: OpenWrt 官方源编译报错。。

### ISSUE THREAD

**Issue by 625045508** [xiaorouji/openwrt-package#3558]
### 描述您遇到的bug

OpenWrt 官方源： v23.05.5 版本，拉取 passwall和相关依赖后，单独编译 passwall报错。

### 复现此Bug的步骤

拉取 passwall 源码，只编译 passwall 就报错

### 您想要实现的目的

希望可以解决

### 日志信息

configure: error: Invalid kernel source directory /lib/modules/5.15.0-122-generic/source
make[2]: *** [Makefile:78: /home/lcx/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ipset-7.17/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/lcx/openwrt/package/network/utils/ipset'
time: package/network/utils/ipset/compile#6.69#0.48#8.01
    ERROR: package/network/utils/ipset failed to build.
make[1]: *** [package/Makefile:129: package/network/utils/ipset/compile] Error 1
make[1]: Leaving directory '/home/lcx/openwrt'
make: *** [/home/lcx/openwrt/include/toplevel.mk:233: package/lcx/openwrt-passwall/luci-app-passwall/compile] Error 2

### 系统相关信息

passwall 最新版

### 其他信息

无

**Comment by smallprogram** [comment]
`ERROR: package/network/utils/ipset failed to build.`
报错的是op的ipset，与passwall无关
