### ISSUE TITLE
[Bug]: 使用feeds添加源编译后，Passwall的版本号显示不正确

### ISSUE THREAD

**Issue by iovefish** [xiaorouji/openwrt-package#3560]
### 描述您遇到的bug

将以下命令添加到feeds
src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main

使用feeds添加源编译后，Passwall的版本号显示不正确，其中包括passwall，chinadns-ng，sing-box的版本都不是 最新的

### 复现此Bug的步骤

LEDE编译

### 您想要实现的目的

怎么可以正确的编译

### 日志信息

无日志

### 截图

![image](https://github.com/user-attachments/assets/2a3e9b5a-f2b7-42ec-9c17-9372dfed688d)

### 系统相关信息

4.78-3

**Comment by lwb1978** [comment]
这个问题自己去翻旧帖子或者问AI，这个是openwrt最基础的东西，我们不负责手把手教学。
