### ISSUE TITLE
[Bug]: 编译错误

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#3563]
### 描述您遇到的bug

编译错误

### 复现此Bug的步骤

编译错误

### 您想要实现的目的

Fix

### 日志信息

install -d -m0755 /home/builder/lede_x86/bin/packages/x86_64/passwall
/home/builder/lede_x86/staging_dir/host/bin/fakeroot /home/builder/lede_x86/staging_dir/host/bin/bash /home/builder/lede_x86/scripts/ipkg-build -m "" /home/builder/lede_x86/build_dir/target-x86_64_musl/tuic-client-1.0.0/ipkg-x86_64/tuic-client /home/builder/lede_x86/bin/packages/x86_64/passwall
Packaged contents of /home/builder/lede_x86/build_dir/target-x86_64_musl/tuic-client-1.0.0/ipkg-x86_64/tuic-client into /home/builder/lede_x86/bin/packages/x86_64/passwall/tuic-client_1.0.0-1_x86_64.ipk
echo "tuic-client" >> /home/builder/lede_x86/staging_dir/target-x86_64_musl/pkginfo/tuic-client.default.install
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/tuic-client'
time: package/feeds/passwall/tuic-client/compile#0.13#0.36#0.47
make[3]: Entering directory '/home/builder/lede_x86/feeds/passwall/v2ray-geoview'
rm -rf /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview.installed /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview
mkdir -p /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/builder/lede_x86/tmp/go-build" GO_MOD_CACHE_DIR="/home/builder/lede_x86/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/snowie2000/geoview" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/snowie2000/geoview" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0" GO_BUILD_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.go_work/build" GO_BUILD_BIN_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/builder/lede_x86/feeds/packages/lang/golang//golang-build.sh install_bin "/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install"
install -d -m0755 /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview/usr/bin
install -m0755 /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install/usr/bin//home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview/usr/bin/
install: cannot stat '/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install/usr/bin//home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview': No such file or directory
make[3]: *** [Makefile:52: /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview.installed] Error 1
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/v2ray-geoview'
time: package/feeds/passwall/v2ray-geoview/compile#0.03#0.10#0.13
    ERROR: package/feeds/passwall/v2ray-geoview failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/v2ray-geoview/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

截止发bug时pull的最新commit

**Comment by GreatMichaelLee** [comment]
why invalid?

**Comment by xcyll** [comment]
重新拉取上游试试 PW应该是没问题的
昨天下午遇到同样的错误  v2ray-geoview/compile] Error  后面晚上重新拉取编译的没问题了（配置未动）

**Comment by GreatMichaelLee** [comment]
> 重新拉取上游试试 PW应该是没问题的 昨天下午遇到同样的错误 v2ray-geoview/compile] Error 后面晚上重新拉取编译的没问题了（配置未动）

没用，我rm -rf ./tmp && make clean之后单线程编译了N个小时之后，出来还是这个错误，Lede的仓库。

**Comment by xcyll** [comment]
那就不清楚了  用的imm现在没问题 v2ray-geoview未报错
