### ISSUE TITLE
[Bug]: 编译错误

### ISSUE THREAD

**Issue by GreatMichaelLee** [xiaorouji/openwrt-package#3564]
### 描述您遇到的bug

![image](https://github.com/user-attachments/assets/b91d55aa-c081-4862-86e8-0731ae6dcdee)
![image](https://github.com/user-attachments/assets/8bd9fb3f-7cc6-4b54-aead-2eed1d51441b)

### 复现此Bug的步骤

编译

### 您想要实现的目的

没办法，问题都没看，就直接给关了，那么明显ERROR里报的路径都不对，里面包含有两个‘//’，自己不太懂makefile只好问chatgpt,按chatgpt的方法，解决了，但解决的只是编译问题，名称对不对我不知道，会不会有名称引用问题也不能确定。但issue还是要提一个。

### 日志信息

nstall -d -m0755 /home/builder/lede_x86/bin/packages/x86_64/passwall
/home/builder/lede_x86/staging_dir/host/bin/fakeroot /home/builder/lede_x86/staging_dir/host/bin/bash /home/builder/lede_x86/scripts/ipkg-build -m "" /home/builder/lede_x86/build_dir/target-x86_64_musl/tuic-client-1.0.0/ipkg-x86_64/tuic-client /home/builder/lede_x86/bin/packages/x86_64/passwall
Packaged contents of /home/builder/lede_x86/build_dir/target-x86_64_musl/tuic-client-1.0.0/ipkg-x86_64/tuic-client into /home/builder/lede_x86/bin/packages/x86_64/passwall/tuic-client_1.0.0-1_x86_64.ipk
echo "tuic-client" >> /home/builder/lede_x86/staging_dir/target-x86_64_musl/pkginfo/tuic-client.default.install
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/tuic-client'
time: package/feeds/passwall/tuic-client/compile#0.13#0.36#0.47
make[3]: Entering directory '/home/builder/lede_x86/feeds/passwall/v2ray-geoview'
rm -rf /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview.installed /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview
mkdir -p /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/builder/lede_x86/tmp/go-build" GO_MOD_CACHE_DIR="/home/builder/lede_x86/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/snowie2000/geoview" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/snowie2000/geoview" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0" GO_BUILD_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.go_work/build" GO_BUILD_BIN_DIR="/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/builder/lede_x86/feeds/packages/lang/golang//golang-build.sh install_bin "/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install"
install -d -m0755 /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview/usr/bin
install -m0755 /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install/usr/bin//home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview/usr/bin/
install: cannot stat '/home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/ipkg-install/usr/bin//home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview': No such file or directory
make[3]: *** [Makefile:52: /home/builder/lede_x86/build_dir/target-x86_64_musl/geoview-0.1.0/.pkgdir/geoview.installed] Error 1
make[3]: Leaving directory '/home/builder/lede_x86/feeds/passwall/v2ray-geoview'
time: package/feeds/passwall/v2ray-geoview/compile#0.03#0.10#0.13
ERROR: package/feeds/passwall/v2ray-geoview failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/v2ray-geoview/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

本issue提出时的last update commit.

**Comment by lwb1978** [comment]
我真是服了，你用其他仓库的makefile怪我们？

**Comment by GreatMichaelLee** [comment]
> 我真是服了，你用其他仓库的makefile怪我们？

哪个是“其他”仓库？？
![image](https://github.com/user-attachments/assets/76985450-3b67-4142-a7c7-cee7ae1e6b38)

**Comment by lwb1978** [comment]
这个pr我昨天就中午就reset，你自己不拉最新代码怪谁？

**Comment by GreatMichaelLee** [comment]
> 这个pr我昨天就中午就reset，你自己不拉最新代码怪谁？

没什么好说的，就这样吧。怪我，你NB。

**Comment by lwb1978** [comment]
![1](https://github.com/user-attachments/assets/49db6e49-9728-446b-b67a-bb1ed9d7399d)
别以为你删了我看不到，你是第一个在这里骂开发人员的，TMD，花时间免费给你们更新维护软件，一句好话没得到，你到是骂得爽，试问你对PW做了什么贡献？如果你不喜欢可以不用，github上科学软件多的是，出门右转不送。

**Comment by GreatMichaelLee** [comment]
我删了就是不想啰嗦纠缠了而已，没想到你还拿出来鞭尸，我都说了，怪我，你Nb，nb是骂人的话吗？你放到哪里问问是骂人？！我第一次听说nb是骂人，如果你觉得是那只能说我们文化不同，倒是你，这句TMD是标准的骂人，你骂谁？说清楚？义务免费不代表可以居高临下！


------------------ 原始邮件 ------------------
发件人: A-BO ***@***.***&gt;
发送时间: 2024年12月14日 01:28
收件人: xiaorouji/openwrt-passwall ***@***.***&gt;
抄送: michael lee ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xiaorouji/openwrt-passwall] [Bug]: 编译错误 (Issue #3564)





 
1.png (view on web)
 别以为你删了我看不到，你是第一个在这里骂开发人员的，TMD，花时间免费给你们更新维护软件，一句好话没得到，你到是骂得爽，试问你对PW做了什么贡献？如果你不喜欢可以不用，github上科学软件多的是，出门右转不送。

**Comment by lwb1978** [comment]
第一次见人对自己爆粗口描述得这么顺其自然的，傻子都知道你说的“你NB”是什么意思，只准你开骂，还不能人家还嘴，没打过三针科兴的都理解不了这种神逻辑，不说了，等肉鸡来评理吧，此贴锁定。
@xiaorouji
