### ISSUE TITLE
[Bug]: 导入Xray的分享URL时，加密方式不是显示none而是显示非法字符！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#3567]
### 描述您遇到的bug

![image](https://github.com/user-attachments/assets/4f6c7a0a-f15c-4ca8-94b5-b023bd654ca5)

### 复现此Bug的步骤

1、导入分享URL
2、输入URL
3、出现加密方式为非法字符，而不是none；
![image](https://github.com/user-attachments/assets/7f195d26-af79-4427-b170-57ddfff5de5d)

### 您想要实现的目的

导入URL时加密方式应该显示正常的none。

### 日志信息

无

### 系统相关信息

![image](https://github.com/user-attachments/assets/23f86757-4ed8-440f-8481-de7a2b630a7a)

**Comment by lwb1978** [comment]
能否直接给个链接调试？假链接就行。

**Comment by zxlhhyccc** [comment]
> 能否直接给个链接调试？假链接就行。

我刚编译新的commit，貌似又正常了。
