### ISSUE TITLE
[Bug]: 导入Xray的分享URL时，节点加密方式为"空"时应显示none，但实际为空且保存并应用后变成非法字符，启动插件后配置中的加密方式应该是none而不是非法字符！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#3569]
### 描述您遇到的bug
**导入时：**

![image](https://github.com/user-attachments/assets/90ace4c8-601c-4e0f-baf4-b7029f959d9c)

**保存并应用后：**

![image](https://github.com/user-attachments/assets/2c53be43-5240-41b3-9d7e-20111de89928)

### 复现此Bug的步骤

1、导入vless的分享URL
2、输入URL
3、出现加密方式实际是为"空"而不是none；
4、保存并应用后出现非法字符；
5、启动插件后配置中加密方式显示的是非法字符而不是none。

例如节点：
vless://56233b35-f3ac-4e72-8294-1fc05deddc9f@run88.uway.com:38459?type=tcp&security=reality&pbk=SLdupdxp3oQl5rPSi082LXaF_UKSCf269qEKJ-F6b1Q&fp=random&sni=[yahoo.com](http://yahoo.com/)&sid=47bf57f4&spx=%2F#test-b

### 您想要实现的目的

导入URL时节点加密方式为空时应显示none，保存并应用后应该也为none，启动插件后加密方式也应为none。

### 日志信息

无。

### 系统相关信息

![image](https://github.com/user-attachments/assets/b7c3ee48-349a-4b97-8904-ccf37731c3cf)

**Comment by lwb1978** [comment]
fix
