### ISSUE TITLE
[Bug]: XHTTP Extra内容生效问题

### ISSUE THREAD

**Issue by yoshino2** [xiaorouji/openwrt-package#3573]
### 描述您遇到的bug

在XHTTP Extra 参数中设置
"downloadSettings": {
      "address": "IP",
      "port": 8443,
      "network": "xhttp",
      "security": "tls",
      "tlsSettings": {
  							"fingerprint": "chrome",
  							"serverName": "www.123.com",
								"alpn": [
           					 "h3"
         							 ]
      	},
      "xhttpSettings": {
      	        "path": "/xxxx"，
      	        "host":"www.123.com"
      }
    }  

功能无法生效，并导致xray无法运行

### 复现此Bug的步骤

在XHTTP Extra 参数中设置
"downloadSettings": {
      "address": "IP",
      "port": 8443,
      "network": "xhttp",
      "security": "tls",
      "tlsSettings": {
  							"fingerprint": "chrome",
  							"serverName": "www.123.com",
								"alpn": [
           					 "h3"
         							 ]
      	},
      "xhttpSettings": {
      	        "path": "/xxxx"，
      	        "host":"www.123.com"
      }
    }  
保存并应用

### 您想要实现的目的

能够正确有效的使用XHTTP Extra 参数功能

### 日志信息

Xray 24.12.15 (Xray, Penetrates Everything.) 7d0a80b (go1.23.4 linux/arm64)
A unified platform for anti-censorship.
2024/12/16 10:17:04 [Info] infra/conf/serial: Reading config: &{Name:/tmp/etc/passwall/acl/default/TCP_SOCKS.json Format:json}
Failed to start: main: failed to load config files: [/tmp/etc/passwall/acl/default/TCP_SOCKS.json] > infra/conf: Failed to build XHTTP config. > infra/conf: Failed to unmarshal "extra". > json: cannot unmarshal string into Go value of type conf.SplitHTTPConfig

打开/tmp/etc/passwall/acl/default/TCP_SOCKS.json
"xhttpSettings": {
          "host": "www.123.com",
          "mode": "auto",
          **"extra": "downloadSettings",**
          "path": "XXXXX"

extra字段中，只显示"downloadSettings"其他输入测参数信息并未在该文件的extra字段中配置成功

### 系统相关信息

passwall   24.12.08

**Comment by lwb1978** [comment]
很显然你的json是错误的：
1.你首尾没有用{}包裹
2.你的json里面还用了中文的逗号“，”：`"path": "/xxxx"，`
正确写法xray文档都有说明，比如你的应该是：
```
{
"downloadSettings": {
"address": "IP",
"port": 8443,
"network": "xhttp",
"security": "tls",
"tlsSettings": {
"fingerprint": "chrome",
"serverName": "www.123.com",
"alpn": [
"h3"
]
},
"xhttpSettings": {
"path": "/xxxx",
"host":"www.123.com"
}
}
}
```
多细心点，大家都很忙的。

**Comment by yoshino2** [comment]
中文的逗号确实是我大意了，谢谢提醒
