### ISSUE TITLE
[Feature Request]: 增加配置备份恢复功能

### ISSUE THREAD

**Issue by snowie2000** [xiaorouji/openwrt-package#3576]
### 描述你想要的新功能

在折腾过程中总会遇到需要刷机或者更换路由等情况，另外如gl.net之类的路由在升级固件时无法保留第三方应用，在这种情况下，passwall那庞大的规则和结点的备份就是一件很麻烦的事情。

### 描述你想要的解决方案

提供类似openwrt官方相似的备份到文件，从文件恢复配置的功能。

**Comment by redfrog999** [comment]
其实用winscp把/etc/config/passwall拉下来就能备份了。

**Comment by snowie2000** [comment]
> 其实用winscp把/etc/config/passwall拉下来就能备份了。

首先winscp并不是很好用……
其次备份这个不够，好像规则列表并不会被备份下来

**Comment by solarflows** [comment]
怎么说呢。。。。你要备份这个文件，也可以用openwrt自带的备份完成，你要在备份列表加一条就行了

**Comment by snowie2000** [comment]
众所周知openwrt不同系统不可以相互恢复备份

**Comment by solarflows** [comment]
额，怎么不能。你备份好，复制需要的部分覆盖就行了😂。

**Comment by solarflows** [comment]
> 众所周知openwrt不同系统不可以相互恢复备份

你说的也对，不能直接恢复，但可以通过解压，覆盖指定文件来完成，就升级系统而言，不保留第三方软件，但保留配置/etc/config（21以后的不清楚）。我个人是用的上述的方案来备份的。但是在某个远古版本的passwall，这样子覆盖会崩。

**Comment by snowie2000** [comment]
没有错，从理论上说，openwrt中所有的配置都是以文件形式存在的，所以只要备份对应的文件就可以了。那么从这个角度上说，openwrt也没有必要存在一个备份还原的功能咯。

提供一个单独的备份还原功能并不是因为不能手动完成这个事情，而是会更方便，并且备份的文件可以跟随pw的版本而随时增加，不用去考虑某个版本开始是不是多了一个文件要备份

**Comment by lwb1978** [comment]
完成

**Comment by smdx** [comment]
@lwb1978 你好，反馈个备份功能问题。
刚才编译的固件pw源码是26668ed，测试备份功能会生成2个tar.gz文档其中带日期的是0kb空文档。
![2024-12-23_192256](https://github.com/user-attachments/assets/a0e51bb2-c3c8-45df-90b6-7073680748ae)

**Comment by redfrog999** [comment]
> @lwb1978 你好，反馈个备份功能问题。 刚才编译的固件pw源码是26668ed，测试备份功能会生成2个zip文档其中带日期的是0kb空文档。 ![2024-12-23_192256](https://private-user-images.githubusercontent.com/9279217/398147079-a0e51bb2-c3c8-45df-90b6-7073680748ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTQ2NDgsIm5iZiI6MTczNDk1NDM0OCwicGF0aCI6Ii85Mjc5MjE3LzM5ODE0NzA3OS1hMGU1MWJiMi1jM2M4LTQ1ZGYtOTBiNi03MDczNjgwNzQ4YWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTE0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZiNThkMjc5ZmYwMzY3MTA4YmU5NTliN2ZlMzA2OTkxZDYyNTUzOGI3MTgwYmFhYzUyZmI2NTA0Yjg1M2E2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JnYLxd0X17dqKkoEbcTxTPFN5sLWi-ImHOwzJlQxVVs)

刚刚在硬路由上测试了下，可以备份，文件大小为10kb左右。

**Comment by lwb1978** [comment]
10kb应该是正常的，可以直接打开备份的压缩包，里面有文件就是对的，但生成0kb文件的情况我这里没能复现，我两台都是软路由.

**Comment by lwb1978** [comment]
> @lwb1978 你好，反馈个备份功能问题。 刚才编译的固件pw源码是26668ed，测试备份功能会生成2个zip文档其中带日期的是0kb空文档。 ![2024-12-23_192256](https://private-user-images.githubusercontent.com/9279217/398147079-a0e51bb2-c3c8-45df-90b6-7073680748ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTUxMDksIm5iZiI6MTczNDk1NDgwOSwicGF0aCI6Ii85Mjc5MjE3LzM5ODE0NzA3OS1hMGU1MWJiMi1jM2M4LTQ1ZGYtOTBiNi03MDczNjgwNzQ4YWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTE1MzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ0Njk0NGU5OGNmOTk3MTIzNTQ3ODVmMWViMjU3NTEzMDUxODk2YzkyNWVlY2UwYjM1NmRmZDZkNjY2MmU0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WTSeSyP6jmoeg_4lqHC5T2VKpGwCjk0O9SJcQnZVgd0)

试试更换个浏览器看。我手机都可以正常备份。

**Comment by smdx** [comment]
> > @lwb1978 你好，反馈个备份功能问题。 刚才编译的固件pw源码是26668ed，测试备份功能会生成2个zip文档其中带日期的是0kb空文档。 ![2024-12-23_192256](https://private-user-images.githubusercontent.com/9279217/398147079-a0e51bb2-c3c8-45df-90b6-7073680748ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTUxMDksIm5iZiI6MTczNDk1NDgwOSwicGF0aCI6Ii85Mjc5MjE3LzM5ODE0NzA3OS1hMGU1MWJiMi1jM2M4LTQ1ZGYtOTBiNi03MDczNjgwNzQ4YWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTE1MzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ0Njk0NGU5OGNmOTk3MTIzNTQ3ODVmMWViMjU3NTEzMDUxODk2YzkyNWVlY2UwYjM1NmRmZDZkNjY2MmU0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WTSeSyP6jmoeg_4lqHC5T2VKpGwCjk0O9SJcQnZVgd0)
> 
> 试试更换个浏览器看。我手机都可以正常备份。

edge、chrome都一样每次都会生成2个文档，不带日期那个文档是正常的。
![2024-12-23_201835](https://github.com/user-attachments/assets/eacb83e0-d6ad-46f1-8b35-2ab0b93e68bc)

**Comment by lwb1978** [comment]
@smdx 请测试最新代码

**Comment by smdx** [comment]
> @smdx 请测试最新代码

开始编译了

**Comment by smdx** [comment]
> @smdx 请测试最新代码



> @smdx 请测试最新代码

新编译的包发现还是会保存2个文档，这次是不带日期的文档没内容。排查发现是不知道什么时候idm接管了默认下载以前一直是用右键触发的（包太小完全看不到下载框）。不用idm正常输出一个带日期的备份。lwb1978有空可以装个idm测试一下？

**Comment by lwb1978** [comment]
当时只是要做个简单的下载过程，但没考虑到还有idm这种多线程的下载器来下载一个几kb的文件😂（但我迅雷测试是不会下到两个文件的）
@smdx  你试试下面的文件，解压后上传到路由的`/usr/lib/lua/luci/view/passwall/log`覆盖同名文件
[backup_restore.zip](https://github.com/user-attachments/files/18235403/backup_restore.zip)

**Comment by smdx** [comment]
> 当时只是要做个简单的下载过程，但没考虑到还有idm这种多线程的下载器来下载一个几kb的文件😂（但我迅雷测试是不会下到两个文件的） @smdx 你试试下面的文件，解压后上传到路由的`/usr/lib/lua/luci/view/passwall/log`覆盖同名文件 [backup_restore.zip](https://github.com/user-attachments/files/18235403/backup_restore.zip)

替换文件后没问题了，谢谢

**Comment by lwb1978** [comment]
ok，那我就推送到仓库了
