### ISSUE TITLE
[Bug]: ss订阅解析失败

### ISSUE THREAD

**Issue by conbbyn** [xiaorouji/openwrt-package#3578]
### 描述您遇到的bug

ss://YWVzLTI1Ni1nY206NTU2NDU5ODUyZ3NkZ2ZhemYqQA%3D%3D@5566-565566-52.856885223.com:21586#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E8%8A%82%E7%82%B91255553254145

显示解析错误，跳过此节点。

### 复现此Bug的步骤

ss://YWVzLTI1Ni1nY206NTU2NDU5ODUyZ3NkZ2ZhemYqQA%3D%3D@5566-565566-52.856885223.com:21586#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E8%8A%82%E7%82%B91255553254145

显示解析错误，跳过此节点。

### 您想要实现的目的

ss://YWVzLTI1Ni1nY206NTU2NDU5ODUyZ3NkZ2ZhemYqQA%3D%3D@5566-565566-52.856885223.com:21586#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E8%8A%82%E7%82%B91255553254145

显示解析错误，跳过此节点。

### 日志信息

ss://YWVzLTI1Ni1nY206NTU2NDU5ODUyZ3NkZ2ZhemYqQA%3D%3D@5566-565566-52.856885223.com:21586#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E8%8A%82%E7%82%B91255553254145

显示解析错误，跳过此节点。

### 系统相关信息

Passwall 版本	【 24.12.17-2 】
Passwall2 版本	【 24.12.19-2 】

**Comment by lwb1978** [comment]
你的ss链接本身就有误，前部的Base64编码根本就是无效的，自行去你机场反馈吧。我大部分节点都是ss的，这个要是出错我自己都用不了。

**Comment by conbbyn** [comment]
> 你的ss链接本身就有误，前部的Base64编码根本就是无效的，自行去你机场反馈吧。我大部分节点都是ss的，这个要是出错我自己都用不了。

我用v2rayn导出来的base64，substore，小火箭都能解析，所以应该是v2rayn的问题
