### ISSUE TITLE
[Bug]: 透明代理使用瓦工服务器访问 gpt app 失败

### ISSUE THREAD

**Issue by zanmeipaul** [xiaorouji/openwrt-package#3580]
### 描述您遇到的bug

1. 使用系统默认的透明代理，路线是使用瓦工的服务器，因为瓦工服务器是通过DNS解锁 gpt的
2. 因为使用DNS透明代理，提交到代理的是IP，不是域名。 所以瓦工服务器无法通过DNS 解锁
3. 我想提问的是，如何通过DNS透明代理指定 chat.openai.com 域名本地不解析成IP提交到代理，而是直接域名提交到代理

### 复现此Bug的步骤

1. 使用系统默认的透明代理，路线是使用瓦工的服务器，因为瓦工服务器是通过DNS解锁 gpt的
2. 因为使用DNS透明代理，提交到代理的是IP，不是域名。 所以瓦工服务器无法通过DNS 解锁
3. 我想提问的是，如何通过DNS透明代理指定 chat.openai.com 域名本地不解析成IP提交到代理，而是直接域名提交到代理

### 您想要实现的目的

我想提问的是，如何通过DNS透明代理指定 chat.openai.com 域名本地不解析成IP提交到代理，而是直接域名提交到代理

### 日志信息

无

### 系统相关信息

版本 
4.73-3
--

<br class="Apple-interchange-newline">

**Comment by lwb1978** [comment]
使用xray打开覆盖连接目标地址，这么老的版本，我不保证功能正常。

**Comment by zanmeipaul** [comment]
> 使用xray打开覆盖连接目标地址，这么老的版本，我不保证功能正常。

那请问最新版本有这个问题吗？

**Comment by lwb1978** [comment]
我没有vps，不清楚，我用机场的，gpt一直正常。

**Comment by zanmeipaul** [comment]
> 我没有vps，不清楚，我用机场的，gpt一直正常。

你是说 DNS 的过滤模式  改成 xray ,然后打开覆盖连接目标地址妈？

**Comment by lwb1978** [comment]
节点用xray作为客户端

**Comment by zanmeipaul** [comment]
> 节点用xray作为客户端

试了不行，最终还是本地DNS解析结果的IP提交到VPS，VPS无法走当前的域名解析流程

**Comment by handsomeji** [comment]
開嗅探，用FakeDNS

**Comment by zanmeipaul** [comment]
> 開嗅探，用FakeDNS

我看了passwall 没有这两个功能，这两个功能是不是在2里面才有？

**Comment by lwb1978** [comment]
> > 開嗅探，用FakeDNS
> 
> 我看了passwall 没有这两个功能，这两个功能是不是在2里面才有？

节点类型使用sing-box、dns过滤模式选择sing-box ，勾选FakeDNS，高级设置，sing-box设置勾选覆盖连接目标地址
