### ISSUE TITLE
[Bug]: 负载均衡

### ISSUE THREAD

**Issue by StephenJose-Dai** [xiaorouji/openwrt-package#3581]
### 描述您遇到的bug

x86版本没有负载均衡的设置页面？

### 复现此Bug的步骤

我看网上都有负载均衡的设置页面，为啥我的x86没有啊

### 您想要实现的目的

配置负载均衡

### 日志信息

![image](https://github.com/user-attachments/assets/db7e3bd0-bcdb-4aea-b76a-1d3514ae68ac)

### 系统相关信息

![image](https://github.com/user-attachments/assets/345deed1-3603-4e54-a637-6feb6a87d8e9)

![image](https://github.com/user-attachments/assets/a7dac2e2-5a12-43aa-88a5-f6aa7cf07504)

**Comment by lwb1978** [comment]
没安装HAProxy
善用搜索，减少我们工作量
https://github.com/xiaorouji/openwrt-passwall/issues/3157
