### ISSUE TITLE
[Feature Request]: 为Xray-HTTP协议增加传输方式选择

### ISSUE THREAD

**Issue by wi11iamzhao** [xiaorouji/openwrt-package#3585]
### 描述你想要的新功能

在使用Xray时，协议选择Vmess/Vless/SS/Socks时，均可以选择传输方式（RAW/mKCP/WS/H2...）：
![image](https://github.com/user-attachments/assets/acf4a2b1-78b7-46a5-ac35-324ae2e2217b)
但是当选择协议为HTTP时，传输方式选项被取消：
![image](https://github.com/user-attachments/assets/1b507ef1-1eca-4a1c-9694-68d8f5e32026)
经过验证，Xray自身的实现上，底层协议为HTTP时和WS/H2/GRPC等传输方式并不冲突，希望能增加协议为HTTP时对传输方式选择的支持。

### 描述你想要的解决方案

增加协议为HTTP时对传输方式选择的支持

**Comment by milkman-wang** [comment]
Transport: Remove HTTP by @RPRX in https://github.com/XTLS/Xray-core/commit/ae62a0fb526f2faa0aa8b3fbce5a566187059090
最新的xray已经移除了http

**Comment by wi11iamzhao** [comment]
> Transport: Remove HTTP by @RPRX in [XTLS/Xray-core@ae62a0f](https://github.com/XTLS/Xray-core/commit/ae62a0fb526f2faa0aa8b3fbce5a566187059090) 最新的xray已经移除了http
没有注意到…

**Comment by wi11iamzhao** [comment]
> Transport: Remove HTTP by @RPRX in [XTLS/Xray-core@ae62a0f](https://github.com/XTLS/Xray-core/commit/ae62a0fb526f2faa0aa8b3fbce5a566187059090) 最新的xray已经移除了http

没有注意到。。
