### ISSUE TITLE
[Bug]: 关于DNS新逻辑的问题，发现dnsmasq无法启动

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-package#3586]
### 描述您遇到的bug

Passwall未启用重定向后，无限重启
Passwall启用重定向后，系统日志发现dnsmasq 无法启动的日志。

### 复现此Bug的步骤

Passwall未启用重定向状态，表现无限重启
Passwall启用重定向状态，Passwall没有显性错误，可以正常使用。

### 您想要实现的目的

修复可能潜在的问题

### 日志信息

系统日志：
Mon Dec 23 11:12:34 2024 cron.err crond[8214]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:12:34 2024 cron.err crond[8342]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:12:34 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geoip database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geoip-to-rule-sets
Mon Dec 23 11:12:34 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geosite database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets
Mon Dec 23 11:12:35 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:12:35 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:12:40 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:12:40 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:12:45 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:12:45 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:12:50 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:12:50 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:12:56 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:12:56 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:01 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:01 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:01 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Mon Dec 23 11:13:09 2024 cron.err crond[12066]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:09 2024 daemon.err procd: Got unexpected signal 1
Mon Dec 23 11:13:09 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:09 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:09 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 7 crashes, 0 seconds since last crash
Mon Dec 23 11:13:12 2024 cron.err crond[12764]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:12 2024 cron.err crond[12891]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:13 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:13 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:13 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geoip database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geoip-to-rule-sets
Mon Dec 23 11:13:13 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geosite database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets
Mon Dec 23 11:13:14 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:14 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:19 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:19 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:24 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:24 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:29 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:29 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:34 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:34 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:39 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:39 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:39 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Mon Dec 23 11:13:44 2024 cron.err crond[15993]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:44 2024 daemon.err procd: Got unexpected signal 1
Mon Dec 23 11:13:44 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:44 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:44 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 7 crashes, 0 seconds since last crash
Mon Dec 23 11:13:47 2024 cron.err crond[16686]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:47 2024 cron.err crond[16813]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:13:47 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:47 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:48 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geoip database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geoip-to-rule-sets
Mon Dec 23 11:13:48 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geosite database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets
Mon Dec 23 11:13:48 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:48 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:53 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:53 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:13:58 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:13:58 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:04 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:04 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:09 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:09 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:14 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:14 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:14 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Mon Dec 23 11:14:22 2024 cron.err crond[19873]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:14:22 2024 daemon.err procd: Got unexpected signal 1
Mon Dec 23 11:14:22 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:22 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:22 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 7 crashes, 1 seconds since last crash
Mon Dec 23 11:14:25 2024 daemon.info procd: - shutdown -
Mon Dec 23 11:14:25 2024 cron.err crond[20568]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:14:25 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:25 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:26 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geoip database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geoip-to-rule-sets
Mon Dec 23 11:14:26 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geosite database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets
Mon Dec 23 11:14:26 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:26 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:30 2024 daemon.info procd: Instance cron::instance1 pid 20568 not stopped on SIGTERM, sending SIGKILL instead
Mon Dec 23 11:14:30 2024 cron.err crond[22055]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:14:31 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:31 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:36 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:36 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:42 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:42 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:47 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:47 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:52 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:52 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:52 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Mon Dec 23 11:14:57 2024 cron.err crond[23967]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:14:57 2024 daemon.err procd: Got unexpected signal 1
Mon Dec 23 11:14:57 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:14:57 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:14:57 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 7 crashes, 0 seconds since last crash
Mon Dec 23 11:15:00 2024 cron.err crond[24655]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:15:00 2024 cron.err crond[24782]: crond (busybox 1.37.0) started, log level 7
Mon Dec 23 11:15:00 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:00 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:00 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geoip database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geoip-to-rule-sets
Mon Dec 23 11:15:00 2024 user.notice PASSWALL_TCP_sing-box: [33mWARN[0m[0000] geosite database is deprecated in sing-box 1.8.0 and will be removed in sing-box 1.12.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets
Mon Dec 23 11:15:05 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:05 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:10 2024 user.notice nft-qos-monitor: ACTION=update, MACADDR=cc:d8:43:62:1a:60, IPADDR=192.168.86.193, HOSTNAME=MiWiFi-RD02
Mon Dec 23 11:15:10 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:10 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:10 2024 user.notice nft-qos-dynamic: ACTION=update, MACADDR=cc:d8:43:62:1a:60, IPADDR=192.168.86.193, HOSTNAME=MiWiFi-RD02
Mon Dec 23 11:15:15 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:15 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:20 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:20 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:25 2024 daemon.crit dnsmasq[1]: failed to create listening socket for 192.168.86.1: Address in use
Mon Dec 23 11:15:25 2024 daemon.crit dnsmasq[1]: FAILED to start up
Mon Dec 23 11:15:25 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

dhcp信息：
config dnsmasq
	option localise_queries '1'
	option rebind_protection '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option localservice '1'
	option localuse '1'
	option allservers '1'
	option domainneeded '1'
	option rebind_localhost '1'
	option ednspacket_max '1232'
	option boguspriv '0'
	option filter_aaaa '1'
	option noresolv '1'
	list server '127.0.0.1#6053'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '4h'
	option dhcpv4 'server'
	option ra 'server'
	option ra_management '1'
	option force '1'
	list dhcp_option '3,192.168.86.1'
	list dhcp_option '6,192.168.86.1'
	option preferred_lifetime '12h'
	option ra_useleasetime '1'
	option max_preferred_lifetime '2700'
	option max_valid_lifetime '5400'
	option ra_default '1'
	list ra_flags 'none'
	option dns_service '0'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

### 系统相关信息

openwrt版本：ImmortalWrt SNAPSHOT r32740-cd5f08f266
Passwall版本：https://github.com/xiaorouji/openwrt-passwall/commit/f5183c44f37de6466fe8f15d8b5384d0caed3a72
Chrome版本：131.0.6778.205

**Comment by lwb1978** [comment]
引用昨天小肉鸡发的邮件:
為了不浪費時間，請有問題的發 /etc/config/passwall 這個文件到我郵箱(xiaoroujixxoo@gmail.com)。否則永遠都不可能能復現並修復

**Comment by SakuraFallingMad** [comment]
收到，我发现是启动Passwall的时候，原dnsmasq不能正常的退出重启诶
![image](https://github.com/user-attachments/assets/cc62055d-1558-41fc-bd60-04cc536a3efa)

**Comment by uingei** [comment]
“DNS 重定向”以新增 dnsmasq 实例的方式是不是更方便些？

最近不启用“DNS 重定向”造成 dnsmasq 异常可能跟 procd-ujail 有关

**Comment by handsomeji** [comment]
Fix

**Comment by uingei** [comment]
不启用重定向能正常用了，但是日志上会出现两条 “脚本已经在运行，不重复运行，退出.”

2024-12-23 16:40:13: 执行启动延时 60 秒后再启动!
2024-12-23 16:41:24: 清空并关闭相关程序和缓存完成。
2024-12-23 16:41:24: 分析 Socks 服务的节点配置...
2024-12-23 16:41:25:   - Socks节点：[]，启动 0.0.0.0:1081
2024-12-23 16:41:25:   - Socks节点：[]，启动 0.0.0.0:1082
2024-12-23 16:41:25:   - Socks节点：[]，启动 0.0.0.0:1083
2024-12-23 16:41:26: TCP节点：[分流总节点]，监听端口：1041
2024-12-23 16:41:26: UDP节点：与TCP节点相同
2024-12-23 16:41:26: DNS域名解析：
2024-12-23 16:41:27:   - udp://127.0.0.1#6553
2024-12-23 16:41:27:   * 请确认上游 DNS 支持 UDP 查询并已使用 UDP 节点，如上游 DNS 非直连地址，确保 UDP 代理打开，并且已经正确转发！
2024-12-23 16:41:28:   - 节点列表中的域名(vpslist)：127.0.0.1#6053
2024-12-23 16:41:28:   - 域名白名单(whitelist)：127.0.0.1#6053
2024-12-23 16:41:28:   - 代理域名表(blacklist)：127.0.0.1#6553
2024-12-23 16:41:29:   - 防火墙域名表(gfwlist)：127.0.0.1#6553
2024-12-23 16:41:29:   - Sing-Box/Xray分流规则(ProxyGame)：127.0.0.1#6553
2024-12-23 16:41:29:   - Sing-Box/Xray分流规则(TikTok)：127.0.0.1#6553
2024-12-23 16:41:29:   - Sing-Box/Xray分流规则(AIGC)：127.0.0.1#6553
2024-12-23 16:41:29:   - Sing-Box/Xray分流规则(Streaming)：127.0.0.1#6553
2024-12-23 16:41:29:   - Sing-Box/Xray分流规则(Proxy)：127.0.0.1#6553
2024-12-23 16:41:29:   - 默认：127.0.0.1#6053
2024-12-23 16:41:30:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-12-23 16:41:33: 脚本已经在运行，不重复运行，退出.
2024-12-23 16:41:35: 重启 dnsmasq 服务
2024-12-23 16:41:35: 开始加载防火墙规则...
2024-12-23 16:41:38: 脚本已经在运行，不重复运行，退出.
2024-12-23 16:41:39:   - [0]追加ISP IPv4 DNS到白名单：192.168.1.1
2024-12-23 16:41:39:   - [0]追加ISP IPv6 DNS到白名单：fe80::1
2024-12-23 16:41:39:   - [0]加入所有IPv4节点到ipset[passwall_vpslist]直连完成
2024-12-23 16:41:39:   - [0]加入所有IPv6节点到ipset[passwall_vpslist6]直连完成
2024-12-23 16:41:40:   - [0]追加WAN IP到iptables：192.168.1.2
2024-12-23 16:41:40:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-12-23 16:41:40:   - 上游 DNS 服务器 127.0.0.1 已在直接访问的列表中，不强制向 UDP 代理转发对该服务器 UDP/6553 端口的访问
2024-12-23 16:41:41:   - 访问控制：
2024-12-23 16:41:41:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-12-23 16:41:41:      - 【默认】，使用 TCP 节点[分流总节点](REDIRECT:1041)
2024-12-23 16:41:41:      - 【默认】，使用 UDP 节点[分流总节点](TPROXY:1041)
2024-12-23 16:41:42: 防火墙规则加载完成！
2024-12-23 16:41:43: 配置定时任务：自动更新【】订阅。
2024-12-23 16:41:43: 运行完成！
