### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by frank-pv** [xiaorouji/openwrt-package#3595]

**Comment by frank-pv** [comment]
目前怀疑和是这一次的提交导致的[[](url)](https://github.com/xiaorouji/openwrt-passwall/commit/d6a79ec627866959dda311d68dd79991e2acec5a)

**Comment by frank-pv** [comment]
纠正一下，是最新的master版本，目前退回https://github.com/xiaorouji/openwrt-passwall/commit/d6a79ec627866959dda311d68dd79991e2acec5a提交之前是正常的，说明是这次改动导致的

**Comment by Eternalklk** [comment]
> 纠正一下，是最新的master版本，目前退回[d6a79ec](https://github.com/xiaorouji/openwrt-passwall/commit/d6a79ec627866959dda311d68dd79991e2acec5a) 提交之前是正常的，但是在线更新规则后，又出现该bug

那个小小请教一下怎么下旧版本的代码呀？每次编译只会下最新的QAQ

**Comment by Pacio** [comment]
不是这个提交的问题，我这个提交之前编译的版本也这样，点击更新规则就触发Bug

**Comment by frank-pv** [comment]
> 那个小小请教一下怎么下旧版本的代码呀？每次编译只会下最新的QAQ

目前定位到问题是自动下载个chroute规则的问题，等会我再把问题发出来

**Comment by lwb1978** [comment]
> 目前怀疑是这一次的提交导致的[]([d6a79ec](https://github.com/xiaorouji/openwrt-passwall/commit/d6a79ec627866959dda311d68dd79991e2acec5a))

最近小肉鸡对防火墙和Dnsmasq修改比较多，我还没得研读他的代码，但是你的问题跟我昨天这个提交没有关系，我是增加smartdns的一些功能，并不涉及防火墙，而且你都没有使用到smartdns就更没有关联了，具体等 @xiaorouji 来看了，我还没熟悉这段时间的代码。

**Comment by handsomeji** [comment]
Try the latest commit.

**Comment by xh0823** [comment]
> Try the latest commit.


谢谢大佬，现在更新规则后正常使用了

**Comment by frank-pv** [comment]
> Try the latest commit.

确实是这个规则集名称问题，刚排查出来

![image](https://github.com/user-attachments/assets/e941e50f-5dce-41f3-a8a7-2db0925ab738)
![image](https://github.com/user-attachments/assets/1ef582e5-3922-486c-b05d-42b2c2cac26e)

**Comment by Pacio** [comment]
> Try the latest commit.

![image](https://github.com/user-attachments/assets/ccd21229-755c-4a8d-a241-3c5b93c5f202)
问题没解决，点击更新规则后依然不能正常分流国内
