### ISSUE TITLE
[Bug]: 24.12.26-1屏蔽不了ipv6网段

### ISSUE THREAD

**Issue by as886944123** [xiaorouji/openwrt-package#3598]
### 描述您遇到的bug

 24.12.26-1屏蔽不了ipv6网段

### 复现此Bug的步骤

![1](https://github.com/user-attachments/assets/6573e52e-0745-44f5-806e-387523b14de4)

### 您想要实现的目的

 24.12.26-1屏蔽不了ipv6网段

### 日志信息

 24.12.26-1屏蔽不了ipv6网段

### 系统相关信息

QWRT
<html>
<body>

目标平台 | ipq60xx/generic
-- | --
固件版本 | QWRT R24.9.9 (QSDK 12.2 R6) / main (git-24.254.32354-e399814)
内核版本 | 5.4.220

</body>
</html>

**Comment by as886944123** [comment]
4.66-8版本可以屏蔽了ipv6 走ipv4

**Comment by as886944123** [comment]
![2](https://github.com/user-attachments/assets/9ef36da0-2840-43be-adb5-f6f4d38b0c7c)
4.66-8的版本就可以屏蔽掉 gpt走ip4才可以用

**Comment by bcseputetto** [comment]
如果你是想代理域名不走IPv6，你用DNS里面的过滤代理域名IPv6功能就行了
![image](https://github.com/user-attachments/assets/1cf67c74-2fb5-444e-81e2-85fc9a8bd678)
DNS分流用推荐的chinadns-ng，过滤代理域名 IPv6勾上，如果你的域名在代理列表或者在分流规则里走代理，那么它就会过滤掉IPv6解析记录，就不会走IPv6了，没有必要用屏蔽这一操作
![image](https://github.com/user-attachments/assets/b6463a75-ff6b-45e8-90e3-c7df24753aba)

**Comment by as886944123** [comment]
过滤代理域名ipv6  指所有的网站都不走ipv6？

**Comment by bcseputetto** [comment]
> 过滤代理域名ipv6 指所有的网站都不走ipv6？

仅代理的，不被代理的域名，比如国内的，一样会解析到IPv6记录

**Comment by as886944123** [comment]
所有的代理都不走ipv6吗  还是就gpt一个网站不走ip6？

**Comment by bcseputetto** [comment]
> 所有的代理都不走ipv6吗 还是就gpt一个网站不走ip6？

当然是所有代理都不走IPv6

**Comment by as886944123** [comment]
这样设置代理ip6的全部屏蔽完了 这种方式不对

**Comment by bcseputetto** [comment]
你有什么特殊需求，要通过IPv6代理？

**Comment by as886944123** [comment]
ip4都是nat速度慢  ip6是公对公速度快 油管用ip4速度慢 用ip6速度拉满宽带速度 按照你这样全部屏蔽掉都走ip4nat网络 速度大大打折

**Comment by bcseputetto** [comment]
> ip4都是nat速度慢 ip6是公对公速度快 油管用ip4速度慢 用ip6速度拉满宽带速度 按照你这样全部屏蔽掉都走ip4nat网络 速度大大打折

和油管实际连接的是你的节点服务器，你的节点服务器本来就是IPv4公网，而且是IPv4公网直接分配在服务器上才对的，哪来的NAT网络速度大打折扣，你这个根本就是想太多了

**Comment by as886944123** [comment]
![2](https://github.com/user-attachments/assets/a00a4487-e45c-4651-a4b2-127626623a8b)
这些都是ip6节点   走ip6节点速度要快特别是移动宽带

**Comment by bcseputetto** [comment]
> ![2](https://private-user-images.githubusercontent.com/58317138/398635750-a00a4487-e45c-4651-a4b2-127626623a8b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODgzNzcsIm5iZiI6MTczNTE4ODA3NywicGF0aCI6Ii81ODMxNzEzOC8zOTg2MzU3NTAtYTAwYTQ0ODctZTQ1Yy00NjUxLWE0YjItMTI3NjI2NjIzYThiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA0NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMGYwNzRjNTExN2FiZTQ5YTFkYjg0ZGZlMTQxM2FkOGE0NWU1MGIzMGE1NTYxMzIxOWQ3MWY0ODg3MDZjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dhCvbVqWIwqfWUsH3sTt288NtxNH0XwLJI5G2bCah2Q) 这些都是ip6节点 走ip6节点速度要快特别是移动宽带

你误会了什么，打开过滤代理IPv6，不影响你通过IPv6连节点

**Comment by bcseputetto** [comment]
你的节点服务器是IPv4+IPv6 双栈网络
你通过节点服务器IPv6 连上节点，你依然可以通过节点的IPv4去访问网站。
你打开过滤代理域名IPv6，这丝毫不影响，你的家庭网络连节点IPv6的这段问题
家庭网络IPv6➡️节点IPv6➡️节点IPv4➡️网站IPv4

**Comment by as886944123** [comment]
24.12.26-1屏蔽不了ipv6网段  屏蔽功能用不了 我只需要屏蔽一部分 不需要全部屏蔽了 这些功能4.66-8老版本可以的

**Comment by chenchuanchao73** [comment]
刷回老版本先用

**Comment by pata166** [comment]
过滤代理域名 IPv6 ，勾选；
DNS 分流  勾选 dnsmasq就不能屏蔽ipv6，chinans-ng正常；
等作者能不能修复下

**Comment by handsomeji** [comment]
@pata166 Dnsmasq其實並沒有單獨屏蔽IPv6的功能，只是解析成::

**Comment by as886944123** [comment]
![1](https://github.com/user-attachments/assets/8ba3ef8e-c5c0-4e41-b4fb-bfa386bc4a61)
![2](https://github.com/user-attachments/assets/ae149d08-c99f-4918-a819-023aaf2ccb19)
开启过滤代理域名 IPv6 和没开滤代理域名 IPv6的区别

**Comment by as886944123** [comment]
一个50MB/S   一个5MB/S  开启过滤代理域名 IPv6就是种错误  应该屏蔽ipv6网段 我说的移动宽带网络 不清楚你们的网络

**Comment by Pacio** [comment]
> 一个50MB/S 一个5MB/S 开启过滤代理域名 IPv6就是种错误 应该屏蔽ipv6网段 我说的移动宽带网络 不清楚你们的网络

 移动就是个大内网，没有IPV6移动科学就废了，我这边尤其晚上移动如果不走ipv6科学慢死

**Comment by lwb1978** [comment]
以上问题请测试最新commit

**Comment by MichaelKnight-Net** [comment]
也使用移动宽带，ipv6节点：ipv6美国线可以到200mbit/s，香港线可以到300-500mbit/s。自从241217到241226release版本后，v6tproxy看似有问题，无法ipv6透明代理。

路由系统：
      主路由routeros，/ip/dns只填10.1.0.1和fd12::1（为istore的lan口v4v6地址），dhcp server不填写dns，自动分配前两个dns到lan设备；istore旁路由，一WAN一LAN，WAN pppoe拨号到routeros LAN上的pppoe-server获取内网ipv4和外网ipv6，wan dns来自上级通告也即10.1.0.1和fd12::1，LAN同时给routeros提供dhcp server为routeros一个WAN口分配与routeros LAN不同段的ipv4+6内网地址做routeros的，lan dns不填写。routeros通过!cn ip分流到istore。

系统设置：
      istore DNSMasq不设置转发；smartdns，default组仅含国内dns udp服务器，端口6053，第二组oversea从default组排除，仅含tls google，端口6553，不自动设置dnsmasq，双栈优选\ipv6解析开启；passwall设置非中国大陆分流，dns选china-ng，直连dns udp://127.0.0.1:6053，远程dns为udp过滤，udp://127.0.0.1:6553，passwall中勾选dns重定向、v6tproxy、v4v6 icmp劫持，不勾选过滤代理域名ipv6，勾选劫持，升级通过下载
![image](https://github.com/user-attachments/assets/232ed695-561c-4bb0-9095-628c0b25daa8)三个文件，ssh强制升级
。

现象描述：
     241208版本通过上述升级方式从老版本升级上来，升级重启后不改动任何设置， v4+v6解析正常，v4+v6 TProxy正常；同样方式从241208升级到241217后，v4+v6解析正常，v4 TProxy正常，v6 TProxy无法使用，无法打开网页或chrome显示不支持协议，passwall不反复重启。同样升级方式再强制从241217降级到241208，不改动任何设置，又一切恢复正常。241208与241217、241226间升级降级多次，现象稳定复现。

测试过程对比如下：
1，passwall日志。08版本体现dns重定向成功。
![image](https://github.com/user-attachments/assets/3022447e-f27f-490d-8258-dfbcc8243bb0)
2，ipv6测试，测试进行时的ros连接信息，可以判断ipv6解析没有问题，但tcp连接状态不正常。
![image](https://github.com/user-attachments/assets/e8c03d87-aa66-465f-aef1-375aae5773e7)
3，ipv6测试，从下面结果大致判断，v6解析没有问题，应该时v6tproxy出现了问题。
![image](https://github.com/user-attachments/assets/c358b6f8-d275-48a7-88a1-ad8d8c117eac)

请参考。

**Comment by as886944123** [comment]
没用还是屏蔽不了的
2606:4700:4400::6812:202f
2606:4700:4400::ac40:920f
2606:4700:4400::6812:231c
2606:4700:4400::6812:29f1
2606:4700:4400::ac40:9bd1
2606:4700:4400::ac40:98e4
2600:1f14:62a:de84:880a:88cc:a16:5423


这些屏蔽chatgpt.com才能打开  问题现在屏蔽不了只能开启过滤代理域名 IPv6 。 开启过滤代理域名 IPv6会导致www.youtube.com网速变慢 因为走ipv4了

**Comment by lwb1978** [comment]
如果你用ipt在ssh下输入下面的代码，看你的ip是否成功写入了ipset
`ipset list passwall_block6`
如果是nft就输入下面这个：
`nft list set "inet passwall" "passwall_block6"`

**Comment by lwb1978** [comment]
经过在imm主分支系统中测试，最新版的pw，ipt和nft防火墙工具下都能正常屏蔽ipv6！
![1](https://github.com/user-attachments/assets/7f4ca089-a47c-4ceb-a90e-0d62aa496b13)
