### ISSUE TITLE
请教下如何合理设置代理模式

### ISSUE THREAD

**Issue by jagerzhang** [xiaorouji/openwrt-package#3602]
### 问题描述

如图设置为 gfw 列表模式，局域网设备无法用到梯子，无法fq：
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/ba8689ea-066e-4005-a7d3-937c5fb32f8f" />

但是软路由测试是正常fq 的：
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/01ccc62b-f72c-4ba4-bbea-5ee0fed4d754" />

当切换使用中国列表以外的模式，一些不用fq的网站也会用到梯子，比如 ios游戏里面付费会异常，改到 gfw 列表模式就可以正常付费：
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/59484d45-83a1-4462-989c-ca6d725e26b8" />

先请教下前辈们，如何设置才能实现国内请求和国外非 gfw 的请求不走代理？

### 您想要实现的目的

如何设置才能实现国内请求和国外非 gfw 的请求不走代理？只有gfw 列表才走代理，不确定是不是其他设置有问题导致的。

### 系统相关信息

passwall 版本：4.78-1 
下载地址：https://github.com/AUK9527/Are-u-ok/blob/main/apps/README.md

**Comment by jagerzhang** [comment]
搜了下 issue：https://github.com/xiaorouji/openwrt-passwall/issues/3234，可能是 dns 设置问题，当前有问题的设置如下：
<img width="838" alt="image" src="https://github.com/user-attachments/assets/b196bbec-e060-4f0a-bda9-72c3f6888313" />

晚上回家试下这个：https://github.com/xiaorouji/openwrt-passwall/issues/3234#issuecomment-2138785813

**Comment by lwb1978** [comment]
更新到本仓库最新版本后再进行提问，你所使用的版本是8月份的，至今代码都不知道已经历经了多少commit了。

**Comment by jagerzhang** [comment]
> 更新到本仓库最新版本后再进行提问，你所使用的版本是8月份的，至今代码都不知道已经历经了多少commit了。

OK，现在已经更新到了24.12.26，辛苦大佬再看看：
![局部截取_20241227_164046](https://github.com/user-attachments/assets/965d014a-a651-4f73-92ca-5f105e071b5a)

**Comment by jagerzhang** [comment]
![局部截取_20241227_181911](https://github.com/user-attachments/assets/cc804d75-5510-442f-8923-b64985960b0a)
最终这么设置应该是可以了，等我回家再测试确认下。

**Comment by jagerzhang** [comment]
试了下，手机连接 wifi 无法fq，笔记本却可以，有点奇怪。

**Comment by jagerzhang** [comment]
试了下，手机连接 wifi 无法fq，笔记本却可以，有点奇怪。
