### ISSUE TITLE
[Feature Request]: 国内需要支持DOH自定义 DNS选项，现在所有 DOT dns 都被污染劫持到反炸页面

### ISSUE THREAD

**Issue by luowei729** [xiaorouji/openwrt-package#3604]
### 描述你想要的新功能

国内需要支持DOH自定义 DNS选项

### 描述你想要的解决方案

国内需要支持DOH自定义 DNS选项

**Comment by lwb1978** [comment]
这个你应该去chinadns-ng那边提

**Comment by lwb1978** [comment]
或者你用smartdns分流，绝大部分dns协议都支持。

**Comment by yk271** [comment]
感觉没啥用，DoT 应该是不能被劫持的，但是上游在做递归查询的时候可能会被污染，所以估计 DoH 也一样。
可以尝试将反诈的 IP 加入代理列表，搭配 chinadns-ng 后会通过可信 DNS 再次解析。

**Comment by lwb1978** [comment]
这种应该不是劫持，估计是工信部门直接要求国内dns加入的，就算doh也是返回一样的结果。

**Comment by luowei729** [comment]
> 这种应该不是劫持，估计是工信部门直接要求国内dns加入的，就算doh也是返回一样的结果。

我后来研究了，是运营商宽带的ipv4 net 网关会劫持域名的 http，https会sni阻止

**Comment by MiyouQ** [comment]
> > 这种应该不是劫持，估计是工信部门直接要求国内dns加入的，就算doh也是返回一样的结果。
> 
> 我后来研究了，是运营商宽带的ipv4 net 网关会劫持域名的 http，https会sni阻止

有啥解决办法没 比如‘https://www.mangacopy.com/’在江苏地区就被反诈劫持 上海没问题 丢进代理列表里么能正常访问 但是跑流量跑的心疼
