### ISSUE TITLE
[Bug]: 24_12_26版本ipv6透明代理问题

### ISSUE THREAD

**Issue by MichaelKnight-Net** [xiaorouji/openwrt-package#3607]
### 描述您遇到的bug

241208版本升级到241226版本重启后，v4+v6解析正常，v4 TProxy正常，v6 TProxy无法使用，chrome无法打开yt、fb等网页或显示不支持协议。再从241226降级到241208，不改动任何设置，又一切恢复正常。241208与241226间升级降级多次，现象稳定复现。

### 复现此Bug的步骤

复现BUG步骤：
          如上所述。

### 您想要实现的目的

修复ipv6透明代理功能。

### 日志信息

附241208版本防火墙。
[firewall_241208.txt](https://github.com/user-attachments/files/18266165/firewall_241208.txt)

### 截图

测试过程：
1，passwall日志。08版本体现dns重定向成功。
![image](https://github.com/user-attachments/assets/77ba8ccd-1cb7-44d6-b3a7-5c08a0c7ba07)
2，ipv6测试，测试进行时的ros连接信息，可以判断ipv6解析没有问题，但tcp连接状态不正常。
![image](https://github.com/user-attachments/assets/bb912aeb-8871-4e61-9cec-8a6534e2b047)
3，ipv6测试，从下面结果大致判断，v6解析没有问题，应该时v6tproxy出现了问题。
![image](https://github.com/user-attachments/assets/cddaa242-d283-4939-868a-3a6259d3ee1d)
**4，此测试结果在istore（iptables）和immortalwrt（nftables）官方版上现象一样。**

### 系统相关信息

路由系统：
1，主路由ros，/ip/dns只填10.1.0.1和fd12::1（为istore的LAN口v4v6地址），dhcp server不填写dns，自动分配前两个dns到LAN设备，ros一接口连接istore LAN dhcp-server获取内网v4+v6地址（无PD）作为ros的一个WAN口用于翻墙，ros通过!cn ip分流到此接口；istore旁路由，一WAN一LAN，WAN pppoe拨号到routeros LAN上的pppoe-server获取内网ipv4和外网ipv6（无PD），WAN使用默认dns，LAN不填写dns。
2，将1中istore换为immortalwrt官方版。上下系统设置一样。

系统设置：
istore DNSMasq不设置转发；smartdns，default组仅含国内dns udp服务器，端口6053，第二组oversea从default组排除，端口6553，仅含tls google并通过1070端口从代理节点出口访问，不自动设置dnsmasq，双栈优选、ipv6解析开启；passwall设置非中国大陆分流，dns选china-ng，直连dns udp://127.0.0.1:6053，远程dns为udp过滤，udp://127.0.0.1:6553，passwall中勾选dns重定向、v6tproxy、v4v6 icmp劫持，不勾选过滤代理域名ipv6。

### 其他信息

无

**Comment by xh0823** [comment]
我的是如果不开启DNS 重定向的话，没有代理的主机检测dns变国外的了，开启DNS 重定向的话国内的ipv6有些网站用不了ipv6，防火墙用的是nftables。
