### ISSUE TITLE
[Bug]: 导入Trojan的节点配置，默认使用Xray，但不会勾选tls和不会勾选不安全连接。

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#3612]
### 描述您遇到的bug

![image](https://github.com/user-attachments/assets/a643a7d8-249f-43f4-a2c1-37987aea999b)

### 复现此Bug的步骤

1、节点列表点击添加；
2、输入Trojan的节点信息；
3、点击确定；
4、不自动勾选tls和不安全连接。

### 您想要实现的目的

导入Trojan的节点信息，应该自动勾选tls和不安全连接。

### 日志信息
导入后结果应该如下：
![image](https://github.com/user-attachments/assets/2c993cf3-71e2-4c66-aaa1-c15077afc881)

节点信息：
trojan://234d084547d1a084717af7b4ed426f0488813.taobao.com@pop.air.com:1058?allowInsecure=1&tfo=0#%E9%A6%99%E6%B8%AF%20IEPL%20%5B01%5D%20%5BAir%5D

### 截图

![image](https://github.com/user-attachments/assets/6bab6f41-3363-4df9-a6cd-dfd4061e8d2a)

### 系统相关信息

最新版本：24.12.26-1

**Comment by lwb1978** [comment]
其实这个也不能算一个bug，你例子里的节点链接看上去就是专门制造错误的，security没有，sni没有，headerType没有，最主要是连最基本的传输方式都没有，全靠猜啊。没见过哪个机场是这样提供订阅链接的。
你也是ssrp那边的协作者，碰到这种垃圾链接你怎么处理？虽然我已经修改好了，给它赋予了默认值，但是我是打心里不想去修它。
