### ISSUE TITLE
[Bug]: TLS情况下，当节点没有alpn参数时，alpn选项是否应该显示为“默认”？其次，当同时有fp参数时，不能导入fp参数。

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#3614]
### 描述您遇到的bug

当节点没有alpn参数时，alpn选项显示为空，保存时自动为“默认”：
![image](https://github.com/user-attachments/assets/77b871fe-4cf6-4eed-80b3-f01ea6a2378e)

![image](https://github.com/user-attachments/assets/80557d4d-9fda-4540-85ae-9a875daf72af)

保存并应用时：
![image](https://github.com/user-attachments/assets/d89c1367-1f1c-4821-a64f-68bcba0f9f46)

### 复现此Bug的步骤

1、节点列表，点击添加；
2、点击导入分享URL；
3、输入节点信息；
4、点击确定；
5、结果输出alpn为空；
6、点击保存应用，alpn改为“默认”；

### 您想要实现的目的

当节点没有alpn参数时，alpn选项应该显示为“默认”

### 日志信息
vless://16a4a59c-e062-4b4a-b1f8-c3f1f352ccab@132.145.95.101:443?encryption=none&security=tls&sni=TG.CMLiussss.elementfx.com&fp=random&type=ws&host=TG.CMLiussss.elementfx.com&path=%2F%3Fed%3D2560#KR-Seoul-ICN%201

**当security=reality时，导入的仍然仅显示tls勾选：**

vless://6389655f-17f4-4586-99f8-333494fb0d87@172.66.47.166:443?encryption=none&security=reality&sni=bPb-WorKeR-PaNEL-a1N.pAgEs.DEv&alpn=h2%2Chttp%2F1.1&fp=randomized&type=ws&host=BPB-wORker-PANEL-A1N.PAgES.dev&path=%2F0hOdNUYv49xi3C55%3Fed%3D2560#%F0%9F%92%A6%20BPB%20-%20IPv4_1%20%3A%20443

![image](https://github.com/user-attachments/assets/77b871fe-4cf6-4eed-80b3-f01ea6a2378e)

### 系统相关信息

24.12.26-1版本

**Comment by zxlhhyccc** [comment]
如果改成如下就正常：
![image](https://github.com/user-attachments/assets/cfd4581d-7a86-43bb-83e4-8c0984967d34)

**Comment by lwb1978** [comment]
这个不是修个导入就行了的，实在不想修了，我也坐等了，xray和sing-box的设置里一堆的互斥，不是所有传输都能用reality，而且reality和tls的一些设置也是互斥的，比如目前pw的设置里ws是不能启用reality的，而reality下也不允许使用alpn。所以要改这个导入，就必须先改xray和sing-box的节点配置代码，xray和sing-box这么多类型我也不熟，所以目前pw的节点设置代码是否符合相关类型的要求就无从知晓。
楼主熟悉的话欢迎PR，ssrp那边的主力维护，pw这边能否也帮帮忙😄

**Comment by zxlhhyccc** [comment]
@lwb1978 我提的这个PR： https://github.com/xiaorouji/openwrt-passwall/pull/3615 可以实现我提到的这个问题，请审查是否可行。另外，PW这边的一堆代码，我都还没理顺，特别是app.sh，待有空理顺后倒是可以考虑。

**Comment by zxlhhyccc** [comment]
@lwb1978 大佬你刚提交的commit，导入：trojan://[234d084547d1a084717af7b4ed426f0488813.taobao.com@pop.air.com](mailto:234d084547d1a084717af7b4ed426f0488813.taobao.com@pop.air.com):1058?allowInsecure=1&tfo=0#%E9%A6%99%E6%B8%AF%20IEPL%20%5B01%5D%20%5BAir%5D 结果是这个样子:
![image](https://github.com/user-attachments/assets/c4827094-f43e-4257-a82f-1dbfbcdae35c)

**(trojan_type == "xray" && has_xray) 应改为：(vmess_type == "xray" && has_xray) 或 (vless_type == "xray" && has_xray)**

**Comment by lwb1978** [comment]
> @lwb1978 大佬你刚提交的commit，导入：trojan://[234d084547d1a084717af7b4ed426f0488813.taobao.com@pop.air.com](mailto:234d084547d1a084717af7b4ed426f0488813.taobao.com@pop.air.com):1058?allowInsecure=1&tfo=0#%E9%A6%99%E6%B8%AF%20IEPL%20%5B01%5D%20%5BAir%5D 结果是这个样子: ![image](https://private-user-images.githubusercontent.com/45259624/399155772-c4827094-f43e-4257-a82f-1dbfbcdae35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzUzNjMsIm5iZiI6MTczNTQ3NTA2MywicGF0aCI6Ii80NTI1OTYyNC8zOTkxNTU3NzItYzQ4MjcwOTQtZjQzZS00MjU3LWE4MmYtMWRiZmJjZGFlMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEyMjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjU4Y2UwOWM1NzBiOGNkOTc5ZWUwNWIwOTc1NDk5YWJjNzdhOWE2N2ViNjhiYjE2ZGQ1ZGQ0MjAyMmUxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.usJ_y1ShxtOtCMbbibqqEILajCv_Ff9BviOHkxevEXg)
> 
> **(trojan_type == "xray" && has_xray) 应改为：(vmess_type == "xray" && has_xray) 或 (vless_type == "xray" && has_xray)**

我这个逻辑是没有问题的，导入也是正常的

**Comment by zxlhhyccc** [comment]
> 我这个逻辑是没有问题的，导入也是正常的

**截图中的trojan_type值按照前面的`local trojan_type = uci:get(appname, "@global_subscribe[0]", "trojan_type") or "trojan-plus"` 不是Xray，导入时不可能没问题啊。我测试无数次导入就出了问题。所以逻辑是不对的，请大佬你再次确认一下。**

(trojan_type == "xray" && has_xray) 改为：(vmess_type == "xray" && has_xray) 或 (vless_type == "xray" && has_xray)就正常。

![image](https://github.com/user-attachments/assets/3498b68b-62be-43ec-bfb9-d5d925e7e0a6)


**下面截图的这个逻辑是trojan_type的值trojan而不是xray。**

![image](https://github.com/user-attachments/assets/c5bc265c-563f-432a-aeeb-8f11c01c2089)

**Comment by lwb1978** [comment]
**你节点订阅的地方设置 Trojan 类型是什么就是什么**
![image](https://github.com/user-attachments/assets/e8183896-a029-4823-af44-b5730a710f25)
**最简单的就是你添加节点，然后查看源码就可以看到：**
![image](https://github.com/user-attachments/assets/266e6c0c-b46f-45fe-829d-d507bf66c1fe)
**这么简单的代码逻辑你没看懂吗？**

**Comment by zxlhhyccc** [comment]
> **你节点订阅的地方设置 Trojan 类型是什么就是什么** ![image](https://private-user-images.githubusercontent.com/86697442/399161527-e8183896-a029-4823-af44-b5730a710f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Nzc4OTAsIm5iZiI6MTczNTQ3NzU5MCwicGF0aCI6Ii84NjY5NzQ0Mi8zOTkxNjE1MjctZTgxODM4OTYtYTAyOS00ODIzLWFmNDQtYjU3MzBhNzEwZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEzMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDViNmM5OGI5NjNmMzRkNTBkMjZiY2RiNTcyYTNjNTdhOWVjOTMzYjMyYzkxZmZmYTI2YTk0YjVkMWJjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g3XfFemoC00d1-p93fbntj3HY1hi-XE5zzhhDki86BQ) **最简单的就是你添加节点，然后查看源码就可以看到：** ![image](https://private-user-images.githubusercontent.com/86697442/399161655-266e6c0c-b46f-45fe-829d-d507bf66c1fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Nzc4OTAsIm5iZiI6MTczNTQ3NzU5MCwicGF0aCI6Ii84NjY5NzQ0Mi8zOTkxNjE2NTUtMjY2ZTZjMGMtYjQ2Zi00NWZlLTgyOWQtZDUwN2JmNjZjMWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEzMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5Njc3MTg5ZGM1ZTYyZGI1NWZjNDhjZmI1OWM3OWZlZDg2ZGRjYTMzZmRjYzYxZjY2ZWJkZjgzYWM0N2I0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7sd86Txjk_V_dMWs6SY8_EBx_7GCeWW-US7agYpKlD4) **这么简单的代码逻辑你没看懂吗？**

**Comment by zxlhhyccc** [comment]
![image](https://github.com/user-attachments/assets/84327d29-695d-4c26-89ed-488f25f04aec)

**Comment by lwb1978** [comment]
你查看“添加节点”的源码，搜索trojan_type 看后面的值是不是xray？用谷歌系的浏览器

**Comment by zxlhhyccc** [comment]
> 你查看“添加节点”的源码，搜索trojan_type 看后面的值是不是xray？用谷歌系的浏览器

在哪个里查看呢？
![image](https://github.com/user-attachments/assets/e913b409-36f6-4283-8874-413447615a8a)

**Comment by lwb1978** [comment]
![image](https://github.com/user-attachments/assets/f668255d-03d1-4fdf-96d8-d0f9c52f2628)

直接在页面点右键

**Comment by zxlhhyccc** [comment]
![image](https://github.com/user-attachments/assets/6fb49da9-bb8b-4982-8265-3904cea5184e)

![image](https://github.com/user-attachments/assets/23ec2478-8411-413f-9ac6-3283f810951a)

找到原因，需要在节点订阅里做一下：保存并应用，否则默认的不是Xray。是不是要修复一下？

**Comment by lwb1978** [comment]
那你都看你的配置里是不是有问题了，没保存过节点订阅的设置？
我做下判断吧

**Comment by zxlhhyccc** [comment]
> 那你都看你的配置里是不是有问题了，没保存过节点订阅的设置？

按道理默认是xray应该就是Xray，还需要保存并应用一次？

**Comment by SakuraFallingMad** [comment]
先确认下修改了节点类型后是不是没有应用，仅保存。这涉及到另外的问题了。我能复现分流管理新建一个规则并排序，仅保存后，在基本设置中并不会出现新的分流规则，必须保存并应用后才显示。
可能和最近适配调整过过luci的js有关联。

**Comment by zxlhhyccc** [comment]
> 先确认下修改了节点类型后是不是没有应用，仅保存。这涉及到另外的问题了。我能复现分流管理新建一个规则并排序，仅保存后，在基本设置中并不会出现新的分流规则，必须保存并应用后才显示。

我直接是默认Xray，然后空配置直接导入，按道理应该订阅配置里要自动有Xray。

这里保存并应用后才有，所以配置里应该要加上默认的选项应该可以。
![image](https://github.com/user-attachments/assets/a853ebb5-79e0-4162-97fc-c1fa07ec3948)

默认的订阅设置是这样子的：
![image](https://github.com/user-attachments/assets/ec384ea2-4a87-4598-81bb-f5b3614cd8ed)

**Comment by SakuraFallingMad** [comment]
> > 先确认下修改了节点类型后是不是没有应用，仅保存。这涉及到另外的问题了。我能复现分流管理新建一个规则并排序，仅保存后，在基本设置中并不会出现新的分流规则，必须保存并应用后才显示。
> 
> 我直接是默认Xray，然后空配置直接导入，按道理应该订阅配置里要自动有Xray。
> 
> 这里保存并应用后才有，所以配置里应该要加上默认的选项应该可以。 ![image](https://private-user-images.githubusercontent.com/45259624/399163834-a853ebb5-79e0-4162-97fc-c1fa07ec3948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Nzk2NjQsIm5iZiI6MTczNTQ3OTM2NCwicGF0aCI6Ii80NTI1OTYyNC8zOTkxNjM4MzQtYTg1M2ViYjUtNzllMC00MTYyLTk3ZmMtYzFmYTA3ZWMzOTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEzMzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YWU2OGQyNGI3YzMxZDQ0YjJhNGVmNTE1NDMyNjc0Mzg0ZjBlMGRmNmY0N2RhNzdhNzRjYmNmYjdjZTFiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ksS-JBO6LYPDYxSFnoAm7idtWQYDF84bM2ltoGqS41Y)

这个是老feature了？默认显示选项你需要保存并应用一次写入配置，因为我外行，只能从使用角度说明，你基本上最好在一个页面配置完后保存并应用一次。

**Comment by zxlhhyccc** [comment]
> 这个是老feature了？默认显示选项你需要保存并应用一次写入配置，因为我外行，只能从使用角度说明，你基本上最好在一个页面配置完后保存并应用一次。

我认为复杂了，不是所有用户都知道需要在订阅设置了保存并应用一次，我也不清楚，所以如果需要你最新的commit，就需在`0_default_config`文件中加上默认设置为好，你没提交最新commit以前，是不需要添加默认配置的。

**Comment by lwb1978** [comment]
look new commit
已经修改默认值。

**Comment by zxlhhyccc** [comment]
> 已经修改默认值。

PW代码太复杂了，尤其是app.sh，都看得头晕，所以我修改只能遇到问题改问题，可能会没改到位，你新的commit应该是完美了。

**Comment by lwb1978** [comment]
确实比较复杂，我差不多半年在修修补补中才慢慢熟悉pw代码，但是最近小肉鸡疯狂输出，我又跟不上了。😂
