### ISSUE TITLE
[Bug]: 极端的bug反馈

### ISSUE THREAD

**Issue by wazzx** [xiaorouji/openwrt-package#3616]
### 描述您遇到的bug

上流路由器开启PW，gfw模式，china-dns ip：192.168.2.1，二级路由器只要安装了PW，然后重启（pw没有点开关，），二级路由器无法联网，二级路由器ip192.168.8.1，无论是什么模式gfw，china列表外。
目前解决问题：1.上级路由器关闭pw，然后二级路由器重启，二级路由器就可以了联网了。
2.上级路由器开启pw，然后二级路由器卸载pw，重启，二级路由器就可以了联网了。
3.上级路由器开启pw，然后二级路由器卸载pw的2个依赖包（kmod-nft-socket kmod-nft-tproxy），重启，二级路由器也可以联网了。

### 复现此Bug的步骤

上述说明了

### 您想要实现的目的

解决bug

### 日志信息

五

### 系统相关信息

pw：[24.12.26-1]
op：23.05.5

### 其他信息

无

**Comment by zxlhhyccc** [comment]
kmod-nft-socket kmod-nft-tproxy 会影响，第一次听说。

**Comment by Aukansh** [comment]
请先正确认识路由并正确使用路由再来吧！

**Comment by wazzx** [comment]
> kmod-nft-socket kmod-nft-tproxy

kmod-nft-socket kmod-nft-tproxy没有安装好！pw在fw4模式下是不会启动的，使用就可以正常上网。

**Comment by wazzx** [comment]
目前问题反馈：已经知道解决问题，但是不知道原理：二级路由器开启gfw模式，重启正常，默认中国列表外，直接DNS解析失败连不了网
