### ISSUE TITLE
更新后产生的Trojan-Go与syncdial(多拨)插件冲突bug

### ISSUE THREAD

**Issue by lxhao61** [xiaorouji/openwrt-package#569]
目前情况是：Trojan-Go客户端与syncdial(多拨)不能正常同时用。表现是：界面测试状态都正常，但不能翻墙。若要同时用，如切换到Trojan-Go账号或默认Trojan-Go账号上网后，必须再次启动syncdial一下，才能恢复正常（每次切换或重启路由器后，都需再次启动syncdial一下。）。
经过折腾，发现是应该是28日更新‘’passwall: enable Trojan-Go TCP TProxy‘’引入的bug。换到27日编译的固件测试，Trojan-Go客户端一切正常。
请更新修复，谢谢！
passwall: enable Trojan-Go TCP TProxy链接如下：
https://github.com/Lienol/openwrt-package/commit/9abfe5c06312c8c16737b085e7131285aa0bc184

**Comment by lxhao61** [comment]
情况是：从其它科学上网账号切换Trojan-Go账号，表面状态都正常，但不能科学上网。需要重新启动（保存应用）syncdial(多拨)插件才能正常。
经过折腾，终于发现是应该是28日更新passwall: enable Trojan-Go TCP TProxy（https://github.com/Lienol/openwrt-package/commit/9abfe5c06312c8c16737b085e7131285aa0bc184）引入的bug。
目前换到之前编译固件，Trojan-Go客户端一切正常。请更新修复，谢谢！

**Comment by lxhao61** [comment]
好像此更新是解决此问题，希望L大尽快批准。
https://github.com/Lienol/openwrt-package/pull/571

**Comment by peter-tank** [comment]
如果只是混用时有问题，不会提交变更。

**Comment by lxhao61** [comment]
> 如果只是混用时有问题，不会提交变更，应该请求Trojan-Go修复吧。
@peter-tank 
什么意思？这个bug，明显不是Trojan-Go自己问题。是更新‘’passwall: enable Trojan-Go TCP TProxy‘’引入的bug。
另外执行你给的两命令，问题解决了呀。
