### ISSUE TITLE
v2ray v4.27.0版已正式新增VLESS协议，望支持。

### ISSUE THREAD

**Issue by lxhao61** [xiaorouji/openwrt-package#582]
VLESS是一个无状态的轻量传输协议，特别套tls应用，比VMess性能更佳。另外支持回落模式，相较于其它协议回落方案，更简洁、高效、安全，功能也更强大。望添加支持此协议。
https://github.com/v2ray/v2ray-core/releases
https://www.v2fly.org/config/protocols/vless.html
https://github.com/v2ray/v2ray-core/issues/2636

**Comment by xiaorouji** [comment]
莫急，该来的迟早会来。

**Comment by lxhao61** [comment]
嗯，谢谢大神！

**Comment by lxhao61** [comment]
目前支持图形化配置 VLESS 的部分客户端已丰富，仅缺路由器支持了。
Qv2ray（v2.6.3+），支持 Linux、macOS、Windows
v2rayN（v3.21+），支持 Windows
v2rayNG（v1.3.0+），支持 Android

**Comment by xiaorouji** [comment]
已初步支持，请测试。可能有BUG ）.

**Comment by lxhao61** [comment]
@xiaorouji 
好的。马上编译新固件测试及反馈。

**Comment by xiaorouji** [comment]
暂时未支持Fallback

**Comment by lxhao61** [comment]
哦，不影响，我目前仅使用其客户端。做服务器此应用才可能需要。

**Comment by lxhao61** [comment]
新加VLESS协议（客户端）经过两天测试，目前没有发现bug，很好用。
