### ISSUE TITLE
今天刚编译的passwall发现打不开总开关后国内外浏览器都打不开了

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#585]
今天刚编译的passwall发现打不开总开关后国内外浏览器都打不开了 奇怪的是QQ 却是正常的

**Comment by shanzigang** [comment]
这种情况十之八九是dns出问题了

**Comment by leochien0102** [comment]
DNS问题，更新源码编译后，DNS设置中国内DNS服务器“默认”无法上网（之前一直保持默认，没有问题），需要改成其它选项才可以。

**Comment by xiaorouji** [comment]
看下系统日志dnsmasq的

**Comment by leochien0102** [comment]
> 看下系统日志dnsmasq的

Sat Aug  8 10:04:44 2020 daemon.crit dnsmasq[30327]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 10:04:44 2020 daemon.crit dnsmasq[30327]: FAILED to start up
Sat Aug  8 10:04:44 2020 cron.info crond[30376]: crond (busybox 1.30.0) started, log level 8
Sat Aug  8 10:04:49 2020 daemon.crit dnsmasq[30421]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 10:04:49 2020 daemon.crit dnsmasq[30421]: FAILED to start up

**Comment by Myoko** [comment]
感谢上面3位 国内DNS 自定义一下就好了 之前一直是用的默认的所以这次就发现不行了

**Comment by xiaorouji** [comment]
@peter-tank

**Comment by peter-tank** [comment]
看起来新的本地DNS的获取方式不正常，倒是有人贴一下输出的log。。。
