### ISSUE TITLE
目前的DNS模式有问题！

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#588]
这个2个DNS模式 都不通！DNS模式选 dns2socks 还是 pdnsd + dns2socks 使用v2ray 外国都不通 没办法暂时只能用pdnsd + tcp 节点解析
![image](https://user-images.githubusercontent.com/3013386/89707011-3d507f80-d99d-11ea-89a6-7141d4936452.png)
![image](https://user-images.githubusercontent.com/3013386/89707016-480b1480-d99d-11ea-83b9-e51b1052aec2.png)

**Comment by dl250** [comment]
今天编译的都不能用

**Comment by peter-tank** [comment]
dns2sock 因为update 这2个commit需要关闭DNS缓存才能启动，或打个临时补丁：
```
app=/usr/share/passwall/app.sh
sed -i 's/"\$dns2sock_cache"/$dns2sock_cache/g' $app
```

**Comment by Myoko** [comment]
关闭了DNS 缓存外网也还是打不开！虽然DNS显示启动但是外网打不开
![image](https://user-images.githubusercontent.com/3013386/89710928-a1813c80-d9b9-11ea-9318-4d00d0ab36c3.png)

**Comment by peter-tank** [comment]
你开了socks服务吗？

**Comment by kxjhcmc** [comment]
@peter-tank ，国内服务器选默认，直接国内都无法解析

**Comment by peter-tank** [comment]
谁给我看下日志

**Comment by leochien0102** [comment]
![QQ截图20200808212511](https://user-images.githubusercontent.com/3915276/89711650-1c4c5680-d9be-11ea-839c-0ada74f324a8.png)


Sat Aug  8 21:24:51 2020 daemon.crit dnsmasq[8961]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 21:24:51 2020 daemon.crit dnsmasq[8961]: FAILED to start up
Sat Aug  8 21:24:56 2020 daemon.crit dnsmasq[9000]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 21:24:56 2020 daemon.crit dnsmasq[9000]: FAILED to start up
Sat Aug  8 21:25:01 2020 daemon.crit dnsmasq[9036]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 21:25:01 2020 daemon.crit dnsmasq[9036]: FAILED to start up
Sat Aug  8 21:25:06 2020 daemon.crit dnsmasq[9072]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 21:25:06 2020 daemon.crit dnsmasq[9072]: FAILED to start up
Sat Aug  8 21:25:11 2020 daemon.crit dnsmasq[9108]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
Sat Aug  8 21:25:11 2020 daemon.crit dnsmasq[9108]: FAILED to start up
Sat Aug  8 21:25:11 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by Myoko** [comment]
> 你开了socks服务吗？
> 我看你是默认的127.0可能忘了开

我没开socks服务 那个是默认的我没改

**Comment by peter-tank** [comment]
不不没改，是你不能改。需要开点socks服务，这里会出现0.0.0.0:xxx可以选

**Comment by peter-tank** [comment]
> 保持默认选项，无法上网，日志显示dnsmasq启动失败
> 
> ![QQ截图20200808212511](https://user-images.githubusercontent.com/3915276/89711650-1c4c5680-d9be-11ea-839c-0ada74f324a8.png)
> 
> Sat Aug 8 21:24:51 2020 daemon.crit dnsmasq[8961]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
> Sat Aug 8 21:24:51 2020 daemon.crit dnsmasq[8961]: FAILED to start up
> Sat Aug 8 21:24:56 2020 daemon.crit dnsmasq[9000]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
> Sat Aug 8 21:24:56 2020 daemon.crit dnsmasq[9000]: FAILED to start up
> Sat Aug 8 21:25:01 2020 daemon.crit dnsmasq[9036]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
> Sat Aug 8 21:25:01 2020 daemon.crit dnsmasq[9036]: FAILED to start up
> Sat Aug 8 21:25:06 2020 daemon.crit dnsmasq[9072]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
> Sat Aug 8 21:25:06 2020 daemon.crit dnsmasq[9072]: FAILED to start up
> Sat Aug 8 21:25:11 2020 daemon.crit dnsmasq[9108]: bad option at line 2 of /var/etc/dnsmasq-passwall.d/direct_host.conf
> Sat Aug 8 21:25:11 2020 daemon.crit dnsmasq[9108]: FAILED to start up
> Sat Aug 8 21:25:11 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

> 看起来新的本地DNS的获取方式不正常，倒是有人贴一下输出的log。。。看下拿的本地DNS是什么样子的
> 
> /tmp/resolv.conf.auto
> /tmp/resolv.conf.d/resolv.conf.auto
> https://github.com/xiaorouji/openwrt-package/blob/d540a4af47f3ac024910af8d45554dc5a5dadd63/lienol/luci-app-passwall/root/usr/share/passwall/app.sh#L294

**Comment by kxjhcmc** [comment]
lean的源码，开了DNS加速，使用这个插件，是不是DNS加速就失效了哦？？就算选择保持默认，实际都没有用DNS加速那个服务器了？DNS加速开启后，添加了DNS转发到127.0.0.1#5333

**Comment by leochien0102** [comment]
/tmp/resolv.conf.auto 内容，是拨号自动获得的ISP DNS

# Interface wan
nameserver 180.168.255.118
nameserver 116.228.111.18

**Comment by peter-tank** [comment]
> /tmp/resolv.conf.auto 内容，是拨号自动获得的ISP DNS
> 
> # Interface wan
> nameserver 180.168.255.118
> nameserver 116.228.111.18

很正常的配置，是处理的时候多于1个就会出错。

**Comment by peter-tank** [comment]
临时方案：
```
app=/usr/share/passwall/app.sh
sed -i "s/|\(.*\) sed .*,\/g')$/| cut '\\\n' ',')/" $app
```

**Comment by peter-tank** [comment]
> lean的源码，开了DNS加速，使用这个插件，是不是DNS加速就失效了哦？？就算选择保持默认，实际都没有用DNS加速那个服务器了？DNS加速开启后，添加了DNS转发到127.0.0.1#5333

不懂你们的各种加速，
选模式那个下拉框可以自定义为127.0.0.1:5333

**Comment by kxjhcmc** [comment]
> > lean的源码，开了DNS加速，使用这个插件，是不是DNS加速就失效了哦？？就算选择保持默认，实际都没有用DNS加速那个服务器了？DNS加速开启后，添加了DNS转发到127.0.0.1#5333
> 
> 不懂你们的各种加速，
> 选模式那个下拉框可以自定义为127.0.0.1:5333
明白了，谢谢，DNS加速是LEAN的一个插件

**Comment by Myoko** [comment]
今天编译的 dns2socks 和 pdnsd+dns2socks 依然不通！这个2模式！都检测谷歌连接都是失败！外网连不上

**Comment by xiaorouji** [comment]
> 今天编译的fix update然后测试了v2下 dns2socks 和 pdnsd+dns2socks 依然不通！这个2模式！检测谷歌连接都是失败！外网连不上

![image](https://user-images.githubusercontent.com/60100640/89725819-77299080-da46-11ea-8393-a5779745472f.png)
大哥，你确定你开socks服务了？

**Comment by Myoko** [comment]
> > 今天编译的fix update然后测试了v2下 dns2socks 和 pdnsd+dns2socks 依然不通！这个2模式！检测谷歌连接都是失败！外网连不上
> 
> ![image](https://user-images.githubusercontent.com/60100640/89725819-77299080-da46-11ea-8393-a5779745472f.png)
> 大哥，你确定你开socks服务了？

socks服务我一直没开过！忘记了 谢谢你的提醒

**Comment by tinnlux** [comment]
> > lean的源码，开了DNS加速，使用这个插件，是不是DNS加速就失效了哦？？就算选择保持默认，实际都没有用DNS加速那个服务器了？DNS加速开启后，添加了DNS转发到127.0.0.1#5333
> 
> 不懂你们的各种加速，
> 选模式那个下拉框可以自定义为127.0.0.1:5333

大佬，国内DNS服务器(UDP)现在还是有bug，选择自动获取就会无法正常运行dns

**Comment by peter-tank** [comment]
@tinnlux chinadns-ng？忘了
```
app=/usr/share/passwall/app.sh
sed -i 's/\(china_ng_chn=.*LOCAL_DNS\)}"$/\1%%,*}"/' $app
```

**Comment by tinnlux** [comment]
> @tinnlux chinadns-ng？忘了
> 
> ```
> app=/usr/share/passwall/app.sh
> sed -i 's/\(china_ng_chn=.*LOCAL_DNS\)}"$/\1%%,}"/' $app
> ```
> 
> 如果不是或者还是不行，就贴passwall 的 log

不是这个，是选择第一行的国内dns服务器，选择自动获取isp的dns的话就会无法启动。不分国内国外的域名解析都会无法解析。

**Comment by YunClick** [comment]
> @tinnlux chinadns-ng？忘了
> 
> ```
> app=/usr/share/passwall/app.sh
> sed -i 's/\(china_ng_chn=.*LOCAL_DNS\)}"$/\1%%,}"/' $app
> ```
> 
> 如果不是或者还是不行，就贴passwall 的 log

我这里chinadns+pdnsd无法解析，单独使用pdnsd正常。具体表现是ssh使用chinadns的7913端口解析百度正常，使用pdnsd的7914端口解析任何一个域名都是超时失败，测试tg客户端可正常上网，希望大佬看一下

**Comment by peter-tank** [comment]
@YunClick 
chinadns-ng 那个确实实际上并不影响。
你可以检查可信DNS(支持TCP查询)是不是写对了，自己从日志里检查一下。
直接pdnsd+TCP节点的模式也应当能测试出来。
不确定，且一定要用chinadns-ng的话，直接chinadns-ng+UDP节点的方式。

**Comment by YunClick** [comment]
> @YunClick
> chinadns-ng 那个确实实际上并不影响。
> 你可以检查可信DNS(支持TCP查询)是不是写对了，自己从日志里检查一下。
> 直接pdnsd+TCP节点的模式也应当能测试出来。
> 不确定，且一定要用chinadns-ng的话，直接chinadns-ng+UDP节点的方式。
> 至于ssh，我不知道你在说什么...

ssh是进入路由器的后台即命令行，可能是我表述不清楚
我并没有自定义可信dns，直接使用谷歌dns，同样的配置旧版本chinadns-ng+pdnsd可正常使用。
使用chinadns-ng+UDP模式国内和国外直接不通了，确定tcp和udp已经开了，这是使用chinadns-ng+UDP模式的dnsmasq的配置文件，直接使用8.8.4.4，而不是使用chinadns-ng的本地地址了
server=8.8.4.4
all-servers
no-resolv
conf-dir=/var/etc/dnsmasq-passwall.d

和使用chinadns-ng+pdnsd一样，国内的dns解析是正常的，但是向可信dns比如8.8.4.4查询的时候直接超时，下面是使用chinadns-ng+UDP模式的查询结果，此时tg客户端可以正常上网，关闭pw后向8.8.4.4查询是正常的。
root@OpenWrt:~# nslookup baidu.com
;; connection timed out; no servers could be reached

root@OpenWrt:~# nslookup www.baidu.com 8.8.4.4
;; connection timed out; no servers could be reached

root@OpenWrt:~# nslookup baidu.com 127.0.0.1#7913
Server:         127.0.0.1
Address:        127.0.0.1#7913

Name:      baidu.com
Address 1: 39.156.69.79
Address 2: 220.181.38.148
*** Can't find baidu.com: No answer

**Comment by peter-tank** [comment]
我猜你是在可信那里选了8.8.4.4
1. 使用UDP节点会直接使用8.8.4.4这个问题已经发现，待merg (https://github.com/xiaorouji/openwrt-package/pull/590/commits/b19fd49cd5804b4ec389530fcafc27388cb004ee#)
1. 直接往可信查询，出来超时有些詭異。
