### ISSUE TITLE
请问一下Trojan-Go+Websocket应该怎么设置

### ISSUE THREAD

**Issue by artxia** [xiaorouji/openwrt-package#596]
请问一下Trojan-Go+Websocket应该怎么设置
自建的Trojan-Go 在Trojan-QT5和ios小飞机上都能正常代理.
但是在passwall上怎么设置都不能连接。(界面上的谷歌连接和GitHub连接有数字，但不能访问境外网站）

附上Trojan-QT5和passwall的设置截图，请大佬解惑

![image](https://user-images.githubusercontent.com/50513568/89893512-14352680-dc0b-11ea-9257-5181dbd14a26.png)

![image](https://user-images.githubusercontent.com/50513568/89893469-fff12980-dc0a-11ea-92a7-0b55743c660f.png)

**Comment by xiaorouji** [comment]
没有trojan-go节点，不清楚。
@ 一下大佬吧
@peter-tank

**Comment by peter-tank** [comment]
从图片上看不出有明显的错误。 
试下把这个配置成socks5服务，以排除掉透明代理的bug。 
甚至自己kill掉进程，找到生成的配置，修改log level，手工启动 trojan-go -config /var/etc/pasawall/TCP_1.json ，以查看trojan-go输出的debug信息。
我自己使用了Trojan-Go全部外加特性，TCP是很正常的，UDP NAT目前是过于苛严，兼容性相当一般。
我使用其它加密DNS，为避免使用UDP，也许你用dns2socks或+TCP节点的方式再试试。
两边配置不匹配的话，服务端也应当能看到有Trojan-Go的异常输出。

**Comment by lxhao61** [comment]
@artxia 
你多拨吧？若是，见之前提交反馈，现在还没有修复！

**Comment by peter-tank** [comment]
临时禁用TCP TProxy参见https://github.com/xiaorouji/openwrt-package/commit/9abfe5c06312c8c16737b085e7131285aa0bc184

----
我看到QT5版的界面(记得最后发布的版本并没有修复这种SNI的使用，换到哪个仓库维护了)，不是配了ticket_reuse(会话复用)？
指纹那个软件默认就是firefox

**Comment by artxia** [comment]
@peter-tank 非常感谢！我分别使用了你列出的几种办法：

1、将该节点作为socks5节点，电脑手机分别连接该socks5，可以正常扶墙。所以可以确定配置应该是没有问题。
2、回到TCP1下，手工启动 trojan-go -config /var/etc/pasawall/TCP_1.json 报错：
`[FATAL] 2020/08/11 23:27:17 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:29 open /var/etc/pasawall/TCP_1.json: no such file or directory`
事实上这个目录下是有这个配置文件的。关于这一步我不是很明白是哪里的问题
3、将原有的pdnsd+tcp改为dns2socks+TCP，问题依然在
4、临时禁用TCP TProxy，不知道是不是和 @lxhao61 提到的多拨有关，我没有使用多拨，路由环境是旁路由扶墙用。
5、服务端和路由器上的Trojan-Go版本都是 v0.8.1

另外我自己加了TCP2，然后访问控制指定某台电脑走tcp2来做实验，问题依旧。
不知道是不是tcp节点不能成功启动trojan-go？

**Comment by peter-tank** [comment]
手误，应该是/var/etc/passwall/TCP_1.json 但不重要了，因为配置文件已经确定无误。
你确定所谓的旁路由配置正确？
有没试过其它v2ray之类的，我感觉应该有同样的问题：路由本身可以翻(可以在路由上测试`curl google` com)，其它不行(界面显示谷歌连接有数字)。
也许你主路由没有配置好DNS指向旁路由，应该是这么说吧？

**Comment by artxia** [comment]
因为我还购有其他节点，分别试过各机场订阅的v2ray、SSR、trojan，都可以正常扶墙

**Comment by peter-tank** [comment]
那我也只有那最后一招了：按上面给的commit链接里的对话，临时禁用TCP TProxy试试...

**Comment by artxia** [comment]
执行
```
ipt=/usr/share/passwall/iptables.sh
sed -i 's/trojan-go/trojan-xx/g' $ipt
```
然后重启路由器

一切正常了。
非常感谢！！

**Comment by peter-tank** [comment]
@xiaorouji 使用情况复杂，看来还是不要启用Trojan-Go的TCP TProxy好了。

**Comment by lxhao61** [comment]
@artxia 你若没有换到Trojan-Go账号，执行后就可以了，不必重启路由器。

**Comment by lxhao61** [comment]
> @xiaorouji 使用情况复杂，看来还是不要启用Trojan-Go的TCP TProxy好了。

支持。

**Comment by peter-tank** [comment]
@lxhao61你有没有在用dev分支的二进制？毕竟修复了一些泄漏的情况，也许只是跟长期使用有关。

**Comment by lxhao61** [comment]
@peter-tank 
在用。其它源码也一样，无关。

**Comment by peter-tank** [comment]
@lxhao61 看到最近brook也有相关的commit在提交，如果brook也是这样，那就是真不适合强制开启了，，，

**Comment by lxhao61** [comment]
@peter-tank 
不知道，没有用brook。
