### ISSUE TITLE
之前的恢复默认配置的选项没有了？

### ISSUE THREAD

**Issue by db-one** [xiaorouji/openwrt-package#598]
![image](https://user-images.githubusercontent.com/20243226/89974417-9a964a80-dc95-11ea-8150-b87c99ff2929.png)
这个选项还是挺方便的，可以重新做一下做成一个按钮更加方便了
今天更新固件之后，PW就启动不了，显示运行中，然后马上又显示未运行，猜测可能是因为更新了插件导致旧的配置文件造成不兼容，所以只能手动从源码复制了默认配置文件进去，重新配置就正常运行了，如果直接有恢复默认选项的按钮就可以直接一键恢复了

**Comment by Myoko** [comment]
没必要吧！手动复制一下改一下IP就可以了！

**Comment by db-one** [comment]
reset_config
关键是要记住这个参数，我上面发图是之前旧的版本的图，新版已经没有这个链接了，只能你自己记住才行，忘记了，就只能自己复制默认配置文件了，而且不知道后台把这个链接给删除了，这个参数是不是也一起删除了

**Comment by xiaorouji** [comment]
看着别扭 注释掉了

**Comment by db-one** [comment]
> 看着别扭 注释掉了

感觉有时候插件升级变动比较大需要重置配置文件的时候还是挺方便的

**Comment by xiaorouji** [comment]
下次看看改到哪里比较好而且看起来不别扭的地方

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/90301488-cc482500-ded2-11ea-9922-afdf8788a4f4.png)

可以在高级设置或者组件更新下面做一个重置配置或者恢复默认设置按钮
