### ISSUE TITLE
3.9-37 解析本地和白名单域名(UDP) 保持默认又不行了

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#599]
3.9-37 解析本地和白名单域名(UDP) 保持默认又不行了 用默认的话 内外都不通了 只能先自定义了

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/90093867-1a3c1c00-dd5f-11ea-947b-77ee36e2d0a2.png)

**Comment by Myoko** [comment]
pdnsd 和 dns2socks 都试过了！ 像li 大的设置也试过了默认情况下都是不通 自能自定义了
![QQ截图20200813122054](https://user-images.githubusercontent.com/3013386/90094186-d8f83c00-dd5f-11ea-81f7-799c248448bc.jpg)
![2](https://user-images.githubusercontent.com/3013386/90094183-d72e7880-dd5f-11ea-9d88-952992166fee.jpg)

**Comment by xiaorouji** [comment]
我不是Li，我的没问题，你之前是否使用过其他dns，去看看dhcp/dns的DNS转发是不是有，去掉

**Comment by Myoko** [comment]
> dhcp/dns

我之前没有用过其他的DNS啊！dhcp/dns里面也没有设置DNS转发

**Comment by xiaorouji** [comment]
系统日志

**Comment by Myoko** [comment]
Thu Aug 13 12:23:38 2020 cron.err crond[26587]: crond (busybox 1.31.1) started, log level 8
Thu Aug 13 12:23:38 2020 daemon.info dnsmasq[26526]: Connected to system UBus
Thu Aug 13 12:28:52 2020 daemon.err uhttpd[2465]: netstat: showing only processes with your user ID
Thu Aug 13 13:04:33 2020 daemon.err uhttpd[2465]: netstat: showing only processes with your user ID
Thu Aug 13 13:04:41 2020 cron.err crond[29319]: crond (busybox 1.31.1) started, log level 8
Thu Aug 13 13:04:41 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 13 13:04:41 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 13 13:04:45 2020 daemon.info dnsmasq[29420]: Connected to system UBus
Thu Aug 13 13:04:47 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 13 13:04:47 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 13 13:04:50 2020 daemon.crit dnsmasq[30272]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:04:50 2020 daemon.crit dnsmasq[30272]: FAILED to start up
Thu Aug 13 13:04:50 2020 cron.err crond[30338]: crond (busybox 1.31.1) started, log level 8
Thu Aug 13 13:04:55 2020 daemon.crit dnsmasq[30378]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:04:55 2020 daemon.crit dnsmasq[30378]: FAILED to start up
Thu Aug 13 13:05:00 2020 daemon.crit dnsmasq[30405]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:05:00 2020 daemon.crit dnsmasq[30405]: FAILED to start up
Thu Aug 13 13:05:05 2020 daemon.crit dnsmasq[30429]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:05:05 2020 daemon.crit dnsmasq[30429]: FAILED to start up
Thu Aug 13 13:05:10 2020 daemon.crit dnsmasq[30433]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:05:10 2020 daemon.crit dnsmasq[30433]: FAILED to start up
Thu Aug 13 13:05:15 2020 daemon.crit dnsmasq[30434]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:05:15 2020 daemon.crit dnsmasq[30434]: FAILED to start up
Thu Aug 13 13:05:15 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Thu Aug 13 13:05:23 2020 daemon.err uhttpd[2465]: netstat: showing only processes with your user ID

**Comment by xiaorouji** [comment]
打开/var/etc/dnsmasq-passwall.d/chinalist_host.conf看看第一行是什么

**Comment by Myoko** [comment]
![dd](https://user-images.githubusercontent.com/3013386/90096531-1d86d600-dd66-11ea-9f68-b07d18d6c66d.jpg)

**Comment by RAYSphere** [comment]
我还以为这是li大小号呢。他干嘛不做了

**Comment by wushenghn** [comment]
把上个版本卸载单独安装37的通了

**Comment by Myoko** [comment]
Thu Aug 13 13:29:23 2020 daemon.err uhttpd[2465]: netstat: showing only processes with your user ID
Thu Aug 13 13:29:45 2020 daemon.err uhttpd[2465]: netstat: showing only processes with your user ID
Thu Aug 13 13:29:46 2020 cron.err crond[10235]: crond (busybox 1.31.1) started, log level 8
Thu Aug 13 13:29:46 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 13 13:29:46 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 13 13:29:49 2020 daemon.info dnsmasq[10334]: Connected to system UBus
Thu Aug 13 13:29:51 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 13 13:29:51 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 13 13:29:54 2020 daemon.crit dnsmasq[11186]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:29:54 2020 daemon.crit dnsmasq[11186]: FAILED to start up
Thu Aug 13 13:29:54 2020 cron.err crond[11247]: crond (busybox 1.31.1) started, log level 8
Thu Aug 13 13:29:59 2020 daemon.crit dnsmasq[11284]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:29:59 2020 daemon.crit dnsmasq[11284]: FAILED to start up
Thu Aug 13 13:30:04 2020 daemon.crit dnsmasq[11305]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:30:04 2020 daemon.crit dnsmasq[11305]: FAILED to start up
Thu Aug 13 13:30:09 2020 daemon.crit dnsmasq[11332]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:30:09 2020 daemon.crit dnsmasq[11332]: FAILED to start up
Thu Aug 13 13:30:14 2020 daemon.crit dnsmasq[11364]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:30:14 2020 daemon.crit dnsmasq[11364]: FAILED to start up
Thu Aug 13 13:30:19 2020 daemon.crit dnsmasq[11389]: bad address at line 1 of /var/etc/dnsmasq-passwall.d/chinalist_host.conf
Thu Aug 13 13:30:19 2020 daemon.crit dnsmasq[11389]: FAILED to start up
Thu Aug 13 13:30:19 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
![12](https://user-images.githubusercontent.com/3013386/90097798-63916900-dd69-11ea-8ad2-17ef7aae2a63.jpg)

**Comment by xiaorouji** [comment]
失误，见最新源码。
