### ISSUE TITLE
最新passwall使用此种模式不能科学，谷歌检测失败！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#600]
**建议恢复使用7913端口模式！！！**
![image](https://user-images.githubusercontent.com/45259624/90144506-7a5bae00-ddb1-11ea-974b-54b19d95c96c.png)

**Comment by lxhao61** [comment]
无问题。见如下，一切正常。
image

**Comment by zxlhhyccc** [comment]
> 无问题。见如下，一切正常。
> ![image](https://user-images.githubusercontent.com/24571146/90145653-bba08d80-ddb2-11ea-870a-b5ecd72cf75e.png)

你这个不是最新版本吧

**Comment by lxhao61** [comment]
是最新版。

**Comment by lxhao61** [comment]
另外不知道怎么回事？反正用“：”没有“#”’好用。

**Comment by zxlhhyccc** [comment]
> 另外不知道怎么回事？反正用“：”没有“#”’好用。

我试试#

**Comment by zxlhhyccc** [comment]
> 另外不知道怎么回事？反正用“：”没有“#”’好用。

按照你的配置，然后使用trojan-plus仍检测谷歌失败，无法科学！！！

**Comment by lxhao61** [comment]
我没有用trojan-plus，我用的是trojan-go。
可SSH中执行如下两命令试试：
ipt=/usr/share/passwall/iptables.sh
sed -i 's/trojan-plus/trojan-xx/g' $ipt
若不行，那么只能找到大佬解决了。

**Comment by zxlhhyccc** [comment]
> 我没有用trojan-plus，我用的是trojan-go。
> 可SSH中执行如下两命令试试：
> ipt=/usr/share/passwall/iptables.sh
> sed -i 's/trojan-plus/trojan-xx/g' $ipt
> 若不行，那么只能找到大佬解决了。

请问trojan-go与trojan-plus一样的配置吗？

**Comment by lxhao61** [comment]
注意我是另外用了SmartDNS，且分组国内及国外DNS，否则不能我这样用。

**Comment by lxhao61** [comment]
> > 我没有用trojan-plus，我用的是trojan-go。
> > 可SSH中执行如下两命令试试：
> > ipt=/usr/share/passwall/iptables.sh
> > sed -i 's/trojan-plus/trojan-xx/g' $ipt
> > 若不行，那么只能找到大佬解决了。
> 
> 请问trojan-go与trojan-plus一样的配置吗？

当然各自配置不一样。DNS配置可以。

**Comment by zxlhhyccc** [comment]
> > > 我没有用trojan-plus，我用的是trojan-go。
> > > 可SSH中执行如下两命令试试：
> > > ipt=/usr/share/passwall/iptables.sh
> > > sed -i 's/trojan-plus/trojan-xx/g' $ipt
> > > 若不行，那么只能找到大佬解决了。
> > 
> > 
> > 请问trojan-go与trojan-plus一样的配置吗？
> 
> 当然各自配置不一样。DNS配置可以。

能指导一下服务器和客户端如何配置么？

**Comment by lxhao61** [comment]
百度查询相关资料。这个非科学上网DNS问题。也不是简单就可以说清楚的。

**Comment by zxlhhyccc** [comment]
> 百度查询相关资料。这个非科学上网DNS问题。也不是简单就可以说清楚的。

我开了smartdns，我是请教trojan-go在服务端和客户端如何配置！

**Comment by lxhao61** [comment]
https://github.com/p4gefau1t/trojan-go

**Comment by xiaorouji** [comment]
> 另外不知道怎么回事？用“：”没有“#”’好用。

: 和 # 都可以的，如果你填 : 实际上也会转换成#

**Comment by peter-tank** [comment]
> **建议恢复使用7913端口模式！！！**

你大概没选UDP代理节点，所以你填的8.8.4.4通常是被污染过的，真不打算开就老实只用TCP或dns2socks的方式

-----
似乎大家贴图比贴文字更方便，但这样提交的问题无法确诊，除了无法被准确检索，查看问题还不方便...
在贴日志后，你们自己的描述基本都只是侧写甚至反成了误导...
也许标题越驚悚越引人注意，如果想解决问题，不是做新闻稿的话，还是不建议取这种基本不能反映你特殊情况的标题。

**Comment by peter-tank** [comment]
> 没有用trojan-plus，我用trojan-go无问题。
> 可SSH中执行如下两命令试试：
> ipt=/usr/share/passwall/iptables.sh
> sed -i 's/trojan-plus/trojan-xx/g' $ipt

沟里带的节奏，不定哪天就翻了船。

**Comment by lxhao61** [comment]
> > 另外不知道怎么回事？用“：”没有“#”’好用。
> 
> : 和 # 都可以的，如果你填 : 实际上也会转换成#
哦，明白了。
我又测试一下。发现目前最新源码编译的，: 和 #都正常了。

**Comment by lxhao61** [comment]
> > 没有用trojan-plus，我用trojan-go无问题。
> > 可SSH中执行如下两命令试试：
> > ipt=/usr/share/passwall/iptables.sh
> > sed -i 's/trojan-plus/trojan-xx/g' $ipt
> 
> 沟里带的节奏，不定哪天就翻了船。

主要对之前trojan-go的TCP TProxy问题太深刻，参考你之前命令修改，看能否排除这个原因而已！
