### ISSUE TITLE
使用vless，速度慢的要死！！！不知道是什么原因！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#602]
![image](https://user-images.githubusercontent.com/45259624/90314866-85494680-df49-11ea-809d-0e0c7dc50abc.png)

**Comment by lxhao61** [comment]
你启用TLS来保护及仿真网站流量来隐藏没？如VLESS+WS+TLS+Caddy/nginx（反向代理），VLESS+TCP+TLS+nginx（回落）、VLESS+H2/H2C+Caddy2（反向代理）应用。

**Comment by viagram** [comment]
感谢楼上科普

**Comment by lxhao61** [comment]
@viagram 
客气了。

**Comment by xiaorouji** [comment]
楼楼楼上正解
