### ISSUE TITLE
passwall的bug

### ISSUE THREAD

**Issue by zeuero** [xiaorouji/openwrt-package#605]
内核版本 4.19.123
固件版本 openwrt r20.7.1/luci master
passwall版本 3.9-33

问题发生的过程：点击左侧选项栏，选择服务选项卡，选择passwall，选择访问控制。 点击添加，添加多个设备的代理模式，选择保存应用。    设备列表中的上下顺序或代理模式发生改变后，点击保存应用。 页面顶上的 直连列表和代理列表数据全部被清空。

**Comment by lxhao61** [comment]
现在passwall最新版本是3.9-37

**Comment by zeuero** [comment]
> 现在passwall最新版本是3.9-37

你试试3.9-37 有无这类问题？

**Comment by xiaorouji** [comment]
似乎更像是luci的bug
