### ISSUE TITLE
passwall 在开启dns服务情况下百度连接耗时明显增长

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#607]
以下为之前版本，耗时正常
![Snipaste_2020-08-17_11-58-12](https://user-images.githubusercontent.com/44677306/90356571-98136680-e082-11ea-94b9-c679451c13c6.png)
新版3.9.37，相同配置下翻倍到100ms以上
![Snipaste_2020-08-17_12-08-16](https://user-images.githubusercontent.com/44677306/90356575-99449380-e082-11ea-9b94-3902ff2c3e5e.png)
新版关闭dns后恢复正常
![Snipaste_2020-08-17_12-08-38](https://user-images.githubusercontent.com/44677306/90356578-99dd2a00-e082-11ea-9bd0-0a4b3f94822e.png)

**Comment by xiaorouji** [comment]
先说一下，那个并不是延迟，而是总耗时

**Comment by WROIATE** [comment]
> 先说一下，那个并不是延迟，而是总耗时

已更正

**Comment by yysw** [comment]
ACC加速里的DNS配置有没有打开

**Comment by RAYSphere** [comment]
![image](https://user-images.githubusercontent.com/69144237/90510947-58d23c00-e18e-11ea-97d2-07b0e21e1146.png)

**Comment by WROIATE** [comment]
> ACC加速里的DNS配置有没有打开

lienol的acc里貌似没有dns加速

**Comment by z826540272** [comment]
> ACC加速里的DNS配置有没有打开

和这个无关

**Comment by WROIATE** [comment]
我这使用最新40版还是未解决
