### ISSUE TITLE
版本37显示TCP和udp未运行

### ISSUE THREAD

**Issue by CoolCollin** [xiaorouji/openwrt-package#608]
背景：从31升级上来，31使用正常；
           日志显示正常
           dns和负载均衡运行正常
           唯独tcp和udp显示未运行，实际也是未运行。
           
           节点使用分流、负载均衡、单独节点，都不行；
           节点列表所有节点（包括负载均衡节点）都延迟正常。
           dns是pdnsd配合smartdns，smartdns正常；
           单独指定国内和国外的dns，也一样问题tcp udp不运行。

试验了35版本，也是一样的问题。目前我这里只有31及之前版本没问题。

不知道是怎么一回事

**Comment by xiaorouji** [comment]
你们这些人都不看提交评论？
不能保留配置！！！

**Comment by CoolCollin** [comment]
> 你们这些人都不看提交评论？
> 不能保留配置！！！
不好意思不常来没有看到。
意思是得重新设置一遍？原配置都得不到保留？

**Comment by xiaorouji** [comment]
是的 或者清空节点重新添加或订阅

**Comment by CoolCollin** [comment]
好的，明白了，感谢。
