### ISSUE TITLE
trojan-go 始终更新不了、google检测一直检测中

### ISSUE THREAD

**Issue by sheiy** [xiaorouji/openwrt-package#621]
![image](https://user-images.githubusercontent.com/12210038/91043345-01c4df00-e646-11ea-81b2-9404d4894f85.png)
trojan-go 始终更新不了

![image](https://user-images.githubusercontent.com/12210038/91043417-215c0780-e646-11ea-8ef1-f6e0e4477842.png)
google检测一直检测中

用的opemwrt官方19.07那个分支编译的

**Comment by sheiy** [comment]
openwrt-package
用的
b5314370b69cc9b264f8a51585e28e47283e1053

**Comment by Myoko** [comment]
好像 trojan go 之前去掉了吧 暂时不用

**Comment by RayorRui** [comment]
可能少编译了用于下载的工具
