### ISSUE TITLE
经自己测试，最新版passwall的“直连/代理名单管理”（rule_list）无效

### ISSUE THREAD

**Issue by tinnlux** [xiaorouji/openwrt-package#622]
设置走代理和不走代理的ip或者域名均无效。测试域名为ip.fm和IP138.com。测试方式为：1、默认代理模式选全局代理下，设置ip.fm和IP138.com不走代理，结果这两个网页显示的ip均为代理的ip地址。2、默认代理模式选防火墙表和中国列表以外，ip.fm和IP138.com在rule_list下设置走代理，结果这两个网页显示的ip为我宽带本来的ip。故测试直连/代理名单功能无效。

**Comment by tinnlux** [comment]
@xiaorouji 求修复这个问题。谢谢大佬！
我查了查，我测试的两个域名都在chnlist这个文件里。是不是rule_list的优先级低于chnlist啊？

**Comment by tinnlux** [comment]
@xiaorouji 大佬，我测试passwall退回到commit c6ade8ec32d9d0d044ce01bc9824c2741ce68d38（8月3日）这个版本，rule_list就是好的了。求大佬修复啊，我编程能力有限，看了半天代码看不出问题在哪。

**Comment by tinnlux** [comment]
@xiaorouji @peter-tank 我现在确定是10号更改的passwall: Update（ ba8b5c1 ）这条造成直连、代理域名功能失效了。但我不会修复。请大佬们帮忙修复下此功能吧！这个功能还是很重要的。

**Comment by peter-tank** [comment]
其实还是域名解析的问题...
这结果在我看来挺符合预期的，因为你挑的2个域名都已经在内置的中国域名内了，而且看样子又都能解析出中国和中国以外的服务器IP。
我只想说你们真的相当需要混用不同的代理模式，，，

还是同样建议把代理模式设置为4个防火墙列表，此时默认DNS会恢复到本地DNS，只有代理域名表和防火墙列表内的域名才提交给其它DNS解析。
可以再去访问控制配置实际需要的代理模式。
