### ISSUE TITLE
能否加入NAIVEPROXY？虽然它目前不支持udp，但同样VPS速度确实比其他的都快很多！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-package#630]

**Comment by lllrrr2** [comment]
支持肉鸡大大加入

**Comment by xiaorouji** [comment]
Encountered a little problem, to be determined.

**Comment by willaytoun** [comment]
我见SSR+有加入Naiveproxy的版本你可以试一下

**Comment by xiaorouji** [comment]
已经支持了

**Comment by lxhao61** [comment]
怎么选择编译支持？passwall无此选项。

**Comment by openips** [comment]
lxhao61 <notifications@github.com> 于2020年9月3日周四 上午9:45写道：

**Comment by hcym** [comment]
执行文件的编译是有了，其它还没用过，回头看看有没有luci设置

**Comment by lxhao61** [comment]
找到了。无LUCI。
![QQ图片20200903121957](https://user-images.githubusercontent.com/24571146/92073181-b4830300-ede5-11ea-8702-43b7cfbba72f.png)

**Comment by hcym** [comment]
速度怎么样？还没有部署节点就没试。

**Comment by lxhao61** [comment]
@hcym 跟VLESS+H2/H2C+Caddy2差不多。不知道是否迁移到路由器上原因，还是插件刚加入优化问题。

**Comment by hcym** [comment]
感谢分享，明天试试看看，和trojian比较比较🤣
