### ISSUE TITLE
Passwall 3.9-43 直连域名在回国模式下失效

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-package#631]
Passwall 3.9-43 直连列表中添加的域名，在回国模式（中国列表）下失效，还是会走回国代理

**Comment by xiaorouji** [comment]
使用最新源码，全部选择回国模式，使不使用chnlist都测试下

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-package/issues/685
