### ISSUE TITLE
L大好，遇到个问题passwall dns+docker adguardhome，设置如下

### ISSUE THREAD

**Issue by smalldickman** [xiaorouji/openwrt-package#637]
路由网段是192.168.1.0/24
macvlan网段是192.168.2.0/24
在docker里弄了 AdGuard Home 地址是192.168.2.32（监听80 53端口）
![4](https://user-images.githubusercontent.com/31898637/91797044-32afa000-ec54-11ea-80ae-f62d940210bf.JPG)

把passwall的dns设置成192.168.2.32如下
![1](https://user-images.githubusercontent.com/31898637/91797018-20356680-ec54-11ea-8c4c-e7f81bdcbf9a.JPG)

设置好后AdGuard Home界面正常也可以使用
![3](https://user-images.githubusercontent.com/31898637/91797100-5377f580-ec54-11ea-8357-276bf071d1c8.JPG)

百度本机ip
![2](https://user-images.githubusercontent.com/31898637/91797151-773b3b80-ec54-11ea-9917-087ea76de50c.JPG)

问题
每次五分钟左右就不能解析，需要清空ipset  刷新passwall的页面后，才能再回复正常。。几种过滤模式都试过，也是一样的效果

pawall日志
![6](https://user-images.githubusercontent.com/31898637/91798099-ba96a980-ec56-11ea-90a8-cda80bf112c7.JPG)

上游 DNS 服务器 测试
清空ipset后
![5](https://user-images.githubusercontent.com/31898637/91798161-d69a4b00-ec56-11ea-8b83-d918931c1ed6.JPG)

运行一段时间后大概五分多钟
![7](https://user-images.githubusercontent.com/31898637/91798252-12cdab80-ec57-11ea-9fa6-43eb135d7709.JPG)

确定清除ipset就可以暂时解决

**Comment by xiaorouji** [comment]
珍爱生命，远离套娃。

**Comment by xiaorouji** [comment]
理论上比较靠谱的做法应该是
passwall正常配置DNS，而不是各种自定义上游。
然后adg上游只设置一个，192.168.1.1:53
路由器重定向内网所有DNS到adg监听端口

**Comment by smalldickman** [comment]
> 珍爱生命，远离套娃。

hhh没法，没编译进去就拿docker试下，多谢指路啦，我再试试

**Comment by smalldickman** [comment]
按照指示设置如下（已解决）

1：passwall dns
![5](https://user-images.githubusercontent.com/31898637/91826479-38b37a00-ec70-11ea-8777-021adda3bf91.JPG)

2:   DHCP/DNS  常规设置
![Inked2_LI](https://user-images.githubusercontent.com/31898637/91826951-d313bd80-ec70-11ea-9fd3-34f2feefce15.jpg)

      DHCP/DNS  高级设置
![Inked3_LI](https://user-images.githubusercontent.com/31898637/91827149-0eae8780-ec71-11ea-9d94-3f42a143dc6e.jpg)

3： AdGuard上游 DNS 服务器
![Inked4_LI](https://user-images.githubusercontent.com/31898637/91827367-546b5000-ec71-11ea-98b9-5bafc20d50e4.jpg)

4：AdGuard查询日志可显示百度记录
![1](https://user-images.githubusercontent.com/31898637/91827633-ae6c1580-ec71-11ea-8729-146bd93c9507.JPG)

感谢老大@@
