### ISSUE TITLE
passwall 用连接的方式导入节点会报错，是什么原因呢？

### ISSUE THREAD

**Issue by slayercjc** [xiaorouji/openwrt-package#644]
![91662891-e2332800-eb17-11ea-9881-851576733884](https://user-images.githubusercontent.com/14236188/92049928-4c6cf680-edbe-11ea-89a2-f023d4c3fbfc.png)
![91662895-e65f4580-eb17-11ea-9da6-989caca24e05](https://user-images.githubusercontent.com/14236188/92049932-4ecf5080-edbe-11ea-9fcf-a2f245d1814e.png)

**Comment by RayKKP** [comment]
先说一下什么协议吧

**Comment by slayercjc** [comment]
trojan 协议

**Comment by slayercjc** [comment]
> 先说一下什么协议吧

trojan

**Comment by xiaorouji** [comment]
已修复
