### ISSUE TITLE
新添加的naiveproxy编译时却依赖了

### ISSUE THREAD

**Issue by Mattaclp** [xiaorouji/openwrt-package#646]
![註解 2020-09-03 120526](https://user-images.githubusercontent.com/51333346/92070185-f7d97380-eddd-11ea-8e1f-07f20beec410.jpg)
![註解 2020-09-03 120558](https://user-images.githubusercontent.com/51333346/92070193-fad46400-eddd-11ea-8bd2-b48e813cd397.jpg)

**Comment by xiaorouji** [comment]
请使用openwrt19.07或master源码编译

**Comment by xiaorouji** [comment]
大雕的openwrt19.07源也太旧了...好多包都没
