### ISSUE TITLE
trojan-go 选项还是去掉了吧

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#649]
trojan-go 组件更新 可以去掉了吧？ 反正都不能更新了
![image](https://user-images.githubusercontent.com/3013386/92202021-91715580-eeb0-11ea-9629-e8a2fd4f4f03.png)

**Comment by git-icu** [comment]
把下方https的S去掉可以更新.

**Comment by Myoko** [comment]
> 把下方https的S去掉可以更新.

居然是多了一个S引起的 我还以为这个组件失效了 多谢告知
