### ISSUE TITLE
passwall自动切换问题

### ISSUE THREAD

**Issue by wangjing-github** [xiaorouji/openwrt-package#651]
启用passwall自动切换功能后，主节点出现问题后能自动切换到备用节点，当主节点恢复后，确不能从备用节点自动切换回主节点。我观察了好久，一直都是这问题，因为我备用节点用的专线，时间长了用不起。

**Comment by hcym** [comment]
这个自动没敢用过，大雕那边也有人说问题，我都是haproxy，感觉靠谱，一目了然

**Comment by wangjing-github** [comment]
> 這個自動沒敢用過，大雕那邊也有人說問題，我都是haproxy，感覺靠譜，一目了然

haproxy是什么

**Comment by Georgiena** [comment]
> > 這個自動沒敢用過，大雕那邊也有人說問題，我都是haproxy，感覺靠譜，一目了然
> 
> haproxy是什么

做负载均衡的软件

**Comment by wangjing-github** [comment]
> > > 這個自動沒敢用過，大雕那邊也有人說問題，我都是haproxy，感覺靠譜，一目了然
> > 
> > 
> > haproxy是什麼
> 
> 做負載均衡的軟件

好的谢谢

**Comment by erenyega** [comment]
是的这问题挺长时间了，现在一般都尽量不用这功能

**Comment by db-one** [comment]
是的，所以我也一直用的负载均衡，没有用过自动切换，要是切换到备用节点之后，可以继续检测主节点，如果主节点判断通了之后，再直接自动切换会主节点就好了

**Comment by db-one** [comment]
看更新日志应该已经搞定了😂
