### ISSUE TITLE
报错缺少https-dns-proxy

### ISSUE THREAD

**Issue by bin20088** [xiaorouji/openwrt-package#655]
svn co https://github.com/openwrt/packages/trunk/net/https-dns-proxy package/openwrt-packages/https-dns-proxy
下载了这个，menuconfig也选中了，CONFIG_PACKAGE_luci-app-passwall_INCLUDE_https_dns_proxy=y。但是编译还是报错WARNING: Makefile 'package/openwrt-packages/luci-app-passwall/Makefile' has a dependency on 'https-dns-proxy', which does not exist

**Comment by Georgiena** [comment]
包的位置放错了，放在feeds/packages而且要再次执行update和install


发自 iPad 版 Yahoo 邮箱


星期六, 九月 5, 2020, 6:53 下午 于 bin20088 <notifications@github.com>写道：




svn co https://github.com/openwrt/packages/trunk/net/https-dns-proxy package/openwrt-packages/https-dns-proxy
下载了这个，menuconfig也选中了，CONFIG_PACKAGE_luci-app-passwall_INCLUDE_https_dns_proxy=y。但是编译还是报错WARNING: Makefile 'package/openwrt-packages/luci-app-passwall/Makefile' has a dependency on 'https-dns-proxy', which does not exist

**Comment by bin20088** [comment]
> 包的位置放错了，放在feeds/packages而且要再次执行update和install 发自 iPad 版 Yahoo 邮箱 星期六, 九月 5, 2020, 6:53 下午 于 bin20088 <notifications@github.com>写道： svn co https://github.com/openwrt/packages/trunk/net/https-dns-proxy package/openwrt-packages/https-dns-proxy 下载了这个，menuconfig也选中了，CONFIG_PACKAGE_luci-app-passwall_INCLUDE_https_dns_proxy=y。但是编译还是报错WARNING: Makefile 'package/openwrt-packages/luci-app-passwall/Makefile' has a dependency on 'https-dns-proxy', which does not exist — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

按你的提示找到原因了，我放那个位置也没问题，发现是源码feeds里自带这个，但是版本太旧，默认选取自带的了，已解决。感谢
