### ISSUE TITLE
使用chnlist并未打勾，部分CDN的IP被解析到国外去了

### ISSUE THREAD

**Issue by kxjhcmc** [xiaorouji/openwrt-package#660]
个人的域名，那个列表肯定没有，这似乎是一个BUG。我使用的防火墙表模式

**Comment by kxjhcmc** [comment]
另外并没有使用使用ChinaDNS-NG模式

**Comment by werifesteria** [comment]
我也遇到类似的问题，就在昨天hp、微软等网站被直接解析至国外的CDN以及国外的服务器。新的源码，前段时间无类似问题。

**Comment by SharerMax** [comment]
你们可能使用了chinadns
