### ISSUE TITLE
passwall在官方luci19.07+nginx无法手动更新规则

### ISSUE THREAD

**Issue by garypang13** [xiaorouji/openwrt-package#662]
弹窗显示错误

![image](https://user-images.githubusercontent.com/48883331/92456649-c99ccf00-f1f5-11ea-90d1-73e92106e345.png)

![image](https://user-images.githubusercontent.com/48883331/92456933-21d3d100-f1f6-11ea-91e6-e3b35d3ea1f3.png)

直接运行
lua /usr/share/passwall/rule_update.lua 无任何报错

wget 和 curl 都有安装

谢谢

**Comment by xiaorouji** [comment]
换回uhttpd。
README写的好清楚了，只保证Lienol源码正常，如果用的其他自己自行解决。
