### ISSUE TITLE
用CF自选IP添加的vmess节点失效

### ISSUE THREAD

**Issue by mamamiya99** [xiaorouji/openwrt-package#665]
用的IBM，同样的设置在V2rayN上没问题
但是搬到passwall上不套自选IP没问题，但是想V2rayN那样设置套自选IP怎么试都连不上去，不知道哪里出错了
希望大佬有空看一下

**Comment by db-one** [comment]
这个是设置问题

**Comment by mamamiya99** [comment]
> 没搞对，可以用，ipv6的cf节点也行

只套cf用没问题，然后把自选ip填到地址里，原先的地址写到host，能帮忙看看有什么问题吗？还是说有其它要设置的？先谢谢了

**Comment by Myoko** [comment]
IBM Cloud 达拉斯的超慢！

**Comment by xiaorouji** [comment]
这玩意都被撸死了 当然慢

**Comment by mamamiya99** [comment]
> 这玩意都被撸死了 当然慢

大佬能给个自选ip在passwall上怎么设置吗？网上找了圈都没找到有说的。。
