### ISSUE TITLE
passwall调用基于ssr节点的HA负载均衡导致CPU占用100%

### ISSUE THREAD

**Issue by js882829** [xiaorouji/openwrt-package#668]
passwall编译时间:20200910 最新版本

主机型号 | Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz : 4 Core 4 Thread (CpuMark : 38472.173798 Scores)
-- | --
CPU 信息 | 2099.998 MHz
固件版本 | OpenWrt R20.8.27 / LuCI Master (git-20.223.26773-d18ef13)
内核版本 | 5.4.61

固件为基于LEDE源码，feed中添加passwall编译

问题描述：
       1.passwall 使用基于ssr的节点的负载均衡，会导致CPU100%。(注passwall单独使用任一ssr节点均正常)
分析过程：
       1.查看系统进程，发现haproxy占用CPU接近50%而passwall调用5个ssr-redir占用50%。(passwd启动了5个ssr-redir(4个TCP和1个UDP))。
       2.关闭passwall保留haproxy负载均衡正常状态。使用ssrp连接ha负载均衡，ssrp一切功能正常且CPU恢复正常。
       3.关闭ssrp回到passwall将高级设置中的多进程并发由默认自动改为单进程后，CPU维持在27%左右。passwall恢复正常使用。
       4.对比passwall和ssrp相关信息，发现passwall和ssrp调用ssr-redir方式有所不同。
         passwall:
                 /usr/bin/ssr-redir -c /var/etc/shadowsocksr.json
         ssrp:
                /usr/bin/ssr-redir -c /var/etc/shadowsocksr.json -f /var/run/ssr-retcp_1.pid
        差别如上所示：ssrp显示对每个进程指定了pid，不知道这个是不是导致passwall连接ha节点导致cpu100%的原因。（注：passwall连接任一非HA节点均功能正常且CPU正常。）

请大神修复一下，感谢！

**Comment by xiaorouji** [comment]
负载均衡就不要开多进程

**Comment by js882829** [comment]
> 负载均衡就不要开多进程

好的 我还以为是bug!那没问题了！谢谢大佬！
