### ISSUE TITLE
迅雷快鸟：权限不足，无法读取UCI配置。

### ISSUE THREAD

**Issue by viagram** [xiaorouji/openwrt-package#672]

**Comment by smalldickman** [comment]
https://github.com/Lienol/openwrt/tree/dev-19.07/package/lean/luci-app-xlnetacc/root/usr/share/rpcd/acl.d
这里有个json文件，放到路由器/usr/share/rpcd/acl.d目录下重启试试看行不行

**Comment by viagram** [comment]
> https://github.com/Lienol/openwrt/tree/dev-19.07/package/lean/luci-app-xlnetacc/root/usr/share/rpcd/acl.d
> 这里有个json文件，放到路由器/usr/share/rpcd/acl.d目录下重启试试看行不行

OK了谢谢

**Comment by viagram** [comment]
> https://github.com/Lienol/openwrt/tree/dev-19.07/package/lean/luci-app-xlnetacc/root/usr/share/rpcd/acl.d
> 这里有个json文件，放到路由器/usr/share/rpcd/acl.d目录下重启试试看行不行

麻烦你发个pr

**Comment by smalldickman** [comment]
> > https://github.com/Lienol/openwrt/tree/dev-19.07/package/lean/luci-app-xlnetacc/root/usr/share/rpcd/acl.d
> > 这里有个json文件，放到路由器/usr/share/rpcd/acl.d目录下重启试试看行不行
> 
> 麻烦你发个pr

这个是Lienol仓库原本就有的搭配好的。。如果需要移植某个应用的话看下有没有json，以前也刚好遇到这个问题
