### ISSUE TITLE
3.9-57 代理模式问题，设备重启后梯子失效。

### ISSUE THREAD

**Issue by dhobii** [xiaorouji/openwrt-package#675]
***  搬瓦工自建vmess节点；
***  国内DNS：119.29.29.29；
***  过滤模式：DoH；
***  解析代理：通过TCP；
***  DoH地址：LibreDNS；
***  TCP/UDP默认代理：中国列表以外；
***  自身TCP/UDP代理：防火墙表；
***  已更新规则。

***  2020/09/14凌晨编译的3.9-57；
***  测试工具：macOS，Chrome 85；
***  Luci-->系统-->重启，以下简称“热启动”；
***  设备手动断电重启，以下简称“冷启动”。

#  **问题：**
路由器自身TCP/UDP代理：_防火墙表_，谷歌连接测试“连接失败”，梯子正常；
热启动，网络正常，谷歌连接测试“连接失败”；
冷启动，网络正常，谷歌连接测试“连接失败”。

路由器自身TCP/UDP代理：_默认_，谷歌连接测试正常，梯子正常；
热启动，微信、手机京东等正常，梯子失效，https://ip.skk.moe 打不开，需要在LuCi-->PassWall中手动操作“主开关”；
多次热启动，偶尔正常；
冷启动，正常。

路由器自身TCP/UDP代理：_中国列表以外_，谷歌连接测试正常，梯子正常；
热启动，微信、手机京东等正常，梯子失效，https://ip.skk.moe 打不开，需要在LuCi-->PassWall中手动操作“主开关”；
多次热启动，偶尔正常；
冷启动，正常。

更改自身TCP/UDP代理：_全局_，谷歌连接测试正常，梯子正常；
热启动，微信、手机京东等正常，梯子失效，https://ip.skk.moe 打不开，需要在LuCi-->PassWall中手动操作“主开关”；
LuCi不出现登录页面，网页不关，SSH工具连接软路由，随便操作点什么，LuCi登录页面稍后打开；
SSH中，“ping www.baidu.com” 正常，“culr www.baidu.com” 无数据；
冷启动，现像与热启动一样。

#  **现在只能使用“防火墙表”模式，暂时没有使用“定时重启”功能，不知道这个问题会不会影响重启后上网。**

**Comment by jyy5206** [comment]
我也碰到差不多情况

9月16日19:23和9月17日1:25
编译出来的针对不同路由器的2个固件
发生以下同样情况：
*Vmess无法翻墙，但是SS可以翻墙*

访问谷歌时，出现：

> 未连接到互联网
> 请试试以下办法：
> 
> 检查网线、调制解调器和路由器
> 重新连接到 Wi-Fi 网络
> 运行 Windows 网络诊断
> DNS_PROBE_FINISHED_NO_INTERNET

访问国内网站=OK的。

好像是DNS的问题？

以前编译的数个不同路由器的固件
就没有这个情况

**Comment by jyy5206** [comment]
谷歌了下
好像是客户端V2ray升级到了4.28后
需要服务端也一起同步升级到4.28

可是我是机场
服务端改不了啊。。。

同时
客户端我可以重新编译
可是如何把V2ray回退到4.27呢？
求大神请教

**Comment by qiaoliG** [comment]
> 谷歌了下
> 好像是客户端V2ray升级到了4.28后
> 需要服务端也一起同步升级到4.28
> 
> 可是我是机场
> 服务端改不了啊。。。
> 
> 同时
> 客户端我可以重新编译
> 可是如何把V2ray回退到4.27呢？
> 求大神请教

我是把 v2ray 的 AlterID 改为 1 ,只要不是 0 就正常了. 你试试看.

**Comment by jyy5206** [comment]
@qiaoliG 
测试OK！
你就是一个神奇的魔术师~
鞠躬致谢！
