### ISSUE TITLE
只能使用SSR，V2RAY使用不了。

### ISSUE THREAD

**Issue by wastelandx** [xiaorouji/openwrt-package#677]
9月15日编译的最新版固件，没有改过menuconfig，全新安装，使用阿里DNS+PDNSD进行配置，V2RAY应用之后，谷歌连接检测失败，打开网页也是失败的，后面尝试的换了SSR，就可以连接了。

自建的V2RAY香港腾讯云+机场V2RAY都试过了，就是连接不了，同一个机场换了SSR模式订阅就可以了。

**Comment by Myoko** [comment]
是你自己的问题吧！V2RAY没问题

**Comment by EdiTurn** [comment]
v2ray 4.28.1 在 alterId 为 0 时会默认启用 AEAD。
主要同时更新服务器和客户端。

**Comment by lxhao61** [comment]
你的问题是楼上告知问题，跟passwall无关！

**Comment by wastelandx** [comment]
感谢！
