### ISSUE TITLE
为啥我编译出来的插件版本一直是3.6.40呢，我看了一眼拉下来的代码，是3.9.xx啊。。

### ISSUE THREAD

**Issue by li-xunhuan** [xiaorouji/openwrt-package#678]
![QQ20200915-093104](https://user-images.githubusercontent.com/10476982/93154445-318f7000-f736-11ea-9d9b-6af6bb24c9bd.png)

**Comment by dhobii** [comment]
试试这个？
git clone https://git.openwrt.org/openwrt/openwrt.git ./
sed -i '$a src-git lienol https://github.com/xiaorouji/openwrt-package.git' ./feeds.conf.default
./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by li-xunhuan** [comment]
> 试试这个？
> git clone https://git.openwrt.org/openwrt/openwrt.git ./
> sed -i '$a src-git lienol https://github.com/xiaorouji/openwrt-package.git' ./feeds.conf.default
> ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a

我用的`Lean`的`Lede`

**Comment by dhobii** [comment]
方法都是一样的啊，你不看第一排拉取官方源就行了。
添加第三方APP的源，再下载源码。

**Comment by li-xunhuan** [comment]
我现在就是这么操作的，很迷惑，我看了feeds里面的代码的版本，确实是最新的

**Comment by li-xunhuan** [comment]
我找到原因了，是我自己傻逼！！
