### ISSUE TITLE
建议访问控制添加只代理列表中的IP

### ISSUE THREAD

**Issue by erenyega** [xiaorouji/openwrt-package#679]
软路由在公司用，连接的设备比较多而且经常有新设备连接，一个一个放黑名单不太可能.感觉挺有用的希望rouji大佬能早日支持.

**Comment by viagram** [comment]
奇怪，这本来就支持的啊。

**Comment by lysoul147** [comment]
默认代理模式选择不代理，访问控制里把需要代理的设备IP加入并分别选择代理模式就可以了。

**Comment by erenyega** [comment]
好的好的原来早已支持了啊，越来越感觉到passwall的强大了🤠
