### ISSUE TITLE
passwall server socks协议无法开启udp

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-package#682]
正常开启socks服务器，使用lsof -i检查端口发现未监听udp以及v6地址，导致另一主机使用passwall无法连接上socks服务器

**Comment by xiaorouji** [comment]
应该是 ssocksd不支持udp

**Comment by xiaorouji** [comment]
可以试试v2的socks

**Comment by WROIATE** [comment]
> 可以试试v2的socks

v2的socks直接无法开启

**Comment by xiaorouji** [comment]
测试没有问题，你自行检查下

**Comment by WROIATE** [comment]
> 测试没有问题，你自行检查下

我这测试有点奇葩，我在小米ac2100可以v2正常开启，在x86_64上则无法打开
v2的也只打开了tcp端口

随便一提，我在x86_64上ssr服务器如果密码none，也打不开，但在ac2100上可以打开，不知道为啥

**Comment by WROIATE** [comment]
更新一下，sse不关开啥只要加密是none就不行，协议好像也只支持origin
显示能打开，但是客户端连不上

**Comment by xiaorouji** [comment]
服务端能启动起来，不算bug
