### ISSUE TITLE
编译 naiveproxy 报错

### ISSUE THREAD

**Issue by jlzsss** [xiaorouji/openwrt-package#683]
报错如下：
error: ../../chrome/android/profiles/afdo.prof: Could not open profile: Unrecognized sample profile encoding format
1 error generated.
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:88: /media/jlz/FIRMWARE/op19/build_dir/target-x86_64_musl/naiveproxy-85.0.4183.83-1/.built] Error 1
make[3]: Leaving directory '/media/jlz/FIRMWARE/op19/feeds/lienol/package/naiveproxy'
time: package/feeds/lienol/naiveproxy/compile#37.67#4.15#13.03
make[2]: *** [package/Makefile:113: package/feeds/lienol/naiveproxy/compile] Error 2
make[2]: Leaving directory '/media/jlz/FIRMWARE/op19'
make[1]: *** [package/Makefile:107: /media/jlz/FIRMWARE/op19/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/media/jlz/FIRMWARE/op19'
make: *** [/media/jlz/FIRMWARE/op19/include/toplevel.mk:227：world] 错误 2

**Comment by xzjue5** [comment]
把SSR Plus下的naiveproxy取消就行了

**Comment by lxhao61** [comment]
Lienol大源编译，无一点问题。

**Comment by jlzsss** [comment]
找到原因了，是代理的问题。
