### ISSUE TITLE
增加关闭VMessAead选项

### ISSUE THREAD

**Issue by Aiaminm** [xiaorouji/openwrt-package#686]
v2ray在4.28.0引入了VMessAead导致alterId为0的节点无法连接，希望能够关闭VMessAead

**Comment by hcym** [comment]
瓦工机场是改成8了，暂时可以续命，

**Comment by lxhao61** [comment]
> v2ray在4.28.0引入了VMessAead导致alterId为0的节点无法连接，希望能够关闭VMessAead

你想多了！VMessAead开启在服务端！只要服务器端alterId为0，就强制开启。客户端随便你关闭都不行！

**Comment by Aiaminm** [comment]
用最新的4.28.2版本只要是Alterid=0的节点访问网站都是连接被终止,退回到4.27.5版本可以正常使用

**Comment by Aiaminm** [comment]
现在很多节点提供商都没有升级v2ray到最新版本，所以不支持VMessAead,而最新版v2ray-core默认开启，如果passwall有关闭选项，就可以解决一些老节点无法连接的问题

**Comment by SharerMax** [comment]
alertId 为 0 本身就是 VmessAEAD 的开启选项，所以没有什么增加不增加选项的问题。

这个问题主要还是版本升级过渡出现的兼容性问题（虽然 `v2ray` 项目组早就提出了相关的升级说明来尽可能的避免升级带来的配置问题）
以下几种方法可以解决这个问题
1. 自行升级服务端（或要求服务商升级）
2. 修改设置（修改alertId）来达到向下兼容的目的
3. 自行下载（https://github.com/v2fly/v2ray-core/releases） 或编译需要的版本替换 `v2ray`程序，其默认目录 `/usr/bin/v2ray/`

**Comment by lxhao61** [comment]
> 现在很多节点提供商都没有升级v2ray到最新版本，所以不支持VMessAead,而最新版v2ray-core默认开启，如果passwall有关闭选项，就可以解决一些老节点无法连接的问题

@Aiaminm 
不知道你逻辑！你passwall中v2ray客户端Alterid设置不为0就关闭了VMessAead！但你这样掩耳盗铃，无卵用！只要你机场v2ray服务器Alterid=0，还是强制开启VMessAead的，连接不了！你只能让机场如上边朋友方法解决！或你自己for大佬源码后，对v2rya进行降级后，以你修改后源码编译！
这些都跟大佬passwall无关！需要你自己解决！

**Comment by Aiaminm** [comment]
引用
https://github.com/v2fly/v2ray-core/issues/195
https://github.com/2dust/v2rayNG/issues/596
https://github.com/2dust/v2rayN/issues/999
希望可以针对单个节点选择不同版本的v2ray-core
或者加入为alterid=0的节点关闭VMessAead选项
引用
https://github.com/v2ray/v2ray-core/releases/tag/v4.28.2
有许多人的节点都是免费的，并没有访问服务器的权限。

**Comment by xiaorouji** [comment]
没有必要，一切按官方为标准

**Comment by EdiTurn** [comment]
4.28.2 里已加入了客户端单方面禁用 AEAD 的功能了。
既然以官方为标准，加个开关也并无不可吧?

**Comment by xiaorouji** [comment]
发pr

**Comment by EdiTurn** [comment]
不熟悉 lua，pr 我就不提了。有需要的朋友自行添加下面这行到 app.sh 吧，v2ray 版本需大于 4.28.2

`export V2RAY_VMESS_AEAD_DISABLED=true`
