### ISSUE TITLE
启用brook后tcp显示未运行

### ISSUE THREAD

**Issue by tporwx** [xiaorouji/openwrt-package#687]
启用brook后tcp显示未运行，实际应该是正常运行的。

**Comment by xiaorouji** [comment]
ps | grep passwall/bin | grep brook

**Comment by tporwx** [comment]
root@OpenWrt:~# ps | grep passwall/bin | grep brook
 1348 root      786m S    /var/etc/passwall/bin/brook_udp_1 tproxy -l :1041 -s
 1387 root      786m S    /var/etc/passwall/bin/brook_udp_1 tproxy -l :1051 -s

这是tcp未运行？
关闭UDP节点后，UDP还是显示运行中

**Comment by xiaorouji** [comment]
已修复
