### ISSUE TITLE
本地电脑可以Google，路由自身Google连接却显示连接失败，是否意味着路由再启用一个L2TP VPN或Trojan-Plus服务器端，远程接入也无法Google连接？

### ISSUE THREAD

**Issue by hawie** [xiaorouji/openwrt-package#689]
本地电脑可以Google，路由自身Google连接却显示连接失败，是否意味着路由再启用一个L2TP VPN或Trojan-Plus服务器端，远程接入也无法Google连接？
之前用lean的ssrplus, 再加trojan server实现同样的，远程经路由，可访问Google。(但有数据回绕导致内存泄漏，没法长时用)。现改用passwall没有内存泄漏，但目前远程经路由访问不了Google。

luci中的‘Google连接’是产生的什么动作，ping google哪个网址？有可能的话，想了解来手工验证一下。

当前设置
主要：TCP节点/Trojan-Plus, UDP节点/与TCP节点相同
模式：TCP/GFW列表， UDP/游戏模式，路由器自身TCP/GFW列表，路由器自身UDP/GFW列表
解析本地和白名单域名(UDP)：114.114.114.114
其余默认。

不知道需要怎样调整配置？

**Comment by xiaorouji** [comment]
不是ping，用curl请求
curl https://www.google.com

**Comment by hawie** [comment]
> 不是ping，用curl请求
> curl https://www.google.com
谢谢老大！试了在路由上的确访问不了。看配置路由器自身也是用的GFW列表，看来没作用上。
不过，这个路由刚重置刷入时，先在单位的网络试了一下，Google连接是显示连接成功的，而现在是放在家里用，就不能连接成功了。两者网络在外网口有差别，前者，单位网是DHCP分配的ipv4内网地址；后者是PPPoE分配的ipv4+ipv6 pd公网地址，另外后者还有移动+电信双光纤，mwan3，负载均衡……，不确定是哪个引起，有时间再排查。
如果Google连接显示连接成功，那么在passwall中再启用一个服务端（trojan plus），远程就也能访问Google了，这理解对吧？

**Comment by hawie** [comment]
我找到一些迹象，有个思路，您看看：
curl https://www.google.com 在路由上无法访问，在电脑端可以访问
curl不是不经trojan代理的icmp，走的是tcp, 所以在路由curl测试应该是走代理的，但无法访问就只有一个可能，域名解释不对。
于是， 在路由上：
root@Home:/# nslookup www.google.com
Server:         240e:1f:1::1
Address:        240e:1f:1::1#53

Name:      www.google.com
Address 1: 104.244.46.208
Address 2: 2001::d01f:fe21

在电脑端：
~ % nslookup www.google.com
Server:		240e:fe:3302:c500::1
Address:	240e:fe:3302:c500::1#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.24.36

~ % nslookup www.google.com 192.168.1.254
Server:		192.168.1.254
Address:	192.168.1.254#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.24.36

对比发现，路由端的默认DNS，变成了运营商的dhcpv6-pd获取的DNS 1。电脑端指向的是正确的路由的ipv4和ipv6地址。
运营商的域名解析，应该是污染了的吧。

那么，下面的问题是，如何强制将路由的dns走passwall所设置的？

**Comment by hawie** [comment]
去掉"使用对端通告的 DNS 服务器"、自定义DNS，只影响了ipv4。路由dns依然是运营商派下来的ipv6 dns 1。
passwall在ipv6的情况下，需要什么样设置，让它接管路由自身的dns？

**Comment by hawie** [comment]
临时办法，手工将/etc/resolv.conf的nameserver改为127.0.0.1，屏蔽原来的，google连接测试显示连接成功了。
root@Home:/# cat /etc/resolv.conf 
# Interface wan_6
#nameserver 240e:1f:1::1
#nameserver 240e:1f:1::33
# Interface wan
#nameserver 202.96.128.166
#nameserver 202.96.134.133
nameserver 127.0.0.1

**Comment by hawie** [comment]
不过，这一会儿功夫，路由就自动将dns重置了。变成了未更改前的：
```
root@Home:/# cat /etc/resolv.conf 
# Interface wan_6
nameserver 240e:1f:1::1
nameserver 240e:1f:1::33
# Interface wan
nameserver 202.96.128.166
nameserver 202.96.134.133

```

**Comment by hawie** [comment]
原来是这样：
```
root@Home:/etc# ls -al resolv.conf 
lrwxrwxrwx    1 root     root            16 Sep 15 14:01 resolv.conf -> /tmp/resolv.conf
root@Home:/etc# ls -al /tmp/resolv.conf
lrwxrwxrwx    1 root     root            35 Sep 25 08:08 /tmp/resolv.conf -> /tmp/resolv.conf.d/resolv.conf.auto
root@Home:/etc# cat /etc/config/dhcp | grep resolv.conf
        option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'

```
所以，暂时删了/etc/resolv.conf的超链接。重新创建一个/etc/resolv.conf文件：
```
root@Home:/etc# rm /etc/resolv.conf 
root@Home:/etc# echo 'nameserver 127.0.0.1' > /etc/resolv.conf
```
至此，路由端的google连接测试显示连接正常。路由重启也存在，自身dns没再被更新覆盖，算是ipv6下的临时办法。

**Comment by xiaorouji** [comment]
resolv.conf没有指向dnsmasq，那就难怪不行了。
有可能真的和多线拨有关系

**Comment by SharerMax** [comment]
忽略解析文件

**Comment by pidou122** [comment]
我的情况和hawie一模一样，今天刚编译的系统。我没有多播，就只有一根线路，刚设置好passwall的时候，google测试连接是正常的，只要重启一次以后，就一直是失败，可以访问google等外网，但是google测试连接失败。刚才用了DHCP 忽略解析文件 这个方法测试了下，重启后也都测试google连接正常了。但是我之前的版本google测试连接都正常，没有遇到现在的问题。
