### ISSUE TITLE
L大源码19.07编译passwall使用naiveprosy节点无法上网问题

### ISSUE THREAD

**Issue by FreeJ233** [xiaorouji/openwrt-package#697]
大佬，在19.07编译出来的passwall，配合smartdns使用，其他节点比如v2ray节点正常使用，但是naiveproxy节点可以打开telegram等手机app，无法打开google，youtube等网站外网。前提，naiveproxy节点测试Qv2ray电脑端过是正常畅通的。

请大佬指教一下~！

**Comment by xiaorouji** [comment]
用passwall内置DNS

**Comment by FreeJ233** [comment]
谢谢大神指点，关掉smartdns后naiveproxy正常运行。
是否未来有可能解决这个问题，长城用户表示很无奈
Ծ‸Ծ

**Comment by xiaorouji** [comment]
This is not a bug, Close.
