### ISSUE TITLE
v2ray编译出错，求教！

### ISSUE THREAD

**Issue by tinnlux** [xiaorouji/openwrt-package#698]
问题貌似出在xtls上，但我看不懂，错误如下：
go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013

Building targets
github.com/xtls/go
# github.com/xtls/go
pkg/mod/github.com/xtls/go@v0.0.0-20200921133830-416584838a0f/auth.go:29:7: undefined: ecdsa.VerifyASN1
pkg/mod/github.com/xtls/go@v0.0.0-20200921133830-416584838a0f/key_schedule.go:177:16: xShared.FillBytes undefined (type *big.Int has no field or method FillBytes)

Cleaning module download cache (golang/go#27455)

make[2]: *** [Makefile:312: /home/ubuntu/openwrt/build_dir/target-x86_64_musl/v2ray-core-4.29.0/.built] Error 2
make[2]: Leaving directory '/home/ubuntu/openwrt/feeds/lienol/package/v2ray'
time: package/feeds/lienol/v2ray/compile#2.45#3.00#18.45
make[1]: *** [package/Makefile:113: package/feeds/lienol/v2ray/compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt'
make: *** [/home/ubuntu/openwrt/include/toplevel.mk:236：package/v2ray/compile] 错误 2

**Comment by xiaorouji** [comment]
需要go > 1.5
只有用lienol的openwrt源码才可以编译通过

**Comment by tinnlux** [comment]
@xiaorouji 哦我从v2fly那里也查到了需要1.5以上，那我改改op主线makefile吧。。谢谢

**Comment by xiaorouji** [comment]
https://github.com/Lienol/openwrt-packages/commits/dev-19.07/lang/golang

**Comment by rprx** [comment]
纠正一下。。。是 1.15（避免误导）

**Comment by xiaorouji** [comment]
> 纠正一下。。。是 1.15（避免误导）

手误..
