### ISSUE TITLE
vless+ws+tls似乎无法使用

### ISSUE THREAD

**Issue by starP-W** [xiaorouji/openwrt-package#701]
![image](https://user-images.githubusercontent.com/22597802/94770285-d1135a80-03e6-11eb-9223-e895d8393b6d.png)
配置如图，使用该配置后无法连接（配置是直接复制粘贴v2rayN里的，电脑上确认配置正确，mux无论开关均无法使用），试着做了个iepl中转的无纯tcp vless则连接正常。
是设置得不对还是暂时没支持？望解答

**Comment by xiaorouji** [comment]
检查证书是否可用或者是否过期？
勾选允许不安全连接看看

**Comment by starP-W** [comment]
我是用caddy来维护证书的，经过测试在该域名下vmess+ws+tls可以正常连接，vless无论是否允许不安全连接、是否开启mux均无法使用。
此问题发生在版本3.9-57、v2ray版本为4.28.1的情况下，这几天是否修复暂时未测试。

**Comment by lxhao61** [comment]
@starP-W v2ray 4.28.1版本问题。现在v2ray已经4.30.0，建议服务器与客户端都升级到4.30.0。

**Comment by starP-W** [comment]
经过最新版测试，发现此问题依然存在。
此外，经过测试，发现此问题发生在服务端使用了vless+ws+tls组合并经过国内中转的情况下(已确认中转可以正常使用)。如果直接连接服务端的443端口则不会出现该问题，无论是否开启mux。

这是可以正常使用的配置
![image](https://user-images.githubusercontent.com/22597802/95163415-6002e700-07da-11eb-83bb-9a40cc4d6e79.png)

**Comment by xiaorouji** [comment]
如果是直接端口中转的话，请填写真实服务器的域名

**Comment by starP-W** [comment]
感谢解答，原来域名和websocket host里要填一样的信息，之前还以为只需要填ws host就够了
