### ISSUE TITLE
最新的版本会在生成socks代理出错

### ISSUE THREAD

**Issue by lonee6** [xiaorouji/openwrt-package#706]
最新的版本会在生成socks代理时候远程地址变成   "remote_addr": "127.0.0.1",
请修正。

**Comment by lonee6** [comment]
我把
if relay_port and relay_port ~= "nil" then
    trojan.remote_addr = "127.0.0.1"
    trojan.remote_port = tonumber(relay_port)
end
这段删掉了，问题解决了，但不知道有没有带来其它负作用。

**Comment by xiaorouji** [comment]
Fix.
