### ISSUE TITLE
passwall 这次更新后 今天编译固件不成功了

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#708]
每次编译总是提示https-dns-proxy和syncthing 不存在！最后编译始终失败 

![image](https://user-images.githubusercontent.com/3013386/95184840-80429e00-07fa-11eb-8cdc-d3d7009f4adb.png)

**Comment by lxhao61** [comment]
无问题，刚编译了两次。你可能网络不好，过程中部分没有下载成功造成的。

**Comment by Myoko** [comment]
> 过程中部分没有下载成功造成的。

可是在云端用 Action-passwall 编译也失败 奇怪了

**Comment by lxhao61** [comment]
你是用的不是Lienol大源码编译吧？

**Comment by Myoko** [comment]
果然是https-dns-proxy有问题！跳过这个在passwall依赖里面取消了https-dns-proxy 编译就成功了
