### ISSUE TITLE
建议还是把https-dns-proxy默认依赖去掉吧

### ISSUE THREAD

**Issue by Myoko** [xiaorouji/openwrt-package#709]
建议还是把https-dns-proxy默认依赖选项去掉吧 今天编译了 几次固件都失败！最后没办法只能不编译https-dns-proxy了！最后居然还成功了
https-dns-proxy 会自动设置 2条 DNS 转发在 网络-HDCP/DNS-DNS 转发 里面！删除了之后无法联网了
使用的lean大雕的4.19稳定版仓库在云端编译的
![image](https://user-images.githubusercontent.com/3013386/95200761-8001cd00-0811-11eb-9bc3-3b9680df054f.png)

**Comment by xiaorouji** [comment]
Li写的luci肯定是以Lienol的openwrt源码做标准，没有义务适配其它的固件源码

**Comment by Myoko** [comment]
> Li写的luci肯定是以Lienol的openwrt源码做标准，没有义务适配其它的固件源码

了解！但是用Li的仓库编译的时候还是会提示https-dns-proxy不存在！哎算了 我自己每次编译的时候手动取消一下就是了 反正psw 也不非https-dns-proxy不能用！不编译这个照常使用！

**Comment by xiaorouji** [comment]
并不会啊，我都是直接编译就过了

**Comment by Myoko** [comment]
> 并不会啊，我都是直接编译就过了

我这边源码下载有点问题！刚才又重新下载一次 这次好了！感谢 xiaorouji
