### ISSUE TITLE
ipv6节点无法分流

### ISSUE THREAD

**Issue by RainCat1998** [xiaorouji/openwrt-package#710]
如题，当节点为ipv6节点，地址栏为ipv6地址时，分流页面中对应节点会消失。
如果地址栏输入域名，对应ipv6节点可以分流，希望可以修复。
ipv4节点不存在上述问题

**Comment by xiaorouji** [comment]
这是设计上没考虑ipv6的原因

**Comment by RainCat1998** [comment]
> 这是设计上没考虑ipv6的原因

实际上ipv6节点在passwall中使用非常完美，仅仅只是使用分流功能时，ipv6节点会不在选项卡中，并且ipv6节点不能进行延迟检测。但是如果ipv6节点不是通过ip进行节点配置，而是通过域名进行节点配置，上述问题均不存在。
感觉这就是一个简单的显示逻辑的bug，希望可以修复。

**Comment by RainCat1998** [comment]
> 这是设计上没考虑ipv6的原因
连接ipv6节点主要是满足没有主机公网ip或者校园网ipv6免流的需求

**Comment by xiaorouji** [comment]
更新最新源码即可
