### ISSUE TITLE
（建议）chinadns-ng好久不更新了…不知……

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-package#712]
看到一个尚在维护的chinadns版本…
既然chinadns-ng好久没更新了…
大佬要是有空…
也许可以换成这个？
https://github.com/IrineSistiana/mos-chinadns
当然也不是什么问题，大佬闲的话，可以观察一下(●°u°●)​ 」

**Comment by xiaorouji** [comment]
说实话 不想再集成dns了，内置的dns方案已经足够够用，而且可以自定义DNS（这个你就自行发挥吧）
