### ISSUE TITLE
passwall ipv6节点没有延迟信息

### ISSUE THREAD

**Issue by RainCat1998** [xiaorouji/openwrt-package#718]
关于ipv6节点分流问题已经解决，非常感谢。
但是ipv6节点在界面中没有延迟测试信息，同样的把ipv6节点通过域名解析后，可以正常显示延迟信息。
希望可以修复这个小BUG。
![Snipaste_2020-10-10_01-14-45](https://user-images.githubusercontent.com/36730607/95612462-00386480-0a96-11eb-828c-126f50502ecb.png)

**Comment by xiaorouji** [comment]
更新最新源码试试
