### ISSUE TITLE
vless xtls无法启动

### ISSUE THREAD

**Issue by nevliv** [xiaorouji/openwrt-package#722]
3.9.66版，选用vless xtls无法启动。电脑和手机用v2rayN同样的参数可以正常使用。

**Comment by xiaorouji** [comment]
输入
/etc/init.d/passwall restart 
看看

**Comment by zxy95** [comment]
作者原话： XTLS不能开启 Mux，XTLS 需要获得原始的数据流，所以原理上也不会支持 WebSocket、不适用于 VMess。此外，UDP over TCP 时，VLESS 不会开启 XTLS 的特殊功能。

**Comment by xiaorouji** [comment]
有一点要注意，flow是要手动填一下的，默认是空的，这个下个版本会修改一下

**Comment by ajmz** [comment]
3.9-73，vless xtls也无法启动，TCP“未连接”，其他方式使用均正常。
输入/etc/init.d/passwall restart，启动守护进程，手动填写xtls-rprx-origin，都试过，还是不行。

**Comment by AU-Linsanity** [comment]
我也有这个问题，最终发现是和smartdns冲突，最后妥协，撤掉smartdns，解决掉了
