### ISSUE TITLE
naiveproxy: Update v86.0.4240.75-1 patches 错误

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-package#723]
naive版本更新了 patches没更新 编译不过去

**Comment by zxlhhyccc** [comment]
> naive版本更新了 patches没更新 编译不过去

自己修复一下patch就行了：
100的补丁改为：
From 5b476d92f8dbee8b83061faa8cd18a46e5ab4aae Mon Sep 17 00:00:00 2001
From: CN_SZTL <cnsztl@project-openwrt.eu.org>
Date: Tue, 18 Aug 2020 20:36:39 +0000
Subject: [PATCH] build: add OpenWrt staging libraries

---
 src/build/config/posix/BUILD.gn | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/build/config/posix/BUILD.gn b/src/build/config/posix/BUILD.gn
index 9ccb89f27..de9e5501d 100644
--- a/src/build/config/posix/BUILD.gn
+++ b/src/build/config/posix/BUILD.gn
@@ -28,6 +28,9 @@ config("runtime_library") {
   if (!is_mac && !is_ios && sysroot != "") {
     # Pass the sysroot to all C compiler variants, the assembler, and linker.
     sysroot_flags = [ "--sysroot=" + rebase_path(sysroot, root_build_dir) ]
+    sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include" ]
+    sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include/nss" ]
+    sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include/nspr" ]
     if (is_linux || is_chromeos) {
       # This is here so that all files get recompiled after a sysroot roll and
       # when turning the sysroot on or off. (defines are passed via the command
@@ -57,6 +60,7 @@ config("runtime_library") {
     cflags_objcc += sysroot_flags
 
     # Need to get some linker flags out of the sysroot.
+    ldflags += [ "-L" + getenv("OP_STAGING_DIR") + "/usr/lib" ]
     ld_paths = exec_script("sysroot_ld_path.py",
                            [
                              rebase_path("//build/linux/sysroot_ld_path.sh",
-- 
2.17.1
101的补丁改为：
From dd07b78f561914ccc6cbe076ae66c380304bf92c Mon Sep 17 00:00:00 2001
From: CN_SZTL <cnsztl@project-openwrt.eu.org>
Date: Wed, 19 Aug 2020 12:42:45 +0000
Subject: [PATCH] build: drop useless deps simd_asm

libjpeg_turbo itself has alreadly set the dependency "simd_asm",
and this will cause cross-compile failed:
```
ERROR Unresolved dependencies.
//:gn_all(//build/toolchain/linux:clang_arm64_openwrt)
  needs //third_party/libjpeg_turbo:simd_asm(//build/toolchain/linux:clang_arm64_openwrt)
```
So, let's drop it in global build file.
---
 src/BUILD.gn | 1 -
 1 file changed, 1 deletion(-)

diff --git a/src/BUILD.gn b/src/BUILD.gn
index 97494c0a0..daddf5213 100644
--- a/src/BUILD.gn
+++ b/src/BUILD.gn
@@ -751,7 +751,6 @@ group("gn_all") {
       if (enable_nacl) {
         deps += [ "//native_client/src/trusted/platform_qualify:vcpuid" ]
       }
-      deps += [ "//third_party/libjpeg_turbo:simd_asm" ]
     }
     if ((is_linux || is_chromeos) && current_toolchain == host_toolchain) {
       deps += [ "//v8:v8_shell" ]
-- 
2.17.1

**Comment by funison** [comment]
> > naive版本更新了 patches没更新 编译不过去
> 
> 自己修复一下patch就行了（把代码贴到对应的位置）：
> 100的补丁改为：
> @@ -28,6 +28,9 @@ config("runtime_library") {
> if (!is_mac && !is_ios && sysroot != "") {
> # Pass the sysroot to all C compiler variants, the assembler, and linker.
> sysroot_flags = [ "--sysroot=" + rebase_path(sysroot, root_build_dir) ]
> 
> * sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include" ]
> * sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include/nss" ]
> * sysroot_flags += [ "-I" + getenv("OP_STAGING_DIR") + "/usr/include/nspr" ]
>   if (is_linux || is_chromeos) {
>   # This is here so that all files get recompiled after a sysroot roll and
>   # when turning the sysroot on or off. (defines are passed via the command
> 
> @@ -57,6 +60,7 @@ config("runtime_library") {
> cflags_objcc += sysroot_flags
> 
> ```
>  # Need to get some linker flags out of the sysroot.
> ```
> 
> * ldflags += [ "-L" + getenv("OP_STAGING_DIR") + "/usr/lib" ]
>   ld_paths = exec_script("sysroot_ld_path.py",
>   [
>   rebase_path("//build/linux/sysroot_ld_path.sh",
>   101的补丁改为：
>   @@ -751,7 +751,6 @@ group("gn_all") {
>   if (enable_nacl) {
>   deps += [ "//native_client/src/trusted/platform_qualify:vcpuid" ]
>   }
> 
> * ```
>    deps += [ "//third_party/libjpeg_turbo:simd_asm" ]
>   ```
>   
>   
>   }
>   if ((is_linux || is_chromeos) && current_toolchain == host_toolchain) {
>   deps += [ "//v8:v8_shell" ]

按你的代码修改了patch，但是还是过不去..

**Comment by hyird** [comment]
会改的直接发pr吧  升级了也不测试下

**Comment by hdgeek** [comment]
https://www.lanzoux.com/i3gLahc6gkb，这是改好的。
P.S 我是整体打包的，直接替换即可
