### ISSUE TITLE
最新的Naiveproxy 更新编译失败，各分支都一样。

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-package#724]
最新的Naiveproxy 更新编译失败，各分支都一样。

**Comment by jackerjiang** [comment]
同样的问题，有解决办法吗

**Comment by hdgeek** [comment]
看这里，[https://github.com/xiaorouji/openwrt-package/issues/723#issuecomment-706650555](https://github.com/xiaorouji/openwrt-package/issues/723#issuecomment-706650555)

**Comment by lxhao61** [comment]
不好意思，已提交naiveproxy patches更新，批准更新后就可以正常编译了。
