### ISSUE TITLE
Trojan-Plus服务器端接入的远端不能google？

### ISSUE THREAD

**Issue by hawie** [xiaorouji/openwrt-package#725]
本地能正常google，路由自身的dns解析(/etc/resolv.conf)强制为127.0.0.1之后，路由google连接测试也正常。
但启用passwall集成的Trojan-Plus服务器端，远程能接入访问内外网，但不能google。使用不集成的单独的trojan服务器也是一样。
不知应该怎样调整？

**Comment by RainCat1998** [comment]
vless协议也是这样，vmess正常

**Comment by hyird** [comment]
/etc/resolv.conf)强制为127.0.0.1   设置成这个有毛用？

**Comment by hawie** [comment]
> /etc/resolv.conf)强制为127.0.0.1 设置成这个有毛用？

有啊，在ipv6下passwall集成的google连接测试才能正常。
https://github.com/xiaorouji/openwrt-package/issues/689

**Comment by hawie** [comment]
> vless协议也是这样，vmess正常

好，那我改天也试试vmess，只要有一种能用起来就行了

**Comment by hawie** [comment]
> vless协议也是这样，vmess正常

感谢！验证了，使用vmess一切正常！就先这么用着了，等到vmess被封的时侯再去折腾trojan server，那时侯估计这种问题都解决了吧
