### ISSUE TITLE
passwall使用naive节点会产生dns解析的问题

### ISSUE THREAD

**Issue by tefiszx** [xiaorouji/openwrt-package#730]
passwall使用naive节点，测试google域名无法解析。ip111.cn无法解析googole的ip。使用其他的节点无此问题。

**Comment by lxhao61** [comment]
此问题我也遇到，但不影响使用。一般重启路由器后就正常了。

**Comment by tefiszx** [comment]
> 此问题我也遇到过，基本不影响使用。一般重启路由器后就正常了。此情况之前版本都有这个现象。

我试过了，重启关机都没用。 YouTube能打开页面，但是不能播放视频。总之这个故障蛮奇怪的。ssh到路由器，dig了一下都正常。

**Comment by lxhao61** [comment]
> > 此问题我也遇到过，基本不影响使用。一般重启路由器后就正常了。此情况之前版本都有这个现象。
> 
> 我试过了，重启关机都没用。 浏览网页，打开网页都正常。YouTube无论是用APP还是用浏览器访问，都能打开页面，但是不能播放视频。总之这个故障蛮奇怪的。ssh到路由器，dig了一下都正常。

从你的描述中发现明显是DNS问题。

**Comment by tefiszx** [comment]
> > > 此问题我也遇到过，基本不影响使用。一般重启路由器后就正常了。此情况之前版本都有这个现象。
> > 
> > 
> > 我试过了，重启关机都没用。 浏览网页，打开网页都正常。YouTube无论是用APP还是用浏览器访问，都能打开页面，但是不能播放视频。总之这个故障蛮奇怪的。ssh到路由器，dig了一下都正常。
> 
> 从你的描述中发现明显是DNS问题。检查DNS配置等

是的。奇怪的是，同样的dns配置，换用非navie的节点（比如ss或v2的节点就不会有问题）

**Comment by xiaorouji** [comment]
你使用的DNS方案是什么

**Comment by tefiszx** [comment]
> 你使用的DNS方案是什么

config global
	option use_tcp_node_resolve_dns '1'
	option up_trust_chinadns_ng_dns 'pdnsd'
	option localhost_tcp_proxy_mode 'chnroute'
	option udp_proxy_mode 'chnroute'
	option localhost_udp_proxy_mode 'chnroute'
	option chinadns_ng '1'
	option use_chnlist '1'
	option up_china_dns '223.5.5.5'
	option dns_mode 'pdnsd'
	option up_trust_pdnsd_dns 'tcp'
	option dns_forward '8.8.4.4'
	option udp_node1 'tcp_'
	option tcp_node1 '6435362c10104cbb994f42511fc1a65d'
	option tcp_proxy_mode 'chnroute'
	option enabled '0'
上述dns方案用其他节点就正常，唯有用naive节点就出问题。

**Comment by xiaorouji** [comment]
naive好像是不支持udp的，udp节点换其他试试
