### ISSUE TITLE
passwall对AndroidStudio的下载链接解析似乎存在一些问题。

### ISSUE THREAD

**Issue by liyuhaolol** [xiaorouji/openwrt-package#732]
passwall设置为gfwlist模式，打开了chinaDNS-NG，公平模式。
访问网页：https://developer.android.google.cn/studio/
点击中间下载AndroidStudio后，会访问下载的地址
地址为：https://r7---sn-2x3eln7d.gvt1.com/edgedl/android/studio/install/4.1.0.19/android-studio-ide-201.6858069-windows.exe?cms_redirect=yes&mh=kO&mip=111.193.125.203&mm=28&mn=sn-2x3eln7d&ms=nvh&mt=1602568460&mv=m&mvi=7&pl=18&shardbypass=yes

随后整个电脑的网络就会假死，卡住，甚至连openwrt后台都访问不了。等待一段时间后恢复，文件无法正常下载，再次点击会重复这个现象，关闭passwall后秒下载，不会断网。这应该是个BUG吧？

**Comment by xiaorouji** [comment]
很抱歉我没复现过这问题，你路由器用的什么？关闭ChinadnsNG试试？

**Comment by liyuhaolol** [comment]
> 很抱歉我没复现过这问题，你路由器用的什么？关闭ChinadnsNG试试？

我路由器是i7 7500U的工控机，经过我多次尝试，关闭ChinadnsNG，这个问题就可以得到立刻修正。基本可以确定是ChinadnsNG造成的(打开或者关闭公平模式都会复现)，我这里复现率是100%。重启路由器，重启电脑。立刻访问这个网站，点击下载AS，网络就会卡死。我个人理解是，所有Android的官网都比较特殊，因为他既是Google，但又可以不翻墙直连。所以ChinadnsNG那里解析是不是就进了什么死循环了？造成后续dns都无法解析，造成网络假死。我是这么感觉的，还需要您懂行的调查吧。

**Comment by xiaorouji** [comment]
chinadns-ng似乎最高支持四级域名，不知道会不会和这个有关系。所以最好向chinadns-ng那边反馈
