### ISSUE TITLE
https-dns-proxy 进程cpu占用过高

### ISSUE THREAD

**Issue by sheiy** [xiaorouji/openwrt-package#733]
![image](https://user-images.githubusercontent.com/12210038/95832012-56462a00-0d6c-11eb-9bb0-e20743b06a78.png)

**Comment by hcym** [comment]
不要编译这个，之前一直不好用，最近就没有编译这个和其他什么dns，反而完全正常

**Comment by xiaorouji** [comment]
非Lienol源码是这样的
简单粗暴方法
/etc/init.d/https-dns-proxy stop
/etc/init.d/https-dns-proxy disable

**Comment by sheiy** [comment]
@xiaorouji @hcym  原来如此，感谢
