### ISSUE TITLE
passwall插件naiveproxy无法解锁netflix

### ISSUE THREAD

**Issue by ymcoming** [xiaorouji/openwrt-package#734]
我的VPS是无法看非自制剧netflix的，所以购了netflix解锁，在resolv.conf里写入唯一的nameserver （提供方的netflix解锁IP）。这台vps搭了v2ray和naiveproxy，在openwrt下的passwall中，创建了v2ray和naiveproxy的连接。

结果v2ray的连接能正确解锁收看netflix，而naiveproxy的连接则解锁失败（连接本身是正常的，能上google/youtube等）。似乎是naiveproxy没有读取VPS的nameserver，没有通过相应的netflix解锁IP去解析。

**Comment by jh0072110** [comment]
这跟psw有啥关系…

**Comment by ymcoming** [comment]
> 这跟psw有啥关系…

因为我直接用PC客户端qv2ray连接naiveproxy时，解锁是成功的。所以确认不是naiveproxy的问题。
只是用openwrt passwall内的naiveproxy插件时，解锁才失败。

**Comment by xiaorouji** [comment]
naiveproxy貌似不支持udp请求，所以有可能是这样。
