### ISSUE TITLE
Passwall 启动关闭速度太慢

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-package#735]
我记得早期版本 开关passwall 速度非常快，现在的版本，打开passwall要5-10秒左右
很慢，希望优化。
另希望增加一键开关/切换 功能，不需要点应用键

**Comment by xiaorouji** [comment]
我都是秒保存...
保存慢可能是dns解析慢吧

**Comment by hcym** [comment]
最新版应该是飞快的，就是广告规则看到有，没效果，还是hosts拦截的，还有一个情况，haproxy权重只能取整数，用5就不行，这个以前没有吧？记得过去只是不能用ipv6
