### ISSUE TITLE
passwall能科学上网却不能正常连接国内上网

### ISSUE THREAD

**Issue by 171bbq** [xiaorouji/openwrt-package#737]
passwall能科学上网却不能国内上网，通过重启软路由之后，会恢复正常，但是没过几分钟，又不行了。
Thu Oct 15 12:48:50 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:48:52 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:48:59 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:49:01 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:49:08 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:49:10 2020 user.info mwan3track[1831]: Check (ping) failed for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:49:10 2020 user.notice mwan3[14915]: Execute ifdown event on interface wan (eth3)
Thu Oct 15 12:49:10 2020 user.info mwan3track[1831]: Detect ifdown event on interface wan (eth3)
Thu Oct 15 12:49:15 2020 user.notice mwan3track[1831]: Interface wan (eth3) is offline
Thu Oct 15 12:49:16 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:49:16 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:49:16 2020 user.info mwan3track[1831]: Lost 6 ping(s) on interface wan (eth3)
Thu Oct 15 12:49:30 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:49:47 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:49:48 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:02 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:02 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:02 2020 user.info mwan3track[1831]: Lost 8 ping(s) on interface wan (eth3)
Thu Oct 15 12:50:09 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:14 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:14 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:14 2020 user.info mwan3track[1831]: Lost 1 ping(s) on interface wan (eth3)
Thu Oct 15 12:50:19 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:19 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:24 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:24 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:29 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:29 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:34 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:34 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:41 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:46 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:47 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:47 2020 user.info mwan3track[1831]: Lost 1 ping(s) on interface wan (eth3)
Thu Oct 15 12:50:52 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:52 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:50:57 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:50:57 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:51:02 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:51:09 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:51:09 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:51:09 2020 user.info mwan3track[1831]: Lost 1 ping(s) on interface wan (eth3)
Thu Oct 15 12:51:14 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:51:50 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:51:54 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:51:55 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:51:55 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:51:55 2020 user.info mwan3track[1831]: Lost 8 ping(s) on interface wan (eth3)
Thu Oct 15 12:52:00 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:00 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:05 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:05 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:10 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:10 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:15 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:15 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:20 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:20 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:25 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:26 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:31 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 12:52:31 2020 user.info mwan3track[1831]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 12:52:31 2020 user.notice mwan3track[1831]: Interface wan (eth3) is online
Thu Oct 15 12:52:41 2020 user.notice mwan3[11256]: Execute ifup event on interface wan (eth3)
Thu Oct 15 12:52:41 2020 user.notice mwan3[11256]: Starting tracker on interface wan (eth3)
Thu Oct 15 12:52:42 2020 user.info mwan3rtmon[7309]: Detect rtchange event.
Thu Oct 15 12:52:42 2020 user.notice firewall: Reloading firewall due to ifup of wan (eth3)
Thu Oct 15 12:54:01 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:55:53 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:57:52 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:59:51 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 12:59:56 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 12:59:58 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:00 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:02 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:04 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:06 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:08 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:10 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:12 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:14 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:16 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:18 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:20 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:22 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:24 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:26 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:28 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:30 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:32 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:34 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:36 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:38 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:40 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:42 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:44 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:46 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:48 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:50 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:52 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:54 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:56 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:00:58 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:00 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:02 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:04 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:06 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:07 2020 user.info mwan3track[12859]: Check (ping) failed for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:08 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:10 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:12 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:14 2020 user.info mwan3track[12859]: Check (ping) failed for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:14 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:16 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:18 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:20 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:21 2020 user.info mwan3track[12859]: Check (ping) failed for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:21 2020 user.notice mwan3[21651]: Execute ifdown event on interface wan (eth3)
Thu Oct 15 13:01:22 2020 user.info mwan3track[12859]: Detect ifdown event on interface wan (eth3)
Thu Oct 15 13:01:22 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:24 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:26 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:27 2020 user.notice mwan3track[12859]: Interface wan (eth3) is offline
Thu Oct 15 13:01:27 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:27 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:27 2020 user.info mwan3track[12859]: Lost 3 ping(s) on interface wan (eth3)
Thu Oct 15 13:01:28 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:30 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:32 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:32 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:32 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:34 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:36 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:37 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:37 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:38 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:40 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:42 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:42 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:42 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:44 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:46 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:47 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:47 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:48 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:50 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:52 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:52 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:52 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:54 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:56 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:01:58 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:01:58 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:01:58 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 13:01:58 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:00 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:02 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:03 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.114.114" on interface wan (eth3)
Thu Oct 15 13:02:03 2020 user.info mwan3track[12859]: Check (ping) success for target "114.114.115.115" on interface wan (eth3)
Thu Oct 15 13:02:03 2020 user.notice mwan3track[12859]: Interface wan (eth3) is online
Thu Oct 15 13:02:04 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:06 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:08 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:10 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:12 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:13 2020 user.notice mwan3[27773]: Execute ifup event on interface wan (eth3)
Thu Oct 15 13:02:13 2020 user.notice mwan3[27773]: Starting tracker on interface wan (eth3)
Thu Oct 15 13:02:14 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:14 2020 user.info mwan3rtmon[7309]: Detect rtchange event.
Thu Oct 15 13:02:14 2020 user.notice firewall: Reloading firewall due to ifup of wan (eth3)
Thu Oct 15 13:02:16 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:18 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:20 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:22 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:24 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:26 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:28 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:30 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:32 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:34 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:36 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:38 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:40 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:42 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:44 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:46 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:48 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:50 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:52 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:54 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:56 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:02:58 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:00 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:02 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:04 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:06 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:08 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:10 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:12 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:14 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:16 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:18 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:20 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:22 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:24 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:26 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:28 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:30 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:32 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:34 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:36 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:38 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:40 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:42 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:44 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:46 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:48 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:50 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:52 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:54 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:54 2020 daemon.err odhcp6c[3953]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Thu Oct 15 13:03:56 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:03:58 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:00 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:02 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:04 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:06 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:08 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:10 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:12 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:14 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Thu Oct 15 13:04:16 2020 daemon.err netdata[7987]: PROCFILE: Cannot open file '/proc/sysvipc/shm'

**Comment by xiaorouji** [comment]
这个日志看不出什么，倒是一大堆mwan3负载均衡和netdata的，如果你不是多拨，把mwan3配置删掉看看
