### ISSUE TITLE
ad+ smartdns+passwall gfw模式无法科学

### ISSUE THREAD

**Issue by saphhireBlue** [xiaorouji/openwrt-package#742]
主路由ipv6关闭后可用一段时间，然后就又不可用

**Comment by tianiue** [comment]
我的可以，adb+smartdns+passwall，设置op中继主路由V6

**Comment by saphhireBlue** [comment]
> 我的可以，adb+smartdns+passwall，设置op中继主路由V6

可以问一下，你的passwall是什么版本吗

**Comment by tianiue** [comment]
之前版本3.4，现在最新版，都可以
