### ISSUE TITLE
tcp节点解析dns域名，dns错误无法访问外网

### ISSUE THREAD

**Issue by zhouruiwu1997** [xiaorouji/openwrt-package#744]
tcp节点解析dns域名，dns错误无法访问外网（Tg正常），国内正常，切换成udp解析后就一切正常，或者重置passwall插件也能恢复，请问这是什么原因导致的？passwall如何快速重置dns？插件中的dns设置如下图。十分感谢
![image](https://user-images.githubusercontent.com/54628120/96492434-359f3800-1276-11eb-8b08-f2e4ee69529a.png)

**Comment by xiaorouji** [comment]
本身就是可选项嘛，哪个能用用哪个
