### ISSUE TITLE
升级新passwall后ping值高网页加载速度慢

### ISSUE THREAD

**Issue by bloomchou** [xiaorouji/openwrt-package#749]
今天升级后 遇到两个问题
第一个是ping飘忽不定
第二个是打开网页速度明显比原先慢了许多
所以想请教下如何设置dns？

环境
型号	Phicomm N1
架构	ARMv8 Processor rev 4 (v8l) x 4
固件版本	OpenWrt R20.7.20 / LuCI Master (git-20.190.41443-b753998)
内核版本	5.7.15-flippy-41+

由5.7.2-flippy-37+直接升级到5.7.15-flippy-41+，pw就不能科学上网，检测节点都是失败，删除重新订阅无果后，移除了旧版本pw，新安装了passwall_3.9-72_all.ipk，可以科学上网，却发现：

相同的节点，因为没有数值，运行状态检测旧版本一直显示都是非常快，现在有数值却发现检测ping很高200-800多飘忽不定、差值很大，但节点列表里显示都很低、稳定20-50，旧版本也是这个值。
如图
<img src="https://www.assdrty.com/images/2020/10/22/Snipaste_2020-10-22_19-12-27.png" alt="Snipaste 2020 10 22 19 12 27" border="0">
<img src="https://www.assdrty.com/images/2020/10/22/Snipaste_2020-10-22_20-13-11.png" alt="Snipaste 2020 10 22 20 13 11" border="0">

带来的体现就是打开网页加载速度慢了很多，多图、视频类的网站尤为明显，预览变得很慢。一直配合SmartDNS使用的，之前打开过一次的网页后，虽然比不上用ros做软路由那样秒开网站，但也是非常迅速的，现在打开网站慢的可以数秒了。

怀疑是和dns设置有关
之前用的版本dns设置比较简单 看的视频，说是官方推荐设置，选的是127.0.0.1#6053和自定义使用本机7913的端口dns，一直很稳定。
现在选项多了，不清楚该如何优化设置
（看到有人说把127.0.0.1#7913改成7053，试了没效果，反而更慢了，勾不勾选使用ChinaDNS-NG，也没有明显改变）

请教如何解决

**Comment by xiaorouji** [comment]
运行状态里面的延迟不是ping延迟，而是请求总体耗时。
另外你可以试试，不要用chnlist，不要用chinadns-ng，清空ipset
