### ISSUE TITLE
Passwall分流

### ISSUE THREAD

**Issue by pangfeng161** [xiaorouji/openwrt-package#754]
ssr p+ 有节点分流很方便不用后台切换,但Passwall只有v2ray分流而已,不知道是不是插件不支持还是设置问题?

**Comment by viagram** [comment]
配合haprox可以ssr分流

**Comment by hcym** [comment]
学习一下，haproxy一直开的，做状态监测不错

**Comment by xiaorouji** [comment]
v2ray分流也可以使用非v2ray节点实现分流

**Comment by xiaorouji** [comment]
而且可以自定义规则，这个就靠你们自行摸索了
