### ISSUE TITLE
naiveproxy编译错误

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-package#758]
今天更新的naiveproxy又无法编译通过！

**Comment by gswangmd-gssi** [comment]
补充信息: X86-64
用ssr带的Naiveproxy，编译能通过。

**Comment by hcym** [comment]
我的都可以，x86和arm，今天编译的，系统是20.04，反而是v2和哪个什么t-go不能选择压缩，大雕的可以，倒也无所谓

**Comment by gswangmd-gssi** [comment]
期待修正Naiveproxy错误！
