### ISSUE TITLE
TCP不运行

### ISSUE THREAD

**Issue by lgfyxx1** [xiaorouji/openwrt-package#759]
1. 开关勾选点击应用后，TCP状态开启后显示“未运行”，尝试多次都是一样的，谷歌连接失败
2. 尝试开了UDP， 只显示UPD运行，TCP仍然“未运行”，谷歌连接失败

**Comment by funison** [comment]
我都试过好几版passwall了，TCP和UDP/SOCKS不能同时开启，而且和UNBLOCKMUSIC冲突，运行在X86_64的虚拟机下

**Comment by hathlife** [comment]
规则管理页面更新一下试试。

**Comment by xiaorouji** [comment]
大可能是配置不当，跑不起来。
终端执行 /etc/init.d/passwall restart 看看
