### ISSUE TITLE
trojan编译报错

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [xiaorouji/openwrt-package#765]
/home/yaodao/lede/build_dir/target-x86_64_musl/trojan-plus-10.0.3/src/core/config.cpp:26:10: fatal error: gsl/gsl: No such file or directory
 #include <gsl/gsl>
          ^~~~~~~~~
compilation terminated.
echo "luci-app-diskman" >> /home/yaodao/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-diskman.default.install
touch /home/yaodao/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-app-wrtbwmon_installed
make[6]: *** [CMakeFiles/trojan.dir/build.make:93: CMakeFiles/trojan.dir/src/core/config.cpp.o] Error 1
make[6]: Leaving directory '/home/yaodao/lede/build_dir/target-x86_64_musl/trojan-plus-10.0.3'
make[5]: *** [CMakeFiles/Makefile2:93: CMakeFiles/trojan.dir/all] Error 2
make[5]: Leaving directory '/home/yaodao/lede/build_dir/target-x86_64_musl/trojan-plus-10.0.3'
make[4]: *** [Makefile:158: all] Error 2
make[4]: Leaving directory '/home/yaodao/lede/build_dir/target-x86_64_musl/trojan-plus-10.0.3'
make[3]: *** [Makefile:71: /home/yaodao/lede/build_dir/target-x86_64_musl/trojan-plus-10.0.3/.built] Error 2
make[3]: Leaving directory '/home/yaodao/lede/feeds/lienol/package/trojan-plus'

 fatal error: gsl/gsl: No such file or directory
 #include <gsl/gsl>

到这里就卡死了，x86平台，斐讯k3这种编译没问题，就是x86

**Comment by MrMatttw** [comment]
请教一下如何解决的
