### ISSUE TITLE
最新版本，负载均衡无设置项？

### ISSUE THREAD

**Issue by AlwaysOnline** [xiaorouji/openwrt-package#770]
![image](https://user-images.githubusercontent.com/3928525/98496344-6d4d3e80-227c-11eb-8258-3b84b4ecc8e3.png)

如图，今天更新的版本，负载均衡无设置项目。

但有负载均衡的检测。

**Comment by soulesprit** [comment]
请问最新版本是多少？哪里能下载呢？谢谢
